// EGYPT — SECOND INTERMEDIATE PERIOD (HYKSOS) AND NEW KINGDOM. Full English content. Same structure and same image slots as the Portuguese version (dados.js).
// Chronology follows Shaw (ed.), The Oxford History of Ancient Egypt (2000). Hornung–Krauss–Warburton (2006) differs by a few years. All dates are “c.” unless stated.

const visao = [
  { caixa: 'In brief', texto: [
    'Between about **1650 and 1069 BC** Egypt went through two very different things: first, a century of division, in which the Delta was ruled by chiefs of Asiatic origin, the **Hyksos**, and the south by Theban pharaohs; then the richest and most powerful era of its history, the **New Kingdom**, the age of the great empires of the Late Bronze Age.',
    'It was the time of **Hatshepsut**, **Thutmose III**, **Akhenaten** and his religious revolution, **Tutankhamun**, **Ramesses II** and the battle of Kadesh. It was the time of the Valley of the Kings, Karnak and Abu Simbel, and also the time when the king began to be called “the Great House” (*per-aa*, the origin of the word “pharaoh”) and went looking for wealth and power far beyond the Nile valley: in Nubia, Syria and Palestine.'
  ] },
  { img: 'eni-mapa-novo-imperio', leg: 'Map of Egyptian expansion in the New Kingdom, c. 1450 BC.' },
  { h: 'Where and when' },
  'The centre of power moved. In the Middle Kingdom the capital lay near Memphis, at the entrance to the Delta; in the New Kingdom it is **Thebes** (modern Luxor), in Upper Egypt, the “city of Amun”, that becomes the religious heart and, most of the time, the political heart of the kingdom. The pharaohs also had residences in the north, above all Memphis and later **Pi-Ramesses**, in the eastern Delta. Beyond the Nile valley, Egypt controlled **Nubia** (up to the Fourth Cataract and beyond) and a network of cities and vassal princes in **Palestine, Lebanon and Syria**.',
  'This page covers two periods: the **Second Intermediate Period** (c. 1650 – 1550 BC), with Dynasties 15 (Hyksos), 16 and 17 (Thebes), and the **New Kingdom** (c. 1550 – 1069 BC), with Dynasties 18, 19 and 20.',
  { tabela: { cab: ['Phase', 'Approximate dates', 'What marks it'], linhas: [
    ['Second Intermediate', 'c. 1650 – 1550 BC', 'A divided country: Hyksos at Avaris (Dynasty 15), Thebans in the south (16–17), the kingdom of Kerma in Nubia; the war of liberation of Kamose and Ahmose I'],
    ['Dynasty 18 (early)', 'c. 1550 – 1479 BC', 'Ahmose I expels the Hyksos; conquests in Nubia and Syria; the first kings of the Valley of the Kings'],
    ['Dynasty 18 (peak)', 'c. 1479 – 1352 BC', 'Hatshepsut and Thutmose III; the empire reaches the Euphrates; Amenhotep III, the king of gold and diplomacy'],
    ['Amarna Period', 'c. 1352 – 1323 BC', 'Akhenaten and the cult of the Aten; Tutankhamun and the restoration; Ay and Horemheb'],
    ['Dynasty 19', 'c. 1295 – 1186 BC', 'Seti I and Ramesses II; Kadesh and the treaty with the Hittites; Pi-Ramesses; Merneptah'],
    ['Dynasty 20', 'c. 1186 – 1069 BC', 'Ramesses III and the Sea Peoples; strikes, tomb robberies and loss of the empire; the power of the priests of Amun']
  ] } },
  { caixa: 'Which chronology we use', texto: 'The chronology of Egypt is not exact. This page follows **Shaw (2000)**, the one most often seen in textbooks; that of **Hornung, Krauss and Warburton (2006)**, for example, differs by a few years, and dates before the New Kingdom are even more disputed. That is why almost all of them carry “c.”. The long reigns (Thutmose III, Ramesses II) and some very well known dates (Megiddo, Kadesh) are safer than the dates of the Hyksos.' },
  { img: 'eni-hipostila-karnak', leg: 'Hypostyle Hall of the Temple of Amun-Ra, Karnak.' },
  { h: 'What changed' },
  { lista: [
    '**An empire:** for the first time Egypt has a standing army and conquers territory outside the Nile. The Hyksos had shown Egypt how vulnerable it was; the pharaohs of Dynasty 18 wanted that never to happen again.',
    '**New weapons:** the horse-drawn war chariot, the composite bow, the bronze axe-blade and the curved *khopesh* sword become common. (Who brought them, and when, is debated: see the section on the Hyksos.)',
    '**A new state:** the pharaoh is now also a war leader, and soldiers and officers form a new elite. Offices appear such as the “King’s Son of Kush” (viceroy of Nubia).',
    '**The power of Amun:** the god of Thebes, Amun (later Amun-Ra), becomes the god of the empire, and his immensely rich clergy a rival power to the pharaoh.',
    '**Hidden tombs:** instead of pyramids, the kings are buried in tombs cut in the rock of the **Valley of the Kings**, with the funerary temple far away on the plain.',
    '**Diplomacy:** Egypt speaks as an equal with Babylon, Mitanni, Hatti and Assyria, exchanging letters, gifts and princesses, as the **Amarna letters** show.'
  ] },
  { h: 'Why it matters' },
  { lista: [
    '**It is the Egypt everyone knows:** Tutankhamun, Nefertiti, Ramesses II, Hatshepsut, the Valley of the Kings, Karnak and Abu Simbel all belong to the New Kingdom.',
    '**A “revolution”:** Akhenaten tried to impose a single god, the Aten, centuries before monotheism as we know it. His reign is one of the most debated in all of history.',
    '**A well-documented society:** the craftsmen’s village of Deir el-Medina left us thousands of papyri and written potsherds with letters, accounts, lawsuits and the first strike on record.',
    '**The end of a world:** the crisis at the end of the Bronze Age (c. 1200 BC) brought down whole empires, and the Egypt of Ramesses III was one of the few to resist.'
  ] },
  { img: 'eni-abu-simbel', leg: 'Facade of the Great Temple of Abu Simbel.' },
  { h: 'How we know' },
  'The sources are abundant. There are **monumental inscriptions** on temple walls (the Annals of Thutmose III at Karnak, the battles of Ramesses II and Ramesses III), **painted tombs** of officials at Thebes, **papyri and ostraca** (pieces of limestone or pottery with writing) from Deir el-Medina, the **diplomatic archives of Amarna** and some two centuries of excavation. The sources for the Hyksos are much poorer, and often written by enemies: part of what we know about them comes from an Egyptian (and later Greek) view that was already hostile.',
  'The New Kingdom also has its silences. The official sources show mostly victories, and no pharaoh’s inscription admits defeat. That is why, to compare versions, archaeologists also use the letters of vassals and foreign kings, and the Hittite texts, which give a different version of Kadesh.',
  { caixa: 'The New Kingdom today', texto: 'The sites of this period are among the most visited in the world: **Thebes** (Karnak, Luxor, the Valley of the Kings, Deir el-Bahari) was inscribed on the UNESCO World Heritage List in 1979, and **Abu Simbel** is part of the group of Nubian monuments, from Abu Simbel to Philae, also World Heritage. The tomb of Tutankhamun and its treasures, now in the Grand Egyptian Museum (Giza), remain the most famous archaeological discovery in the world.' },
  { img: 'eni-mascara-tutankhamon', leg: 'Tutankhamun’s gold funerary mask, photographed at the Grand Egyptian Museum, Giza.' }
];

const linha = [
  'This timeline follows the main events from c. 1650 to 1069 BC. The dates are those of Shaw (2000); for the kings before Ahmose I they are approximate. For the lives of the pharaohs in detail, see the page “The pharaohs”.',
  { linha: [
    { d: 'c. 1650 BC', t: 'Egypt divides', x: 'The power of the kings of Dynasty 13, who ruled from the Memphis region, weakens. Chiefs of Asiatic origin (from the Levant), settled for generations in the eastern Delta, take power in the city of **Avaris** and form **Dynasty 15**, that of the Hyksos. In the south, a local dynasty (16) rules from Thebes.' },
    { d: 'c. 1650 – 1550 BC', t: 'The Hyksos at Avaris', x: 'The name *Hyksos* comes from the Egyptian *heqa-khasut*, “rulers of foreign lands”. Their kings (Khayan, **Apepi** and others) use Egyptian titles and writing but keep Canaanite elements, such as the cult of the god Seth, identified with the storm god Baal. They trade with the Levant, Cyprus and the Aegean world, and ally with the kingdom of **Kerma**, in Nubia.' },
    { d: 'c. 1555 BC', t: 'The death of Seqenenre Tao', x: 'A Theban king, **Seqenenre Tao**, is killed, most probably in battle or by execution: his mummy, found in 1881, has severe head wounds. A late Egyptian story tells of a quarrel between him and the Hyksos king Apepi (the *Tale of Apophis and Seqenenre*), but it is a narrative, not a historical account.' },
    { d: 'c. 1555 – 1550 BC', t: 'Kamose attacks', x: '**Kamose**, the last king of Dynasty 17, attacks northward and takes his boats close to Avaris. His two stelae at Karnak tell of the campaign. Kamose dies soon after, and his brother (or son: debated) **Ahmose I** continues the war.' },
    { d: 'c. 1550 BC', t: 'Ahmose I expels the Hyksos', x: 'Ahmose I takes **Avaris** and then, according to one of his officers, also Sharuhen in southern Palestine, after a three-year siege. By reunifying the country he founds **Dynasty 18**. The officer **Ahmose son of Ibana** tells in his tomb at El-Kab of the battles he took part in, and is one of our best sources.' },
    { d: 'c. 1525 – 1504 BC', t: 'Amenhotep I and Ahmose-Nefertari', x: 'Amenhotep I and his mother, Queen **Ahmose-Nefertari**, consolidate the kingdom. The couple come to be venerated by the craftsmen of Deir el-Medina as protectors of the village. Amenhotep I campaigns in Nubia and Libya and builds at Karnak.' },
    { d: 'c. 1504 – 1492 BC', t: 'Thutmose I takes the empire to the Euphrates', x: 'Thutmose I advances through the Levant to the Euphrates and through Nubia far to the south. His architect **Ineni** tells us of the works at Karnak. In this period begins the tradition of royal tombs in the Valley of the Kings (which was the first is debated).' },
    { d: 'c. 1479 – 1458 BC', t: 'Hatshepsut', x: 'After the death of her husband Thutmose II, **Hatshepsut** rules first as regent for the young Thutmose III and, around year 7, takes the title of king. Her reign is peaceful and prosperous. She builds the temple of **Deir el-Bahari** and, c. 1471 BC, sends a maritime expedition to the land of **Punt**.' },
    { d: '1457 BC', t: 'The battle of Megiddo', x: 'Now sole king, **Thutmose III** defeats at Megiddo, in year 23, a coalition of Canaanite princes led by the king of Kadesh. A siege of about seven months follows. It is the first battle in history of which we have a detailed account, carved on the walls of Karnak.' },
    { d: 'c. 1458 – 1425 BC', t: 'The empire of Thutmose III', x: 'In some seventeen campaigns, Thutmose III turns the Levant into an Egyptian province and crosses the Euphrates, defeating the kingdom of **Mitanni**. Nubia is controlled up to the Fourth Cataract. It is the largest territory Egypt ever controlled. After him, Amenhotep II and Thutmose IV maintain it, more by diplomacy than by war.' },
    { d: 'c. 1390 – 1352 BC', t: 'Amenhotep III and the peak', x: 'A reign of peace, wealth and diplomacy. **Amenhotep III** builds all over Egypt (Luxor, Soleb, the palace of Malkata, the “Colossi of Memnon”) and exchanges letters and gifts with the kings of Babylon, Mitanni and Hatti. His chief wife, **Tiy**, has great influence.' },
    { d: 'c. 1352 – 1347 BC', t: 'Akhenaten and the Aten', x: 'The son of Amenhotep III, **Amenhotep IV**, raises the sun disc **Aten** above the other gods and, c. 1348 BC, changes his name to **Akhenaten**. In year 5 he founds a new capital, **Akhetaten** (modern Amarna), halfway between Memphis and Thebes. From his diplomatic archive survive some 380 **Amarna letters**, written in Akkadian.' },
    { d: 'c. 1336 BC', t: 'The end of Amarna', x: 'Akhenaten dies in year 17. An obscure period follows, with one or two short reigns (**Smenkhkare** and/or **Neferneferuaten**, between whom Nefertiti may stand: debated). A boy of about 8 to 10, **Tutankhaten**, comes to the throne, soon changes his name to **Tutankhamun** and restores the traditional cults; the court returns to Thebes.' },
    { d: 'c. 1327 BC', t: 'Death of Tutankhamun', x: 'Tutankhamun dies aged about 18 or 19 and is buried in a small tomb that stays almost intact until 1922. The elderly **Ay** takes the throne. A Hittite letter, thought to be from a widowed Egyptian queen (perhaps Ankhesenamun, but debated), asks for a Hittite prince as husband; the prince is killed on the way to Egypt.' },
    { d: 'c. 1323 – 1295 BC', t: 'Horemheb', x: 'The general **Horemheb**, former army chief of Tutankhamun, becomes king, restores order and publishes an edict against corruption. He erases Akhenaten’s name from the official lists and reuses the stones of his temples. Childless, he names the vizier **Ramesses I** as successor.' },
    { d: 'c. 1294 – 1279 BC', t: 'Seti I', x: 'Dynasty 19. **Seti I** reconquers lands in the Levant, builds the great temple at Abydos and begins the hypostyle hall at Karnak. His tomb (KV17) is the most beautiful and longest in the Valley of the Kings up to that time.' },
    { d: 'c. 1274 BC', t: 'The battle of Kadesh', x: 'In year 5 of **Ramesses II**, the Egyptian army faces the Hittite army of **Muwatalli II** near the Syrian city of Kadesh. The pharaoh escapes an ambush and declares himself the victor in all his temples; the Hittites do the same. Today it is seen as a **draw** that left Kadesh in Hittite hands.' },
    { d: 'c. 1259 BC', t: 'The peace treaty', x: 'In year 21 of Ramesses II, he and the Hittite king **Hattusili III** sign a treaty of peace and mutual aid, of which copies survive in Egyptian and in Akkadian. It is one of the oldest peace treaties whose text is known. Later the king marries a Hittite princess.' },
    { d: 'c. 1264 – 1244 BC', t: 'Abu Simbel', x: 'Ramesses II has the **Great Temple** of Abu Simbel and the small temple of Queen **Nefertari** cut into the rock in Nubia. He also founds the new Delta capital, **Pi-Ramesses**. He reigned 66 years and had more than a hundred children.' },
    { d: 'c. 1213 – 1203 BC', t: 'Merneptah and the Libyans', x: 'His son **Merneptah** defeats an invasion of Libyans and “Sea Peoples” (c. 1208 BC). His “Israel Stele” is the earliest Egyptian text to mention the name **Israel**, as a people (not a city or a kingdom). A series of weak and disputed kings follows (Amenmesse, Seti II, Siptah) and a queen, **Twosret**.' },
    { d: 'c. 1186 – 1153 BC', t: 'Ramesses III and the Sea Peoples', x: 'After a civil war, **Setnakht** founds Dynasty 20. His son **Ramesses III** faces two Libyan invasions and, c. 1177 BC (year 8), the great threat of the **Sea Peoples**, who had razed the Hittite empire and the cities of Syria. He defeats them on land and in the Delta, and records it at Medinet Habu.' },
    { d: 'c. 1158 BC', t: 'The first recorded strike', x: 'In year 29 of Ramesses III, the craftsmen of **Deir el-Medina**, unpaid in grain rations, stop work and march to the temples of Thebes. It is the first collective workers’ movement of which there is a detailed record.' },
    { d: 'c. 1155 BC', t: 'The harem conspiracy', x: 'Ramesses III is the victim of a plot organised by a secondary wife, **Tiye**, to put her son **Pentaweret** on the throne. The conspirators are tried (the *Judicial Papyrus of Turin*), but the king’s mummy has a fatal cut in the throat, which suggests the king was indeed killed.' },
    { d: 'c. 1155 – 1069 BC', t: 'Ramesses IV to XI and the decline', x: 'Eight kings named **Ramesses** follow one another, with ever less power. Floods fail, prices rise, robberies of royal tombs multiply (the Abbott and Amherst papyri record the trials, c. 1110 BC), and Nubia and the Levant are lost. In Thebes the High Priest of Amun becomes almost as powerful as the king.' },
    { d: 'c. 1069 BC', t: 'The end of the New Kingdom', x: 'With the death of **Ramesses XI**, the country splits: one king, **Smendes**, rules the Delta from Tanis, while the priests of Amun dominate the south. The Third Intermediate Period begins (see the page “Third Intermediate and Late Period”).' }
  ] },
  { img: 'eni-estela-kamose', leg: 'Kamose stela describing the war against the Hyksos, Luxor Museum.' },
  { img: 'eni-cerco-megiddo', leg: 'Siege of Megiddo by Thutmose III’s army, c. 1457 BC. AI-generated illustration.' },
  { img: 'eni-carta-amarna', leg: 'Amarna letter from Shipti-Baal, ruler of Lachish, in Akkadian, fourteenth century BC; British Museum ME 29848, EA 330.' },
  { img: 'eni-povos-do-mar', leg: 'Graphic copy of the relief of Ramesses III’s battle against the Sea Peoples, Medinet Habu.' }
];

const mapa = [
  'The Egypt of the New Kingdom is at once the Nile valley and an empire. At home are the great capitals and temples, between Memphis and Elephantine; abroad, the fortresses of Nubia and the governors of the Levant. The cities and sites that follow are the most important of this period.',
  { img: 'eni-mapa-hicsos', leg: 'Map of the early Hyksos period: political divisions of Egypt and the kingdom of Kush/Kerma; labels in Portuguese.' },
  { tabela: { cab: ['City or site', 'God or function', 'Place today', 'What it is known for'], linhas: [
    ['Avaris', 'Seth (Baal); Hyksos capital', 'Tell el-Dab’a, eastern Delta', 'Capital of the Hyksos; trading city with the Levant and the Aegean; besieged by Ahmose I'],
    ['Thebes', 'Amun-Ra, Mut, Khonsu', 'Luxor', 'Religious and often political capital of the New Kingdom'],
    ['Karnak', 'Amun-Ra', 'Luxor (east bank)', 'The largest temple complex in Egypt'],
    ['Luxor Temple', 'Amun-Ra (as Amenemope)', 'Luxor', 'Destination of the Opet festival; temple of Amenhotep III and Ramesses II'],
    ['Deir el-Bahari', 'Amun; Hathor', 'West bank of Thebes', 'Temple of Hatshepsut; temple of Mentuhotep II'],
    ['Valley of the Kings', 'Royal necropolis', 'West bank of Thebes', 'Tombs of Thutmose III, Seti I, Ramesses II, Tutankhamun…'],
    ['Deir el-Medina', 'Village of the tomb craftsmen', 'West bank of Thebes', 'Letters, lawsuits and the first recorded strike'],
    ['Medinet Habu', 'Mortuary temple of Ramesses III', 'West bank of Thebes', 'Reliefs of the Sea Peoples'],
    ['Memphis', 'Ptah', 'Mit Rahina, near Cairo', 'Administrative capital and military base of the empire'],
    ['Pi-Ramesses', 'Capital of Ramesses II', 'Qantir, eastern Delta', 'Royal residence and base for the campaigns in Syria'],
    ['Akhetaten', 'Aten', 'Tell el-Amarna', 'Capital of Akhenaten; Amarna letters; bust of Nefertiti'],
    ['Abydos', 'Osiris', 'Abydos', 'Temple of Seti I and the King List; pilgrimage centre'],
    ['Elephantine', 'Khnum, Satet, Anuket', 'Aswan', 'Southern frontier; trade with Nubia'],
    ['Buhen and Semna', 'Fortresses', 'Sudan (the Second Cataract)', 'Forts of Nubia inherited from the Middle Kingdom'],
    ['Napata (Gebel Barkal)', 'Amun', 'Karima, Sudan', 'Southern limit of the empire of Thutmose III'],
    ['Abu Simbel', 'Ra-Horakhty; Hathor', 'South of Aswan', 'Rock temples of Ramesses II and of Nefertari'],
    ['Gaza', 'Capital of the province of Canaan', 'Gaza Strip', 'Military and administrative base of the Levant'],
    ['Megiddo', 'Canaanite city', 'Tel Megiddo, Israel', 'Battle of Thutmose III, 1457 BC'],
    ['Kadesh', 'Syrian city', 'Tell Nebi Mend, Syria', 'Battle of Ramesses II against the Hittites'],
    ['Punt', 'Land of incense', 'Red Sea coast (Sudan/Eritrea?)', 'Destination of the expeditions of Hatshepsut']
  ] } },
  { h: 'Avaris (Tell el-Dab’a)' },
  'The capital of the Hyksos stood on an eastern branch of the Nile, now dry, near modern Qantir. The excavations, led by **Manfred Bietak** from 1966, show a large city, with houses and tombs in Canaanite style (horse burials included), pottery from all over the eastern Mediterranean and, in a palace, **Minoan-style frescoes** (with “bull-leapers”), which can only be explained by close contacts with the Aegean world. Archaeologists still discuss their dating (whether they belong to the Hyksos period or to after its fall).',
  { img: 'eni-tell-el-daba', leg: 'Tell el-Dab’a, ancient Avaris: view of the tell and present-day landscape, with modern cemetery and settlement.' },
  { img: 'eni-avaris-reconstrucao', leg: 'Conjectural reconstruction of Avaris in the Hyksos period, c. 1600 BC; Minoan frescoes are omitted because their chronology is disputed. AI-generated illustration.' },
  { h: 'Thebes (Luxor)' },
  'The “city of Amun” was, throughout the New Kingdom, the heart of the country. On the east bank, the city of the living, stood the temples of **Karnak** and **Luxor**; on the west bank, the city of the dead, the **Valley of the Kings**, the Valley of the Queens, the mortuary temples and the craftsmen’s villages. The link between the two banks was the life of the river: processions, funeral cortèges and the “Beautiful Festival of the Valley” crossed it every year. The Greeks called it “Thebes” and Homer speaks of it as the city of the “hundred gates”.',
  { h: 'Karnak' },
  'The enclosure of **Amun-Ra** grew for more than two thousand years, but it is the New Kingdom that gives it its present scale: pylons of Amenhotep III, Horemheb and Ramesses II, obelisks of Thutmose I and Hatshepsut and, at the centre, the **hypostyle hall** of Seti I and Ramesses II, with 134 columns (the twelve of the central aisle are about 21 m high). The walls hold the Annals of Thutmose III and the battles of Seti I and Ramesses II. Akhenaten’s temples to the Aten were dismantled after his death: their stones (the *talatat*) were reused as fill in the pylons and are now being recovered.',
  { img: 'eni-karnak-reconstrucao', leg: 'Artistic reconstruction of the Temple of Amun-Ra at Karnak under Ramesses II, c. 1250 BC. AI-generated illustration.' },
  { h: 'Luxor' },
  'Luxor temple, linked to Karnak by an avenue of sphinxes about 2.7 km long, was begun by Amenhotep III and extended by Ramesses II, who added the great court and the first pylon, with only one of the two original obelisks: the other is now in Paris, in the Place de la Concorde, given by Mehmet Ali in 1830 and erected in 1836.',
  { h: 'Deir el-Bahari' },
  'The mortuary temple of Hatshepsut, with terraces and colonnades, was built against a rock cliff, beside the older temple of Mentuhotep II. The reliefs show the expedition to **Punt**, the divine birth of the queen and the transport of the obelisks. The authorship of the design is debated: it is usually credited to **Senenmut**, but there is no firm proof. The queen was later erased from the walls, and many statues were broken and buried.',
  { img: 'eni-deir-el-bahari', leg: 'Mortuary Temple of Hatshepsut, Deir el-Bahari.' },
  { h: 'The Valley of the Kings' },
  'The pharaohs of Dynasty 18 and after stopped building pyramids and chose a dry valley, dominated by a peak shaped like a natural pyramid, where they cut their tombs. More than **60 tombs** have been identified (numbered KV1 to KV65 and beyond), not all of them royal. They are decorated with funerary texts (the *Amduat*, the *Book of Gates*) and, in the later ones, with the *Book of the Dead*. In 1922, Howard Carter found that of Tutankhamun (KV62), and in 1995 the huge **KV5**, of the sons of Ramesses II, was revealed.',
  { img: 'eni-vale-reis', leg: 'Panoramic view of the Valley of the Kings, western Thebes.' },
  { h: 'Deir el-Medina' },
  'The village of the craftsmen who cut and decorated the royal tombs, behind the hill of West Thebes, lasted some 450 years. It had around 60 houses, a temple of Hathor and its own necropolis, with painted tombs (of Sennedjem, of Inherkhau…). It is the place where we know best the life of ordinary people in Egypt, thanks to thousands of ostraca and papyri: letters, medical recipes, accounts, lawsuits and complaints.',
  { h: 'Medinet Habu and the Ramesseum' },
  'The mortuary temple of **Ramesses III** at Medinet Habu, almost intact, has on its walls the most complete narrative of battles in Egypt, including the fight against the Sea Peoples, on land and in the Delta. The **Ramesseum**, the mortuary temple of Ramesses II, has the remains of a colossal statue that inspired Shelley’s poem *Ozymandias* (1818).',
  { img: 'eni-medinet-habu', leg: 'First pylon of Ramesses III’s mortuary temple, Medinet Habu, Thebes.' },
  { h: 'Memphis' },
  'Memphis, the capital of the Old Kingdom, remained a major centre of the kingdom: seat of the vizier of the North, of the arsenals and of the fleet, with a huge temple of Ptah. Amenhotep II, who spent his youth there, and other kings made it the base of the armies that set out for Asia. Very little of what existed there survives today, because it was destroyed and reused.',
  { h: 'Pi-Ramesses' },
  'The “House of Ramesses, Great of Victories”, the capital Ramesses II founded in the eastern Delta, beside old Avaris, was a city of palaces, temples, barracks, chariot workshops and shipyards. It was abandoned when the branch of the Nile it stood on dried up (c. 1100 BC) and its monuments were taken to Tanis. The city is mentioned in the Bible (“Raamses”, Exodus 1:11), but this is not historical proof of the Exodus.',
  { img: 'eni-pi-ramses', leg: 'Artistic reconstruction of Pi-Ramesses in the eastern Delta, c. 1250 BC. AI-generated illustration.' },
  { h: 'Akhetaten (Amarna)' },
  'Akhenaten founded his city on a virgin site, in a semicircular bay of cliffs on the east bank of the Nile, halfway between Memphis and Thebes. It had palaces, the Great Temple of the Aten (open to the sky), residential districts, workshops (where the bust of Nefertiti was found), a workmen’s village and tombs in the cliffs. It was built in a few years and abandoned soon after the king’s death.',
  { img: 'eni-amarna-ruinas', leg: 'Ruins of Akhetaten, Tell el-Amarna.' },
  { h: 'Abydos' },
  'City of Osiris, it was the great pilgrimage place of Egypt. **Seti I** built a remarkable temple there, with the famous **Abydos King List**, in which the king and his son, the future Ramesses II, pay homage to 76 ancestors. The list deliberately omits Hatshepsut, the Amarna kings and the Hyksos. Behind the temple lies the Osireion, a cenotaph of Seti I.',
  { h: 'Elephantine and Nubia' },
  'The island of Elephantine, by the First Cataract (Aswan), was the gateway to the south. Beyond it, the pharaohs of the New Kingdom controlled Nubia up to the Fourth Cataract, with governors (the “King’s Son of Kush”), fortresses and temples. The Egyptians built **Soleb** (Amenhotep III), **Gebel Barkal** (near Napata) and **Abu Simbel** (Ramesses II). Nubia supplied **gold**, slaves, ebony and soldiers (the Medjay).',
  { h: 'The Levant' },
  'In the Levant, Egypt did not create real provinces in the Roman manner. It governed through local **vassal kings** (the Canaanites, whose letters we know), with Egyptian governors in Gaza and other cities and garrisons on the roads. The princes paid tribute and gave horses, timber and sons as hostages, who were educated at the Egyptian court. Among the main cities: **Gaza, Jaffa, Megiddo, Beth Shean, Kumidi, Byblos and Kadesh**.',
  { h: 'Punt' },
  'The land from which came incense, myrrh and ebony, it lay in the south of the Red Sea (eastern Sudan, Eritrea or both: debated). Hatshepsut sent five ships there, c. 1471 BC (year 9).',
  { h: 'The routes' },
  { lista: [
    '**The Nile:** the main “road”. The annual floods defined the calendar, and everything moved by boat, downstream to the north and under sail to the south, with the north wind.',
    '**The Way of Horus:** the coastal military route linking the Delta to Gaza across Sinai, with fortresses and wells along the whole road.',
    '**The Wadi Hammamat and the Red Sea:** road between the Nile valley and the Red Sea port (Mersa Gawasis), from which the expeditions to Punt set out.',
    '**The desert routes:** caravan roads to the gold mines of Nubia and to the western oases.'
  ] }
];

const sociedade = [
  { h: '1. Political organisation' },
  'The Egypt of the New Kingdom was a **divine monarchy**: the pharaoh was the son of Amun-Ra, guarantor of the order of the universe (*Maat*) and supreme commander of the army. Succession was usually from father to son, but queens had an important role, and there were women kings (Hatshepsut and, later, Twosret). From Thutmose III the pharaoh also appears as a warrior “hero”: he rides a chariot, kills lions and crushes his enemies.',
  'The administration was headed by **two viziers** (one for the North, one for the South, at Thebes), who were supreme judges and heads of the administration; **treasurers**, **overseers of the granaries** and **governors** (the “mayors”) of the cities; and, in Nubia, the **viceroy of Kush**. In the Levant there were vassal kings and garrisons. A standing army and a bureaucracy of scribes kept it all running.',
  { cit: 'So that order may remain in the world: I have restored what was destroyed, raised up what was dismembered, since the Asiatics were in the midst of Avaris, in the north.', fonte: 'Inscription of Hatshepsut at the Speos Artemidos (approximate translation; the “restoration” she boasts of is partly propaganda)' },
  { h: '2. The Hyksos: facts and myths' },
  'The Hyksos were not a sudden “invasion”, as Manetho and Flavius Josephus told it (Josephus calls them “shepherd kings”, by a mistranslation). Archaeology shows that Canaanites, or western Semites, settled in the eastern Delta over generations, as traders, soldiers and craftsmen, and that their chiefs ended up taking local power when the kingdom of Dynasty 13 broke apart. They ruled with Egyptian titles and adopted Egyptian writing. The *Rhind Mathematical Papyrus*, the most famous work of Egyptian mathematics, was copied in their reign, in year 33 of Apepi (c. 1550 BC), by a scribe named Ahmes.',
  { lista: [
    '**Chariots and horses:** it is often said that the Hyksos brought the horse and the war chariot, but this is debated. The horse does appear in the Delta in this period, but the chariot only appears in Egyptian texts and images at the beginning of Dynasty 18.',
    '**Composite bow, bronze weapons, new pottery and the vertical loom:** these are innovations from the Levant that entered Egypt in this period. How much of this came with the Hyksos and how much from wider contacts is debated.',
    '**The Hyksos are not to be confused with the Israelites:** the idea, which comes from Josephus, that their expulsion is the Bible’s “Exodus” has no proof, and most historians reject it.'
  ] },
  { cit: 'To what end do I know my strength? One chief is in Avaris, another in Kush, and I sit joined with an Asiatic and a Nubian! Each man has his slice of this Egypt.', fonte: 'Stela of Kamose (approximate translation)' },
  { h: '3. Social classes' },
  'Society was a pyramid. At the top, the **pharaoh** and the royal family. Below, an elite of **high officials, priests and officers**, often linked by marriage. Then the **scribes** (the category closest to power), the **chariot soldiers** and the **craftsmen**, among them the well-paid specialists of Deir el-Medina. The great majority were **peasants**, tied to the land of the state, of a temple or of a lord; there were also **servants and slaves**, mostly prisoners of war and foreigners, above all Nubians and Asiatics.',
  'Rising was possible: many officers of modest origin became viziers, and the general **Horemheb** and the vizier **Ramesses I** became pharaohs. But advancement always came through a link to the palace.',
  { h: '4. Religion' },
  'In the New Kingdom the old gods continue to be worshipped, but one of them takes first place: **Amun**, the hidden god of Thebes, merged with the sun god as **Amun-Ra**, “King of the Gods”. The pharaohs credited him with their victories and offered him a share of the booty, land and slaves, which made the temples and their priests grow enormously. For the general details of Egyptian religion, see the page “Gods, writing and daily life”.',
  { tabela: { cab: ['God', 'Domain', 'Role in the New Kingdom'], linhas: [
    ['Amun-Ra', 'King of the gods, sun', 'God of the empire; temple of Karnak; oracles'],
    ['Mut and Khonsu', 'Wife and son of Amun', 'The Theban triad; temple of Mut at Karnak'],
    ['Aten', 'The sun disc', 'Only official god in the time of Akhenaten'],
    ['Osiris', 'Death and rebirth', 'Judge of the dead; centre at Abydos'],
    ['Ptah', 'Creator, craftsmen', 'God of Memphis, with Sekhmet and Nefertem'],
    ['Seth', 'Desert, storm, foreigners', 'God of Avaris (with Baal) and patron of the Ramessides, whose name comes from him (Seti)'],
    ['Hathor', 'Love, music, the dead', 'Protector of the dead and of the craftsmen; temples at Deir el-Bahari, Deir el-Medina and Abu Simbel'],
    ['Anubis', 'Embalming', 'Guide of the dead'],
    ['Maat', 'Order, truth', 'The principle the pharaoh must uphold'],
    ['Taweret and Bes', 'Protectors of childbirth and the home', 'Very popular in houses']
  ] } },
  { img: 'eni-festa-opet', leg: 'Opet festival procession at Thebes, c. 1300 BC, with Amun’s sacred barque. AI-generated illustration.' },
  { lista: [
    '**The Opet festival:** every year, in the flood season, the statue of Amun, and those of Mut and Khonsu, were carried on barques from the temple of Karnak to that of Luxor, among crowds. The festival came to last almost a month, and was a renewal of the king’s power.',
    '**The Beautiful Festival of the Valley:** the image of Amun visited the mortuary temples on the west bank, and families went to the tombs, ate and drank and remembered their dead.',
    '**Oracles:** the statue of the god, carried by priests, “answered” questions by moving forward or backward. According to Hatshepsut herself, it was an oracle of Amun that chose her to rule.'
  ] },
  { h: '5. The Amarna “revolution”' },
  'In the fifth year of his reign, King **Amenhotep IV** became **Akhenaten** (“he who serves the Aten”). The **Aten** was the sun disc, shown with rays ending in hands that bless. Akhenaten closed the temples of other gods, especially those of Amun, erased their names, built a new capital and changed art: royal figures came to have elongated faces, strangely shaped bodies and intimate family scenes. The **Great Hymn to the Aten**, attributed to the king, has similarities with Psalm 104 of the Bible, but the relationship between the two is debated.',
  { lista: [
    '**Monotheism?** Many historians speak of a **monolatrous** religion (only one god is worshipped) rather than true monotheism: the king and the family remained divine, and the people worshipped the king and queen as intermediaries of the Aten.',
    '**Akhenaten and Moses:** the idea (from Freud, among others) that Moses was influenced by Akhenaten has no historical or archaeological basis.',
    '**The end:** with the king’s death his cult was abandoned. Tutankhamun restored the old gods (in the “Restoration Stela”), Horemheb erased the names of the Amarna kings and their stones were reused. Akhenaten became “the enemy of Akhetaten”.'
  ] },
  { img: 'eni-amarna-vida', leg: 'Akhenaten, Nefertiti and their daughters venerating Aten at Akhetaten, c. 1345 BC; rays ending in hands are an artistic religious motif. AI-generated illustration.' },
  { h: '6. Death and tombs' },
  'The pharaohs of the New Kingdom separated the tomb from the temple. The **tomb** (hypogeum) was dug, hidden, in the Valley of the Kings; the **mortuary temple** (the “temples of millions of years”) stood on the plain, near the river, and offerings to the dead king were made there, also linked to the cult of Amun. Nobles had themselves buried in painted chapel-tombs on the hill of Thebes, where scenes of life (hunting, banquets, harvests) show the ideal of the “afterlife” as a happy continuation of this one.',
  { img: 'eni-livro-dos-mortos', leg: 'Weighing of the heart in the Papyrus of Ani, British Museum, EA 10470.' },
  { lista: [
    '**The texts in royal tombs:** the *Amduat* (“That which is in the Underworld”) and the *Book of Gates* describe the Sun’s night journey through the world of the dead.',
    '**The Book of the Dead:** a collection of magical spells written on papyri placed in tombs (mainly for private individuals). Its chapter 125 describes the Judgement of Osiris, with the weighing of the heart against the feather of Maat.',
    '**Ushabti:** small statuettes that would work for the deceased in the afterlife. Tutankhamun had 413.',
    '**Tomb robbery:** nearly all the royal tombs were plundered in antiquity; that of Tutankhamun largely escaped because it was covered by the debris from the tomb of Ramesses VI.'
  ] },
  { img: 'eni-enterro-real', leg: 'Royal funeral procession towards the Valley of the Kings, c. 1300 BC. AI-generated illustration.' },
  { h: '7. Economy' },
  'The economy rested on the **agriculture** of the valley and the Delta, watered by the Nile floods, in which **grain** (wheat and barley) was the base. There was no coinage: payments were made in grain, bread, beer, cloth, and weights of copper or silver (the *deben*). **Taxes** were collected in produce and by scribes, and the **temples** owned huge lands and herds, especially that of Amun. The **wealth of the empire** came from the gold of Nubia, the tribute of Asia and an active trade with the Levant, Cyprus and the Aegean, and with Punt.',
  { img: 'eni-navio-punt', leg: 'Ship of Hatshepsut’s expedition to Punt, c. 1471 BC, loading myrrh trees and other goods. AI-generated illustration.' },
  { lista: [
    '**Gold:** the mines of Nubia gave gold in abundance, the basis of diplomacy. In an Amarna text, the king of Mitanni says that in Egypt gold “is like dust”.',
    '**Copper and turquoise:** extracted in the mines of Sinai (Serabit el-Khadim), with a temple of Hathor.',
    '**Timber and resins:** cedar from Lebanon and incense and ebony from Punt.',
    '**Foreigners in Egypt:** there were Canaanite, Nubian, Libyan and Aegean traders, mercenaries and craftsmen. The “Sea Peoples” even served as mercenaries.'
  ] },
  { h: '8. Writing and language' },
  'In the New Kingdom the spoken language, **Late Egyptian**, was no longer that of the Middle Kingdom, but monuments continued to use classical Egyptian, in **hieroglyphs**. Everyday documents used **hieratic** (cursive script) on papyrus and ostraca. For diplomacy abroad, **Akkadian** was used, on clay tablets, the international language of the time, and the Amarna letters show that the court had scribes who mastered it.',
  'Future scribes learned from childhood, copying texts, in harsh conditions. A much-copied school text, the *Satire of the Trades*, praises the scribe’s profession at the expense of all others.',
  { h: '9. The house' },
  'Ordinary houses were of mud brick, with a flat roof of branches and straw. In the districts of Amarna and Deir el-Medina a pattern can be seen: an entrance room, a main room with a central column and a family altar, bedrooms, a kitchen and a stair to the roof terrace. The rich had **villas** with a garden, a water pool and trees, as seen in many tomb paintings. Palaces, such as that of Amenhotep III at Malkata, had painted floors and walls.',
  { img: 'eni-casa-novo-imperio', leg: 'Conjectural interior of a craftsman’s house at Deir el-Medina, c. 1250 BC. AI-generated illustration.' },
  { h: '10. Food' },
  'Bread and beer were the base. Beer was low in alcohol and nutritious, drunk by all, children included. People also ate onions, garlic, lentils, chickpeas, lettuce, fish (dried and salted), fowl and, at festivals, beef. The rich drank **wine**, of which there are many traces, including the amphorae of Tutankhamun’s tomb, labelled with the year, the vineyard and the vintner. Honey and dates were the sweets, and oil came from the moringa and the olive.',
  { img: 'eni-nebamun-pesca', leg: 'Nebamun hunting birds in the marshes: tomb painting, British Museum, EA 37977.' },
  { h: '11. Clothing, beauty and adornment' },
  'Linen was everyday clothing. In the New Kingdom, rich men took to pleated linen tunics and kilts and women’s dresses became long and pleated. Men and women wore **wigs** and painted their eyes with **kohl**, which protected from the sun and from flies. They wore **jewellery** of gold, faience and stones. The paintings in the tombs of the Theban elite show parties at which guests wear cones of scented fat on their heads (whether these were real or only a painting convention is debated).',
  { h: '12. Music, games and entertainment' },
  'Feasts had **harpists, lute and flute players, dancers and acrobats**. The lute, the lyre and the tambourine came from Asia in the New Kingdom. The most popular board game was **senet**, a game of the dead person’s “path”, and there are others such as **mehen** and “20 squares”. Children had balls, spinning tops and dolls. **Hunting** and **fishing** in the marshes were seen as the ideal pleasure of the elites.',
  { h: '13. Science and medicine' },
  'Two of the great medical papyri are from this time or were copied in it: the **Edwin Smith Papyrus** (on trauma surgery, with cases of injuries described with an almost scientific method) and the **Ebers Papyrus** (c. 1550 BC, with some 700 remedies and spells). Mathematics used fractions and the “rule of three”, as the Rhind papyrus shows. Astronomers recorded the rising of Sirius and the decans (groups of stars); **water clocks** (clepsydras) and shadow clocks were used to mark the hours. The “Turin Papyrus” (a map of mines) is considered the oldest known topographical map.',
  { h: '14. Technology' },
  { lista: [
    '**War chariot:** light, of wood and hide, with two six-spoked wheels and two horses, driven by a charioteer and an archer. It was the “decisive weapon” of the New Kingdom.',
    '**Composite bow and khopesh sword:** the bow, of wood, horn and sinew, had a longer range than the simple bow.',
    '**Shaduf:** a bucket attached to a lever arm, to lift water from the river. It appears in Egypt in the New Kingdom and made it possible to irrigate higher land.',
    '**Glass:** the making of coloured glass, in moulded objects, began early in Dynasty 18.',
    '**Metals:** bronze was common; iron was rare and precious, like Tutankhamun’s dagger, made of meteoritic iron.',
    '**Building:** pylons, columns and huge blocks of stone, moved on sledges, with ramps, levers and a large workforce.'
  ] },
  { h: '15. The army and war' },
  'For the first time Egypt had a **professional army**, of two arms: the **infantry**, with archers and spearmen, and the **chariots**, the elite of the nobles. To these were added mercenaries, such as the Nubian **Medjay** and the **Sherden**. The army marched in divisions named after gods (Amun, Ra, Ptah, Seth). The river and sea fleet carried it to the Levant. The pharaohs campaigned in spring, after the harvest, and took cities by siege, assault or treachery, as told in a story about **Djehuty**, general of Thutmose III, who is said to have entered Jaffa with soldiers hidden in baskets (a tale, not history).',
  { img: 'eni-carro-guerra', leg: 'Egyptian war chariots of the thirteenth century BC, with two horses, a driver and an archer. AI-generated illustration.' },
  { h: '16. Kadesh and the treaty' },
  'In 1274 BC, Ramesses II led four divisions against the Hittites near Kadesh. Spies deceived him, and the pharaoh, with his division isolated, was attacked by 2,500 Hittite chariots, but held out, helped by the arrival of reinforcements. The reliefs of Abu Simbel, the Ramesseum and Karnak present the king as the only hero and winner, while the Hittite archives tell another version. In 1259 BC the two powers signed the treaty, which was carved in the temple of Karnak and written on clay tablets at Hattusa (now in the Istanbul Archaeology Museum).',
  { img: 'eni-batalha-kadesh-relevo', leg: 'Relief of the Battle of Kadesh, Ramesseum, Thebes.' },
  { img: 'eni-tratado-kadesh', leg: 'Tablet of the treaty between Ramesses II and Hattusili III, Istanbul Archaeology Museum.' },
  { h: '17. Diplomacy: the “club of great kings”' },
  'In the time of Amenhotep III and Akhenaten, the rulers of Egypt, Babylon, Mitanni, Hatti and (later) Assyria addressed one another as “brothers” and exchanged letters, gifts and brides. The Amarna letters, written in Akkadian, show us kings complaining about the poor quality of the gold received, asking for doctors and sculptors and negotiating marriages. Egypt, curiously, **very rarely sent brides**: it asked for princesses from others but did not give them, which was a cause of complaint.',
  { h: '18. The Sea Peoples' },
  'Around 1200 BC a series of crises (droughts, wars, earthquakes, the action of bands of warriors from the sea) brought down the kingdoms of the Late Bronze Age: Hatti disappeared, Ugarit was destroyed and the Mycenaean cities collapsed. The Egyptians knew these groups by name (*Peleset*, *Tjeker*, *Shekelesh*, *Denyen*, *Weshesh*, among others) and called them “the Sea Peoples”. Ramesses III defeated them, on land and in a naval battle in the Delta, c. 1177 BC (year 8), but exactly who these peoples were and where they came from is much debated. The Peleset are, for many, the **Philistines** of the Bible, but this is not certain.',
  { img: 'eni-batalha-naval-delta', leg: 'Artistic interpretation of Ramesses III’s naval battle against the Sea Peoples in the Delta, c. 1177 BC. AI-generated illustration.' },
  { h: '19. Deir el-Medina: the craftsmen’s village' },
  'About **60 families** of craftsmen (stonecutters, sculptors, draughtsmen, painters and scribes) lived in a walled village near the Valley of the Kings and worked there in two gangs, the “left” and the “right”, led by foremen and scribes. The week had ten days, eight of work and two off. They were paid by the state, in grain, beer, fish, firewood, vegetables and clothing, and received bonuses at festivals. When the rations were late, in year 29 of Ramesses III (c. 1158 BC), they stopped work and marched, shouting that they were hungry, to the temples of Thebes, and the vizier ordered grain distributed.',
  { img: 'eni-vila-trabalhadores', leg: 'Artistic reconstruction of Deir el-Medina under Ramesses II, c. 1250 BC. AI-generated illustration.' },
  { lista: [
    '**Ostraca:** letters, lists, sketches, love poems, recipes and humorous drawings, which show us a community of readers and writers.',
    '**Justice:** there was a local court (*kenbet*), of men of the village, that judged cases of debts, inheritances and assaults. Women could be witnesses, inherit and dispose of their property.',
    '**Free workers, not slaves:** the pyramids and tombs were not built by slaves, as in the myth of Herodotus and the cinema, but by paid craftsmen and workers.'
  ] },
  { h: '20. Women' },
  'Egyptian women had more rights than the women of almost all other ancient civilisations. They could own property, inherit, buy, sell, bring a case in court and divorce. There were priestesses, musicians and “God’s Wives of Amun”, a very important office held by queens (Ahmose-Nefertari, Hatshepsut). Some queens held real political power: **Tiy**, **Nefertiti**, **Nefertari** and **Hatshepsut** herself.',
  { h: '21. Crime and punishment' },
  'Penalties included beating, mutilation, forced labour, exile to Nubia and death. The worst crimes were robbing royal tombs and conspiracy. The **Abbott**, **Amherst** and **Mayer** papyri (c. 1110 BC) record the trials of robbers of the tombs of the Valley of the Kings, with interrogations under torture, and the **Judicial Papyrus of Turin** the trial of the harem conspiracy against Ramesses III, with many death sentences, and some judges who were themselves punished for socialising with the accused.',
  { h: '22. Art' },
  'The art of the New Kingdom is colourful, elegant and luxurious. The reliefs and tomb paintings show feasts, hunting, harvests and the afterlife. Under Amenhotep III and Akhenaten the style becomes softer and more elegant, and after the “Amarna style” (rounded forms, elongated bodies) there is a return to a more classical style. The colossal statues of Ramesses II are a symbol of power. The workshop of the sculptor **Thutmose** at Amarna produced the most celebrated portraits of the age, including the bust of **Nefertiti**.',
  { img: 'eni-oficina-escultor', leg: 'Workshop of a royal sculptor at Akhetaten, c. 1345 BC, with unfinished busts and heads. AI-generated illustration.' }
];

const personalidades = [
  'The figures that follow are all real. For the complete life of each pharaoh, see the page “The pharaohs”. The dates are those of Shaw (2000); the most debated reigns and identifications are flagged.',
  { h: 'Apepi (Aauserre Apepi), Hyksos king (mid-16th century BC)' },
  'The best-known Hyksos king. He reigned at least 33 years (the Rhind Papyrus was copied in his year 33) from Avaris, and was the rival of the Theban kings. A late Egyptian tale, the *Tale of Apophis and Seqenenre*, says Apepi complained that the hippopotamuses in the pool at Thebes would not let him sleep; it is a narrative, not a fact. His name appears on stone objects and seals.',
  { h: 'Kamose (c. 1555 – 1550 BC)' },
  'The last king of Dynasty 17. In his stelae at Karnak he tells how his counsellors told him to keep still, and how he, “with my strength”, launched the war, attacked the north and intercepted a message from Apepi to the kings of Kush. He died soon after, without freeing Avaris. It is not known for certain whether he was brother or son of Seqenenre Tao, nor whether he was brother or father of Ahmose I.',
  { h: 'Ahmose I (c. 1550 – 1525 BC)' },
  'Founder of Dynasty 18 and of the New Kingdom. He came to the throne as a child and completed the war against the Hyksos, whom he expelled from Egypt and pursued to southern Palestine. He then fought in Nubia and reorganised the state. His mummy was found in the Deir el-Bahari cache (DB320) in 1881.',
  { h: 'Ahmose-Nefertari (16th century BC)' },
  'Wife and sister of Ahmose I, mother of Amenhotep I. She was the first “God’s Wife of Amun” with real power, and after her death was venerated as a goddess, above all at Deir el-Medina, where she appears in paintings with black skin, the colour of rebirth and of the fertile soil of the Nile.',
  { h: 'Hatshepsut (king c. 1473 – 1458 BC; regent from c. 1479)' },
  'Daughter of Thutmose I, wife of Thutmose II and regent for her stepson, the future Thutmose III. Around year 7 of the reign she took the title of **king** and was shown, in statues, with masculine attributes and the false beard. She reigned about 15 years as king (over 20 counting the regency), during which the country prospered: she built at Deir el-Bahari and Karnak, and sent the expedition to Punt. Near the end of the reign of Thutmose III, her names and images were erased in many monuments, but why is debated (it is no longer thought to be immediate personal hatred). In 2007 a mummy (KV60A) was identified as hers, by a tooth that fitted a box bearing her name, but the identification is contested.',
  { img: 'eni-hatshepsut-estatua', leg: 'Kneeling granite statue of Hatshepsut, Metropolitan Museum.' },
  { h: 'Senenmut (active c. 1479 – 1458 BC)' },
  'Of modest origin, he rose to “Great Steward of Amun” and tutor of Princess Neferure, Hatshepsut’s daughter. He was linked to the building of Deir el-Bahari, as overseer of the works (but the architect of the temple is debated). His two tombs, one of them at Deir el-Bahari, include an astronomical ceiling. It is not known whether he was the queen’s lover, as has often been said (there is no proof), nor when and how he left the scene.',
  { h: 'Thutmose III (c. 1479 – 1425 BC)' },
  'The most famous warrior pharaoh. He came to the throne as a child and reigned 54 years, but ruled alone only from 1458. He made some 17 campaigns in Asia, won at Megiddo, crossed the Euphrates and had his **Annals** carved at Karnak, from the diary of a military scribe. He also had the exotic plants and animals he brought back from Syria shown at Karnak (the “Botanical Garden”). His mummy is in Cairo. He is sometimes called “the Napoleon of Egypt”, an exaggerated comparison.',
  { img: 'eni-tutmes-iii', leg: 'Greywacke statue of Thutmose III, Luxor Museum.' },
  { h: 'Amenhotep III (c. 1390 – 1352 BC) and Tiy' },
  'The king of the peak. He reigned 38 years in peace and luxury. He built the temple of Luxor, that of Soleb, the palace of Malkata and his mortuary temple, of which only the colossi (of Memnon) remain. He had hundreds of statues made of the lioness goddess Sekhmet. He married his chief wife **Tiy**, daughter of people from outside the royal family, whose name appears beside the king’s on all the monuments, and princesses of Mitanni and Babylon. His relations with the neighbouring kingdoms are recorded in the Amarna letters.',
  { img: 'eni-amenofis-iii', leg: 'Colossal red granite head of Amenhotep III, British Museum.' },
  { h: 'Akhenaten (c. 1352 – 1336 BC)' },
  'The “heretic king”. Son of Amenhotep III and Tiy, he came to the throne as Amenhotep IV, but hastened to elect the Aten as supreme god and to move to Amarna. He reigned 17 years. He is portrayed in an unusual way, with a long face, thin neck, and wide belly and hips: it is not known whether for reasons of illness (Marfan syndrome, which genetic tests have not confirmed) or by artistic and religious choice, the explanation preferred today. After his death he was almost erased from memory. His body has not been identified with certainty: the mummy from tomb KV55 is perhaps his, but some think it is Smenkhkare’s.',
  { img: 'eni-akhenaton-colosso', leg: 'Colossus of Akhenaten from Karnak, Egyptian Museum, Cairo.' },
  { h: 'Nefertiti (14th century BC)' },
  'The “Beautiful One has come”, chief wife of Akhenaten and mother of six daughters. She appears in the reliefs beside the king, on the same scale, offering to the Aten, and smiting enemies, an image until then reserved for the king. She disappears from the sources around year 12–16, and the reason is debated: she may have died, been displaced, or reigned as king under the name **Neferneferuaten**; there is no consensus. Her tomb has never been found, and the hypothesis, put forward in 2015, that it lay hidden behind that of Tutankhamun was ruled out by radar in 2018. The bust, from the workshop of Thutmose, is in Berlin.',
  { img: 'eni-nefertiti-busto', leg: 'Bust of Nefertiti, Neues Museum, Berlin.' },
  { h: 'Tutankhamun (c. 1336 – 1327 BC)' },
  'He came to the throne aged 8–10, at the end of the Amarna period. His birth name was Tutankhaten, “living image of the Aten”. He reigned less than ten years, during which the ministers (**Ay**, the vizier, and the general **Horemheb**) ruled in fact. He restored the old gods. He died aged about 18–19. Genetic tests published in 2010 indicate that his father was the mummy of KV55 and his mother the “Younger Lady” of KV35, both children of Amenhotep III and Tiy; the study has been criticised, and the cause of death (malaria, a leg fracture, or both) is still debated. He is famous above all for his tomb, found in 1922.',
  { h: 'Horemheb (c. 1323 – 1295 BC)' },
  'A career soldier, general of Tutankhamun, then king. He put order into the administration with an edict against the corruption of officials, restored the temples, erased the traces of Akhenaten and appropriated monuments of Tutankhamun and Ay. He had no children and chose his vizier **Ramesses I** as heir.',
  { h: 'Seti I (c. 1294 – 1279 BC)' },
  'Second king of Dynasty 19. He reconquered the Levant and opened the war with the Hittites, and had building done all over Egypt. His temple at Abydos and the hypostyle hall at Karnak are masterpieces, as is his tomb (KV17), found by Belzoni in 1817. His mummy, remarkably well preserved, is in Cairo.',
  { h: 'Ramesses II, “the Great” (c. 1279 – 1213 BC) and Nefertari' },
  'He reigned 66 years and dominated his century. He presented Kadesh as a great victory, signed the peace treaty, founded Pi-Ramesses, raised the Ramesseum and Abu Simbel and added his names to many monuments (sometimes erasing those of other kings). He had several wives, of whom the best loved was **Nefertari**, of the painted tomb (QV66) and of the small temple at Abu Simbel, and more than a hundred children. He died aged about 90; his mummy was found in 1881 and was studied in Paris in 1976.',
  { img: 'eni-ramses-ii-estatua', leg: 'Seated statue of Ramesses II, Museo Egizio, Turin.' },
  { h: 'Ramesses III (c. 1184 – 1153 BC)' },
  'The last great pharaoh of the New Kingdom. He defeated the Libyans and the Sea Peoples and built Medinet Habu. His reign was marked by crises: the strike at Deir el-Medina (year 29) and, at the end, the **harem conspiracy**, in which he lost his life. The CT scan of his mummy, in 2012, showed a deep cut in the throat, which confirms the murder. He was succeeded by his son, Ramesses IV.'
];

const legado = [
  { h: 'What they left us' },
  { lista: [
    '**The great temples and tombs:** Karnak, Luxor, Abu Simbel, the Valley of the Kings and Medinet Habu are still the great images of ancient Egypt.',
    '**International diplomacy:** the Amarna letters and the treaty of Kadesh are the earliest evidence of diplomacy between great powers.',
    '**The first debated “monotheism”:** Akhenaten’s experiment continues to fascinate historians and believers.',
    '**Social history:** the papyri and ostraca of Deir el-Medina are the best portrait of a working community of antiquity.',
    '**Technology:** the chariot, glass, the shaduf and the composite bow entered Egypt in this period and later passed to other peoples.'
  ] },
  { h: 'Art' },
  'The art of the New Kingdom, with its gold, its painted reliefs and the soft faces of Amenhotep III and Nefertiti, is regarded as the high point of Egyptian refinement. The gold and semi-precious stones of Tutankhamun’s jewellery, the furniture, the paintings of the Theban tombs (such as those of **Nebamun**, in the British Museum) and the portraits of Amarna are known worldwide.',
  { img: 'eni-trono-tutankhamon', leg: 'Tutankhamun’s golden throne.' },
  { h: 'Architecture' },
  'Pylons and hypostyle halls, avenues of sphinxes and temples cut into the rock are the typical style of the New Kingdom. They were made of sandstone and limestone blocks, raised with mud-brick ramps, and then painted in bright colours, of which only traces remain. The style later influenced the Ptolemaic and Roman temples.',
  { h: 'Rediscovery' },
  { lista: [
    '**1817:** Giovanni Belzoni finds the tomb of Seti I (KV17) and takes the alabaster sarcophagus to London, now in the Soane Museum.',
    '**1822:** Champollion deciphers the hieroglyphs (see the page “Gods, writing and daily life”).',
    '**1881 and 1898:** the two royal “caches” are found, at Deir el-Bahari (DB320) and in KV35, where the priests of the Third Intermediate Period had stored dozens of royal mummies to protect them from thieves.',
    '**1887:** a local peasant woman discovers at Amarna the clay tablets, now the “Amarna letters”.',
    '**1912:** the German archaeologist Ludwig Borchardt finds the bust of Nefertiti in the workshop of Thutmose.',
    '**4 November 1922:** the team of **Howard Carter**, funded by Lord Carnarvon, discovers the steps of the tomb of Tutankhamun, and in February 1923 opens the burial chamber.',
    '**1966 onwards:** Manfred Bietak excavates Tell el-Dab’a and reveals Avaris.',
    '**1995:** Kent Weeks reveals that tomb KV5, of the sons of Ramesses II, is enormous, with more than 120 chambers.'
  ] },
  { cit: 'Yes, wonderful things.', fonte: 'Howard Carter’s reply to Lord Carnarvon, who asked whether he could see anything, as he first peered into the chamber of Tutankhamun, according to Carter’s own account (1923)' },
  { img: 'eni-carter-tumba', leg: 'Howard Carter and Arthur Callender examining objects in Tutankhamun’s tomb, c. 1924; photograph by Harry Burton.' },
  { h: 'The mysteries that remain' },
  { lista: [
    '**The tomb of Nefertiti:** the hypothesis that it was hidden next to that of Tutankhamun (2015) was refuted by radar in 2018. Where it is remains to be discovered.',
    '**The Exodus:** there is no archaeological proof of the departure of a large group of Israelites from Egypt in the time of Ramesses II, and many archaeologists doubt the biblical account as history. The Merneptah Stele (c. 1208 BC) mentions “Israel” as a people, probably in Canaan.',
    '**The Sea Peoples:** still debated. Who they were, where they came from and why.',
    '**The curse of Tutankhamun:** a myth of the 1923 press, which spread after the death of Lord Carnarvon, in April 1923, of an infection. Studies show that the life expectancy of those involved in the discovery was no shorter than that of others.'
  ] },
  { h: 'Controversies and conservation' },
  'The **bust of Nefertiti** left Egypt in 1913, in a division of finds, and is in Berlin; Egypt has asked for its return for decades. **Abu Simbel** was saved by UNESCO in the 1960s: the temples were cut into blocks and reassembled 65 m higher, to escape the waters of the Aswan dam (1964–1968). The new **Grand Egyptian Museum**, in Giza, officially opened in November 2025 and shows, for the first time together, all the objects from Tutankhamun’s tomb. In 2021, 22 royal mummies were taken in procession from the Cairo Museum to the National Museum of Egyptian Civilization.',
  { img: 'eni-abu-simbel-salvamento', leg: 'Dismantling of an Osiriac pillar in the entrance hall of Abu Simbel’s Great Temple during the UNESCO rescue.' },
  { img: 'eni-grande-museu', leg: 'Grand Egyptian Museum, Giza.' },
  { h: 'Where to visit' },
  { lista: [
    '**Luxor (Thebes):** Karnak, Luxor temple, the Valley of the Kings, Deir el-Bahari, Medinet Habu, Deir el-Medina, the Ramesseum.',
    '**Abu Simbel and Aswan:** the temples of Ramesses II and the UNESCO rescue works.',
    '**Tell el-Amarna:** hard to reach, but with nobles’ tombs in the cliff.',
    '**Abydos:** the temple of Seti I and the King List.',
    '**Museums:** the Grand Egyptian Museum (Giza) and the Egyptian Museum (Cairo), the British Museum, the Louvre, the Neues Museum (Berlin), the Egyptian Museum of Turin, the Metropolitan Museum (New York) and the Luxor Museum.'
  ] },
  { h: 'Egyptomania' },
  'The New Kingdom is the Egypt the West loves most. The discovery of Tutankhamun’s tomb, in 1922, launched a fashion for “Egyptomania” that reached architecture, jewellery and cinema. Obelisks from Luxor, Karnak and Heliopolis are now in Paris, London, New York, Rome and Istanbul. Most of the images we have today of “ancient Egypt”, from golden pharaohs to Queen Nefertiti, come from this period.',
  { h: 'To continue' },
  'For the lives of the great kings, see “The pharaohs”; for the monuments, “Monuments and sites”; for religion, writing and everyday life, “Gods, writing and daily life”; for what came afterwards, “Third Intermediate and Late Period”.'
];

const quiz = [
  { p: 'Who were the Hyksos?', op: ['A people of Aegean sailors', 'Rulers of Asiatic (Canaanite) origin who dominated the Delta', 'The soldiers of Ramesses II', 'The priests of Amun'], certa: 1, exp: 'The name comes from the Egyptian *heqa-khasut*, “rulers of foreign lands”; their capital was Avaris.' },
  { p: 'Which king completed the expulsion of the Hyksos and founded Dynasty 18?', op: ['Thutmose III', 'Ahmose I', 'Amenhotep III', 'Horemheb'], certa: 1, exp: 'Ahmose I took Avaris, c. 1550 BC, and reunified the country.' },
  { p: 'Which woman reigned as pharaoh, built Deir el-Bahari and sent an expedition to Punt?', op: ['Nefertiti', 'Nefertari', 'Hatshepsut', 'Tiy'], certa: 2, exp: 'Hatshepsut took the title of king around year 7 of her reign.' },
  { p: 'Which battle did Thutmose III win against a Canaanite coalition in 1457 BC?', op: ['Kadesh', 'Megiddo', 'Actium', 'Carchemish'], certa: 1, exp: 'The battle of Megiddo (year 23) is recorded in the Annals at Karnak.' },
  { p: 'Where is the great account of the campaigns of Thutmose III, the “Annals”, inscribed?', op: ['At Abu Simbel', 'At Karnak', 'At Giza', 'At Memphis'], certa: 1, exp: 'The Annals were carved on the walls of the temple of Amun-Ra at Karnak.' },
  { p: 'Which god did Akhenaten raise above all others?', op: ['Osiris', 'Amun', 'Aten', 'Ptah'], certa: 2, exp: 'The Aten, the sun disc. Akhenaten founded a new capital, Akhetaten, at Amarna.' },
  { p: 'In which language were the Amarna letters written?', op: ['In Egyptian hieroglyphs', 'In Greek', 'In Akkadian, in cuneiform script', 'In Hebrew'], certa: 2, exp: 'Akkadian was the international language of diplomacy in the Late Bronze Age.' },
  { p: 'Who discovered the tomb of Tutankhamun in 1922?', op: ['Giovanni Belzoni', 'Howard Carter', 'Jean-François Champollion', 'Auguste Mariette'], certa: 1, exp: 'Carter, funded by Lord Carnarvon, found the steps of the tomb on 4 November 1922.' },
  { p: 'What did Tutankhamun do soon after coming to the throne?', op: ['Moved the capital to the Delta', 'Restored the traditional cults and returned to Thebes', 'Conquered Syria', 'Abolished the priesthood'], certa: 1, exp: 'He changed his name from Tutankhaten to Tutankhamun and restored Amun (Restoration Stela).' },
  { p: 'Where was the 1274 BC battle between Ramesses II and the Hittites fought?', op: ['At Megiddo', 'At Kadesh', 'At Avaris', 'At Thebes'], certa: 1, exp: 'Kadesh, in Syria. It is now considered a draw, despite Egyptian propaganda.' },
  { p: 'Which c. 1259 BC document is one of the oldest peace treaties whose text is known?', op: ['The Merneptah Stele', 'The treaty between Ramesses II and Hattusili III', 'The Code of Hammurabi', 'The Turin Papyrus'], certa: 1, exp: 'There are versions in Egyptian and in Akkadian.' },
  { p: 'Who built the temples of Abu Simbel?', op: ['Hatshepsut', 'Thutmose III', 'Ramesses II', 'Ramesses III'], certa: 2, exp: 'Ramesses II had the Great Temple and the temple of Queen Nefertari cut, c. 1264–1244 BC.' },
  { p: 'What happened at Deir el-Medina in year 29 of Ramesses III?', op: ['A military revolt', 'The first recorded strike', 'An earthquake', 'The discovery of a tomb'], certa: 1, exp: 'The craftsmen, without grain rations, stopped work (c. 1158 BC).' },
  { p: 'Against whom did Ramesses III fight, c. 1177 BC, in the battle shown at Medinet Habu?', op: ['The Assyrians', 'The Persians', 'The Sea Peoples', 'The Greeks'], certa: 2, exp: 'The Sea Peoples came by land and sea, and were defeated in the Delta.' },
  { p: 'Where were the pharaohs of the New Kingdom buried?', op: ['In pyramids at Giza', 'In tombs cut in the Valley of the Kings', 'In mastabas at Saqqara', 'At Alexandria'], certa: 1, exp: 'The rock-cut tombs in West Thebes were hidden from thieves.' }
];

export default { visao, linha, mapa, sociedade, personalidades, legado, quiz };
