// EGITO — 2.º INTERMÉDIO (HICSOS) E REINO NOVO. Conteúdo em português; a versão inglesa está em dados-en.js (mesma estrutura).
import EN from './dados-en.js';
import CRED from './creditos.js';
import { GRUPO } from '../grupo.js';
// Cronologia: segue-se Shaw (ed.), The Oxford History of Ancient Egypt (2000). Hornung–Krauss–Warburton (2006) dá datas ligeiramente diferentes (poucos anos). Todas as datas são «c.» salvo indicação contrária.
// Imagens: cada {img:'id'} procura o ficheiro  egito/novo-imperio/img/id.jpg  (ver IMAGENS_EGITO_NOVO_IMPERIO.md).

const visao = [
  { caixa: 'Em resumo', texto: [
    'Entre cerca de **1650 e 1069 a.C.** o Egito passou por duas coisas muito diferentes: primeiro, um século de divisão, em que o Delta foi governado por chefes de origem asiática, os **Hicsos**, e o sul por faraós tebanos; depois, a era mais rica e mais poderosa da sua história, o **Reino Novo**, o tempo dos grandes impérios do Bronze Final.',
    'Foi o tempo de **Hatshepsut**, de **Tutmés III**, de **Akhenaton** e da sua revolução religiosa, de **Tutankhamon**, de **Ramsés II** e da batalha de Kadesh. Foi o tempo do Vale dos Reis, de Karnak e de Abu Simbel, e também o tempo em que o rei começou a ser chamado «a Grande Casa» (*per-aa*, de onde vem a palavra «faraó») e foi buscar riqueza e poder muito para além do vale do Nilo: à Núbia, à Síria e à Palestina.'
  ] },
  { img: 'eni-mapa-novo-imperio', leg: 'Mapa da expansão egípcia no Reino Novo, c. 1450 a.C.' },
  { h: 'Onde e quando' },
  'O centro do poder deslocou-se. Durante o Reino Médio a capital ficava perto de Mênfis, a entrada do Delta; no Reino Novo é **Tebas** (hoje Luxor), no Alto Egito, a «cidade de Amon», que se torna o coração religioso e, quase sempre, político do reino. Os faraós tinham também residências no Norte, sobretudo Mênfis e, depois, **Pi-Ramessés**, no Delta oriental. Para lá do vale do Nilo, o Egito controlou a **Núbia** (até à quarta catarata e além) e uma rede de cidades e príncipes vassalos na **Palestina, no Líbano e na Síria**.',
  'Esta página cobre dois períodos: o **2.º Período Intermédio** (c. 1650 – 1550 a.C.), com as dinastias XV (Hicsos), XVI e XVII (Tebas), e o **Reino Novo** (c. 1550 – 1069 a.C.), com as dinastias XVIII, XIX e XX.',
  { tabela: { cab: ['Fase', 'Datas aproximadas', 'O que a marca'], linhas: [
    ['2.º Intermédio', 'c. 1650 – 1550 a.C.', 'Divisão do país: Hicsos em Avaris (dinastia XV), tebanos no sul (XVI–XVII), reino de Kerma na Núbia; guerra de libertação de Kamose e Ahmés I'],
    ['Dinastia XVIII (início)', 'c. 1550 – 1479 a.C.', 'Ahmés I expulsa os Hicsos; conquistas na Núbia e na Síria; os primeiros reis do Vale dos Reis'],
    ['Dinastia XVIII (apogeu)', 'c. 1479 – 1352 a.C.', 'Hatshepsut e Tutmés III; o império chega ao Eufrates; Amenófis III, o rei do ouro e da diplomacia'],
    ['Período de Amarna', 'c. 1352 – 1323 a.C.', 'Akhenaton e o culto do Aton; Tutankhamon e a restauração; Ay e Horemheb'],
    ['Dinastia XIX', 'c. 1295 – 1186 a.C.', 'Seti I e Ramsés II; Kadesh e o tratado com os hititas; Pi-Ramessés; Merneptah'],
    ['Dinastia XX', 'c. 1186 – 1069 a.C.', 'Ramsés III e os Povos do Mar; greves, roubos de túmulos e perda do império; o poder dos sacerdotes de Amon']
  ] } },
  { caixa: 'Que cronologia usamos', texto: 'A cronologia do Egito não é exata. Esta página segue a de **Shaw (2000)**, a que mais se vê nos manuais; a de **Hornung, Krauss e Warburton (2006)**, por exemplo, difere em alguns anos, e as datas anteriores ao Reino Novo são ainda mais discutidas. Por isso quase todas vêm com «c.». Os reinados longos (Tutmés III, Ramsés II) e algumas datas muito conhecidas (Megiddo, Kadesh) são mais seguros do que as datas dos Hicsos.' },
  { img: 'eni-hipostila-karnak', leg: 'Sala hipostila do templo de Amon-Rá, Karnak.' },
  { h: 'O que mudou' },
  { lista: [
    '**Um império:** pela primeira vez o Egito tem um exército permanente e conquista territórios fora do Nilo. Os Hicsos tinham mostrado ao Egito como era vulnerável; os faraós da dinastia XVIII quiseram que isso nunca mais acontecesse.',
    '**Armas novas:** o carro de guerra puxado por cavalos, o arco composto, o machado de lâmina de bronze e a espada curva *khopesh* tornam-se comuns. (Quem as trouxe, e quando, é discutido: ver a secção sobre os Hicsos.)',
    '**Um Estado novo:** o faraó é agora também chefe de guerra, e os soldados e oficiais formam uma nova elite. Aparecem cargos como o «Filho do rei de Kush» (vice-rei da Núbia).',
    '**O poder de Amon:** o deus de Tebas, Amon (depois Amon-Rá), torna-se o deus do império e o seu clero, riquíssimo, um poder rival do faraó.',
    '**Túmulos escondidos:** em vez de pirâmides, os reis fazem-se enterrar em túmulos escavados na rocha do **Vale dos Reis**, com o templo funerário longe, na planície.',
    '**Uma diplomacia:** o Egito fala de igual para igual com Babilónia, Mitani, Hatti e Assíria, trocando cartas, presentes e princesas, como mostram as **cartas de Amarna**.'
  ] },
  { h: 'Porque importa' },
  { lista: [
    '**É o Egito que toda a gente conhece:** Tutankhamon, Nefertiti, Ramsés II, Hatshepsut, o Vale dos Reis, Karnak e Abu Simbel são todos do Reino Novo.',
    '**Uma «revolução»:** Akhenaton tentou impor um único deus, o Aton, séculos antes da religião monoteísta tal como a conhecemos. O seu reinado é um dos mais debatidos de toda a História.',
    '**Uma sociedade bem documentada:** a aldeia dos artífices de Deir el-Medina deixou-nos milhares de papéis e cacos escritos com cartas, contas, processos e a primeira greve de que há registo.',
    '**O fim de um mundo:** a crise do fim da Idade do Bronze (c. 1200 a.C.) derrubou impérios inteiros, e o Egito de Ramsés III foi dos poucos a resistir.'
  ] },
  { img: 'eni-abu-simbel', leg: 'Fachada do Grande Templo de Abu Simbel.' },
  { h: 'Como sabemos' },
  'As fontes são abundantes. Há **inscrições monumentais** nas paredes dos templos (os Anais de Tutmés III em Karnak, as batalhas de Ramsés II e de Ramsés III), **túmulos pintados** de funcionários em Tebas, **papiros e óstracos** (pedaços de calcário ou cerâmica escritos) de Deir el-Medina, os **arquivos diplomáticos de Amarna** e cerca de dois séculos de escavações. As fontes para os Hicsos são muito mais pobres, e muitas vezes escritas por inimigos: em parte, o que sabemos deles vem de uma visão egípcia (e mais tarde grega) já hostil.',
  'O Reino Novo também tem os seus silêncios. As fontes oficiais mostram sobretudo vitórias, e nenhuma inscrição de um faraó admite derrotas. Por isso, e para comparar versões, os arqueólogos usam também as cartas dos vassalos e dos reis estrangeiros, e os textos hititas, que dão uma versão diferente de Kadesh.',
  { caixa: 'O Reino Novo hoje', texto: 'Os sítios deste período estão entre os mais visitados do mundo: **Tebas** (Karnak, Luxor, o Vale dos Reis, Deir el-Bahari) foi inscrita na lista do Património Mundial da UNESCO em 1979, e **Abu Simbel** faz parte do conjunto dos monumentos da Núbia, de Abu Simbel a Filas, também Património Mundial. O túmulo de Tutankhamon e os seus tesouros, hoje no Grande Museu Egípcio (Gizé), continuam a ser a descoberta arqueológica mais famosa do mundo.' },
  { img: 'eni-mascara-tutankhamon', leg: 'Máscara funerária de ouro de Tutankhamon, fotografada no Grande Museu Egípcio, Gizé.' }
];

const linha = [
  'Esta linha segue os acontecimentos principais de c. 1650 a 1069 a.C. As datas são as de Shaw (2000); para os reis anteriores a Ahmés I são aproximadas. Para a vida dos faraós em pormenor, veja a página «Os faraós».',
  { linha: [
    { d: 'c. 1650 a.C.', t: 'O Egito divide-se', x: 'O poder dos reis da dinastia XIII, que governavam a partir da região de Mênfis, enfraquece. Chefes de origem asiática (do Levante), instalados desde há gerações no Delta oriental, tomam o poder na cidade de **Avaris** e formam a **dinastia XV**, a dos Hicsos. No sul, uma dinastia local (XVI) governa a partir de Tebas.' },
    { d: 'c. 1650 – 1550 a.C.', t: 'Os Hicsos em Avaris', x: 'O nome *Hicsos* vem do egípcio *heqa-khasut*, «governantes de terras estrangeiras». Os seus reis (Khayan, **Apepi** e outros) usam títulos e escrita egípcios mas mantêm elementos cananeus, como o culto do deus Seth, identificado com o deus da tempestade Baal. Comerciam com o Levante, com Chipre e com o mundo egeu, e fazem aliança com o reino de **Kerma**, na Núbia.' },
    { d: 'c. 1555 a.C.', t: 'A morte de Seqenenré Tao', x: 'Um rei tebano, **Seqenenré Tao**, é morto, com toda a probabilidade num combate ou numa execução: a sua múmia, encontrada em 1881, tem feridas graves na cabeça. Uma história egípcia tardia conta uma disputa entre ele e o rei Hicso Apepi (o *Conto de Apófis e Seqenenré*), mas é uma narrativa, não um relato histórico.' },
    { d: 'c. 1555 – 1550 a.C.', t: 'Kamose ataca', x: '**Kamose**, o último rei da dinastia XVII, ataca para norte e leva os seus barcos até perto de Avaris. As suas duas estelas, em Karnak, contam a campanha. Kamose morre pouco depois, e o seu irmão (ou filho: é debatido) **Ahmés I** continua a guerra.' },
    { d: 'c. 1550 a.C.', t: 'Ahmés I expulsa os Hicsos', x: 'Ahmés I toma **Avaris** e depois, segundo um dos seus oficiais, também Sharuhen, no sul da Palestina, após um cerco de três anos. Ao reunificar o país funda a **dinastia XVIII**. O oficial **Ahmés, filho de Ibana**, conta no seu túmulo em El-Kab as batalhas de que participou, e é uma das nossas melhores fontes.' },
    { d: 'c. 1525 – 1504 a.C.', t: 'Amenófis I e Ahmés-Nefertari', x: 'Amenófis I e a sua mãe, a rainha **Ahmés-Nefertari**, consolidam o reino. O casal vem a ser venerado pelos artífices de Deir el-Medina como protetores da aldeia. Amenófis I faz campanhas na Núbia e na Líbia e constrói em Karnak.' },
    { d: 'c. 1504 – 1492 a.C.', t: 'Tutmés I leva o império ao Eufrates', x: 'Tutmés I avança pelo Levante até ao Eufrates e pela Núbia até muito para sul. O seu arquiteto **Ineni** fala-nos das obras em Karnak. Nesta época começa a tradição dos túmulos reais no Vale dos Reis (qual foi o primeiro é debatido).' },
    { d: 'c. 1479 – 1458 a.C.', t: 'Hatshepsut', x: 'Depois da morte do seu marido Tutmés II, **Hatshepsut** governa primeiro como regente do jovem Tutmés III e, por volta do ano 7, assume o título de rei. O seu reinado é pacífico e próspero. Constrói o templo de **Deir el-Bahari** e, c. 1471 a.C., envia uma expedição marítima à terra de **Punt**.' },
    { d: '1457 a.C.', t: 'A batalha de Megiddo', x: 'Já como único rei, **Tutmés III** derrota em Megiddo, no ano 23, uma coligação de príncipes cananeus chefiada pelo rei de Kadesh. Segue-se um cerco de cerca de sete meses. É a primeira batalha da História de que temos um relato pormenorizado, gravado nas paredes de Karnak.' },
    { d: 'c. 1458 – 1425 a.C.', t: 'O império de Tutmés III', x: 'Ao longo de cerca de dezassete campanhas, Tutmés III faz do Levante uma província egípcia e atravessa o Eufrates, derrotando o reino de **Mitani**. A Núbia é controlada até à quarta catarata. É o maior território que o Egito alguma vez controlou. Depois dele, o faraó Amenófis II e Tutmés IV mantêm-no, mais pela diplomacia do que pela guerra.' },
    { d: 'c. 1390 – 1352 a.C.', t: 'Amenófis III e o apogeu', x: 'Um reinado de paz, riqueza e diplomacia. **Amenófis III** constrói em todo o Egito (Luxor, Soleb, o palácio de Malkata, os «Colossos de Mêmnon») e troca cartas e presentes com os reis de Babilónia, Mitani e Hatti. A sua esposa principal, **Tiy**, tem grande influência.' },
    { d: 'c. 1352 – 1347 a.C.', t: 'Akhenaton e o Aton', x: 'O filho de Amenófis III, **Amenófis IV**, eleva o disco solar **Aton** acima dos outros deuses e, c. 1348 a.C., muda o seu nome para **Akhenaton**. No ano 5 funda uma capital nova, **Akhetaton** (hoje Amarna), a meio caminho entre Mênfis e Tebas. Do seu arquivo diplomático sobrevivem as cerca de 380 **cartas de Amarna**, escritas em acádio.' },
    { d: 'c. 1336 a.C.', t: 'O fim de Amarna', x: 'Akhenaton morre no ano 17. Segue-se um período obscuro, com um ou dois reinados curtos (**Smenkhkaré** e/ou **Neferneferuaton**, entre os quais pode estar Nefertiti: é debatido). Sobe ao trono um rapaz de uns 8 a 10 anos, **Tutankhaton**, que logo muda o nome para **Tutankhamon** e restaura os cultos tradicionais; a corte volta a Tebas.' },
    { d: 'c. 1327 a.C.', t: 'Morte de Tutankhamon', x: 'Tutankhamon morre com cerca de 18 ou 19 anos e é enterrado num túmulo pequeno, que se mantém quase intacto até 1922. Sobe ao trono o idoso **Ay**. Uma carta hitita, que se pensa ser de uma rainha egípcia viúva (talvez Ankhesenamon, mas é debatido), pede um príncipe hitita para marido; o príncipe é morto a caminho do Egito.' },
    { d: 'c. 1323 – 1295 a.C.', t: 'Horemheb', x: 'O general **Horemheb**, antigo chefe do exército de Tutankhamon, torna-se rei, restaura a ordem e publica um edito contra a corrupção. Apaga o nome de Akhenaton das listas oficiais e reutiliza as pedras dos seus templos. Sem filhos, nomeia como sucessor o vizir **Ramsés I**.' },
    { d: 'c. 1294 – 1279 a.C.', t: 'Seti I', x: 'Dinastia XIX. **Seti I** reconquista terras no Levante, constrói o grande templo de Abidos e começa a sala hipostila de Karnak. O seu túmulo (KV17) é o mais belo e mais longo do Vale dos Reis até então.' },
    { d: 'c. 1274 a.C.', t: 'A batalha de Kadesh', x: 'No ano 5 de **Ramsés II**, o exército egípcio enfrenta o hitita de **Muwatalli II** junto à cidade síria de Kadesh. O faraó escapa de uma emboscada e declara-se vencedor em todos os seus templos; os hititas fazem o mesmo. Hoje vê-se como um **empate** que deixou Kadesh nas mãos dos hititas.' },
    { d: 'c. 1259 a.C.', t: 'O tratado de paz', x: 'No ano 21 de Ramsés II, ele e o rei hitita **Hattusili III** assinam um tratado de paz e de ajuda mútua, de que se conservam cópias em egípcio e em acádio. É um dos mais antigos tratados de paz de que se conhece o texto. Mais tarde o rei casa com uma princesa hitita.' },
    { d: 'c. 1264 – 1244 a.C.', t: 'Abu Simbel', x: 'Ramsés II manda escavar na rocha, na Núbia, o **Grande Templo** de Abu Simbel e o templo pequeno da rainha **Nefertari**. Funda também a nova capital do Delta, **Pi-Ramessés**. Reinou 66 anos e teve mais de cem filhos.' },
    { d: 'c. 1213 – 1203 a.C.', t: 'Merneptah e os Líbios', x: 'O seu filho **Merneptah** derrota uma invasão de líbios e de «Povos do Mar» (c. 1208 a.C.). A sua «Estela de Israel» é o mais antigo texto egípcio a mencionar o nome de **Israel**, como um povo (não uma cidade ou um reino). A seguir há uma sequência de reis fracos e disputados (Amenmesse, Seti II, Sipta) e uma rainha, **Tauosret**.' },
    { d: 'c. 1186 – 1153 a.C.', t: 'Ramsés III e os Povos do Mar', x: 'Depois de uma guerra civil, **Setnakht** funda a dinastia XX. O seu filho **Ramsés III** enfrenta duas invasões de líbios e, c. 1177 a.C. (ano 8), a grande ameaça dos **Povos do Mar**, que tinham arrasado o império hitita e as cidades da Síria. Derrota-os em terra e no Delta, e relata-o em Medinet Habu.' },
    { d: 'c. 1158 a.C.', t: 'A primeira greve registada', x: 'No ano 29 de Ramsés III, os artífices de **Deir el-Medina**, sem receberem as rações de cereal, param o trabalho e marcham até aos templos de Tebas. É o primeiro movimento coletivo de trabalhadores de que há registo detalhado.' },
    { d: 'c. 1155 a.C.', t: 'A conspiração do harém', x: 'Ramsés III é vítima de uma conspiração organizada por uma esposa secundária, **Tiy**, para colocar o seu filho **Pentaweret** no trono. Os conspiradores são julgados (o *Papiro Judicial de Turim*), mas a múmia do rei tem um golpe fatal no pescoço, o que indica que o rei foi mesmo morto.' },
    { d: 'c. 1155 – 1069 a.C.', t: 'Ramsés IV a XI e o declínio', x: 'Oito reis chamados **Ramsés** sucedem-se, com poder cada vez menor. As cheias falham, os preços sobem, os roubos de túmulos reais multiplicam-se (os papiros Abbott e Amherst contam os processos, c. 1110 a.C.), a Núbia e o Levante perdem-se. Em Tebas, o Sumo Sacerdote de Amon torna-se quase tão poderoso como o rei.' },
    { d: 'c. 1069 a.C.', t: 'O fim do Reino Novo', x: 'Com a morte de **Ramsés XI**, o país divide-se: um rei, **Smendes**, governa do Delta a partir de Tânis, enquanto os sacerdotes de Amon dominam o sul. Começa o 3.º Período Intermédio (veja a página «3.º Intermédio e Época Tardia»).' }
  ] },
  { img: 'eni-estela-kamose', leg: 'Estela de Kamose com o relato da guerra contra os Hicsos, Museu de Luxor.' },
  { img: 'eni-cerco-megiddo', leg: 'Cerco de Megiddo pelo exército de Tutmés III, c. 1457 a.C. Ilustração gerada por IA.' },
  { img: 'eni-carta-amarna', leg: 'Carta de Amarna de Shipti-Baal, governante de Laquis, em acádio, século XIV a.C.; Museu Britânico ME 29848, EA 330.' },
  { img: 'eni-povos-do-mar', leg: 'Cópia gráfica do relevo da batalha de Ramsés III contra os Povos do Mar, Medinet Habu.' }
];

const mapa = [
  'O Egito do Reino Novo é, ao mesmo tempo, o vale do Nilo e um império. Em casa estão as grandes capitais e templos, entre Mênfis e Elefantina; fora dela, as fortalezas da Núbia e os governadores do Levante. As cidades e sítios que se seguem são os mais importantes desta época.',
  { img: 'eni-mapa-hicsos', leg: 'Mapa do início do período hicso: divisão política do Egito e reino de Cuxe/Kerma; legendas em português.' },
  { tabela: { cab: ['Cidade ou sítio', 'Deus ou função', 'Local hoje', 'Para que ficou conhecido'], linhas: [
    ['Avaris', 'Seth (Baal); capital dos Hicsos', 'Tell el-Dab’a, Delta oriental', 'Capital dos Hicsos; cidade de comércio com o Levante e o Egeu; cercada por Ahmés I'],
    ['Tebas', 'Amon-Rá, Mut, Khonsu', 'Luxor', 'Capital religiosa e frequentemente política do Reino Novo'],
    ['Karnak', 'Amon-Rá', 'Luxor (margem leste)', 'O maior complexo de templos do Egito'],
    ['Templo de Luxor', 'Amon-Rá (aspeto de Amenemope)', 'Luxor', 'Destino da festa de Opet; templo de Amenófis III e de Ramsés II'],
    ['Deir el-Bahari', 'Amon; Hathor', 'Margem oeste de Tebas', 'Templo de Hatshepsut; templo de Mentuhotep II'],
    ['Vale dos Reis', 'Necrópole real', 'Margem oeste de Tebas', 'Túmulos de Tutmés III, Seti I, Ramsés II, Tutankhamon…'],
    ['Deir el-Medina', 'Aldeia dos artífices dos túmulos', 'Margem oeste de Tebas', 'Cartas, processos e a primeira greve registada'],
    ['Medinet Habu', 'Templo funerário de Ramsés III', 'Margem oeste de Tebas', 'Relevos dos Povos do Mar'],
    ['Mênfis', 'Ptah', 'Mit Rahina, perto do Cairo', 'Capital administrativa e base militar do império'],
    ['Pi-Ramessés', 'Capital de Ramsés II', 'Qantir, Delta oriental', 'Residência real e base para as campanhas na Síria'],
    ['Akhetaton', 'Aton', 'Tell el-Amarna', 'Capital de Akhenaton; cartas de Amarna; busto de Nefertiti'],
    ['Abidos', 'Osíris', 'Abydos', 'Templo de Seti I e a Lista dos Reis; centro de peregrinação'],
    ['Elefantina', 'Khnum, Satet, Anuket', 'Assuão', 'Fronteira sul; comércio com a Núbia'],
    ['Buhen e Semna', 'Fortalezas', 'Sudão (a segunda catarata)', 'Fortes da Núbia herdados do Reino Médio'],
    ['Napata (Gebel Barkal)', 'Amon', 'Karima, Sudão', 'Limite sul do império de Tutmés III'],
    ['Abu Simbel', 'Rá-Horakhty; Hathor', 'Sul de Assuão', 'Templos rupestres de Ramsés II e de Nefertari'],
    ['Gaza', 'Capital da província de Canaã', 'Faixa de Gaza', 'Base militar e administrativa do Levante'],
    ['Megiddo', 'Cidade cananeia', 'Tel Megiddo, Israel', 'Batalha de Tutmés III, 1457 a.C.'],
    ['Kadesh', 'Cidade síria', 'Tell Nebi Mend, Síria', 'Batalha de Ramsés II contra os hititas'],
    ['Punt', 'Terra do incenso', 'Costa do Mar Vermelho (Sudão/Eritreia?)', 'Destino de expedições de Hatshepsut']
  ] } },
  { h: 'Avaris (Tell el-Dab’a)' },
  'A capital dos Hicsos ficava num braço oriental do Nilo, hoje seco, perto da atual Qantir. As escavações, dirigidas por **Manfred Bietak** a partir de 1966, mostram uma cidade grande, com casas e túmulos de estilo cananeu (túmulos de cavalos incluídos), cerâmica de todo o Mediterrâneo oriental e, num palácio, **frescos de estilo minoico** (com «saltadores de touros»), que só se explicam por contactos estreitos com o mundo egeu. Os arqueólogos continuam a discutir a sua datação (se são da época dos Hicsos ou de depois da sua queda).',
  { img: 'eni-tell-el-daba', leg: 'Tell el-Dab’a, antiga Avaris: vista do tell e da paisagem atual, com cemitério e povoação modernos.' },
  { img: 'eni-avaris-reconstrucao', leg: 'Reconstrução conjetural de Avaris no tempo dos Hicsos, c. 1600 a.C.; os frescos minoicos não são representados por terem cronologia discutida. Ilustração gerada por IA.' },
  { h: 'Tebas (Luxor)' },
  'A «cidade de Amon» foi, ao longo do Reino Novo, o coração do país. Na margem leste, a cidade dos vivos, ficavam os templos de **Karnak** e de **Luxor**; na margem oeste, a cidade dos mortos, o **Vale dos Reis**, o Vale das Rainhas, os templos funerários e as aldeias de artífices. A ligação entre as duas margens era a vida do rio: as procissões, os cortejos funerários e a «Bela Festa do Vale» atravessavam-no todos os anos. Os gregos chamaram-lhe «Tebas» e Homero fala-lhe como a cidade das «cem portas».',
  { h: 'Karnak' },
  'O recinto de **Amon-Rá** foi crescendo durante mais de dois mil anos, mas é o Reino Novo que lhe dá a escala atual: pilones de Amenófis III, Horemheb e Ramsés II, obeliscos de Tutmés I e de Hatshepsut e, no centro, a **sala hipostila** de Seti I e Ramsés II, com 134 colunas (as doze do corredor central têm cerca de 21 m). As paredes guardam os Anais de Tutmés III e as batalhas de Seti I e Ramsés II. Os templos de Akhenaton ao Aton foram desmantelados depois da sua morte: as suas pedras (as *talatat*) foram reutilizadas como enchimento dos pilones e são hoje recuperadas.',
  { img: 'eni-karnak-reconstrucao', leg: 'Reconstrução artística do templo de Amon-Rá em Karnak, no tempo de Ramsés II, c. 1250 a.C. Ilustração gerada por IA.' },
  { h: 'Luxor' },
  'O templo de Luxor, ligado a Karnak por uma avenida de esfinges de cerca de 2,7 km, foi iniciado por Amenófis III e ampliado por Ramsés II, que lhe acrescentou o grande pátio e o primeiro pilone, com um só dos dois obeliscos originais: o outro está hoje em Paris, na Praça da Concórdia, oferecido por Mehmet Ali em 1830 e erguido em 1836.',
  { h: 'Deir el-Bahari' },
  'O templo funerário de Hatshepsut, de terraços e colunatas, foi construído encostado a uma parede de rocha, ao lado do templo mais antigo de Mentuhotep II. Os relevos mostram a expedição a **Punt**, o nascimento divino da rainha e o transporte dos obeliscos. A autoria do projeto é discutida: costuma atribuir-se a **Senenmut**, mas não há provas seguras. A rainha foi mais tarde apagada das paredes, e muitas estátuas foram partidas e enterradas.',
  { img: 'eni-deir-el-bahari', leg: 'Templo funerário de Hatshepsut, Deir el-Bahari.' },
  { h: 'O Vale dos Reis' },
  'Os faraós da dinastia XVIII e seguintes deixam de construir pirâmides e escolhem um vale seco, dominado por um pico em forma de pirâmide natural, onde escavam os túmulos. Foram identificados mais de **60 túmulos** (numerados KV1 a KV65 e depois), nem todos de reis. Estão decorados com textos funerários (o *Amduat*, o *Livro das Portas*) e, nos mais tardios, com o *Livro dos Mortos*. Em 1922, Howard Carter encontrou o de Tutankhamon (KV62), e em 1995 foi reconhecido o enorme **KV5**, dos filhos de Ramsés II.',
  { img: 'eni-vale-reis', leg: 'Vista geral do Vale dos Reis, Tebas Ocidental.' },
  { h: 'Deir el-Medina' },
  'A aldeia dos artífices que escavavam e decoravam os túmulos reais, atrás da colina de Tebas Ocidental, existiu por cerca de 450 anos. Tinha à volta de 60 casas, um templo de Hathor e uma necrópole própria, com túmulos pintados (de Sennedjem, de Inherkhau…). É o sítio onde melhor conhecemos a vida de gente comum no Egito, graças a milhares de óstracos e papiros: cartas, receitas médicas, contas, processos e queixas.',
  { h: 'Medinet Habu e o Ramesseum' },
  'O templo funerário de **Ramsés III** em Medinet Habu, quase intacto, tem nas paredes a mais completa narração de batalhas do Egito, incluindo a luta contra os Povos do Mar, em terra e no Delta. O **Ramesseum**, o templo funerário de Ramsés II, tem os restos de uma estátua colossal que inspirou o poema *Ozymandias*, de Shelley (1818).',
  { img: 'eni-medinet-habu', leg: 'Primeiro pilone do templo funerário de Ramsés III, Medinet Habu, Tebas.' },
  { h: 'Mênfis' },
  'Mênfis, a capital do Reino Antigo, continuou a ser um grande centro do reino: sede do vizir do Norte, dos arsenais e da frota, com um templo de Ptah de enormes dimensões. Amenófis II, que aí passou a juventude, e outros reis fizeram dela a base dos exércitos que partiam para a Ásia. Muito pouco do que lá existiu se conserva hoje, porque foi destruído e reutilizado.',
  { h: 'Pi-Ramessés' },
  'A «Casa de Ramsés, Grande de Vitórias», a capital que Ramsés II fundou no Delta oriental, ao pé da velha Avaris, era uma cidade de palácios, templos, quartéis, oficinas de carros e estaleiros. Foi abandonada quando o ramo do Nilo em que ficava secou (c. 1100 a.C.) e os seus monumentos foram levados para Tânis. A cidade vem referida na Bíblia («Ramessés», Êxodo 1:11), mas isso não é prova histórica do Êxodo.',
  { img: 'eni-pi-ramses', leg: 'Reconstrução artística de Pi-Ramesses no Delta oriental, c. 1250 a.C. Ilustração gerada por IA.' },
  { h: 'Akhetaton (Amarna)' },
  'Akhenaton fundou a sua cidade num sítio virgem, numa baía semicircular de falésias na margem leste do Nilo, a meio caminho entre Mênfis e Tebas. Teve palácios, o Grande Templo do Aton (aberto ao céu), bairros de casas, oficinas (onde se encontrou o busto de Nefertiti), um bairro de operários e túmulos nos penhascos. Foi construída em poucos anos e abandonada pouco depois da morte do rei.',
  { img: 'eni-amarna-ruinas', leg: 'Ruínas de Akhetaton, Tell el-Amarna.' },
  { h: 'Abidos' },
  'Cidade de Osíris, era o grande lugar de peregrinação do Egito. **Seti I** construiu aí um templo notável, com a famosa **Lista dos Reis de Abidos**, em que o rei e o seu filho, o futuro Ramsés II, prestam homenagem a 76 antepassados. A lista omite de propósito Hatshepsut, os reis de Amarna e os Hicsos. Atrás do templo fica o Osireion, um cenotáfio de Seti I.',
  { h: 'Elefantina e a Núbia' },
  'A ilha de Elefantina, junto à primeira catarata (Assuão), era a porta do Sul. Para lá dela, os faraós do Reino Novo controlaram a Núbia até à quarta catarata, com governadores (o «Filho do rei de Kush»), fortalezas e templos. Foram os egípcios que construíram **Soleb** (Amenófis III), **Gebel Barkal** (junto de Napata) e **Abu Simbel** (Ramsés II). A Núbia fornecia **ouro**, escravos, ébano e soldados (os medjai).',
  { h: 'O Levante' },
  'No Levante, o Egito não criou verdadeiras províncias à maneira romana. Governava por meio de **reis-vassalos** locais (os cananeus, cujas cartas conhecemos), com governadores egípcios em Gaza e noutras cidades e guarnições nas estradas. Os príncipes pagavam tributo e davam cavalos, madeira e filhos como reféns, que eram educados na corte egípcia. Entre as cidades principais: **Gaza, Jaffa, Megiddo, Beth Shean, Kumidi, Byblos e Kadesh**.',
  { h: 'Punt' },
  'Terra de onde vinha o incenso, a mirra e o ébano, ficava no sul do Mar Vermelho (Sudão oriental, Eritreia ou ambos: é discutido). Foi para lá que Hatshepsut enviou cinco navios, c. 1471 a.C. (ano 9).',
  { h: 'As rotas' },
  { lista: [
    '**O Nilo:** a «estrada» principal. As cheias anuais definiam o calendário, e tudo se movia de barco, a favor da corrente para norte e à vela para sul, com o vento do norte.',
    '**A Via de Hórus:** a rota militar costeira que ligava o Delta a Gaza, cruzando o Sinai, com fortalezas e poços ao longo de toda a estrada.',
    '**O Uadi Hammamat e o Mar Vermelho:** estrada entre o vale do Nilo e o porto do Mar Vermelho (Mersa Gawasis), de onde partiam as expedições a Punt.',
    '**As rotas do deserto:** estradas de caravanas para as minas de ouro da Núbia e para os oásis ocidentais.'
  ] }
];

const sociedade = [
  { h: '1. Organização política' },
  'O Egito do Reino Novo era uma **monarquia divina**: o faraó era filho de Amon-Rá, garante da ordem do universo (a *Maat*) e chefe supremo do exército. A sucessão era em regra de pai para filho, mas as rainhas tinham um papel importante, e houve mulheres reis (Hatshepsut e, mais tarde, Tauosret). A partir de Tutmés III, o faraó aparece também como «herói» guerreiro: monta em carro, mata leões e esmaga os inimigos.',
  'A administração era dirigida por **dois vizires** (um para o Norte, um para o Sul, em Tebas), que eram juízes supremos e chefes da administração; **tesoureiros**, **superintendentes dos celeiros** e **governadores** (os «prefeitos») das cidades; e, na Núbia, o **vice-rei de Kush**. No Levante havia reis-vassalos e guarnições. Um exército permanente e uma burocracia de escribas mantinham tudo isto a funcionar.',
  { cit: 'Para que ordem no mundo se mantenha: tenho restaurado o que estava destruído, erguido o que estava desfeito, desde que os asiáticos estavam no meio de Avaris, no Norte.', fonte: 'Inscrição de Hatshepsut no Speos Artemidos (tradução aproximada; a «restauração» de que ela se gaba é, em parte, propaganda)' },
  { h: '2. Os Hicsos: factos e mitos' },
  'Os Hicsos não foram uma «invasão» súbita, como contaram Manethon e Flávio Josefo (que os chama «reis pastores», por erro de tradução). A arqueologia mostra que cananeus, ou semitas ocidentais, se instalaram no Delta oriental ao longo de gerações, como comerciantes, soldados e artífices, e que os seus chefes acabaram por tomar o poder local quando o reino da dinastia XIII se desfez. Governaram com títulos egípcios e adotaram a escrita egípcia. O *Papiro Matemático de Rhind*, a mais famosa obra de matemática egípcia, foi copiado no seu reinado, no ano 33 de Apepi (c. 1550 a.C.), por um escriba chamado Ahmés.',
  { lista: [
    '**Carros e cavalos:** costuma dizer-se que os Hicsos trouxeram o cavalo e o carro de guerra, mas é debatido. O cavalo aparece de facto no Delta nesta época, mas o carro de guerra só aparece nos textos e nas imagens egípcias no início da dinastia XVIII.',
    '**Arco composto, armas de bronze, novas cerâmicas e o tear vertical:** são inovações do Levante que entraram no Egito neste período. Quanto de tudo isto veio com os Hicsos e quanto de contactos mais amplos é discutido.',
    '**Os Hicsos não se confundem com os israelitas:** a ideia, que vem de Josefo, de que a sua expulsão é o «Êxodo» da Bíblia não tem provas, e a maior parte dos historiadores rejeita-a.'
  ] },
  { cit: 'Para que sirvo eu, que conheço a minha força? Há um chefe em Avaris, outro em Kush, e eu estou sentado com um asiático e um núbio! Cada um tem o seu pedaço deste Egito.', fonte: 'Estela de Kamose (tradução aproximada)' },
  { h: '3. Classes sociais' },
  'A sociedade era uma pirâmide. No topo, o **faraó** e a família real. Abaixo, uma elite de **altos funcionários, sacerdotes e oficiais**, muitas vezes ligados por casamento. Depois, os **escribas** (a categoria que mais se aproximava do poder), os **soldados de carro** e os **artesãos**, entre os quais os especialistas de Deir el-Medina, bem pagos. A grande maioria eram **camponeses**, ligados à terra do Estado, de um templo ou de um senhor; havia também **servos e escravos**, na maioria prisioneiros de guerra e estrangeiros, sobretudo núbios e asiáticos.',
  'Era possível subir: muitos oficiais de origem modesta chegaram a vizires, e o general **Horemheb** e o vizir **Ramsés I** chegaram a faraós. Mas a ascensão fazia-se sempre através de uma ligação ao palácio.',
  { h: '4. Religião' },
  'No Reino Novo, os deuses antigos continuam a ser venerados, mas um deles passa a primeiro lugar: **Amon**, o deus escondido de Tebas, fundido com o deus Sol em **Amon-Rá**, «Rei dos Deuses». Os faraós atribuem-lhe as suas vitórias e oferecem-lhe uma parte dos despojos, terras e escravos, o que fez crescer enormemente os templos e os seus sacerdotes. Para os pormenores gerais da religião egípcia, veja a página «Deuses, escrita e vida quotidiana».',
  { tabela: { cab: ['Deus', 'Domínio', 'Papel no Reino Novo'], linhas: [
    ['Amon-Rá', 'Rei dos deuses, sol', 'Deus do império; templo de Karnak; oráculos'],
    ['Mut e Khonsu', 'Esposa e filho de Amon', 'A tríade tebana; templo de Mut em Karnak'],
    ['Aton', 'O disco solar', 'Único deus oficial no tempo de Akhenaton'],
    ['Osíris', 'Morte e renascimento', 'Juiz dos mortos; centro em Abidos'],
    ['Ptah', 'Criador, artífices', 'Deus de Mênfis, com Sekhmet e Nefertum'],
    ['Seth', 'Deserto, tempestade, estrangeiros', 'Deus de Avaris (com Baal) e padroeiro dos Ramessidas, cujo nome vem dele (Seti)'],
    ['Hathor', 'Amor, música, mortos', 'Protetora dos mortos e dos artífices; templos em Deir el-Bahari, Deir el-Medina e Abu Simbel'],
    ['Anúbis', 'Embalsamamento', 'Guia dos mortos'],
    ['Maat', 'Ordem, verdade', 'O princípio que o faraó deve manter'],
    ['Taweret e Bes', 'Protetores do parto e do lar', 'Muito populares nas casas']
  ] } },
  { img: 'eni-festa-opet', leg: 'Procissão da festa de Opet em Tebas, c. 1300 a.C., com a barca sagrada de Amon. Ilustração gerada por IA.' },
  { lista: [
    '**A festa de Opet:** todos os anos, na época das cheias, a estátua de Amon, as de Mut e de Khonsu eram levadas em barcas, do templo de Karnak ao de Luxor, entre multidões. A festa chegou a durar quase um mês, e era uma renovação do poder do rei.',
    '**A Bela Festa do Vale:** a imagem de Amon visitava os templos funerários da margem oeste, e as famílias iam aos túmulos, comiam e bebiam e recordavam os seus mortos.',
    '**Oráculos:** a estátua do deus, levada pelos sacerdotes, «respondia» a perguntas movendo-se para a frente ou para trás. Foi um oráculo de Amon que, segundo Hatshepsut, a escolheu para reinar.'
  ] },
  { h: '5. A «revolução» de Amarna' },
  'No quinto ano do seu reinado, o rei **Amenófis IV** tornou-se **Akhenaton** («o que serve o Aton»). O **Aton** era o disco solar, representado com raios que terminam em mãos que abençoam. Akhenaton fechou os templos de outros deuses, em especial os de Amon, apagou o seu nome, construiu uma nova capital, e mudou a arte: as figuras reais passaram a ter rostos alongados, corpos de formas estranhas e cenas de família íntimas. O **Grande Hino ao Aton**, atribuído ao rei, tem semelhanças com o Salmo 104 da Bíblia, mas a relação entre ambos é discutida.',
  { lista: [
    '**Monoteísmo?** Muitos historiadores falam de uma religião **monolátrica** (só se adora um deus) e não de um verdadeiro monoteísmo: o rei e a família continuavam a ser divinos, e o povo adorava o rei e a rainha como mediadores do Aton.',
    '**Akhenaton e Moisés:** a ideia (de Freud, entre outros) de que Moisés foi influenciado por Akhenaton não tem base histórica nem arqueológica.',
    '**O fim:** com a morte do rei, o seu culto foi abandonado. Tutankhamon restaurou os deuses antigos (na «Estela da Restauração»), Horemheb apagou os nomes dos reis de Amarna e as suas pedras foram reutilizadas. Akhenaton passou a ser «o inimigo de Akhetaton».'
  ] },
  { img: 'eni-amarna-vida', leg: 'Akhenaton, Nefertiti e as filhas venerando Aton em Akhetaton, c. 1345 a.C.; os raios com mãos são um motivo religioso artístico. Ilustração gerada por IA.' },
  { h: '6. Morte e túmulos' },
  'Os faraós do Reino Novo separaram o túmulo do templo. O **túmulo** (hipogeu) era escavado, escondido, no Vale dos Reis; o **templo funerário** (os «templos de milhões de anos») ficava na planície, junto ao rio, e ali se faziam as oferendas ao rei morto, também ligado ao culto de Amon. Os nobres faziam-se enterrar em túmulos de capela pintada na colina de Tebas, onde as cenas da vida (caça, banquetes, colheitas) mostram o ideal do «além» como uma continuação feliz desta vida.',
  { img: 'eni-livro-dos-mortos', leg: 'Pesagem do coração no Papiro de Ani, Museu Britânico, EA 10470.' },
  { lista: [
    '**Os textos nos túmulos reais:** o *Amduat* («O que há no Além») e o *Livro das Portas* descrevem a viagem noturna do Sol pelo mundo dos mortos.',
    '**O Livro dos Mortos:** coleção de fórmulas mágicas escritas em papiros colocados nos túmulos (para os particulares, sobretudo). O seu capítulo 125 descreve o Julgamento de Osíris, com a pesagem do coração contra a pena de Maat.',
    '**Os ushebti:** pequenas estatuetas que, no além, trabalhariam pelo defunto. Tutankhamon tinha 413.',
    '**Roubo de túmulos:** quase todos os túmulos reais foram saqueados ainda na Antiguidade; o de Tutankhamon escapou em grande parte porque foi coberto pelos entulhos do túmulo de Ramsés VI.'
  ] },
  { img: 'eni-enterro-real', leg: 'Procissão funerária real em direção ao Vale dos Reis, c. 1300 a.C. Ilustração gerada por IA.' },
  { h: '7. Economia' },
  'A economia assentava na **agricultura** do vale e do Delta, regada pelas cheias do Nilo, na qual o **cereal** (trigo e cevada) era a base. Não havia moeda: os pagamentos faziam-se em cereal, pão, cerveja, tecido, e peso de cobre ou prata (o *deben*). Os **impostos** eram cobrados em produtos e por escribas, e os **templos** possuíam terras e rebanhos enormes, em especial o de Amon. A **riqueza do império** vinha do ouro da Núbia, dos tributos da Ásia e de um comércio ativo com o Levante, Chipre e o Egeu, e com Punt.',
  { img: 'eni-navio-punt', leg: 'Navio da expedição de Hatshepsut a Punt, c. 1471 a.C., carregando árvores de mirra e outras mercadorias. Ilustração gerada por IA.' },
  { lista: [
    '**Ouro:** as minas da Núbia davam ouro em abundância, a base da diplomacia. Num texto de Amarna, o rei de Mitani diz que no Egito o ouro «é como pó».',
    '**Cobre e turquesa:** extraídos nas minas do Sinai (Serabit el-Khadim), com um templo a Hathor.',
    '**Madeira e resinas:** cedro do Líbano e incenso e ébano de Punt.',
    '**Estrangeiros no Egito:** havia comerciantes, mercenários e artífices cananeus, núbios, líbios e do Egeu. Os «Povos do Mar» chegaram a servir como mercenários.'
  ] },
  { h: '8. Escrita e língua' },
  'No Reino Novo, a língua falada, o **egípcio tardio**, já não era a do Reino Médio, mas os monumentos continuaram a usar o egípcio clássico, em **hieróglifos**. Os documentos do dia a dia usavam o **hierático** (escrita cursiva) em papiro e em óstracos. Para a diplomacia com o exterior, utilizava-se o **acádio**, em tabuinhas de argila, a língua internacional da época, e as cartas de Amarna mostram que a corte tinha escribas que a dominavam.',
  'Os futuros escribas aprendiam desde crianças, copiando textos, em condições duras. Um texto escolar muito copiado, a *Sátira dos Ofícios*, elogia a profissão de escriba à custa de todas as outras.',
  { h: '9. A casa' },
  'As casas de gente comum eram de tijolo de lama, com o telhado plano de ramos e palha. Nos bairros de Amarna e de Deir el-Medina, vê-se um padrão: uma sala de entrada, uma sala principal com uma coluna ao centro e um altar de família, quartos, uma cozinha e uma escada para o terraço. Os ricos tinham **vilas** com jardim, tanque de água e árvores, como se vê em muitas pinturas de túmulos. Os palácios, como o de Amenófis III em Malkata, tinham pavimentos e paredes pintados.',
  { img: 'eni-casa-novo-imperio', leg: 'Interior conjetural de uma casa de artesão em Deir el-Medina, c. 1250 a.C. Ilustração gerada por IA.' },
  { h: '10. Alimentação' },
  'O pão e a cerveja eram a base. A cerveja era pouco alcoólica e nutritiva, bebida por todos, crianças incluídas. Comia-se também cebola, alho, lentilhas, grão, alface, peixe (seco e salgado), aves e, nas festas, carne de vaca. Os ricos bebiam **vinho**, de que há muitos vestígios, incluindo as ânforas do túmulo de Tutankhamon, com o ano, a vinha e o vinhateiro. Mel e tâmaras eram os doces, e o óleo vinha da moringa e da oliveira.',
  { img: 'eni-nebamun-pesca', leg: 'Nebamun caçando aves nos pântanos: pintura do túmulo, Museu Britânico, EA 37977.' },
  { h: '11. Vestuário, beleza e adornos' },
  'O linho era a roupa de todos os dias. No Reino Novo, os homens ricos passaram a usar túnicas e saiotes de linho plissado e os vestidos das mulheres tornaram-se longos e pregueados. Homens e mulheres usavam **perucas** e pintavam os olhos de **kohl**, que protegia do sol e das moscas. Usavam **joias** de ouro, faiança e pedras. As pinturas dos túmulos da elite tebana mostram festas em que os convidados usam cones de gordura perfumada na cabeça (discute-se se eram reais ou apenas uma convenção da pintura).',
  { h: '12. Música, jogos e diversão' },
  'As festas tinham **harpistas, tocadores de alaúde e flauta, dançarinas e acrobatas**. O alaúde, a lira e o pandeiro vieram da Ásia no Reino Novo. O jogo de tabuleiro mais popular era o **senet**, um jogo do «caminho» do morto, e há outros como o **mehen** e os «20 quadrados». As crianças tinham bolas, piões e bonecas. A **caça** e a **pesca** nos pântanos eram vistos como o prazer ideal das elites.',
  { h: '13. Ciência e medicina' },
  'Dois dos grandes papiros médicos são deste tempo ou foram copiados nele: o **Papiro de Edwin Smith** (de cirurgia de trauma, com casos de lesões descritos com um método quase científico) e o **Papiro Ebers** (c. 1550 a.C., com cerca de 700 receitas e conjuros). A matemática usava frações e a «regra de três», como mostra o papiro de Rhind. Os astrónomos registavam o nascimento de Sírio e os decanos (grupos de estrelas); os **relógios de água** (clepsidras) e os relógios de sombra eram usados para marcar as horas. O «Papiro de Turim» (um mapa de minas) é considerado o mais antigo mapa topográfico conhecido.',
  { h: '14. Tecnologia' },
  { lista: [
    '**Carro de guerra:** leve, de madeira e pele, com duas rodas de seis raios e dois cavalos, conduzido por um cocheiro e um arqueiro. Foi a «arma decisiva» do Reino Novo.',
    '**Arco composto e espada khopesh:** o arco, de madeira, chifre e tendão, tinha maior alcance do que o arco simples.',
    '**Shaduf:** um balde preso a um braço de alavanca, para tirar água do rio. Aparece no Egito no Reino Novo e permitiu irrigar terras mais altas.',
    '**Vidro:** o fabrico de vidro colorido, em objetos moldados, começou no início da dinastia XVIII.',
    '**Metais:** o bronze era comum; o ferro era raro e precioso, como o punhal de Tutankhamon, feito de ferro de meteorito.',
    '**Construção:** pilones, colunas e blocos enormes de pedra, movidos em trenós, com rampas, alavancas e grande mão de obra.'
  ] },
  { h: '15. O exército e a guerra' },
  'Pela primeira vez o Egito teve um **exército profissional**, de duas armas: a **infantaria**, com arqueiros e lanceiros, e os **carros**, a elite dos nobres. A estes juntavam-se mercenários, como os **medjai** núbios e os **Sherden**. O exército marchava em divisões com o nome de deuses (Amon, Rá, Ptah, Seth). A frota fluvial e marítima transportava-o até ao Levante. Os faraós guerreavam na primavera, depois da colheita, e tomavam as cidades por cerco, por assalto ou por traição, como se conta numa história de **Djehuty**, general de Tutmés III, que teria entrado em Jaffa com soldados escondidos em cestos (é um conto, e não história).',
  { img: 'eni-carro-guerra', leg: 'Carros de guerra egípcios do século XIII a.C., com dois cavalos, condutor e arqueiro. Ilustração gerada por IA.' },
  { h: '16. Kadesh e o tratado' },
  'Em 1274 a.C., Ramsés II conduziu quatro divisões contra os hititas junto a Kadesh. Os espiões enganaram-no, e o faraó, com a sua divisão isolada, foi atacado por 2 500 carros hititas, mas resistiu, ajudado pela chegada de reforços. Os relevos de Abu Simbel, do Ramesseum e de Karnak apresentam o rei como o único herói e vencedor, enquanto os arquivos hititas contam outra versão. Em 1259 a.C. as duas potências assinaram o tratado, que ficou gravado no templo de Karnak e em tabuinhas de argila em Hattusa (hoje no Museu Arqueológico de Istambul).',
  { img: 'eni-batalha-kadesh-relevo', leg: 'Relevo da batalha de Kadesh, Ramesseum, Tebas.' },
  { img: 'eni-tratado-kadesh', leg: 'Tabuinha do tratado de Ramsés II e Hattusili III, Museu Arqueológico de Istambul.' },
  { h: '17. Diplomacia: o «clube dos grandes reis»' },
  'No tempo de Amenófis III e de Akhenaton, os soberanos do Egito, da Babilónia, de Mitani, de Hatti e (mais tarde) da Assíria tratavam-se por «irmãos» e trocavam cartas, presentes e noivas. As cartas de Amarna, escritas em acádio, mostram-nos reis a queixar-se da pouca qualidade do ouro recebido, a pedir médicos e escultores e a negociar casamentos. O Egito, curiosamente, **enviava noivas muito raramente**: pedia princesas dos outros mas não as dava, o que era motivo de queixas.',
  { h: '18. Os Povos do Mar' },
  'Por volta de 1200 a.C. uma sequência de crises (secas, guerras, terramotos, a ação de bandos de guerreiros do mar) derrubou os reinos do Bronze Final: Hatti desapareceu, Ugarit foi destruída e as cidades micénicas ruíram. Os egípcios conheciam estes grupos pelos nomes (*Peleset*, *Tjeker*, *Shekelesh*, *Denyen*, *Weshesh*, entre outros) e chamaram-lhes «os Povos do Mar». Ramsés III derrotou-os, em terra e numa batalha naval no Delta, c. 1177 a.C. (ano 8), mas o que são exatamente esses povos e de onde vieram é muito discutido. Os Peleset são, segundo muitos, os **Filisteus** da Bíblia, mas não é certo.',
  { img: 'eni-batalha-naval-delta', leg: 'Interpretação artística da batalha naval de Ramsés III contra os Povos do Mar no Delta, c. 1177 a.C. Ilustração gerada por IA.' },
  { h: '19. Deir el-Medina: a aldeia dos artífices' },
  'Cerca de **60 famílias** de artífices (pedreiros, escultores, desenhadores, pintores e escribas) viviam numa aldeia murada, perto do Vale dos Reis, e trabalhavam ali em duas equipas, a «esquerda» e a «direita», dirigidas por capatazes e escribas. A semana tinha dez dias, oito de trabalho e dois de folga. Eram pagos pelo Estado, em cereal, cerveja, peixe, lenha, legumes, vestuário, e recebiam bónus em festas. Quando as rações atrasaram, no ano 29 de Ramsés III (c. 1158 a.C.), pararam o trabalho e marcharam, a gritar que tinham fome, até aos templos de Tebas, e o vizir mandou distribuir cereal.',
  { img: 'eni-vila-trabalhadores', leg: 'Reconstrução artística da aldeia de Deir el-Medina no tempo de Ramsés II, c. 1250 a.C. Ilustração gerada por IA.' },
  { lista: [
    '**Óstracos:** cartas, listas, esboços, poemas de amor, receitas e desenhos humorísticos, que nos mostram uma comunidade de leitores e escritores.',
    '**Justiça:** havia um tribunal local (*kenbet*), de homens da aldeia, que julgava casos de dívidas, heranças e agressões. As mulheres podiam ser testemunhas, herdar e dispor da sua propriedade.',
    '**Trabalhadores livres, não escravos:** as pirâmides e os túmulos não foram construídos por escravos, como no mito de Heródoto e do cinema, mas por artífices e trabalhadores pagos.'
  ] },
  { h: '20. Mulheres' },
  'As egípcias tinham mais direitos do que as mulheres de quase todas as outras civilizações antigas. Podiam possuir bens, herdar, comprar, vender, apresentar queixa em tribunal e divorciar-se. Havia sacerdotisas, músicas e «Esposas de Deus de Amon», um cargo importantíssimo ocupado por rainhas (Ahmés-Nefertari, Hatshepsut). Algumas rainhas tiveram poder político real: **Tiy**, **Nefertiti**, **Nefertari** e a própria **Hatshepsut**.',
  { h: '21. Crime e castigo' },
  'As penas incluíam a surra, a mutilação, o trabalho forçado, o exílio na Núbia e a morte. Os maiores crimes eram o roubo de túmulos reais e a conspiração. Os papiros **Abbott**, **Amherst** e **Mayer** (c. 1110 a.C.) contam os processos de assaltantes dos túmulos do Vale dos Reis, com interrogatórios sob tortura, e o **Papiro Judicial de Turim** o julgamento da conspiração do harém contra Ramsés III, com muitas condenações à morte, e alguns juízes que foram, eles próprios, punidos por conviverem com os acusados.',
  { h: '22. A arte' },
  'A arte do Reino Novo é colorida, elegante e luxuosa. Os relevos e as pinturas dos túmulos mostram festas, caça, colheitas e o além. Sob Amenófis III e Akhenaton, o estilo fica mais suave e elegante, e depois do «estilo de Amarna» (formas arredondadas, corpos alongados) volta-se a um estilo mais clássico. As estátuas colossais de Ramsés II são símbolo do poder. A oficina do escultor **Tutmés** (Thutmose), em Amarna, produziu os retratos mais celebrados da época, incluindo o busto de **Nefertiti**.',
  { img: 'eni-oficina-escultor', leg: 'Oficina de um escultor real em Akhetaton, c. 1345 a.C., com bustos e cabeças inacabados. Ilustração gerada por IA.' }
];

const personalidades = [
  'As figuras que se seguem são todas reais. Para a vida completa de cada faraó, veja a página «Os faraós». As datas são as de Shaw (2000); os reinados e as identificações mais debatidos vêm assinalados.',
  { h: 'Apepi (Aauserré Apepi), rei Hicso (meados do século XVI a.C.)' },
  'O rei Hicso mais bem conhecido. Reinou pelo menos 33 anos (o Papiro de Rhind foi copiado no seu ano 33) a partir de Avaris, e foi o rival dos reis tebanos. Um conto egípcio tardio, o *Conto de Apófis e Seqenenré*, diz que Apepi se queixava de que os hipopótamos do tanque de Tebas não o deixavam dormir; é uma narrativa, não um facto. O seu nome aparece em objetos de pedra e em selos.',
  { h: 'Kamose (c. 1555 – 1550 a.C.)' },
  'O último rei da dinastia XVII. Nas suas estelas de Karnak conta como os seus conselheiros lhe diziam para ficar quieto, e como ele, «com a minha força», lançou a guerra, atacou o Norte e interceptou uma mensagem de Apepi aos reis de Kush. Morreu pouco depois, sem chegar a libertar Avaris. Não se sabe ao certo se era irmão ou filho de Seqenenré Tao, nem se era irmão ou pai de Ahmés I.',
  { h: 'Ahmés I (c. 1550 – 1525 a.C.)' },
  'Fundador da dinastia XVIII e do Reino Novo. Subiu ao trono ainda criança e completou a guerra contra os Hicsos, que expulsou do Egito e perseguiu até ao sul da Palestina. Depois combateu na Núbia e reorganizou o Estado. A sua múmia foi encontrada no esconderijo de Deir el-Bahari (DB320), em 1881.',
  { h: 'Ahmés-Nefertari (século XVI a.C.)' },
  'Esposa e irmã de Ahmés I, mãe de Amenófis I. Foi a primeira «Esposa de Deus de Amon» com poder real, e depois da morte foi venerada como deusa, sobretudo em Deir el-Medina, onde aparece em pinturas com pele negra, cor do renascimento e da terra fértil do Nilo.',
  { h: 'Hatshepsut (rei c. 1473 – 1458 a.C.; regente desde c. 1479)' },
  'Filha de Tutmés I, esposa de Tutmés II e regente do enteado, o futuro Tutmés III. Por volta do ano 7 do reinado assumiu o título de **rei** e foi representada, nas estátuas, com os atributos masculinos e a barba postiça. Reinou cerca de 15 anos como rei (mais de 20 contando a regência), durante os quais o país prosperou: construiu em Deir el-Bahari e Karnak, e enviou a expedição a Punt. No final do reinado de Tutmés III, os seus nomes e imagens foram apagados em muitos monumentos, mas porquê é discutido (já não se pensa que seja ódio pessoal imediato). Em 2007 identificou-se como sua uma múmia (KV60A), por um dente que encaixava numa caixa com o seu nome, mas a identificação é contestada.',
  { img: 'eni-hatshepsut-estatua', leg: 'Estátua ajoelhada de Hatshepsut em granito, Metropolitan Museum.' },
  { h: 'Senenmut (ativo c. 1479 – 1458 a.C.)' },
  'De origem modesta, chegou a «Grande Mordomo de Amon» e a tutor da princesa Neferuré, filha de Hatshepsut. Esteve ligado à construção de Deir el-Bahari, como supervisor das obras (mas o arquiteto do templo é discutido). Os seus dois túmulos, um deles em Deir el-Bahari, incluem um teto astronómico. Não se sabe se foi amante da rainha, como se disse muitas vezes (não há provas), nem quando e como saiu de cena.',
  { h: 'Tutmés III (c. 1479 – 1425 a.C.)' },
  'O mais famoso faraó guerreiro. Subiu ao trono em criança e reinou 54 anos, mas só governou sozinho a partir de 1458. Fez cerca de 17 campanhas na Ásia, venceu em Megiddo, atravessou o Eufrates e mandou gravar os seus **Anais** em Karnak, a partir do diário de um escriba militar. Mandou também representar em Karnak as plantas e os animais exóticos que trouxe da Síria (o «Jardim Botânico»). A sua múmia está no Cairo. É por vezes chamado «o Napoleão do Egito», uma comparação exagerada.',
  { img: 'eni-tutmes-iii', leg: 'Estátua de Tutmés III em grauvaque, Museu de Luxor.' },
  { h: 'Amenófis III (c. 1390 – 1352 a.C.) e Tiy' },
  'O rei do apogeu. Reinou 38 anos em paz e luxo. Construiu o templo de Luxor, o de Soleb, o palácio de Malkata e o seu templo funerário, de que só restam os colossos (de Mêmnon). Mandou fazer centenas de estátuas da deusa leoa Sekhmet. Casou com a sua esposa principal **Tiy**, filha de gente de fora da família real, cujo nome aparece ao lado do do rei em todos os monumentos, e com princesas de Mitani e da Babilónia. As suas relações com os reinos vizinhos estão registadas nas cartas de Amarna.',
  { img: 'eni-amenofis-iii', leg: 'Cabeça colossal de Amenófis III em granito vermelho, Museu Britânico.' },
  { h: 'Akhenaton (c. 1352 – 1336 a.C.)' },
  'O «rei herético». Filho de Amenófis III e de Tiy, subiu ao trono como Amenófis IV, mas apressou-se a eleger o Aton como deus supremo e a mudar-se para Amarna. Reinou 17 anos. É retratado de forma invulgar, com rosto longo, pescoço fino, ventre e ancas largos: não se sabe se por razões de doença (síndrome de Marfan, que os exames genéticos não confirmaram) ou por escolha artística e religiosa, que é a explicação hoje preferida. Depois da morte foi quase apagado da memória. O seu corpo não foi identificado com certeza: a múmia da tumba KV55 é, talvez, a dele, mas há quem pense que é a de Smenkhkaré.',
  { img: 'eni-akhenaton-colosso', leg: 'Colosso de Akhenaton de Karnak, Museu Egípcio, Cairo.' },
  { h: 'Nefertiti (século XIV a.C.)' },
  'A «Bela que chegou», esposa principal de Akhenaton e mãe de seis filhas. Aparece nos relevos ao lado do rei, na mesma escala, a oferecer ao Aton, e a golpear inimigos, uma imagem até então só do rei. Desaparece das fontes por volta do ano 12–16, e a razão é discutida: pode ter morrido, ter sido deslocada, ou ter reinado como rei, sob o nome de **Neferneferuaton**; não há consenso. A sua tumba nunca foi encontrada, e a hipótese, lançada em 2015, de estar escondida atrás da de Tutankhamon foi afastada por radar em 2018. O busto, do ateliê de Tutmés, está em Berlim.',
  { img: 'eni-nefertiti-busto', leg: 'Busto de Nefertiti, Neues Museum, Berlim.' },
  { h: 'Tutankhamon (c. 1336 – 1327 a.C.)' },
  'Subiu ao trono com 8–10 anos, no final do período de Amarna. O seu nome de nascimento era Tutankhaton, «imagem viva do Aton». Reinou menos de dez anos, durante os quais os ministros (**Ay**, o vizir, e o general **Horemheb**) governaram de facto. Restaurou os deuses antigos. Morreu com cerca de 18–19 anos. Exames genéticos, publicados em 2010, indicam que o pai foi a múmia de KV55 e a mãe a «Jovem Dama» de KV35, ambos filhos de Amenófis III e Tiy; o estudo foi criticado, e a causa da morte (malária, uma fratura na perna, ou ambas) continua a ser discutida. Foi famoso sobretudo pelo seu túmulo, achado em 1922.',
  { h: 'Horemheb (c. 1323 – 1295 a.C.)' },
  'Soldado de carreira, general de Tutankhamon, depois rei. Pôs ordem na administração com um edito contra a corrupção dos funcionários, restaurou os templos, apagou os vestígios de Akhenaton e apropriou-se de monumentos de Tutankhamon e de Ay. Não teve filhos e escolheu como herdeiro o seu vizir **Ramsés I**.',
  { h: 'Seti I (c. 1294 – 1279 a.C.)' },
  'Segundo rei da dinastia XIX. Reconquistou o Levante e abriu a guerra com os hititas, e fez construir em todo o Egito. O seu templo de Abidos e a sala hipostila de Karnak são obras-primas, tal como o seu túmulo (KV17), encontrado por Belzoni em 1817. A sua múmia, notavelmente bem conservada, está no Cairo.',
  { h: 'Ramsés II, «o Grande» (c. 1279 – 1213 a.C.) e Nefertari' },
  'Reinou 66 anos e dominou o seu século. Apresentou Kadesh como uma grande vitória, assinou o tratado de paz, fundou Pi-Ramessés, ergueu o Ramesseum, Abu Simbel e acrescentou os seus nomes a muitos monumentos (por vezes apagando os de outros reis). Teve várias esposas, das quais a mais amada foi **Nefertari**, de túmulo pintado (QV66) e do pequeno templo de Abu Simbel, e mais de cem filhos. Morreu com cerca de 90 anos; a sua múmia foi encontrada em 1881 e foi estudada em Paris em 1976.',
  { img: 'eni-ramses-ii-estatua', leg: 'Estátua sedente de Ramsés II, Museo Egizio, Turim.' },
  { h: 'Ramsés III (c. 1184 – 1153 a.C.)' },
  'O último grande faraó do Reino Novo. Derrotou os líbios e os Povos do Mar e construiu Medinet Habu. O seu reinado ficou marcado por crises: a greve de Deir el-Medina (ano 29) e, no fim, a **conspiração do harém**, em que perdeu a vida. A tomografia da sua múmia, em 2012, mostrou um corte profundo na garganta, que confirma o assassínio. Foi sucedido pelo filho, Ramsés IV.'
];

const legado = [
  { h: 'O que nos deixaram' },
  { lista: [
    '**Os grandes templos e túmulos:** Karnak, Luxor, Abu Simbel, o Vale dos Reis e Medinet Habu são, ainda hoje, as grandes imagens do Egito antigo.',
    '**A diplomacia internacional:** as cartas de Amarna e o tratado de Kadesh são os primeiros testemunhos da diplomacia entre grandes potências.',
    '**O primeiro «monoteísmo» discutido:** a experiência de Akhenaton continua a fascinar historiadores e crentes.',
    '**A história social:** os papiros e óstracos de Deir el-Medina são o melhor retrato de uma comunidade operária da Antiguidade.',
    '**Tecnologia:** o carro, o vidro, o shaduf e o arco composto entraram no Egito neste período e depois passaram a outros povos.'
  ] },
  { h: 'A arte' },
  'A arte do Reino Novo, com os seus ouros, os seus relevos pintados e os rostos suaves de Amenófis III e de Nefertiti, é considerada o ponto mais alto do requinte egípcio. O ouro e as pedras semipreciosas das joias de Tutankhamon, os móveis, as pinturas das tumbas tebanas (como as de **Nebamun**, no Museu Britânico) e os retratos de Amarna são conhecidos no mundo todo.',
  { img: 'eni-trono-tutankhamon', leg: 'Trono dourado de Tutankhamon.' },
  { h: 'A arquitetura' },
  'Os pilones e as salas hipostilas, as avenidas de esfinges e os templos escavados na rocha são o estilo típico do Reino Novo. Fizeram-se com blocos de arenito e de calcário, elevados com rampas de tijolo, e depois pintados em cores vivas, de que restam apenas vestígios. O estilo influenciou, mais tarde, os templos ptolemaicos e romanos.',
  { h: 'A redescoberta' },
  { lista: [
    '**1817:** Giovanni Belzoni encontra o túmulo de Seti I (KV17) e leva para Londres o sarcófago de alabastro, hoje no Museu Soane.',
    '**1822:** Champollion decifra os hieróglifos (veja a página «Deuses, escrita e vida quotidiana»).',
    '**1881 e 1898:** descobertos os dois «esconderijos» reais, em Deir el-Bahari (DB320) e em KV35, onde os sacerdotes do Terceiro Período Intermédio tinham guardado dezenas de múmias de reis, para as proteger dos ladrões.',
    '**1887:** uma camponesa local descobre em Amarna as tabuinhas de argila, hoje as «cartas de Amarna».',
    '**1912:** o arqueólogo alemão Ludwig Borchardt encontra o busto de Nefertiti no ateliê de Tutmés.',
    '**4 de novembro de 1922:** a equipa de **Howard Carter**, financiada por Lord Carnarvon, descobre os degraus do túmulo de Tutankhamon, e em fevereiro de 1923 abre a câmara funerária.',
    '**1966 em diante:** Manfred Bietak escava Tell el-Dab’a e revela Avaris.',
    '**1995:** Kent Weeks revela que o túmulo KV5, dos filhos de Ramsés II, é enorme, com mais de 120 câmaras.'
  ] },
  { cit: 'Sim, coisas maravilhosas.', fonte: 'Resposta de Howard Carter a Lord Carnarvon, que lhe perguntou se via alguma coisa, ao espreitar pela primeira vez a câmara de Tutankhamon, segundo o relato do próprio Carter (1923)' },
  { img: 'eni-carter-tumba', leg: 'Howard Carter e Arthur Callender a examinar objetos no túmulo de Tutankhamon, c. 1924; fotografia de Harry Burton.' },
  { h: 'Os mistérios que ficam' },
  { lista: [
    '**A tumba de Nefertiti:** a hipótese de que estivesse escondida junto à de Tutankhamon (2015) foi desmentida por radares em 2018. Onde está continua por descobrir.',
    '**O Êxodo:** não há prova arqueológica da saída de um grande grupo de israelitas do Egito no tempo de Ramsés II, e muitos arqueólogos duvidam do relato bíblico como história. A Estela de Merneptah (c. 1208 a.C.) menciona «Israel» como um povo, provavelmente em Canaã.',
    '**Os Povos do Mar:** continuam a ser debatidos. Quem foram, de onde vieram e por que causa.',
    '**A maldição de Tutankhamon:** é um mito da imprensa de 1923, que se espalhou após a morte de Lord Carnarvon, em abril de 1923, de uma infeção. Os estudos mostram que a esperança de vida dos envolvidos na descoberta não foi menor do que a dos outros.'
  ] },
  { h: 'Polémicas e conservação' },
  'O **busto de Nefertiti** saiu do Egito em 1913, numa partilha de achados, e está em Berlim; o Egito pede a sua devolução há décadas. O **Abu Simbel** foi salvo pela UNESCO nos anos 1960: os templos foram cortados em blocos e remontados 65 m mais alto, para escapar às águas da barragem de Assuão (1964–1968). O novo **Grande Museu Egípcio**, em Gizé, abriu oficialmente em novembro de 2025 e mostra, pela primeira vez juntos, todos os objetos do túmulo de Tutankhamon. Em 2021, 22 múmias reais foram levadas em procissão do Museu do Cairo para o Museu Nacional da Civilização Egípcia.',
  { img: 'eni-abu-simbel-salvamento', leg: 'Desmontagem de um pilar osiríaco da sala de entrada do Grande Templo de Abu Simbel durante o resgate da UNESCO.' },
  { img: 'eni-grande-museu', leg: 'Grande Museu Egípcio, Gizé.' },
  { h: 'Onde visitar' },
  { lista: [
    '**Luxor (Tebas):** Karnak, o templo de Luxor, o Vale dos Reis, Deir el-Bahari, Medinet Habu, Deir el-Medina, o Ramesseum.',
    '**Abu Simbel e Assuão:** os templos de Ramsés II e as obras de resgate da UNESCO.',
    '**Tell el-Amarna:** de difícil acesso, mas com túmulos de nobres no penhasco.',
    '**Abidos:** o templo de Seti I e a Lista dos Reis.',
    '**Museus:** o Grande Museu Egípcio (Gizé) e o Museu Egípcio (Cairo), o Museu Britânico, o Louvre, o Neues Museum (Berlim), o Museu Egípcio de Turim, o Metropolitan Museum (Nova Iorque) e o Museu de Luxor.'
  ] },
  { h: 'Egiptomania' },
  'O Reino Novo é o Egito de que o Ocidente mais gosta. A descoberta do túmulo de Tutankhamon, em 1922, lançou uma moda de «egiptomania» que chegou à arquitetura, à joalharia e ao cinema. Os obeliscos de Luxor, Karnak e Heliópolis estão hoje em Paris, Londres, Nova Iorque, Roma e Istambul. A maior parte das imagens que temos hoje do «antigo Egito», dos faraós de ouro à rainha Nefertiti, é desta época.',
  { h: 'Para continuar' },
  'Para a vida dos grandes reis, veja «Os faraós»; para os monumentos, «Monumentos e sítios»; para a religião, a escrita e o dia a dia, «Deuses, escrita e vida quotidiana»; para o que veio depois, «3.º Intermédio e Época Tardia».'
];

const quiz = [
  { p: 'Quem eram os Hicsos?', op: ['Um povo de marinheiros do Egeu', 'Governantes de origem asiática (cananeia) que dominaram o Delta', 'Os soldados de Ramsés II', 'Os sacerdotes de Amon'], certa: 1, exp: 'O nome vem do egípcio *heqa-khasut*, «governantes de terras estrangeiras»; a sua capital era Avaris.' },
  { p: 'Qual foi o rei que completou a expulsão dos Hicsos e fundou a dinastia XVIII?', op: ['Tutmés III', 'Ahmés I', 'Amenófis III', 'Horemheb'], certa: 1, exp: 'Ahmés I tomou Avaris, c. 1550 a.C., e reunificou o país.' },
  { p: 'Que mulher reinou como faraó, construiu Deir el-Bahari e enviou uma expedição a Punt?', op: ['Nefertiti', 'Nefertari', 'Hatshepsut', 'Tiy'], certa: 2, exp: 'Hatshepsut assumiu o título de rei por volta do ano 7 do seu reinado.' },
  { p: 'Qual foi a batalha em que Tutmés III derrotou uma coligação cananeia, em 1457 a.C.?', op: ['Kadesh', 'Megiddo', 'Actium', 'Cárquemis'], certa: 1, exp: 'A batalha de Megiddo (ano 23) está relatada nos Anais de Karnak.' },
  { p: 'Onde está inscrito o grande relato de campanhas de Tutmés III, os «Anais»?', op: ['Em Abu Simbel', 'Em Karnak', 'Em Gizé', 'Em Mênfis'], certa: 1, exp: 'Os Anais foram gravados nas paredes do templo de Amon-Rá em Karnak.' },
  { p: 'Que deus Akhenaton elevou acima de todos os outros?', op: ['Osíris', 'Amon', 'Aton', 'Ptah'], certa: 2, exp: 'O Aton, o disco solar. Akhenaton fundou uma nova capital, Akhetaton, em Amarna.' },
  { p: 'Em que língua foram escritas as cartas de Amarna?', op: ['Em hieróglifos egípcios', 'Em grego', 'Em acádio, em escrita cuneiforme', 'Em hebraico'], certa: 2, exp: 'O acádio era a língua internacional da diplomacia no Bronze Final.' },
  { p: 'Quem descobriu o túmulo de Tutankhamon em 1922?', op: ['Giovanni Belzoni', 'Howard Carter', 'Jean-François Champollion', 'Auguste Mariette'], certa: 1, exp: 'Carter, financiado por Lord Carnarvon, encontrou os degraus do túmulo a 4 de novembro de 1922.' },
  { p: 'O que fez Tutankhamon pouco depois de subir ao trono?', op: ['Mudou a capital para o Delta', 'Restaurou os cultos tradicionais e voltou a Tebas', 'Conquistou a Síria', 'Aboliu o clero'], certa: 1, exp: 'Mudou o nome de Tutankhaton para Tutankhamon e restaurou Amon (Estela da Restauração).' },
  { p: 'Onde se travou a batalha de 1274 a.C. entre Ramsés II e os hititas?', op: ['Em Megiddo', 'Em Kadesh', 'Em Avaris', 'Em Tebas'], certa: 1, exp: 'Kadesh, na Síria. É hoje considerado um empate, apesar da propaganda egípcia.' },
  { p: 'Que documento de c. 1259 a.C. é um dos mais antigos tratados de paz de que se conhece o texto?', op: ['A Estela de Merneptah', 'O tratado entre Ramsés II e Hattusili III', 'O Código de Hamurabi', 'O Papiro de Turim'], certa: 1, exp: 'Há versões em egípcio e em acádio.' },
  { p: 'Quem construiu os templos de Abu Simbel?', op: ['Hatshepsut', 'Tutmés III', 'Ramsés II', 'Ramsés III'], certa: 2, exp: 'Ramsés II mandou escavar o Grande Templo e o templo da rainha Nefertari, c. 1264–1244 a.C.' },
  { p: 'O que aconteceu em Deir el-Medina no ano 29 de Ramsés III?', op: ['Uma revolta militar', 'A primeira greve registada', 'Um terramoto', 'A descoberta de um túmulo'], certa: 1, exp: 'Os artífices, sem rações de cereal, pararam o trabalho (c. 1158 a.C.).' },
  { p: 'Contra quem lutou Ramsés III, em c. 1177 a.C., na batalha representada em Medinet Habu?', op: ['Os assírios', 'Os persas', 'Os Povos do Mar', 'Os gregos'], certa: 2, exp: 'Os Povos do Mar chegaram por terra e por mar, e foram vencidos no Delta.' },
  { p: 'Onde eram enterrados os faraós do Reino Novo?', op: ['Em pirâmides em Gizé', 'Em túmulos escavados no Vale dos Reis', 'Em mastabas em Saqqara', 'Em Alexandria'], certa: 1, exp: 'Os túmulos escavados na rocha, em Tebas Ocidental, escondiam-se dos ladrões.' }
];

export default {
  id: 'egito',
  cor: '#d9b44a',
  emblema: '../../assets/img/egito.png',
  grupo: { ...GRUPO, aqui: 'novo-imperio' },
  nome:    { pt: '2.º Intermédio e Reino Novo', en: 'Second Intermediate and New Kingdom' },
  periodo: { pt: 'c. 1650 – 1069 a.C.', en: 'c. 1650 – 1069 BC' },
  visao:          { pt: visao, en: EN.visao },
  linha:          { pt: linha, en: EN.linha },
  mapa:           { pt: mapa, en: EN.mapa },
  sociedade:      { pt: sociedade, en: EN.sociedade },
  personalidades: { pt: personalidades, en: EN.personalidades },
  legado:         { pt: [...legado, ...CRED.pt], en: [...EN.legado, ...CRED.en] },
  quiz:           { pt: quiz, en: EN.quiz }
};
