// SUMERIANS — full English content. Same structure and same image slots as the Portuguese version (dados.js).
// Dates are approximate, in the "middle chronology". BC = before Christ. The Akkadians are treated here as part of this civilization.

const visao = [
  { caixa: 'In brief', texto: [
    'The **Sumerians** were the people who, in southern Mesopotamia (today southern Iraq), created the first known city-states, invented writing (cuneiform, c. 3300 BC) and left humanity inventions we still use: written records of accounts and contracts, schools, a code of laws, the division of time into multiples of 60, and much of what we know as urban life.',
    'They never formed a single country. They were dozens of independent cities, each with its own patron god, its own ruler and its own fields, almost always rivals for land and water.'
  ] },
  { img: 'sum-mapa-regiao', leg: 'Sumer in southern Mesopotamia, between the Tigris and the Euphrates, near the Persian Gulf.' },
  { h: 'Where it was' },
  'Sumer occupied **Lower Mesopotamia**, the alluvial plain formed by the **Tigris** and **Euphrates** rivers between the area of present-day Baghdad and the Persian Gulf. In Sumerian times the coastline lay further inland than today, and the cities of Eridu and Ur stood beside marshes and lagoons connected to the sea. The Sumerians called their land **Ki-en-gi** and themselves “the black-headed people” (ùĝ saĝ gíg-ga). The name “Sumer” comes from the Akkadian form Šumerum, used by neighbouring peoples.',
  'It was a hard and generous place at the same time. It hardly ever rained (less than 200 mm a year), and there was no stone, good timber or metal. But the rivers brought fertile silt and, with irrigation canals, the land produced large barley harvests. That paradox explains almost everything: without rain, canals and dykes had to be organized in common, which required leaders, scribes, records and temples to store the surplus. The floods of the Tigris and Euphrates were violent and unpredictable, and the memory of them lies behind the flood myths.',
  { img: 'sum-paisagem-pantanais', leg: 'Interior of a mudhif, the traditional reed house of the marshes of southern Iraq, a building that recalls the reed houses on Sumerian seals.' },
  { h: 'When it existed' },
  'In the archaeological and written sources, Sumerian history is divided into phases. The dates are approximate and vary with the chronology used; the most common one, the “middle chronology”, is followed here.',
  { tabela: { cab: ['Phase', 'Approximate dates', 'What marks it'], linhas: [
    ['Ubaid period', 'c. 6500 – 3800 BC', 'First villages in the south; Eridu founded c. 5400 BC; temples on platforms; irrigation'],
    ['Uruk period', 'c. 4000 – 3100 BC', 'First true cities; giant Uruk; accounting tablets and writing; cylinder seals; the wheel and fast pottery'],
    ['Jemdet Nasr', 'c. 3100 – 2900 BC', 'Consolidation of cities and writing; more trade'],
    ['Early Dynastic (I–III)', 'c. 2900 – 2350 BC', 'City-states at war; kings such as Gilgamesh and Eannatum; Royal Cemetery of Ur'],
    ['Akkadian Empire', 'c. 2334 – 2154 BC', 'Sargon of Akkad unites Mesopotamia; Enheduana; Naram-Sin'],
    ['Gutians and Gudea', 'c. 2154 – 2112 BC', 'Rule by the Gutian highlanders; Sumerian revival in Lagash under Gudea'],
    ['Third Dynasty of Ur (Ur III)', 'c. 2112 – 2004 BC', 'Bureaucratic state; Ur-Nammu and Shulgi; Code of Ur-Nammu; Great Ziggurat of Ur'],
    ['After Ur III', 'after c. 2000 BC', 'Fall of Ur; Sumerian stops being spoken; Isin, Larsa and later Babylon inherit the culture']
  ] } },
  { img: 'sum-tabuinha-uruk', leg: 'Proto-cuneiform administrative tablet (c. 3100–2900 BC): accounts of grain and animals, with signs still in the form of pictures.' },
  { h: 'Where did they come from?' },
  'No one knows for sure. The Sumerian language belongs to no known family: it is a **language isolate**, which for decades fed the idea of a people who arrived from elsewhere. Today many archaeologists argue that the Sumerians descend from the populations already living in southern Mesopotamia since the Ubaid period, and that the “invention” of Sumer was a local process lasting centuries, in which Sumerian-speaking and Semitic-speaking peoples (to which the Akkadians belong) mixed. The question remains open.',
  { h: 'Why they matter' },
  { lista: [
    '**Writing:** the oldest known writing appeared in Uruk to count grain, beer and sheep.',
    '**The city:** they lived in the first true cities, with thousands of inhabitants, temples, walls and specialized districts.',
    '**State and law:** they created written administration, taxes and the oldest known law code.',
    '**School and literature:** they founded the first schools and produced the first written literature, including the oldest author known by name.',
    '**Practical science:** base-60 mathematics, a lunar calendar, medicine with written prescriptions, observational astronomy.',
    '**Technology:** the potter’s wheel, wheeled vehicles, the seeder plough, sailing boats, bronze.'
  ] },
  { caixa: 'Sumer today', texto: 'The ruins of **Ur, Uruk and Eridu** have been part, since 2016, of the UNESCO World Heritage site “The Ahwar of Southern Iraq”. The Great Ziggurat of Ur can still be seen from far away across the plain.' },
  { img: 'sum-ziggurat-ur', leg: 'The Great Ziggurat of Ur, built by Ur-Nammu c. 2100 BC and partly reconstructed in the 20th century.' }
];

const linha = [
  'This timeline follows the main events of Sumerian history. The dates are approximate, especially the oldest ones.',
  { linha: [
    { d: 'c. 6500 – 5400 BC', t: 'Ubaid period: the first villages of the south', x: 'Small farming communities begin to settle southern Mesopotamia, practising simple irrigation. They build mud-brick houses and the first temples. Around 5400 BC **Eridu** appears, which the Sumerians considered the oldest of cities, linked to the god Enki.' },
    { d: 'c. 4000 – 3500 BC', t: 'Temples grow, and Uruk grows with them', x: 'Temples become large buildings on platforms and economic centres that store and distribute grain and wool. Uruk becomes the largest urban centre in the world of its time.' },
    { d: 'c. 3500 BC', t: 'The potter’s wheel and wheeled vehicles', x: 'The potter’s wheel and, soon after, wheeled carts appear in Mesopotamia. The origin of the wheel is debated, because it appears in different regions at about the same time.' },
    { d: 'c. 3350 – 3200 BC', t: 'Written accounts are born', x: 'In Uruk, scribes use clay tokens and then signs engraved on tablets to record grain, beer, textiles and livestock. This is **proto-cuneiform writing**, the oldest known. The first signs are pictures of objects; the written language is still hard to read.' },
    { d: 'c. 3200 – 3000 BC', t: 'The Uruk Vase and the first cylinder seals', x: 'Sumerian art produces the Uruk (Warka) Vase, with its procession of offerings to the goddess Inanna. Cylinder seals, rolled over clay, serve as signature and authentication of goods.' },
    { d: 'c. 2900 BC', t: 'The wall of Uruk', x: 'Uruk is surrounded by a wall about 9 km long. Tradition attributes it to Gilgamesh. It is a sign that war between cities had become normal.' },
    { d: 'c. 2900 – 2600 BC', t: 'Early Dynastic I–II: kings and wars', x: 'The city-states of Kish, Uruk, Ur, Lagash, Umma and others dispute land and canals. Rulers such as **Enmebaragesi of Kish** (c. 2600 BC) and **Gilgamesh of Uruk** are the first kings recorded by tradition. The Sumerian King List, compiled centuries later, mixes historical names with legendary figures.' },
    { d: 'c. 2600 – 2500 BC', t: 'The royal tombs of Ur', x: 'In Ur, rulers and the queen **Puabi** are buried with gold, lapis lazuli, lyres, the “Standard of Ur” and dozens of sacrificed attendants. It is the largest group of Sumerian art known.' },
    { d: 'c. 2600 BC', t: 'First literature and schools', x: 'Tablets from Shuruppak and Abu Salabikh show wisdom texts, word lists and schoolchildren’s exercises. Written Sumerian literature begins to exist.' },
    { d: 'c. 2450 BC', t: 'Eannatum of Lagash defeats Umma', x: 'The war between Lagash and Umma over the border and the canals is documented on the **Stele of the Vultures**, the first great war account in image and text.' },
    { d: 'c. 2350 BC', t: 'The reforms of Urukagina', x: 'The king of Lagash cuts abuses by officials and the temple, and protects widows and orphans. It is considered one of the first texts of social reform. It contains the oldest known occurrence of the Sumerian word **ama-gi** (freedom, or “return to the mother”).' },
    { d: 'c. 2340 BC', t: 'Lugalzagesi unites the southern cities', x: 'The king of Umma conquers Lagash and Uruk and proclaims rule from the “lower sea” to the “upper sea”, that is, from the Gulf to the Mediterranean. His power does not last long.' },
    { d: 'c. 2334 – 2279 BC', t: 'Sargon of Akkad conquers Sumer', x: 'Sargon, a Semitic speaker, defeats Lugalzagesi and creates the **first empire of Mesopotamia**, with its capital at Akkad (location still unknown). Akkadian becomes the language of power, but Sumerian keeps its religious and cultural prestige.' },
    { d: 'c. 2285 – 2250 BC', t: 'Enheduana, the first author', x: 'Sargon’s daughter is high priestess of Nanna in Ur and composes hymns in Sumerian. She is the **first person known by name** to sign literary works.' },
    { d: 'c. 2254 – 2218 BC', t: 'Naram-Sin', x: 'Sargon’s grandson takes the empire to its height and declares himself a god in his lifetime. The Victory Stele of Naram-Sin is one of the great works of Mesopotamian art.' },
    { d: 'c. 2154 – 2112 BC', t: 'Collapse of Akkad and Gutian rule', x: 'The empire falls under pressure from Gutian highlanders, and perhaps a prolonged drought around 2200 BC (the “4.2-kiloyear event”, a debated theory). The southern cities regain autonomy.' },
    { d: 'c. 2144 – 2124 BC', t: 'Gudea of Lagash', x: 'The ruler of Lagash rebuilds temples and leaves statues and the **Gudea Cylinders**, the longest known Sumerian text, about the building of the temple of Ningirsu.' },
    { d: 'c. 2112 BC', t: 'Utu-hengal expels the Gutians', x: 'The king of Uruk defeats the Gutians. Soon after, Ur-Nammu of Ur takes power.' },
    { d: 'c. 2112 – 2095 BC', t: 'Ur-Nammu founds the Third Dynasty of Ur', x: 'He restores order, builds the Great Ziggurat of Ur and issues the **Code of Ur-Nammu**, the oldest known law code.' },
    { d: 'c. 2094 – 2047 BC', t: 'Shulgi and the bureaucratic state', x: 'For almost half a century, Shulgi builds a highly centralized state apparatus, with standardized weights and measures, enormous archives and regular taxes. He declares himself a god. Scribal schools multiply.' },
    { d: 'c. 2047 – 2004 BC', t: 'Decline of Ur III', x: 'Under Amar-Sin, Shu-Sin and Ibbi-Sin, the state faces famine, pressure from the Amorites and attacks from Elam. Around 2004 BC the Elamites sack Ur and carry the king off prisoner. The “Lament for the Destruction of Ur” mourns the event.' },
    { d: 'c. 2000 – 1700 BC', t: 'Sumerian stops being a spoken language', x: 'Isin, Larsa and then Babylon inherit the culture. Sumerian continues to be copied and taught as a sacred and learned language, like Latin in Europe, for more than a thousand years.' },
    { d: 'c. AD 75', t: 'The last dated cuneiform text', x: 'The last known cuneiform tablets are astronomical, from c. AD 75. The writing invented in Uruk ended after more than 3000 years of use.' }
  ] },
  { img: 'sum-tokens-bullae', leg: 'Clay tokens of various shapes, used to count goods before writing (c. 3500 BC).' },
  { img: 'sum-vaso-warka', leg: 'The Uruk (Warka) Vase, c. 3200–3000 BC, in a museum display case.' },
  { img: 'sum-estandarte-ur', leg: 'The Standard of Ur, c. 2600–2400 BC: the “War” side, with chariots and prisoners.' },
  { img: 'sum-estela-abutres', leg: 'Stele of the Vultures (Eannatum of Lagash, c. 2450 BC), Louvre.' },
  { img: 'sum-sargao-cabeca', leg: 'Bronze head of an Akkadian king, traditionally associated with Sargon or Naram-Sin.' },
  { img: 'sum-codigo-urnammu', leg: 'Tablet with the Code of Ur-Nammu, from Nippur, 2112–2095 BC (Istanbul Archaeology Museums).' }
];

const mapa = [
  'Sumer was a mosaic of city-states, each with its own religious centre, its wall, its fields and canals. This map shows where the main ones were. In each, the patron god was seen as the true owner of the city.',
  { img: 'sum-mapa-cidades-estado', leg: 'Sumer c. 3000 BC and its main cities, among them Eridu, Ur, Uruk, Larsa, Lagash, Girsu, Nippur, Isin and Kish.' },
  { tabela: { cab: ['City', 'Patron god', 'Modern site', 'What it is known for'], linhas: [
    ['Eridu', 'Enki (Ea)', 'Abu Shahrain, southern Iraq', 'The oldest city according to tradition; seat of the god of fresh water and wisdom'],
    ['Ur', 'Nanna (Moon)', 'Tell el-Muqayyar', 'Royal tombs, the Standard of Ur, the Great Ziggurat, capital of Ur III'],
    ['Uruk', 'Inanna and An', 'Warka', 'First great city, cradle of writing, city of Gilgamesh'],
    ['Larsa', 'Utu (Sun)', 'Tell as-Senkereh', 'Centre of sun worship; a power after the fall of Ur III'],
    ['Lagash and Girsu', 'Ningirsu', 'Tell al-Hiba and Tello', 'Stele of the Vultures, Urukagina, Gudea, enormous archives'],
    ['Umma', 'Shara', 'Tell Jokha', 'Constant rival of Lagash; land of Lugalzagesi'],
    ['Shuruppak', 'Sud', 'Fara', 'Land of Ziusudra, the flood hero; early schoolchildren’s texts'],
    ['Nippur', 'Enlil', 'Nuffar', 'Religious centre of all Sumer; school and library; thousands of tablets'],
    ['Isin', 'Nininsina', 'Ishan al-Bahriyat', 'Succeeds Ur III; Code of Lipit-Ishtar'],
    ['Kish', 'Zababa', 'Tell Uhaimir', 'The title “king of Kish” was prestigious throughout Mesopotamia']
  ] } },
  { h: 'Eridu and the beginning' },
  'Eridu was founded around 5400 BC beside marshes near the Gulf. The Sumerians said that kingship began there, coming down from heaven. Enki, god of fresh water and wisdom, lived in the **Abzu**, the abyss of fresh water beneath the earth, and his temple was one of the oldest. Excavations found layers of superimposed temples, ever larger, over thousands of years.',
  { img: 'sum-eridu-ruinas', leg: 'Remains of mud brick and fired brick at Eridu, in southern Iraq: one of the oldest cities of Sumer.' },
  { h: 'Uruk, the first city' },
  'Uruk (the Erech of the Bible) was, around 3200 BC, the largest urban settlement in the world, with tens of thousands of inhabitants (the usual estimates range from 25,000 to 50,000). The wall, c. 2900 BC, was about 9 km long and enclosed an area of about 6 km². It had two great religious centres: the **Eanna** sector, of Inanna, and the **Anu** sector, with the White Temple on a platform about 12 m high. It was in Eanna that the first written tablets were found.',
  { img: 'sum-uruk-ruinas', leg: 'Ruins of Uruk (Warka).' },
  { h: 'Ur, city of the Moon' },
  'Ur stood beside the Euphrates, with harbours and canals. It was the capital of the Third Dynasty of Ur. It became famous for the **royal tombs** discovered by Leonard Woolley (1922–1934) and for the Great Ziggurat. According to biblical tradition, it was also the city of Abraham (Ur of the Chaldees), though without archaeological confirmation.',
  { img: 'sum-ur-vista-aerea', leg: 'Excavated ruins of a city in Sumer, photograph from the Matson collection (c. 1930).' },
  { h: 'Lagash and Girsu' },
  'The state of Lagash had several cities, among them Girsu (Tello), where thousands of administrative tablets were found. It was the first Sumerian site excavated on a large scale, by Ernest de Sarzec, from 1877. The Stele of the Vultures and the statues of Gudea came from there.',
  { img: 'sum-lagash-girsu', leg: 'Mound of ruins on the salt plain of southern Iraq, in the region of Lagash.' },
  { h: 'Nippur, the city of Enlil' },
  'Nippur was never a political capital, but it was the religious centre of all Sumer. Whoever controlled the temple of Enlil legitimized himself as king. One of the great scribal schools was also there, and the excavations of the University of Pennsylvania, from 1889, found tens of thousands of tablets.',
  { img: 'sum-nipur-ruinas', leg: 'Excavations at Nippur (Nuffar): an old photograph of the mound, with numbered zones.' },
  { h: 'Trade routes' },
  'Sumer had no stone, metals or timber, and so depended on long-distance trade: **copper** from Magan (present-day Oman) and Anatolia, **lapis lazuli** from Badakhshan (Afghanistan), **carnelian** and other goods from Meluhha (the Indus Valley), **cedar** from Lebanon, **silver** from the Taurus. The island of **Dilmun** (Bahrain) was the great trading post in the Gulf. Indus seals found in Ur show there was direct contact with the Indus civilization.',
  { img: 'sum-rotas-comercio', leg: 'The sea route between Mesopotamia and the Indus Valley, through the Persian Gulf and the Arabian Sea.' }
];

const sociedade = [
  { h: '1. Political organization' },
  'The political unit was the **city-state**: a city, the surrounding fields, the canals, the temple. Each was governed by an **en** (high priest), a **lugal** (“big man”, king) or an **ensi** (governor), and worked as the property of its god. In moments of crisis, the sources speak of assemblies of free men and elders who decided on war, as in the poems of Gilgamesh. Kingship was seen as a gift of the gods: according to the Sumerian King List, “kingship descended from heaven”.',
  'War over canals and borders was constant. Armies had spearmen in phalanx with shields and copper helmets, and four-wheeled carts drawn by onagers (wild asses).',
  { img: 'sum-selo-cilindrico', leg: 'Cylinder seal and its impression in clay: they served as signature and identification.' },
  { h: '2. Social classes' },
  { lista: [
    '**Kings, priests and senior officials:** rulers and administrators of the temple and the palace.',
    '**Free men:** landowners, craftsmen, merchants, scribes, soldiers.',
    '**Temple and palace dependents:** workers who received rations of barley, wool and beer in exchange for labour.',
    '**Slaves:** mainly prisoners of war and people handed over for debt. In general they had some rights and could, in certain cases, buy their freedom.'
  ] },
  { h: '3. Religion' },
  'Religion was **polytheistic and anthropomorphic**: the gods were imagined with human form and behaviour, but immortal and with enormous powers. The main ones were:',
  { tabela: { cab: ['God', 'Domain', 'City'], linhas: [
    ['An', 'Sky, father of the gods', 'Uruk'],
    ['Enlil', 'Air, wind, destiny; head of the pantheon', 'Nippur'],
    ['Enki (Ea)', 'Fresh water, wisdom, magic, the arts', 'Eridu'],
    ['Ninhursag', 'Mother earth, mountain', 'several centres'],
    ['Inanna (Ishtar)', 'Love, war, fertility, morning and evening star', 'Uruk'],
    ['Nanna (Suen)', 'Moon', 'Ur'],
    ['Utu (Shamash)', 'Sun and justice', 'Larsa and Sippar'],
    ['Ereshkigal', 'Queen of the underworld', 'Kur / Irkalla'],
    ['Dumuzi', 'Shepherd and husband of Inanna, dies and returns', 'Bad-tibira']
  ] } },
  'Each city was the “house” of its god. The **temple** was the centre of economic and religious life: it owned land, workshops and storehouses, and distributed rations. Every day the priests dressed, fed and honoured the statues of the gods. The universe was ruled by hundreds of divine norms called **me**, and a myth tells how Inanna stole them from Enki for Uruk. Worship included annual festivals and, according to some scholars, a “sacred marriage” rite between the king and the priestess of Inanna (a debated matter).',
  { img: 'sum-templo-ritual', leg: 'Worship scene in a temple: offerings and the statue of the god.' },
  { h: 'Life after death' },
  'The dead went to **Kur** or **Irkalla**, a gloomy world beneath the earth, where they ate dust and clay. There were no moral rewards or punishments as later in other religions; the afterlife was the same for everyone, although the gods of the underworld judged deeds. The dead were buried under house floors or in cemeteries, with pottery, jewellery and, in the royal tombs, dozens of attendants. Descendants made regular offerings of water and food to secure the rest of the ancestors.',
  { h: '4. Economy and agriculture' },
  'The economy rested on irrigation agriculture. They grew **barley** (the basis of food and of currency), wheat, pulses, onion, garlic, lettuce, cucumber, flax and date palms. They raised sheep, goats, cattle and donkeys, and fished in the canals and marshes. Most land belonged to the temples and palaces, but there was also private property.',
  'Intensive irrigation brought a problem: **soil salinization**. According to classic studies, wheat, which is more sensitive to salt, was gradually replaced by barley, and productivity probably fell in the south between 3500 and 2100 BC. The importance of this factor in the fall of the cities is debated today.',
  { img: 'sum-campos-irrigacao', leg: 'Barley fields irrigated by canals, with farmers and donkeys.' },
  'There was no coinage, but there were standards of value: barley and silver, measured in **gur** (capacity) and **shekels** (weight). A shekel weighed about 8.3 g; 60 shekels made a **mina** (about 500 g); 60 minas made a **talent** (about 30 kg). Contracts of sale, loan and lease were written on tablets, witnessed and sealed.',
  { h: '5. Writing, scribes and schools' },
  'Writing was born from accounting. Before it, small clay tokens were used to count goods. Around 3350–3200 BC, in Uruk, people began to impress or engrave signs on tablets. The first signs were pictures (a foot, a head, a fish); over time, written with a **reed stylus** on wet clay, they became wedge-shaped, hence the name **cuneiform** (from Latin *cuneus*, “wedge”). They used a few hundred signs, which stood for words or syllables. The same system was later adopted to write Akkadian, Elamite, Hittite and other languages.',
  { img: 'sum-escrita-evolucao', leg: 'From picture to wedge: the evolution of a sign over more than a thousand years.' },
  'Scribes learned in the **edubba**, the “tablet house”. They copied lists of words, gods, professions, animals, cities; later, hymns, proverbs and poems. Surviving school texts speak of strict teachers and punishment with the cane. Being a scribe was a privilege, almost always of families with resources, and opened the door to the administration of the temple and the palace.',
  { img: 'sum-escriba-escola', leg: 'A lesson in an edubba: pupils copying signs on clay tablets.' },
  { img: 'sum-cuneiforme-estilete', leg: 'Reed stylus and tablet: how people wrote in cuneiform.' },
  { h: '6. Home and family' },
  'Houses were of raw **clay brick**, with a central courtyard, a flat roof and few windows, to escape the heat. The poorest lived in **reed** houses, especially in the marshes. The family was patriarchal, but women could own property, do business and go to court. Some were priestesses and, more rarely, scribes. Marriage was a contract between families, with bride price and dowry. The sources speak of divorce and adoption.',
  { img: 'sum-casa-sumeria', leg: 'A Sumerian brick house with a central courtyard.' },
  { caixa: 'Kug-Bau, the tavern-keeper who became queen', texto: 'The Sumerian King List includes only one woman: **Kug-Bau** (Ku-Baba) of Kish, described as a tavern-keeper, who is said to have reigned c. 2500 BC. This is a tradition, not a confirmed fact, but it shows that the idea of a woman ruler was not unthinkable.' },
  { h: '7. Food' },
  'The diet was based on **bread** and barley porridge, pulses (lentils, chickpeas, broad beans), onion, garlic, cheese, butter, fish and dates. Meat was rarer: mutton and goat, mainly at festivals and in offerings. **Beer** was everyone’s drink, made from barley and bread, and it was drunk through reed straws from large jars, as seen on seals. Workers received daily beer rations. A hymn to **Ninkasi**, goddess of beer (c. 1800 BC), is also a recipe.',
  { img: 'sum-cerveja-palhinhas', leg: 'A Sumerian banquet: beer drunk through straws from a shared jar.' },
  { h: '8. Clothing and jewellery' },
  'At first, men and women wore woollen skirts with fringes and tufts, called **kaunakes**. Men often went bare-chested; women wore dresses that left one shoulder uncovered. Hair and beard were cared for and, in some periods, shaved. The elites wore jewellery of gold, silver, lapis lazuli, carnelian and shell, as seen in the royal tombs of Ur.',
  { img: 'sum-vestuario', leg: 'Worshipper statuettes from Tell Asmar (c. 2800–2600 BC): large eyes, kaunakes skirt, hands clasped in prayer.' },
  { h: '9. Music and games' },
  'The Sumerians played **lyres**, harps, flutes, drums and sistra, at religious ceremonies, banquets and funerals. The lyres of Ur, with gold bull heads and shell, are among the oldest known. They played the **Royal Game of Ur**, on a board of twenty squares, of which examples are known from the tombs of Ur (c. 2600 BC) and rules written much later, on a Babylonian tablet. There were also games of dice and stones.',
  { img: 'sum-lira-ur', leg: 'Lyre of Ur with a bull’s head, c. 2500 BC.' },
  { img: 'sum-jogo-real-ur', leg: 'Board of the Royal Game of Ur, c. 2600 BC.' },
  { h: '10. Science, mathematics and medicine' },
  'The Sumerians created a **sexagesimal** (base 60) number system combined with base 10, with place value. From it come the 60 minutes of the hour, the 60 seconds of the minute and the 360° of the circle, which the Babylonians perfected. The tablets of Shuruppak (c. 2500 BC) show exercises in measuring areas and dividing grain; in the later centuries (c. 2100–1900 BC) there are tables of multiplication, reciprocals, squares and roots.',
  { img: 'sum-relogio-60', leg: 'One hypothesis for base 60: counting to 12 on the finger joints of one hand and keeping track of the dozens with the fingers of the other (5 × 12 = 60).' },
  'The **calendar** was lunar: twelve months of 29 or 30 days (354 days), with an extra month from time to time. Each year was named after an important event. They watched stars and planets for religious purposes.',
  'In medicine, the pharmacological tablet from Nippur (c. 2100 BC) is one of the oldest known collections of prescriptions, with about fifteen formulas based on plants, salt and minerals. There were two kinds of specialist: the **asu**, who used drugs and dressings, and the **ashipu**, who performed exorcisms and rituals.',
  { h: '11. Technology' },
  { lista: [
    '**Potter’s wheel** (c. 3500 BC) and **wheeled vehicles** (one of the oldest depictions is a tablet from Uruk, c. 3200 BC).',
    '**Seeder plough**, which buried the seed in rows, saving grain.',
    '**Sailing and rowing boats** for rivers and the Gulf.',
    '**Bronze:** first copper with arsenic, then copper with tin (c. 2500 BC), imported from far away.',
    '**Fired brick, vault and arch** in public buildings and tombs.',
    '**Cylinder seal:** carved in stone, it was rolled on clay to sign and seal.',
    '**Lists of professions, signs and words:** the first reference works.'
  ] },
  { img: 'sum-mercado-cidade', leg: 'Market of a Sumerian city: barley, wool, pottery, merchants and scribes keeping records.' }
];

const personalidades = [
  'The Sumerians did not write biographies as we do today, but they left names, inscriptions and stories. These are the most important figures, real or partly legendary.',
  { h: 'Gilgamesh, king of Uruk' },
  'King of Uruk, c. 2700–2600 BC. The King List says he reigned 126 years and was the fifth king of the first dynasty of Uruk; tradition made him a hero. He is thought to have really existed. In the Sumerian poems (c. 2100 BC) and later in the **Epic of Gilgamesh** (Akkadian version, c. 1800 BC and standardized later), he seeks immortality after the death of his friend Enkidu and ends up accepting the human condition. He was the first great literary hero.',
  { img: 'sum-gilgamesh', leg: 'Gilgamesh overpowering a lion, Assyrian relief of the 8th century BC (Louvre): a later image, inspired by the legend.' },
  { img: 'sum-gilgamesh-tab11', leg: 'Tablet of the Epic of Gilgamesh with the account of the flood, in cuneiform writing.' },
  { h: 'Enmebaragesi, king of Kish' },
  'King of Kish around 2600 BC, the first ruler whose existence is confirmed by inscriptions of the time (fragments of vessels). The King List says he defeated Elam.',
  { h: 'Puabi, queen of Ur' },
  'A woman of high status, buried in the royal cemetery of Ur c. 2600–2500 BC, with a headdress of gold leaves and beads of lapis lazuli and carnelian, and with dozens of attendants. A cylinder seal bearing her name made it possible to know her by name.',
  { img: 'sum-puabi', leg: 'Headdress of gold leaves, flowers and beads of Queen Puabi of Ur, c. 2500 BC.' },
  { h: 'Eannatum, king of Lagash' },
  'He ruled c. 2470–2450 BC. He defeated Umma and fixed the border with markers. He is remembered on the **Stele of the Vultures**, where vultures carry off the enemy dead.',
  { h: 'Urukagina, reformer of Lagash' },
  'He ruled c. 2350 BC and made reforms: he limited abuses by officials, protected the poorest and guaranteed justice. He was defeated by Lugalzagesi of Umma, who overthrew him.',
  { h: 'Lugalzagesi, of Umma' },
  'He conquered Lagash and Uruk and wanted to rule the whole south. He was defeated by Sargon of Akkad, who took him prisoner to Nippur, c. 2334 BC.',
  { h: 'Sargon of Akkad' },
  'Founder of the first empire of Mesopotamia, c. 2334–2279 BC, a speaker of Semitic Akkadian. A legend says he was abandoned in a reed basket, found by a gardener and raised by him, and became cupbearer to the king of Kish before taking power from him. Generations later, he was the model of a king.',
  { img: 'sum-sargao-cabeca', leg: 'Bronze head of an Akkadian king, from Nineveh.' },
  { h: 'Enheduana, priestess and poet' },
  'Daughter of Sargon and high priestess of Nanna in Ur, c. 2285–2250 BC. She composed hymns to Inanna (among them “The Exaltation of Inanna”) and a collection of temple hymns. She is the **first person known by name to write literary works**. An alabaster disc with her portrait, found in Ur, has come down to us.',
  { img: 'sum-enheduana', leg: 'Limestone disc of Enheduana, c. 2300 BC: the figure in the tiered skirt is the priestess.' },
  { h: 'Gudea of Lagash' },
  'He ruled c. 2144–2124 BC while the Gutians dominated. He was a pious ruler who rebuilt temples and left numerous statues of himself in diorite. The **Gudea Cylinders**, with more than 1300 lines, are the longest known Sumerian text.',
  { img: 'sum-gudea-estatua', leg: 'Seated statue of Gudea of Lagash, headless, with a cuneiform inscription on the lap (c. 2120 BC).' },
  { h: 'Ur-Nammu, founder of Ur III' },
  'He reigned c. 2112–2095 BC. He built the Great Ziggurat and many temples and canals, and issued the oldest known law code (authorship is sometimes attributed to his son, Shulgi). He was killed in battle, and his death inspired a lament poem.',
  { img: 'sum-urnammu-estela', leg: 'Stele of Ur-Nammu, reconstructed from fragments (Penn Museum): the king who built the ziggurat of Ur.' },
  { h: 'Shulgi, king of Ur' },
  'He reigned c. 2094–2047 BC. He created a centralized state with standardized weights and measures, a common calendar, enormous archives and a fleet of officials. He declared himself a god in his lifetime and founded scribal schools.',
  { h: 'Ziusudra, the flood hero' },
  'A legendary figure of Shuruppak, who survives the flood on a boat. He is the ancestor of the flood heroes of later texts, the Babylonian Atrahasis and Utnapishtim, and many scholars see in him an influence on the biblical story of Noah.'
];

const legado = [
  { h: 'What they left us' },
  { lista: [
    '**Writing:** the idea of keeping the spoken word on a durable medium. Cuneiform was used for more than 3000 years.',
    '**The city and administration:** records, taxes, archives, officials and budgets.',
    '**Written law:** the Code of Ur-Nammu (c. 2100 BC) predates Hammurabi’s by three centuries.',
    '**School and library:** the edubba and the collections of copied and taught texts.',
    '**Literature:** poems, hymns, proverbs, laments and the legend of Gilgamesh.',
    '**Base 60:** we still divide hours and angles this way.',
    '**Myths:** the flood and paradise (Dilmun, Eridu) left a mark on the traditions of Genesis. The links are debated.',
    '**Ziggurats:** they inspired the Etemenanki of Babylon, the probable origin of the Tower of Babel.'
  ] },
  { img: 'sum-babel-etemenanki', leg: 'Artistic reconstruction of a ziggurat with its top covered in blue glazed tiles, like the Etemenanki of Babylon, associated with the Tower of Babel.' },
  { h: 'Art' },
  'Sumerian art is mostly religious and commemorative. Outstanding are: the **Uruk Vase** (c. 3200 BC), the **cylinder seals**, the worshipper statuettes of **Tell Asmar**, the **Standard of Ur** (a mosaic in shell, lapis lazuli and red limestone, with scenes of war and peace), the **bull lyre** and the **“Ram in a Thicket”** of Ur, the **Stele of the Vultures** and the statues of **Gudea**.',
  { h: 'Architecture: the ziggurat' },
  'The ziggurat was a stepped tower with a core of mud brick and a facing of fired brick set in bitumen. At the top was a temple, where the god “descended”. The **Great Ziggurat of Ur**, built by Ur-Nammu, had three levels. It was restored by Nabonidus in the 6th century BC and partly reconstructed in the 1980s. In the White Temple of Uruk (c. 3500–3000 BC), the tradition of temples on platforms begins to take shape.',
  { h: 'The rediscovery of Sumer' },
  { linha: [
    { d: '1850 – 1869', t: 'Recognizing a forgotten language', x: 'Scholars such as Edward Hincks and Jules Oppert conclude that cuneiform was invented by a non-Semitic-speaking people. The name “Sumerian” becomes established in 1869.' },
    { d: '1877', t: 'De Sarzec at Girsu', x: 'Ernest de Sarzec begins to excavate Tello and finds the first Sumerian statues and inscriptions.' },
    { d: '1889 – 1900', t: 'Nippur', x: 'The University of Pennsylvania excavates Nippur and recovers tens of thousands of tablets.' },
    { d: '1912 to today', t: 'Uruk', x: 'German excavations, which continue, reveal the cradle of writing.' },
    { d: '1922 – 1934', t: 'Woolley at Ur', x: 'Leonard Woolley discovers the royal tombs, the Standard of Ur and the royal games.' },
    { d: '1956', t: 'History Begins at Sumer', x: 'Samuel Noah Kramer publishes the book that brought Sumerian literature to the general public.' },
    { d: '2003', t: 'Looting of the Iraq Museum', x: 'Thousands of pieces disappear from the Baghdad museum, including the Uruk Vase, which was later recovered.' },
    { d: '2016', t: 'World Heritage', x: 'Ur, Uruk and Eridu are inscribed by UNESCO in the site “The Ahwar of Southern Iraq”.' }
  ] },
  { img: 'sum-museu-iraque', leg: 'The National Museum of Iraq, in Baghdad, with the largest collection of Sumerian art.' },
  { img: 'sum-woolley-ur', leg: 'Excavation team at Ur with local workers, photograph from the 1920s–1930s.' },
  { img: 'sum-decifracao', leg: 'The Behistun inscription (Iran), copied by Rawlinson in the 19th century, made it possible to decipher Akkadian cuneiform.' },
  { img: 'sum-reconstrucao-ur', leg: 'Artistic reconstruction of a Sumerian city with its ziggurat and river port, as Ur would have been in the time of Ur-Nammu.' },
  { caixa: 'Where to see them', texto: 'The **British Museum** (London), the **Louvre** (Paris), the **Penn Museum** (Philadelphia), the **Pergamon Museum** (Berlin) and the **National Museum of Iraq** (Baghdad) have the great Sumerian collections.' }
];

const quiz = [
  { p: 'Where was Sumer?', op: ['In the Nile Valley', 'In southern Mesopotamia, between the Tigris and the Euphrates', 'On the Mediterranean coast', 'On the Iranian plateau'], certa: 1, exp: 'Sumer occupied Lower Mesopotamia, today southern Iraq.' },
  { p: 'What is the oldest known writing, which appeared in Uruk?', op: ['Hieroglyphs', 'Phoenician alphabet', 'Cuneiform (proto-cuneiform) writing', 'Chinese writing'], certa: 2, exp: 'The proto-cuneiform writing of Uruk, c. 3350–3200 BC, was born for accounting.' },
  { p: 'What was writing used for at first?', op: ['To write poems', 'For accounts and records of goods', 'For love letters', 'To write laws'], certa: 1, exp: 'The first tablets record grain, beer, textiles and livestock.' },
  { p: 'Why is it called “cuneiform”?', op: ['From the wedge shape of the signs', 'From the name of a king', 'From the colour of the clay', 'From a city called Cune'], certa: 0, exp: 'From Latin cuneus, “wedge”: the signs were made with a reed stylus in clay.' },
  { p: 'What is a ziggurat?', op: ['A type of boat', 'A stepped tower with a temple at the top', 'A law code', 'A board game'], certa: 1, exp: 'It was a stepped brick tower, with the god’s temple at the summit.' },
  { p: 'What was the base of the Sumerian number system that we still use for time and angles?', op: ['Base 10 only', 'Base 12', 'Base 60 (sexagesimal)', 'Base 100'], certa: 2, exp: 'Base 60 lives on in the 60-minute hour and the 360-degree circle.' },
  { p: 'Who was Gilgamesh?', op: ['A sea god', 'A king of Uruk who became the hero of an epic', 'The founder of Ur', 'A scribe of Nippur'], certa: 1, exp: 'Gilgamesh was king of Uruk, c. 2700–2600 BC, and hero of the oldest known epic.' },
  { p: 'Who is considered the first author known by name?', op: ['Sappho', 'Cleopatra', 'Enheduana', 'Puabi'], certa: 2, exp: 'Enheduana, daughter of Sargon and priestess of Nanna in Ur, signed hymns to Inanna.' },
  { p: 'Which king gave his name to the oldest known law code?', op: ['Hammurabi', 'Ur-Nammu', 'Sargon', 'Gudea'], certa: 1, exp: 'The Code of Ur-Nammu (c. 2100 BC) predates Hammurabi’s by three centuries.' },
  { p: 'Who unified Mesopotamia, creating the first empire?', op: ['Sargon of Akkad', 'Gilgamesh', 'Shulgi', 'Eannatum'], certa: 0, exp: 'Sargon of Akkad, c. 2334 BC, defeated Lugalzagesi and united the cities of the south and north.' },
  { p: 'Which was the city of the god Enlil, religious centre of all Sumer?', op: ['Ur', 'Eridu', 'Nippur', 'Lagash'], certa: 2, exp: 'Nippur was the religious centre: whoever controlled the temple of Enlil legitimized himself as king.' },
  { p: 'What did the Sumerians drink through reed straws from large jars?', op: ['Wine', 'Milk', 'Beer', 'River water'], certa: 2, exp: 'Barley beer was everyone’s drink and was drunk through straws.' },
  { p: 'Which of these metals was imported, because Sumer had none?', op: ['None', 'Copper', 'Clay', 'Barley'], certa: 1, exp: 'Copper, lapis lazuli and timber came from far away, from Magan, Afghanistan and Lebanon.' },
  { p: 'Who discovered the royal tombs of Ur in the 1920s?', op: ['Howard Carter', 'Heinrich Schliemann', 'Leonard Woolley', 'Henry Rawlinson'], certa: 2, exp: 'Leonard Woolley excavated Ur between 1922 and 1934 and found the Standard of Ur and Queen Puabi.' },
  { p: 'What eventually happened to Sumerian as a language?', op: ['It is still spoken in Iraq today', 'It stopped being spoken, but continued to be taught as a learned language', 'It was banned by Sargon', 'It was never written down'], certa: 1, exp: 'It stopped being a spoken language around 2000–1700 BC, but was copied for more than a thousand years, like Latin.' }
];

export default { visao, linha, mapa, sociedade, personalidades, legado, quiz };
