// SCYTHIANS — full English content. Same structure and same image slots as the Portuguese version (dados.js).
// Dates follow the “middle chronology”. Almost everything we know about Scythian life comes from two very unequal sources: the tombs (kurgans), which are fact, and Herodotus (Book IV of the *Histories*, c. 430 BC), a precious but second-hand source that mixes observation, hearsay and legend. The Scythians left no literature of their own. BC/AD.

const visao = [
  { caixa: 'In brief', texto: [
    'The **Scythians** (Greek *Skythai*, Persian *Saka*) were a group of **Iranian-speaking nomadic peoples** who dominated the **steppe** between the Danube delta and the river Don, in what is now southern Ukraine and Russia, from about the 7th to the 3rd century BC, and whose relatives and neighbours, called **Saka** by the Persians, roamed the Central Asian steppe as far as the Altai. They were among the first peoples to build power on **cavalry** and the **bow**, and they left one of the most remarkable **gold** arts of the ancient world: coiled animals, stags, panthers and griffins in an unmistakable manner, the **animal style**.',
    'They built no monumental cities and wrote no books: what we know of them comes from their **giant tombs** (*kurgans*), from Greek descriptions, above all **Herodotus**, and, later, from excavation. According to tradition they defeated the Persian king **Darius I** (c. 513 BC) without a single decisive battle, they dealt with the Greek cities of the Black Sea, they had famous kings, such as **Ateas**, and they were finally pushed aside by the **Sarmatians** and destroyed or absorbed by Goths, Huns and Slavs. Almost everything said about them must be read with care: this text always marks what is **fact** and what is **legend** or a late report.'
  ] },
  { img: 'esc-mapa-citia', leg: 'Map of Scythia Minor (Dobruja), on the western shore of the Black Sea: one of the regions that ancient authors called “Scythia”.' },
  { h: 'Where it was' },
  'The Scythian world is, first of all, a **landscape**: the great **Eurasian steppe**, an almost continuous belt of grassland running from the Danube to Mongolia, with few trees, broad rivers (Danube, Dniester, Bug, Dnieper, Don, Volga) and hard winters. It was ideal country for **horses**, herds and wagons, and very poor country for cities. Herodotus’ **Scythia** is the space between the Danube and the Don, with the Black Sea and the **Crimean** peninsula to the south; archaeologists call it “European Scythia”.',
  'Further east, in Central Asia, the same world of mounted nomads stretches across Kazakhstan and the Altai, and includes the people the Persians called **Saka**, in the whole arc from the Aral Sea to southern Siberia. These groups share tomb types, weapons, harness and art, but they were **not one state**: they were confederations of tribes and chiefs, with related languages and identities of their own. Part of the scholarly debate turns on the question “where did the first ones come from?”, and the answer is still uncertain (southern Siberia, Kazakhstan, the Pontic steppe).',
  { img: 'esc-estepe', leg: 'The Pontic steppe on a map of Europe: almost treeless grassland between the Black Sea and the Don.' },
  { h: 'When it existed' },
  'Scythian dates depend on what one calls “Scythian”. Archaeologists distinguish the **Scythian culture** (the one that shares the “triad”: weapons, harness and animal art) from the **historical Scythians** (Herodotus’ people, on the Black Sea). In broad terms:',
  { tabela: { cab: ['Phase', 'Approximate dates', 'What marks it'], linhas: [
    ['Origins and early phase', 'c. 900 – 700 BC', 'First chiefs’ kurgans (Arzhan 1, Tuva, c. 800 BC); first harness, bronze arrowheads and gold animals'],
    ['Scythians in the Near East', 'c. 720 – 600 BC (tradition)', 'Scythians appear in Assyrian sources; invasion of Media and the Levant, according to Herodotus; rule for “28 years” (tradition)'],
    ['Pontic golden age', 'c. 600 – 300 BC', 'Trade with Greek colonies; royal kurgans (Kelermes, Solokha, Chertomlyk, Kul-Oba); Darius’ campaign (c. 513); kingdom of Ateas (until 339)'],
    ['Late Scythia in Crimea', 'c. 300 BC – c. AD 260', 'Pressure from the Sarmatians; kingdom of Skilouros (2nd century BC) with its capital at Neapolis; destroyed by the Goths'],
    ['Saka and Sarmatians', 'c. 700 BC – c. AD 400', 'Saka in the Altai and Central Asia (Pazyryk, Issyk); Sarmatians replacing the Scythians on the steppe; the Indo-Scythians in India']
  ] } },
  { img: 'esc-pente-solokha', leg: 'Gold comb from the Solokha kurgan, c. 400 BC, Hermitage, St Petersburg: Scythian warriors in combat.' },
  { h: 'Who were the Scythians?' },
  'The Scythians’ language was **Iranian** (a branch of Indo-European, related to Avestan and Old Persian), known mainly from **personal names** and a few words recorded by Greek authors. Herodotus (IV.6) says they called themselves **Skolotoi**. To the Assyrians they were the *Ishkuzai*; to the Persians, the *Saka*; to the Greeks, the *Skythai*.',
  'They were a **mixed** people: **ancient DNA** analyses show that Scythians and Saka were not one biologically uniform population but several, with Bronze Age steppe ancestry and stronger eastern contributions in the east. Herodotus gives three versions of their origins, none of them verifiable: a legend of a hero, **Targitaus**, from whom the Scythians descended, golden objects fallen from the sky (a plough, a yoke, an axe and a cup), and a version in which the Scythians were pushed west by the Massagetae and crossed the river Araxes (IV.5–12).',
  { h: 'Why they matter' },
  { lista: [
    '**Equestrian nomadism:** they show how a people without cities, but with horses, herds and bows, could dominate an immense territory for centuries.',
    '**Herodotus:** his Book IV is the first ethnographic portrait of a “barbarian” people, with famous scenes (the blood, the scalps, the hemp), and a good example of the limits of a Greek source.',
    '**Gold and the animal style:** one of the great arts of Antiquity, directly linked to the later jewellery of Europe and Asia.',
    '**The kurgans:** tombs such as Arzhan 2, with more than 5,000 gold objects, or those of the Pazyryk culture, where ice preserved textiles, wood and even tattooed skin.',
    '**Darius’ war:** the episode in which the greatest empire of its day could not catch an enemy who would not be caught.',
    '**Women warriors:** the legend of the Amazons and the archaeology of women’s graves with weapons.'
  ] },
  { img: 'esc-cavaleiro-estepe', leg: 'Scythian horseman shooting a composite bow, 5th century BC; conjectural reconstruction. AI-generated illustration.' },
  { caixa: 'The Scythians today', texto: 'The Scythians vanished as a people, but not from memory. Their **gold** is a national symbol in **Ukraine** and **Russia**, and was even the object of a legal dispute between museums after the Russian annexation of Crimea (2014). The **Ossetians**, in the Caucasus, speak the only Iranian language of steppe origin to have survived, descended from that of the **Alans**, a Sarmatian branch. In the 20th century the Russian poet **Aleksandr Blok** wrote a poem, *The Scythians* (1918), in which Russia casts itself as a “Scythian” between Europe and Asia. And “Scythian” still serves, in several languages, to mean “warrior of the steppe”.' }
];

const linha = [
  'This timeline follows the Scythians and their relatives, the Saka and the Sarmatians, from the Iron Age to the destruction of the last Scythian kingdom in Crimea. Whenever a date comes **only from Herodotus** or a late author, it is marked “tradition”.',
  { linha: [
    { d: 'c. 900 – 800 BC', t: 'The first kurgans', x: 'In **Tuva** (southern Siberia), the tomb of **Arzhan 1**, an enormous circular kurgan of stone and timber about 110 m across, excavated in the 1970s by Mikhail Gryaznov, is radiocarbon-dated to c. 800 BC. It holds bronze weapons, harness and pieces with animals (stag, boar, feline): the “Scythian triad” already appears. It is the oldest known tomb of this kind, but Tuva’s status as the Scythians’ “cradle” is debated.' },
    { d: 'c. 720 – 650 BC', t: 'Cimmerians and Scythians', x: 'According to Herodotus (IV.11–12), the Scythians, pushed west, took the steppe from the **Cimmerians**, who fled to Anatolia. Assyrian sources speak of the “*Ishkuzai*” (Scythians): the chief **Ishpakaya** appears as an adversary of King **Esarhaddon** (c. 679), and King **Bartatua** (Herodotus’ *Protothyes*), an ally of Assyria, asked for one of the king’s daughters in marriage (c. 670). This is the first time the Scythians appear in written documents.' },
  ] },
  { img: 'esc-arzhan', leg: 'View of the Arzhan plain in Tuva (southern Siberia), site of the Arzhan kurgans, among the oldest of the Scythian world.' },
  { linha: [
    { d: 'c. 650 – 600 BC', t: 'Arzhan 2 and “Asian Scythia”', x: 'In the Tuva valley, the **Arzhan 2** kurgan (excavated by the Russian-German team of Konstantin Chugunov and Hermann Parzinger in 2000–2004) held a royal couple and sixteen sacrificed attendants, with about **5,700 gold objects** (c. 20 kg), Baltic amber and weapons. The date is c. 650–600 BC. The wealth shows an already organised power.' },
    { d: 'c. 650 – 590 BC (tradition)', t: 'Scythians in Media and the Levant', x: 'According to Herodotus (I.103–106), the Scythians, led by **Madyes**, son of Protothyes, dominated Asia for **28 years**, invaded Media, reached Palestine (as far as **Ashkelon**) and were held off by the pharaoh Psammetichus with gifts. Herodotus says **Cyaxares**, king of Media, made them drunk at a banquet and killed them (legend or exaggeration). A small Scythian presence in the Near East is likely; the 28-year rule is almost certainly a simplification.' },
    { d: 'c. 650 – 500 BC', t: 'The Greek colonies and trade', x: 'Greek settlers from **Miletus** found **Olbia** (c. 647, at the mouth of the Bug and the Dnieper) and **Panticapaeum** (c. 600, at Kerch), and later **Chersonesos**, in Crimea (422/421). The Greeks buy grain, hides, slaves, fish and honey from the Scythians, and sell wine, olive oil, pottery and worked metals. This is where **Greco-Scythian gold** is born.' },
  ] },
  { linha: [
    { d: '6th century BC', t: 'The Kelermes kurgans', x: 'In the North Caucasus, the **Kelermes** kurgans (c. 600 – 550 BC), excavated from 1903, revealed a **gold-covered mirror**, a sword with a gold sheath and a gold **panther**, in a style mixing Assyrian, Greek and steppe themes: they prove that the Scythian elite was linked to the whole Orient.' },
    { d: 'c. 530 BC (tradition)', t: 'Tomyris and Cyrus', x: 'According to Herodotus (I.205–214), the Persian king **Cyrus the Great**, attacking the **Massagetae**, a people related to the Saka east of the Caspian Sea, is defeated and killed by Queen **Tomyris**, who is said to have put his head in a wineskin of blood. Herodotus admits there are other versions (Xenophon says Cyrus died in his bed), but Tomyris’ is the most famous. Cyrus’ death in combat in the north is plausible; the rest is legend.' },
    { d: 'c. 513 BC', t: 'Darius’ campaign', x: 'The Persian king **Darius I** crosses the Bosporus and the Danube (on a bridge of boats built by Mandrocles of Samos) to punish the Scythians. According to Herodotus (IV.83–142), the Scythians withdraw, burn the pastures, stop up the wells and never accept battle; King **Idanthyrsus** sends Darius a bird, a mouse, a frog and five arrows, which the king reads as surrender and his adviser Gobryas as a threat. Darius returns without a clear victory. The **essentials are probable** (the campaign happened, and so did the Persian failure), but the detail of the narrative is Herodotus’.' },
  ] },
  { img: 'esc-tumulo-ciro', leg: 'Tomb of Cyrus the Great at Pasargadae (Iran): the king who, according to Herodotus, died fighting the Massagetae, c. 530 BC.' },
  { img: 'esc-campanha-dario', leg: 'Scorched earth: Scythian horsemen withdrawing before the Persian army, c. 513 BC; conjectural scene. AI-generated illustration.' },
  { img: 'esc-behistun', leg: 'Relief and inscription of Behistun (Iran), of Darius I, c. 520 BC: the last prisoner in the row, in a pointed hat, is the Saka chief Skunkha.' },
  { linha: [
    { d: '5th century BC', t: 'Herodotus visits the Pontic coast', x: 'The Greek historian **Herodotus** probably visits Olbia (c. 450 BC) and gathers what will become **Book IV** of the *Histories*: Scythian tribes, rivers, gods, funerals and customs. His information comes from Greeks of Olbia, from merchants and from local contacts, not from long observation; so it mixes facts that archaeology has confirmed with fabulous things (werewolves, goat-footed peoples).' },
    { d: 'c. 480 BC', t: 'The Bosporan kingdom', x: 'On the Strait of Kerch the **Bosporan kingdom** is born, a state of Greek cities and local populations with its capital at Panticapaeum, which for centuries will be the Scythians’ great partner and neighbour, supplying grain to Athens. Scythian kings and chiefs buy works from Greek goldsmiths.' },
    { d: '4th century BC', t: 'The peak of the royal kurgans', x: 'The great royal tombs of the lower Dnieper: **Solokha** (c. 400, excavated in 1912–13), **Kul-Oba**, at Kerch (c. 350, opened in 1830), **Chertomlyk** (c. 350 – 320, 1863) and **Tovsta Mohyla** (c. 350 – 300, excavated in 1971, with the **gold pectoral** now in Kyiv). They are full of gold, weapons and objects made by Greeks for Scythian clients.' },
  ] },
  { img: 'esc-kul-oba-vaso', leg: 'Drawing of the electrum vase from Kul-Oba (4th century BC): Scythians treating a tooth, stringing a bow and bandaging a wound; a modern engraving.' },
  { img: 'esc-pectoral-tovsta', leg: 'Gold pectoral from Tovsta Mohyla (Dnipropetrovsk), c. 350–300 BC, Museum of Historical Treasures of Ukraine, Kyiv.' },
  { linha: [
    { d: 'c. 340 – 339 BC', t: 'Ateas and Philip II', x: 'The Scythian king **Ateas**, already very old (authors speak of about 90 years), rules the lands between the Dnieper and the Danube. He comes into conflict with **Philip II of Macedon**, who defeats him in 339 BC, near the Danube; Ateas dies in battle. According to the Roman historian Justin, Philip took 20,000 young captives and as many thoroughbred mares. It is the end of the last great Scythian monarchy of Europe.' },
    { d: 'c. 331 BC', t: 'Zopyrion’s disaster', x: 'Zopyrion, Alexander the Great’s governor of Thrace, attacks Olbia with an army and is killed, with his men, by the Scythians, according to Justin (the date, c. 331, varies). In 329, Alexander defeated the **Saka** (whom the Greeks called Scythians “beyond the Tanais”) at the river **Jaxartes** (Syr Darya).' },
    { d: '5th – 3rd century BC', t: 'Pazyryk and the ice tombs', x: 'In the **Altai**, the **Pazyryk** kurgans (excavated by Sergei Rudenko, 1929 and 1947–49) and those of the **Ukok** plateau preserved, in the ice, textiles, carpets, carved wood and **tattooed bodies**. They are not “Scythians” in the strict sense, but they illustrate the same world of mounted nomads, and prove trade with Persia and China (silks, bronzes).' },
  ] },
  { img: 'esc-pazyryk-tapete', leg: 'Reproduction of a Pazyryk carpet (maker Megerian, Armenia): the original, c. 5th–4th century BC, Hermitage, is the oldest surviving knotted carpet.' },
  { linha: [
    { d: '4th – 3rd century BC', t: 'The “Golden Man” of Issyk', x: 'Near Almaty, in Kazakhstan, the **Issyk** kurgan (excavated in 1969 by Kemal Akishev) held a young person buried in a costume covered with about **four thousand gold pieces**, and a tall pointed hat, in line with Persian depictions of the Saka. It is one of Kazakhstan’s national symbols (the sex of the deceased, man or woman, is debated).' },
    { d: 'c. 300 – 200 BC', t: 'The Sarmatians arrive', x: 'The **Sarmatians**, Iranian-speaking nomads from east of the Don, advance westward and occupy the Pontic steppe. The Scythians are reduced to a lesser state, in **Crimea** and the Dobruja (Scythia Minor). Herodotus told how the Sarmatians descended from Amazons and Scythians.' },
    { d: 'c. 200 – 110 BC', t: 'Skilouros and Neapolis', x: 'In Crimea (near Simferopol), the capital **Scythian Neapolis** is a fortified centre, with stone houses and mausoleums, and the kings **Skilouros** and **Palakos** (2nd century BC) left coins and monuments. In c. 110 BC, the general **Diophantus**, of Mithridates VI of Pontus, defeats the Scythians of Crimea, who fall under the rule of Pontus.' },
  ] },
  { img: 'esc-issyk', leg: 'Replica of the headdress of the Issyk “Golden Man”, Kazakhstan, 4th–3rd century BC: the costume was covered with thousands of gold plaques.' },
  { img: 'esc-neapolis', leg: 'Scythian Neapolis, near Simferopol, in Crimea: capital of the last Scythian kings (3rd century BC – 3rd century AD).' },
  { img: 'esc-escilurus-relevo', leg: 'The Scythian king Scilurus and the bundle of rods (an anecdote from Plutarch): an engraved medal of the modern era.' },
  { linha: [
    { d: 'c. AD 175', t: 'Sarmatians in the Roman army', x: 'According to Cassius Dio, the emperor **Marcus Aurelius**, at the end of the Marcomannic wars, required the **Iazyges** Sarmatians to supply 8,000 horsemen, of whom 5,500 were sent to Britain. It is one of the first uses of steppe heavy cavalry in the Roman army. According to a controversial hypothesis, here lay one of the origins of the Arthurian legends.' },
    { d: 'c. AD 250 – 260', t: 'The Goths destroy Neapolis', x: 'The **Goths**, coming from north of the Black Sea, take Crimea and burn Scythian Neapolis, which is never rebuilt. The last Scythians mix with the newcomers and with the Greeks of the Bosporus. In the 370s the **Huns** finally crush the Alans and the steppe passes to another people.' },
    { d: '1st century BC – 4th century AD', t: 'Saka in India', x: 'Peoples of Saka origin (the **Indo-Scythians**) enter Bactria and north-western India from c. 150 BC. King **Maues** (c. 85 BC) founds the first Indo-Scythian state; the Western Satraps rule Gujarat until about AD 400. The “Saka era” (AD 78), still used in India’s national calendar, has a debated origin.' }
  ] },
  { h: 'Rediscovery' },
  'Modern interest in the Scythians begins with **Peter the Great**, who received, in 1715, gold from Siberian tombs (the “Siberian collection”), the core of the present holdings of the **Hermitage**. In the 19th century, excavations of kurgans in Crimea and on the Dnieper (**Kul-Oba**, 1830; **Chertomlyk**, 1863) showed the royal wealth. In the 20th century, **Sergei Rudenko** (Pazyryk, 1940s), **Boris Mozolevsky** (Tovsta Mohyla, 1971) and **Natalia Polosmak** (Ukok, 1993) opened the tombs of ice and of gold. In the 21st century the German-Russian excavations at **Arzhan 2** (2000–2004) and genetics are rewriting the people’s origins.'
];

const mapa = [
  'The Scythian “map” is above all a map of **rivers, kurgans and Greek ports**. The Scythians had no great cities, apart from the final phase (Neapolis); it was the **Greeks** who founded cities on the Black Sea shores, and it is through them that the Scythian world appears in the sources. The main ones are these:',
  { tabela: { cab: ['Place', 'Where (today)', 'When', 'Importance'], linhas: [
    ['Arzhan', 'Tuva, southern Siberia (Russia)', 'c. 800 and c. 650–600 BC', 'Two royal kurgans: the oldest and the richest of early Scythian culture'],
    ['Kelermes', 'North Caucasus (Russia)', 'c. 600 – 550 BC', 'Tombs with gold of great richness; links to the East'],
    ['Olbia', 'Mykolaiv, Ukraine', 'c. 647 BC – 4th century AD', 'Greek colony of Miletus at the mouth of the Bug; port where Herodotus probably gathered information'],
    ['Panticapaeum', 'Kerch, Crimea', 'c. 600 BC – 4th century AD', 'Capital of the Bosporan kingdom; exported grain; Greek goldsmiths'],
    ['Chersonesos', 'Sevastopol, Crimea', 'c. 422 BC – 14th century', 'Greek colony in south-western Crimea, near the Taurians'],
    ['Tanais', 'Mouth of the Don (Russia)', '3rd century BC – 5th century AD', 'Trading post of Greeks, Scythians and Sarmatians at the mouth of the Don'],
    ['Solokha, Chertomlyk and Tovsta Mohyla', 'Lower Dnieper (Ukraine)', '4th century BC', 'The great royal kurgans, with the most famous gold'],
    ['Pazyryk and Ukok', 'Altai (Russia, Kazakhstan)', '5th – 3rd century BC', 'Ice tombs, with textiles, wood, carpets and tattooed bodies'],
    ['Issyk', 'Near Almaty, Kazakhstan', '4th – 3rd century BC', 'The “Golden Man” of the Saka'],
    ['Scythian Neapolis', 'Simferopol, Crimea', '3rd century BC – c. AD 260', 'Capital of the last Scythian kingdom; mausoleums; walls']
  ] } },
  { h: 'The steppe and the Danube' },
  'The Scythian space has a simple, hard geography: the **steppe** begins at the Danube and runs, north of the Black Sea, to the Don and the Volga. The rivers flow from north to south and helped define tribes (Herodotus speaks of the rivers Ister, Tyras, Hypanis, Borysthenes, Panticapes, Hypacyris, Gerrhus and Tanais, that is, the Danube, Dniester, Bug, Dnieper and several tributaries), while the forests to the north and the Caucasus mountains to the south limited expansion. Along the rivers the **kurgans** are scattered: mounds of earth, sometimes 20 m high, that still dot the Ukrainian landscape.',
  { img: 'esc-estela-kurgan', leg: 'Stone stele of a warrior on a steppe, of the “kamennaya baba” type: stone figures accompanied kurgans (from the 6th century BC onward, and later).' },
  { h: 'Olbia: the grain port' },
  '**Olbia** (in Greek, “the Fortunate”) was founded by Miletus around 647 BC, on a peninsula in the estuary of the Bug and the Dnieper. It became the main point of contact between Greeks and Scythians: the Greeks brought **wine**, olive oil, pottery and cloth and took away **grain**, hides, fish and slaves. Olbia paid gifts and tribute to the Scythian kings, and Herodotus probably passed through. The ruins are near Parutyne, in Mykolaiv.',
  { h: 'The Bosporus and Crimea' },
  'On the Strait of **Kerch**, **Panticapaeum** was the capital of the **Bosporan kingdom**, a Greco-Scythian state that exported **grain** to Athens. In the kurgans around the city, the rich were buried with gold made by Greek goldsmiths, such as the **Kul-Oba** vase. Further south, **Chersonesos** (now Sevastopol) was a Dorian colony, founded c. 422 BC. Inland, the Crimean mountains belonged to the Taurians and, later, to the last Scythian tribes.',
  { img: 'esc-panticapeu', leg: 'Panticapaeum, today Kerch, in Crimea: capital of the Bosporan kingdom, seen from Mount Mithridates.' },
  { h: 'Scythian Neapolis' },
  '**Scythian Neapolis** (“new city”), near Simferopol, was the capital of the last Scythian kingdom, between the 3rd century BC and c. AD 260. It is a real **fortified city**, with stone walls, houses, workshops and two mausoleums of nobles (one of them, c. 115 BC, held the body of a king, possibly **Skilouros**, with a gold cap). It shows a society already settled and much Hellenised, very different from Herodotus’ nomads.',
  { img: 'esc-neapolis-reconstrucao', leg: 'Scythian Neapolis in the 2nd century BC, with walls, stone houses and a mausoleum; conjectural reconstruction. AI-generated illustration.' },
  { h: 'The Altai and the Saka' },
  'In the **Altai** and in **Tuva**, the permafrost of the kurgans preserved textiles, wood and bodies, something not found in Ukraine. This is the region of the oldest tombs of Scythian culture (**Arzhan**) and of the best preserved (**Pazyryk**, **Ukok**). East of the Aral Sea, **Issyk** and other kurgans in Kazakhstan show the same tradition among the Saka.',
  { img: 'esc-ukok', leg: 'The Ukok plateau, in the Altai: an area where ice kurgans preserved bodies and textiles (for example, the “Ukok Princess”).' },
  { h: 'Routes' },
  'The Scythians served as **intermediaries** between the Greeks of the Pontus and the peoples of the north, and between Europe and Asia. There was a route from the **Danube** to the **Don**, another across the **steppe** to Central Asia, anticipating the future Silk Road, and a river route to the northern forests. Herodotus (IV.21–24) describes peoples further north, such as the **Budini** and the **Argippaei**, and from there a trade “road” to the Ural mountains. Gold, amber, furs, slaves, horses, bronze, wine and, later, silk moved across the steppe.'
];

const sociedade = [
  { h: '1. Political organisation' },
  'The Scythians were a **confederation of tribes**, not a bureaucratic state. Herodotus (IV.20) distinguishes the **Royal Scythians** (the dominant group, who considered themselves lords of the others), the **nomad** Scythians and the **farming** Scythians, who cultivated the fields north of the Black Sea and sold grain to the Greeks. The kings, held to descend from the gold fallen from the sky, had religious and military power; in moments of crisis, such as Darius’ invasion, Herodotus (IV.119–120) speaks of an assembly of three kings (Idanthyrsus, Scopasis and Taxacis) who organise the defence together.',
  'Power rested on **livestock**, **gold**, clan ties and, above all, the ability to bring mounted warriors. According to Herodotus (IV.68), the most solemn oath was sworn by the **king’s hearth**, and diviners found to have sworn falsely were put to death. It was a mobile, flexible system, and that was its strength.',
  { img: 'esc-acampamento', leg: 'Scythian summer camp, with felt-covered wagons and herds; conjectural reconstruction. AI-generated illustration.' },
  { h: '2. Social classes' },
  { lista: [
    '**Royalty and warrior aristocracy:** kings and clan chiefs, buried in kurgans with gold, weapons and horses.',
    '**Free warriors:** most men were mounted archers, and had the right to take part in assemblies.',
    '**Priests and diviners:** they read the future in bundles of willow rods (Herodotus, IV.67); Herodotus and Hippocrates also describe the *Enarees*, men who lived as women, a much-discussed description.',
    '**Herders, farmers and craftsmen:** those who tended the herds, cultivated the fields and worked metal and leather.',
    '**Slaves:** prisoners of war and purchased, also sold to the Greeks; Herodotus (IV.2) says they blinded slaves to milk the mares, which is probably an exaggeration.'
  ] },
  { h: 'Scythian women and the Amazons' },
  'Scythian women played a visible role: **priestesses**, queens and, in some tombs, **warriors**. The Greek legend of the **Amazons**, warrior women, daughters of Ares, is linked to the Scythians: Herodotus (IV.110–117) tells how the Amazons, defeated by the Greeks, were captured, escaped and married young Scythians, giving rise to the **Sarmatians**, whose women “hunt on horseback, go to war and wear men’s clothing”, and do not marry before killing an enemy. This story is **legend**. Archaeology shows, however, that in a share of the women’s graves of the steppe, of the Sarmatians and the earliest nomads (about **20%**, according to an estimate by Jeannine Davis-Kimball, which is disputed), there are weapons (arrows, daggers, sometimes spears). That does not prove they fought in armies, but it suggests that some women knew how to use weapons, and that the Amazon model has some real basis.',
  { img: 'esc-guerreira', leg: 'Scythian woman warrior with bow and dagger, 4th century BC; reconstruction based on women’s graves with weapons. AI-generated illustration.' },
  { img: 'esc-amazonomaquia', leg: 'Amazonomachy: combat between Greeks and Amazons, relief from a Greek sarcophagus. The Amazons were shown in Scythian-type dress.' },
  { h: '3. Religion' },
  'According to Herodotus (IV.59), the Scythians venerated above all **Tabiti**, goddess of fire and the hearth, the most important (whom he says is equivalent to Hestia), and then **Papaios** (like Zeus), **Api** (the Earth), **Goitosyros** (Apollo), **Argimpasa** (Aphrodite Urania) and **Thagimasadas** (Poseidon). A god of war was worshipped in the form of an **iron sword** (*akinakes*) planted in a pile of brushwood, where horses, cattle and, for every hundred prisoners of war, one man were sacrificed. The equivalences with Greek gods are Herodotus’ and can mislead.',
  { tabela: { cab: ['Deity (according to Herodotus)', 'Greek equivalent', 'Role'], linhas: [
    ['Tabiti', 'Hestia', 'Goddess of fire and the hearth; the most venerated; linked to kingship'],
    ['Papaios', 'Zeus', 'Father of the gods, husband of Api'],
    ['Api', 'Gaia', 'The Earth'],
    ['Goitosyros', 'Apollo', 'Solar god'],
    ['Argimpasa', 'Aphrodite Urania', 'Heavenly goddess of love'],
    ['Thagimasadas', 'Poseidon', 'God of the waters (of the rivers?)'],
    ['Sword-god', 'Ares', 'God of war, venerated in the form of an iron sword']
  ] } },
  { h: 'The blood oath, scalps and skull cups' },
  'Herodotus describes rituals that impressed (and scandalised) the Greeks. In the **blood oath** (IV.70), the parties cut themselves, poured blood into a cup of wine, dipped into it a sword, arrows, an axe and a javelin, and drank it. On the battlefield, the warrior **scalped** the dead enemy and kept the scalp as a trophy (IV.64), and from the skulls of the most hated made **cups** lined with gold (IV.65). These customs are plausible (there are cut skulls in kurgans, and skull cups among other steppe peoples), but the general description comes from a Greek speaking of “barbarians”, with its measure of exaggeration.',
  { img: 'esc-juramento-sangue', leg: 'Blood oath between two Scythian chiefs, according to Herodotus (IV.70); conjectural scene. AI-generated illustration.' },
  { h: 'Hemp and the Scythian “sauna”' },
  'Herodotus (IV.73–75) describes a purification ritual after funerals: the Scythians set up a small **felt tent** over three poles, put inside a vessel of red-hot stones and threw **hemp seeds** on it, which smoked: “the Scythians, breathing this vapour, howl with pleasure”. Archaeology has confirmed the account: in the **Pazyryk** kurgans (Altai), **wooden tripods** with felt covering, bronze braziers, burnt stones and leather bags with hemp seeds were found. Scholars disagree about whether it was only purification or also a trance rite, and about how much psychoactive substance the vapour contained; the ritual use of hemp itself is well demonstrated.',
  { img: 'esc-cannabis', leg: 'Hemp plant (*Cannabis sativa*), whose seeds the Scythians burned in rituals, according to Herodotus and the Pazyryk finds.' },
  { img: 'esc-sauna-cannabis', leg: 'Hemp-vapour rite in a felt tent, according to Herodotus (IV.73–75); conjectural reconstruction. AI-generated illustration.' },
  { h: 'Death and the king' },
  'A king’s funeral was an enormous ceremony. According to Herodotus (IV.71–72), the body was **embalmed** with wax and aromatic herbs and carried by wagon among all the tribes, and each tribe sacrificed horses and cut off an ear or part of its hair in mourning. Finally the king was buried in a timber chamber, with a concubine, the cupbearer, the cook, the groom, the messenger and strangled **horses**, and a great mound was raised. A year later **fifty young men** and fifty horses were strangled, stuffed and set upright around the tomb (this too is known only from Herodotus, but the royal kurgans, with **Arzhan 2**, **Solokha** and **Chertomlyk**, confirm the sacrifices of attendants and horses).',
  { img: 'esc-funeral-real', leg: 'Funeral of a Scythian king, with the embalmed body and sacrificed horses, according to Herodotus (IV.71–72); conjectural reconstruction. AI-generated illustration.' },
  { h: '4. Economy' },
  'The economy was mixed: **herding** (horses, sheep, cattle, goats), **farming** (the farming Scythians of the Bug and the Dnieper grew wheat and barley), **hunting** and **trade** with the Greeks. **Horses** were the most precious possession; mares gave milk and meat, and stallions served as mounts and sacrifices. The Dnieper **grain**, exported through the Bosporus, fed Athens, and the Scythians received in return **wine**, pottery, textiles and worked **gold**. Coinage was rare: only late kings, such as Skilouros, left issues with their names.',
  { h: '5. Writing and language' },
  'The Scythians **left no literature**. Their language, **Eastern Iranian**, is known only from names of people, tribes and rivers (for example, Herodotus translates *oior* “man” and *pata* “kill”, in the Amazons’ name, *oiorpata*, “man-killers”) and from some short inscriptions in Greek letters. They used **tamgas** (clan marks) to signal ownership on objects and on horses. Oral memory, in poems and genealogies, was lost, and the tradition about the Scythians was almost all written by Greeks and Persians. So a useful warning: all the “Scythian data” on customs and beliefs is, ultimately, **a foreigner’s view**.',
  { h: '6. Home and daily life' },
  'The **wagon** was the mobile home par excellence: a wooden platform on wheels, covered by a **felt** tent (Herodotus IV.46 says the women and children lived in them). Men on horseback drove the herds. The farming Scythians and those of the late phase lived in villages and houses of stone and brick. In the camps there were fires, bronze cauldrons and tents, and a world of leather, felt and wool.',
  { h: '7. Food' },
  { lista: [
    '**Mare’s milk** (and its fermented derivative, *kumis*): the typical drink, for which the Greeks found a name, *hippace* (mare’s cheese).',
    '**Meat:** horse, sheep and ox, cooked in bronze cauldrons or, according to Herodotus (IV.61), inside the animal’s **own stomach**, heated with its bones as fuel.',
    '**Cereals and porridges:** grown by the farming Scythians.',
    '**Wine:** bought from the Greeks and drunk undiluted, which the Greeks thought barbaric (to drink “the Scythian way” meant to drink to excess).',
    '**Fish and game:** from the rivers and their banks.'
  ] },
  { h: '8. Clothing' },
  'The Scythians wore **trousers** (a novelty to Greeks and Romans), tunics of wool or leather, decorated coats, soft boots and a **conical felt hat** (the *kyrbasia* or *bashlyk*). The pointed-hat Saka (*tigraxauda*) are shown in Persian reliefs. Elite clothes were **covered with gold plaques** sewn onto the fabric, as seen at Issyk, Kul-Oba and Tovsta Mohyla. At Pazyryk, the ice preserved trousers, felt boots, fur cloaks and decorated socks.',
  { img: 'esc-persepolis-saka', leg: 'Relief from the Apadana staircase at Persepolis (c. 500 BC): delegations of the empire; some have been identified as Saka, in pointed hats.' },
  { h: '9. Art: gold and the animal style' },
  'The Scythian **animal style** is the signature of the culture: figures of **stags**, **horses**, **panthers**, **griffins**, **birds of prey** and coiled animals, with twisted bodies and folded limbs, in gold, bronze, wood, leather and felt. It served to decorate harness, weapons, vessels, clothes and tombs. Among the best examples are the **gold stag** of Kostromskaya (c. 600 BC, Hermitage), the **Solokha comb**, the **Tovsta Mohyla pectoral** and the **Kul-Oba electrum vase**, the work of **Greek goldsmiths** for Scythian clients, with realistic scenes of Scythians in which one sees the face, hair, clothing and bow.',
  { img: 'esc-cervo-ouro', leg: 'Gold stag in Scythian style, 7th–6th century BC, found at Tápiószentmárton (Hungary).' },
  { img: 'esc-ourives', leg: 'Greek goldsmiths of Panticapaeum working a piece of gold for a Scythian client, 4th century BC; conjectural reconstruction. AI-generated illustration.' },
  { h: '10. Tattoos, felt and carpets: Pazyryk' },
  'At **Pazyryk** and **Ukok**, the combination of climate and ice preserved everything normally lost: **carpets**, embroidered felts, Chinese silk fabrics, wooden wagons, saddles, horse masks and **tattooed bodies**. The Pazyryk carpet (c. 5th–4th century BC) is the **oldest surviving knotted carpet**; its origin (Persian, Armenian or Central Asian) is debated. The **tattoos** of men and women (fantastic animals, stags, griffins and felines, made with soot and applied with bone needles) prove that **animal art** was not only on objects but on skin: they were signs of status and, perhaps, of protection. The **“Ukok Princess”**, discovered by **Natalia Polosmak** in 1993, was about 25, had tattoos on her shoulders and arms, and was buried with six horses; her body has since also become a political matter, and the Altai people demand its return to the earth.',
  { img: 'esc-tatuagem-pazyryk', leg: 'Pazyryk tattooist decorating a warrior’s arm with fantastic animals; conjectural reconstruction. AI-generated illustration.' },
  { h: '11. War' },
  'The Scythians were **horsemen and archers**. Their **composite bow** (of wood, bone and sinew, short and powerful) was shot from horseback, and the arrows, of **trilobate bronze**, came from a special quiver, the **gorytos**, which also held the bow. They used the **axe** (*sagaris*), the **short sword** (*akinakes*), scale armour and bronze helmets. They had no stirrups (those come later), but could ride and manoeuvre with felt saddles. The Greeks believed the arrows were **poisoned**, and there is some basis for this, though the details are debated.',
  'Their **tactic** was one of retreat and attrition: attack from afar, withdraw, burn the land, stop the wells and let the enemy die of hunger and thirst, just as Herodotus describes (IV.120–127) with Darius. The Scythians were therefore **invincible on their own steppe**, and vulnerable when one tried to fight them head on, as the fate of Ateas shows.',
  { img: 'esc-arco-composto', leg: 'Reconstructed composite bow (Novgorod Kremlin Museum): a steppe-type weapon of wood, bone and sinew.' },
  { h: '12. Science and technology' },
  'The Scythians left no written science, but they mastered a series of **techniques**: **horse taming and breeding**, **felt**, **metallurgy** (bronze cast in moulds, iron, gold with filigree and granulation), **wagon building** and **tomb engineering**, with timber chambers, false tombs and hidden exits against robbers (Arzhan 2). The Greek **Anacharsis** is, according to tradition, a Scythian sage, and **Hippocrates** wrote in *Airs, Waters, Places* one of the first medical portraits of the Scythian body, attributing to it a “soft” and moist character, explained by the climate and the habit of riding. It is a text of great historical value, but of weak medical science.'
];

const personalidades = [
  'Hardly any Scythian left us his name in writing: the names we know come from Greeks and Persians, and many of the figures below live on the border between history and legend. Real and legendary figures are marked.',
  { h: 'Herodotus of Halicarnassus (c. 484 – c. 425 BC)' },
  'The “father of history” and the main source on the Scythians. His **Book IV** describes the territory, the rivers, the tribes, the gods, the funerals and Darius’ campaign. It must be read with care: he used Greek informants, and had a taste for wonder and the picturesque. Much of what he writes has been confirmed by archaeology (the hemp, the sacrifices at funerals, the weapons), and other parts are no more than rumour.',
  { img: 'esc-herodoto', leg: 'Bust of Herodotus (Cameron Gallery, Tsarskoe Selo, Russia).' },
  { h: 'Targitaus (legend)' },
  'First king of the Scythians, according to the legend Herodotus (IV.5) gathered among the Scythians of the Pontus: son of Zeus and the daughter of the river Borysthenes. He had three sons, **Lipoxais**, **Arpoxais** and **Colaxais**, and when a plough, a yoke, an axe and a gold cup fell from the sky, only the youngest could touch them without their burning, and became king. It is a founding legend, of no historical value, but it shows that the Scythians tied kingship to gold.',
  { h: 'Idanthyrsus (c. 513 BC)' },
  'The Scythian king who, according to Herodotus, answered Darius with a bird, a mouse, a frog and five arrows, and, to the demand that he fight or submit, declared he would fight only for the tombs of his fathers. His name appears in Iranian form (*Indathyrsos*). He probably existed as a chief, but the words attributed to him belong to Herodotus’ narrative.',
  { h: 'Darius I (c. 550 – 486 BC)' },
  'King of the Persians and organiser of the Achaemenid empire. His Scythian campaign (c. 513 BC), the first Persian expedition to eastern Europe, is told by Herodotus as a failure, while the **Behistun** inscription, for its part, shows **Skunkha**, the captured Saka chief, as part of the celebration of his triumphs. It is a good example of how sources can diverge.',
  { h: 'Tomyris (legend and history, 6th century BC)' },
  'Queen of the **Massagetae**, a people east of the Caspian Sea. According to Herodotus (I.205–214), she refused to marry Cyrus and, after he tricked her son **Spargapises**, who killed himself in shame, she defeated the Persian king and **plunged his head into a wineskin of blood**, telling him: “I warned you I would sate you with blood.” Cyrus’ death, c. 530 BC, in combat in the north is probable; the wineskin episode is very probably legend.',
  { img: 'esc-tomiris-cena', leg: 'Tomyris before the body of Cyrus, according to Herodotus (I.214): legendary scene. AI-generated illustration.' },
  { h: 'Anacharsis (6th century BC, tradition)' },
  'A Scythian prince, son of a Greek mother, who is said to have visited Athens in the time of **Solon** and whom some Greek authors place among the **Seven Sages**. According to Herodotus (IV.76), he was killed by his brother, King **Saulius**, when he returned to Scythia and was caught performing a Greek rite to **Cybele**. The historicity of his life is debated, but his name remained a symbol of the “wise barbarian” of Greek tradition.',
  { h: 'Scyles (5th century BC)' },
  'A Scythian king with a Greek mother, who led two lives: at Olbia he dressed as a Greek and followed Greek rites, and on the steppe he lived as a Scythian. When his subjects found out, they rebelled, and he was beheaded (Herodotus, IV.78–80, c. 450). It shows the tension between the two worlds. A gold ring with the name *Skyles* in Greek letters, found in Romania, is sometimes linked to him (the identification is debated).',
  { h: 'Ateas (d. 339 BC)' },
  'The most famous historical Scythian king: he ruled the steppe between the Dnieper and the Danube. According to Plutarch, he said that the neighing of his horse pleased him more than the flute of the musician Ismenias. When the two kings met, in 339 BC, Ateas, about **90 years old**, died in combat. It is the most secure date in Scythian history.',
  { h: 'Madyes (7th century BC, tradition)' },
  'A Scythian king, son of Protothyes (Bartatua) and central figure of the tradition that has them dominate Asia for 28 years. According to Herodotus, **Cyaxares** ended Scythian power by making the chiefs drunk and killing them. The story is highly literary. What can be said is that there were Scythians active in Media and Anatolia in the 7th century BC.',
  { h: 'Skilouros (2nd century BC)' },
  'A Scythian king of Crimea, about whom Plutarch tells an anecdote: on his deathbed he gave an arrow to each of his 80 sons, and showed them that a bundle of arrows would not break. It is a Scythian version of the fable of unity, with no historical proof. What is certain is that there are coins with Skilouros’ name and a famous relief from Scythian Neapolis linked to his kingdom.',
  { h: 'Sergei Rudenko (1885 – 1969)' },
  'Russian archaeologist who excavated the Pazyryk kurgans between 1929 and 1949 and discovered, in the ice, the carpet, the textiles and the tattooed bodies. His monograph on the culture of the Altai nomads (1953) is a work of reference.',
  { h: 'Natalia Polosmak (b. 1956)' },
  'Russian archaeologist. In 1993, on the Ukok plain, she discovered the **“Ukok Princess”**, a woman of about 25, tattooed, with a felt headdress about 90 cm tall. Her team showed that the textiles, silks and wooden objects had links to China and Persia.',
  { h: 'Hermann Parzinger (b. 1959)' },
  'German archaeologist who directed, with Konstantin Chugunov, the excavation of **Arzhan 2** (2000–2004), one of the few great Scythian tombs found intact, with 5,700 gold objects. He is the author of synthesis works on the world of the Scythians and the steppes.',
  { h: 'Maues (c. 85 BC)' },
  'A Saka king who founded the first **Indo-Scythian** state in north-western India, in the Taxila region. His bilingual coins, with Greek and Indian deities, are the main source for this kingdom. He shows that the Saka did not stay only on the steppe.',
  { img: 'esc-moeda-maues', leg: 'Coin of the Indo-Scythian king Maues (c. 85 BC), with legends in Greek and Kharosthi.' }
];

const legado = [
  { h: 'What they left us' },
  { lista: [
    '**The animal style:** the art of coiled figures and twisted animals influenced the arts of the peoples of the Caucasus, Central Asia, the Celts (La Tène art has similarities) and, later, Germanic peoples and Vikings; the direct link is sometimes debated.',
    '**Cavalry:** the idea of using horses as a weapon of war, and the arms and harness that go with it, passed on to the Sarmatians, the Parthians, the Huns and the Mongols.',
    '**Trousers and the coat:** today, part of the world’s wardrobe; the Greeks saw them as barbarian clothing.',
    '**Hemp:** the Scythians were among the first to use it for ritual purposes, and science continues to study the use.',
    '**The image of the “barbarian”:** Scythia remained in Western culture as the archetype of the warrior, free and unpredictable people, through Herodotus and the poets.',
    '**The memory of the Amazons:** the legend, reinforced by discoveries of armed women’s graves, still feeds the imagination about women warriors.'
  ] },
  { h: 'Art' },
  'Scythian art divides into two worlds that touch: the **animal art of the steppe**, more abstract and stylised (plaques of horses and stags, felt and wood ornaments) and **Greco-Scythian art**, more naturalistic, by Greek goldsmiths (Kul-Oba, Solokha, Tovsta Mohyla, Chertomlyk) for the Scythian elite. The **Tovsta Mohyla pectoral** (c. 350 – 300 BC), of about 1.1 kg of gold, has three registers: at the bottom, steppe animals fighting, in the middle, flowers and birds, and at the top, Scythians sewing a hide, two men tending horses and cows and sheep being milked (scenes of daily life, of rare delicacy).',
  { h: 'Architecture' },
  'The Scythians left few buildings, but **earth monuments**: the **kurgans**, mounds that could be 20 m high, with timber or stone chambers, corridors, niches and galleries. Chertomlyk has cross-shaped chambers; Arzhan 2, a set of false tombs. At Scythian Neapolis, the mausoleums and walls are already of Greek type. On the steppes there are also **stone stelae** (*kamennye baby*), with human figures, partly linked to later peoples.',
  { h: 'The end of the Scythians' },
  'The Scythians were not exterminated: they were **absorbed**. The pressure of the **Sarmatians** (from the 3rd century BC), of the expansion of the **Pontus** of Mithridates VI and of the **Goths** (3rd century AD), and finally of the **Huns** (4th century AD), reduced their territory to nothing. The last Scythians mixed with Sarmatians, Goths, Greeks and, later, Slavs. The **Alans**, a branch of the Sarmatians, wandered across Europe as far as the Iberian Peninsula, where, in 409, they entered with the Suevi and Vandals; the **Ossetians** of the Caucasus are today their linguistic heirs.',
  { h: 'The Sarmatians, the successors' },
  'The **Sarmatians** (in Greek, *Sauromatai* or *Sarmatai*), Iranian-speaking nomads, are the great people who replace the Scythians on the Pontic steppe, from c. 300 BC. Among them stand out the **Roxolani**, the **Iazyges** (who fought Rome on the Danube) and the **Alans**. They used **heavy cavalry**, with lance and scale armour, for man and horse (the *cataphracts*), and their tradition of women warriors was noted by Greek authors. The Romans adopted their cavalry, and the link of the Sarmatians to the Arthurian legends (the hypothesis of Scott Littleton and Linda Malcor, 1994) is a **much-debated** theory.',
  { img: 'esc-sarmata-catafracta', leg: 'Sarmatian heavy cavalryman (cataphract), 2nd century AD; conjectural reconstruction. AI-generated illustration.' },
  { h: 'Rediscovery' },
  'Scythian gold is today one of the great collections of ancient art: the **Hermitage** (St Petersburg), the **Museum of Historical Treasures of Ukraine** (Kyiv), the museums of Kazakhstan, Tuva and the Altai. In 2014, after the Russian annexation of Crimea, a set of pieces from Crimean museums, which were on show in an Amsterdam museum, became the object of a long legal battle between Ukraine and the museums of the peninsula. Today’s science, with **radiocarbon**, ancient DNA and isotope studies, keeps refining what we thought we knew about the Scythians.',
  { caixa: 'Where to see the Scythians', texto: 'At the **Hermitage**, in St Petersburg, the “Gold Room” (Pazyryk, Solokha, Kul-Oba, Chertomlyk). At the **Museum of Historical Treasures of Ukraine**, in Kyiv, the Tovsta Mohyla pectoral. In **Kazakhstan**, the “Golden Man” of Issyk. In the **Altai**, the museums of Gorno-Altaysk, with finds from Ukok and Pazyryk. In **Crimea**, Scythian Neapolis (Simferopol) and Chersonesos. At the **British Museum**, the Oxus Treasure (Achaemenid, with echoes of steppe art). In the kurgans of the Dnieper and of Tuva, the best thing is to see the **landscape**.' }
];

const quiz = [
  { p: 'What did the Persians call the Scythians and their relatives in Central Asia?', op: ['Skolotoi', 'Saka', 'Sarmatai', 'Tyrrhenoi'], certa: 1, exp: 'The Persians called them Saka; the Greeks, Skythai; the Assyrians, Ishkuzai. Herodotus says they called themselves Skolotoi.' },
  { p: 'To which language family did the Scythians’ language belong?', op: ['Semitic', 'Turkic', 'Iranian (Indo-European)', 'Uralic'], certa: 2, exp: 'It was an Eastern Iranian language, known mainly from personal names and a few words recorded by the Greeks.' },
  { p: 'Which Greek historian wrote, in Book IV of the *Histories*, the most famous description of the Scythians?', op: ['Thucydides', 'Xenophon', 'Polybius', 'Herodotus'], certa: 3, exp: 'Herodotus, c. 430 BC, from information gathered mainly on the Black Sea coast, with the mixture of facts and legends that implies.' },
  { p: 'What are the great earthen tombs of the Scythians called?', op: ['Pyramids', 'Kurgans', 'Mastabas', 'Dolmens'], certa: 1, exp: 'Kurgans, burial mounds of earth, sometimes more than 20 m high, contain timber chambers, gold, weapons and horses.' },
  { p: 'What is the Scythian “animal style”?', op: ['A way of painting racehorses', 'An art of stylised animal figures, in gold and other materials', 'A type of music', 'A technique for taming lions'], certa: 1, exp: 'Stags, panthers, griffins and coiled animals decorate weapons, harness and gold objects, and are the mark of Scythian culture.' },
  { p: 'According to Herodotus, what did the Scythians do when Darius I invaded them, c. 513 BC?', op: ['Accepted battle and were defeated', 'Surrendered at once', 'Withdrew, burned the land and never accepted a decisive fight', 'Asked the Romans for help'], certa: 2, exp: 'The tactic of retreat and scorched earth wore out the Persians, who returned without a clear victory.' },
  { p: 'What was Idanthyrsus’ gift to Darius, according to Herodotus?', op: ['A bird, a mouse, a frog and five arrows', 'A gold crown', 'A white horse', 'A barrel of wine'], certa: 0, exp: 'Darius saw in it a sign of surrender; his adviser Gobryas read a threat.' },
  { p: 'Who, according to tradition, defeated and killed King Cyrus the Great, c. 530 BC?', op: ['King Ateas', 'Alexander the Great', 'Queen Tomyris of the Massagetae', 'King Skilouros'], certa: 2, exp: 'It is Herodotus’ version; other authors tell Cyrus’ death differently. The wineskin of blood episode is legend.' },
  { p: 'Which Scythian king died, aged about 90, fighting Philip II of Macedon in 339 BC?', op: ['Idanthyrsus', 'Ateas', 'Scyles', 'Madyes'], certa: 1, exp: 'Ateas, who ruled the steppe as far as the Danube, was defeated and killed by Philip, father of Alexander the Great.' },
  { p: 'What was found in the Pazyryk kurgans, in the Altai, that is rarely preserved?', op: ['Papyrus books', 'Textiles, carpets, wood and tattooed bodies, preserved in ice', 'Marble sculptures', 'Silver coins'], certa: 1, exp: 'The ice preserved the Pazyryk carpet, felts, saddles and tattoos of fantastic animals.' },
  { p: 'What did the hemp ritual described by Herodotus involve?', op: ['Throwing hemp seeds on hot stones, in a felt tent, and breathing the vapour', 'Making ropes for boats', 'Baking hemp bread', 'Painting the body with hemp'], certa: 0, exp: 'Pazyryk archaeology confirmed the tripods, braziers and hemp seeds.' },
  { p: 'In Herodotus, the Amazon legend is linked to which people, descended from Scythians and Amazons?', op: ['The Etruscans', 'The Sarmatians', 'The Huns', 'The Egyptians'], certa: 1, exp: 'Herodotus says the Sarmatians descend from Amazons and young Scythians. It is a legend, but there are women’s graves with weapons on the steppe.' },
  { p: 'Where was Scythian Neapolis, capital of the last Scythian kingdom?', op: ['In the Altai', 'In Crimea, near Simferopol', 'In Kazakhstan', 'In Anatolia'], certa: 1, exp: 'It was the capital of Skilouros and Palakos and was destroyed by the Goths around AD 260.' },
  { p: 'Which Iranian-speaking people replaced the Scythians on the Pontic steppe from c. 300 BC?', op: ['The Sarmatians', 'The Vikings', 'The Gauls', 'The Parthians'], certa: 0, exp: 'The Sarmatians (Roxolani, Iazyges, Alans) advanced from the Don westward and occupied the steppe.' },
  { p: 'Which famous gold piece, found in Ukraine in 1971, shows scenes of Scythian daily life?', op: ['The Mask of Agamemnon', 'The Tovsta Mohyla pectoral', 'The Persepolis Comb', 'The Treasure of Priam'], certa: 1, exp: 'The pectoral from the Tovsta Mohyla kurgan (c. 350–300 BC) is in the Museum of Historical Treasures of Ukraine, in Kyiv.' }
];

export default { visao, linha, mapa, sociedade, personalidades, legado, quiz };
