// FENÍCIOS E CARTAGO — conteúdo completo em português. A versão inglesa está em dados-en.js (mesma estrutura).
import EN from './dados-en.js';
import CRED from './creditos.js';
// Datas aproximadas, na «cronologia média». a.C. = antes de Cristo. As datas «tradicionais» de fundação das colónias (Útica, Gadir, Cartago) são anteriores às que a arqueologia confirma; o texto di-lo sempre que isso importa.
// As Guerras Púnicas vistas de Roma estão em roma/republica-tardia; aqui contam-se do lado de Cartago, sem repetir os pormenores.
// Imagens: cada {img:'id'} procura o ficheiro  fenicios/img/id.jpg  (ver IMAGENS_FENICIOS.md para a lista e os prompts).

const visao = [
  { caixa: 'Em resumo', texto: [
    'Os **fenícios** foram um conjunto de cidades-estado independentes (**Biblos**, **Tiro**, **Sídon**, **Arwad** e outras) na estreita faixa costeira do atual Líbano, entre a montanha e o mar. Nunca formaram um único Estado: partilhavam a língua, os deuses e o ofício de navegar. Foram os grandes **mercadores e navegadores** do Mediterrâneo da Idade do Ferro, fundaram cidades da Síria à Península Ibérica e ao Atlântico, e espalharam um dos inventos mais importantes da História: o **alfabeto**.',
    'A mais famosa das suas colónias, **Cartago** (hoje na Tunísia), tornou-se uma potência por direito próprio. Durante séculos dominou o Mediterrâneo ocidental, até ao choque com Roma nas três **Guerras Púnicas**, a de **Aníbal** incluída, e à destruição de 146 a.C. Grande parte do que se sabe dos fenícios vem de autores gregos, romanos e hebreus, e muitos deles eram inimigos ou rivais; a escrita fenícia usava sobretudo materiais perecíveis, e quase nenhuma literatura fenícia chegou até nós.'
  ] },
  { img: 'fen-mapa-mediterraneo', leg: 'Mapa das rotas e colónias fenícias e cartaginesas no Mediterrâneo.' },
  { h: 'Onde ficavam' },
  'A **Fenícia** era uma faixa costeira com cerca de 200 a 300 km de comprimento e poucos quilómetros de largura, correspondente sobretudo ao litoral do Líbano atual, com extensões para norte (Arwad, na costa síria) e para sul (até ao Carmelo, hoje em Israel). Atrás das cidades erguiam-se as montanhas do **Líbano**, cobertas de cedros, madeira muito procurada no Egito e na Mesopotâmia. Havia pouca terra para cultivar, pelo que o mar era o caminho natural. As cidades ficavam muitas vezes em ilhotas ou promontórios com dois portos, fáceis de defender.',
  'O nome vem do grego **Phoinikes**, que se liga a *phoinix*, «púrpura, vermelho-escuro», por causa do corante. Eles próprios não parecem ter usado um nome comum: diziam-se «de Tiro», «de Sídon», «de Biblos», e, segundo algumas fontes, também **cananeus** (*kena‘ani*). Os romanos chamaram **Poeni** aos fenícios do Ocidente, de onde vem **púnico**: «Guerras Púnicas» quer dizer, simplesmente, «guerras contra os fenícios de Cartago».',
  { img: 'fen-biblos-ruinas', leg: 'Ruínas de Biblos, Jbeil, Líbano.' },
  { h: 'Quando existiram' },
  'As raízes são cananeias e anteriores a 1500 a.C.: as cidades da costa já existiam na Idade do Bronze e comerciavam com o Egito. O que chamamos «fenício» surge, em sentido estrito, por volta de **1200 a.C.**, depois do colapso das grandes potências do Bronze Final (hititas, Ugarit, micénicos), de que as cidades da costa sobreviveram melhor do que a maioria. Esta é uma convenção moderna: a mudança foi gradual.',
  { tabela: { cab: ['Fase', 'Datas aproximadas', 'O que a marca'], linhas: [
    ['Raízes cananeias', 'c. 1500 – 1200 a.C.', 'Cidades-estado da costa sob influência egípcia; as cartas de Amarna; Biblos, Tiro e Sídon já são importantes'],
    ['Idade de ouro fenícia', 'c. 1100 – 800 a.C.', 'Libertos do domínio egípcio, os fenícios dominam o comércio marítimo; Hiram I de Tiro; consolidação do alfabeto'],
    ['Expansão colonial', 'c. 900 – 600 a.C.', 'Chipre, Norte de África, Sicília, Sardenha, Ibéria, Atlântico; fundação (tradicional, 814 a.C.) de Cartago'],
    ['Sob Assíria e Babilónia', 'c. 740 – 539 a.C.', 'Tributo e conquistas assírias; cerco de Tiro por Nabucodonosor II; Cartago torna-se independente de facto'],
    ['Sob a Pérsia', '539 – 332 a.C.', 'As cidades fenícias fornecem a melhor marinha do Império Persa; revolta de Sídon (c. 351)'],
    ['Cartago, potência ocidental', 'c. 600 – 264 a.C.', 'Império marítimo no Mediterrâneo ocidental; guerras na Sicília; tratados com Roma'],
    ['Guerras Púnicas e queda', '264 – 146 a.C.', 'Três guerras com Roma, Aníbal, destruição de Cartago'],
    ['Depois', 'depois de 146 a.C.', 'Fenícia helenística e romana; cidades neo-púnicas no Norte de África; Cartago refundada por Roma']
  ] } },
  { img: 'fen-tiro-ruinas', leg: 'Ruínas de Tiro, sítio de Al-Mina, Líbano.' },
  { h: 'Porque importam' },
  { lista: [
    '**O alfabeto:** o sistema de 22 letras, usado pelos fenícios por volta de 1050 a.C., é o antepassado do alfabeto grego, do latino (que usamos) e dos alfabetos hebraico e árabe.',
    '**Navegação e comércio:** foram os grandes intermediários entre o Oriente e o Ocidente, levando metais, cerâmica, vinho, têxteis e ideias, e ligando regiões que não se conheciam.',
    '**A púrpura de Tiro:** o corante de caracóis do mar, símbolo de poder durante mais de mil anos (a «púrpura imperial»).',
    '**Cartago:** uma república comercial com uma constituição que Aristóteles admirou, e uma grande rival de Roma.',
    '**A Península Ibérica:** os fenícios foram dos primeiros povos do Mediterrâneo oriental a chegar ao território que é hoje Portugal, onde deixaram vestígios no Algarve, no Sado, no Mondego e em Lisboa.'
  ] },
  { caixa: 'A Fenícia hoje', texto: 'Biblos, Tiro e Cartago estão na lista do Património Mundial da UNESCO (Biblos e Tiro em 1984, Cartago em 1979). O Líbano e a Tunísia, onde se encontram as principais ruínas, têm as cidades modernas por cima das antigas, o que limita as escavações. Muitos libaneses reivindicam uma identidade «fenícia»; os historiadores têm cautela com essa ideia, porque as ligações genéticas e culturais, embora existam, são complexas e discutidas.' },
  { img: 'fen-cartago-portos', leg: 'Portos púnicos de Cartago, vista aérea histórica de um postal anterior a 1958.' }
];

const linha = [
  'Esta linha do tempo segue os momentos principais dos fenícios e de Cartago. As datas são aproximadas e as mais antigas são as mais incertas: as datas «tradicionais» de fundação das colónias, transmitidas por autores gregos e romanos, são muitas vezes séculos anteriores às que a arqueologia permite confirmar.',
  { linha: [
    { d: 'c. 1350 a.C.', t: 'Cartas de Amarna', x: 'Os reis das cidades cananeias da costa (Biblos, Tiro, Sídon e outras) escrevem ao faraó, em acádio, a pedir ajuda contra vizinhos e piratas. Rib-Hadda, de Biblos, é o correspondente mais insistente. Mostram uma costa organizada em cidades-estado rivais, sob influência egípcia.' },
    { d: 'c. 1200 – 1175 a.C.', t: 'Colapso do Bronze Final', x: 'Ugarit, ao norte, é destruída; os hititas desaparecem; o Egito perde o controlo do Levante. As cidades da costa fenícia, ao contrário de outras, sobrevivem e recuperam depressa: é o começo da Fenícia propriamente dita.' },
    { d: 'c. 1075 a.C.', t: 'O relato de Wenamun', x: 'Um funcionário egípcio vai a Biblos comprar cedro para o barco do deus Amon e é tratado com frieza pelo príncipe Zakar-Baal, que lhe exige pagamento. É um texto literário egípcio, mas mostra bem o novo equilíbrio: o Egito já não manda, e Biblos negoceia de igual.' },
    { d: 'c. 1050 – 1000 a.C.', t: 'O alfabeto fenício', x: 'O alfabeto de 22 letras consonânticas fixa-se nas cidades fenícias. A inscrição gravada no sarcófago do rei **Ahiram de Biblos** é um dos mais antigos exemplos longos (a datação, entre o século XI e o X, é discutida).' },
    { d: 'c. 969 – 936 a.C.', t: 'Hiram I de Tiro', x: 'O rei mais famoso de Tiro, aliado de David e de Salomão segundo a Bíblia e o historiador Josefo (que cita fontes tírias): fornece cedro e artesãos para o Templo de Jerusalém. As datas do seu reinado dependem da cronologia usada, e discutem-se.' },
    { d: 'c. 900 – 800 a.C.', t: 'Começa a expansão pelo Mediterrâneo', x: 'Aparecem estabelecimentos fenícios em Chipre (Kition), no Norte de África (Útica), em Malta, na Sicília e na Sardenha. A tradição fala em fundações anteriores (Útica por volta de 1100 a.C.), mas as provas arqueológicas mais antigas são do século IX.' },
    { d: '814 a.C. (tradicional)', t: 'Fundação de Cartago', x: 'Segundo a tradição (Timeu, transmitido por Justino), a princesa **Elissa (Dido)**, de Tiro, funda a «Cidade Nova», **Qart-Hadasht**. É uma lenda com núcleo histórico possível: as primeiras cerâmicas encontradas em Cartago datam de cerca de 800 – 750 a.C.' },
    { d: 'c. 800 – 600 a.C.', t: 'Os fenícios na Península Ibérica', x: 'Gadir (Cádis), Málaga, Almuñécar e outras cidades do litoral andaluz; mais a oeste, **Castro Marim**, **Tavira**, **Abul**, **Santa Olaia** e **Lisboa** têm vestígios fenícios, desde meados do século VIII a.C. O comércio da prata do sudoeste ibérico é o grande atrativo.' },
    { d: '744 – 701 a.C.', t: 'A pressão assíria', x: 'Os reis assírios, a começar por Tiglat-Pileser III, impõem tributo às cidades fenícias. Em 701 a.C., Senaqueribe ataca a região e o rei de Sídon foge para Chipre. As cidades pagam, resistem e, às vezes, revoltam-se.' },
    { d: '677 a.C.', t: 'Sídon destruída', x: 'Depois de uma revolta, Assaradão arrasa Sídon e funda no mesmo local uma cidade assíria. Tiro, na ilha, assina com ele um tratado, o que mostra o poder dos seus marinheiros.' },
    { d: 'c. 654 a.C.', t: 'Ibiza', x: 'Segundo Diodoro, Ebusus (Ibiza) é fundada 160 anos depois de Cartago, por volta de 654 a.C. É um dos primeiros sinais de que Cartago assume um papel próprio no Mediterrâneo ocidental.' },
    { d: 'c. 600 a.C.', t: 'A volta a África', x: 'Segundo Heródoto, o faraó Neco II teria enviado marinheiros fenícios a dar a volta a África, a partir do mar Vermelho, em três anos. Heródoto não acredita na parte em que o Sol aparece à direita, que é precisamente o que um viajante do hemisfério sul veria. A viagem é possível, mas não é confirmada.' },
    { d: '586 – 573 a.C.', t: 'O cerco de Tiro', x: 'Nabucodonosor II da Babilónia cerca Tiro durante treze anos, segundo Josefo, sem a conquistar por completo: no fim, Tiro aceita a autoridade babilónica e recebe juízes em vez de reis. Os fenícios saem enfraquecidos e Cartago ganha peso.' },
    { d: '539 – 332 a.C.', t: 'Domínio persa', x: 'Ciro conquista Babilónia e a costa fenícia passa para o Império Persa. As cidades mantêm os seus reis e fornecem a melhor frota persa: nas guerras contra a Grécia, os navios de Sídon são os melhores, diz Heródoto.' },
    { d: 'c. 535 a.C.', t: 'A batalha de Alália', x: 'Cartagineses e etruscos vencem uma frota de gregos de Foceia perto da Córsega. Os foceus abandonam a ilha, e o Mediterrâneo ocidental fica dividido entre púnicos, etruscos e gregos.' },
    { d: 'c. 509 a.C.', t: 'Primeiro tratado com Roma', x: 'Segundo Políbio, Roma e Cartago assinam um tratado que define zonas de navegação e de comércio. A data é debatida; mostra que Roma, ainda uma cidade pequena, já era tratada como um parceiro.' },
    { d: '480 a.C.', t: 'Himera', x: 'O general cartaginês Amílcar, filho de Magão, é derrotado e morto por Gélon de Siracusa em Himera, na Sicília. A tradição grega fazia coincidir a batalha com a de Salamina, no mesmo dia; é provável que seja uma bonita coincidência inventada.' },
    { d: 'séc. V a.C. (debatido)', t: 'Hanão e Himilco', x: 'Cartago envia **Hanão** a fundar colónias e a explorar a costa atlântica de África, e **Himilco** a explorar o Atlântico norte. Os seus relatos chegaram em versões tardias e discutidas.' },
    { d: '332 a.C.', t: 'Alexandre Magno toma Tiro', x: 'Depois de sete meses de cerco, e de uma rampa de pedra que liga a ilha à terra, Alexandre conquista Tiro. É destruída em parte e muitos habitantes são vendidos como escravos; a cidade recupera, mas a ilha fica para sempre ligada ao continente.' },
    { d: '310 a.C.', t: 'Agátocles em África', x: 'O tirano de Siracusa, Agátocles, desembarca em África e ameaça Cartago. A cidade resiste, e as fontes dizem que, em desespero, sacrificou aos deuses 200 crianças de famílias nobres (cifra de Diodoro). Este episódio é muito citado no debate sobre o tofet.' },
    { d: '264 – 241 a.C.', t: 'Primeira Guerra Púnica', x: 'Guerra pela Sicília, em grande parte naval. Cartago perde, entrega a Sicília e paga uma pesada indemnização; Roma, que construiu uma frota de raiz, torna-se uma potência marítima. (Vista de Roma, ver a página da República Tardia.)' },
    { d: '241 – 238 a.C.', t: 'A Guerra dos Mercenários', x: 'Os soldados estrangeiros de Cartago, por pagar, revoltam-se, e as cidades africanas ficam do lado deles. **Amílcar Barca** esmaga a revolta com grande brutalidade. Com a derrota, Cartago perde também a Sardenha e a Córsega para Roma.' },
    { d: '237 – 219 a.C.', t: 'Os Barcidas na Hispânia', x: 'Amílcar, o genro Asdrúbal e depois o filho Aníbal criam um império na Ibéria, com base em **Carthago Nova** (Cartagena). A prata das minas paga a indemnização a Roma e financia o exército.' },
    { d: '218 – 202 a.C.', t: 'Segunda Guerra Púnica', x: 'Aníbal atravessa os Alpes e vence em Trébia, Trasimeno e Canas (216). Fica quinze anos em Itália, mas não toma Roma. Cipião expulsa os cartagineses da Hispânia e leva a guerra a África. Em **Zama** (202) vence Aníbal; Cartago fica sem império, sem elefantes e com uma frota reduzida a dez navios.' },
    { d: '149 – 146 a.C.', t: 'A queda de Cartago', x: 'Cartago, que recuperara economicamente, é atacada por Roma pela terceira vez. Resiste três anos. Cipião Emiliano toma-a, ao fim de uma semana de combate casa a casa, e ela arde durante dias. Terá havido dezenas de milhares de sobreviventes, vendidos como escravos. A lenda de que o solo foi salgado é moderna.' },
    { d: '44 a.C. – 439 d.C.', t: 'A Cartago romana', x: 'César planeia e Augusto concretiza a refundação de Cartago, que se torna capital da província de África e uma das maiores cidades do Império. A língua púnica sobrevive no campo durante séculos: Santo Agostinho, bispo de Hipona (m. 430), ainda a conhece. Os vândalos tomam Cartago em 439.' }
  ] },
  { img: 'fen-navios-senaqueribe', leg: 'Relevo de Nínive com galera de tipo fenício, 705–681 a.C., fotografado no Birmingham Museum and Art Gallery.' },
  { img: 'fen-moeda-barcida', leg: 'Quarto de shekel de prata da Hispânia púnica, cerca de 237–209 a.C., com cabeça masculina e elefante.' },
  { img: 'fen-cartago-destruicao-ia', leg: 'Destruição de Cartago, 146 a.C., cena imaginada. Ilustração gerada por IA.' }
];

const mapa = [
  'A «Fenícia» dos livros de História não é um país mas uma rede: as cidades da costa libanesa, as colónias fundadas por elas e, mais tarde, a rede de Cartago, no Ocidente. As cidades mais antigas ficavam no Levante; as mais ricas e influentes, no Mediterrâneo central e ocidental.',
  { img: 'fen-mapa-cidades', leg: 'Mapa esquemático da costa fenícia e das suas cidades, sem representar um império unificado.' },
  { tabela: { cab: ['Cidade', 'Deus protetor', 'Local hoje', 'Para que ficou conhecida'], linhas: [
    ['Biblos (Gebal)', 'Baalat Gebal, «Senhora de Biblos»', 'Jbeil, Líbano', 'Cedro e papiro; o sarcófago de Ahiram; o grego *byblos*, «livro»'],
    ['Tiro (Sor)', 'Melqart', 'Sur, Líbano', 'A maior cidade comercial; a púrpura; mãe de Cartago e de Gadir'],
    ['Sídon (Saida)', 'Eshmun e Astarte', 'Saida, Líbano', 'Vidro, púrpura; o templo de Eshmun; sarcófagos reais'],
    ['Arwad (Arados)', '—', 'Ilha de Arwad, Síria', 'Cidade-ilha ao norte, grande marinha; rival de Tiro'],
    ['Berito', '—', 'Beirute, Líbano', 'Pequena cidade, depois muito importante com os romanos'],
    ['Kition', 'Astarte e Melqart', 'Lárnaca, Chipre', 'Principal colónia de Tiro em Chipre; cobre cipriota'],
    ['Útica', '—', 'Tunísia, perto de Bizerta', 'Mais antiga colónia fenícia do Norte de África, segundo a tradição; aliada, depois rival, de Cartago'],
    ['Cartago', 'Baal Hammon e Tanit', 'Cartago, Tunísia', 'A «Cidade Nova»; potência do Mediterrâneo ocidental'],
    ['Motya', '—', 'Mozia, Sicília', 'Ilhota fortificada com um porto circular e um tofet'],
    ['Gadir', 'Melqart', 'Cádis, Espanha', 'Uma das colónias mais ocidentais do mundo antigo, junto às Colunas de Hércules; templo famoso de Melqart'],
    ['Tharros e Nora', '—', 'Sardenha, Itália', 'Cidades púnicas da Sardenha; a Pedra de Nora, com uma inscrição fenícia antiga'],
    ['Lixus, Mogador', 'Melqart (Lixus)', 'Larache e Essaouira, Marrocos', 'Postos atlânticos de Marrocos para ouro, marfim e púrpura']
  ] } },
  { h: 'Biblos' },
  'A mais antiga das grandes cidades fenícias, habitada desde o Neolítico e ligada ao Egito desde o terceiro milénio a.C. Exportava cedro e comprava papiro e ouro egípcios, e o nome grego da cidade, **Byblos**, acabou por designar o «livro» (papiro), de onde vem a palavra «Bíblia». É em Biblos que foi encontrado o sarcófago de **Ahiram**, com uma das inscrições alfabéticas fenícias mais antigas. A cidade foi escavada por Pierre Montet e depois, durante meio século, por Maurice Dunand. Depois do século X a.C., Tiro e Sídon ultrapassam-na, mas Biblos manteve o seu prestígio religioso.',
  { h: 'Tiro' },
  'A «Rocha» (Sor) era uma ilha a cerca de 700 m da costa, com dois portos, um virado ao norte (Sídon) e outro ao sul (o «egípcio»). Os seus habitantes construíram torres e casas de vários andares, e a cidade chegou a ser uma das mais ricas do mundo antigo. O profeta Ezequiel (cap. 27) fez dela uma «nave» perfeita, com a lista dos produtos que recebia, de Társis ao Egito. Resistiu a Nabucodonosor II e foi conquistada por Alexandre, que construiu uma rampa de pedra até à ilha; os sedimentos acumulados fazem hoje da antiga ilha uma península. Nos tempos romanos, continuou grande, e os seus arcos e hipódromo são visitáveis.',
  { img: 'fen-tiro-ilha-ia', leg: 'Tiro insular no século VII a.C., reconstituição conjetural. Ilustração gerada por IA.' },
  { h: 'Sídon' },
  'A cidade vizinha e rival de Tiro (a Bíblia chama «sidónios» a todos os fenícios, e Homero também). Famosa pelo vidro, pela púrpura e pelos artesãos. Perto da cidade, o **templo de Eshmun**, deus da cura, escavado por Maurice Dunand a partir dos anos 1960, data do século VII a.C. em diante. Na necrópole real de Sídon foram encontrados sarcófagos reais, entre eles o de **Eshmunazar II** (séc. V a.C., hoje no Louvre), com uma maldição inscrita contra quem violar o túmulo. Sídon revoltou-se contra os persas por volta de 351 a.C. e foi arrasada; o rei Tennes entregou-a aos persas, segundo Diodoro.',
  { img: 'fen-sidon-castelo', leg: 'Castelo do Mar de Sídon, construído pelos cruzados em 1228, posterior à época fenícia.' },
  { h: 'Arwad' },
  'Cidade-ilha no extremo norte, com cerca de 800 m de comprimento, mesmo em frente a Tartus (Síria). A cidade dominava também alguns povoados da costa em frente, em terra firme, e tinha uma marinha importante. A ilha ainda é habitada hoje, com uma fortaleza medieval.',
  { img: 'fen-arwad-ilha', leg: 'Vista histórica da ilha de Arwad, fotografia da década de 1930.' },
  { h: 'Cartago' },
  'Cartago fica na península de Túnis, num sítio fácil de defender e com dois portos: um **porto comercial** retangular e um **porto de guerra** circular, o *cothon*, com ilha central e docas para cerca de 220 navios (Apiano). Sobre a colina de **Byrsa** erguia-se a cidadela; o **tofet**, ao sul, era o santuário sagrado; as casas, de vários andares, estendiam-se pelas encostas. Tinha uma muralha enorme (os autores antigos dão números de dezenas de quilómetros, provavelmente exagerados) e bairros de jardins. A população é discutida: Estrabão fala em 700 000, mas as estimativas modernas são bem menores, de cem a duzentos mil habitantes. A cidade romana ergue-se por cima da púnica, e só uma parte desta foi escavada.',
  { img: 'fen-cartago-reconstrucao', leg: 'Cartago e os portos púnicos, reconstituição conjetural. Ilustração gerada por IA.' },
  { h: 'Os outros portos do Norte de África' },
  'Para além de Cartago e Útica, a costa tinha **Hadrumeto** (Sousse), **Leptis Magna** e **Sabrata** (hoje na Líbia) e muitas outras. Chamavam-se «líbio-fenícios» os habitantes mestiços de fenícios e de populações locais. Mais para o interior estavam os reinos **númidas** e **mauritanos**, aliados, vassalos ou inimigos de Cartago, com a sua cultura própria; **Masinissa**, que ajudou Roma, foi um deles. Em **Kerkouane**, no Cabo Bon, uma cidade abandonada no século III a.C. conservou casas, banheiras e ruas intactas, um dos melhores retratos da vida quotidiana púnica.',
  { img: 'fen-kerkouane-casa', leg: 'Casa púnica com banheira, Kerkouane, Tunísia.' },
  { h: 'Sicília, Malta e Sardenha' },
  'Na Sicília, os fenícios ocuparam o oeste, com **Motya**, **Panormo** (Palermo) e **Soluntum**, enquanto os gregos ficavam no leste. **Motya**, uma ilha numa laguna, com um porto artificial (*cothon*), foi destruída por Dionísio de Siracusa em 397 a.C., e a sua população foi para Lilibeu. Em Malta e na Sardenha (**Nora**, **Tharros**, **Sulcis**) a presença fenícia e depois cartaginesa foi forte, e a Sardenha foi uma colónia cartaginesa até 238 a.C. A **Pedra de Nora** (séc. IX – VIII a.C.) tem uma das mais antigas inscrições fenícias do Ocidente.',
  { img: 'fen-motya-cothon', leg: 'Bacia de Motya tradicionalmente chamada cothon, interpretada como piscina sagrada de água doce por Nigro (2022).' },
  { h: 'Gadir e a Ibéria fenícia' },
  'Segundo a tradição, **Gadir** foi fundada por Tiro por volta de 1100 a.C. As escavações mostram ocupação desde o século IX – VIII a.C. Ficava numa ilha da baía de Cádis, junto ao território de **Tartessos**, e era o centro do comércio da prata e do estanho do Atlântico. O seu templo de **Melqart**, situado, segundo se crê, no ilhéu de Sancti Petri, era visitado por peregrinos; Aníbal ali fez sacrifícios antes de partir para Itália, e Júlio César visitou o santuário. Em Cádis foram encontrados dois **sarcófagos antropomórficos** de mármore, de inspiração egípcia e grega, do século V a.C. Mais a leste havia Malaka, Sexi (Almuñécar) e Abdera; Ibiza (Ebusus) tinha uma enorme necrópole, a de Puig des Molins.',
  { img: 'fen-gadir-fundacao-ia', leg: 'Chegada imaginada de navegadores fenícios à baía de Gadir, século VIII a.C. Ilustração gerada por IA.' },
  { img: 'fen-gadir-sarcofagos', leg: 'Tampa de sarcófago antropomórfico fenício com figura feminina, Museu de Cádis.' },
  { img: 'fen-mapa-iberia', leg: 'Mapa de colónias fenícias e gregas na Península Ibérica, cerca de 300 a.C.' },
  { h: 'Os fenícios em Portugal' },
  'A presença fenícia no que é hoje Portugal é **real, mas modesta e discutida**. O que a arqueologia mostra, sobretudo desde os anos 1980, são feitorias e povoados costeiros, ou populações locais que adotam produtos e modos de vida fenícios, entre os séculos VIII e V a.C. Os arqueólogos debatem se eram colonos, comerciantes ou nativos «orientalizados». Os sítios mais conhecidos são:',
  { lista: [
    '**Castro Marim (Algarve):** povoado perto da foz do Guadiana com cerâmicas fenícias do séc. VIII a.C. e depois uma presença «orientalizante» forte, ligada ao comércio dos metais.',
    '**Tavira:** escavações encontraram um povoado com **edifícios do século VIII – VII a.C.** de planta e técnica fenícias, entre os mais antigos conhecidos em Portugal.',
    '**Abul (Alcácer do Sal):** feitoria no estuário do Sado, do século VII – VI a.C., com um grande edifício com pátio, fornos de cerâmica e muita louça fenícia; um dos sítios mais bem estudados.',
    '**Santa Olaia (Figueira da Foz):** povoado fortificado na foz do Mondego, do século VIII – VII a.C. ao V a.C., com cerâmicas e objetos de origem fenícia; é um dos pontos mais setentrionais da presença fenícia no Atlântico peninsular.',
    '**Lisboa:** na Sé, nos Correeiros e no Castelo de São Jorge, apareceram cerâmicas fenícias do século VIII – VII a.C., nos níveis mais antigos da cidade. A ideia de que o nome *Olisipo* viria do fenício *Alis Ubbo*, «porto seguro», é uma etimologia popular, **sem prova**.'
  ] },
  { img: 'fen-tavira-fenicio', leg: 'Palácio da Galeria, sede do Museu Municipal de Tavira; vista exterior, em substituição da fotografia de cerâmica pedida.' },
  { img: 'fen-porto-tejo-ia', leg: 'Cena imaginada de trocas no estuário do Tejo, século VII a.C. Ilustração gerada por IA.' },
  { h: 'Mogador e o Atlântico' },
  'A ilha de **Mogador**, em frente a Essaouira (Marrocos), teve um posto de comércio fenício e depois púnico a partir do século VII a.C., com cerâmica fenícia e, mais tarde, uma tinturaria de púrpura do tempo do rei Juba II da Mauritânia. **Lixus**, no rio Loukkos, tinha um grande templo. O comércio atlântico fazia-se por **Gadir**, que trazia da Mauritânia o marfim, o ouro (em troca de bugigangas, segundo Heródoto, no célebre «comércio silencioso», que ele conta como uma curiosidade) e a púrpura. Este circuito ligava-se ao Algarve e a Lisboa.',
  { img: 'fen-mogador-ilha', leg: 'Ilha de Mogador, Essaouira, Marrocos.' },
  { h: 'As rotas' },
  'Os fenícios navegavam sobretudo de **cabotagem**, de porto em porto, a pequenas distâncias, e a vela, com um mastro e uma vela quadrada. Havia três grandes rotas: a **norte** (Chipre, Creta, Grécia, Sicília), a **do meio** (Egito, Malta, Cartago, Sardenha, Baleares) e a **do sul** (costa de África até Gadir e ao Atlântico). Passavam as **Colunas de Hércules** (o estreito de Gibraltar) para chegar a Cádis, a Lisboa e a Mogador. Hanão desceu pela costa africana e Himilco subiu pela europeia. Uma viagem entre Tiro e Cádis, com escalas, demorava semanas.'
];

const sociedade = [
  { h: '1. Organização política' },
  'Cada cidade fenícia era uma **cidade-estado** independente, com o seu **rei** (*melek*) e um conselho de anciãos ou de famílias ricas. O rei tinha funções militares, religiosas e comerciais, e era muitas vezes o grande sacerdote do deus da cidade. As cidades rivalizavam entre si, e quando uma era forte (como Tiro, sob Hiram I) exercia hegemonia sobre as outras. Nunca criaram um reino unificado, e foi isso que as tornou frágeis perante as grandes potências do Oriente: o Egito, a Assíria, a Babilónia e a Pérsia.',
  'Sob os **assírios** pagavam tributo e recebiam funcionários; sob os **babilónios** foram vigiadas; sob os **persas** foram uma das satrapias, a «Além-Rio», e mantiveram os reis, a autonomia e o direito de cunhar moeda. Em troca davam a frota, a base da marinha persa. Segundo Heródoto, quando o rei Cambises quis atacar Cartago, os fenícios recusaram-se a navegar contra a sua colónia, e o rei desistiu.',
  { h: '2. Cartago: a constituição' },
  'Cartago começou como uma monarquia e tornou-se uma **república de aristocratas e mercadores**, com uma constituição que **Aristóteles** (*Política*, II, 11) admirou como equilibrada. O que sabemos vem, sobretudo, de Aristóteles e de Políbio, que a viu em ação, e é incompleto.',
  { lista: [
    '**Os dois suffetes** (*šōfeṭīm*, «juízes»): magistrados eleitos por um ano entre as famílias ricas, que presidiam ao Senado e administravam a justiça. Não comandavam exércitos. Os romanos traduziram a palavra por *reges* ou *consules*, mas o cargo não era igual.',
    '**O Senado**: uma assembleia de notáveis, com centenas de membros (as fontes discordam sobre o número); decidia a guerra, a paz e as finanças. Dentro dele havia um conselho mais restrito.',
    '**O Conselho dos 104** (ou «dos Cem»): um tribunal que fiscalizava os generais e magistrados, criado para limitar o poder de famílias poderosas. Podia condenar à morte um general derrotado.',
    '**A assembleia do povo**: só era consultada em caso de desacordo entre os suffetes e o Senado, o que dava aos cidadãos pouco poder.',
    '**Os generais**: escolhidos separadamente, com funções militares. A família **Magónida** (séc. VI – V a.C.) e a família **Barca** (séc. III a.C.) dominaram os cargos militares, o que levou a lutas com o Senado.'
  ] },
  { h: '3. Classes sociais' },
  'Havia uma elite de **grandes famílias** que viviam do comércio, dos latifúndios e dos cargos; **cidadãos** artesãos e pequenos comerciantes; **camponeses** dependentes; **escravos**, vindos da guerra e do comércio; e, em Cartago, populações **líbias** súbditas e **mercenários** estrangeiros. O papel das **mulheres** é pouco conhecido. As inscrições e os túmulos mostram sacerdotisas e mulheres com riqueza e nome próprio, mas o poder político era dos homens; a lenda de Dido é uma exceção, ainda que seja apenas uma história.',
  { h: '4. Religião' },
  'Os deuses fenícios eram os do mundo cananeu e semita, com «Baal» («Senhor») e «Baalat» («Senhora») a servir de título para os deuses de cada cidade. Cada cidade tinha o seu deus protetor, e os templos eram a casa do deus, com altares, pátios e estelas (os **betilos**, pedras sagradas). Praticavam sacrifícios de animais, oferendas, procissões, banquetes rituais e festas anuais, como o «despertar» de Melqart, que, segundo a tradição, morria e ressuscitava com a estação.',
  { tabela: { cab: ['Deus', 'Domínio', 'Cidade / lugar'], linhas: [
    ['Baal Hammon', 'Deus supremo de Cartago, ligado à fertilidade e à agricultura; o significado de *Hammon* é debatido', 'Cartago, Motya, Útica'],
    ['Tanit', 'Deusa principal de Cartago, com o título «Face de Baal»; o seu símbolo é um triângulo, com uma barra e um disco', 'Cartago'],
    ['Melqart', '«Rei da Cidade»; deus de Tiro, da navegação e das colónias, identificado com Hércules', 'Tiro, Gadir, Cartago'],
    ['Astarte (Ashtart)', 'Deusa do amor, da guerra e do céu; equivalente à Ishtar da Mesopotâmia', 'Sídon, Éryx, Kition'],
    ['Eshmun', 'Deus da cura e da vegetação', 'Sídon'],
    ['Baal Shamem', '«Senhor do Céu»', 'várias cidades'],
    ['Baalat Gebal', '«Senhora de Biblos», identificada com Isis ou Hathor', 'Biblos'],
    ['Reshef', 'Deus da guerra e da peste', 'várias']
  ] } },
  { img: 'fen-melqart-sancti-petri', leg: 'Estatueta de bronze de Melqart, área de Sancti Petri, Cádis, séculos VIII–VII a.C., fotografada na exposição Carthago.' },
  { img: 'fen-tanit-estela', leg: 'Estela em forma do símbolo de Tanit, Museu Nacional do Bardo, Tunísia.' },
  { img: 'fen-templo-eshmun', leg: 'Templo de Eshmun perto de Sídon, Líbano.' },
  'Um documento raro é o **tratado de Aníbal com Filipe V da Macedónia** (215 a.C.), que Políbio transcreveu: lista os deuses que o juram, entre eles o «Génio dos cartagineses», Hércules (Melqart), Iolau, Ares, Tritão e Poseidon, tal como os gregos traduziam os nomes dos deuses púnicos. Aníbal rezava no templo de Melqart em Gadir antes de partir para Itália.',
  { h: 'O tofet e o debate sobre o sacrifício de crianças' },
  'O **tofet** (a palavra vem da Bíblia hebraica, onde designa um lugar maldito perto de Jerusalém) é um santuário a céu aberto, existente em Cartago e noutras cidades púnicas (Motya, Sulcis, Tharros, Hadrumeto). Em Cartago foi usado desde cerca de **800 a.C. até 146 a.C.** e ocupa vários milhares de metros quadrados. Contém milhares de **urnas** com ossos queimados, de crianças pequenas e de animais (carneiros, aves), e **estelas** de pedra dedicadas a Baal Hammon e a Tanit, com símbolos e fórmulas votivas.',
  'O que **se sabe**: houve ali cremações de crianças muito pequenas, incluindo recém-nascidos e fetos, e de animais, em grande quantidade, durante séculos, num espaço sagrado, e as pessoas faziam oferendas com estelas pagas por famílias, algumas com nomes e o termo *molk*. Autores gregos e romanos (Diodoro, Plutarco, Tertuliano) acusam os cartagineses de **sacrificar crianças** vivas, e a Bíblia hebraica condena a prática de «passar os filhos pelo fogo». Estas fontes são hostis, escritas por inimigos.',
  'O que **é debatido**: se as crianças eram **mortas ritualmente** (sacrifício) ou se se trata de um cemitério especial de crianças que morreram de **causas naturais** e foram oferecidas aos deuses. Alguns estudos de ossos (2010) apontaram para muitas mortes naturais ou perinatais, mas foram contestados por outros especialistas, que veem sinais de sacrifício e consideram que a elevada mortalidade infantil não explica a presença dos animais e das inscrições. Há também a hipótese de que *molk* significaria «oferenda» e de que o animal era por vezes oferecido **em vez da criança**. Os historiadores não chegaram a consenso. A verdade pode variar com a época e o local. O que parece seguro é que a prática era religiosa, pública e aceite pela comunidade, e que a propaganda romana a exagerou.',
  { img: 'fen-tofet-cartago', leg: 'Tofet de Cartago, Salammbô, com estelas.' },
  { h: '5. Economia e comércio' },
  'A economia fenícia assentava no **comércio marítimo** e no artesanato de luxo. Compravam metais (prata da Ibéria, estanho do Atlântico, cobre de Chipre, ouro e marfim de África) e vendiam madeira de cedro, vinho, azeite, cerâmica, têxteis tintos de púrpura, vidro, objetos de marfim e de metal. O profeta **Ezequiel** (cap. 27) faz uma lista famosa dos produtos e dos parceiros de Tiro, da Grécia a Judá, de Társis a Damasco. Em Cartago, a **agricultura** foi muito importante: as terras do Cabo Bon e do vale do Bagradas produziam trigo, vinho, azeite e figos, e **Magão**, um agrónomo cartaginês, escreveu um tratado de 28 livros que o Senado romano mandou traduzir para latim em 146 a.C. (o original perdeu-se, mas autores como Columela citam-no).',
  'As cidades fenícias cunharam moeda a partir do século V a.C. (Tiro, Sídon, Arwad, Biblos); Cartago cunhou moeda a partir do século V – IV a.C., primeiro para pagar aos mercenários na Sicília. O comércio era feito por famílias de armadores, sem um «Estado» capitalista como hoje, mas com apoio de reis e templos, que financiavam as viagens. As expedições levavam sal, peixe seco e **conservas de peixe**, e Gadir fez do **garum** (molho de peixe fermentado) uma exportação famosa na época romana.',
  { img: 'fen-vidro-fenicio', leg: 'Pendente de vidro em forma de cabeça humana, de tipo fenício-púnico.' },
  { h: '6. A púrpura de Tiro' },
  'A **púrpura** era um corante extraído das glândulas de caracóis do mar do género *Murex* (espécies *Bolinus brandaris*, *Hexaplex trunculus* e outras). Esmagavam-se ou fervia-se o animal, e a secreção, ao ser exposta à luz e ao ar, passava de amarelada a verde e a um vermelho-arroxeado que **não desbotava**. Eram precisos milhares de caracóis para uma pequena quantidade de tinta, o que fez dela uma das substâncias mais caras da Antiguidade. Em Tiro, em Sídon e em outros portos há montes de conchas partidas, restos desta indústria. Reis, magistrados e sacerdotes usavam roupa de púrpura; na Roma imperial, a púrpura passou a símbolo do imperador.',
  { cit: 'Tiro, disseste: «Sou de perfeita beleza». As tuas fronteiras estão no coração dos mares.', fonte: 'Ezequiel 27, 3 (tradução livre)' },
  'A lenda grega (conservada em Pólux, séc. II d.C.) conta que o deus **Melqart** passeava na praia com a ninfa Tiro e o seu cão trincou um caracol; a boca do cão ficou púrpura, e a ninfa pediu um vestido dessa cor. É apenas uma lenda de origem, e **não é história**.',
  { img: 'fen-murex-purpura', leg: 'Concha de Bolinus brandaris em cinco vistas, espécie utilizada na produção de púrpura.' },
  { img: 'fen-purpura-tinturaria-ia', leg: 'Tinturaria de púrpura fenícia, cena imaginada. Ilustração gerada por IA.' },
  { h: '7. Escrita, alfabeto e língua' },
  'O **alfabeto fenício** tem 22 letras, todas consoantes, escritas da direita para a esquerda. Não inventou a escrita, mas foi o primeiro sistema **simples e prático**, ao alcance de qualquer comerciante, sem os centenas de sinais do cuneiforme ou dos hieróglifos. A ideia veio de escritas alfabéticas mais antigas no Sinai e em Canaã (cerca de 1900 – 1500 a.C.), de origem debatida, ligada aos hieróglifos egípcios. Cada letra tinha o nome de um objeto, e o som inicial era o da letra: *aleph* («boi»), *beth* («casa»), *gimel* («camelo» ou «bastão»).',
  'Os **gregos** adotaram o alfabeto por volta dos séculos IX – VIII a.C. e converteram algumas consoantes em vogais (*aleph* → alfa, *beth* → beta, de onde «alfabeto»). Deles descendem o alfabeto etrusco, o latino e o cirílico. Do ramo semita vêm o hebraico, o aramaico e o árabe. Heródoto dizia que Cadmo, um fenício, trouxe as letras para a Grécia (lenda, mas com uma verdade essencial).',
  { img: 'fen-alfabeto-quadro', leg: 'Quadro da formação do alfabeto latino a partir do fenício, passando por alfabetos gregos e pelo etrusco.' },
  { img: 'fen-escriba-biblos-ia', leg: 'Escriba em Biblos, século X a.C., cena imaginada. Ilustração gerada por IA.' },
  'A língua fenícia pertence ao grupo **cananeu** das línguas semitas, próxima do hebraico. O **púnico** foi a variedade de Cartago e do Ocidente, e o **neo-púnico**, a de depois de 146 a.C., escrito mesmo em Lepcis Magna e em Cartago romana, ainda no século III d.C. Na comédia *Poenulus*, de Plauto (c. 190 a.C.), há passagens em púnico (muito deturpadas pela transmissão). Os textos fenícios preservados são sobretudo **inscrições** em pedra, metal e cerâmica: dedicatórias, túmulos, tratados. A escrita em papiro e em pele, onde estaria a literatura, perdeu-se.',
  { h: '8. Cidade e casa' },
  'As cidades fenícias eram densas, compactas, muradas, com ruas estreitas e casas de pedra, por vezes com vários andares, por falta de espaço (em Tiro, segundo os autores gregos, tinham mais andares do que as de Roma). Em Cartago, Apiano diz que as casas da colina de Byrsa tinham seis andares. Em **Kerkouane** viam-se casas com um pátio central, quartos à volta, uma sala de banho com banheira e um revestimento de argamassa de cal e cerâmica moída, o *opus signinum*, que os romanos chamariam «pavimento púnico» (*pavimentum punicum*). Os betilos, as estelas e os pequenos santuários domésticos eram comuns.',
  { img: 'fen-casa-cartago-ia', leg: 'Casa púnica inspirada em Kerkouane, reconstituição conjetural. Ilustração gerada por IA.' },
  { h: '9. Alimentação' },
  'A dieta era mediterrânea: pão e papas de cereal, azeitonas e azeite, vinho, figos, tâmaras, romãs (os romanos chamavam à romã *malum punicum*, «maçã púnica»), peixe, carne de ovelha e de cabra, leguminosas e queijo. O peixe seco e salgado era um produto de exportação. O único «prato» púnico de que sabemos a receita é a ***puls punica***, transmitida por Catão, o Velho, na obra *De Agri Cultura*: uma papa de farinha de trigo cozida em água, depois arrefecida e misturada com queijo fresco, mel e ovo. Os cartagineses eram também conhecidos pelo vinho de passas, e por um tratado agrícola completo de **Magão**.',
  { h: '10. Vestuário e adornos' },
  'Sabemos pouco: o que se conhece vem de relevos assírios, estatuetas, sarcófagos e das descrições dos vizinhos. Os homens usavam túnicas curtas ou compridas, mantos e barretes cónicos; as mulheres, vestidos compridos, véus e mantos, e muitos **adornos**: brincos, colares de contas de vidro, anéis, escaravelhos de pedra e amuletos egípcios. As roupas dos ricos eram tingidas de **púrpura**, e lã e linho eram os têxteis principais. Os sarcófagos reais de Biblos e de Sídon, de tipo egípcio, mostram a abertura dos fenícios às modas de fora. No campo, em Cartago, o traje seria mais simples, de lã.',
  { h: '11. Música, jogos e festas' },
  'Os fenícios conheciam a **lira**, a **harpa**, a **flauta dupla**, o **pandeiro** e os **címbalos**, que aparecem em estatuetas e relevos, e eram **músicos** apreciados nas cortes vizinhas. Os músicos e dançarinos tinham papel nas festas religiosas, em procissões e banquetes. Dos jogos sabe-se pouco: encontraram-se tabuleiros e peões em algumas cidades, mas as regras estão perdidas. Os **banquetes** (*marzeah*) eram reuniões de grupos de homens, com vinho, música e ritos fúnebres, atestadas no mundo cananeu.',
  { img: 'fen-mascara-punica', leg: 'Máscara de terracota púnica de rosto grotesco, Museu do Bardo.' },
  { h: '12. Ciência e navegação' },
  'Na Antiguidade acreditava-se que os fenícios eram sábios nos números e nos astros (a tradição grega atribui-lhes a «**Estrela Fenícia**», a Ursa Menor, que usavam para se orientar de noite, enquanto os gregos preferiam a Ursa Maior). Não temos textos científicos fenícios, e muito do que se diz vem de gregos como Estrabão, que lhes dava a invenção da aritmética e da astronomia (o que é exagerado). O que se pode afirmar é que **navegavam bem**: conheciam os ventos, as correntes, os astros e a costa, e tinham sabedoria prática de geografia, que partilhavam com os gregos.',
  'Os **relatos de viagem** são o melhor testemunho. O **Periplo de Hanão** é um texto grego, traduzido de uma inscrição que Hanão teria posto no templo de Baal Hammon (Cronos, para os gregos). Conta como partiu com **sessenta navios de cinquenta remos**, e cerca de 30 000 pessoas, para fundar cidades na costa atlântica de Marrocos e explorar mais a sul. Menciona rios, ilhas, um monte com «um carro dos deuses» (talvez um vulcão, o Monte Camarões, ou outro) e «mulheres peludas» (gorilas?) que os cartagineses esfolaram e levaram para casa. Os especialistas discutem até onde foi (Senegal, Serra Leoa ou Camarões) e se o texto é de uma viagem real, em que século. **Himilco** navegou para norte a partir de Gadir, à procura de estanho. A sua viagem é citada por Avieno, no séc. IV d.C., que usou textos antigos, e fala de mares de algas e de monstros. O resultado é muito discutido.',
  { img: 'fen-periplo-hanao-mapa', leg: 'Mapa de uma interpretação da viagem de Hanão.' },
  { h: '13. Tecnologia, navios e construção' },
  'Os navios fenícios eram de dois tipos principais. O **navio de carga** (*gaulos*, «banheira» em grego) era largo, redondo, com um grande mastro e vela quadrada, para transportar cargas. O **navio de guerra** era comprido e estreito, com remos, um esporão à proa (para abalroar) e, mais tarde, duas ou três filas de remadores (**birreme**, **trirreme**). Os fenícios deixaram nos relevos de Nínive os desenhos mais antigos destes navios; também se escavaram **naufrágios** (Mazarrón, em Espanha; Xlendi e Ashkelon, no Mediterrâneo) com cargas de metais e de ânforas. Os cartagineses usaram ainda o **quinquerreme**, e os romanos copiaram, segundo Políbio, um navio púnico encalhado para construir a sua frota.',
  { img: 'fen-navio-comercio-ia', leg: 'Navio mercante fenício gaulos, século VIII a.C., reconstituição conjetural. Ilustração gerada por IA.' },
  'Na construção, usavam grandes blocos de pedra bem aparelhada, **cisternas** para água, **ânforas** de tipos próprios (as ânforas púnicas, de fundo pontiagudo, que se encontram aos milhares nos naufrágios) e o *opus africanum*, um método de construção com pilares de pedra e enchimento de pequenos blocos, depois usado pelos romanos. A **vidraria** e a **metalurgia** (taças de bronze e prata, gravuras em marfim, joias de ouro) eram também muito apreciadas. O vidro soprado só aparece, no entanto, no século I a.C., por técnicos do Levante.',
  { h: '14. Guerra' },
  'Os fenícios do Levante eram sobretudo marinheiros e defendiam-se com muralhas e navios. **Cartago**, pelo contrário, fez guerra em terra, na Sicília e em África, com um exército em que os cidadãos eram uma minoria. A maior parte era **mercenária**: **líbios** (infantaria pesada), **númidas** (cavalaria ligeira, excelente), **iberos** e **celtas**, fundibulários das ilhas **Baleares** e alguns gregos. O corpo de elite, a **Banda Sagrada**, era formado por cidadãos (cerca de 2500 homens). Os generais eram escolhidos entre as famílias ricas, e a vitória era muitas vezes recompensada, e a derrota castigada.',
  'Usavam **elefantes de guerra**, do Norte de África, hoje extintos e menores do que o elefante da Índia. Aníbal levou-os para Itália, e em Zama os cartagineses tinham cerca de oitenta. A frota era a mais forte do Mediterrâneo ocidental até à Primeira Guerra Púnica, e a fraqueza do seu sistema, a dependência de mercenários, mostrou-se na Guerra dos Mercenários (241 – 238 a.C.), quando Cartago não podia pagar. Em 146 a.C., a cidade resistiu a Roma durante três anos.',
  { img: 'fen-exercito-cartago-ia', leg: 'Exército cartaginês em marcha, século III a.C., cena imaginada. Ilustração gerada por IA.' },
  { h: '15. A morte e os túmulos' },
  'Os fenícios praticavam tanto a **inumação** (corpo enterrado em câmaras ou em sarcófagos) como a **cremação**, consoante a época e o local. Em Biblos e em Sídon os reis foram enterrados em sarcófagos de pedra, alguns egípcios. Em Cartago há milhares de túmulos em poços, com ricos **ajuares** (amuletos, vasos, jóias, máscaras). Em Ibiza a necrópole de **Puig des Molins** tem milhares de sepulturas. Cria-se numa vida depois da morte, mas a ideia é pouco conhecida. As inscrições funerárias ameaçam com maldições quem violar o túmulo, como a de Eshmunazar II (paráfrase): que o violador não tenha descendência entre os vivos.'
];

const personalidades = [
  'As figuras que se seguem são sobretudo cartaginesas, porque Cartago tem mais fontes (e mais inimigos que escreveram sobre ela). Do Levante há poucos nomes: os reis de Tiro e de Sídon são conhecidos sobretudo por inscrições, pela Bíblia, por Josefo e por Heródoto. A primeira, Dido, pertence à lenda.',
  { h: 'Hiram I, rei de Tiro (c. 969 – 936 a.C.)' },
  'O rei de Tiro no tempo de David e de Salomão, que a Bíblia e o historiador Josefo recordam. Segundo a Bíblia, fez uma aliança com os reis de Israel e forneceu cedro, madeira de cipreste, artesãos e ouro para o **Templo de Jerusalém**, em troca de trigo e de azeite. Segundo Josefo, aterrou o espaço entre duas ilhotas de Tiro e construiu templos a Melqart e a Astarte. As datas do seu reinado dependem de cronologias muito discutidas.',
  { h: 'Ahiram, rei de Biblos (séc. XI – X a.C., datação discutida)' },
  'O rei cujo sarcófago, encontrado em Biblos em 1923, tem uma das inscrições fenícias mais antigas e mais importantes. O texto, uma maldição contra quem o abrir, é a prova da existência do alfabeto fenício por volta de 1000 a.C. Sabemos o nome do rei e o do filho, e pouco mais.',
  { img: 'fen-ahiram-sarcofago', leg: 'Sarcófago de Ahiram de Biblos, Museu Nacional de Beirute.' },
  { h: 'Elissa (Dido), a rainha lendária de Cartago' },
  'Segundo a tradição (que Justino resume a partir do historiador Timeu, séc. IV – III a.C.), **Elissa** era filha do rei de Tiro e irmã de **Pigmaleão**, que matou o seu marido, o sacerdote Acérbas, por causa do tesouro. Ela fugiu com um grupo de nobres, parou em Chipre, onde levou consigo jovens para as futuras esposas dos colonos, e chegou à costa de África. Os habitantes locais cederam-lhe «o que uma pele de boi pudesse cobrir», e Elissa cortou a pele em tiras finíssimas para delimitar uma colina: **Byrsa** (do grego *byrsa*, «pele»; trocadilho, pois em fenício *bosra* quer dizer «fortaleza»). Quando o rei local, **Iarbas**, quis casar com ela, Elissa subiu a uma pira e matou-se, para não quebrar a fidelidade ao marido. Os cartagineses terão-na adorado como deusa.',
  'Na *Eneida* de **Virgílio** (c. 29 – 19 a.C.), Dido é uma rainha que se apaixona por Eneias, que a abandona para fundar Roma, e mata-se. Esta versão é uma invenção do poeta (Troia caiu mais de 350 anos antes da data tradicional de Cartago), mas moldou a visão que o Ocidente teve de Dido, e de Cartago como inimiga de Roma. Elissa pode ser um nome real ou uma figura mítica; **não existe prova** de que tenha existido.',
  { img: 'fen-dido-byrsa-ia', leg: 'Lenda de Elissa, Dido, e a pele de boi em Byrsa. Ilustração gerada por IA.' },
  { h: 'Magão (séc. VI a.C.)' },
  'O general, ou rei, que, segundo Justino, lançou as bases do império cartaginês: reorganizou o exército, conquistou terras em África, na Sicília e na Sardenha, e deu o nome à família dos **Magónidas**, que governou Cartago durante gerações. Pouco se sabe com certeza. Não deve ser confundido com o **agrónomo Magão** (que escreveu os 28 livros sobre agricultura) nem com o irmão de Aníbal, também chamado Magão.',
  { h: 'Hamílcar, filho de Magão (m. 480 a.C.)' },
  'O comandante cartaginês que, segundo Heródoto, atacou a Sicília com um exército enorme (300 000 homens, número exagerado) e foi derrotado em **Himera**. Heródoto diz que, vendo a derrota, se atirou à fogueira de um sacrifício; Diodoro conta outra versão. Os cartagineses ergueram-lhe monumentos em Cartago e nas colónias.',
  { h: 'Hanão, o Navegador (séc. V a.C., datação debatida)' },
  'Autor, segundo a tradição, do **Periplo** (ver «Ciência e navegação»), o relato da sua viagem ao longo da costa atlântica de África. Terá fundado colónias em Marrocos e explorado a costa até uma região incerta no sul. É frequentemente confundido com outros cartagineses chamados Hanão (o nome era comum, como «Hannibal»).',
  { h: 'Amílcar Barca (c. 275 – 228 a.C.)' },
  'O general que defendeu a Sicília na Primeira Guerra Púnica a partir do monte Éryx, e que, depois da guerra, esmagou a revolta dos mercenários. **Barca** parece vir do fenício *baraq*, «relâmpago» (a etimologia é provável). Em 237 a.C. partiu para a Hispânia com o filho Aníbal, e criou um império na Ibéria que pagou a indemnização a Roma. Morreu em combate, em 228 a.C., ao atravessar um rio, em luta contra tribos locais (Diodoro; Políbio diz só que morreu em batalha). Segundo a tradição, fez o filho Aníbal jurar que seria sempre inimigo de Roma, mas é uma história provavelmente embelezada.',
  { h: 'Asdrúbal, o Belo (m. 221 a.C.)' },
  'Genro de Amílcar. Governou a Hispânia cartaginesa de 228 a 221 a.C. e fundou **Carthago Nova** (Cartagena). Preferia a diplomacia e as alianças com chefes ibéricos, casando-se com uma princesa local. Assinou com Roma o «tratado do Ebro» (226 a.C.), pelo qual os cartagineses se comprometiam a não passar o rio com um exército. Foi assassinado por um escravo celta, ao que parece por vingança.',
  { h: 'Aníbal Barca (247 – c. 183 a.C.)' },
  'O mais famoso cartaginês. Cresceu em campanha, subiu ao comando da Hispânia em 221 a.C., aos 26 anos, tomou **Sagunto** (219) e, em 218, partiu para Itália com um exército em que serviam africanos, iberos e celtas. Atravessou os **Alpes** (a passagem exata é debatida) e venceu os romanos em **Trébia**, **Trasimeno** e **Canas** (216), a pior derrota da história de Roma, ao envolver o inimigo com uma tática de pinça. Não tinha, porém, meios para sitiar Roma, e as cidades aliadas não se rebelaram como esperava. Em 203 foi chamado a defender África e foi vencido por Cipião em **Zama**. Depois da guerra, como **suffete** (196 a.C.), reformou as finanças e o Conselho dos 104, mas a oligarquia denunciou-o a Roma. Fugiu para a corte do rei Antíoco III e depois do rei Prúsias da Bitínia; quando os romanos exigiram a sua entrega, tomou veneno, c. 183 a.C. Os romanos, que o temiam, também o admiraram: Políbio fala dele com respeito. O busto de Aníbal mais conhecido (de Cápua) tem a identificação **incerta**; não se conhece nenhum retrato seguro, a não ser as moedas.',
  { img: 'fen-anibal-busto', leg: 'Busto de Cápua tradicionalmente identificado como Aníbal, atribuição duvidosa, Museu de Nápoles.' },
  { img: 'fen-anibal-alpes-ia', leg: 'Travessia dos Alpes por Aníbal, 218 a.C., cena imaginada. Ilustração gerada por IA.' },
  { h: 'Asdrúbal Barca (m. 207 a.C.) e Magão Barca' },
  'Os irmãos de Aníbal. **Asdrúbal** ficou a defender a Hispânia, foi derrotado por Cipião em Bécula (208) e, em 207, conduziu outro exército a Itália para se juntar ao irmão. Foi vencido e morto em **Metauro**, e a cabeça foi lançada no acampamento de Aníbal, segundo Lívio. **Magão** comandou na Hispânia e depois na Ligúria (Itália), onde morreu em 203 a.C. de uma ferida de guerra. Os três irmãos, em conjunto, formaram a família militar mais brilhante de Cartago.',
  { h: 'Asdrúbal, general em 149 – 146 a.C.' },
  'Chefe das forças cartaginesas durante o cerco final de Cartago. Quando Cipião Emiliano tomou a colina de Byrsa, Asdrúbal rendeu-se, e a sua mulher, segundo Políbio, que viu a cena, o insultou do alto do templo antes de se atirar com os filhos às chamas. É uma das imagens mais fortes da queda de Cartago, contada por um autor que estava no local.',
  { h: 'Masinissa (c. 240 – 148 a.C.)' },
  'Rei dos númidas, aliado de Cartago na Hispânia e depois de Roma. Mudou de lado em 206 a.C., combateu ao lado de Cipião em Zama e passou o resto da vida a ocupar terras cartaginesas, com o apoio de Roma, o que levou à guerra de 149 a.C. Morreu em 148 a.C., com cerca de 90 anos, já nos preparativos da guerra. É uma figura contraditória: traidor para Cartago, aliado fiel para Roma.'
];

const legado = [
  { h: 'O que nos deixaram' },
  { lista: [
    '**O alfabeto:** o legado maior. Quase todos os alfabetos do mundo ocidental, médio-oriental e europeu descendem do fenício.',
    '**Comércio e redes:** a ideia de uma economia mediterrânica ligada por mercadores, com cidades-porto, ânforas, pesos e moedas.',
    '**A navegação atlântica:** as rotas de Gadir, de Lisboa e de Mogador antecederam as dos romanos e, em muitos aspetos, as dos portugueses.',
    '**A púrpura:** a cor do poder, do Império Romano ao Império Bizantino, aos cardeais e aos reis.',
    '**Palavras:** «Bíblia» (de Biblos), «púnico», «Fenícia», «fénix» (do mesmo grego *phoinix*) e a própria palavra «alfabeto» (de *aleph* e *beth*, via grego).',
    '**A imagem de Cartago:** o inimigo de Roma, que Virgílio, Lívio e depois a Europa inteira usaram como contraponto. Vencido, Cartago só teve a história contada pelos vencedores.'
  ] },
  { cit: 'Houve uma antiga cidade, que colonos de Tiro habitaram: Cartago, defronte de Itália e das bocas do Tibre, rica de recursos e muito feroz na guerra.', fonte: 'Virgílio, Eneida, I, 12 – 14 (tradução livre)' },
  { h: 'Arte' },
  'A arte fenícia é uma arte de **fusão**: combina motivos egípcios (a esfinge, o escaravelho, a flor de lótus, o disco solar alado), mesopotâmicos e gregos, num estilo próprio, apreciado nas cortes de todo o Mediterrâneo. Os seus melhores trabalhos são os **marfins esculpidos** (encontrados em Nimrud, na Assíria), as **taças de metal** decoradas, as **joias** de ouro, os **sarcófagos**, as **estelas** votivas, as **máscaras** de terracota, as **ânforas** e os **pequenos objetos** de vidro. As cidades fenícias e púnicas tinham também esculturas em pedra e bronze. Faltam, em geral, grandes obras: quase tudo o que sobreviveu é pequeno ou funerário.',
  { h: 'Arquitetura' },
  'A arquitetura fenícia é mais bem conhecida em templos como o de **Eshmun**, de pátios e capelas, em torres e muralhas (Tiro, Arwad), e em portos artificiais como o de **Motya** e o de **Cartago**, com o seu *cothon* e docas. O **mausoléu líbio-púnico de Dougga**, na Tunísia (séc. II a.C.), é um dos raros edifícios inteiros que sobrevivem de uma cultura mista. Em Cartago, a maior parte foi arrasada em 146 a.C., e o que se vê hoje são, sobretudo, bairros romanos sobre ruínas púnicas.',
  { h: 'A redescoberta' },
  'Ao longo da Idade Média e do Renascimento, os fenícios e Cartago eram conhecidos apenas pelos autores antigos. No século XIX, **Ernest Renan**, enviado pela França à Fenícia (1860 – 1861), fez as primeiras explorações em Biblos, Tiro e Sídon. A **Cartago** romana e púnica foi escavada desde meados do século XIX, e o romance *Salammbô*, de **Gustave Flaubert** (1862), popularizou uma Cartago exótica e cruel, de forte influência. O **tofet** foi descoberto em 1921. **Maurice Dunand** escavou Biblos durante meio século; **Joseph Whitaker** escavou Motya a partir de 1906. As inscrições em fenício e em púnico foram sendo decifradas desde o século XVIII (o abade Barthélemy leu a primeira em 1758). Hoje, as descobertas continuam: sarcófagos em Cádis (1980s), a necrópole de Tiro, e, em Portugal, os sítios de Abul, Castro Marim, Tavira e Lisboa. O Conselho da Europa reconhece a **Rota dos Fenícios** como itinerário cultural europeu desde 2003.',
  { img: 'fen-cartago-byrsa', leg: 'Casas púnicas escavadas na colina de Byrsa, Cartago.' },
  { h: 'Onde visitar' },
  { lista: [
    '**Líbano:** Biblos, Tiro, Sídon (templo de Eshmun) e o **Museu Nacional de Beirute**, com o sarcófago de Ahiram.',
    '**Tunísia:** Cartago (colina de Byrsa, porto púnico, tofet), o **Museu do Bardo**, **Kerkouane**, Útica e o mausoléu de Dougga.',
    '**Itália:** Motya (Mozia), com o museu Whitaker; Tharros, Nora e Sulcis, na Sardenha.',
    '**Espanha:** Museu de Cádis, Almuñécar, Málaga e **Ibiza** (Puig des Molins).',
    '**Marrocos:** Lixus e a ilha de Mogador, em Essaouira.',
    '**Portugal:** vestígios fenícios nos museus de Lisboa, Tavira, Castro Marim, Alcácer do Sal e Figueira da Foz (Santa Olaia, no Museu Municipal Santos Rocha). Confirme sempre as peças em exposição e os horários.',
    '**Em museus de todo o mundo:** o Louvre (sarcófago de Eshmunazar II), o Museu Britânico (relevos de Nínive com navios fenícios) e o Museu Arqueológico Nacional de Madrid.'
  ] },
  { img: 'fen-museu-beirute', leg: 'Sala do Museu Nacional de Beirute, com sarcófagos e esculturas antigas.' }
];

const quiz = [
  { p: 'Qual era a principal característica política da Fenícia?', op: ['Um reino unificado com capital em Tiro', 'Um conjunto de cidades-estado independentes', 'Uma federação governada por Cartago', 'Um império governado pelo faraó'], certa: 1, exp: 'Biblos, Tiro, Sídon, Arwad e outras eram cidades-estado independentes e rivais.' },
  { p: 'De onde vem a palavra «Fenícia»?', op: ['Do nome do primeiro rei', 'De um deus de Biblos', 'Do grego *phoinix*, «púrpura»', 'Do latim *poenus*, «guerra»'], certa: 2, exp: 'Os gregos chamaram-lhes «os da púrpura», por causa do corante de Tiro.' },
  { p: 'Qual foi o grande legado dos fenícios à escrita?', op: ['O cuneiforme', 'Os hieróglifos', 'O alfabeto de 22 letras', 'O papiro'], certa: 2, exp: 'O alfabeto consonântico fenício é o antepassado do grego, do latino e de muitos outros.' },
  { p: 'De que animais se extraía a púrpura de Tiro?', op: ['Lagostas', 'Polvos', 'Caracóis do mar do género Murex', 'Insetos'], certa: 2, exp: 'A secreção de caracóis marinhos, depois exposta à luz, dava um corante que não desbotava.' },
  { p: 'Quem, segundo a tradição, fundou Cartago?', op: ['Aníbal', 'Elissa (Dido), princesa de Tiro', 'Hanão', 'Hiram I'], certa: 1, exp: 'Segundo a tradição (data: 814 a.C.), Elissa fugiu de Tiro e fundou a «Cidade Nova». É lenda, com um possível núcleo histórico.' },
  { p: 'Que cidade era o centro fenício na Península Ibérica, junto às Colunas de Hércules?', op: ['Gadir (Cádis)', 'Sagunto', 'Lisboa', 'Cartagena'], certa: 0, exp: 'Gadir, com o templo de Melqart, foi a principal colónia fenícia junto ao estreito de Gibraltar, no limite ocidental do mundo mediterrânico.' },
  { p: 'Qual destes sítios portugueses tem vestígios fenícios?', op: ['Conímbriga', 'Abul, no estuário do Sado', 'Mértola romana', 'Sé de Braga'], certa: 1, exp: 'Abul, em Alcácer do Sal, é uma feitoria fenícia do século VII – VI a.C.; Tavira, Castro Marim, Santa Olaia e Lisboa também têm vestígios.' },
  { p: 'Quem eram os suffetes de Cartago?', op: ['Generais do exército', 'Dois magistrados anuais, eleitos, com funções de juízes', 'Sacerdotes de Baal Hammon', 'Reis hereditários'], certa: 1, exp: 'Os suffetes (*šōfeṭīm*, «juízes») eram magistrados eleitos por um ano, e não comandavam exércitos.' },
  { p: 'Qual era o deus principal de Cartago, juntamente com Tanit?', op: ['Baal Hammon', 'Eshmun', 'Marduk', 'Hércules'], certa: 0, exp: 'Baal Hammon e Tanit eram as grandes divindades de Cartago. Melqart era o deus de Tiro.' },
  { p: 'O que sabem os historiadores sobre o tofet de Cartago?', op: ['Era um mercado', 'Foi só uma invenção romana', 'Era um santuário com urnas de crianças e animais cremados; se havia sacrifício é debatido', 'Era um cemitério de generais'], certa: 2, exp: 'O santuário é real e as cremações também. Se as crianças eram sacrificadas, ou se morreram de causas naturais, é objeto de debate.' },
  { p: 'Que escritor romano descreveu a receita da «puls punica»?', op: ['Virgílio', 'Catão, o Velho', 'Políbio', 'Heródoto'], certa: 1, exp: 'Catão registou em *De Agri Cultura* a papa de trigo com queijo, mel e ovo.' },
  { p: 'Que general cartaginês atravessou os Alpes em 218 a.C.?', op: ['Amílcar Barca', 'Magão', 'Aníbal', 'Asdrúbal, o Belo'], certa: 2, exp: 'Aníbal, filho de Amílcar Barca, invadiu a Itália pelos Alpes com elefantes.' },
  { p: 'Em que batalha foi Aníbal derrotado por Cipião, em 202 a.C.?', op: ['Canas', 'Zama', 'Trasimeno', 'Himera'], certa: 1, exp: 'Zama pôs fim à Segunda Guerra Púnica; Cartago perdeu o império.' },
  { p: 'Quem comandou as tropas romanas que tomaram Cartago em 146 a.C.?', op: ['Cipião Africano', 'Júlio César', 'Cipião Emiliano', 'Catão'], certa: 2, exp: 'Cipião Emiliano, neto adotivo do vencedor de Zama, tomou e destruiu a cidade.' },
  { p: 'Qual destas afirmações é verdadeira sobre o «sal lançado nas terras de Cartago»?', op: ['Foi feito por ordem do Senado', 'É uma invenção moderna', 'Foi relatado por Políbio', 'Está nas inscrições púnicas'], certa: 1, exp: 'A história do sal só aparece em autores modernos (séculos XIX – XX); nenhuma fonte antiga a menciona.' }
];

export default {
  id: 'fenicios',
  cor: '#7a3a8a',
  emblema: '../assets/img/fenicios.png',
  nome:    { pt: 'Fenícios e Cartago', en: 'Phoenicians and Carthage' },
  periodo: { pt: 'c. 1500 a.C. – 146 a.C.', en: 'c. 1500 BC – 146 BC' },
  visao:          { pt: visao, en: EN.visao },
  linha:          { pt: linha, en: EN.linha },
  mapa:           { pt: mapa, en: EN.mapa },
  sociedade:      { pt: sociedade, en: EN.sociedade },
  personalidades: { pt: personalidades, en: EN.personalidades },
  legado:         { pt: [...legado, ...CRED.pt], en: [...EN.legado, ...CRED.en] },
  quiz:           { pt: quiz, en: EN.quiz }
};
