// DIVISÃO, SUI E TANG (220–907) — conteúdo completo em português. A versão inglesa está em dados-en.js (mesma estrutura, mesmos ids de imagem).
// Datas convencionais das histórias dinásticas (Sanguozhi, Jinshu, Suishu, Jiu e Xin Tangshu, Zizhi Tongjian); números de população e de baixas são estimativas e assinalam-se como tal.
// Imagens: cada {img:'id'} procura o ficheiro  china/divisao-tang/img/id.jpg  (ver IMAGENS_CHINA_DIVISAO_TANG.md).
import EN from './dados-en.js';
import CRED from './creditos.js';
import { GRUPO } from '../grupo.js';

const visao = [
  { caixa: 'Em resumo', texto: [
    'Esta página cobre quase **setecentos anos**, de **220** (fim da dinastia Han) a **907** (fim da dinastia Tang). Começa com mais de três séculos e meio de **divisão**: os **Três Reinos**, a breve reunificação dos **Jin**, as invasões e reinos de povos do norte, e as **Seis Dinastias** do sul. Depois, em **581**, os **Sui** reunificam o país e constroem o **Grande Canal**; e em **618** os **Tang** instalam o império mais aberto, rico e cosmopolita que a China conhecera, com capital em **Chang’an**, uma das maiores cidades do mundo.',
    'É também o tempo em que o **budismo**, vindo da Índia, se torna parte da vida chinesa, em que a **poesia** atinge o auge (Li Bai, Du Fu), em que o **exame** para escolher funcionários se afirma, e em que uma **rebelião** (755–763) mostra que até o império mais brilhante pode desfazer-se. A dinastia só cairá em 907, e o país voltará a dividir-se nas **Cinco Dinastias**.'
  ] },
  { img: 'cdt-mapa-tres-reinos', leg: 'Mapa dos Três Reinos da China em 262 d.C.' },
  { h: 'Onde ficava' },
  'O cenário continua a ser o das dinastias anteriores: a **Planície Central**, no rio Amarelo, e o vale do **Yangtzé**. O que muda é o peso de cada zona. Durante a divisão, o norte é invadido e governado por povos de língua turca, mongol e tibetana, e milhões de chineses fogem para o sul, que se enche de gente, de arrozais e de cidades (**Jiankang**, a atual Nanjing, torna-se capital de seis dinastias sucessivas). Com os Sui e os Tang, o **Grande Canal** liga o norte político ao sul rico em arroz, e o império estende-se, no seu auge (século VII), do Pacífico ao deserto de Taklamacã e para além dele, com protetorados na Ásia Central.',
  { img: 'cdt-mapa-norte-sul', leg: 'Mapa do Wei do Norte e do Qi do Sul, finais do século V.' },
  { h: 'Quando existiu' },
  'As datas são as convencionais das histórias dinásticas chinesas. Os períodos de divisão têm várias sequências de reinos em paralelo, por isso a tabela dá só as principais.',
  { tabela: { cab: ['Fase', 'Datas', 'O que a marca'], linhas: [
    ['Três Reinos', '220 – 280', 'Wei (norte), Shu (sudoeste) e Wu (sul) disputam o legado dos Han; Cao Cao, Liu Bei, Sun Quan'],
    ['Jin Ocidental', '266 – 316', 'Reunificação (280) breve, desfeita pela Guerra dos Oito Príncipes e pelas invasões'],
    ['Dezasseis Reinos e Jin Oriental', '304 – 439 (norte) · 317 – 420 (sul)', 'Povos do norte fundam reinos; a corte Jin refugia-se em Jiankang'],
    ['Dinastias do Norte e do Sul', '420 / 439 – 589', 'No norte, Wei do Norte e sucessores; no sul, Song, Qi, Liang e Chen; auge do budismo'],
    ['Sui', '581 – 618', 'Reunificação (589); Grande Canal; guerras na Coreia; queda'],
    ['Tang', '618 – 907', 'Taizong, Wu Zetian, Xuanzong; Chang’an; An Lushan (755); declínio'],
    ['Cinco Dinastias e Dez Reinos', '907 – 960', 'Fragmentação no norte e no sul; só os Song a encerram (ver página Song e Yuan)']
  ] } },
  { img: 'cdt-mapa-sui', leg: 'Mapa do império Sui, c. 609' },
  { h: 'Porque importam estes séculos' },
  { lista: [
    '**Uma China dividida que se reencontra:** as invasões e as migrações misturaram chineses e povos do norte; os Tang, de ascendência em parte do norte, herdam essa mistura.',
    '**O budismo chinês:** de religião estrangeira passa a presença central na arte, na escrita e na vida; nascem escolas próprias, como o *Chan* (o Zen japonês).',
    '**O modelo de governo:** os Sui e os Tang fixam a organização do Estado (três departamentos e seis ministérios), a lei e o exame que durarão até 1905.',
    '**Cosmopolitismo:** Chang’an recebe mercadores sogdianos, persas, monges indianos e embaixadores coreanos e japoneses; é o primeiro grande cruzamento de culturas do Extremo Oriente.',
    '**Cultura:** a poesia Tang é, ainda hoje, a referência da poesia chinesa.'
  ] },
  { img: 'cdt-mapa-tang-755', leg: 'Mapa da extensão do Império Tang em 661 d.C.' },
  { h: 'Mito e romance: atenção aos Três Reinos' },
  'A imagem popular dos Três Reinos vem do romance *Romance dos Três Reinos* (*Sanguo yanyi*), escrito por **Luo Guanzhong** no século XIV, mais de mil anos depois dos factos. A fonte histórica é o *Sanguozhi* (*Registo dos Três Reinos*) de **Chen Shou** (233–297), com notas do século V de Pei Songzhi. O romance mistura factos e invenção: episódios como o «barco de palha que recolhe flechas» ou o «forte vazio» de Zhuge Liang são **ficção** (ou muito exagerados). Esta página segue o *Sanguozhi* e assinala o que é romance.',
  { caixa: 'Uma nota sobre números', texto: 'Os recenseamentos chineses mostram uma queda enorme da população: c. **56 milhões** de registados em 156 d.C. (Han), c. **16 milhões** em 280 (Jin). Mas muita gente deixou de ser registada, protegida por famílias poderosas, em fuga ou em zonas fora do controlo do Estado, por isso os números exprimem **perda de controlo** tanto como mortes. Os dados dos Tang (cerca de 50 milhões de registados em meados do século VIII) também são estimativas.' },
  { h: 'Hoje' },
  'Os sítios deste período continuam entre os mais visitados da China: as **grutas budistas** de Yungang, Longmen e Mogao (Património Mundial), o **Grande Canal** (UNESCO, 2014), a **Rota da Seda** (UNESCO, 2014, com Chang’an e outros sítios) e o **Grande Pagode do Ganso Selvagem**, em Xi’an. A poesia Tang é decorada pelas crianças chinesas, e a palavra **«tangren»** («gente Tang») ainda designa os chineses no estrangeiro, nos «bairros chineses» (*tangrenjie*): sinal do prestígio da dinastia.'
];

const linha = [
  'Esta linha do tempo percorre os grandes momentos entre 220 e 907. As datas são as convencionais; o que é lenda ou romance fica assinalado. Para os Han, ver a página Qin e Han; para os Song, a página Song e Yuan.',
  { linha: [
    { d: '208', t: 'Batalha de Chibi (Penhascos Vermelhos)', x: 'No Yangtzé, as forças aliadas de **Sun Quan** e **Liu Bei** derrotam o exército muito maior de **Cao Cao**, que ambicionava unificar o país. É a base da divisão em três. O romance exagera o papel de Zhuge Liang e dos «barcos de fogo»; o *Sanguozhi* confirma o fogo e a vitória aliada.' },
    { d: '220', t: 'Fim dos Han; nasce Wei', x: 'Morto Cao Cao (220), o seu filho **Cao Pi** obriga o último imperador Han a abdicar e funda a dinastia **Wei**, com capital em Luoyang. Pouco depois o sistema de **nove categorias** de recrutamento dos funcionários favorece as grandes famílias.' },
    { d: '221 – 229', t: 'Shu e Wu proclamam-se impérios', x: '**Liu Bei** declara-se imperador de **Shu Han** (221), em Chengdu, reclamando a herança Han; **Sun Quan** proclama o reino de **Wu**, com capital no sul, e toma o título de imperador em 229. Está formado o triângulo dos «Três Reinos».' },
    { d: '263 – 280', t: 'Jin reunifica a China', x: 'Wei conquista Shu (263); o general **Sima Yan** depõe o seu soberano e funda os **Jin** (266). Em 280, Wu rende-se e o império fica reunificado, mas por pouco tempo.' },
    { d: '311 – 316', t: 'Queda de Luoyang e de Chang’an', x: 'Depois da Guerra dos Oito Príncipes (291–306), os exércitos de chefes xiongnu tomam **Luoyang** (311) e **Chang’an** (316) e capturam os imperadores Jin. Começa a época dos «**Dezasseis Reinos**» do norte, fundados por povos como Xiongnu, Xianbei, Di, Jie e Qiang.' },
    { d: '317', t: 'Os Jin Orientais em Jiankang', x: 'Um príncipe Jin, **Sima Rui**, restabelece a dinastia em **Jiankang** (Nanjing). Grandes famílias do norte emigram em massa para o sul; é o início do desenvolvimento económico do Yangtzé.' },
    { d: '383', t: 'Batalha do rio Fei', x: 'O soberano **Fu Jian** do norte (Qin Anterior) tenta conquistar o sul com um exército gigantesco, segundo as fontes de c. 800 000 homens (número muito duvidoso), e é derrotado por forças muito menores dos Jin Orientais. O norte volta a fragmentar-se.' },
    { d: '386 – 439', t: 'Wei do Norte unifica o norte', x: 'O clã **Tuoba**, de origem xianbei, funda o Wei do Norte (386) e, em 439, reunifica o norte. Domina o norte durante cerca de um século, governando em simbiose com a administração e a aristocracia chinesas.' },
    { d: 'c. 460', t: 'Yungang: as grutas do Wei do Norte', x: 'Começa a escavação das grutas de **Yungang**, perto da capital Pingcheng (Datong), com Budas colossais, patrocinadas pela corte. Foram um dos grandes centros da escultura budista.' },
    { d: '494', t: 'Xiaowen muda a capital para Luoyang', x: 'O imperador **Xiaowen** do Wei do Norte transfere a corte para **Luoyang**, proíbe o traje e a língua xianbei na corte e promove nomes e casamentos chineses. A «sinização» é debatida: modernizou o Estado, mas provocou descontentamento entre os soldados da fronteira. Em Luoyang começam as grutas de **Longmen**.' },
    { d: '534', t: 'O Wei do Norte divide-se', x: 'Revoltas dos guarnecidos da fronteira rasgam o reino: Wei Oriental (534) e Wei Ocidental (535), depois Qi do Norte e Zhou do Norte. O Zhou do Norte conquista o Qi em 577 e reunifica o norte.' },
    { d: '581', t: 'Yang Jian funda os Sui', x: 'O general **Yang Jian**, regente do Zhou do Norte, força a abdicação do jovem imperador e funda a dinastia **Sui** (581), tornando-se o imperador **Wen**. Constrói a nova capital, **Daxing**, a sudeste da antiga Chang’an.' },
    { d: '589', t: 'Sui reunifica a China', x: 'Com uma frota e um exército que cruzam o Yangtzé, os Sui conquistam o último dos reinos do sul, **Chen**, e a China fica unida depois de quase **370 anos** de divisão (a contar de 220, com o breve intervalo dos Jin).' },
    { d: '605 – 610', t: 'O Grande Canal', x: 'O imperador **Yang** (604–618) manda abrir ou unir canais entre Luoyang, o Yangtzé e Hangzhou, e para norte até à região de Pequim. Segundo as fontes, trabalharam mais de um milhão de pessoas, número que os historiadores consideram provavelmente exagerado.' },
    { d: '612 – 618', t: 'Guerras na Coreia e queda dos Sui', x: 'Três campanhas contra o reino coreano de **Goguryeo** (612, 613 e 614) falham e esgotam o império; o trabalho forçado nas obras provoca revoltas. Em 618 o imperador Yang é assassinado em Jiangdu (Yangzhou) por um oficial.' },
    { d: '618', t: 'Li Yuan funda os Tang', x: 'O governador de Taiyuan, **Li Yuan**, que se tinha revoltado em 617 com o filho **Li Shimin**, entra em Chang’an (617) e, em 618, proclama a dinastia **Tang**, tomando o título de imperador **Gaozu**.' },
    { d: '626 – 649', t: 'Taizong e o «governo de Zhenguan»', x: 'Depois de matar dois irmãos no incidente da Porta Xuanwu (626), **Li Shimin** sobe ao trono como **Taizong**. Reinando com ministros fortes, derrota os Turcos Orientais (630), organiza o Estado e é lembrado como modelo de governante.' },
    { d: '629 – 645', t: 'A viagem de Xuanzang', x: 'O monge **Xuanzang** parte sem licença para a Índia (em 629, segundo a data mais comum; algumas fontes indicam 627), para estudar e trazer escrituras budistas, e regressa a Chang’an em 645 com 657 textos. O seu relato é uma fonte essencial sobre a Ásia Central e a Índia; mais tarde inspira o romance *Viagem ao Ocidente* (século XVI).' },
    { d: 'c. 660 – 670', t: 'O apogeu territorial', x: 'Com o seu filho **Gaozong**, os Tang, aliados do reino coreano de Silla, destroem Baekje (660) e Goguryeo (668), e controlam o Tarim e partes da Ásia Central. É a maior extensão da dinastia. Os Tibetanos, entretanto, tornam-se rivais fortes.' },
    { d: '690 – 705', t: 'Wu Zetian, imperatriz', x: 'Concubina de Taizong e depois esposa de Gaozong, **Wu Zetian** governa de facto desde cerca de 660 e, em 690, proclama a dinastia **Zhou**, sendo a única mulher a reinar em nome próprio na história imperial. É deposta em 705, num golpe palaciano, e morre nesse ano.' },
    { d: '712 – 756', t: 'Xuanzong: do auge à crise', x: 'O imperador **Xuanzong** inaugura a era *Kaiyuan* (713–741), de paz e prosperidade, em que Chang’an e a cultura florescem. Nos anos de *Tianbao* (742–756), o governo enfraquece e dá poder a generais de fronteira.' },
    { d: '751', t: 'Batalha do rio Talas', x: 'Um exército Tang comandado por **Gao Xianzhi** é derrotado, junto ao rio Talas (hoje no Cazaquistão ou Quirguistão), por forças do Califado Abássida e aliados. Marca o limite do avanço Tang para oeste. A tradição de que prisioneiros chineses ensinaram a fazer papel aos árabes é debatida.' },
    { d: '755 – 763', t: 'Rebelião de An Lushan', x: 'O general **An Lushan**, com o comando de três regiões do nordeste, revolta-se (dezembro de 755), toma Luoyang e proclama a dinastia Yan. **Xuanzong** foge para Sichuan; em Mawei os soldados exigem a morte de Yang Guifei. A rebelião, continuada por Shi Siming e outros, acaba em 763. Os Tang sobrevivem, mas o poder dos governadores militares torna-se quase independente.' },
    { d: '845', t: 'Perseguição Huichang ao budismo', x: 'O imperador **Wuzong** manda destruir milhares de mosteiros e devolver monges ao estado laico, em parte por razões fiscais (os mosteiros não pagavam impostos). Segundo as fontes, mais de 4600 mosteiros e cerca de 260 000 monges e monjas. Acaba em 846 com a morte do imperador.' },
    { d: '868', t: 'O Sutra do Diamante impresso', x: 'Em Dunhuang, **Wang Jie** manda imprimir o *Sutra do Diamante*, o livro impresso com data mais antigo conhecido do mundo. O rolo foi descoberto em 1900 e encontra-se hoje na Biblioteca Britânica.' },
    { d: '874 – 884', t: 'Huang Chao', x: 'O revoltoso **Huang Chao**, ex-candidato falhado nos exames, e o seu exército percorrem a China, tomam Guangzhou (879) e **Chang’an** (880). É vencido em 884, mas a corte já era uma sombra de si própria.' },
    { d: '907', t: 'Fim dos Tang', x: 'O antigo oficial de Huang Chao, **Zhu Wen**, que se tinha aliado aos Tang, depõe o último imperador e funda a dinastia **Liang Posterior**, a primeira das Cinco Dinastias. Os Tang tinham durado 289 anos.' },
    { d: '907 – 960', t: 'Cinco Dinastias e Dez Reinos', x: 'No norte sucedem-se cinco dinastias efémeras (Liang, Tang, Jin, Han e Zhou Posteriores); no sul e no oeste, uns dez reinos. Em 936, Shi Jingtang, ajudado pelos Khitan (Liao), funda os Jin Posteriores e cede-lhes dezasseis prefeituras do norte. Em 960, **Zhao Kuangyin** funda os Song: ver a página Song e Yuan.' }
  ] },
  { img: 'cdt-ai-tres-reinos-chibi', leg: 'Batalha dos Penhascos Vermelhos, 208 d.C.; interpretação artística. Ilustração gerada por IA.' },
  { img: 'cdt-ai-rebeldes-an-lushan', leg: 'Avanço do exército rebelde de An Lushan, 755–756. Ilustração gerada por IA.' }
];

const mapa = [
  'Este período tem várias capitais ao mesmo tempo. O mapa que se segue é a lista dos lugares que importam, desde as cidades dos Três Reinos às cidades Tang e aos sítios budistas.',
  { tabela: { cab: ['Lugar', 'Época', 'Hoje', 'Para que ficou conhecido'], linhas: [
    ['Luoyang', 'Han Oriental, Wei, Jin, Wei do Norte, Sui, Tang (capital «oriental»)', 'Luoyang, Henan', 'Capital várias vezes; grutas budistas de Longmen'],
    ['Chang’an', 'Tang (e Sui, como Daxing)', 'Xi’an, Shaanxi', 'Capital imperial e cidade cosmopolita'],
    ['Jiankang', 'Wu, Jin Oriental e dinastias do Sul', 'Nanjing, Jiangsu', 'Capital do sul durante mais de três séculos, com interrupção (c. 229 – 589)'],
    ['Pingcheng', 'Wei do Norte (398 – 494)', 'Datong, Shanxi', 'Primeira capital do Wei; Yungang'],
    ['Ye (Yecheng)', 'Wei de Cao Cao, Qi do Norte', 'Linzhang, Hebei', 'Capital de vários reinos do norte'],
    ['Chengdu', 'Shu Han; Tang (refúgio de Xuanzong)', 'Sichuan', 'Capital de Liu Bei; riqueza da bacia de Sichuan'],
    ['Yangzhou', 'Sui e Tang', 'Jiangsu', 'Grande porto do Canal, de sal e comércio'],
    ['Guangzhou', 'Tang', 'Guangdong', 'Porto marítimo com mercadores árabes e persas'],
    ['Dunhuang', 'Han a Tang', 'Gansu', 'Porta do deserto; grutas de Mogao'],
    ['Turfan (Gaochang)', 'Conquistada pelos Tang em 640', 'Xinjiang', 'Oásis; vinha e manuscritos'],
    ['Taiyuan', 'Tang (capital do Norte)', 'Shanxi', 'Onde se revoltou Li Yuan em 617'],
    ['Monte Wutai', 'Wei do Norte a Tang', 'Shanxi', 'Montanha sagrada budista; templo de Nanchan (782)'],
    ['Bianzhou', 'Final dos Tang e Cinco Dinastias', 'Kaifeng, Henan', 'Futura capital dos Song'],
    ['Lhasa', 'Reino Tibetano (Tubo)', 'Tibete', 'Rival e aliado dos Tang; casamento de Wencheng (641)']
  ] } },
  { h: 'Luoyang: a cidade dos muitos imperadores' },
  'Luoyang, no rio Luo, foi capital dos Han Orientais, dos Wei de Cao Pi, dos Jin Ocidentais e do Wei do Norte (depois de 494), e mais tarde os Sui e os Tang a fizeram sua «capital oriental». Era um ponto estratégico: tinha acesso fácil ao Grande Canal e aos celeiros do leste. Na sua queda, em 311, os cronistas descrevem destruição enorme e a morte de dezenas de milhares de pessoas, números a tomar com cautela.',
  { img: 'cdt-longmen-vairocana', leg: 'Buda Vairocana de Fengxian, grutas de Longmen' },
  { h: 'Jiankang e o sul' },
  'Jiankang, hoje Nanjing, foi capital de **seis dinastias** (Wu, Jin Oriental, Song, Qi, Liang e Chen), e daí vem a expressão «Seis Dinastias» para a cultura do sul. Era uma cidade de aristocratas cultos, mosteiros e mercadores. Segundo a tradição, havia no tempo da dinastia Liang perto de 500 mosteiros (o poeta Du Mu falou de 480). Tomada em 589 pelos Sui, a cidade foi arrasada e deixou de ser capital durante séculos.',
  { h: 'Chang’an: a cidade em quadrícula' },
  'A **Chang’an dos Tang** assentava na cidade planeada pelos Sui (Daxing). Tinha uma muralha de terra batida de cerca de **9,7 km por 8,6 km** (cerca de 84 km²), ruas em quadrícula, uma avenida central, a **Zhuque**, com cerca de 150 m de largura, e **110 bairros** (*fang*) muralhados, com portas que se fechavam ao toque de tambores ao fim do dia. Havia dois grandes mercados oficiais, o **Mercado Leste** e o **Mercado Oeste**, este último o dos mercadores estrangeiros. A população (cidade e arredores) é estimada em **cerca de um milhão**, embora haja quem defenda números menores (500 000 a 800 000).',
  { img: 'cdt-ai-chang-an-mercado', leg: 'Mercado Ocidental de Chang’an Tang, século VIII. Ilustração gerada por IA.' },
  { img: 'cdt-pagode-ganso', leg: 'Grande Pagode do Ganso Selvagem, Xi’an' },
  { h: 'O Grande Canal e Yangzhou' },
  'O **Grande Canal** liga as bacias do rio Amarelo e do Yangtzé. O seu eixo principal na época Sui e Tang era o canal **Tongji**, de Luoyang a Yangzhou, e o canal de **Jiangnan**, de Yangzhou a Hangzhou. Levava arroz e impostos em espécie do sul para o norte, e foi, durante séculos, a espinha dorsal económica do império. O canal que hoje vemos (cerca de **1776 km**, entre Pequim e Hangzhou) resulta de alterações posteriores, sobretudo dos Yuan e dos Ming.',
  { img: 'cdt-grande-canal', leg: 'Troço do Grande Canal em Hangzhou' },
  { img: 'cdt-ai-grande-canal', leg: 'Barcaças de cereais no Grande Canal Sui, c. 610. Ilustração gerada por IA.' },
  { h: 'Dunhuang e as grutas de Mogao' },
  'Dunhuang, no fim do corredor de Hexi, era a porta do deserto. A sul da cidade, as **grutas de Mogao** começaram a ser escavadas em **366** (segundo a tradição) e estenderam-se por mais de mil anos, com centenas de grutas pintadas. Na chamada **gruta da biblioteca** (descoberta em 1900) encontraram-se milhares de manuscritos, incluindo o *Sutra do Diamante* de 868, textos em tibetano, sogdiano, hebraico e outras línguas.',
  { img: 'cdt-mogao-gruta', leg: 'Exterior e câmaras das grutas de Mogao, Dunhuang.' },
  { h: 'Fronteiras e protetorados' },
  'No seu auge, os Tang administraram a Ásia Central através de **protetorados** (*duhufu*), como Anxi (em Kucha) e Beiting, com guarnições, postos e tropas auxiliares, e controlaram durante décadas as cidades-oásis do Tarim. A oeste e sul, o reino do **Tibete** foi um rival formidável: chegou a tomar Chang’an por poucos dias em 763. A nordeste, os Tang combateram, ora aliados ora inimigos, Goguryeo, os Khitan e Balhae; a norte, os Turcos e depois os Uigures.',
  { h: 'Batalhas e lugares de memória' },
  { lista: [
    '**Chibi (208), no Yangtzé:** vitória aliada sobre Cao Cao; o local exato ainda é discutido.',
    '**Rio Fei (383), Anhui:** a vitória do sul sobre o Qin Anterior.',
    '**Porta Xuanwu (626), Chang’an:** o golpe de Li Shimin contra os irmãos.',
    '**Talas (751):** o encontro dos Tang com o Califado, no Cazaquistão ou Quirguistão atuais.',
    '**Passo de Tong (756):** a queda do desfiladeiro que protegia Chang’an, aberto aos rebeldes de An Lushan.',
    '**Mawei (756):** onde a escolta de Xuanzong exigiu a morte de Yang Guifei.'
  ] },
  { h: 'Rotas da Seda e rotas do mar' },
  'Chang’an era o ponto de partida da **Rota da Seda** continental, que passava pelo corredor de Hexi, por Dunhuang e Turfan, e prosseguia para Samarcanda, a Pérsia e a Síria. A **rota marítima**, a partir de Guangzhou e de Yangzhou, ligava a China à Índia, ao golfo Pérsico e ao Leste de África. Em 758 Guangzhou foi saqueada por árabes e persas; em 879, Huang Chao tomou a cidade e as fontes árabes falam de um massacre de estrangeiros, com números que os historiadores tomam com muita cautela.',
  { h: 'O sul e o sudoeste' },
  'Para lá do Yangtzé, as regiões de Fujian, Guangdong e Yunnan foram integradas aos poucos. Em Yunnan, o reino de **Nanzhao** (738–902) foi um vizinho independente. O Vietname do Norte era então o protetorado de Annam (679), e as regiões do extremo sul serviam de exílio para funcionários caídos em desgraça.'
];

const sociedade = [
  { h: '1. Organização política: dos Três Reinos aos Tang' },
  'Os **Três Reinos** eram Estados militares: **Wei** (norte), com os exércitos e os celeiros militares de Cao Cao; **Shu** (sudoeste), mais pequeno e pobre, e **Wu** (sul), com uma marinha forte. Nenhum conseguiu vencer os outros por muito tempo. Durante a divisão seguinte, o poder passou muitas vezes para **famílias aristocráticas**, que dominavam os cargos pelo sistema das **nove categorias** (*jiupin zhongzheng*): um funcionário local classificava os candidatos, e as grandes famílias obtinham sempre as melhores.',
  'Os **Sui** e os **Tang** reorganizaram o Estado de forma que durou séculos: o governo central tinha **três departamentos** (*sheng*: Secretaria, Chancelaria e Departamento dos Assuntos de Estado) e, sob este último, **seis ministérios** (Pessoal, Rendas, Ritos, Guerra, Justiça e Obras). Abaixo havia províncias (*dao*), prefeituras (*zhou*) e distritos (*xian*). Os funcionários eram nomeados, e rodados de posto, e um órgão de inspeção, o **Censorado**, vigiava-os. O imperador continuava a ser a fonte da lei.',
  { img: 'cdt-ai-corte-taizong', leg: 'Audiência na corte de Taizong, século VII. Ilustração gerada por IA.' },
  { img: 'cdt-yan-liben', leg: 'Rolo dos Treze Imperadores, atribuído a Yan Liben, Museum of Fine Arts, Boston' },
  { h: '2. A lei e as terras' },
  'O **Código Tang** (*Tang lü*, completo em 653, com comentários) é o código chinês mais antigo que chegou inteiro até nós, e serviu de modelo ao Japão, à Coreia e ao Vietname. Previa cinco castigos (pancadas com vara leve, vara pesada, trabalhos forçados, exílio, morte) e distinguia crimes graves, como a traição e a impiedade filial, os «Dez Abomináveis». Previa também atenuantes para os nobres e para os funcionários.',
  'Para evitar que os camponeses perdessem as terras para os grandes proprietários, o Wei do Norte, os Sui e os Tang praticaram o sistema das **terras iguais** (*juntian*): o Estado atribuía a cada família um lote vitalício, com uma parte hereditária, em troca de impostos em grão (*zu*), em tecidos (*diao*) e em trabalho (*yong*). O sistema funcionou bem no início, mas com o crescimento da população e a concentração de terra nas mãos de poderosos, **desfez-se** no século VIII.',
  { h: '3. As grandes famílias e a sociedade' },
  'Até aos Tang, a elite era formada por **grandes clãs** (como os Cui de Boling, os Lu de Fanyang, os Zheng de Xingyang, os Wang de Taiyuan e os Li de Longxi), que se casavam entre si e se diziam descendentes de nobres antigos. Os próprios imperadores Tang, de família Li de Longxi, tinham ligações familiares aos povos do norte. Abaixo estavam os camponeses livres, os arrendatários, os artesãos e mercadores, e os **servos e escravos** (por dívida, condenação ou compra). Os mercadores eram teoricamente desprezados, mas muitos enriqueceram.',
  'As **mulheres** tinham, nos Tang, mais liberdade social do que em épocas posteriores: montavam a cavalo, jogavam polo, vestiam-se em modas estrangeiras e, nas elites, tinham voz na política. Mas a lei e a moral confuciana subordinavam-nas ao pai, ao marido e ao filho. A **atadura dos pés** só se espalhou mais tarde (as origens situam-se no fim dos Tang ou nas Cinco Dinastias, e a difusão nos Song; a data é debatida).',
  { img: 'cdt-tang-damas', leg: 'Damas da corte com flores no cabelo, atribuído a Zhou Fang, Museu de Liaoning' },
  { img: 'cdt-ai-polo-tang', leg: 'Mulheres aristocratas a jogar polo, época Tang. Ilustração gerada por IA.' },
  { h: '4. O exame imperial' },
  'Os Sui criaram os exames para recrutar funcionários (a data tradicional é 605, mas a evolução é debatida). Os **Tang** desenvolveram-nos: havia vários graus, o mais prestigiado era o do **jinshi** («erudito apresentado»), que exigia o conhecimento dos clássicos, a composição de ensaios e de **poemas**. Só algumas dezenas de candidatos passavam por ano, e muitos tentavam durante décadas. Os grandes clãs continuaram a dominar o poder até ao fim dos Tang, e o exame só se tornou o caminho principal no tempo dos Song. Mas já se via o princípio: o **mérito**, medido por texto, podia substituir o berço.',
  { h: '5. O budismo chinês' },
  'O budismo chegou à China no século I d.C., pela Rota da Seda, e foi durante séculos uma religião de estrangeiros. Com o colapso dos Han e as invasões, tornou-se atrativo: prometia consolo e dava aos governantes do norte uma religião não ligada ao confucionismo. Nos séculos V e VI, o **Wei do Norte**, os imperadores do sul (como **Wu de Liang**, 502–549) e muitos fiéis financiaram templos, mosteiros e grutas. Segundo as fontes, o Wei do Norte tinha, em 477, mais de 6000 templos e cerca de 77 000 monges e monjas, e muito mais nas décadas seguintes (números incertos).',
  'Os grandes tradutores, como **Kumarajiva** (c. 344–413, em Chang’an), tornaram as escrituras indianas legíveis em chinês. Surgiram **escolas chinesas**: **Tiantai** (Zhiyi, 538–597), **Huayan**, **Terra Pura** (devoção a Amitabha) e o **Chan**, que insiste na meditação direta, sem escrituras (a tradição atribui a sua origem ao indiano Bodhidharma, figura de muita lenda; o patriarca Huineng, 638–713, é mais firmemente histórico). Os mosteiros eram também bancos, hospitais, escolas e estalagens.',
  { img: 'cdt-yungang-buda', leg: 'Buda sentado das grutas de Yungang, Datong' },
  { img: 'cdt-ai-copista-budista', leg: 'Monges a copiar sutras em Dunhuang, século IX. Ilustração gerada por IA.' },
  { h: 'Críticas e perseguições' },
  'O budismo teve sempre críticos: os confucianos recusavam o celibato, o culto das imagens e a isenção fiscal; os daoístas competiam com ele. Houve **perseguições**: em 446 (Wei do Norte), em 574 (Zhou do Norte) e, a maior, em **842–845** (Tang), de que fala a linha do tempo. O budismo sobreviveu, mas nunca mais teve o poder do século VII.',
  { h: '6. Daoísmo e outros cultos' },
  'O **Daoísmo** organizado (Mestres Celestiais, Maoshan) teve apoio dos Tang, que diziam descender de **Laozi**, cujo apelido era Li. Os alquimistas procuravam elixires da imortalidade (e vários imperadores Tang morreram, ao que parece, de elixires com mercúrio ou chumbo, segundo alguns historiadores). Em Chang’an conviviam outras religiões: o **cristianismo nestoriano** (missão de Alopen, 635; a estela de 781 em Xi’an tem texto em chinês e siríaco), o **zoroastrismo**, o **maniqueísmo** (adotado pelos Uigures) e o **islão**, trazido por mercadores.',
  { img: 'cdt-estela-nestoriana', leg: 'Estela nestoriana de Xi’an, 781' },
  { h: '7. Economia, moeda e comércio' },
  'Com os Sui e os Tang, a economia recuperou. O centro de gravidade deslocou-se para o sul: o **arroz** do Yangtzé, a seda, o chá e o sal alimentaram o império. A moeda de referência era o **cash** de bronze com buraco quadrado: os Tang, em 621, criaram o *Kaiyuan Tongbao*, que se tornou o modelo durante mais de mil anos. O dinheiro era pouco, e usavam-se também **rolos de seda** e grão como meio de pagamento. No século IX apareceram os **«dinheiros voadores»** (*feiqian*), letras de câmbio que os mercadores usavam para evitar transportar moeda.',
  { img: 'cdt-moedas-kaiyuan', leg: 'Moedas Kaiyuan Tongbao, dinastia Tang' },
  'O Estado instituiu o **monopólio do sal** a partir de 758, que chegou a dar, no fim do século VIII, cerca de metade da receita do governo, segundo as fontes tradicionais (valor a tomar com cautela). Cidades como Yangzhou, Chengdu e Guangzhou enriqueceram com o comércio. O correio oficial dispunha de **estações** (*yi*) com cavalos para os mensageiros.',
  { h: '8. Os estrangeiros e os Sogdianos' },
  'Os **Sogdianos**, mercadores do vale de Samarcanda, foram os grandes intermediários da Rota da Seda. Viviam em comunidades em Chang’an e Dunhuang, importavam cavalos, prata, vidro e vinho, e traziam a música e a dança da Ásia Central. Os Tang receberam também embaixadores e estudantes **coreanos** e **japoneses** (o Japão copiou o plano de Chang’an para as suas capitais, Heijō-kyō/Nara e Heian-kyō/Quioto), persas exilados (como o príncipe Peroz, filho do último rei sassânida), monges indianos e mercadores árabes. Havia estrangeiros entre os generais, como **An Lushan**, de pai sogdiano (segundo as fontes) e mãe turca.',
  { img: 'cdt-ai-mercador-sogdiano', leg: 'Mercador sogdiano em Chang’an Tang. Ilustração gerada por IA.' },
  { h: '9. A casa e a cidade' },
  'Em Chang’an, as casas ficavam em **bairros murados**. As famílias ricas viviam em complexos de pátios, com pavilhões de madeira, telhados de telha, jardins e lagos; os pobres, em casas simples de taipa. Nesta época, a vida deixou lentamente de se fazer sentado em esteiras no chão, e **cadeiras e bancos**, trazidos por povos do norte, foram-se espalhando, o que alterou a altura das mesas e a forma das casas (o processo completa-se nos Song). Dentro das casas havia braseiros e biombos; as janelas eram de papel.',
  { img: 'cdt-ai-casa-tang', leg: 'Casa de pátio de uma família Tang. Ilustração gerada por IA.' },
  { h: '10. Alimentação e bebidas' },
  'Comia-se **painço** e **trigo** no norte (em papas, pão cozido, noodles e bolos), e **arroz** no sul. Os Tang apreciavam **pastelaria** e os **pães achatados com sésamo** (*hu bing*, «pães dos *hu*», nome dado aos povos do Ocidente). Trouxeram-se vinhas de Turfan depois de 640 e plantou-se vinho de uva; também se importou da Índia a tecnologia do **açúcar**. O **chá** passou de remédio e bebida de monges a bebida nacional: **Lu Yu** (733–804) escreveu o *Clássico do Chá* (c. 760–780). Comia-se com pauzinhos e colher, ainda sentado em esteiras ou em bancos.',
  { h: '11. Vestuário e moda' },
  'Os homens usavam túnica de gola redonda, cinto e chapéu de gaze (*futou*); as cores indicavam o posto. As mulheres da elite usavam saias longas de cintura alta, mantos de seda, xailes e, nalgumas fases, **decotes** e roupas de estilo «bárbaro» (*hu*), com mangas estreitas e botas. Penteados altos, flores, **cosméticos** e mantos transparentes eram a moda. É frequente dizer-se que os Tang preferiam mulheres roliças, mas isto é em parte estereótipo: as pinturas mostram uma variedade de ideais.',
  { h: '12. Música, dança e jogos' },
  'A música da corte juntou instrumentos chineses (a cítara *qin*, o *guzheng*) e da Ásia Central (o alaúde **pipa**, a flauta, os tambores). O imperador **Xuanzong** fundou o **Jardim das Pereiras** (*Liyuan*), uma escola de música e dança. Dançavam-se danças sogdianas (*huxuan*, «o giro») e jogava-se **polo** a cavalo, popular entre homens e mulheres, e o *weiqi* (go) e o tiro com arco. Os túmulos incluíam figuras de dançarinas e músicos em cerâmica.',
  { img: 'cdt-ai-banquete-poetas', leg: 'Banquete de poetas Tang num pavilhão de jardim. Ilustração gerada por IA.' },
  { h: '13. A poesia Tang' },
  'A poesia foi a grande arte dos Tang e fazia parte do exame e da vida social. Dela se conservam cerca de **49 000 poemas**, de cerca de **2200 poetas**, reunidos em 1705 na antologia *Quan Tang shi*. Há formas fixas (o **poema regulado**, *lüshi*, de oito versos, e a quadra *jueju*). Os grandes nomes: **Wang Wei** (c. 699–759), poeta e pintor budista; **Li Bai** (701–762), vivo e fantasista; **Du Fu** (712–770), o poeta «sábio da poesia», autor de versos sobre a guerra e a miséria; **Bai Juyi** (772–846), claro e popular; **Li Shangyin** (c. 813–858), sugestivo e obscuro.',
  { cit: 'Diante da minha cama, o luar: / parece geada sobre o chão. / Ergo a cabeça, vejo a lua; / baixo-a, e penso na minha terra.', fonte: '«Pensamentos numa noite tranquila», poema atribuído a Li Bai (versão livre; o texto circula em variantes)' },
  { h: '14. Pintura, caligrafia e arte funerária' },
  'A pintura de figura e de paisagem atingiu grande nível: **Wu Daozi** (c. 685–758) foi o «santo da pintura», autor de murais budistas; **Han Gan** pintou cavalos; **Zhou Fang** pintou damas da corte. Na caligrafia, a escola de **Wang Xizhi** (século IV) continuou a ser o modelo e brilharam **Ouyang Xun**, **Yan Zhenqing** (709–785) e **Liu Gongquan**. Os túmulos da elite Tang eram decorados com **murais** e cheios de figuras de cerâmica (*mingqi*) vidradas em tons de verde, ocre e branco, os **sancai** («três cores»).',
  { img: 'cdt-tang-sancai', leg: 'Cavalo de cerâmica sancai, dinastia Tang' },
  { img: 'cdt-mural-yongtai', leg: 'Mural do túmulo da princesa Yongtai, Qianling' },
  { h: '15. Cerâmica e porcelana' },
  'O sul do Yangtzé tinha uma tradição de grés vidrado, os **celadons** verdes do tipo **Yue** (Zhejiang). No norte, os fornos de Xing faziam grés branco. Os Tang aproximaram-se da porcelana verdadeira: uma pasta branca, dura e translúcida, cozida a alta temperatura. A porcelana plena (com a técnica madura) é geralmente associada aos séculos seguintes, e a data exata em que ela «nasce» é debatida. Os Tang já exportavam cerâmica pelo mar: foram encontrados fragmentos chineses de época Tang em Samarra (Iraque), Siraf (Irão) e Fustate (Egito).',
  { img: 'cdt-celadon-yue', leg: 'Jarro de grés celadon tipo Yue' },
  { h: '16. Ciência e tecnologia' },
  { tabela: { cab: ['Realização', 'Quando', 'Notas'], linhas: [
    ['Estribos', 'século IV', 'Os primeiros estribos de par aparecem em túmulos do século IV; mudam a guerra a cavalo'],
    ['Cálculo de π', 'c. 480', '**Zu Chongzhi** (429–500) calcula π entre 3,1415926 e 3,1415927, uma precisão que só foi igualada séculos depois'],
    ['Imprensa de blocos', 'século VII a IX', 'Primeiras impressões xilográficas; o *Sutra do Diamante* de 868 é o exemplar datado mais antigo'],
    ['Cadastro e calendário', 'século VIII', '**Yi Xing** (683–727), monge e astrónomo, mede o arco de meridiano e constrói um relógio astronómico de água'],
    ['Pólvora', 'século IX – X', 'Alquimistas descrevem misturas de salitre, enxofre e carvão; só no século X aparece o uso militar'],
    ['Medicina', 'século VII', '**Sun Simiao** escreve o *Mil Peças de Ouro para Emergências*; Tang faz a primeira farmacopeia oficial (659)'],
    ['Engenharia', 'c. 595 – 605', 'Ponte em arco segmentar de Zhaozhou (Sui), do engenheiro Li Chun']
  ] } },
  'A **ponte de Zhaozhou** (Hebei, c. 595–605, construída pelo engenheiro **Li Chun**) é a mais antiga ponte em arco segmentar aberto que se conserva no mundo, com um vão de cerca de 37 m. A **imprensa** não era ainda a dos livros em série, mas serviu para fazer sutras, calendários e amuletos budistas.',
  { h: '17. Guerra e exército' },
  'O exército Tang começou com o sistema de **milícias** (*fubing*): soldados-camponeses que cultivavam as terras e serviam por turnos, com cavalaria forte (os Tang importaram cavalos da Ásia Central). Perto de 750, o sistema deixou de funcionar, e na fronteira passaram a existir **exércitos profissionais** sob **governadores militares** (*jiedushi*). Essa mudança, necessária para defender as fronteiras, criou os generais poderosos de que veio a rebelião de An Lushan. Os Tang usavam armaduras, bestas, cavalaria pesada e, nos cercos, catapultas e máquinas de guerra; contratavam arqueiros turcos e Uigures.',
  { img: 'cdt-ai-cavalaria-tang', leg: 'Cavalaria Tang em marcha, século VII. Ilustração gerada por IA.' },
  { h: '18. A rebelião de An Lushan e o fim do equilíbrio' },
  'A rebelião de **755–763** é a grande viragem. An Lushan, com os seus 150 000 homens (estimativa) das fronteiras do nordeste, revoltou-se em dezembro de 755, tomou Luoyang em janeiro de 756 e o Passo de Tong em julho de 756; a corte fugiu. Os Tang só recuperaram o controlo com a ajuda dos Uigures e de comandantes como **Guo Ziyi**. Os registos de população caem de cerca de 53 milhões (754) para uns 17 milhões (764): o número reflete muito mais a **perda de controlo** do que a morte de milhões, mas as vítimas foram, sem dúvida, imensas.',
  'Depois da rebelião, o governo central perdeu os impostos do nordeste, e os **governadores militares** (*jiedushi*) de Hebei governaram como príncipes quase independentes. Os **eunucos** da corte ganharam o comando do exército do palácio e fizeram e desfizeram imperadores. A reforma fiscal do **duplo imposto** (780) acompanhou a mudança: cobrava-se a terra, não as pessoas. A queda estava, de facto, anunciada, mas demorou mais de um século.',
  { h: '19. O fim dos Tang e as Cinco Dinastias' },
  'As revoltas de **Huang Chao** (874–884) destruíram o que restava do poder central: Chang’an foi saqueada em 880. Os governadores regionais tornaram-se senhores. **Zhu Wen** depôs o último imperador em 907, e o país dividiu-se. No norte, as **Cinco Dinastias** (907–960): Liang, Tang, Jin, Han e Zhou Posteriores, as três do meio fundadas por chefes **shatuo** (turcos). Em 932–953, o ministro **Feng Dao** mandou imprimir os Nove Clássicos por xilogravura, um marco da cultura impressa. No sul, os **Dez Reinos**, como o Tang do Sul, cujo último soberano, o poeta **Li Yu** (937–978), é um dos grandes autores da poesia *ci*.',
  { h: 'Mulan: lenda e história' },
  'A *Balada de Mulan*, de autor desconhecido, descreve uma rapariga que se disfarça de homem para ir à guerra em lugar do pai e que, ao regressar, recusa honrarias. Foi composta provavelmente no tempo do Wei do Norte (século V – VI), e depois retocada nos Tang. Mulan é uma **personagem lendária**; não há prova de que tenha existido. A história dela, porém, mostra a presença dos costumes dos povos do norte, onde as mulheres cavalgavam e combatiam.'
];

const personalidades = [
  'As figuras abaixo são históricas; os aspetos lendários (sobretudo em Cao Cao, Zhuge Liang, Bodhidharma e Mulan) vêm indicados. As principais fontes são o *Sanguozhi*, o *Jinshu*, o *Suishu*, os *Tangshu* (velho e novo), o *Zizhi Tongjian* e os próprios poemas.',
  { h: 'Cao Cao (155 – 220)' },
  'Chefe militar e poeta, neto de um eunuco influente (o pai fora por ele adotado). Depois da revolta dos Turbantes Amarelos, tornou-se o senhor de facto do norte, tendo o imperador Han como figura nas mãos. Foi derrotado em Chibi (208), mas lançou as bases do reino de **Wei**, organizando colónias agrícolas militares (*tuntian*). Nos romances aparece como vilão; os historiadores veem nele um administrador capaz e implacável. O seu filho Cao Pi, ao fundar Wei, honrou-o postumamente como imperador.',
  { img: 'cdt-cao-cao', leg: 'Retrato tradicional de Cao Cao (obra posterior)' },
  { h: 'Zhuge Liang (181 – 234)' },
  'Chanceler do reino de Shu, depois da morte de **Liu Bei** (223). Dirigiu uma administração justa e organizou as campanhas do norte contra Wei, que não deram resultado. Morreu no campo, em Wuzhangyuan. O *Sanguozhi* elogia-o como administrador, mas diz que lhe faltava talento militar de génio. O Zhuge Liang do romance, com leques de penas e artimanhas milagrosas, é uma **criação literária** de séculos depois.',
  { img: 'cdt-zhuge-liang', leg: 'Retrato tradicional de Zhuge Liang no Sancai Tuhui, 1609.' },
  { h: 'Wang Xizhi (séc. IV) e Tao Yuanming (c. 365 – 427)' },
  '**Wang Xizhi**, o «sábio da caligrafia», é a grande referência da escrita regular, corrente e cursiva; as obras originais perderam-se e conhecemo-lo por cópias antigas. **Tao Yuanming** foi um funcionário que abandonou o cargo («não me curvo por cinco alqueires de arroz», diz a tradição) para viver no campo e escrever poemas sobre a vida simples, o vinho e a natureza, e que se tornou modelo dos poetas seguintes.',
  { h: 'Faxian (c. 337 – c. 422) e Kumarajiva (344 – 413)' },
  '**Faxian**, monge, viajou a pé de Chang’an até à Índia (399) e regressou por mar (412) com textos budistas; escreveu o relato dessa viagem. **Kumarajiva**, de pai indiano e mãe de Kucha, foi levado para Chang’an em 401 e dirigiu uma grande equipa de tradutores: as suas versões do *Sutra do Lótus* e do *Sutra do Diamante* tornaram-se clássicas em chinês.',
  { h: 'O imperador Xiaowen do Wei do Norte (467 – 499)' },
  'Governou, sob a regência da avó, e depois em nome próprio, a partir de 490. Transferiu a capital para Luoyang (494), mandou usar o chinês e os trajes chineses na corte, adotou o apelido **Yuan** para a família imperial e tentou aproximar os seus nobres da cultura chinesa. A sinização é um dos temas mais debatidos do período.',
  { h: 'Zu Chongzhi (429 – 500)' },
  'Matemático e astrónomo do sul. Calculou o valor de **π** com sete casas decimais exatas (entre 3,1415926 e 3,1415927) e a razão aproximada **355/113**; criou o calendário *Daming*, com uma medida do ano solar muito precisa. O seu livro perdeu-se, e conhecemos o resultado por citações. Há também referências a máquinas e a um «barco» que andava sem vela, de valor histórico incerto.',
  { h: 'Yang Jian, o imperador Wen dos Sui (541 – 604)' },
  'Sogro de um imperador do Zhou do Norte e avô do último, tomou o poder em 581 e unificou a China em 589. Reformou a administração, criou uma nova lei (o Código de Kaihuang), reduziu os impostos e deixou celeiros cheios. Era frugal e desconfiado; morreu em 604, e há quem suspeite (sem prova) que o filho o tenha assassinado. A sua mulher, a imperatriz **Dugu**, teve grande influência.',
  { h: 'O imperador Yang dos Sui (569 – 618)' },
  'Segundo filho de Wen, governou de 604 a 618. Concluiu o Grande Canal, reconstruiu Luoyang, expandiu para o oeste e fez as guerras da Coreia. Os historiadores Tang, que o precisavam de justificar como o último dos maus governantes e justificar a queda dos Sui, descrevem-no como tirano e libertino; é difícil separar o juízo político do facto. Foi estrangulado em Jiangdu em 618.',
  { h: 'Taizong, Li Shimin (598 – 649)' },
  'Segundo filho de Li Yuan e verdadeiro fundador do império Tang. Depois de eliminar os irmãos (626), governou com ministros críticos como **Wei Zheng**, cujas críticas, segundo as fontes, aceitava. Derrotou os Turcos, recebeu o título de «Grande Cã Celeste» dos povos da estepe, patrocinou o Código e os exames, e enviou tropas à Ásia Central. É o governante ideal da tradição, embora as fontes (escritas sob a sua própria vigilância) o favoreçam.',
  { img: 'cdt-taizong', leg: 'Retrato do imperador Taizong, Museu Nacional do Palácio, Taipé' },
  { h: 'Wu Zetian (624 – 705)' },
  'Entrou no palácio como concubina de Taizong, e tornou-se esposa de Gaozong (imperatriz em 655). Governou em nome dele, depois dos filhos, e em 690 fundou a dinastia **Zhou**. Promoveu os exames, patrocinou o budismo (as grutas de Longmen), construiu o Salão Luminoso (*Mingtang*) em Luoyang e serviu-se de funcionários-inquisidores implacáveis. As fontes confucianas, escritas por homens, carregam as tintas (acusam-na de infanticídio e de crimes que os historiadores modernos consideram dúbios). Foi deposta em 705.',
  { img: 'cdt-wu-zetian', leg: 'Retrato tradicional de Wu Zetian (obra posterior)' },
  { h: 'Xuanzang (602 – 664)' },
  'Monge de Luoyang, partiu em c. 629 (627 segundo algumas fontes) sem autorização do Estado, atravessou Gansu, Turfan, Samarcanda e o Afeganistão, chegou à Índia, estudou em **Nalanda** e voltou em 645, recebido com honras por Taizong. Traduziu mais de **setenta** obras (cerca de 1300 fascículos, segundo a tradição) e escreveu os *Registos Ocidentais do Grande Tang*, uma das melhores fontes sobre a Índia do século VII. A *Viagem ao Ocidente*, com o Rei Macaco e o porco Zhu Bajie, é um romance do século XVI, e **não** história.',
  { img: 'cdt-xuanzang', leg: 'Retrato de Xuanzang em rolo suspenso (versão japonesa do séc. XIV, período Kamakura), com a mochila de escrituras' },
  { img: 'cdt-ai-xuanzang-deserto', leg: 'Xuanzang a atravessar o deserto em 629; interpretação artística. Ilustração gerada por IA.' },
  { h: 'Xuanzong e Yang Guifei (685 – 762 e 719 – 756)' },
  '**Xuanzong** reinou 44 anos, desde 712. Na primeira metade, governou com bons ministros (Yao Chong, Song Jing, Zhang Jiuling) e a China viveu a sua idade de ouro; na segunda, deixou o governo a ministros como **Li Linfu** e depois **Yang Guozhong**, e apaixonou-se por **Yang Guifei**, consorte desde 745, cuja família alcançou muito poder. Em 756, em Mawei, as tropas exigiram a morte dela, e Xuanzong consentiu. Poetas como Bai Juyi contaram a história no *Canto do Pesar Eterno*.',
  { img: 'cdt-xuanzong', leg: 'Retrato tradicional do imperador Xuanzong dos Tang (obra posterior)' },
  { h: 'An Lushan (c. 703 – 757)' },
  'General de origem mista (sogdiana e turca, segundo as fontes), tornou-se favorito de Xuanzong e de Yang Guifei e acumulou o comando de três regiões do nordeste. Rebelou-se em 755 e proclamou-se imperador de uma dinastia **Yan** (756). Foi assassinado pelo seu próprio filho em 757. O motivo exato da revolta (ambição, medo dos rivais da corte, ou ambos) é discutido. O seu nome tornou-se, para os chineses, sinónimo de rebelião e do fim da idade de ouro.',
  { h: 'Li Bai (701 – 762), Du Fu (712 – 770), Wang Wei e Bai Juyi' },
  '**Li Bai**, o «imortal da poesia», viveu entre a corte de Xuanzong e as viagens pelos rios e montanhas; é famoso pelas imagens da lua e do vinho, e pela lenda de que morreu ao tentar abraçar o reflexo da lua na água (não confirmada). **Du Fu**, o «sábio da poesia», pobre e doente, viu a rebelião e a fome e escreveu versos de profunda compaixão. **Wang Wei**, pintor e poeta budista, é o mestre da paisagem silenciosa. **Bai Juyi**, funcionário, escrevia em linguagem simples, para ser entendida por toda a gente.',
  { img: 'cdt-li-bai', leg: 'Li Bai a caminhar e a recitar, atribuído a Liang Kai' },
  { img: 'cdt-du-fu', leg: 'Retrato tradicional de Du Fu (obra posterior)' },
  { h: 'Huang Chao (m. 884) e Zhu Wen (852 – 912)' },
  '**Huang Chao**, de uma família ligada ao comércio do sal, reprovou nos exames e liderou uma revolta que percorreu o país, de Shandong a Cantão e a Chang’an (880). Foi derrotado em 884 e morreu nesse ano (suicídio ou morte às mãos de um subordinado, segundo as versões). Um dos seus lugares-tenentes, **Zhu Wen**, passou-se para os Tang em 882, tornou-se o homem forte do império e, em 907, depôs o imperador e fundou o Liang Posterior. Foi assassinado pelo seu próprio filho em 912.'
];

const legado = [
  { h: 'O que nos deixaram' },
  { lista: [
    '**Um Estado:** os Sui e os Tang fixaram o modelo burocrático (ministérios, províncias, exames, lei escrita) que o império chinês usou, com variações, até ao século XX, e que a Coreia, o Japão e o Vietname copiaram.',
    '**O Grande Canal:** continua a ser, em parte, uma via de navegação; foi inscrito na lista do Património Mundial em 2014.',
    '**O budismo na Ásia Oriental:** da China passou à Coreia, ao Japão (a escola Zen vem do Chan) e ao Vietname.',
    '**A poesia:** os poemas Tang ainda são decorados pelas crianças chinesas, e inspiraram poetas ocidentais do século XX, como Ezra Pound e Rexroth.',
    '**A imprensa:** o livro impresso, nascido nos mosteiros e nas casas de adivinhos, mudou a divulgação dos textos.',
    '**O chá:** bebida nacional da China a partir dos Tang, e depois do mundo.'
  ] },
  { h: 'Arte' },
  'A **escultura budista** de Yungang, Longmen e Mogao, as pinturas murais, as figuras de cerâmica sancai e os bronzes espelhados são das maiores obras de arte da Antiguidade tardia na Ásia. A **pintura de paisagem** e a **caligrafia** consolidaram-se: os Song só lhes vão dar novo impulso.',
  { h: 'Arquitetura' },
  'A madeira dos edifícios antigos perdeu-se quase toda. O mais antigo templo de madeira conhecido na China é o **Templo de Nanchan**, no Monte Wutai (782); segue-se o **Templo de Foguang** (857). Do mundo Tang há também os **pagodes de tijolo** (Grande Pagode do Ganso Selvagem, 652; Pequeno Pagode do Ganso Selvagem, c. 707–709). Para ver a arquitetura Tang em madeira, a melhor imagem é em Nara e Quioto (Japão), onde as cópias foram mais bem conservadas, como o templo de **Tōshōdai-ji**.',
  { img: 'cdt-nanchan', leg: 'Salão principal do templo de Nanchan, Monte Wutai, 782' },
  { img: 'cdt-sutra-diamante', leg: 'Sutra do Diamante, 868, Biblioteca Britânica' },
  { h: 'A redescoberta' },
  'Os Tang foram esquecidos e lembrados de maneira diferente: os imperadores seguintes copiaram o seu modelo, e os poetas Tang nunca deixaram de ser lidos. A arqueologia moderna trouxe novos achados: os **manuscritos de Dunhuang** (1900), os túmulos com murais de **Qianling** (Gaozong e Wu Zetian) e de Zhaoling (Taizong), nos arredores de Xi’an, o **tesouro de Hejiacun** em Xi’an (1970, com prata e ouro Tang) e o **cofre de Famen** (1987), que guarda uma relíquia budista e um tesouro de prata e vidro, enterrado em 874.',
  { h: 'O que a Europa e Portugal sabem destes tempos' },
  'A Europa só tomou contacto direto com a China Tang pelos relatos de viajantes árabes (*Akhbar al-Sin wa l-Hind*, 851, com acrescentos de c. 916), que descrevem o porto de Guangzhou e a revolta de Huang Chao. A palavra **«Cathay»** vem dos Khitan (Liao), e não dos Tang. Os Portugueses foram, em 1513, os primeiros europeus a chegar à China por mar, mais de seiscentos anos depois do fim dos Tang; a coleção do **Museu do Oriente** (Lisboa) e do **Museu de Macau** guarda peças deste legado.',
  { h: 'Onde visitar' },
  { lista: [
    '**Xi’an:** Grande Pagode do Ganso Selvagem, Museu de História de Shaanxi, Floresta de Estelas (estela nestoriana), muralhas.',
    '**Luoyang:** grutas de Longmen, Museu de Luoyang.',
    '**Datong:** grutas de Yungang.',
    '**Dunhuang:** grutas de Mogao e Museu de Dunhuang.',
    '**Monte Wutai:** templos de Nanchan e de Foguang.',
    '**Hangzhou e Yangzhou:** troços do Grande Canal.',
    '**Fora da China:** Biblioteca Britânica (Sutra do Diamante), Museu Britânico, Museu Guimet (Paris), Museu Nacional de Tóquio, Shōsōin (Nara, tesouros do século VIII), Museu do Oriente (Lisboa).'
  ] },
  { cit: 'Usando o bronze como espelho, podemos ajustar a roupa; usando a história como espelho, podemos compreender a ascensão e a queda; usando um homem como espelho, podemos ver os nossos ganhos e perdas.', fonte: 'Atribuído a Taizong, ao saber da morte de Wei Zheng (643), segundo o *Jiu Tangshu*; a formulação varia (paráfrase)' }
];

const quiz = [
  { p: 'Quais eram os Três Reinos que dividiram a China depois dos Han?', op: ['Qin, Han e Chu', 'Wei, Shu e Wu', 'Sui, Tang e Song', 'Jin, Liao e Xia'], certa: 1, exp: 'Wei (norte), Shu (sudoeste) e Wu (sul), entre 220 e 280.' },
  { p: 'Que obra é a fonte histórica principal sobre os Três Reinos, por oposição ao romance?', op: ['O Sanguozhi, de Chen Shou', 'O Shiji, de Sima Qian', 'A Viagem ao Ocidente', 'Os Analectos'], certa: 0, exp: 'O romance de Luo Guanzhong (século XIV) mistura factos e ficção.' },
  { p: 'Que cidade foi capital do sul durante a divisão, sob seis dinastias?', op: ['Chang’an', 'Jiankang (Nanjing)', 'Kaifeng', 'Dunhuang'], certa: 1, exp: 'Jiankang foi capital de Wu, Jin Oriental, Song, Qi, Liang e Chen.' },
  { p: 'Que imperador do Wei do Norte mudou a capital para Luoyang em 494 e promoveu a sinização?', op: ['Taizong', 'Xiaowen', 'Wen de Sui', 'Wudi'], certa: 1, exp: 'Xiaowen mandou usar o chinês e os trajes chineses na corte.' },
  { p: 'Em que ano os Sui reunificaram a China?', op: ['220', '317', '589', '907'], certa: 2, exp: 'Em 589 conquistaram o reino de Chen, no sul.' },
  { p: 'Que grande obra pública mandou fazer o imperador Yang dos Sui?', op: ['A Grande Muralha completa', 'O Grande Canal', 'O Exército de Terracota', 'A Cidade Proibida'], certa: 1, exp: 'Entre 605 e 610 foram unidos canais entre Luoyang, o Yangtzé e Hangzhou.' },
  { p: 'Quem fundou a dinastia Tang em 618?', op: ['Li Yuan', 'Li Bai', 'Yang Jian', 'Zhu Wen'], certa: 0, exp: 'Li Yuan, com o filho Li Shimin (Taizong), tomou Chang’an e proclamou os Tang.' },
  { p: 'Qual foi a única mulher a governar em nome próprio como imperatriz?', op: ['Yang Guifei', 'Wu Zetian', 'Lü Zhi', 'Dugu'], certa: 1, exp: 'Wu Zetian fundou a dinastia Zhou em 690 e governou até 705.' },
  { p: 'Para onde partiu o monge Xuanzang em 629?', op: ['Para a Coreia', 'Para a Índia', 'Para o Japão', 'Para Roma'], certa: 1, exp: 'Voltou em 645 com 657 textos budistas. A «Viagem ao Ocidente» é um romance posterior.' },
  { p: 'O que eram os bairros (fang) de Chang’an?', op: ['Mercados', 'Quarteirões murados com portas que fechavam à noite', 'Mosteiros', 'Quartéis'], certa: 1, exp: 'Havia 110 bairros e dois mercados oficiais, o Leste e o Oeste.' },
  { p: 'Quem eram os Sogdianos?', op: ['Soldados Tang', 'Mercadores da Ásia Central, intermediários da Rota da Seda', 'Poetas', 'Monges coreanos'], certa: 1, exp: 'Vinham da região de Samarcanda e viviam em comunidades em Chang’an e Dunhuang.' },
  { p: 'Quais são os dois grandes poetas Tang mais citados?', op: ['Li Bai e Du Fu', 'Confúcio e Mêncio', 'Sima Qian e Ban Gu', 'Zhuangzi e Laozi'], certa: 0, exp: 'Li Bai (701–762) e Du Fu (712–770).' },
  { p: 'Que acontecimento começou em 755 e abalou os Tang?', op: ['A rebelião de An Lushan', 'A batalha de Chibi', 'A queda de Luoyang aos Xiongnu', 'A viagem de Xuanzang'], certa: 0, exp: 'A rebelião durou até 763 e deu poder aos governadores militares.' },
  { p: 'Qual é o livro impresso com data mais antigo conhecido?', op: ['A Bíblia de Gutenberg', 'O Sutra do Diamante de 868', 'O Shiji', 'O Código Tang'], certa: 1, exp: 'Foi encontrado em Dunhuang em 1900 e está na Biblioteca Britânica.' },
  { p: 'Quem depôs o último imperador Tang em 907?', op: ['Huang Chao', 'Zhu Wen', 'Zhao Kuangyin', 'An Lushan'], certa: 1, exp: 'Zhu Wen fundou o Liang Posterior, a primeira das Cinco Dinastias.' }
];

export default { id: 'china', cor: '#b83a3a', emblema: '../../assets/img/china.png', grupo: { ...GRUPO, aqui: 'divisao-tang' },
  nome: { pt: 'Divisão, Sui e Tang', en: 'Division, Sui and Tang' },
  periodo: { pt: '220 – 907', en: 'AD 220 – 907' },
  visao: { pt: visao, en: EN.visao }, linha: { pt: linha, en: EN.linha }, mapa: { pt: mapa, en: EN.mapa }, sociedade: { pt: sociedade, en: EN.sociedade },
  personalidades: { pt: personalidades, en: EN.personalidades }, legado: { pt: [...legado, ...CRED.pt], en: [...EN.legado, ...CRED.en] }, quiz: { pt: quiz, en: EN.quiz } };
