// EMPERORS AND GREAT FIGURES — full English content. Same structure and same image slots as the Portuguese version (dados.js).
// Conventional dates (Principate from 27 BC; end of the Western Empire in AD 476). Reigns follow the usual lists; where scholars disagree, the text says so.

const visao = [
  { caixa: 'In brief', texto: [
    'Between **27 BC** and **AD 476** (conventional dates), Rome had **more than seventy** men recognised as emperors, counting those who shared power and those who held it for only months. Some ruled for nearly half a century, like Augustus; others lasted weeks and were murdered. They were generals, bureaucrats, intellectuals, soldiers of humble birth and children. This page brings together the **table of all the emperors**, with dates and dynasties, and **30 biographies** of emperors and other figures who shaped their time: generals and politicians of the Republic (Scipio, Cato, Cicero, Pompey, Caesar), women of the imperial household (Livia, Agrippina), writers and thinkers (Virgil, Seneca, the two Plinys, Tacitus).',
    'It does not tell the story of each era in detail (for that, see the pages on the Late Republic, the High Empire and Crisis and Dominate), but answers a simpler question: **who were the men and women who made Rome**, what we know about them, from what sources, and with how much caution.'
  ] },
  { img: 'rim-augusto-prima-porta', leg: 'Augustus of Prima Porta, Vatican Museums.' },
  { h: 'The word “emperor”' },
  'The word comes from the Latin **imperator**, which in the Republic was only the honorific title given by soldiers to a general victorious on the battlefield. It was **Augustus** who created, after 27 BC, a new regime, the **Principate**, without ever using the word “king”, which the Romans had hated since the expulsion of Tarquin the Proud (509 BC, according to tradition). Augustus said he was merely the **princeps**, the “first citizen”, and kept the Senate, the consuls and the magistracies. In practice he held the command of the armies, the money and the last word.',
  { h: 'From princeps to dominus' },
  'The regime changed slowly. In the first two centuries the emperor presented himself as the first among senators. From the Crisis of the 3rd century, and above all under **Diocletian** (284–305), he lived apart, surrounded by ceremony, and was addressed as **dominus**, “lord”. Historians therefore call the first period (27 BC – c. AD 284) the **Principate** and the second (c. 284 – 476) the **Dominate**. The distinction is a modern convention: the Romans went on calling their state “the republic” (res publica) to the end.',
  { h: 'How one became emperor' },
  'There was no law of succession. Rome never wrote down a rule, and that explains much of the violence of its history. Power passed in four ways:',
  { lista: [
    '**Inheritance or adoption:** Augustus adopted Tiberius; Claudius adopted Nero; in the 2nd century, Nerva, Trajan, Hadrian and Antoninus Pius each chose a successor by adoption. It was the only period in which the system worked for generations.',
    '**Acclamation by the army or the Praetorian Guard:** this was how Claudius came to power in 41, and most emperors of the 3rd century.',
    '**Civil war:** Vespasian (69), Septimius Severus (193), Constantine (306–324) and others beat rivals by force.',
    '**Conspiracy and murder:** Caligula, Domitian, Commodus and dozens of others were killed by their own guards, officers or relatives.'
  ] },
  { img: 'rim-arvore-dinastias', leg: 'Drawn diagram of the Julio-Claudian (left) and Flavian (right) houses. Solid lines: biological parentage; red dashed lines: adoption. Four small circles represent intervening generations; identification in arvore-posicoes.json and LEIA-ME.md.' },
  { h: 'Dynasties: a modern arrangement' },
  'The Romans did not speak of “dynasties”; they spoke of families (the Julii and Claudii, the Flavii, the Antonines). Historians use the term to organise a long list: **Julio-Claudians** (27 BC – AD 68), **Flavians** (69–96), **Nerva-Antonines** (96–192), **Severans** (193–235), **Military Anarchy** or Crisis of the 3rd century (235–284), **Tetrarchy** and **Constantinians** (284–363), **Valentinians** and **Theodosians** (364–455), and the last emperors of the West (455–476). In reality many of these “dynasties” were linked by adoption or marriage rather than by blood.',
  { caixa: 'Chronology: a note of caution', texto: 'Reigns are given in Roman calendar years converted to AD, and many are **approximate**: an emperor was proclaimed in a province, recognised in Rome months later, and sometimes had rivals whom the Senate also recognised. In 476 Romulus Augustulus was deposed, but **Julius Nepos**, the legitimate emperor in the eyes of Constantinople, did not die until 480: the date 476 is a convention. The numbers of dead, soldiers and inhabitants quoted by ancient sources are estimates, and this page gives them only with caution.' },
  { h: 'What sources do we have' },
  'Almost everything we know about the emperors comes from a handful of authors, nearly all senators or close to them, and that shapes the image that has come down to us:',
  { lista: [
    '**Tacitus** (c. 56 – c. 120): Annals and Histories, on the Julio-Claudians and the year 69. Rigorous and sombre, he writes with the mistrust of someone who has seen rulers at close quarters.',
    '**Suetonius** (c. 70 – after 122): Lives of the Twelve Caesars, from Caesar to Domitian. He likes anecdotes and scandals, and does not always distinguish them from facts.',
    '**Cassius Dio** (c. 155 – after 229): Roman History in Greek, 80 books, of which only part survives intact; he lived under Commodus and the Severans.',
    '**Herodian** (3rd century): Greek historian, from Marcus Aurelius to 238.',
    '**Historia Augusta:** a collection of biographies of emperors from Hadrian to Numerian, presented as the work of six authors but now attributed to a single anonymous author of the late 4th century; it mixes fact with invention and must be used with great caution.',
    '**Coins, inscriptions, portraits and monuments:** they lie no less, but in another way, because they were official propaganda.'
  ] },
  { img: 'rim-mapa-imperio-117', leg: 'Roman Empire at its greatest extent, AD 117.' },
  { h: 'Why they matter' },
  { lista: [
    '**An institution of five hundred years:** the office of emperor, created by Augustus, lasted in the West until 476 and, in the East, continued in Constantinople until 1453.',
    '**A political model:** the title “Caesar” gave the German Kaiser and the Russian tsar; “emperor” is still the name of the head of any empire.',
    '**A unified Mediterranean:** common coinage, roads, language and law under a central power, which influenced the whole of Europe.',
    '**Good literature:** Virgil, Tacitus, Seneca and Marcus Aurelius are still read as living works, and not merely out of historical curiosity.'
  ] },
  { caixa: 'The emperors today', texto: 'Thousands of imperial portraits survive, in marble and bronze, in the **Capitoline Museums** in Rome, the **Vatican Museums**, the **National Archaeological Museum of Naples**, the **Munich Glyptothek** and the **Louvre**. Their monuments can still be visited: the Colosseum, the Pantheon, the Arch of Constantine, Trajan’s Column, Hadrian’s Wall, Diocletian’s Palace in Split.' },
  { h: 'Beware of myths' },
  'Some very popular images of emperors have **little or no solid basis in the sources**: Nero playing the lyre while Rome burned (Tacitus says the rumour circulated, but that he was at Antium and returned to Rome to organise relief; Suetonius and Cassius Dio say he sang the “Sack of Ilium” during the fire, but the classic scene of the lyre is a later elaboration); the horse Incitatus made consul by Caligula (Suetonius says he planned it, not that he did it); the “thumbs down” as a death sentence at the games; “Hail, Caesar, those who are about to die salute you” as the usual greeting of gladiators (attested only once, in 52, at a naval show given by Claudius). Each biography below notes what is fact, what is tradition and what is probably propaganda.'
];

const linha = [
  'This timeline follows the emperors and the events that defined them most. Dates are conventional; the details of each figure’s life are in the biographies, in the “Personalities” section.',
  { linha: [
    { d: '31 BC', t: 'Actium: Octavian defeats Antony and Cleopatra', x: 'In the naval battle of Actium, in the Ionian Sea, Octavian’s forces, commanded at sea by Agrippa, defeated those of Mark Antony and Cleopatra VII. A year later Egypt was annexed. Octavian had no rivals left and was master of the Mediterranean.' },
    { d: '27 BC', t: 'The Principate is born', x: 'In January, in the Senate, Octavian symbolically handed back his extraordinary powers and received in return the name **Augustus** and command of the provinces where the legions were stationed. The date is the convention for the beginning of the Empire.' },
    { d: 'AD 14', t: 'Death of Augustus; Tiberius', x: 'Augustus died at Nola, aged 75. Tiberius, his adopted son and an experienced general, succeeded him without civil war: the regime had proved it could outlive its founder.' },
    { d: '31', t: 'Fall of Sejanus', x: 'Aelius Sejanus, prefect of the Praetorian Guard and Tiberius’ right-hand man during the years when the emperor withdrew from Rome, was arrested and executed after a letter from Tiberius was read to the Senate. Years of treason trials followed.' },
    { d: '41', t: 'Caligula murdered; Claudius acclaimed', x: 'Caligula was killed by officers of the Praetorian Guard. According to tradition, the praetorians found his uncle Claudius hiding in the palace and proclaimed him emperor before the Senate could debate restoring the Republic.' },
    { d: '43', t: 'Conquest of Britain', x: 'Claudius sent four legions to Britain under Aulus Plautius and went there in person for a few days. Camulodunum (Colchester) became the first capital of the new province.' },
    { d: '54', t: 'Death of Claudius; Nero, aged 16', x: 'Claudius died in October. Ancient sources say he was poisoned by Agrippina, his wife, to give the throne to her son Nero; it is possible, but **not proven**.' },
    { d: '64', t: 'Great Fire of Rome', x: 'In July the fire destroyed or damaged ten of the city’s fourteen regions. Nero directed the relief and then rebuilt with new fire regulations. He blamed the Christians, who were persecuted in Rome. The idea that he ordered the fire has no proof.' },
    { d: '68 – 69', t: 'The Year of the Four Emperors', x: 'Nero committed suicide in June 68. In eighteen months there were four emperors (Galba, Otho, Vitellius, Vespasian), three of them killed. The “secret of empire” was revealed: an emperor could be made outside Rome, by the legions.' },
    { d: '70 – 80', t: 'The Flavians: Jerusalem and the Colosseum', x: 'Titus took and destroyed Jerusalem in 70, and the Arch of Titus in Rome celebrates it. Vespasian began the Flavian Amphitheatre (the Colosseum) c. 70–72; Titus inaugurated it in 80 with a hundred days of games.' },
    { d: '79', t: 'Eruption of Vesuvius', x: 'Pompeii, Herculaneum and Stabiae were buried. Pliny the Elder, commander of the fleet at Misenum, died at Stabiae while trying to rescue people. The traditional date, 24 August, comes from Pliny the Younger’s letters; a charcoal inscription found at Pompeii in 2018 led some to propose October, but the question is still debated.' },
    { d: '96', t: 'End of the Flavians; Nerva', x: 'Domitian was assassinated in a palace conspiracy. The Senate chose Nerva, old and childless, who adopted Trajan, a general, to secure the army’s support.' },
    { d: '101 – 106', t: 'The Dacian Wars', x: 'Trajan defeated King Decebalus and made Dacia (today Romania) a province, with the gold of its mines. Trajan’s Column, inaugurated in 113, tells the campaign in spiral reliefs.' },
    { d: '117', t: 'The Empire at its greatest extent', x: 'At the end of the campaign against the Parthians, Trajan created provinces in Armenia and Mesopotamia, which his successor Hadrian abandoned soon afterwards. It was the moment of greatest extent, though short-lived.' },
    { d: '122', t: 'Hadrian and the Wall', x: 'Hadrian visited nearly every province. In Britain he ordered a stone wall of about 118 km, which marked the frontier for centuries. Around 126–128 the rebuilt Pantheon was dedicated.' },
    { d: '161 – 180', t: 'Marcus Aurelius, Lucius Verus and the Danube wars', x: 'For the first time there were two emperors of equal title. The war against the Parthians brought an epidemic to Rome (the Antonine Plague), and Marcus Aurelius spent much of his reign fighting Danubian tribes, where he wrote the Meditations.' },
    { d: '180 – 192', t: 'Commodus', x: 'Marcus Aurelius’ son was the first emperor since Titus to succeed his natural father; his five predecessors had all been chosen by adoption. His reign ended with his murder on 31 December 192.' },
    { d: '193', t: 'Year of the Five Emperors; Septimius Severus', x: 'Pertinax was killed after three months; Didius Julianus, according to the sources, bought the throne at auction from the praetorians; Septimius Severus, from Leptis Magna, was acclaimed by the Danube legions and defeated his rivals by 197.' },
    { d: '212', t: 'Constitutio Antoniniana', x: 'Caracalla granted Roman citizenship to nearly all free inhabitants of the Empire. The motives are debated: equality, taxation or propaganda.' },
    { d: '235 – 284', t: 'Crisis of the 3rd century', x: 'Half a century of civil wars, invasions and inflation. More than twenty emperors were recognised, almost all with violent ends. Valerian was captured by the Persians in 260; the Empire split in three for some years (Gallic, Roman, Palmyrene).' },
    { d: '270 – 275', t: 'Aurelian reunifies the Empire', x: 'He defeated invaders in northern Italy, Queen Zenobia of Palmyra (272) and the Gallic Empire (274). He had Rome surrounded by a new wall (the Aurelian Walls).' },
    { d: '284 – 305', t: 'Diocletian and the Tetrarchy', x: 'He divided government among four (two augusti and two caesars) and reformed taxes, coinage and provinces. He abdicated in 305, a very rare event, and retired to his palace at Split.' },
    { d: '312', t: 'Milvian Bridge; Constantine', x: 'Constantine defeated Maxentius at the gates of Rome on 28 October and became master of the West. In 313, with Licinius, he adopted a policy of toleration for Christians; in 324 he reunified the Empire.' },
    { d: '330', t: 'Constantinople', x: 'Constantine inaugurated the city, on the site of ancient Byzantium, on 11 May. It became the capital of the East and, after 476, the only imperial capital.' },
    { d: '361 – 363', t: 'Julian', x: 'Constantine’s nephew tried to restore the cult of the traditional gods and to reduce the privileges of the Church. He died on campaign against the Persians, aged 31, and his project died with him.' },
    { d: '378 – 395', t: 'Adrianople and Theodosius', x: 'In 378 the Goths destroyed the eastern army and killed Emperor Valens at Adrianople. Theodosius I made a settlement with the Goths, proclaimed Nicene Christianity the state religion (380) and was the last to rule the whole Empire; at his death in 395 he divided it between his sons.' },
    { d: '476', t: 'Romulus Augustulus is deposed', x: 'Odoacer, a Germanic commander, deposed the young emperor of the West and sent the insignia to Constantinople. It remains the conventional date for the end of the Western Roman Empire. The Eastern Empire continued until 1453.' }
  ] }
];

const mapa = [
  'The emperors and great figures did not live only in Rome: they were born, ruled and died all over the Mediterranean. This section walks through the places where their history was decided.',
  { tabela: { cab: ['Place', 'Today', 'What happened there'], linhas: [
    ['Rome (Palatine)', 'Italy', 'Residence of the emperors from Augustus; the word “palace” comes from Palatine'],
    ['Nola', 'Italy', 'Where Augustus died, in AD 14'],
    ['Capri', 'Italy', 'Tiberius’ retreat, from 26/27 to 37'],
    ['Misenum and Baiae', 'Italy', 'Fleet base; deaths of Tiberius and Hadrian; scene of the attempt on Agrippina'],
    ['Lugdunum', 'Lyon, France', 'Birthplace of Claudius and Caracalla; battle of 197 between Severus and Albinus'],
    ['Córdoba (Corduba)', 'Spain', 'City of Seneca'],
    ['Italica', 'Santiponce, Spain', 'Origin of Trajan and Hadrian'],
    ['Tivoli', 'Italy', 'Hadrian’s villa'],
    ['Leptis Magna', 'Libya', 'Home city of Septimius Severus'],
    ['Eboracum', 'York, England', 'Death of Severus (211); acclamation of Constantine (306)'],
    ['Carnuntum and Vindobona', 'Austria', 'Campaigns of Marcus Aurelius; acclamation of Severus'],
    ['Nicomedia', 'İzmit, Turkey', 'Diocletian’s capital'],
    ['Split (Spalatum)', 'Croatia', 'Diocletian’s retirement palace'],
    ['Milan and Ravenna', 'Italy', 'Capitals of the Western Empire'],
    ['Trier (Augusta Treverorum)', 'Germany', 'Imperial capital in the 4th century'],
    ['Constantinople', 'Istanbul, Turkey', 'Capital founded by Constantine in 330'],
    ['Palmyra', 'Syria', 'City of Zenobia, defeated by Aurelian'],
    ['Adrianople', 'Edirne, Turkey', 'Defeat of Valens, in 378']
  ] } },
  { h: 'Rome and the Palatine' },
  'The Palatine hill, where tradition placed Romulus’ hut, was chosen by Augustus as his residence. His successors added palaces, until Domitian built the enormous complex (the Domus Flavia and the Domus Augustana) that served as the imperial residence for centuries.',
  { img: 'rim-palatino-reconstrucao', leg: 'AI-generated illustration. Palatine Hill, c. AD 100.' },
  { h: 'Domus Aurea (Rome)' },
  'After the fire of 64, Nero built the **Golden House**, a pleasure villa with an artificial lake, pavilions and decorated rooms in the centre of Rome. His successors dismantled it: the Colosseum was raised over the lake, and the Baths of Trajan over part of the building. Rediscovered in the Renaissance (c. 1480), its frescoes inspired painters, who called them “grotesques” because they were found in grotte (buried rooms).',
  { img: 'rim-domus-aurea-sala', leg: 'AI-generated illustration. Octagonal hall of Nero’s Domus Aurea, c. AD 65.' },
  { h: 'Nola and Capri' },
  'At **Nola**, in Campania, Augustus died on 19 August AD 14, in the house where his father had died. On **Capri**, Tiberius had twelve villas built; the largest, the Villa Jovis, can still be visited. From there he governed by letter from 26/27 to 37, and his orgies (reported by Suetonius and Tacitus) are almost certainly exaggeration by enemies.',
  { h: 'Misenum and Baiae' },
  'At **Misenum** lay the largest war fleet of Rome. Tiberius died there (37), and so did the fleet’s commander Pliny the Elder (79, at Stabiae, across the bay). At **Baiae**, the aristocracy’s holiday resort, Hadrian died (138), and Nero tried to kill his mother Agrippina in a boat designed to fall apart at sea (59).',
  { h: 'Lugdunum (Lyon)' },
  'Capital of the Gauls, founded in 43 BC. Claudius (10 BC) and Caracalla (188) were born there. A bronze tablet with Claudius’ speech to the Senate in 48, on admitting Gauls to the assembly, survives in Lyon. In February 197 the battle between Septimius Severus and Clodius Albinus was fought there, one of the largest Roman civil wars.',
  { h: 'Córdoba (Corduba)' },
  'Capital of Baetica, it had a Romanised elite: **Seneca** the Elder (the rhetorician) and his son **Seneca** the philosopher were born there. From the same milieu came the poet Lucan, Seneca’s nephew, and Quintilian, from Calagurris (Calahorra), teacher of rhetoric under Domitian.',
  { h: 'Italica' },
  'Founded in 206 BC by Scipio Africanus for his veterans, near Seville, it was the city of **Trajan** (AD 53) and, through family, of **Hadrian**. Hadrian enlarged it with a new quarter; its amphitheatre was among the largest in Hispania. The two emperors show that in the 2nd century the elites of the western provinces governed Rome.',
  { h: 'Tivoli: Hadrian’s Villa' },
  'From 118, Hadrian built at Tivoli, about 30 km from Rome, an enormous villa with more than 30 buildings, baths, theatres, a canal called the Canopus, named after the Egyptian city, and replicas of places he had visited in Greece and Egypt. It is a UNESCO World Heritage Site.',
  { h: 'Leptis Magna' },
  'A Punic and Roman city on the coast of Libya, home of **Septimius Severus**. When he became emperor he filled it with monuments: a four-way arch, a new forum, a basilica and a reworked harbour. It is well preserved because it was abandoned and covered by sand.',
  { h: 'Eboracum (York)' },
  'Seat of a legion and capital of northern Britain. Septimius Severus died there (4 February 211), during the campaign in Scotland, and there the troops proclaimed Constantine, on 25 July 306, when his father Constantius Chlorus died. Two decisive moments of imperial history, a century apart, happened in the same city.',
  { h: 'Carnuntum, Vindobona and the Danube' },
  'Carnuntum, in Pannonia (near Vienna), was a legionary base and, in 193, the place where Septimius Severus was acclaimed. Marcus Aurelius spent part of his adult life there and around it, in the wars against the Marcomanni and Quadi; the notes at the end of books 1 and 2 of the Meditations, transmitted by the manuscripts, read “among the Quadi, by the Granua” and “at Carnuntum”. He died at Vindobona (Vienna) or at Sirmium: the sources differ.',
  { h: 'Nicomedia, Split and Dalmatia' },
  'Diocletian, born in Dalmatia, made **Nicomedia**, in Asia Minor, his eastern capital, and built at **Split**, near his homeland, the enormous palace-fortress where he spent his last years. The palace survives as the centre of today’s Split, and is a World Heritage Site.',
  { img: 'rim-tetrarcas', leg: 'The Tetrarchs, porphyry, St Mark’s Basilica, Venice.' },
  { h: 'Milan, Ravenna and Trier' },
  'With the Tetrarchy, Rome ceased to be the seat of daily government. **Milan** was the imperial capital in the West in the 4th century (where Constantine and Licinius agreed, in 313, on a policy of religious toleration); **Ravenna**, better protected by marshes, became capital from 402, under Honorius; and **Trier**, on the Rhine, was an important imperial residence, with its Porta Nigra and an enormous audience hall, still standing.',
  { h: 'Constantinople' },
  'Constantine founded it in 324–330 on Byzantium. It had a strategic position (between Europe and Asia, on the Bosphorus), a harbour and, later, walls that protected it for almost a thousand years. When the West fell the city remained the imperial capital, which is why 476 marks only the end of the empire in the West.',
  { h: 'Palmyra and the East' },
  'An oasis in Syria, rich from the caravan trade, Palmyra was governed by Odaenathus, an ally of Rome against the Persians, and then by his widow **Zenobia**, who in 270–272 rebelled and controlled Egypt and part of Asia Minor. **Aurelian** defeated her in 272, near Antioch and Emesa, and led her in his triumph in Rome.',
  { img: 'rim-aureliano-zenobia', leg: 'AI-generated illustration. Aurelian’s triumph and Zenobia in captivity, AD 274; interpretation of the literary tradition.' },
  { h: 'Adrianople and the Frigidus' },
  'At **Adrianople** (today Edirne, Turkey), on 9 August 378, the eastern army was destroyed by rebel Goths, and Emperor Valens died on the field. In 394, on the river **Frigidus** (today the Vipava, in Slovenia), Theodosius defeated the usurper Eugenius, the last great civil battle of the united Empire.',
  { h: 'Arpinum, Tusculum and republican Campania' },
  'Cicero was born at **Arpinum**, and had villas at Tusculum, Formiae and Puteoli, where he wrote many works. **Cato** the Elder came from Tusculum; **Scipio** spent his last years at Liternum (Campania). This rural aristocracy, Italian rather than Roman in origin, was the one that made the Republic.',
  { h: 'Mantua, Como and Stabiae' },
  'Virgil was born near **Mantua** (c. 70 BC). **Como**, on the lake of the same name, was the city of the two Plinys. **Stabiae** (near Castellammare di Stabia) is where Pliny the Elder died in 79; his nephew, at Misenum, told of the day in two letters to Tacitus.',
  { h: 'Cologne (Agrippina)' },
  'On the left bank of the Rhine **Agrippina** the Younger was born, and it was at her request, as Claudius’ wife, that the emperor founded in 50 the **Colonia Claudia Ara Agrippinensium**, the future Cologne. The city still bears her name.',
  { h: 'Pelusium and Pharsalus' },
  'At **Pharsalus**, in Thessaly (48 BC), Caesar defeated Pompey, who fled to Egypt. He was killed on landing at **Pelusium**, in the delta, on the orders of the young Ptolemy XIII, who hoped to please the victor. Caesar arrived a few days later.',
  { h: 'Hispania and Portugal' },
  'The territory of Portugal, Lusitania, was linked to several of these men. **Scipio** drove the Carthaginians out of Hispania (206 BC); **Caesar** was governor of Hispania Ulterior in 61–60 BC and fought the Lusitanians, and it was in his honour that Lisbon was called **Felicitas Iulia Olisipo** and Beja **Pax Iulia**; **Augustus** founded **Augusta Emerita** (Mérida) in 25 BC for his veterans and created the province of Lusitania (c. 27–13 BC), with its capital at Mérida. **Trajan**, **Hadrian** and **Theodosius** came from families of Hispania.'
];

const sociedade = [
  'This section explains how the emperor’s power worked, what he was called, how he was succeeded and how he was celebrated, and gives the **complete table of the emperors**, arranged by dynasty.',
  { h: 'The emperor’s titles' },
  'The emperor accumulated titles and powers that in the Republic had been separate and temporary. The main ones:',
  { lista: [
    '**Imperator:** supreme commander of the army; in its modern use, the emperor himself.',
    '**Caesar:** the family name of Julius Caesar, which Augustus inherited by adoption and which his successors used, first as a name, then as a title for the heir (the “Caesar”, as opposed to the “Augustus”).',
    '**Augustus:** “the revered one”, a title voted to Octavian in 27 BC, with no earlier equivalent; afterwards given to all emperors.',
    '**Princeps:** “first citizen”, the term preferred in the 1st and 2nd centuries.',
    '**Pontifex Maximus:** head of the state religion, from Augustus (12 BC).',
    '**Tribunician power** (tribunicia potestas): gave the emperor inviolability and the veto, and was counted by years; inscriptions are dated by it.',
    '**Greater proconsular imperium:** command over all provinces with legions.',
    '**Pater patriae:** “father of the fatherland”, an honour granted to Cicero and Augustus, and afterwards to many emperors.'
  ] },
  { tabela: { cab: ['Element', 'Example (Augustus)', 'Meaning'], linhas: [
    ['Imperator', 'IMP', 'victorious commander; later, an acclaimed salutation'],
    ['Caesar', 'CAESAR', 'name adopted from Caesar'],
    ['Divi filius', 'DIVI F', 'son of the deified (Caesar)'],
    ['Augustus', 'AUGUSTUS', 'title of 27 BC'],
    ['Pontifex Maximus', 'PONT MAX', 'chief priest'],
    ['Tribunician power', 'TR POT', 'followed by the year number']
  ] } },
  { h: 'The court, the guard and the army' },
  'The emperor ruled with three supports. The **court** (trusted freedmen, secretaries, equestrians and senators of his household), the **Praetorian Guard** (between about 4,500 and 10,000 men depending on the period, concentrated in Rome from Tiberius) and the **legions** (between 25 and 33 over the centuries, which with the auxiliary troops made up some hundreds of thousands of men; very approximate figures). Whoever lost one of these supports lost the throne. The Praetorian Guard killed or made emperors from Caligula to Maxentius, and was disbanded by Constantine in 312.',
  { h: 'The Senate and the magistracies' },
  'The **Senate** continued throughout the Empire, with 600 members, but its role diminished: it was now a body of prestige, which confirmed the emperor and supplied commanders and governors. The **equestrians** (the class of wealthy men who were not senators) gradually took the posts of trust: prefects of the praetorians, of Egypt, of the fleet. In the 3rd century senators lost, according to tradition by decision of Gallienus, their military commands, and power passed to professional officers.',
  { h: 'Succession: adoption, acclamation, war' },
  'There was no rule, and each solution had advantages and risks. **Heredity** produced dreadful rulers (Caligula, Nero, Commodus); **adopting the best man** produced Trajan, Hadrian and Marcus Aurelius, but depended on the emperor having the courage to choose outside his family and living long enough; **military acclamation** gave the throne to the man most popular with the troops; **civil war** decided the rest. Diocletian tried to create a regular system, the Tetrarchy, in which the caesars would succeed the augusti. It failed within a few years.',
  { h: 'Damnatio memoriae and consecration' },
  'The Senate could vote against a dead emperor the **damnatio memoriae**: his name was erased from inscriptions, his statues pulled down, his coins withdrawn. This happened to Domitian, Commodus (briefly) and Geta. The opposite was **consecration** (consecratio): the Senate voted the deification of the dead emperor, who became divus, with a temple and priests. Caesar, Augustus, Claudius, Vespasian, Titus, Trajan, Hadrian, Marcus Aurelius and many others received it, and also **Livia**, by decision of Claudius.',
  { h: 'Ceremonies and spectacles' },
  { lista: [
    '**The triumph:** parade of the victorious general along the Via Sacra, with soldiers, captives and spoils. In the early Empire only the emperor and his family had the right to a triumph.',
    '**The adventus:** the emperor’s solemn entry into a city, with procession, hymns and speeches.',
    '**The congiarium and distributions:** from time to time the emperor distributed money or grain to the people of Rome. The poet Juvenal summed up imperial policy as “bread and circuses” (panem et circenses).',
    '**The games:** chariot races in the Circus Maximus, gladiator fights, hunts in the amphitheatre; the emperor presided, and his presence could earn popularity.',
    '**The adlocutio:** the address to the troops, a theme of coins and reliefs.'
  ] },
  { h: 'Propaganda: coins, portraits and arches' },
  'There was no printing, so power spoke through objects. **Coins** circulated throughout the Empire, with the emperor’s portrait on one side and messages on the other (Pax, Victoria, Concordia). **Statues and busts** repeated the official model: Augustus young and serene for ever; Trajan with his fringe hairstyle; Hadrian bearded, in the Greek manner; Constantine with his gaze turned upward. **Triumphal arches** and **columns** (Trajan, Marcus Aurelius) told victories in stone.',
  { img: 'rim-cesar-denario', leg: 'Denarius of Caesar, February–March 44 BC, P. Sepullius Macer: laureate portrait and Venus Victrix reverse (Crawford 480/10).' },
  { h: 'Emperors from afar: the provincials' },
  'In the early years the emperors were Italians. Then power passed to the provinces: **Trajan** and **Hadrian** came from Hispania, **Septimius Severus** from Africa, **Philip the Arab** from Syria, **Maximinus** from Thrace, **Diocletian** from Dalmatia, **Constantine** from Moesia, **Theodosius** again from Hispania. From the 3rd century the most powerful came from the Danube area (Illyricum), where the best soldiers were recruited.',
  { h: 'The women of the imperial household' },
  'The emperor’s women held no official posts, but had great influence: **Livia** (wife of Augustus), **Agrippina** the Younger, **Julia Domna** (wife of Septimius Severus and mother of Caracalla, whose court attracted philosophers), **Julia Maesa** and her daughters (who made and unmade emperors in the 3rd century), **Helena** (mother of Constantine, venerated as a saint in Christianity), **Galla Placidia** (mother of Valentinian III, regent in the West) and, in the East, **Pulcheria**. They received the title **Augusta**.',
  { h: 'The table of the emperors' },
  'The following lists follow conventional dates and group the emperors by dynasty or period. Where two or more ruled at the same time (for instance, in the Tetrarchy), the reigns overlap. Names in brackets are birth names. The “End” column indicates how the reign ended, according to the most common sources; where there is doubt, it says so.',
  { h: 'Julio-Claudians (27 BC – AD 68)' },
  { tabela: { cab: ['Emperor', 'Reign', 'End'], linhas: [
    ['Augustus (Gaius Octavius)', '27 BC – AD 14', 'Natural death, at Nola'],
    ['Tiberius', '14 – 37', 'Died at Misenum; rumour that he was smothered, not proven'],
    ['Caligula (Gaius Caesar)', '37 – 41', 'Murdered by the Praetorian Guard'],
    ['Claudius', '41 – 54', 'Died in debated circumstances; poisoning is the ancient version, without proof'],
    ['Nero', '54 – 68', 'Suicide, after being declared a public enemy']
  ] } },
  { h: 'Year of the Four Emperors and Flavians (68 – 96)' },
  { tabela: { cab: ['Emperor', 'Reign', 'End'], linhas: [
    ['Galba', '68 – 69', 'Killed in Rome by the praetorians'],
    ['Otho', '69', 'Suicide, after defeat at Bedriacum'],
    ['Vitellius', '69', 'Killed by Flavian troops, in Rome'],
    ['Vespasian', '69 – 79', 'Natural death'],
    ['Titus', '79 – 81', 'Illness'],
    ['Domitian', '81 – 96', 'Murdered in a palace conspiracy']
  ] } },
  { h: 'Nerva-Antonines (96 – 192)' },
  { tabela: { cab: ['Emperor', 'Reign', 'End'], linhas: [
    ['Nerva', '96 – 98', 'Natural death'],
    ['Trajan', '98 – 117', 'Died in Cilicia, on the return from the campaign against the Parthians'],
    ['Hadrian', '117 – 138', 'Natural death, at Baiae'],
    ['Antoninus Pius', '138 – 161', 'Natural death'],
    ['Marcus Aurelius', '161 – 180', 'Died on the Danube frontier (Vindobona or Sirmium, debated)'],
    ['Lucius Verus (co-emperor)', '161 – 169', 'Died of a sudden illness (apoplexy), near Altinum'],
    ['Commodus', '180 – 192', 'Murdered in a palace conspiracy']
  ] } },
  { h: 'Year of the Five Emperors and Severans (193 – 235)' },
  { tabela: { cab: ['Emperor', 'Reign', 'End'], linhas: [
    ['Pertinax', '193', 'Killed by the praetorians'],
    ['Didius Julianus', '193', 'Executed by order of the Senate'],
    ['Septimius Severus', '193 – 211', 'Illness, at Eboracum (York)'],
    ['Caracalla', '211 – 217', 'Murdered by soldiers, near Carrhae'],
    ['Geta (co-emperor)', '211', 'Murdered, on his brother’s orders'],
    ['Macrinus', '217 – 218', 'Defeated and killed'],
    ['Elagabalus', '218 – 222', 'Murdered by the praetorians'],
    ['Severus Alexander', '222 – 235', 'Murdered by soldiers, near Mogontiacum (Mainz)']
  ] } },
  { h: 'Crisis of the 3rd century (235 – 284)' },
  'The most confusing period of the list. Historians call it the **Military Anarchy**: more than twenty recognised emperors in fifty years, almost all killed in civil wars. The list below gives the main ones; there were also regional usurpers, sometimes for years.',
  { tabela: { cab: ['Emperor', 'Reign', 'End'], linhas: [
    ['Maximinus Thrax', '235 – 238', 'Killed by his own troops'],
    ['Gordian I and II', '238', 'Father and son; the son died in battle, the father committed suicide'],
    ['Pupienus and Balbinus', '238', 'Killed by the praetorians'],
    ['Gordian III', '238 – 244', 'Died on the campaign against Persia; circumstances debated'],
    ['Philip the Arab', '244 – 249', 'Killed in battle against Decius'],
    ['Decius', '249 – 251', 'Died in battle against the Goths, at Abritus'],
    ['Trebonianus Gallus', '251 – 253', 'Killed by his own troops'],
    ['Aemilian', '253', 'Killed by his own troops'],
    ['Valerian', '253 – 260', 'Captured by the Persians; died in captivity'],
    ['Gallienus', '253 – 268', 'Murdered, during the siege of Milan'],
    ['Claudius II Gothicus', '268 – 270', 'Died of plague'],
    ['Quintillus', '270', 'Suicide, or murdered'],
    ['Aurelian', '270 – 275', 'Murdered by officers'],
    ['Tacitus', '275 – 276', 'Died in obscure circumstances'],
    ['Florian', '276', 'Killed by his own troops'],
    ['Probus', '276 – 282', 'Murdered by soldiers, at Sirmium'],
    ['Carus', '282 – 283', 'Died on the Persian campaign, cause debated'],
    ['Carinus and Numerian', '283 – 285', 'Numerian died in 284 (murdered); Carinus was killed in battle in 285']
  ] } },
  { h: 'Tetrarchy and Constantinians (284 – 363)' },
  { tabela: { cab: ['Emperor', 'Reign', 'End'], linhas: [
    ['Diocletian', '284 – 305', 'Abdicated; died at Split, c. 311–312'],
    ['Maximian (augustus of the West)', '286 – 305, and then 306–308, 310', 'Abdicated, returned to power, and was forced to commit suicide by Constantine'],
    ['Constantius I', '305 – 306 (Caesar from 293)', 'Died of illness, at Eboracum'],
    ['Galerius', '305 – 311', 'Died of illness'],
    ['Maxentius', '306 – 312', 'Killed at the battle of the Milvian Bridge'],
    ['Licinius', '308 – 324', 'Defeated by Constantine and executed'],
    ['Constantine I', '306 – 337', 'Died near Nicomedia, after being baptised'],
    ['Constantine II', '337 – 340', 'Killed in battle against his brother Constans'],
    ['Constans', '337 – 350', 'Murdered by a usurper, Magnentius'],
    ['Constantius II', '337 – 361', 'Natural death, while marching against Julian'],
    ['Julian', '361 – 363', 'Killed on campaign against the Persians'],
    ['Jovian', '363 – 364', 'Died in obscure circumstances, on the way to Constantinople']
  ] } },
  { h: 'Valentinians and Theodosians (364 – 455)' },
  { tabela: { cab: ['Emperor', 'Reign', 'End'], linhas: [
    ['Valentinian I (West)', '364 – 375', 'Died of apoplexy, during an audience'],
    ['Valens (East)', '364 – 378', 'Killed at the battle of Adrianople'],
    ['Gratian (West)', '367 / 375 – 383', 'Killed by an officer of the usurper Maximus'],
    ['Valentinian II (West)', '375 – 392', 'Found hanged; suicide or murder, debated'],
    ['Theodosius I', '379 – 395', 'Natural death, at Milan; sole master of the whole Empire in 394–395'],
    ['Arcadius (East)', '395 – 408', 'Natural death'],
    ['Honorius (West)', '395 – 423', 'Natural death'],
    ['Theodosius II (East)', '408 – 450', 'Fall from a horse'],
    ['Valentinian III (West)', '425 – 455', 'Murdered by guards loyal to General Aetius, whom he himself had had killed']
  ] } },
  { h: 'The last emperors of the West (455 – 476)' },
  { tabela: { cab: ['Emperor', 'Reign', 'End'], linhas: [
    ['Petronius Maximus', '455', 'Killed while fleeing Rome'],
    ['Avitus', '455 – 456', 'Deposed; became a bishop'],
    ['Majorian', '457 – 461', 'Deposed and killed by Ricimer'],
    ['Libius Severus', '461 – 465', 'Natural death, or by Ricimer'],
    ['Anthemius', '467 – 472', 'Killed on Ricimer’s orders (by Gundobad), after Rome was taken'],
    ['Olybrius', '472', 'Natural death'],
    ['Glycerius', '473 – 474', 'Deposed by Julius Nepos; became a bishop'],
    ['Julius Nepos', '474 – 475 (recognised by the East until 480)', 'Exiled to Dalmatia, where he was murdered in 480'],
    ['Romulus Augustulus', '475 – 476', 'Deposed by Odoacer; retired, probably in Campania (later fate uncertain)']
  ] } },
  'In the East, **Marcian** (450–457), **Leo I** (457–474) and **Zeno** (474–491) continued the line, in Constantinople. The history of the Eastern empire, which runs to 1453, belongs to the future Byzantine Empire project.',
  { h: 'The writers: imperial literature' },
  'The age of the emperors is also one of the great phases of Latin literature. The so-called **Golden Age** (c. 70 BC – AD 14) has Cicero, Caesar, Sallust, Virgil, Horace, Livy and Ovid. The **Silver Age** (c. 14 – 130) has Seneca, Lucan, Pliny the Elder, Martial, Quintilian, Pliny the Younger, Juvenal, Tacitus and Suetonius. Afterwards Greek dominates again (Plutarch, Epictetus, Marcus Aurelius, who writes the Meditations in Greek) and Christian Latin gains strength, with Tertullian, Augustine and Jerome.',
  { img: 'rim-virgilio-mosaico', leg: 'Mosaic of Virgil with Clio and Melpomene, Bardo Museum, Tunis.' },
  { h: 'How a career was made' },
  'A senator followed the **cursus honorum**, the “sequence of honours”: quaestor, aedile or tribune, praetor, consul, and then governor of a province. In practice the emperor chose who advanced. An equestrian followed his own career, from officer to procurator and, at the top, prefect. There were rare cases of men risen from nothing: Diocletian was of humble origin (the son of a freedman or of a scribe, according to the sources), and Maximinus Thrax of modest origin.',
  { h: 'The cost of being emperor' },
  'The office was dangerous. Between Augustus and Septimius Severus about half the emperors died violently or in suspicious circumstances; in the 3rd century, the overwhelming majority. Emperors therefore spent enormous sums on gifts to the soldiers and on spectacles: the support of both groups was life insurance.',
  { img: 'rim-triunfo-cena', leg: 'AI-generated illustration. Roman triumphal procession on the Via Sacra, second century AD.' },
  { h: 'The emperor and religion' },
  'The emperor was Pontifex Maximus, and therefore responsible for public worship. In Rome his person was not venerated as a god, but his **genius** (protecting spirit) received offerings; in the eastern provinces the worship of a living king was naturally accepted. After death, consecration made him a divus. Refusal to offer incense to the emperor was one of the reasons Christians were persecuted at certain times (Nero, Decius, Diocletian). With Constantine the emperor begins to protect the Church and to preside over councils.',
  { h: 'The emperor and justice' },
  'The emperor answered petitions from citizens and governors with letters and decisions (**rescripts**), which counted as law. The correspondence of **Pliny the Younger** with Trajan, when he was governor of Bithynia, shows the bureaucratic side: even an aqueduct or a question about the Christians was referred to the emperor. The great jurists of the time were senior officials: Papinian was praetorian prefect of Septimius Severus, and Ulpian of Severus Alexander.',
  { h: 'The emperor and money' },
  'The imperial treasury (fiscus) paid for the army, public works and distributions. Revenue came from taxes on land and persons (in the provinces), customs, mines and imperial estates. In the 3rd century emperors paid for wars by reducing the silver in the coinage: the silver coin (the denarius, and later the antoninianus) went from more than 90% silver in Nero’s time to little more than 5% around 270. Diocletian’s monetary reform and then Constantine’s gold coin, the **solidus** (about 4.5 g), stabilised the system for centuries.',
  { h: 'Emperors and cities' },
  'Each emperor left his mark on the urban landscape: Augustus rebuilt Rome and the Campus Martius; Vespasian and Titus the Colosseum; Domitian his palace; Trajan a forum, a market and a harbour at Portus; Hadrian the Pantheon and his mausoleum (Castel Sant’Angelo); Caracalla the largest baths; Aurelian a wall; Diocletian baths and a palace; Constantine a basilica, an arch and a new city. Each work was a political message as much as a public service.',
  { h: 'A lesson from Tacitus' },
  { cit: 'I shall write without anger or partiality (sine ira et studio).', fonte: 'Tacitus, Annals 1.1, the historian’s programme; the translation is free' },
  'Tacitus promises impartiality, but he is a writer with strong opinions. He himself lived under Domitian and knew fear. His image of the first emperors, however brilliant, must therefore be read in the knowledge that it is a senator writing about the man who took power from senators.'
];

const personalidades = [
  'These 30 figures were chosen because they marked their time or the memory of later ages: emperors, but also generals, politicians, women of the imperial household, writers and thinkers. They are, broadly, in chronological order of birth. Where something is legend, tradition or a matter of debate, the text says so. Dates before 27 BC belong to the Republic; for their context, see the pages on the Late Republic and the High Empire.',
  { h: 'Publius Cornelius Scipio Africanus (236/235 – 183 BC)' },
  'The general who defeated Hannibal. The son of a consul, he survived the disasters of the Ticinus and Cannae, and at about 25 took command of the Roman forces in Hispania, where he took New Carthage (209) and defeated the Carthaginians at Baecula (208) and Ilipa (206). Consul in 205, he took the war to Africa and defeated Hannibal at **Zama** (202). He received the name Africanus. Later, political opponents, among them Cato, attacked him with accusations of corruption; he retired to Liternum, in Campania, where he died. The **Tomb of the Scipios**, on the Appian Way, belongs to his family; where he himself was buried is uncertain.',
  { img: 'rim-cipiao-zama', leg: 'AI-generated illustration. Scipio and the battle of Zama, 202 BC.' },
  { h: 'Marcus Porcius Cato the Elder (234 – 149 BC)' },
  'Born at Tusculum, of a plebeian family with no senatorial tradition (a “new man”). Consul in 195 (he commanded in Hispania), censor in 184, he became the symbol of Roman austerity and of hostility to Greek influence (although he learned Greek in old age). He wrote the Origines, the first history of Rome in Latin, and **De agri cultura**, the oldest Latin prose text that survives complete. The phrase Carthago delenda est (“Carthage must be destroyed”), which according to tradition he repeated at the end of his speeches, is attributed to him by later authors; the exact form is uncertain. He died in 149, the year the Third Punic War began.',
  { h: 'Marcus Tullius Cicero (106 – 43 BC)' },
  'Orator, lawyer, politician and philosopher, born at Arpinum of an equestrian family, and therefore a “new man” in the Senate. Consul in 63, he uncovered and suppressed the **conspiracy of Catiline**, having five accomplices executed without trial, which cost him exile in 58–57. He tried, without success, to preserve the Republic between Caesar and Pompey. After Caesar’s assassination he attacked Mark Antony in the Philippics; when Antony, Octavian and Lepidus formed the Triumvirate, he was included in the proscriptions and **killed on 7 December 43**. His head and hands were displayed on the Rostra in the Forum. He left speeches, treatises (On the Republic, On Duties) and about 900 letters, the best source for the political life of his time and the model of Latin prose.',
  { img: 'rim-cicero-busto', leg: 'Bust of Cicero, Capitoline Museums.' },
  { img: 'rim-cicero-catilina', leg: 'AI-generated illustration. Cicero and Catiline in the Senate, 63 BC.' },
  { h: 'Gnaeus Pompeius Magnus, Pompey (106 – 48 BC)' },
  'The most prestigious general of his generation. He began as a partisan of Sulla, won the name “Magnus” and celebrated a triumph before having held any magistracy. He defeated Sertorius in Hispania (c. 76–71), cleared the Mediterranean of pirates in a few months (67) and reorganised the East after defeating Mithridates (66–62): Jerusalem was taken in 63. He allied with Caesar and Crassus in the **first triumvirate** (60) and married Caesar’s daughter Julia. His rivalry with Caesar led to civil war. Defeated at **Pharsalus** (48), he fled to Egypt, where he was killed on landing at Pelusium. He built the first permanent stone theatre in Rome (55 BC), on the Campus Martius.',
  { img: 'rim-pompeu-busto', leg: 'Portrait of Pompey, Ny Carlsberg Glyptotek, Copenhagen.' },
  { h: 'Gaius Julius Caesar (100 – 44 BC)' },
  'An aristocrat of an ancient but then not very powerful family, Marius’ nephew by marriage, he rose by the popular route. Consul in 59, he was then governor of Gaul (58–50), which he conquered in eight years of war and narrated in the Commentaries. In January 49 he crossed the **Rubicon** with a legion, beginning the civil war: he defeated Pompey at Pharsalus (48), and later the Pompeians at Thapsus (46) and Munda (45). In Alexandria he supported Cleopatra VII, by whom he had a son, Caesarion. As dictator he reformed the calendar (the **Julian calendar**, 46 BC), founded colonies and enlarged the Senate. He was named dictator for life in February 44 and **assassinated on 15 March** (the “Ides of March”) by a group of senators, among them Brutus and Cassius. The phrase “Veni, vidi, vici” is attributed to him by Plutarch and Suetonius, after the victory over Pharnaces (47).',
  { img: 'rim-cesar-busto', leg: 'Tusculum head, portrait of Caesar, Turin Museum of Antiquities.' },
  { img: 'rim-idos-de-marco', leg: 'AI-generated illustration. Caesar’s assassination in the Curia of Pompey, 44 BC.' },
  { h: 'Augustus (63 BC – AD 14)' },
  'Gaius Octavius, Caesar’s great-nephew, was adopted in Caesar’s will at 18. He allied with Antony and Lepidus in the triumvirate (43), avenged Caesar at **Philippi** (42), and defeated Antony and Cleopatra at **Actium** (31). In 27 BC he received the name **Augustus** and built the Principate, which kept up the appearance of the Republic. He reformed the army (professional and paid by the state), created the Praetorian Guard, the fire brigade and the post, reorganised the provinces, and left his successors a capital of marble (the phrase is attributed by Suetonius). He lost three legions in the Teutoburg Forest (AD 9) and gave up Germany beyond the Rhine. His account of his own career, the Res Gestae, was engraved in bronze at the entrance of his mausoleum, and survives, in copy, in Ankara. He died at Nola, aged 75.',
  { img: 'rim-res-gestae', leg: 'Res Gestae Divi Augusti, Temple of Rome and Augustus, Ankara.' },
  { h: 'Livia Drusilla (59 BC – AD 29)' },
  'She was born into a republican family of great name. Married to Tiberius Claudius Nero, she divorced him to marry Octavian, in 38 BC, pregnant with her second son, Drusus. She was Augustus’ wife for more than 50 years, mother of Tiberius, and his trusted adviser; by his will she received the name **Julia Augusta** and entered the Julian family. Ancient historians (Tacitus, Cassius Dio) insinuate that she poisoned rivals to give the throne to her son; there is **no proof**, and the authors speak out of hostility to the regime. She lived to 86, and Claudius, her grandson, had her consecrated a goddess in 42.',
  { img: 'rim-livia-busto', leg: 'Basalt head identified as Livia Drusilla, Louvre; photographed at an exhibition at the Grand Palais, Paris.' },
  { h: 'Publius Vergilius Maro, Virgil (70 – 19 BC)' },
  'Rome’s greatest poet, born near Mantua, of a rural family. He wrote the Bucolics (the Eclogues), the Georgics (on farming) and, in the service of Augustus’ project, the **Aeneid**, the epic poem that tells the voyage of Aeneas, the Trojan who survived the fall of Troy and reached Italy, from where the Romans were to descend. According to the ancient life attributed to Donatus, he died at Brundisium on the way back from Greece, asking that the unfinished poem be burned; Augustus ordered it published. Dante chose him as his guide in the Divine Comedy.',
  { h: 'Tiberius (42 BC – AD 37)' },
  'Livia’s son, stepson and then adopted son and son-in-law of Augustus, he was one of the best generals of his time, in Pannonia and Germany. He withdrew to Rhodes (6 BC – AD 2), resentful, before being adopted in AD 4. He was emperor from 14 to 37. He governed well, soberly and with healthy finances, but his reign was marked by **treason trials**, and by the rise and fall of **Sejanus** (31), prefect of the praetorians. From 26/27 he lived on Capri, far from Rome. During his reign the prefect of Judaea was Pontius Pilate (26–36). Tacitus and Suetonius paint him as a sombre tyrant, but both write with strong senatorial prejudice.',
  { img: 'rim-tiberio-busto', leg: 'Bust of Tiberius, Ny Carlsberg Glyptotek.' },
  { h: 'Caligula (12 – 41)' },
  'Gaius Caesar Germanicus was born at Antium, son of Germanicus, Rome’s most beloved general, and of Agrippina the Elder. The nickname “Caligula” (“little boot”) comes from the military footwear he wore as a child in his father’s camp. He became emperor at 24, hugely popular. After a serious illness in 37, the sources describe a man growing ever more cruel and megalomaniac: he demanded worship, ordered a bridge of boats built at Baiae, and, according to Suetonius, is said to have planned to make his horse Incitatus consul (a plan never carried out). Almost all of this comes from Suetonius and Dio, who write decades later and hostile; modern historians treat it with caution, without denying the tyranny. He was **assassinated on 24 January 41** by praetorian officers led by Cassius Chaerea.',
  { h: 'Claudius (10 BC – AD 54)' },
  'Born at Lugdunum, grandson of Livia, lame and with a stammer, he was kept out of public life and studied history (he wrote works, now lost, on the Etruscans and the Carthaginians). At 50, according to tradition, the praetorians found him hiding in the palace after Caligula’s death and **proclaimed him emperor**. He governed competently: he created a bureaucracy of freedmen, built the harbour at Ostia (Portus) and two aqueducts, and ordered the **conquest of Britain** (43). He widened citizenship and opened the Senate to notables from Gaul. His wives were problematic: Messalina was executed in 48, and Agrippina the Younger married him in 49. He died in 54; the **ancient version** is that he was poisoned by Agrippina, which is plausible but uncertain.',
  { h: 'Agrippina the Younger (15 – 59)' },
  'Daughter of Germanicus and sister of Caligula, she was born at the Oppidum Ubiorum, on the Rhine, the future Cologne; she was the mother of Nero, from a first marriage. Exiled by Caligula, she returned under Claudius, who married her, his niece, in 49, after the Senate changed the law that forbade marriage between uncle and niece. She got Claudius to adopt Nero and, in the first phase of her son’s reign, governed from the shadows. Nero, resentful, tried to drown her in a collapsible boat at Baiae; she survived and was killed by men sent by Nero, in her villa (59). She wrote memoirs, now lost, used by Tacitus, who describes her as ambitious and ruthless.',
  { img: 'rim-agripina-busto', leg: 'Seated statue traditionally identified as Agrippina the Younger, Farnese collection, Naples National Archaeological Museum; attribution debated.' },
  { h: 'Lucius Annaeus Seneca (c. 4 BC – AD 65)' },
  'Born at Córdoba, the son of a rhetorician, he trained in Rome as a **Stoic** philosopher. Exiled to Corsica by Claudius (41–49), he was recalled by Agrippina to be Nero’s tutor. With the prefect Burrus he guided the government in the young emperor’s first years (the so-called quinquennium). He was extremely rich, which earned him accusations of hypocrisy. He wrote treatises (On the Shortness of Life, On Anger), the **124 Letters to Lucilius**, and tragedies. Accused of taking part in the Pisonian conspiracy (65), he was ordered to commit suicide, and Tacitus describes his serene death, surrounded by friends.',
  { img: 'rim-seneca-nero', leg: 'AI-generated illustration. Seneca, Nero and Burrus during a lesson, c. AD 55.' },
  { h: 'Nero (37 – 68)' },
  'Lucius Domitius Ahenobarbus, adopted by Claudius, became emperor at 16. In the first five years he governed well, with Seneca and Burrus. Then he had his adoptive brother Britannicus killed (55), his mother (59), and later his wife Octavia (62). On the **fire of 64** the sources differ: a rumour that he had ordered it circulated, and Tacitus reports it without confirming it; Nero blamed the Christians. He built the Domus Aurea, sponsored Greek festivals and performed publicly as singer and charioteer, which shocked the aristocracy. After the revolt of Vindex and Galba, the Senate declared him a public enemy, and he **committed suicide on 9 June 68**. The legend that he played the lyre while Rome burned has no solid basis: Tacitus says he was at Antium (Suetonius and Dio say he sang the “Sack of Ilium” during the fire). Many believed he had not died, and there were several false Neros.',
  { img: 'rim-nero-busto', leg: 'Bust of Nero, Capitoline Museums.' },
  { h: 'Vespasian (9 – 79)' },
  'Titus Flavius Vespasianus, from an equestrian family of humble origin (Reate, in the Sabine hills), rose through the military career: he served in Britain under Claudius, and was sent by Nero to crush the Jewish revolt (67). In 69, on learning that Vitellius had taken power, he was acclaimed by the legions of Egypt and Syria, and won the civil war. He **founded the Flavian dynasty**, restored the finances, had the Empire surveyed, and began the **Colosseum** and the Temple of Peace. Tradition (Suetonius) says he imposed a tax on the urinals of the fullers, and answered his son with pecunia non olet, “money does not smell”. On his deathbed he is said to have remarked: “I think I am becoming a god.” Both sayings are anecdotes.',
  { img: 'rim-vespasiano-busto', leg: 'Colossal bust of Vespasian, Naples National Archaeological Museum (inv. 6068).' },
  { h: 'Pliny the Elder (23/24 – 79)' },
  'Born at Como, a lawyer, officer and commander of the fleet at Misenum, he wrote numerous works, of which only the **Natural History** survives, in 37 books, an encyclopaedia of astronomy, geography, zoology, botany, medicine and minerals, dedicated to Titus in 77. In 79, seeing the eruption of Vesuvius from Misenum, he set out to help friends at Stabiae, and died there (suffocated by the fumes, according to his nephew). The work was curious and credulous, but it is the greatest compilation of knowledge of Latin antiquity.',
  { h: 'Titus (39 – 81)' },
  'Vespasian’s son, he commanded the army in Judaea after his father was acclaimed, and took **Jerusalem in 70**, destroying the Temple. He had a love affair with Queen Berenice, whom he sent away from Rome on becoming emperor, because she was unpopular. Emperor from 79 to 81, he faced Vesuvius, a great fire in Rome (80) and an epidemic. He inaugurated the **Colosseum**, with a hundred days of games, and distributed aid to the victims of the disasters. Tradition (Suetonius) says that on a day when he had done no kindness to anyone he said: “I have lost a day.” He died of illness aged 41, and the people mourned him. He was the opposite of his brother Domitian, who succeeded him.',
  { h: 'Pliny the Younger (c. 61 – c. 113)' },
  'Nephew and adopted son of Pliny the Elder, born at Como. A lawyer, consul in 100, he governed the province of Bithynia and Pontus (c. 109–113, dates debated) by appointment of Trajan. His **Letters** (nine books plus one with the correspondence with Trajan) are precious portraits of the life of a cultivated senator: the villa, friends, lawsuits. Two of them, to Tacitus, describe the eruption of Vesuvius and his uncle’s death. Another, to Trajan (book 10), is one of the first Roman texts to describe how Christians were treated: the emperor replies that they should not be sought out, but that those denounced who refuse to recant should be punished.',
  { img: 'rim-plinio-vesuvio', leg: 'AI-generated illustration. Pliny the Younger and his mother observe Vesuvius from Misenum, AD 79.' },
  { h: 'Publius Cornelius Tacitus (c. 56 – c. 120)' },
  'Rome’s greatest historian. Probably of Gallia Narbonensis origin (uncertain), he was a senator, consul in 97 and governor of Asia. He married the daughter of Agricola. He wrote the Agricola (life of his father-in-law, governor of Britain), the Germania, the Dialogue on Orators, the Histories (69–96) and the Annals (14–68). Only parts survive: of the Histories, the year 69 and the beginning of 70; of the Annals, the reign of Tiberius (with a gap), part of those of Claudius and Nero (the text breaks off in the year 66); Caligula’s is missing. In Annals 15.44 he describes Nero’s persecution of the Christians after the fire of 64: it is one of the earliest mentions of Christ by a Roman author.',
  { h: 'Marcus Ulpius Traianus, Trajan (53 – 117)' },
  'Born at Italica (Hispania Baetica), he was the **first non-Italian emperor**. A competent general, he was governing Upper Germany when Nerva adopted him in 97. As emperor he conquered **Dacia** (101–102, 105–106), bringing in the gold of its mines and financing works such as Trajan’s Forum and Markets. He created the system of the **alimenta**, pensions for poor children of Italy. In 113 he set out against the Parthians, and reached the Persian Gulf; in 117 the Empire was at its greatest extent, but the new provinces revolted. He died at Selinus, in Cilicia, and his ashes were placed in the base of **Trajan’s Column**. The Senate gave him the title optimus princeps, the “best of rulers”.',
  { img: 'rim-trajano-busto', leg: 'Bust of Trajan, Munich Glyptothek.' },
  { h: 'Publius Aelius Hadrianus, Hadrian (76 – 138)' },
  'Distant cousin (first cousin once removed) and ward of Trajan, born in Rome or at Italica (debated). His succession, in 117, was contested (Trajan’s wife Plotina helped him). He abandoned the conquests in Mesopotamia and spent more than half his reign travelling through the provinces, always on foot or on horseback, inspecting troops, granting privileges and ordering buildings. A lover of Greece, he had the temple of Zeus in Athens completed. In Rome he had the **Pantheon** rebuilt (c. 126–128), and at Tivoli his villa. In Britain he ordered **Hadrian’s Wall** (122). The death of his favourite, **Antinous**, in the Nile, in 130, led him to found a city (Antinoopolis) and promote his cult. He crushed the Jewish revolt of **Bar Kokhba** (132–135) and refounded Jerusalem as Aelia Capitolina. He chose Antoninus Pius as his successor.',
  { img: 'rim-adriano-busto', leg: 'Bust of Hadrian, Capitoline Museums.' },
  { h: 'Marcus Aurelius (121 – 180)' },
  'Adopted by Antoninus Pius, he came to the throne in 161, sharing power with Lucius Verus, the first case of two equal augusti. His reign was almost entirely war and disaster: the campaign against the Parthians (161–166), the **Antonine Plague** (from 165, with enormous mortality of very uncertain estimate) and the wars against the Marcomanni and Quadi on the Danube. A Stoic, he wrote in Greek, for himself, the 12 books of the **Meditations**, during the campaigns; it became one of the most widely read books of antiquity. He was the last of the “five good emperors” (the expression is Machiavelli’s), and broke the rule of adoption by making his son **Commodus** his successor. He died on 17 March 180, on the Danube.',
  { img: 'rim-marco-aurelio-equestre', leg: 'Original equestrian statue of Marcus Aurelius, Capitoline Museums.' },
  { h: 'Commodus (161 – 192)' },
  'Marcus Aurelius’ son, born at Lanuvium, he was associated with power in 177 and became sole emperor in 180, aged 18. He made peace with the Marcomanni and returned to Rome, leaving government to favourites. He identified with Hercules (coins and statues show him with the lion skin and club) and **fought in the arena** as a gladiator, which scandalised the Senate (Cassius Dio, who witnessed it, describes it). After several conspiracies he grew more violent and renamed Rome “Colonia Commodiana”. He was **assassinated on 31 December 192**, strangled by an athlete, in a conspiracy that involved his concubine and the prefect. The Senate decreed the damnatio memoriae, revoked by Septimius Severus.',
  { img: 'rim-commodo-hercules', leg: 'Commodus as Hercules, Capitoline Museums.' },
  { img: 'rim-commodo-arena', leg: 'AI-generated illustration. Commodus in the arena as Hercules, c. AD 190.' },
  { h: 'Lucius Septimius Severus (145 – 211)' },
  'Born at Leptis Magna, in Africa, of an equestrian family, the first African emperor. He was acclaimed by the Danube legions in 193, the “Year of the Five Emperors”, and in four years defeated his rivals Niger and Albinus. He campaigned against the Parthians (taking Ctesiphon in 198) and in North Africa. He raised the legions’ pay, created three new legions and **militarised government**, putting equestrians in posts that had been senators’. He married the Syrian Julia Domna, and left the house to his sons Caracalla and Geta. The phrase Cassius Dio attributes to him on his deathbed (“be united, enrich the soldiers, scorn all others”) is an anecdote. He died at Eboracum (York), during the Scottish campaign.',
  { img: 'rim-septimio-severo-tondo', leg: 'Severan Tondo: Septimius Severus, Julia Domna and Caracalla, with Geta’s face erased; Antikensammlung, Berlin.' },
  { h: 'Caracalla (188 – 217)' },
  'Lucius Septimius Bassianus, born at Lugdunum, took the name “Marcus Aurelius Antoninus”, and became known by the Gallic cloak he wore (caracallus). In 211, after his father’s death, he had his brother and co-emperor **Geta** killed and his name erased. In 212 he issued the **Constitutio Antoniniana**, which gave citizenship to nearly all free inhabitants of the Empire; the reasons (fiscal, religious, egalitarian) are debated. He minted the antoninianus and built the **Baths of Caracalla**, inaugurated in 216, among the largest in Rome. He was killed on 8 April 217 by a guard officer, near Carrhae, on the way to a campaign against the Parthians.',
  { h: 'Lucius Domitius Aurelianus, Aurelian (c. 214 – 275)' },
  'A soldier of humble origin, born in the Danube region (Sirmium or Dacia, debated), he became emperor in 270, when the Empire was divided in three. He defeated the Goths and Germans who invaded Italy, abandoned Dacia, defeated Queen **Zenobia** of Palmyra (272) and the **Gallic Empire** (274), and reunified the Empire. He had the **Aurelian Walls** built, still visible in Rome today. He sought to unify worship around the Unconquered Sun, with a great temple in Rome, in 274. He was assassinated in 275 by officers, as a result of an intrigue in which a secretary made them fear punishment. He had been given the title Restitutor Orbis, “restorer of the world”.',
  { h: 'Diocletian (c. 244 – c. 311)' },
  'Born in Dalmatia, of humble origin, he rose through the ranks of the army and was proclaimed in 284. Understanding that one man could not defend the Empire, he chose **Maximian** as caesar (285) and then augustus (286) and created the **Tetrarchy** (293): two augusti and two caesars, each in a region. He doubled the number of provinces and reorganised the army, taxes and coinage; the **Edict on Maximum Prices** (301) tried to curb inflation, without success. He imposed a court ceremonial in which the emperor was greeted on bended knee. In 303 he began the **Great Persecution** of the Christians, the last and the most severe. On 1 May 305 he abdicated and retired to the palace at Split. He died c. 311–312; the dates are not certain.',
  { img: 'rim-diocleciano-busto', leg: 'Head of Diocletian, Istanbul Archaeology Museum.' },
  { h: 'Constantine (c. 272 – 337)' },
  'Son of Constantius Chlorus and Helena, born at Naissus (Niš, Serbia), he was acclaimed by the troops at Eboracum on **25 July 306**. He defeated Maxentius at the **Milvian Bridge** (28 October 312); according to Lactantius he dreamed the night before of a Christian sign to put on the shields; according to Eusebius he saw a cross in the sky: the two versions differ. In 313, with Licinius, he agreed the policy of toleration known as the “Edict of Milan” (historians debate whether it was an edict). He convened the **Council of Nicaea** (325) and, after defeating Licinius (324), reunited the Empire, founding **Constantinople** (330). He created the solidus, the stable gold coin. He was baptised only on his deathbed, in 337. In 326 he had his son Crispus executed and, soon after, his wife Fausta: the reasons are obscure.',
  { img: 'rim-constantino-colosso', leg: 'Head of the Colossus of Constantine, Capitoline Museums.' },
  { img: 'rim-ponte-milvio', leg: 'AI-generated illustration. Battle of the Milvian Bridge, AD 312; Christian symbolism following the tradition.' },
  { h: 'Flavius Claudius Julianus, Julian (331/332 – 363)' },
  'Constantine’s nephew, he survived a massacre of the family in 337. He studied Neoplatonic philosophy and was named Caesar in 355. In Gaul he defeated the Alamanni at **Strasbourg** (357) and restored the Rhine frontiers. Proclaimed augustus by his troops at Paris (360), he marched against his cousin Constantius II, who died before the clash. He had become a pagan in secret, and when he came to power (361) he tried to **restore the traditional cults** and withdrew privileges from the Christian clergy; the Christians called him “the Apostate”. He wrote in Greek (the Misopogon, a satire on himself, and speeches). He died on 26 June 363, wounded during the Persian campaign, aged 31.',
  { h: 'Theodosius I, the Great (347 – 395)' },
  'Born in Hispania (at Cauca, in the Segovia region, or at Italica; debated), son of a general of the same name. He was called by Gratian in 379, after the disaster at Adrianople, to govern the East. He made peace with the Goths (382), who settled as federates inside the Empire. In **380**, with the Edict of Thessalonica, he ordered all subjects to follow the faith of the bishops of Rome and Alexandria, that is, Nicene Christianity; in the following years he banned pagan sacrifices. After the massacre at Thessalonica (390), Ambrose, bishop of Milan, imposed public penance on him. In 394 he defeated Eugenius and Arbogast at the Frigidus, and **ruled the whole Empire alone** for a few months. He died at Milan in 395, leaving the East to Arcadius and the West to Honorius, his sons. There was never again, on a stable basis, a single emperor for the whole Roman world.',
  { img: 'rim-teodosio-missorium', leg: 'Missorium of Theodosius I (AD 388), Real Academia de la Historia, Madrid; historical glass-slide photograph.' }
];

const legado = [
  'What remains of the emperors and great figures of Rome lives on in words, buildings, books, and also in the images, often false, that popular culture has kept.',
  { h: 'Inherited words' },
  { lista: [
    '**Caesar** gave Kaiser (German) and tsar or czar (Russian, Bulgarian and Serbian).',
    '**Augustus** gave the name of the month of **August**, and **Julius Caesar** that of **July**.',
    '**Emperor** (from imperator) is the word for the head of an empire in nearly all European languages.',
    '**Palace** comes from Palatium, the Palatine hill where the emperors lived.',
    '**Caesarean:** the popular name of the operation is linked to Caesar, but there is no proof that he was born that way.',
    '**Dictator, consul, senate, tribune, veto** are Roman political words.'
  ] },
  { h: 'Architecture you can visit' },
  { lista: [
    '**Colosseum** (Rome): the work of the Flavians, AD 70–80.',
    '**Pantheon** (Rome): Hadrian, c. 126–128; still the largest unreinforced concrete dome in the world.',
    '**Trajan’s Forum and Column** (Rome).',
    '**Arch of Constantine** and **Arch of Titus** (Rome).',
    '**Baths of Caracalla** (Rome).',
    '**Aurelian Walls** (Rome).',
    '**Hadrian’s Wall** (England), **Hadrian’s Villa** (Tivoli).',
    '**Diocletian’s Palace** (Split, Croatia).',
    '**Porta Nigra** (Trier, Germany).',
    '**Leptis Magna** (Libya), the city of Septimius Severus.'
  ] },
  { img: 'rim-coluna-trajano', leg: 'Trajan’s Column, Rome.' },
  { img: 'rim-panteao', leg: 'Facade and portico of the Pantheon, Rome.' },
  { img: 'rim-muralha-adriano', leg: 'Aerial view of Hadrian’s Wall and Housesteads fort, Northumberland.' },
  { img: 'rim-arco-tito', leg: 'Arch of Titus relief showing the spoils of Jerusalem’s Temple.' },
  { img: 'rim-arco-constantino', leg: 'Arch of Constantine, Rome.' },
  { img: 'rim-muralhas-aurelianas', leg: 'Porta San Sebastiano in Rome’s Aurelian Walls; present state with later alterations.' },
  { h: 'Portraits and museums' },
  'The best collections of imperial portraits are in the **Capitoline Museums** (Rome), the **Vatican Museums**, the **National Archaeological Museum of Naples**, the **Munich Glyptothek**, the **Ny Carlsberg Glyptotek** (Copenhagen), the **Louvre** (Paris), the **British Museum** (London) and the **Antikensammlung** in Berlin. Most statues were painted, and today only the marble is seen.',
  { h: 'Texts still read' },
  'Marcus Aurelius’ **Meditations** are one of the most widely read books of practical philosophy. Virgil’s **Aeneid** was the Roman national poem, and remains a classic. Seneca’s **Letters to Lucilius**, Tacitus’ **Annals** and Pliny the Younger’s **Letters** are first-rate literature. Caesar’s **Commentaries** on the Gallic war were, for centuries, the first text read by Latin pupils.',
  { h: 'Rediscovery and historiography' },
  'In the Middle Ages the manuscripts of Tacitus and Suetonius almost vanished (the Annals survived in very few medieval codices). The Renaissance rediscovered them and rediscovered Rome: around 1480 the buried Domus Aurea was seen by painters. In 1776–1789 Edward Gibbon published the History of the Decline and Fall of the Roman Empire, which fixed for two centuries the image of the emperors as figures of power and decadence. Modern historians, with archaeology and epigraphy, have nuanced it.',
  { h: 'False and true images' },
  { lista: [
    '**Nero and the lyre:** no proof of the scene; Tacitus says he was at Antium (Suetonius and Dio say he sang the “Sack of Ilium” during the fire).',
    '**The thumbs down:** we do not know which gesture meant death; the Latin expression pollice verso (thumb “turned”) is ambiguous.',
    '**“Hail, Caesar, those who are about to die salute you”:** recorded only once, with Claudius, in 52, at a naval battle with condemned men.',
    '**The consul horse:** Suetonius speaks of a plan of Caligula’s, without saying it was carried out.',
    '**Commodus in the film Gladiator (2000):** Commodus kills his father; in reality Marcus Aurelius died on the Danube, of illness, and Commodus was murdered in Rome in 192.',
    '**Constantine and the “Edict of Milan”:** the letter of Licinius and Constantine of 313 was a policy of toleration, but the sources do not show a single “edict”.'
  ] },
  { h: 'Hispania and Portugal' },
  'The Romans of the Peninsula left their mark on Rome’s memory: **Trajan** and **Hadrian** from Italica, **Seneca** from Córdoba, **Theodosius** from Cauca (Segovia region) or Italica, **Quintilian** from Calahorra. In Portugal, **Caesar** left his name in Lisbon (Felicitas Iulia Olisipo) and in Beja (Pax Iulia); **Augustus** gave his name to Braga (Bracara Augusta) and Mérida (Augusta Emerita, where veterans were settled), and in Évora the so-called Roman temple, of the 1st century AD, is usually associated with the imperial cult. At Conímbriga, the House of the Fountains and the baths show the life of a Roman city in the time of the emperors.',
  { h: 'Where to visit' },
  'Anyone going to Rome should see the **Colosseum and the Roman Forum**, the **Palatine** (where the ruins of the imperial palaces are), the **Pantheon**, the **Mausoleum of Augustus** (reopened to the public in 2021), the **Mausoleum of Hadrian** (Castel Sant’Angelo), the **Baths of Caracalla** and the **Capitoline Museums**. In Portugal, the **Conímbriga Monographic Museum**, the **National Museum of Archaeology** (Lisbon) and the **Roman Temple of Évora**. In Spain, Mérida and Italica.',
  { h: 'Further reading' },
  'Anyone wishing to read the authors themselves will find translations of several of them: Suetonius (Lives of the Twelve Caesars), Tacitus (Annals, Germania, Agricola), Marcus Aurelius (Meditations), Seneca (Letters to Lucilius), Pliny the Younger (Letters) and Virgil (Aeneid). A title search in a library catalogue gives the most accessible edition.',
  { caixa: 'A note on the images', texto: 'This page uses images from Wikimedia Commons and some AI-generated illustrations, marked as such in the captions. Individual photo credits will be added when the images are inserted.' }
];

const quiz = [
  { p: 'In what year does the Roman Empire (the Principate) conventionally begin?', op: ['44 BC', '31 BC', '27 BC', 'AD 14'], certa: 2, exp: 'In 27 BC Octavian received the name Augustus; Actium (31 BC) was the victory that gave him power.' },
  { p: 'What title did Augustus use to avoid the word “king”?', op: ['Dominus', 'Princeps', 'Rex', 'Tyrant'], certa: 1, exp: 'Princeps, “first citizen”; dominus became general only with Diocletian.' },
  { p: 'Who was acclaimed emperor by the praetorians after Caligula’s murder?', op: ['Tiberius', 'Claudius', 'Nero', 'Galba'], certa: 1, exp: 'Claudius, Caligula’s uncle, was found in the palace and proclaimed in 41.' },
  { p: 'Who ruled during the “Year of the Four Emperors” (69)?', op: ['Galba, Otho, Vitellius and Vespasian', 'Nerva, Trajan, Hadrian and Antoninus', 'Nero, Galba, Otho and Titus', 'Claudius, Nero, Galba and Otho'], certa: 0, exp: 'The first three died; Vespasian founded the Flavian dynasty.' },
  { p: 'Which emperor conquered Dacia and took the Empire to its greatest extent (117)?', op: ['Augustus', 'Vespasian', 'Trajan', 'Septimius Severus'], certa: 2, exp: 'Trajan, born in Hispania, at Italica.' },
  { p: 'Which emperor had a wall built in Britain, from 122?', op: ['Claudius', 'Hadrian', 'Marcus Aurelius', 'Constantine'], certa: 1, exp: 'Hadrian; the wall was about 118 km long.' },
  { p: 'In what language did Marcus Aurelius write his Meditations?', op: ['In Latin', 'In Greek', 'In Hebrew', 'In Etruscan'], certa: 1, exp: 'He wrote them in Greek, for personal use, during the campaigns.' },
  { p: 'Which emperor granted, in 212, Roman citizenship to nearly all free inhabitants of the Empire?', op: ['Caracalla', 'Commodus', 'Diocletian', 'Claudius'], certa: 0, exp: 'The Constitutio Antoniniana, by Caracalla.' },
  { p: 'Which emperor created the Tetrarchy, in 293?', op: ['Aurelian', 'Constantine', 'Diocletian', 'Theodosius'], certa: 2, exp: 'Diocletian, with two augusti and two caesars.' },
  { p: 'In which battle did Constantine defeat his rival Maxentius, in 312?', op: ['Actium', 'Adrianople', 'Milvian Bridge', 'Pharsalus'], certa: 2, exp: 'On 28 October 312, at the gates of Rome.' },
  { p: 'What is the traditional date of Julius Caesar’s assassination?', op: ['15 March 44 BC', '9 August 48 BC', '1 January 27 BC', '7 December 43 BC'], certa: 0, exp: 'The Ides of March; 7 December 43 BC is the death of Cicero.' },
  { p: 'Who wrote the Annals and the Histories, great works on the first emperors?', op: ['Suetonius', 'Tacitus', 'Virgil', 'Pliny the Elder'], certa: 1, exp: 'Tacitus (c. 56 – c. 120).' },
  { p: 'Who described the eruption of Vesuvius of 79 in two letters to Tacitus?', op: ['Pliny the Younger', 'Seneca', 'Suetonius', 'Cicero'], certa: 0, exp: 'Pliny the Younger; his uncle, Pliny the Elder, died at Stabiae.' },
  { p: 'Who was Nero’s philosopher tutor, forced to commit suicide in 65?', op: ['Cicero', 'Seneca', 'Tacitus', 'Cato'], certa: 1, exp: 'Seneca, born in Córdoba, implicated in the Pisonian conspiracy.' },
  { p: 'Which of these popular ideas about the emperors is contradicted by Tacitus, the most cautious source on the fire of 64?', op: ['That Caligula planned to make his horse consul', 'That Nero was in Rome playing the lyre while the city burned', 'That Nero blamed the Christians for the fire', 'That Commodus fought in the arena'], certa: 1, exp: 'Tacitus says Nero was at Antium and returned to organise relief; Suetonius and Dio mention a song during the fire, but the scene of the lyre in Rome is a later elaboration.' }
];

export default { visao, linha, mapa, sociedade, personalidades, legado, quiz };
