// ASSYRIA — full English content. Same structure and same image slots as the Portuguese version (dados.js).
// Dates are approximate, in the "middle chronology". BC = before Christ. For the 1st millennium BC, Assyrian dates are very secure (eponym lists and the solar eclipse of 763 BC); for the 2nd millennium and earlier they are approximate.

const visao = [
  { caixa: 'In brief', texto: [
    '**Assyria** was a kingdom of northern Mesopotamia (today northern Iraq) that grew out of the city of **Ashur**, on the bank of the Tigris, and lasted about 1400 years. It began as a city of merchants sending donkey caravans to Anatolia (c. 2000 BC), became a regional kingdom, and finally, between c. 900 and 612 BC, the **largest empire the world had yet seen**: from Egypt to the Persian Gulf and the mountains of Iran.',
    'It left us one of the great libraries of antiquity (Ashurbanipal’s, at Nineveh), stone reliefs of extraordinary power, the first large-scale imperial administration, and a reputation for cruelty that deserves a careful look: part of it was real, part was royal propaganda, and part comes from the fact that its enemies wrote the history.'
  ] },
  { img: 'asi-mapa-imperio', leg: 'Map of Neo-Assyrian expansion up to the reign of Ashurbanipal, 7th century BCE; approximate extent, French labels.' },
  { h: 'Where it was' },
  'The heart of Assyria was a relatively small territory in **northern Mesopotamia**, along the **Tigris** and its tributaries, the **Greater Zab** and **Lesser Zab** rivers. It is the so-called “Assyrian triangle”, with the cities of **Ashur**, **Nineveh** and **Arbela** (today’s Erbil) at its corners, and **Nimrud** (Kalhu) and **Khorsabad** (Dur-Sharrukin) in between. Today the region lies around Mosul, in Iraq.',
  'Unlike Sumer and Babylonia in the south, Assyrian land receives enough rain (about 300 to 500 mm a year over much of the region) to grow cereals without intensive irrigation. It was a country of farmers and herders, open on every side and without natural frontiers, which helps explain both the Assyrian taste for war and their obsession with defence. It lacked, however, almost everything except wheat and barley: metals, good timber, fine stone. It always had to fetch them from afar, by trade or by conquest.',
  { img: 'asi-paisagem-tigre', leg: 'View of the site of Ashur and the Tigris plain, northern Iraq.' },
  { h: 'When it existed' },
  'Assyrian history is usually divided into three great periods, Old, Middle and Neo-Assyrian, with intervals of weakness between them. The dates follow the “middle chronology” and, for the earliest periods, are approximate.',
  { tabela: { cab: ['Phase', 'Approximate dates', 'What marks it'], linhas: [
    ['Early Ashur', 'c. 2600 – 2025 BC', 'Small city with a temple of Ishtar; dependent on Akkad and then on Ur III'],
    ['Old Assyrian', 'c. 2025 – 1750 BC', 'Independent merchant city-state; trading colonies in Anatolia (Kanesh); Shamshi-Adad I builds a kingdom from the Upper Euphrates to the Zagros (c. 1808 – 1776 BC)'],
    ['Interval', 'c. 1750 – 1365 BC', 'Ashur is a small state, at times under the influence of the kingdom of Mitanni'],
    ['Middle Assyrian', 'c. 1365 – 1050 BC', 'Ashur-uballit I makes Assyria a great power; Tukulti-Ninurta I conquers Babylon; the Late Bronze Age crisis; Tiglath-Pileser I'],
    ['Contraction', 'c. 1050 – 935 BC', 'Pressure from Aramean tribes; the territory shrinks to the Assyrian heartland'],
    ['Neo-Assyrian', '934 – 612 BC', 'Reconquest and then the greatest empire of its day: Ashurnasirpal II, Shalmaneser III, Tiglath-Pileser III, Sargon II, Sennacherib, Esarhaddon, Ashurbanipal'],
    ['Fall', '614 – 609 BC', 'Ashur is sacked (614), Nineveh falls (612), the last remnants resist at Harran (610 – 609)']
  ] } },
  { h: 'Who they were and what language they spoke' },
  'The Assyrians spoke **Assyrian**, a dialect of **Akkadian**, a Semitic language (of the family of Hebrew and Arabic), and wrote it in **cuneiform**, the script inherited from the Sumerians. From the 8th century BC, **Aramaic**, easier to write, spread across the empire and eventually became the everyday language of many people. Culturally, the Assyrians were close relatives of the Babylonians, their neighbours to the south, from whom they inherited religion, literature and science, and with whom they had a relationship of admiration and war for a thousand years.',
  { caixa: 'From Assyria to “Syria”', texto: 'The word **Syria** probably comes from **Assyria**: for centuries the Greeks used the two forms almost as synonyms. A bilingual inscription from Çineköy (Turkey), in Luwian and Phoenician, discovered in 1997, is the strongest argument for this link, now accepted by most specialists.' },
  { h: 'Why they matter' },
  { lista: [
    '**Empire:** they were the first state to govern an enormous territory of different peoples and languages, with provinces, governors, couriers, taxes and a standing army.',
    '**Library:** Ashurbanipal’s library at Nineveh saved thousands of texts of Mesopotamian literature from destruction, among them the Epic of Gilgamesh.',
    '**Art:** the stone reliefs of the palaces, with scenes of war and lion hunting, are among the most remarkable works of ancient art.',
    '**A source for other histories:** Assyrian texts name kings of Israel, Judah, Egypt and dozens of other peoples, and the reliefs show how they dressed and fought.',
    '**A difficult memory:** Assyria became a symbol of violence, in the Bible and then in the Western imagination. Working out what is fact and what is propaganda is part of the interest of the subject.'
  ] },
  { caixa: 'Assyria today', texto: 'The city of **Ashur** has been on the UNESCO World Heritage List since 2003 (and, since then, also on the list of World Heritage in Danger). The great palaces of **Nimrud**, **Khorsabad** and **Nineveh** lie in ruins, and some suffered serious destruction in the 21st century. Today, Syriac-speaking Christian communities live in northern Iraq, Syria, Turkey and Iran, the modern “Assyrians”, who identify with this past; historians debate the question of continuity, but the name and the region remain.' },
  { img: 'asi-disco-alado', leg: 'Winged disc above Ashurnasirpal II on a relief from Nimrud’s Northwest Palace. British Museum.' }
];

const linha = [
  'This timeline follows the main events of Assyrian history. Dates are approximate up to the 9th century BC and very secure after that, thanks to the Assyrian eponym lists and a solar eclipse of 763 BC.',
  { linha: [
    { d: 'c. 2600 BC', t: 'Ashur, a small city on the Tigris', x: 'The city of Ashur already exists, with a temple of Ishtar. For centuries it stays in the shadow of the great powers of the south: Akkad (c. 2334 – 2154 BC) and then the Third Dynasty of Ur, to whom the rulers of Ashur are subordinate.' },
    { d: 'c. 2025 BC', t: 'Ashur becomes independent', x: 'With the collapse of Ur III, Ashur gains autonomy under **Puzur-Ashur I**. The Old Assyrian period begins. The city is governed by a king and by an assembly of citizens, “the City” (*ālum*), and each year is named after an annual magistrate, the *limmum*.' },
    { d: 'c. 1950 – 1840 BC', t: 'The merchants of Kanesh', x: 'Donkey caravans carry tin and textiles from Ashur to Anatolia (over 1000 km away) and bring back silver and gold. The merchants live in districts of their own, the *karum*, of which the most important is **Kanesh** (Kültepe, Turkey). More than 23,000 tablets from this archive have been found, the oldest large-scale commercial documentation in history.' },
    { d: 'c. 1808 – 1776 BC', t: 'Shamshi-Adad I and the first kingdom of “Upper Mesopotamia”', x: 'The Amorite **Shamshi-Adad I** conquers Ashur and creates a kingdom stretching from the Euphrates to the Zagros, with one son ruling at Ekallatum and another at Mari. He takes the title “king of the universe”. He dies c. 1776 BC and the kingdom falls apart soon after.' },
    { d: 'c. 1750 – 1365 BC', t: 'Centuries of modesty', x: 'Ashur survives as a small state, at times under the influence of the kingdom of Mitanni in north-eastern Syria. The Assyrian king list continues, but there is little documentation.' },
    { d: 'c. 1363 – 1328 BC', t: 'Ashur-uballit I: Assyria joins the club of the great powers', x: 'Taking advantage of Mitanni’s weakening, **Ashur-uballit I** writes to the pharaoh of Egypt (the Amarna letters) as to an equal, calling him “brother” and demanding recognition as a “great king”. He marries a daughter to the king of Babylon and intervenes in the succession of that kingdom.' },
    { d: 'c. 1305 – 1244 BC', t: 'Adad-nirari I and Shalmaneser I', x: 'The two kings conquer the territory of Hanigalbat (the former Mitanni), as far as the Euphrates, and make Assyria a kingdom of imperial size, from the Tigris to the Euphrates.' },
    { d: 'c. 1243 – 1207 BC', t: 'Tukulti-Ninurta I conquers Babylon', x: 'He defeats the Hittite king Tudhaliya IV (c. 1237 BC) and, c. 1225 BC, takes Babylon and captures its king, something no Assyrian had done. He founds a new city, **Kar-Tukulti-Ninurta**, but is murdered by his sons c. 1207 BC. An epic in Akkadian celebrates the victory and blames the Babylonian king for breaking his oaths.' },
    { d: 'c. 1200 – 1100 BC', t: 'The Late Bronze Age crisis', x: 'The Hittites disappear, Ugarit is destroyed and Egypt is shaken; Babylonia and Elam weaken. Assyria suffers pressure from Aramean tribes but does not collapse: it is one of the few states in the region to survive, though diminished.' },
    { d: 'c. 1114 – 1076 BC', t: 'Tiglath-Pileser I', x: 'He recovers territory and reaches the Mediterranean, where he kills a “nahiru” (a sea animal) and receives a crocodile and a hippopotamus from Egypt, according to his annals. He assembles a library of tablets at Ashur.' },
    { d: 'c. 1050 – 935 BC', t: 'Contraction', x: 'Drought, famine and Aramean pressure reduce Assyria to its core around Ashur and Nineveh. Documentation almost vanishes. But the state does not dissolve, and the king list continues.' },
    { d: '934 – 891 BC', t: 'The reconquest begins', x: '**Ashur-dan II** and **Adad-nirari II** recover the lost territories, reorganise agriculture and rebuild the army. The Neo-Assyrian period begins.' },
    { d: 'c. 879 BC', t: 'Ashurnasirpal II founds the new capital at Nimrud', x: 'The king turns **Kalhu** (Nimrud) into a capital, with a palace decorated with reliefs. For its inauguration, the king’s stela records a ten-day banquet for about 69,574 guests.' },
    { d: '853 BC', t: 'Battle of Qarqar', x: 'Shalmaneser III faces a coalition of Levantine kings, led by Damascus, including “Ahab of Israel”. The Assyrians claim victory, but the coalition is not destroyed and the Assyrian advance halts for some years.' },
    { d: '841 BC', t: 'The Black Obelisk', x: 'Shalmaneser III receives tribute from **Jehu**, king of Israel, shown kneeling. It is the only known contemporary image of a king of Israel.' },
    { d: 'c. 811 – 806 BC', t: 'The regency of Shammuramat', x: 'Shammuramat, wife of Shamshi-Adad V, governs in the name of her son Adad-nirari III. Greek tradition will make her the legendary “Semiramis”.' },
    { d: '15 June 763 BC', t: 'Solar eclipse', x: 'An eclipse of the Sun, recorded in the Assyrian eponym lists, makes it possible to date every year from the 9th to the 7th century BC with certainty. It is the foundation of the chronology of the whole ancient Near East.' },
    { d: '745 – 727 BC', t: 'Tiglath-Pileser III reforms the empire', x: 'He seizes power at Nimrud and reforms the state: smaller provinces with governors appointed by the king, a standing army, large-scale deportations and tighter vassalage. He conquers Damascus (732 BC) and is crowned king of Babylon (729 BC).' },
    { d: 'c. 722/721 BC', t: 'Fall of Samaria', x: 'After a siege of about three years, the capital of the kingdom of Israel is taken. Shalmaneser V had begun the siege; **Sargon II** claims the conquest and deports, according to his own inscriptions, 27,290 people (a figure that may be inflated). It is the end of the northern kingdom of Israel.' },
    { d: '717 – 705 BC', t: 'Sargon II and Khorsabad', x: 'Sargon II builds a new city, **Dur-Sharrukin** (“Sargon’s Fortress”), inaugurated in 706 BC. The following year he dies in battle in Anatolia and his body is not recovered, a fact that shocks the kingdom.' },
    { d: '701 BC', t: 'Sennacherib, Lachish and Jerusalem', x: 'Sargon’s son marches against a revolt in the Levant. He takes **Lachish**, a fortified city of Judah, and besieges Jerusalem, but does not conquer it: King Hezekiah pays tribute. The Bible, the Assyrian annals and Herodotus tell this story in different ways.' },
    { d: '689 BC', t: 'Destruction of Babylon', x: 'After years of revolt, Sennacherib razes Babylon, an act that shocks the Mesopotamian world and that his son Esarhaddon will later rebuild. Sennacherib makes **Nineveh** the capital and builds there the “Palace Without Rival”.' },
    { d: '681 – 669 BC', t: 'Esarhaddon conquers Egypt', x: 'Sennacherib is assassinated in 681 BC and Esarhaddon wins the civil war. He rebuilds Babylon and, in 671 BC, takes Memphis, making Egypt part of the empire. He dies in 669 BC, on the way to a new Egyptian campaign.' },
    { d: '669 – c. 631 BC', t: 'Ashurbanipal and the Library of Nineveh', x: 'The last great Assyrian king gathers at Nineveh the greatest library of Mesopotamia, of more than 30,000 tablets and fragments. In 663 BC his troops sack Thebes, in Egypt. The date of his death is debated (c. 631 or 627 BC).' },
    { d: '652 – 647 BC', t: 'Civil war and the destruction of Elam', x: 'Ashurbanipal’s brother, king of Babylon, rebels. After a four-year war, Ashurbanipal defeats him and then destroys Susa, the capital of Elam (c. 647 BC). The empire is at its height, but exhausted.' },
    { d: '626 – 614 BC', t: 'The revolt of Babylon and the Medes', x: 'In 626 BC, Nabopolassar, a Chaldean leader, proclaims himself king of Babylon. Ashurbanipal’s successors fight each other. The Medes, allied with the Babylonians, sack **Ashur** in 614 BC.' },
    { d: '612 BC', t: 'Fall of Nineveh', x: 'After a siege of about three months, the Assyrian capital is taken by Babylonians and Medes. King Sin-shar-ishkun dies. The Chronicle of the Fall of Nineveh describes the sack. The Assyrian empire ceases to exist.' },
    { d: '610 – 609 BC', t: 'The last stronghold: Harran', x: 'The prince **Ashur-uballit II** holds out at Harran, in what is today southern Turkey. Harran falls in 610 BC and an attempt to retake it, with Egyptian help, fails in 609 BC. This is the usual date for the end of the Assyrian state.' }
  ] },
  { img: 'asi-tabuinha-kanesh', leg: 'Old Assyrian tablet from Kültepe (Kanesh) and envelope with seal impressions, early 2nd millennium BCE. British Museum.' },
  { img: 'asi-carta-amarna', leg: 'Amarna letter from Shipti-Ba’al of Lachish to the king of Egypt, in Akkadian, 14th century BCE; not one of Ashur-uballit I’s letters EA 15–16. British Museum.' },
  { img: 'asi-obelisco-negro', leg: 'Black Obelisk of Shalmaneser III, c. 825 BCE, including the panel of Jehu. British Museum.' },
  { img: 'asi-estela-zincirli', leg: 'Stele of Esarhaddon from Zincirli, 7th century BCE. Pergamon Museum, Berlin.' },
  { img: 'asi-prisma-taylor', leg: 'Taylor Prism of Sennacherib, c. 691 BCE. British Museum.' },
  { img: 'asi-reconstrucao-ninive', leg: 'Hypothetical panorama of Nineveh under Sennacherib, c. 690 BCE, with palace, walls and irrigated gardens; layout and architectural details are conjectural. AI-generated illustration.' }
];

const mapa = [
  'Assyria was always a country of cities, and almost all the capitals had a role of religion, power and prestige. Moving the capital was the king’s decision, and four kings did so. The most sacred, Ashur, never lost its religious place.',
  { img: 'asi-mapa-cidades', leg: 'Map of Assyrian heartland cities, including Ashur, Kalhu (Nimrud), Dur-Sharrukin (Khorsabad), Nineveh and Arbela; French labels.' },
  { tabela: { cab: ['City', 'Patron god', 'Location today', 'What it is known for'], linhas: [
    ['Ashur', 'Ashur', 'Qal’at Sherqat, Iraq', 'The city-god; cradle and religious centre of Assyria; tombs of the kings; sacked by the Medes in 614 BC'],
    ['Kanesh (Nesa)', '—', 'Kültepe, Turkey', 'Assyrian merchant colony in Anatolia; archive of more than 23,000 tablets'],
    ['Shubat-Enlil', '—', 'Tell Leilan, Syria', 'Capital of Shamshi-Adad I (name of the kingdom: “Upper Mesopotamia”)'],
    ['Kalhu (Nimrud)', 'Ninurta', 'Nimrud, Iraq', 'Capital of Ashurnasirpal II from c. 879 BC; Northwest Palace; ivories; tombs of the queens'],
    ['Dur-Sharrukin', 'various gods', 'Khorsabad, Iraq', 'Capital of Sargon II, c. 717 – 706 BC; city abandoned after his death'],
    ['Nineveh', 'Ishtar', 'Kuyunjik and Nebi Yunus (Mosul), Iraq', 'Capital from Sennacherib to Ashurbanipal; Library of Ashurbanipal; Lachish in the reliefs'],
    ['Arbela', 'Ishtar of Arbela', 'Erbil, Iraq', 'Cult centre of Ishtar and an important city; the citadel has been inhabited for millennia'],
    ['Kar-Tukulti-Ninurta', 'Ashur', 'Tulul al-Aqar, Iraq', 'Short-lived capital of Tukulti-Ninurta I, c. 1230 – 1207 BC'],
    ['Harran', 'Sin', 'Harran, Turkey', 'Last Assyrian stronghold, 610 – 609 BC; city of the Moon god']
  ] } },
  { h: 'Ashur, the city and the god' },
  'Ashur was built on a spur of rock above the Tigris, in a place easy to defend. The name designated at the same time **the city, the territory and the chief god**, and the distinction is hard to make: the Assyrians said “Ashur” for all three. Here stood the great temple of the god, his ziggurat and, in the old palace, the tombs of the kings. Even when the political capital moved to Nimrud, Khorsabad and Nineveh, the kings returned to Ashur to be enthroned and buried. It was excavated by the Germans under Walter Andrae, between 1903 and 1914.',
  { img: 'asi-assur-ruinas', leg: 'Ruins of Ashur (Qal\'at Sherqat), overlooking the Tigris, Iraq.' },
  { img: 'asi-assur-reconstrucao', leg: 'Artistic reconstruction of Ashur overlooking the Tigris, c. 800 BCE, with ziggurat and temple precincts; details are conjectural. AI-generated illustration.' },
  { h: 'Kanesh and the merchant network' },
  'At the beginning of the 2nd millennium BC, the merchants of Ashur created a network of trading “colonies” in central Anatolia. Kanesh, the largest, was a district of Assyrian merchants, the **karum**, next to the local city, and from there letters and contracts went out to the families in Ashur. The excavations, since 1925 (when Bedřich Hrozný discovered the first tablets) and above all since 1948 with Turkish teams, show houses of stone and brick, family archives, seals and a network of smaller trading posts around.',
  { img: 'asi-mercadores-kanesh', leg: 'Imagined Old Assyrian merchant caravan with donkeys, tin and textiles near Kanesh, c. 1900 BCE. AI-generated illustration.' },
  { h: 'Nimrud (Kalhu)' },
  'Kalhu is an old city that Ashurnasirpal II refounded in c. 879 BC as the capital. It had a citadel, the **Northwest Palace**, temples of Ninurta and Nabu, and later the huge “Fort Shalmaneser” (an arsenal and barracks). Excavated by Layard (1845 – 1851) and later by the Briton Max Mallowan (1949 – 1958), it yielded thousands of ivories, reliefs and, in 1988 – 1989, the **tombs of the Assyrian queens** with gold jewellery.',
  { img: 'asi-nimrud-ruinas', leg: 'Relief-bearing wall of Nimrud’s Northwest Palace, photographed in 2008 before the destruction of 2015.' },
  { img: 'asi-reconstrucao-nimrud', leg: 'Hypothetical reconstruction of Nimrud’s citadel under Ashurnasirpal II, 9th century BCE, with ziggurat and lamassu at the palace entrance. AI-generated illustration.' },
  { h: 'Dur-Sharrukin (Khorsabad)' },
  'Sargon II’s city was designed from scratch, on an almost square plan, with seven gates and a palace on a terrace. It was built in only about a decade and, when the king died, it was abandoned. It was here, in 1843, that the Frenchman Paul-Émile Botta discovered the first Assyrian palace, which is why there are so many winged bulls and reliefs from Khorsabad in the Louvre and in Chicago.',
  { img: 'asi-khorsabad-lamassu', leg: 'Lamassu from Sargon II’s palace at Khorsabad. Louvre.' },
  { h: 'Nineveh' },
  'Nineveh was an old cult centre of Ishtar. Sennacherib, c. 700 BC, made it the capital and transformed it: walls of about 12 km, with more than a dozen monumental gates, canals and an aqueduct (at Jerwan, dozens of kilometres away) to bring water, gardens, and the **Palace Without Rival**. Ashurbanipal gathered his library there. Today the ancient city lies inside and beside the modern city of Mosul, on the mounds of Kuyunjik and Nebi Yunus.',
  { img: 'asi-ninive-porta', leg: 'Mashki Gate at Nineveh: modern reconstruction photographed before the destruction of 2015.' },
  { caixa: 'The Hanging Gardens: Nineveh or Babylon?', texto: 'The famous Hanging Gardens have never been found at Babylon. The historian Stephanie Dalley proposed that the legendary gardens were in fact those of Sennacherib at Nineveh, watered by a system of canals and aqueducts that the texts describe. The hypothesis is interesting but **debated**: there is no consensus.' },
  { h: 'The routes of the empire' },
  'Assyria depended on routes: that of **tin** and textiles to Anatolia, in the 2nd millennium; and, in the 1st millennium, the imperial roads that linked the capitals to the provinces, to the Mediterranean, to the Zagros mountains and to Arabia. The **Tigris** served as a river route for timber and stone. The Assyrian kings speak of a **royal road**, maintained with supply stations, which allowed messengers to travel fast. From the Phoenician ports came metals and cedar from Lebanon, which the kings so greatly desired.',
  { img: 'asi-correio-estrada', leg: 'Artistic interpretation of an Assyrian royal messenger on horseback at a relay station, 7th century BCE; clothing and station are conjectural. AI-generated illustration.' }
];

const sociedade = [
  { h: '1. Political organisation and administration' },
  'In the Old Assyrian period, Ashur was governed by an **assembly** of citizens and by a king who was above all a priest and judge. In time, kingship became absolute. In the Neo-Assyrian empire, the king was the supreme head of the state, of war and of religion, but he depended on an elite of high officials, many of them trusted men of varied origin.',
  'Tiglath-Pileser III (745 – 727 BC) and then Sargon II created an imperial administration: the territory was divided into **provinces**, each with a **governor** (appointed by the king, generally one of his trusted men) who collected taxes, recruited soldiers and kept order. States that were not annexed continued as **vassals** that paid tribute and swore loyalty. The system left thousands of letters and reports, the **state archives** of Nineveh and Kalhu, which show a government attentive to detail. Each year was named after a high official, the **eponym** (*limmu*), which today gives us the most secure chronology of antiquity.',
  { img: 'asi-selo-assirio', leg: 'Neo-Assyrian cylinder seal and modern impression, showing a banquet. Louvre, N 8379.' },
  { h: '2. The king and royal ideology' },
  'The Assyrian king was the “vice-regent” (*iššiakku*) of the god Ashur on earth, chosen by the god to extend “Assyrian” territory to the limits of the world and to keep order against chaos. His titles included “king of the universe, king of Assyria”. War was, in this view, a religious duty: each campaign was described as an order of the god. The annals, written for posterity, were carved on palace walls and buried in foundations, and always tell of victories.',
  'The king’s image was carefully built: invincible warrior, lion hunter, builder, pious man, sage. The **lion hunt** was a ritual of kingship: the king protected the country from wild chaos, and lions were brought in cages to be killed in arenas. Ashurbanipal’s reliefs show him doing it. When an omen (an eclipse, for example) threatened the king’s life, a **substitute king** could be appointed, an ordinary person who reigned for a few days and was then put to death, so that the omen would be fulfilled in him and not in the real king. Esarhaddon used this ritual.',
  { img: 'asi-assurnasirpal-genio', leg: 'Ashurnasirpal II and winged genies beside the sacred tree, relief from Nimrud’s Northwest Palace.' },
  { h: '3. The army' },
  'The Assyrian army was the most effective of its time. Over the centuries it combined **infantry** (archers, spearmen, slingers), **chariots**, and from the 9th century BC, **cavalry**. From Tiglath-Pileser III it became **permanent**, with royal units made up of soldiers from all over the empire, and a large foreign contingent. It used **iron weapons** on a large scale and had remarkable logistics: pontoon bridges, inflated skins for crossing rivers, supply, engineers.',
  'Its speciality was **siege warfare**. The reliefs show **battering rams** on wheels, towers, ladders and ramps of earth and stone built up to the walls, all covered with wicker shields. The excavations at Lachish found the remains of one such ramp, one of the few known. The Assyrians also learned to use terrain and to build a network of spies and informants, and the governors’ letters carry reports on enemy movements.',
  { img: 'asi-laquis-cerco', leg: 'Siege of Lachish in reliefs from Nineveh’s Southwest Palace. British Museum.' },
  { img: 'asi-cerco-assirio', leg: 'Artistic reconstruction of an Assyrian siege, c. 700 BCE, with ramp, battering rams and archers, inspired by the Lachish reliefs; not a documented moment. AI-generated illustration.' },
  { img: 'asi-cavalaria-relevo', leg: 'Assyrian horsemen in a relief from Nimrud, 9th century BCE. British Museum; alternative to the requested 7th-century relief.' },
  { h: '4. Deportations and “Assyrian cruelty”' },
  'Mass **deportation** was one of the hallmarks of Assyrian policy. Whole populations of rebel territories were moved to another part of the empire: the inhabitants of Samaria went to Mesopotamia and to Iran, and other peoples were brought in to take their place. The overall figures are uncertain, but according to modern estimates they run to several million people over three centuries. The aim was above all practical: to break the spirit of revolt, to repopulate empty lands and to bring craftsmen and soldiers to the centre. Families travelled together, received rations, and the deportees were often integrated into the economy, even the army. It was not extermination, but it was an experience of brutal rupture.',
  { img: 'asi-laquis-deportados', leg: 'Families deported from Lachish, relief from Nineveh’s Southwest Palace. British Museum.' },
  { caixa: 'Cruelty: propaganda and reality', texto: [
    'The Assyrians left texts and images describing impalement, flaying, mutilation and piles of heads. This is **true in part**: the reliefs of Lachish show impaled prisoners, and letters and treaties also speak of severe punishments, not only propaganda. But three things must be remembered.',
    '**1.** The royal annals were written to impress and to deter. Violence was a language: by celebrating horror, the king told the enemy “surrender”. The number of dead, in particular, is often exaggerated. **2.** The Assyrians preferred, whenever possible, vassalage to destruction: those who paid tribute generally survived, and local kings kept their thrones and their gods. Violence was selective and political, above all against those who had sworn loyalty and betrayed it. **3.** Much of the image we have comes from enemies: the Bible (which condemns Nineveh), the Greeks and the Assyrians’ own official texts, chosen for the glory of the king. Other ancient empires also resorted to exemplary violence, though they rarely celebrated it in such detail.',
    'The historians’ conclusion is nuanced: Assyria was indeed a militarist and brutal empire, **but no more “barbaric” than other states of the time**, and it was at the same time a sophisticated, cultured state with a remarkable administration.'
  ] },
  { h: '5. Social classes' },
  { lista: [
    '**The king and the royal family:** the queen and the king’s mother had great influence, with their own palaces, estates and officials.',
    '**High officials and nobles:** the commander-in-chief (*turtanu*), the chief scribe, the chief cupbearer, governors. Among the officials, those called *ša rēši* (“the one at the head”) are generally translated as “eunuchs”, a term whose exact meaning is debated.',
    '**Free peasants and craftsmen:** the majority of the population; they had obligations of military service and labour for the state.',
    '**Merchants:** important above all in the 2nd millennium, and later in the service of the palace and the temples.',
    '**Deportees and slaves:** prisoners of war and people handed over for debt; deportees were, in general, peasants and craftsmen with a status of dependence.'
  ] },
  { h: '6. Religion' },
  'Assyrian religion was **polytheistic** and inherited much from the religion of Babylonia and Sumer, but with a feature of its own: the national god, **Ashur**, was supreme, the king was his representative and Assyrian policy was his will. The main gods were:',
  { tabela: { cab: ['God', 'Domain', 'City'], linhas: [
    ['Ashur', 'National god; king of the gods, protector of the king and of Assyria', 'Ashur'],
    ['Ishtar', 'Love, war and fertility; Ishtar of Nineveh and Ishtar of Arbela, two important forms', 'Nineveh, Arbela'],
    ['Adad', 'Storm, rain and thunder', 'Ashur, various'],
    ['Sin', 'Moon', 'Harran'],
    ['Shamash', 'Sun and justice', 'Ashur, various'],
    ['Ninurta', 'War and hunting; protector of the warrior king', 'Kalhu (Nimrud)'],
    ['Nabu', 'Writing and wisdom; patron of scribes', 'Kalhu, Nineveh'],
    ['Nergal', 'War, plague, the world of the dead', 'Tarbisu and Nineveh'],
    ['Marduk', 'Chief god of Babylon, respected and contested', 'Babylon']
  ] } },
  'The symbol of the god Ashur was the **winged disc**, sometimes with an archer figure (the identification with Ashur is debated). In religious texts the Assyrian kings identified him with **Anshar**, the ancestor of the gods in the cosmogony, and Sennacherib even altered the poem of creation, the *Enuma Elish*, so that the hero became Ashur instead of the Babylonian Marduk. The great **New Year festival** (*akitu*) celebrated the god and the renewal of the kingdom. Kings consulted the gods through **omens**: the liver of sacrificed animals, the sky, dreams, and the specialists (*bārû*, diviners; *āšipu*, exorcists) wrote reports to the king.',
  { img: 'asi-templo-assur', leg: 'Imagined offerings in a temple of Ashur, 8th century BCE; interior, cult statue, colours and ceremony are conjectural. AI-generated illustration.' },
  { h: 'Life after death' },
  'As in Sumer and Babylonia, the dead went to a gloomy world beneath the earth, ruled by Ereshkigal and Nergal. The Assyrians buried the dead under the floors of houses or in vaults. Kings were buried at Ashur, and the **queens** of Nimrud in brick chambers with stone sarcophagi, with gold jewellery, which came to light in 1988 – 1989. Descendants made offerings of water and food to their ancestors.',
  { img: 'asi-tumba-rainhas-ouro', leg: 'Gold crown from the queens’ Tomb II at Nimrud; documentary photograph made available at low resolution.' },
  { h: '7. Economy and agriculture' },
  'The economy rested on rain-fed agriculture (wheat, barley, sesame, lentils, onions), on raising sheep and horses, and, in the empire, on **tribute** and **plunder**: silver, gold, iron, copper, ivory, timber, horses, textiles and craftsmen arrived from defeated peoples. Sargon II and Sennacherib built canals and aqueducts to irrigate the heart of the country and supply the capitals. Trade included the routes of Arabia (incense), Phoenicia (metals, cedar) and Anatolia (iron, horses). Assyrian weights and measures had their own standard, and silver was used by weight.',
  { img: 'asi-portas-balawat', leg: 'Historical photograph of a bronze band from the Balawat Gates of Shalmaneser III.' },
  { h: '8. Writing, languages and libraries' },
  'Writing was **cuneiform** on clay tablets, in the Assyrian dialect of Akkadian. From the 8th century BC, **Aramaic**, written in an alphabet, on papyrus or hide, became an administrative language; the reliefs often show two scribes side by side, one with a stylus and a tablet and the other with a scroll. Aramaic would end up defeating Akkadian. Learning to write was long and difficult, and scribes formed an elite of great prestige.',
  { img: 'asi-escribas-aramaico', leg: 'Scribes counting booty in a relief from Nineveh’s Southwest Palace, c. 640–620 BCE. British Museum; alternative to the Tiglath-Pileser III relief.' },
  'The **Library of Ashurbanipal**, at Nineveh, is the most famous collection of texts of the ancient world: more than 30,000 tablets and fragments (perhaps some 10,000 different texts, by modern estimates), with literature, hymns, omens, medical texts, treaties, word lists, correspondence. The king had texts copied from all over Mesopotamia, above all from Babylonia, and claimed he could read the ancient texts. Thanks to it, for example, the most complete version of the **Epic of Gilgamesh** has reached us.',
  { img: 'asi-escribas-biblioteca', leg: 'Imagined scribes with cuneiform tablets and scrolls in Nineveh’s royal library, 7th century BCE; furniture and arrangement are conjectural. AI-generated illustration.' },
  { img: 'asi-tabuinha-diluvio', leg: 'Tablet XI of the Epic of Gilgamesh (Flood), from the Library of Ashurbanipal. British Museum.' },
  { h: '9. Post and roads' },
  'The empire stretched over thousands of kilometres, and the king needed to know quickly what was happening. Letters from governors, spies and astrologers reached Nineveh through a network of messengers on horseback and mule, with **relay stations** along the main roads. Letters were closed, generally on clay tablets or in scrolls, and often sealed. Thousands have survived, and they give a day-to-day view of the empire, from military reports to complaints from peasants.',
  { h: '10. Home and family' },
  'Houses were of mud brick, around a courtyard, with a flat roof. In the main cities, wealthy families had houses with several courtyards and rooms. The family was patriarchal. The **Middle Assyrian Laws** (tablets of the 12th – 11th centuries BC, with laws probably older) are harsh on women: they provided for physical punishment by the husband and imposed the **veil** on married women and concubines in public, forbidding it to prostitutes. But in the 2nd millennium the women of Ashur ran textile production and managed the family business while their husbands were in Anatolia, as the Kanesh letters show. Queens held power, and the regent Shammuramat and the queen mother Naqi’a are notable cases.',
  { img: 'asi-casa-assiria', leg: 'Artistic reconstruction of domestic life in an Assyrian courtyard, 7th century BCE, with food preparation and weaving. AI-generated illustration.' },
  { h: '11. Food' },
  'The diet was based on **bread** of wheat and barley, porridges, lentils, chickpeas, onions, garlic, vegetables, cheese, **dates, figs, pomegranates** and **meat** of sheep, goat and fowl, the last above all on the tables of the rich. People drank **beer** and **wine**. The stela of Ashurnasirpal II lists the quantities of food and drink for the Nimrud banquet: thousands of oxen, sheep, ducks, loaves and skins of wine.',
  { img: 'asi-banquete-corte', leg: 'Artistic interpretation of an Assyrian court banquet, 9th century BCE, with king, courtiers, musicians and servants; details are conjectural. AI-generated illustration.' },
  { h: '12. Clothing' },
  'The clothes in the reliefs are one of the best sources. Men and women wore linen or wool tunics down to the knee or ankle, with fringes and embroidery, and cloaks or shawls over them. Soldiers wore pointed helmets of iron or bronze, and a short belted tunic. The king wore a tall hat with a point, the “royal tiara”. Men wore long, curled beards. Jewellery included earrings, bracelets and necklaces.',
  { h: '13. Music and games' },
  'Music was important at court, at banquets and in war. The reliefs show **harps**, lyres, drums and **flutes**, and even singers. In the palaces, as at Khorsabad, there are **game boards** carved into the floor slabs, such as the game of twenty squares.',
  { h: '14. Science, astronomy and medicine' },
  'The Assyrians inherited Mesopotamian science and preserved it. The king’s **astronomers and astrologers** wrote him regular reports on the heavens (eclipses, planets, comets) and their meaning for the kingdom, and many of these reports have reached us. In **medicine**, the library of Nineveh kept the manuals of the specialists: the *asû* (“physician”, who treated with plants and bandages) and the *āšipu* (“exorcist”, who treated with rituals). The distinction between natural and supernatural causes of disease was fluid.',
  { h: '15. Technology' },
  { lista: [
    '**Iron:** used on a large scale in weapons and tools, from the 9th century BC.',
    '**Hydraulic engineering:** canals, and the **Jerwan aqueduct** (c. 690 BC), in limestone, about 280 m long with stone arches, to bring water to Nineveh.',
    '**Military engineering:** ramps, rams, towers, pontoon bridges, skins for crossing rivers.',
    '**Bronze casting:** Sennacherib describes the casting of enormous bronze figures in multi-piece moulds.',
    '**Ivory and glass:** the workshops of Nimrud produced thousands of carved ivories, and glass and glazed bricks of several colours.',
    '**Roads and post:** a rapid communication network across the empire.'
  ] },
  { img: 'asi-marfins-nimrud', leg: 'Woman at the window, ivory found at Nimrud, in Phoenician style. Iraq Museum.' }
];

const personalidades = [
  'Assyrian history is, in large part, the history of its kings, who left long inscriptions and carved their names on the palaces. These are the main figures, with the caveat that almost everything we know comes from official sources.',
  { h: 'Shamshi-Adad I' },
  'Reigned c. 1808 – 1776 BC. He was an Amorite, from outside Ashur. He conquered the city and created a kingdom stretching from the Upper Euphrates to the Zagros, with its capital at Shubat-Enlil (Tell Leilan) and two sons as governors: Ishme-Dagan at Ekallatum and Yasmah-Adad at Mari. The letters in the Mari archive show him scolding his son Yasmah-Adad for being weak. He died c. 1776 BC and the kingdom fell apart.',
  { h: 'Ashur-uballit I' },
  'Reigned c. 1363 – 1328 BC. He wrote to the pharaoh (the Amarna letters) to ask for gold and to claim for Assyria the status of a “great kingdom”. He took advantage of the fall of the kingdom of Mitanni to gain territory and, with it, began the Middle Assyrian period. Tradition considered him the founder of Assyria as a great power.',
  { h: 'Tukulti-Ninurta I' },
  'Reigned c. 1243 – 1207 BC. He defeated the Hittites, conquered Babylon and took the Babylonian king prisoner. He founded a new capital, Kar-Tukulti-Ninurta, and was murdered by his sons. An epic in Akkadian celebrates him, but the same work shows the gods abandoning Babylon because of its sins, a way of justifying the attack.',
  { h: 'Tiglath-Pileser I' },
  'Reigned c. 1114 – 1076 BC. He recovered territory, reached the Mediterranean and Anatolia, and proclaimed himself a great hunter: the annals say he killed 120 lions on foot and 800 from his chariot. After his death Assyria entered a phase of contraction.',
  { h: 'Ashurnasirpal II' },
  'Reigned 883 – 859 BC. He rebuilt Assyria and made Nimrud the capital, where he built the Northwest Palace, decorated with stone reliefs bearing the same repeated inscription (the “Standard Inscription”). His annals describe a policy of extreme terror against rebels, and also the opening of gardens and the inauguration banquet. He was the first of the great kings of the Neo-Assyrian empire.',
  { img: 'asi-assurnasirpal-estela', leg: 'Stele of Ashurnasirpal II from Nimrud. British Museum.' },
  { h: 'Shalmaneser III' },
  'Reigned 858 – 824 BC. He made more than thirty campaigns, and his long struggle against Damascus was documented on the Black Obelisk and the Balawat Gates. His texts mention Ahab and Jehu, kings of Israel. He ended his reign in a civil war provoked by one of his sons.',
  { h: 'Shammuramat (Semiramis)' },
  'She was regent c. 811 – 806 BC, in the name of her son Adad-nirari III, and is the **only woman** known to have acted as regent in Assyria (her formal status as regent is debated). A stela of Shammuramat was erected at Ashur. Greece made of her the legendary “Semiramis”, a warrior and builder queen, in stories with little truth and much fantasy.',
  { img: 'asi-shammuramat-estela', leg: 'Stele of Shammuramat from Ashur, c. 809 BCE. Pergamon Museum, Berlin.' },
  { h: 'Tiglath-Pileser III' },
  'Reigned 745 – 727 BC. He was the founder of the Neo-Assyrian empire as we know it. He reformed the army and administration, created provinces with appointed governors, deported populations and was crowned king of Babylon. For many historians he is the most important king of Assyria.',
  { img: 'asi-tiglat-pileser-iii', leg: 'Tiglath-Pileser III in his chariot, relief from Nimrud. British Museum.' },
  { h: 'Sargon II' },
  'Reigned 722 – 705 BC. His name (*Šarru-kīn*, “the king is legitimate”) suggests he came to the throne by unclear means. He reorganised the army, defeated the Urartians, occupied Babylon and founded Dur-Sharrukin. He died in battle, far from home, in Anatolia, and the Assyrians saw in this a bad omen. His palace at Khorsabad gave the Louvre the first great ensemble of Assyrian art.',
  { img: 'asi-sargao-ii-relevo', leg: 'Sargon II with a high official, relief from Khorsabad. Louvre.' },
  { h: 'Sennacherib' },
  'Reigned 704 – 681 BC. He made Nineveh the capital and built the Palace Without Rival. He attacked Judah in 701 BC, destroyed Babylon in 689 BC, and was assassinated by one of his sons. The reliefs of the siege of Lachish, in his palace, show him seated on a campaign throne before the captured city.',
  { img: 'asi-senaqueribe-laquis', leg: 'Sennacherib enthroned, receiving the spoils of Lachish. British Museum.' },
  { h: 'Naqi’a (Zakutu)' },
  'She was the wife of Sennacherib and the mother of Esarhaddon, and one of the most powerful women in Assyria. Her Aramaic name, Zakutu, appears in texts. Around 669 BC, after Esarhaddon’s death, she had the princes and the great men of the kingdom swear loyalty to Ashurbanipal, her grandson, as king. She is a good example of the power of Assyrian queens.',
  { h: 'Esarhaddon' },
  'Reigned 681 – 669 BC. He won the civil war after his father’s assassination, rebuilt the Babylon his father had razed and conquered Egypt in 671 BC. He lived obsessed with omens and illnesses, and used the substitute king. In 672 BC he made the kingdom swear loyalty, in a “succession treaty”, to his two sons: Ashurbanipal in Assyria and Shamash-shum-ukin in Babylon.',
  { h: 'Ashurbanipal' },
  'Reigned 669 – c. 631 BC. He was educated as a future king and, unlike many kings, learned to read and write: he boasted of it. He had the library of Nineveh assembled, defeated Egypt, Elam and his rebel brother, and left the finest lion-hunt reliefs. His long reign was the height and the beginning of the end of the empire, exhausted by constant wars.',
  { img: 'asi-jardim-assurbanipal', leg: 'Ashurbanipal’s Garden Party, relief from Nineveh. British Museum.' }
];

const legado = [
  { h: 'What they left us' },
  { lista: [
    '**The library:** Ashurbanipal’s collection saved Mesopotamian literature, including Gilgamesh, for the modern world.',
    '**The empire:** the model of provinces, governors, couriers and standing armies was inherited by the Babylonians and the Persians.',
    '**Aramaic:** the language the Assyrians spread across the Near East became the language of the Persian empire and, later, the language of Jesus.',
    '**Chronology:** the eponyms and the eclipse of 763 BC are the backbone of the chronology of the ancient Near East.',
    '**The Bible:** Assyrian accounts intersect with the books of Kings, Isaiah and Nahum, and give dates and names that allow the history of Israel and Judah to be reconstructed.',
    '**Art:** the stone reliefs are among the most expressive works of ancient art, and the figure of the winged bull became an icon.'
  ] },
  { h: 'Art' },
  'Assyrian art is an art of the **palace**. The walls of the rooms were covered with slabs of limestone and gypsum alabaster with reliefs about 2 m high, painted, showing the king at war, hunting, in ceremony, and winged genies protecting the house. At the gateways, the **lamassu** (winged bulls or lions with human heads) guarded the entrance, and had **five legs**, so as to appear standing still seen from the front and walking seen from the side. Ashurbanipal’s hunting scene (c. 645 – 635 BC) shows wounded animals with a realism rare in ancient art, and the “wounded lioness” is one of the most famous works.',
  { img: 'asi-caca-leao', leg: 'Lion Hunt of Ashurbanipal, relief from Nineveh’s North Palace. British Museum.' },
  { img: 'asi-leoa-ferida', leg: 'Dead or wounded lions and lioness, Lion Hunt relief of Ashurbanipal, c. 645–635 BCE. British Museum.' },
  { h: 'Architecture' },
  'Assyrian palaces were enormous complexes of mud brick, with reception halls, courtyards, offices, archives and living quarters, built on raised terraces. The great religious buildings included **ziggurats**, as at Ashur and Nimrud. The cities had imposing walls and monumental gates, and were planned with streets, canals and gardens.',
  { h: 'The rediscovery of Assyria' },
  'For more than two thousand years, Assyria was known only from the Bible and the Greeks. The mounds where Nineveh and Nimrud stood were anonymous heaps of earth. The rediscovery was the work of the 19th century, and it had a less attractive side: many finds were taken to European museums without much respect for the local inhabitants.',
  { linha: [
    { d: '1820', t: 'Claudius Rich at Nineveh', x: 'The Briton Claudius James Rich, East India Company resident in Baghdad, visits and measures the mound of Kuyunjik (Nineveh) and collects inscriptions.' },
    { d: '1843', t: 'Botta at Khorsabad', x: 'Paul-Émile Botta, French consul at Mosul, discovers the palace of Sargon II at Khorsabad, the first known Assyrian palace. The Assyrian Museum of the Louvre opens in 1847.' },
    { d: '1845 – 1851', t: 'Layard at Nimrud and Nineveh', x: 'Austen Henry Layard excavates Nimrud (which he believes to be Nineveh) and then Nineveh. He discovers the Black Obelisk in 1846 and sends winged bulls and reliefs to the British Museum, in a difficult transport down the Tigris. He publishes *Nineveh and Its Remains* (1849).' },
    { d: '1853', t: 'Rassam and the North Palace', x: 'Hormuzd Rassam, a Christian Assyrian from Mosul who worked with Layard, discovers Ashurbanipal’s North Palace, with the lion hunt, and a large part of the library. In 1878 he will find the Balawat Gates.' },
    { d: '1857', t: 'Deciphering Akkadian', x: 'Four scholars (Rawlinson, Hincks, Fox Talbot and Oppert) independently translate the same inscription of Tiglath-Pileser I, and the translations agree: Akkadian cuneiform was considered deciphered.' },
    { d: '1872', t: 'George Smith and the flood', x: 'At the British Museum, George Smith reads on a tablet from Nineveh a flood story similar to Noah’s. It was Tablet XI of the Epic of Gilgamesh.' },
    { d: '1903 – 1914', t: 'Andrae at Ashur', x: 'The German Orient Society excavates Ashur under Walter Andrae and reveals the great ziggurat, the temples and the tombs.' },
    { d: '1949 – 1958', t: 'Mallowan at Nimrud', x: 'Max Mallowan (husband of Agatha Christie, who accompanied him) excavates Nimrud and finds thousands of ivories and the inscriptions of Fort Shalmaneser.' },
    { d: '1988 – 1989', t: 'The tombs of the queens', x: 'Iraqi archaeologists find, beneath the Northwest Palace at Nimrud, tombs of Assyrian queens with gold jewellery, among them those of **Yaba** (wife of Tiglath-Pileser III) and **Atalia** (wife of Sargon II).' },
    { d: '2015 – 2016', t: 'The destruction in Iraq', x: 'During the rule of the self-proclaimed Islamic State in Mosul, the Mosul Museum and Nimrud (2015) and the Mashki and Adad gates of Nineveh (2016) were deliberately destroyed. Antiquities were also looted and Khorsabad damaged. Since 2017, Iraqi and international teams have been documenting and restoring what was possible.' }
  ] },
  { img: 'asi-layard', leg: 'Portrait of Austen Henry Layard (1817–1894).' },
  { img: 'asi-transporte-touro', leg: 'Historical engraving of the transport of a winged bull from Nimrud.' },
  { img: 'asi-sala-museu-britanico', leg: 'Assyrian gallery at the British Museum, with lamassu and reliefs.' },
  { img: 'asi-destruicao-2015', leg: 'Cuneiform-inscribed fragment among the rubble at Nimrud, photographed in January 2019 after the destruction of 2015; documentary detail.' },
  { caixa: 'Where to visit', texto: 'The **British Museum** (London) has the largest collection of reliefs from Nimrud and Nineveh, including the Black Obelisk, the Lachish reliefs and Ashurbanipal’s lion hunt. The **Louvre** (Paris) holds the winged bulls of Khorsabad. The **Oriental Institute** of the University of Chicago has a great lamassu from Khorsabad. The **Pergamon Museum** (Berlin) has pieces from Ashur, and the **National Museum of Iraq** (Baghdad) has the jewels of the queens of Nimrud and the largest holding of Assyrian art in its land of origin.' }
];

const quiz = [
  { p: 'Which was the original city of Assyria, which gave its name to the kingdom and to the chief god?', op: ['Nineveh', 'Nimrud', 'Babylon', 'Ashur'], certa: 3, exp: 'Ashur, on the Tigris, was at the same time city, territory and national god.' },
  { p: 'What did Assyrian merchants carry from Ashur to Kanesh, in Anatolia?', op: ['Horses and weapons', 'Tin and textiles', 'Cedar timber', 'Slaves'], certa: 1, exp: 'Assyrian merchants carried tin and textiles and brought back silver and gold.' },
  { p: 'Roughly how many tablets have been found in the archive of Kanesh (Kültepe)?', op: ['About 200', 'About 2000', 'More than 23,000', 'More than 1 million'], certa: 2, exp: 'The merchant archive of Kültepe is one of the greatest sources of ancient economic history.' },
  { p: 'Which Assyrian king wrote to the pharaoh of Egypt as to an equal, in the 14th century BC?', op: ['Ashurnasirpal II', 'Sargon II', 'Ashurbanipal', 'Ashur-uballit I'], certa: 3, exp: 'In the Amarna letters, Ashur-uballit I calls the pharaoh “brother” and asks to be recognised as a great king.' },
  { p: 'Which Assyrian king conquered Babylon around 1225 BC and founded Kar-Tukulti-Ninurta?', op: ['Tukulti-Ninurta I', 'Shamshi-Adad I', 'Sargon II', 'Esarhaddon'], certa: 0, exp: 'Tukulti-Ninurta I took Babylon and was later murdered by his sons.' },
  { p: 'Where did Ashurnasirpal II build his new capital, c. 879 BC?', op: ['At Nimrud (Kalhu)', 'At Nineveh', 'At Khorsabad', 'At Harran'], certa: 0, exp: 'Ashurnasirpal II refounded Kalhu (Nimrud), with the Northwest Palace.' },
  { p: 'Which Assyrian king is shown on the Black Obelisk receiving tribute from Jehu of Israel?', op: ['Tiglath-Pileser III', 'Esarhaddon', 'Shalmaneser III', 'Sennacherib'], certa: 2, exp: 'The Black Obelisk, c. 825 BC, shows Jehu prostrating himself before Shalmaneser III.' },
  { p: 'Which reform of Tiglath-Pileser III was decisive for the empire?', op: ['Abolishing vassals', 'Provinces with governors and a standing army', 'Founding a new religion', 'Banning Aramaic'], certa: 1, exp: 'Tiglath-Pileser III created provinces with appointed governors and a standing army.' },
  { p: 'Which king founded Dur-Sharrukin (Khorsabad) and died in battle, his body never recovered?', op: ['Sennacherib', 'Tukulti-Ninurta I', 'Ashurbanipal', 'Sargon II'], certa: 3, exp: 'Sargon II founded the city and died on campaign, in Anatolia, in 705 BC.' },
  { p: 'What happened to Jerusalem in Sennacherib’s campaign of 701 BC?', op: ['It was totally destroyed', 'It was taken and the king carried off to Nineveh', 'It was besieged but not conquered: King Hezekiah paid tribute', 'It was not attacked'], certa: 2, exp: 'Sennacherib took Lachish and besieged Jerusalem, but the city was not taken. The accounts differ on the reason.' },
  { p: 'Where were the famous reliefs of the siege of Lachish found?', op: ['In the temple of Ashur', 'In Babylon', 'In Sennacherib’s palace at Nineveh', 'In Persepolis'], certa: 2, exp: 'The reliefs of the Southwest Palace at Nineveh are today in the British Museum.' },
  { p: 'What was the famous collection assembled by Ashurbanipal at Nineveh?', op: ['An archive of letters to the pharaoh', 'A museum of art', 'A group of statues', 'A library of more than 30,000 tablets and fragments'], certa: 3, exp: 'The Library of Ashurbanipal saved much of Mesopotamian literature, including Gilgamesh.' },
  { p: 'What is the best description of “Assyrian cruelty”?', op: ['Partly real, partly exaggeration of royal propaganda; other empires also used violence', 'A modern invention with no basis', 'A fact with no exaggeration', 'Something that existed only in biblical accounts'], certa: 0, exp: 'There was real violence (impalement, for example), but the annals exaggerate to deter, and the image was shaped by enemies.' },
  { p: 'In what year did Nineveh fall to the Babylonians and Medes?', op: ['722 BC', '689 BC', '612 BC', '539 BC'], certa: 2, exp: 'Nineveh fell in 612 BC; the last Assyrians resisted at Harran until 610 – 609 BC.' },
  { p: 'Who discovered the first Assyrian palace, at Khorsabad, in 1843?', op: ['Austen Henry Layard', 'Paul-Émile Botta', 'Hormuzd Rassam', 'George Smith'], certa: 1, exp: 'Botta, French consul at Mosul, discovered the palace of Sargon II at Khorsabad.' }
];

export default { visao, linha, mapa, sociedade, personalidades, legado, quiz };
