// ASSÍRIA — conteúdo completo em português. A versão inglesa está em dados-en.js (mesma estrutura).
import EN from './dados-en.js';
import CRED from './creditos.js';
// Datas aproximadas, na «cronologia média». a.C. = antes de Cristo. Para o 1.º milénio a.C. as datas assírias são muito seguras (listas de epónimos e eclipse de 763 a.C.); para o 2.º milénio e antes são aproximadas.
// Imagens: cada {img:'id'} procura o ficheiro  assiria/img/id.jpg  (ver IMAGENS_ASSIRIA.md para a lista e os prompts).

const visao = [
  { caixa: 'Em resumo', texto: [
    'A **Assíria** foi um reino do norte da Mesopotâmia (hoje o norte do Iraque) que nasceu da cidade de **Assur**, na margem do Tigre, e que durou cerca de 1400 anos. Foi primeiro uma cidade de mercadores que enviava caravanas de burros até à Anatólia (c. 2000 a.C.), depois um reino regional, e por fim, entre c. 900 e 612 a.C., o **maior império que o mundo tinha visto até então**: do Egito ao Golfo Pérsico e às montanhas do Irão.',
    'Deixou-nos uma das maiores bibliotecas da Antiguidade (a de Assurbanípal, em Nínive), relevos de pedra de uma força extraordinária, a primeira administração imperial de grande escala e uma reputação de crueldade que merece ser olhada com cuidado: parte foi realidade, parte foi propaganda real, e parte vem de os inimigos terem escrito a história.'
  ] },
  { img: 'asi-mapa-imperio', leg: 'Mapa da expansão do Império Neoassírio até ao reinado de Assurbanípal, século VII a.C.; extensão aproximada, legendas em francês.' },
  { h: 'Onde ficava' },
  'O coração da Assíria era um território relativamente pequeno no **norte da Mesopotâmia**, junto ao **Tigre** e aos seus afluentes, os rios **Grande Zab** e **Pequeno Zab**. É o chamado «triângulo assírio», com as cidades de **Assur**, **Nínive** e **Arbela** (a atual Erbil) nos vértices, e **Nimrud** (Calá) e **Khorsabad** (Dur-Sharrukin) pelo meio. Hoje essa região fica à volta de Mossul, no Iraque.',
  'Ao contrário da Suméria e da Babilónia, no sul, a terra assíria recebe chuva suficiente (cerca de 300 a 500 mm por ano em grande parte da região) para cultivar cereais sem irrigação intensiva. Era um país de agricultores e de pastores, aberto a todos os lados e sem fronteiras naturais, o que ajuda a explicar tanto o gosto assírio pela guerra como a sua obsessão com a defesa. Faltava-lhe, porém, quase tudo o que não fosse trigo e cevada: metais, madeira de qualidade, pedra fina. Teve sempre de os ir buscar longe, pelo comércio ou pela conquista.',
  { img: 'asi-paisagem-tigre', leg: 'Vista do sítio de Assur e da planície do Tigre, norte do Iraque.' },
  { h: 'Quando existiu' },
  'A história assíria costuma dividir-se em três grandes períodos, o paleo-assírio, o médio-assírio e o neo-assírio, com os respetivos intervalos de fraqueza. As datas seguem a «cronologia média» e, para os períodos mais antigos, são aproximadas.',
  { tabela: { cab: ['Fase', 'Datas aproximadas', 'O que a marca'], linhas: [
    ['Assur antiga', 'c. 2600 – 2025 a.C.', 'Pequena cidade com templo de Ishtar; depende de Acad e depois de Ur III'],
    ['Paleo-assírio', 'c. 2025 – 1750 a.C.', 'Cidade-estado independente de mercadores; colónias comerciais na Anatólia (Kanesh); Shamshi-Adad I cria um reino do Alto Eufrates ao Zagros (c. 1808 – 1776 a.C.)'],
    ['Intervalo', 'c. 1750 – 1365 a.C.', 'Assur é um estado pequeno, por vezes sob influência do reino de Mitani'],
    ['Médio-assírio', 'c. 1365 – 1050 a.C.', 'Assur-uballit I torna a Assíria uma grande potência; Tukulti-Ninurta I conquista a Babilónia; crise do fim da Idade do Bronze; Tiglat-Pileser I'],
    ['Retração', 'c. 1050 – 935 a.C.', 'Pressão de tribos arameias; o território encolhe para o coração assírio'],
    ['Neo-assírio', '934 – 612 a.C.', 'Reconquista e depois o maior império da época: Assurnasirpal II, Salmanasar III, Tiglat-Pileser III, Sargão II, Senaqueribe, Esarhaddon, Assurbanípal'],
    ['Queda', '614 – 609 a.C.', 'Assur é saqueada (614), Nínive cai (612), os últimos restos resistem em Harran (610 – 609)']
  ] } },
  { h: 'Quem eram e que língua falavam' },
  'Os Assírios falavam **assírio**, um dialeto do **acádio**, língua semita (da família do hebraico e do árabe), e escreviam-no em **cuneiforme**, a escrita herdada dos Sumérios. A partir do século VIII a.C. o **aramaico**, mais simples de escrever, espalhou-se pelo império e acabou por tornar-se a língua do dia a dia de muita gente. Culturalmente, os Assírios eram parentes próximos dos Babilónios, seus vizinhos do sul, de quem herdaram a religião, a literatura e a ciência, e com quem tiveram uma relação de admiração e de guerra durante mil anos.',
  { caixa: 'De Assíria a «Síria»', texto: 'A palavra **Síria** vem provavelmente de **Assíria**: os Gregos usaram durante séculos as duas formas quase como sinónimos. Uma inscrição bilingue de Çineköy (Turquia), em luvita e fenício, descoberta em 1997, é o argumento mais forte para esta ligação, hoje aceite pela maioria dos especialistas.' },
  { h: 'Porque importam' },
  { lista: [
    '**Império:** foram o primeiro estado a governar um território enorme, de povos e línguas diferentes, com províncias, governadores, correios, impostos e um exército permanente.',
    '**Biblioteca:** a biblioteca de Assurbanípal, em Nínive, salvou da destruição milhares de textos da literatura mesopotâmica, entre eles a Epopeia de Gilgamesh.',
    '**Arte:** os relevos de pedra dos palácios, com cenas de guerra e de caça ao leão, são das mais notáveis obras da arte antiga.',
    '**Fonte para outras histórias:** os textos assírios citam pelo nome reis de Israel, de Judá, do Egito e de dezenas de outros povos, e os relevos mostram como eles se vestiam e lutavam.',
    '**Memória difícil:** a Assíria ficou como símbolo de violência, na Bíblia e depois na imaginação ocidental. Perceber o que é facto e o que é propaganda faz parte do interesse do tema.'
  ] },
  { caixa: 'A Assíria hoje', texto: 'A cidade de **Assur** está inscrita desde 2003 na lista do Património Mundial da UNESCO (e, desde essa data, também na lista do património mundial em perigo). Os grandes palácios de **Nimrud**, **Khorsabad** e **Nínive** estão em ruínas, e alguns sofreram destruição grave no século XXI. Hoje vivem no norte do Iraque, na Síria, na Turquia e no Irão comunidades cristãs de língua siríaca, os «Assírios» modernos, que se identificam com este passado; a questão da continuidade é debatida pelos historiadores, mas o nome e a região permanecem.' },
  { img: 'asi-disco-alado', leg: 'Disco alado sobre Assurnasirpal II no relevo do Palácio do Noroeste de Nimrud. Museu Britânico.' }
];

const linha = [
  'Esta linha do tempo segue os acontecimentos principais da história assíria. As datas são aproximadas até ao século IX a.C. e muito seguras a partir daí, graças às listas de epónimos assírias e a um eclipse solar de 763 a.C.',
  { linha: [
    { d: 'c. 2600 a.C.', t: 'Assur, uma pequena cidade no Tigre', x: 'A cidade de Assur já existe, com um templo de Ishtar. Durante séculos fica à sombra dos grandes poderes do sul: Acad (c. 2334 – 2154 a.C.) e depois a Terceira Dinastia de Ur, de quem os governantes de Assur são subordinados.' },
    { d: 'c. 2025 a.C.', t: 'Assur torna-se independente', x: 'Com o colapso de Ur III, Assur ganha autonomia sob **Puzur-Assur I**. Começa o período paleo-assírio. A cidade é governada por um rei e por uma assembleia de cidadãos, a «cidade» (*ālum*), e o ano é designado pelo nome de um magistrado anual, o *limmum*.' },
    { d: 'c. 1950 – 1840 a.C.', t: 'Os mercadores de Kanesh', x: 'Caravanas de burros levam estanho e tecidos de Assur até à Anatólia (a mais de 1000 km) e trazem prata e ouro. Os mercadores vivem em bairros próprios, os *karum*, de que o mais importante é **Kanesh** (Kültepe, Turquia). Mais de 23 000 tabuinhas deste arquivo foram encontradas, e são a mais antiga documentação comercial em grande escala da história.' },
    { d: 'c. 1808 – 1776 a.C.', t: 'Shamshi-Adad I e o primeiro reino da «Alta Mesopotâmia»', x: 'O amorreu **Shamshi-Adad I** conquista Assur e cria um reino que vai do Eufrates ao Zagros, com um filho a governar em Ekallatum e outro em Mari. Adota o título de «rei do universo». Morre c. 1776 a.C. e o reino desfaz-se logo a seguir.' },
    { d: 'c. 1750 – 1365 a.C.', t: 'Séculos de modéstia', x: 'Assur sobrevive como estado pequeno, por vezes sob a influência do reino de Mitani, no nordeste da Síria. A lista de reis assíria continua, mas há pouca documentação.' },
    { d: 'c. 1363 – 1328 a.C.', t: 'Assur-uballit I: a Assíria entra no clube das grandes potências', x: 'Aproveitando o enfraquecimento de Mitani, **Assur-uballit I** escreve ao faraó do Egito (cartas de Amarna) como a um igual, tratando-o por «irmão» e exigindo reconhecimento como «grande rei». Casa uma filha com o rei da Babilónia e intervém na sucessão desse reino.' },
    { d: 'c. 1305 – 1244 a.C.', t: 'Adad-nirari I e Salmanasar I', x: 'Os dois reis conquistam o território de Hanigalbat (o antigo Mitani), até ao Eufrates, e fazem da Assíria um reino de dimensão imperial, do Tigre ao Eufrates.' },
    { d: 'c. 1243 – 1207 a.C.', t: 'Tukulti-Ninurta I conquista a Babilónia', x: 'Vence o rei hitita Tudhaliya IV (c. 1237 a.C.) e, c. 1225 a.C., toma a Babilónia, capturando o rei, o que nenhum assírio tinha feito. Funda uma cidade nova, **Kar-Tukulti-Ninurta**, mas é assassinado pelos filhos c. 1207 a.C. Uma epopeia em acádio celebra a vitória e culpa o rei babilónico de ter quebrado os juramentos.' },
    { d: 'c. 1200 – 1100 a.C.', t: 'A crise do fim da Idade do Bronze', x: 'Os hititas desaparecem, Ugarit é destruída e o Egito é abalado; a Babilónia e Elam enfraquecem. A Assíria sofre a pressão de tribos arameias, mas não colapsa: é um dos poucos estados da região a sobreviver, ainda que diminuído.' },
    { d: 'c. 1114 – 1076 a.C.', t: 'Tiglat-Pileser I', x: 'Reconquista território e chega ao Mediterrâneo, onde mata um «nahiru» (animal marinho) e recebe do Egito um crocodilo e um hipopótamo, segundo os seus anais. Reúne uma biblioteca de tabuinhas em Assur.' },
    { d: 'c. 1050 – 935 a.C.', t: 'Retração', x: 'Seca, fome e a pressão arameia reduzem a Assíria ao seu núcleo à volta de Assur e Nínive. A documentação quase desaparece. Mas o estado não se desfaz, e a lista de reis continua.' },
    { d: '934 – 891 a.C.', t: 'A reconquista começa', x: '**Assur-dan II** e **Adad-nirari II** recuperam os territórios perdidos, reorganizam a agricultura e reconstroem o exército. Começa o período neo-assírio.' },
    { d: 'c. 879 a.C.', t: 'Assurnasirpal II funda a nova capital em Nimrud', x: 'O rei transforma **Calá** (Nimrud) em capital, com palácio decorado por relevos. Para a inauguração, a estela do rei refere um banquete de dez dias para cerca de 69 574 convidados.' },
    { d: '853 a.C.', t: 'Batalha de Qarqar', x: 'Salmanasar III enfrenta uma coligação de reis do Levante, chefiada por Damasco, entre eles «Acab de Israel». Os Assírios proclamam vitória, mas a coligação não é destruída e o avanço assírio pára durante alguns anos.' },
    { d: '841 a.C.', t: 'O Obelisco Negro', x: 'Salmanasar III recebe tributo de **Jeú**, rei de Israel, representado a ajoelhar-se. É a única imagem contemporânea conhecida de um rei de Israel.' },
    { d: 'c. 811 – 806 a.C.', t: 'A regência de Shammuramat', x: 'Shammuramat, mulher de Shamshi-Adad V, governa em nome do filho Adad-nirari III. A tradição grega fará dela a lendária «Semíramis».' },
    { d: '15 de junho de 763 a.C.', t: 'Eclipse solar', x: 'Um eclipse do Sol, registado nas listas de epónimos assírias, permite datar com segurança todos os anos do século IX ao VII a.C. É a base da cronologia de todo o Próximo Oriente antigo.' },
    { d: '745 – 727 a.C.', t: 'Tiglat-Pileser III reforma o império', x: 'Toma o poder em Nimrud e reforma o estado: províncias mais pequenas com governadores nomeados pelo rei, exército permanente, deportações em larga escala e vassalagem mais apertada. Conquista Damasco (732 a.C.) e é coroado rei da Babilónia (729 a.C.).' },
    { d: 'c. 722/721 a.C.', t: 'Queda de Samaria', x: 'Depois de um cerco de cerca de três anos, a capital do reino de Israel é tomada. Salmanasar V iniciara o cerco; **Sargão II** reivindica a conquista e deporta, segundo as suas próprias inscrições, 27 290 pessoas (número que pode estar inflacionado). É o fim do reino do norte de Israel.' },
    { d: '717 – 705 a.C.', t: 'Sargão II e Khorsabad', x: 'Sargão II constrói uma cidade nova, **Dur-Sharrukin** («Fortaleza de Sargão»), inaugurada em 706 a.C. No ano seguinte morre numa batalha na Anatólia e o seu corpo não é recuperado, um facto que choca o reino.' },
    { d: '701 a.C.', t: 'Senaqueribe, Laquis e Jerusalém', x: 'O filho de Sargão marcha contra uma revolta no Levante. Toma **Laquis**, cidade fortificada de Judá, e cerca Jerusalém, mas não a conquista: o rei Ezequias paga tributo. A Bíblia, os anais assírios e Heródoto contam esta história de formas diferentes.' },
    { d: '689 a.C.', t: 'Destruição da Babilónia', x: 'Depois de anos de revolta, Senaqueribe arrasa a Babilónia, um ato que choca o mundo mesopotâmico, que o seu filho Esarhaddon reconstruirá mais tarde. Senaqueribe faz de **Nínive** a capital e constrói ali o «Palácio Sem Rival».' },
    { d: '681 – 669 a.C.', t: 'Esarhaddon conquista o Egito', x: 'Senaqueribe é assassinado em 681 a.C. e Esarhaddon vence a guerra civil. Reconstrói a Babilónia e, em 671 a.C., toma Mênfis, fazendo do Egito parte do império. Morre em 669 a.C., a caminho de uma nova campanha egípcia.' },
    { d: '669 – c. 631 a.C.', t: 'Assurbanípal e a Biblioteca de Nínive', x: 'O último grande rei assírio reúne em Nínive a maior biblioteca da Mesopotâmia, de mais de 30 000 tabuinhas e fragmentos. Em 663 a.C. as suas tropas saqueiam Tebas, no Egito. A data da sua morte é debatida (c. 631 ou 627 a.C.).' },
    { d: '652 – 647 a.C.', t: 'Guerra civil e destruição de Elam', x: 'O irmão de Assurbanípal, rei da Babilónia, revolta-se. Depois de uma guerra de quatro anos, Assurbanípal vence-o e, em seguida, destrói Susa, a capital de Elam (c. 647 a.C.). O império está no máximo, mas esgotado.' },
    { d: '626 – 614 a.C.', t: 'A revolta da Babilónia e dos Medos', x: 'Em 626 a.C., Nabopolassar, um chefe caldeu, proclama-se rei da Babilónia. Os sucessores de Assurbanípal lutam entre si. Os Medos, aliados dos Babilónios, saqueiam **Assur** em 614 a.C.' },
    { d: '612 a.C.', t: 'Queda de Nínive', x: 'Depois de um cerco de cerca de três meses, a capital assíria é tomada por Babilónios e Medos. O rei Sin-shar-ishkun morre. A Crónica da Queda de Nínive descreve o saque. O império assírio deixa de existir.' },
    { d: '610 – 609 a.C.', t: 'O último reduto: Harran', x: 'O príncipe **Assur-uballit II** resiste em Harran, no atual sul da Turquia. Harran cai em 610 a.C. e uma tentativa de a retomar, com ajuda egípcia, falha em 609 a.C. É a data habitual do fim do estado assírio.' }
  ] },
  { img: 'asi-tabuinha-kanesh', leg: 'Tabuinha paleoassíria de Kültepe (Kanesh) e envelope com impressões de selos, início do II milénio a.C. Museu Britânico.' },
  { img: 'asi-carta-amarna', leg: 'Carta de Amarna de Shipti-Ba’al de Laquis ao rei do Egito, em acádio, século XIV a.C.; não é uma das cartas EA 15–16 de Assur-uballit I. Museu Britânico.' },
  { img: 'asi-obelisco-negro', leg: 'Obelisco Negro de Salmanasar III, c. 825 a.C., com o painel de Jeú. Museu Britânico.' },
  { img: 'asi-estela-zincirli', leg: 'Estela de Esarhaddon de Zincirli, século VII a.C. Museu de Pérgamo, Berlim.' },
  { img: 'asi-prisma-taylor', leg: 'Prisma de Taylor de Senaqueribe, c. 691 a.C. Museu Britânico.' },
  { img: 'asi-reconstrucao-ninive', leg: 'Panorama hipotético de Nínive no reinado de Senaqueribe, c. 690 a.C., com palácio, muralhas e jardins irrigados; disposição e pormenores arquitetónicos conjeturais. Ilustração gerada por IA.' }
];

const mapa = [
  'A Assíria foi sempre um país de cidades, e quase todas as capitais tiveram um papel de religião, de poder e de prestígio. Mudar de capital era uma decisão do rei, e quatro reis fizeram-no. A mais sagrada, Assur, nunca perdeu o seu lugar religioso.',
  { img: 'asi-mapa-cidades', leg: 'Mapa das cidades do coração assírio, incluindo Assur, Kalhu (Nimrud), Dur-Sharrukin (Khorsabad), Nínive e Arbela; legendas em francês.' },
  { tabela: { cab: ['Cidade', 'Deus protetor', 'Local hoje', 'Para que ficou conhecida'], linhas: [
    ['Assur', 'Assur', 'Qal’at Sherqat, Iraque', 'A cidade-deus; berço e centro religioso da Assíria; tumbas dos reis; sacada pelos Medos em 614 a.C.'],
    ['Kanesh (Nesa)', '—', 'Kültepe, Turquia', 'Colónia mercantil assíria na Anatólia; arquivo de mais de 23 000 tabuinhas'],
    ['Shubat-Enlil', '—', 'Tell Leilan, Síria', 'Capital de Shamshi-Adad I (nome do reino: «Alta Mesopotâmia»)'],
    ['Calá (Nimrud)', 'Ninurta', 'Nimrud, Iraque', 'Capital de Assurnasirpal II em c. 879 a.C.; Palácio do Noroeste; marfins; tumbas das rainhas'],
    ['Dur-Sharrukin', 'vários deuses', 'Khorsabad, Iraque', 'Capital de Sargão II, c. 717 – 706 a.C.; cidade abandonada depois da sua morte'],
    ['Nínive', 'Ishtar', 'Kuyunjik e Nebi Yunus (Mossul), Iraque', 'Capital de Senaqueribe a Assurbanípal; Biblioteca de Assurbanípal; Laquis nos relevos'],
    ['Arbela', 'Ishtar de Arbela', 'Erbil, Iraque', 'Centro de culto de Ishtar e cidade importante; a cidadela está habitada desde há milénios'],
    ['Kar-Tukulti-Ninurta', 'Assur', 'Tulul al-Aqar, Iraque', 'Capital efémera de Tukulti-Ninurta I, c. 1230 – 1207 a.C.'],
    ['Harran', 'Sin', 'Harran, Turquia', 'Último reduto assírio, 610 – 609 a.C.; cidade do deus Lua']
  ] } },
  { h: 'Assur, a cidade e o deus' },
  'Assur foi construída num esporão de rocha por cima do Tigre, num lugar fácil de defender. O nome designava ao mesmo tempo **a cidade, o território e o deus principal**, e a distinção não é fácil de fazer: os Assírios diziam «Assur» para tudo. Aqui estavam o grande templo do deus, o seu zigurate e, no palácio antigo, as tumbas dos reis. Mesmo quando a capital política passou para Nimrud, Khorsabad e Nínive, os reis voltavam a Assur para serem entronizados e enterrados. Foi escavada pelos alemães de Walter Andrae, entre 1903 e 1914.',
  { img: 'asi-assur-ruinas', leg: 'Ruínas de Assur (Qal\'at Sherqat), sobre o Tigre, Iraque.' },
  { img: 'asi-assur-reconstrucao', leg: 'Reconstrução artística de Assur sobre o Tigre, c. 800 a.C., com zigurate e recintos de templos; pormenores conjeturais. Ilustração gerada por IA.' },
  { h: 'Kanesh e a rede de mercadores' },
  'No início do 2.º milénio a.C., os mercadores de Assur criaram uma rede de «colónias» comerciais na Anatólia central. Kanesh, o maior, era um bairro de mercadores assírios, o **karum**, ao lado da cidade local, e de lá saíam cartas e contratos para as famílias de Assur. As escavações, desde 1925 (quando Bedřich Hrozný descobriu as primeiras tabuinhas) e sobretudo desde 1948 com equipas turcas, mostram casas de pedra e tijolo, arquivos familiares, selos e uma rede de postos comerciais mais pequenos à volta.',
  { img: 'asi-mercadores-kanesh', leg: 'Cena imaginada de uma caravana de mercadores paleoassírios com burros, estanho e tecidos, junto de Kanesh, c. 1900 a.C. Ilustração gerada por IA.' },
  { h: 'Nimrud (Calá)' },
  'Calá é uma cidade antiga que Assurnasirpal II refundou em c. 879 a.C. como capital. Tinha uma cidadela, o **Palácio do Noroeste**, templos de Ninurta e Nabu, e mais tarde o enorme «Forte de Salmanasar» (um arsenal e quartel). Escavada por Layard (1845 – 1851) e depois pelo britânico Max Mallowan (1949 – 1958), forneceu milhares de marfins, relevos e, em 1988 – 1989, as **tumbas das rainhas assírias** com joias de ouro.',
  { img: 'asi-nimrud-ruinas', leg: 'Parede com relevos do Palácio do Noroeste de Nimrud, fotografada em 2008, antes da destruição de 2015.' },
  { img: 'asi-reconstrucao-nimrud', leg: 'Reconstrução hipotética da cidadela de Nimrud no reinado de Assurnasirpal II, século IX a.C., com zigurate e lamassu à entrada do palácio. Ilustração gerada por IA.' },
  { h: 'Dur-Sharrukin (Khorsabad)' },
  'A cidade de Sargão II foi desenhada de raiz, num plano quase quadrado, com sete portas e um palácio sobre um terraço. Foi construída em apenas cerca de uma década e, quando o rei morreu, foi abandonada. Foi aqui, em 1843, que o francês Paul-Émile Botta descobriu o primeiro palácio assírio, e é por isso que há tantos touros alados e relevos de Khorsabad no Louvre e em Chicago.',
  { img: 'asi-khorsabad-lamassu', leg: 'Lamassu do palácio de Sargão II em Khorsabad. Louvre.' },
  { h: 'Nínive' },
  'Nínive era um velho centro de culto de Ishtar. Senaqueribe, c. 700 a.C., fez dela capital e transformou-a: muralhas de cerca de 12 km, com mais de uma dezena de portas monumentais, canais e um aqueduto (em Jerwan, a dezenas de quilómetros) para trazer água, jardins, e o **Palácio Sem Rival**. Assurbanípal juntou ali a sua biblioteca. Hoje a cidade antiga está dentro e ao lado da cidade moderna de Mossul, nos montes de Kuyunjik e Nebi Yunus.',
  { img: 'asi-ninive-porta', leg: 'Porta de Mashki de Nínive: reconstrução moderna fotografada antes da destruição de 2015.' },
  { caixa: 'Os Jardins Suspensos: Nínive ou Babilónia?', texto: 'Os célebres Jardins Suspensos nunca foram encontrados na Babilónia. A historiadora Stephanie Dalley propôs que os jardins lendários eram, na verdade, os de Senaqueribe, em Nínive, regados por um sistema de canais e aquedutos que os textos descrevem. A hipótese é interessante, mas **debatida**: não há consenso.' },
  { h: 'As rotas do império' },
  'A Assíria dependia de rotas: a do **estanho** e dos tecidos até à Anatólia, no 2.º milénio; e, no 1.º milénio, as estradas imperiais que ligavam as capitais às províncias, ao Mediterrâneo, às montanhas do Zagros e à Arábia. O **Tigre** servia de rota fluvial para madeira e para pedra. Os reis assírios falam de uma **estrada real**, mantida com postos de abastecimento, que permitia aos mensageiros viajar depressa. Dos portos fenícios chegavam metais e madeira de cedro do Líbano, que os reis tanto desejavam.',
  { img: 'asi-correio-estrada', leg: 'Interpretação artística de um mensageiro real assírio a cavalo junto de uma estação de muda, século VII a.C.; vestuário e estação conjeturais. Ilustração gerada por IA.' }
];

const sociedade = [
  { h: '1. Organização política e administração' },
  'Na época paleo-assíria, Assur era governada por uma **assembleia** de cidadãos e por um rei que era sobretudo um sacerdote e juiz. Com o tempo, a realeza tornou-se absoluta. No império neo-assírio, o rei era o chefe supremo do estado, da guerra e da religião, mas dependia de uma elite de altos funcionários, muitos deles de confiança e de origem diversa.',
  'Tiglat-Pileser III (745 – 727 a.C.) e depois Sargão II criaram uma administração imperial: o território foi dividido em **províncias**, cada uma com um **governador** (nomeado pelo rei, em geral um dos seus homens de confiança) que cobrava impostos, recrutava soldados e mantinha a ordem. Os estados que não eram anexados continuavam como **vassalos** que pagavam tributo e juravam lealdade. O sistema deixou milhares de cartas e relatórios, os **arquivos de estado** de Nínive e Calá, que mostram um governo atento aos pormenores. Cada ano era designado pelo nome de um alto funcionário, o **epónimo** (*limmu*), o que permite hoje a cronologia mais segura da Antiguidade.',
  { img: 'asi-selo-assirio', leg: 'Selo cilíndrico neoassírio e impressão moderna, com cena de banquete. Louvre, N 8379.' },
  { h: '2. O rei e a ideologia real' },
  'O rei assírio era o «vice-regente» (*iššiakku*) do deus Assur na terra, escolhido pelo deus para estender o território «assírio» até aos limites do mundo e para manter a ordem contra o caos. Os seus títulos incluíam «rei do universo, rei da Assíria». A guerra era, nesta ideia, um dever religioso: cada campanha era descrita como uma ordem do deus. Os anais, escritos para a posteridade, eram gravados nas paredes dos palácios e enterrados nos alicerces, e contam sempre vitórias.',
  'A imagem do rei era cuidadosamente construída: guerreiro invencível, caçador de leões, construtor, piedoso, sábio. A **caça ao leão** era um ritual de realeza: o rei protegia o país do caos selvagem, e os leões eram trazidos em jaulas para serem mortos em arenas. Os relevos de Assurbanípal mostram-no a fazê-lo. Quando um presságio (um eclipse, por exemplo) ameaçava a vida do rei, podia ser nomeado um **rei substituto**, uma pessoa comum que reinava por uns dias e depois era morta, para que o presságio se cumprisse nele e não no verdadeiro rei. Esarhaddon recorreu a este ritual.',
  { img: 'asi-assurnasirpal-genio', leg: 'Assurnasirpal II e génios alados junto à árvore sagrada, relevo do Palácio do Noroeste de Nimrud.' },
  { h: '3. O exército' },
  'O exército assírio foi o mais eficaz da sua época. Ao longo dos séculos, combinou **infantaria** (arqueiros, lanceiros, fundibulários), **carros de combate**, e a partir do século IX a.C., **cavalaria**. A partir de Tiglat-Pileser III tornou-se **permanente**, com unidades do rei compostas por soldados de todo o império, e com um grande contingente de estrangeiros. Usou **armas de ferro** em larga escala e uma logística notável: pontes de barcos, odres cheios de ar para atravessar rios, intendência, engenheiros.',
  'A sua especialidade foi a **guerra de cerco**. Os relevos mostram **aríetes** sobre rodas, torres, escadas e rampas de terra e pedra construídas até às muralhas, tudo coberto de escudos de vime. As escavações em Laquis encontraram os restos de uma dessas rampas, uma das poucas conhecidas. Os Assírios aprenderam também a usar o terreno e a construir uma rede de espiões e de informadores, e as cartas dos governadores trazem relatórios sobre os movimentos do inimigo.',
  { img: 'asi-laquis-cerco', leg: 'Cerco de Laquis nos relevos do Palácio Sudoeste de Nínive. Museu Britânico.' },
  { img: 'asi-cerco-assirio', leg: 'Reconstrução artística de um cerco assírio, c. 700 a.C., com rampa, aríetes e arqueiros, inspirada nos relevos de Laquis; não representa um momento documentado. Ilustração gerada por IA.' },
  { img: 'asi-cavalaria-relevo', leg: 'Cavaleiros assírios em relevo de Nimrud, século IX a.C. Museu Britânico; alternativa ao relevo do século VII pedido.' },
  { h: '4. Deportações e a «crueldade assíria»' },
  'A **deportação** em massa foi uma das marcas da política assíria. Populações inteiras de territórios rebeldes eram transferidas para outro ponto do império: os habitantes de Samaria foram para a Mesopotâmia e para o Irão, e outros povos foram trazidos para o seu lugar. As cifras totais são incertas, mas rondam, segundo estimativas modernas, vários milhões de pessoas ao longo de três séculos. O objetivo era sobretudo prático: quebrar o espírito de revolta, repovoar terras desertas e trazer artesãos e soldados para o centro. As famílias viajavam juntas, recebiam rações, e os deportados eram muitas vezes integrados na economia, até no exército. Não se tratava de um extermínio, mas era uma experiência de rutura brutal.',
  { img: 'asi-laquis-deportados', leg: 'Famílias deportadas de Laquis, relevo do Palácio Sudoeste de Nínive. Museu Britânico.' },
  { caixa: 'Crueldade: propaganda e realidade', texto: [
    'Os Assírios deixaram textos e imagens que descrevem empalamentos, esfolamentos, mutilações e pilhas de cabeças. Isto é **verdade em parte**: os relevos de Laquis mostram prisioneiros empalados, e as cartas e os tratados falam também de castigos severos, não apenas a propaganda. Mas é preciso lembrar três coisas.',
    '**1.** Os anais reais foram escritos para impressionar e para dissuadir. A violência era uma linguagem: ao celebrar o horror, o rei dizia ao inimigo «rende-te». O número de mortos, em especial, é muitas vezes exagerado. **2.** Os Assírios preferiam, sempre que possível, a vassalagem a destruir: quem pagava tributo, geralmente sobrevivia, e os reis locais mantinham os seus tronos e os seus deuses. A violência era seletiva e política, sobretudo contra quem tinha jurado lealdade e traiu. **3.** Muito da imagem que temos vem dos inimigos: a Bíblia (que condena Nínive), os Gregos e os próprios textos oficiais assírios, escolhidos para a glória do rei. Outros impérios antigos também recorreram à violência exemplar, ainda que raramente a celebrassem com tanto pormenor.',
    'A conclusão dos historiadores é matizada: a Assíria foi de facto um império militarista e brutal, **mas não mais «bárbara» do que outros estados da época**, e foi ao mesmo tempo um estado sofisticado, culto, com uma administração notável.'
  ] },
  { h: '5. Classes sociais' },
  { lista: [
    '**O rei e a família real:** a rainha e a mãe do rei tinham grande influência, com palácios, propriedades e funcionários próprios.',
    '**Altos funcionários e nobres:** o comandante supremo (*turtanu*), o chefe dos escribas, o copeiro-mor, governadores. Entre os funcionários, os chamados *ša rēši* («os da cabeça») são geralmente traduzidos como «eunucos», um termo cujo sentido exato é debatido.',
    '**Camponeses e artesãos livres:** a maioria da população; tinham obrigação de serviço militar e de trabalho para o estado.',
    '**Mercadores:** importantes sobretudo no 2.º milénio, e depois ao serviço do palácio e dos templos.',
    '**Deportados e escravos:** prisioneiros de guerra e pessoas entregues por dívidas; os deportados eram, em geral, camponeses e artesãos com um estatuto de dependência.'
  ] },
  { h: '6. Religião' },
  'A religião assíria era **politeísta** e herdou muito da religião da Babilónia e da Suméria, mas com uma característica própria: o deus nacional, **Assur**, era supremo, o rei era o seu representante e a política assíria era a sua vontade. Os principais deuses eram:',
  { tabela: { cab: ['Deus', 'Domínio', 'Cidade'], linhas: [
    ['Assur', 'Deus nacional; rei dos deuses, protetor do rei e da Assíria', 'Assur'],
    ['Ishtar', 'Amor, guerra e fertilidade; Ishtar de Nínive e Ishtar de Arbela, duas formas importantes', 'Nínive, Arbela'],
    ['Adad', 'Tempestade, chuva e trovão', 'Assur, vários'],
    ['Sin', 'Lua', 'Harran'],
    ['Shamash', 'Sol e justiça', 'Assur, vários'],
    ['Ninurta', 'Guerra e caça; protetor do rei guerreiro', 'Calá (Nimrud)'],
    ['Nabu', 'Escrita e sabedoria; patrono dos escribas', 'Calá, Nínive'],
    ['Nergal', 'Guerra, peste, mundo dos mortos', 'Tarbisu e Nínive'],
    ['Marduk', 'Deus principal da Babilónia, respeitado e disputado', 'Babilónia']
  ] } },
  'O símbolo do deus Assur era o **disco alado**, por vezes com uma figura de arqueiro (a identificação com Assur é debatida). Os reis assírios identificaram-no, nos textos religiosos, com **Anshar**, o ancestral dos deuses da cosmogonia, e Senaqueribe chegou a alterar o poema da criação, o *Enuma Elish*, para que o herói passasse a ser Assur em vez do babilónico Marduk. O grande **festival de Ano Novo** (*akitu*) celebrava o deus e a renovação do reino. Os reis consultavam os deuses por **presságios**: o fígado de animais sacrificados, o céu, os sonhos, e os especialistas (*bārû*, adivinhos; *āšipu*, exorcistas) escreviam relatórios ao rei.',
  { img: 'asi-templo-assur', leg: 'Cena imaginada de oferendas num templo de Assur, século VIII a.C.; interior, estátua de culto, cores e cerimónia conjeturais. Ilustração gerada por IA.' },
  { h: 'A vida depois da morte' },
  'Como na Suméria e na Babilónia, os mortos iam para um mundo sombrio debaixo da terra, governado por Ereshkigal e Nergal. Os Assírios enterravam os mortos sob o chão das casas ou em jazigos. Os reis eram sepultados em Assur, e as **rainhas** de Nimrud em câmaras de tijolo com sarcófagos de pedra, com joias de ouro, que apareceram em 1988 – 1989. Os descendentes faziam oferendas de água e de comida aos antepassados.',
  { img: 'asi-tumba-rainhas-ouro', leg: 'Coroa de ouro da tumba II das rainhas de Nimrud; fotografia documental disponibilizada em baixa resolução.' },
  { h: '7. Economia e agricultura' },
  'A economia assentava na agricultura de sequeiro (trigo, cevada, sésamo, lentilhas, cebolas), na criação de ovelhas e de cavalos, e, no império, no **tributo** e no **saque**: prata, ouro, ferro, cobre, marfim, madeira, cavalos, têxteis e artesãos chegavam dos povos vencidos. Sargão II e Senaqueribe construíram canais e aquedutos para irrigar o coração do país e abastecer as capitais. O comércio incluía as rotas da Arábia (incenso), da Fenícia (metais, cedro) e de Anatólia (ferro, cavalos). Pesos e medidas assírios tinham o seu próprio padrão, e usava-se prata em peso.',
  { img: 'asi-portas-balawat', leg: 'Fotografia histórica de uma banda de bronze das Portas de Balawat, Salmanasar III.' },
  { h: '8. Escrita, línguas e bibliotecas' },
  'A escrita era o **cuneiforme** em tabuinhas de argila, no dialeto assírio do acádio. A partir do século VIII a.C., o **aramaico**, escrito em alfabeto, em papiro ou pele, tornou-se língua administrativa; os relevos mostram frequentemente dois escribas lado a lado, um com um estilete e uma tabuinha e outro com um rolo. O aramaico acabaria por vencer o acádio. Aprender a escrever era longo e difícil, e os escribas formavam uma elite com grande prestígio.',
  { img: 'asi-escribas-aramaico', leg: 'Escribas a contar o butim, num relevo do Palácio Sudoeste de Nínive, c. 640–620 a.C. Museu Britânico; alternativa ao relevo de Tiglat-Pileser III.' },
  'A **Biblioteca de Assurbanípal**, em Nínive, é o mais famoso conjunto de textos do mundo antigo: mais de 30 000 tabuinhas e fragmentos (talvez cerca de 10 000 textos diferentes, segundo estimativas modernas), com literatura, hinos, presságios, textos médicos, tratados, listas de palavras, correspondência. O rei mandou copiar textos de toda a Mesopotâmia, sobretudo da Babilónia, e afirmou saber ler os textos antigos. Graças a ela chegou até nós, por exemplo, a versão mais completa da **Epopeia de Gilgamesh**.',
  { img: 'asi-escribas-biblioteca', leg: 'Cena imaginada de escribas com tabuinhas cuneiformes e rolos na biblioteca real de Nínive, século VII a.C.; mobiliário e organização conjeturais. Ilustração gerada por IA.' },
  { img: 'asi-tabuinha-diluvio', leg: 'Tabuinha XI da Epopeia de Gilgamesh (Dilúvio), da Biblioteca de Assurbanípal. Museu Britânico.' },
  { h: '9. O correio e as estradas' },
  'O império estendia-se por milhares de quilómetros, e o rei precisava de saber, rapidamente, o que se passava. As cartas dos governadores, dos espiões e dos astrólogos chegavam a Nínive por uma rede de mensageiros a cavalo e a mula, com **postos de muda** ao longo das estradas principais. As cartas eram fechadas, em geral em tabuinhas de argila ou em rolos, e muitas vezes seladas. Chegaram até nós milhares, e dão uma visão diária do império, desde relatórios militares a queixas de camponeses.',
  { h: '10. Casa e família' },
  'As casas eram de tijolo cru, em torno de um pátio, com telhado plano. Nas cidades principais, as famílias ricas tinham casas com vários pátios e quartos. A família era patriarcal. As **Leis Médio-Assírias** (tabuinhas dos séculos XII – XI a.C., com leis provavelmente mais antigas) são duras com as mulheres: previam castigos físicos pelo marido e impunham o **véu** às mulheres casadas e às concubinas em público, e proibiam-no às prostitutas. Mas, no 2.º milénio, as mulheres de Assur dirigiam a produção de tecidos e administravam os negócios da família enquanto os maridos estavam na Anatólia, como as cartas de Kanesh mostram. As rainhas tinham poder, e a regente Shammuramat e a rainha-mãe Naqi’a são casos notáveis.',
  { img: 'asi-casa-assiria', leg: 'Reconstrução artística da vida doméstica num pátio assírio, século VII a.C., com preparação de alimentos e tecelagem. Ilustração gerada por IA.' },
  { h: '11. Alimentação' },
  'A dieta baseava-se em **pão** de trigo e de cevada, papas, lentilhas, grão, cebola, alho, legumes, queijo, **tâmaras, figos, romãs** e **carne** de carneiro, cabra e aves, esta última sobretudo à mesa dos ricos. Bebia-se **cerveja** e **vinho**. A estela de Assurnasirpal II lista as quantidades de comida e de bebida do banquete de Nimrud: milhares de bois, de carneiros, de patos, de pães e de odres de vinho.',
  { img: 'asi-banquete-corte', leg: 'Interpretação artística de um banquete da corte assíria, século IX a.C., com rei, cortesãos, músicos e servos; pormenores conjeturais. Ilustração gerada por IA.' },
  { h: '12. Vestuário' },
  'As roupas dos relevos são uma das melhores fontes. Homens e mulheres usavam túnicas de linho ou de lã até ao joelho ou ao tornozelo, com franjas e bordados, e capas ou xailes por cima. Os soldados usavam capacetes pontiagudos de ferro ou de bronze, e uma túnica curta com cinto. O rei usava um chapéu alto com uma ponta, a «tiara real». Os homens usavam barba comprida e frisada. As joias incluíam brincos, braceletes e colares.',
  { h: '13. Música e jogos' },
  'A música era importante na corte, nos banquetes e na guerra. Nos relevos vê-se **harpas**, liras, tambores e **flautas**, e até cantores. Nos palácios, como em Khorsabad, há **tabuleiros de jogo** gravados nas lajes do chão, como o jogo das vinte casas.',
  { h: '14. Ciência, astronomia e medicina' },
  'Os Assírios herdaram a ciência mesopotâmica e preservaram-na. Os **astrónomos e astrólogos** do rei escreviam-lhe relatórios regulares sobre os céus (eclipses, planetas, cometas) e o seu significado para o reino, e muitos desses relatórios chegaram até nós. Na **medicina**, a biblioteca de Nínive guardava os manuais dos especialistas: o *asû* («médico», que tratava com plantas e ligaduras) e o *āšipu* («exorcista», que tratava com rituais). A distinção entre causas naturais e causas sobrenaturais das doenças era fluida.',
  { h: '15. Tecnologia' },
  { lista: [
    '**Ferro:** usado em larga escala em armas e ferramentas, a partir do século IX a.C.',
    '**Engenharia hidráulica:** canais, e o **aqueduto de Jerwan** (c. 690 a.C.), em calcário, com cerca de 280 m de comprimento e arcos de pedra, para levar água a Nínive.',
    '**Engenharia militar:** rampas, aríetes, torres, pontes de barcos, odres para atravessar rios.',
    '**Fundição de bronze:** Senaqueribe descreve a fundição de enormes figuras de bronze em moldes de várias peças.',
    '**Marfim e vidro:** as oficinas de Nimrud produziram milhares de marfins esculpidos, e vidro e tijolos vidrados de várias cores.',
    '**Estradas e correio:** rede de comunicação rápida pelo império.'
  ] },
  { img: 'asi-marfins-nimrud', leg: 'Mulher à janela, marfim encontrado em Nimrud, em estilo fenício. Museu do Iraque.' }
];

const personalidades = [
  'A história assíria é, em grande parte, a história dos seus reis, que deixaram inscrições longas e gravaram o seu nome nos palácios. Estas são as figuras principais, com a ressalva de que quase tudo o que sabemos vem de fontes oficiais.',
  { h: 'Shamshi-Adad I' },
  'Reinou c. 1808 – 1776 a.C. Era amorreu, de origem fora de Assur. Conquistou a cidade e criou um reino que ia do Alto Eufrates ao Zagros, com capital em Shubat-Enlil (Tell Leilan) e dois filhos governadores: Ishme-Dagan em Ekallatum e Yasmah-Adad em Mari. As cartas do arquivo de Mari mostram-no a repreender o filho Yasmah-Adad por ser fraco. Morreu c. 1776 a.C. e o reino desfez-se.',
  { h: 'Assur-uballit I' },
  'Reinou c. 1363 – 1328 a.C. Escreveu ao faraó (as cartas de Amarna) a pedir ouro e a reclamar para a Assíria o estatuto de «grande reino». Aproveitou a queda do reino de Mitani para ganhar território e, com ele, começou o período médio-assírio. A tradição considerou-o o fundador da Assíria como grande potência.',
  { h: 'Tukulti-Ninurta I' },
  'Reinou c. 1243 – 1207 a.C. Venceu os hititas, conquistou a Babilónia e levou o rei babilónico preso. Fundou uma capital nova, Kar-Tukulti-Ninurta, e foi assassinado pelos filhos. Uma epopeia em acádio celebra-o, mas a mesma obra mostra os deuses a abandonarem a Babilónia por causa dos seus pecados, uma forma de justificar o ataque.',
  { h: 'Tiglat-Pileser I' },
  'Reinou c. 1114 – 1076 a.C. Reconquistou território, chegou ao Mediterrâneo e à Anatólia, e proclamou-se grande caçador: os anais dizem que matou 120 leões a pé e 800 do carro. Depois da sua morte a Assíria entrou numa fase de retração.',
  { h: 'Assurnasirpal II' },
  'Reinou 883 – 859 a.C. Reconstruiu a Assíria e transformou Nimrud em capital, onde construiu o Palácio do Noroeste, decorado com relevos de pedra com a mesma inscrição repetida (a «Inscrição Padrão»). Os seus anais descrevem uma política de terror extremo contra os rebeldes, e também a abertura de jardins e o banquete de inauguração. Foi o primeiro dos grandes reis do império neo-assírio.',
  { img: 'asi-assurnasirpal-estela', leg: 'Estela de Assurnasirpal II, de Nimrud. Museu Britânico.' },
  { h: 'Salmanasar III' },
  'Reinou 858 – 824 a.C. Fez mais de trinta campanhas e a sua longa luta contra Damasco ficou documentada no Obelisco Negro e nas Portas de Balawat. Os seus textos mencionam Acab e Jeú, reis de Israel. Terminou o reinado numa guerra civil provocada por um dos seus filhos.',
  { h: 'Shammuramat (Semíramis)' },
  'Foi regente c. 811 – 806 a.C., em nome do filho Adad-nirari III, e é a **única mulher** conhecida a ter exercido a regência na Assíria (o seu estatuto formal de regente é debatido). A estela de Shammuramat foi erguida em Assur. A Grécia fez dela a lendária «Semíramis», uma rainha guerreira e construtora, em histórias com pouco de verdade e muito de fantasia.',
  { img: 'asi-shammuramat-estela', leg: 'Estela de Shammuramat, de Assur, c. 809 a.C. Museu de Pérgamo, Berlim.' },
  { h: 'Tiglat-Pileser III' },
  'Reinou 745 – 727 a.C. Foi o fundador do império neo-assírio tal como o conhecemos. Reformou o exército e a administração, criou províncias com governadores nomeados, deportou populações e foi coroado rei da Babilónia.  É, para muitos historiadores, o rei mais importante da Assíria.',
  { img: 'asi-tiglat-pileser-iii', leg: 'Tiglat-Pileser III no carro, relevo de Nimrud. Museu Britânico.' },
  { h: 'Sargão II' },
  'Reinou 722 – 705 a.C. O seu nome (*Šarru-kīn*, «o rei é legítimo») sugere que subiu ao trono por meios pouco claros. Reorganizou o exército, venceu os Urartianos, ocupou a Babilónia e fundou Dur-Sharrukin. Morreu numa batalha, longe de casa, na Anatólia, e os Assírios viram nisso um mau presságio. O seu palácio, em Khorsabad, deu o primeiro grande conjunto de arte assíria ao Louvre.',
  { img: 'asi-sargao-ii-relevo', leg: 'Sargão II com um alto dignitário, relevo de Khorsabad. Louvre.' },
  { h: 'Senaqueribe' },
  'Reinou 704 – 681 a.C. Fez de Nínive a capital e construiu o Palácio Sem Rival. Atacou Judá em 701 a.C., destruiu a Babilónia em 689 a.C., e foi assassinado por um dos filhos. Os relevos do cerco de Laquis, no seu palácio, mostram-no sentado num trono de campanha diante da cidade tomada.',
  { img: 'asi-senaqueribe-laquis', leg: 'Senaqueribe no trono a receber o butim de Laquis. Museu Britânico.' },
  { h: 'Naqi’a (Zakutu)' },
  'Foi mulher de Senaqueribe e mãe de Esarhaddon, e uma das mulheres mais poderosas da Assíria. O seu nome aramaico, Zakutu, aparece em textos. Por volta de 669 a.C., depois da morte de Esarhaddon, fez jurar aos príncipes e aos grandes do reino lealdade a Assurbanípal, o seu neto, como rei. É um bom exemplo do poder das rainhas assírias.',
  { h: 'Esarhaddon' },
  'Reinou 681 – 669 a.C. Ganhou a guerra civil depois do assassinato do pai, reconstruiu a Babilónia que o pai arrasara e conquistou o Egito em 671 a.C. Viveu obcecado por presságios e doenças, e usou o rei substituto. Em 672 a.C. mandou o reino jurar lealdade, num «tratado de sucessão», aos dois filhos: Assurbanípal na Assíria e Shamash-shum-ukin na Babilónia.',
  { h: 'Assurbanípal' },
  'Reinou 669 – c. 631 a.C. Foi educado como futuro rei e, ao contrário de muitos reis, aprendeu a ler e a escrever: gabava-se disso. Mandou reunir a biblioteca de Nínive, venceu o Egito, o Elam e o irmão rebelde, e deixou os mais belos relevos de caça ao leão. O seu longo reinado foi o auge e o início do fim do império, esgotado por guerras constantes.',
  { img: 'asi-jardim-assurbanipal', leg: 'Banquete no jardim de Assurbanípal, relevo de Nínive. Museu Britânico.' }
];

const legado = [
  { h: 'O que nos deixaram' },
  { lista: [
    '**A biblioteca:** a coleção de Assurbanípal salvou a literatura mesopotâmica, incluindo Gilgamesh, para o mundo moderno.',
    '**O império:** o modelo de províncias, de governadores, de correios e de exércitos permanentes foi herdado pelos Babilónios e pelos Persas.',
    '**O aramaico:** a língua que os Assírios espalharam pelo Próximo Oriente passou a ser a língua do império persa e, mais tarde, a língua de Jesus.',
    '**A cronologia:** os epónimos e o eclipse de 763 a.C. são a espinha dorsal da cronologia do Próximo Oriente antigo.',
    '**A Bíblia:** os relatos assírios cruzam-se com os livros dos Reis, de Isaías e de Naum, e dão datas e nomes que permitem reconstruir a história de Israel e de Judá.',
    '**A arte:** os relevos de pedra são das obras mais expressivas da arte antiga, e a figura do touro alado ficou como ícone.'
  ] },
  { h: 'Arte' },
  'A arte assíria é uma arte de **palácio**. As paredes das salas eram cobertas com lajes de calcário e de alabastro-gipso com relevos de cerca de 2 m de altura, pintados, que mostravam o rei em guerra, em caça, em cerimónia, e génios alados que protegiam a casa. Nos portais, os **lamassu** (touros ou leões alados com cabeça humana) guardavam a entrada, e tinham **cinco patas**, para parecerem estar parados vistos de frente e a andar vistos de lado. A cena de caça de Assurbanípal (c. 645 – 635 a.C.) mostra animais feridos com um realismo raro na arte antiga, e a «leoa ferida» é uma das obras mais célebres.',
  { img: 'asi-caca-leao', leg: 'Caça ao leão de Assurbanípal, relevo do Palácio Norte de Nínive. Museu Britânico.' },
  { img: 'asi-leoa-ferida', leg: 'Leões e leoa mortos ou feridos, relevo da caça ao leão de Assurbanípal, c. 645–635 a.C. Museu Britânico.' },
  { h: 'Arquitetura' },
  'Os palácios assírios eram enormes complexos de tijolo cru, com salas de aparato, pátios, escritórios, arquivos e alojamentos, construídos sobre terraços elevados. Os grandes edifícios religiosos incluíam **zigurates**, como em Assur e Nimrud. As cidades tinham muralhas imponentes e portas monumentais, e eram planeadas com ruas, canais e jardins.',
  { h: 'A redescoberta da Assíria' },
  'Durante mais de dois mil anos, a Assíria foi conhecida só pela Bíblia e pelos Gregos. Os montes onde estavam Nínive e Nimrud eram montes anónimos de terra. A redescoberta foi obra do século XIX, e teve uma parte menos bonita: muitos achados foram levados para museus europeus sem grande respeito pelos habitantes locais.',
  { linha: [
    { d: '1820', t: 'Claudius Rich em Nínive', x: 'O britânico Claudius James Rich, residente da Companhia das Índias Orientais em Bagdade, visita e mede o monte de Kuyunjik (Nínive) e recolhe inscrições.' },
    { d: '1843', t: 'Botta em Khorsabad', x: 'Paul-Émile Botta, cônsul de França em Mossul, descobre o palácio de Sargão II em Khorsabad, o primeiro palácio assírio conhecido. O Museu Assírio do Louvre abre em 1847.' },
    { d: '1845 – 1851', t: 'Layard em Nimrud e Nínive', x: 'Austen Henry Layard escava Nimrud (que julga ser Nínive) e depois Nínive. Descobre o Obelisco Negro em 1846 e envia touros alados e relevos para o Museu Britânico, num transporte difícil pelo Tigre. Publica *Nineveh and Its Remains* (1849).' },
    { d: '1853', t: 'Rassam e o Palácio Norte', x: 'Hormuzd Rassam, assírio cristão de Mossul que trabalhava com Layard, descobre o Palácio Norte de Assurbanípal, com a caça ao leão, e grande parte da biblioteca. Em 1878 encontrará as Portas de Balawat.' },
    { d: '1857', t: 'Decifração do acádio', x: 'Quatro estudiosos (Rawlinson, Hincks, Fox Talbot e Oppert) traduzem de forma independente a mesma inscrição de Tiglat-Pileser I, e as traduções coincidem: o cuneiforme acádio foi considerado decifrado.' },
    { d: '1872', t: 'George Smith e o dilúvio', x: 'No Museu Britânico, George Smith lê numa tabuinha de Nínive um relato do dilúvio parecido com o de Noé. Era a tabuinha XI da Epopeia de Gilgamesh.' },
    { d: '1903 – 1914', t: 'Andrae em Assur', x: 'A Sociedade Alemã do Oriente escava Assur sob Walter Andrae e revela o grande zigurate, os templos e as tumbas.' },
    { d: '1949 – 1958', t: 'Mallowan em Nimrud', x: 'Max Mallowan (marido de Agatha Christie, que o acompanhou) escava Nimrud e encontra milhares de marfins e as inscrições do Forte de Salmanasar.' },
    { d: '1988 – 1989', t: 'As tumbas das rainhas', x: 'Arqueólogos iraquianos encontram, sob o Palácio do Noroeste de Nimrud, tumbas de rainhas assírias com joias de ouro, entre elas as de **Yaba** (mulher de Tiglat-Pileser III) e **Atalia** (mulher de Sargão II).' },
    { d: '2015 – 2016', t: 'A destruição no Iraque', x: 'Durante o domínio do autoproclamado Estado Islâmico em Mossul, o Museu de Mossul e Nimrud (2015) e as portas de Mashki e de Adad de Nínive (2016) foram deliberadamente destruídos. Houve também saque de antiguidades e dano a Khorsabad. Desde 2017, equipas iraquianas e internacionais documentam e restauram o que foi possível.' }
  ] },
  { img: 'asi-layard', leg: 'Retrato de Austen Henry Layard (1817–1894).' },
  { img: 'asi-transporte-touro', leg: 'Gravura histórica do transporte de um touro alado de Nimrud.' },
  { img: 'asi-sala-museu-britanico', leg: 'Galeria assíria do Museu Britânico, com lamassu e relevos.' },
  { img: 'asi-destruicao-2015', leg: 'Fragmento com inscrição cuneiforme nos escombros de Nimrud, fotografado em janeiro de 2019, após a destruição de 2015; pormenor documental.' },
  { caixa: 'Para visitar', texto: 'O **Museu Britânico** (Londres) tem a maior coleção de relevos de Nimrud e Nínive, incluindo o Obelisco Negro, os relevos de Laquis e a caça ao leão de Assurbanípal. O **Louvre** (Paris) guarda os touros alados de Khorsabad. O **Instituto Oriental** da Universidade de Chicago tem um grande lamassu de Khorsabad. O **Museu de Pérgamo** (Berlim) tem peças de Assur, e o **Museu Nacional do Iraque** (Bagdade) tem as joias das rainhas de Nimrud e o maior acervo de arte assíria na sua terra de origem.' }
];

const quiz = [
  { p: 'Qual era a cidade original da Assíria, que deu o nome ao reino e ao deus principal?', op: ['Nínive', 'Nimrud', 'Babilónia', 'Assur'], certa: 3, exp: 'Assur, no Tigre, era ao mesmo tempo cidade, território e deus nacional.' },
  { p: 'O que levavam os mercadores assírios de Assur até Kanesh, na Anatólia?', op: ['Cavalos e armas', 'Estanho e tecidos', 'Madeira de cedro', 'Escravos'], certa: 1, exp: 'Os mercadores assírios levavam estanho e tecidos e traziam prata e ouro.' },
  { p: 'Quantas tabuinhas, aproximadamente, foram encontradas no arquivo de Kanesh (Kültepe)?', op: ['Cerca de 200', 'Cerca de 2000', 'Mais de 23 000', 'Mais de 1 milhão'], certa: 2, exp: 'O arquivo de mercadores de Kültepe é uma das maiores fontes de história económica antiga.' },
  { p: 'Que rei assírio escreveu ao faraó do Egito como a um igual, no século XIV a.C.?', op: ['Assurnasirpal II', 'Sargão II', 'Assurbanípal', 'Assur-uballit I'], certa: 3, exp: 'Nas cartas de Amarna, Assur-uballit I trata o faraó como «irmão» e pede o reconhecimento como grande rei.' },
  { p: 'Que rei assírio conquistou a Babilónia por volta de 1225 a.C. e fundou Kar-Tukulti-Ninurta?', op: ['Tukulti-Ninurta I', 'Shamshi-Adad I', 'Sargão II', 'Esarhaddon'], certa: 0, exp: 'Tukulti-Ninurta I tomou a Babilónia e foi depois assassinado pelos filhos.' },
  { p: 'Onde construiu Assurnasirpal II a sua nova capital, c. 879 a.C.?', op: ['Em Nimrud (Calá)', 'Em Nínive', 'Em Khorsabad', 'Em Harran'], certa: 0, exp: 'Assurnasirpal II refundou Calá (Nimrud), com o Palácio do Noroeste.' },
  { p: 'Que rei assírio é representado no Obelisco Negro a receber o tributo de Jeú, de Israel?', op: ['Tiglat-Pileser III', 'Esarhaddon', 'Salmanasar III', 'Senaqueribe'], certa: 2, exp: 'O Obelisco Negro, de c. 825 a.C., mostra Jeú a prostrar-se diante de Salmanasar III.' },
  { p: 'Que reforma de Tiglat-Pileser III foi decisiva para o império?', op: ['Acabar com os vassalos', 'Províncias com governadores e exército permanente', 'Fundar uma nova religião', 'Proibir o aramaico'], certa: 1, exp: 'Tiglat-Pileser III criou províncias com governadores nomeados e um exército permanente.' },
  { p: 'Que rei fundou Dur-Sharrukin (Khorsabad) e morreu em batalha, sem que o corpo fosse recuperado?', op: ['Senaqueribe', 'Tukulti-Ninurta I', 'Assurbanípal', 'Sargão II'], certa: 3, exp: 'Sargão II fundou a cidade e morreu em campanha, na Anatólia, em 705 a.C.' },
  { p: 'O que aconteceu a Jerusalém na campanha de Senaqueribe de 701 a.C.?', op: ['Foi totalmente destruída', 'Foi tomada e o rei levado para Nínive', 'Foi cercada, mas não conquistada: o rei Ezequias pagou tributo', 'Não foi atacada'], certa: 2, exp: 'Senaqueribe tomou Laquis e cercou Jerusalém, mas a cidade não foi tomada. Os relatos divergem sobre o motivo.' },
  { p: 'Onde se encontravam os célebres relevos do cerco de Laquis?', op: ['No templo de Assur', 'Em Babilónia', 'No palácio de Senaqueribe, em Nínive', 'Em Persépolis'], certa: 2, exp: 'Os relevos do Palácio Sudoeste de Nínive estão hoje no Museu Britânico.' },
  { p: 'Qual foi a famosa coleção reunida por Assurbanípal em Nínive?', op: ['Um arquivo de cartas ao faraó', 'Um museu de arte', 'Um conjunto de estátuas', 'Uma biblioteca com mais de 30 000 tabuinhas e fragmentos'], certa: 3, exp: 'A Biblioteca de Assurbanípal salvou muita da literatura mesopotâmica, incluindo Gilgamesh.' },
  { p: 'Qual é a melhor descrição da «crueldade assíria»?', op: ['Em parte real, em parte exagero de propaganda real; outros impérios também usaram violência', 'Uma invenção moderna sem qualquer base', 'Um facto sem exageros', 'Algo que só existia nos relatos bíblicos'], certa: 0, exp: 'Houve violência real (por exemplo, empalamentos), mas os anais exageram para dissuadir, e a imagem foi moldada pelos inimigos.' },
  { p: 'Em que ano caiu Nínive, às mãos de Babilónios e Medos?', op: ['722 a.C.', '689 a.C.', '612 a.C.', '539 a.C.'], certa: 2, exp: 'Nínive caiu em 612 a.C.; os últimos assírios resistiram em Harran até 610 – 609 a.C.' },
  { p: 'Quem descobriu em 1843 o primeiro palácio assírio, em Khorsabad?', op: ['Austen Henry Layard', 'Paul-Émile Botta', 'Hormuzd Rassam', 'George Smith'], certa: 1, exp: 'Botta, cônsul de França em Mossul, descobriu o palácio de Sargão II em Khorsabad.' }
];

export default {
  id: 'assiria',
  cor: '#8a5a3a',
  emblema: '../assets/img/assiria.png',
  nome:    { pt: 'Assíria', en: 'Assyria' },
  periodo: { pt: 'c. 2025 a.C. – 609 a.C.', en: 'c. 2025 BC – 609 BC' },
  visao:          { pt: visao, en: EN.visao },
  linha:          { pt: linha, en: EN.linha },
  mapa:           { pt: mapa, en: EN.mapa },
  sociedade:      { pt: sociedade, en: EN.sociedade },
  personalidades: { pt: personalidades, en: EN.personalidades },
  legado:         { pt: [...legado, ...CRED.pt], en: [...EN.legado, ...CRED.en] },
  quiz:           { pt: quiz, en: EN.quiz }
};
