// ÍNDIA — CIÊNCIA, MATEMÁTICA E ARTE — conteúdo completo em português. A versão inglesa está em dados-en.js (mesma estrutura, mesmos ids de imagem).
// Página temática: matemática, astronomia, medicina, metalurgia e técnica; arquitetura, escultura, pintura, teatro, música, dança e literatura. Período coberto: da Antiguidade a c. 1500 d.C.
// Datas aproximadas; muitas obras indianas só se datam por intervalos e por tradição, e isso é assinalado no texto. a.C. = antes de Cristo, d.C. = depois de Cristo.
// Imagens: cada {img:'id'} procura o ficheiro  india-classica/ciencia-arte/img/id.jpg  (ver IMAGENS_INDIA_CLASSICA_CIENCIA_ARTE.md).
import EN from './dados-en.js';
import CRED from './creditos.js';
import { GRUPO } from '../grupo.js';

const visao = [
  { caixa: 'Em resumo', texto: [
    'Esta página reúne o que a Índia antiga e medieval **pensou, calculou, curou, construiu e imaginou**. Do lado da ciência: o **sistema decimal de posição com o zero**, as regras de cálculo de **Brahmagupta**, a astronomia de **Aryabhata**, a **trigonometria** do seno, a cirurgia de **Sushruta**, a medicina de **Charaka**, o ferro que quase não enferruja do **Pilar de Delhi** e o aço de cadinho. Do lado da arte: os **estupas** e as grutas pintadas de **Ajanta**, os templos escavados de **Ellora**, os templos de pedra dos **Gupta**, dos **Pallavas** e dos **Cholas**, as esculturas de **Gandhara**, **Mathura** e **Sarnath**, os bronzes de **Nataraja**, o teatro e a música codificados no ***Natyashastra***, e a literatura em sânscrito e em tâmil.',
    'O que une as duas metades é um hábito de **sistematizar**: a Índia produziu tratados (*shastra*) sobre quase tudo, da gramática e da política à dança, à arquitetura, ao cavalo e ao amor. Esses tratados fixaram regras, mas não impediram a invenção; deixaram uma linguagem comum a sábios, artesãos e artistas que trabalhavam de Taxila ao Tamil Nadu.'
  ] },
  { img: 'ica-ajanta-pintura', leg: 'Pintura mural do Bodisatva Padmapani, Gruta 1 de Ajanta (Maharashtra), séc. V d.C.' },
  { h: 'Onde e quando' },
  'Esta página é **temática**: percorre o subcontinente inteiro e cerca de dois mil anos. Os grandes marcos de cada área ficam, grosso modo, assim:',
  { tabela: { cab: ['Período', 'Ciência e técnica', 'Arte e arquitetura'], linhas: [
    ['Antes de c. 300 a.C.', 'Geometria dos altares védicos (*Sulba Sutras*); métrica de Pingala (c. séc. III–II a.C., debatido)', 'Pilares e estupas de Ashoka (séc. III a.C.); escultura polida máuria'],
    ['c. 200 a.C. – c. 300 d.C.', 'Textos médicos de Charaka e Sushruta (em formação); astronomia com influência grega; aço de cadinho no sul', 'Bharhut, Sanchi, Karli; primeiras grutas de Ajanta; imagens do Buda em Gandhara e Mathura; teatro: *Natyashastra*'],
    ['c. 320 – 550 (Gupta)', 'Aryabhata, Varahamihira; zero e valor posicional; Pilar de Ferro (c. 400)', 'Pinturas de Ajanta; templos de Deogarh e Bhitargaon; Buda de Sarnath; Kalidasa'],
    ['c. 550 – 1000', 'Brahmagupta (628); zero com regras; inscrição de Gwalior (876)', 'Mahabalipuram, Aihole, Pattadakal; Ellora (Kailasa, séc. VIII); Elephanta'],
    ['c. 1000 – 1500', 'Bhaskara II (c. 1150); Sarngadeva (séc. XIII); escola de Kerala (Madhava, séc. XIV)', 'Brihadisvara (1010), Khajuraho, Konark, Hoysalas, Vijayanagara; bronzes Chola; primeiras mesquitas do Sultanato de Deli']
  ] } },
  { img: 'ica-bakhshali', leg: 'Folha do manuscrito de Bakhshali, em casca de bétula, com números em notação decimal e um ponto como zero (Biblioteca Bodleian, Oxford). A sua datação é debatida.' },
  { h: 'Dois fios, uma civilização' },
  'Ciência e arte raramente são separadas nas fontes indianas. O mesmo homem podia ser astrónomo e poeta (**Varahamihira** escreveu sobre eclipses e sobre arquitetura de templos), e os tratados de templos falam de proporções, de astronomia e de ritual na mesma página. As **matemáticas** serviam para calcular o calendário, medir altares e templos, dividir terras e contar impostos; a **medicina** vivia entre a observação clínica, a botânica e a filosofia; a **arte** respondia a regras de proporção (*tala*), de gesto (*mudra*) e de sentimento (*rasa*).',
  { h: 'O que é seguro e o que não é' },
  'A cronologia da ciência e da arte da Índia antiga é frágil. Muitos textos foram transmitidos **oralmente** durante séculos, copiados em folhas de palmeira que apodrecem no clima húmido, e revistos por gerações de comentadores. Por isso há debates de séculos sobre as datas de **Sushruta**, **Charaka**, **Bharata** (*Natyashastra*), **Kalidasa** ou do **Tirukkural**. Nesta página, as datas são intervalos e as atribuições a pessoas (*Bharata*, *Kautilya*, *Vatsyayana*) significam, na maior parte dos casos, que o texto **é tradicionalmente atribuído** a essa figura.',
  { img: 'ica-pilar-ferro', leg: 'O Pilar de Ferro de Delhi, no complexo de Qutb, c. 400 d.C.: cerca de 7 m de altura e mais de 6 toneladas.' },
  { h: 'Porque importam' },
  { lista: [
    '**O zero e os algarismos:** o sistema de dez algarismos com valor de posição, hoje usado no mundo inteiro, formou-se na Índia e chegou à Europa pelo mundo árabe.',
    '**Trigonometria e astronomia:** a «corda» indiana (*jya*) tornou-se, por vias árabes e latinas, o nosso **seno**; Aryabhata e os seus sucessores calcularam eclipses e movimentos planetários com precisão notável.',
    '**Cirurgia e medicina:** a *Sushruta Samhita* descreve a reconstrução do nariz e outras operações; o Ayurveda ainda é praticado.',
    '**Arquitetura sagrada:** o estupa, a gruta escavada, o templo de pedra com torre; formas que viajaram com o budismo e o hinduísmo até ao Camboja, à Indonésia, ao Tibete e ao Japão.',
    '**Artes do espetáculo:** o teatro sânscrito, a teoria do *rasa*, a música de *raga* e *tala* e as danças clássicas têm as raízes em textos e práticas desta época.',
    '**Literatura:** de Kalidasa ao Tirukkural, do Panchatantra à poesia do Sangam; fábulas indianas chegaram à Europa, e a poesia sânscrita encantou Goethe.'
  ] },
  { img: 'ica-kailasa', leg: 'O templo de Kailasa (Gruta 16) em Ellora, escavado numa só rocha no séc. VIII, sob a dinastia Rashtrakuta.' },
  { caixa: 'Uma regra para ler esta página', texto: 'Quando um texto diz que a Índia «inventou» algo, quase sempre há duas perguntas: **quando** e **para quem**. O zero, por exemplo, tem uma história de séculos, com contributos de astrónomos, de comentadores e de escribas, e circulou entre Índia, Camboja, Pérsia e mundo árabe. Procuramos aqui descrever o que as fontes mostram, sem transformar tudo em «o primeiro do mundo».' },
  { img: 'ica-nataraja', leg: 'Shiva Nataraja, o «Senhor da Dança», bronze da época Chola (séc. XI ou XII), exemplo da arte do bronze fundido pelo método da cera perdida.' },
  { h: 'Hoje' },
  'Hoje, a Índia é uma potência em ciência e tecnologia, e continua a reivindicar este passado como parte da sua identidade, às vezes com exagero e propaganda (há quem atribua à Antiguidade indiana aviões, cirurgia plástica moderna ou física quântica). O historiador distingue as duas coisas: **o que os textos realmente dizem** já é impressionante e dispensa invenções. Ajanta, Ellora, Elephanta, Khajuraho, Mahabalipuram, Konark, Hampi, os «Grandes Templos Vivos dos Cholas» e outros sítios são **Património Mundial da UNESCO**.',
  { img: 'ica-observatorio', leg: 'Reconstrução artística: um astrónomo indiano e discípulos a observar o céu ao anoitecer, com um gnómon, uma esfera armilar de madeira e folhas de palmeira, c. séc. V d.C.' }
];

const linha = [
  'Esta linha do tempo segue a **evolução da ciência e da arte**, das fórmulas dos altares védicos à escola matemática de Kerala. As datas são intervalos; para vários textos a datação é discutida e está assinalada.',
  { linha: [
    { d: 'c. 800 – 500 a.C.', t: 'Os Sulba Sutras', x: 'Manuais rituais ligados aos Vedas ensinam a construir altares com formas geométricas exatas, usando cordas (*sulba*). Os textos de **Baudhayana** e outros enunciam a relação entre a diagonal e os lados do retângulo (o que hoje chamamos teorema de Pitágoras) e dão aproximações da raiz quadrada de 2. A datação (séc. VIII a séc. VI a.C.) é aproximada.' },
    { d: 'c. séc. III – II a.C. (debatido)', t: 'Pingala e a métrica', x: 'O *Chandahshastra*, atribuído a **Pingala**, estuda os metros da poesia sânscrita com sequências de sílabas longas e breves, que se podem descrever como códigos binários. Comentadores posteriores (Halayudha, séc. X) ligaram estas sequências ao que hoje chamamos o triângulo de Pascal.' },
    { d: 'c. 250 a.C.', t: 'Pilares polidos de Ashoka', x: 'O imperador **Ashoka** manda erguer pilares monolíticos de arenito, polidos como espelho, coroados por animais (leões, touros, elefantes). É a primeira grande escultura de pedra indiana de que há provas seguras, e o capitel de Sarnath é hoje o emblema da República da Índia. O Grande Estupa de Sanchi começa nesta época, como monte de tijolo.' },
    { d: 'séc. II – I a.C.', t: 'Bharhut, Sanchi, primeiras grutas de Ajanta', x: 'Sob os **Sungas** e depois os **Satavahanas**, os estupas ganham balaustradas e portas de pedra cobertas de relevos que contam as vidas anteriores do Buda (*Jatakas*). Em Ajanta começa a primeira fase de grutas budistas (séc. II a.C. – séc. I d.C.), e em Karli e noutros locais do Decão escavam-se os primeiros grandes salões de oração (*chaityas*).' },
    { d: 'c. 200 a.C. – 200 d.C.', t: 'O Natyashastra', x: 'O tratado de teatro, música e dança **Natyashastra**, atribuído a **Bharata**, é compilado ao longo de séculos; a maioria dos especialistas aceita uma primeira versão completa entre c. 200 a.C. e 200 d.C. (outros propõem datas mais largas). Fixa a teoria do *rasa* («sabor» ou sentimento) e uma gramática do gesto e da música.' },
    { d: 'séc. I – II d.C.', t: 'O Buda ganha rosto: Gandhara e Mathura', x: 'Sob os Kushanas, duas escolas começam a representar o Buda em forma humana, em vez de símbolos (pegadas, roda, árvore, trono vazio): **Gandhara**, no noroeste, com influência helenística, e **Mathura**, em arenito vermelho. Qual veio primeiro é discutido; é provável que se tenham desenvolvido em paralelo.' },
    { d: 'séc. I – III d.C.', t: 'Literatura Sangam e textos médicos', x: 'No Tamil Nadu, os poetas do **Sangam** compõem antologias de poesia de amor e de guerra em tâmil (a datação por intervalos, c. séc. I – III d.C., é debatida). Em paralelo tomam forma as grandes compilações médicas, a *Charaka Samhita* (medicina interna) e a *Sushruta Samhita* (cirurgia), que serão revistas durante séculos.' },
    { d: 'séc. II – III d.C.', t: 'Astronomia com influências gregas', x: 'Textos astrológicos e astronómicos em sânscrito, como o *Yavanajataka* («o livro dos gregos»), mostram contacto com a astronomia helenística, trazida pelo comércio com Alexandria e por reinos indo-gregos. Mais tarde, os *siddhantas* indianos integram métodos de várias origens.' },
    { d: 'c. séc. III d.C. (debatido)', t: 'O Kama Sutra', x: 'O *Kama Sutra*, atribuído a **Vatsyayana Mallanaga**, é composto provavelmente entre os sécs. II e IV, mais provavelmente no séc. III. É um tratado sobre a «arte de viver» e sobre o prazer (*kama*) como um dos objetivos da vida; a maior parte do texto trata de cortejo, casamento, vida doméstica e cultura, e só uma parte dele de união física.' },
    { d: 'c. 335 – 375 d.C.', t: 'Samudragupta e a lira', x: 'O rei Gupta **Samudragupta** manda cunhar moedas de ouro que o mostram a tocar uma **veena** (um instrumento de cordas arqueado), prova de que a música era uma arte régia. Os Gupta entram na chamada «idade clássica» das artes.' },
    { d: 'c. 400 d.C.', t: 'O Pilar de Ferro de Delhi', x: 'Em c. 400, no tempo de **Chandragupta II** (identificação mais aceite), é forjado um pilar de ferro de mais de 7 m e 6 toneladas, com inscrição em sânscrito. Não enferruja, graças à composição do ferro e a uma película protetora. Esteve primeiro noutro local e foi levado para Delhi na Idade Média.' },
    { d: '458 d.C.', t: 'Lokavibhaga: números com zero', x: 'O texto jainista de cosmologia ***Lokavibhaga***, datado de 458 no seu próprio calendário, é dos primeiros em que se usa, com certeza, o valor posicional decimal com uma palavra para zero (*shunya*, «vazio»). Mostra que o sistema já era conhecido no tempo dos Gupta.' },
    { d: 'c. 460 – 480 d.C.', t: 'Os frescos de Ajanta', x: 'Sob o rei **Harishena** dos Vakatakas e o seu ministro **Varahadeva**, aliados dos Gupta, escavam-se e pintam-se as grutas mais célebres de **Ajanta**. As pinturas murais, feitas sobre gesso seco, são o melhor testemunho da pintura clássica indiana.' },
    { d: '476 / 499 d.C.', t: 'Aryabhata', x: 'O matemático e astrónomo **Aryabhata** nasceu em 476; em 499 escreveu o *Aryabhatiya*, em 121 versos. Trata de numeração, geometria, trigonometria e astronomia, e defende que a Terra roda sobre o seu eixo.' },
    { d: 'séc. VI d.C.', t: 'Templos Gupta e Varahamihira', x: 'Em **Deogarh**, o templo de **Dashavatara** (início do séc. VI) é um dos primeiros templos de pedra com torre sobre o santuário, e o de **Bhitargaon** é um dos mais antigos de tijolo. Em Ujjain, **Varahamihira** (c. 505 – 587) escreve o *Pancha-siddhantika*, resumo de cinco escolas de astronomia, e a *Brihat Samhita*, enciclopédia que inclui arquitetura e pedras preciosas.' },
    { d: '628 d.C.', t: 'Brahmagupta e as regras do zero', x: '**Brahmagupta** escreve o *Brahmasphutasiddhanta*, em que dá regras para somar, subtrair e multiplicar com zero e com números negativos («dívidas» e «fortunas»). É um passo decisivo: o zero passa de simples sinal de lugar a número com que se calcula.' },
    { d: 'séc. VII d.C.', t: 'Os Pallavas e Mahabalipuram', x: 'Os reis **Pallavas** (Narasimhavarman I, o «Mamalla», 630 – 668) mandam esculpir em Mahabalipuram templos monolíticos (os *rathas*) e o enorme relevo da «Descida do Ganges» (ou «Penitência de Arjuna»). O **Templo da Costa** (c. 700 – 728) é dos primeiros grandes templos de pedra construídos no sul.' },
    { d: 'c. 756 – 773 d.C.', t: 'Kailasa, em Ellora', x: 'No reinado do rei **Rashtrakuta Krishna I** escava-se de cima para baixo, numa só rocha, o gigantesco **templo de Kailasa** (Gruta 16 de Ellora): um templo completo, com torre, pátio e salas, cortado da montanha.' },
    { d: '876 d.C.', t: 'O zero em Gwalior', x: 'Uma inscrição do templo de **Chaturbhuj**, em Gwalior, é o exemplo mais antigo, bem datado e indiscutível, de um zero em forma de pequeno círculo, num texto em pedra. Antes, já havia zeros em manuscritos (Bakhshali, de datação debatida) e em inscrições no Camboja (Sambor, 683).' },
    { d: 'c. 950 – 1050 d.C.', t: 'Khajuraho', x: 'Os reis **Chandelas** constroem em Khajuraho dezenas de templos de arenito (hoje restam cerca de 25), com esculturas de deuses, músicos, dançarinas e cenas da vida de corte. O **Kandariya Mahadeva** terá sido concluído em c. 1029.' },
    { d: '1010 d.C.', t: 'O Brihadisvara de Thanjavur', x: 'O imperador **Rajaraja I** (985 – 1014) inaugura o templo de **Brihadisvara**, dedicado a Shiva, com uma torre (*vimana*) de cerca de 63 m. É a obra-prima da arquitetura **Chola**, e na mesma época florescem os bronzes do **Shiva Nataraja**.' },
    { d: 'c. 1150 d.C.', t: 'Bhaskara II', x: 'Em Ujjain, **Bhaskara II** escreve o *Siddhanta Shiromani*, com quatro partes (aritmética, álgebra, planetas e esfera celeste), incluindo o célebre *Lilavati*. Resolve equações com o método *chakravala* e antecipa ideias de cálculo infinitesimal.' },
    { d: 'c. 1210 – 1247 d.C.', t: 'Sarngadeva e a música', x: '**Sarngadeva**, na corte dos Yadavas de Devagiri, redige o *Sangita Ratnakara*, a grande síntese da teoria musical (ragas, ritmos, instrumentos, dança) usada depois no norte e no sul da Índia.' },
    { d: 'c. 1250 d.C.', t: 'O Templo do Sol de Konark', x: 'Os reis de Orissa (dinastia Ganga Oriental) constroem o **Templo do Sol de Konark**, desenhado como um carro de pedra com 24 rodas e cavalos. Do edifício, em grande parte ruinoso, resta a plataforma e o salão.' },
    { d: 'séc. XIV d.C.', t: 'Madhava e Vijayanagara', x: 'Em Kerala, **Madhava de Sangamagrama** (c. 1340 – 1425) descobre séries infinitas para o seno, o cosseno e o arco-tangente, séculos antes da Europa. No sul, a fundação de **Vijayanagara** (1336) dá origem a Hampi, com templos, palácios e um estilo próprio.' },
    { d: 'c. 1500 – 1530 d.C.', t: 'A escola de Kerala continua', x: '**Nilakantha Somayaji** escreve o *Tantrasangraha* (c. 1500) e **Jyesthadeva** o *Yuktibhasha* (c. 1530, em malaiala), com demonstrações das séries. Em 1498 **Vasco da Gama** chegou a Calecute; os portugueses fixam-se em Cochim, ao lado desta escola. Não há provas de que o saber matemático de Kerala tenha chegado à Europa.' }
  ] }
];

const mapa = [
  'Este mapa é o dos **lugares onde se vê a ciência e a arte da Índia**: sítios arqueológicos, centros de saber e templos. A lista não é exaustiva, mas cobre as maiores obras. Os locais da ciência são menos visíveis (um observatório, uma escola) do que os da arte, e por isso muitos aparecem sobretudo nos textos.',
  { img: 'ica-mapa-chola', leg: 'Mapa do Império Chola no seu auge, c. 1030 d.C., com a rede de templos e portos do sul.' },
  { tabela: { cab: ['Local', 'Onde', 'O que lá se vê'], linhas: [
    ['Sanchi', 'Madhya Pradesh', 'Grande Estupa, balaustradas e portas (*toranas*) com relevos; séc. III a.C. – I d.C.'],
    ['Bharhut', 'Madhya Pradesh', 'Estupa sunga, séc. II a.C.; a balaustrada está no Museu Indiano de Calcutá'],
    ['Karli e Bhaja', 'Maharashtra', 'Salões de oração (*chaityas*) escavados na rocha, séc. II a.C. – séc. II d.C.'],
    ['Ajanta', 'Maharashtra', '30 grutas budistas escavadas e pintadas; sécs. II a.C. – V d.C.'],
    ['Ellora', 'Maharashtra', '34 grutas budistas, hindus e jainistas; Kailasa, séc. VIII'],
    ['Elephanta', 'Ilha perto de Mumbai', 'Grutas de Shiva com o relevo da Trimurti; séc. V – VII'],
    ['Taxila e Gandhara', 'Paquistão', 'Mosteiros e estupas com imagens do Buda em estilo helenístico; sécs. I – V'],
    ['Mathura', 'Uttar Pradesh', 'Oficina de escultura em arenito vermelho; Kushanas e Gupta'],
    ['Sarnath', 'Uttar Pradesh', 'Pilar de Ashoka, Buda Gupta, mosteiros; museu'],
    ['Deogarh e Udayagiri', 'Uttar Pradesh e Madhya Pradesh', 'Templos e relevos Gupta, sécs. V – VI'],
    ['Mahabalipuram', 'Tamil Nadu', 'Rathas, relevos e Templo da Costa; Pallavas, sécs. VII – VIII'],
    ['Aihole, Badami, Pattadakal', 'Karnataka', 'Templos Chalukya, sécs. VI – VIII; berço de estilos de templo'],
    ['Thanjavur', 'Tamil Nadu', 'Brihadisvara, 1010; bronzes Chola'],
    ['Khajuraho', 'Madhya Pradesh', 'Templos Chandela, sécs. X – XI'],
    ['Konark', 'Odisha', 'Templo do Sol, c. 1250'],
    ['Ujjain', 'Madhya Pradesh', 'Centro de astronomia; meridiano de referência indiano; Varahamihira, Brahmagupta, Bhaskara II'],
    ['Hampi', 'Karnataka', 'Capital de Vijayanagara, sécs. XIV – XVI; templos, palácios e mercados'],
    ['Delhi (Mehrauli)', 'Delhi', 'Pilar de Ferro (c. 400) e primeiras mesquitas e minarete do Sultanato (c. 1200)']
  ] } },
  { h: 'Sanchi e as portas de pedra' },
  'O **Grande Estupa** de Sanchi, perto de Vidisha, é o melhor exemplo de estupa antigo. O núcleo de tijolo é do tempo de Ashoka (séc. III a.C.); no séc. II a.C. foi revestido de pedra e rodeado de uma balaustrada, e entre o séc. I a.C. e o séc. I d.C. foram erguidas as quatro portas (*toranas*), cobertas de relevos de cenas dos *Jatakas*, da vida do Buda e de multidões de devotos. O Buda aparece apenas em símbolos (a árvore, a roda, as pegadas, o trono vazio). Uma inscrição regista que os marfinistas de Vidisha esculpiram parte da porta sul, o que mostra como a pedra copiava técnicas de ofícios mais antigos.',
  { img: 'ica-sanchi-torana', leg: 'Porta oriental (torana) do Grande Estupa de Sanchi, com relevos esculpidos em arenito.' },
  { h: 'Karli, Bhaja e as grutas do Decão' },
  'Na costa ocidental, nos Gates Ocidentais, floresceu a arquitetura rupestre budista, financiada por mercadores, monges e reis satavahanas. O salão de oração de **Karli** (séc. I d.C., c. 50 – 70) é o maior *chaitya* escavado da Índia: cerca de 45 m de comprimento, com 15 colunas de cada lado e um estupa ao fundo. As inscrições nas colunas mostram doadores diversos, incluindo muitos **gregos** (*Yavanas*) vindos do comércio marítimo. A madeira original do teto e do guarda-sol do estupa sobreviveu.',
  { img: 'ica-karli', leg: 'O grande salão (chaitya) de Karli, Maharashtra, escavado na rocha, séc. I d.C.' },
  { h: 'Ajanta' },
  'No vale de Waghora, uma falésia em forma de ferradura guarda **30 grutas budistas**, escavadas em duas fases: a primeira (séc. II a.C. – séc. I d.C., sob os Satavahanas) com salões com estupas; a segunda (c. 460 – 480 d.C., sob os Vakatakas) com mosteiros e capelas ricamente pintadas e esculpidas. Foram abandonadas e esquecidas, até um oficial britânico, **John Smith**, as «redescobrir» em 1819, durante uma caçada ao tigre, embora a população local as conhecesse. São Património Mundial desde 1983.',
  { img: 'ica-ajanta-gruta', leg: 'Vista geral das grutas de Ajanta, escavadas numa falésia em arco sobre o rio Waghora.' },
  { h: 'Ellora e Elephanta' },
  'Em **Ellora**, 34 grutas lado a lado mostram a convivência de três religiões: 12 budistas (c. séc. V – VII), 17 hindus (c. séc. VII – IX) e 5 jainistas (c. séc. IX – X). A joia é o **Kailasa** (Gruta 16), um templo inteiro, com cerca de 32 m de altura e um pátio de c. 82 × 46 m, escavado **de cima para baixo** na rocha, sob Krishna I (756 – 773). Em **Elephanta**, numa ilha do porto de Mumbai, as grutas de Shiva (séc. V – VII, datação debatida) têm um relevo monumental de Shiva de três faces. Ambos são Património Mundial.',
  { h: 'Gandhara, Taxila e Mathura' },
  'No noroeste, **Gandhara** e **Taxila** (hoje no Paquistão e no Afeganistão) foram ponto de encontro de indianos, persas, gregos e povos da Ásia Central. As esculturas de xisto cinzento e de estuque mostram um Buda de feições quase greco-romanas, com cabelo ondulado e mantos pregueados. Em **Mathura**, a oficina de arenito vermelho pintalgado produziu imagens do Buda, de divindades e de reis kushanas, como a estátua (sem cabeça) de **Kanishka**.',
  { h: 'Sarnath' },
  'Em Sarnath, onde o Buda proferiu o primeiro sermão, ficam o pilar de Ashoka (de que resta a base) e as ruínas de estupas e mosteiros. O museu local guarda o capitel dos quatro leões e o célebre **Buda Gupta** (séc. V) em posição de pregação, sereno, com um halo decorado e um manto fino, quase transparente.',
  { h: 'Deogarh, Udayagiri e a época Gupta' },
  'O templo de **Dashavatara**, em **Deogarh** (início do séc. VI), tem uma plataforma e painéis de relevos com cenas do *Ramayana* e de Vishnu, e outro santuário que terá tido torre. Em **Udayagiri** (Madhya Pradesh), grutas escavadas no tempo de Chandragupta II (c. 400) têm o relevo de Vishnu como javali (*Varaha*). Estes locais mostram o início do **templo hindu de pedra**, a partir do santuário simples.',
  { img: 'ica-deogarh', leg: 'O templo de Dashavatara, em Deogarh (Uttar Pradesh), início do séc. VI.' },
  { h: 'Mahabalipuram' },
  'Na costa de Tamil Nadu, os reis **Pallavas** deixaram um conjunto invulgar: cinco *rathas* («carros») talhados cada um num só bloco de granito (séc. VII), um relevo gigante com mais de 25 m (a «Descida do Ganges» ou «Penitência de Arjuna», o debate sobre qual a cena persiste), e o **Templo da Costa**, de c. 700 – 728, já construído com blocos. Foi um laboratório para os templos do sul. Património Mundial desde 1984.',
  { img: 'ica-mahabalipuram', leg: 'O Templo da Costa em Mahabalipuram (Tamil Nadu), época Pallava, c. 700 – 728 d.C.' },
  { h: 'Aihole, Badami e Pattadakal' },
  'No norte de Karnataka, os **Chalukyas de Badami** (sécs. VI – VIII) experimentaram estilos do norte e do sul. Em **Aihole** há mais de uma centena de templos de épocas e formas diferentes, muitos como ensaios. **Pattadakal** (Património Mundial) reúne templos de estilo *nagara* (norte) e *dravida* (sul), como o de Virupaksha (c. 740), mandado erguer por uma rainha.',
  { h: 'Thanjavur e o país Chola' },
  'O **Brihadisvara** de Thanjavur, construído entre 1003 e 1010 por **Rajaraja I**, tem uma torre (*vimana*) de 13 andares e cerca de 63 m, coroada por um bloco de granito que a tradição diz pesar 80 toneladas (cifra discutida). Em frente, uma escultura de **Nandi**, o touro de Shiva, talhada num só bloco de granito (acrescentada mais tarde, no período Nayak, c. séc. XVI – XVII, e não no tempo de Rajaraja). O filho, **Rajendra I**, fundou nova capital, **Gangaikondacholapuram** (c. 1030), com outro grande templo. Os dois, com o templo de Darasuram, são os «Grandes Templos Vivos dos Cholas» (UNESCO, 1987 e 2004).',
  { img: 'ica-brihadisvara', leg: 'O Brihadisvara de Thanjavur (Tamil Nadu), consagrado em 1010 sob Rajaraja I.' },
  { h: 'Khajuraho' },
  'Os reis **Chandelas** construíram em Khajuraho, entre os sécs. X e XI, uns 85 templos, dos quais cerca de 25 sobrevivem. O **Kandariya Mahadeva** (c. 1029), com mais de 800 esculturas, é o maior. As esculturas de casais, tão famosas, são uma **minoria** (menos de 10 % do total, segundo estimativas), no meio de deuses, dançarinas, músicos, animais e cenas de guerra e de caça. Foi «redescoberto» por um engenheiro britânico em 1838 e é Património Mundial desde 1986.',
  { img: 'ica-khajuraho', leg: 'Templos do grupo ocidental de Khajuraho (Madhya Pradesh), séc. X – XI, época Chandela.' },
  { h: 'Konark' },
  'O **Templo do Sol** de Konark (Odisha), do séc. XIII (c. 1250, sob Narasimhadeva I), foi concebido como o carro de Surya, o deus-sol, puxado por sete cavalos sobre 24 rodas de pedra, que funcionam como relógios solares. A grande torre desabou há séculos, mas o conjunto é Património Mundial (1984).',
  { img: 'ica-konark', leg: 'Uma das 24 rodas de pedra do Templo do Sol de Konark, Odisha, séc. XIII.' },
  { h: 'Ujjain, Kusumapura e os centros de ciência' },
  'A astronomia indiana teve centros de saber, mais do que edifícios famosos: **Ujjain** (Madhya Pradesh), onde trabalharam Varahamihira, Brahmagupta e Bhaskara II, e cujo meridiano serviu de referência aos astrónomos indianos; **Kusumapura** (perto de Pataliputra, Patna), onde viveu Aryabhata; **Taxila** e **Nalanda**, universidades que atraíam estudantes; e, mais tarde, **Kerala**, com a escola de Madhava, ao longo do rio Bharathappuzha. A tradição liga Aryabhata a Nalanda, o que não está provado.',
  { h: 'Delhi: ferro e primeiras mesquitas' },
  'No complexo de Qutb, em Mehrauli (Delhi), ergue-se o **Pilar de Ferro**, junto da mesquita **Quwwat-ul-Islam** (iniciada em 1193) e do minarete de **Qutb** (iniciado c. 1199). A mesquita foi construída com colunas e blocos de templos hindus e jainistas reaproveitados, e mostra a primeira arquitetura do Sultanato de Deli (1206), já com mãos de artesãos indianos.',
  { h: 'Hampi e o sul no século XIV' },
  'A capital do Império de **Vijayanagara** (fundado em 1336) estende-se por mais de 40 km² nas margens do rio Tungabhadra. Palácios, mercados, tanques, templos como o de **Virupaksha** e o de **Vittala** (com o célebre «carro de pedra») mostram o estilo sulino tardio, com grandes pórticos e torres de entrada (*gopuras*). Foi visitada por viajantes estrangeiros, incluindo portugueses, já no século XVI.',
  { h: 'Patan e os poços escalonados' },
  'Nos climas secos do Gujarate e do Rajastão construíram-se **poços escalonados** (*vav*), obras de engenharia e de arte. O **Rani-ki-vav** de Patan (séc. XI, cerca de 1063) tem sete níveis de escadarias com mais de 500 esculturas principais, e é Património Mundial desde 2014.'
];

const sociedade = [
  { h: '1. Os números e o zero' },
  'A Índia usa há muito um sistema **decimal**: já os Vedas contam por potências de dez. O que se desenvolveu entre a Antiguidade tardia e a Idade Média foi a notação de **valor de posição com um sinal para o vazio**, o zero. A forma como nasceu é uma história de **séculos**, não de uma invenção única. Primeiro apareceram símbolos para os algarismos (a escrita *brahmi* tem sinais próprios para 1 a 9). Depois, a ideia de que a posição vale (cada lugar vale dez vezes o anterior). Depois, o sinal de **lugar vazio** (um ponto ou círculo). E por fim o zero como **número** com que se calcula.',
  { img: 'ica-escola-matematica', leg: 'Reconstrução artística: um mestre e discípulos a calcular numa tábua de areia, com folhas de palmeira e pontos como marcadores, c. séc. VI d.C.' },
  { caixa: 'Os marcos do zero', texto: [
    '**c. 458 d.C.:** o texto jainista *Lokavibhaga* usa valor de posição decimal com a palavra *shunya* («vazio»). **c. 499:** o *Aryabhatiya* descreve a regra de que cada lugar vale dez vezes o anterior. **628:** Brahmagupta dá **regras de cálculo** com o zero. **683:** inscrição de Sambor, no Camboja, com um zero em ponto (a mais antiga datada com certeza). **876:** inscrição de Gwalior, com um zero em círculo.',
    'O **manuscrito de Bakhshali**, em casca de bétula, encontrado em 1881 no atual Paquistão, usa um ponto como zero. As análises de radiocarbono de 2017 sugeriram datas do séc. III ao séc. X para as suas folhas, mas uma nova calibração, em 2024, situou o conjunto entre c. 800 e 1100 (sécs. IX – XII), e a sua datação continua em discussão. Não se deve, por isso, apresentá-lo como «o zero mais antigo».'
  ] },
  { img: 'ica-gwalior-zero', leg: 'Inscrição do templo de Chaturbhuj, em Gwalior (876 d.C.), com o zero em forma de pequeno círculo.' },
  { h: 'De Brahmagupta a Bhaskara' },
  '**Brahmagupta** (c. 598 – c. 668), no *Brahmasphutasiddhanta* (628), trata o zero e os negativos como números: um positivo mais um negativo, a diferença; uma «dívida» menos zero, uma dívida; e assim por diante. Errou ao dizer que zero a dividir por zero dá zero. Deu também a fórmula da área do quadrilátero cíclico e métodos para equações. **Bhaskara I** (séc. VII) comentou Aryabhata e deu uma aproximação racional ao seno. **Bhaskara II** (c. 1114 – c. 1185), no *Siddhanta Shiromani* (1150), usou o método *chakravala* para equações indeterminadas (como a de Pell) e tratou a divisão por zero como um «infinito», sem dizer o resultado.',
  { h: 'A trigonometria e o seno' },
  'Os gregos mediam cordas de círculos; os indianos passaram a usar **a metade da corda**, o *jya* ou *jiva*, que é o nosso seno. Aryabhata deu uma tabela de 24 valores do seno. Os árabes transcreveram *jiva* como *jiba*, depois lido *jayb* («dobra, seio»), e os tradutores latinos do séc. XII verteram por **sinus**: daí «seno». É um bom exemplo de como a matemática viajou, de Ujjain a Bagdade e a Toledo.',
  { h: 'Geometria, métrica e números famosos' },
  'Os *Sulba Sutras* davam receitas para construir altares de tijolo com áreas exatas; Pingala, a métrica; os matemáticos jainistas, grandes números, combinações e séries. **Virahanka** (séc. VII) e **Hemachandra** (séc. XII) descreveram, ao contar métricas poéticas, a sequência que a Europa conhece como de **Fibonacci** (1202). O valor de **π**, em Aryabhata, é 3,1416, a que ele chama «aproximado».',
  { h: 'A escola de Kerala' },
  'No séc. XIV, **Madhava de Sangamagrama** (c. 1340 – 1425) descobriu séries infinitas para o seno, o cosseno e o arco-tangente (a que a Europa chamou séries de **Gregory** e **Leibniz**, séc. XVII). Os seus sucessores, **Nilakantha Somayaji** (*Tantrasangraha*, c. 1500) e **Jyesthadeva** (*Yuktibhasha*, c. 1530, em malaiala, com demonstrações), continuaram o trabalho. Foi uma escola de génio, mas **não há provas** de que o seu saber tenha chegado à Europa, apesar de contactos comerciais e de missionários em Cochim. É apenas uma hipótese.',
  { img: 'ica-kerala-astronomia', leg: 'Reconstrução artística: astrónomos de Kerala, séc. XIV, a medir sombras e a calcular séries em folhas de palmeira.' },
  { h: '2. A astronomia e o calendário' },
  'A astronomia (*jyotisha*) servia para fixar o **calendário religioso**, escolher dias favoráveis e prever eclipses. Os textos de referência foram os *Siddhantas*, entre os quais o ***Surya Siddhanta*** (com uma versão original de c. sécs. IV – V e a forma atual revista por volta de 800, com alterações até ao séc. X). Varahamihira, no *Pancha-siddhantika*, resumiu cinco escolas, entre elas uma «romana» (*Romaka*) e uma «grega» (*Paulisa*), prova do contacto com a astronomia helenística, que os indianos adaptaram e melhoraram.',
  'O calendário indiano é **lunissolar**: meses lunares ajustados ao ano solar por meses intercalares. Há várias eras (a *Saka* começa em 78 d.C., a *Vikrama* em 57 a.C.), e as datas das inscrições devem ser convertidas com cuidado. A semana de sete dias, com nomes dos planetas, terá chegado à Índia pela astrologia helenística, segundo muitos historiadores.',
  { h: 'Aryabhata e a rotação da Terra' },
  'No *Aryabhatiya* (499), **Aryabhata** explicou os eclipses pelas sombras da Terra e da Lua, calculou o ano sideral em cerca de 365,2586 dias (muito próximo do valor atual) e defendeu que a **Terra roda** sobre o seu eixo, o que explica o movimento aparente das estrelas. **Não** propôs que a Terra girasse em torno do Sol; o seu modelo é geocêntrico, com epiciclos, embora alguns historiadores discutam se há aspetos «heliocêntricos» nos cálculos dos planetas. Astrónomos posteriores, como Brahmagupta, criticaram a rotação.',
  { h: 'Instrumentos e observação' },
  'Os indianos usavam o **gnómon** (haste vertical para medir sombras), o relógio de água (*ghati*), esferas armilares e quadrantes. Os grandes observatórios de pedra de Jaipur e Ujjain (séc. XVIII) são tardios, mas inspiram-se numa tradição antiga. Os astrónomos eram muitas vezes também poetas e matemáticos, e comentavam-se uns aos outros ao longo de séculos.',
  { h: '3. A medicina: Ayurveda' },
  'O **Ayurveda** («saber da vida») assenta em duas grandes compilações. A ***Charaka Samhita***, de medicina interna, é tradicionalmente ligada ao médico **Charaka**, e foi revista mais tarde. A ***Sushruta Samhita***, de cirurgia, ligada a **Sushruta**, tem camadas dos últimos séculos antes de Cristo aos séculos IV – V d.C. Os dois nomes são tradições; quais os textos mais antigos e quem foram os autores continua a ser discutido, e a forma atual resulta de revisões.',
  { img: 'ica-sushruta-ms', leg: 'Folha de um manuscrito antigo da Sushruta Samhita, em folha de palmeira (o exemplar mais antigo conservado, de 878 d.C., está no Nepal).' },
  { h: 'A teoria e a prática' },
  'A teoria clássica fala de três humores ou **doshas** (*vata*, *pitta*, *kapha*) e do equilíbrio entre eles. É um quadro tradicional, que **não** corresponde aos conceitos da medicina moderna. Mas os textos são cheios de observação clínica: sintomas, diagnóstico, dieta, higiene, uma farmacopeia de centenas de plantas (a *Sushruta Samhita* enumera mais de 700) e minerais, e normas de **ética médica** para o médico e o estudante.',
  { h: 'A cirurgia de Sushruta' },
  'A *Sushruta Samhita* descreve mais de 1100 doenças e dezenas de instrumentos de metal (bisturis, pinças, sondas), os métodos para os afiar e esterilizar com fogo, e operações como a extração de cálculos, o tratamento de fístulas e da catarata. Ensina a treinar os alunos em **frutos, bexigas e peles de animais** antes de operarem pessoas, e a estudar o corpo humano num **cadáver** preparado em água corrente. É célebre a **reconstrução do nariz** com um retalho da face, técnica que os cirurgiões europeus conheceram nos séculos XVIII e XIX através de relatos na Índia.',
  { img: 'ica-cirurgia', leg: 'Reconstrução artística: um mestre cirurgião treina alunos a fazer incisões em frutos e peles antes de operar, de acordo com o método descrito na Sushruta Samhita.' },
  { h: 'Hospitais, ervas e animais' },
  'Os éditos de Ashoka (séc. III a.C.) falam de tratamento médico para **pessoas e animais** e de ervas plantadas. O peregrino chinês **Fa-Xian** (c. 400 d.C.) descreveu em Pataliputra hospitais gratuitos mantidos por nobres. Existiam tratados para elefantes e cavalos. O **manuscrito de Bower**, em casca de bétula (c. séc. V), com receitas médicas, foi encontrado em Kucha (Ásia Central), mostrando a circulação do saber.',
  { img: 'ica-hospital-pataliputra', leg: 'Reconstrução artística: um hospital de caridade em Pataliputra, c. 400 d.C., como o descrito pelo peregrino Fa-Xian.' },
  { h: '4. Metalurgia e técnica' },
  'Os ferreiros indianos eram dos melhores do mundo antigo. O **Pilar de Ferro** (c. 400 d.C.), de ferro forjado em blocos soldados a quente, tem cerca de 7,2 m de altura e mais de 6 toneladas. A razão de quase não enferrujar é o **teor de fósforo** (c. 0,25 %), que forma uma película protetora de fosfato de ferro. A inscrição em sânscrito louva um rei chamado «Chandra», habitualmente identificado com **Chandragupta II**. O pilar esteve noutro local e só foi para Delhi na Idade Média (por quem e quando, é debatido).',
  { img: 'ica-ferro-forja', leg: 'Reconstrução artística: ferreiros indianos a forjar um grande bloco de ferro, c. séc. V d.C.' },
  'No sul, em Tamil Nadu e Karnataka, produzia-se **aço de cadinho**, o *wootz*: ferro e carbono aquecidos em cadinhos fechados, com resultados de grande dureza. Há indícios arqueológicos desde c. séc. III a.C. no Tamil Nadu. O *wootz*, exportado em lingotes, esteve na origem das lâminas famosas do Médio Oriente (as chamadas «de Damasco»). A Índia dominou também a destilação do **zinco** (Zawar, no Rajastão, em escala industrial, a partir de c. séc. XII, segundo a datação mais citada; a mineração é muito anterior) e o trabalho do cobre e do bronze.',
  { h: 'Água, cultivo e outras técnicas' },
  'A engenharia hidráulica foi essencial: o **lago Sudarshana**, em Girnar, construído no tempo dos Máurias e reparado em c. 150 d.C. (segundo a inscrição de Rudradaman); a barragem de **Kallanai** (Grand Anicut), no rio Kaveri, tradicionalmente atribuída a Karikala Chola (séc. II d.C.) e ainda em uso; os grandes tanques de templo e os poços escalonados. Foram indianos os primeiros métodos conhecidos de **cristalização do açúcar** de cana (período Gupta), o cultivo do algodão e do índigo, e os tecidos de algodão que fizeram a fama do comércio indiano.',
  { h: '5. Jogos e o Kama Sutra' },
  'O **chaturanga**, antepassado do xadrez, e o *pachisi*, antepassado do ludo, são jogos indianos de tabuleiro. Os mais antigos testemunhos seguros do chaturanga são do séc. VI. O jogo das serpentes e escadas (*moksha patam*) serviu para ensinar moral.',
  'O ***Kama Sutra***, de **Vatsyayana Mallanaga** (provavelmente séc. III d.C.), é muitas vezes mal compreendido. É um tratado de 7 «livros» e 36 capítulos sobre **kama**, o prazer e o amor, um dos quatro objetivos da vida (com *dharma*, *artha* e *moksha*). A maior parte trata de cortejo, casamento, vida de casa, deveres da esposa e da cortesã, e de uma educação nas **64 artes** (canto, dança, pintura, perfumes, jogos). A parte sobre a união física é apenas **um dos livros**. A tradução inglesa de Richard Burton (1883) deu-lhe fama escandalosa na Europa, e distorceu-lhe o conteúdo.',
  { h: '6. Arquitetura: estupas, grutas e templos' },
  'Os primeiros edifícios sagrados indianos eram de madeira, bambu e tijolo, e desapareceram. A arquitetura de pedra começa com Ashoka (séc. III a.C.). Podem distinguir-se três formas principais. O **estupa**, monte hemisférico de relíquias, com guarda-sol e balaustrada. A **gruta escavada**, usada por budistas, hindus e jainistas, que imita em pedra a arquitetura de madeira (os salões *chaitya* têm nervuras de teto que reproduzem vigas). E o **templo** construído, que nasce na época Gupta.',
  { img: 'ica-estupa-construcao', leg: 'Reconstrução artística: pedreiros e escultores a erguer a balaustrada de um estupa, séc. I a.C., com andaimes de bambu.' },
  { h: 'O templo hindu' },
  'O templo hindu clássico tem um pequeno santuário (*garbhagriha*, «útero») onde fica a imagem, uma torre sobre ele, e salões à frente. Os tratados de arquitetura (*Vastu Shastra*, *Manasara*, *Mayamata*) dão regras de proporção e orientação, ligadas à astronomia e ao ritual. Distinguem-se dois grandes estilos: o ***nagara***, do norte, com torre curvilínea (*shikhara*), e o ***dravida***, do sul, com torre em andares (*vimana*) e grandes portas (*gopuras*). Há também um estilo misto do Decão (*vesara*), de debate terminológico.',
  { h: 'Gupta, Pallavas, Chalukyas, Cholas' },
  'A evolução pode seguir-se em quatro passos: os pequenos templos **Gupta** (Sanchi, Deogarh, séc. V – VI); os templos **Chalukya** e **Pallava** (séc. VII – VIII), com Aihole, Pattadakal, Mahabalipuram e o Kailasanatha de Kanchipuram; a monumentalidade **Chola** (séc. XI), com o Brihadisvara; e a riqueza decorativa dos **Hoysalas** (Belur, Halebidu, séc. XII – XIII), com pedra-sabão esculpida como renda, e de **Vijayanagara**.',
  { h: 'Quem construía?' },
  'Os templos eram obra de reis, rainhas, mercadores e **guildas** (*shreni*), que pagavam e deixavam o nome em inscrições. Os mestres-de-obras (*sthapati*) e os escultores (*shilpin*) formavam famílias de ofício, e o nome de poucos chegou até nós: em Thanjavur, a tradição liga a obra a um mestre chamado **Kunjara Mallan Rajaraja Perunthachan**. No Kailasa de Ellora, a técnica de escavar **de cima para baixo** exigia um plano rigoroso, porque o erro era irreparável.',
  { img: 'ica-kailasa-escavacao', leg: 'Reconstrução artística: escultores a talhar o Kailasa de Ellora de cima para baixo, séc. VIII, com cinzéis de ferro e andaimes de madeira.' },
  { h: '7. Escultura' },
  'Antes do Buda, a escultura monumental de pedra aparece no tempo de Ashoka: os pilares e o **capitel de Sarnath**, com a famosa polidez máuria, e figuras como a **Yakshi de Didarganj** (Museu de Patna, tradicionalmente máuria, de datação debatida). Em Bharhut e Sanchi, os relevos narram os *Jatakas* e as vidas do Buda, representado apenas por símbolos.',
  { img: 'ica-bharhut', leg: 'Relevo da balaustrada do estupa de Bharhut (séc. II a.C.), hoje no Museu Indiano de Calcutá.' },
  { h: 'O Buda em figura humana' },
  'Sob os Kushanas surgem, em paralelo, as primeiras imagens humanas do Buda, nas escolas de **Gandhara** e de **Mathura**. A primeira, mais naturalista, com cabelo ondulado, drapeado pesado e traços que lembram Apolo; a segunda, mais indiana, com ombros largos e roupa colada ao corpo. Na época Gupta, a escola de **Sarnath** criou o Buda ideal, calmo, de olhos descidos e manto leve. Esta iconografia, com gestos das mãos (*mudras*) e marcas físicas codificadas, correu a Ásia com o budismo.',
  { img: 'ica-buda-gandhara', leg: 'Buda de pé em estilo de Gandhara (xisto), séc. II – III d.C., com drapeado de influência helenística.' },
  { img: 'ica-buda-mathura', leg: 'Buda sentado em arenito vermelho de Mathura, período Kushana, séc. II d.C.' },
  { img: 'ica-buda-sarnath', leg: 'Buda a pregar, em arenito, estilo de Sarnath, época Gupta (séc. V), Museu de Sarnath.' },
  { h: 'Os bronzes Chola' },
  'No sul, a dinastia **Chola** (séc. IX – XIII) é célebre pelos **bronzes** fundidos pelo método da **cera perdida**: modela-se a figura em cera, cobre-se de argila, aquece-se para fundir a cera e deita-se o metal no molde. O mais famoso é o **Shiva Nataraja**, dançando num círculo de chamas, com um pé sobre um anão (a ignorância). As imagens eram levadas em procissão nas festas, vestidas e adornadas. Têm o rigor das regras dos tratados e a vida de cada oficina. Os descendentes dos ofícios ainda trabalham em Swamimalai (Tamil Nadu). Uma rainha, **Sembiyan Mahadevi**, é associada ao patrocínio de templos e bronzes no séc. X.',
  { img: 'ica-bronze-chola', leg: 'Reconstrução artística: oficina de fundição de bronzes de estilo Chola pelo método da cera perdida, séc. XI.' },
  { h: '8. Pintura' },
  'A pintura indiana antiga conservou-se quase só nas **grutas**. As pinturas de **Ajanta** foram feitas sobre gesso seco (técnica chamada *fresco secco*), com pigmentos minerais e vegetais (ocres, verde, negro de fumo, branco de cal e outros), e mostram a vida do Buda, os *Jatakas*, cortes, mercadores, músicos, mulheres, animais e flores. As melhores estão nas Grutas 1, 2, 16 e 17 (séc. V). Há restos de pintura em Bagh, Sittanavasal (Jain, séc. VII) e Ellora. Em c. séc. V – VII, um texto, o *Vishnudharmottara*, tem um tratado de pintura.',
  'Fora das grutas, a pintura chegou-nos em **manuscritos ilustrados**: folhas de palmeira de mosteiros budistas do leste (Pala, séc. XI – XII) e manuscritos jainistas do Gujarate (séc. XII – XV). As cortes de Vijayanagara e dos sultanatos tiveram os seus pintores. As técnicas de miniatura foram a base para as escolas de pintura mogol e rajput dos séculos seguintes.',
  { h: '9. Teatro' },
  'O teatro indiano tem a sua teoria no ***Natyashastra*** («tratado da arte dramática»), atribuído ao sábio **Bharata**, de 36 capítulos e c. 6000 versos (a versão completa mais antiga é posterior a c. 200 a.C.). Trata de composição dramática, construção de teatros, atuação, gestos, maquilhagem, trajes, música e dança. Descreve três tipos de teatro (retangular, quadrado e triangular) e uma plateia para centenas de espectadores.',
  { img: 'ica-teatro-sanscrito', leg: 'Reconstrução artística: representação de teatro sânscrito num salão de corte, com músicos, atores de maquilhagem expressiva e um público de cortesãos, c. séc. V d.C.' },
  { h: 'O rasa' },
  'A ideia central é o **rasa** («sabor»): o espetáculo não imita a vida, mas provoca no espectador uma emoção estilizada e partilhada. O *Natyashastra* enumera **oito rasas**: erótico, cómico, patético, furioso, heroico, terrível, repugnante e maravilhoso; um nono, o **sereno** (*shanta*), foi acrescentado mais tarde (e é debatido). O drama sânscrito tem regras: não se mostram a morte em cena nem o fim trágico, e usa-se o sânscrito para personagens nobres, o prácrito para mulheres e personagens menores, e há um bobo (*vidushaka*).',
  { h: 'Dramaturgos' },
  'Os grandes dramaturgos são **Bhasa** (treze peças descobertas em 1912, em Kerala, de datação debatida), **Kalidasa** (*Abhijnanashakuntalam*, «Shakuntala e o anel do reconhecimento»), **Shudraka** (*Mricchakatika*, «O carrinho de barro», uma comédia social com uma cortesã e um brâmane), **Vishakhadatta** (*Mudrarakshasa*, sobre Chanakya e Chandragupta Maurya), o rei **Harsha** e **Bhavabhuti**. O teatro sânscrito vive hoje no **Kutiyattam** de Kerala, uma das mais antigas formas de teatro vivas do mundo, reconhecida pela UNESCO.',
  { h: '10. Música' },
  'A música indiana tem raízes nos cantos védicos (o *Samaveda*), com três e depois sete notas. O *Natyashastra* tem capítulos sobre escalas (as sete notas *sa ri ga ma pa dha ni*), sobre **22 microtons** (*shruti*), sobre instrumentos (cordas, sopros, tambores e idiofones) e sobre ritmos. A palavra **raga** (melodia com carácter e hora próprios) surge em textos tardios, como o *Brihaddeshi* (séc. VI – VIII). O *Sangita Ratnakara* de **Sarngadeva** (séc. XIII) é a grande síntese.',
  { img: 'ica-moeda-lirista', leg: 'Moeda de ouro de Samudragupta (séc. IV), do tipo «do tocador de lira»: o rei toca uma veena.' },
  'Dos instrumentos, a **veena** (cordas), a flauta de bambu, os tambores (*mridangam*, *dhol*) e os pratos eram os mais comuns. A partir do séc. XIII, com o Sultanato de Deli e a influência persa (o poeta e músico **Amir Khusrau**, séc. XIII – XIV, é frequentemente referido), as tradições do norte (**hindustani**) e do sul (**carnática**) foram-se separando, embora com raízes comuns; a data e o processo exatos são discutidos.',
  { img: 'ica-danca-templo', leg: 'Reconstrução artística: uma dançarina e músicos num salão de templo Chola, séc. XI, com lamparinas de bronze.' },
  { h: '11. Dança' },
  'O *Natyashastra* descreve **108 karanas**, posturas e movimentos de dança, e codifica os gestos das mãos e do rosto. Estas posições vêem-se esculpidas nos templos, como no portal de **Chidambaram**. Nos grandes templos do sul, as dançarinas (*devadasis*) faziam parte do culto: as inscrições de Thanjavur falam de centenas de dançarinas e músicos ao serviço do Brihadisvara. As danças clássicas modernas (**Bharatanatyam**, **Kathak**, **Odissi** e outras) foram reconstruídas e nomeadas sobretudo nos séculos XIX e XX a partir de tradições locais e dos tratados, e não são uma continuação linear.',
  { h: '12. A literatura sânscrita' },
  'O sânscrito foi a língua da corte, da religião e da ciência. Depois dos Vedas e das epopeias (*Mahabharata*, *Ramayana*, tratados na página das religiões), floresceu a **poesia de corte** (*kavya*), com **Ashvaghosha** (*Buddhacharita*, vida do Buda, séc. I – II), **Kalidasa**, **Bharavi**, **Magha**, **Dandin** e **Bana** (*Kadambari*, séc. VII). Os versos de **Bhartrihari** e de **Amaru** são poemas curtos de amor, de sabedoria e de renúncia. **Kalhana** escreveu, c. 1148, a *Rajatarangini*, crónica de Caxemira, uma das poucas «histórias» indianas.',
  { h: 'O Panchatantra e as fábulas' },
  'O **Panchatantra** («cinco livros»), atribuído a **Vishnu Sharma**, é uma coleção de fábulas de animais para ensinar política e conduta a príncipes, composta entre c. 300 a.C. e 300 d.C. (data incerta). Foi traduzido para **persa médio** no séc. VI, para **árabe** (como *Kalila e Dimna*, c. 750) e daí para hebraico, latim e línguas europeias, e inspirou **La Fontaine**. Os *Jatakas* budistas contam as vidas anteriores do Buda em histórias que também correram o mundo.',
  { img: 'ica-manuscrito-palma', leg: 'Reconstrução artística: escribas a gravar e a copiar um texto em folhas de palmeira, com estilete, num mosteiro, c. séc. VII.' },
  { h: '13. Literatura em tâmil e outras línguas' },
  'O **tâmil**, língua dravídica, tem uma literatura clássica independente do sânscrito. A **poesia Sangam** (c. séc. I – III d.C., datação debatida) é formada por antologias (*Ettuthokai*, *Pattuppattu*) de poemas de amor (*akam*) e de guerra e elogio (*puram*), de poetas de todas as origens sociais, incluindo mulheres, como **Avvaiyar**. A gramática *Tolkappiyam* é a base da língua. Seguem-se as epopeias *Silappatikaram* e *Manimekalai*, a poesia devocional dos **Alvares** e **Nayanares** (séc. VI – IX) e, no mundo das pessoas, o **Tirukkural**, de **Tiruvalluvar**: 1330 dísticos em 133 capítulos, sobre virtude, riqueza e amor. Os especialistas datam-no entre c. séc. V e VI, ou antes (debatido).',
  'Outras línguas ganharam literatura escrita mais tarde: em **kannada**, a de **Pampa** (séc. X); em **telugu**, a de **Nannaya** (séc. XI); em **malaiala**, a de Kerala, e em **prácrito**, a *Gatha Saptashati*, de poemas de amor atribuídos a Hala (séc. I – III). Os textos budistas em **pali** formaram um grande cânone.',
  { h: '14. Como se transmitia o saber' },
  'Durante séculos o saber foi **oral**: memorizava-se, de mestre a discípulo (*guru-shishya*), com técnicas de recitação rigorosas. A escrita (*brahmi* desde o séc. III a.C.) usou a **folha de palmeira** (gravada com estilete e coberta de tinta), a **casca de bétula** (no norte e em Caxemira), o cobre (para registar doações de terras) e a pedra. O papel só se generalizou depois da chegada dos muçulmanos. Os mosteiros e universidades (**Taxila**, **Nalanda**, **Vikramashila**) reuniram bibliotecas e mestres; os manuscritos mais antigos que chegaram aos nossos dias (Bakhshali, Bower, Gilgit) vêm de zonas secas ou de esconderijos.',
  { h: 'A viagem do saber' },
  'A matemática e a astronomia indianas chegaram ao mundo árabe a partir do séc. VIII (segundo a tradição, um texto astronómico indiano foi apresentado ao califa al-Mansur em Bagdade, c. 770). **Al-Khwarizmi** (c. 825) escreveu sobre os algarismos indianos, e **Fibonacci** (*Liber Abaci*, 1202) levou-os à Europa, onde se chamaram «arábicos» por terem chegado pelos árabes. A medicina de Charaka e Sushruta foi traduzida para árabe e persa; as fábulas, os jogos e a música seguiram também. A arte budista levou os estupas e os Budas à China, ao Japão, ao Sudeste Asiático e ao Tibete.'
];

const personalidades = [
  'Nesta lista misturam-se figuras históricas bem documentadas (como Aryabhata ou Rajaraja I) e outras que são sobretudo tradições (Charaka, Sushruta, Bharata). As datas são aproximadas e as incertezas estão assinaladas.',
  { h: 'Charaka (c. séc. I – II d.C., tradição)' },
  'O nome de Charaka está ligado à ***Charaka Samhita***, o grande tratado de medicina interna do Ayurveda. A tradição liga-o à corte dos Kushanas, mas pouco se sabe com certeza sobre ele; o texto atual foi revisto e completado mais tarde (a tradição indica Dridhabala, séc. IV). Insiste na prevenção, na dieta e na ética do médico, e na importância de observar o doente.',
  { h: 'Sushruta (tradição: séc. VI a.C.; texto: últimos séculos a.C. – séc. V d.C.)' },
  'A tradição fá-lo um cirurgião de Varanasi. A *Sushruta Samhita* que leva o seu nome descreve instrumentos, anatomia e operações, entre elas a reconstrução do nariz. O texto é obra de várias mãos e revisões, e a datação é muito discutida. É frequentemente chamado «pai da cirurgia» na Índia, designação moderna e simbólica.',
  { h: 'Bharata (tradição; texto c. 200 a.C. – 200 d.C.)' },
  'O sábio a quem se atribui o ***Natyashastra***. É possível que seja uma figura lendária e que o texto seja obra coletiva. A tradição diz que Bharata ensinou o teatro a cem filhos, e que recebeu a arte dos deuses. Seja como for, o tratado moldou o teatro, a dança e a música da Índia.',
  { h: 'Vatsyayana Mallanaga (c. séc. III d.C.)' },
  'O autor do ***Kama Sutra***. Sabe-se muito pouco da sua vida: o texto sugere um homem culto, de ambiente urbano, e conhecedor de textos anteriores. A obra reúne conselhos de uma vida «bem vivida», e não se limita ao amor físico; teve comentadores, como Yashodhara (séc. XIII).',
  { h: 'Kalidasa (c. séc. IV – V d.C., debatido)' },
  'O maior poeta e dramaturgo em sânscrito. Escreveu o poema *Meghaduta* («O mensageiro nuvem», em que um yaksha exilado envia uma mensagem à esposa por uma nuvem), os poemas épicos *Raghuvamsha* e *Kumarasambhava*, e peças como *Abhijnanashakuntalam*. Nada se sabe de seguro da sua vida; há quem o ligue à corte de Chandragupta II, mas é tradição. A tradução de *Shakuntala* para inglês por William Jones (1789) e para alemão encantou poetas como Goethe.',
  { img: 'ica-kalidasa-shakuntala', leg: 'Pintura de Raja Ravi Varma (1870) com Shakuntala, personagem da peça de Kalidasa, a olhar para trás para o rei Dushyanta.' },
  { h: 'Aryabhata (476 – c. 550 d.C.)' },
  'Associado a Kusumapura (perto de Patna), onde viveu e trabalhou, escreveu o *Aryabhatiya* aos 23 anos, em 499 (segundo o cálculo que se faz a partir do próprio texto). Apresentou o valor de π, tabelas de senos, o método *kuttaka* para equações, uma explicação dos eclipses e a rotação diária da Terra. A tradição liga-o a Nalanda. Alguns estudiosos defendem que seria de Kerala; a maioria aceita Kusumapura (Bihar) como o seu meio de trabalho, e o local de nascimento é incerto.',
  { img: 'ica-aryabhata-estatua', leg: 'Estátua moderna de Aryabhata no IUCAA, Pune: uma representação imaginada, pois não existe nenhum retrato antigo.' },
  { h: 'Varahamihira (c. 505 – 587 d.C.)' },
  'Astrónomo, astrólogo e polígrafo de Ujjain. O *Pancha-siddhantika* resume cinco sistemas de astronomia, incluindo influências gregas, e a *Brihat Samhita* é uma enciclopédia sobre tempo, cometas, arquitetura, pedras preciosas, plantas e presságios. Foi um defensor da astrologia, e também um observador cuidadoso, que criticou a rotação da Terra.',
  { h: 'Brahmagupta (c. 598 – c. 668 d.C.)' },
  'Nascido em Bhillamala (Rajastão), trabalhou em Ujjain. O *Brahmasphutasiddhanta* (628) trata de astronomia, mas o seu valor maior é a matemática: regras de cálculo com zero e negativos, fórmula para o quadrilátero cíclico e solução de equações quadráticas e de Pell. Cometeu o erro de dizer que 0 ÷ 0 = 0. Escreveu ainda o *Khandakhadyaka* (665).',
  { h: 'Bhaskara II (c. 1114 – c. 1185 d.C.)' },
  'Matemático e astrónomo, chefe do observatório de Ujjain. O *Siddhanta Shiromani* (1150) tem quatro partes, entre elas o ***Lilavati***, de aritmética, com problemas em verso para um estudante. Uma lenda popular diz que o livro foi escrito para consolar a filha, mas não é confirmada. Desenvolveu o método *chakravala* e ideias de movimento instantâneo dos astros que antecipam o cálculo.',
  { h: 'Rajaraja I (r. 985 – 1014 d.C.)' },
  'O imperador **Chola** que unificou o sul, conquistou o norte de Sri Lanka e as Maldivas, e mandou construir o **Brihadisvara** de Thanjavur (1003 – 1010). As inscrições do templo registam doações de terras, ouro, bronzes e pessoal (músicos, dançarinas, cozinheiros), com uma contabilidade pormenorizada. Foi um patrono de artes e de templos, e o filho, Rajendra I, continuou a sua obra.',
  { h: 'Sarngadeva (séc. XIII)' },
  'Ligado à corte do rei **Simhana** (r. 1210 – 1247) dos Yadavas de Devagiri, foi contabilista e músico, e escreveu o *Sangita Ratnakara*, em sete capítulos, a maior síntese medieval da música (ragas, ritmos, instrumentos) e da dança indianas. É lido por músicos do norte e do sul, e foi muito comentado.',
  { h: 'Madhava de Sangamagrama (c. 1340 – 1425)' },
  'Matemático e astrónomo de Kerala, fundador da escola que leva o seu nome. Descobriu séries infinitas para o seno, o cosseno e o arco-tangente, e um cálculo de π muito exato. As suas obras originais perderam-se quase todas e conhece-se o trabalho através dos continuadores (Nilakantha, Jyesthadeva). Não está provado que o seu trabalho tenha chegado à Europa.',
  { h: 'Tiruvalluvar (data debatida)' },
  'Poeta tâmil, autor do **Tirukkural**. Quase nada se sabe de seguro da sua vida: as biografias são lendas tardias. A obra, com 1330 dísticos sobre virtude, governo e amor, é uma das mais traduzidas da literatura indiana (o Tamil Nadu comemora-o com uma grande estátua em Kanyakumari). Não pertence a uma religião em particular, e é reivindicada por várias.',
  { img: 'ica-tiruvalluvar-estatua', leg: 'Estátua de Tiruvalluvar em Kanyakumari (Tamil Nadu), inaugurada em 2000: uma homenagem moderna, não um retrato.' }
];

const legado = [
  { h: 'O que nos deixaram' },
  { lista: [
    '**O zero e os algarismos:** a notação decimal de posição, com zero, é a base da matemática e da informática modernas. Chegou à Europa pelos árabes.',
    '**O seno e a trigonometria:** a palavra «seno» vem, por árabe e latim, do sânscrito *jiva*.',
    '**A cirurgia e o Ayurveda:** a reconstrução do nariz da *Sushruta Samhita* e uma medicina tradicional que ainda se pratica na Índia e no mundo.',
    '**O aço de cadinho e o ferro do Pilar de Delhi:** o *wootz* esteve na origem de lâminas famosas, e o pilar é objeto de estudo de metalurgistas modernos.',
    '**Os estupas e os templos:** a arquitetura budista e hindu inspirou Borobudur (Java), Angkor Wat (Camboja), as pagodas chinesas e japonesas e os templos de todo o Sudeste Asiático.',
    '**A imagem do Buda:** as formas de Gandhara, de Mathura e de Sarnath são a base de todas as imagens budistas posteriores.',
    '**O teatro, a música e a dança:** o *rasa*, o *raga* e o *tala* continuam a ser a gramática das artes do espetáculo na Índia.',
    '**As fábulas:** do *Panchatantra* a *Kalila e Dimna* e a La Fontaine.'
  ] },
  { img: 'ica-panchatantra', leg: 'Ilustração de um manuscrito árabe de Kalila e Dimna (séc. XIII), versão árabe de fábulas do Panchatantra indiano.' },
  { h: 'Arte e arquitetura' },
  'Os edifícios indianos influenciaram a Ásia: o **estupa** deu origem ao *chedi* tailandês, ao *dagoba* do Sri Lanka e à pagoda; os **templos** de Shiva e de Vishnu inspiraram Angkor, Prambanan e Borobudur; as **imagens** do Buda de Gandhara chegaram à China e ao Japão. Um achado muito citado é a **estatueta de marfim** com origem indiana (a «Lakshmi de Pompeia», séc. I d.C.), encontrada em Pompeia em 1938, hoje no Museu Arqueológico de Nápoles (provavelmente fabricada em Bhokardan, no Decão, e não em Mathura, como se pensou de início), que mostra as trocas com Roma.',
  { img: 'ica-pompeia-lakshmi', leg: 'A «Lakshmi de Pompeia», estatueta de marfim de origem indiana (séc. I d.C.), encontrada em Pompeia em 1938, Museu Arqueológico Nacional de Nápoles.' },
  { h: 'A redescoberta' },
  'A arte e a ciência indianas foram redescobertas pelos europeus a partir do século XVIII e, sobretudo, no XIX. Ajanta foi «descoberta» em 1819; Khajuraho em 1838; Bharhut em 1873 (por **Alexander Cunningham**); a escrita brahmi foi decifrada em 1837 por **James Prinsep**. Os matemáticos europeus estudaram os textos de Brahmagupta e de Bhaskara no séc. XIX, e as séries de Kerala só foram dadas a conhecer ao Ocidente em 1835 (por **Charles Whish**) e estudadas a fundo no séc. XX.',
  { h: 'Património em perigo e destruição' },
  'Muita arte foi perdida por clima, abandono e guerra. Mosteiros e templos foram destruídos ou reconvertidos em vários momentos (as mesquitas de Delhi usaram material de templos; Nalanda foi saqueada em c. 1200); no Afeganistão, os dois Budas gigantes de **Bamiyan** (séc. VI) foram dinamitados em 2001. A Índia e outros países trabalham hoje na conservação, e a UNESCO protege dezenas de sítios.',
  { h: 'A Índia e Portugal' },
  'Quando **Vasco da Gama** chegou a Calecute em 1498, a tradição científica de Kerala estava no seu auge. Os portugueses encontraram, em Goa e em Cochim, a medicina e a botânica indianas: **Garcia de Orta**, em Goa, publicou em 1563 os *Colóquios dos Simples e Drogas da Índia*, em que usa o saber de médicos locais. A arte indiana também deixou marcas na arte luso-indiana (marfins de Goa, arquitetura de igrejas com motivos locais).',
  { img: 'ica-rani-ki-vav', leg: 'Escadaria do poço escalonado Rani-ki-vav, em Patan (Gujarate), séc. XI, Património Mundial.' },
  { h: 'Onde visitar' },
  { lista: [
    '**Ajanta e Ellora (Maharashtra):** as grutas pintadas e o templo de Kailasa. Um dia para cada.',
    '**Sanchi (Madhya Pradesh):** o estupa e as portas esculpidas.',
    '**Khajuraho (Madhya Pradesh):** os grupos de templos Chandela, ao nascer do sol.',
    '**Mahabalipuram e Thanjavur (Tamil Nadu):** a arte dos Pallavas e dos Cholas, e o Museu de Thanjavur com bronzes.',
    '**Hampi (Karnataka):** as ruínas de Vijayanagara.',
    '**Konark (Odisha):** o Templo do Sol.',
    '**Delhi:** o Pilar de Ferro, no complexo de Qutb, e o Museu Nacional, com esculturas e bronzes.',
    '**Sarnath (Uttar Pradesh):** o museu, com o capitel dos leões e o Buda Gupta.',
    '**Em Portugal:** o Museu Nacional de Arte Antiga e o Museu do Oriente (Lisboa) têm peças indianas e luso-indianas.'
  ] },
  { img: 'ica-hampi-vittala', leg: 'O «carro de pedra» no templo de Vittala, em Hampi (Karnataka), séc. XVI, Vijayanagara.' },
  { h: 'Mitos e exageros a evitar' },
  { lista: [
    '**«A Índia inventou tudo»:** muitas ideias circularam entre Índia, Grécia, Pérsia e Mesopotâmia. A Índia deu contributos decisivos, mas as histórias são de troca.',
    '**O zero «inventado» por uma pessoa:** foi um processo de séculos, com vários nomes.',
    '**Aviões e cirurgia plástica «modernos» na Antiguidade:** afirmações sem base nos textos.',
    '**O Kama Sutra como um manual erótico:** é um tratado sobre a vida e o prazer, e a maior parte trata de outros assuntos.',
    '**Os templos de Khajuraho como «templos eróticos»:** a escultura erótica é uma pequena parte.',
    '**O Pilar de Ferro como «mistério»:** a ausência de ferrugem tem explicação química conhecida.'
  ] },
  { caixa: 'Resumo final', texto: 'Ciência e arte, na Índia clássica e medieval, partilharam o gosto de **ordenar** o mundo em regras e de lhe dar **forma** em pedra, bronze, som e palavra. O que sobrevive é uma fração pequena do que se produziu, mas basta para colocar a Índia entre as grandes fontes do pensamento científico e da arte do mundo.' }
];

const quiz = [
  { p: 'Qual é o texto indiano antigo que dá regras de cálculo com o zero e com números negativos?', op: ['Aryabhatiya', 'Brahmasphutasiddhanta', 'Natyashastra', 'Sushruta Samhita'], certa: 1, exp: 'Brahmagupta escreveu o Brahmasphutasiddhanta em 628, com as primeiras regras escritas para operar com zero e negativos.' },
  { p: 'De onde vem a palavra «seno»?', op: ['Do grego sinos', 'Do chinês', 'Do persa sin', 'Do sânscrito jiva, por via árabe e latina'], certa: 3, exp: 'O sânscrito jiva (corda) foi transcrito em árabe como jiba/jayb e traduzido para o latim sinus, no séc. XII.' },
  { p: 'O que defendeu Aryabhata sobre a Terra?', op: ['Que gira em torno do Sol', 'Que é plana', 'Que roda sobre o seu eixo', 'Que está parada'], certa: 2, exp: 'No Aryabhatiya (499) defende a rotação diária da Terra; o seu modelo era, no entanto, geocêntrico.' },
  { p: 'Porque é que o Pilar de Ferro de Delhi quase não enferruja?', op: ['É de aço inoxidável', 'Tem uma película protetora ligada ao fósforo do ferro', 'Foi pintado com ouro', 'Está sempre debaixo de água'], certa: 1, exp: 'O teor de fósforo (c. 0,25 %) forma uma camada protetora de fosfato de ferro hidratado.' },
  { p: 'Qual é a obra médica indiana famosa pela cirurgia, incluindo a reconstrução do nariz?', op: ['Charaka Samhita', 'Kama Sutra', 'Sushruta Samhita', 'Arthashastra'], certa: 2, exp: 'A Sushruta Samhita descreve a rinoplastia com retalho da face e dezenas de instrumentos cirúrgicos.' },
  { p: 'Que tratado antigo codifica o teatro, a música e a dança indianos?', op: ['Natyashastra', 'Manusmriti', 'Panchatantra', 'Lilavati'], certa: 0, exp: 'O Natyashastra, atribuído a Bharata, desenvolve a teoria do rasa e das artes do espetáculo.' },
  { p: 'Como foi escavado o templo de Kailasa, em Ellora?', op: ['De baixo para cima, bloco a bloco', 'De cima para baixo, numa só rocha', 'Com explosivos', 'Foi construído com tijolos'], certa: 1, exp: 'Os escultores começaram no topo da rocha e escavaram para baixo, esculpindo o templo inteiro.' },
  { p: 'Onde estão as grutas budistas pintadas com frescos do séc. V d.C.?', op: ['Elephanta', 'Karli', 'Khajuraho', 'Ajanta'], certa: 3, exp: 'Em Ajanta (Maharashtra), com mecenas dos Vakatakas, c. 460 – 480.' },
  { p: 'Que dinastia construiu o Brihadisvara de Thanjavur, consagrado em 1010?', op: ['Gupta', 'Pallava', 'Chola', 'Chandela'], certa: 2, exp: 'Foi obra do imperador Chola Rajaraja I.' },
  { p: 'Que técnica se usava nos bronzes Chola?', op: ['Cera perdida', 'Moldagem em gesso', 'Forjamento a frio', 'Impressão 3D'], certa: 0, exp: 'Modelava-se em cera, cobria-se de argila e vazava-se o metal no molde, depois de derretida a cera.' },
  { p: 'Qual a verdade sobre o Kama Sutra?', op: ['É só sobre sexo', 'Foi escrito no séc. XIX', 'É um tratado de 7 livros sobre a vida e o prazer, em que a união física é só uma parte', 'É um poema épico'], certa: 2, exp: 'Atribuído a Vatsyayana (c. séc. III), trata de cortejo, casamento, vida doméstica e artes.' },
  { p: 'Quem escreveu o Abhijnanashakuntalam?', op: ['Kalidasa', 'Bana', 'Panini', 'Tiruvalluvar'], certa: 0, exp: 'Kalidasa, o maior poeta e dramaturgo em sânscrito (c. séc. IV – V).' },
  { p: 'Que obra tâmil tem 1330 dísticos sobre virtude, riqueza e amor?', op: ['Tirukkural', 'Silappatikaram', 'Tolkappiyam', 'Manimekalai'], certa: 0, exp: 'O Tirukkural, de Tiruvalluvar, tem 133 capítulos de 10 dísticos.' },
  { p: 'O que descobriu Madhava de Sangamagrama no séc. XIV?', op: ['O zero', 'Séries infinitas para o seno, o cosseno e o arco-tangente', 'O sistema solar', 'O xadrez'], certa: 1, exp: 'Madhava (c. 1340 – 1425), em Kerala, descobriu séries séculos antes da Europa, mas não está provado que tenham chegado lá.' },
  { p: 'Que fábulas indianas chegaram à Europa, passando pelo persa e pelo árabe?', op: ['Os Jatakas de Ajanta', 'O Mahabharata', 'O Panchatantra', 'O Ramayana'], certa: 2, exp: 'O Panchatantra foi traduzido para persa médio e depois para árabe (Kalila e Dimna), chegando a La Fontaine.' }
];

export default { id: 'india-classica', cor: '#c4682f', emblema: '../../assets/img/india-classica.png', grupo: { ...GRUPO, aqui: 'ciencia-arte' },
  nome: { pt: 'Ciência, matemática e arte', en: 'Science, mathematics and art' },
  periodo: { pt: 'Da Antiguidade a c. 1500 d.C.', en: 'From antiquity to c. AD 1500' },
  visao: { pt: visao, en: EN.visao }, linha: { pt: linha, en: EN.linha }, mapa: { pt: mapa, en: EN.mapa }, sociedade: { pt: sociedade, en: EN.sociedade },
  personalidades: { pt: personalidades, en: EN.personalidades }, legado: { pt: [...legado, ...CRED.pt], en: [...EN.legado, ...CRED.en] }, quiz: { pt: quiz, en: EN.quiz } };
