// O IMPÉRIO MAURYA E ASHOKA — conteúdo completo em português. A versão inglesa está em dados-en.js (mesma estrutura, mesmos ids de imagem).
// Datas na «cronologia média»: Chandragupta c. 321 – 297 a.C., Bindusara c. 297 – 273 a.C., Ashoka c. 268 – 232 a.C. (coroação; a ascensão ao poder foi alguns anos antes), fim em 185 a.C. Todas são aproximadas e debatidas.
// Fontes: éditos de Ashoka; Arthashastra; fragmentos de Megástenes (Estrabão, Arriano, Diodoro); crónicas budistas do Sri Lanka (Dipavamsa, Mahavamsa) e Ashokavadana; tradição jainista; Puranas; arqueologia.
// Imagens: cada {img:'id'} procura o ficheiro  india-classica/maurya/img/id.jpg  (ver IMAGENS_INDIA_CLASSICA_MAURYA.md).
import EN from './dados-en.js';
import CRED from './creditos.js';
import { GRUPO } from '../grupo.js';

const visao = [
  { caixa: 'Em resumo', texto: [
    'O **Império Máuria** (em inglês, *Maurya*) foi o primeiro Estado a unir grande parte do subcontinente indiano. Fundado por volta de **321 a.C.** por **Chandragupta Maurya**, com capital em **Pataliputra** (a atual Patna), chegou ao auge sob o seu neto **Ashoka** (c. 268 – 232 a.C.), quando se estendia do Afeganistão e do Baluchistão, a oeste, até Bengala e Odisha, a leste, e do Himalaia até ao planalto de Karnataka, no sul. Terminou em **185 a.C.**, quando o último rei foi morto por um general.',
    'É o império mais bem documentado da Índia antiga, e por razões raras: temos as **palavras do próprio imperador**, gravadas em rochas e pilares por todo o território (os éditos de Ashoka); um **tratado de governo**, o *Arthashastra*, atribuído pela tradição ao ministro de Chandragupta; e o relato de um **embaixador grego**, Megástenes, que viveu em Pataliputra. Nenhum outro Estado indiano antigo deixou tanto sobre si próprio.'
  ] },
  { img: 'imu-mapa-maurya', leg: 'Mapa da extensão aproximada do Império Máuria no tempo de Ashoka, século III a.C.' },
  { h: 'Onde ficava' },
  'O coração do império era **Magadha**, no vale do Ganges (Bihar), com Pataliputra na confluência do Ganges e do Son. Daí partiam as estradas e os governadores para um território imenso: a oeste, o **Punjab**, o vale do Indo, **Gandhara** e, depois do acordo com Seleuco, partes do atual **Afeganistão** (Arachósia, Gedrósia, Paropamisadas); no centro, **Avanti** (Ujjain) e o Gujarat; a leste, **Kalinga** (Odisha), conquistada por Ashoka; e, no sul, grande parte do planalto do **Decão**, até ao norte de Karnataka e ao sul de Andhra Pradesh.',
  'Ficaram de fora o **extremo sul** (os reinos tâmeis dos Cholas, Pandyas, Keralaputras e Satiyaputras, que Ashoka cita como vizinhos) e a ilha de **Sri Lanka** (*Tambapanni*), com a qual teve relações amigáveis. O império era mais uma rede de **cidades, estradas e minas** unidas por um centro forte do que um território contínuo; entre elas havia florestas e povos tribais que nunca foram plenamente controlados (o Édito de Pedra n.º 13 avisa os povos da floresta).',
  { img: 'imu-mapa-editos', leg: 'Mapa dos locais onde foram encontrados éditos de Ashoka; a sua distribuição ajuda a desenhar os limites do império.' },
  { h: 'Quando existiu' },
  'Pouco mais de um século e meio. As datas dos primeiros reinos assentam em fontes indianas tardias e em sincronismos com os gregos (Alexandre, Seleuco, Antíoco), por isso são aproximadas.',
  { tabela: { cab: ['Fase', 'Datas aproximadas', 'O que a marca'], linhas: [
    ['Antes: os Nandas', 'c. 345 – 321 a.C.', 'Dinastia de Magadha com um exército e um tesouro enormes; derrubada por Chandragupta'],
    ['Chandragupta Maurya', 'c. 321 – 297 a.C.', 'Conquista de Pataliputra e do norte; guerra e acordo com Seleuco (c. 305 – 303 a.C.); embaixada de Megástenes'],
    ['Bindusara', 'c. 297 – 273 a.C.', 'Consolidação e expansão para o sul; contactos diplomáticos com o mundo helenístico'],
    ['Ashoka', 'c. 268 – 232 a.C.', 'Guerra de Kalinga (c. 261 a.C.); política do *dhamma*; éditos em pedra; missões budistas; apogeu do império'],
    ['Os últimos Máurias', 'c. 232 – 185 a.C.', 'Divisão do poder, perda de territórios no noroeste, fraqueza financeira; assassinato de Brihadratha por Pushyamitra Shunga']
  ] } },
  { h: 'Quem eram os Máurias?' },
  'A origem da dinastia é obscura e as fontes divergem, o que mostra que era uma questão sensível. Textos **budistas** ligam Chandragupta ao clã dos **Moriyas**, de Pipphalivana, um pequeno grupo que, segundo o *Mahaparinibbana Sutta*, recebeu uma parte das relíquias do Buda; a palavra lembraria *mora*, «pavão». Textos **brâmanes** (os Puranas) e o drama *Mudrarakshasa* sugerem uma origem humilde, ligada a uma criada chamada Mura; a tradição **jainista** faz de Chandragupta um devoto de Mahavira. Nada disto é confirmado. O que parece seguro é que não vinham de uma casa real antiga, e que chegaram ao poder por mérito militar e político.',
  'O nome «Maurya» é, aliás, usado só pelas fontes posteriores. Nos seus éditos, Ashoka nunca fala do clã ou dos antepassados: chama-se «Devanampiya Piyadasi» («Amado dos Deuses, de Olhar Benévolo»).',
  { h: 'O que sabemos e como o sabemos' },
  { lista: [
    '**Os éditos de Ashoka:** mais de trinta inscrições em rochas, pilares e grutas, de c. 260 a 232 a.C.; são a fonte mais direta e a mais antiga escrita datável da Índia, depois da civilização do Indo.',
    '**O *Arthashastra*:** tratado de política e administração, atribuído a Kautilya (Chanakya). A forma que conhecemos foi composta e revista entre os séculos II a.C. e III d.C., por isso descreve talvez uma administração posterior aos Máurias, ainda que inspirada nela.',
    '**Megástenes:** embaixador de Seleuco I em Pataliputra. A sua obra *Indica* perdeu-se; sobrevivem fragmentos em Estrabão, Arriano e Diodoro. É um olhar de fora, por vezes fantasioso.',
    '**Crónicas budistas:** o *Dipavamsa* e o *Mahavamsa* (Sri Lanka, séculos IV – V d.C.) e o *Ashokavadana* (séc. II d.C.) contam a vida de Ashoka com muita lenda.',
    '**Jainismo e Puranas:** tradições sobre Chandragupta e a sucessão, escritas muito depois.',
    '**Arqueologia:** Pataliputra, Taxila, Sanchi, os pilares polidos, moedas de prata marcadas por punção.'
  ] },
  { img: 'imu-pilar-sarnath', leg: 'O capitel dos quatro leões de Sarnath, em arenito polido, século III a.C., Museu de Sarnath.' },
  { h: 'Porque importam' },
  { lista: [
    '**O primeiro império indiano:** mostrou que era possível governar do Hindu Kush ao Decão, e deixou um modelo (e um ideal) a todos os reinos seguintes.',
    '**O rei que se arrependeu:** os éditos de Ashoka contêm um dos primeiros testemunhos de um governante a reconhecer, por escrito, o sofrimento que causou e a propor uma ética pública.',
    '**A difusão do budismo:** por ação, direta ou indireta, do imperador, o budismo passou de uma doutrina do vale do Ganges a uma religião de alcance internacional, do Sri Lanka à Ásia Central.',
    '**A administração:** burocracia, espiões, estradas, moeda e impostos; o *Arthashastra* é um dos grandes textos de teoria política da Antiguidade.',
    '**Arte monumental em pedra:** os pilares polidos, os primeiros estupas e as grutas de Barabar iniciam a grande arquitetura em pedra da Índia.'
  ] },
  { caixa: 'Os Máurias hoje', texto: 'O **capitel de Sarnath** é o emblema do Estado indiano desde 26 de janeiro de 1950, e a **roda de Ashoka** (*Ashoka Chakra*), de 24 raios, está no centro da bandeira nacional (adotada em 22 de julho de 1947). O nome de Ashoka é hoje o de um ideal: de tolerância, de governo justo e de não violência. Os historiadores têm, contudo, o cuidado de separar o imperador histórico, que governou com um exército, castigos severos e propaganda, da figura quase santa das lendas.' },
  { img: 'imu-sanchi-estupa', leg: 'O Grande Estupa de Sanchi (Madhya Pradesh): o núcleo foi erguido no tempo de Ashoka e ampliado nos séculos seguintes.' },
  { caixa: 'Facto e lenda', texto: [
    'Esta página separa o que está nos **éditos** e na arqueologia (o que o rei disse, onde e quando), do que vem das **crónicas budistas** e jainistas (escritas séculos depois, com intenção religiosa). Exemplos de lenda: os 99 irmãos mortos por Ashoka, o «inferno» que mandou construir, os 84 000 estupas, as maravilhas de Chanakya. Alguns pormenores podem ter base histórica; o que não está nos éditos fica assinalado como «segundo a tradição».',
    'Convém lembrar também que **não existe nenhum retrato fiel** dos imperadores máurias: as imagens que se veem em livros são reconstruções modernas.'
  ] }
];

const linha = [
  'A linha do tempo segue o império do fundador ao fim e termina na redescoberta moderna. As datas antes de 300 a.C. são aproximadas e as de Ashoka seguem a contagem a partir da coroação (c. 268 a.C.); muitas fontes variam um a três anos. O que vem só de crónicas tardias é assinalado como «tradição».',
  { linha: [
    { d: 'c. 345 a.C.', t: 'Os Nandas em Magadha', x: 'A dinastia **Nanda** assume o trono de Magadha e domina o Ganges, com um exército que as fontes gregas descrevem como colossal e um tesouro riquíssimo, mas com fama de impopular entre os súditos. Pataliputra torna-se capital sob eles ou pouco antes.' },
    { d: '326 – 325 a.C.', t: 'Alexandre no Punjab', x: 'Alexandre vence Poro no Hidaspes, mas o exército recusa-se a avançar para leste, em direção ao império dos Nandas. Segundo Plutarco, um jovem chamado «Androcotto» (Chandragupta) terá conhecido Alexandre e dito mais tarde que podia ter derrubado o rei de Magadha, odiado pelo povo. A história pode ser tradição, mas mostra que a figura era conhecida dos gregos.' },
    { d: '325 – 316 a.C.', t: 'O vazio após Alexandre', x: 'Depois da morte de Alexandre (323 a.C.), os governadores macedónios do Indo retiram-se ou são mortos (Poro foi assassinado por Eudemo c. 317 a.C.). O noroeste fica sem poder forte. É neste vácuo que cresce o poder de Chandragupta.' },
    { d: 'c. 321 a.C.', t: 'Chandragupta toma Pataliputra', x: 'Segundo a tradição, **Chandragupta**, aconselhado por **Chanakya**, derruba o último rei Nanda e ocupa Pataliputra. A data (entre 324 e 313 a.C., segundo os autores) e os pormenores (as lendas sobre o juramento de Chanakya vêm de fontes muito posteriores) são incertos.' },
    { d: 'c. 320 – 305 a.C.', t: 'Expansão para o oeste e o centro', x: 'Chandragupta controla o Punjab e as regiões do Indo e estende o poder ao Gujarat: uma inscrição de **Rudradaman** (c. 150 d.C.), em Junagadh, refere que um governador de Chandragupta, **Pushyagupta**, construiu o lago Sudarshana. Textos tâmeis posteriores falam da chegada dos «Moriyar» ao sul, o que é debatido.' },
    { d: 'c. 305 – 303 a.C.', t: 'Seleuco I e o tratado', x: '**Seleuco I Nicator** tenta recuperar os territórios de Alexandre no Indo e acaba por fazer um acordo com Chandragupta: cede Aracósia, Gedrósia e Paropamisadas (e parte de Aria, segundo Estrabão) e recebe **500 elefantes de guerra**; as fontes mencionam também uma aliança por casamento (cujo sentido é debatido). Os elefantes ajudaram Seleuco a vencer em Ipsos (301 a.C.).' },
    { d: 'c. 302 – 288 a.C.', t: 'Megástenes em Pataliputra', x: 'Seleuco envia **Megástenes** como embaixador. Este escreve a *Indica*, hoje perdida, de que Estrabão, Arriano e Diodoro conservaram fragmentos sobre a capital, as «classes», a administração e o exército.' },
    { d: 'c. 297 a.C.', t: 'Fim do reinado de Chandragupta', x: 'Chandragupta morre ou abdica (as datas vão de 298 a 293 a.C.). A **tradição jainista** diz que se tornou monge e se retirou para Shravanabelagola, no sul, onde terá morrido por jejum ritual; a historicidade é discutida.' },
    { d: 'c. 297 – 273 a.C.', t: 'Bindusara', x: 'O filho, **Bindusara** (os gregos chamam-lhe *Amitrochates*, de *Amitraghata*, «destruidor de inimigos»), consolida o império e alarga-o provavelmente para o sul, até ao Decão. Mantém relações diplomáticas com os reis helenísticos: **Deímaco** é embaixador de Antíoco I na sua corte.' },
    { d: 'c. 280 – 270 a.C.', t: 'Os figos de Bindusara', x: 'Segundo Ateneu, Bindusara pediu a Antíoco I vinho doce, figos secos e um sofista; Antíoco enviou os dois primeiros e respondeu que os gregos não vendiam sofistas. A anedota pode ser embelezada, mas é um sinal do contacto cortês entre as duas cortes.' },
    { d: 'c. 273 – 268 a.C.', t: 'A sucessão', x: 'Segundo as crónicas do Sri Lanka, houve quatro anos de luta entre a morte de Bindusara e a coroação de Ashoka, que teria eliminado 99 irmãos (lenda). Os próprios éditos de Ashoka falam de famílias de irmãos e irmãs com funcionários que cuidam delas, o que desmente o massacre total; mas uma disputa pelo trono é provável.' },
    { d: 'c. 268 a.C.', t: 'Ashoka é coroado', x: '**Ashoka** governava Ujjain (e, segundo a tradição, esteve em Taxila) antes de subir ao trono. Os éditos contam os anos a partir da **coroação**, e é daí que se fixa a cronologia do reinado, de c. 268 a 232 a.C.' },
    { d: 'c. 261 a.C.', t: 'A guerra de Kalinga', x: 'No oitavo ano de reinado, Ashoka conquista **Kalinga** (Odisha). No Édito de Pedra n.º 13 diz que **150 000 pessoas foram deportadas, 100 000 mortas e muitas outras morreram**, e que sente remorso. Os números são do próprio rei e podem ser retóricos.' },
    { d: 'c. 260 – 258 a.C.', t: 'O caminho do *dhamma*', x: 'Ashoka diz ter-se tornado **leigo budista** (*upasaka*) e, passados dois anos e meio, ter-se empenhado a fundo na doutrina. Surge a política do *dhamma*: ética pública de respeito, compaixão e tolerância. Nomeia funcionários dedicados (*dhamma-mahamattas*) c. 256 a.C. (13.º ano de reinado).' },
    { d: 'c. 257 a.C.', t: 'Os primeiros éditos e as grutas de Barabar', x: 'Gravam-se os **Éditos de Pedra Menores** (por volta do 11.º ano) e começam os 14 **Éditos de Pedra Maiores** (a partir do 12.º ano, c. 257 a.C.). No mesmo ano, as grutas de **Barabar**, em Bihar, são dedicadas aos monges **ajivikas**.' },
    { d: 'c. 256 – 250 a.C.', t: 'Embaixadas ao mundo helenístico', x: 'O Édito n.º 13 diz que o *dhamma* chegou aos reinos de **Antíoco II** (Síria), **Ptolomeu II** (Egito), **Antígono Gonatas** (Macedónia), **Magas** (Cirene) e Alexandre (de Épiro ou de Corinto; é debatido), e também ao sul da Índia e a Sri Lanka. Não há provas de que estes reis tenham reagido, e as fontes ocidentais nada dizem.' },
    { d: 'c. 250 a.C. (tradição)', t: 'Mahinda e o Sri Lanka; o concílio de Pataliputra', x: 'Segundo as crónicas do Sri Lanka, o monge **Mahinda**, filho de Ashoka, e **Sanghamitta**, a filha, levam o budismo à ilha, onde convertem o rei **Devanampiya Tissa** em Mihintale. A mesma tradição fala de um **terceiro concílio budista** em Pataliputra, presidido por **Moggaliputta Tissa**, que expulsa os monges considerados hereges. Estes episódios são só da tradição Theravada.' },
    { d: 'c. 249 a.C.', t: 'A peregrinação a Lumbini', x: 'No 20.º ano do reinado, Ashoka visita **Lumbini**, o local de nascimento do Buda, e ergue um pilar com uma inscrição: reduz o imposto da aldeia a um oitavo da colheita e isenta-a de outros encargos.' },
    { d: 'c. 243 – 242 a.C.', t: 'Os Éditos de Pilar', x: 'Entre o 26.º e o 27.º ano, Ashoka manda gravar os sete **Éditos de Pilar** (Delhi-Topra, Allahabad, Lauriya-Araraj, etc.), que fazem o balanço do reinado: fala de justiça, de hospitais, de poços e árvores, de proteção dos animais, de amnistias.' },
    { d: 'c. 232 a.C.', t: 'Morte de Ashoka', x: 'Ashoka morre depois de cerca de 37 anos no trono. As fontes tradicionais descrevem os seus últimos anos como tristes, com o tesouro esvaziado pelas doações aos mosteiros (lenda do *Ashokavadana*). Não há inscrições do fim do reinado.' },
    { d: 'c. 232 – 185 a.C.', t: 'Os sucessores', x: 'As fontes (Puranas, textos budistas e jainistas) citam nomes como **Dasharatha** (que doou grutas aos ajivikas em Nagarjuni), **Samprati** e outros, em listas que não concordam. O império divide-se, e parte do noroeste perde-se, com a chegada dos **gregos da Báctria**.' },
    { d: 'c. 206 a.C.', t: 'Antíoco III e Subhagasena', x: 'O rei selêucida **Antíoco III** atravessa o Hindu Kush e renova a «amizade» com um rei indiano, **Sophagasenos** (Subhagasena), de quem recebe elefantes (Políbio). É possível que este fosse um rei máuria do noroeste ou um governante local; é debatido.' },
    { d: '185 a.C.', t: 'Brihadratha e Pushyamitra', x: 'O general **Pushyamitra Shunga** mata o último rei, **Brihadratha**, durante uma revista às tropas (segundo Bana, séc. VII d.C.) e funda a dinastia dos **Sungas**. A data de 185 a.C. é a mais usada; outras propostas vão de 187 a 180 a.C.' },
    { d: 'séc. II a.C.', t: 'O império deixa herança', x: 'Os Sungas ampliam e revestem de pedra o estupa de Sanchi, e erguem Bharhut. As técnicas de pedra e de polimento, a escrita brahmi e a moeda continuam. Ashoka torna-se uma lembrança religiosa e política que atravessa o budismo.' },
    { d: '1837 – 1838', t: 'Prinsep decifra a brahmi', x: '**James Prinsep** decifra a escrita brahmi e lê os éditos; George Turnour, que lia o *Mahavamsa*, liga o «Piyadasi» dos éditos ao Ashoka das crónicas. Ashoka, esquecido durante mais de dois mil anos, volta à história.' },
    { d: '1905 – 1909', t: 'O Arthashastra reaparece', x: 'O bibliotecário **R. Shamasastry** encontra em Mysore um manuscrito do *Arthashastra*, até então conhecido só por citações. Publica-o em 1909 e traduz-o para inglês em 1915.' }
  ] },
  { img: 'imu-chandragupta-chanakya', leg: 'Reconstrução artística: Chandragupta e o seu conselheiro Chanakya a planear a tomada de Pataliputra. Pintura de imaginação (não há retratos fiéis).' },
  { img: 'imu-moeda-seleuco', leg: 'Moeda de Seleuco I Nicator, o rei que cedeu territórios do Indo a Chandragupta e recebeu 500 elefantes de guerra.' },
  { img: 'imu-kalinga-depois', leg: 'Reconstrução artística: o campo de batalha de Kalinga, depois da guerra, c. 261 a.C.' },
  { img: 'imu-dhauli-elefante', leg: 'O elefante esculpido na rocha em Dhauli (Odisha), junto dos éditos de Ashoka sobre Kalinga, séc. III a.C.' },
  { img: 'imu-mahinda-ceilao', leg: 'Reconstrução artística: o monge Mahinda a ensinar o rei Devanampiya Tissa e a corte do Sri Lanka, segundo as crónicas da ilha.' },
  { img: 'imu-mihintale', leg: 'Mihintale, no Sri Lanka, local onde a tradição situa o encontro de Mahinda com o rei Devanampiya Tissa.' }
];

const mapa = [
  'O império teve **uma só capital**, Pataliputra, e várias cidades-chave por onde passavam estradas, impostos e funcionários. Para o governo, o território dividia-se em Magadha (a zona central, sob controlo direto) e quatro grandes províncias entregues a príncipes da casa real. A tabela mostra os principais lugares.',
  { tabela: { cab: ['Local', 'Onde fica hoje', 'Para que ficou conhecido'], linhas: [
    ['Pataliputra', 'Patna, Bihar', 'Capital do império; uma das maiores cidades do mundo antigo; palácio e paliçada de madeira'],
    ['Taxila (Takshashila)', 'perto de Islamabad, Paquistão', 'Capital da província do noroeste; centro de comércio e de ensino; mosteiro de Dharmarajika'],
    ['Ujjain (Avanti)', 'Madhya Pradesh', 'Capital da província ocidental; Ashoka foi governador, segundo a tradição'],
    ['Tosali', 'perto de Bhubaneswar, Odisha', 'Capital da província de Kalinga, depois da conquista; éditos de Dhauli e Jaugada'],
    ['Suvarnagiri', 'Karnataka (localização debatida)', 'Capital da província do sul, provavelmente na região de Raichur'],
    ['Sanchi e Vidisha', 'Madhya Pradesh', 'Grande estupa; ligação a Devi, esposa de Ashoka (tradição)'],
    ['Sarnath', 'perto de Varanasi, Uttar Pradesh', 'Local do primeiro sermão do Buda; pilar com o capitel dos quatro leões'],
    ['Bodh Gaya', 'Bihar', 'Local da iluminação do Buda; Ashoka visitou-o no 10.º ano'],
    ['Lumbini', 'Nepal', 'Local de nascimento do Buda; pilar de Ashoka com inscrição'],
    ['Kausambi', 'perto de Prayagraj, Uttar Pradesh', 'Pilar com éditos (hoje em Allahabad); importante cidade comercial'],
    ['Barabar', 'perto de Gaya, Bihar', 'As mais antigas grutas escavadas na rocha da Índia, dadas aos ajivikas'],
    ['Kandahar', 'Afeganistão', 'Éditos em grego e em aramaico (Alexandria da Aracósia)'],
    ['Dhauli e Jaugada', 'Odisha', 'Éditos especiais de Kalinga, dirigidos aos funcionários locais'],
    ['Tamralipti e Bharukaccha', 'Bengala e Gujarat', 'Portos de saída para o Sri Lanka, o Sudeste Asiático e o Ocidente']
  ] } },
  { h: 'Pataliputra' },
  'Pataliputra, na confluência do Ganges com o Son, é descrita por Megástenes como uma cidade comprida e estreita, de cerca de **80 estádios** (c. 14 km) de comprimento por 15 (c. 2,7 km) de largura, rodeada por uma **paliçada de madeira** com 570 torres e 64 portas, e por um fosso largo. A cidade era já antiga: segundo as tradições budistas, o rei Ajatashatru fortificou a aldeia de Pataligrama no século V a.C., e foi sob Udayin ou os Nandas que se tornou capital.',
  'Era uma cidade sobretudo de **madeira** (a pedra era para monumentos), o que explica que se tenha perdido quase tudo: incêndios e cheias, e o facto de Patna continuar ocupada, impedem escavações em grande escala. Mas as partes encontradas são suficientes para confirmar Megástenes.',
  { img: 'imu-pataliputra-reconstrucao', leg: 'Reconstrução artística de Pataliputra no tempo máuria, com a paliçada de madeira, o palácio e o rio Ganges.' },
  { img: 'imu-kumhrar', leg: 'Vestígios da sala de colunas máuria em Kumhrar, Patna, escavada a partir de 1912; ficou conhecida como a «sala das 80 colunas».' },
  { img: 'imu-bulandibagh', leg: 'Estacas de madeira da paliçada de Pataliputra encontradas em Bulandibagh (Patna), em escavações do século XX.' },
  'Em **Kumhrar**, a escavação encontrou os restos de uma sala hipostila, com dezenas de **colunas de arenito polido** dispostas em fileiras (as 80 colunas são a hipótese de reconstrução de Spooner, o primeiro escavador, que a comparou com as salas persas de Persépolis; a comparação é discutida). Terá sido uma sala de assembleia ou de palácio, destruída por fogo. Em **Bulandibagh** foram encontrados troncos enterrados em fileiras, que se interpretam como restos da paliçada que Megástenes descreve.',
  { h: 'O noroeste: Taxila e Gandhara' },
  'Taxila, na rota entre a Ásia Central e a planície do Ganges, foi o centro da província do noroeste. Segundo a tradição, Ashoka foi lá como príncipe para reprimir uma revolta, e voltou depois como vice-rei. A arqueologia mostra uma cidade no sítio de Bhir Mound com ocupação máuria, e um mosteiro e estupa em **Dharmarajika**, cuja primeira construção a tradição atribui a Ashoka. Nesta região, os éditos vêm em **kharosthi** (Shahbazgarhi, Mansehra) e em **aramaico** (Taxila), e a norte e a oeste do Hindu Kush, em **grego** e aramaico (Kandahar), por causa dos súbditos de língua grega e persa.',
  { img: 'imu-taxila-dharmarajika', leg: 'O estupa de Dharmarajika, em Taxila (Paquistão); a tradição liga a primeira fundação a Ashoka. Património Mundial da UNESCO.' },
  { h: 'O centro: Ujjain, Vidisha e Sanchi' },
  'Ujjain, antiga capital de Avanti, era a cidade principal da província ocidental, na rota entre o Ganges e os portos do Gujarat. Segundo as crónicas, Ashoka foi vice-rei de Ujjain e casou com **Devi**, filha de um mercador de Vidisha, a poucos quilómetros de **Sanchi**. É nessa colina que se ergue um dos mais importantes monumentos budistas: o **Grande Estupa**.',
  'O primeiro estupa de Sanchi era uma estrutura **hemisférica de tijolo**, com cerca de metade do tamanho atual, que guardava relíquias do Buda; o pilar de arenito polido com o capitel de leões e um édito sobre o cisma da comunidade monástica é da mesma época. O estupa foi **ampliado, revestido de pedra** e cercado por uma balaustrada nos séculos seguintes (tradicionalmente, no tempo dos Sungas, séc. II a.C.), e as quatro **portas esculpidas** (*toranas*) acrescentaram-se entre c. 50 a.C. e o século I d.C.',
  { img: 'imu-estupa-tijolo', leg: 'Reconstrução artística do estupa original de tijolo de Sanchi, no tempo de Ashoka, com o parasol (*chatra*) no topo.' },
  { img: 'imu-sanchi-pilar', leg: 'O pilar de Ashoka junto à porta sul do Grande Estupa de Sanchi, hoje partido; o capitel de leões está no museu arqueológico de Sanchi.' },
  { h: 'Kalinga: Tosali, Dhauli e Jaugada' },
  'Kalinga, a costa de Odisha, era um reino rico e marítimo, que resistiu aos Nandas e aos Máurias até c. 261 a.C. Depois da conquista, Ashoka gravou em **Dhauli** e **Jaugada** dois éditos especiais, dirigidos aos funcionários locais, que mostram a face paternalista do rei: «todos os homens são meus filhos» e quer-lhes o mesmo bem que a si próprio. No rochedo de Dhauli esculpiu-se, perto dos éditos, um elefante, um dos mais antigos monumentos escultóricos em rocha da Índia. Mais tarde, um rei de Kalinga, **Kharavela**, regista as suas campanhas, incluindo contra Magadha, na inscrição da gruta de Hathigumpha (datação debatida).',
  { h: 'O sul: Suvarnagiri e os éditos do Karnataka' },
  'O sul do império é conhecido por **éditos menores** em Brahmagiri, Siddapura, Jatinga-Rameshwara (Karnataka), Erragudi e Rajula-Mandagiri (Andhra Pradesh) e Maski (onde, em 1915, o nome «Ashoka» apareceu pela primeira vez num édito). A capital da província, **Suvarnagiri** («montanha de ouro»), localiza-se talvez na região de Raichur-Kanakagiri, mas a identificação é debatida. O Decão era rico em **ouro, ferro e pedras preciosas**, e a ligação a estas minas ajuda a explicar o interesse dos Máurias.',
  { h: 'Os lugares do Buda' },
  'Ashoka visitou os lugares ligados ao Buda e deixou marcas. Em **Lumbini** (hoje no Nepal), o pilar descoberto em 1896 diz, numa inscrição breve, que o rei, «20 anos depois da coroação», veio venerar o lugar onde nasceu o Buda e isentou a aldeia de impostos. Em **Bodh Gaya** conta-se que visitou o local da iluminação no 10.º ano; a laje de arenito polido (*Vajrasana*) junto à árvore Bodhi é atribuída ao tempo máuria. Em **Sarnath**, onde o Buda pregou o primeiro sermão, ergueu-se o pilar com os quatro leões. Em **Nigali Sagar**, um pilar regista que Ashoka ampliou o estupa de um Buda anterior, Konakamana.',
  { img: 'imu-lumbini-pilar', leg: 'O pilar de Ashoka em Lumbini (Nepal), com a inscrição que regista a visita do rei no 20.º ano de reinado.' },
  { img: 'imu-bodh-gaya', leg: 'O Templo de Mahabodhi, em Bodh Gaya (Bihar); o edifício atual é bem posterior a Ashoka, mas o local foi visitado por ele.' },
  { h: 'As grutas de Barabar' },
  'As colinas de **Barabar** e Nagarjuni, perto de Gaya, têm as mais antigas **grutas escavadas na rocha** do subcontinente, com o interior polido como espelho («polimento máuria»). As inscrições dizem que **Sudama** e **Visva Zopri** foram dadas aos monges **ajivikas** no 12.º ano de Ashoka (c. 257 a.C.) e **Karan Chaupar** no 19.º. Os Ajivikas eram uma seita de ascetas fatalistas, rivais de budistas e jainistas, e o gesto mostra a tolerância proclamada por Ashoka. A gruta **Lomas Rishi**, com uma fachada que imita a arquitetura de madeira, não tem inscrição de Ashoka e pode ser um pouco posterior.',
  { img: 'imu-barabar-sudama', leg: 'A gruta de Sudama, em Barabar (Bihar), dedicada por Ashoka aos monges ajivikas no 12.º ano de reinado.' },
  { img: 'imu-barabar-lomas', leg: 'A fachada da gruta de Lomas Rishi, em Barabar, que reproduz em pedra uma casa de madeira e bambu.' },
  { h: 'As estradas e as rotas' },
  'Megástenes descreve uma **estrada real** de Pataliputra ao noroeste, de cerca de **10 000 estádios** (cerca de 1800 km), com marcos de distância, e o *Arthashastra* distingue a *Uttarapatha*, a «rota do norte», para Taxila e Ásia Central, da *Dakshinapatha*, a «rota do sul», para o Decão e as minas. Ashoka diz ter mandado plantar **figueiras-de-bengala e mangueiras**, e escavar **poços** e construir casas de repouso, em intervalos de oito *kos*, para pessoas e animais. Os rios (Ganges, Son, Yamuna) eram também vias comerciais, e os portos de **Tamralipti**, na foz do Ganges, e **Bharukaccha**, no Gujarat, ligavam o império ao Sri Lanka, ao Sudeste Asiático e ao mar Arábico.',
  { h: 'Vizinhos e fronteiras' },
  { caixa: 'O mundo à volta', texto: 'No Édito n.º 2, Ashoka lista os vizinhos **sem os conquistar**: os Cholas, os Pandyas, os Satiyaputras e os Keralaputras, e *Tambapanni* (Sri Lanka). A oeste, o Édito n.º 13 nomeia reis do Mediterrâneo: **Antíoco II**, **Ptolomeu II**, **Antígono Gonatas**, **Magas** e **Alexandre**. Nas montanhas do noroeste ficavam povos como os Kambojas, os Gandharas e os Yavanas (gregos do noroeste), citados no Édito n.º 13 como estando sob o *dhamma* do rei.' }
];

const sociedade = [
  { h: '1. O rei e o Estado' },
  'O império era uma **monarquia** em que o rei concentrava o poder, a justiça e o comando militar. Era ajudado por um **conselho de ministros** (*mantri-parishad*) e por um corpo de funcionários bem hierarquizado. O *Arthashastra* descreve com minúcia o ideal: o rei deve ser disciplinado, rodeado de bons conselheiros, vigiar os ministros e trabalhar sem descanso. Diz que o rei **deve repartir o dia e a noite** entre o governo, o estudo e o descanso, e dormir pouco. Ashoka, no Édito n.º 6, diz algo parecido: que à hora das refeições, no harém, no gabinete, em qualquer lugar, os funcionários podem trazer-lhe assuntos do povo.',
  { cit: 'Não há obra mais importante para mim do que trabalhar pelo bem-estar de todo o mundo. (Édito de Pedra n.º 6, paráfrase)', fonte: 'Éditos de Ashoka' },
  { img: 'imu-palacio-sala', leg: 'Reconstrução artística: o imperador máuria a receber ministros e embaixadores na sala de colunas de Pataliputra.' },
  { h: 'Províncias e funcionários' },
  'O império estava dividido em **Magadha** (a zona central, governada diretamente do palácio) e quatro **províncias** (Taxila a noroeste, Ujjain a oeste, Tosali a leste, Suvarnagiri ao sul) governadas por **príncipes** (*kumara*, *aryaputra*), com conselhos de ministros próprios. Abaixo, havia os **distritos** e as **aldeias**. Os éditos nomeiam as categorias de funcionários: os **rajukas** (responsáveis pelo campo, com poderes de justiça e de cobrança), os **pradeshikas** (inspetores de distrito), os **yuktas** (subordinados) e os **mahamattas** («grandes funcionários»). Ashoka criou **funcionários do dhamma** (*dhamma-mahamattas*), c. 256 a.C., para visitar o povo, ajudar presos, velhos e famílias numerosas, e supervisionar as seitas, e outros para as **mulheres**.',
  { h: 'O Arthashastra e a teoria do Estado' },
  'O *Arthashastra* («ciência da riqueza ou do Estado») é um tratado em sânscrito, com **15 livros** e 150 capítulos, sobre governo, economia, justiça, diplomacia e guerra. A tradição atribui-o a **Kautilya**, também chamado **Chanakya** ou Vishnugupta, o ministro de Chandragupta. Os especialistas rejeitam hoje a autoria de uma só pessoa: Patrick Olivelle propõe que o texto foi composto em fases, entre c. 150 a.C. e 300 d.C., a partir de fontes anteriores (R. P. Kangle e outros defendiam datas mais antigas, com um núcleo do tempo dos Máurias). Por isso, serve para conhecer a **teoria política** indiana, e menos para descrever com rigor o governo dos Máurias.',
  { lista: [
    '**Os sete elementos do Estado** (*saptanga*): o rei, o ministro, o território, a fortaleza, o tesouro, o exército e o aliado.',
    '**A teoria dos mandalas:** o vizinho é inimigo natural e o vizinho do vizinho é aliado; o rei deve escolher entre seis políticas (paz, guerra, espera, marcha, aliança, política dupla).',
    '**Os superintendentes** (*adhyakshas*): chefes dos departamentos de minas, florestas, comércio, moeda, sal, pesos e medidas, gado, prostitutas, navios, armazéns…',
    '**Segurança e espionagem:** redes de agentes disfarçados (de asceta, mercador, estudante) para vigiar funcionários e inimigos.',
    '**Economia:** o Estado tinha monopólios e empresas próprias (minas, fiação, armazéns), mas aceitava os privados. Calcula salários: do mais alto ministro (48 000 *panas* por ano, segundo o texto) ao empregado mais baixo (60).',
    '**Justiça:** tribunais civis e criminais, distinção de delitos, penas proporcionais (multas, mutilações, morte para alguns crimes).'
  ] },
  { img: 'imu-arthashastra-ms', leg: 'Folha de um manuscrito do *Arthashastra*, texto sobre governo atribuído a Kautilya (Chanakya).' },
  { caixa: 'Maquiavel indiano?', texto: 'Comparou-se muitas vezes Kautilya a **Maquiavel**, e a ideia de «real-politik» sem moral vem daí. A comparação é redutora: o *Arthashastra* dá muito espaço aos **deveres do rei** para com os súditos, ao *dharma* e à justiça, e a «medidas secretas» (venenos, assassinatos) a título de recurso contra inimigos e traidores, não como norma. Mas é verdade que fala de coisas pouco simpáticas com a calma de um manual técnico.' },
  { h: 'Os espiões' },
  'O *Arthashastra* dedica muito espaço à espionagem, e os éditos de Ashoka falam de *pativedakas*, «informadores» que lhe levavam notícias a qualquer hora (Édito n.º 6). Megástenes diz que os «inspetores» (*episkopoi*) vigiavam o campo e a cidade e informavam o rei. A rede de informação do império era, de facto, um dos seus instrumentos, e foi um traço reconhecido do Estado máuria.',
  { h: 'A cidade de Pataliputra e as suas comissões' },
  'Megástenes (por Estrabão e Diodoro) descreve a administração da cidade por **seis comissões de cinco membros**, cada uma com uma tarefa: artes e ofícios, estrangeiros, nascimentos e mortes, comércio e pesos, produtos manufaturados e imposto sobre vendas (um décimo). Os estrangeiros eram vigiados e protegidos, e os que morriam em Pataliputra tinham os bens entregues aos herdeiros. A descrição pode ser idealizada, mas mostra uma cidade muito administrada.',
  { img: 'imu-megastenes', leg: 'Reconstrução artística: Megástenes, o embaixador grego, a tomar notas diante de funcionários máurias em Pataliputra.' },
  { h: 'O exército' },
  'O exército máuria era enorme e estava sob direção de um **conselho militar** (segundo Megástenes, seis comissões de cinco, para infantaria, cavalaria, elefantes, carros, marinha e transportes). As fontes gregas falam de **600 000 soldados de infantaria, 30 000 cavaleiros, 8 000 carros e 9 000 elefantes**: números que são, quase de certeza, **exagerados** (Plínio e Plutarco repetem-nos) mas indicam a ideia da época. Os elefantes eram a arma mais famosa: Seleuco recebeu 500. O exército era pago pelo Estado, e vivia à custa de impostos pesados. A **marinha** e os navios de rio estavam a cargo de um superintendente.',
  { img: 'imu-exercito-quatro-armas', leg: 'Reconstrução artística: o exército máuria, com infantaria, cavalaria, carros e elefantes de guerra, em marcha.' },
  { h: '2. Ashoka e o dhamma' },
  'O *dhamma* (em sânscrito, *dharma*) de Ashoka não é uma doutrina religiosa em sentido estrito, mas um **código ético de convivência**, defendido por um governante para uma população de crenças variadas. Resume-se em poucos pontos: **respeito** pelos pais, mestres, anciãos e sacerdotes de todas as seitas; **generosidade** para com amigos, parentes e ascetas; **não violência** com os seres vivos; **verdade**, moderação nos gastos, domínio de si. Ashoka explica que o recompensado por este caminho é feliz neste mundo e no outro (os éditos usam a ideia de «céu»).',
  'O que é *dhamma* é traduzido de várias formas (moralidade, piedade, lei, «Dharma»); o Édito de Kandahar em grego usa a palavra *eusebeia* («piedade, reverência»). É também uma **política de Estado**: estabelece uma linguagem comum, aproxima o rei do povo, e reforça a unidade de um território imenso. Há historiadores que lhe dão peso de **ideologia imperial**, e não só de convicção pessoal.',
  { cit: 'Quem honra a sua própria seita e deprecia as outras, por apego à sua, fá-la sofrer muito. (Édito de Pedra n.º 12, paráfrase)', fonte: 'Éditos de Ashoka' },
  { h: 'O que Ashoka fez, e o que não fez' },
  { lista: [
    '**Reduziu a violência:** pediu que não se matassem certos animais, regulou o abate e limitou a caça (Édito n.º 1 e Pilar n.º 5). Nas cozinhas reais passou de muitas centenas de milhares de animais por dia, segundo o próprio édito, a dois pavões e um veado, e depois nenhum.',
    '**Trocou as viagens de prazer** (*vihara-yatra*, com caça) **por viagens do dhamma** (*dhamma-yatra*), a visitar ascetas, anciãos e o campo (Édito n.º 8).',
    '**Construiu hospitais e abrigos:** o Édito n.º 2 refere cuidados médicos para pessoas e animais, plantas medicinais, poços e árvores à beira das estradas.',
    '**Não aboliu a pena de morte** nem as penas severas: o Pilar n.º 4 dá três dias aos condenados para prepararem a morte, mas não abole o castigo. O exército manteve-se, e os povos da floresta foram avisados.',
    '**Amnistiou presos** (25 vezes nos primeiros 26 anos, segundo o Pilar n.º 5).',
    '**Não impôs o budismo:** os éditos pedem tolerância e tratam brâmanes, ajivikas e outras seitas com o mesmo respeito.'
  ] },
  { h: 'O budismo de Ashoka' },
  'O próprio Ashoka diz, no Édito Menor de Rupnath/Maski, que durante mais de dois anos foi **leigo** (*upasaka*) e que depois entrou em contacto mais estreito com a comunidade monástica (*sangha*). Num édito dirigido à *sangha* (Bhabra/Bairat) cita **textos budistas** que recomenda a monges e leigos, e no **Édito do Cisma** (Sanchi, Sarnath, Kausambi) ameaça expulsar monges ou monjas que dividam a comunidade. Peregrinou a Lumbini e a Bodh Gaya, e mandou ampliar estupas. É difícil dizer até onde interveio no governo da *sangha*, e quanto da sua imagem de grande patrono vem das crónicas.',
  { h: 'A difusão do budismo' },
  'Os éditos falam de missionários do *dhamma* enviados a reinos vizinhos; as crónicas do Sri Lanka falam de **nove missões** do tempo do terceiro concílio (a Cachemira-Gandhara, a Maharashtra, a Yona, ao Himalaia, a Suvannabhumi, etc.), e a de **Mahinda** ao Sri Lanka. Estas missões não aparecem nos éditos e a sua historicidade é desigual; mas os resultados são claros: o budismo existia, séculos depois, no noroeste (Gandhara), no Sri Lanka e em várias regiões do Decão, e daí passou à Birmânia, ao Sudeste Asiático e à Ásia Central.',
  { h: '3. Religião no império' },
  { tabela: { cab: ['Tradição', 'Ideias e práticas', 'Notas'], linhas: [
    ['Bramanismo (religião védica)', 'Sacrifícios do fogo, rituais conduzidos por sacerdotes brâmanes; Vedas', 'Continua forte; Ashoka restringiu certos sacrifícios de animais, mas os éditos tratam os brâmanes com respeito'],
    ['Budismo', 'Quatro Nobres Verdades, Caminho Óctuplo, *sangha*; veneração de estupas e da árvore Bodhi', 'Beneficiou do patrocínio de Ashoka; ainda não tem imagens do Buda em forma humana'],
    ['Jainismo', 'Não violência absoluta, ascetismo, Mahavira', 'Tradição liga-o a Chandragupta e a Samprati; forte entre mercadores'],
    ['Ajivikas', 'Fatalismo (*niyati*), ascetismo radical, de Makkhali Gosala', 'Apoiados por Ashoka e Dasharatha (grutas de Barabar e Nagarjuni); extinguem-se séculos mais tarde'],
    ['Cultos populares', 'Yakshas e yakshis (espíritos da natureza), árvores sagradas, deusas-mães', 'Visíveis na escultura (Yakshi de Didarganj); mais tarde absorvidos pelo budismo e pelo hinduísmo'],
    ['No noroeste', 'Cultos persas e gregos; aramaico como língua administrativa', 'Presença de comunidades *yavanas* (gregos) e *kambojas*']
  ] } },
  { h: '4. Economia' },
  'A base era a **agricultura**: arroz, trigo, cevada, lentilhas, cana-de-açúcar, algodão. O Estado cobrava um **imposto sobre a colheita** (em princípio um sexto, segundo os textos, que podia subir em tempo de aperto; em Lumbini, a aldeia ficou com uma carga de um oitavo), mais **taxas** sobre o comércio, as minas e a venda. O *Arthashastra* manda o rei **fundar aldeias novas**, abrir canais e açudes, dar sementes e animais aos camponeses, e vigiar as florestas, que forneciam madeira e **elefantes**. O Estado era dono de **minas** (ferro, cobre, ouro), de **florestas de elefantes**, de oficinas de tecelagem e de armazéns.',
  { img: 'imu-aldeia', leg: 'Reconstrução artística: uma aldeia da planície do Ganges no tempo dos Máurias, com campos de arroz, gado e casas de barro e colmo.' },
  { h: 'Moeda e comércio' },
  'O sistema monetário baseava-se em **moedas de prata com marca de punção** (*karshapana* ou *pana*), pequenas peças com símbolos gravados por vários punções: o sol, uma roda de seis raios, um monte com crescente, animais. Eram emitidas sob controlo do Estado (o *Arthashastra* tem um superintendente da moeda). O comércio fazia-se por terra, pelas rotas do Ganges, do Indo e do Decão, e pelo mar, a partir de Tamralipti e dos portos do oeste. Exportavam-se **tecidos**, pedras preciosas, pérolas e marfim; os Máurias procuravam cavalos e metais do noroeste. Mercadores e artesãos organizavam-se em **guildas** (*shreni*), com regras e tribunais próprios.',
  { img: 'imu-moeda-punch', leg: 'Moeda de prata com marca de punção (*karshapana*), do tipo usado no período máuria.' },
  { img: 'imu-mercado', leg: 'Reconstrução artística: mercado de Pataliputra, com tecidos de algodão, especiarias e mercadores de várias terras.' },
  { h: '5. A escrita e os éditos' },
  'Os éditos são os **primeiros documentos datáveis em escrita indiana** depois da civilização do Indo. Usam sobretudo a escrita **brahmi** (da esquerda para a direita), em várias formas de **prácrito** próximas da língua da corte de Magadha, adaptadas aos dialetos locais; no noroeste usam **kharosthi** (da direita para a esquerda, derivada do aramaico), e em Kandahar, o **grego** e o **aramaico**. A origem da brahmi (invenção indiana ou inspirada no aramaico) é um dos grandes debates; é provável que fosse conhecida antes de Ashoka, mas os éditos são o primeiro testemunho datável claro. Quase todas as escritas da Índia, do Sudeste Asiático e do Tibete derivam dela.',
  { img: 'imu-brahmi-alfabeto', leg: 'Quadro das letras da escrita brahmi, tal como aparecem nos éditos de Ashoka.' },
  'Os éditos foram **gravados** em três suportes: **rochas naturais** (os Éditos de Pedra, 14 maiores, repetidos em cerca de dez lugares e vários menores), **pilares monolíticos polidos** (os Éditos de Pilar, 7 maiores) e **paredes de grutas**. Ashoka diz-se «Devanampiya Piyadasi» e termina quase sempre pedindo que a mensagem seja **gravada para durar** «enquanto durarem o sol e a lua» (fórmula comum). Escribas e leitores eram necessários para a ler ao povo; os éditos eram provavelmente **lidos em voz alta** por funcionários.',
  { img: 'imu-edito-girnar', leg: 'A rocha de Girnar, no Gujarat, com os 14 Éditos de Pedra Maiores de Ashoka; a mesma rocha tem uma inscrição de Rudradaman (c. 150 d.C.).' },
  { img: 'imu-edito-kandahar', leg: 'Édito de Ashoka em grego, de Kandahar (Afeganistão); o texto usa vocabulário da filosofia grega para traduzir o *dhamma*.' },
  { img: 'imu-escribas-edito', leg: 'Reconstrução artística: gravadores a esculpir um édito numa rocha, sob a direção de um funcionário real.' },
  { h: '6. Sociedade' },
  'Megástenes dividiu a sociedade indiana em **sete classes**: filósofos (brâmanes e ascetas), agricultores, pastores, artesãos e comerciantes, soldados, inspetores e conselheiros do rei. É um esquema grego (talvez influenciado por modelos da filosofia grega) que **não corresponde** ao sistema de quatro *varnas* dos textos indianos, e os historiadores usam-no com cautela. A sociedade real era mais complexa: os textos indianos falam de *varnas* (brâmanes, kshatriyas, vaishyas, shudras) e de dezenas de grupos hereditários (*jatis*); as guildas e as seitas ascéticas ofereciam outras formas de identidade.',
  'Os Máurias não eram kshatriyas pelos critérios dos textos brâmanes (de origem humilde, segundo as tradições), e o seu sucesso mostra que **o poder político não dependia da classificação ritual**. Ashoka pede nos éditos respeito por brâmanes e *shramanas* (ascetas) em conjunto, e fala dos «mestres, dos pobres, dos escravos e dos servidores» como destinatários da generosidade.',
  { h: 'Escravatura e trabalho' },
  'Megástenes escreveu que na Índia **não havia escravos** (Arriano), o que é falso ou, pelo menos, enganador: o *Arthashastra* regula os *dasas* (servos por dívida, guerra ou nascimento), com limites à sua exploração (não se pode vender um *arya* como escravo, por exemplo), e os éditos de Ashoka mandam tratar bem os servos (*dasa-bhatakas*). Uma explicação possível é que a escravatura indiana, de tipo doméstico, não era como a grega, de mão de obra em massa, e Megástenes não a reconheceu. Os deportados de Kalinga mostram também formas de trabalho forçado.',
  { h: 'Mulheres' },
  'Os textos mostram uma sociedade patriarcal, em que as mulheres dependiam do pai, do marido e do filho, mas com algum direito de propriedade (o *stridhana*, bens da mulher) e de divórcio em casos limitados, segundo o *Arthashastra*. Megástenes descreve o rei **guardado por mulheres armadas**, e o *Arthashastra* confirma a existência de guardas femininas e espiãs. Ashoka criou **funcionários para as mulheres** (*stri-adhyaksha-mahamattas*, Édito n.º 12) e a única das suas esposas nos éditos, **Karuvaki**, aparece num édito sobre as suas doações (o «Édito da Rainha»). Segundo as crónicas, a sua filha **Sanghamitta** foi monja e missionária no Sri Lanka.',
  { h: '7. Casa, alimentação e vestuário' },
  'No campo, as casas eram de **barro, cana e colmo**, e nas cidades, de **madeira e tijolo** (o tijolo crescia em importância). As casas ricas tinham pátios. A família era geralmente patriarcal e extensa. Ao ar livre, a vida passava pela aldeia, pelo poço e pelo mercado.',
  'Comia-se **arroz, trigo, cevada, lentilhas**, legumes, leite e **ghee**, frutas (manga, banana, jaca) e açúcar de cana. As especiarias eram usadas na cozinha e na medicina. Megástenes (em Estrabão) diz que os indianos bebiam vinho (de arroz) só nos sacrifícios. Muitos, em especial budistas e jainistas, evitavam a carne, e Ashoka reduziu o consumo nas cozinhas reais; mas os animais continuavam a ser comidos, e a caça era um passatempo real.',
  'O vestuário era de **algodão** (as mussolinas finas são famosas), de lã e de seda, com o **dhoti** à cintura e um pano sobre o ombro (*uttariya*), e o equivalente das mulheres. As fontes gregas notam as joias de ouro e pedras, as roupas bordadas a ouro e as **sombrinhas** dos nobres. Segundo as fontes gregas, os homens usavam turbantes e tingiam a barba.',
  { img: 'imu-hospital', leg: 'Reconstrução artística: um centro de cuidados, com médicos e ervas medicinais, como os que o Édito n.º 2 de Ashoka manda estabelecer.' },
  { h: '8. Ciência, medicina e tecnologia' },
  'A **medicina** tradicional (*Ayurveda*) formava-se nesta época, e os éditos citam o apoio de Ashoka a cuidados para **pessoas e animais**, e à plantação de ervas medicinais. Grandes tratados (Charaka, Sushruta) são de data posterior. A **metalurgia** do ferro e do cobre era avançada, e o Estado controlava as minas. A **astronomia** e o calendário seguiam a tradição védica (os *Vedangas*); contactos com a Grécia vieram sobretudo mais tarde.',
  { h: 'A tecnologia da pedra: o polimento máuria' },
  'O que mais impressionou os arqueólogos foram os **pilares monolíticos** de arenito claro, vindos sobretudo das pedreiras de **Chunar**, perto de Varanasi, com 12 a 15 m de altura e muitas toneladas, **polidos** até brilharem como metal. Tinham um **capitel** esculpido separado (leões, touros, elefantes), com a forma de um sino invertido de pétalas. O polimento aparece também no interior das grutas de Barabar. Os pilares foram **transportados** a centenas de quilómetros dos locais de extração (a hipótese é por rio, em jangadas), e a perfeição do trabalho sugere oficinas de elite, onde, segundo alguns historiadores, trabalharam artesãos formados no mundo persa e grego (a influência é debatida).',
  { img: 'imu-pilar-transporte', leg: 'Reconstrução artística: o transporte de um pilar monolítico de arenito de Chunar até ao local onde vai ser erguido e polido.' },
  { h: '9. Lei e justiça' },
  'A lei tinha três fontes: o **rei** (*rajashasana*), o **dharma** e o **costume** das regiões, guildas e castas. O *Arthashastra* distingue os tribunais **civis** (*dharmasthiya*) e **criminais** (*kantakashodhana*, «limpeza dos espinhos»), com juízes e testemunhas, e regista penas por tipo de crime e de classe social. Ashoka diz que os *rajukas* têm poderes de julgar e de castigar, e que devem fazê-lo com **imparcialidade** (Pilar n.º 4). Pede também que os condenados à morte tenham **três dias** de aviso para rezar ou dar esmola, e que os presos sejam libertados nas datas especiais.',
  { h: '10. Divertimentos e jogos' },
  'O Édito n.º 1 proíbe certas reuniões festivas (*samajas*), com carne e bebida, mas aprova outras. Havia **música, dança, teatro, lutas** e corridas de carros, **jogos de dados** e de tabuleiro, e o rei caçava. O *Arthashastra* tem um superintendente das **jogos de azar**, que tira receita das casas de jogo e das cortesãs. A grande festa pública era a procissão real.',
  { h: '11. Guerra e diplomacia' },
  'O *Arthashastra* distingue três modos de guerra (aberta, encoberta e silenciosa), prefere a diplomacia quando possível e dá regras para cercos, espionagem e tratamento dos vencidos. Os Máurias combinaram **ação militar** (Chandragupta, Bindusara, Kalinga) e **diplomacia** (acordo com Seleuco, embaixadas helenísticas, missões do *dhamma*). O Édito n.º 13 propõe a «**conquista pelo dhamma**» como a verdadeira vitória, mas não promete largar as armas.',
  { cit: 'A maior conquista é a conquista pelo dhamma. (Édito de Pedra n.º 13, paráfrase)', fonte: 'Éditos de Ashoka' }
];

const personalidades = [
  'Os Máurias vivem em fontes de tipos muito diferentes: inscrições do próprio rei, relatos de estrangeiros, crónicas religiosas e lendas. Em cada figura, assinala-se o que é historicamente seguro e o que é tradição. As datas são aproximadas.',
  { h: 'Chandragupta Maurya (c. 321 – 297 a.C.)' },
  'Fundador do império. A sua origem é incerta (ver «Quem eram os Máurias?»). As fontes gregas chamam-lhe *Sandrokottos* ou *Androkottos*, e foi esta identificação com Chandragupta, feita por **William Jones** em 1793, que permitiu ancorar a cronologia indiana à grega. Derrubou os Nandas, dominou o norte, conteve os gregos e fez o acordo com Seleuco. Segundo a tradição jainista, abdicou e retirou-se como asceta; é debatido.',
  { h: 'Chanakya / Kautilya / Vishnugupta' },
  'Conselheiro lendário de Chandragupta. As histórias (o brâmane humilhado pelo rei Nanda que jura vingar-se, o veneno nas refeições do rei) vêm de fontes muito tardias, como o drama *Mudrarakshasa* (de Vishakhadatta, entre os séculos IV e VIII d.C.), e das crónicas budistas e jainistas. A autoria do *Arthashastra* é hoje considerada coletiva e tardia (ver Sociedade). A existência de um conselheiro com este papel é possível, mas não está confirmada por fontes contemporâneas: Megástenes não fala dele.',
  { h: 'Seleuco I Nicator (c. 358 – 281 a.C.)' },
  'General de Alexandre e fundador do Império Selêucida. Tentou recuperar o leste e foi detido por Chandragupta. O acordo (c. 305 – 303 a.C.) trouxe-lhe 500 elefantes e paz no leste, e permitiu-lhe voltar-se para os rivais no Ocidente, vencendo em Ipsos (301 a.C.).',
  { h: 'Megástenes (c. 350 – 290 a.C.)' },
  'Diplomata grego, nascido talvez na Jónia, que viveu na Aracósia e foi enviado várias vezes a Pataliputra. A *Indica* descreve a capital, a administração, os «sete grupos» da sociedade e fantasias (povos sem boca, formigas gigantes que escavam ouro). Foi a fonte principal dos gregos e romanos sobre a Índia durante séculos. As partes sobre as instituições estão em acordo geral com outras fontes, mas é difícil separar observação, tradução e idealização.',
  { h: 'Bindusara (c. 297 – 273 a.C.)' },
  'Filho de Chandragupta, pai de Ashoka. É o menos conhecido dos três grandes Máurias. Os gregos chamam-lhe *Amitrochates* (de *Amitraghata*, «destruidor de inimigos»), e uma tradição muito tardia (a do tibetano Taranatha) diz que conquistou o território «entre os dois mares», talvez uma referência ao Decão. Troca embaixadores com os selêucidas e com o Egito (**Dionísio**, enviado de Ptolomeu II). O *Mahavamsa* diz que sustentava milhares de brâmanes, e o *Ashokavadana* liga a sua corte a um asceta ajivika; as fontes são pouco claras quanto às suas crenças.',
  { h: 'Ashoka (n. c. 304 a.C.; reina c. 268 – 232 a.C.)' },
  'O terceiro e mais famoso imperador. Sabemos dele por duas fontes que não coincidem em tudo: os **éditos** (o rei que fala de si) e as **crónicas** budistas (o «Ashoka cruel» e depois o «Ashoka justo», um contraste típico da hagiografia). Foi vice-rei, subiu ao trono depois de uma disputa e conquistou Kalinga. A partir daí promoveu o *dhamma*, patrocinou o budismo, ergueu pilares e estupas e escreveu os éditos, de que se destaca a variedade de tom: de orgulhoso e paternalista a humilde e reflexivo. Governou cerca de 37 anos. Os historiadores hoje preferem vê-lo como um **governante pragmático** que usou a ética como ferramenta de unidade, e também como um homem que mudou realmente.',
  { h: 'Devi e Karuvaki, as rainhas de Ashoka' },
  'Segundo as crónicas do Sri Lanka, a primeira esposa de Ashoka foi **Devi** (ou Vidisha-mahadevi), filha de um mercador de Vidisha, mãe de Mahinda e Sanghamitta. A única rainha nomeada nos éditos é **Karuvaki**, mãe de Tivara: o «Édito da Rainha», no pilar de Allahabad-Kosam, regista as suas doações (mangueiras, jardins, esmolas), e mostra que as mulheres da casa real tinham património próprio. As crónicas falam de outras rainhas (Asandhimitra, Tishyarakshita), com lendas.',
  { h: 'Mahinda e Sanghamitta' },
  'Filho e filha de Ashoka (ou irmão, segundo outra versão, no caso de Mahinda), segundo as crónicas do Sri Lanka. Mahinda levou o budismo à ilha, onde converteu o rei, e Sanghamitta levou um ramo da árvore Bodhi de Bodh Gaya, que se diz estar na origem da árvore sagrada de Anuradhapura (**Jaya Sri Maha Bodhi**, ainda venerada). São figuras centrais da tradição Theravada, mas a sua história só aparece em fontes tardias (Dipavamsa, Mahavamsa, comentários), e não nos éditos.',
  { h: 'Moggaliputta Tissa (tradição)' },
  'Monge budista, que as crónicas do Sri Lanka apresentam como presidente do terceiro concílio em Pataliputra e como autor do *Kathavatthu*. Teria sido o mestre de Ashoka (ou de Mahinda), mas outras tradições budistas atribuem o papel a outros monges (**Upagupta**, na tradição do norte). Quase nada se sabe com certeza.',
  { h: 'Devanampiya Tissa (c. 250 – 210 a.C.)' },
  'Rei de Sri Lanka, contemporâneo de Ashoka. A tradição diz que foi convertido ao budismo por Mahinda em Mihintale e que fundou o mosteiro de Mahavihara em Anuradhapura. O seu nome («Amado dos Deuses») é o mesmo epíteto que Ashoka usa: o que mostra a partilha de uma fórmula régia.',
  { h: 'Dasharatha e Samprati' },
  'Netos de Ashoka, segundo as listas. **Dasharatha** deixou inscrições em Nagarjuni (Bihar), a oferecer grutas aos ajivikas, e imitou o título «Devanampiya». **Samprati** é, para os jainistas, o grande protetor da religião, o «Ashoka jainista»; os historiadores duvidam. As listas de reis depois de Ashoka são confusas, e até a divisão do império entre dois ramos (este e oeste) é debatida.',
  { h: 'Brihadratha e Pushyamitra Shunga (séc. II a.C.)' },
  'Brihadratha, o último rei máuria, foi morto pelo seu comandante, **Pushyamitra Shunga**, durante uma parada militar, segundo Bana (séc. VII d.C.) e os Puranas. Pushyamitra fundou a dinastia dos Sungas, e as tradições budistas pintam-no como perseguidor de monges (e destruidor de mosteiros, de que a arqueologia mostra poucas provas), enquanto os textos brâmanes o louvam como restaurador dos rituais. A verdade está provavelmente no meio: um general que tomou o poder e patrocinou os brâmanes e as artes, incluindo Bharhut e Sanchi.',
  { h: 'James Prinsep (1799 – 1840)' },
  'Oficial britânico da Casa da Moeda de Calcutá e secretário da Sociedade Asiática de Bengala. Em 1837 – 1838 decifrou a escrita brahmi, graças a moedas bilingues grego-brahmi e a inscrições de doadores de Sanchi, e leu os éditos. Morreu aos 40 anos, em Londres, depois de uma doença. Sem o seu trabalho (e o de colegas como George Turnour, Christian Lassen e Alexander Cunningham) Ashoka continuaria esquecido.'
];

const legado = [
  { h: 'O que nos deixaram' },
  { lista: [
    '**A ideia de um império indiano:** os Máurias criaram o modelo de um Estado que une o subcontinente; reis posteriores (Guptas, Mogóis, a Índia moderna) invocaram o seu exemplo.',
    '**Os éditos:** a mais antiga voz de um governante a falar de tolerância, de compaixão e de consciência própria, e as mais antigas inscrições indianas datáveis.',
    '**Os estados budistas:** a imagem de **Ashoka como rei ideal** (*dhammaraja*) foi modelo para reis do Sri Lanka, da Birmânia, da Tailândia e do Camboja ao longo de séculos.',
    '**A teoria política:** o *Arthashastra*, a teoria dos mandalas e a burocracia.',
    '**A escrita brahmi**, ancestral de quase todas as escritas do sul e sudeste da Ásia.',
    '**A arquitetura em pedra:** pilares polidos, estupas e as primeiras grutas escavadas.',
    '**O budismo como religião mundial,** que chega ao Sri Lanka, à Ásia Central e, daí, à China.'
  ] },
  { h: 'Os símbolos da Índia moderna' },
  { caixa: 'Leões e roda', texto: 'Em 1950, a República da Índia adotou como **emblema do Estado** o capitel de Sarnath, com os quatro leões (três visíveis, sobre uma base com a roda e animais) e o lema *Satyameva Jayate* («só a verdade triunfa», de um Upanishad). A **Ashoka Chakra**, de 24 raios, está na bandeira. O **Ashoka Chakra** é também o nome de condecorações militares.' },
  { img: 'imu-didarganj', leg: 'A Yakshi de Didarganj (Museu de Patna), escultura em arenito polido; a datação (máuria ou posterior) é debatida.' },
  { h: 'Arte: o polimento e os capitéis' },
  'Os pilares terminavam num **capitel** de leões, touros ou elefantes, assente num ábaco decorado com flores de lótus ou animais, símbolos do poder do *dhamma* ou do rei. O de Sarnath é o mais perfeito. Os **pilares de Lauriya-Nandangarh** (com leão) e de **Rampurva** (touro) mostram variações. A escultura em pedra tem outra figura: a **Yakshi** de Didarganj, de superfície polida como os pilares, que alguns datam do período máuria e outros de épocas posteriores.',
  { img: 'imu-pilar-lauriya', leg: 'O pilar de Lauriya-Nandangarh (Bihar), com um leão no topo e éditos de Ashoka, ainda no local original.' },
  { img: 'imu-pilar-rampurva', leg: 'O capitel de touro de Rampurva (Bihar), arenito polido, século III a.C.; hoje no Rashtrapati Bhavan, em Nova Deli.' },
  { h: 'Os pilares na História' },
  'Os pilares sobreviveram séculos como curiosidades. O de **Allahabad**, que veio provavelmente de Kausambi, tem éditos de Ashoka, o «Édito da Rainha», uma inscrição de **Samudragupta** (séc. IV d.C.) e outra do imperador mogol Jahangir. O sultão **Firuz Shah Tughlaq** (séc. XIV) levou dois pilares para Deli (Topra e Meerut), onde ninguém conseguia ler a escrita; as explicações locais falavam de «bengala de Bhima» (herói do Mahabharata).',
  { img: 'imu-allahabad-pilar', leg: 'O pilar de Allahabad (Prayagraj), com éditos de Ashoka e inscrições posteriores de Samudragupta e de Jahangir.' },
  { h: 'A redescoberta' },
  'Durante mais de dois mil anos, o nome de Ashoka sobreviveu só em lendas budistas fora da Índia. Em 1837, **James Prinsep** leu a brahmi; **George Turnour** identificou Piyadasi com Ashoka, a partir do *Mahavamsa* do Sri Lanka; **Alexander Cunningham** escavou Sanchi, Sarnath e Bodh Gaya; e a descoberta de **Lumbini** (1896) e de **Maski** (1915, com o nome «Ashoka») completou o quadro. O *Arthashastra* foi publicado em 1909. Estes achados fizeram dos Máurias um símbolo do primeiro grande passado da Índia, o que serviu o nacionalismo indiano do século XX.',
  { img: 'imu-prinsep', leg: 'James Prinsep (1799 – 1840), que decifrou a escrita brahmi em 1837 – 1838. Retrato do século XIX.' },
  { h: 'Um debate: Ashoka, santo ou estadista?' },
  { caixa: 'Duas leituras', texto: [
    'Para uns, como o historiador **A. L. Basham** ou os autores budistas, Ashoka foi um **monarca iluminado**, que aplicou valores budistas ao governo. Para outros, como **Romila Thapar**, o *dhamma* foi uma **política de Estado**, uma ética pública sem pertença religiosa, que servia para unir um império diverso, e Ashoka foi um governante prático, mais do que um místico. Uma terceira posição, mais céptica, nota que, depois de Ashoka, o império caiu em meio século, e que o seu *dhamma* não substituiu os meios militares.',
    'Também se debate se o *dhamma* **enfraqueceu o exército** e causou o declínio (tese antiga de H. C. Raychaudhuri, hoje quase abandonada), e se o fim do império se deveu a **problemas financeiros**, **sucessão difícil**, **excessiva centralização** e pressões do noroeste.'
  ] },
  { h: 'Porque caiu o império?' },
  'Não há uma resposta única. Os historiadores apontam: (1) **dificuldades de sucessão**, com a divisão em dois ramos; (2) **peso financeiro** de um exército e de uma burocracia imensos, com moedas cada vez mais baixas em prata (hipótese discutida); (3) **dependência de um centro forte** (Magadha) e de um rei activo, sem estruturas locais independentes; (4) **pressões externas** (gregos da Báctria, Antíoco III) e **autonomia de províncias**; (5) **golpe de Estado** de Pushyamitra. É uma queda típica de impérios de base pessoal.',
  { h: 'Onde visitar' },
  { lista: [
    '**Sanchi (Madhya Pradesh):** o Grande Estupa, o pilar de Ashoka e os estupas menores. Património Mundial (1989).',
    '**Sarnath (Uttar Pradesh):** o Museu de Sarnath, com o capitel dos quatro leões, e as ruínas do mosteiro.',
    '**Bodh Gaya e Barabar (Bihar):** o templo de Mahabodhi; as grutas dos ajivikas, perto de Gaya.',
    '**Patna (Bihar):** o Museu de Patna (Yakshi de Didarganj) e Kumhrar, com as ruínas da sala de colunas.',
    '**Lumbini (Nepal):** o pilar de Ashoka, num sítio Património Mundial.',
    '**Dhauli e Jaugada (Odisha):** o elefante e os éditos de Kalinga.',
    '**Girnar (Gujarat) e Dhauli:** rochas com éditos maiores.',
    '**Taxila (Paquistão):** Dharmarajika e outros mosteiros; Património Mundial (1980).',
    '**Mihintale e Anuradhapura (Sri Lanka):** lugares da tradição de Mahinda.',
    '**Museu Nacional (Deli) e Museu Indiano (Calcutá):** pilares, moedas e esculturas máurias.',
    '**Museu Britânico (Londres):** moedas e inscrições. Os éditos gregos de Kandahar foram guardados no Museu de Cabul (Afeganistão), cujo estado atual é incerto.'
  ] }
];

const quiz = [
  { p: 'Quem fundou o Império Máuria, por volta de 321 a.C.?', op: ['Ashoka', 'Chandragupta Maurya', 'Bindusara', 'Pushyamitra Shunga'], certa: 1, exp: 'Chandragupta derrubou os Nandas e tomou Pataliputra. Ashoka era o seu neto e Pushyamitra, o general que pôs fim à dinastia.' },
  { p: 'Qual era a capital do Império Máuria?', op: ['Taxila', 'Ujjain', 'Pataliputra', 'Varanasi'], certa: 2, exp: 'Pataliputra, no atual Patna, junto ao Ganges. Taxila e Ujjain eram capitais de províncias.' },
  { p: 'Que acordo fez Chandragupta com Seleuco I, por volta de 305 – 303 a.C.?', op: ['Casou com a filha de Seleuco e foi a Babilónia', 'Recebeu territórios do Indo e deu 500 elefantes', 'Cedeu o Punjab a Seleuco', 'Aliou-se a Seleuco contra os Nandas'], certa: 1, exp: 'Seleuco cedeu territórios a oeste do Indo e recebeu 500 elefantes de guerra. Parece ter havido também uma aliança por casamento, cujo sentido é debatido.' },
  { p: 'Quem foi Megástenes?', op: ['Um general macedónio', 'O embaixador grego de Seleuco em Pataliputra', 'Um monge budista', 'O ministro de Ashoka'], certa: 1, exp: 'Escreveu a *Indica*, perdida mas conservada em fragmentos de Estrabão, Arriano e Diodoro.' },
  { p: 'A que fonte se atribui a teoria dos mandalas, sobre política externa?', op: ['Os éditos de Ashoka', 'O *Arthashastra*', 'O *Mahabharata*', 'O *Mahavamsa*'], certa: 1, exp: 'O *Arthashastra*, atribuído a Kautilya (Chanakya), mas composto e revisto ao longo de séculos, segundo a maioria dos investigadores.' },
  { p: 'Em que guerra Ashoka mudou de atitude, segundo os seus próprios éditos?', op: ['Guerra contra Seleuco', 'Guerra de Kalinga', 'Guerra contra os Cholas', 'Guerra contra os Hunas'], certa: 1, exp: 'No Édito n.º 13, Ashoka fala de 150 000 deportados, 100 000 mortos e do seu remorso depois da conquista de Kalinga.' },
  { p: 'Em que escritas e línguas foram gravados os éditos de Ashoka?', op: ['Só em sânscrito', 'Brahmi, kharosthi, grego e aramaico', 'Só em grego', 'Escrita do Indo'], certa: 1, exp: 'Na maior parte do império, em prácrito com escrita brahmi; no noroeste, em kharosthi; em Kandahar, em grego e aramaico.' },
  { p: 'Quem decifrou a escrita brahmi e leu os éditos, em 1837?', op: ['William Jones', 'James Prinsep', 'Alexander Cunningham', 'Max Müller'], certa: 1, exp: 'James Prinsep, com base em moedas bilingues e em inscrições de doadores.' },
  { p: 'O que é o dhamma de Ashoka?', op: ['Uma religião nova, criada por ele', 'Um código ético público, de inspiração budista, para todos os súditos', 'Um exército especial', 'Um imposto'], certa: 1, exp: 'Não é doutrina budista em sentido estrito: pede respeito, compaixão, tolerância e não violência, e Ashoka honra todas as seitas.' },
  { p: 'A que seita Ashoka dedicou as grutas de Barabar?', op: ['Aos budistas', 'Aos jainistas', 'Aos ajivikas', 'Aos brâmanes'], certa: 2, exp: 'As grutas de Sudama e Visva Zopri foram dadas aos ajivikas no 12.º ano de reinado, c. 257 a.C.' },
  { p: 'Segundo as crónicas do Sri Lanka, quem levou o budismo à ilha?', op: ['Megástenes', 'Mahinda, filho de Ashoka', 'Chanakya', 'Kanishka'], certa: 1, exp: 'A tradição Theravada diz que Mahinda converteu o rei Devanampiya Tissa em Mihintale; a história não está nos éditos.' },
  { p: 'Que monumento do tempo de Ashoka deu o emblema à Índia moderna?', op: ['O Pilar de Ferro de Delhi', 'O capitel de Sarnath', 'O Taj Mahal', 'A gruta de Karli'], certa: 1, exp: 'O capitel dos quatro leões de Sarnath, adotado como emblema do Estado em 1950.' },
  { p: 'Quem matou o último rei máuria, Brihadratha, por volta de 185 a.C.?', op: ['Seleuco', 'Samudragupta', 'Pushyamitra Shunga', 'Menandro'], certa: 2, exp: 'O seu general, que fundou a dinastia dos Sungas.' },
  { p: 'O que era o chamado «polimento máuria»?', op: ['Um tipo de moeda', 'O acabamento brilhante, como espelho, dado ao arenito dos pilares e de algumas grutas', 'Uma técnica de guerra', 'Um estilo de escrita'], certa: 1, exp: 'Os pilares de Ashoka, de arenito de Chunar, e o interior das grutas de Barabar têm uma superfície polida que brilha.' },
  { p: 'Porque é preciso cuidado ao usar o Arthashastra como retrato do governo máuria?', op: ['Porque é muito curto', 'Porque a forma que temos foi composta e revista até aos primeiros séculos d.C.', 'Porque foi escrito por um grego', 'Porque se perdeu'], certa: 1, exp: 'Os estudos recentes veem-no como obra de várias mãos, entre os séculos II a.C. e III d.C., que descreve uma teoria do Estado, mais do que a prática de Chandragupta.' }
];

export default {
  id: 'india-classica',
  cor: '#c4682f',
  emblema: '../../assets/img/india-classica.png',
  grupo: { ...GRUPO, aqui: 'maurya' },
  nome:    { pt: 'O Império Maurya e Ashoka', en: 'The Maurya Empire and Ashoka' },
  periodo: { pt: 'c. 321 – 185 a.C.', en: 'c. 321 – 185 BC' },
  visao:          { pt: visao, en: EN.visao },
  linha:          { pt: linha, en: EN.linha },
  mapa:           { pt: mapa, en: EN.mapa },
  sociedade:      { pt: sociedade, en: EN.sociedade },
  personalidades: { pt: personalidades, en: EN.personalidades },
  legado:         { pt: [...legado, ...CRED.pt], en: [...EN.legado, ...CRED.en] },
  quiz:           { pt: quiz, en: EN.quiz }
};
