// GRÉCIA ANTIGA: FILOSOFIA, CIÊNCIA E LITERATURA — conteúdo completo em português. A versão inglesa está em dados-en.js (mesma estrutura, mesmos ids de imagem).
// Datas aproximadas, na «cronologia média». Muitas datas de nascimento e morte de pensadores antigos são estimativas ou tradições tardias (sobretudo Diógenes Laércio, século III d.C.); assinala-se quando há debate.
// Imagens: cada {img:'id'} procura o ficheiro  grecia/filosofia-ciencia/img/id.jpg  (ver IMAGENS_GRECIA_FILOSOFIA_CIENCIA.md).
import EN from './dados-en.js';
import CRED from './creditos.js';
import { GRUPO } from '../grupo.js';

const visao = [
  { caixa: 'Em resumo', texto: [
    'Entre os séculos VIII a.C. e II d.C., os gregos criaram a maior parte das formas de pensar e de escrever que ainda hoje reconhecemos como «europeias»: a **filosofia**, a **demonstração matemática**, a **ciência da natureza**, a **medicina baseada na observação**, a **história** como investigação, o **teatro** e a **poesia lírica**. Esta página percorre as grandes figuras e as grandes obras: dos primeiros pensadores de **Mileto** a **Sócrates**, **Platão** e **Aristóteles**; de **Euclides**, **Arquimedes** e **Eratóstenes** a **Hipócrates**; de **Heródoto** e **Tucídides** a **Homero**, **Safo**, **Ésquilo**, **Sófocles**, **Eurípides** e **Aristófanes**.',
    'Não foi uma obra de um só lugar nem de uma só época. Começou nas cidades gregas da costa da Ásia Menor, floresceu em **Atenas** no século IV a.C., e passou a **Alexandria** e a outros centros helenísticos, onde reis pagaram a sábios e a bibliotecas. É também uma história de **perdas**: do que os gregos escreveram, sobreviveu talvez uma pequena parte, e quase tudo o que sabemos de muitos pensadores vem de citações de outros autores, escritas séculos depois.'
  ] },
  { img: 'gfc-escola-atenas-rafael', leg: 'A *Escola de Atenas*, fresco de Rafael, 1509–1511, nos Palácios do Vaticano. É uma imagem renascentista, e não um retrato fiel: reúne pensadores de séculos diferentes, com Platão e Aristóteles ao centro.' },
  { h: 'Uma ideia nova: explicar sem recorrer aos deuses' },
  'Antes dos gregos, as grandes civilizações do Egito e da Mesopotâmia já faziam astronomia, medicina e matemática prática, em muitos casos com grande precisão. O que muda na Grécia, a partir do século VI a.C., é a pergunta e o método: **porquê?** Em vez de aceitar que o trovão é a voz de Zeus, alguns pensadores procuraram uma explicação **natural** e discutiram-na em público, aceitando que outros a refutassem. A discussão aberta, com argumentos, definições e contra-argumentos, é a grande invenção, mais do que qualquer teoria em particular, e muitas das teorias antigas estavam erradas.',
  { img: 'gfc-tales-observa', leg: 'Cena imaginada de Tales de Mileto a observar o céu, c. século VI a.C. Os pormenores do cenário são hipotéticos. Ilustração gerada por IA.' },
  { h: 'As grandes fases' },
  { tabela: { cab: ['Fase', 'Datas aproximadas', 'Figuras e obras'], linhas: [
    ['Poesia épica e didática', 'séc. VIII–VII a.C.', 'Homero (*Ilíada*, *Odisseia*), Hesíodo (*Teogonia*, *Trabalhos e Dias*)'],
    ['Lírica arcaica', 'séc. VII–V a.C.', 'Arquíloco, Safo, Alceu, Simónides, Píndaro'],
    ['Primeiros filósofos (pré-socráticos)', 'c. 600–400 a.C.', 'Tales, Anaximandro, Anaxímenes, Pitágoras, Heráclito, Parménides, Empédocles, Anaxágoras, Demócrito'],
    ['Idade de ouro de Atenas', 'séc. V a.C.', 'Ésquilo, Sófocles, Eurípides, Aristófanes, Heródoto, Tucídides, os sofistas, Sócrates, Hipócrates'],
    ['As grandes escolas atenienses', 'séc. IV a.C.', 'Platão (Academia), Aristóteles (Liceu), Xenofonte, Demóstenes'],
    ['Período helenístico', 'séc. III–I a.C.', 'Epicuro, Zenão de Cício, Euclides, Arquimedes, Eratóstenes, Aristarco, Hiparco, Calímaco, Teócrito, Menandro'],
    ['Período greco-romano', 'séc. I–II d.C. e depois', 'Plutarco, Galeno, Ptolemeu, Epicteto e outros autores de língua grega sob o domínio de Roma (só de passagem)']
  ] } },
  { h: 'Como sabemos o que sabemos' },
  'Quase nenhuma obra grega antiga chegou até nós no original. O que lemos hoje foi **copiado à mão** durante séculos, primeiro em rolos de papiro e depois, em cadernos de pergaminho, por copistas gregos, bizantinos, árabes e latinos. Com a cópia vieram erros e, por vezes, acrescentos; e muitos textos desapareceram porque ninguém os copiou.',
  { lista: [
    '**Obras completas:** só algumas, como os diálogos de Platão, as *Histórias* de Heródoto, a *Guerra do Peloponeso* de Tucídides, os *Elementos* de Euclides ou sete tragédias de Ésquilo e de Sófocles.',
    '**Fragmentos e citações:** de pensadores como Heráclito, Parménides ou Safo só restam frases soltas, citadas por outros autores. Chamam-se *fragmentos*, e a ordenação e a tradução são, por vezes, muito discutidas.',
    '**Relatos de segunda mão:** muitos pormenores biográficos vêm de **Diógenes Laércio** (século III d.C.), que escreveu *Vidas e Doutrinas dos Filósofos Ilustres* seis séculos depois de alguns dos seus protagonistas. É útil, mas mistura factos com anedotas.',
    '**Papiros e descobertas modernas:** em Oxirrinco, no Egito, escavações a partir de 1896 recuperaram milhares de fragmentos de papiro com textos gregos. Em 1890 foi adquirido no Egito o papiro da *Constituição dos Atenienses* (editado em 1891); em 1958 foi publicada uma comédia quase completa de Menandro, o *Díscolo*.'
  ] },
  { img: 'gfc-papiro-euclides', leg: 'Fragmento de papiro de Oxirrinco (P.Oxy. 29), c. 100 d.C., com um diagrama dos *Elementos* de Euclides. Universidade da Pensilvânia.' },
  { h: 'Onde nasceu o pensamento grego' },
  'O pensamento grego não nasceu só na Grécia europeia. Os primeiros filósofos viveram na **Jónia**, a costa grega da Ásia Menor, em cidades como **Mileto** e **Éfeso**, ricas pelo comércio e em contacto com o Egito e a Mesopotâmia. Depois, foi no **sul de Itália** e na **Sicília** (Crotona, Eleia, Siracusa) que se ensinou o pitagorismo e se escreveu filosofia em verso. **Atenas** só se torna centro intelectual no século V a.C., quando o império ateniense atrai sábios e mestres de toda a parte. Com Alexandre e os seus sucessores, o centro desloca-se para **Alexandria**.',
  { img: 'gfc-pitagoras-busto', leg: 'Busto de um tipo romano identificado como Pitágoras (c. 570 – c. 495 a.C.), cópia de um original grego. Museus Capitolinos, Roma. A identificação é tradicional e não é certa.' },
  { h: 'Os temas que atravessam a filosofia grega' },
  { lista: [
    '**O que existe e de que é feito o mundo** (a *physis*, natureza): água, ar, fogo, «o ilimitado», átomos.',
    '**O que é o conhecimento** e como distingui-lo da opinião: Parménides, Platão, Aristóteles, os céticos.',
    '**Como devemos viver** (a ética): Sócrates, Platão, Aristóteles, estoicos, epicuristas.',
    '**Como deve ser governada uma cidade** (a política): a *República* e as *Leis* de Platão, a *Política* de Aristóteles.',
    '**Como se argumenta bem** (a lógica e a retórica): Aristóteles criou a primeira lógica formal conhecida.'
  ] },
  { img: 'gfc-socrates-busto', leg: 'Busto de Sócrates (c. 470 – 399 a.C.), cópia romana de um original grego do século IV a.C. Louvre, Paris.' },
  { h: 'Ciência e matemática: provar, medir, calcular' },
  'Os gregos fizeram da matemática uma disciplina de **demonstração**. A partir de definições e de axiomas, **Euclides** (c. 300 a.C.) deduziu centenas de proposições em ordem rigorosa. **Arquimedes** calculou áreas e volumes e criou os fundamentos da estática; **Eratóstenes** mediu a Terra com uma sombra e uma distância; **Aristarco** propôs que a Terra girava à volta do Sol; **Hiparco** montou um catálogo de estrelas. Nem todas estas ideias foram aceites na época: o sistema com a Terra no centro, de Aristóteles e mais tarde de Ptolemeu, dominou durante quase dois mil anos.',
  { h: 'Literatura: da voz ao livro' },
  'A literatura grega começou como **voz**: poemas cantados ou recitados em festas, banquetes e concursos, que só mais tarde foram escritos. Daí vem a sua musicalidade, o uso de fórmulas repetidas e a importância dos concursos (tragédias, comédias, ditirambos, jogos pan-helénicos). Só com o alfabeto, o papiro e, mais tarde, as bibliotecas helenísticas é que a literatura se tornou também **livro**, copiado, comentado e ordenado em edições.',
  { img: 'gfc-homero-busto', leg: 'Busto de Homero, cópia romana de um tipo helenístico (o tipo do «Homero cego»). Museu Britânico, Londres. Não há retrato real de Homero.' },
  { h: 'Porque importam' },
  { lista: [
    '**Palavras:** filosofia, ética, lógica, física, biologia, história, teatro, tragédia, comédia, poesia, democracia, ciência e muitas outras vêm do grego.',
    '**Método:** a ideia de que uma afirmação precisa de prova e de que se aprende discutindo é o ponto de partida da ciência e da universidade.',
    '**Obras de leitura viva:** Homero, Sófocles, Platão e Tucídides continuam a ser lidos, representados e debatidos.',
    '**Ponte para o futuro:** os textos gregos foram traduzidos para latim, siríaco e árabe, e voltaram à Europa medieval e renascentista, onde alimentaram a ciência moderna.'
  ] },
  { caixa: 'Hoje', texto: 'Quem estuda lógica, geometria, ética, política, medicina ou crítica literária ainda usa conceitos definidos pelos gregos: o silogismo, o axioma, o *ethos*, a catarse, o juramento hipocrático (no sentido ético, embora o texto original seja de autoria incerta). Em Atenas, o Liceu de Aristóteles e a Academia de Platão podem visitar-se como sítios arqueológicos, e o Teatro de Dioniso ainda se mantém de pé.' },
  { h: 'Atenção às simplificações' },
  'Este tema presta-se a histórias bonitas que são **falsas ou incertas**: a «Terra plana» da Antiguidade (os gregos instruídos sabiam que a Terra era esférica desde o século IV a.C.); o «Eureka!» de Arquimedes na banheira (é uma anedota tardia, de Vitrúvio); os «espelhos ardentes» de Arquimedes contra os navios romanos (lenda, sem prova); a «queima da Biblioteca de Alexandria» num único dia. A secção «Sociedade» distingue em cada caso o que se sabe do que é tradição.'
];

const linha = [
  'Cada entrada é uma data aproximada: muitos pensadores gregos não têm data de nascimento nem de morte seguras, e as datas «de atividade» (o *floruit*) são convenções dos historiadores antigos, sobretudo de Apolodoro de Atenas (século II a.C.), citado por Diógenes Laércio.',
  { linha: [
    { d: 'c. 750–700 a.C.', t: 'Homero e Hesíodo', x: 'Datas debatidas para a fixação por escrito da *Ilíada* e da *Odisseia* (tradicionalmente Homero, século VIII a.C.) e para a *Teogonia* e os *Trabalhos e Dias* de Hesíodo.' },
    { d: 'c. 650–600 a.C.', t: 'Lírica arcaica', x: 'Arquíloco de Paros, Álcman em Esparta, e em Lesbos Safo e Alceu: a poesia passa a falar na primeira pessoa.' },
    { d: 'c. 585 a.C.', t: 'Tales e o eclipse', x: 'Segundo Heródoto, Tales de Mileto previu um eclipse solar durante a guerra entre lídios e medos. Os historiadores da ciência duvidam de que o pudesse prever com rigor.' },
    { d: 'c. 550 a.C.', t: 'Anaximandro', x: 'Discípulo de Tales, defende que a origem de tudo é o *ápeiron* («o ilimitado») e desenha, segundo a tradição, um dos primeiros mapas do mundo conhecido.' },
    { d: 'c. 534 a.C.', t: 'Tespis e a tragédia', x: 'Segundo a tradição, o ator Tespis ganha o primeiro concurso de tragédia nas Grandes Dionísias de Atenas.' },
    { d: 'c. 530 a.C.', t: 'Pitágoras em Crotona', x: 'Natural de Samos, funda no sul de Itália uma comunidade que mistura matemática, música, religião e regras de vida.' },
    { d: 'c. 500 a.C.', t: 'Heráclito e Parménides', x: 'Heráclito de Éfeso fala do devir e do «logos»; Parménides de Eleia escreve um poema sobre o ser, que mudou a filosofia.' },
    { d: '472 a.C.', t: 'Os *Persas* de Ésquilo', x: 'A mais antiga tragédia grega que conservamos, representada em Atenas oito anos depois de Salamina.' },
    { d: '458 a.C.', t: 'A *Oresteia*', x: 'Ésquilo ganha com a trilogia sobre Agamémnon, Orestes e a criação do tribunal do Areópago; é a única trilogia completa que sobreviveu.' },
    { d: 'c. 440–425 a.C.', t: 'Sofistas e atomistas', x: 'Protágoras e, a partir de 427 a.C., Górgias ensinam retórica em Atenas; Leucipo e Demócrito propõem que a matéria é feita de átomos; Anaxágoras ensina em Atenas.' },
    { d: 'c. 430–425 a.C.', t: 'As *Histórias* de Heródoto', x: 'Primeira grande obra de investigação histórica em prosa; o autor morre pouco depois, por volta de 425 a.C.' },
    { d: '431–404 a.C.', t: 'Tucídides escreve a Guerra do Peloponeso', x: 'Começa a escrever o relato logo no início da guerra; a obra interrompe-se no ano de 411 a.C.' },
    { d: '399 a.C.', t: 'Morte de Sócrates', x: 'Condenado por impiedade e por corromper os jovens, bebe a cicuta em Atenas, segundo o relato de Platão no *Fédon*.' },
    { d: 'c. 387 a.C.', t: 'A Academia', x: 'Platão funda a sua escola num ginásio dos arredores de Atenas, dedicado ao herói Academo.' },
    { d: '335 a.C.', t: 'O Liceu', x: 'Aristóteles regressa a Atenas e funda a sua escola, que ficou conhecida como a dos «peripatéticos».' },
    { d: '323 a.C.', t: 'Morte de Alexandre e de Aristóteles', x: 'Alexandre morre em Babilónia (junho); Aristóteles, de quem os atenienses desconfiam por ligação à Macedónia, retira-se para Cálcis, onde morre em 322 a.C.' },
    { d: 'c. 306 a.C.', t: 'O Jardim de Epicuro', x: 'Epicuro funda a sua escola numa casa com jardim em Atenas; por volta de 300 a.C., Zenão de Cício começa a ensinar na Estoa Pecile.' },
    { d: 'c. 300 a.C.', t: 'Os *Elementos* de Euclides', x: 'Em Alexandria, o manual de geometria que durou mais de dois mil anos.' },
    { d: 'c. 290–280 a.C.', t: 'O Museu e a Biblioteca de Alexandria', x: 'Fundados sob os primeiros Ptolomeus (Ptolomeu I e II); a data exata é debatida.' },
    { d: 'c. 270 a.C.', t: 'Aristarco de Samos', x: 'Propõe que a Terra gira em torno do Sol; só conhecemos a ideia por Arquimedes.' },
    { d: 'c. 240 a.C.', t: 'Eratóstenes mede a Terra', x: 'Diretor da Biblioteca de Alexandria, calcula a circunferência da Terra a partir da sombra do Sol em Siene e em Alexandria.' },
    { d: '212 a.C.', t: 'Morte de Arquimedes', x: 'Morre em Siracusa durante o saque da cidade pelos romanos, segundo a tradição, às mãos de um soldado.' },
    { d: 'c. 150–120 a.C.', t: 'Hiparco', x: 'Astrónomo em Rodes e Alexandria: catálogo de estrelas, descoberta da precessão dos equinócios e bases da trigonometria.' },
    { d: 'c. 100 a.C.', t: 'O Mecanismo de Anticítera', x: 'Fabricado algures entre c. 200 e 87 a.C. (a maioria dos estudiosos aponta para o século II ou o início do I a.C.); o navio onde seguia naufragou perto de Anticítera por volta de 70–60 a.C.' },
    { d: 'c. 529 d.C.', t: 'O «fim» da filosofia em Atenas?', x: 'Segundo a tradição, o imperador Justiniano proibiu o ensino da filosofia em Atenas; os historiadores discutem o alcance e a data da medida.' }
  ] }
];

const mapa = [
  'O pensamento grego não tem uma capital: nasceu em dezenas de cidades, muitas na costa da atual Turquia e no sul de Itália. Esta secção mostra onde viveram e trabalharam os principais autores.',
  { tabela: { cab: ['Lugar', 'Hoje', 'Quem e o quê'], linhas: [
    ['Mileto', 'Turquia (costa jónica)', 'Tales, Anaximandro, Anaxímenes e Hecateu; berço da filosofia natural'],
    ['Éfeso', 'Turquia', 'Heráclito'],
    ['Samos', 'Ilha grega', 'Pitágoras e Aristarco; Epicuro nasceu ali, segundo a tradição'],
    ['Crotona', 'Calábria, Itália', 'Escola pitagórica'],
    ['Eleia (Vélia)', 'Campânia, Itália', 'Parménides e Zenão de Eleia'],
    ['Abdera', 'Norte da Grécia (Trácia)', 'Demócrito, Leucipo (tradição) e o sofista Protágoras'],
    ['Atenas', 'Grécia', 'Sócrates, Platão, Aristóteles, Epicuro, Zenão de Cício; teatro, tribunais e assembleia'],
    ['Estagira', 'Calcídica, Grécia', 'Cidade natal de Aristóteles'],
    ['Cós', 'Ilha grega', 'Hipócrates; santuário de Asclépio'],
    ['Cnido', 'Turquia', 'Escola médica rival de Cós; o astrónomo Eudoxo'],
    ['Halicarnasso', 'Bodrum, Turquia', 'Heródoto'],
    ['Lesbos', 'Ilha grega', 'Safo (Ereso ou Mitilene), Alceu, Teofrasto'],
    ['Tebas', 'Beócia, Grécia', 'Píndaro'],
    ['Ascra', 'Beócia, Grécia', 'Aldeia de Hesíodo, na encosta do Hélicon'],
    ['Siracusa', 'Sicília, Itália', 'Arquimedes; visitas de Platão (c. 388, 367 e 361 a.C.)'],
    ['Alexandria', 'Egito', 'Euclides, Eratóstenes, Herófilo, Erasístrato; Museu e Biblioteca'],
    ['Cirene', 'Líbia', 'Eratóstenes, Calímaco, Aristipo'],
    ['Rodes', 'Ilha grega', 'Hiparco (observações); escolas de retórica e filosofia'],
    ['Pérgamo', 'Turquia', 'Biblioteca rival da de Alexandria; mais tarde, cidade natal de Galeno'],
    ['Cício', 'Chipre', 'Zenão, fundador do estoicismo'],
    ['Sinope', 'Turquia (mar Negro)', 'Diógenes, o Cínico'],
    ['Delfos', 'Grécia', 'Santuário de Apolo; máximas «Conhece-te a ti mesmo» e «Nada em excesso»']
  ] } },
  { h: 'Mileto' },
  'Grande cidade comercial da Jónia, com quatro portos e colónias em todo o mar Negro, foi o primeiro centro da filosofia natural. **Tales** (c. 624 – c. 546 a.C.) propôs que tudo vem da água; **Anaximandro** e **Anaxímenes** seguiram-no com outras explicações. O seu pensamento não foi um acaso: Mileto ficava na rota de caravanas e navios, em contacto com o Egito, a Lídia e a Babilónia. A cidade foi destruída pelos persas em 494 a.C., depois da revolta jónica, mas foi reconstruída e as suas ruínas (teatro, ágora, termas) ainda se visitam.',
  { h: 'Atenas: Academia, Liceu, Jardim e Pórtico' },
  'Atenas teve **quatro escolas famosas**, todas fora ou à beira do centro da cidade, em ginásios e jardins. A **Academia**, a norte-oeste, a cerca de dois quilómetros da cidade, num recinto arborizado dedicado ao herói Academo: foi fundada por Platão c. 387 a.C. e funcionou, com interrupções, durante cerca de novecentos anos. O **Liceu**, a leste, junto de um santuário de Apolo Lício, foi a escola de Aristóteles. O **Jardim**, uma casa com horta, foi a escola de Epicuro. A **Estoa Pecile** («pórtico pintado»), na Ágora, deu o nome aos **estoicos**, cujo fundador, Zenão, ali ensinava. A **Ágora** e a **Pnyx** foram os lugares de debate de Sócrates, dos sofistas e dos oradores.',
  { img: 'gfc-academia-mosaico', leg: 'Mosaico de Pompeia, c. século I a.C. – I d.C., com um grupo de filósofos reunidos (tradicionalmente descrito como a «Academia de Platão»; a identificação é incerta). Museu Arqueológico Nacional de Nápoles.' },
  { img: 'gfc-liceu-peripatos', leg: 'Reconstrução imaginada de Aristóteles a conversar com discípulos no passeio coberto (*perípatos*) do Liceu, Atenas, c. 330 a.C. Ilustração gerada por IA; os pormenores do local são hipotéticos.' },
  'O Liceu e a Academia estavam longe do centro mas faziam parte da vida da cidade: usavam ginásios públicos, onde os jovens também treinavam o corpo. O nome «Academia» deu origem à palavra moderna, e o de «Liceu» a escolas secundárias em Portugal e em França. Em 1996, escavações feitas para a ampliação de um museu da cidade identificaram os restos do ginásio do Liceu, a leste da Acrópole.',
  { img: 'gfc-teatro-dioniso', leg: 'Estátua de Menandro no Teatro de Dioniso, Atenas. A maior parte do teatro visível hoje é dos séculos IV a.C. e romano; no tempo de Ésquilo e de Sófocles, as bancadas seriam de madeira.' },
  { h: 'Alexandria: o Museu e a Biblioteca' },
  'Fundada por Alexandre em 331 a.C. e capital dos Ptolomeus, Alexandria foi a cidade mais científica da Antiguidade. O **Museu** («casa das Musas») era uma instituição de pesquisa mantida pelo rei, onde sábios viviam com alojamento, refeições e salário, e a **Biblioteca** juntava rolos de todo o mundo grego, comprados, copiados e, segundo a tradição, confiscados dos navios que chegavam ao porto para serem copiados. Ali trabalharam Euclides, Eratóstenes, Aristarco de Samotrácia, Calímaco, Herófilo e Erasístrato. A localização exata dos edifícios não é conhecida: o bairro real está hoje sob o mar e sob a cidade moderna.',
  { img: 'gfc-museion-alexandria', leg: 'Reconstrução imaginada do Museu e da Biblioteca de Alexandria, séc. III a.C.; a aparência dos edifícios é hipotética. Ilustração gerada por IA.' },
  { h: 'Siracusa' },
  'Grande cidade grega da Sicília, governada por tiranos e reis (Hierão II, no tempo de **Arquimedes**). Foi aqui que Platão tentou educar o tirano Dionísio II, sem sucesso, e foi aqui que Arquimedes viveu e morreu. Os romanos tomaram a cidade em 212 a.C., depois de um cerco de cerca de dois anos, em que as máquinas de Arquimedes (segundo Políbio, Lívio e Plutarco) causaram grandes dificuldades aos atacantes.',
  { img: 'gfc-arquimedes-siracusa', leg: 'Cena imaginada de Arquimedes com uma máquina de defesa nas muralhas de Siracusa, 213 a.C.; as máquinas e a aparência da cidade são reconstruções hipotéticas. Ilustração gerada por IA.' },
  { h: 'Cós e Cnido' },
  'Duas ilhas e penínsulas do Egeu sul, ambas com santuários de **Asclépio**, o deus da medicina, e escolas médicas famosas. **Hipócrates** nasceu em Cós, onde ainda se vê o grande santuário (o Asclepieion), em terraços sobre o mar. Cnido competia com Cós; a sua escola ficou conhecida pelo detalhe da classificação das doenças.',
  { h: 'Lesbos, Tebas e Ascra' },
  'Em **Lesbos** nasceram a poeta **Safo** (de Ereso ou de Mitilene, a tradição não é unânime) e o poeta **Alceu**, e mais tarde **Teofrasto**, discípulo de Aristóteles. Em **Tebas** viveu **Píndaro**; ao seu lado, a Beócia deu o poeta **Hesíodo**, que escreve que o seu pai tinha emigrado da Cime eólica e se instalou numa aldeia «má no inverno, dura no verão, e nunca boa»: Ascra, à sombra do monte Hélicon, morada das Musas.',
  { h: 'As rotas do saber' },
  'O conhecimento grego circulava por **mar** e por **mestres itinerantes**: Platão viajou ao Egito (tradição), à Itália e à Sicília; os sofistas percorriam as cidades a dar aulas pagas; alunos de Atenas fundavam escolas nas suas terras. Depois de Alexandre, as rotas ligam o Mediterrâneo à Mesopotâmia: Hiparco usou observações astronómicas babilónicas, e a astronomia grega usou as unidades de 360 graus e os sistemas sexagesimais de origem babilónica. Os livros viajavam em rolos, em navios mercantes; Atenas era o mercado de livros, e Alexandria o maior centro de cópia.',
  { h: 'Os navegadores que mediram o mundo' },
  'Há também exploradores entre os sábios. **Píteas**, de Massália (Marselha), navegou no século IV a.C. pelo Atlântico Norte até uma terra a que chamou «Tule» e descreveu as marés e o sol da meia-noite; a obra perdeu-se, e só a conhecemos por citações críticas (Políbio, Estrabão). **Eratóstenes** desenhou um mapa do mundo conhecido, com paralelos e meridianos, a partir de relatos de viajantes.'
];

const sociedade = [
  { h: '1. Como se organizava o saber' },
  'Não havia universidades nem diplomas. O saber passava de **mestre a discípulo**, em escolas fundadas por um fundador, que depois designava um sucessor: Platão deixou a Academia a Espeusipo, Aristóteles passou o Liceu a Teofrasto. Os sofistas cobravam pelas lições, e por isso eram criticados por Sócrates e por Platão; sobre o financiamento das escolas filosóficas sabe-se pouco. Os testamentos de Aristóteles e de Epicuro, que Diógenes Laércio transcreve, mostram que ambos tinham bens próprios.',
  'A escola não era só uma sala de aulas: tinha ginásio, biblioteca, refeições em comum e um culto às Musas. A filosofia era também **uma forma de vida**, com exercícios de disciplina, de atenção e de debate, e não apenas um conjunto de teorias.',
  { h: '2. Os primeiros filósofos: Mileto, Éfeso e o Ocidente' },
  'Os pensadores anteriores a Sócrates (ou contemporâneos dele) chamam-se **pré-socráticos**, termo moderno. Perguntam o que há por detrás da variedade do mundo:',
  { lista: [
    '**Tales de Mileto** (c. 624 – c. 546 a.C.): a água como princípio. Segundo Heródoto, previu o eclipse de 585 a.C.; se o fez, foi por regras empíricas, e não por uma teoria completa.',
    '**Anaximandro** (c. 610 – c. 546 a.C.): o princípio é o *ápeiron*, o «ilimitado»; escreveu em prosa um tratado, e foi, segundo a tradição, o autor de um mapa do mundo e de um *gnómon* (relógio de sol).',
    '**Anaxímenes** (c. 586 – c. 526 a.C.): o ar, que se condensa e rarefaz para formar as coisas.',
    '**Heráclito de Éfeso** (c. 535 – c. 475 a.C.): o mundo está sempre em mudança («não se pode entrar duas vezes no mesmo rio» é uma versão resumida de um fragmento) e governado por um **logos**, uma razão comum. Era chamado «o Obscuro» pelo estilo enigmático.',
    '**Parménides de Eleia** (c. 515 – c. 450 a.C.): num poema, argumenta que o que existe é uno, imóvel e sem mudança, e que os sentidos enganam. Zenão de Eleia, seu discípulo, criou paradoxos (como o de Aquiles e a tartaruga) para defender a tese.',
    '**Empédocles de Agrigento** (c. 494 – c. 434 a.C.): quatro «raízes» (terra, ar, fogo, água), movidas por duas forças, o Amor e a Discórdia.',
    '**Anaxágoras de Clazómenas** (c. 500 – c. 428 a.C.): o primeiro filósofo a ensinar em Atenas, amigo de Péricles; afirmou que o Sol era uma massa incandescente, e foi acusado de impiedade.',
    '**Leucipo e Demócrito de Abdera** (Demócrito, c. 460 – c. 370 a.C.): a matéria é feita de **átomos** e vazio. A teoria era filosófica, sem experiências, mas anteviu uma ideia moderna.'
  ] },
  'A **escola pitagórica** merece uma menção à parte: Pitágoras e os seus discípulos terão tratado a **matemática** como a chave do mundo («tudo é número»), davam importância às proporções musicais e seguiam regras de vida comunitárias. Quase tudo o que se diz de Pitágoras em particular (a descoberta do teorema, a transmigração das almas, os interditos alimentares) vem de fontes tardias e é incerto.',
  { h: '3. Os sofistas e Sócrates' },
  'Em meados do século V a.C., Atenas atraiu professores itinerantes, os **sofistas** (de *sophia*, sabedoria), que ensinavam a retórica e a argumentação, úteis para vencer na assembleia e nos tribunais. **Protágoras** disse que «o homem é a medida de todas as coisas» (cada um julga a partir do seu ponto de vista); **Górgias** ensinou a arte de persuadir. O termo «sofista» ficou depreciativo por culpa de Platão, que os critica como vendedores de aparência, mas muitos eram pensadores sérios.',
  'Em contraste, **Sócrates** (c. 470 – 399 a.C.) não cobrava e não escrevia. Dedicava-se a **interrogar**: perguntava o que é a coragem, a justiça, a piedade, e mostrava que os interlocutores não sabiam responder. É o chamado **método socrático** (a *elenkhos*, a refutação). A frase «só sei que nada sei» é uma síntese tardia; na *Apologia*, Platão faz Sócrates dizer que é sábio apenas por reconhecer que não sabe.',
  { img: 'gfc-socrates-agora', leg: 'Cena imaginada de Sócrates a conversar com atenienses na Ágora, c. 420 a.C.; a arquitetura e o vestuário são reconstruções. Ilustração gerada por IA.' },
  'Em 399 a.C., depois da derrota de Atenas na guerra, da tirania dos Trinta e do regresso da democracia, Sócrates foi acusado por três cidadãos (Meleto, Ânito e Lícon) de **não honrar os deuses da cidade** e de **corromper os jovens**. Um tribunal de 501 jurados condenou-o por maioria; recusou fugir e bebeu a cicuta. Os historiadores discutem as razões políticas do processo (alguns discípulos, como Alcibíades e Crítias, tinham estado ligados a episódios antidemocráticos).',
  { img: 'gfc-morte-socrates-david', leg: '*A Morte de Sócrates*, de Jacques-Louis David, 1787. Museu Metropolitano de Arte, Nova Iorque. Pintura neoclássica: é uma interpretação da cena do *Fédon*, e não uma fonte antiga.' },
  { h: '4. Platão e a Academia' },
  'Platão (c. 428 – 348 a.C.) escreveu cerca de **trinta diálogos** que chegaram até nós, em que Sócrates e outras personagens discutem a justiça, o amor, a alma, o conhecimento e a política. Não fala em nome próprio. A doutrina mais conhecida é a **teoria das Formas**: a justiça, a beleza ou o bem existiriam como realidades perfeitas e inteligíveis, de que as coisas visíveis seriam imitações imperfeitas. A **alegoria da caverna** (livro VII da *República*) apresenta a ideia como uma história de prisioneiros que só veem sombras.',
  'Na **República**, Platão imagina uma cidade justa governada por filósofos, com três classes (governantes, guardiães, produtores), educação rigorosa e, para os guardiães, vida em comum. Nas *Leis*, escritas no fim da vida, propõe uma cidade mais realista, com leis detalhadas. A relação entre estas propostas e a prática política de Platão (as suas viagens a Siracusa) é debatida.',
  { img: 'gfc-simposio-platao', leg: 'Cena imaginada de um simpósio como o descrito no *Banquete* de Platão: convidados reclinados em *klinai* a discutir o amor. Os pormenores da sala são reconstruções hipotéticas. Ilustração gerada por IA.' },
  { h: '5. Aristóteles e o Liceu' },
  'Aristóteles (384 – 322 a.C.) foi um investigador de campo, mais do que um filósofo de gabinete. No Liceu, dirigiu estudos de **lógica** (inventou o silogismo e a primeira lógica formal), de **física** (movimento, causas), de **biologia** (descreveu cerca de quinhentas espécies de animais, segundo os estudiosos, e observou o desenvolvimento do embrião do pinto), de **ética** (a «virtude» como hábito e o justo meio), de **política** (analisou 158 constituições, segundo a tradição) e de **retórica e poética**.',
  'Ao contrário de Platão, Aristóteles recusava as Formas separadas: para ele, as coisas têm uma «forma» que existe nelas próprias. Muitos erros famosos na física antiga vêm dele (corpos mais pesados caem mais depressa; o Sol e os planetas giram à volta da Terra; as mulheres teriam menos dentes do que os homens, afirmação que fez e que nunca verificou), mas também uma enorme quantidade de observações exatas.',
  { img: 'gfc-papiro-constituicao-atenas', leg: 'Papiro com parte da *Constituição dos Atenienses*, obra atribuída a Aristóteles ou à sua escola, comprado no Egito em 1890 (edição de 1891). Biblioteca Britânica, Londres (Papiro 131). (Imagem ilustrativa gerada por IA.)' },
  { h: '6. As escolas helenísticas' },
  'Depois de Alexandre, as cidades gregas perderam peso político e a filosofia virou-se para a pergunta: **como viver bem num mundo incerto?** Surgiram quatro escolas principais:',
  { lista: [
    '**Cinismo:** **Diógenes de Sinope** (século IV a.C.) viveu com o mínimo e desprezava as convenções; as anedotas dizem que vivia num grande jarro (*pithos*) e que pediu a Alexandre que se afastasse porque lhe tapava o sol. As anedotas são tardias.',
    '**Epicurismo:** **Epicuro** (341 – 270 a.C.) defendia que o fim da vida é o **prazer** entendido como ausência de dor e de perturbação (*ataraxia*), com amizade, vida simples e sem medo dos deuses nem da morte. Seguia os atomistas na física.',
    '**Estoicismo:** **Zenão de Cício** (c. 334 – c. 262 a.C.) e **Crisipo** (c. 279 – c. 206 a.C.) ensinavam que o mundo é governado por uma razão universal, e que a vida boa é viver de acordo com a natureza, aceitando o que não depende de nós. O estoicismo influenciou Séneca, Epicteto e Marco Aurélio, já na época romana.',
    '**Ceticismo:** **Pirro de Élis** (c. 360 – c. 270 a.C.) e, mais tarde, **Sexto Empírico** defendiam suspender o juízo sobre o que não é evidente, para alcançar a tranquilidade.'
  ] },
  { img: 'gfc-diogenes-waterhouse', leg: '*Diógenes*, pintura de John William Waterhouse, 1882. Galeria de Arte de Nova Gales do Sul, Sydney. Interpretação do século XIX: Diógenes procura «um homem» com a lanterna.' },
  { h: '7. Matemática' },
  'A matemática grega parte de egípcios e babilónios, mas muda de natureza: já não se dão apenas receitas de cálculo, **demonstra-se**. Os **pitagóricos** descobriram a existência de grandezas **incomensuráveis** (como a diagonal do quadrado em relação ao lado), o que abalou a ideia de que tudo se exprime por números inteiros e razões; a lenda diz que o discípulo que o revelou foi afogado, mas a história não tem fundamento seguro.',
  '**Euclides** (c. 300 a.C.), em Alexandria, escreveu os **Elementos**, em treze livros: geometria plana e sólida, teoria dos números (incluindo a prova de que os números primos são infinitos) e a teoria das proporções. A obra parte de definições, de «noções comuns» e de cinco **postulados**, e deduz as proposições em cadeia. O quinto postulado, o das paralelas, foi discutido durante séculos e levou, no século XIX, às geometrias não-euclidianas. Pouco se sabe da vida de Euclides.',
  { img: 'gfc-euclides-bodleian', leg: 'Página de um manuscrito bizantino dos *Elementos* de Euclides, copiado em 888 d.C. Biblioteca Bodleiana, Oxford (MS D’Orville 301). É o manuscrito grego mais antigo conservado que contém os *Elementos* quase completos (há fragmentos de papiro mais antigos).' },
  '**Apolónio de Perga** (c. 240 – c. 190 a.C.) estudou as **cónicas** (elipse, parábola, hipérbole), cujos nomes são seus. **Arquimedes** (c. 287 – 212 a.C.) calculou a área do círculo e do segmento de parábola, o volume da esfera, aproximações do valor de π, e fundou a **estática** e a **hidrostática**: o princípio que leva o seu nome diz que um corpo mergulhado num fluido sofre um impulso igual ao peso do fluido deslocado.',
  { img: 'gfc-palimpsesto-arquimedes', leg: 'Folha do Palimpsesto de Arquimedes (Walters Art Museum, Baltimore), com uma miniatura do martírio de São Zótico; o texto de Arquimedes, do século X, está por baixo da escrita do livro de orações.' },
  'O **palimpsesto** foi descoberto em Constantinopla por Johan Heiberg, em 1906, e hoje estuda-se com imagens multiespectrais. Contém o *Método*, em que Arquimedes expõe o raciocínio mecânico que o conduzia aos resultados, antes de os demonstrar de modo formal.',
  { h: '8. Astronomia e geografia' },
  'Os gregos observaram e mediram o céu, e criaram **modelos geométricos** para explicar os movimentos dos planetas. Já no século IV a.C., Aristóteles apresentou provas de que a **Terra é esférica**: a sombra redonda na Lua durante os eclipses e o facto de se verem estrelas diferentes ao viajar para norte ou sul. **Eudoxo de Cnido** propôs esferas concêntricas para explicar os planetas.',
  { lista: [
    '**Aristarco de Samos** (c. 310 – c. 230 a.C.) sugeriu que a Terra gira em torno do Sol e sobre si própria. A ideia quase não teve seguidores; só a conhecemos por uma frase de Arquimedes (*O Contador de Areia*). A sua única obra que sobrevive é *Sobre os Tamanhos e as Distâncias do Sol e da Lua*, em que tenta calcular essas distâncias.',
    '**Eratóstenes de Cirene** (c. 276 – c. 194 a.C.): comparou a sombra de uma vara em Alexandria com a ausência de sombra, ao meio-dia do solstício, num poço em Siene (Assuão), e deduziu a circunferência da Terra em cerca de 252 000 estádios. Como o comprimento exato do estádio é incerto, não sabemos qual foi o erro: pode ter sido de poucos por cento ou de mais de dez por cento.',
    '**Hiparco de Niceia** (c. 190 – c. 120 a.C.): fez o primeiro catálogo de estrelas conhecido, descobriu a **precessão dos equinócios** e criou tabelas que são a base da trigonometria.',
    '**Ptolomeu** (século II d.C.), de língua grega, já sob o domínio romano, fixou no *Almagesto* o modelo com a Terra no centro, que dominou até Copérnico.'
  ] },
  { img: 'gfc-aristarco-manuscrito', leg: 'Diagrama de um manuscrito grego do século X (Vaticano, Gr. 204) da obra de Aristarco de Samos sobre os tamanhos e as distâncias do Sol e da Lua. Biblioteca Apostólica Vaticana. (Imagem ilustrativa gerada por IA.)' },
  { img: 'gfc-eratostenes-esquema', leg: 'Esquema didático do método de Eratóstenes: o ângulo da sombra em Alexandria, comparado com a ausência de sombra em Siene, dá a fração da circunferência da Terra. Esquema gerado por IA; as proporções são simplificadas.' },
  { h: '9. Tecnologia e máquinas' },
  'A ciência grega não foi só teoria. **Ctesíbio** (século III a.C., Alexandria) fez bombas de água e relógios de água; **Arquimedes** concebeu o parafuso de água, a roldana composta e máquinas de guerra; **Hero de Alexandria** (século I d.C.) descreveu autómatos e uma máquina de vapor de brinquedo, a eolípila. Mas raramente foi aplicada à produção: uma explicação frequente (e discutida) é que o trabalho escravo e a mão de obra barata tiravam interesse económico a poupar esforço.',
  { img: 'gfc-antikythera', leg: 'Fragmento principal do Mecanismo de Anticítera, bronze, c. século II – I a.C. Museu Arqueológico Nacional, Atenas.' },
  'O **Mecanismo de Anticítera** foi recuperado em 1901 de um naufrágio (c. 70–60 a.C.), perto da ilha de Anticítera, entre Creta e o Peloponeso. É um aparelho com dezenas de engrenagens de bronze que, ao rodar uma manivela, mostrava a posição do Sol e da Lua, as fases lunares, o calendário e os eclipses. Os investigadores debatem a data exata de fabrico e a sua origem (Rodes, Siracusa, Pérgamo ou outra), mas ninguém duvida de que revela um nível de engenharia que se julgava só existir mil anos mais tarde.',
  { h: '10. Medicina' },
  'A medicina grega nasceu da observação e do debate. **Hipócrates de Cós** (c. 460 – c. 370 a.C.) foi o médico mais famoso do seu tempo, mas não sabemos quais dos cerca de sessenta tratados do **Corpus Hipocrático** são dele. Esses textos defendem que as doenças têm causas naturais (a «doença sagrada», a epilepsia, não vem dos deuses), e valorizam a observação do doente, a dieta, o clima e o prognóstico. A teoria dos quatro **humores** (sangue, fleuma, bílis amarela e bílis negra) dominou a medicina ocidental durante cerca de dois mil anos.',
  { img: 'gfc-hipocrates-cabeceira', leg: 'Cena imaginada de um médico grego à cabeceira de um doente, c. século V a.C.; a decoração e os instrumentos são reconstruções hipotéticas. Ilustração gerada por IA.' },
  'Em Alexandria, **Herófilo da Calcedónia** e **Erasístrato de Ceos** (século III a.C.) fizeram dissecações de cadáveres e, segundo alguns autores antigos, de condenados vivos (relato disputado): distinguiram os nervos e estudaram o cérebro, o coração e as válvulas. **Galeno de Pérgamo** (129 – c. 216 d.C.), médico de gladiadores e de imperadores romanos, sistematizou a medicina grega e, escrevendo em grego, fixou-a para a medicina bizantina, islâmica e europeia, até ao século XVII. O **juramento hipocrático** tem data e autoria debatidas: não se sabe se foi escrito por Hipócrates, e o texto foi muito adaptado ao longo dos séculos.',
  { h: '11. Ciências da natureza' },
  'Aristóteles e o seu discípulo **Teofrasto** (c. 371 – c. 287 a.C.), de Lesbos, fundaram as ciências naturais descritivas. Teofrasto escreveu a *História das Plantas* e *Sobre as Causas das Plantas*, os primeiros tratados de botânica que conhecemos, com descrições de centenas de espécies e de técnicas de cultivo; também escreveu os *Caracteres*, pequenos retratos satíricos de tipos humanos, que fazem parte da literatura. Aristóteles escreveu ainda a *História dos Animais* e *Sobre as Partes dos Animais*, e deixou observações de peixes, cefalópodes e abelhas, em parte confirmadas séculos depois (embora também tenha errado em muitos pontos).',
  { h: '12. Homero e a epopeia' },
  'A *Ilíada* e a *Odisseia* são dois poemas épicos em hexâmetros, atribuídos a **Homero**, uma figura da qual nada de seguro se sabe: cegueira, origem (Quios, Esmirna e outras cidades disputavam-no) e até existência são tradição. A *Ilíada* conta uns dias do décimo ano da guerra de Troia, centrados na **cólera de Aquiles**; a *Odisseia* conta o regresso de Ulisses a Ítaca, ao fim de dez anos de viagens. Foram fixados por escrito, provavelmente, no século VIII ou VII a.C., a partir de uma longa tradição oral.',
  'A **Questão Homérica** (um ou vários autores? como foram compostos?) foi renovada no século XX por **Milman Parry** e Albert Lord, que mostraram que os epítetos fixos («Aquiles de pés velozes», «Atena de olhos de coruja») e as cenas típicas são técnicas de improvisação de poetas orais, que recitavam sem ler. Os poemas foram depois recitados por **rapsodos** nas grandes festas, e Atenas fixou um texto oficial para as Grandes Panateneias, segundo a tradição por ordem de Pisístrato ou de seu filho Hiparco.',
  { img: 'gfc-recital-homerico', leg: 'Cena imaginada de um rapsodo a recitar a *Ilíada* numa festa, com o público sentado à volta, c. século V a.C.; o ambiente é reconstruído. Ilustração gerada por IA.' },
  { img: 'gfc-venetus-a', leg: 'Folha do *Venetus A*, manuscrito bizantino do século X da *Ilíada*, com comentários (escólios) dos sábios de Alexandria nas margens. Biblioteca Marciana, Veneza.' },
  'Em Alexandria, **Zenódoto de Éfeso**, **Aristófanes de Bizâncio** e **Aristarco de Samotrácia** (que não se deve confundir com o astrónomo de Samos) editaram os poemas e criaram o texto que, em essência, nos chegou: a divisão de cada poema em 24 cantos é atribuída aos sábios alexandrinos. O *Venetus A* ainda guarda os sinais críticos e os comentários desses sábios.',
  { h: '13. Hesíodo' },
  'Hesíodo viveu c. 700 a.C. na Beócia, e é a primeira figura literária grega de que se pode dizer algo de individual: fala de si e do pai, e do irmão Perses, com quem litigou por uma herança. A *Teogonia* conta a **origem dos deuses**, do Caos a Zeus, e é a base de muitos mitos gregos; os *Trabalhos e Dias* é um poema didático sobre a lavoura, a justiça e o trabalho honesto, com o mito de **Pandora** e o das **cinco idades** (ouro, prata, bronze, heróis, ferro).',
  { img: 'gfc-hesiodo-mosaico', leg: 'Mosaico romano de Tréveris (Alemanha), final do século III d.C., obra de Monnus, com Hesíodo e uma figura feminina associada às Musas. Rheinisches Landesmuseum, Tréveris. É uma imagem romana tardia: não há retrato contemporâneo de Hesíodo.' },
  { h: '14. A poesia lírica' },
  'A poesia **lírica** (cantada com a lira ou a flauta) é, ao contrário da épica, pessoal e curta: fala de amor, guerra, vinho, política e morte. Poetas principais:',
  { lista: [
    '**Arquíloco de Paros** (século VII a.C.): soldado e poeta, escreve na primeira pessoa e conta que largou o escudo na fuga, sem vergonha. Muito citado pela sua ironia.',
    '**Safo de Lesbos** (c. 630 – c. 570 a.C.): poemas de amor e de saudade, cantados num círculo de jovens mulheres em Lesbos. Dos oito ou nove livros que existiam na Antiguidade só se conserva um poema completo (o *Hino a Afrodite*) e fragmentos. Em 2014 foram publicados novos fragmentos em papiro, entre eles um poema sobre os irmãos.',
    '**Alceu de Mitilene** (c. 620 – c. 580 a.C.): poeta político e exilado, contemporâneo de Safo; deu o nome à estrofe alcaica, usada depois por Horácio.',
    '**Simónides de Ceos** (c. 556 – c. 468 a.C.): compôs o epigrama dos mortos das Termópilas e foi poeta de odes de vitória; teria sido o primeiro a cobrar pelos poemas.',
    '**Píndaro de Tebas** (c. 518 – c. 438 a.C.): odes triunfais para os vencedores dos jogos de Olímpia, Delfos, Nemeia e do Istmo, em linguagem solene e de grande riqueza.'
  ] },
  { img: 'gfc-safo-lesbos', leg: 'Cena imaginada de Safo a cantar com a lira a um grupo de jovens em Lesbos, c. 600 a.C.; o vestuário e o cenário são reconstruções hipotéticas. Ilustração gerada por IA.' },
  { h: '15. Heródoto, o «pai da história»' },
  'Heródoto (c. 484 – c. 425 a.C.), de Halicarnasso, viajou pelo Egito, pela Babilónia (discute-se se chegou lá), pela Cítia e pelas cidades gregas. As suas *Histórias* explicam as causas das **Guerras Médicas**, e fazem-no através de digressões enormes sobre os povos que os persas encontraram: egípcios, lídios, citas, babilónios. A palavra *historiē* significa «investigação», e foi ele quem a fixou como título. Combina testemunhos, tradições locais e lendas, e diz mais de uma vez que a sua obrigação é registar o que lhe contam, mas não acreditar em tudo (por exemplo, 7.152).',
  'Cícero chamou-lhe «pai da história» (*De legibus*); Plutarco acusou-o, num escrito polémico, de «malícia» e de parcialidade. A verdade está no meio: muitas das suas informações foram confirmadas por arqueologia (a rota do Grande Rei, os estaleiros, factos da vida egípcia), e outras claramente não (as formigas gigantes que escavam ouro). A divisão da obra em nove livros, com nomes de Musas, é atribuída aos editores alexandrinos.',
  { h: '16. Tucídides e a história política' },
  'Tucídides (c. 460 – c. 400 a.C.), ateniense, foi estratego em 424 a.C. e foi exilado depois de falhar a defesa de Anfípolis. Passou vinte anos fora de Atenas e usou o tempo para recolher testemunhos dos dois lados da **Guerra do Peloponeso**. Escreve para ser «uma aquisição para sempre», e não um espetáculo para ouvir: rejeita explicações divinas, e procura causas humanas (o medo, o interesse, a ambição). É célebre pela análise do **poder** nas relações entre Estados (o *Diálogo dos Melianos*), pelo **discurso fúnebre de Péricles** e pela descrição da **peste de Atenas**, onde ele próprio adoeceu.',
  'Os **discursos** da sua obra não são transcrições: o próprio autor diz que escreveu o que «cada orador devia ter dito», tentando manter o sentido geral do que ficou dito. A obra está inacabada, e termina em 411 a.C.',
  { h: '17. Xenofonte e os historiadores seguintes' },
  '**Xenofonte** (c. 430 – c. 354 a.C.) foi discípulo de Sócrates, mercenário e escritor. Na *Anábase* conta a marcha dos dez mil gregos que foram contratados pelo príncipe persa Ciro e voltaram a pé do coração da Pérsia até ao mar Negro; nas *Helénicas* continuou a obra de Tucídides até 362 a.C.; escreveu também as *Memoráveis* sobre Sócrates, a *Ciropedia* (romance educativo sobre Ciro) e o *Económico*, sobre a gestão da casa. **Políbio** (c. 200 – c. 118 a.C.), grego exilado em Roma, escreveu como o poder de Roma conquistou o Mediterrâneo em cinquenta e três anos, e analisou a constituição romana; é a principal fonte para as Guerras Púnicas.',
  { h: '18. A oratória' },
  'Na democracia ateniense, falar bem era poder. Os **oradores** escreviam discursos para o tribunal ou para a assembleia: **Lísias** (discursos para clientes, com retratos vivos da vida privada), **Isócrates** (fundou uma escola de retórica), **Demóstenes** (384 – 322 a.C.), célebre pelas *Filípicas* contra Filipe II da Macedónia, e **Ésquines**, seu rival.',
  { h: '19. O teatro: origem e concursos' },
  'O teatro grego nasceu no culto de **Dioniso**, e a tragédia terá começado com um **coro** que cantava e dançava o ditirambo. A tradição liga a primeira representação a **Tespis**, c. 534 a.C. Em Atenas, as tragédias e comédias representavam-se nas **Grandes Dionísias** (março) e nas Leneias (janeiro), em concursos a que cada poeta apresentava três tragédias e um drama satírico (trilogia e peça burlesca). O Estado escolhia os poetas, e um cidadão rico, o **corego**, pagava o coro; um júri decidia o vencedor.',
  'Os atores eram **homens**, usavam máscaras e vários papéis; o coro de 12 ou 15 cantava e dançava na **orquestra**, o espaço circular em baixo. A plateia assistia durante o dia, em bancadas na encosta. Eram representações religiosas, políticas e comunitárias, e não entretenimento privado.',
  { img: 'gfc-mascaras-mosaico', leg: 'Mosaico romano com duas máscaras teatrais, uma trágica e outra cómica, séc. II d.C., Vila de Adriano em Tivoli. Museus Capitolinos, Roma. As máscaras gregas originais eram de linho e madeira, e perderam-se. (Imagem ilustrativa gerada por IA.)' },
  { h: '20. Ésquilo' },
  'Ésquilo (c. 525 – 456 a.C.), nascido em Elêusis, lutou em Maratona (a sua lápide fala só disso, e não das tragédias, segundo a tradição). Escreveu cerca de setenta ou oitenta peças, e sobrevivem **sete**: os *Persas* (472 a.C., a tragédia grega mais antiga que conservamos e uma das raras peças de tema histórico), *Os Sete contra Tebas*, *As Suplicantes*, *Prometeu Agrilhoado* (a autoria é debatida) e a trilogia da *Oresteia* (458 a.C.: *Agamémnon*, *Coéforas*, *Euménides*). Introduziu o segundo ator, o que permitiu o diálogo.',
  { img: 'gfc-esquilo-busto', leg: 'Ésquilo numa gravura antiga. O retrato é idealizado: não há imagem contemporânea do poeta.' },
  { h: '21. Sófocles' },
  'Sófocles (c. 496 – 406 a.C.) escreveu cerca de 120 peças (número da tradição antiga); sobrevivem **sete**: *Ájax*, *Antígona*, *Édipo Rei*, *Electra*, *As Traquínias*, *Filoctetes* e *Édipo em Colono*. Venceu muitos concursos (as fontes antigas dão números de 18 a 24), foi também político e estratego. Introduziu o terceiro ator, e fez do herói trágico alguém que enfrenta o destino com a sua liberdade. *Édipo Rei*, onde o rei de Tebas procura o assassino do seu antecessor e descobre que é ele próprio, é o exemplo a que Aristóteles mais recorre na *Poética*.',
  { img: 'gfc-edipo-esfinge-vaso', leg: 'Édipo e a Esfinge, taça ática de figuras vermelhas, c. 470 a.C., atribuída ao Pintor de Édipo. Museus do Vaticano.' },
  { h: '22. Eurípides' },
  'Eurípides (c. 480 – 406 a.C.) foi o mais jovem dos três grandes, e o mais inquietante. As suas personagens são mais psicológicas, as mulheres têm papéis centrais e os deuses surgem muitas vezes em crítica: *Medeia* (431 a.C.), *Hipólito*, *As Troianas* (415 a.C., composta depois do massacre de Melos), *Helena*, *Ifigénia em Áulide* e *As Bacantes* (representada depois da sua morte, c. 405 a.C.). Sobrevivem dezoito ou dezanove peças (a autoria de *Reso* é duvidosa). Morreu na corte do rei da Macedónia, Arquelau.',
  { h: '23. Aristófanes e a comédia' },
  'A **comédia antiga** é política, obscena, fantástica e satírica, com um coro de animais ou de figuras estranhas e ataques diretos a políticos vivos. **Aristófanes** (c. 446 – c. 386 a.C.) escreveu cerca de quarenta peças, e sobrevivem **onze**: *Os Acarnenses*, *Os Cavaleiros*, *As Nuvens* (423 a.C., onde Sócrates é pendurado num cesto, a ensinar a enganar os credores), *As Vespas*, *A Paz*, *As Aves*, *Lisístrata* (411 a.C.), *As Mulheres que Celebram as Tesmofórias*, *As Rãs* (405 a.C.), *As Mulheres na Assembleia* e *Pluto*. Em *As Rãs*, Dioniso desce ao Hades para trazer de volta um poeta trágico e, depois de um concurso, escolhe Ésquilo em vez de Eurípides.',
  { img: 'gfc-aristofanes-comedia', leg: 'Cena imaginada de uma comédia antiga em Atenas: atores mascarados com trajes exagerados, um coro a dançar na orquestra e o público na encosta, séc. V a.C. Os trajes são reconstruções. Ilustração gerada por IA.' },
  'Já no fim do século IV a.C., com **Menandro** (c. 342 – c. 290 a.C.), nasceu a **comédia nova**, que trata da vida doméstica: amores contrariados, pais severos, escravos espertos. Dessa comédia quase nada chegava até nós, até à publicação, em 1958, de um papiro com o *Díscolo* («O Misantropo»), quase completo.',
  { h: '24. Aristóteles e a *Poética*' },
  'Na *Poética*, Aristóteles analisa a tragédia como **imitação** (*mimesis*) de uma ação séria, que provoca **piedade e medo**, e cuja finalidade é a **catarse** (um termo de interpretação muito discutida: purificação, purgação ou clarificação). Fala do enredo (*mythos*), dos caracteres, da linguagem e do espetáculo, e da «falha trágica» (*hamartia*). Boa parte do tratado, que tratava da comédia, perdeu-se.',
  { h: '25. Livros: papiro, rolos e leitura' },
  'Os livros antigos eram **rolos de papiro** (*bíblia*, do porto de Biblos, de onde o papiro seria exportado), em colunas de texto, geralmente escritos de um só lado. Cada rolo comportava um «livro» de uma obra longa, o que explica a divisão em livros da *Ilíada* ou das *Histórias*. Não havia espaços entre as palavras nem pontuação sistemática, e a leitura era muitas vezes em **voz alta**. O papiro era produzido no Egito; para escrever em bom material, os reis de Pérgamo teriam recorrido ao pergaminho (de *pergamenon*), quando, segundo a tradição, os Ptolomeus proibiram a exportação de papiro.',
  { img: 'gfc-papiro-derveni', leg: 'Papiro de Derveni, c. 340–320 a.C., encontrado em 1962 numa pira funerária, perto de Salónica, na Macedónia. Parcialmente carbonizado, é um dos mais antigos manuscritos europeus conservados e traz um comentário a um poema órfico. Museu Arqueológico de Salónica.' },
  { h: '26. A Biblioteca de Alexandria e o mito do seu fim' },
  'A **Biblioteca** foi criada pelos primeiros Ptolomeus, no início do século III a.C., com a ambição de reunir **todos os livros do mundo**. Chegou a ter, segundo estimativas antigas e discutidas, entre algumas dezenas e algumas centenas de milhar de rolos (o número é incerto). **Calímaco** compôs um catálogo, os *Pínaces*, em 120 livros, em que os autores se organizavam por género. Os bibliotecários chefes incluíram Zenódoto, Eratóstenes, Aristófanes de Bizâncio e Aristarco de Samotrácia.',
  'A ideia de que a Biblioteca foi destruída de uma só vez é um **mito**. O que sabemos: um incêndio provocado por Júlio César em 48 a.C. destruiu uma parte (armazéns de livros junto ao porto, segundo alguns autores); depois houve decadência por falta de dinheiro, perseguição de sábios por Ptolomeu VIII e, mais tarde, guerras e crises na cidade. O Serapeu, que tinha uma biblioteca-filha, foi destruído em 391 d.C. por uma multidão cristã. A história da queima do Califa Omar, em 642, é uma lenda tardia.',
  { h: '27. Mulheres na filosofia e na literatura' },
  'Havia **poucas**, e as fontes são curtas: as mulheres atenienses não frequentavam as escolas, e a educação era sobretudo masculina. Mas há exceções: **Safo** e as suas discípulas em Lesbos; **Corina** (de Tanagra, Beócia), poeta que, segundo a tradição, venceu Píndaro num concurso; **Aspásia** de Mileto, companheira de Péricles, de quem Platão e Plutarco falam como mulher culta; **Diotima**, a sacerdotisa que ensina Sócrates sobre o amor no *Banquete*, que é possivelmente uma personagem inventada; **Hiparquia de Maroneia** (c. 350 – c. 280 a.C.), filósofa cínica que viveu como o marido, Crates, e foi muito comentada. Escolas como o Jardim de Epicuro aceitavam mulheres, e a escola pitagórica teve discípulas, como Teano (as obras atribuídas a «Teano» são pseudoepigráficas). Mais tarde, em Alexandria, **Hipátia** (c. 360 – 415 d.C.; o ano de nascimento é debatido) ensinou matemática e filosofia, e foi assassinada por uma multidão.',
  { h: '28. O que os gregos aprenderam dos outros' },
  'Os gregos nunca esconderam o que deviam ao Oriente. Heródoto diz que a geometria nasceu no Egito, por causa das cheias do Nilo, que apagavam os limites dos campos; os astrónomos gregos usaram observações babilónicas de eclipses e o sistema sexagesimal (360 graus, 60 minutos); a medicina grega aprendeu com a egípcia; o alfabeto veio dos fenícios. Mas fizeram com esses materiais outra coisa: quiseram **provar** e **explicar**, e organizaram o saber em tratados que se podiam ensinar, copiar e criticar.',
  { h: '29. Filosofia e política' },
  'Os filósofos não estavam acima da política. Platão foi três vezes a Siracusa, e as suas esperanças fracassaram; Aristóteles foi tutor de Alexandre, e teve de fugir de Atenas em 323 a.C.; Anaxágoras foi acusado de impiedade; **Sócrates** foi condenado. Epicuro aconselhava a retirada da vida pública («vive escondido»); os estoicos, pelo contrário, defendiam o dever cívico, e influenciaram o direito romano. O processo de impiedade era uma arma política: servia para atingir os amigos de Péricles ou de um partido.',
  { h: '30. Palavras que viajaram' },
  'Boa parte do vocabulário intelectual do português vem do grego, diretamente ou através do latim: **filosofia** (amor da sabedoria), **ética** (de *ethos*, costume), **lógica** (de *logos*, razão), **física** e **metafísica** (o que vem «depois da *Física*» na edição das obras de Aristóteles), **teoria** (contemplação), **método** (caminho), **história** (investigação), **drama** (ação), **tragédia**, **comédia**, **ritmo**, **harmonia**, **geometria** (medida da terra), **átomo** («indivisível»), **ecologia** (estudo da casa, termo moderno com raiz grega), **academia** e **liceu**.',
  { h: '31. O que se perdeu' },
  'Os números ajudam a ver a escala da perda:',
  { tabela: { cab: ['Autor', 'Obra estimada', 'Obra conservada'], linhas: [
    ['Ésquilo', 'c. 70–90 peças', '7 tragédias'],
    ['Sófocles', 'c. 120 peças', '7 tragédias'],
    ['Eurípides', 'c. 90 peças', '18 ou 19 tragédias'],
    ['Aristófanes', 'c. 40 comédias', '11 comédias'],
    ['Menandro', 'c. 100 comédias', '1 quase completa (*Díscolo*) e partes de outras'],
    ['Safo', '8 ou 9 livros (Antiguidade)', '1 poema completo e fragmentos'],
    ['Crisipo', 'c. 700 obras (tradição)', 'só fragmentos e citações'],
    ['Aristóteles', 'c. 150–190 títulos (listas antigas)', 'c. 30 obras, sobretudo notas de aulas'],
    ['Arquimedes', 'vários tratados', '9 ou 10 tratados, uns de modo parcial']
  ] } },
  'Os números são **estimativas** baseadas em listas antigas, e alguns são discutidos. A seleção das obras que sobreviveram foi decidida por escolas, bibliotecas e copistas: os textos mais usados no ensino tendiam a ser copiados mais vezes, e por isso tinham maior hipótese de chegar até nós.',
  { h: '32. Um dia de um aluno de filosofia' },
  'Não há um «horário» documentado; o que se segue é uma reconstrução geral, a partir de várias fontes. Um jovem a estudar em Atenas, no século IV a.C., treinava no ginásio, assistia às lições e conversas do mestre (por vezes passeando) e discutia com os colegas; as refeições em comum podiam incluir um tema de debate, como no *Banquete* de Platão. O estudo incluía matemática, astronomia, dialética e, na Academia, geometria («Que ninguém entre aqui sem saber geometria», frase atribuída à porta da Academia, só em fontes tardias). Os livros eram caros e raros: aprendia-se sobretudo ouvindo e tomando notas.',
  { h: '33. Mitos e erros comuns' },
  { lista: [
    '**«Os gregos achavam que a Terra era plana»:** falso para os sábios; Aristóteles dá argumentos para a esfericidade e Eratóstenes mediu-a. A ideia de que os medievais acreditavam numa Terra plana é, em grande parte, um mito moderno.',
    '**«Eureka!» na banheira:** conta-o Vitrúvio, dois séculos depois, a propósito da coroa do rei Hierão; os textos de Arquimedes não mencionam a história.',
    '**Os espelhos ardentes de Arquimedes:** lendas que só aparecem séculos depois; as experiências modernas mostram que seria muito difícil incendiar um navio assim.',
    '**Sócrates e a frase «só sei que nada sei»:** é uma síntese de uma passagem da *Apologia* de Platão, não uma frase do filósofo.',
    '**O teorema de Pitágoras:** já era conhecido na Babilónia e noutras culturas; a atribuição da demonstração a Pitágoras é tardia e incerta.',
    '**A Biblioteca de Alexandria queimou de uma vez:** não, foi um declínio longo (ver acima).',
    '**Aristóteles «travou» a ciência:** a sua autoridade foi enorme, mas a ciência moderna começou também a partir de debate com ele, e não só contra ele.',
    '**Os gregos eram «racionalistas» sem religião:** não, os pensadores gregos viviam numa sociedade profundamente religiosa e muitos, como Platão e os estoicos, davam à divindade um lugar central.'
  ] }
];

const personalidades = [
  { h: 'Tales de Mileto (c. 624 – c. 546 a.C.)' },
  'Segundo a tradição, mercador, político e pensador de Mileto, é considerado o primeiro filósofo da tradição ocidental. Segundo Aristóteles, defendia que a **água** era o princípio de todas as coisas e que a Terra flutuava na água. A tradição atribui-lhe a previsão do eclipse de 585 a.C., a medição da altura das pirâmides pela sombra e vários teoremas de geometria, mas não escreveu nada que conheçamos. Era incluído entre os «Sete Sábios».',
  { h: 'Pitágoras de Samos (c. 570 – c. 495 a.C.)' },
  'Natural de Samos, emigrou para Crotona, no sul de Itália, onde fundou uma comunidade de discípulos que partilhava bens, seguia regras (como o vegetarianismo, segundo algumas fontes) e estudava os números. Defendeu a **transmigração das almas** e a importância da proporção na música. Nada do que se escreveu como seu é autêntico, e quase todas as informações sobre ele vêm de séculos depois. O teorema que tem o seu nome já era conhecido na Babilónia.',
  { h: 'Heráclito de Éfeso (c. 535 – c. 475 a.C.)' },
  'Aristocrata de Éfeso, escreveu um livro em prosa de que só restam cerca de cem fragmentos. Falava da **mudança constante** («tudo flui» é uma síntese posterior) e da unidade dos opostos, e usava um estilo de aforismos enigmáticos, que lhe deu o apelido de «o Obscuro». Defendia que o mundo é governado por um *logos*, uma razão comum que a maioria dos homens não entende.',
  { h: 'Sócrates (c. 470 – 399 a.C.)' },
  'Filho de um escultor e de uma parteira, serviu como hoplita na Guerra do Peloponeso e dedicou a vida a interrogar os atenienses sobre a virtude. Não escreveu: conhecemo-lo por Platão, Xenofonte e Aristófanes, que o retratam de formas muito diferentes (o problema do «Sócrates histórico»). Na *Apologia*, Platão faz dizer que o seu «daimon» (voz interior) o impedia de fazer o que era errado. Foi condenado à morte em 399 a.C. e bebeu a cicuta, rodeado de discípulos.',
  { h: 'Platão (c. 428 – 348 a.C.)' },
  'Aristocrata ateniense, parente de Crítias, um dos Trinta, desistiu da política depois da morte de Sócrates. Viajou, fundou a **Academia** em c. 387 a.C. e escreveu diálogos de uma enorme variedade, desde o *Êutifron*, a *Apologia* e o *Críton*, curtos e socráticos, até à *República*, o *Fédon*, o *Banquete*, o *Teeteto*, o *Timeu* e as *Leis*. Foi o filósofo cujo pensamento teve mais influência na teologia cristã e no Renascimento. O filósofo Alfred North Whitehead escreveu que a tradição filosófica europeia é, em boa medida, «uma série de notas de rodapé a Platão».',
  { img: 'gfc-platao-busto', leg: 'Busto de Platão, cópia romana de um retrato grego do século IV a.C., geralmente atribuído a Silanion. Existem várias cópias, por exemplo na Gliptoteca de Munique.' },
  { h: 'Aristóteles (384 – 322 a.C.)' },
  'Nascido em Estagira, filho de um médico do rei da Macedónia, ficou vinte anos na Academia de Platão, foi preceptor de Alexandre (c. 343–340 a.C.) e fundou o **Liceu**. Os seus escritos, que chegaram em forma de **notas de aula** (os «tratados esotéricos»), cobrem lógica, física, biologia, metafísica, ética e política. Em 323 a.C., com a morte de Alexandre, os sentimentos antimacedónicos em Atenas fizeram-no partir para Cálcis, onde morreu. Em Bizâncio, no mundo islâmico e na Europa latina, foi «o Filósofo» por excelência.',
  { img: 'gfc-aristoteles-busto', leg: 'Busto de Aristóteles, cópia romana de um retrato grego de c. 330 a.C. Palácio Altemps, Roma (Museu Nacional Romano).' },
  { h: 'Epicuro (341 – 270 a.C.)' },
  'Nascido em Samos, de pai ateniense, fundou o **Jardim** em Atenas c. 306 a.C. Escreveu muito (trezentos rolos, segundo Diógenes Laércio), mas só nos chegaram três cartas e algumas máximas. Defendia uma vida simples, com amigos, sem medo dos deuses (que existiriam, mas não se ocupariam dos homens) e sem medo da morte («quando existimos, a morte não existe; quando ela existe, nós não existimos»). A sua doutrina foi acompanhada em Roma por **Lucrécio**, que a pôs em verso no poema *De rerum natura*.',
  { img: 'gfc-epicuro-busto', leg: 'Busto de Epicuro, cópia romana de um retrato grego do século III a.C. Museus Capitolinos, Roma. (Imagem ilustrativa gerada por IA.)' },
  { h: 'Euclides de Alexandria (c. 300 a.C.)' },
  'Quase nada se sabe da vida de Euclides, nem onde nasceu: apenas que ensinou em Alexandria, no tempo de Ptolomeu I. Escreveu os **Elementos**, que organizaram a matemática grega num sistema dedutivo. Escreveu também *Dados*, *Óptica* e *Fenómenos*. Os *Elementos* tiveram, diz-se, mais edições do que qualquer livro exceto a Bíblia, e foram o manual de geometria nas escolas europeias até ao século XX.',
  { h: 'Arquimedes de Siracusa (c. 287 – 212 a.C.)' },
  'Matemático, físico e engenheiro, foi consultor do rei Hierão II. Descobriu a lei da alavanca («dêem-me um ponto de apoio e moverei o mundo» é frase atribuída por Pappus), o princípio do empuxo, a relação entre a esfera e o cilindro (o seu túmulo, segundo Cícero, tinha uma esfera inscrita num cilindro), o cálculo aproximado de π entre 3 + 10/71 e 3 + 1/7, e um método que antecipa o cálculo integral. Morreu no saque de Siracusa, em 212 a.C.; Plutarco refere versões diferentes da sua morte.',
  { h: 'Eratóstenes de Cirene (c. 276 – c. 194 a.C.)' },
  'Poeta, geógrafo, astrónomo e matemático, estudou em Atenas e foi chamado por Ptolomeu III para ser tutor do seu filho e depois **bibliotecário-chefe** de Alexandria. Mediu a circunferência da Terra, escreveu a *Geografia*, onde pela primeira vez usou o termo, e desenhou um mapa do mundo; fez um crivo para encontrar números primos (o «crivo de Eratóstenes») e uma lista de vencedores olímpicos. Alcunhado «Beta» (o segundo), por ser excelente em tudo e primeiro em nada, segundo um relato antigo. Segundo a tradição, morreu voluntariamente, de fome, quando ficou cego.',
  { h: 'Hipócrates de Cós (c. 460 – c. 370 a.C.)' },
  'Médico e professor, contemporâneo de Sócrates, é mencionado por Platão como mestre de medicina, e por Aristóteles. O **Corpus Hipocrático**, com cerca de sessenta obras de autores diversos, foi-lhe atribuído em bloco, mas os especialistas debatem quais são dele. Ensinava que o médico deve observar, descrever e ajudar a natureza do doente a curar-se, e que não deve fazer mal (o célebre «em primeiro lugar, não prejudicar» é uma fórmula moderna; nas *Epidemias* lê-se «ajudar ou, pelo menos, não prejudicar»).',
  { img: 'gfc-hipocrates-busto', leg: 'Busto de Hipócrates, cópia romana de um retrato helenístico. Museu Arqueológico de Óstia Antica. O retrato é idealizado: não se conhece a aparência real de Hipócrates. (Imagem ilustrativa gerada por IA.)' },
  { h: 'Heródoto de Halicarnasso (c. 484 – c. 425 a.C.)' },
  'Nasceu em Halicarnasso, cidade da Cária então governada pela rainha Artemísia I, que combateu ao lado dos persas em Salamina; foi obrigado a partir por razões políticas e viveu em Samos e em Atenas, antes de se instalar em Túrios, colónia no sul de Itália. Viajou muito, e as *Histórias* nasceram dessas viagens e das conversas com sacerdotes, comerciantes e soldados. É a nossa fonte principal sobre as Guerras Médicas e, ao mesmo tempo, uma enciclopédia dos povos do seu tempo.',
  { img: 'gfc-herodoto-busto', leg: 'Hermes duplo de Heródoto e Tucídides, cópia romana de um original grego. Museu Arqueológico Nacional de Nápoles. A identificação do retrato de Heródoto é tradicional.' },
  { h: 'Tucídides (c. 460 – c. 400 a.C.)' },
  'Ateniense de família rica, com minas de ouro na Trácia, adoeceu na peste de 430–426 a.C. e sobreviveu. Em 424 a.C. foi estratego e falhou a defesa de Anfípolis, e foi exilado durante vinte anos. Exigia **exatidão** e rejeitava os poetas e logógrafos, e a sua obra é uma lição de rigor político e de análise do poder. O seu relato morre a meio de uma frase, em 411 a.C., e a conclusão da guerra (404 a.C.) tem de se ler em Xenofonte.',
  { img: 'gfc-tucidides-busto', leg: 'Busto de Tucídides, cópia romana de um original grego do século IV a.C. Holkham Hall, Norfolk (Reino Unido).' },
  { h: 'Safo de Lesbos (c. 630 – c. 570 a.C.)' },
  'Poeta de Lesbos, de família aristocrática, dirigiu um círculo de mulheres jovens, para quem escreveu hinos, cantos de casamento e poemas de amor e de saudade. Foi tão admirada na Antiguidade que se lhe chamou «a décima Musa». A sua vida está envolta em lenda (o salto do penhasco de Léucade por amor de Fáon é uma invenção tardia, mais de comédia do que de biografia). A sua poesia, que fala de desejo de mulheres por mulheres, deu origem às palavras «lésbica» e «sáfico», e a maior parte perdeu-se ao longo da Idade Média (a ideia de que a Igreja queimou os seus livros não tem prova).',
  { img: 'gfc-safo-vaso', leg: 'Safo e Alceu, taça (kalathos) ática de figuras vermelhas, c. 470 a.C., atribuída ao Pintor de Brygos. Staatliche Antikensammlungen, Munique. Retrato imaginado, feito um século depois da sua morte.' },
  { h: 'Sófocles (c. 496 – 406 a.C.)' },
  'Nascido em Colono, perto de Atenas, foi o dramaturgo mais bem sucedido do seu tempo: venceu mais concursos do que Ésquilo e Eurípides, e foi também tesoureiro dos aliados e estratego com Péricles (na guerra de Samos, 441 a.C.). As suas peças tratam o conflito entre o indivíduo, a família, o Estado e os deuses, com **Antígona** (que enterra o irmão contra o decreto do rei) e **Édipo** como figuras centrais. Sigmund Freud usou o nome de Édipo para o «complexo de Édipo», uma leitura que o dramaturgo nunca teve em mente.',
  { img: 'gfc-sofocles-laterano', leg: 'Estátua de Sófocles (tipo «Latrão»), cópia romana de um original grego de c. 340 a.C. Museus do Vaticano (antes no Palácio de Latrão).' }
];

const legado = [
  { h: 'O que nos deixaram' },
  { lista: [
    '**A filosofia como disciplina:** a ideia de que se pode discutir racionalmente o conhecimento, a moral e a política, e a divisão em lógica, ética, física e metafísica.',
    '**A demonstração:** os *Elementos* de Euclides foram modelo de rigor para Newton e para Spinoza, e ainda são lidos como exercício de raciocínio.',
    '**A história crítica:** Heródoto e Tucídides inspiraram todos os historiadores, de Políbio a Tito Lívio, ao Renascimento e ao presente.',
    '**O teatro:** os géneros (tragédia, comédia, drama satírico), a estrutura em atos e coro e conceitos como a catarse e o herói trágico.',
    '**A literatura:** a *Ilíada*, a *Odisseia* e as peças de Sófocles e Eurípides são fonte de inspiração permanente, de Virgílio a James Joyce.',
    '**Medicina e ciência:** a observação, o caso clínico, a classificação, o raciocínio matemático e o método experimental incipiente.'
  ] },
  { h: 'A transmissão: de Alexandria a Bagdade' },
  'Os textos gregos chegaram até nós graças a uma corrente de copistas e de tradutores. Em **Constantinopla**, os bizantinos copiaram os clássicos e deram-lhes a forma de livros de pergaminho (códices), com letra minúscula, a partir do século IX. Em **Bagdade**, entre os séculos VIII e X, o califado abássida patrocinou um grande **movimento de tradução** do grego (muitas vezes através do siríaco) para o árabe, com figuras como **Hunayn ibn Ishaq**; Aristóteles, Euclides, Galeno, Ptolomeu e Arquimedes entraram na ciência árabe. No século XII, as traduções do árabe para o latim, em Toledo, trouxeram-nos de volta à Europa.',
  { img: 'gfc-casa-sabedoria', leg: 'Cena imaginada de tradutores e copistas a trabalhar com manuscritos gregos em Bagdade, séc. IX; a decoração e os trajes são reconstruções. Ilustração gerada por IA.' },
  { h: 'O Renascimento e a imprensa' },
  'Depois da queda de Constantinopla (1453), e já antes dela, sábios bizantinos como Manuel Crisoloras (em Florença, a partir de 1397) levaram manuscritos e o ensino do grego para Itália. Em Florença, **Marsílio Ficino** traduziu para latim a obra completa de Platão (impressa em 1484). Em Veneza, **Aldo Manúcio** imprimiu a partir de 1495 as primeiras edições dos clássicos gregos, incluindo Aristóteles. A primeira edição impressa dos *Elementos* de Euclides é de Veneza, 1482. Foi a partir daqui que se fez o regresso à ciência antiga e à sua crítica, de Copérnico (que cita Aristarco) a Galileu.',
  { h: 'Os papiros de Herculano e de Oxirrinco' },
  'Os arqueólogos recuperaram textos que se julgavam perdidos. Na **Vila dos Papiros**, em Herculano, soterrada pelo Vesúvio em 79 d.C., encontraram-se (desde 1752) cerca de 1800 rolos carbonizados, em grande parte obras do epicurista **Filodemo de Gádara**; hoje desenrolam-se com raios X e inteligência artificial. Em **Oxirrinco**, no Egito, os papiros descobertos a partir de 1896 por Bernard Grenfell e Arthur Hunt incluem Safo, Píndaro, Menandro e outros autores, e documentos do quotidiano de uma cidade grega no Egito.',
  { h: 'A «Escola de Atenas» e o ensino' },
  'A Academia, o Liceu e a Estoa são os antepassados distantes das universidades, mesmo que as universidades medievais tenham nascido de outro contexto (as escolas catedrais, as corporações de mestres de Bolonha e de Paris). As «sete artes liberais» da Idade Média (gramática, retórica, lógica, aritmética, geometria, música e astronomia) vêm de uma educação grega, passada por Roma. A palavra «escola» vem do grego *skholē* («tempo livre»), e «universidade», pelo contrário, do latim.',
  { h: 'O Cristianismo e a filosofia grega' },
  'O pensamento cristão primitivo, escrito em grego, usou conceitos e categorias do platonismo e do estoicismo (*logos*, alma, natureza). Santo Agostinho leu «os livros dos platónicos»; Tomás de Aquino, no século XIII, fez do aristotelismo a base da teologia escolástica; e a filosofia islâmica (Avicena, Averróis) e judaica (Maimónides) também se construíram em diálogo com Aristóteles. A relação entre a razão grega e a fé é um dos grandes temas da cultura ocidental.',
  { h: 'Os gregos na ciência moderna' },
  'Galileu e Newton leram Arquimedes e Euclides; Copérnico mencionou Aristarco e os pitagóricos num manuscrito; Kepler construiu os seus modelos com cónicas de Apolónio. **Átomo**, **cosmos**, **física**, **biologia**, **energia** (de *energeia*) e **ecologia** são termos de origem grega. No entanto, a ciência moderna distingue-se da grega pela experimentação sistemática e pela quantificação, que só se tornaram regra no século XVII.',
  { h: 'O teatro grego hoje' },
  'As peças gregas continuam a ser representadas no mundo todo, nos teatros antigos, como o de **Epidauro** (festival de Atenas e de Epidauro, todos os verões), e em adaptações modernas, desde *Antígona* (Anouilh, Brecht) a *Medeia* (Pasolini, Lars von Trier) e a ópera (*Édipo*, de Enescu; *Elektra*, de Richard Strauss). Também em Portugal tiveram versões de grande impacto, em traduções de helenistas portugueses como Maria Helena da Rocha Pereira, Maria do Céu Fialho e Frederico Lourenço.',
  { h: 'Literatura grega em português' },
  'Em Portugal, a tradição dos estudos clássicos foi assegurada por Universidades como a de Coimbra e de Lisboa. **Maria Helena da Rocha Pereira** (1925–2017), de Coimbra, é autora de *Hélade*, antologia de textos gregos, e de *Estudos de História da Cultura Clássica*, e traduziu a *República* de Platão. **Frederico Lourenço** traduziu diretamente do grego, para português europeu, a *Odisseia* (2003) e a *Ilíada* (2005), e mais tarde a Bíblia. São leituras recomendadas para quem queira conhecer os textos sem intermediários.',
  { h: 'Onde visitar' },
  { lista: [
    '**Atenas:** a Ágora Antiga e a Estoa de Átalo (museu), o Teatro de Dioniso, a Acrópole, o Museu da Acrópole, o Museu Arqueológico Nacional (Mecanismo de Anticítera); os sítios da Academia de Platão (Parque Arqueológico) e do Liceu de Aristóteles.',
    '**Delfos e Epidauro:** o santuário de Delfos e o teatro de Epidauro, famoso pela acústica.',
    '**Cós:** o santuário de Asclépio (Asclepieion).',
    '**Turquia:** Mileto, Éfeso, Pérgamo, Priene e Halicarnasso (Bodrum).',
    '**Itália:** o Museu Arqueológico Nacional de Nápoles (Mosaico da Academia, papiros de Herculano), as ruínas de Siracusa, de Eleia/Vélia e de Crotona.',
    '**Egito:** Alexandria, com a nova Biblioteca de Alexandria (2002) e o museu greco-romano.',
    '**Museus:** o Louvre, o Museu Britânico, os Museus do Vaticano, o Museu Calouste Gulbenkian (Lisboa) e outros museus têm esculturas, vasos e inscrições gregas.',
    '**Livros e leituras:** a *Ilíada* e a *Odisseia* (tradução de Frederico Lourenço), as tragédias de Sófocles (Maria do Céu Fialho e outros helenistas) e a *República* de Platão (Maria Helena da Rocha Pereira).'
  ] },
  { cit: '«Uma vida sem exame não vale a pena ser vivida.»', fonte: 'Platão, *Apologia de Sócrates*, 38a, na tradução habitual; as palavras são de Platão, e não sabemos até que ponto reproduzem as de Sócrates' },
  { h: 'Notas finais' },
  'Esta página resume mais de mil anos de pensamento e de escrita. Muitas datas são aproximadas e muitos pormenores biográficos vêm de fontes tardias; sempre que possível, assinalámos o que é tradição e o que é facto. As páginas sobre a **Época Clássica**, o **Helenismo** e a **Arte e arquitetura** completam o quadro; as figuras principais da filosofia e da literatura são também apresentadas, de forma mais breve, na página-mãe da Grécia.'
];

const quiz = [
  { p: 'Que filósofo de Mileto defendeu que a água era o princípio de todas as coisas?', op: ['Anaximandro', 'Tales', 'Heráclito', 'Parménides'], certa: 1, exp: 'Tales de Mileto, segundo Aristóteles; Anaximandro defendeu o *ápeiron* e Anaxímenes o ar.' },
  { p: 'Quem foi acusado em 399 a.C. de não honrar os deuses da cidade e de corromper os jovens?', op: ['Platão', 'Aristóteles', 'Sócrates', 'Demóstenes'], certa: 2, exp: 'Sócrates foi condenado por um júri de 501 cidadãos e bebeu a cicuta.' },
  { p: 'Como se chama a escola fundada por Platão, por volta de 387 a.C.?', op: ['O Liceu', 'O Jardim', 'A Academia', 'O Museu'], certa: 2, exp: 'A Academia, num recinto dedicado ao herói Academo; o Liceu foi de Aristóteles e o Jardim de Epicuro.' },
  { p: 'Que escola de filosofia deve o nome à «Estoa Pecile» (pórtico pintado) de Atenas?', op: ['O epicurismo', 'O estoicismo', 'O cinismo', 'O ceticismo'], certa: 1, exp: 'Zenão de Cício ensinava no pórtico, daí «estoicos».' },
  { p: 'Quem escreveu os *Elementos*, um manual de geometria usado durante mais de dois mil anos?', op: ['Arquimedes', 'Euclides', 'Pitágoras', 'Eratóstenes'], certa: 1, exp: 'Euclides, em Alexandria, c. 300 a.C.' },
  { p: 'Como calculou Eratóstenes a circunferência da Terra?', op: ['Contando passos entre duas cidades', 'Comparando a sombra do Sol em Alexandria e em Siene', 'Observando um eclipse da Lua', 'Medindo a altura de uma montanha'], certa: 1, exp: 'Ao meio-dia do solstício, em Siene o Sol ficava a pique, em Alexandria havia sombra, e a diferença dava a fração do círculo.' },
  { p: 'Que astrónomo grego propôs que a Terra gira em torno do Sol?', op: ['Hiparco', 'Aristarco de Samos', 'Ptolomeu', 'Eudoxo'], certa: 1, exp: 'Aristarco de Samos (século III a.C.); a ideia quase não teve seguidores.' },
  { p: 'O que é o Mecanismo de Anticítera?', op: ['Um poema épico', 'Um aparelho de engrenagens de bronze que mostrava movimentos dos astros', 'Um templo de Apolo', 'Uma máquina de cerco'], certa: 1, exp: 'Foi recuperado de um naufrágio em 1901, e data, muito provavelmente, dos séculos II–I a.C.' },
  { p: 'A medicina de Hipócrates defendia que as doenças:', op: ['Eram castigos dos deuses', 'Tinham causas naturais', 'Eram sempre hereditárias', 'Curavam-se só com sacrifícios'], certa: 1, exp: 'O Corpus Hipocrático rejeita as causas divinas, mesmo para a «doença sagrada» (epilepsia).' },
  { p: 'Quem é considerado o «pai da história» pelas suas *Histórias* sobre as Guerras Médicas?', op: ['Tucídides', 'Xenofonte', 'Heródoto', 'Políbio'], certa: 2, exp: 'Heródoto de Halicarnasso; Tucídides escreveu sobre a Guerra do Peloponeso.' },
  { p: 'Qual destas obras é de Tucídides?', op: ['A *Anábase*', 'A *Guerra do Peloponeso*', 'As *Histórias*', 'A *Ciropedia*'], certa: 1, exp: 'A *Anábase* e a *Ciropedia* são de Xenofonte; as *Histórias*, de Heródoto.' },
  { p: 'Qual é o tema central da *Ilíada*?', op: ['O regresso de Ulisses a Ítaca', 'A cólera de Aquiles durante a guerra de Troia', 'A origem dos deuses', 'A fundação de Roma'], certa: 1, exp: 'O regresso de Ulisses é a *Odisseia*; a origem dos deuses é a *Teogonia*, de Hesíodo.' },
  { p: 'Que poeta de Lesbos tem apenas um poema completo conservado, e de resto só fragmentos?', op: ['Corina', 'Safo', 'Aspásia', 'Hiparquia'], certa: 1, exp: 'Safo (c. 630 – c. 570 a.C.), de Lesbos; só o *Hino a Afrodite* chegou completo.' },
  { p: 'Qual é a mais antiga tragédia grega que conservamos, de Ésquilo, de 472 a.C.?', op: ['*Antígona*', '*Os Persas*', '*Medeia*', '*As Bacantes*'], certa: 1, exp: '*Os Persas*, sobre a derrota persa em Salamina, é a única tragédia conservada sobre um tema histórico recente.' },
  { p: 'Que comédia de Aristófanes satiriza Sócrates?', op: ['*As Rãs*', '*Lisístrata*', '*As Nuvens*', '*As Aves*'], certa: 2, exp: '*As Nuvens* (423 a.C.); em *As Rãs* confrontam-se Ésquilo e Eurípides.' }
];

export default {
  id: 'grecia',
  cor: '#3a7ab8',
  emblema: '../../assets/img/grecia.png',
  grupo: { ...GRUPO, aqui: 'filosofia-ciencia' },
  nome:    { pt: 'Filosofia, ciência e literatura', en: 'Philosophy, science and literature' },
  periodo: { pt: 'séc. VIII a.C. – II d.C.', en: '8th century BC – 2nd century AD' },
  visao:          { pt: visao, en: EN.visao },
  linha:          { pt: linha, en: EN.linha },
  mapa:           { pt: mapa, en: EN.mapa },
  sociedade:      { pt: sociedade, en: EN.sociedade },
  personalidades: { pt: personalidades, en: EN.personalidades },
  legado:         { pt: [...legado, ...CRED.pt], en: [...EN.legado, ...CRED.en] },
  quiz:           { pt: quiz, en: EN.quiz }
};
