// BERBERS AND NUMIDIA — full English content. Same structure and same image slots as the Portuguese version (dados.js).
// Dates are approximate. BC = before Christ. The focus is the ancient Amazigh (Libyco-Berber) world up to the Roman annexation of Mauretania (AD 40–44), with a short epilogue on the legacy.

const visao = [
  { caixa: 'In brief', texto: [
    'The **Amazigh** (plural **Imazighen**; in English usually «Berbers») are the indigenous peoples of North Africa, from the Atlantic to the oasis of Siwa in Egypt, and from the Mediterranean to the Sahara and the Sahel. In antiquity the Greeks and Egyptians called them **Libyans**, and the Romans **Numidians**, **Moors** (Mauri) and **Gaetulians**. They spoke related languages, wrote in a script of their own (the Libyan script, ancestor of Tifinagh) and organised themselves in tribes, confederations and kingdoms.',
    'Between c. 1200 BC and AD 40 they were neighbours and rivals of pharaonic Egypt (which even had a dynasty of pharaohs of Libyan descent), partners and opponents of Carthage, and decisive allies of Hannibal and then of Rome. **Masinissa** created a unified, agricultural kingdom in Numidia, **Jugurtha** defied Rome, and **Juba II** reigned as a scholar-king and married the daughter of Cleopatra. In AD 40 the last royal dynasty of Mauretania ended, and Rome annexed the kingdoms.',
    'It was not an «empire» nor a single political people: it was a world of tribes, cities and kingdoms that shared language, customs and landscape, and that is still alive today.'
  ] },
  { img: 'ber-mapa-regiao', leg: 'Contemporary map of Berber-speaking areas in North Africa and the Sahara, 2024 version.' },
  { h: 'Where it was' },
  'The ancient Amazigh space is the **Maghreb** (the «West» in Arabic) and the **Sahara**: from Morocco to Libya, with the desert oases as far as the Fezzan and the Egyptian border. Ancient geographers divided it by regions. The **Libya** of the Greeks was, in a broad sense, the whole continent west of the Nile. **Numidia** corresponds roughly to north-eastern Algeria and western Tunisia. Ancient **Mauretania** (not to be confused with the modern country) was the north-west of Africa, today Morocco and western Algeria. **Gaetulia** was the steppe and semi-desert to the south, and the **Fezzan** (south-west Libya) was the land of the Garamantes.',
  'It is a land of contrasts: a fertile Mediterranean coast, mountain ranges (the **Atlas**, the Aurès, Kabylia), steppe plateaus for herding and, to the south, the Sahara with its oases. This variety explains the ways of life: cereals, vines and olives on the plains, herding and **transhumance** (the seasonal movement of flocks) on steppes and mountains, caravans and oases in the desert.',
  { img: 'ber-paisagem-atlas', leg: 'Landscape of the High Atlas, Morocco.' },
  { h: 'When it existed' },
  'Berber-speaking peoples are much older than any kingdom: the populations of North Africa have thousands of years of continuity. But they appear in written sources only from c. 1200 BC, first in Egyptian texts and later in Greek, Carthaginian and Roman ones. The phases below are approximate, and the boundaries between them, especially the oldest, are debated.',
  { tabela: { cab: ['Phase', 'Approximate dates', 'What marks it'], linhas: [
    ['Prehistory and Green Sahara', 'c. 10,000 – 3000 BC', 'A humid Sahara, hunters and herders; rock art of Tassili n’Ajjer; then the desert dries'],
    ['Libyans and Egypt', 'c. 1200 – 730 BC', 'Libu and Meshwesh attack Egypt; settle in the Delta; Shoshenq I and the 22nd Dynasty'],
    ['Carthage and the Libyans', 'c. 814 – 202 BC', 'Phoenician colonies on the coast; Libyans as farmers, soldiers and neighbours of Carthage; Numidian cavalry'],
    ['Kingdoms of Numidia and Mauretania', 'c. 220 – 105 BC', 'Syphax and Masinissa; Zama; Masinissa’s peak; the Jugurthine War'],
    ['Kingdoms and Rome', '105 BC – AD 40', 'Bocchus, Juba I, Juba II; Mauretania as a client kingdom; Tacfarinas; annexation in AD 40–44'],
    ['Epilogue: the Amazigh world afterwards', 'after AD 40', 'Romanisation, Christianity, Islamisation; Tuareg; Almoravids and Almohads; Tamazight and Tifinagh today']
  ] } },
  { img: 'ber-tassili-paisagem', leg: 'Sandstone plateau of Tassili n’Ajjer, Algeria.' },
  { h: 'Amazigh and «Berber»: two words' },
  'The peoples themselves prefer **Amazigh** (plural **Imazighen**), usually translated as «free man» or «noble». This translation is popular but disputed among linguists, and the exact origin of the word is uncertain. Some scholars link it to peoples that ancient sources call **Mazices** or **Maxyes** (Herodotus), but the connection is debated.',
  '«Berber» is a word of foreign origin. It comes from the Greek and Latin **barbaros / barbarus**, used by Greeks and Romans for anyone who did not speak their language (the word imitates the «bar-bar» of an unintelligible tongue). The Arabs used **barbar** for the peoples of the Maghreb, and the word passed into European languages. This is why many Amazigh find it pejorative, although it has been used for centuries, including by the people themselves, and need not carry that meaning today. Here «Amazigh» is used for the peoples and «Berber» for the languages, which is the usual linguistic term in English.',
  { h: 'Language and writing' },
  'The Berber languages form a branch of the **Afro-Asiatic family** (the same as ancient Egyptian, Arabic and Hebrew). Today they are collectively called **Tamazight**, and include Tashelhit and Tarifit (Morocco), Kabyle and Chaoui (Algeria), Tuareg (Sahara and Sahel), Siwi (the oasis of Siwa in Egypt) and others. There is no single Berber language, but a set of varieties, some barely intelligible to each other. In antiquity the language spoken by the Libyans, Numidians and Moors was certainly Berber or very close to it, but direct proof is scarce: we have personal names and short inscriptions in the **Libyan script**, which is only partly deciphered.',
  { h: 'Where did they come from?' },
  'They did not come «from somewhere else» in the simple sense of a single migration. Genetics and archaeology point to a long continuity of populations in North Africa since prehistory, with mixing over time (with sub-Saharan, Phoenician, Greek, Roman, Arab and other populations). The **Berber language** belongs to a family whose exact origin is debated (North Africa, North-East Africa or the Middle East). Any claim of a single «origin» or a Berber «race» is a simplification: what exists is a **cultural and linguistic identity** with more than two thousand years of written record.',
  { h: 'Why they matter' },
  { lista: [
    '**They shaped ancient Mediterranean history:** Numidian cavalry decided battles of Hannibal and of Scipio; Masinissa’s kingdom was central to the fall of Carthage.',
    '**They ruled Egypt:** the 22nd Dynasty (Shoshenq I and successors) was of Libyan origin and lasted more than 200 years.',
    '**They created kingdoms and a script of their own:** Libyco-Berber is one of the oldest African scripts still in use (among the Tuareg, as Tifinagh).',
    '**They left unique monuments:** the great mausoleums of Medracen, El Khroub, Dougga and Mauretania (Tipasa).',
    '**They have living continuity:** languages, script, traditions, festivals (Yennayer) and a flag that speaks for millions of people.'
  ] },
  { caixa: 'The Amazigh today', texto: 'An estimated **25 to 36 million** people identify as Amazigh, mostly in Morocco and Algeria, but also in Libya, Tunisia, Mali, Niger and the European diaspora. Tamazight has been an official language in Morocco since 2011 and in Algeria since 2016. Estimates vary widely and depend on whom one counts (speakers, self-identified, descendants).' }
];

const linha = [
  'This timeline follows the ancient Amazigh world up to the Roman annexation and ends with an epilogue. Dates are approximate, especially the oldest; the best-dated events are those of the Roman period.',
  { linha: [
    { d: 'c. 10,000 – 5000 BC', t: 'The Green Sahara and the first images', x: 'Ten thousand years ago the Sahara was a region of lakes, savannas and seasonal rivers, with giraffes, hippos and cattle. Hunter-gatherers and later herders painted and engraved thousands of scenes on the rocks of **Tassili n’Ajjer** (Algeria), the Acacus (Libya) and other massifs. It cannot be claimed that these artists spoke Berber: the continuity is debated.' },
    { d: 'c. 5500 – 2500 BC', t: 'The Sahara dries', x: 'From c. 5500 BC the climate becomes progressively drier, and by about 3000–2500 BC the Sahara approaches today’s desert. Many groups migrate north (the Maghreb and the Nile valley) and south (the Sahel). The herding communities and the future Libyan and Garamantian societies take shape in this context.' },
    { d: 'c. 1200 BC onwards (dating debated)', t: 'Horses, chariots and the «horse period»', x: 'Paintings and engravings show horses and two-wheeled chariots at a «flying» gallop in the central Sahara. Some have tried to see in them a «chariot route» linking the Mediterranean to the Niger, a hypothesis now contested for lack of archaeological proof. What is certain is that the horse became central to Libyco-Berber culture.' },
    { d: 'c. 1208 BC', t: 'The Libyans attack Egypt (Merneptah)', x: 'In Merneptah’s 5th year, a coalition of **Libu**, **Meshwesh** and «Sea Peoples» invades the Delta but is defeated. It is the first major entry of the Libyans into written history. Egyptian sources call them **Tjehenu**, **Tjemehu**, **Libu** and **Meshwesh**; the name «Libya» comes from Libu.' },
    { d: 'c. 1176 and c. 1170 BC', t: 'Ramesses III defeats the Libyans', x: 'Ramesses III repels two Libyan invasions (years 5 and 11). The temple of **Medinet Habu** preserves the reliefs, with Libyan prisoners with long hair, beards and decorated sheaths. Many Libyans eventually settle in the Delta as mercenaries and colonists.' },
    { d: 'c. 814 BC (traditional date)', t: 'Carthage is founded', x: 'Phoenician settlers from Tyre found Carthage (the traditional date is debated; archaeological evidence points to the 8th century BC). The city lives side by side with Libyan populations, from whom it receives land, workers and soldiers. Tradition (Justin) says it paid the Libyans an annual rent for the site until the 5th century BC, a detail that is disputed.' },
    { d: 'c. 945 – 925 BC', t: 'Shoshenq I and the 22nd Dynasty', x: 'A great chief of the Meshwesh becomes pharaoh and founds the **22nd Dynasty** (c. 945–715 BC). Around 925 BC Shoshenq leads a campaign in Palestine, recorded in the Bubastite Portal at Karnak and generally identified with the **Shishak** of the Bible. The dynasties of Libyan origin (22nd to 24th) govern parts of Egypt for c. 200 years.' },
    { d: '7th – 5th century BC', t: 'Greeks in Cyrene and the Libya of Herodotus', x: 'Greeks from Thera found Cyrene (c. 631 BC) on the territory of Libyan populations. Herodotus (5th century BC) devotes Book IV of the «Histories» to Libya: he describes tribes such as the **Nasamonians**, the **Garamantes**, the **Maxyes** and the **Atlantes**. His accounts contain real information and fanciful details. The Garamantes, in the Fezzan, are already a power.' },
    { d: 'c. 5th – 3rd century BC', t: 'Carthage and its relations with the Libyans', x: 'Libyan soldiers serve in large numbers in Punic armies, and the farmland around Carthage is largely worked by Libyan peasants (alongside mixed communities, the «Libyphoenicians»). The Libyans revolt several times (396 BC, according to Diodorus, with exaggerated numbers; 241–238 BC, in the Mercenary War).' },
    { d: '3rd – 2nd century BC', t: 'The Libyan script enters monuments', x: 'The Numidian kingdoms adopt inscriptions in Libyan script, sometimes in bilingual texts with Punic. The most famous is that of **Dougga**, c. mid-2nd century BC, on the mausoleum of Atban. Its study, from 1843, made it possible to decipher much of the alphabet.' },
    { d: '218 – 216 BC', t: 'Hannibal and the Numidian cavalry', x: 'In the Second Punic War, Numidian horsemen are Hannibal’s shock and scouting arm. They shine at the Trebia (218) and at **Cannae** (216). According to Livy, at Cannae about five hundred Numidians pretended to surrender and then attacked the Romans from behind. The episode is told by Livy, who wrote nearly two centuries after the events.' },
    { d: 'c. 213 – 205 BC', t: 'Syphax, Masinissa and the choice of sides', x: '**Syphax**, king of the Masaesyli, allies with Rome and then with Carthage (206–205 BC), marrying **Sophonisba**. **Masinissa**, of the Massyli, fights for Carthage in Spain and switches to Rome in 206 BC, after losing his father’s kingdom to Syphax.' },
    { d: '203 BC', t: 'Fall of Syphax and death of Sophonisba', x: 'Scipio, Laelius and Masinissa defeat Syphax at the Battle of the Great Plains and take **Cirta**. Syphax is taken to Italy and dies in captivity. Masinissa marries Sophonisba but, faced with Scipio’s demand to hand her over to Rome, sends her poison, and she drinks it.' },
    { d: '202 BC', t: 'Zama and Masinissa’s triumph', x: 'At the Battle of **Zama** (site debated), Masinissa’s cavalry, who had gone over to the Roman side, attack the Punic rear and decide Scipio’s victory. Masinissa becomes king of a unified Numidia, bringing together the Massyli and a large part of the Masaesyli.' },
    { d: 'c. 202 – 148 BC', t: 'The reign of Masinissa', x: 'Masinissa rules for more than 50 years. He settles herders as farmers, mints coins, builds cities (**Cirta** is the capital) and opens up to Hellenistic and Punic culture. He pressures Carthage, which finally reacts. In 149 BC Rome declares war on Carthage (the **Third Punic War**), and the city is destroyed in 146 BC.' },
    { d: '148 BC', t: 'Death of Masinissa', x: 'Masinissa dies aged about 90. According to Polybius he had fought on horseback shortly before. The kingdom is divided among his three sons, with Scipio Aemilianus as arbiter; from c. 145 BC **Micipsa** rules alone.' },
    { d: '134 – 118 BC', t: 'Jugurtha, Numantia and the succession', x: 'Jugurtha, Masinissa’s grandson, fights for Rome at **Numantia** (134–133 BC), where he learns how Roman intrigue and bribery work. Micipsa adopts him, and when the king dies in 118 BC, Jugurtha and Micipsa’s two sons, **Hiempsal** and **Adherbal**, are co-heirs.' },
    { d: '112 BC', t: 'The massacre at Cirta', x: 'Jugurtha besieges Adherbal in Cirta. When the city falls, many Italian traders living there are killed, and Rome declares war.' },
    { d: '112 – 105 BC', t: 'The Jugurthine War', x: 'Rome sends several commanders (Bestia, Metellus, **Marius**). The war drags on, with bribes, battles and guerrilla warfare. Sallust narrates it in the following century in **The War with Jugurtha**. In 105 BC **Bocchus I** of Mauretania, Jugurtha’s father-in-law, hands him over to **Sulla**, Marius’s quaestor. Jugurtha is paraded in Marius’s triumph and dies in Rome (104 BC).' },
    { d: '105 BC onwards', t: 'Bocchus I and the kingdom of Mauretania', x: 'As a reward for betraying Jugurtha, Bocchus I receives part of the territory. Mauretania consolidates as a kingdom in the far west, with a history separate from Numidia.' },
    { d: '49 – 46 BC', t: 'Juba I and the Roman civil war', x: '**Juba I**, king of Numidia, supports Pompey and defeats Curio in 49 BC. In 46 BC, however, he is beaten with the Pompeians by Caesar at **Thapsus**, and commits suicide. Eastern Numidia becomes the Roman province of **Africa Nova**; the future historian Sallust is its first governor.' },
    { d: '33 – 25 BC', t: 'Rome gives Mauretania to Juba II', x: 'When Bocchus II dies without heirs in 33 BC, Rome annexes Mauretania in practice. In 25 BC Augustus gives the kingdom to **Juba II**, son of Juba I, raised in Rome. He marries **Cleopatra Selene**, daughter of Cleopatra VII and Mark Antony (date of the marriage debated, c. 25–20 BC).' },
    { d: '19 BC', t: 'Rome against the Garamantes', x: 'The proconsul Lucius Cornelius Balbus defeats the Garamantes and takes their towns, including Garama, according to Pliny. He celebrates a triumph: the last granted to someone outside the imperial family. For centuries the Garamantes become trading partners of Rome.' },
    { d: 'c. late 1st century BC', t: 'The Royal Mausoleum of Mauretania', x: 'Near Tipasa stands an enormous circular mausoleum, generally attributed to Juba II and Cleopatra Selene, about 60 m wide, which still dominates the landscape today. No human remains have been found in it.' },
    { d: 'AD 17 – 24', t: 'The revolt of Tacfarinas', x: 'A Numidian who had served as a Roman auxiliary, **Tacfarinas**, leads the **Musulamii** and other peoples against Rome for seven years, with guerrilla warfare and raids on harvests. He is killed in AD 24 near Auzea.' },
    { d: 'AD 23 – 44', t: 'End of the dynasty and annexation', x: 'Juba II dies in AD 23, and his son **Ptolemy** reigns until he is summoned to Rome and murdered on Caligula’s orders (AD 40). A freedman, **Aedemon**, leads a revolt. Claudius crushes it and organises Mauretania into two provinces (c. AD 42–44), **Tingitana** and **Caesariensis**.' },
    { d: '1842 – 1843', t: 'The rediscovery of the Libyan script', x: 'The British consul Thomas Reade removes the bilingual inscription of Dougga from the mausoleum (and damages it). The comparison of the Punic and Libyan texts allows, from 1843, much of the Libyco-Berber alphabet to be deciphered.' },
    { d: 'after AD 40 (epilogue)', t: 'The Amazigh world goes on', x: 'In the 4th century AD the tomb of **Tin Hinan**, the legendary ancestor of the Tuareg, is built. In the 7th century the queen **Dihya (the «Kahina»)** resists the Arab armies. In the 11th–13th centuries empires of Amazigh origin, the **Almoravids** and the **Almohads**, dominate the Maghreb and Islamic Iberia. In 1970 the Amazigh flag is born, and Tamazight becomes an official language in Morocco (2011) and Algeria (2016).' }
  ] },
  { img: 'ber-tassili-pintura', leg: 'Rock paintings with human and animal figures at Tanzoumaitak, Tassili n’Ajjer, Algeria.' },
  { img: 'ber-tassili-carros', leg: 'Rock engraving of a chariot at Oued Djerat, Tassili n’Ajjer. Documentary alternative to the requested flying-gallop horse painting.' },
  { img: 'ber-medinet-habu-libios', leg: 'Libyan prisoners in a relief of Ramesses III at Medinet Habu; historical photograph dated to 1870–1896, Photographic Archive of the Egyptian Museum, Turin.' },
  { img: 'ber-shoshenq-bubastita', leg: 'Bubastite Portal at Karnak, associated with Shoshenq I’s campaign.' },
  { img: 'ber-batalha-zama', leg: 'Battle of Zama, an anonymous Renaissance painting after Cornelis Cort, 1567–1578; Art Institute of Chicago.' }
];

const mapa = [
  'The ancient Amazigh world was not a map of city-states like Sumer, but a mosaic of **kingdoms, tribes, oases and cities** with strong Punic and later Roman influence. Many sites now have only ruins, and the most important cities survive beneath modern ones, such as Constantine (Cirta). The table lists the main places; the following sections tell the essentials of each.',
  { img: 'ber-mapa-reinos', leg: 'Map of the kingdoms of Syphax (Masaesyli) and Gaia (Massylii), c. 220 BC.' },
  { tabela: { cab: ['Place', 'Where it is today', 'Role in antiquity', 'What remains'], linhas: [
    ['Cirta (Constantine)', 'North-eastern Algeria', 'Capital of Masinissa and of the kings of eastern Numidia; site of the El Hofra sanctuary', 'Modern city above a gorge; some Roman structures and finds in the museum'],
    ['Siga', 'North-western Algeria (Takembrit)', 'Capital of Syphax and the Masaesyli', 'Excavated ruins, Libyan inscriptions'],
    ['Hippo Regius', 'Annaba, Algeria', 'Numidian royal residence; later the city of Saint Augustine', 'Roman ruins'],
    ['Dougga (Thugga)', 'Northern Tunisia', 'Libyco-Punic city, later Roman; mausoleum of Atban', 'One of the best-preserved ancient sites of the Maghreb'],
    ['Bulla Regia', 'North-western Tunisia', 'Numidian royal city, later Roman', 'Roman underground houses and mosaics'],
    ['Zama', 'Tunisia (site debated)', 'Setting of the battle of 202 BC', 'Site debated: Jama or Naraggara, among others'],
    ['Caesarea (Iol Caesarea, Cherchell)', 'Algeria, coast', 'Capital of Juba II and Cleopatra Selene', 'Ruins, museum with statues'],
    ['Tipasa and the Royal Mausoleum', 'Algeria, coast', 'Tomb attributed to the Mauretanian dynasty', 'Mausoleum about 60 m wide'],
    ['Volubilis', 'Morocco', 'Mauretanian city, later Roman', 'Mosaics, arch, basilica; World Heritage Site'],
    ['Lixus, Tingis (Tangier)', 'Morocco, Atlantic coast', 'Phoenician and Mauretanian ports, later Roman', 'Ruins at Larache; modern Tangier'],
    ['Garama (Jarma)', 'Fezzan, Libya', 'Capital of the Garamantes', 'Ruins of the city, cemeteries, remains of irrigation systems'],
    ['Siwa', 'Western Egypt', 'Oasis of the oracle of Amun, still Berber-speaking today', 'Temple, village of Shali, the Siwi language'],
    ['Tassili n’Ajjer', 'Southern Algeria', 'Rock art since the Green Sahara', 'Paintings and engravings, World Heritage Site']
  ] } },
  { h: 'Cirta, Masinissa’s capital' },
  'Cirta was built on a rock surrounded by the gorge of the Rummel river, and the topography gives it a natural defence. According to Livy, it was Syphax’s «royal city» after he occupied the lands of the Massyli, and Masinissa retook it in 203 BC. It became the **capital of eastern Numidia**. In Constantine the sanctuary of **El Hofra** (a Punic-Numidian tophet) keeps hundreds of votive stelae dedicated to **Baal Hammon and Tanit**, with inscriptions in Punic and Libyan, showing how Numidian and Punic cultures mixed. After Rome took the territory the city remained important. In the 4th century AD the emperor Constantine rebuilt it and gave it his name: Constantine.',
  { img: 'ber-cirta-gargantas', leg: 'Modern view of Constantine, ancient Cirta, above the Rhumel River gorge, Algeria.' },
  { img: 'ber-cirta-reconstrucao', leg: 'Hypothetical reconstruction of Cirta, c. 190 BC, above the Rhumel River gorge. AI-generated illustration.' },
  { h: 'Siga, capital of the Masaesyli' },
  'Siga (today Takembrit, near Beni Saf) was the capital of the **Masaesyli**, the great western kingdom of Numidia, whose most famous king, **Syphax**, at his height controlled a region running roughly from the Moulouya river to the area of Cirta. It is a port city at the mouth of the Tafna river, and was also a Phoenician trading post. Inscriptions in Libyan script have been found here, and Livy (Book XXVIII) tells of Scipio’s visit to Syphax at Siga in 206 BC, which coincided with the arrival of the Carthaginian Hasdrubal Gisco: the king is said to have received the two enemies at the same table. The tomb of Syphax is not known with certainty: the idea that the mausoleum of El Khroub or another one belonged to him has no solid support.',
  { img: 'ber-siga-ruinas', leg: 'Ruins of the so-called Royal Mausoleum of Syphax near Siga (Takembrit), Algeria; photograph taken in 2026.' },
  { h: 'Dougga (Thugga) and the mausoleum of Atban' },
  'The city of Thugga, on a hill in northern Tunisia, was a Libyan settlement before being Punic and then Roman. From the Numidian period (3rd–2nd centuries BC) survives the remarkable **Libyco-Punic mausoleum**, three storeys and 21 m high, made famous by its bilingual inscription. From the Roman period survive the theatre (2nd century AD), the Capitol, the temple of Saturn and a number of houses. It has been a World Heritage Site since 1997.',
  { img: 'ber-dougga-teatro', leg: 'Roman theatre at Dougga (Thugga), Tunisia; a monument from a period later than the Numidian kingdom.' },
  { img: 'ber-thugga-reconstrucao', leg: 'Hypothetical reconstruction of Thugga (Dougga), c. 150 BC, with its Libyco-Punic mausoleum. AI-generated illustration.' },
  { h: 'Caesarea and the kingdom of Mauretania' },
  'At Iol, an old Punic port, Juba II built his capital, which he called **Caesarea** (today Cherchell), in honour of Augustus. It was a city of Hellenistic and Roman culture, with a theatre, temples and sculptures in Greek and Egyptian style linked to the royal court, now in the local museum. The royal mausoleum, to the east, along the road to Algiers and near Tipasa, was probably built as the tomb of the royal family.',
  { img: 'ber-cherchell-ruinas', leg: 'Ruins of the Western Baths at Cherchell (Iol Caesarea), Algeria.' },
  { h: 'Volubilis' },
  'Volubilis, by the plains of Morocco, was a settlement of Amazigh and Punic culture from the 3rd century BC, with Phoenician and Mauretanian influence. It was one of the main cities of the Mauretanian kingdom in Juba II’s time, but it is not certain that it was the capital of the kingdom (the main capital was Caesarea). After the annexation of AD 44 it became a prosperous Roman city, producing olive oil, and it still has arches, a basilica and mosaics. It was abandoned late and has been a World Heritage Site since 1997.',
  { img: 'ber-volubilis-ruinas', leg: 'Arch of Caracalla at Volubilis, Morocco, seen from the south; a Roman monument later than the Numidian kingdoms.' },
  { h: 'Garama, capital of the Garamantes' },
  'In the Fezzan, in south-western Libya, the **Garamantes** built an urban society in a desert, with no river nearby. Garama (Jarma), the capital, perhaps had a few thousand inhabitants, and the surrounding areas may have supported tens of thousands of people. They grew dates, wheat, barley and vines thanks to a system of **foggaras**, underground channels that carried water from fossil aquifers. They traded with Rome and with the Sahel region. Modern excavation, above all by David Mattingly, has shown that they were not mere «desert nomads», as Greek and Roman sources suggested.',
  { img: 'ber-garama-ruinas', leg: 'Ruins of Garama (Jarma), Fezzan, Libya.' },
  { img: 'ber-garama-reconstrucao', leg: 'Hypothetical reconstruction of Garama, capital of the Garamantes, c. AD 100, with foggara irrigation. AI-generated illustration.' },
  { h: 'Routes and oases' },
  'Routes linked the Mediterranean to the Sahel across the Sahara. The Garamantes controlled part of them, and the oases (Siwa, Ghadames, Kufra and others) were essential stops. Before the camel, horses, donkeys and oxen were used; the camel gradually became common in the Sahara during the 1st millennium BC and the first centuries AD (the chronology is debated), with an enormous role in later crossings. Salt, dates, ivory, gold, slaves (a trade whose scale is little known) and Mediterranean goods travelled along the routes. The scale and date of trans-Saharan trade in the ancient period are debated.'
];

const sociedade = [
  { h: '1. Political organisation' },
  'There was no single Amazigh state. The political unit was the **tribe** (a group linked by real or supposed kinship) and, above it, the **confederation** and the **kingdom**. The main peoples recorded in ancient sources are the **Massyli** (in the east, around Cirta), the **Masaesyli** (in the west, around Siga), the **Moors** (far west), the **Gaetulians** (steppes of the south), the **Musulamii**, the **Nasamonians**, the **Garamantes**, among many others. Several groups had elected or hereditary chiefs, assemblies of elders and bonds of personal loyalty.',
  '**Kings** (in modern Berber, **agellid**) concentrated military command, justice and diplomacy. Succession could be by primogeniture but, according to Livy, among the Numidians the oldest male of the family succeeded rather than the son, which caused conflicts (Jugurtha and the sons of Micipsa are the most cited example). Numidian kings made alliances with Carthage and with Rome and were educated in Greek and Roman culture (Juba II).',
  { h: '2. Social classes' },
  { lista: [
    '**Kings and their family:** great owners of land, flocks and horses; patrons of cities.',
    '**Military aristocracy:** tribal chiefs, horsemen and commanders.',
    '**Free men:** peasants, herders, craftsmen, traders, warriors.',
    '**Dependants and slaves:** farm workers, prisoners of war and enslaved people (data on slavery are scarce).'
  ] },
  'One source of wealth was **cattle and horses**, and ancient sources insist on the great flocks and on the Numidian horse. Prestige was tied to the ability to gather horsemen and, after Masinissa, also to landownership.',
  { h: '3. Religion' },
  'The indigenous religion was polytheistic and tied to nature and ancestors. Herodotus says (IV, 188) that the Libyans sacrificed above all to the **Sun and the Moon**; other sources mention the cult of stones, trees, springs, mountains and caves, and strong attention to the dead (monumental tombs, bazinas and dolmens). Phoenician influence brought the Punic gods, and the Numidians came to worship **Baal Hammon and Tanit** as well, often with Libyan names and dedications. Later, with Rome, Roman gods came and the cults took new names.',
  { tabela: { cab: ['Deity', 'Domain', 'Where and how it appears'], linhas: [
    ['Amun (Zeus-Ammon)', 'Ram-god, oracle', 'Oasis of Siwa; linked to Libya and Cyrene; the oracle was visited by Alexander in 331 BC'],
    ['Baal Hammon', 'Supreme Punic god, fertility and abundance', 'Stelae of El Hofra (Cirta); in Roman times, «African Saturn»'],
    ['Tanit', 'Goddess of fertility and protector of Carthage', 'Stelae with the symbol of Tanit at Carthage and in Numidia; the link with Libyan cults is debated'],
    ['Sun and Moon', 'Heavenly bodies', 'According to Herodotus, the Libyans sacrificed to them'],
    ['Ifri / Ifru', 'Deity of caves (debated)', '«Ifri» means «cave» in Berber; associated with place names and tribes; its character as a deity is discussed'],
    ['Gurzil (late)', 'Bull-god', 'Attested only in Late Antiquity (6th century AD), outside the period']
  ] } },
  { img: 'ber-tanit-estela', leg: 'Punic stele from Carthage with the symbol of Tanit; Louvre, AO 23068.' },
  { img: 'ber-templo-amon-siwa', leg: 'Ruins of the Temple of the Oracle of Amun at Aghurmi, Siwa Oasis, Egypt.' },
  { h: '4. Economy' },
  'The economy combined **agriculture, herding and trade**. On the plains wheat, barley, vines, olives and figs were grown; on the steppes, sheep, goats, cattle and horses; in the oases, date palms. Masinissa was crucial: according to the sources, he gave land to herders and settled them in fields and villages, which expanded grain growing. Numidian wheat would later be one of the pillars of Rome’s food supply. Numidia exported horses, cattle, ivory, hides and wild animals for the Roman games; Mauretania had **Gaetulian purple** (a dye extracted from molluscs, produced at Mogador, Morocco, in Juba II’s time).',
  { img: 'ber-mercado-numida', leg: 'Interpretation of a Numidian market in the 2nd century BC. AI-generated illustration.' },
  { h: 'Agriculture and transhumance' },
  '**Transhumance** is the seasonal movement of flocks between summer pastures in the mountains and winter ones on the plains or in the south. It was the basis of herding and in part continues today. Some groups were semi-nomadic, others settled (the classic dualism of the ancient sources, nomad versus farmer, is too simple). Strabo and Sallust describe the Numidians as nomads, but archaeology and the sources on Masinissa show a society with many villages and fields.',
  { img: 'ber-transumancia', leg: 'Interpretation of transhumance in the Atlas Mountains, c. 150 BC. AI-generated illustration.' },
  { h: '5. Writing' },
  'The **Libyan script** (or Libyco-Berber) is an **abjad**: it writes consonants, generally without vowels. It appears in thousands of inscriptions carved in stone, funerary, votive and boundary ones, from the 3rd century BC (probably earlier) to the Roman period. It was often written bottom to top or right to left. There are two main variants: the **eastern** (Tunisia and eastern Algeria), better understood thanks to bilingual texts with Punic, and the **western**, still largely undeciphered. The origin of the alphabet is debated: the most cited theory is of a local prototype inspired by Phoenician or Semitic models.',
  '**Tifinagh**, used by the Tuareg, is a direct descendant of this script and survived for centuries in the Sahara, used in inscriptions, games and letters. The modern version, **neo-Tifinagh**, was standardised in Morocco in 2003 to write Tamazight.',
  { img: 'ber-inscricao-libica', leg: 'Reproduction of the Punic–Libyco-Berber bilingual inscription from Dougga published by Wilhelm Gesenius in 1837; the original is held by the British Museum.' },
  { h: '6. The house' },
  'Sallust describes the houses of the Numidian herders, the **mapalia**, as elongated huts with a curved roof, «like the hulls of ships turned upside down». They were made of branches, reed and hides. In permanent villages stone, adobe and rammed earth were used. In the cities, under Punic and later Roman influence, there were courtyard houses. Monumental tombs (**bazinas**, tumuli) are among the oldest and most durable constructions.',
  { img: 'ber-mapalia-reconstrucao', leg: 'Hypothetical reconstruction of a Numidian mapalia village, 2nd century BC, inspired by Sallust’s description. AI-generated illustration.' },
  { h: '7. Food' },
  'The base was cereals (wheat and barley, as porridge, bread and cakes), milk and its products (curds, cheese), mutton and goat, fruit (figs, dates, olives) and honey. Some ancient sources mention the **«lotus-eaters»**, eaters of lotus, a plant with sweet fruit. **Couscous** is today the emblematic dish of the Maghreb, but the oldest written sources are medieval, and the idea that it was already eaten in Numidian times is debated. Wine and olive oil spread with Carthage and Rome; Herodotus says the nomadic Libyans lived on plenty of milk and meat.',
  { h: '8. Clothing and appearance' },
  'Libyans and Numidians are shown with **short tunics**, cloaks and skins. The Egyptians show the Libyans with long hair, sometimes with a side lock, short beards, decorated sheaths and tattoos. Herodotus (IV, 189) claims that the goatskin dress of Libyan women inspired Athena’s aegis, a thesis historians regard as a curiosity, not a fact. In Roman sources Numidian horsemen appear without armour, with a leopard skin or a small round shield.',
  { img: 'ber-vestuario-numida', leg: 'Artistic study of Numidian clothing in the 2nd century BC. AI-generated illustration.' },
  { h: '9. Music, games and festivals' },
  'Ancient sources say little about music and games. We know there was dance and music at festivals, and that horsemen gave displays of skill. Rock art shows figures dancing and playing. Modern Amazigh traditions (**ahidus** and **ahwash**, collective dances and songs) have roots that go far back in time, but linking them directly to antiquity is speculation.',
  { h: '10. Science and knowledge' },
  'Numidian and Mauretanian kings took an interest in culture. **Juba II** wrote works of history, geography and botany in Greek (lost, known from quotations by Pliny the Elder). His name became linked to plants, such as **Euphorbia regis-jubae**. The Garamantes engineered the foggaras, and the herders accumulated knowledge of climate, stars and desert paths.',
  { h: '11. Technology' },
  'The great technology was the management of water and animals. The Garamantes dug **foggaras**: gently sloping tunnels with vertical access shafts, which carried water from fossil aquifers (groundwater accumulated in wetter periods) to the fields, without pumping. The dating is debated (between c. 500 BC and AD 200), as is the origin of the technique (perhaps inspired by Persian qanats, or an independent invention). Breeding small, hardy horses was another «technology», and Numidian horsemen used simple reins or no bit at all.',
  { img: 'ber-foggara-esquema', leg: 'Illustrative cross-section of a foggara: water-collecting tunnel, access shafts and channel to an oasis; not to scale. AI-generated illustration.' },
  { h: '12. War' },
  'Ancient Amazigh warfare was mainly **light cavalry**. **Numidian** horsemen rode without saddle or bridle: according to Livy and Strabo, they guided the horse with a rope or a switch and the pressure of their legs. They used javelins, a small sword and a round leather shield, and wore no armour. They attacked in loose formation, threw javelins, withdrew and returned, wearing out heavy enemy troops. They were the shock and scouting arm of Hannibal, and later of the Romans, who formed auxiliary units of Moorish cavalry that served for centuries.',
  { img: 'ber-cavaleiro-mouro', leg: 'Moorish horsemen on the relief of Trajan’s Column (2nd century AD), reproduced in The History of the World (1902). This depiction postdates the Numidian kingdoms.' },
  { img: 'ber-cavaleiro-numida-cena', leg: 'Interpretation of Numidian light cavalry during the Punic Wars, 216–202 BC, riding without saddles or bridles. AI-generated illustration.' },
  { h: 'The elephants of North Africa' },
  'Carthage and the Numidian kingdoms used **war elephants**, captured and trained in North Africa. They were smaller than today’s African savanna elephant (about 2.5 m at the shoulder, according to estimates), perhaps comparable to the forest elephant. Their classification is debated (a distinct subspecies, or not). Hannibal took them to Italy in 218 BC. At Zama the Carthaginian elephants fled in panic at the noise of the Romans. They were hunted for the Roman games and for war and became extinct in North Africa in the 4th century AD.',
  { img: 'ber-elefante-moeda', leg: 'Reverse of a Carthaginian silver shekel, c. 213–210 BC, showing an elephant; British Museum, TC,p74.42.Pan.' },
  { img: 'ber-elefante-guerra', leg: 'Artistic reconstruction of a Punic war elephant, 3rd century BC; species identification and the use of towers are uncertain. AI-generated illustration.' },
  { h: 'The Libyans and Carthage' },
  'The relationship was always one of interdependence and tension. Carthage needed land, grain and soldiers; the Libyans supplied infantry, cavalry and peasants. Carthage imposed heavy tribute (Polybius speaks of half the harvest during the First Punic War) and revolts were frequent. Punic culture, with its language, gods and urbanism, influenced the Numidians, who adopted it in cities and administration. The boundary between «Libyan» and «Carthaginian» was, in many cases, fluid.'
];

const personalidades = [
  'The sources on the ancient Amazigh were almost all written by outsiders (Egyptians, Greeks, Carthaginians, Romans), so the portraits are filtered and sometimes hostile. These are the most important figures, from the oldest to the latest; the last two belong to the epilogue.',
  { h: 'Shoshenq I, pharaoh of Libyan origin' },
  'He descended from a family of great chiefs of the **Meshwesh**, settled in Egypt for generations. He ruled c. 945–925 BC (dates vary by a few years) and founded the **22nd Dynasty**, with its capital at Bubastis in the Delta. He placed sons in key posts, including that of high priest of Amun, to control the country. Around 925 BC he campaigned in Palestine, recorded at Karnak and generally identified with the **Shishak** of the Bible. His Libyan ancestry is well documented; that his language was «Berber» is plausible but not proven.',
  { h: 'Syphax, king of the Masaesyli' },
  'He reigned c. 215–203 BC from Siga. He allied first with Rome, then with Carthage, and married **Sophonisba**, daughter of the Carthaginian general Hasdrubal Gisco. He was defeated at the Battle of the Great Plains (203 BC) and taken prisoner to Italy, where he died (c. 201 BC, at Tibur according to Livy). For some historians he is a skilful king who played the two powers against each other; for Roman sources he is a traitor. His tomb is not known.',
  { h: 'Sophonisba' },
  'Daughter of Hasdrubal Gisco, she married Syphax as part of the alliance between Carthage and the Masaesyli. Captured in 203 BC after the fall of Cirta, she married **Masinissa**, to whom she had earlier been promised. Scipio demanded that she be handed over to Rome, and Masinissa sent her poison, which she drank, according to Livy and Appian. The story is known mainly from Roman accounts and was taken up in European literature (Petrarch, Corneille and many others). Details, such as her final defiance, are of literary origin.',
  { img: 'ber-sofonisba-pintura', leg: 'Sophonisba Drinking the Poison, a painting by Giovanni Caroto.' },
  { h: 'Masinissa, the founding king' },
  'Born c. 238 BC among the **Massyli**, he was educated in Carthage. He fought for Carthage in Spain, switched to Rome’s side in 206 BC and was decisive at Zama (202 BC). King of a unified Numidia until 148 BC, he settled herders in villages, minted coins, enriched Cirta and was a faithful ally of Rome, and his pressure on Carthage ended by leading to war. According to Polybius, at 88 he could still mount a horse without a saddle. He died aged about 90, leaving a rich kingdom, a huge progeny (tradition speaks of 44 children) and a dynasty. For many Amazigh he is today a national symbol.',
  { img: 'ber-moeda-massinissa', leg: 'Bronze coin attributed to Masinissa or Micipsa, 2nd century BC, minted at Siga: diademed head and a horse on the reverse.' },
  { h: 'Micipsa' },
  'Son of Masinissa, he reigned c. 148–118 BC, first with his brothers and then alone. He kept the alliance with Rome, sent troops to Numantia and adopted his nephew **Jugurtha**; Sallust suggests he sent him to Numantia hoping he would die there. The Soumâa of El Khroub, near Constantine, is attributed by some researchers to Micipsa, but the attribution is uncertain.',
  { h: 'Jugurtha' },
  'Grandson of Masinissa and illegitimate son of Mastanabal, he was born around 160 BC. He distinguished himself at Numantia, became co-heir of Micipsa and, in 118 BC, came into conflict with his cousins. He killed Hiempsal and attacked Adherbal at Cirta (112 BC), which triggered the war with Rome (112–105 BC). According to Sallust, he said of Rome: «a city for sale, that will soon perish if it finds a buyer». He was betrayed by his father-in-law Bocchus I, paraded in Marius’s triumph and died in prison in 104 BC. Sallust made him a good soldier and a bad man, and used him to criticise the corruption of the Roman elite. The **Jugurthine War** must be read with that lens.',
  { cit: 'Urbem venalem et mature perituram, si emptorem invenerit.', fonte: 'Sallust, The War with Jugurtha, 35 (words attributed to Jugurtha on leaving Rome)' },
  { img: 'ber-denario-jugurta', leg: 'Denarius of Faustus Cornelius Sulla, c. 56 BC: Bocchus hands Jugurtha over to Sulla.' },
  { h: 'Bocchus I of Mauretania' },
  'King of Mauretania in the late 2nd century BC. He married his daughter to Jugurtha, supported him for a time and ended by handing him to Sulla in 105 BC in exchange for part of western Numidia. A famous episode of betrayal, told by Sallust. According to Plutarch, he had a sculptural group dedicated on the Capitol showing the handover.',
  { h: 'Juba I of Numidia' },
  'King of Numidia (c. 60–46 BC), he supported Pompey in the civil war and defeated Caesar’s general Curio in 49 BC. He was beaten at Thapsus (46 BC) and committed suicide. His son, Juba II, was taken to Rome as a child and appeared in Caesar’s triumph.',
  { h: 'Juba II of Mauretania' },
  'Born around 50 BC, he was raised in Rome, in the orbit of Julius Caesar and then of Augustus. Augustus made him king of Mauretania in 25 BC. He reigned until AD 23 from Caesarea. A **scholar**, he wrote in Greek on history, geography and plants, and is cited many times by Pliny the Elder. Pliny says Juba maintained (wrongly) that the Nile rose in Mauretania. He is also associated with organising purple production at Mogador and with an expedition to the «Fortunate Islands» (the Canaries), whose details are debated.',
  { img: 'ber-juba-ii-busto', leg: 'Ancient bust of Juba II, king of Mauretania; Archaeological Museum of Cherchell, Algeria.' },
  { h: 'Cleopatra Selene' },
  'Daughter of Cleopatra VII and Mark Antony, she was born c. 40 BC. After the death of her parents she was raised in Rome by Octavia, and married Juba II (c. 25–20 BC). She was queen of Mauretania and appears on coins of her own, with Egyptian symbols (the crocodile). She died c. 5 BC. They had a son, **Ptolemy**. Her figure links the world of the Ptolemies to that of the Maghreb.',
  { img: 'ber-cleopatra-selene-moeda', leg: 'Reverse of a bronze coin of Cleopatra Selene II showing a crocodile; Bibliothèque nationale de France.' },
  { h: 'Ptolemy of Mauretania' },
  'Son of Juba II and Cleopatra Selene, he was co-king from c. AD 21 and reigned alone after AD 23. In AD 40 he was summoned to Rome and executed on Caligula’s orders. The reasons are debated (envy of his purple cloak, according to Suetonius, or his wealth, according to Cassius Dio). With him the dynasty ended.',
  { h: 'Tacfarinas' },
  'A Numidian (probably a Musulamian) who served as an auxiliary in the Roman army, deserted and for seven years (AD 17–24) led a guerrilla war against Rome in Africa Proconsularis. He gathered Musulamii, Moors and other peoples, and used Roman tactics learned in service. He was defeated and died at Auzea in AD 24, according to Tacitus, throwing himself on the Roman spears. Tacitus is the main source, and sees him through Roman eyes.',
  { h: 'Tin Hinan (epilogue)' },
  'Considered by the Tuareg the «mother of us all», she has a tomb at Abalessa, in the Hoggar (Algeria), discovered in 1925. Datings to the 4th century AD fit a woman of high status buried with jewellery and Roman objects. The oral tradition is a mixture of legend and history, and the link with the present is symbolic.',
  { h: 'Dihya, the «Kahina» (epilogue)' },
  'An Amazigh chief of the late 7th century AD who, according to medieval Arab sources, led resistance in the Aurès region against the Umayyad conquest. The accounts are late and partisan, and her religion (Jewish, Christian or other) and the chronology are debated. She falls outside the period of this chapter, but is today a central figure of Amazigh memory.'
];

const legado = [
  { h: 'What they left us' },
  { lista: [
    '**An identity and a language:** Tamazight and its varieties are still spoken by millions of people, and ancient words (such as **agellid**, «king») live on in them.',
    '**A script:** the Libyco-Berber alphabet gave the Tifinagh of the Tuareg, today also an official script in Morocco.',
    '**The horsemen:** the idea of light cavalry and mobile warfare, which Rome adopted in auxiliary units.',
    '**Masinissa’s kingdom:** a state that mixed Amazigh tradition, Punic culture and Hellenistic influence.',
    '**Cultural transmission:** many place names, personal names and customs of the Maghreb, and modern Amazigh identity, derive from this continuity.',
    '**Monuments:** unique mausoleums that combine local architecture with Greek and Egyptian models.'
  ] },
  { h: 'Art' },
  'The oldest art is the **rock art** of the Sahara (Tassili n’Ajjer, Acacus). In the Numidian period there are **coins** with royal portraits and horses, votive **stelae** (such as those of Cirta and those of «African Saturn»), painted pottery and jewellery. In the Mauretania of Juba II, Hellenistic and Roman art dominates: sculptures, mosaics and royal portraits that mix Egyptian, Greek and local symbols.',
  { h: 'Architecture: the great mausoleums' },
  'The great tombs are the most original architecture. **Medracen**, near Batna (Algeria), is a tumulus of cut stone, with Doric columns and an Egyptian cornice, about 59 m in diameter and 18.5 m high. Its date is debated (radiocarbon points to the 4th–3rd century BC) and the king it was built for is unknown. The **Soumâa of El Khroub**, near Constantine, is a stone funerary monument of uncertain attribution (perhaps Micipsa), dated by Italian amphorae to the late 2nd century BC. The **Libyco-Punic mausoleum of Dougga** (21 m high, 2nd century BC, rebuilt in 1908–1910) has three storeys and a bilingual inscription. The **Royal Mausoleum of Mauretania**, near Tipasa, is a great cylinder on a square base, about 60 m wide and over 30 m high today, from the dynasty of Juba II (late 1st century BC). The Arabs called it **Kbor er Roumia**, «tomb of the Christian woman».',
  { img: 'ber-mausoleu-tipaza', leg: 'Royal Mausoleum of Mauretania near Tipasa, Algeria.' },
  { img: 'ber-medracen', leg: 'Medracen, a mausoleum near Batna, Algeria.' },
  { img: 'ber-soumaa-khroub', leg: 'Soumâa of El Khroub, a Numidian royal mausoleum near Constantine, Algeria; its attribution to a specific king is debated.' },
  { img: 'ber-mausoleu-atban', leg: 'Libyco-Punic mausoleum at Dougga, Tunisia.' },
  { h: 'Rediscovery' },
  'Ancient Amazigh culture was studied mainly from the 19th century, with colonial archaeology, which dominated the reading and left its marks (such as the removal of the Dougga inscription in 1842). Henri Lhote popularised Tassili with the 1956–57 expedition, although his work has been criticised for damaging paintings by «brightening» them. In recent decades archaeology (David Mattingly and others, on the Garamantes) and the work of Maghrebi researchers have revealed more than the ancient sources said. The western script remains undeciphered.',
  { h: 'Epilogue: after antiquity' },
  'The Roman annexation (AD 44) did not make the Amazigh disappear. There was Romanisation in the cities, Christianity (Tertullian, Cyprian and Saint Augustine lived in Roman Africa) and, from the 7th century, progressive Islamisation and Arabisation. The **Tuareg**, nomadic people of the Sahara and Sahel, kept Tifinagh and a society of their own. The **Almoravid** (11th–12th century) and **Almohad** (12th–13th century) dynasties, of Amazigh origin, governed the Maghreb and Islamic Iberia. In the 20th century Amazigh cultural movements claimed language and rights: the flag of 1970, the standardisation of Tifinagh (2003) and the official status of Tamazight in Morocco (2011) and Algeria (2016). **Yennayer**, the Amazigh New Year, is celebrated around 12–14 January (the 12th in Algeria) and has been an official holiday in Algeria since 2018 and in Morocco (decreed in 2023).',
  { img: 'ber-tuaregues', leg: 'Modern portrait of a Tuareg man wearing tagelmust in Libya.' },
  { img: 'ber-tifinagh-moderno', leg: 'Road sign for Ain Aouda in Arabic and Neo-Tifinagh, Morocco; photograph taken in October 2025.' },
  { img: 'ber-bandeira-amazigh', leg: 'Contemporary Amazigh flag: blue, green and yellow with a red yaz symbol.' },
  { caixa: 'The flag', texto: 'Created in 1970 by Mohand Arav Bessaoud (Berber Academy), the flag has three stripes (blue, green and yellow) and, in the centre, the letter **yaz** (ⵣ) in red. The **yaz** is the letter «z» of Tifinagh and stands for the word Amazigh and the «free man». It was adopted by the World Amazigh Congress in 1997.' },
  { h: 'Where to visit' },
  { lista: [
    '**Algeria:** Tassili n’Ajjer (rock art, World Heritage Site, 1982); Medracen (Batna); Soumâa of El Khroub and Constantine; Tipasa and the Royal Mausoleum; Cherchell museum; ruins of Siga.',
    '**Tunisia:** Dougga (World Heritage Site, 1997); Bulla Regia; Bardo (Tunis), with mosaics and stelae.',
    '**Morocco:** Volubilis (World Heritage Site, 1997); Lixus; museums of Rabat.',
    '**Libya:** Garama (Jarma) and the landscapes of the Fezzan; Acacus. Visiting conditions in Libya are difficult and should be checked.',
    '**Egypt:** the oasis of Siwa, temple of the oracle of Amun.',
    '**Museums:** Louvre, British Museum (bilingual inscription of Dougga), Bardo Museum (Algiers and Tunis).'
  ] }
];

const quiz = [
  { p: 'What do the peoples known as «Berbers» call themselves?', op: ['Phoenicians', 'Amazigh (plural Imazighen)', 'Tuareg only', 'Arabs of the Maghreb'], certa: 1, exp: 'Amazigh is the name they prefer, and «Berber» comes from the Greek and Latin barbarus.' },
  { p: 'Where does the word «Berber» come from?', op: ['From a Numidian tribe', 'From barbaros / barbarus, «foreigner» in Greek and Latin', 'From the name of King Masinissa', 'From the Berber desert'], certa: 1, exp: 'Greeks and Romans used barbaros for those who did not speak their language; the Arabs adopted barbar.' },
  { p: 'Which ancient script is the ancestor of the Tifinagh of the Tuareg?', op: ['Hieroglyphs', 'The Latin alphabet', 'The Libyan (Libyco-Berber) script', 'Cuneiform'], certa: 2, exp: 'Tifinagh descends from the Libyco-Berber alphabet, an abjad used since at least the 3rd century BC.' },
  { p: 'Who was Shoshenq I?', op: ['A Numidian king', 'A pharaoh of Libyan origin, founder of the 22nd Dynasty', 'A Carthaginian general', 'A king of Israel'], certa: 1, exp: 'Shoshenq I, of the Meshwesh, reigned c. 945–925 BC; he is generally identified with the biblical Shishak.' },
  { p: 'What are the foggaras of the Garamantes?', op: ['Fortresses', 'Underground channels that carried fossil water to the fields', 'Throwing weapons', 'Types of houses'], certa: 1, exp: 'Tunnels with access shafts carried groundwater to the oasis, making an urban society in the desert possible.' },
  { p: 'What was the capital of the Garamantes?', op: ['Garama (Jarma)', 'Siga', 'Volubilis', 'Cirta'], certa: 0, exp: 'Garama was in the Fezzan, in what is now south-western Libya.' },
  { p: 'How did Numidian horsemen ride, according to ancient sources?', op: ['In full armour', 'Without saddle or bridle, with a rope or switch', 'In war chariots', 'On camels'], certa: 1, exp: 'Livy and Strabo describe them guiding horses with a rope or switch and the pressure of their legs.' },
  { p: 'Which Numidian king was decisive at the Battle of Zama (202 BC)?', op: ['Syphax', 'Jugurtha', 'Masinissa', 'Juba I'], certa: 2, exp: 'Masinissa went over to Rome’s side and his cavalry attacked the rear of Hannibal’s army.' },
  { p: 'What was Masinissa’s capital?', op: ['Carthage', 'Cirta (today Constantine)', 'Siga', 'Caesarea'], certa: 1, exp: 'Cirta, in Algeria, was the capital of eastern Numidia.' },
  { p: 'Who wrote The War with Jugurtha?', op: ['Livy', 'Tacitus', 'Sallust', 'Herodotus'], certa: 2, exp: 'Sallust wrote it around 41–40 BC, also using it to criticise corruption in Rome.' },
  { p: 'Who handed Jugurtha over to the Romans in 105 BC?', op: ['Micipsa', 'Bocchus I of Mauretania', 'Juba I', 'Masinissa'], certa: 1, exp: 'Jugurtha’s father-in-law, Bocchus I, handed him to Sulla, Marius’s quaestor.' },
  { p: 'Whom did King Juba II of Mauretania marry?', op: ['Sophonisba', 'Cleopatra Selene, daughter of Cleopatra VII and Mark Antony', 'Cleopatra VII', 'Dihya'], certa: 1, exp: 'Cleopatra Selene was queen of Mauretania alongside Juba II.' },
  { p: 'What is «Kbor er Roumia»?', op: ['The Royal Mausoleum of Mauretania, near Tipasa', 'A city in Morocco', 'A Numidian god', 'A battle'], certa: 0, exp: 'It means «tomb of the Christian woman» in Arabic and is traditionally held to be the tomb of the family of Juba II.' },
  { p: 'When did the revolt of Tacfarinas take place?', op: ['112–105 BC', 'AD 17–24', '202 BC', 'AD 40–44'], certa: 1, exp: 'Tacfarinas, a former Roman auxiliary, led a guerrilla war for seven years and died in AD 24.' },
  { p: 'What does the yaz (ⵣ) on the Amazigh flag represent?', op: ['The letter «z» of Tifinagh, a symbol of «free man» and of Amazigh', 'The sun', 'A horse', 'The letter A of the Latin alphabet'], certa: 0, exp: 'It is the letter «z» of Tifinagh, associated with the name Amazigh and the idea of freedom.' }
];

export default { visao, linha, mapa, sociedade, personalidades, legado, quiz };
