// THE HIGH EMPIRE (27 BC – AD 192) — full English content. Same structure and same image slots as the Portuguese version (dados.js).
// Conventional dates (Principate of Augustus in 27 BC; death of Commodus on 31 December AD 192). Figures (population, troop numbers, casualties) are estimates.

const visao = [
  { caixa: 'In brief', texto: [
    'The **High Empire** (or **Principate**) is the period in which Rome, already mistress of the Mediterranean, stopped being a republic ruled by annual magistrates and came to be ruled by a **princeps**, the “first citizen”, whom tradition calls the **emperor**. It begins in **27 BC**, when the Senate gave Octavian the name **Augustus**, and ends by convention in **AD 192** with the assassination of Commodus, followed by civil war.',
    'It was more than two centuries in which the Empire reached its greatest extent (in AD 117, under Trajan), built the Colosseum, the Pantheon and the wall across northern England, and enjoyed what is called the **Pax Romana**: a relative peace within, imposed by the legions on the frontiers. It was also when **Lusitania**, the territory of today’s Portugal south of the Douro and western Spain, was organised around cities such as Mérida (the capital), Olisipo (Lisbon), Pax Iulia (Beja) and Aeminium (Coimbra).'
  ] },
  { img: 'rai-augusto-prima-porta', leg: 'Augustus of Prima Porta, Vatican Museums.' },
  { h: 'From the end of the Republic to the Principate' },
  'The Late Republic ended in civil wars (see the page “The Late Republic”). Octavian, great-nephew and adopted son of Caesar, defeated Mark Antony and Cleopatra at **Actium (31 BC)** and was left without a rival. Instead of declaring himself king, a word hated in Rome since the expulsion of the Tarquins, he presented himself as the man who was **“restoring the Republic”**. In practice he gathered into his hands the military command, the money and foreign policy, keeping the Senate, the consuls and the elections as a façade or, as some historians prefer, as subordinate partners. This ambiguity, a monarchy that did not speak its name, was Augustus’s most lasting political invention.',
  { img: 'rai-mapa-imperio', leg: 'Roman Empire in AD 117, at its greatest extent.' },
  { h: 'Where and when' },
  { tabela: { cab: ['Phase', 'Dates', 'Emperors', 'Main features'], linhas: [
    ['Augustus', '27 BC – AD 14', 'Augustus', 'Foundation of the Principate; professional army; end of the civil wars; conquest of northern Hispania and the Alps; disaster of Teutoburg (AD 9)'],
    ['Julio-Claudians', 'AD 14 – 68', 'Tiberius, Caligula, Claudius, Nero', 'Consolidation and court crises; conquest of Britain (43); fire of Rome (64); end of Augustus’s family'],
    ['Year of the Four Emperors', 'AD 68 – 69', 'Galba, Otho, Vitellius, Vespasian', 'Civil war: it becomes clear that an emperor can be made outside Rome'],
    ['Flavians', 'AD 69 – 96', 'Vespasian, Titus, Domitian', 'Repair of the finances; Jewish War; Colosseum; eruption of Vesuvius (79); authoritarian reign of Domitian'],
    ['Antonines (adoptive)', 'AD 96 – 180', 'Nerva, Trajan, Hadrian, Antoninus Pius, Marcus Aurelius (and Lucius Verus)', 'Succession by adoption; territorial peak (117); frontiers fixed; wars and plague under Marcus Aurelius'],
    ['Commodus', 'AD 180 – 192', 'Commodus', 'Succession by birth; erratic rule; assassinated on 31 December 192']
  ] } },
  'The space is that of the **whole Mediterranean** (*Mare Nostrum*, “our sea”) and the lands around it: from Britain to Egypt, from Hispania to northern Mesopotamia, briefly. Some **50 to 70 million people** (an estimate that varies between authors) lived under Roman rule in Trajan’s time, over an area of about 5 million km².',
  { img: 'rai-res-gestae', leg: 'Detail of the Greek version of the Res Gestae at the Temple of Rome and Augustus, Ankara.' },
  { h: 'The Pax Romana' },
  'The phrase **Pax Romana**, “Roman peace”, describes the long absence of civil war between Actium (31 BC) and the death of Marcus Aurelius (AD 180), apart from 68–69. It was not absolute peace: there were campaigns of conquest, revolts (Judaea, Britain, Pannonia, Germany) and frontier wars. But inside the Empire merchants and travellers could move from one end to the other along patrolled roads and seas free of pirates. An ancient historian, Tacitus, puts a famous line into the mouth of a British chief, Calgacus: *“They make a desert and call it peace.”* The speech was written by Tacitus himself, not recorded live: it shows that there were Romans aware of the price of that peace.',
  { img: 'rai-ara-pacis', leg: 'Ara Pacis Augustae, Rome (9 BC).' },
  { h: 'What changed from the Republic' },
  { lista: [
    '**A single head:** supreme power rested in the hands of one man, and the succession became the central problem of the regime.',
    '**A permanent, paid army:** instead of citizens mobilised in wartime, professional legions with 20 or more years of service, stationed along the frontiers.',
    '**An administration for the Empire:** governors, procurators, prefects, a bureaucracy of knights and imperial freedmen, in place of the plundering of Republican governors.',
    '**Provincials with a voice:** Gauls, Hispanics and Africans entered the Senate; by the second century the emperor was already a son of a province (Trajan and Hadrian’s family came from Italica, in Hispania).',
    '**Peace and urbanisation:** new cities, roads, aqueducts and baths across the territory.'
  ] },
  { h: 'Sources and cautions' },
  'We know the High Empire from **ancient historians** (Tacitus, Suetonius, Cassius Dio, Josephus, Pliny the Younger), from **inscriptions, coins and papyri**, and from **archaeology**. But most authors were of senatorial or equestrian origin, wrote for the elite and often after the death of the emperor they describe. Suetonius and Tacitus are severe on Tiberius, Caligula, Nero and Domitian, and it is hard to separate fact from scandal. In this text, when something is rumour or tradition, it says so.',
  { caixa: 'Why the High Empire matters', texto: 'It was the time when the Roman Empire was **strongest, largest and most cohesive**. The law, the Latin language, the cities, the roads and many monuments we still see in Europe, North Africa and the Middle East date from this period. It was also when **Christianity** was born and spread, and when the Jewish people were struck by two wars and the destruction of the Temple of Jerusalem. Even today, much of our idea of “Rome” is that of Augustus, Trajan and Hadrian.' },
  { img: 'rai-provincias-esquema', leg: 'Cartographic diagram for c. AD 125–130, adapted from a map of AD 125: imperial provinces in terracotta, senatorial provinces in ochre and Italy in a neutral tone; approximate roads and frontiers.' },
  { h: 'The High Empire today' },
  'From this age survive the **Pantheon** (still in use as a church), the **Colosseum**, **Trajan’s Column**, **Hadrian’s Wall** (World Heritage), bridges and aqueducts such as the **Alcántara bridge** or the **Segovia aqueduct**, and entire cities, like **Pompeii**, preserved by the eruption of Vesuvius. In Portugal you can visit **Conímbriga**, the **Roman temple of Évora**, the **Roman ruins of Tróia**, the **Roman theatre of Lisbon** and those of **Miróbriga**, **Mértola** and **Ammaia**.'
];

const linha = [
  'This timeline covers more than two centuries. For this period dates are generally firm (reign lengths and many exact dates are known); disputed ones are flagged.',
  { img: 'rai-forum-augusto', leg: 'AI-generated illustration. Forum of Augustus, c. 2 BC: artistic interpretation.' },
  { linha: [
    { d: '27 BC', t: 'Augustus and the “restoration of the Republic”', x: 'On 13 January Octavian formally hands his extraordinary powers back to the Senate; three days later, on 16 January, the Senate gives him the name **Augustus** (“worthy of reverence”) and entrusts him, for ten years, with the provinces where the legions were. The date is the conventional start of the Principate.' },
    { d: '23 BC', t: 'The second settlement', x: 'Augustus gives up the annual consulship and keeps the *imperium proconsulare maius* (authority superior to that of governors) and the **tribunicia potestas** (tribunician powers): the legal basis of his power for the rest of his life.' },
    { d: '29 – 19 BC', t: 'End of the Cantabrian Wars', x: 'The campaigns in northern Hispania end after years of war against the Cantabri and Astures. **Lusitania** is organised as a province; **Augusta Emerita** (Mérida) is founded in 25 BC for veterans.' },
    { d: '12 BC – AD 9', t: 'Offensive in Germany', x: 'Drusus and Tiberius advance to the Elbe. In **September AD 9**, three legions (XVII, XVIII and XIX) under Publius Quinctilius Varus are annihilated in the **Teutoburg Forest** by Arminius. Augustus gives Germany up for lost and fixes the frontier on the Rhine.' },
    { d: 'AD 6', t: 'Military treasury and watchmen', x: 'The **aerarium militare** (a fund to pay soldiers’ pensions) and the **vigiles**, Rome’s fire brigade and night police, are created.' },
    { d: 'AD 14', t: 'Death of Augustus', x: 'Augustus dies at **Nola** on 19 August, aged 75. Tiberius, his adopted son, succeeds him. The pattern of the regime is set: the emperor designates and adopts his successor.' },
    { d: 'AD 14 – 37', t: 'Tiberius', x: 'A reign prudent at first, then gloomy. In 26 he retires to Capri; in **31** falls the Praetorian prefect Sejanus, to whom Tiberius had entrusted power in Rome. In this reign Jesus of Nazareth is executed in Judaea under the prefect Pontius Pilate (c. 30 or 33, debated).' },
    { d: 'AD 37 – 41', t: 'Caligula', x: 'A popular young man at first, then authoritarian and erratic in the accounts of Suetonius and Dio (who write long afterwards and are hostile). He is assassinated by his own Praetorian Guard on 24 January 41.' },
    { d: 'AD 41 – 54', t: 'Claudius and the conquest of Britain', x: 'Proclaimed emperor by the Praetorians, Claudius gives the state an effective bureaucracy, builds the harbour at Ostia and in **43** orders the **invasion of Britain**. The conquest of the island is slow and will last decades. He dies in 54, perhaps poisoned (tradition, without proof).' },
    { d: 'AD 64', t: 'Great Fire of Rome', x: 'In July a fire devastates Rome: according to Tacitus, three of the fourteen regions are completely destroyed and seven badly damaged. Tacitus says Nero blamed the Christians, who were persecuted. There is **no evidence** that Nero “played the lyre” watching the city burn: it is a later legend.' },
    { d: 'AD 66 – 73/74', t: 'The Great Jewish Revolt', x: 'The revolt of Judaea against Roman rule is crushed by Vespasian and then Titus. In **70** Jerusalem falls and the **Temple** is destroyed. The fortress of **Masada** falls in 73 or 74 (date debated). The main source is Flavius Josephus.' },
    { d: 'AD 68 – 69', t: 'Year of the Four Emperors', x: 'Nero commits suicide on 9 June 68 after the governors’ revolt. There follow **Galba** (murdered), **Otho** (suicide), **Vitellius** (killed in Rome) and finally **Vespasian**, acclaimed in the East.' },
    { d: 'AD 69 – 79', t: 'Vespasian, founder of the Flavians', x: 'He puts the finances in order, begins the **Flavian Amphitheatre** (Colosseum) and the **Temple of Peace**. He dies on 23 June 79.' },
    { d: 'AD 79', t: 'Eruption of Vesuvius', x: 'The eruption destroys **Pompeii**, **Herculaneum**, Stabiae and other settlements on the Bay of Naples. The traditional date is **24 August**, but a charcoal graffito found in Pompeii in 2018, dated “16 days before the Kalends of November” (17 October), suggests it happened later, in autumn. The debate is open.' },
    { d: 'AD 80', t: 'Inauguration of the Colosseum', x: 'Titus inaugurates the **Flavian Amphitheatre** with a hundred days of games, according to Cassius Dio. Domitian adds the top storey and the underground galleries.' },
    { d: 'AD 81 – 96', t: 'Domitian', x: 'Efficient, authoritarian government, in which, in hostile sources, he has himself addressed as “lord and god”. Wars on the Danube against the Dacians. He is assassinated in a court conspiracy on 18 September 96; the Senate decrees *damnatio memoriae*.' },
    { d: 'AD 96 – 98', t: 'Nerva and adoption', x: 'An elderly emperor chosen by the Senate. In 97 (traditionally October) he adopts **Trajan**, a general in Germany, to protect himself from a Praetorian revolt. The “Antonine dynasty” begins (so called although none of these successions was from father to son until Commodus).' },
    { d: 'AD 101 – 106', t: 'The Dacian Wars', x: 'Trajan defeats King **Decebalus** in two campaigns and annexes **Dacia** (modern Romania) in 106. Dacian gold pays for Trajan’s buildings. It is the last great permanent conquest.' },
    { d: 'c. AD 112–113', t: 'Trajan’s Column', x: 'Dedication (112 or 113, depending on the source) of the column that tells the story of the Dacian wars in a spiral frieze, in Trajan’s Forum in Rome.' },
    { d: 'AD 114 – 117', t: 'Eastern campaign and peak', x: 'Trajan invades the Parthian Empire and reaches the Persian Gulf; this is the **greatest extent** of the Empire. The conquests beyond the Euphrates break out in revolts; Trajan dies at Selinus in Cilicia in August 117, and **Hadrian** abandons them.' },
    { d: 'AD 122', t: 'Hadrian’s Wall', x: 'Hadrian orders in Britain a wall about 117 km (80 Roman miles) long between the Tyne and the Solway. It marks a policy of **consolidating** rather than conquering.' },
    { d: 'AD 132 – 135', t: 'Bar Kokhba revolt', x: 'The last great Jewish revolt in Judaea, crushed with heavy losses. Jerusalem becomes **Aelia Capitolina**, a Roman city closed to Jews. (Whether the foundation of Aelia, around 130, came before or after the revolt is debated.)' },
    { d: 'c. AD 142', t: 'The Antonine Wall', x: 'Antoninus Pius has a second barrier built in Scotland, of turf and earth, between the Forth and the Clyde. It was abandoned in the 160s.' },
    { d: 'AD 165 – 180', t: 'Antonine Plague and the Danube wars', x: 'An epidemic brought by troops from the Parthian campaign (probably smallpox, but this is not certain) devastates the Empire. At the same time Marcus Aurelius fights the **Marcomannic Wars** on the Danube. He dies in 180, at Vindobona (Vienna) or Sirmium (debated).' },
    { d: 'AD 180 – 192', t: 'Commodus', x: 'Son of Marcus Aurelius, he is the first emperor to succeed his biological father since Titus. He governs badly, devotes himself to the arena and is assassinated on **31 December 192**. The “Year of the Five Emperors” (193) follows: see the page “Crisis, Dominate and Fall”.' }
  ] },
  { img: 'rai-tiberio-busto', leg: 'Bust of Tiberius, Ny Carlsberg Glyptotek, Copenhagen.' },
  { img: 'rai-caligula-busto', leg: 'Bust of Caligula, Ny Carlsberg Glyptotek, Copenhagen.' },
  { img: 'rai-incendio-64', leg: 'AI-generated illustration. Great Fire of Rome, AD 64: artistic interpretation.' },
  { img: 'rai-arco-tito', leg: 'Menorah relief in the Arch of Titus, Roman Forum.' },
  { img: 'rai-erupcao-vesuvio', leg: 'AI-generated illustration. Eruption of Vesuvius over Pompeii, AD 79: artistic interpretation.' },
  { img: 'rai-coluna-trajano', leg: 'Trajan’s Column, Rome (AD 113).' },
  { img: 'rai-muralha-adriano', leg: 'Hadrian’s Wall near Housesteads, Northumberland.' }
];

const mapa = [
  'The High Empire was a network of **cities** linked by roads and sea routes. This section presents the main places of the period: the capital, the cities of Italy, those of the provinces, the frontiers, the battlefields and the routes, with special attention to Lusitania, the province that covered what is now Portugal.',
  { tabela: { cab: ['Place', 'Roman name', 'Province / region', 'Why it matters'], linhas: [
    ['Rome', 'Roma', 'Italy', 'Capital; the emperor’s residence; about a million inhabitants (estimate)'],
    ['Ostia / Portus', 'Ostia; Portus', 'Italy (Latium)', 'Ports of Rome, enlarged by Claudius and Trajan'],
    ['Pompeii', 'Pompeii', 'Italy (Campania)', 'City buried by Vesuvius in 79'],
    ['Herculaneum', 'Herculaneum', 'Italy (Campania)', 'Also buried; preserved wood and organic objects'],
    ['Lyon', 'Lugdunum', 'Gallia Lugdunensis', 'Capital of the Gauls; Claudius was born here'],
    ['Cologne', 'Colonia Claudia Ara Agrippinensium', 'Lower Germany', 'City on the Rhine frontier, founded in AD 50'],
    ['London', 'Londinium', 'Britain', 'Founded shortly after 43; commercial capital of Britain'],
    ['Vindolanda', 'Vindolanda', 'Britain', 'Fort near Hadrian’s Wall; wooden tablets with letters'],
    ['Carnuntum', 'Carnuntum', 'Pannonia', 'Military base on the Danube; Marcus Aurelius’s headquarters in 172–173'],
    ['Sarmizegetusa', 'Colonia Ulpia Traiana Sarmizegetusa', 'Dacia', 'Roman capital of Dacia, founded by Trajan'],
    ['Alexandria', 'Alexandria', 'Egypt', 'Second city of the Empire; Library; grain port'],
    ['Antioch', 'Antiochia', 'Syria', 'Third city of the Empire; base of operations in the East'],
    ['Ephesus', 'Ephesus', 'Asia', 'Capital of the province of Asia; Library of Celsus (c. 114–135)'],
    ['Jerusalem / Aelia Capitolina', 'Hierosolyma; Aelia Capitolina', 'Judaea / Syria Palaestina', 'Destroyed in 70; refounded by Hadrian'],
    ['Palmyra', 'Palmyra', 'Syria', 'Caravan city in the desert, annexed to Syria in the first century'],
    ['Leptis Magna', 'Leptis Magna', 'Africa', 'Punic-Roman city that grew greatly under the Antonines and then the Severans'],
    ['Carthage', 'Colonia Iulia Concordia Carthago', 'Africa Proconsularis', 'Refounded by Augustus; centre of the African grain trade'],
    ['Mérida', 'Augusta Emerita', 'Lusitania', 'Capital of Lusitania, founded in 25 BC'],
    ['Lisbon', 'Olisipo (Felicitas Iulia)', 'Lusitania', 'Roman municipality; port on the Tagus'],
    ['Beja', 'Pax Iulia', 'Lusitania', 'Colony from the time of Augustus (or Caesar), in the Alentejo'],
    ['Braga', 'Bracara Augusta', 'Hispania Citerior (Tarraconensis)', 'Founded c. 16–13 BC; capital of a district in the north-west'],
    ['Coimbra / Conímbriga', 'Aeminium / Conimbriga', 'Lusitania', 'Conímbriga: the largest known Roman site in Portugal']
  ] } },
  { h: 'Rome: capital of the Empire' },
  'Augustus, according to Suetonius, boasted that he had found Rome brick and left it marble. It was a half truth, but true in spirit: he built the Forum of Augustus, the Theatre of Marcellus and the Mausoleum, reorganised the city into **14 regions** and created the fire brigade of the *vigiles*. The city had **800,000 to a million inhabitants** (estimates), the great majority in **insulae**, multi-storey apartment blocks with a constant danger of fire and collapse. After the fire of 64 Nero rebuilt with safety rules; the Flavians added the **Colosseum** and the **Temple of Peace**, and Trajan his **forum and markets**.',
  { img: 'rai-roma-trajano', leg: 'AI-generated illustration. Trajan’s Forum, c. AD 115: artistic interpretation.' },
  { img: 'rai-coliseu', leg: 'Colosseum (Flavian Amphitheatre), Rome.' },
  { h: 'Ostia and Portus: the port of Rome' },
  'Rome imported much of its grain. The port of **Ostia**, at the mouth of the Tiber, was insufficient; **Claudius** had the great artificial harbour of **Portus** built, which **Trajan** enlarged with a hexagonal basin (c. 100–112). Ostia, today one of the richest archaeological sites, shows apartment blocks, baths, taverns, warehouses and a theatre, and lets us see what urban life was like in a medium-sized Roman city.',
  { img: 'rai-ostia-porto', leg: 'AI-generated illustration. Portus and Trajan’s hexagonal harbour, c. AD 110: artistic interpretation.' },
  { h: 'Pompeii and Herculaneum' },
  'Two cities in Campania buried by Vesuvius in 79. **Pompeii** (between 10 and 20 thousand inhabitants, an estimate) was covered by ash and pumice; **Herculaneum**, smaller and wealthier, by pyroclastic flows, which carbonised wood, food and even papyri, still being read today. They are not “cities frozen in time”: Pompeii had already been shaken by an earthquake in 62 or 63 and was under repair. The skeletons and plaster casts of the victims show the moment of death; the graffiti and the taverns show the daily life of a provincial town.',
  { img: 'rai-pompeia-vesuvio', leg: 'Pompeii ruins with Vesuvius in the background.' },
  { h: 'Lugdunum, Cologne and the cities of Gaul and Germany' },
  '**Lugdunum** (Lyon), founded in 43 BC, was the capital of the Gauls; there the cult of Rome and Augustus was celebrated and Claudius was born. **Cologne** (Colonia Claudia Ara Agrippinensium) was raised in AD 50 to the status of a colony at the request of Agrippina, Claudius’s wife, who had been born there. Both were trading ports and bases for the defence of the Rhine.',
  { h: 'Londinium and Britain' },
  'Britain was conquered after **43**, and only in part: northern Scotland was never integrated, despite Agricola’s victory at **Mons Graupius** (c. 83 or 84). **Londinium** began as a trading settlement and was destroyed by Boudicca in 60 or 61, queen of the Iceni, in revolt against Roman abuses; it was then rebuilt and became the largest city on the island. **Eboracum** (York) and **Deva** (Chester) were legionary bases.',
  { h: 'Hadrian’s Wall and the frontier forts' },
  'In Hadrian’s time the northern frontier of Britain had a **wall** of stone and turf with **forts**, **milecastles** (one every Roman mile) and **watchtowers**. Nearby, at **Vindolanda**, excavations found hundreds of **wooden tablets** with letters, supply lists and even a birthday invitation written by a woman, Claudia Severa, to Sulpicia Lepidina, c. AD 100.',
  { img: 'rai-limes-forte', leg: 'AI-generated illustration. Fort on Hadrian’s Wall, c. AD 130: artistic interpretation.' },
  { h: 'The Danube and Dacia' },
  'The Danube was the most dangerous frontier. At **Carnuntum**, in Pannonia, Marcus Aurelius set up his headquarters and wrote, according to notes in the text itself, parts of the *Meditations* during the campaigns against the Marcomanni and the Quadi. At **Sarmizegetusa**, in the heart of Dacia, Trajan founded the capital of the new province, after the fall of King Decebalus’s capital, **Sarmizegetusa Regia**, in the mountains. Near Adamclisi (in today’s Romania) stands the monument commemorating a victory of Trajan over the Dacians, the **Tropaeum Traiani**, of the year 109.',
  { h: 'The East: Alexandria, Antioch, Ephesus, Palmyra' },
  '**Alexandria** was the greatest city of the East and the port of Egyptian grain, with Jews, Greeks and Egyptians in tension; in 115–117 there was a brutal Jewish revolt there. **Antioch** was the base for campaigns against the Parthians. **Ephesus** was capital of the province of Asia and has the **Library of Celsus** (built c. 114–135). **Palmyra**, in the Syrian desert, grew rich on the caravans and, in the following age, became an independent kingdom.',
  { h: 'Jerusalem and Judaea' },
  'Judaea was annexed as a province in **AD 6**, governed by prefects (later procurators). The **Great Revolt (66–73/74)** ended with the destruction of the Temple (70); that of **Bar Kokhba (132–135)** with the refounding of Jerusalem as **Aelia Capitolina**. The number of victims and the length of the ban on Jews are debated; the main sources are Josephus (for the first) and Cassius Dio (for the second, less reliable).',
  { h: 'Mérida, capital of Lusitania' },
  '**Augusta Emerita** was founded in **25 BC** for the veterans of the Cantabrian wars, on the river Guadiana, and became capital of the province of **Lusitania**. It preserves one of the most important Roman ensembles of the Peninsula: the **theatre** (inaugurated around 16–15 BC, in Agrippa’s time), the **amphitheatre**, the 792 m **bridge** over the Guadiana, the circus and several aqueducts. A UNESCO World Heritage Site.',
  { img: 'rai-teatro-merida', leg: 'Roman theatre of Mérida (Augusta Emerita).' },
  { h: 'Olisipo and Atlantic Lusitania' },
  '**Olisipo** (Lisbon) received the title **Felicitas Iulia**, probably in the time of Augustus (or Caesar), and was a municipality of Roman citizens. It preserves the **Roman theatre** at the foot of the castle, built in Augustus’s time and bearing an inscription of **AD 57** (Nero’s reign) that records works on the building. It was a port exporting **salted fish and *garum*** (fish sauce), olive oil and wine. **Scallabis** (Santarém), **Pax Iulia** (Beja), **Ebora** (Évora), **Myrtilis** (Mértola), **Salacia** (Alcácer do Sal) and **Aeminium** (Coimbra) were other cities of the province.',
  { img: 'rai-olisipo', leg: 'AI-generated illustration. Olisipo in the second century AD: conjectural view: artistic interpretation.' },
  { h: 'Conímbriga and Évora' },
  '**Conímbriga** (municipality of Condeixa-a-Nova) was a city of Lusitania whose importance grew under the Flavians, when it received a new forum and the status of municipality; it keeps magnificent **mosaics**, the **House of the Fountains** and baths. The **Roman temple of Évora** (first century AD, traditionally called “of Diana”, a name with no ancient basis, from the seventeenth century) is the most remarkable Roman monument of the Alentejo.',
  { img: 'rai-conimbriga-mosaicos', leg: 'Mosaic detail in the House of the Fountains, Conímbriga.' },
  { img: 'rai-templo-evora', leg: 'Roman temple of Évora, traditionally called the Temple of Diana.' },
  { h: 'The Alcántara bridge and the roads of Hispania' },
  'The **Alcántara bridge** (river Tagus, Spain, next to the Portuguese border) was built between 103 and 106 under Trajan, and the inscription credits the work to an engineer, **Gaius Julius Lacer**. The **Via Augusta** linked Cádiz with the Pyrenees; the **Via Nova** (c. 79–80, Vespasian and Titus) linked Braga with Astorga; the roads of Lusitania linked Mérida with Olisipo, Pax Iulia and Bracara. The milestones, still found today in the Minho and the Alentejo, record the emperors who had them repaired.',
  { img: 'rai-ponte-alcantara', leg: 'Roman Alcántara Bridge over the Tagus, Spain.' },
  { h: 'The battlefields' },
  { lista: [
    '**Teutoburg / Kalkriese (AD 9):** an ambush that annihilated three legions; the exact site is debated, with Kalkriese (near Osnabrück) a strong candidate.',
    '**Bedriacum (AD 69):** two battles near Cremona decided the civil war between Otho, Vitellius and Vespasian.',
    '**Jerusalem (AD 70) and Masada (73/74):** the final points of the Great Jewish Revolt.',
    '**Mons Graupius (c. 83/84):** Agricola’s victory in Scotland, told by Tacitus, his son-in-law.',
    '**Tapae (AD 88 and 101):** battles of the Dacian wars.',
    '**Ctesiphon (116):** the Parthian capital, taken by Trajan.'
  ] },
  { h: 'The routes' },
  'Roman **roads** totalled about **80,000 km paved** (an estimate; the whole network, with dirt tracks, would be larger), with **milestones** and relay stations for changing horses on the **cursus publicus**, the imperial post established by Augustus. At sea, **navigation** was open from March to November; in midwinter most ships stayed in port. From Egypt came the grain fleets; from the Red Sea, the route to India (described in the *Periplus of the Erythraean Sea*, first century) brought pepper, silk and pearls.'
];

const sociedade = [
  'This section describes how the High Empire was governed and how people lived: power, classes, the army, the economy, religion, law, the home, the table, the spectacle. Attention is given to changes from the Republic and to what we still recognise today.',
  { h: 'The princeps and his powers' },
  'Augustus was never “king” or “dictator”. His title was **princeps** (“the first”), and his power, legally, came from **accumulated Republican powers**: the proconsular *imperium* (command over armies and provinces), the *tribunicia potestas* (inviolability and the right of veto), the censorship and the office of **chief priest** (*pontifex maximus*, from 12 BC). What gave substance to all this was ***auctoritas***: personal prestige. The word **imperator**, which meant “victorious commander”, only later became the title of the ruler. The following emperors inherited the whole package, more and more explicitly; a document from Vespasian’s time, the *lex de imperio Vespasiani*, lists the emperor’s powers in a law voted by the Senate.',
  { tabela: { cab: ['Emperor', 'Reign', 'Dynasty / how he came to power'], linhas: [
    ['Augustus', '27 BC – AD 14', 'Julio-Claudians; adopted son of Caesar'],
    ['Tiberius', 'AD 14 – 37', 'Julio-Claudians; adopted son of Augustus'],
    ['Caligula', 'AD 37 – 41', 'Julio-Claudians; great-nephew of Tiberius; assassinated'],
    ['Claudius', 'AD 41 – 54', 'Julio-Claudians; proclaimed by the Praetorian Guard'],
    ['Nero', 'AD 54 – 68', 'Julio-Claudians; adopted son of Claudius; committed suicide'],
    ['Galba', 'AD 68 – 69', 'Acclaimed in Hispania; assassinated'],
    ['Otho', 'AD 69 (Jan.–Apr.)', 'Backed by the Praetorians; committed suicide'],
    ['Vitellius', 'AD 69 (Apr.–Dec.)', 'Acclaimed by the legions of the Rhine; killed'],
    ['Vespasian', 'AD 69 – 79', 'Flavians; acclaimed in the East'],
    ['Titus', 'AD 79 – 81', 'Flavians; son of Vespasian'],
    ['Domitian', 'AD 81 – 96', 'Flavians; brother of Titus; assassinated'],
    ['Nerva', 'AD 96 – 98', 'Chosen by the Senate; adopted Trajan'],
    ['Trajan', 'AD 98 – 117', 'Adopted by Nerva; born in Italica (Hispania)'],
    ['Hadrian', 'AD 117 – 138', 'Relative and ward of Trajan (adoption disputed)'],
    ['Antoninus Pius', 'AD 138 – 161', 'Adopted by Hadrian'],
    ['Marcus Aurelius', 'AD 161 – 180', 'Adopted by Antoninus; ruled with Lucius Verus until 169'],
    ['Commodus', 'AD 180 – 192', 'Son of Marcus Aurelius; assassinated']
  ] } },
  { h: 'Succession: the weak point' },
  'There was no constitutional rule of succession. Augustus tried to make relatives his heirs and ended up adopting Tiberius. The Julio-Claudians kept the dynastic principle until Nero; after 68 it was realised that **an emperor could be made outside Rome**, by a frontier army. The Antonines solved the problem for almost a century by **adopting** the best candidate; this was luck, not a rule. When Marcus Aurelius preferred his biological son, Commodus, the system failed.',
  { h: 'The Senate, the knights and the freedmen' },
  'The **Senate** lost real power but gained prestige and went on supplying the governors of the older provinces, the commanders of legions and the consuls. The **equestrian order** (the *equites*, knights, who had to have a fortune of at least 400,000 sesterces) supplied administrators: procurators, commanders of auxiliary cohorts, the **prefect of Egypt** and the **praetorian prefect**. Claudius and later emperors gave great power to **imperial freedmen** (the emperor’s former slaves) who ran the finance and correspondence offices. By the end of the first century, and above all in the second, the Senate was increasingly filled with **provincials**.',
  { h: 'The Praetorian Guard' },
  'The **Praetorian Guard**, organised by Augustus in nine cohorts and concentrated by Tiberius in Rome, in the *Castra Praetoria* (c. AD 23), was the main permanent armed force in Italy. It had better pay and service terms than the legions. It made and unmade emperors: it assassinated Caligula, proclaimed Claudius, backed Otho, demanded the punishment of Domitian’s assassins in 97.',
  { h: 'Provinces and governors' },
  'The Empire was divided into **more than forty provinces**. The **senatorial** ones (pacified, without legions, such as Baetica) were governed by *proconsuls* chosen by lot in the Senate for one year. The **imperial** ones (frontiers and provinces with legions, such as Hispania Tarraconensis, Syria or Britain) were governed by *legati Augusti* appointed by the emperor for several years. **Egypt** was a special case: governed by an equestrian prefect, and senators needed imperial permission to enter, because it was Rome’s granary and the emperor’s personal province. **Lusitania** was an imperial province, with a legate at Mérida.',
  { img: 'rai-mercados-trajano', leg: 'Markets of Trajan, Rome.' },
  { h: 'Taxes, census and administration' },
  'The Empire lived on taxes on **land** (*tributum soli*) and on the **person** (*tributum capitis*) in the provinces, on customs duties (2 to 5 % of the value of goods, depending on the region) and on the sale of slaves, and, for the citizens of Rome, on inheritance (5 %) and sales taxes. A periodic **census** was held in each province to find out who paid and how much. The Republic’s tax collectors, the *publicani*, were largely replaced by imperial officials.',
  { h: 'Citizenship and cities' },
  'The Empire was a network of **cities** of various statuses: **colonies** (founded for veterans), **municipalities** (local cities with Roman or Latin rights) and **peregrine** cities, of people without citizenship. Emperors granted citizenship to cities and to individuals. Vespasian gave **Latin rights** to the whole of Hispania (c. 73–74), which made the cities of Lusitania municipalities with Roman magistrates and laws. Only in **212**, under Caracalla, was citizenship given to most free inhabitants (the *Constitutio Antoniniana*), already outside the period of this page.',
  { h: 'The social classes' },
  { lista: [
    '**Senators:** about six hundred, with a minimum fortune of one million sesterces; they wore the tunic with a broad purple stripe (*latus clavus*).',
    '**Knights:** fortune of 400,000 sesterces; narrow purple stripe; officials and businessmen.',
    '**Decurions:** councillors and magistrates of the towns, the elites of the cities.',
    '**Plebs:** ordinary free citizens, from peasants to craftsmen; in Rome many lived on “bread and circuses”.',
    '**Freedmen:** former slaves; they could grow rich (Petronius satirised the wealthy Trimalchio) but could not hold public office; their children were already free.',
    '**Slaves:** perhaps 10 to 20 % of the Empire’s population (an estimate), most of them in Italy and on large estates; they worked in houses, fields, mines, workshops and as gladiators.'
  ] },
  { h: 'Slavery' },
  'Slaves were **property**: prisoners of war, children of slave women, abandoned children, or victims of piracy and debt. Their fate varied greatly: in the house of a rich master a cultivated slave, doctor or secretary, had a far better life than a mine slave, who worked until death. The law became slightly more protective: Hadrian forbade selling slaves to gladiator trainers and to brothels without cause and took away masters’ right to kill them; Antoninus Pius punished a master who killed a slave without cause. But slavery was never questioned as an institution. There was no slave revolt on a scale comparable to that of Spartacus during the High Empire.',
  { h: 'Women and family' },
  'The **family** (*familia*) was headed by the **father** (*pater familias*), with legal power over his children and slaves. In practice the power had limits: women of the elite inherited property, managed estates and had great indirect political influence, like **Livia**, Augustus’s wife. Women could not vote or hold magistracies. Elite girls were generally married at 12 to 15 to older men; divorce was easy. Augustus promoted marriage and births by law (*lex Iulia de maritandis ordinibus*, 18 BC, and *lex Papia Poppaea*, AD 9), with penalties for the unmarried and rewards for families with three children (*ius trium liberorum*).',
  { h: 'Rome: bread and circuses' },
  'In Rome, the emperor was responsible for feeding the people (the **annona**): some 150 to 200 thousand citizens received a free or cheap grain ration; Juvenal summed up the politics of the plebs as “**bread and circuses**” (*panem et circenses*), in Satire X, as a criticism. The games were the work of the emperor and the magistrates: they were part of the **legitimation** of power. The calendar had more than a hundred days of festivals and games a year in the second century (the figures vary according to the calendars that survive).',
  { img: 'rai-insula', leg: 'AI-generated illustration. Roman street with insulae, second century AD: artistic interpretation.' },
  { h: 'Living in an insula' },
  'Most poor and middling Romans lived in **insulae**, apartment blocks of brick and wood that could have five or six storeys. The lower floors were better (and dearer); the upper ones, hotter and more exposed to fire, were cheapest. There was no running water on the upper floors: people fetched it from the public fountain. A law of Augustus limited building height (c. 21 m, later reduced by Trajan to about 18 m). Fires were frequent, which led to the creation of the *vigiles*.',
  { h: 'The circus, the theatre and the amphitheatre' },
  'Three kinds of spectacle. In the **Circus Maximus**, **chariot races** (two-horse and four-horse), with four teams (the “colours”: greens, blues, whites and reds), thrilled more than a hundred thousand spectators. In the **theatre**, comedy, tragedy and, with greater success, the **pantomime** were performed. In the **amphitheatre** there were **animal hunts** (*venationes*), executions of the condemned and **gladiator** combats. Gladiators were slaves, convicts or volunteers; they trained in schools (*ludi*) and only a small proportion died in each fight. A good gladiator was worth a great deal of money to his owner, so deaths were less frequent than in the modern imagination.',
  { img: 'rai-gladiadores', leg: 'AI-generated illustration. Gladiator combat in the Colosseum, c. AD 100: artistic interpretation.' },
  { caixa: 'Myths about gladiators', texto: 'The salute “**Ave, Caesar, morituri te salutant**” (“Hail, Caesar, those who are about to die salute you”) is attested **only once**, by Suetonius, in connection with a mock naval battle staged by Claudius in 52. It was not the usual salute. The “thumbs down” as a sign of death is also **not certain**: ancient sources speak of “turning the thumb” without saying in which direction. The *vomitoria* were not places for vomiting: they were the exits through which the crowd left the building.' },
  { h: 'The baths' },
  'Going to the **baths** was a daily habit. There were small neighbourhood baths and large imperial complexes (those of Agrippa, of Nero, of Titus, of Trajan, dedicated in AD 109, and, after the period of this page, of Caracalla). They had cold (*frigidarium*), warm (*tepidarium*) and hot (*caldarium*) rooms, heated by a system of hot air under the floor and in the walls (*hypocaust*), gyms, gardens and libraries. They were places for social meeting, business and conversation.',
  { h: 'The home: *domus* and *villa*' },
  'The rich lived in **domus** (town houses with atrium, peristyle, garden, dining rooms) or in **villae** (country houses, from farmhouses to great luxury residences). In Portugal, among others, the villae of **Milreu** (Estoi), **Torre de Palma** (Monforte), **Pisões** (Beja) and **São Cucufate** (Vidigueira) are known. The mosaics, wall paintings and private baths show the taste of the elites. The poor lived in rented rooms in an *insula* or in huts.',
  { h: 'Food' },
  'The basic diet was the **Mediterranean triad**: wheat (bread and cereal porridge, the *puls*), olive oil and wine. They also ate vegetables, cheese, fish, oysters and meat (pork, poultry; beef was rare). The Romans used **garum**, a fermented fish sauce, produced in coastal factories in Hispania, including **Tróia** and **Lisbon**, and exported all over the Empire. The rich gave **banquets** (*convivia*), with guests reclining on *triclinia*; the writer Petronius satirised the excess in **Trimalchio’s dinner**. Sugar did not exist: they sweetened with honey.',
  { img: 'rai-banquete', leg: 'AI-generated illustration. Banquet in a domus, first century AD: artistic interpretation.' },
  { h: 'Clothing' },
  'The key garment was the **tunic**, in wool or linen. The **citizen** wore over it the **toga**, a complicated and impractical garment that by the second century was used only on formal occasions. Women wore the *stola* (married women) and the *palla* (cloak). Soldiers wore the tunic and the cloak (*sagum*). Footwear was sandals, and soldiers wore the *caligae* (open boots with hobnails). Silk, from China and India, was expensive, and moralists complained of its use.',
  { h: 'Education and languages' },
  'Elementary school, paid for, taught reading, writing and counting to children from 7 to 11, boys and girls; only boys from rich families went on to a **grammarian** (literature) and then a **rhetor** (oratory), the training of the future politician. **Latin** was the language of administration and the army; **Greek** was the language of culture and trade in the East. In many regions local languages (Celtic, Punic, Aramaic, Coptic...) continued to be spoken, though in Hispania Latin prevailed almost entirely. Marcus Aurelius, a Roman emperor, wrote the *Meditations* in **Greek**.',
  { h: 'Official religion and the imperial cult' },
  'Roman religion was **civic** and **ritual**: what mattered was to perform the cult of the state gods (Jupiter, Juno, Minerva, Mars, Vesta...) correctly, not to believe in a doctrine. Augustus restored temples and rituals, and became **pontifex maximus**. The **imperial cult** was created: the *genius* (protective spirit) of the living emperor received worship, and dead emperors could be **deified** by the Senate (*divus*): Caesar, Augustus, Claudius, Vespasian and others, but not Caligula or Nero. In the provinces the imperial cult was a sign of loyalty to Rome.',
  { h: 'Eastern religions, Judaism and Christianity' },
  'There was de facto religious freedom, provided the civic cult was respected. Eastern cults spread: **Isis** (Egypt), **Cybele** (Phrygia) and **Mithras**, popular among soldiers (from the first century AD). **Jews** had a special status, which exempted them from the imperial cult. **Christians**, at first seen as a Jewish sect, were distinguished from Jews and became objects of suspicion for refusing the civic cult. In **64** Nero made them scapegoats for the fire, according to Tacitus. Around **112**, Pliny the Younger, governor of Bithynia, wrote to Trajan asking what to do about them, and Trajan replied that they were not to be sought out but that, if accused and if they refused to sacrifice, they should be punished. Persecutions were **local and sporadic**, not general, in this period.',
  { h: 'Roman law' },
  'Roman law developed greatly in the High Empire. Emperors legislated by **constitutions** and **rescripts** (replies to specific cases). The **jurists** (Salvius Julianus, under Hadrian, who codified the praetors’ edict; Gaius, c. 160, author of the *Institutes*) became the great names. Principles we still recognise: the **presumption of innocence** in judicial practice (Trajan: “it is better to leave a guilty man unpunished than to condemn an innocent one”, according to the Digest), **contract**, **property**, **inheritance rights**. Citizens had the right of **appeal to the emperor** (as St Paul did, according to the *Acts of the Apostles*).',
  { h: 'Literature and thought' },
  'The **Age of Augustus** was the “golden age” of Latin literature: **Virgil** (*Aeneid*), **Horace**, **Livy** (*Ab Urbe Condita*) and **Ovid**, exiled by Augustus in AD 8 to Tomis, on the Black Sea, for reasons that remain obscure. Then the “silver age”: **Seneca**, **Lucan**, **Petronius**, **Pliny the Elder**, **Quintilian**, **Martial**, **Juvenal**, **Tacitus**, **Pliny the Younger**, **Suetonius**. In Greek wrote **Plutarch**, **Josephus**, **Epictetus** and **Cassius Dio**. The dominant philosophy among the elites was **Stoicism**: Seneca, Epictetus and Marcus Aurelius.',
  { h: 'Economy and money' },
  'The economy was essentially **agricultural**, but with a long-distance trade without parallel in antiquity. **Olive oil** from Baetica, **grain** from Egypt and Africa, **wine** from Gaul and Italy, **garum** from Hispania and **metal** from the mines (gold from **Las Médulas**, in Galicia/León; copper and silver from southern Portugal) circulated throughout the Empire. **Monte Testaccio**, in Rome, is a hill made of some 53 million olive-oil amphorae (an estimate), mostly from Baetica, discarded mostly between c. AD 140 and 250. The silver **denarius** was the basic coin (a legionary earned 225 denarii a year under Augustus, 300 from Domitian); the gold **aureus** was worth 25 denarii; the **sesterce** was worth ¼ of a denarius. Nero reduced the weight and purity of the denarius in 64, and his successors went on slowly debasing it.',
  { h: 'The Aljustrel mines (Vipasca)' },
  'The **Tablets of Vipasca**, found at Aljustrel in the Alentejo, are bronzes with the regulations for running an imperial mine (copper and silver) and services (barber, shoemaker, auctions) in **Hadrian’s** time (second century). They are a rare document of the life of miners and of Roman administration in Lusitania.',
  { h: 'Roads, bridges and aqueducts' },
  'Roman engineering was made of **stone, brick and concrete** (*opus caementicium*, a mixture of lime, volcanic sand and small stones that hardens even under water). **Roads** had layered foundations, drainage and gentle curves; **bridges** and **aqueducts** used the **arch**. Rome had nine aqueducts when **Frontinus**, curator of the waters, wrote *De Aquaeductu* (c. 97), ten after Trajan’s (109) and eleven in the third century; together they brought perhaps a million cubic metres of water a day (an estimate). The **Segovia aqueduct** (c. first–second century, the dating is debated) and the **Pont du Gard** (mid first century) are among the best preserved.',
  { img: 'rai-aqueduto-segovia', leg: 'Aqueduct of Segovia, Spain.' },
  { img: 'rai-pont-du-gard', leg: 'Pont du Gard, Roman aqueduct, France.' },
  { img: 'rai-estrada-romana', leg: 'AI-generated illustration. Roman road in Italy, c. AD 120: artistic interpretation.' },
  { h: 'The Pantheon and the concrete revolution' },
  'The **Pantheon** in Rome was first built by Agrippa (27–25 BC). It burned and was rebuilt under **Domitian**, and burned again; the present building was made under **Trajan and Hadrian** (c. 113–125, by the brick stamps) and has the **largest unreinforced concrete dome** in the world, 43.3 m in diameter, with an oculus 8.2 m wide. The inscription on the façade, “M. AGRIPPA L. F. COS TERTIUM FECIT” (Marcus Agrippa, son of Lucius, consul for the third time, made it), names the original builder, not the present one. The architect’s name is **unknown**; the link to Apollodorus of Damascus is a hypothesis.',
  { img: 'rai-panteao', leg: 'Pantheon, Rome: facade and portico.' },
  { h: 'Science and medicine' },
  'The High Empire was not an age of great theoretical discoveries, but it was one of **synthesis** and **observation**. **Pliny the Elder** compiled the *Naturalis Historia* (37 books, c. 77); **Claudius Ptolemy** (c. 100–170, Alexandria) wrote the *Almagest* and the *Geography*; **Dioscorides** the treatise on medicinal plants (*De Materia Medica*); **Galen of Pergamon** (129–c. 210) anatomy and medicine, the most influential for about **1,400 years**. Medicine was based on the theory of the **four humours**; there was surgery (caesarean section, removal of bladder stones, trepanation) and army doctors. Hospitals (*valetudinaria*) existed in the large legionary forts.',
  { h: 'The army: legions and auxiliaries' },
  'Augustus reduced the civil-war armies from about 60 legions to **28** (25 after Teutoburg). Each **legion** had about **5,000 to 5,500 men**, Roman citizens who served 20 years (later 25) as professionals, to which were added **auxiliary** troops, non-citizens, who received citizenship at the end of service (by a bronze military diploma). In all, the army would have been **300 to 400 thousand men** in the second century (an estimate). The legion was divided into **cohorts** and **centuries**, led by **centurions**. Soldiers were also builders of roads, bridges and forts.',
  { h: 'The fleet and the frontiers (limes)' },
  'There were two great Italian fleets, at **Misenum** and at **Ravenna**, and provincial fleets (of the Rhine, the Danube, Britain, Egypt). They fought mainly pirates and escorted the grain. The **frontier** (*limes*) was not a continuous wall: it was a **military zone** with forts, roads, watchtowers and rivers. Trajan and Hadrian fixed it on the Rhine and the Danube (to which Dacia was added) and on the Euphrates (after 117), with walls in Britain and Upper Germany.',
  { img: 'rai-triunfo-trajano', leg: 'AI-generated illustration. Trajan’s triumph after the Dacian wars, AD 106: artistic interpretation.' },
  { h: 'Writing in everyday life' },
  'People wrote on **papyrus** (from Egypt), on **wax tablets** (for notes and accounts) and on thin **wooden tablets** written with ink (like those of Vindolanda). On the walls of Pompeii there are thousands of **graffiti**, with prices, insults, declarations of love and election propaganda. Books were **rolls** (*volumina*); from the first century there was also the **codex**, folded and stitched sheets, the ancestor of the modern book, used early by Christians.',
  { img: 'rai-vindolanda', leg: 'Claudia Severa’s birthday invitation, Vindolanda tablet, British Museum (1986,1001.64).' },
  { h: 'Calendar and public life' },
  'The **Julian calendar** (45 BC) was in use, with twelve months, years of 365 days and a leap year every four years. The months **July** (for Julius Caesar) and **August** (for Augustus, in 8 BC) were named in honour of their men. Days were divided into **fasti** (working days) and **nefasti**; the year was counted by consuls (“in the consulship of...”) or by regnal years, and only rarely “from the foundation of Rome” (*ab Urbe condita*).',
  { h: 'The Antonine Plague' },
  'In **165–166**, troops returning from the Parthian campaign brought an **epidemic** that crossed the Empire and lasted until 180 or later. Galen, who witnessed it, described fever and a skin eruption: historians of medicine propose **smallpox** (it is not certain). The death toll is much debated: estimates range from a few per cent to **ten per cent** or more of the population. It is one of the factors that weakened the Empire in the second half of the second century, but its exact importance is also discussed.'
];

const personalidades = [
  'These fourteen figures were chosen because they shaped the High Empire or the memory left of it. Many other emperors and personalities have their own biography on the page “Emperors and great figures”. Dates are firm in most cases; what is tradition or debate is flagged.',
  { h: 'Augustus (63 BC – AD 14)' },
  'Born Gaius Octavius, Caesar’s great-nephew (his mother, Atia, was the dictator’s niece), he was adopted in the dictator’s will in 44 BC and became Gaius Julius Caesar Octavianus. He defeated Brutus and Cassius, and Mark Antony at Actium (31 BC). In 27 BC he took the name **Augustus**. He reigned 41 years and created the professional army, the provincial administration and the foundations of the Principate. He wrote an account of his life, the *Res Gestae*. He died at Nola in AD 14. To admirers, the creator of peace; to critics, a dictator in velvet gloves. His rise to power began with the brutality of the triumvirate’s proscriptions, which Augustan legend erased.',
  { h: 'Livia Drusilla (58 BC – AD 29)' },
  'She married Augustus in 38 BC and was his adviser for 52 years. Mother of **Tiberius**, she was granted in Augustus’s will the title **Augusta**. Tacitus and Dio insinuate that she poisoned rivals, **without proof**; hostile sources have an interest in overstating her intrigue. She was a model of the Roman matron.',
  { h: 'Marcus Vipsanius Agrippa (c. 63 – 12 BC)' },
  'A friend of Augustus from youth, son-in-law and right-hand man. **General** at Naulochus and Actium, **administrator** (the Aqua Virgo aqueduct in 19 BC, the first public baths of Rome, the first Pantheon) and author of a known **map of the world**. He married Julia, Augustus’s daughter, and was grandfather of Caligula. His death in 12 BC left Augustus without his ablest successor.',
  { h: 'Claudius (10 BC – AD 54)' },
  'Born in Lugdunum, lame and with a stammer, he was sidelined by his family until the Praetorians proclaimed him emperor in 41. He surprised: he conquered **Britain** (43), created the **harbour of Portus**, opened the Senate to notables from Gaul (speech engraved on the “Lyon Tablet”), and reorganised the imperial services. He wrote works of history (lost). He died in 54, perhaps poisoned by Agrippina (tradition; the debate continues).',
  { img: 'rai-claudio-busto', leg: 'Bust of Claudius, Vatican Museums.' },
  { h: 'Nero (AD 37 – 68)' },
  'Son of Agrippina, adopted by Claudius, he came to the throne at 16. The first five years, with the advisers **Seneca** and **Burrus**, are considered a period of good government (the *quinquennium Neronis*). Afterwards he had his mother (59), his wife and many senators killed; he rebuilt Rome after the fire of 64 and began the **Domus Aurea**, a luxury palace. He toured Greece (66–67) as an artist and athlete. The revolts of Vindex and Galba led to his suicide on 9 June 68. He was hated in the senatorial tradition and **popular** in the East and among the plebs, which the sources hide.',
  { img: 'rai-nero-busto', leg: 'Bust of Nero, Capitoline Museums, with early modern restorations.' },
  { h: 'Vespasian (AD 9 – 79)' },
  'From an equestrian family of Reate, in the Sabine country, with no noble blood, he made a career as a general (Britain, Judaea). Acclaimed emperor at Alexandria in 69, he **restored the finances and the peace**, began the **Colosseum** and the **Temple of Peace**. He was an emperor of dry humour: according to Suetonius, on hearing he was to be deified, he is said to have remarked “alas, I think I am becoming a god”. The tax on urine from public urinals (the origin of the phrase “*pecunia non olet*”, money does not stink) is an anecdote of Suetonius.',
  { img: 'rai-vespasiano-busto', leg: 'Bust of Vespasian, Ny Carlsberg Glyptotek.' },
  { h: 'Flavius Josephus (c. AD 37 – c. 100)' },
  'A Jewish priest from Jerusalem, born Joseph ben Matityahu. He commanded the revolt in Galilee in 66; captured at Jotapata in 67, he predicted that Vespasian would be emperor, and was freed when it happened. He lived in Rome under Flavian protection, with the name **Flavius Josephus**, and wrote *The Jewish War* and the *Jewish Antiquities*. He is the **main source** for the Great Revolt, but must be read with caution, being an interested party.',
  { h: 'Pliny the Elder (AD 23/24 – 79)' },
  'A knight, officer and administrator, he wrote the ***Naturalis Historia***, an encyclopaedia in 37 books on the cosmos, geography, animals, plants, minerals and art, with much information on the **mines of Hispania**. He commanded the fleet at Misenum in 79, and died at Stabiae observing the eruption of Vesuvius, according to his nephew. It was the work of a curious man, not a modern scientist: it mixes observation and legend.',
  { h: 'Publius Cornelius Tacitus (c. AD 56 – c. 120)' },
  'A senator, consul in 97, the greatest Latin historian. He wrote the *Agricola* (the life of his father-in-law), the *Germania*, the *Histories* (69–96) and the *Annals* (14–68). His style is sombre and relentless towards tyrants and towards the Senate’s servility. His view of the Principate is pessimistic: he lived through Domitian’s terror and wrote afterwards, with resentment. From him come the best-known passages on the fire of Rome and the Christians.',
  { h: 'Trajan (AD 53 – 117)' },
  'Marcus Ulpius Traianus, born at **Italica**, near Seville, was the **first emperor born outside Italy**. A career general, he was adopted by Nerva in 97. He conquered **Dacia** (101–106) and, at the end of his life, Parthian territory as far as the Persian Gulf (114–117): the Empire reached its greatest extent. At home he created the support programme for poor children (*alimenta*), built the **forum**, the **column** and the **markets**, and was hailed by the Senate as **Optimus Princeps**, “the best prince”. He died at Selinus (Cilicia) in August 117.',
  { img: 'rai-trajano-busto', leg: 'Bust of Trajan, Glyptothek, Munich.' },
  { h: 'Hadrian (AD 76 – 138)' },
  'Relative and successor of Trajan (the adoption in 117 was contested by some, who attributed it to the widow Plotina). He spent more than half his reign **travelling** the provinces. He gave up Trajan’s conquests beyond the Euphrates, **fixed the frontiers** (the Wall in Britain, the *limes* in Germany) and reformed the army and administration. An admirer of Greek culture (he wore a beard, like the philosophers), he embellished **Athens**; he built **Hadrian’s Villa** at Tivoli and the present **Pantheon**. The death of his young companion **Antinous** in the Nile (130) led to a posthumous cult. The **Bar Kokhba Revolt** (132–135) was the black mark of the reign. He died at Baiae in 138.',
  { img: 'rai-adriano-busto', leg: 'Bust of Hadrian, Capitoline Museums, Rome.' },
  { h: 'Pliny the Younger (c. AD 61 – c. 113)' },
  'Nephew and adopted son of Pliny the Elder, a lawyer, senator and friend of Tacitus. Two of his **Letters**, addressed to Tacitus, describe the **eruption of Vesuvius** that he saw from Misenum at the age of 17. As governor of Bithynia-Pontus he wrote to Trajan (letter X, 96) about the **Christians**, and Trajan’s replies are the **first official Roman testimony** about them. His *Panegyric* to Trajan (100) is a speech of praise.',
  { h: 'Marcus Aurelius (AD 121 – 180)' },
  'The philosopher-emperor, adopted by Antoninus Pius. He first reigned with **Lucius Verus** (until 169), and had to face the Parthian war, the **plague** and the **Marcomannic wars** on the Danube, where he spent much of his last years. He wrote in Greek the **Meditations**, personal notes of **Stoic** inspiration that he never meant to publish (the title is later). His bronze equestrian statue in Rome survived the Middle Ages because it was thought to be of Constantine, the first Christian emperor. He chose his son **Commodus** as successor, and many historians consider that decision his worst mistake.',
  { img: 'rai-marco-aurelio', leg: 'Original bronze equestrian statue of Marcus Aurelius, Capitoline Museums.' },
  { h: 'Claudius Galen (AD 129 – c. 210)' },
  'Born in Pergamon (in today’s Turkey), he was physician to gladiators, then physician to Marcus Aurelius and his successors. He dissected animals and wrote more than a hundred treatises, in Greek, on anatomy, physiology and pharmacy. He left a theory of the four humours and of circulation, partly wrong, that dominated European and Arab medicine until the sixteenth century. The date of his death (between c. 200 and c. 216) is debated.'
];

const legado = [
  { h: 'What they left us' },
  { lista: [
    '**A model of empire:** a multicultural state with one head, one law, one currency and one administrative language, which inspired Europe for centuries (the Holy Empire, the tsars and the kaisers, from “caesar”, used the name).',
    '**Latin:** the language from which Portuguese, Spanish, French, Italian and Romanian came.',
    '**Law:** the ideas of contract, property, individual rights and citizenship passed, via Justinian and medieval law, into European civil law.',
    '**The city:** roads, bridges, aqueducts, baths, theatres and forums. Many cities of western Europe (London, Paris, Lisbon, Cologne, Vienna) are Roman foundations or developments.',
    '**Christianity:** it was born and grew in this period, along the roads and cities of the Empire.',
    '**Latin literature:** Virgil, Horace, Ovid, Tacitus, Seneca and Pliny are still read.'
  ] },
  { img: 'rai-domus-aurea', leg: 'Octagonal room of the Domus Aurea, Rome.' },
  { h: 'The golden century, according to Gibbon' },
  'Edward Gibbon, in the *History of the Decline and Fall of the Roman Empire* (1776), claimed that the period between the death of Domitian (96) and the accession of Commodus (180) was that in which the condition of mankind was happiest and most prosperous. The phrase “**five good emperors**” (Nerva, Trajan, Hadrian, Antoninus Pius, Marcus Aurelius), attributed to Machiavelli, became traditional. Modern historians qualify this: prosperity was uneven, the elites wrote the sources, and slavery and the poverty of the masses persisted.',
  { h: 'Rediscovery' },
  'Roman monuments never disappeared from the landscape, but they were reused and plundered. The **Renaissance** rediscovered them as a model: Brunelleschi measured the Pantheon before raising the dome of Florence. **Herculaneum** was discovered in **1738** (by wells dug for a prince), **Pompeii** in **1748**, and the excavations shaped the neoclassical taste of the eighteenth century. **Trajan’s Column** served as an art book for generations of artists. Reading the **Herculaneum papyri** with modern technology (X-rays, artificial intelligence) continues to reveal texts.',
  { h: 'What to see in Portugal' },
  { lista: [
    '**Conímbriga** (Condeixa-a-Nova): the largest excavated Roman city in Portugal, with a site museum.',
    '**Roman temple of Évora**, first century AD, and its surroundings.',
    '**Roman theatre of Lisbon** (Olisipo), with a museum and the Roman Gallery (Rua da Prata).',
    '**Roman ruins of Tróia** (Grândola) and **Milreu** (Estoi, Faro).',
    '**Mértola** (Myrtilis) and the **Mértola Museum**.',
    '**Miróbriga** (Santiago do Cacém), **Ammaia** (Marvão) and **São Cucufate** (Vidigueira).',
    '**Braga** (Bracara Augusta), with the Domus da Escola Velha and the D. Diogo de Sousa Museum.'
  ] },
  { h: 'What to see in the rest of the Empire' },
  { lista: [
    '**Italy:** Rome (Colosseum, Imperial Forums, Pantheon, Domus Aurea), Pompeii, Herculaneum, Ostia Antica, Hadrian’s Villa at Tivoli.',
    '**United Kingdom:** Hadrian’s Wall and the Vindolanda museum (World Heritage).',
    '**Spain:** Mérida, Segovia, Italica, Tarragona, the Alcántara bridge.',
    '**France:** Pont du Gard, Nîmes, Arles, Orange, Lyon.',
    '**Turkey, Jordan, Libya, Tunisia:** Ephesus, Jerash, Leptis Magna, Dougga, El Djem.'
  ] },
  { h: 'Debates and cautions' },
  'Some points remain open: the **date of Vesuvius** (August or October 79); the **site of Teutoburg**; the **death toll** of the Antonine plague and its importance; the **population** of the Empire (50 to 70 million?); the **date of Masada** (73 or 74); the **year of Jesus’s death** (c. 30 or 33); the **dating of the Segovia aqueduct**; the role of Apollodorus of Damascus in the Pantheon and Trajan’s **adoption** of Hadrian. The “fall” of Rome is not for this page: the High Empire ends, by convention, in 192, and the Empire went on for three more centuries in the West and more than a thousand years in the East.',
  { h: 'Reading map' },
  'For the history that comes before, see “The Late Republic”; for what comes after, “Crisis, Dominate and Fall”. Full biographies are in “Emperors and great figures”; the army in “Army and warfare”; cities and engineering in “Cities, monuments and engineering”; religion, law and daily life in “Religion, law and daily life”.',
  { h: 'Main sources' },
  { lista: [
    '**Ancient:** Res Gestae Divi Augusti; Tacitus (Annals, Histories, Agricola, Germania); Suetonius (Lives of the Twelve Caesars); Cassius Dio (Roman History); Josephus (Jewish War); Pliny the Younger (Letters); Frontinus (De Aquaeductu); Pliny the Elder (Natural History).',
    '**Modern:** Cambridge Ancient History, vols. X–XI; Oxford Classical Dictionary; Mary Beard, *SPQR* (2015); Adrian Goldsworthy, *Pax Romana* (2016); Greg Woolf, *Rome: An Empire’s Story* (2012); Peter Garnsey and Richard Saller, *The Roman Empire* (1987); on Lusitania, Jorge de Alarcão, *O Domínio Romano em Portugal* (1988).'
  ] },
  { h: 'Images' },
  'Freely licensed images come from Wikimedia Commons and museum collections; illustrations marked “AI-generated” are illustrative reconstructions and not documents. See the file IMAGENS_ROMA_ALTO_IMPERIO.md for the requests and search terms.'
];

const quiz = [
  { p: 'In what year did the Senate give Octavian the name Augustus, the conventional start of the Principate?', op: ['44 BC', '31 BC', '27 BC', 'AD 14'], certa: 2, exp: 'In 27 BC (16 January); Actium, in 31 BC, was the battle that left him without a rival.' },
  { p: 'What title did Augustus use instead of “king”?', op: ['Dictator perpetuus', 'Princeps', 'Rex', 'Tyrannus'], certa: 1, exp: '“Princeps”, the first citizen. The word “emperor” comes from *imperator*, “victorious commander”.' },
  { p: 'Which three legions were annihilated at Teutoburg in AD 9?', op: ['I, II and III', 'X, XI and XII', 'XVII, XVIII and XIX', 'XXI, XXII and XXIII'], certa: 2, exp: 'Legions XVII, XVIII and XIX, commanded by Quinctilius Varus, fell into an ambush set by Arminius.' },
  { p: 'Who were the emperors of the “Year of the Four Emperors” (69)?', op: ['Nero, Galba, Otho, Vitellius', 'Galba, Otho, Vitellius, Vespasian', 'Claudius, Nero, Galba, Otho', 'Vespasian, Titus, Domitian, Nerva'], certa: 1, exp: 'Galba, Otho, Vitellius and Vespasian; the last founded the Flavian dynasty.' },
  { p: 'Which emperor conquered Dacia, in AD 106?', op: ['Hadrian', 'Domitian', 'Trajan', 'Marcus Aurelius'], certa: 2, exp: 'Trajan, after two wars (101–102 and 105–106) against King Decebalus.' },
  { p: 'Which eruption destroyed Pompeii and Herculaneum?', op: ['Etna', 'Vesuvius', 'Stromboli', 'Santorini'], certa: 1, exp: 'Vesuvius, in AD 79 (traditional date: 24 August; a 2018 graffito suggests October).' },
  { p: 'In what year did the Roman Empire reach its greatest extent?', op: ['27 BC', 'AD 43', 'AD 117', 'AD 180'], certa: 2, exp: 'In 117, at the end of Trajan’s reign, after the Parthian campaign; Hadrian then gave up the conquests beyond the Euphrates.' },
  { p: 'Who had the wall in northern Britain built, from 122?', op: ['Trajan', 'Claudius', 'Hadrian', 'Septimius Severus'], certa: 2, exp: 'Hadrian; the wall was about 117 km (80 Roman miles) long.' },
  { p: 'In what language did Marcus Aurelius write his *Meditations*?', op: ['Latin', 'Greek', 'Aramaic', 'Etruscan'], certa: 1, exp: 'In Greek, the language of philosophy; the title “Meditations” is later.' },
  { p: 'In which city was the capital of Lusitania founded in 25 BC?', op: ['Olisipo', 'Pax Iulia', 'Augusta Emerita', 'Bracara Augusta'], certa: 2, exp: 'Augusta Emerita (Mérida), for the veterans of the Cantabrian wars.' },
  { p: 'For which event does Tacitus say Nero blamed the Christians?', op: ['The Great Jewish Revolt', 'The fire of Rome, in 64', 'The death of Claudius', 'The eruption of Vesuvius'], certa: 1, exp: 'The fire of 64; but there is no evidence that Nero “played the lyre” during the blaze.' },
  { p: 'Which phrase is attested **only once**, by Suetonius, in connection with Claudius?', op: ['“Veni, vidi, vici”', '“Ave, Caesar, morituri te salutant”', '“Alea iacta est”', '“Panem et circenses”'], certa: 1, exp: 'The salute of “those about to die” was spoken at a mock naval battle in AD 52; it was not the usual gladiators’ salute.' },
  { p: 'What were the vigiles, created by Augustus?', op: ['The emperor’s guard', 'The fire brigade and night police of Rome', 'A military fleet', 'Tax collectors'], certa: 1, exp: 'The vigiles fought fires and kept night watch over the city.' },
  { p: 'Which building has the largest unreinforced concrete dome in the world, still standing?', op: ['The Colosseum', 'The Domus Aurea', 'The Pantheon', 'The Baths of Caracalla'], certa: 2, exp: 'The Pantheon, 43.3 m in diameter, rebuilt in the time of Trajan and Hadrian.' },
  { p: 'Who wrote the Letters describing the eruption of Vesuvius and asking Trajan about the Christians?', op: ['Tacitus', 'Pliny the Younger', 'Suetonius', 'Martial'], certa: 1, exp: 'Pliny the Younger, nephew of Pliny the Elder, who died in the eruption.' }
];

export default { visao, linha, mapa, sociedade, personalidades, legado, quiz };
