// ROMA — RELIGIÃO, DIREITO E VIDA QUOTIDIANA — conteúdo completo em português. A versão inglesa está em dados-en.js (mesma estrutura).
// Datas convencionais; tudo o que anterior a c. 500 a.C. vem da tradição (Lívio, Dionísio de Halicarnasso, Plutarco) e é assinalado como tal.
// Imagens: cada {img:'id'} procura o ficheiro  roma/religiao-vida/img/id.jpg  (ver IMAGENS_ROMA_RELIGIAO_VIDA.md).
import EN from './dados-en.js';
import CRED from './creditos.js';
import { GRUPO } from '../grupo.js';

const visao = [
  { caixa: 'Em resumo', texto: [
    'Esta página ocupa-se do que fazia dos romanos **romanos** para além das legiões e dos imperadores: **como rezavam, como se julgavam uns aos outros e como viviam todos os dias**. Os romanos eram um povo religioso, mas a sua religião era sobretudo um conjunto de **ritos** que garantiam a boa relação entre a cidade e os deuses (a *pax deorum*, a «paz com os deuses»), e não uma doutrina que se tivesse de acreditar. Criaram um **direito** tão rigoroso e tão bem pensado que ainda hoje serve de base aos sistemas jurídicos da Europa continental, da América Latina e de Portugal. E viveram numa sociedade desigual, assente na família, na escravatura, na clientela e no dinheiro, mas também de cidades animadas, banhos públicos, teatros, escolas, médicos e mercados.',
    'Veja nas outras páginas a história política (Monarquia, República, Império), o exército, os imperadores e as cidades. Aqui está o **tecido da vida**: do altar da família ao tribunal do pretor, da escola do *ludus* à mesa do *triclinium*.'
  ] },
  { img: 'rrv-panteao', leg: 'Interior do Panteão de Roma (oculus e cúpula)' },
  { h: 'Onde e quando' },
  'A «vida romana» abrange mais de mil anos (da fundação tradicional, em 753 a.C., até ao fim do Império do Ocidente, em 476 d.C., e para além disso) e um território que ia da Escócia ao Eufrates e do Reno ao Saara. Por isso nada é «típico» sem ressalva: a vida de um senador em Roma no tempo de Cícero, a de uma escrava numa quinta da Lusitânia e a de um soldado em Vindolanda (norte de Inglaterra) tinham pouco em comum. Esta página descreve sobretudo o **período mais bem documentado: do século I a.C. ao século III d.C.**, com recuos e avanços quando a evolução importa.',
  { tabela: { cab: ['Fase', 'Religião', 'Direito e sociedade', 'Vida quotidiana'], linhas: [
    ['Monarquia e República antiga (753 a.C. – c. 264 a.C.)', 'Culto da cidade e das famílias; influência etrusca (tríade capitolina); colégios sacerdotais', 'Doze Tábuas (c. 450 a.C.); Conflito das Ordens; patrícios e plebeus', 'Sociedade agrária de pequenos proprietários; casa simples'],
    ['República tardia (264 – 27 a.C.)', 'Chegada de cultos gregos e orientais (Cibele, 204 a.C.); repressão das Bacanais (186 a.C.)', 'Pretores e jurisconsultos; ius gentium; expansão da escravatura em massa', 'Luxo das elites; primeiras termas e teatros; crise agrária'],
    ['Alto Império (27 a.C. – 192 d.C.)', 'Culto imperial; cultos de mistérios; judeus e cristãos; Panteão', 'Pax Romana; grandes juristas; cidadania alargada', 'Apogeu das cidades, jogos, comércio; insulae e villae'],
    ['Crise e Dominato (193 – 476 d.C.)', 'Perseguições e Edito de Milão (313); cristianismo religião dominante (380)', 'Cidadania universal (212); códigos de leis (438, 529–534)', 'Inflação, fiscalidade pesada; vida rural em villae fortificadas']
  ] } },
  { h: 'Porque importam' },
  { lista: [
    '**Direito:** o direito romano é a origem do direito civil europeu continental (Portugal, Espanha, França, Itália, Alemanha) e latino-americano; conceitos como *propriedade*, *contrato*, *testamento*, *pessoa jurídica*, *boa-fé* vêm de Roma ou foram elaborados com base nela.',
    '**Língua:** o latim deu origem ao português, ao espanhol, ao francês, ao italiano, ao romeno e a outras línguas; e forneceu à ciência, à medicina e ao direito grande parte do vocabulário que hoje usamos.',
    '**Religião:** o Império Romano foi o quadro em que o cristianismo nasceu, se difundiu e se tornou religião do Estado; a Igreja ocidental herdou do mundo romano o latim, a organização em dioceses e o título de *pontifex*.',
    '**Quotidiano:** do calendário aos meses, da toga ao livro, das estradas à escola e ao hospital militar, muito do que hoje nos parece natural foi organizado em Roma.'
  ] },
  { img: 'rrv-fresco-casal', leg: 'Retrato de casal de Pompeia, Museu Arqueológico Nacional de Nápoles (inv. 9058)' },
  { h: 'Como sabemos' },
  'Conhecemos a vida romana por **textos** (Cícero, Plínio, Plutarco, Tácito, Marcial, Juvenal, Petrónio, Apício, Vitrúvio…), por **inscrições** (centenas de milhares de lápides, dedicatórias e leis em bronze), por **papiros e tabuinhas** (Egito, Vindolanda), por **sítios** como Pompeia, Herculano e Óstia, e por milhões de objetos do quotidiano, de lucernas a ânforas. Todos os textos foram escritos por uma minoria instruída, quase sempre homens livres e ricos: a voz das mulheres, dos escravos e dos pobres chega-nos de forma indireta (um grafito, uma epígrafe, uma carta).',
  { img: 'rrv-ara-pacis', leg: 'Pormenor da procissão na Ara Pacis: Agripa e uma figura tradicionalmente identificada como Lívia; Roma.' },
  { h: 'Mitos e equívocos a evitar' },
  'Convém afastar logo alguns lugares-comuns: os romanos **não** usavam «vomitórios» para vomitar nos banquetes (os *vomitoria* eram as saídas dos anfiteatros e teatros); **não** há prova do «polegar para baixo» como sinal de morte nas arenas; o **cinto de castidade** é uma invenção medieval; a saudação *Ave, Caesar, morituri te salutant* só está atestada uma vez (Cláudio, 52 d.C., numa batalha naval simulada); e os cristãos **não** foram perseguidos sem pausa durante três séculos (houve perseguições locais e esporádicas, e só algumas gerais, entre 249 e 311). Será assinalado ao longo da página o que é tradição e o que é facto.',
  { img: 'rrv-culto-lar', leg: 'Ilustração gerada por IA. Família romana a oferecer vinho e incenso ao altar dos lares (c. séc. I d.C.)' },
  { h: 'O que cobre cada aba' },
  { lista: [
    '**Linha do tempo:** a evolução da religião, do direito e do quotidiano, de Numa (tradição) a Justiniano.',
    '**Mapa:** os lugares onde se rezava, se julgava e se vivia: Fórum, Capitólio, Pompeia, Óstia, Nîmes, Mérida, Évora, Conímbriga, Aljustrel.',
    '**Sociedade:** religião, direito, língua, classes sociais, escravatura, mulheres e família, casa, comida, vestuário, educação, jogos, medicina, escrita e dinheiro.',
    '**Personalidades:** 15 figuras: juristas, escritores, médicos, mulheres e um sacerdote lendário.',
    '**Legado:** o direito, o latim, o calendário, a Igreja; onde visitar, em Portugal e fora dele.',
    '**Quiz:** 15 perguntas.'
  ] },
  { h: 'Um aviso sobre números' },
  'A população do Império no século II d.C. é estimada entre **50 e 70 milhões** de habitantes, com Roma talvez perto de **um milhão** (estimativas variam muito). A percentagem de escravos, a taxa de alfabetização, a esperança de vida ou o número de cristãos são **estimativas de historiadores**, não contagens; quando as damos, dá-se um intervalo e indica-se que é debatido.'
];

const linha = [
  'Esta linha do tempo segue a religião, o direito e a vida quotidiana. Tudo o que é anterior a c. 500 a.C. vem da **tradição** antiga (Lívio, Dionísio, Plutarco), escrita séculos depois dos factos, e é assinalado como tal. Para a história política e militar, vá às outras páginas.',
  { linha: [
    { d: '753 a.C. (tradição)', t: 'Fundação de Roma e primeiro calendário', x: 'Segundo a tradição, Rómulo fundou a cidade a 21 de abril de 753 a.C. e organizou um primeiro calendário de dez meses. A data é convencional, fixada por Varrão no século I a.C.; a arqueologia mostra aldeias nas colinas desde meados do século VIII a.C., mas não prova nenhum «fundador».' },
    { d: 'c. 715 – 673 a.C. (tradição)', t: 'Numa Pompílio, rei sacerdote', x: 'A tradição romana atribuiu ao segundo rei, o sabino Numa, a criação dos principais sacerdócios (pontífices, vestais, flâmines, sálios), do templo de Jano e de um calendário de doze meses. Não há prova histórica de Numa; mas a atribuição mostra como os romanos pensavam a sua religião: obra de um rei piedoso e pacífico.' },
    { d: 'c. 600 – 509 a.C.', t: 'A influência etrusca', x: 'Dos etruscos, Roma recebeu a arte de ler o fígado dos animais (a *haruspicina*), o culto de uma tríade (Júpiter, Juno e Minerva) e o modelo do templo sobre alto podium. O **templo de Júpiter Ótimo Máximo** no Capitólio foi dedicado, segundo a tradição, em 509 a.C., no primeiro ano da República.' },
    { d: '509 a.C. (tradição)', t: 'Rex sacrorum e pontifex maximus', x: 'Com a queda dos reis, as funções sacerdotais do rei passaram para um *rex sacrorum*, sem poder político, e o chefe do colégio dos pontífices (o **pontifex maximus**) tornou-se a maior autoridade religiosa de Roma.' },
    { d: 'c. 451 – 450 a.C.', t: 'As Doze Tábuas', x: 'Primeira lei escrita de Roma, redigida por uma comissão de dez homens (os *decemviri*) depois de pressões da plebe. Perdeu-se o texto original (talvez em bronze), conhecemo-lo por citações. Regulava família, dívida, propriedade, delitos e funerais; **é tradição** que foi inspirada em leis gregas.' },
    { d: '367 e 300 a.C.', t: 'Plebeus chegam ao poder e ao altar', x: 'As leis Licínio-Sextias (367 a.C., segundo a tradição) abrem o consulado aos plebeus; a **Lex Ogulnia** (300 a.C.) abre-lhes os colégios dos pontífices e dos áugures. Os cargos religiosos eram também cargos políticos.' },
    { d: 'c. 304 a.C. (tradição)', t: 'O direito deixa de ser segredo', x: 'Segundo Lívio, o escriba Cneu Flávio tornou públicos o calendário judiciário e as fórmulas do processo, até aí guardados pelos pontífices. A partir daí o direito começa a ser tema de estudo laico e jurisprudência.' },
    { d: '291 a.C.', t: 'Esculápio chega a Roma', x: 'Depois de uma epidemia, os romanos pediram ao santuário de Epidauro o culto do deus da medicina; segundo a tradição, uma serpente sagrada foi levada para a ilha Tiberina, onde o templo de Esculápio ficou a ser local de cura.' },
    { d: 'c. 211 a.C.', t: 'O denário', x: 'Durante a Segunda Guerra Púnica surgiu a moeda de prata que seria a base do sistema monetário durante séculos: o **denário**. A data exata (c. 211 a.C.) é aceite com ressalvas.' },
    { d: '204 a.C.', t: 'Cibele, a Magna Mater', x: 'Em plena guerra com Aníbal, e seguindo um oráculo dos Livros Sibilinos, os romanos trouxeram de Pessinunte (Ásia Menor) a pedra negra da deusa Cibele. Foi o primeiro grande culto oriental oficial em Roma, mas os sacerdotes eunucos (*galli*) eram mantidos à distância dos cidadãos.' },
    { d: '186 a.C.', t: 'Repressão das Bacanais', x: 'O Senado mandou perseguir um culto de Baco que se espalhara pela Itália, acusando-o de crimes e conspiração (relato de Lívio, livro 39). Há mortes e execuções; mas muito da descrição pode ser exagerada. O decreto (*senatus consultum de Bacchanalibus*) foi gravado em bronze e sobrevive.' },
    { d: '155 a.C.', t: 'Os filósofos gregos chegam', x: 'Uma embaixada de filósofos atenienses (entre eles Carnéades) impressionou os jovens romanos e inquietou Catão, o Censor. A cultura grega entrou nas escolas, na retórica e na medicina romanas, mesmo contra resistências.' },
    { d: '63 a.C.', t: 'César, pontifex maximus', x: 'Júlio César ganhou nas urnas o cargo de pontífice máximo, o que mostra que o lugar era já uma peça da luta política. Manteve-o até ao fim da vida.' },
    { d: '46 – 45 a.C.', t: 'Calendário juliano', x: 'Para corrigir o desfasamento entre o calendário e as estações, César (com o astrónomo Sosígenes, segundo a tradição) decretou um ano de 365 dias com um dia extra de quatro em quatro anos. Entrou em vigor a 1 de janeiro de 45 a.C. e durou, na Europa, até 1582.' },
    { d: '27 a.C. – 14 d.C.', t: 'Augusto restaura a religião', x: 'Augusto, pontífice máximo desde 12 a.C., reconstruiu dezenas de templos, restaurou festas e sacerdócios e fez do culto de Roma e do imperador um laço entre as províncias. Pelas leis **Júlia** (18 a.C.) e **Papia Popeia** (9 d.C.) tentou incentivar o casamento e punir o adultério.' },
    { d: '64 d.C.', t: 'Nero e os cristãos', x: 'Depois do grande incêndio de Roma, Nero castigou os cristãos como culpados (relato de Tácito, c. 116 d.C.). Mostra que já havia cristãos em Roma e que a população os via com desconfiança. A dimensão da repressão é debatida.' },
    { d: '79 d.C.', t: 'Pompeia e Herculano', x: 'A 24 de agosto (data tradicional; hoje alguns defendem outubro) o Vesúvio erupciona e soterra as cidades da baía de Nápoles. Congelou um instantâneo de lojas, casas, grafitos e altares domésticos.' },
    { d: 'c. 100 d.C.', t: 'Cartas de Vindolanda', x: 'Num forte do norte de Inglaterra, soldados e famílias escrevem a tinta em tabuinhas de madeira: pedidos de cerveja, listas de roupa, e o convite de aniversário de **Cláudia Severa** a Sulpícia Lepidina. É uma das mais antigas cartas escritas por uma mulher em latim.' },
    { d: 'c. 112 d.C.', t: 'Plínio e Trajano sobre os cristãos', x: 'O governador da Bitínia pergunta ao imperador como tratar os cristãos; Trajano responde que não os procurem, mas que sejam punidos se recusarem sacrificar (cartas 10.96–97 de Plínio, o Moço).' },
    { d: 'c. 161 d.C.', t: 'As Institutas de Gaio', x: 'Manual de direito escrito pelo jurista Gaio, de que só chegou até nós, quase completo, um palimpsesto de Verona descoberto em 1816. Foi modelo das *Institutas* de Justiniano.' },
    { d: '212 d.C.', t: 'Constitutio Antoniniana', x: 'O imperador Caracala concedeu a cidadania romana à maioria dos habitantes livres do Império, num decreto de que só sobrevive uma cópia papirácea mutilada. As motivações (fiscais?) discutem-se.' },
    { d: '249 – 311 d.C.', t: 'Perseguições aos cristãos', x: 'Décio ordenou em 249–251 que todos sacrificassem pelo imperador. Valeriano seguiu-se (257–258). A **Grande Perseguição** de Diocleciano e dos seus colegas começou em 303 e terminou com o edito de tolerância de Galério (311).' },
    { d: '301 d.C.', t: 'Edito dos Preços Máximos', x: 'Diocleciano tentou travar a inflação fixando preços e salários máximos para mais de mil produtos. Foi aplicado de forma desigual e abandonado pouco depois. Um dos mais longos textos sobre o dia a dia romano que se conservam.' },
    { d: '313 d.C.', t: 'Milão: liberdade de culto', x: 'Constantino e Licínio acordaram em Milão dar a todos liberdade de seguirem a religião que escolhessem, devolvendo aos cristãos os bens confiscados. Os historiadores discutem se se tratou de um «edito» formal.' },
    { d: '380 – 394 d.C.', t: 'Do cristianismo permitido ao único culto oficial', x: 'Em 380, o edito de Tessalónica (*Cunctos populos*) declara o cristianismo niceno a religião dos povos do Império. Em 391–392, Teodósio proíbe os sacrifícios públicos pagãos; as vestais perdem o apoio do Estado (Graciano retirou-lhes as receitas em 382; a última vestal documentada é de 385) e a ordem desaparece nessas décadas.' },
    { d: '438 – 534 d.C.', t: 'Códigos de leis', x: 'O Código de Teodósio II (438) reúne as leis imperiais; Justiniano manda compilar o *Codex* (529), o *Digesto* e as *Institutas* (533) e as *Novelas*. O conjunto, o *Corpus Iuris Civilis*, será redescoberto no Ocidente a partir do século XI.' },
    { d: 'séculos V – IX d.C.', t: 'Do latim às línguas românicas', x: 'Com a queda do Império do Ocidente, o latim falado divide-se, ao longo de séculos, em dialetos que viram línguas distintas, entre elas o galego-português. O latim escrito sobrevive na Igreja, no direito e na ciência.' }
  ] }
];

const mapa = [
  'Roma não era um lugar: era uma rede de cidades onde se reproduzia um mesmo modelo, com templo, fórum, tribunal, teatro, termas e mercado. Este mapa vai do coração religioso e jurídico de Roma, no Fórum e no Capitólio, às cidades da Itália, às províncias e, em especial, à **Lusitânia**.',
  { tabela: { cab: ['Lugar', 'Onde', 'O que ali se vê / aconteceu', 'Porque importa aqui'], linhas: [
    ['Fórum Romano e Capitólio', 'Roma', 'Templos de Vesta, Saturno, César; Casa das Vestais; templo de Júpiter Capitolino', 'Centro religioso, político e judicial'],
    ['Campo de Marte e Panteão', 'Roma', 'Panteão de Adriano; Ara Pacis; assembleias', 'Culto «de todos os deuses» e propaganda de Augusto'],
    ['Catacumbas', 'Via Ápia, Roma', 'Cemitérios subterrâneos judeus e cristãos (séc. II–V)', 'Primeira arte cristã; não eram esconderijos'],
    ['Pompeia e Herculano', 'Campânia, Itália', 'Casas, tabernas, lararia, grafitos (soterradas em 79 d.C.)', 'O quotidiano congelado'],
    ['Óstia', 'Foz do Tibre', 'Insulae, mitreus, sinagoga, termas', 'O porto de Roma: religiões e profissões'],
    ['Verona', 'Norte de Itália', 'Palimpsesto das Institutas de Gaio', 'Como o direito romano foi redescoberto'],
    ['Beirute (Berytus)', 'Líbano', 'Célebre escola de direito (séc. III–VI)', 'Formação de juristas do Oriente'],
    ['Constantinopla', 'Turquia', 'Onde Justiniano mandou compilar o Corpus Iuris', 'Fim da evolução do direito romano'],
    ['Nîmes (Nemausus)', 'Sul de França', 'Maison Carrée, templo do culto imperial (séc. I)', 'Melhor templo romano conservado'],
    ['Augusta Emerita (Mérida)', 'Estremadura, Espanha', 'Teatro (16–15 a.C.), anfiteatro, templo de Diana', 'Capital da Lusitânia'],
    ['Ebora Liberalitas Iulia (Évora)', 'Alentejo', 'Templo romano (sécs. I–II d.C.)', 'Culto imperial na Lusitânia'],
    ['Conímbriga', 'Beira Litoral', 'Casas com mosaicos, termas, fórum', 'Vida urbana numa cidade lusitana'],
    ['Vipasca', 'Aljustrel, Alentejo', 'Duas tábuas de bronze com leis de mineração (séc. II)', 'Direito e economia nas minas'],
    ['Cabeço das Fráguas', 'Guarda, Beira', 'Inscrição rupestre em língua lusitana', 'Religião indígena sob domínio romano'],
    ['Vindolanda', 'Norte de Inglaterra', 'Tabuinhas de madeira com cartas (c. 100 d.C.)', 'Voz de soldados e mulheres']
  ] } },
  { h: 'O Fórum Romano e o Capitólio' },
  'No Fórum, entre a colina do Capitólio e o Palatino, concentravam-se **templos, tribunais (basílicas), a Cúria do Senado e os rostra** (a tribuna dos oradores). Dali os magistrados falavam ao povo, os pretores julgavam e os cortejos triunfais passavam pela Via Sacra. No topo do Capitólio ficava o templo de **Júpiter Ótimo Máximo**, onde os cônsules faziam os votos no primeiro dia do ano e onde os generais vitoriosos agradeciam ao deus no fim do triunfo.',
  { img: 'rrv-tribunal-forum', leg: 'Ilustração gerada por IA. Pretor a julgar num tribunal do Fórum (séc. I a.C.–I d.C.)' },
  { h: 'O templo e a casa das vestais' },
  'O pequeno **templo circular de Vesta**, no Fórum, guardava o fogo sagrado da cidade, que nunca se devia apagar. Ao lado, a **Casa das Vestais** (*Atrium Vestae*) era um grande edifício com pátio de tanques e estátuas das vestais mais antigas. As ruínas que hoje se veem são em boa parte da época imperial (reconstruções depois de incêndios, incluindo o de 64 d.C.).',
  { img: 'rrv-templo-vesta', leg: 'Templo circular de Vesta, Fórum Romano' },
  { img: 'rrv-atrium-vestae', leg: 'Pátio da Casa das Vestais com estátuas de vestais' },
  { h: 'Catacumbas: os cemitérios dos cristãos' },
  'Os cristãos de Roma enterravam os mortos em galerias escavadas no tufo, ao longo das grandes vias, fora da cidade (por lei, não se podia sepultar dentro do pomério). As **catacumbas** (palavra de uso tardio) não eram esconderijos: a sua localização era conhecida. Os judeus também as usaram. As pinturas mais antigas mostram cenas bíblicas, o Bom Pastor, o peixe, a âncora.',
  { h: 'Pompeia e Herculano' },
  'O Vesúvio soterrou em 79 d.C. duas cidades da baía de Nápoles e preservou casas, pinturas, lojas, tabernas, mercados, padarias e grafitos que nenhum texto antigo nos daria. Pompeia teria **cerca de 10 000 a 20 000 habitantes** (estimativa debatida; as mais recentes ficam perto de 11 500). Os altares domésticos (*lararia*), as pinturas de deuses nas esquinas e os templos de Ísis, de Apolo e de Júpiter mostram como a religião invadia a vida diária.',
  { h: 'Óstia: o porto de Roma' },
  'Na foz do Tibre, Óstia era o porto de entrada do trigo e do vinho da capital. Tinha **blocos de apartamentos de vários andares**, termas, lojas de ofícios, a sede de corporações de mercadores e templos de muitos deuses. Conservam-se cerca de dezoito **mitreus** e uma **sinagoga** (a fase mais antiga talvez do século I d.C.; a datação é debatida). Mostra bem como uma cidade romana juntava gente de muitas origens e cultos.',
  { img: 'rrv-mitreu-interior', leg: 'Ilustração gerada por IA. Interior de um mitreu (Óstia, séc. II–III d.C.)' },
  { h: 'Verona, Beirute e Constantinopla: três cidades do direito' },
  'Foi em **Verona**, num manuscrito medieval onde se escrevera por cima de um texto antigo (um palimpsesto), que o historiador Niebuhr reconheceu em 1816 as *Institutas* de Gaio. Em **Beirute** (Berytus) funcionou, entre os séculos III e VI, uma das mais célebres escolas de direito do Império. Em **Constantinopla**, o imperador Justiniano, com o jurista Triboniano, mandou compilar entre 529 e 534 o *Corpus Iuris Civilis*.',
  { h: 'Nîmes e o culto do imperador' },
  'Em **Nîmes** (sul da França), a **Maison Carrée** foi construída por volta de 2 d.C. e dedicada ao culto dos netos e filhos adotivos de Augusto, Gaio e Lúcio César (a inscrição foi reconstituída a partir dos buracos dos pregos das letras). É um dos templos romanos mais bem conservados do mundo e mostra o que seria um templo imperial numa cidade provincial.',
  { h: 'Mérida: a capital da Lusitânia' },
  '**Augusta Emerita**, fundada em 25 a.C. para veteranos de duas legiões, tornou-se capital da província da Lusitânia. Conserva um **teatro** (inaugurado em 16–15 a.C. por iniciativa de Agripa), um anfiteatro, um circo, termas, pontes e aquedutos, e um templo. É a melhor cidade romana para ver, na Península, o conjunto de lugares de culto, espetáculo e justiça.',
  { img: 'rrv-teatro-merida', leg: 'Teatro romano de Mérida' },
  { h: 'Évora e o culto imperial na Lusitânia' },
  'No centro de **Évora** (a romana *Ebora Liberalitas Iulia*) ergue-se um templo de que sobrevivem o pódio de granito e catorze colunas de granito com capitéis e bases de mármore de Estremoz. Chama-se tradicionalmente «templo de Diana», mas esse nome é uma lenda do século XVII; a dedicação mais provável é ao culto imperial, embora Júpiter também seja proposto. A data é dos séculos I–II d.C. (estilo da época flávia), com remodelações.',
  { img: 'rrv-templo-evora', leg: 'Templo romano de Évora' },
  { h: 'Conímbriga: uma cidade lusitana' },
  'Em **Conímbriga** (perto de Condeixa-a-Nova), cidade já existente antes de Roma (o nome tem o elemento celta *-briga*, «colina fortificada»), conservam-se casas com mosaicos e pátios com tanques, termas, um fórum e uma muralha tardia. Mostra o que era a casa romana na Lusitânia, como a **Casa dos Repuxos**, com jardim e jogos de água.',
  { h: 'Aljustrel (Vipasca): a lei da mina' },
  'Em Aljustrel foram achadas, em 1876 e 1906, duas **tábuas de bronze** (as «Tábuas de Vipasca»), do século II d.C. (a segunda menciona Adriano, 117–138). A primeira regula os direitos dos arrendatários dos serviços da povoação mineira (banhos, barbeiros, sapateiros, tinturaria, leilões) e dos mineiros; a segunda, o regime das concessões das minas. É um dos mais importantes textos jurídicos romanos de Portugal e uma fonte rara sobre o dia a dia de uma comunidade mineira, com escravos, condenados e homens livres.',
  { h: 'Cabeço das Fráguas: os deuses antes de Roma' },
  'Numa colina perto da Guarda, uma inscrição gravada na rocha, em **língua lusitana** mas com alfabeto latino, regista uma oferenda de animais (uma ovelha, um porco, um touro) a divindades indígenas, como *Trebopala*. É a prova de que, nas montanhas da Beira, se continuou a falar e a sacrificar à maneira indígena em época romana (a datação é debatida: provavelmente do século I d.C.).',
  { h: 'Vindolanda: cartas do fim do mundo' },
  'No forte de Vindolanda (junto à futura Muralha de Adriano, no norte de Inglaterra), descobriram-se desde 1973 **mais de 1700 tabuinhas de madeira** com texto a tinta, em geral de c. 95–105 d.C.: cartas, listas de compras, relatórios do exército e o convite de aniversário de Cláudia Severa. Dão-nos o latim de todos os dias, dos soldados, dos escravos e das mulheres, longe do latim literário.',
  { h: 'Rotas da religião e do direito' },
  'As ideias e os cultos viajavam com os soldados, os mercadores, os escravos, os governadores e os juristas. Os cultos orientais (Cibele, Ísis, Mitra, o cristianismo) seguiram as rotas do Mediterrâneo; o direito, as das legiões e das chancelarias: um governador provincial julgava segundo o seu **edito**, e o direito local sobrevivia à sombra do direito romano. Em Hispânia, **Vespasiano** concedeu o **direito latino** a todas as comunidades (c. 73–74 d.C.), e as suas cidades receberam leis municipais, de que a *Lex Irnitana* (descoberta em 1981, perto de Sevilha) é a mais completa.'
];

const sociedade = [
  { h: 'A religião romana: ritos, não dogmas' },
  'A religião romana era uma religião **cívica**: os cidadãos deviam à divindade o culto exato e o respeito pelas tradições (o *mos maiorum*); em troca, os deuses protegiam a cidade. O que importava era a **correção do ritual** (a ortopraxia), não a crença interior: um sacrifício com um erro era repetido do início. Não havia Igreja, nem livro sagrado, nem clero profissional: os sacerdotes eram, em regra, os mesmos senadores que governavam a República.',
  { h: 'Os deuses' },
  'Os romanos aceitaram muitos deuses: os antigos deuses itálicos, os que recebiam dos etruscos e dos gregos, e (quando faziam sentido) os dos povos conquistados. A partir do século III a.C. os principais deuses romanos foram **identificados com os gregos**, mas conservaram traços próprios. Mais do que mitos, os romanos tinham **funções**: cada deus tutelava um aspeto da vida.',
  { tabela: { cab: ['Deus (romano)', 'Equivalente grego', 'Domínio', 'Notas'], linhas: [
    ['Júpiter', 'Zeus', 'Céu, raio, juramentos; rei dos deuses', '«Ótimo Máximo»: culto no Capitólio'],
    ['Juno', 'Hera', 'Casamento, mulheres, o Estado', 'Juno Regina; mês de junho'],
    ['Minerva', 'Atena', 'Sabedoria, artesanato, guerra estratégica', 'Tríade capitolina'],
    ['Marte', 'Ares', 'Guerra; pai tradicional de Rómulo e Remo', 'Mês de março; sálios'],
    ['Vénus', 'Afrodite', 'Amor, beleza; mãe de Eneias', 'Venus Genetrix: ancestral de César'],
    ['Apolo', 'Apolo', 'Profecia, cura, música', 'Mesmo nome em Roma; primeiro templo c. 431 a.C.'],
    ['Diana', 'Ártemis', 'Caça, lua, mulheres', 'Culto no monte Aventino'],
    ['Ceres', 'Deméter', 'Cereais, agricultura', 'Associada aos plebeus'],
    ['Vesta', 'Héstia', 'Lareira e fogo da cidade', 'Servida pelas vestais'],
    ['Mercúrio', 'Hermes', 'Comércio, viajantes, mensageiro', 'Culto dos comerciantes'],
    ['Neptuno', 'Posídon', 'Mares, cavalos', 'Neptunália (23 de julho)'],
    ['Vulcano', 'Hefesto', 'Fogo, forja, vulcões', 'Culto em Óstia'],
    ['Jano', '(sem equivalente grego)', 'Portas, começos e fins; janeiro', 'Duas faces; templo de portas abertas em guerra'],
    ['Saturno', 'Crono', 'Semeadura, riqueza, Idade de Ouro', 'Saturnais; templo com o tesouro do Estado'],
    ['Líber e Líbera / Baco', 'Dioniso', 'Vinho, fertilidade; mistérios', 'Bacanais reprimidas em 186 a.C.'],
    ['Fortuna', 'Tique', 'Sorte, destino', 'Muitos santuários, entre eles em Preneste'],
    ['Lares e Penates', '—', 'Proteção da casa, da família e dos alimentos', 'Altar doméstico (*lararium*)']
  ] } },
  { img: 'rrv-augusto-pontifice', leg: 'Augusto de Via Labicana como pontífice máximo, Palazzo Massimo' },
  { h: 'Rituais: sacrifícios, votos e augúrios' },
  'O ato central era o **sacrifício**: oferecia-se aos deuses um animal (um boi, um porco, uma ovelha, uma ave), comendo-se depois, em geral, parte das carnes. Nas grandes purificações da cidade ou dos campos fazia-se o **suovetaurilia**, o sacrifício de um porco, de uma ovelha e de um touro. Os romanos faziam também **votos** (*vota*): promessas de oferendas, se o deus concedesse um favor. Os estudiosos resumem o princípio na fórmula *do ut des*, «dou para que dês», com cautela, porque o culto era mais do que uma troca.',
  { img: 'rrv-suovetaurilia', leg: 'Relevo de suovetaurilia (altar de Domício Aenobarbo), Louvre' },
  { h: 'Adivinhação: ler a vontade dos deuses' },
  'Nenhuma decisão importante se tomava sem **auspícios**. Os **áugures** observavam o voo e o canto das aves dentro de um espaço sagrado delimitado (*templum*); os **harúspices**, de origem etrusca, liam o fígado dos animais sacrificados; os prodígios (chuvas de pedras, partos monstruosos) eram resolvidos com ritos de expiação, por vezes após consulta dos **Livros Sibilinos**, guardados no templo de Júpiter. O que hoje nos parece superstição era uma forma de **consultar os deuses e proteger a decisão política**; Cícero, ele próprio áugure, duvidou da adivinhação no tratado *De divinatione*, mas defendeu o seu uso público.',
  { img: 'rrv-figado-piacenza', leg: 'Fígado de Placência, modelo etrusco de bronze para a adivinhação; Musei Civici, Placência.' },
  { img: 'rrv-augure', leg: 'Ilustração gerada por IA. Áugure a observar o voo das aves (República)' },
  { h: 'Colégios sacerdotais e magistrados' },
  { lista: [
    '**Pontífices:** o colégio mais importante; guardavam o calendário e o direito sagrado. O chefe era o *pontifex maximus*.',
    '**Áugures:** interpretavam os sinais dos deuses.',
    '**Quindecênviros:** guardavam os Livros Sibilinos e os cultos estrangeiros (*quindecimviri sacris faciundis*).',
    '**Epulões:** organizavam os banquetes sagrados.',
    '**Flâmines:** sacerdotes de um só deus; o *flamen Dialis* (de Júpiter) estava sujeito a proibições (não usar anéis, não montar a cavalo, etc.).',
    '**Sálios:** doze sacerdotes de Marte que dançavam e cantavam hinos arcaicos, em março.',
    '**Rex sacrorum:** o «rei dos ritos», sem poder político.',
    '**Fetiais:** realizavam os ritos de declaração de guerra e de tratado.'
  ] },
  { h: 'As vestais' },
  'As **vestais**, em número de seis, eram as únicas sacerdotisas de Estado em Roma. Escolhidas ainda crianças (entre os seis e os dez anos) entre famílias livres, serviam a deusa durante cerca de **trinta anos** (segundo a tradição, dez a aprender, dez a servir e dez a ensinar); deviam ser castas, e as que quebravam o voto podiam ser enterradas vivas (o castigo é descrito pelas fontes, poucas vezes aplicado). Tinham privilégios raros para mulheres romanas: podiam testar, tinham lugar de honra nos espetáculos e era lícito perdoar um condenado que cruzasse o caminho de uma vestal. A ordem durou séculos, até às últimas décadas do século IV d.C.',
  { h: 'O calendário e as festas' },
  'O ano romano era marcado por dezenas de festas públicas. O calendário contava os dias a partir de três pontos fixos de cada mês: as **calendas** (dia 1), as **nonas** (5 ou 7) e os **idos** (13 ou 15), e não por números simples; os dias eram *fastos* (permitidos para tribunais e assembleias) ou *nefastos*. Na República o ano começou em março, até que, em 153 a.C., a posse dos cônsules passou para 1 de janeiro.',
  { img: 'rrv-fasti', leg: 'Fasti Antiates Maiores: fragmentos de um calendário romano pintado sobre reboco, primeira metade do século I a.C.; Palazzo Massimo, Roma.' },
  { tabela: { cab: ['Festa', 'Quando', 'O que era'], linhas: [
    ['Lupercais', '15 de fevereiro', 'Rito de purificação: sacerdotes percorriam o Palatino e batiam com tiras de pele em mulheres, para favorecer a fertilidade'],
    ['Parentais', '13–21 de fevereiro', 'Os romanos visitavam os túmulos e ofereciam alimentos aos antepassados'],
    ['Matronais', '1 de março', 'Festa das mulheres casadas, em honra de Juno Lucina'],
    ['Flora (Floralia)', '28 de abril – 3 de maio', 'Festa da primavera, com jogos e teatro'],
    ['Lemúrias', '9, 11 e 13 de maio', 'Rito doméstico para afastar os espíritos errantes dos mortos'],
    ['Vestais (Vestalia)', '7–15 de junho', 'Festa de Vesta; limpeza do templo'],
    ['Jogos Romanos', 'Setembro', 'Os mais antigos jogos públicos; corridas e teatro'],
    ['Saturnais', '17 de dezembro (depois alargada a vários dias)', 'Festa de inversão: banquetes, presentes, escravos servidos pelos senhores (em parte), jogos de azar'],
    ['Sol Invictus', '25 de dezembro', 'Festa do «Sol Invicto», atestada no calendário de 354 d.C.; liga-se à origem do Natal, assunto debatido']
  ] } },
  { img: 'rrv-saturnalia', leg: 'Ilustração gerada por IA. Banquete das Saturnais numa casa romana (séc. I d.C.)' },
  { h: 'A religião da casa' },
  'Em cada casa, a religião vivia no *lararium*, uma capela, nicho ou pintura com a figura dos **Lares** (espíritos protetores da família), dos **Penates** (protetores das provisões) e do **Génio** do pater familias. De manhã fazia-se uma pequena oferta (incenso, vinho, bolos); nas festas, flores e coroas. Os escravos participavam. O pater familias era o sacerdote da sua casa.',
  { img: 'rrv-lararium-pompeia', leg: 'Lararium com Lares e Génio, casa de Pompeia (p. ex. Casa dos Vetti)' },
  { h: 'O culto do imperador' },
  'Depois da morte de César (divinizado em 42 a.C.) e de Augusto (14 d.C.), os imperadores falecidos podiam ser declarados deuses (*divi*) pelo Senado. O imperador vivo recebia um culto indireto, ligado ao seu Génio ou à deusa Roma. No Oriente havia cultos ao imperador vivo; no Ocidente, em colónias como Évora, Nîmes ou Mérida, **flâmines** locais encarregavam-se do culto. Para muitos cidadãos era uma forma de expressar lealdade, não uma «adoração» no sentido cristão.',
  { h: 'Cultos orientais e de mistérios' },
  'Cultos que prometiam salvação pessoal ou uma relação mais íntima com o deus espalharam-se pelo Império: o de **Cibele** (oficial desde 204 a.C.), o de **Ísis** (com templo em Pompeia), o de **Mitra** e o de **Baco**. O **mitraísmo**, praticado por grupos de homens (soldados, funcionários, mercadores) em santuários subterrâneos (*mitreus*), girava em torno de uma cena de um touro a ser morto por Mitra (*tauroctonia*). Embora o nome do deus seja persa, o culto, tal como era praticado, foi uma criação do mundo romano, dos séculos I a IV d.C.; o que se sabe dos seus mistérios vem sobretudo de imagens e de poucos textos.',
  { img: 'rrv-mitra-tauroctonia', leg: 'Mitra a sacrificar o touro: relevo de mármore de Fiano Romano, séculos II–III d.C.; Louvre (Ma 3441).' },
  { h: 'Judeus e cristãos no Império' },
  'Os **judeus** tinham comunidades por todo o Império e, em geral, foram tolerados nos seus costumes (o repouso ao sábado, a isenção do culto imperial), mas houve conflitos graves, como as revoltas de 66–73 d.C. (destruição do Templo, em 70) e de 132–135 d.C. Os **cristãos**, a princípio vistos como uma seita judaica, tornaram-se visíveis no século I; recusavam o culto aos deuses e ao imperador, o que lhes valeu a suspeita de ateísmo e de deslealdade. Houve perseguições locais e esporádicas, e algumas gerais (Décio, Valeriano, Diocleciano). Estima-se que fossem uma minoria, talvez cerca de 10% da população no ano 300 (as estimativas vão de 5 a 15%), mas os números são muito debatidos.',
  { img: 'rrv-catacumbas', leg: 'Fresco da cripta de Lucina nas catacumbas de São Calisto, Roma.' },
  { img: 'rrv-bom-pastor', leg: 'Bom Pastor, mosaico do Mausoléu de Gala Placídia, Ravena' },
  { h: 'De religião perseguida a religião do Estado' },
  'Em 311, Galério concedeu tolerância aos cristãos. Em 313, Constantino e Licínio, em Milão, garantiram liberdade de culto a todos. Constantino favoreceu a Igreja, convocou o concílio de Niceia (325) e fez do domingo dia de descanso (321). Em 380, Teodósio I declarou o cristianismo niceno a religião dos povos do Império (edito de Tessalónica); em 391–392 proibiu os sacrifícios pagãos. O paganismo não desapareceu de um dia para o outro: durou séculos, sobretudo no campo (*pagani*, «gente do campo», é a origem da palavra «pagão», explicação debatida).',
  { h: 'Os mortos' },
  'Os romanos temiam os mortos sem sepultura. Os **funerais** das famílias nobres incluíam uma procissão com máscaras de cera dos antepassados (as *imagines*), usadas por atores, e um elogio fúnebre (*laudatio funebris*) feito no Fórum. A cremação foi a regra até ao século II d.C., quando a inumação passou a ser mais frequente. Os túmulos ficavam **fora da cidade**, ao longo das estradas (a Via Ápia é o exemplo clássico), e os mais pobres podiam inscrever-se numa associação funerária (*collegium funeraticium*) que garantia um enterro digno.',
  { h: 'O direito romano: o que é e donde vem' },
  'O direito foi, para os romanos, tão importante como a religião. Nasceu como um **direito sagrado**, guardado pelos pontífices, e tornou-se, a partir do século III a.C., um saber **laico** estudado por juristas. Os historiadores distinguem o *ius civile* (direito dos cidadãos romanos), o *ius gentium* («direito das gentes», aplicável também aos estrangeiros) e o direito pretório (criado pelos pretores).',
  { tabela: { cab: ['Fonte de direito', 'O que era'], linhas: [
    ['*Leges* (leis)', 'Aprovadas pelas assembleias do povo; de início a única fonte formal'],
    ['*Plebiscita*', 'Decisões da assembleia da plebe, equiparadas a lei depois da Lex Hortensia (287 a.C.)'],
    ['*Senatus consulta*', 'Pareceres do Senado, com força de lei no Império'],
    ['*Edicta* dos magistrados', 'Programa anual de cada pretor, que indicava em que casos daria ação em tribunal; fonte criativa de direito'],
    ['*Responsa prudentium*', 'Pareceres de juristas, com enorme autoridade'],
    ['*Constitutiones*', 'Decisões dos imperadores (decretos, rescritos, editos): principal fonte a partir do século II']
  ] } },
  { h: 'As Doze Tábuas' },
  'As **Doze Tábuas** (c. 451–450 a.C.) foram a primeira lei escrita de Roma, exposta no Fórum, que os rapazes aprendiam de cor ainda no tempo de Cícero. Tratavam do processo, das dívidas, do poder do pai, da propriedade, dos delitos e dos funerais. O texto perdeu-se; conhecemos-lhe fragmentos por citações. Tinham regras duras (o devedor insolvente podia ser preso e, em teoria, vendido como escravo) e outras que visavam limitar a vingança privada.',
  { h: 'Pretores, juízes e processo' },
  'O **pretor**, magistrado eleito, não julgava o caso: dirigia a primeira fase do processo (*in iure*) e fixava o problema jurídico numa **fórmula**; depois, um **juiz** privado (*iudex*), escolhido pelas partes, decidia (*apud iudicem*). Os advogados (*patroni*) eram oradores, como Cícero, que discursavam nos casos mais conhecidos. Na época imperial, o processo passou a ser conduzido do princípio ao fim por um magistrado (*cognitio extra ordinem*), com tribunais de recurso e, em última instância, o imperador.',
  { h: 'Os juristas' },
  'Os **jurisconsultos** (*iuris prudentes*) davam pareceres sobre casos reais. Alguns imperadores concederam a certos juristas o direito de dar pareceres vinculativos (*ius respondendi*). Os grandes nomes (Sálvio Juliano, Gaio, Papiniano, Ulpiano, Paulo, Modestino) escreveram entre os séculos I e III d.C. Das suas obras, citadas no *Digesto* de Justiniano (533), vem boa parte do que se sabe do direito clássico.',
  { h: 'Cidadania' },
  'O estatuto de cidadão (*civis Romanus*) dava direitos ao casamento legal, ao voto (em Roma), à propriedade protegida, ao recurso a Roma. Em certas situações, um cidadão não podia ser torturado nem castigado sem julgamento (episódio do apóstolo Paulo, nos Atos dos Apóstolos). A cidadania foi sendo alargada: aos aliados itálicos depois da Guerra Social (90–88 a.C.), a muitos provinciais, e, em 212, pela *Constitutio Antoniniana*, à grande maioria dos habitantes livres do Império. Havia ainda o **direito latino**, estatuto intermédio de muitas cidades provinciais, entre elas as da Hispânia desde Vespasiano.',
  { h: 'Família e poder paterno' },
  'No direito romano, o **pater familias**, o homem mais velho da casa, tinha o poder (*patria potestas*) sobre os filhos, os netos, os escravos e, em certos casamentos, a mulher. Em teoria, podia castigar gravemente e até condenar à morte (*ius vitae necisque*), mas na prática havia limites sociais, e o poder sobre os filhos só cessava com a morte do pai ou a emancipação. Só quem não estava sob poder de outrem (*sui iuris*) podia ter propriedade própria; os filhos adultos, em teoria, tinham apenas um pecúlio.',
  { h: 'Propriedade, contratos e testamentos' },
  'O direito romano distinguiu com rigor a **posse** da **propriedade**, os direitos sobre coisas alheias (usufruto, servidões) e as obrigações (compra e venda, arrendamento, mandato, sociedade, empréstimo). Criou o **contrato consensual** (basta o acordo), o **testamento**, a **herança** (com quotas mínimas para os filhos), a **tutela** e a **curatela**. Conceitos como a *bona fides* (boa-fé) e a *aequitas* (equidade) tornaram-se princípios gerais.',
  { h: 'Crimes e castigos' },
  'Em Roma, a maior parte dos delitos privados (roubo, dano) resolvia-se com **indemnização** à vítima. Os crimes públicos (traição, homicídio, corrupção, adultério, magia) foram, a partir do século II a.C., julgados por tribunais permanentes (*quaestiones*). No Império, as penas dependiam da **classe social**: os *honestiores* (elites) podiam ser desterrados ou decapitados; os *humiliores* (gente comum) condenados a trabalhos forçados, às minas, às feras, à cruz ou à fogueira. A pena de morte por **crucificação** era reservada a escravos e a gente humilde; um cidadão romano raramente a sofria. A prisão servia para guardar o réu até ao julgamento, não como pena.',
  { h: 'Codificar o direito: de Teodósio a Justiniano' },
  'Com o crescimento das fontes, tornou-se necessário **compilar**. O **Código de Teodósio II** (438) reuniu as leis imperiais desde Constantino. Justiniano, no Oriente, mandou compilar três obras: o *Codex* (529, atualizado em 534), o *Digesto* (533), antologia de juristas clássicos em 50 livros, e as *Institutas* (533), manual para estudantes. O conjunto, completado pelas *Novelas*, é o **Corpus Iuris Civilis**.',
  { img: 'rrv-corpus-iuris', leg: 'Página de título do Corpus Iuris Civilis, edição de Dionísio Godofredo, 1583.' },
  { h: 'O latim' },
  'O **latim**, língua indo-europeia do ramo itálico, era falado no Lácio e espalhou-se com as legiões, os colonos e a administração. Distingue-se o **latim arcaico** (até c. 100 a.C.), o **latim clássico** (de Cícero e Virgílio: escrito, literário), o **latim tardio** e o **latim vulgar**, a língua falada, de que descendem as línguas românicas. No Oriente, a língua comum era o **grego**, que os romanos cultos também falavam. O alfabeto latino tinha 23 letras no período clássico (sem J, U, W). Em Portugal, o latim substituiu as línguas pré-romanas (celta, lusitano e outras), de que restam topónimos, como os terminados em *-briga* («colina fortificada»), e algumas palavras.',
  { h: 'A escrita e os livros' },
  'Escrevia-se em **papiro** (importado do Egito) e em **pergaminho** (cada vez mais, a partir do século IV), com tinta e cálamo, e em **tabuinhas de cera** com um estilete (*stilus*) para notas, contas e cartas curtas. As tabuinhas de madeira de Vindolanda são cartas a tinta. Os livros eram **rolos** (*volumina*) copiados por escravos; no século I d.C. surge o **códice** (páginas cosidas), que se tornou o formato corrente no século IV. A **epigrafia**, escrita em pedra e bronze, era omnipresente: leis, dedicatórias, epitáfios, listas de magistrados.',
  { img: 'rrv-vindolanda-tabuinha', leg: 'Tabuinha de Vindolanda com tinta, British Museum' },
  { h: 'Os números e a escrita romana' },
  'Os números romanos (I, V, X, L, C, D, M) serviam para inscrever, mas não para calcular: o cálculo fazia-se com o **ábaco** e com os dedos. Os romanos não tinham zero nem notação posicional. Os nomes: um cidadão tinha três (*tria nomina*): praenomen (nome próprio), nomen (da família ou *gens*) e cognomen (apelido); as mulheres usavam o nome da gens no feminino (Cornélia, Júlia).',
  { h: 'A sociedade romana: ordens e classes' },
  'A sociedade era hierárquica e legalmente desigual. Dividia-se em **cidadãos e não cidadãos**, em **livres e escravos**, e entre os livres em **ordens** definidas pela fortuna e pela dignidade.',
  { tabela: { cab: ['Grupo', 'Quem eram', 'Notas'], linhas: [
    ['Ordem senatorial', 'Membros (e famílias) do Senado', 'Fortuna mínima de 1 milhão de sestércios (Augusto); toga com banda larga púrpura (*laticlavus*)'],
    ['Ordem equestre (cavaleiros)', 'Homens ricos de negócios e funcionários', 'Mínimo de 400 000 sestércios; banda estreita; administrava e coletava impostos'],
    ['Decuriões', 'Elites locais das cidades', 'Faziam parte do conselho municipal; pagavam muitos custos públicos'],
    ['Plebe livre', 'Artesãos, comerciantes, camponeses, soldados', 'Maioria dos cidadãos; muitos dependiam de patronos'],
    ['Libertos (*liberti*)', 'Escravos libertados', 'Cidadãos com restrições; os filhos nasciam livres e plenamente cidadãos'],
    ['Escravos (*servi*)', 'Propriedade de outrem', 'Sem direitos legais; podiam ter pecúlio; estimativas variam muito sobre a sua percentagem']
  ] } },
  { img: 'rrv-estatua-togado', leg: 'Togado Barberini, figura romana com retratos de antepassados; Centrale Montemartini, Museus Capitolinos, Roma.' },
  { h: 'Patronos e clientes' },
  'O laço do **patronato** estruturava a sociedade: um cliente (mais pobre) cumprimentava o patrono de manhã (*salutatio*), apoiava-o politicamente e recebia dele proteção, comida, dinheiro ou ajuda em tribunal. Quanto mais clientes, mais prestígio. Os libertos eram clientes obrigatórios do antigo dono. Era um sistema de favores, não de igualdade.',
  { h: 'Escravatura' },
  'A escravatura foi uma **instituição central**. As pessoas tornavam-se escravas por **guerra** (os cativos), por **nascimento** (os *vernae*, filhos de escravas), pelo comércio (inclusive pirataria) e pelo abandono de recém-nascidos. Trabalhavam nas **minas**, nos **campos**, nas **casas** e nos ofícios, e alguns, os mais cultos (gregos, sobretudo), eram secretários, professores, médicos ou contabilistas. A percentagem de escravos foi estimada em cerca de **20 a 30%** da população de Itália no tempo de Augusto e **10 a 20%** no resto do Império (valores muito debatidos). As condições variavam enormemente, e os das minas eram terríveis.',
  { img: 'rrv-coleira-escravo', leg: 'Coleira de escravo em bronze com inscrição; Museo Nazionale Romano (65043).' },
  { h: 'Alforria, libertos e revoltas' },
  'Muitos escravos eram **libertados** (alforria), por testamento, por cerimónia formal ou por decisão do dono, por vezes em troca de dinheiro do pecúlio. As leis de Augusto (a *Lex Aelia Sentia*, 4 d.C., e a *Lex Fufia Caninia*, 2 a.C.) limitaram o número e as condições. O **liberto** ficava ligado ao antigo dono por obrigações; o seu filho já era plenamente cidadão. Houve **revoltas** de escravos, das quais a mais célebre foi a de **Espártaco** (73–71 a.C.). Escritores como **Séneca** (carta 47) defenderam que os escravos são também seres humanos, e no século II os imperadores (Antonino Pio, Adriano) limitaram em teoria o poder de morte do dono.',
  { h: 'As mulheres' },
  'As mulheres romanas **não votavam nem exerciam magistraturas**, e estavam sob a autoridade de um homem (pai, marido ou tutor). Mas podiam **ter propriedade, herdar, fazer testamento, gerir negócios** e ter património próprio, sobretudo se o casamento fosse «sem *manus*», o tipo mais comum no Império. As mulheres das elites tinham influência política indireta (Lívia, mulher de Augusto); as sacerdotisas (vestais, flaminicas) tinham papel público; muitas mulheres de menor estatuto trabalhavam como parteiras, tecelãs, vendedoras, taberneiras, escritoras, médicas (*medicae*). Em 42 a.C. Hortênsia, filha de um orador célebre, discursou no Fórum contra um imposto sobre as mulheres ricas (relato de Apiano).',
  { img: 'rrv-retrato-fayum', leg: 'Retrato funerário de mulher do Egito romano, c. 200 d.C., encáustica sobre madeira; Museu Britânico (EA 65344).' },
  { h: 'Casamento e divórcio' },
  'O casamento romano era um **acordo privado**, sem cerimónia religiosa obrigatória, que exigia o consentimento e a intenção de viver como marido e mulher (*affectio maritalis*). Os romanos de classe alta casavam cedo: a lei fixava os mínimos de 12 anos para as raparigas e 14 para os rapazes; as raparigas das elites casavam, em regra, entre os 12 e os 18 anos. A noiva levava um **dote**. A cerimónia incluía a mão direita unida (*dextrarum iunctio*), o véu cor de laranja, uma procissão à casa do noivo. O **divórcio** era fácil e frequente, bastando a vontade de um dos cônjuges.',
  { img: 'rrv-casamento', leg: 'Ilustração gerada por IA. Cerimónia de casamento romana (séc. I d.C.)' },
  { h: 'Crianças e educação' },
  'Um recém-nascido era reconhecido pelo pai, que o levantava do chão (*tollere liberum*); o abandono (exposição) de crianças indesejadas, sobretudo meninas e deficientes, era legal, embora a sua frequência seja debatida. A mortalidade infantil era elevada: a esperança de vida à nascença (talvez 20–30 anos) reflete-a, e quem passava a infância tinha boas hipóteses de chegar aos cinquenta. As crianças usavam, ao pescoço, uma **bula** (amuleto) e os rapazes livres vestiam a toga com banda púrpura (*praetexta*) até à toga viril (*toga virilis*), por volta dos 14–17 anos, na festa dos Liberais, a 17 de março.',
  { h: 'A escola' },
  'Não havia ensino público obrigatório: as famílias escolhiam. Dos sete aos onze anos, o rapaz (e, por vezes, a rapariga) ia ao **ludus litterarius**, com um mestre (*litterator*) que ensinava a ler, a escrever e a contar. Depois, o **grammaticus** ensinava gramática e literatura (Homero, Virgílio), e por volta dos 15 ou 16 anos o **rhetor** ensinava a arte de falar, indispensável à carreira pública e ao tribunal. Os filhos das elites tinham um **pedagogo**, em regra escravo grego, que os acompanhava. **Quintiliano** foi o grande teórico: na sua *Institutio oratoria* (c. 95 d.C.) defendeu um ensino com paciência e sem castigos físicos excessivos. Estima-se que apenas uma minoria soubesse ler e escrever (talvez cerca de 10% no Império, segundo W. Harris; estimativa muito debatida).',
  { img: 'rrv-escola-ludus', leg: 'Ilustração gerada por IA. Aula num ludus litterarius (séc. I d.C.)' },
  { img: 'rrv-fresco-safo', leg: 'Jovem com estilete e tabuinhas, tradicionalmente chamada «Safo», fresco de Pompeia; MANN (9084).' },
  { h: 'A casa: domus, insula e villa' },
  'Os ricos viviam na **domus**, de um só piso, voltada para o interior: uma entrada (*fauces*), o **átrio** com tanque de chuva (*impluvium*), o escritório (*tablinum*), os quartos (*cubicula*), o **triclínio** (sala de jantar), o **peristilo** (pátio com jardim) e a cozinha. À frente havia lojas (*tabernae*). Os pobres viviam em **insulae**, blocos de apartamentos de vários andares, sem água corrente nem cozinha e com risco de incêndio e de desabamento; Augusto fixou a altura máxima em 70 pés romanos (c. 21 m) e Trajano em 60. No campo, os grandes proprietários tinham **villae**: casas senhoriais com exploração agrícola.',
  { img: 'rrv-domus-atrio', leg: 'Ilustração gerada por IA. Átrio de uma domus rica (Pompeia, séc. I d.C.)' },
  { img: 'rrv-rua-insula', leg: 'Ilustração gerada por IA. Rua de uma cidade romana com insulae (Óstia, séc. II d.C.)' },
  { h: 'Mobiliário, luz e aquecimento' },
  'O mobiliário era simples: camas e **leitos** de jantar, mesas, cadeiras (em geral para os mais velhos), arcas e cestos. A luz vinha de **lucernas** (candeias de azeite). Para aquecer, usavam-se braseiros; nas termas e em algumas villae havia **hipocausto** (ar quente por baixo do pavimento). As paredes eram pintadas, e os chãos, nas casas ricas, cobertos de **mosaicos**. As casas urbanas ricas tinham água canalizada; as dos pobres, não.',
  { h: 'O que se comia' },
  'A base da dieta era **pão** (trigo ou cevada), **papas** (*puls*), azeite, vinho, legumes, queijo, peixe e, para os mais ricos, carne. O vinho bebia-se **diluído em água**. O **garum**, molho de peixe fermentado, era um condimento universal; na Lusitânia, a salga de peixe e a produção de garum, por exemplo em Tróia (Setúbal), foram importantes. Não havia tomate, batata, milho, nem açúcar (usava-se mel). O dia tinha três refeições: *ientaculum* (pequeno-almoço), *prandium* (almoço leve) e a **cena**, ao fim da tarde, a refeição principal. O único livro de receitas conservado, o *De re coquinaria*, atribui-se a um Apício, mas foi compilado mais tarde (séculos IV–V d.C.).',
  { img: 'rrv-triclinio-banquete', leg: 'Ilustração gerada por IA. Banquete num triclínio (Roma, séc. I d.C.)' },
  { h: 'Tabernas e comida de rua' },
  'Muitos pobres não tinham cozinha em casa e comiam em **tabernas** (*popinae*) e **termopólios**, balcões com panelas embutidas que vendiam comida quente e vinho. Pompeia conservou dezenas. A «ceia à romana» deitados em leitos era para convivas de classe alta; o comum dos romanos comia sentado.',
  { h: 'O vestuário' },
  'A peça base era a **túnica**, de lã ou linho, usada por homens e mulheres. Por cima, o cidadão usava a **toga**, grande manto de lã em semicírculo, obrigatória em ocasiões formais e símbolo da cidadania; a banda púrpura marcava o estatuto. As mulheres casadas usavam a **stola** (vestido comprido) e a **palla** (manto). No dia a dia usavam-se mantos como a **paenula** (capa de capuz) ou o *sagum* do soldado. Calçavam **sandálias**, **sapatos** (*calcei*) e, os soldados, as botas *caligae*. A seda era um luxo importado da China; o algodão, raro. Os penteados femininos seguiam as modas da corte imperial.',
  { h: 'Higiene, termas e cosméticos' },
  'Os romanos tinham fama de limpos. As **termas** públicas eram frequentadas por todos os grupos, a um preço módico, com salas quentes (*caldarium*), mornas (*tepidarium*) e frias (*frigidarium*), ginásio, biblioteca e jardins. Os banhos eram também locais de encontro e de negócios. Os homens depilavam-se por vezes e as mulheres usavam pós, perfumes e pinturas. Não havia sabão como o nosso: untavam-se com azeite e raspavam-no com o **estrígil**.',
  { img: 'rrv-termas-banho', leg: 'Ilustração gerada por IA. Área masculina de umas termas romanas, século II d.C.; reconstituição conjetural.' },
  { h: 'Jogos de circo e anfiteatro' },
  'Os **jogos** (*ludi*) e os **espetáculos** (*munera*) eram parte do calendário religioso e da política: os magistrados organizavam-nos para ganhar o favor do povo («pão e circo» é uma fórmula do satírico Juvenal). Nas **corridas de carros**, no **Circo Máximo** de Roma, que podia receber muitas dezenas de milhares de espetadores (estimativas de 150 000 a 250 000 são discutíveis), competiam equipas identificadas por cores (as quatro facções: brancos, vermelhos, azuis e verdes), com enorme paixão popular. Os **gladiadores** combatiam no anfiteatro (o Coliseu foi inaugurado em 80 d.C.); a origem remonta a rituais funerários do século III a.C. Eram escravos, condenados ou voluntários; os combates nem sempre acabavam em morte, pois um gladiador treinado custava muito dinheiro.',
  { img: 'rrv-circo-corrida', leg: 'Ilustração gerada por IA. Corrida de quadrigas no Circo Máximo (séc. II d.C.)' },
  { img: 'rrv-mosaico-gladiadores', leg: 'Mosaico de gladiadores, Galleria Borghese' },
  { h: 'Teatro, música e jogos de mesa' },
  'No **teatro**, as comédias de Plauto e de Terêncio e depois o **mimo** e o **pantomimo** (dança mimada, com máscara) divertiam o público. O primeiro teatro permanente de pedra de Roma foi o de Pompeu (55 a.C.). Havia **música** em quase todas as ocasiões (flautas, liras, órgão hidráulico, trompetes militares). Jogavam-se **dados** (*tesserae*), ossinhos (*tali*), jogos de tabuleiro como os *latrunculi* (uma espécie de jogo de estratégia) e as *tabulae* (parente do gamão); o jogo a dinheiro era formalmente proibido, mas frequente, e permitido durante as Saturnais.',
  { h: 'Medicina' },
  'A medicina romana foi, em grande medida, **grega**. Segundo Plínio, o primeiro médico grego a estabelecer-se em Roma foi Arcágato (219 a.C.). Havia médicos de formação (muitas vezes escravos ou libertos gregos), parteiras, curandeiros e boticários, e a cura procurava-se também nos **templos de Esculápio**. Médicos importantes: **Celso** (século I d.C., *De medicina*), **Sorano** (ginecologia), **Dioscórides** (plantas medicinais, em grego) e **Galeno**. Os instrumentos cirúrgicos (bisturis, pinças, cateteres, espéculos) eram sofisticados e conhecemos exemplares de Pompeia. Não havia teoria dos micróbios; as doenças explicavam-se pelos «humores» ou por miasmas.',
  { img: 'rrv-medico-consulta', leg: 'Ilustração gerada por IA. Médico a examinar um doente em casa (séc. II d.C.)' },
  { img: 'rrv-instrumentos-cirurgicos', leg: 'Fotografia histórica de instrumentos cirúrgicos romanos de Pompeia; Museu Arqueológico Nacional de Nápoles, arquivo Wellcome.' },
  { h: 'Saúde pública e hospitais' },
  'Os romanos construíram aquedutos, esgotos (a *Cloaca Maxima*) e latrinas públicas, e o exército tinha **hospitais de campanha** (*valetudinaria*), com médicos militares. Havia **archiatri**, médicos pagos pelas cidades. Mas as doenças infecciosas (malária, tifo, tuberculose) e as pestes (como a «peste Antonina», c. 165–180 d.C.) matavam muita gente.',
  { h: 'Trabalho e ofícios' },
  'Cerca de 80% da população vivia da **agricultura**. Nas cidades, trabalhava-se como artesão (oleiros, tecelões, ferreiros, pedreiros), comerciante, taberneiro, transportador, escriba ou professor. Os ofícios organizavam-se em **corporações** (*collegia*), com carácter religioso e funerário, e protetores comuns. O dia dividia-se em **doze horas de dia** e **doze de noite**, de duração variável conforme a estação; a semana tinha oito dias (*nundinae*, com dia de mercado), até se generalizar a semana de sete dias, que Constantino consagrou em 321 como dia de descanso, ao domingo.',
  { h: 'A economia' },
  'A economia era sobretudo agrária (cereais, vinha, olival) mas com forte comércio no Mediterrâneo. O trigo do Egito e da África alimentava Roma; o azeite da Bética e o vinho da Gália seguiam em **ânforas**: o monte Testaccio, em Roma, é um morro de cacos de ânforas de azeite. Em Hispânia, a prata e o cobre das minas (incluindo as de Vipasca), o azeite, o garum e o vinho eram exportados. O Estado cobrava impostos sobre as terras e as pessoas (nas províncias), taxas aduaneiras (*portoria*), e, a cidadãos, um imposto de 5% sobre heranças. Pagava a soldados e funcionários: um legionário de Augusto ganhava 225 denários (900 sestércios) por ano.',
  { h: 'A moeda' },
  'O sistema monetário baseava-se no **denário** de prata (de c. 211 a.C.), o **sestércio** (um quarto de denário), o **asse** (cobre) e, a partir de César e Augusto, o **áureo** de ouro (25 denários). Os imperadores punham o seu retrato nas moedas, que serviam também de **propaganda**. A partir do século III, a prata das moedas foi sendo diluída e a inflação disparou; Diocleciano reformou a moeda (294) e tentou fixar preços (301); Constantino criou em 309 o **sólido** de ouro, que se manteve estável durante séculos no Oriente.',
  { img: 'rrv-denario-eid-mar', leg: 'Denário de prata de Bruto «EID MAR», 42 a.C.; Museu Britânico (1860,0328.124).' },
  { h: 'Dinheiro e crédito' },
  'Os romanos conheciam o **empréstimo a juros**, os banqueiros (*argentarii*) e a **escrita contabilística**; o juro legal máximo ficou nos 12% anuais (as famosas «centesimae» mensais de 1%), valor frequentemente excedido. Para o comércio marítimo havia empréstimos de risco (*faenus nauticum*). Grandes fortunas formaram-se na agricultura, nos contratos públicos e nas guerras.'
];

const personalidades = [
  'Estas 15 figuras mostram diferentes lados da religião, do direito e da vida romana: sacerdotes lendários, magistrados, juristas, escritores, médicos e mulheres. Para os imperadores e generais, veja a página «Imperadores e grandes figuras». As datas são convencionais; o que é lenda diz-se.',
  { h: 'Numa Pompílio (tradição: c. 715 – 673 a.C.)' },
  'Segundo a tradição, foi o **segundo rei de Roma**, um sabino escolhido pelos romanos por ser homem piedoso. Teria criado os colégios sacerdotais, o calendário de doze meses e o templo de Jano. É figura **lendária**: não há prova de que tenha existido, mas os romanos viam-no como o fundador da sua religião.',
  { h: 'Ápio Cláudio Cego (c. 340 – c. 273 a.C.)' },
  'Censor em 312 a.C. (cônsul em 307 e 296), mandou construir a **Via Ápia** (a «rainha das estradas») e o primeiro aqueduto de Roma, a *Aqua Appia*. Segundo a tradição, ficou cego em idade avançada e, mesmo assim, convenceu o Senado a rejeitar a paz com Pirro. O seu nome liga-se também, na tradição, a reformas da escrita e à jurisprudência. Os detalhes são tradição.',
  { h: 'Catão, o Censor (234 – 149 a.C.)' },
  'Político e escritor, defensor da frugalidade antiga e inimigo da influência grega. Foi censor em 184 a.C. Escreveu o *De agri cultura*, o mais antigo texto latino em prosa que chegou completo, e as *Origines*, a primeira história de Roma em latim. É famoso por terminar discursos com *Carthago delenda est*, «Cartago tem de ser destruída» (a forma exata é tradição). Segundo Plutarco, aconselhava vender os escravos velhos e doentes, o que mostra a dureza do sistema.',
  { h: 'Cornélia, mãe dos Gracos (c. 190 – c. 115 a.C.)' },
  'Filha de Cipião, o Africano, e mãe de Tibério e Caio Graco, tornou-se o modelo da **matrona romana**: educou os filhos, foi mulher culta e teve influência política. Conta-se (Valério Máximo) que, quando uma visita lhe mostrou as suas joias, ela respondeu apontando para os filhos: «estas são as minhas joias». A anedota é tradição.',
  { h: 'Cícero (106 – 43 a.C.)' },
  'O maior orador romano, advogado, político e filósofo, cônsul em 63 a.C. Os seus discursos, cartas (cerca de 900 conservam-se) e tratados (*De re publica*, *De legibus*, *De officiis*, *De divinatione*) são a principal fonte da religião, do direito e da vida da República tardia. Foi áugure. Moldou o latim literário e o vocabulário político e filosófico europeu. Foi assassinado por ordem de Marco António, depois das proscrições de 43 a.C.',
  { img: 'rrv-ciceron-busto', leg: 'Busto de Cícero, Museus Capitolinos' },
  { h: 'Séneca (c. 4 a.C. – 65 d.C.)' },
  'Nascido em Córdova (Hispânia), filósofo estoico, escritor e conselheiro de Nero. Nas *Cartas a Lucílio* (carta 47) defendeu que os escravos «são também seres humanos», uma posição rara para a época. Foi forçado a suicidar-se por Nero, depois de implicado, talvez injustamente, na conspiração de Pisão.',
  { h: 'Plínio, o Velho (23/24 – 79 d.C.)' },
  'Oficial, administrador e naturalista. Escreveu a **História Natural** (*Naturalis historia*), enciclopédia de 37 livros sobre geografia, plantas, animais, medicina, arte, minerais, onde cita centenas de autores. Morreu na erupção do Vesúvio, em 79, quando comandava a frota de Miseno e tentou socorrer pessoas. Hispânia aparece muitas vezes na sua obra: foi procurador na Tarraconense.',
  { h: 'Plínio, o Moço (c. 61 – c. 113 d.C.)' },
  'Sobrinho e filho adotivo de Plínio, o Velho; advogado, senador e governador da Bitínia. As suas **cartas** descrevem a vida das elites, a erupção do Vesúvio (que presenciou jovem) e, no livro 10, a troca de correspondência com Trajano, que inclui a pergunta, c. 112, sobre como tratar os cristãos. É a primeira descrição romana, por um funcionário, dos cristãos e dos seus ritos.',
  { h: 'Quintiliano (c. 35 – c. 100 d.C.)' },
  'Nascido em Calagurris (hoje Calahorra, Hispânia), foi advogado e titular de uma cátedra de retórica paga pelo Estado, criada por Vespasiano. A sua **Institutio oratoria** (c. 95 d.C.), em doze livros, é um tratado sobre a formação do orador desde a infância, e fonte preciosa sobre a **educação romana**.',
  { h: 'Marcial (c. 38 – c. 104 d.C.)' },
  'Poeta nascido em Bílbilis (Hispânia), viveu em Roma, onde publicou os seus **Epigramas** (86–103 d.C.): pequenos poemas satíricos sobre banhos, banquetes, médicos, advogados, vizinhos, patronos e jogos. É uma das melhores fontes sobre o dia a dia da Roma flaviana, vista com humor e ironia. Regressou a Hispânia no fim da vida.',
  { h: 'Gaio (século II d.C.)' },
  'Jurista de que quase nada se sabe, nem sequer o nome completo (Gaio é um praenomen). Provavelmente professor de direito, ativo entre os reinados de Adriano e de Cómodo, escreveu as **Institutas** (c. 161 d.C.), manual de direito que se conservou numa cópia de Verona (descoberta em 1816). É a melhor exposição do direito privado clássico e serviu de modelo às Institutas de Justiniano.',
  { h: 'Ulpiano (c. 170 – c. 223 d.C.)' },
  'Domício Ulpiano, jurista natural de Tiro (Fenícia), foi conselheiro de Septímio Severo e prefeito do pretório de Severo Alexandre; foi morto pelos pretorianos, c. 223 (a data é discutida). Escreveu muito: cerca de **um terço do Digesto** de Justiniano é de sua autoria. A frase «viver honestamente, não prejudicar ninguém, dar a cada um o que é seu» (*honeste vivere, alterum non laedere, suum cuique tribuere*), citada nas Institutas, é-lhe atribuída.',
  { h: 'Galeno (129 – c. 216 d.C.)' },
  'Médico grego, nascido em Pérgamo, foi médico dos gladiadores do sumo sacerdote da Ásia, em Pérgamo, e depois esteve ao serviço dos imperadores em Roma (entre eles Marco Aurélio). Escreveu centenas de tratados sobre anatomia, farmacologia e filosofia da medicina, e dissecou animais para estudar o corpo. As suas ideias dominaram a medicina europeia e islâmica até ao Renascimento; muitas estavam erradas, mas o seu método influenciou séculos. A data da sua morte (c. 216 ou c. 200) é debatida.',
  { h: 'Cláudia Severa (c. 100 d.C.)' },
  'Mulher de um oficial romano, é a autora de um **convite de aniversário** a Sulpícia Lepidina, mulher do comandante do forte de Vindolanda, escrito a tinta numa tabuinha de madeira por um escriba, com uma despedida de próprio punho: «Hei de esperar-te, irmã. Passa bem, irmã, minha alma mais querida…». É um dos mais antigos textos em latim escritos por uma mulher. Mostra a vida social das famílias de oficiais nas fronteiras do Império.',
  { h: 'Triboniano (c. 485 – c. 542 d.C.)' },
  'Jurista natural de Side (Panfília), ministro da justiça (*quaestor sacri palati*) de Justiniano, dirigiu as comissões que compilaram o *Codex*, o *Digesto* e as *Institutas* (529–534). Foi acusado de corrupção por contemporâneos (como Procópio), e perdeu o cargo em 532, após a revolta de Nika, mas voltou ao cargo em 535. Sem o seu trabalho, parte do direito clássico romano teria desaparecido.'
];

const legado = [
  { h: 'O que nos deixaram' },
  { lista: [
    '**O direito civil:** a tradição jurídica de Portugal, Espanha, França, Itália, Alemanha e América Latina descende do direito romano, via *Corpus Iuris Civilis*, estudado nas universidades desde Bolonha (séc. XII).',
    '**O latim e as línguas românicas:** o português, o espanhol, o francês, o italiano, o romeno e o catalão derivam do latim falado.',
    '**O alfabeto:** o alfabeto latino é hoje o mais usado no mundo; os algarismos romanos ainda aparecem em relógios, séculos e reis.',
    '**O calendário:** o calendário juliano, corrigido em 1582 (calendário gregoriano), é o nosso. Os meses (janeiro, março, junho, julho, agosto) têm nomes romanos.',
    '**A medicina e o vocabulário científico:** muitos termos anatómicos e jurídicos são latinos.',
    '**A organização da Igreja:** a Igreja ocidental herdou o latim, as dioceses e o título de pontífice.',
    '**A cidade e o espaço público:** fórum, teatro, termas, aqueduto, estrada são modelos urbanos que ainda se reconhecem.'
  ] },
  { h: 'O direito romano e o direito português' },
  'O direito português é de **matriz romano-germânica**. Os juristas medievais, a começar pela escola de Bolonha, estudaram o *Corpus Iuris Civilis*, e as Ordenações do reino e os códigos civis portugueses (1867, 1966) nasceram dessa tradição. Muitos conceitos, expressões e brocardos jurídicos ainda são latinos (*habeas corpus*, *in dubio pro reo*, *pacta sunt servanda*, *res nullius*).',
  { h: 'Do latim ao português' },
  'O português nasceu do latim falado no ocidente da Península, a que se juntaram, ao longo dos séculos, palavras germânicas (visigodos, suevos), árabes (depois de 711) e de outras origens. A grande maioria do vocabulário básico é latina: *água* (aqua), *casa* (casa), *pai* (pater), *noite* (nox, noctis), *lume* (lumen). Muitas palavras eruditas foram retomadas do latim culto mais tarde.',
  { h: 'Calendário e semana' },
  'Os nomes dos meses vêm de Roma: **janeiro** (Jano), **março** (Marte), **maio** (talvez Maia), **junho** (Juno, ou *iuniores*), **julho** (Júlio César), **agosto** (Augusto). Setembro a dezembro mantêm os números antigos (sétimo, oitavo, nono, décimo mês, de quando o ano começava em março). Os nomes de vários dias da semana em línguas românicas (francês *mardi*, espanhol *martes*) vêm de deuses romanos; em português, as «feiras» (*feria*) têm origem eclesiástica (séc. VI), mas **sábado** e **domingo** têm raiz cristã e judaica.',
  { h: 'Palavras e frases que usamos' },
  'Usamos expressões romanas sem saber: *ex libris*, *curriculum vitae*, *et cetera*, *carpe diem* (Horácio), *quid pro quo*, *alter ego*, *in vitro*, *sine die*, *vice-versa*, *status quo*, *grosso modo*. «**Pão e circo**» é uma frase de Juvenal; «**Todos os caminhos levam a Roma**» é de origem medieval, não romana.',
  { h: 'Arte, arquitetura e vida urbana' },
  'A arquitetura romana, da **abóbada** e do **arco** ao betão, serviu de modelo à Renascença, ao Neoclassicismo e à arquitetura institucional do século XIX (tribunais, bancos, universidades). A pintura de Pompeia (os «quatro estilos») e os mosaicos influenciaram a decoração da Europa. Nos retratos romanos, a ênfase na individualidade, com rugas, marcas de idade e defeitos (a tradição «realista» da República), é uma das glórias da arte.',
  { h: 'A redescoberta' },
  'O *Corpus Iuris Civilis* foi redescoberto em Itália no século XI, estimulando a fundação de universidades. As ruínas de Herculano (1738) e Pompeia (1748) começaram a ser escavadas no século XVIII, e Pompeia tornou-se uma fonte de inspiração do Neoclassicismo. As tabuinhas de Vindolanda (1973) e os papiros de Egito e Herculano abriram novos mundos. A arqueologia continua: em Pompeia, em 2020 foi apresentado um termopólio completo, com pinturas e vasilhas, na Regio V.',
  { h: 'Como sabemos: o que ainda se debate' },
  { lista: [
    'A **percentagem de escravos** na população do Império e a **taxa de alfabetização**.',
    'A **extensão real das perseguições** aos cristãos e o **número de cristãos** em 300.',
    'A **dedicação do templo de Évora** e a data exata de muitos monumentos hispânicos.',
    'A **origem exata** do 25 de dezembro como festa cristã e as origens do mitraísmo.',
    'A **data da erupção do Vesúvio** (24 de agosto, como diz uma carta de Plínio, ou outubro, segundo achados arqueológicos).',
    'Se o **Edito de Milão** foi um edito formal.'
  ] },
  { h: 'Mitos que ainda circulam' },
  { lista: [
    '**«Os romanos vomitavam para continuar a comer»:** a ideia vem de uma má leitura de Séneca e de *vomitoria*, que eram as saídas dos anfiteatros e teatros.',
    '**«O polegar para baixo»:** não há prova de que significasse a morte; os textos usam *pollice verso* de forma ambígua.',
    '**«Nero tocou lira enquanto Roma ardia»:** Tácito diz que o rumor circulava, mas que Nero estava em Âncio; o que o acusava era ter cantado a «Queda de Tróia» no seu palco, segundo a tradição.',
    '**«Todos os cristãos foram lançados aos leões»:** houve martírios em arenas, mas as perseguições foram intermitentes e as condenações variadas.',
    '**«As mulheres romanas não tinham direitos»:** tinham direitos limitados, mas não nulos: propriedade, herança, divórcio.',
    '**«O latim é uma língua morta»:** deixou de ser língua materna, mas continua nas línguas românicas e na ciência.'
  ] },
  { h: 'Onde visitar' },
  { lista: [
    '**Roma:** Fórum Romano, Capitólio, Panteão, Ara Pacis, Museus Capitolinos, Palazzo Massimo, catacumbas da Via Ápia.',
    '**Pompeia, Herculano e o Museu Arqueológico Nacional de Nápoles:** casas, lararia, frescos e objetos do quotidiano.',
    '**Óstia Antiga:** mitreus, insulae e termas.',
    '**Nîmes:** a Maison Carrée.',
    '**Mérida (Espanha):** teatro, anfiteatro, templo de Diana, Museu Nacional de Arte Romana.',
    '**Évora:** o templo romano, no centro histórico.',
    '**Conímbriga:** ruínas e Museu Monográfico de Conímbriga.',
    '**Lisboa:** Museu Nacional de Arqueologia, com inscrições, mosaicos e esculturas da Lusitânia.',
    '**Vindolanda e o British Museum:** as tabuinhas de madeira.',
    '**Aljustrel:** a antiga Vipasca e a memória da mineração romana.'
  ] },
  { h: 'Porque ainda importa' },
  'Roma não nos deixou apenas pedras. Deixou um **modo de pensar a lei**, uma **língua** que continua a evoluir e **instituições** que o Ocidente adaptou. Mostra também como uma sociedade pode ser, ao mesmo tempo, **brilhante e cruel**: criou direitos e ciência, e viveu da escravatura e dos espetáculos de morte. Estudar a vida romana é aprender a ver as continuidades e as diferenças com o nosso mundo.'
];

const quiz = [
  { p: 'O que importava mais na religião romana tradicional?', op: ['A fé interior em cada deus', 'A leitura de um livro sagrado', 'A obediência a uma Igreja única', 'A execução correta dos ritos'], certa: 3, exp: 'Era uma religião cívica de ritos (ortopraxia): um erro no ritual obrigava a repeti-lo.' },
  { p: 'Quem eram as vestais?', op: ['Sacerdotisas que guardavam o fogo sagrado de Vesta', 'Escravas de uma casa rica', 'Atrizes de teatro', 'Esposas dos cônsules'], certa: 0, exp: 'Eram seis sacerdotisas, escolhidas ainda crianças, que serviam cerca de trinta anos e deviam ser castas.' },
  { p: 'Qual era o título do chefe do colégio dos pontífices?', op: ['Rex sacrorum', 'Flamen Dialis', 'Pontifex maximus', 'Augur maximus'], certa: 2, exp: 'Júlio César foi eleito em 63 a.C.; Augusto assumiu o cargo em 12 a.C. e os imperadores seguintes mantiveram-no.' },
  { p: 'Em que ano se tornou o cristianismo (niceno) religião oficial dos povos do Império, pelo edito de Tessalónica?', op: ['313', '325', '380', '476'], certa: 2, exp: 'Em 380, Teodósio I; em 313 foi o acordo de Milão sobre liberdade de culto.' },
  { p: 'Qual foi a primeira lei escrita de Roma, c. 450 a.C.?', op: ['O Código de Justiniano', 'A Lex Hortensia', 'As Institutas de Gaio', 'As Doze Tábuas'], certa: 3, exp: 'As Doze Tábuas (c. 451–450 a.C.), segundo a tradição redigidas pelos decênviros.' },
  { p: 'O que fazia o pretor romano?', op: ['Comandava a cavalaria', 'Recolhia os impostos', 'Dirigia a fase inicial do processo e publicava o edito', 'Escolhia os sacerdotes'], certa: 2, exp: 'Fixava a fórmula do caso; um juiz privado decidia depois.' },
  { p: 'Que obra de Justiniano reúne extratos dos juristas clássicos em 50 livros?', op: ['O Codex', 'As Institutas', 'As Novelas', 'O Digesto'], certa: 3, exp: 'O Digesto (533) compilou os juristas; o Codex reuniu as leis imperiais; as Institutas eram um manual.' },
  { p: 'O que concedeu a Constitutio Antoniniana (212 d.C.)?', op: ['A liberdade a todos os escravos', 'A cidadania romana à maioria dos habitantes livres do Império', 'O direito de voto às mulheres', 'O fim do serviço militar'], certa: 1, exp: 'O imperador Caracala alargou a cidadania a quase todos os homens livres.' },
  { p: 'O que eram os «vomitoria» dos edifícios romanos?', op: ['Salas para vomitar nos banquetes', 'Fontes públicas', 'Santuários', 'Saídas de passagem dos anfiteatros'], certa: 3, exp: 'O mito da «sala de vomitar» é falso: eram as passagens por onde o público entrava e saía.' },
  { p: 'Quais eram os três nomes de um cidadão romano (tria nomina)?', op: ['Praenomen, nomen, cognomen', 'Nome, apelido, alcunha', 'Pai, filho, neto', 'Cidade, tribo, família'], certa: 0, exp: 'O nome próprio, o da gens e o apelido.' },
  { p: 'Onde foram achadas as Tábuas de bronze com leis de mineração do século II d.C. em Portugal?', op: ['Conímbriga', 'Évora', 'Braga', 'Aljustrel (Vipasca)'], certa: 3, exp: 'Em Aljustrel, em 1876 e 1906; regulavam a mina e os serviços da povoação mineira.' },
  { p: 'Que tipo de documento é a coleção de Vindolanda?', op: ['Leis em bronze', 'Tabuinhas de madeira com cartas a tinta', 'Moedas', 'Mosaicos'], certa: 1, exp: 'Mais de 1700 tabuinhas de c. 95–105 d.C., com cartas, listas e relatórios do forte.' },
  { p: 'Qual era a refeição principal dos romanos?', op: ['Ientaculum', 'Cena', 'Prandium', 'Merenda'], certa: 1, exp: 'A cena, ao fim da tarde. O ientaculum era o pequeno-almoço e o prandium um almoço leve.' },
  { p: 'Que médico grego de Pérgamo dominou a medicina europeia até ao Renascimento?', op: ['Hipócrates', 'Celso', 'Dioscórides', 'Galeno'], certa: 3, exp: 'Galeno (129 – c. 216 d.C.), médico de Marco Aurélio, cujas obras foram autoridade durante mais de mil anos.' },
  { p: 'O que foi o denário?', op: ['Uma moeda de prata romana, de c. 211 a.C.', 'Um imposto sobre heranças', 'Um peso', 'Um tipo de ânfora'], certa: 0, exp: 'Era a moeda de prata base do sistema; um sestércio valia um quarto de denário.' }
];

export default {
  id: 'roma',
  cor: '#b5413a',
  emblema: '../../assets/img/roma.png',
  grupo: { ...GRUPO, aqui: 'religiao-vida' },
  nome:    { pt: 'Religião, direito e vida quotidiana', en: 'Religion, law and daily life' },
  periodo: { pt: '753 a.C. – 476 d.C.', en: '753 BC – AD 476' },
  visao:          { pt: visao, en: EN.visao },
  linha:          { pt: linha, en: EN.linha },
  mapa:           { pt: mapa, en: EN.mapa },
  sociedade:      { pt: sociedade, en: EN.sociedade },
  personalidades: { pt: personalidades, en: EN.personalidades },
  legado:         { pt: [...legado, ...CRED.pt], en: [...EN.legado, ...CRED.en] },
  quiz:           { pt: quiz, en: EN.quiz }
};
