// QIN AND HAN: THE FIRST EMPIRE (221 BC – AD 220) — full English version. Same structure and image ids as dados.js.
// Dates follow the usual chronology (Shiji, Hanshu, Hou Hanshu; Cambridge History of China, vol. 1). Debates are flagged. Names in pinyin.

const visao = [
  { caixa: 'In brief', texto: [
    'In **221 BC**, the king of Qin, **Ying Zheng**, finished conquering the other six great states of China and did something new: he took the title **Huangdi**, “August Sovereign”, and is known to history as **Qin Shi Huang** (Shi Huangdi), the “First Emperor”. For the first time the Central Plain, the Yangtze valley and much of the south and north-east came under a single government, with one official script, one coinage, the same weights and measures and officials appointed from the centre. The **Qin** dynasty lasted only **15 years** (221–206 BC), but the model survived.',
    'It was the **Han** (206 BC – AD 220), a dynasty founded by a former village headman, **Liu Bang**, who made it last. For four centuries, with one 14-year interruption (**Wang Mang**’s Xin dynasty, AD 9–23), the Han adapted the Qin state, softened it with Confucian ethics, expanded it to Central Asia and Korea, and opened the **Silk Road**. It was the age that saw the birth of **paper**, of Sima Qian’s great **historiography**, and of the idea that a Chinese empire should be run by educated men. Even today most Chinese call themselves the “Han people” and their language “the Han language”.'
  ] },
  { img: 'cqh-mapa-han', leg: 'Map of the Han dynasty in AD 2, showing commanderies and the Tarim Basin protectorate.' },
  { h: 'Where and when' },
  'The heart of the empire lay in the valley of the **Wei** river (the “Guanzhong”, home to Xianyang and Chang’an) and in the Central Plain of the Yellow River (with Luoyang). Under the Qin and then under Wudi, the frontiers widened: to the north, as far as the steppes of Inner Mongolia; to the west, the Hexi Corridor and the Tarim Basin; to the south, the Canton region and northern Vietnam; to the north-east, the north of the Korean peninsula. At its height the Han empire covered, by estimate, about **6 million km²** (estimates vary), and the census of **AD 2** counts about **57.7 million** people, one of the largest censuses of the ancient world.',
  { tabela: { cab: ['Phase', 'Dates', 'What marks it'], linhas: [
    ['Qin', '221 – 206 BC', 'Unification, standardisation, Great Wall (sections), Terracotta Army; Legalism; collapse within four years of the Emperor’s death'],
    ['Chu–Han War', '206 – 202 BC', 'Xiang Yu and Liu Bang fight over the empire; Liu Bang wins'],
    ['Western (or Former) Han', '202 BC – AD 9', 'Capital at Chang’an; Wen and Jing; Wudi (141–87 BC); Zhang Qian; Sima Qian'],
    ['Xin', 'AD 9 – 23', 'Wang Mang’s radical reforms; Yellow River floods and revolts'],
    ['Eastern (or Later) Han', 'AD 25 – 220', 'Capital at Luoyang; Ban Chao; Cai Lun; Zhang Heng; eunuchs, imperial in-laws and local magnates; Yellow Turbans'],
    ['End of the Han', 'AD 184 – 220', 'The Yellow Turban revolt, the warlords, and the abdication of the last emperor'],
  ] } },
  { img: 'cqh-shi-huangdi', leg: 'Imagined later portrait of Qin Shi Huang, not a contemporary likeness.' },
  { h: 'What changed in 221 BC' },
  'Before, China was a mosaic of warring states, each with its own coinage, regional script and measures. The new regime made unity a doctrine of state:',
  { lista: [
    '**A new title:** *Huangdi* (“August Sovereign”), which stayed in use until 1912, more than 2,100 years.',
    '**Commanderies and counties:** the empire was divided into units run by officials appointed by the centre and removable at will, instead of hereditary fiefs.',
    '**Script, coinage and measures:** one official script (the small seal script), the *banliang* coin and single weights and measures; even the width of cart axles was standardised.',
    '**Equal laws:** the Qin penal and administrative code, **Legalist** in character, applied to all subjects.',
    '**Works and defence:** roads, canals and the linking of the northern walls, at the cost of enormous forced labour.'
  ] },
  { img: 'cqh-banliang', leg: 'Banliang coins of the Qin and Han dynasties, Shanghai Museum.' },
  { h: 'Qin: a state built fast, and too fast' },
  'The first empire was built on the reforms of **Shang Yang** (4th century BC) and the Qin war machine, and it was harsh: heavy punishments, collective responsibility, crushing labour service and taxes. When the Emperor died in **210 BC**, the system could not withstand a disputed succession. Revolts began in **209 BC**; by **206 BC** his heir no longer existed. The Han tradition, written by the victors, laid on the Qin tyranny thickly, and modern historians try to separate fact from propaganda.',
  { img: 'cqh-exercito-terracota', leg: 'Terracotta Army, Pit 1, Lintong, Xi’an.' },
  { h: 'Han: the empire that lasted' },
  'The Han inherited almost everything from the Qin (the title, the commanderies, many laws), but changed the tone: lighter taxes, milder punishments, ritual and Confucianism at the centre of the court. The name **Han** comes from the title “king of Han” that Liu Bang received in 206 BC, tied to the Hanzhong region, and came to name the people, the language and the script of China. It lasted **over four hundred years**, which historians divide into Western, or Former, Han (capital Chang’an) and Eastern, or Later, Han (capital Luoyang). For the Chinese it is the classical age of the empire.',
  { h: 'Why they matter' },
  { lista: [
    '**The imperial model:** for two millennia almost every Chinese dynasty ruled with a version of the Qin–Han state: emperor, bureaucracy, commanderies and a common script.',
    '**Identity:** “Han” is still the name of the majority group and of the Chinese script (*hanzi*).',
    '**History:** Sima Qian’s *Shiji* and Ban Gu’s *Hanshu* created the model of the official dynastic history, copied for two thousand years.',
    '**Inventions:** paper, the seismoscope, cast iron on a large scale, silk, and improvements to the crossbow and the plough.',
    '**The world:** the Han linked China to Central Asia, Persia, India and, indirectly, Rome.'
  ] },
  { h: 'Legend, propaganda and history' },
  'The main sources were written by **Han officials** (Sima Qian, c. 91 BC; Ban Gu, 1st century AD) for whom Qin was the example of bad government. So famous episodes, such as the **burning of books** or the burying of scholars, must be read with caution. Archaeology helps: the bamboo slips of laws and accounts from Shuihudi and Liye, the Qin mausoleum and the Han tombs (Mawangdui, Mancheng, Haihunhou) show a state that was more organised, more regulated and, in many respects, more ordinary than the texts let us see.',
  { caixa: 'Reading notes', texto: [
    '**Chronology:** the Qin dynasty is usually counted from 221 BC (unification) to 206 BC (fall of Xianyang); some authors count to 207 BC (Ziying’s surrender). The Han dynasty is counted from 202 BC (Gaozu’s title) to AD 220; a start in 206 BC refers to Liu Bang’s title “king of Han”.',
    '**Names:** we use pinyin (Qin, Han, Xiongnu). “Western Han” and “Eastern Han” are names after the capital’s location; “Former” and “Later” are the traditional Chinese designations.',
    '**Numbers:** populations, armies and casualties in ancient sources are exaggerated or approximate; we give only what historians accept as an order of magnitude.'
  ] },
  { h: 'Today' },
  'Today’s China often describes itself as the direct heir of the Qin–Han empire: one hypothesis for the origin of the word “China” is “Qin”, the script is a continuation of the Han one, and the idea of a single nation rests on the memory of 221 BC. The Terracotta Army is the most visited monument of the ancient world in China, and recent discoveries, such as the tens of thousands of **Liye** slips (2002), the tomb of the Marquis of **Haihun** (2011) and the Han wooden slips from **Dunhuang** (Xuanquanzhi, 1990–92), keep changing what we know.'
];

const linha = [
  'This timeline covers the period from 247 BC to AD 220. Dates follow the traditional Han chronology; those of the early campaigns and reigns come from the *Shiji* and the *Hanshu*. Legendary episodes are flagged.',
  { h: 'From Qin to collapse (247 – 206 BC)' },
  { linha: [
    { d: '247 – 221 BC', t: 'The conquest of the six kingdoms', x: 'Ying Zheng takes the throne of Qin in 247 BC, aged 13, and rules in person from 238 BC. With generals such as **Wang Jian** and the counsellor **Li Si**, he annexes the state of **Han** (230), **Zhao** (228), **Wei** (225), **Chu** (223), **Yan** (222) and finally **Qi** (221 BC). The campaign against Chu involves hundreds of thousands of soldiers, according to the sources.' },
    { d: '221 BC', t: 'The First Emperor', x: 'King Zheng takes the title **Huangdi** and proclaims unification. The capital is **Xianyang**. The empire is divided into 36 commanderies (more later) and the great standardisations begin: script, coinage, weights and measures, cart axles.' },
    { d: '215 – 214 BC', t: 'North and South', x: 'The general **Meng Tian** drives the Xiongnu out of the Ordos and links up the northern walls (the sources give him 300,000 men). In the south, Qin armies conquer the lands of Lingnan, helped by the **Lingqu** canal (214 BC), which joins the Yangtze system to the Pearl River system.' },
    { d: '213 – 212 BC', t: 'Books and scholars', x: 'On **Li Si**’s proposal, the books of the states and the schools (except those on medicine, divination and agriculture) were to be handed over to the authorities; in 212 BC, according to the *Shiji*, 460 scholars were buried. This is the Han tradition: modern historians debate its scale and scope.' },
    { d: '210 BC', t: 'Death of the First Emperor', x: 'On an inspection tour in the east, the Emperor dies at **Shaqiu** (Hebei). The eunuch **Zhao Gao** and Li Si hide the death, forge a decree forcing the crown prince **Fusu** to kill himself and enthrone the younger son, **Huhai** (Qin Er Shi). The Emperor is buried in the mausoleum near Mount Li.' },
    { d: '209 BC', t: 'Chen Sheng and Wu Guang', x: 'Soldiers conscripted for the frontier are held up by rain at **Daze** and, knowing they would be executed for arriving late, rebel. Their leaders, the peasants **Chen Sheng** and **Wu Guang**, proclaim the kingdom of Zhang Chu. The revolt spreads to all the former states.' },
    { d: '208 – 206 BC', t: 'The end of Qin', x: 'Li Si is executed (208); Zhao Gao forces Huhai to suicide (207) and installs **Ziying** as “king”, who kills him. Liu Bang enters the Guanzhong and Ziying surrenders after a 46-day reign. In 206 BC **Xiang Yu** arrives, executes Ziying and burns the palaces of Xianyang. The **Hongmen** banquet (206 BC), where Xiang Yu spares Liu Bang, became a famous episode.' }
  ] },
  { img: 'cqh-ai-hongmen', leg: 'Hongmen banquet, 206 BC. AI-generated illustration.' },
  { h: 'Western Han (206 BC – AD 9)' },
  { linha: [
    { d: '206 – 202 BC', t: 'The Chu–Han War', x: 'Xiang Yu divides China into 18 kingdoms and keeps the title “Hegemon-King of Western Chu”; Liu Bang is “king of Han”. Between 205 and 202 BC the two fight for the empire. Xiang Yu’s defeat at **Gaixia** (202 BC) leads him to suicide, and Liu Bang becomes emperor **Gaozu**, with his capital first at Luoyang and then at **Chang’an**.' },
    { d: '200 BC', t: 'Baideng and the *heqin* policy', x: 'Gaozu is besieged for seven days by **Modu Chanyu**’s Xiongnu at Baideng, in northern Shanxi. The Han then respond with the policy of “**harmonious kinship**” (*heqin*): princesses, silk, grain and wine in exchange for peace, which lasted about 60 years.' },
    { d: '195 – 180 BC', t: 'Empress Lü', x: 'After Gaozu’s death, Empress **Lü Zhi** rules as regent in her sons’ name. She promotes members of her clan, and after her death in 180 BC the court eliminates the Lü and enthrones the prince of Dai, **Wen**.' },
    { d: '180 – 141 BC', t: 'Wen and Jing: low taxes', x: 'The emperors **Wen** and **Jing** cut taxes and punishments, and the treasury fills. In **154 BC** the “Revolt of the Seven Kingdoms”, by princes of the Liu family, is crushed and the great kingdoms lose their power.' },
    { d: '141 – 87 BC', t: 'The long reign of Wudi', x: 'Emperor **Wudi** reigns for 54 years. He promotes Confucian education (the Imperial Academy, **Taixue**, in 124 BC), creates the salt and iron monopolies, centralises coinage and launches wars in the north, west, south and north-east. In 127 BC the “Decree of Grace” divides the kingdoms among all the princes’ sons, which weakens them.' },
    { d: 'c. 138 – 126 BC', t: 'Zhang Qian sets out for the West', x: 'The envoy **Zhang Qian** is sent to find the Yuezhi, possible allies against the Xiongnu. He is held by the Xiongnu for about ten years (more than ten, according to the *Shiji*), escapes, reaches Ferghana and Bactria, and returns c. 126–125 BC, some 13 years after setting out, with news of the West. A second mission (c. 119 BC) visits the Wusun.' },
    { d: '121 – 119 BC', t: 'Huo Qubing and Mobei', x: 'The generals **Wei Qing** and **Huo Qubing** drive the Xiongnu out of the **Hexi** corridor (121) and pursue them beyond the Gobi desert (119, the Mobei campaign). In the following decades the Han set up commanderies in Hexi and fortify the corridor as far as Dunhuang.' },
    { d: '111 – 108 BC', t: 'South and north-east', x: 'In 111 BC the Han annex the kingdom of **Nanyue** (Canton and northern Vietnam); in 108 BC they defeat the kingdom of **Wiman Joseon** and set up four commanderies in northern Korea, among them **Lelang**.' }
  ] },
  { img: 'cqh-ai-xiongnu', leg: 'Han cavalry fighting Xiongnu horsemen, c. 119 BC. AI-generated illustration.' },
  { linha: [
    { d: 'c. 91 BC', t: 'The Shiji', x: 'The historian **Sima Qian**, having been castrated for defending a disgraced general (99 BC), completes the *Records of the Grand Historian* in 130 chapters, from the age of Huangdi to Wudi.' },
    { d: '81 BC', t: 'The Salt and Iron Debate', x: 'At the court of Zhaodi, Confucian scholars criticise Wudi’s monopolies and wars, and the senior official **Sang Hongyang** defends them. It was later recorded by Huan Kuan in the *Yantie lun*.' },
    { d: '36 – 33 BC', t: 'Zhizhi and Wang Zhaojun', x: 'In 36 BC the Han kill the rebel chanyu **Zhizhi**. In 33 BC the allied chanyu **Huhanye** receives as his wife the court lady **Wang Zhaojun**, who became the subject of many poems.' }
  ] },
  { h: 'Xin and Eastern Han (AD 9 – 220)' },
  { linha: [
    { d: 'AD 9', t: 'Wang Mang founds the Xin dynasty', x: 'Having been regent (since AD 1), the empress’s relative **Wang Mang** deposes a child emperor and proclaims the **Xin**, “New”, dynasty. He attempts a radical reform: “royal” land, a ban on selling land and slaves, new coins.' },
    { d: 'AD 11 – 23', t: 'Floods, revolts, fall', x: 'The Yellow River changes course in AD 11 and causes famine in the north. Peasants rise up (the **Red Eyebrows**) and, in the south, the Liu family, with **Liu Xiu**, joins the rebels. Wang Mang dies in **Chang’an** on 6 October 23, when the palace is stormed.' },
    { d: 'AD 25', t: 'Guangwu restores the Han', x: '**Liu Xiu** proclaims himself emperor **Guangwu**, of the “restored” Han, and sets his capital at **Luoyang**. The Eastern Han begin.' },
    { d: 'AD 73 – 102', t: 'Ban Chao and the Western Regions', x: 'The general-diplomat **Ban Chao** subdues more than fifty kingdoms of the Tarim, defeats a Kushan army in 90 and becomes Protector-General in 91. In 97 he sends the envoy **Gan Ying** west, who reaches the Persian Gulf area and turns back.' },
    { d: 'AD 105 and 132', t: 'Paper and the seismoscope', x: 'In **105**, **Cai Lun** presents the emperor He with an improved paper made of bark, rags and fishing nets. In **132**, **Zhang Heng** presents his bronze seismoscope, which, according to the sources, detected an earthquake hundreds of kilometres away in 138.' },
    { d: 'AD 166 – 169', t: 'Eunuchs, scholars and Rome', x: 'In 166 the “Partisan Prohibitions” mark the conflict between the court eunuchs and the scholar-officials; they recur in 169. In the same year (166) the Chinese sources record the arrival of a mission from the king of **Daqin** (“Rome”), “Andun”, which many historians see as merchants rather than an official embassy.' },
    { d: 'AD 184', t: 'The Yellow Turbans', x: 'The religious teacher **Zhang Jue** leads, in the name of the “Great Peace” (*Taiping*), a revolt of hundreds of thousands of peasants wearing yellow headcloths. It is crushed within months, but forces the court to give military powers to regional governors.' },
    { d: 'AD 189 – 220', t: 'Warlords and the end of the Han', x: '**Dong Zhuo** seizes Luoyang in 189; **Cao Cao** takes in emperor Xian in 196. After Cao Cao’s death, his son **Cao Pi** forces the last Han emperor to abdicate, in 220. The Three Kingdoms era begins.' }
  ] },
  { img: 'cqh-ai-turbantes', leg: 'Yellow Turban rebels, AD 184. AI-generated illustration.' },
  { h: 'Rediscovery' },
  'The Han kept and studied their own classics, but modern archaeology has changed our picture of the period. In **1957**, in the Baqiao tomb (Xi’an), ancient paper was found; in **1965**, near Xianyang, an army of Han pottery figures; in **1968**, the jade suits of Mancheng; in **1972–1974**, **Mawangdui** (Changsha); in **1974**, the **Terracotta Army**; in **1975**, the Qin laws of **Shuihudi**; in **2002**, the tens of thousands of **Liye** slips; in **2011**, the tomb of the Marquis of **Haihun**, in Nanchang. With every decade the Qin–Han China comes closer.'
];

const mapa = [
  'The Qin–Han empire founded few new cities, but its political centres stayed in the Wei valley and the Central Plain. Around them, a network of commanderies, fortresses, canals and roads held the empire together.',
  { img: 'cqh-mapa-qin', leg: 'Map of Qin dynasty commanderies and population centres, 221–206 BC.' },
  { tabela: { cab: ['Place', 'Period', 'Today', 'What it is known for'], linhas: [
    ['Xianyang', 'Qin (capital)', 'Near Xi’an, Shaanxi', 'Capital of the First Emperor, with palaces and a bridge over the Wei river; burned in 206 BC'],
    ['Mount Li and the Qin mausoleum', 'Qin', 'Lintong, Xi’an', 'The First Emperor’s tomb and the Terracotta Army'],
    ['Chang’an', 'Western Han (capital)', 'Near Xi’an', 'Walled city of c. 36 km² with palaces and markets; c. 246,000 inhabitants in the AD 2 census'],
    ['Maoling', 'Western Han', 'Xingping, Shaanxi', 'Mausoleum of emperor Wudi, the largest of the Han tombs'],
    ['Luoyang', 'Eastern Han (capital)', 'Luoyang, Henan', 'Capital with the Imperial Academy and, by tradition, the White Horse Temple'],
    ['Linzi', 'Han', 'Zibo, Shandong', 'Former capital of Qi; a centre of silk and salt'],
    ['Chengdu', 'Han', 'Sichuan', 'Shu silk brocades, lacquers, salt and iron; Dujiangyan nearby'],
    ['Dunhuang', 'Han (commandery from c. 111 BC)', 'Gansu', 'The “gate” to the West; the Han fortifications; Yumenguan'],
    ['Lelang', 'Han (108 BC – 4th c. AD)', 'Near Pyongyang', 'Han commandery in northern Korea'],
    ['Panyu', 'Nanyue, then Han', 'Canton (Guangzhou)', 'Southern port; tomb of the king of Nanyue (c. 122 BC)']
  ] } },
  { h: 'Xianyang: the Qin capital' },
  'Xianyang stood on the north bank of the Wei river. The First Emperor had a series of palaces built or rebuilt there, with replicas of the palaces of the defeated states, and moved to the capital, according to the *Shiji*, **120,000 families** of the rich and noble families of the old states, to keep an eye on them. The **Epang** palace is the most famous in the sources, but excavations have not confirmed its legendary scale. It was destroyed in 206 BC by Xiang Yu; it burned, tradition says, for three months.',
  { img: 'cqh-ai-xianyang', leg: 'Conjectural view of Xianyang, Qin capital, c. 220 BC. AI-generated illustration.' },
  { h: 'The First Emperor’s mausoleum' },
  'The Emperor’s tomb occupies a huge area east of Xi’an, at Mount Li, with an artificial mound about 50 m high (today) surrounded by walls, moats and dozens of pits. The Terracotta Army is a small part: there are also pits with bronzes (such as the half-scale chariots), acrobats, musicians, officials and animals. According to the *Shiji*, the central chamber had “rivers” of mercury and a sky of precious stones, and construction employed 700,000 workers; soil analyses detected high **mercury** concentrations, but the chamber remains unopened.',
  { img: 'cqh-ai-mausoleu', leg: 'First Emperor’s mausoleum complex, c. 210 BC; conjectural reconstruction. AI-generated illustration.' },
  { h: 'Chang’an: capital of the Western Han' },
  'In 200 BC the minister **Xiao He** had the **Changle** and **Weiyang** palaces built beside the Wei river; between 194 and 190 BC the rammed-earth walls, with 12 gates, went up. The city, with markets, official quarters and a layout still far from the regularity of the Tang, had, according to the AD 2 census, about **246,000** inhabitants. At the end of the Western Han it was one of the largest cities of its time.',
  { img: 'cqh-ai-chang-an', leg: 'Western Han Chang’an, c. 100 BC; conjectural reconstruction. AI-generated illustration.' },
  { h: 'Maoling and the imperial tombs' },
  'The Western Han emperors were buried north of the Wei river, in great mounds of rammed earth, each surrounded by a “mausoleum town” with thousands of transferred families. **Maoling**, Wudi’s, took, according to the sources, 53 years to build (140–87 BC). These cemeteries are today one of the main archaeological complexes of Shaanxi.',
  { img: 'cqh-maoling', leg: 'Maoling, the tomb of Emperor Wu of Han, Xingping, Shaanxi.' },
  { h: 'Luoyang: capital of the Eastern Han' },
  'Guangwu moved the capital to Luoyang in AD 25. The city, beside the Luo river, had a rectangular wall with gates, two palaces (South and North), markets and the **Imperial Academy** (Taixue), which in the 2nd century had, according to the sources, about 30,000 students. Zhang Heng and Cai Lun worked here. In AD 190 **Dong Zhuo** had it burned before fleeing to Chang’an.',
  { h: 'The Hexi Corridor and Dunhuang' },
  'The **Hexi Corridor** (“west of the river”) is a narrow strip of oases between the Qilian mountains and the desert, in Gansu, linking central China to the Tarim Basin. After Huo Qubing’s campaigns, the Han set up commanderies here (**Wuwei, Zhangye, Jiuquan and Dunhuang**), military colonies and fortresses linked by a line of rammed-earth walls and **signal towers**. At **Dunhuang**, the wall continued to the passes of **Yumenguan** (“Jade Gate”) and **Yangguan**, the gates to the West. In the towers and desert posts, archaeologists have found tens of thousands of wood and bamboo slips with orders, records and soldiers’ letters.',
  { img: 'cqh-muralha-han-dunhuang', leg: 'Rammed-earth Han frontier wall near Dunhuang, Gansu.' },
  { h: 'The Western Regions' },
  'The “Western Regions” (*Xiyu*) were, to the Han, the small oasis kingdoms around the Taklamakan desert: Loulan, Khotan, Kashgar, Kucha, Turfan and others. From **60 BC** the **Protectorate of the Western Regions** oversaw them; it was lost under Wang Mang and re-established by **Ban Chao** in the 1st century AD. It was not direct administration: it was a network of vassalage, garrisons and trade.',
  { img: 'cqh-ai-caravana', leg: 'Han-period caravan in the Hexi corridor near Dunhuang. AI-generated illustration.' },
  { h: 'The Silk Road in the Han period' },
  'The route that linked Chang’an to the Mediterranean was not opened in a single journey but through the sum of embassies, merchants and armies. **Zhang Qian** brought information; the Han then sent dozens of missions a year, according to the sources, with silk and metals, and received Ferghana horses, grapes, alfalfa and musicians. Further west, **Sogdian**, **Parthian** and **Kushan** merchants passed the goods on, as far as the Romans, who paid for silk, in Pliny the Elder’s words, with enormous sums of gold and silver. The routes passed through Dunhuang and split into two roads, north and south of the Taklamakan.',
  { h: 'The North: the Xiongnu frontier' },
  'In the north, the frontier was a transition zone between Chinese farming and steppe pastoralism. The Qin linked up the walls, and the Han reinforced and extended them with towers, but this “Great Wall” was neither continuous nor equivalent to the Ming one (of brick and stone): they were mostly rammed-earth and wattle walls, with forts and signal towers, tied to military colonies. Recent surveys count several thousand kilometres of Qin and Han sections.',
  { h: 'The South: Lingnan, Nanyue and the Lingqu' },
  'In 214 BC the Qin conquered the **Lingnan** region, helped by the **Lingqu canal** (over 30 km), one of the first in the world to join two river basins. With Qin’s fall, the general **Zhao Tuo** founded the kingdom of **Nanyue** (204 BC), with its capital at Panyu (Canton); Wudi annexed it in 111 BC. The tomb of Nanyue’s second king, Zhao Mo, discovered in 1983, held a jade suit sewn with silk thread and hundreds of objects.',
  { img: 'cqh-lingqu', leg: 'Lingqu Canal, Xing’an, Guangxi.' },
  { h: 'The North-East: Lelang' },
  'In 108 BC the Han destroyed the kingdom of **Wiman Joseon** and created four commanderies in the north of the Korean peninsula. **Lelang**, near Pyongyang, lasted until AD 313 and left tombs with lacquers, bronze mirrors and silk, one of the best records of Han frontier life.',
  { h: 'The South-West and Vietnam' },
  'In the south-west, Wudi sent armies to the kingdoms of **Dian** (Yunnan), where the gold seal of 109 BC was found, and to Vietnam, the **Jiaozhi**, a province from which sea routes ran south and to India. In AD 40 the **Trung** sisters led a revolt there against Han rule, crushed in AD 43 by the general **Ma Yuan**.',
  { h: 'Sichuan and the iron of Nanyang' },
  'Sichuan, the “land of abundance”, had the **Dujiangyan** irrigation works (c. 256 BC), salt extracted from deep wells, lacquers, brocades and mines. **Nanyang** (Henan) and other centres were great iron-smelting hubs, with workshops of hundreds of workers, many later nationalised by Wudi.',
  { h: 'Mawangdui and the kingdom of Changsha' },
  'The kingdom of **Changsha** (Hunan) was one of the Han vassal kingdoms. Near the capital, three tombs at **Mawangdui**, belonging to an aristocratic family of the 2nd century BC, were excavated in 1972–74 and held silks, lacquers, food, maps, medicine and philosophical manuscripts, in a rare state of preservation.',
  { h: 'The limits of the empire' },
  'For the Han the frontier was not a line but a gradation: directly administered territory (commanderies), vassal kingdoms, “dependent” peoples and, further away, foreigners who sent gifts and were treated as tributaries. The Eastern Han ceased to control the Western Regions permanently, and the northern frontier passed to the Southern Xiongnu and the Xianbei, who settled inside and outside the walls.'
];

const sociedade = [
  { h: '1. The Qin state: Legalism and centralisation' },
  'The state of Qin became powerful in the 4th and 3rd centuries BC through the reforms of the minister **Shang Yang**, who made public laws, and punishments and rewards by military merit, the centre of government. This is the doctrine of **Legalism** (*fajia*), the “school of law”, which held, with **Han Fei** (d. 233 BC), that the ruler should govern by technique, authority and law, not by virtue. The First Emperor, who read Han Fei with admiration, took the doctrine to the whole empire.',
  'The empire was divided into **commanderies** (*jun*) and **counties** (*xian*), run by **appointed officials** of the emperor, paid in grain and removable; offices were not hereditary. This is the structure that, with variations, lasted two thousand years. At the lower levels were the “pavilion heads” (*tingzhang*) and village headmen, who looked after the census and local policing.',
  { img: 'cqh-tiras-shuihudi', leg: 'Qin legal texts on bamboo slips from Shuihudi, Hubei.' },
  { h: '2. Qin law' },
  'Thanks to the bamboo slips found at **Shuihudi** (1975, the tomb of a minor official, with over a thousand slips) and **Liye** (2002, tens of thousands of administrative documents), we know Qin law from the inside. It regulated the census, agriculture, granaries, forced labour, slaves and crimes. Punishments included fines, **penal labour**, mutilations (cutting off the nose or foot), death, and **collective responsibility**, in which neighbours and relatives were punished for each person’s crimes. The code also protected: it laid down procedures, evidence and inquiries, and demanded rigorous records.',
  { h: '3. The standardisations' },
  'Between 221 and 210 BC the Emperor imposed, according to the *Shiji*, the same law, measures, cart axles and script across the empire. In practice the work was gradual and imperfect.',
  { lista: [
    '**Script:** the state imposed the **small seal script** (*xiaozhuan*), derived from the script of the state of Qin and which tradition credits to Li Si. For administration, clerks already used a faster form, the basis of the **clerical script** (*lishu*), which became general under the Han.',
    '**Coinage:** the round bronze coin with a square hole, the *banliang* (the name gives its nominal weight, “half a *liang*”), replaced the knife-, spade- and shell-shaped money.',
    '**Weights and measures:** standard weights and measures, many with the Emperor’s edict inscribed on them, were sent out to all the commanderies.',
    '**Axles and roads:** the same wheel gauge made carts run in the same ruts; a road network, including the “Straight Road” (*Zhidao*, over 700 km, c. 212 BC), linked the capital to the frontiers.'
  ] },
  { img: 'cqh-peso-edito', leg: 'Qin standard bronze weight with an inscription on standardisation.' },
  { h: '4. Public works, forced labour and the wall' },
  'The Qin launched gigantic works: roads, canals, palaces, the mausoleum and the linking of the northern walls, the last directed by **Meng Tian**. To build them, hundreds of thousands of convicts and peasants had to be mobilised in labour-service shifts. The sources speak of 700,000 men on the mausoleum and palace and 300,000 soldiers on the wall, figures that are probably exaggerated but indicate the scale. The weight of this machine explains the revolt of 209 BC.',
  { img: 'cqh-ai-muralha-qin', leg: 'Construction of a Qin rammed-earth wall, c. 214 BC. AI-generated illustration.' },
  { h: '5. The Terracotta Army' },
  'In **1974**, farmers digging a well at Lintong found, 1.5 km from the Emperor’s burial mound, an army of life-size terracotta figures. Excavations revealed four pits: pit no. 1, about 230 × 62 m, holds over 3,000 figures in battle formation, and the total is estimated at **more than 8,000 soldiers**, 130 chariots with 520 horses and 150 cavalry horses. Each figure was assembled from moulded parts and finished by hand, so that the faces differ; originally they were **painted** in bright colours, which faded on exposure to air. More than 40,000 bronze weapons have been found (swords, spears, arrowheads, crossbow triggers), some still with an edge.',
  { img: 'cqh-guerreiro-terracota', leg: 'Detail of the head of a kneeling archer from the Terracotta Army, Qin Shihuang mausoleum.' },
  'That the army represented the Emperor’s own army, his guard in the afterlife, is an interpretation; other ideas, such as that it represents the garrison of the capital, are debated. The tomb itself has **not been opened**.',
  { img: 'cqh-carruagem-bronze', leg: 'Half-scale bronze chariot model from Qin Shi Huang’s mausoleum.' },
  { h: '6. The burned books: fact and debate' },
  'In 213 BC, after a debate at court in which some scholars argued for a return to fiefs and tradition, **Li Si** proposed that the *Book of Songs*, the *Documents* and the writings of the schools be handed in and burned, except for those in the imperial library and books on medicine, divination and agriculture. The following year, according to the *Shiji*, 460 “scholars” were buried. Historians agree there was serious **censorship**, but debate whether it was as total as the Han tradition claims: the imperial library kept copies, many books survived, and **“buried alive”** may be an exaggerated reading. By a frequent argument, the greatest book losses were those of the war of 206 BC, when the palaces burned.',
  { img: 'cqh-ai-livros', leg: 'Collection and burning of books in Qin times, c. 213 BC; artistic interpretation. AI-generated illustration.' },
  { h: '7. The Han state: emperor, ministers and kingdoms' },
  'The Han inherited the Qin machine: the **emperor**, surrounded by counsellors; the **Three Excellencies** (prime minister, military commander and censor) and the **Nine Ministers**, who ran the administration (rites, finance, court, justice, etc.); and the commanderies and counties. But Gaozu, to reward allies and relatives, also created **vassal kingdoms** (*guo*) in the east, ruled by members of his family and other chiefs. The result was a mixed system, in which the centre had gradually to take power away from the kingdoms. This is what Wudi did, after the revolt of 154 BC, with the **Decree of Grace** (127 BC), forcing kingdoms to be divided among all the sons.',
  { h: '8. How one became an official' },
  'There were not yet any imperial examinations. Candidates came in by **recommendation** (from 134 BC each commandery had to recommend yearly men “of filial piety and integrity”, the *xiaolian*), by **inheritance of posts** from fathers of high rank, by purchase or by service. In the Imperial Academy (**Taixue**, 124 BC), the “Erudites of the Five Classics” taught students, and the best were appointed to posts. It was the beginning of the ideal of the scholar-official, which only the Sui and Tang turned into an examination.',
  { h: '9. Confucianism and the court' },
  'The Han did not abolish Legalism: they **assimilated** it. Wudi and his successors ruled, in practice, with harsh laws and a Qin administration, but expressed it in Confucian language. The thinker **Dong Zhongshu** (c. 198 – 105 BC) combined Confucianism with *yin-yang* and the Five Phases: Heaven sends **signs** (eclipses, comets, floods) to warn the emperor, and the ruler responds with acts of virtue. Tradition says that Wudi “rejected the hundred schools and honoured only Confucius”, but modern specialists see this as a simplification: Confucianism became the official ideology only slowly, over a century.',
  { img: 'cqh-ai-taixue', leg: 'Imperial Academy in Luoyang, second century AD. AI-generated illustration.' },
  { h: '10. The Mandate of Heaven, omens and ritual' },
  'The emperor was the “Son of Heaven” and the bridge between Heaven and Earth. He performed sacrifices at the solstice, in the ancestral temple and on sacred mountains; in 110 BC Wudi climbed Mount Tai for the *feng* and *shan* sacrifices, a rare ceremony that proclaimed that Heaven had accepted the dynasty’s rule. Omens (a comet, an earthquake, a flood) could be read as a sign that Heaven was displeased, and high officials sometimes offered their resignation because of them. This is the theory of the **Mandate of Heaven**, now articulated with Han cosmology.',
  { h: '11. Social classes' },
  'At the top, the emperor, the imperial family, kings and marquises (the “titled” nobles) and high officials. Below, the **free peasants**, the great majority, who in Confucian theory were the “foundation of the state”. Next came **artisans** and **merchants**, viewed with suspicion although some were as rich as princes (Sima Qian devoted a chapter to the rich). There was also a scale of **20 grades of merit**, inherited from Qin, which gave privileges (exemptions, more land) and could be bought or granted. From the 1st century BC the great landowning families grew, the **haoqiang** (“local magnates”), who concentrated land and dependants.',
  { h: '12. Taxes, labour service and military service' },
  'Peasants paid a **harvest tax** (which went from one-fifteenth to one-thirtieth of the crop under the emperor Jing), a money **poll tax** (120 coins per adult) and gave **forced labour** (about a month a year on public works) and **military service** (two years, generally, one in the capital and one on the frontier). Those with money could pay to be exempted. It was because they could not bear this burden, the debts and the floods that many peasants lost their land and became tenants of magnates, or fled.',
  { h: '13. Slaves and dependants' },
  'There were private and public slaves, in numbers the sources do not allow us to estimate well (perhaps a few per cent of the population). They entered through debt, sale of children, prisoners of war or penal punishment (a convict’s family could be enslaved). Wang Mang banned the buying and selling of private slaves early in his reign, but the measure was repealed a few years later (the dates in the sources vary). Han slavery did not support the economy, as in Rome: most farm labour was done by free peasants.',
  { h: '14. Women and family' },
  'The extended family was the basic unit, with the eldest male as head. Confucian morality taught **filial piety** (*xiao*), and a woman was subordinate to her father, husband and son. Even so, empresses and imperial mothers played a major role, such as **Lü Zhi** (d. 180 BC) or the Empress Dowager **Dou** (d. 135 BC), and the empresses’ families (the “in-laws”) dominated the court several times. The historian **Ban Zhao** (c. AD 45 – c. 116) wrote the *Lessons for Women* (*Nüjie*), a treatise on women’s duties that at the same time argued for girls’ education.',
  { h: '15. Religion and beliefs' },
  'Han religion had several layers. The **cult of ancestors** was the centre of family life; the state performed sacrifices to Heaven, Earth, mountains and rivers. Belief in **immortals** (*xian*) and in herbs and elixirs of immortality attracted Qin Shi Huang and Wudi, and **magicians** (*fangshi*) frequented the courts. In 3 BC, according to the *Hanshu*, a mass movement, in which people travelled the country carrying talismans and dancing for the **Queen Mother of the West** (*Xiwangmu*), showed the strength of a popular cult. Han tombs are full of images of her.',
  { h: '16. Religious Daoism and Buddhism' },
  'In the 2nd century AD organised religions appeared. In AD 142 (traditional date), **Zhang Daoling** founded in Sichuan the **Celestial Masters** (the “Five Pecks of Rice”), a church with healing by confession and its own administration. Zhang Jue’s **Yellow Turbans** (184) had a doctrine of “Great Peace”. **Buddhism**, coming from Central Asia along the Silk Road, is documented in AD 65, when an edict mentions a prince, Liu Ying, making offerings to the Buddha; tradition speaks of a dream of emperor Ming and of the “White Horse Temple” in Luoyang (c. AD 68), a much embroidered story. In AD 148 the Parthian monk **An Shigao** arrived in Luoyang and began to translate Buddhist texts.',
  { h: '17. Tombs and the afterlife' },
  'The Han believed that the dead went on living in the tomb and took with them food, clothes, pottery servants, and miniature houses and oxen. The rich were buried in wooden or brick chambers, with painted or carved walls. At **Mawangdui**, the body of **Lady Dai** (Xin Zhui), wife of the Marquis of Dai, was so well preserved, inside four lacquered coffins and surrounded by charcoal and clay, that an autopsy was possible; over the coffin, a T-shaped **silk banner** shows the world of the living, that of the dead and that of heaven.',
  { img: 'cqh-mawangdui-estandarte', leg: 'T-shaped silk banner from Mawangdui Tomb 1, Hunan Museum.' },
  'Some princes were buried in **jade suits**, made of thousands of plaques sewn with gold thread, in the belief that jade preserved the body. That of **Liu Sheng**, prince of Zhongshan (d. 113 BC), at Mancheng, uses about 2,500 plaques. The bodies, of course, did not survive.',
  { img: 'cqh-jade-liu-sheng', leg: 'Jade burial suit of Liu Sheng, Mancheng, Hebei Museum.' },
  { h: '18. Agriculture' },
  'The basis of the economy was the peasant with a small holding (the typical unit would be a family of five and about 100 *mu*, roughly 4–5 hectares, according to the sources). In the north they grew **millet**, increasingly **wheat**, **soya** and hemp; in the south, **rice**. Han advances included the **iron plough** with a mouldboard, drawn by oxen, crop rotation and the alternating-fields system, and irrigation works; the spread of a multi-tube **seed drill** is attributed to Wudi’s time (the dating is debated). The stone **rotary mill** spread and made wheat a more common food.',
  { img: 'cqh-ai-quinta', leg: 'Farm and agricultural work in Han times. AI-generated illustration.' },
  { h: '19. Iron, salt and the monopolies' },
  'High-quality **cast iron**, known in China since the 5th century BC, was made on an industrial scale under the Han, with blast furnaces and bellows to which, in AD 31, **Du Shi** applied **water power**, according to the *Hou Hanshu*. Salt came from the sea, from lakes and, in Sichuan, from **deep wells** drilled with a bamboo bit and raised through tubes. Wudi, to pay for the wars, nationalised **iron** and **salt** (and later, for a time, wine) between c. 119 and 117 BC. The monopolies were criticised in the Salt and Iron Debate of 81 BC, and were alternately suspended and restored in the following centuries.',
  { img: 'cqh-ai-ferro', leg: 'Iron foundry in Han times. AI-generated illustration.' },
  { img: 'cqh-tijolo-sal', leg: 'Han tomb brick relief depicting salt production in Sichuan.' },
  { h: '20. Money, markets and cities' },
  'Han coinage was at first a series of bronze types; in **118 BC** Wudi introduced the **wuzhu** coin (five *zhu*), with centralised minting from 113 BC, which stayed in use, with interruptions, for more than 700 years. Silk and grain were also used as payment. Cities had **markets** supervised by officials, with shops grouped by trade, and merchants paid heavier taxes than peasants. Even so, owners of mines and workshops grew rich, and the sources mention fortunes of millions of coins. Wang Mang, in the 1st century AD, tried to create a system of **28 types of coin**, which confused people and caused disorder.',
  { img: 'cqh-ai-mercado', leg: 'Market in a Han city. AI-generated illustration.' },
  { h: '21. Silk, lacquer and crafts' },
  '**Silk** was produced on a large scale in Shandong (Linzi), Sichuan (Shu brocade) and Hubei, with treadle looms, and served as clothing, as currency and as a diplomatic gift. **Lacquers**, of wood and of fabric, red and black, with painted scenes, were the luxury object par excellence, and the imperial workshops of Sichuan were famous. Bronze continued in mirrors, lamps and vessels, and lead-glazed (green) pottery appears in tombs.',
  { h: '22. The Silk Road and relations with the world' },
  '**Zhang Qian**’s missions, the armies in the Tarim and Ban Chao’s diplomacy linked China to **Ferghana** (source of the “heavenly horses” Wudi coveted), **Bactria**, **Parthia** and, in the 1st century, the **Kushan Empire**. Silk reached the **Romans**, who paid dearly for it; Pliny the Elder complained, in the 1st century AD, that luxury drained 100 million sesterces a year to the “Seres”, India and Arabia. In AD 97 **Gan Ying** reached the shores of the Persian Gulf and, according to tradition, gave up going further when Parthian sailors told him of the long voyage.',
  { img: 'cqh-zhang-qian-mural', leg: 'Later mural depicting Zhang Qian’s departure, Mogao Cave 323.' },
  { h: '23. The Xiongnu and other peoples' },
  'The **Xiongnu**, a confederation of nomadic herders led by the **chanyu**, were the Han’s great rival. Under **Modu** (209–174 BC) they besieged Gaozu at Baideng; the response was the policy of **heqin**. Wudi went on the offensive, with cavalry and enormous logistical support, which cost a great deal and was not always effective. From 60 BC the Xiongnu split: the chanyu **Huhanye** allied with the Han (53 BC), and in 33 BC received **Wang Zhaojun** as his wife. In AD 48 the people divided for good into **Southern Xiongnu**, vassals of the Han, and **Northern**, defeated in AD 89–91. Among other peoples, the **Qiang** (west), the **Wuhuan** and **Xianbei** (north-east) and the **Yue** of the south stood out.',
  { img: 'cqh-selo-na', leg: 'Engraved face of a replica of the King of Na gold seal, with a mirrored image for reading, Toi Museum.' },
  { h: '24. War and the army' },
  'In Qin times the army was made of infantry **conscripts** with bronze **crossbows** (a decisive weapon, with a bronze trigger, mass-produced), spears and swords, supported by chariots and cavalry. Under the Han, **horsemen** gained importance to face the Xiongnu, and iron replaced bronze in weapons: the long iron sword and the halberd (*ji*). Recruitment was by **compulsory service**, supplemented by professional soldiers, military colonists (*tuntian*) and, on the frontier, mercenaries and nomad auxiliaries. Under the Eastern Han compulsory service was abolished (in AD 30 for most inland commanderies) and replaced by hired soldiers, which gave generals more power.',
  { img: 'cqh-exercito-yangjiawan', leg: 'Western Han terracotta soldier from Yangjiawan, Xianyang Museum.' },
  { h: '25. The house and daily life' },
  'Peasants lived in rammed-earth or wooden houses with one or two rooms, a thatch or tile roof, a courtyard with the oven and stable, and a granary. Rich houses were complexes of courtyards with tall halls and **towers**, and great families raised **watchtowers** and pottery granaries that the tombs reproduce in miniature. People sat on the floor, on mats, beside low tables; chairs with backs came later. Foundations were of rammed earth, and the columns of wood, with **brackets** (*dougong*) supporting wide eaves.',
  { img: 'cqh-modelo-torre-han', leg: 'Green-glazed pottery model of a watchtower, Eastern Han period.' },
  { h: '26. Food' },
  'The basis was **millet** (in porridges and cakes) and, increasingly, **wheat**, ground in rotary mills and cooked in cakes, noodles and “*bing*”; in the south, **rice**. People ate vegetables (cabbage, turnip, chives, melon), fermented **soya** and pastes, and fruit such as peach and apricot. Meat, for the rich, was pork, mutton, fowl, dog and game, and fish was common in the south. They drank **grain wine**, and **tea** was already drunk in Sichuan. They ate with **chopsticks** and spoon. The bamboo menu list from a Mawangdui tomb shows a varied cuisine, with soups, roasts and stews.',
  { h: '27. Clothing' },
  'The typical garment was the **wrap-over robe** (*shenyi*), with wide sleeves, tied with a belt; men wore tunics, trousers and boots on the frontier, and hats and headdresses that indicated rank. **Silk** clothed the elites, while peasants wore **hemp** and ramie. At Mawangdui a **silk gauze gown** was found weighing only about 49 g, proof of the weavers’ skill. Hair tied in a bun, and the use of jade pieces, buckles and bronze mirrors, completed the dress.',
  { h: '28. Writing and books' },
  'The **clerical script** (*lishu*), with straight, angular strokes adapted to the brush, was the Han everyday script, and from it the regular script would be born. People wrote on **bamboo slips** or wood, tied with cord, on **silk** (expensive) and later on **paper**. Around **AD 100**, **Xu Shen** compiled the *Shuowen jiezi*, the first dictionary of characters, with over 9,000 entries arranged under 540 radicals. The oldest **papers** found (Fangmatan, Baqiao) date from the 2nd century BC, used for maps and wrapping; Cai Lun’s contribution, in AD 105, was to improve production for writing.',
  { img: 'cqh-papel-fangmatan', leg: 'Paper map fragment from Fangmatan, Western Han period.' },
  { h: '29. Literature and history' },
  'Sima Qian’s *Shiji* (c. 91 BC) spans, in 130 chapters, over two thousand years, with “Basic Annals”, “Hereditary Houses”, “Treatises”, “Tables” and “Biographies” (of generals, merchants, assassins, poets and foreign peoples). Ban Gu’s *Hanshu* (c. AD 82, completed by his sister Ban Zhao) is the first history of a single dynasty and served as a model for the official histories. In poetry, the *fu* (rhapsodies) of **Sima Xiangru**, the songs of the Music Bureau (*yuefu*) and the “Nineteen Old Poems” stand out. The *Huainanzi* (c. 139 BC), by Liu An, combines philosophy and cosmology; **Wang Chong** (AD 27 – c. 100) wrote the *Lunheng*, a rationalist critique of superstition.',
  { h: '30. Music, games and spectacle' },
  'Wudi created the **Music Bureau** (*Yuefu*), which collected popular songs and songs from foreign regions. The orchestra included bronze bells, lithophones, drums, flutes, **zithers** (*qin* and *se*) and mouth organs. People played **weiqi** (go) and **liubo**, a board game with sticks, very popular among the elite; boards of both appear in tombs. In markets and at festivals there were **acrobats, jugglers, wrestlers and dancers**, the “hundred entertainments” (*baixi*), and cockfights. *Cuju*, a ball game played with the feet, is also attested under the Han.',
  { h: '31. Astronomy, mathematics and the calendar' },
  'In **104 BC** the **Taichu** calendar replaced the old one, with lunar months and solar adjustments; it was the starting point of Chinese calendars. Astronomers recorded eclipses, comets and sunspots (there is a record of 28 BC). **Zhang Heng** (78–139) made a water-driven armillary sphere and proposed that the Moon reflects the Sun’s light. In mathematics, the *Nine Chapters on the Mathematical Art*, compiled across the 2nd century BC – 1st century AD (the dating is debated), deal with areas, volumes, proportions and systems of equations, and the *Zhoubi suanjing* applies geometry to astronomy.',
  { img: 'cqh-sismoscopio', leg: 'Replica of the seismoscope attributed to Zhang Heng, exhibited at Chabot Space & Science Center, Oakland.' },
  { h: '32. Technology and engineering' },
  'Besides paper and cast iron, the Han mastered a series of techniques: the bronze **crossbow** with a trigger mechanism; the **stern rudder** on boats (visible in pottery models of the 1st–2nd century AD); the **wheelbarrow** (depicted in reliefs of the 1st–2nd century AD); the **drilling of deep brine wells**; Du Shi’s **hydraulic bellows**; stone and wooden **bridges**, and great hydraulic works against floods and for irrigation. **Dujiangyan**, of c. 256 BC (state of Qin), and Zheng Guo’s canal, of 246 BC, predate the unification but remained in use.',
  { h: '33. Medicine' },
  'The *Huangdi neijing* (“Inner Canon of the Yellow Emperor”), compiled between the Warring States and the Han, explains the body with *yin-yang*, the Five Phases and **qi** (vital breath), and describes the channels and **acupuncture**. The **Mawangdui** manuscripts include recipes and texts on therapeutic gymnastics. The *Shennong bencao jing*, the oldest treatise on drugs, and **Zhang Zhongjing**’s *Shanghan zabing lun* (c. AD 200), on fevers, are reference works. **Hua Tuo** (d. 208) is remembered for using an anaesthetic potion (*mafei san*), although what the sources say of him is mixed with legend.',
  { h: '34. Art and architecture' },
  'Han art is above all tomb art: **stamped bricks** and **stone reliefs** (such as those of the Wu Liang shrine, Shandong, c. AD 151) with scenes of hunting, banquets, myth and history; **paintings** on walls and silk; pottery and bronze **sculptures**, such as the famous **“Heavenly Horse”** of Wuwei, and monumental **gate towers** (*que*) of stone and wood. No Han palaces stand today, but the pottery models show wooden architecture with brackets and curved eaves, the basis of the later tradition.',
  { img: 'cqh-cavalo-voador', leg: 'Bronze galloping horse treading on a flying swallow, Gansu Provincial Museum.' },
  { h: '35. The crisis of the Eastern Han' },
  'From the end of the 1st century AD, emperors came to the throne very young, and power lay in the hands of the **empresses’ families** and, to depose them, of the court **eunuchs**. The scholar-officials, who opposed both, were persecuted in the “Partisan Prohibitions” (166 and 169). In the countryside, **magnates** accumulated land and dependants, floods, droughts and epidemics ruined the peasants, and wars against the Qiang drained the treasury. When the Yellow Turbans revolted in 184, the state no longer had the strength to contain them without giving autonomy to the generals, and that is what destroyed it.'
];

const personalidades = [
  'The figures below are historical; the main sources are the *Shiji* and the *Hanshu*, which are not neutral. Dates follow the usual chronologies; where there is debate, it is flagged.',
  { h: 'Qin Shi Huang, First Emperor (259 – 210 BC)' },
  'Born in Handan, son of the crown prince of Qin (the legend, spread by the *Shiji*, says he was the son of the merchant **Lü Buwei**, which is probably Han slander), he became king at 13, ruled in person from 238 and conquered the six states in nine years. He took the title **Huangdi**, travelled the empire, and had stone inscriptions raised proclaiming his works. He sought immortality with magicians and elixirs and, according to one tradition, may have died poisoned by mercury. The source is Han and hostile; archaeology shows a methodical administrator.',
  { h: 'Li Si (c. 280 – 208 BC)' },
  'A native of Chu and a disciple of Xunzi, he was chancellor of the Qin and architect of the **standardisations**, from the script to the division into commanderies. He proposed the burning of the books. After the Emperor’s death he allied with the eunuch **Zhao Gao** to forge the succession decree and was later his victim: accused of treason, he was executed in Xianyang in 208 BC, with his family, according to the *Shiji*.',
  { h: 'Xiang Yu (232 – 202 BC)' },
  'An aristocrat of Chu, grandson of a general, he was a gifted and famous warrior. He destroyed the Qin armies at Julu (207 BC), sacked Xianyang and divided the empire, but, impulsive and proud, lost the war to Liu Bang. Surrounded at Gaixia, he killed himself on the bank of the Wu river. The *Shiji* gives him a moving chapter among the “Basic Annals”, as if he were a sovereign.',
  { h: 'Liu Bang, emperor Gaozu (c. 256 – 195 BC)' },
  'A peasant and “pavilion” headman in Pei, a minor official, he was sent to escort convicts and, having lost them along the way, joined the rebels. He surrounded himself with good advisers (**Xiao He**, **Zhang Liang**, **Han Xin**) and beat Xiang Yu through patience and organisation. As emperor he kept the Qin machine, with milder laws, but eliminated many of the old companions who ruled kingdoms. According to the *Shiji*, it was the adviser **Lu Jia** who reminded him that one can conquer an empire on horseback but not govern it on horseback.',
  { h: 'Empress Lü Zhi (241 – 180 BC)' },
  'Wife of Gaozu and mother of the second emperor, she ruled as regent between 195 and 180 BC. According to the sources, which are hostile, she had rivals killed, among them the concubine **Qi**, with extreme cruelty; she kept, however, peace with the Xiongnu and a stable administration, and did not take the title of reigning empress. After her death, her relatives were massacred and the child-emperors she had installed were removed.',
  { h: 'Wudi (156 – 87 BC)' },
  'He came to the throne at 15 and reigned 54 years. He extended the empire in every direction, sent Zhang Qian to the West, instituted the salt and iron monopolies, the *wuzhu* coin and the Imperial Academy, and left the coffers empty. Late in life, in 91 BC, the **witchcraft** affair (*wugu*) led to the death of the crown prince and the punishment of hundreds, and, according to one tradition, Wudi issued the so-called “Luntai edict” (c. 89 BC), expressing regret for the wars, whose authenticity is debated. He was buried at Maoling.',
  { h: 'Wei Qing (d. 106 BC) and Huo Qubing (140 – 117 BC)' },
  '**Wei Qing**, the son of a servant, rose thanks to his sister, a concubine of Wudi, and proved a great general; he led seven campaigns against the Xiongnu. His nephew, **Huo Qubing**, stood out from the age of 17 for his cavalry raids: in 121 BC he swept the Hexi corridor, and in 119 BC he advanced as far as present-day Mongolia where, according to the *Shiji*, he performed sacrifices. He died at 23. His tomb, beside Wudi’s, has stone sculptures, among them the “Horse Trampling a Xiongnu”.',
  { img: 'cqh-huo-qubing', leg: 'Horse trampling a Xiongnu, stone sculpture at Huo Qubing’s tomb, Maoling.' },
  { h: 'Zhang Qian (d. c. 114 BC)' },
  'An official of Wudi, he set out in c. 138 BC with about a hundred men in search of the Yuezhi. He was captured by the Xiongnu, married and had a son among them, and after more than ten years managed to escape (the whole mission lasted about 13 years). He visited Ferghana, Sogdiana and Bactria and returned, in c. 126 BC, with only his guide Ganfu. His reports, preserved in the *Shiji*, are the first Chinese description of Central Asia. He did not “open” the Silk Road alone, but he was the first to show the court that the West existed.',
  { h: 'Sima Qian (c. 145 – c. 86 BC)' },
  'The son of a court astrologer, **Sima Tan**, he inherited the post and the idea of writing a universal history. In 99 BC, when he defended the general Li Ling, who had surrendered to the Xiongnu, Wudi sentenced him to death, and he chose **castration**, to have time to finish the work. The *Shiji* was ready c. 91 BC. In the *Letter to Ren An* he explains that he lived to finish the book. He wrote with a remarkable critical sense: he criticises kings, conquerors and the emperor himself.',
  { img: 'cqh-sima-qian', leg: 'Posthumous portrait of Sima Qian, album of historical sages, National Palace Museum, Taipei.' },
  { h: 'Wang Mang (45 BC – AD 23)' },
  'Nephew of the empress dowager, regent in AD 1 and emperor of the **Xin** dynasty in 9, he wanted to recover the ideal government of the Zhou, as the classics described it: “royal land” shared among families, a ban on the sale of land and slaves, new monopolies and coins. It was a badly prepared reform, with floods, famine and defeats on the frontiers. He died at the hands of rebels in Chang’an. Han historians condemned him as a usurper; modern ones see him as either a fanatic or an idealistic reformer.',
  { h: 'Guangwu, Liu Xiu (5 BC – AD 57)' },
  'A descendant of Gaozu and the son of a magistrate, he joined the rebellion against Wang Mang and distinguished himself at the battle of Kunyang (AD 23). He proclaimed himself emperor in 25, settled in Luoyang and spent the next twelve years reunifying the empire. He ruled with moderation, reduced the army and gave strong support to scholar-officials, earning the epithet “restorer”.',
  { h: 'Ban Chao (AD 32 – 102)' },
  'Brother of Ban Gu and Ban Zhao, he threw down, according to the *Hou Hanshu*, his copyist’s brush, saying that a man should do deeds in foreign lands. From 73, with a few dozen men, he subdued the kingdoms of the Tarim through diplomacy, exploiting rivalries and with daring strokes. In 90 he defeated the Kushan; in 91 he became Protector-General. In 97 he sent Gan Ying to the West. He returned to Luoyang aged 70 and died soon after.',
  { h: 'Ban Gu (AD 32 – 92) and Ban Zhao (c. AD 45 – c. 116)' },
  '**Ban Gu** wrote the *Hanshu*, the first of the great single-dynasty records; he died in prison, accused of links to a disgraced general. His sister, **Ban Zhao**, completed the eight “Tables” and the astronomical treatise, was tutor to the court ladies (and adviser to the regent Deng) and wrote the *Lessons for Women*, a text of enormous influence, which she saw as a manual of education.',
  { h: 'Cai Lun (d. AD 121) and Zhang Heng (AD 78 – 139)' },
  '**Cai Lun**, a palace eunuch, ran the imperial workshops and in 105 presented paper of bark, rags and nets; he received the title of marquis, but committed suicide in 121 after falling from favour at court. **Zhang Heng**, court astronomer, poet and engineer, built the hydraulic armillary sphere and the seismoscope (132) and wrote the *Rhapsody on the Two Capitals*; he calculated a value of π of about 3.16 (the square root of 10).',
  { h: 'Zhang Jue (d. AD 184)' },
  'A religious leader from Hebei, he healed the sick through confession and holy water and preached the coming of a new age of **Great Peace**. He organised his followers into 36 military-religious “regions”, and the revolt of 184, with the slogan “The blue Heaven is already dead, the yellow Heaven will arise”, gathered hundreds of thousands. He died of illness in the autumn of 184, and the revolt, although defeated, opened the door to the warlords.'
];

const legado = [
  { h: 'What they left us' },
  { lista: [
    '**The imperial state:** the emperor, the bureaucracy, the commanderies and counties, and the idea that government should choose officials on merit lasted until 1912.',
    '**The “Han” identity:** the name of China’s largest group, and of its script (*hanzi*), language (*hanyu*) and dress (*hanfu*), is that of the dynasty.',
    '**Writing:** the clerical script and, with it, the transition to the regular script, which is the basis of today’s.',
    '**History:** the *Shiji* and the *Hanshu* created the genre of official history and a tradition of criticism of power.',
    '**Paper and technology:** paper, cast iron, the seismoscope, the crossbow, and many techniques of farming and crafts.',
    '**The Silk Road:** the network of contacts between China, Central Asia, Persia, India and the Mediterranean.'
  ] },
  { h: 'The political mould' },
  'The Qin and Han empire is, for the Chinese, the “first” and the model: when a regime fell, the next was rebuilt on its pattern. This explains why China, unlike post-Roman Europe, reunited several times. The Han also left a tension that lasted two millennia: that of a **strong state, Legalist in character, with a Confucian moral language**.',
  { h: 'Art' },
  'Han art is that of **tombs**: stamped bricks and stone reliefs with scenes of life and myth; pottery and lacquers; bronze (mirrors, lamps, the Heavenly Horse); the silk painting of Mawangdui and the funerary sculpture of **Qin Shi Huang**, where the realism and scale of each figure in the army are unique in Antiquity.',
  { h: 'Architecture and engineering' },
  'Because architecture was of wood, almost nothing survives, but the rammed-earth walls, the desert signal towers, the *que* gates, the canals (**Lingqu**, **Dujiangyan**), the roads and the ruins of the cities show the grandeur of the works. The layout of Chang’an and Luoyang influenced later capitals, from Chang’an (Tang) to Kyoto and Nara.',
  { img: 'cqh-dujiangyan', leg: 'Dujiangyan irrigation system, Sichuan.' },
  { h: 'Memory and politics' },
  'The image of Qin Shi Huang oscillates between that of **tyrant** (the Han and Confucian tradition) and that of **unifier** (modern historiography and Chinese nationalism of the 20th century). The Han remained in memory as the “golden age”, and are still the word many Chinese use for themselves. Both readings say more about the reader than about the past.',
  { h: 'Rediscovery' },
  { lista: [
    '**1957:** Baqiao paper, Xi’an, c. 118 BC.',
    '**1965:** Han pottery army at Yangjiawan, Xianyang.',
    '**1968:** Mancheng tombs, with the jade suits of Liu Sheng and Dou Wan.',
    '**1972–1974:** Mawangdui, Changsha.',
    '**1974:** Terracotta Army, Lintong (UNESCO, 1987).',
    '**1975:** Shuihudi laws; **1983:** tomb of the king of Nanyue; **1986:** Fangmatan paper; **2002:** Liye slips; **2011:** Haihunhou tomb, near Nanchang.'
  ] },
  { h: 'Where to visit' },
  { lista: [
    '**Xi’an and surroundings:** Terracotta Army Museum (Lintong); Shaanxi History Museum; Hanyangling Museum (tomb of emperor Jing); Maoling (Xingping); ruins of Han Chang’an.',
    '**Xianyang:** Xianyang Museum, with the Han army figures from Yangjiawan.',
    '**Luoyang:** Luoyang Museum and the ruins of the Eastern Han capital.',
    '**Changsha:** Hunan Provincial Museum, with Mawangdui.',
    '**Shijiazhuang:** Hebei Museum, with the Mancheng jade suits.',
    '**Lanzhou:** Gansu Provincial Museum, with the Heavenly Horse; **Dunhuang:** the Han walls, Yumenguan and Hecang.',
    '**Canton:** Museum of the Mausoleum of the Nanyue King.',
    '**Sichuan:** Dujiangyan and the Sichuan Museum, in Chengdu.',
    '**Outside China:** British Museum (London), Musée Guimet (Paris), Metropolitan Museum (New York) and, in Portugal, the Museu do Oriente (Lisbon), with Chinese pieces from several periods.'
  ] },
  { cit: 'Every man must die once: for some, death weighs more than Mount Tai; for others, it weighs less than a feather. It depends on the use made of it.', fonte: 'Sima Qian, Letter to Ren An (free translation)' }
];

const quiz = [
  { p: 'In what year did the king of Qin unify China and take the title Huangdi?', op: ['256 BC', '221 BC', '206 BC', '202 BC'], certa: 1, exp: 'In 221 BC, after defeating the last rival state, Qi, King Zheng became Qin Shi Huang, the First Emperor.' },
  { p: 'Which of these measures was NOT a Qin standardisation?', op: ['The official script', 'The banliang coin', 'Weights and measures', 'The imperial examination'], certa: 3, exp: 'The imperial examination appeared much later (Sui and Tang). Qin standardised script, coinage, weights and measures and even cart axles.' },
  { p: 'How was the Terracotta Army discovered?', op: ['By an archaeological expedition in 1928', 'By farmers digging a well, in 1974', 'It was always visible', 'By Marco Polo'], certa: 1, exp: 'It was on 29 March 1974, at Lintong, near Xi’an. There are estimated to be more than 8,000 soldiers.' },
  { p: 'According to the Shiji, what happened in 213–212 BC?', op: ['The unification of the script', 'The building of the Lingqu', 'The death of the Emperor', 'The burning of books and the burying of scholars'], certa: 3, exp: 'This is the Han tradition; modern historians accept that there was censorship, but debate its scale and scope.' },
  { p: 'Who raised the peasants in 209 BC and began the collapse of Qin?', op: ['Chen Sheng and Wu Guang', 'Liu Bang and Xiang Yu', 'Zhang Jue and Zhang Liang', 'Wang Mang and Liu Xiu'], certa: 0, exp: 'The two leaders revolted at Daze, after being held up by rain on the way to the frontier.' },
  { p: 'Who was the founder of the Han dynasty?', op: ['Xiang Yu', 'Liu Xiu (Guangwu)', 'Liu Bang (Gaozu)', 'Wudi'], certa: 2, exp: 'A former village headman, he defeated Xiang Yu and proclaimed himself emperor Gaozu in 202 BC.' },
  { p: 'What was the Han policy of “harmonious kinship” (heqin) towards the Xiongnu?', op: ['Marriages and gifts in exchange for peace', 'Permanent war', 'A treaty with the Romans', 'Linking up the walls'], certa: 0, exp: 'After Baideng (200 BC), the Han sent princesses and gifts in exchange for peace, for about 60 years.' },
  { p: 'Which emperor reigned 54 years, created the Imperial Academy and sent Zhang Qian west?', op: ['Wen', 'Jing', 'Wudi', 'Guangwu'], certa: 2, exp: 'Wudi (141–87 BC) turned the Han empire into an expansionist power.' },
  { p: 'Why was Zhang Qian sent west in c. 138 BC?', op: ['To seek the elixir of immortality', 'To buy silk', 'To found a colony', 'To seek allies, the Yuezhi, against the Xiongnu'], certa: 3, exp: 'He found no allies, but brought back new information about Central Asia and the “heavenly horses” of Ferghana.' },
  { p: 'Who was the “Grand Historian”, author of the Shiji?', op: ['Sima Qian', 'Ban Gu', 'Dong Zhongshu', 'Wang Chong'], certa: 0, exp: 'Sima Qian completed the “Records of the Grand Historian”, in 130 chapters, c. 91 BC.' },
  { p: 'Which short-lived dynasty interrupted the Han between AD 9 and 23?', op: ['Sui', 'Jin', 'Xin', 'Wei'], certa: 2, exp: 'Wang Mang’s Xin dynasty, which made radical reforms and fell to Yellow River floods and revolts.' },
  { p: 'Who improved paper and presented it to the emperor in AD 105?', op: ['Zhang Heng', 'Ban Chao', 'Cai Lun', 'Hua Tuo'], certa: 2, exp: 'Cruder paper had existed since the 2nd century BC; Cai Lun improved it for writing.' },
  { p: 'What is the “Heavenly Horse” of Wuwei (Gansu)?', op: ['A poem by Sima Xiangru', 'A name for the Terracotta Army', 'A sacred mountain', 'A Han bronze sculpture of a horse treading on a swallow'], certa: 3, exp: 'It is an Eastern Han bronze sculpture, now in the Gansu Provincial Museum.' },
  { p: 'Who led the Yellow Turban revolt in AD 184?', op: ['Zhang Jue', 'Cao Cao', 'Dong Zhuo', 'Liu Bei'], certa: 0, exp: 'Zhang Jue, religious leader of the “Great Peace” movement. The revolt was defeated, but it gave power to the warlords.' },
  { p: 'In what year did the last Han emperor abdicate, and in favour of whom?', op: ['206 BC, in favour of Liu Bang', 'AD 25, in favour of Guangwu', 'AD 184, in favour of Zhang Jue', 'AD 220, in favour of Cao Pi'], certa: 3, exp: 'Emperor Xian abdicated in 220 in favour of Cao Pi, who founded the kingdom of Wei, and the Three Kingdoms era began.' }
];

export default { visao, linha, mapa, sociedade, personalidades, legado, quiz };
