// EGYPT — Ptolemaic and Roman Period (332 BC – c. AD 641). English content. Same structure and same image slots as the Portuguese version (dados.js).
// Dates are approximate; BC = before Christ. For the Hellenistic period the usual historians’ dating of the Ptolemies’ reigns is used; some exact dates are debated and flagged.

const visao = [
  { caixa: 'In brief', texto: [
    'In the roughly **970 years** between the arrival of **Alexander the Great** (332 BC) and the Arab conquest (c. AD 641), Egypt ceased to be ruled by native dynasties and became, in turn, the centre of a Greek kingdom (the **Ptolemies**), a Roman province, the great granary of Rome and, finally, a Christian land of the **Coptic** Church within the Byzantine Empire. It was the longest period of foreign rule in Egyptian history, and the least known to the general public.',
    'The Ptolemies founded the city of **Alexandria**, with its Lighthouse, the Museion and the Great Library, and ruled both as Macedonian kings and as pharaohs, building traditional temples such as those of **Edfu**, **Dendera** and **Philae**. The last queen, **Cleopatra VII**, lost the kingdom to Rome in 30 BC. In the following centuries Egypt was one of the richest territories of the Empire, and its people passed from the religion of Isis and Osiris, whose last temples closed in the 6th century, to Christianity, whose Egyptian Church still keeps the Coptic language today, a direct descendant of ancient Egyptian.'
  ] },
  { img: 'epr-mapa-reino-ptolemaico', leg: 'Map of the Ptolemaic Kingdom in the third–second centuries BC; labels in Portuguese.' },
  { h: 'Where and when' },
  'The setting is the same as ever: the valley and delta of the **Nile**, a strip of fertile land surrounded by desert. What changes is the centre of gravity. Under the Ptolemies the capital moves from Memphis and Thebes to **Alexandria**, a new city on the Mediterranean coast, facing Greece, Syria and the world of the sea. Under Rome, Egypt is a special province, administered directly by the emperor, and under the Byzantines it becomes part of a Christian empire governed from Constantinople.',
  'The end of the period can be marked in different ways. Here the **Arab conquest of AD 639–642** is used (the year 641, with the fall of the fortress of Babylon, and the entry into Alexandria in 642), because it marks the end of Eastern Roman rule in Egypt, as opposed to the traditional “ancient Egypt”, which many books end in 30 BC.',
  { tabela: { cab: ['Phase', 'Dates', 'What marks it'], linhas: [
    ['Conquest of Alexander', '332 – 323 BC', 'The Persians surrender without a fight; foundation of Alexandria (331 BC); death of Alexander in Babylon'],
    ['Ptolemies (Hellenistic period)', '323 / 305 – 30 BC', 'Ptolemy I rules first as satrap, then as king (305 or 304 BC); height in the 3rd century; revolts and decline in the 2nd–1st centuries; ends with Cleopatra VII'],
    ['Roman Egypt (Early Empire)', '30 BC – AD 284', 'Augustus’ province; grain for Rome; Red Sea trade; Fayum portraits; Jewish revolts; plague and crises of the 3rd century'],
    ['Late Roman and Byzantine Egypt', 'AD 284 – 641', 'Diocletian; Christianization, monasticism, Council of Chalcedon (451); Persian occupation (619–629); end of Byzantine rule'],
    ['Arab conquest', 'AD 639 – 642', 'Amr ibn al-As takes Egypt; foundation of Fustat; Islamic Egypt begins']
  ] } },
  { img: 'epr-alexandria-reconstrucao', leg: 'Conjectural reconstruction of Ptolemaic Alexandria in the third century BC, with the lighthouse and harbours. AI-generated illustration.' },
  { h: 'Who were the Egyptians of this time?' },
  'The largest part of the population remained the **Egyptians** who lived in the villages of the valley and the delta and spoke Egyptian (in its Demotic form, and later Coptic). Above them the Ptolemies settled **Greeks and Macedonians**: soldiers, officials, merchants, colonists. There were also **Jews** (the community of Alexandria was very large), Syrians, Libyans, Nubians and, after 30 BC, **Romans** and Italians.',
  'Estimates of the total population differ greatly and run from about 4 to 8 million over the period. What is known is that the two cultures, Greek and Egyptian, lived side by side without fully merging: at first the Greeks lived in the cities and the Egyptians in the countryside, but marriage, business and religion brought them closer, and the funerary portraits of the Fayum show this mixture well.',
  { img: 'epr-templo-edfu', leg: 'Pylon of the Temple of Horus, Edfu.' },
  { h: 'Why it matters' },
  { lista: [
    '**Alexandria:** the greatest city of the Hellenistic Mediterranean, with the Lighthouse (one of the seven wonders), the Museion and the Library, where Euclid, Eratosthenes and many others worked.',
    '**A two-faced Egypt:** the Ptolemies and later the Roman emperors presented themselves in the temples as pharaohs, with the traditional titles and images, while governing in Greek and according to Mediterranean rules.',
    '**Papyri:** thousands of papyri, written in Greek, Demotic and Coptic, tell us how peasants, officials and women lived, as in no other ancient civilization.',
    '**Cleopatra and the Rosetta Stone:** the last Ptolemaic queen and the decree of 196 BC that, almost two thousand years later, would allow hieroglyphs to be deciphered.',
    '**Christianity and monasticism:** the Egyptian desert was the cradle of Christian monasticism, and the Coptic Church is one of the oldest in the world.',
    '**End and continuity:** the last hieroglyphic inscription (AD 394) and the last Demotic text (AD 452) close the history of a script nearly four thousand years old; Coptic kept the language alive.'
  ] },
  { img: 'epr-cleopatra-busto', leg: 'Bust of Cleopatra VII, Altes Museum, Berlin.' },
  { caixa: 'Ptolemaic and Roman Egypt today', texto: 'The great temples of **Edfu**, **Dendera**, **Kom Ombo**, **Esna** and **Philae** are Ptolemaic or Roman, and are among the most visited monuments in Egypt. In Alexandria, the **Bibliotheca Alexandrina** (2002) recalls the ancient Library, and underwater archaeologists continue to explore the ancient harbour and the submerged cities. The Coptic Church keeps alive in the 21st century the worship and the language of Christian Egypt.' },
  { img: 'epr-fayum-retrato', leg: 'Fayum funerary portrait of a man, encaustic painting on wood; National Archaeological Museum, Athens, 1627.' },
  { img: 'epr-mosteiro-santo-antonio', leg: 'Monastery of Saint Anthony, near the Red Sea.' }
];

const linha = [
  'This timeline follows the main events of Egypt between Alexander and the Arab conquest. For the Ptolemaic period most dates are exact to the year; where there is doubt, it is flagged.',
  { linha: [
    { d: '332 BC', t: 'Alexander arrives in Egypt', x: 'After defeating the Persians in Syria, **Alexander the Great** enters Egypt, which is handed to him without a fight by the Persian satrap Mazaces. The Egyptians, who hated the Persians, welcome him as a liberator. Alexander sacrifices to the Apis bull in Memphis. Whether he was formally crowned pharaoh is debated, because the Greek sources are ambiguous.' },
    { d: '331 BC', t: 'Foundation of Alexandria', x: 'Alexander lays out the plan of a new city on the coast, between the sea and Lake Mareotis, and visits the oracle of Amun at the oasis of **Siwa**, where, according to Greek authors, the priest greets him as the god’s son. He leaves Egypt never to return. Tradition credits the plan to the architect Dinocrates of Rhodes.' }
  ] },
  { img: 'epr-alexandre-luxor', leg: 'Alexander the Great depicted as pharaoh making an offering to Min, sanctuary of Luxor Temple.' },
  { linha: [
    { d: '323 BC', t: 'Death of Alexander; Ptolemy, satrap of Egypt', x: 'Alexander dies in Babylon, in June. The empire is divided among his generals, the Diadochi. **Ptolemy**, son of Lagos, receives Egypt and, in a famous coup, takes Alexander’s body to Egypt instead of letting it go on to Macedonia. The tomb, in Alexandria, was lost, and its exact location is unknown.' },
    { d: '305 / 304 BC', t: 'Ptolemy I proclaims himself king', x: 'Imitating the other Diadochi, Ptolemy I takes the title of king (whether in 305 or 304 BC is debated) and founds the Ptolemaic dynasty, the longest of the Hellenistic period, which will last until 30 BC. He is called **Soter**, “saviour”.' },
    { d: 'c. 295 – 280 BC', t: 'Museion, Library and Lighthouse', x: 'Under Ptolemy I and his son Ptolemy II the **Museion** (“house of the Muses”, a kind of research institute) and the **Library** are created in Alexandria. The **Lighthouse on the island of Pharos**, credited to Sostratus of Cnidus, is completed around 280 BC. Ancient authors give very high figures (hundreds of thousands of scrolls) that should be taken with caution.' },
    { d: '285 – 246 BC', t: 'Ptolemy II Philadelphus', x: 'He reigns with his sister and wife **Arsinoe II** (“sibling-lovers”), a scandalous novelty for the Greeks and a tradition well accepted by the Egyptians. He consolidates the state, builds the port of Berenike on the Red Sea and brings Egypt to its cultural height. In his time the Torah is translated into Greek, the basis of the future **Septuagint**; the story of 72 translators is legend, but the translation is real.' },
    { d: '274 – 168 BC', t: 'The six Syrian Wars', x: 'The Ptolemies and the Seleucids (who rule Syria and Mesopotamia) fight for more than a century over **Coele-Syria** (today’s Palestine and Lebanon). Egypt wins and loses territories over the course of the six wars.' },
    { d: '217 BC', t: 'Battle of Raphia', x: 'Ptolemy IV defeats the Seleucid Antiochus III at Raphia, on the Sinai border. The victory was possible because the king armed thousands of Egyptians as phalanx soldiers, according to the historian Polybius. Feeling their strength, the Egyptians rebel.' },
    { d: '205 – 186 BC', t: 'Revolt of the Thebaid', x: 'In Upper Egypt two native leaders, **Horwennefer** and then **Ankhwennefer**, proclaim themselves pharaohs and control Thebes for about twenty years. The revolt only ends in 186 BC. It shows that Ptolemaic rule, far from the delta, was fragile.' },
    { d: '196 BC', t: 'The Memphis decree (Rosetta Stone)', x: 'Priests meeting in Memphis publish a decree in honour of **Ptolemy V**, then a boy, with tax benefits for the temples and the order to carve it “in sacred script, in the script of documents and in Greek script”. It is the text of the **Rosetta Stone**, rediscovered in 1799.' },
    { d: '168 BC', t: 'The “Day of Eleusis”', x: 'The Seleucid king Antiochus IV invades Egypt. The Roman envoy **Gaius Popillius Laenas** draws a circle in the sand around him and orders him to decide before leaving it; Antiochus withdraws. It is the moment that shows Egypt already depends on Rome.' },
    { d: '51 BC', t: 'Cleopatra VII comes to the throne', x: 'Aged about 18, **Cleopatra VII** inherits the throne together with her brother Ptolemy XIII. She comes into conflict with him and his advisers.' },
    { d: '48 – 47 BC', t: 'Pompey, Caesar and Cleopatra', x: 'Pompey, defeated by Caesar at Pharsalus, flees to Egypt and is murdered at Pelusium on the orders of the young king’s advisers. **Julius Caesar** arrives in Alexandria, supports Cleopatra in the Alexandrian War (in which part of the harbour burns, and perhaps books) and stays with her. Caesarion is born (47 BC).' }
  ] },
  { img: 'epr-cleopatra-cesar', leg: 'Imagined meeting of Cleopatra VII and Julius Caesar in Alexandria, 48 BC. AI-generated illustration.' },
  { linha: [
    { d: '41 – 34 BC', t: 'Cleopatra and Mark Antony', x: 'The Roman **Mark Antony** meets Cleopatra at Tarsus (41 BC) and settles with her in Alexandria. They have three children. In 34 BC, in the so-called “Donations of Alexandria”, Antony distributes territories to the children, and Octavian uses this as propaganda against them.' },
    { d: '31 BC', t: 'Battle of Actium', x: 'On 2 September, Octavian’s fleet (commanded by Agrippa) defeats that of Antony and Cleopatra at Actium, on the Greek coast. The couple flee to Egypt.' }
  ] },
  { img: 'epr-batalha-accio', leg: 'Artistic interpretation of the naval Battle of Actium, 31 BC. AI-generated illustration.' },
  { linha: [
    { d: '30 BC', t: 'End of the Ptolemies', x: 'Octavian enters Alexandria on 1 August. Antony kills himself; Cleopatra dies shortly after (the traditional date is 12 August; ancient sources speak of poison and the bite of an asp, but the exact cause is debated). Her son Caesarion is put to death. Egypt becomes a Roman province.' },
    { d: '30 – 26 BC', t: 'Augustus’ province; Cornelius Gallus', x: 'Octavian (Augustus from 27 BC) turns Egypt into a personal domain: a **prefect** of the equestrian order governs in his name, and senators need imperial permission to enter. The first prefect, **Cornelius Gallus**, defeats a revolt in the south, has a trilingual inscription carved at Philae (29 BC) and eventually falls from favour.' },
    { d: '25 – 22 BC', t: 'War against Meroe', x: 'The prefect Gaius Petronius responds to attacks from the kingdom of Kush (Meroe) and advances through Nubia. The queen of Kush (the kandake, probably **Amanirenas**) negotiates peace with Augustus; the frontier is set in the region of Philae and the First Cataract. A bronze head of Augustus was found at Meroe and is now in the British Museum.' },
    { d: 'AD 115 – 117', t: 'Jewish revolt', x: 'During the reign of Trajan, the Jewish communities of Egypt, Cyrene and Cyprus rebel. The repression is brutal and the great Jewish community of Alexandria is almost wiped out.' },
    { d: 'AD 130', t: 'Hadrian in Egypt; Antinoopolis', x: 'The emperor **Hadrian** visits Egypt. His young companion **Antinous** drowns in the Nile, in circumstances the sources do not clarify. Hadrian founds the city of **Antinoopolis** in his honour.' },
    { d: 'AD 249 – 251', t: 'Decius and the last cartouches', x: 'The emperor **Decius**, who launched the first empire-wide persecution of Christians, is one of the last emperors with his name written in a hieroglyphic cartouche, in the temple of Esna. From then on, the temples receive ever fewer new works.' },
    { d: 'AD 297 – 298', t: 'Diocletian in Alexandria', x: 'After a long siege (eight months, according to some sources) of a revolt, the emperor **Diocletian** takes Alexandria. He reorganizes the provinces and the tax system. The “Pompey’s Pillar” was raised in his honour. The Coptic Church counts its years from Diocletian’s accession in 284, the “era of the martyrs”.' }
  ] },
  { img: 'epr-pilar-diocleciano', leg: 'Column of Diocletian, known as Pompey’s Pillar, Alexandria.' },
  { linha: [
    { d: 'AD 325 – 373', t: 'Athanasius and the Council of Nicaea', x: 'At the Council of Nicaea (325) Arianism is condemned, and **Athanasius**, bishop of Alexandria (from 328), becomes the great defender of the Nicene doctrine, with several exiles. In 367 he writes the first known list of the 27 books of the New Testament.' },
    { d: 'AD 391 – 394', t: 'End of the old cults', x: 'The emperor Theodosius I bans pagan cults. Bishop Theophilus destroys the **Serapeum** of Alexandria (391 or 392). The last dated hieroglyphic inscription, at Philae, is of 24 August 394.' },
    { d: 'AD 415', t: 'Death of Hypatia', x: 'The philosopher and mathematician **Hypatia** is murdered in Alexandria by a Christian mob, in the time of Patriarch Cyril. Cyril’s direct responsibility is debated.' },
    { d: 'AD 451', t: 'Council of Chalcedon', x: 'The council defines the nature of Christ in a way that the Church of Egypt rejects. The separation between the Coptic Church and the imperial Church begins to take shape from here.' },
    { d: 'c. AD 535 – 537', t: 'Philae is closed', x: 'According to the historian Procopius, the emperor Justinian orders the temple of Isis at Philae, the last focus of the old cult, to be closed and the sanctuary turned into a church. The last Demotic graffito at Philae is of 452.' },
    { d: 'AD 639 – 642', t: 'Arab conquest', x: 'The general **Amr ibn al-As** enters Egypt with a few thousand men (December 639), defeats the Byzantines at Heliopolis (640), takes the fortress of Babylon (next to present-day Cairo, April 641) and enters Alexandria in 642. The exact chronology varies according to the sources. The conquerors found **Fustat**, the first Islamic capital.' }
  ] },
  { img: 'epr-fortaleza-babilonia', leg: 'Remains of the Roman fortress of Babylon, Coptic Cairo.' }
];

const mapa = [
  'Ptolemaic and Roman Egypt is a territory of three very different regions: the **delta** (Lower Egypt) with Alexandria, the **valley** (Middle and Upper Egypt) and the **desert** with its roads and oases. Add to this the Red Sea coast, through which the trade of India and Arabia arrived, and **Nubia** to the south, where the empire ended. The following table gathers the main cities and places, with the Greek names used at the time.',
  { img: 'epr-farol-reconstrucao', leg: 'Conjectural reconstruction of the Lighthouse of Alexandria, c. 270 BC. AI-generated illustration.' },
  { tabela: { cab: ['Place', 'Greek or Roman name', 'Location today', 'What it is known for'], linhas: [
    ['Alexandria', 'Alexandreia', 'Alexandria, Egypt', 'Capital of the Ptolemies; Lighthouse, Museion, Library, Serapeum; largest city of Egypt'],
    ['Naukratis', 'Naukratis', 'Kom Gieif, delta', 'Ancient Greek colony, a trading centre since the 7th century BC'],
    ['Ptolemais', 'Ptolemais Hermiou', 'El Mansha, near Sohag', 'Greek city founded by Ptolemy I in Upper Egypt, with its own self-government'],
    ['Memphis', 'Memphis', 'Mit Rahina, near Giza', 'Ancient capital; cult of Apis; the site of priestly ceremonies and decrees'],
    ['Thebes', 'Diospolis Magna', 'Luxor and Karnak', 'Religious centre of the south; capital of native revolts; temples of Karnak and Medinet Habu still extended'],
    ['Edfu', 'Apollonopolis Magna', 'Edfu', 'Temple of Horus, the best-preserved in Egypt'],
    ['Dendera', 'Tentyris', 'Dendera', 'Temple of Hathor, with the zodiac and the images of Cleopatra and Caesarion'],
    ['Kom Ombo', 'Ombos', 'Kom Ombo', 'Double temple of Sobek and Horus the Elder'],
    ['Esna', 'Latopolis', 'Esna', 'Temple of Khnum, with cartouches of Decius, one of the last emperors written in hieroglyphs'],
    ['Philae', 'Philai', 'Island of Agilkia, Aswan', 'Sanctuary of Isis, the last to close (AD 535–537)'],
    ['Elephantine and Syene', 'Elephantine, Syene', 'Aswan', 'Southern frontier; Nilometer; granite quarries'],
    ['Fayum', 'Arsinoe (Krokodilopolis)', 'Fayum', 'Lands reclaimed from the lake by the Ptolemies; papyri and portraits'],
    ['Oxyrhynchus', 'Oxyrhynchos', 'El-Bahnasa', 'City of Middle Egypt, famous for its Greek papyri'],
    ['Hermopolis', 'Hermoupolis Magna', 'El-Ashmunein', 'City of the god Thoth (Hermes); great Christian centre'],
    ['Antinoopolis', 'Antinoopolis', 'Sheikh Abada', 'Founded by Hadrian in AD 130 in honour of Antinous'],
    ['Babylon', 'Babylon', 'Old (Coptic) Cairo', 'Roman fortress; Coptic quarter; next to Fustat'],
    ['Canopus and Heracleion', 'Kanopos, Thonis-Herakleion', 'Abu Qir Bay', 'Ancient ports, now under water'],
    ['Pelusium', 'Pelousion', 'Tell el-Farama', 'Fortress of the eastern frontier, where Pompey was killed'],
    ['Berenike', 'Berenike', 'Red Sea coast', 'Port of the India trade, founded by Ptolemy II'],
    ['Myos Hormos', 'Myos Hormos', 'Quseir al-Qadim (identification debated)', 'Red Sea port, linked to Koptos by road'],
    ['Koptos', 'Koptos', 'Qift', 'Starting point of the caravans to the Red Sea'],
    ['Tuna el-Gebel', '—', 'Near Mallawi', 'Necropolis of Hermopolis; tomb of Petosiris (c. 300 BC)'],
    ['Bahariya Oasis', '—', 'Western Desert', 'The “golden mummies” (1st–2nd century AD)'],
    ['Siwa', 'Ammonion', 'Western Desert', 'The oracle of Amun visited by Alexander'],
    ['Abu Mena', '—', 'Near Alexandria', 'Sanctuary of St Menas, a centre of Christian pilgrimage (5th–7th centuries)'],
    ['St Catherine', '—', 'Sinai', 'Monastery founded in the 6th century by Justinian']
  ] } },
  { h: 'Alexandria' },
  'Alexandria stood on a narrow strip of land between the sea and Lake Mareotis, and had two harbours, separated by a causeway, the **Heptastadion**, which linked the city to the island of Pharos, where the Lighthouse stood. It was laid out on a grid, with two great avenues that crossed. The **Royal Quarter**, in the centre, housed the palaces, the Museion and the tomb of Alexander (the Soma). The Serapeum, dedicated to Serapis, stood in the Egyptian quarter, to the south. Ancient authors estimate hundreds of thousands of inhabitants, but the figures are debated.',
  'Almost everything known about the ancient city comes from texts, because the modern city lies on top of the old one and part of the royal quarter sank into the sea through earthquakes and the rise of sea level. Underwater excavations in recent decades have found statues, columns and remains of the ancient harbour.',
  { h: 'The Lighthouse of Pharos' },
  'The Lighthouse, built in the time of Ptolemy II, was one of the **seven wonders of the ancient world**. Ancient authors describe it as a tower of three stages, with a fire at the top, and estimates of its height run to 100 metres or more. It was destroyed by several earthquakes, above all between the 10th and 14th centuries AD, and its stones were used to build the fort of Qaitbay, in 1477–1479, on the same spot. The word for “lighthouse” comes from the island’s name: phare in French, faro in Italian and Spanish.',
  { img: 'epr-forte-qaitbay', leg: 'Citadel of Qaitbay, Alexandria.' },
  { h: 'The great temples of Upper Egypt' },
  'The Ptolemies and the emperors went on building temples on the traditional model, and it was in this age that the best-preserved ones were completed. At **Edfu**, the temple of Horus took about 180 years to build (237–57 BC). At **Dendera** is the temple of Hathor, with the famous zodiac of the ceiling (the original is in the Louvre) and a relief of Cleopatra VII with her son Caesarion. At **Kom Ombo** there is a double temple, with two axes for two gods, and at **Esna** the temple of Khnum, of which the hypostyle hall remains, dug out below the level of the modern town.',
  { img: 'epr-templo-dendera', leg: 'Facade of the Temple of Hathor, Dendera.' },
  { h: 'Philae, the island of Isis' },
  'From the Ptolemies until the 6th century, Philae was the great sanctuary of **Isis**, attracting pilgrims from Egypt, Nubia and the Mediterranean. Roman emperors gave it monuments, such as “Trajan’s Kiosk”. It was the last Egyptian temple in operation, where native priests went on praying under Christian rule. With the building of the Aswan dam, the sanctuary was dismantled and rebuilt on the island of Agilkia, between 1972 and 1980, in an international UNESCO operation.',
  { img: 'epr-templo-filas', leg: 'Temple of Isis at Philae, Agilkia Island.' },
  { h: 'The Fayum and the desert towns' },
  'The Fayum, a depression with a lake west of the Nile, was transformed by the Ptolemies into a rich farming region, with canals and villages of Greek settlers. It is where many of the papyri of the period were found, and the famous **Fayum portraits**. **Oxyrhynchus**, farther south, became famous for supplying more than half a million papyrus fragments, among them lost Greek literary texts.',
  { h: 'The Red Sea ports' },
  'The Ptolemies founded **Berenike** and other ports for the trade in ivory, war elephants (hunting African elephants was a royal operation) and later spices and incense. In Roman times, Red Sea ships brought pepper and gems from India by taking advantage of the monsoons. The roads linking the Nile to the ports, crossing the Eastern Desert, had forts and water wells, and in the same mountains porphyry and granite quarries were opened for the emperors.',
  { img: 'epr-porto-berenike', leg: 'Artistic reconstruction of the port of Berenike and Red Sea trade, first century AD. AI-generated illustration.' },
  { h: 'Oases and necropolises' },
  'In the western desert, **Siwa** kept the oracle of Amun, and **Bahariya** was an important wine and caravan depot, where in 1996 dozens of gold-faced mummies (the “golden mummies”) were found. At **Tuna el-Gebel**, the necropolis of Hermopolis, the tomb of **Petosiris**, high priest of Thoth around 300 BC, shows the fusion of the Egyptian style with Greek influences, and in Alexandria the **Catacombs of Kom el-Shoqafa** (2nd century AD) combine Egyptian gods with Roman decoration.',
  { img: 'epr-kom-el-shoqafa', leg: 'Decorated sarcophagus and panel with the Apis bull, Catacombs of Kom el-Shoqafa, Alexandria.' },
  { h: 'Monasteries and Christian Egypt' },
  'From the 4th century the desert filled with monasteries. In **Wadi Natrun** and **Scetis** there were hundreds of monks, and in Upper Egypt **Pachomius** founded the first communal monasteries. Near the Red Sea are the monasteries of St Anthony and St Paul, and in Sinai that of **St Catherine**, of the 6th century, which holds one of the oldest collections of manuscripts and icons in Christendom.',
  { img: 'epr-santa-catarina', leg: 'Saint Catherine’s Monastery, Sinai.' },
  { h: 'Nubia and the southern frontier' },
  'The frontier lay near the First Cataract, at Philae and Syene. Farther south, the region between Aswan and Maharraqa, the so-called **Dodekaschoinos**, was controlled by the Ptolemies and the Romans, with temples such as Kalabsha and Dendur (the latter was dismantled and is now in New York). To the south reigned the kings of Kush (Meroe), and later, in the 4th century, the kingdom of Axum. In the 6th century, the Christian kingdoms of Nubia (Nobatia, Makuria and Alodia) arose from the evangelization of this area.',
  { h: 'Routes' },
  { lista: [
    '**The Nile:** the great river highway, with navigation downstream to the north and by sail, with the wind, to the south.',
    '**Trajan’s canal:** linked the Nile to the Red Sea (in the area of Babylon). It was restored by Trajan from an older canal.',
    '**Koptos – Red Sea:** caravans with water and escorts, between the Nile and the ports of Berenike and Myos Hormos.',
    '**Alexandria – Mediterranean:** grain fleets for Rome, with voyages that depended greatly on the winds.',
    '**Oasis routes:** from the Nile valley to Bahariya, Dakhla, Kharga and Siwa.'
  ] }
];

const sociedade = [
  'The Ptolemies and the Romans ruled a society with clearly distinct layers. The following sections describe how the state worked, how people lived, what they believed and what they knew, in the time of the Macedonian kings as well as that of the emperors.',
  { h: 'Politics: the Ptolemaic kingdom' },
  'The king was at once a **Hellenistic monarch** (king by right of conquest, military leader) and a **pharaoh** (son of Ra, lord of the Two Lands). He addressed the Greeks in Greek and the Egyptians in Egyptian. In Alexandria he was a Macedonian king; in the temples he appeared with the double crown and made offerings to the god.',
  'The **dynasty** was marked by marriages between siblings, a practice the Greeks found strange but which imitated the gods (Isis and Osiris, Zeus and Hera) and the Egyptian tradition. The worship of the king and queen, in life and after death, was obligatory. The Ptolemies adopted dynastic names (Ptolemy, Berenice, Arsinoe, Cleopatra) and dozens of epithets (Soter, Philadelphus, Euergetes, Philopator, Epiphanes...).',
  'The state was an immense **bureaucracy** stretching from the palace to the fields. The kingdom was divided into about forty districts (nomes), each with a strategos (military and civil chief), a royal scribe and an economic administrator. Everything was recorded on papyrus: land, harvests, taxes, contracts.',
  { h: 'Politics: Roman Egypt' },
  'After 30 BC, Egypt was governed in the emperor’s name by a **prefect** (praefectus Aegypti), a knight (not a senator), who lived in Alexandria and commanded the legions. Below him, officials called epistrategoi governed the great regions (Delta, Heptanomia, Thebaid), and the strategoi continued to govern the districts. The main towns, the **metropoleis**, only gained town councils (boulai) in AD 200, in the reign of Septimius Severus.',
  'In the temples, the emperor continued to be portrayed as pharaoh, with crown and cartouche, making offerings to the gods, even when he never set foot in Egypt. It is one of the clearest cases of ritual continuity.',
  { h: 'Classes and statuses' },
  { tabela: { cab: ['Group', 'Who they were', 'Privileges and duties'], linhas: [
    ['Greeks and Macedonians', 'Soldiers, officials, settlers, citizens of Alexandria', 'Top posts, land, lower taxes; Greek law'],
    ['Egyptians', 'Peasants, craftsmen, priests, scribes', 'The majority of the population; they worked the land, paid taxes; Egyptian law (Demotic)'],
    ['Jews', 'Large community in Alexandria and other cities', 'Community with its own organization; periodic tensions with the Greeks'],
    ['Romans and Italians', 'Soldiers, administrators, merchants (from 30 BC)', 'Roman citizenship; few in number at first'],
    ['Slaves', 'Prisoners, purchased or born into slavery', 'Domestic and farm labour; less numerous than in Rome']
  ] } },
  'After Augustus, society was divided into ranks: Roman citizens, citizens of Alexandria, Greeks of the metropoleis (who paid a lower poll tax) and Egyptians. The Constitutio Antoniniana (AD 212) made free men Roman citizens, which reduced these formal differences.',
  { h: 'Law and justice' },
  'The Ptolemies kept Egyptian laws for Egyptians, with their own courts (the laokritai, who judged in Demotic), and used Greek law for Greeks. The papyri preserve thousands of contracts, wills, petitions and complaints, which lets us see justice in action. Many petitions are from peasants complaining about abuses by officials or neighbours.',
  'Egyptian women had more rights than Greek women: they could own land, sign contracts and take part in business. Greek women in Egypt also gained a certain independence. The queen was a figure of power, and in official documents the queen often appears alongside the king.',
  { h: 'Religion: the gods of two worlds' },
  'The Ptolemies did not impose Greek gods on the Egyptians; they treated the two cults in parallel and created bridges between them. Egyptian temples had privileges and were extended with royal support, and the clergy met in synods (as at Canopus and Memphis) to decree honours to the king. To unite the two worlds a new god also appeared, **Serapis**, a god of Greek form with traits of Osiris and the Apis bull, whose promotion to official god is attributed to Ptolemy I (the attribution is debated).',
  { tabela: { cab: ['God', 'Domain', 'Where worshipped'], linhas: [
    ['Isis', 'Magic, motherhood, protection; a cult widespread in the Mediterranean', 'Philae, Alexandria and all over the Empire'],
    ['Serapis', 'Syncretic god: fertility, healing, the world of the dead', 'Serapeum of Alexandria, and cities of the Empire'],
    ['Horus of Edfu', 'Falcon god, victor over Seth, protector of the king', 'Temple of Edfu'],
    ['Hathor', 'Love, music, joy, cow goddess', 'Temple of Dendera'],
    ['Sobek', 'Crocodile god, lord of waters and fertility', 'Kom Ombo and the Fayum'],
    ['Khnum', 'Ram god, who moulds men on the potter’s wheel', 'Esna and Elephantine'],
    ['Amun', 'King of the gods; oracle of Siwa', 'Thebes and Siwa'],
    ['Anubis and Thoth', 'Mummification and the dead; writing and wisdom (Hermes for the Greeks)', 'Cynopolis; Hermopolis'],
    ['Harpocrates', 'Horus the child; popular on amulets and statuettes', 'Homes and tombs of Egypt and the Mediterranean']
  ] } },
  'In Roman times the cult of **Isis** and Serapis spread over the whole Empire, from Pompeii to London. Egypt went on mummifying the dead until the 3rd and 4th centuries (the practice declined with Christianity). The emperors presented themselves to the Egyptians as pharaohs and gave honours to the old gods, but the temples gradually lost their revenues and, at the end of the 4th century, the Christian state banned the old cults.',
  { h: 'Christianity and the Coptic Church' },
  'Tradition says that the evangelist **Mark** brought Christianity to Alexandria, around the middle of the 1st century, but there is no direct proof. By the 2nd century there was already a large Christian community, and the Catechetical School of Alexandria had teachers such as **Clement** and **Origen**. The persecutions of Decius and Diocletian made many martyrs, which the Coptic Church calls the “era of the martyrs”.',
  'In the 4th century, Christianity became the official religion, and Egypt had great figures: **Athanasius** (bishop of Alexandria), **St Anthony** and **Pachomius** (monasticism). In 451, the Council of Chalcedon divided the Church of Egypt from that of Constantinople: most Egyptians, **Miaphysites**, rejected the decisions of Chalcedon and organized their own Church, the **Coptic Church**, while a minority followed the emperor. The word “Copt” comes from the Greek Aigyptios, “Egyptian”.',
  { h: 'Writing and languages' },
  'In this period four scripts coexist: **Greek** (the language of administration, courts and science), **Demotic** (the everyday script of the Egyptians, until the 5th century), **hieroglyphs** (used only in temples, for sacred texts) and, from the 2nd–3rd century, **Coptic**, which writes Egyptian with the Greek letters plus six or seven signs inherited from Demotic. Coptic was the first way of writing Egyptian with an alphabet that also marks the vowels, and it allowed the translation of the Bible and monastic literature.',
  '**Papyrus** was the main writing material, and Egypt’s dry climate preserved it. The most famous archives are the archive of Zenon (3rd century BC, about a large estate in the Fayum) and the papyri of **Oxyrhynchus**. Ostraca (potsherds) were used for notes and receipts. The hieroglyphic script became ever more complicated, with hundreds of new signs, used by priests for games of scholarship.',
  { img: 'epr-pedra-roseta', leg: 'Rosetta Stone, British Museum, EA 24.' },
  { h: 'Economy and taxes' },
  'The Ptolemaic state controlled the economy as no other in the Mediterranean did. It kept **monopolies** over oil, salt, papyrus, linen and beer, and leased tax collection to entrepreneurs. Egypt had its own silver **coinage**, lighter than the Greek, which did not circulate outside the kingdom: anyone entering Egypt had to change their money.',
  { img: 'epr-moeda-ptolemeu-i', leg: 'Reverse of a silver tetradrachm of Ptolemy I Soter, c. 305–283 BC: eagle on a thunderbolt; Staatliche Münzsammlung, Munich.' },
  'Under the Romans, Egypt paid taxes in grain, in money and in labour, including the laographia (poll tax) created by Augustus. The historian Josephus says Egypt fed Rome for four months of the year (an ancient estimate, to be taken with care), and the grain fleet from Alexandria was vital to the capital. Egypt also exported papyrus, linen, glass and perfumes, and received from India pepper, gems, textiles and ivory.',
  { h: 'Farming, the Nile and water' },
  'Life depended on the Nile, and still depended on the annual flood, measured on **nilometers** (like that of Elephantine, used to calculate taxes). The Ptolemies introduced new irrigation techniques, such as the **saqiya** (ox-driven water wheel) and the Archimedes screw, and expanded crops such as the vine, the olive and durum wheat. They drained part of the Fayum lake and founded settlers’ villages there.',
  { img: 'epr-campo-saqiya', leg: 'Conjectural scene of saqiya irrigation in the Ptolemaic Fayum, third century BC. AI-generated illustration.' },
  { img: 'epr-nilometro-elefantina', leg: 'Nilometer at Elephantine, Aswan.' },
  { h: 'Cities and houses' },
  'The Greek cities of Egypt had a **gymnasium**, theatre, agora and temples, and streets laid out on a grid. Alexandria was the largest, but the towns of the valley (Oxyrhynchus, Hermopolis, Arsinoe) copied the same model. Houses were of mud brick, with a courtyard, stairs and flat roofs; richer ones had mosaics, paintings and baths. Many houses had dovecotes, and pigeon towers were a feature of the landscape.',
  { img: 'epr-rua-alexandria-romana', leg: 'Commercial street in Roman Alexandria, second century AD: artistic interpretation. AI-generated illustration.' },
  { h: 'Food' },
  'The basis was still **bread** and barley **beer**, with vegetables (onion, garlic, lentils, beans), fruit (figs, dates, grapes) and Nile fish. The Greeks brought a taste for **wine** and olive oil, and the Ptolemies encouraged viticulture. The papyri contain recipes, shopping lists and banquet accounts, and the poorest ate very little meat.',
  { h: 'Clothing and appearance' },
  'The Greeks wore the **chiton** and **himation** of wool or linen; the Egyptians kept linen and the kilt (shendyt) or tunic. In time fashion merged: the linen tunic with decorative bands became the common dress. **Coptic textiles** are famous for their woven decorations in coloured wool, with mythological and Christian scenes. Women wore jewellery, wigs and make-up, and hairstyles changed with the fashion of Rome, which the Fayum portraits document very well.',
  { img: 'epr-tecido-copto', leg: 'Coptic textile roundel in linen and wool, fourth century AD, Kharga Oasis; Metropolitan Museum, 33.10.51.' },
  { h: 'Music, games and festivals' },
  'Music was everywhere: harps, double flutes, lyres, sistra and drums. The Alexandrian **Ctesibius** invented, in the 3rd century BC, the **water organ** (hydraulis), ancestor of the organ. People played **senet** and the game of twenty squares, dice and board games. In Alexandria there were theatres, horse and chariot races, music contests and the great **processions** (Ptolemy II held one, described by Callixeinus of Rhodes, with floats, exotic animals and thousands of participants).',
  { h: 'Education, Museion and Library' },
  'Greek boys went to the **gymnasium** and learned gymnastics, music, reading and writing (the “ephebeia”). The sons of Egyptian scribes learned in temple schools. The **Museion** of Alexandria was a research institute maintained by the king, where scholars received lodging, food and exemption from taxes. The **Library** aimed to gather the books of the known world: ships that arrived in port were searched and their books copied (according to the physician Galen). The ancient figures (400,000 to 700,000 scrolls) are probably exaggerated.',
  { img: 'epr-biblioteca-estudiosos', leg: 'Hypothetical interior of the Library of Alexandria, third century BC, with scholars and papyrus scrolls. AI-generated illustration.' },
  { h: 'Science and mathematics' },
  'Alexandria was the great scientific centre of the Hellenistic world. **Euclid** wrote the Elements of geometry, around 300 BC. **Eratosthenes**, head of the Library, calculated the circumference of the Earth by comparing the angle of the noon shadow in Alexandria and in Syene (Aswan), at the summer solstice; the value depends on the length of the stade used, which is debated, but the method was brilliant. Greek astronomy, from Aristarchus and Hipparchus, culminated in Alexandria with **Claudius Ptolemy** (2nd century AD), author of the Almagest, which dominated science until Copernicus. **Hero of Alexandria** described steam devices and automata (1st century AD).',
  { img: 'epr-esquema-eratostenes', leg: 'Educational diagram of Eratosthenes’ method: parallel sunlight, a well at Syene and a shadow at Alexandria; dimensions and angle exaggerated for readability.' },
  { h: 'Medicine' },
  'The physicians of Alexandria, such as **Herophilus** and **Erasistratus** (3rd century BC), were the first to perform systematic dissections of the human body and identified the brain as the centre of the nervous system, along with nerves and vessels. Some ancient authors, such as Celsus, accused them of vivisecting condemned prisoners; the accusation is debated. In the 2nd century AD, **Galen**, who studied in Alexandria, became the great medical authority of Antiquity. The papyri also show temple medicine, with cures during sleep and prayers to Isis and to Imhotep (identified with Asclepius).',
  { h: 'Technology and engineering' },
  'Among the inventions and works of the period are the **Lighthouse**, the water organ, the saqiya, the Archimedes screw (according to tradition, conceived during a visit to Egypt), Hero’s automata and the great ships and canals. Roman engineers built roads, forts and Trajan’s canal, and worked quarries in the Eastern Desert, such as **Mons Claudianus** (granite) and **Mons Porphyrites** (purple porphyry, reserved for emperors).',
  { h: 'War and the army' },
  'The Ptolemaic army combined **Greek mercenaries**, who received land (klerouchoi), a rank of Egyptian soldiers (machimoi, from Raphia) and African **war elephants**, hunted on the Red Sea. The navy, with giant galleys, dominated the eastern Mediterranean in the 3rd century BC. Under the Romans, Egypt was at first guarded by three legions, later two and finally one, plus auxiliary troops, which shows it was a quiet province despite occasional revolts. In Byzantine times, the troops were frontier units, and Egypt was taken by the Arabs after decades of exhaustion in wars with Persia.',
  { h: 'Art and architecture' },
  'Ptolemaic art mixes. In the temples it keeps the Egyptian style, with reliefs on the wall and columns with composite flower capitals, but the king’s face and posture show Greek influences. In Alexandria, buildings were in Greek style (colonnades, gymnasia, theatres). Sculpture gave the kings a Hellenistic look, more realistic and emotional. Roman art also brought mosaics and wall paintings.',
  'The best example of cultural fusion is the **Fayum portraits**: faces of people painted on wood (in encaustic or tempera) over the face of mummies, in a very realistic Graeco-Roman style, but used in an Egyptian ritual. About a thousand are known, datable from the 1st to the 3rd century AD. The **Coptic art** that followed developed its own style, more stylized, in textiles, icons, manuscripts and churches.',
  { img: 'epr-oficina-retratos', leg: 'Funerary portrait workshop in the Fayum, second century AD, with encaustic painting and preparation of a mummy. AI-generated illustration.' },
  { img: 'epr-mumia-dourada-bahariya', leg: 'Mummy with a gilded face from Bahariya Oasis.' },
  { h: 'Everyday papyri' },
  'Thanks to the dry climate, Egypt is the place in the ancient world with the most everyday documents to have survived. There are letters from soldiers and anxious mothers, marriage contracts, recipes, receipts, shopping lists, horoscopes, school lessons and petitions. The fragments of **Oxyrhynchus** were discovered by Bernard Grenfell and Arthur Hunt from 1897 in a rubbish mound of the ancient city, and are still being edited in Oxford, more than a century later.',
  { img: 'epr-papiro-oxirrinco', leg: 'Greek Oxyrhynchus papyrus P.Oxy. I 29: fragment of Euclid’s Elements.' },
  { h: 'Mummification in Graeco-Roman times' },
  'Mummification continued, but it changed. Embalmers became more concerned with the exterior than the interior: they wrapped the body in complex geometric patterns, applied portraits or masks and gilded the face. Bodies were sometimes less well preserved. There were enormous cemeteries, such as that of the ibises and sacred animals at Saqqara and Tuna el-Gebel. With the arrival of Christianity, the custom was abandoned in the 4th–5th centuries.',
  { h: 'Women and family' },
  'The Ptolemaic queens had enormous power (Arsinoe II, Berenice II, Cleopatra III, Cleopatra VII). In ordinary society, Egyptian marriage contracts gave the woman rights of her own, and Greek women in Egypt signed contracts and managed land. In the Roman-Egyptian censuses there are many documented cases of sibling marriage in ordinary families, a phenomenon historians debate. Children were brought up early for work, and many died in childhood.',
  { h: 'Calendar' },
  'The Egyptian calendar had 365 days, with no leap day. The Decree of Canopus (238 BC) proposed adding one day every four years, but it was not applied. Around 26–25 BC Augustus introduced in Alexandria the **Alexandrian calendar**, with a leap year, on the same lines as the Julian calendar. The **Coptic calendar** derives from it, and the Coptic Church counts the years from AD 284 (the “era of the martyrs”).',
  { h: 'The end of ancient Egypt' },
  'The end of the old cults was slow. The last imperial cartouches in hieroglyphs date from the 3rd century, the last dated hieroglyph is of 394 and the last Demotic graffito, at Philae, of 452. The temples were abandoned, closed or turned into churches, like that of Philae in the 6th century. But many traditions survived: the calendar, names, festivals, the Coptic language, art, monasteries. Christian Egypt and pharaonic Egypt were not two separate worlds.',
  { h: 'Neighbouring peoples' },
  'Ptolemaic and Roman Egypt was surrounded by active peoples: the Seleucids (Syria), the Antigonids (Macedonia), the kingdoms of Kush and later Axum (south), the Nubians, the Libyans and the nomads of the Eastern Desert, the Parthians and Sasanian Persians (east) and, above all, Rome. Diplomacy, marriage and war defined relations. Frontiers were fluid, and Egypt was a crossroads of cultures.'
];

const personalidades = [
  'The following figures were chosen from among many names. They mix kings and queens, scholars, Christians and the man who took Egypt into Islam. Where the stories surrounding them are legend or uncertain, this is flagged.',
  { h: 'Alexander the Great (356 – 323 BC)' },
  'King of Macedonia and conqueror of the Persian Empire. He entered Egypt in 332 BC, where he was received without a fight, and founded **Alexandria** in 331. He visited the oracle of Amun at the oasis of Siwa. He died in Babylon, aged 32. His body was taken to Egypt by Ptolemy, and the tomb in Alexandria was visited until Late Antiquity; afterwards it was lost. The Egyptians kept an image of him as a pharaoh.',
  { h: 'Ptolemy I Soter (c. 367 – 283 BC)' },
  'A general of Alexander who took Egypt and founded the dynasty. He was satrap from 323 BC and king from 305 or 304. He won several wars against the other Diadochi, created the Museion and the Library and became known for writing a history of Alexander’s campaigns, now lost. He passed the throne to his son Ptolemy II while still alive.',
  { h: 'Arsinoe II (c. 316 – 270 BC)' },
  'Daughter of Ptolemy I, she was queen of Thrace (married to Lysimachus) and then of Egypt, where she married her own brother Ptolemy II. She had great political and military influence. After her death she was worshipped as a goddess, and her cult spread throughout Egypt. Gold coins with her portrait, the mnaieia, were minted after her death.',
  { img: 'epr-arsinoe-ii-octodracma', leg: 'Obverse of a gold octodrachm with Arsinoe II’s portrait, issued under Ptolemy V or VI, 205–145 BC; Cleveland Museum of Art, 1965.552.a.' },
  { h: 'Manetho of Sebennytos (3rd century BC)' },
  'An Egyptian priest who lived in the time of Ptolemy I and II and wrote in Greek the Aegyptiaca, the first history of Egypt written by an Egyptian. He divided the kings into **30 dynasties**, a division still in use, to which Egyptologists later added a 31st (the second Persian rule). The work is known only from quotations by later authors, and there are errors and additions, so it is used with care.',
  { h: 'Eratosthenes of Cyrene (c. 276 – c. 194 BC)' },
  'Mathematician, geographer and head of the Library of Alexandria. He calculated the circumference of the Earth and made one of the first maps of the known world. He was nicknamed “Beta”, for being second in everything. In old age, he is said to have starved himself to death after going blind, a late story that is not secure.',
  { h: 'Cleopatra VII Philopator (69 – 30 BC)' },
  'The last queen of the Ptolemies. She was cultured (the ancient source Plutarch says she was the first of the family to learn Egyptian), governed in alliance with **Julius Caesar** and then with **Mark Antony** and tried to keep Egypt independent. She was defeated at Actium and died in 30 BC. The image we have of her, that of a seductress, comes largely from Roman propaganda. Her coins show a face with a strong nose, which contrasts with her legendary beauty. It is not known where she is buried.',
  { img: 'epr-cleopatra-dendera', leg: 'Relief of Cleopatra VII and Caesarion, Temple of Hathor, Dendera.' },
  { h: 'Cornelius Gallus (c. 69 – 26 BC)' },
  'A Roman poet and soldier, friend of Augustus, he was the first prefect of Egypt (30–26 BC). He defeated a revolt in the south and had an inscription in Latin, Greek and hieroglyphs carved at Philae boasting of his deeds (29 BC). Augustus withdrew his favour, and Gallus killed himself. Of his poems only a fragment survives.',
  { img: 'epr-augusto-meroe', leg: 'Bronze head of Augustus from Meroe, British Museum.' },
  { h: 'Philo of Alexandria (c. 20 BC – c. AD 50)' },
  'A Greek-speaking Jewish philosopher, who combined the Hebrew Bible with the philosophy of Plato, reading the sacred texts allegorically. He led an embassy of Alexandrian Jews to the emperor Caligula, after the riots of AD 38, and left an account of the events. His work influenced the Church Fathers.',
  { h: 'Hadrian (AD 76 – 138) and Antinous' },
  'The emperor **Hadrian** visited Egypt in AD 130 with the young Bithynian **Antinous**, who drowned in the Nile that year. The causes are unknown (accident, suicide, ritual sacrifice: all hypotheses). Hadrian deified him and founded **Antinoopolis**. Antinous was portrayed in hundreds of statues across the Empire.',
  { img: 'epr-antinoo-busto', leg: 'Detail of the marble bust of Antinous from Patras, AD 130–138; National Archaeological Museum, Athens.' },
  { h: 'Claudius Ptolemy (c. AD 100 – c. 170)' },
  'An astronomer, mathematician and geographer who worked in Alexandria (he was unrelated to the Ptolemaic kings). He wrote the Almagest, in which he explains the movement of the planets with a geocentric system, the Geography, with coordinates of thousands of places, and the Tetrabiblos, on astrology. His astronomy was the reference for the Islamic and European world until the 16th century.',
  { h: 'St Anthony the Great (c. AD 251 – 356)' },
  'Born in a village of Middle Egypt, he withdrew to the desert around 285 to live as a hermit, and attracted disciples. His life, written by **Athanasius**, made him the model of monks. Tradition gives him 105 years of life (the age is doubtful). He is considered the “father of monks”, though there had been hermits before him.',
  { img: 'epr-eremita-deserto', leg: 'Christian hermit in the Egyptian desert, fourth century AD: artistic interpretation. AI-generated illustration.' },
  { h: 'Pachomius (c. AD 292 – 346)' },
  'Born a pagan at Esna and converted after serving as a soldier, he founded around 320 at Tabennisi, in Upper Egypt, the first **communal** (cenobitic) monastery, with a rule and shared work. At his death he left monasteries with thousands of monks. His experience shaped later monastic life, in East and West.',
  { h: 'Athanasius of Alexandria (c. AD 296 – 373)' },
  'Bishop of Alexandria from 328 to 373, the great opponent of Arianism. He was exiled five times, by emperors hostile to him. He wrote the Life of St Anthony and, in 367, the Easter letter that contains the list of the 27 books of the New Testament, the same as is used today. He is a saint of the Coptic Church and of the other Christian Churches.',
  { h: 'Hypatia of Alexandria (c. AD 360 – 415)' },
  'A mathematician, astronomer and Neoplatonist philosopher, daughter of Theon, she taught in Alexandria and was respected by Christians and pagans alike. In March 415 she was murdered by a Christian mob, amid a dispute between the prefect Orestes and the patriarch Cyril. Cyril’s responsibility is debated. She was later turned into a symbol, but her works were lost, and the image of a martyr of science is in part a modern construction.',
  { h: 'Amr ibn al-As (c. AD 585 – 664)' },
  'The Arab general who conquered Egypt between 639 and 642 and was its first Muslim governor. He founded **Fustat**, next to the fortress of Babylon, and the mosque that bears his name today, the oldest in Egypt (the present building, however, is much later). The stories about the destruction of the Library of Alexandria on his orders are late legends, with no support in the early sources.'
];

const legado = [
  'Ptolemaic, Roman and Christian Egypt did not end suddenly in 641. It left an enormous legacy of texts, temples, ideas, a language and a Church, which is preserved and studied to this day.',
  { h: 'The Rosetta Stone and the decipherment' },
  'The **Rosetta Stone** was found in July 1799 by French soldiers near Rosetta (Rashid), in the delta. Handed to the British in 1801, in the capitulation of the French troops, it has been in the British Museum since 1802. The text, the same in hieroglyphs, Demotic and Greek, allowed **Jean-François Champollion** to decipher hieroglyphic writing in 1822, building on earlier work by Thomas Young. It is the key that opened the history of ancient Egypt.',
  { h: 'The papyri' },
  'The Greek, Demotic and Coptic papyri of Egypt are the greatest source of stories of everyday life in Antiquity. At Oxyrhynchus, Grenfell and Hunt found from 1897 more than half a million fragments, with poems of Sappho, comedies of Menander, letters and accounts. Many are still unread and continue to be published in Oxford.',
  { h: 'Alexandria and the Library' },
  'The myth of the burned Library weighs on our imagination, but the story is more complex: there was no single fire. Caesar’s war (48 BC) burned warehouses by the harbour, the emperor Aurelian razed the Royal Quarter around AD 272, and the Serapeum was destroyed in 391. The idea that the caliph Omar ordered it burned is a 13th-century legend. In 2002 the **Bibliotheca Alexandrina**, designed by the firm Snøhetta, was opened as a tribute.',
  { h: 'Underwater archaeology' },
  'Since the 1990s divers and archaeologists, such as Jean-Yves Empereur and Franck Goddio, have explored the ancient harbour of Alexandria and the cities of **Canopus** and **Thonis-Heracleion** (discovered in 2000), sunk by earthquakes and floods. They found statues, temples, boats and coins. The remains of the Royal Quarter, of the Caesareum and of the Lighthouse lie under water. The tomb of Alexander has not been found, nor that of Cleopatra, despite several searches (the one at Taposiris Magna, since 2005, has proved nothing).',
  { h: 'Serapis, Isis and the religion of the Empire' },
  'The cult of Isis and Serapis spread across the rest of the Mediterranean, with temples in Rome, in Pompeii and on the Iberian Peninsula. The image of **Isis nursing Horus** inspired, according to some historians, the Christian iconography of the Virgin and Child, a debated thesis. The Roman taste for Egypt (“Egyptomania”) left pyramids, obelisks and sphinxes: it is often said that Rome has more ancient obelisks than Egypt, brought by Augustus and other emperors.',
  { h: 'The Septuagint, Philo and the Hermetic tradition' },
  'The **Septuagint**, the Greek translation of the Hebrew Bible made in Alexandria, was the Bible of the first Greek-speaking Christians. The Hermetic texts (Corpus Hermeticum, 2nd–3rd centuries AD), attributed to Hermes Trismegistus, a figure that fuses Thoth and Hermes, and Alexandrian alchemy shaped the esotericism of the Middle Ages and the Renaissance.',
  { h: 'Egyptian Christianity and its manuscripts' },
  'The monasteries, bishoprics and pilgrimages of Christian Egypt influenced Europe. At **Nag Hammadi**, thirteen papyrus codices with Gnostic texts in Coptic, of the 4th century, such as the Gospel of Thomas, were found in 1945. At the monastery of **St Catherine**, in Sinai, the Codex Sinaiticus, one of the oldest complete Bibles in Greek, was found in the 19th century (now kept mainly in London). The Coptic Church is today one of the largest Christian communities of the Middle East.',
  { img: 'epr-codice-nag-hammadi', leg: 'Page 32 of Nag Hammadi Codex II, with the end of the Apocryphon of John and the beginning of the Gospel of Thomas; Coptic Museum, Cairo.' },
  { h: 'The Coptic language' },
  '**Coptic** is the last phase of the Egyptian language, and the only one written with Greek letters. It stopped being spoken in daily life around the Middle Ages, but it is still the liturgical language of the Coptic Church. Some words came from Egyptian through Greek (an Egyptian origin of “oasis” is probable), and the name “Egypt” comes from the Greek Aigyptos, which derived from Hut-ka-Ptah, “the castle of the ka of Ptah”, a name of Memphis.',
  { h: 'Cleopatra in culture' },
  'Cleopatra is one of the most portrayed women in history: from Plutarch and Shakespeare (Antony and Cleopatra) to the canvases of painters such as Tiepolo, to operas (Handel) and cinema (with Elizabeth Taylor in 1963). The image varies between the dangerous seductress, for the Romans, and the tragic heroine, for the Romantics. Today’s historians insist on her political intelligence and her culture.',
  { h: 'Obelisks and “Cleopatra’s Needles”' },
  'The two obelisks called **Cleopatra’s Needles**, now in London (1878) and New York (1881), were raised at Heliopolis by Thutmose III, in the 15th century BC, and moved by Augustus to Alexandria around 13/12 BC. They have no direct connection with the queen. They were given in the 19th century to the British and the Americans.',
  { h: 'Where to visit' },
  { lista: [
    '**Alexandria:** Graeco-Roman Museum, Catacombs of Kom el-Shoqafa, Pillar of Diocletian, fort of Qaitbay, Roman auditoria of Kom el-Dikka, Bibliotheca Alexandrina and the National Museum.',
    '**Upper Egypt:** the temples of Edfu, Dendera, Kom Ombo, Esna and Philae, and the Grand Egyptian Museum in Giza.',
    '**Fayum, Bahariya and Siwa:** the oases, the ruins of Karanis and Tebtunis and the museum at Bahariya.',
    '**Coptic Cairo:** the Hanging Church, the fortress of Babylon, the Coptic Museum and the mosque of Amr.',
    '**Monasteries:** St Anthony, St Paul, Wadi Natrun and St Catherine (Sinai).',
    '**Outside Egypt:** the British Museum (the Rosetta Stone), the Louvre (the Dendera zodiac and Fayum portraits), the Altes Museum in Berlin, the Metropolitan in New York (the temple of Dendur) and the Vatican museums.'
  ] },
  { img: 'epr-igreja-suspensa', leg: 'Hanging Church, Al-Muallaqa, Coptic Cairo.' },
  { img: 'epr-quiosque-trajano', leg: 'Trajan’s Kiosk, Philae.' }
];

const quiz = [
  { p: 'Who founded Alexandria, in 331 BC?', op: ['Ptolemy I', 'Augustus', 'Cleopatra VII', 'Alexander the Great'], certa: 3, exp: 'Alexander laid out the plan of the city on entering Egypt; only later did it become the capital of the Ptolemies.' },
  { p: 'Which of Alexander’s generals took Egypt and founded a dynasty?', op: ['Seleucus', 'Antigonus', 'Lysimachus', 'Ptolemy'], certa: 3, exp: 'Ptolemy, son of Lagos, was satrap and then king (305 or 304 BC).' },
  { p: 'In what language was Ptolemaic Egypt administered?', op: ['Latin', 'Aramaic', 'Greek', 'Coptic'], certa: 2, exp: 'Greek was the language of administration, although Demotic continued to be used by the Egyptians.' },
  { p: 'Which three scripts does the Rosetta Stone have?', op: ['Hieroglyphic, hieratic and Greek', 'Hieroglyphic, Demotic and Greek', 'Cuneiform, Greek and Latin', 'Hieroglyphic, Coptic and Latin'], certa: 1, exp: 'The decree of 196 BC is in hieroglyphs, Demotic and Greek.' },
  { p: 'Which Alexandrian structure was one of the seven wonders of the ancient world?', op: ['The Library', 'The Serapeum', 'The Lighthouse of Pharos', 'The Museion'], certa: 2, exp: 'The Lighthouse was completed around 280 BC and collapsed in earthquakes, much later.' },
  { p: 'Who calculated the circumference of the Earth using the Sun’s shadow at Syene and Alexandria?', op: ['Eratosthenes', 'Euclid', 'Ptolemy', 'Herophilus'], certa: 0, exp: 'Eratosthenes was head of the Library; the exact value of his result depends on the stade used, but the method was correct.' },
  { p: 'Who was the last Ptolemaic queen?', op: ['Arsinoe II', 'Berenice II', 'Cleopatra VII', 'Nefertiti'], certa: 2, exp: 'Cleopatra VII reigned from 51 to 30 BC.' },
  { p: 'In which battle were Mark Antony and Cleopatra defeated, in 31 BC?', op: ['Pharsalus', 'Actium', 'Raphia', 'Philippi'], certa: 1, exp: 'The naval battle of Actium, on 2 September 31 BC, gave victory to Octavian.' },
  { p: 'Who was the first Roman prefect of Egypt?', op: ['Cornelius Gallus', 'Gaius Petronius', 'Flaccus', 'Pompey'], certa: 0, exp: 'Gallus governed from 30 to 26 BC and had a trilingual stele inscribed at Philae.' },
  { p: 'Which emperor founded Antinoopolis, after the death of his companion in the Nile?', op: ['Trajan', 'Augustus', 'Diocletian', 'Hadrian'], certa: 3, exp: 'Hadrian founded the city in AD 130, in honour of Antinous.' },
  { p: 'What are the Fayum portraits?', op: ['Statues of the Ptolemies', 'Painted funerary portraits placed over mummies', 'Mosaics of Alexandria', 'Portraits of emperors on coins'], certa: 1, exp: 'Painted on wood, between the 1st and 3rd centuries AD, they combine Graeco-Roman realism and Egyptian ritual.' },
  { p: 'Who is considered the founder of communal (cenobitic) monasticism in Egypt?', op: ['St Anthony', 'Athanasius', 'Origen', 'Pachomius'], certa: 3, exp: 'Pachomius founded the monastery of Tabennisi, with a common rule, around 320. St Anthony is the model of hermits.' },
  { p: 'Which Church arose from Egypt’s rejection of the decisions of the Council of Chalcedon (451)?', op: ['Greek Orthodox Church', 'Coptic Church', 'Armenian Church', 'Anglican Church'], certa: 1, exp: 'Most Egyptians, Miaphysites, organized the Coptic Church.' },
  { p: 'Which was the last Egyptian temple to close, according to Procopius, in the time of Justinian?', op: ['The temple of Isis at Philae', 'Karnak', 'Dendera', 'Abu Simbel'], certa: 0, exp: 'Procopius reports the closure in AD 535–537.' },
  { p: 'Which Arab general conquered Egypt, from 639 to 642?', op: ['Umar ibn al-Khattab', 'Amr ibn al-As', 'Khalid ibn al-Walid', 'Saladin'], certa: 1, exp: 'Amr ibn al-As also founded Fustat, the first Islamic capital of Egypt.' }
];

export default { visao, linha, mapa, sociedade, personalidades, legado, quiz };
