// MONARQUIA E REPÚBLICA ANTIGA (753–264 a.C.) — conteúdo completo em português. A versão inglesa está em dados-en.js (mesma estrutura).
// Cronologia: datas «varronianas» (de Varrão, séc. I a.C.), as convencionais para a tradição romana (753 a.C., 509 a.C.); para a época arcaica indica-se sempre o que é tradição e o que é arqueologia.
// Fontes antigas principais: Lívio (*Ab Urbe Condita*, livros 1–10), Dionísio de Halicarnasso, Políbio, Plutarco, Cícero (*De Re Publica*); o grosso foi escrito séculos depois dos factos.
// Imagens: cada {img:'id'} procura o ficheiro  roma/monarquia-republica/img/id.jpg  (ver IMAGENS_ROMA_MONARQUIA_REPUBLICA.md).
import EN from './dados-en.js';
import CRED from './creditos.js';
import { GRUPO } from '../grupo.js';

const visao = [
  { caixa: 'Em resumo', texto: [
    'Esta página conta como uma aldeia de pastores e agricultores do Lácio, junto ao Tibre, se tornou, em cerca de **quinhentos anos**, a senhora de toda a península italiana. Começa na **fundação**, que a tradição romana data de **753 a.C.** (e que a arqueologia mostra ser um processo lento, entre os séculos X e VI a.C.), passa pelos **sete reis**, pela revolução de **509 a.C.** que instaurou a **República**, pela longa luta entre patrícios e plebeus (o **Conflito das Ordens**), pelas **Leis das XII Tábuas**, pelas guerras contra Etruscos, Latinos, Gauleses e **Samnitas**, e termina com a derrota de **Pirro** e a conquista da Itália, em **264 a.C.**, na véspera da Primeira Guerra Púnica.',
    'Há uma dificuldade que o leitor deve ter presente: quase tudo o que se sabe sobre os primeiros séculos foi escrito por autores como Lívio (séc. I a.C.) ou Dionísio de Halicarnasso, **trezentos a setecentos anos depois dos factos**. Por isso, ao longo da página, distingue-se sempre a **tradição lendária** («segundo Lívio…») da **arqueologia** e da **história documentada**.'
  ] },
  { img: 'rmr-forum-romano', leg: 'Fórum Romano visto do Capitólio.' },
  { h: 'Onde e quando' },
  'Roma nasceu a cerca de 25 km da foz do Tibre, num ponto onde o rio podia ser atravessado com facilidade, na **Ilha Tiberina**, e onde se cruzavam a rota do sal (a futura *Via Salaria*, que levava o sal das salinas da foz do Tibre ao interior sabino) e o caminho entre a Etrúria, a norte, e a Campânia grega, a sul. A cidade assentava em colinas de tufo vulcânico, as célebres **sete colinas** (Palatino, Capitolino, Quirinal, Viminal, Esquilino, Célio e Aventino), com um vale baixo e pantanoso, o futuro Fórum, entre elas. Era um sítio defensável, perto do rio, mas não demasiado perto do mar, e à beira de duas grandes civilizações: os **Etruscos**, a norte, e os **Gregos** das colónias do sul.',
  { img: 'rmr-mapa-italia-povos', leg: 'Povos da Itália, c. 400 a.C.' },
  { tabela: { cab: ['Fase', 'Datas (convencionais)', 'O que a caracteriza'], linhas: [
    ['Aldeias do Lácio', 'c. 1000 – 750 a.C.', 'Idade do Ferro; cabanas no Palatino e túmulos no futuro Fórum (cultura Lacial)'],
    ['Fundação e Monarquia', '753 – 509 a.C. (tradição)', 'Sete reis; a cidade cresce sob forte influência etrusca e grega; templo de Júpiter Capitolino'],
    ['Primeira República', '509 – 367 a.C.', 'Dois cônsules anuais, Senado; tribunos da plebe; XII Tábuas; guerras com Équos, Volscos, Veios; saque gaulês (390)'],
    ['Conquista do Lácio e da Campânia', '367 – 295 a.C.', 'Leis Licínio-Sêxtias; Guerra Latina; Guerras Samnitas; Via Ápia; Sentino'],
    ['Senhora da Itália', '295 – 264 a.C.', 'Lei Hortênsia (287); guerra contra Pirro (280–275); queda de Tarento (272); sistema de aliados itálicos']
  ] } },
  { img: 'rmr-mapa-expansao', leg: 'Mapa das fases da conquista romana de Itália, incluindo as guerras Púnicas.' },
  { h: 'Porque importa' },
  'Os Romanos não inventaram a ideia de cidade-Estado nem a de república, mas fizeram dela algo novo: um Estado que **integrava os vencidos** em vez de os eliminar, dando-lhes, conforme os casos, cidadania plena, cidadania sem voto ou o estatuto de aliados. Foi este sistema, e não só a força militar, que lhe permitiu repor, geração após geração, as legiões perdidas (Pirro, que venceu batalhas e não ganhou a guerra, percebeu-o à sua custa). As instituições desta época (cônsules, Senado, assembleias, tribunos, a ideia de uma **lei escrita** válida para todos) são a origem direta de muito do vocabulário político do Ocidente.',
  { lista: [
    '**Instituições:** a divisão do poder entre magistrados, Senado e povo, a anualidade e a colegialidade dos cargos, o veto e a responsabilidade política.',
    '**Direito:** as XII Tábuas (c. 450 a.C.) são o ponto de partida do direito romano, que marcaria a Europa durante dois milénios.',
    '**Expansão:** o modelo de colónias, estradas e alianças desenvolvido na Itália será aplicado depois ao Mediterrâneo.',
    '**Memória e mito:** Rómulo e Remo, Lucrécia, Horácio, Cincinato ou Camilo foram contados e recontados durante séculos como modelos de virtude e de vício cívico.'
  ] },
  { h: 'Fundação: mito e arqueologia' },
  'Segundo a tradição, **Rómulo** e **Remo**, gémeos descendentes de Eneias de Troia (por intermédio dos reis de Alba Longa), foram abandonados no Tibre, amamentados por uma loba e criados por um pastor. Rómulo teria fundado a cidade no Palatino a 21 de abril de 753 a.C. e matado o irmão; a data foi calculada pelo erudito **Varrão** no séc. I a.C. (outros autores propuseram anos diferentes, como 751 ou 748 a.C.). Isto é **lenda**: uma elaboração tardia, em parte inspirada em modelos gregos, que dava a Roma uma origem divina e troiana. Mas a arqueologia confirma duas coisas: havia de facto **cabanas de madeira e barro** no Palatino desde o séc. IX a.C., e a cidade só se formou como tal, com um centro cívico no Fórum, por volta de **600 a.C.**',
  { img: 'rmr-fundacao-aratro', leg: 'Ilustração gerada por IA. Fundação lendária de Roma: Rómulo traça o sulco sagrado, 753 a.C. segundo a tradição.' },
  { img: 'rmr-loba-capitolina', leg: 'Loba Capitolina, Museus Capitolinos.' },
  { h: 'O que nos diz a arqueologia' },
  { lista: [
    '**Séculos X–VIII a.C.:** necrópole no futuro Fórum e cabanas no Palatino e no Capitólio, com urnas funerárias em forma de cabana; é a cultura do Ferro do Lácio, de agricultores e pastores.',
    '**Século VII a.C.:** as aldeias das colinas aproximam-se; aparecem os primeiros edifícios de pedra e a escrita (adaptada de alfabetos etrusco e grego).',
    '**c. 600–575 a.C.:** drena-se e pavimenta-se o vale do Fórum; começa o que será a *Regia* (a «casa do rei»); é a data em que a arqueologia põe o nascimento da cidade, em acordo com a tradição sobre os reis Tarquínios.',
    '**Século VI a.C.:** monumentalização, templos com telhados de terracota; o grande templo de Júpiter no Capitólio é, pela tradição, dedicado em 509 a.C.',
    '**Debate:** desde os anos 1980, e sobretudo depois de 2005, o arqueólogo Andrea Carandini defende ter achado, no sopé do Palatino, uma muralha e um santuário do séc. VIII a.C. ligados a Rómulo; a maioria dos colegas rejeita essa identificação.'
  ] },
  { img: 'rmr-urna-cabana', leg: 'Urna cinerária em forma de cabana, Idade do Ferro do Lácio.' },
  { h: 'Roma hoje: o que resta desta época' },
  'Do período que esta página cobre, restam sobretudo alicerces e pedras soltas, e uns poucos documentos escritos. Pode ver-se o **Fórum Romano** (embora quase tudo o que está à vista seja posterior), o **Lapis Niger**, troços da **muralha serviana** (junto da estação Termini, no Aventino), a saída da **Cloaca Maxima**, a **Via Ápia Antiga**, o **Largo di Torre Argentina** (templos dos séculos IV–III a.C.), e as coleções etruscas do **Museu Nacional Etrusco da Villa Giulia**. As «Antiguidades» vivas desta época estão mais nos nomes, nos conceitos e nas instituições do que nos monumentos.',
  { h: 'Como ler esta página' },
  'Cada secção segue a mesma lógica das outras páginas de Roma: **Linha do tempo** (as datas-chave), **Mapa** (cidades, sítios e vias), **Sociedade** (política, religião, economia, guerra e vida quotidiana), **Personalidades**, **Legado** e um **Quiz** de 15 perguntas. Para o que vem a seguir (Guerras Púnicas, conquista do Mediterrâneo, Gracos, César), siga para a página **A República Tardia**; para o conjunto, volte à **página-mãe de Roma**.'
];

const linha = [
  'As datas anteriores a c. 300 a.C. são, na sua maioria, **tradicionais** (as «varronianas»): foram fixadas séculos depois e podem estar erradas por alguns anos, até mais de uma década nos séculos V–IV. Quando não há documentos contemporâneos, diz-se «segundo a tradição». A partir das guerras samnitas, a fiabilidade melhora, embora a narrativa de Lívio ainda contenha embelezamentos.',
  { linha: [
    { d: 'c. 1000 – 800 a.C.', t: 'Aldeias do Lácio', x: 'Pequenas comunidades de agricultores e pastores ocupam o Palatino, o Capitólio e outras colinas, e enterram os mortos no vale do futuro Fórum. Fazem urnas em forma de cabana. Esta é a base arqueológica de Roma: sem rei, sem muralhas, sem cidade.' },
    { d: '753 a.C. (tradição)', t: 'A fundação de Roma', x: 'Segundo a tradição, **Rómulo** funda a cidade a 21 de abril e torna-se o primeiro rei. A data é de Varrão (séc. I a.C.) e é **lendária**: a arqueologia mostra um processo gradual, não um dia de fundação. Segue-se o **rapto das Sabinas**, também lendário, que explicaria a união de Latinos e Sabinos.' },
    { d: '715 – 641 a.C. (tradição)', t: 'Numa Pompílio e Tulo Hostílio', x: 'O segundo rei, **Numa**, seria o pacífico organizador da religião: sacerdotes, Vestais, calendário. O terceiro, **Tulo Hostílio**, guerreiro, teria destruído **Alba Longa** depois do duelo entre os Horácios e os Curiácios. Ambos são figuras mais lendárias do que históricas.' },
    { d: 'séc. VII a.C.', t: 'A cidade toma forma', x: 'A arqueologia mostra que, a partir de c. 650 a.C., as aldeias das colinas se fundem e o Fórum deixa de ser cemitério. Chegam objetos gregos e etruscos. A tradição atribui a Anco Márcio (c. 640–616 a.C.) a ponte sobre o Tibre e a fundação de Óstia; a arqueologia de Óstia só mostra, porém, um *castrum* do séc. IV a.C.' },
    { d: 'c. 616 – 579 a.C. (tradição)', t: 'Tarquínio Prisco, o primeiro rei etrusco', x: 'A tradição conta que veio de Tarquínia, filho de um mercador coríntio, e que construiu o **Circo Máximo**, iniciou a **Cloaca Maxima**, drenou o Fórum e prometeu o templo de Júpiter no Capitólio. A arqueologia confirma a drenagem e pavimentação do Fórum c. 600 a.C.' },
    { d: 'c. 570 – 550 a.C.', t: 'O Lapis Niger', x: 'Descoberto em 1899 por Giacomo Boni no Comício, é uma inscrição em latim arcaico, escrita em boustrofédon e muito fragmentada, que menciona um *rex* («rei»). É um dos mais antigos textos em latim (com o vaso de Duenos e a fíbula de Preneste), e dos poucos **documentos contemporâneos** da Monarquia, embora o sentido seja obscuro.' },
    { d: '578 – 535 a.C. (tradição)', t: 'Sérvio Túlio e a reforma das classes', x: 'Segundo a tradição, o sexto rei reorganizou os cidadãos em **cinco classes** segundo a riqueza, base das «centúrias» (unidades militares e de voto), e dividiu a cidade em tribos. Recebe também a atribuição da primeira muralha («muralha serviana», que na verdade é de 378 a.C.).' },
    { d: '535 – 509 a.C. (tradição)', t: 'Tarquínio o Soberbo e o templo capitolino', x: 'O último rei teria governado como tirano. É-lhe atribuída a conclusão do **templo de Júpiter Ótimo Máximo** no Capitólio, o maior templo etrusco-itálico conhecido. A dedicação seria em 509 a.C., o primeiro ano da República, segundo Lívio e Políbio.' },
    { d: '509 a.C. (tradição)', t: 'Fim da Monarquia, início da República', x: 'Depois da violação de **Lucrécia** por Sexto Tarquínio (lenda), **Lúcio Júnio Bruto** e Lúcio Tarquínio Colatino expulsam o rei e tornam-se os primeiros cônsules. Os historiadores modernos pensam que a transição foi mais gradual e que a data de 509 a.C. é convencional; um tratado com Cartago, que Políbio data deste ano, é, porém, argumento a favor da existência real de uma República por esses anos.' },
    { d: 'c. 508 a.C. (tradição)', t: 'Lars Porsena de Clúsio', x: 'Segundo Lívio, o rei etrusco tentou repor os Tarquínios; a defesa da ponte por **Horácio Cocles** e os episódios de **Múcio Cévola** e de **Clélia** são lendas famosas. Tácito e Plínio, porém, dão a entender que Porsena chegou a ocupar Roma, o que a tradição romana quis esquecer.' },
    { d: '496 – 493 a.C.', t: 'Lago Régilo e a liga com os Latinos', x: 'A batalha do **Lago Régilo** (496 a.C., tradição) teria sido ganha com a ajuda divina de Castor e Pólux. Em 493 a.C., o *foedus Cassianum* fez de Roma e dos Latinos aliados contra Équos e Volscos; o tratado é considerado, em geral, histórico.' },
    { d: '494 a.C.', t: 'Primeira secessão da plebe', x: 'Segundo a tradição, a plebe abandonou a cidade em protesto contra as dívidas e o serviço militar, retirando-se para o Monte Sagrado (ou o Aventino). Para voltar, obteve os **tribunos da plebe**, magistrados sacrossantos com direito de proteger os cidadãos contra os magistrados. Começa o **Conflito das Ordens**.' },
    { d: '451 – 450 a.C.', t: 'Os decênviros e as XII Tábuas', x: 'Dois colégios de dez magistrados (decênviros) redigem a primeira lei escrita de Roma, gravada, segundo a tradição, em doze tábuas de bronze (ou madeira) e exposta no Fórum. A promulgação final é por vezes datada de 449 a.C. O texto original perdeu-se e só se conhece por citações posteriores.' },
    { d: '396 a.C. (tradição)', t: 'Queda de Veios', x: 'Roma conquista, depois de um cerco de dez anos (número que lembra o cerco de Troia), a cidade etrusca rival, a 16 km, sob o comando do ditador **Marco Fúrio Camilo**. Roma aumenta muito o seu território e passa a dominar a margem direita do Tibre.' },
    { d: '390 a.C. (tradição)', t: 'O saque de Roma pelos Gauleses', x: 'Um bando de **Gauleses Senones**, chefiados por Breno, derrota os Romanos na batalha do **Ália** e saqueia a cidade; só o Capitólio resiste. Segundo a lenda, os gansos sagrados avisam os defensores. A data pode ser 387 ou 386 a.C. (Políbio). Em 378 a.C. constrói-se a **muralha serviana**, de 11 km.' },
    { d: '367 – 366 a.C.', t: 'Leis Licínio-Sêxtias', x: 'Segundo a tradição, estas leis abrem o **consulado** à plebe, limitam a posse de terras públicas e aliviam dívidas. **Lúcio Sêxtio Lateranense** foi o primeiro cônsul plebeu (366 a.C.). Criam-se também a pretoria e a edilidade curul. A sua redação exata é debatida.' },
    { d: '340 – 338 a.C.', t: 'A Guerra Latina e o fim da Liga', x: 'Os Latinos, saturados da hegemonia romana, rebelam-se e são derrotados. Roma dissolve a Liga Latina e integra as cidades, de formas diferentes, sob a sua autoridade. Em Âncio, os esporões (*rostra*) dos navios capturados enfeitam a tribuna do Fórum, que passa a chamar-se *Rostra*.' },
    { d: '326 – 304 a.C.', t: 'A Segunda Guerra Samnita', x: 'Roma e os montanheses do Sâmnio combatem pelo controlo da Campânia. Em **321 a.C.**, nas **Forcas Caudinas**, um exército romano é cercado e obrigado a passar «sob o jugo»; segundo Lívio, o Senado repudia o acordo (o relato é contraditório) e a guerra continua. Constrói colónias fortificadas (Lucera, 314 a.C.) e estradas.' },
    { d: '312 a.C.', t: 'Ápio Cláudio Cego: a Via Ápia e o primeiro aqueduto', x: 'Como censor, **Ápio Cláudio Cego** começa a **Via Ápia**, de Roma a Cápua (c. 200 km), e a **Aqua Appia**, o primeiro aqueduto de Roma (c. 16,5 km, quase todo subterrâneo). São as primeiras grandes obras públicas romanas atestadas com datas razoavelmente seguras.' },
    { d: '295 a.C.', t: 'A batalha de Sentino', x: 'Na Úmbria, os cônsules **Quinto Fábio Ruliano** e **Públio Décio Mus** derrotam uma coligação de Samnitas, Etruscos, Úmbrios e Gauleses. Décio morre numa *devotio*, o sacrifício ritual de um general (tradição). Acaba a resistência da Itália central.' },
    { d: '290 – 287 a.C.', t: 'Fim da Terceira Guerra Samnita e Lei Hortênsia', x: 'Mânio Cúrio Dentato submete o Sâmnio (290 a.C.). Em 287 a.C., a **Lei Hortênsia** (tradição) dá aos *plebiscita*, decisões da assembleia da plebe, força de lei para todos os cidadãos: considera-se o fim do Conflito das Ordens.' },
    { d: '280 – 275 a.C.', t: 'A guerra de Pirro', x: 'Tarento chama **Pirro**, rei do Épiro, contra Roma. Pirro vence em **Heraclea** (280) e **Ásculo** (279), com elefantes, mas com perdas pesadas («vitória de Pirro»), e é travado em **Benevento** (275 a.C.) por Mânio Cúrio Dentato. Parte para a Sicília e depois regressa à Grécia.' },
    { d: '272 a.C.', t: 'Queda de Tarento', x: 'Com a rendição de Tarento, a cidade grega mais poderosa do sul, Roma domina praticamente toda a península a sul do rio Arno, em acordo com cada povo (nem todos de forma igual). Pouco depois, a moeda de prata romana-campaniana mostra que Roma se vê já como potência regional.' },
    { d: '264 a.C.', t: 'Os primeiros gladiadores e a Primeira Guerra Púnica', x: 'Segundo Lívio e Valério Máximo, realizou-se em 264 a.C., no Foro Boário, o primeiro combate de gladiadores em Roma, nos funerais de Décimo Júnio Bruto Pera. No mesmo ano, o apelo dos Mamertinos de Messina leva Roma à **Primeira Guerra Púnica** (264–241 a.C.), contra Cartago: fecha-se esta página, abre-se **A República Tardia**.' }
  ] },
  { img: 'rmr-palatino-aldeia', leg: 'Ilustração gerada por IA. Aldeia do Palatino, c. 800 a.C.' },
  { img: 'rmr-lapis-niger', leg: 'Lapis Niger no Comício, Fórum Romano.' },
  { img: 'rmr-doze-tabuas', leg: 'As Leis das XII Tábuas elaboradas por uma comissão: gravura de Claude-Nicolas Malapeau segundo Silvestre David Mirys, c. 1799.' },
  { img: 'rmr-saque-gaules', leg: 'Ilustração gerada por IA. Saque gaulês de Roma, 390 a.C. segundo a cronologia tradicional.' },
  { img: 'rmr-forcas-caudinas', leg: 'Ilustração gerada por IA. Forcas Caudinas, 321 a.C.: passagem dos romanos sob o jugo, segundo a tradição.' }
];

const mapa = [
  'O espaço desta página é, primeiro, **uma cidade** (Roma e as suas sete colinas), depois o **Lácio** e as cidades etruscas vizinhas, e por fim, a pouco e pouco, **toda a Itália**. A tabela dá as principais cidades e lugares; seguem-se os mais importantes, em detalhe, e as vias que ligaram a península.',
  { tabela: { cab: ['Lugar', 'O que foi', 'Época', 'Local hoje'], linhas: [
    ['Roma', 'Cidade das sete colinas; capital', '753 a.C. (tradição) em diante', 'Roma, Itália'],
    ['Alba Longa', 'Cidade-mãe lendária de Roma, capital da Liga Latina', 'Séc. IX–VII a.C. (tradição: destruída por Tulo Hostílio)', 'Colinas Albanas (localização incerta), Castel Gandolfo'],
    ['Lavínio', 'Cidade latina do santuário de Eneias (tradição); centro religioso da Liga Latina', 'Séc. VIII a.C. em diante', 'Pratica di Mare, Pomezia'],
    ['Véios', 'Cidade etrusca rival, a 16 km; conquistada em 396 a.C.', 'Séc. VIII – 396 a.C.', 'Isola Farnese, norte de Roma'],
    ['Cére (Caere)', 'Cidade etrusca rica, aliada de Roma; necrópole da Banditaccia', 'Séc. VII–IV a.C.', 'Cerveteri'],
    ['Tarquínia', 'Cidade etrusca de onde viria a família dos Tarquínios', 'Séc. VIII–IV a.C.', 'Tarquinia'],
    ['Clúsio', 'Cidade do rei Porsena', 'Séc. VI–V a.C.', 'Chiusi'],
    ['Preneste', 'Cidade latina com grande santuário da Fortuna', 'Séc. VII a.C. em diante', 'Palestrina'],
    ['Tíbur', 'Cidade latina, no vale do Aniene', 'Séc. VI a.C. em diante', 'Tivoli'],
    ['Túsculo', 'Cidade latina nos Montes Albanos', 'Séc. VI a.C. em diante', 'Frascati, arredores'],
    ['Âncio (Antium)', 'Cidade volsca, conquistada em 338 a.C. (esporões nos *Rostra*)', 'Séc. VI–IV a.C.', 'Anzio'],
    ['Sátrico', 'Cidade latina; inscrição com «Públio Valério»', 'Séc. VII–IV a.C.', 'Borgo Montello, Latina'],
    ['Óstia', 'Porto na foz do Tibre; *castrum* do séc. IV a.C.', 'Séc. IV a.C. em diante', 'Ostia Antica'],
    ['Cápua', 'Grande cidade da Campânia, aliada de Roma; ligada pela Via Ápia (312 a.C.)', 'Séc. VI a.C. em diante', 'Santa Maria Capua Vetere'],
    ['Cumas', 'Colónia grega, fonte do alfabeto e dos Livros Sibilinos (tradição)', 'Séc. VIII a.C. em diante', 'Cuma, Pozzuoli'],
    ['Cáudio (Forcas Caudinas)', 'Desfiladeiro do Sâmnio onde Roma foi humilhada em 321 a.C.', '321 a.C.', 'Vale de Arpaia, Benevento (localização debatida)'],
    ['Sentino', 'Batalha de 295 a.C. contra a coligação', '295 a.C.', 'Sassoferrato, Marcas'],
    ['Tarento', 'Colónia espartana, a maior cidade grega do sul de Itália', 'Séc. VIII a.C. – 272 a.C.', 'Taranto'],
    ['Heraclea', 'Cidade grega, batalha de 280 a.C.', '280 a.C.', 'Policoro, Basilicata'],
    ['Ásculo (Ausculum)', 'Batalha de 279 a.C. (a «vitória de Pirro»)', '279 a.C.', 'Ascoli Satriano, Apúlia'],
    ['Benevento (Maleventum)', 'Batalha de 275 a.C.; mais tarde colónia latina', '275 a.C.', 'Benevento'],
    ['Aríminum', 'Colónia latina no Adriático, bastião face aos Gauleses', '268 a.C.', 'Rimini']
  ] } },
  { img: 'rmr-roma-etrusca-reconstrucao', leg: 'Ilustração gerada por IA. Roma, c. 510 a.C.: reconstituição conjetural.' },
  { h: 'Roma e as sete colinas' },
  'O **Palatino**, onde a tradição põe a cabana de Rómulo, era a colina mais prestigiada e, mais tarde, a das residências dos poderosos. O **Capitólio**, com a cidadela (*arx*) e o templo de Júpiter, foi o centro religioso e o último refúgio. Entre o Palatino e o Capitólio estendia-se o **Fórum**, um vale pantanoso que se tornou praça pública, e a norte, a planície do **Campo de Marte**, usada para treinar tropas, e onde se reuniam as assembleias de voto. O **Foro Boário**, junto ao rio, era o mercado de gado e o porto.',
  { img: 'rmr-cloaca-maxima', leg: 'Saída da Cloaca Maxima no Tibre.' },
  { h: 'A muralha de Roma' },
  'A chamada **muralha serviana**, que a tradição atribuía a Sérvio Túlio (séc. VI a.C.), foi na verdade construída depois do saque gaulês, a partir de **378 a.C.** (segundo Lívio), em grande parte com tufo de Grotta Oscura, de pedreiras do território de **Véios** (a cidade conquistada em 396 a.C.). Tinha cerca de **11 km** de extensão e fechava uma área de várias centenas de hectares, as sete colinas, dentro da qual Roma viveu até ao Império. Existem troços visíveis junto à estação Termini e no Aventino.',
  { img: 'rmr-muralha-serviana', leg: 'Muralha serviana junto à estação Termini.' },
  { h: 'O Lácio e as cidades latinas' },
  'O **Lácio** (*Latium*) era a planície entre o Tibre e os Montes Albanos, com dezenas de cidades pequenas que falavam latim e partilhavam santuários, como o de Júpiter Latiar no Monte Albano e o de Diana em Arícia. No séc. V a.C., Roma era uma entre elas; tornou-se a maior depois de 338 a.C., quando a **Liga Latina** foi dissolvida. Algumas cidades foram anexadas, outras tornaram-se municípios, outras mantiveram aliança.',
  { h: 'Etrúria: Véios, Cére, Tarquínia' },
  'Os **Etruscos** formavam uma rede de cidades-Estado independentes, ricas pelo comércio de metais e pelo mar, entre o Arno e o Tibre. Deixaram túmulos, cerâmica, ourivesaria e templos de grande beleza. Roma aprendeu com eles a construir templos, a usar os fasces, a toga e o triunfo, entre muitas outras coisas, e, na tradição, teve reis etruscos. **Véios**, a cidade mais próxima, foi a rival: a sua queda em 396 a.C. foi o primeiro grande salto territorial de Roma.',
  { img: 'rmr-sarcofago-esposos', leg: 'Sarcófago dos Esposos, de Cerveteri, Villa Giulia.' },
  { img: 'rmr-apolo-veios', leg: 'Pormenor do Apolo de Véios, do santuário de Portonaccio; Museu Nacional Etrusco de Villa Giulia, Roma.' },
  { h: 'A Campânia e a Magna Grécia' },
  'Para sul, a costa estava cheia de cidades gregas, como **Cumas**, **Nápoles** e **Tarento**, ricas, cultas e com exércitos de mercenários. Foi dos Gregos que Roma recebeu o alfabeto (por via etrusca ou direta), deuses como Apolo e Hércules, e mais tarde muitas ideias de escultura e de teatro. **Cápua** era a grande cidade da Campânia, e foi a primeira a receber a Via Ápia.',
  { h: 'O Sâmnio e os povos do Apenino' },
  'No interior montanhoso, os **Samnitas** viviam em aldeias e em federações, e falavam osco. Não tinham grandes cidades, mas eram ótimos guerreiros, e foi a sua resistência, em três guerras ao longo de cinquenta anos (343–290 a.C., segundo a cronologia tradicional), que obrigou Roma a mudar de tática e a construir estradas e colónias nas montanhas. Outros povos itálicos, como **Úmbrios**, **Picenos**, **Sabinos** e **Marsos**, acabaram integrados em Roma por conquista ou aliança.',
  { img: 'rmr-guerreiro-capestrano', leg: 'Guerreiro de Capestrano, século VI a.C., Chieti.' },
  { h: 'A Via Ápia e as vias romanas' },
  'A **Via Ápia** (*Via Appia*), que Ápio Cláudio Cego iniciou em 312 a.C., foi a primeira grande estrada pública pavimentada de Roma, a «rainha das estradas»: ligou inicialmente Roma a Cápua (c. 200 km), e foi prolongada a Benevento e a Brindes. Seguiam-se a *Via Latina*, mais antiga, e a *Via Salaria*, a rota do sal. Estas vias serviram, sobretudo, para mover legiões depressa para as colónias.',
  { img: 'rmr-via-appia', leg: 'Via Ápia Antiga, pavimento original.' },
  { h: 'As colónias romanas e latinas' },
  'Roma fundou **colónias** em pontos estratégicos, por exemplo Óstia, Âncio, Tarracina, Lucera, Pesto, Cosa e Aríminum. Havia dois tipos: **colónias romanas** (pequenas, de cidadãos, na costa, quase postos de guarda) e **colónias latinas** (maiores, com estatuto de aliados, em territórios conquistados, para onde iam camponeses e soldados). Entre 338 e 264 a.C., deslocaram-se talvez dezenas de milhares de colonos: um grande instrumento de romanização e de controlo.',
  { h: 'A península em 264 a.C.' },
  'Por volta de 264 a.C., Roma controlava, direta ou indiretamente, toda a península a sul do Arno e do Rubicão. Mas não era um império: era uma **rede** com um centro (o território romano, de cidadãos), em torno do qual se agrupavam cidades de cidadãos sem voto, colónias latinas e dezenas de **aliados** (*socii*), cada um ligado a Roma por um tratado distinto, obrigados a fornecer tropas em guerra, mas sem pagar impostos regulares. O exército de Roma, com os aliados, podia pôr em campo mais de 700 000 homens, segundo Políbio (cerca de 225 a.C.), número que se deve ler com cautela.'
];

const sociedade = [
  { h: 'A Monarquia: o rei e o seu poder' },
  'Segundo a tradição, os reis de Roma eram **eleitos**, não hereditários: o *interrex* propunha um nome, o Senado e o povo (as *cúrias*) aprovavam e o *imperium*, o poder supremo de comando, era conferido por uma lei curiata. O rei era chefe militar, juiz, sumo sacerdote e legislador. Usava os símbolos que a tradição diz herdados dos Etruscos: a **cadeira curul**, a toga de bordado púrpura e os **fasces**, os feixes de varas com um machado, carregados por doze **litores**. Estes símbolos passaram aos magistrados republicanos.',
  { img: 'rmr-fasces', leg: 'Estatueta de bronze de um lictor com fasces; Art Institute of Chicago (1980.809).' },
  { h: 'O Senado e as cúrias' },
  'O **Senado** (de *senex*, «velho») era, na origem, o conselho dos chefes das famílias (*patres*): cem membros, segundo a tradição, a que se foram juntando outros, até 300 no final da República Antiga. Aconselhava o rei, e depois os magistrados; as suas decisões, os *senatus consulta*, eram conselhos, mas tinham grande peso. O povo estava dividido em trinta **cúrias**, que votavam na *comitia curiata*, de papel cada vez mais limitado e quase só ritual.',
  { h: 'A reforma de Sérvio Túlio: classes e centúrias' },
  'A tradição atribui a **Sérvio Túlio** a reforma do **censo**: os cidadãos eram recenseados e classificados em cinco **classes** segundo a riqueza (em terras e gado), cada uma obrigada a fornecer um certo equipamento militar, da cavalaria (os *equites*) aos soldados de infantaria ligeira. Cada classe estava dividida em **centúrias**, que eram simultaneamente unidades do exército e unidades de voto. A *comitia centuriata*, a assembleia do povo em armas, que decidia sobre a guerra, as leis e a eleição dos magistrados superiores, deu aos mais ricos a maioria dos votos. A reforma, na forma que se conhece, é provavelmente posterior ao séc. VI a.C., mas o princípio da participação política segundo o património marcou a República.',
  { img: 'rmr-comicios-centuriados', leg: 'Ilustração gerada por IA. Comícios centuriados no Campo de Marte, século IV a.C.; cena interpretativa.' },
  { h: 'A República: os cônsules e os magistrados' },
  'Depois de 509 a.C., o poder do rei foi dividido: dois **cônsules**, eleitos por um ano, com poder igual (colegialidade), cada um podendo vetar o outro. Em caso de guerra grave, o Senado podia nomear um **ditador** por seis meses, com poder absoluto (como **Cincinato**, em 458 a.C., segundo a tradição). Aos poucos acrescentaram-se outros cargos: **questores** (finanças), **edis** (obras e jogos), **pretores** (justiça, desde 367 a.C.) e **censores** (recenseamento e costumes, desde 443 a.C., segundo a tradição). Os magistrados eram escolhidos entre os cidadãos mais ricos, pelo que a *cursus honorum*, a carreira de cargos, era quase uma exclusividade das elites.',
  { tabela: { cab: ['Magistratura', 'Quantos e quanto tempo', 'Funções principais'], linhas: [
    ['Cônsul', '2, por 1 ano', 'Comando do exército, presidência do Senado e das assembleias, justiça'],
    ['Pretor', '1 a partir de 367 a.C. (depois mais)', 'Administração da justiça; substituía os cônsules'],
    ['Censor', '2, por 18 meses, de 5 em 5 anos', 'Recenseamento, lista do Senado, supervisão da moral pública'],
    ['Edil', '2 plebeus e 2 curuis', 'Mercados, templos, ruas, jogos públicos'],
    ['Questor', 'Vários (4 desde 421 a.C.; 8 desde 267 a.C.)', 'Tesouro, finanças, apoio aos cônsules'],
    ['Tribuno da plebe', '2 a 10, por 1 ano', 'Proteger os plebeus, direito de veto, sacrossantos'],
    ['Ditador', '1, no máximo 6 meses', 'Autoridade total em emergências, sem direito de recurso']
  ] } },
  { h: 'Patrícios e plebeus: o Conflito das Ordens' },
  'A sociedade romana dividia-se em duas «ordens»: os **patrícios**, uma aristocracia de famílias antigas (as *gentes*), que detinham os sacerdócios e todos os cargos, e os **plebeus**, o resto dos cidadãos, que incluía desde camponeses pobres até famílias ricas, mas que ficavam excluídos do poder. A origem exata da divisão é debatida (talvez uma questão de riqueza e de religião, não de «raça»). Durante mais de duzentos anos (494–287 a.C.) a plebe lutou, por vezes com **secessões** (a greve dos soldados e artesãos, que abandonavam a cidade), pelo reconhecimento dos seus direitos: tribunos, lei escrita, casamento misto, acesso ao consulado e aos sacerdócios. A luta foi quase sempre pacífica, o que é invulgar na Antiguidade.',
  { img: 'rmr-secessao-plebe', leg: 'Ilustração gerada por IA. Primeira secessão da plebe, 494 a.C., segundo a tradição.' },
  { lista: [
    '**494 a.C.:** primeiros tribunos da plebe (tradição) e edis plebeus.',
    '**451–450 a.C.:** leis das XII Tábuas, que publicam o direito e limitam o arbítrio dos magistrados.',
    '**445 a.C.:** *Lex Canuleia*, que permite o casamento entre patrícios e plebeus (tradição).',
    '**367–366 a.C.:** Leis Licínio-Sêxtias; o consulado abre-se a um plebeu.',
    '**356 a.C.:** primeiro ditador plebeu (Caio Márcio Rutilo); **351** primeiro censor plebeu.',
    '**339 a.C.:** Leis Publílias, do ditador Quinto Publílio Filão (tradição, segundo Lívio: um dos censores passa a ser plebeu e as decisões da plebe ganham alcance mais largo).',
    '**337 a.C.:** primeiro pretor plebeu (Quinto Publílio Filão).',
    '**326 a.C. (ou 313):** *Lex Poetelia Papiria*, que acaba com a escravidão por dívidas (*nexum*) para cidadãos.',
    '**300 a.C.:** *Lex Ogulnia*: plebeus admitidos aos colégios dos pontífices e dos áugures.',
    '**287 a.C.:** *Lex Hortensia*: as decisões da assembleia da plebe valem para todos. Fim do Conflito das Ordens.'
  ], ord: true },
  { h: 'O resultado: uma nova elite' },
  'O fim do conflito não criou uma democracia. Em vez de patrícios contra plebeus, formou-se uma **nobreza** (*nobilitas*) de famílias, patrícias e plebeias, que tinham tido cônsules; essas famílias dominavam o Senado e as eleições, e controlavam o acesso ao poder. Para os pobres, restavam as assembleias e o direito de veto dos tribunos, e a promessa de terras nas colónias. Foi um equilíbrio que durou cerca de 150 anos, até à crise dos Gracos.',
  { h: 'A família romana e o *pater familias*' },
  'A unidade básica da sociedade era a **família** (*familia*), que incluía a mulher, os filhos, os escravos e os bens, sob a autoridade absoluta do **pater familias**, o chefe masculino mais velho. Na lei antiga (as XII Tábuas), o pai tinha poder de vida e de morte (*patria potestas*) sobre os filhos, embora na prática o exercesse raramente. As mulheres romanas, sempre sujeitas a um tutor, não podiam votar nem ocupar cargos, mas, ao contrário das gregas, circulavam em público, geriam a casa e podiam herdar bens. Muitas famílias pertenciam a uma **gens**, um clã que partilhava o nome (*nomen*), os cultos e muitas vezes um túmulo.',
  { h: 'Clientes e patronos' },
  'Uma peça essencial da vida política era o laço entre o **patrono** (*patronus*), um homem poderoso, e os seus **clientes** (*clientes*), pessoas de condição mais humilde que lhe deviam apoio político e serviços e recebiam em troca proteção, ajuda legal, comida ou dinheiro. Era uma relação moral, regulada pela *fides* (a boa-fé). Os grandes homens tinham dezenas de clientes que os acompanhavam e votavam por eles; foi uma base do poder da nobreza.',
  { h: 'Escravidão e dívidas' },
  'Havia escravos em Roma desde cedo, sobretudo prisioneiros de guerra e pessoas nascidas na casa, mas o seu número era pequeno nesta época e muitos trabalhavam ao lado do dono, no campo. A **escravidão por dívidas** (*nexum*), em que o devedor trabalhava para o credor, era uma das maiores causas da revolta da plebe. Só nas guerras do séc. III a.C. e seguintes a escravatura se tornaria massiva. O escravo podia ser libertado (*manumissio*), e o liberto (*libertus*) tornava-se cidadão, com limitações.',
  { h: 'Religião romana: deuses e ritos' },
  'A religião romana não era uma crença pessoal, mas um **contrato** (*do ut des*, «dou para que dês») entre a comunidade e os deuses, mantido por ritos exatos. Os primeiros deuses eram forças da natureza e do lar, mais do que pessoas: **Júpiter** (céu e juramentos), **Marte** (guerra e agricultura), **Quirino**, **Jano** (portas e começos), **Vesta** (lareira), **Saturno** (sementeira), **Ceres** (cereais) e os **Lares** e **Penates** (casa). Com os Etruscos e Gregos chegaram **Juno**, **Minerva** (com Júpiter formam a **Tríade Capitolina**), **Apolo** (templo votado em 433 e dedicado em 431 a.C., durante uma epidemia; deus de origem grega), **Castor e Pólux** (templo em 484 a.C.) e **Esculápio** (trazido de Epidauro em 291 a.C., outra epidemia).',
  { tabela: { cab: ['Deus', 'Domínio', 'Notas'], linhas: [
    ['Júpiter Ótimo Máximo', 'Céu, trovão, juramentos', 'Templo no Capitólio, dedicado em 509 a.C. (tradição); chefe da Tríade'],
    ['Juno', 'Casamento, mulheres', 'Rainha dos deuses; no Capitólio, com Júpiter e Minerva'],
    ['Minerva', 'Artesãos, sabedoria', 'Equivale à grega Atena; no Capitólio'],
    ['Marte', 'Guerra; campos', 'Pai de Rómulo na lenda; o Campo de Marte; mês de março'],
    ['Quirino', 'Comunidade romana', 'Identificado com o Rómulo divinizado (tradição)'],
    ['Jano', 'Portas, passagens, começos', 'Duas faces; o seu templo ficava aberto em tempo de guerra'],
    ['Vesta', 'Lareira da cidade', 'Fogo sagrado mantido pelas seis Vestais'],
    ['Saturno', 'Sementeira, agricultura', 'Templo no Fórum (tradição, 497 a.C.); festa dos Saturnais'],
    ['Ceres, Líber e Libera', 'Cereais, plebe', 'Templo no Aventino, 493 a.C.; ligado à plebe'],
    ['Apolo', 'Cura, profecia', 'Templo de 431 a.C.; deus de origem grega, cultuado cedo em Roma'],
    ['Esculápio', 'Medicina', 'Chegado de Epidauro em 291 a.C.; santuário na Ilha Tiberina']
  ] } },
  { img: 'rmr-modelo-capitolino', leg: 'Maqueta do templo de Júpiter Capitolino.' },
  { h: 'Sacerdotes e adivinhação' },
  'Em Roma, os sacerdotes eram cidadãos e magistrados e não uma casta à parte. O **pontífice máximo** presidia ao colégio dos pontífices (calendário, rituais, direito sagrado). Os **áugures** liam o voo das aves para saber se os deuses aprovavam um ato público: nenhuma assembleia ou batalha começava sem auspícios. Os **feciais** declaravam a guerra por um ritual. As **Vestais**, seis mulheres, mantinham o fogo da cidade, e eram punidas com a morte se violassem o voto de castidade. Os **haruspices**, adivinhos etruscos que liam o fígado de animais sacrificados, eram consultados nos grandes prodígios. Os **Livros Sibilinos**, uma coleção de oráculos em grego, guardados no templo de Júpiter, eram consultados em crises.',
  { img: 'rmr-figado-piacenza', leg: 'Fígado de Placência: modelo etrusco de bronze para a adivinhação; Musei Civici, Placência.' },
  { h: 'Festas e calendário' },
  'O calendário romano, segundo a tradição criado por Rómulo com dez meses e completado por Numa com janeiro e fevereiro, era controlado pelos pontífices, que anunciavam os dias úteis e as festas. Entre as festas mais antigas contam-se as **Parilia** (21 de abril, dia de fundação), as **Lupercais** (fevereiro), os **Saturnais** (dezembro), a **Feriae Latinae** e os **Ludi Romani**, com corridas e jogos, que a tradição liga aos Tarquínios. Em 304 a.C. o edil **Cneu Flávio** publicou o calendário e as fórmulas processuais, tirando aos pontífices o monopólio da informação (tradição).',
  { h: 'Direito: as XII Tábuas' },
  'As **Leis das XII Tábuas** (451–450 a.C., tradição) foram a primeira lei escrita de Roma. Gravadas em bronze (Lívio), ou talvez em madeira, e expostas no Fórum, regulavam o processo, as dívidas, a família, a propriedade, os crimes e os enterros. O texto original perdeu-se, e conhece-se por citações em autores posteriores (como Cícero e Gaio). Previam, por exemplo, que o devedor insolvente fosse entregue ao credor, que o «ladrão apanhado de noite» pudesse ser morto, e que ninguém pudesse ser condenado à morte sem julgamento do povo. Para os Romanos, eram «a fonte de todo o direito público e privado» (Lívio). Foram aprendidas de cor por gerações de estudantes até ao séc. I a.C.',
  { h: 'Escrita e língua' },
  'Os Romanos falavam **latim**, uma língua indo-europeia do ramo itálico, parente do osco e do úmbrio. O alfabeto latino foi adaptado do **etrusco**, que por sua vez veio do grego (talvez de Cumas), por volta do séc. VII a.C. Os documentos mais antigos são a **inscrição do Lapis Niger** (c. 570–550 a.C.), o **vaso de Duenos** (séc. VI a.C.) e o **cipo de Sátrico** (c. 500 a.C.), este último com uma dedicatória de companheiros de «Públio Valério» a Marte, quase certamente o Publícola da tradição. A literatura em latim só começou em 240 a.C., com Lívio Andronico. Os historiadores romanos começaram a escrever cerca de 200 a.C. (Fábio Píctor, em grego); os *Annales Maximi* dos pontífices, registo anual de acontecimentos, são uma fonte perdida.',
  { img: 'rmr-inscricao-duenos', leg: 'Inscrição de Duenos, Antikensammlung, Berlim.' },
  { h: 'Economia: agricultura e terra' },
  'Roma era, acima de tudo, uma sociedade de **camponeses-soldados**. A riqueza media-se em terra e em gado (a palavra *pecunia*, «dinheiro», vem de *pecus*, «gado»). Cultivavam trigo vestido (*far*, espelta), cevada, favas, oliveiras, vinhas e pastavam ovelhas e porcos. A propriedade típica era pequena (poucos hectares, dois *iugera* por cidadão, segundo a tradição), e muitos camponeses endividavam-se. A conquista de terra, partilhada entre colonos e cidadãos pobres, foi a solução permanente para a fome de terra da plebe, até ao séc. II a.C.',
  { h: 'Comércio, sal e moeda' },
  'O Tibre e as vias ligavam Roma ao comércio do Mediterrâneo: os Etruscos e os Gregos traziam vinho, cerâmica, ourivesaria e metais, enquanto Roma exportava sal, gado e produtos agrícolas. O **Foro Boário** era o grande mercado. Primeiro, o valor media-se em bronze a peso (*aes rude*, pedaços de bronze), depois em barras com marca (*aes signatum*) e em grandes discos (*aes grave*). As **primeiras moedas** foram cunhadas nas colónias gregas do sul; Roma começou a emitir as suas por volta de 300–280 a.C., com didracmas de prata do tipo «romano-campaniano», e só pouco antes de 211 a.C. criou o denário.',
  { img: 'rmr-aes-signatum', leg: 'Barra de bronze romana, aes signatum.' },
  { h: 'A casa e o quotidiano' },
  'As primeiras casas eram cabanas de madeira e barro, com telhado de colmo. A partir do séc. VII–VI a.C., sob influência etrusca, passam a ser de tijolo cru, com telhas de terracota, e o modelo da casa romana, a *domus*, com o **átrio** (uma sala central aberta ao céu, com um tanque para a água da chuva, o *impluvium*) e os quartos à volta, ganha forma. Os pobres viviam em casas pequenas ou em pardieiros nos bairros baixos. Os móveis eram poucos: camas, arcas, bancos, e o altar dos **Lares**, deuses da casa, no átrio.',
  { img: 'rmr-casa-arcaica', leg: 'Ilustração gerada por IA. Casa romana com átrio, século IV a.C.; interpretação conjetural.' },
  { h: 'Alimentação' },
  'A base era a **puls**, uma papa de espelta (*far*), com legumes, queijo, azeitonas e, quando possível, carne de porco ou ovelha. O **pão** de trigo só se generalizou mais tarde (os padeiros profissionais surgem no séc. II a.C., segundo Plínio). Bebia-se vinho diluído em água, nunca puro. O sal era essencial e, segundo a tradição, a venda do sal esteve cedo sujeita a regulação pública (o monopólio estatal está documentado só em 204 a.C.). Nas casas ricas, os banquetes incluíam carne e peixe; segundo a tradição, antigamente as mulheres não bebiam vinho, e o homem tinha o direito de as beijar para verificar.',
  { h: 'Vestuário' },
  'A **toga**, uma grande peça de lã em forma de semicírculo, era o traje do cidadão romano, e provavelmente de origem etrusca. A **toga praetexta**, com uma tira púrpura, era usada pelos magistrados e pelos rapazes; os rapazes usavam ao pescoço a **bulla**, um amuleto. Por baixo vestia-se a **túnica**. As mulheres casadas usavam a **stola**, um vestido comprido, e um manto (*palla*). O calçado, os **calcei**, era de couro. Os senadores usavam uma túnica com tira larga púrpura (*latus clavus*).',
  { h: 'Funerais e antepassados' },
  'Os funerais de aristocratas eram cerimónias públicas: o corpo era levado ao Fórum, onde um parente fazia o elogio fúnebre, e seguido por atores que usavam as **máscaras de cera** (*imagines*) dos antepassados que tinham sido magistrados, segundo o relato de Políbio (séc. II a.C.). Os mortos eram cremados ou enterrados, fora das muralhas, por lei das XII Tábuas, que também limitava o luxo dos funerais. Um funeral famoso, em 264 a.C., viu os primeiros combates de gladiadores em Roma (Foro Boário).',
  { img: 'rmr-funeral-aristocratico', leg: 'Ilustração gerada por IA. Funeral aristocrático no Fórum, século III a.C.' },
  { h: 'Jogos, teatro e música' },
  'Os **Ludi Romani**, segundo a tradição criados por Tarquínio Prisco, incluíam corridas de carros no **Circo Máximo**, pugilismo e desfiles. Os espetáculos de teatro eram, antes de 240 a.C., danças e farsas de origem etrusca e osca, como as farsas atelanas e os versos fesceninos. Os combates de gladiadores, originalmente rituais fúnebres (264 a.C.), só se tornariam espetáculo de massas mais tarde. Os instrumentos eram a **tibia** (flauta dupla), o **cornu** (corneta), a **tuba** e o **lituus**; os sacerdotes **Sálios** cantavam e dançavam em março, em honra de Marte. Entre os jogos de tabuleiro mais populares estavam o *latrunculi* (uma espécie de jogo de guerra) e os dados.',
  { h: 'Ciência, calendário e medicina' },
  'Os Romanos desta época eram engenheiros práticos, mais do que teóricos. A **medicina** assentava em ervas, rezas e deuses curadores (Esculápio, a partir de 291 a.C.); não havia ainda médicos gregos em Roma (o primeiro, Arquágato, chega em 219 a.C., segundo Plínio). O **calendário**, lunar e depois ajustado ao sol por intercalação mal controlada, era um instrumento de poder dos pontífices. A **astronomia** aplicava-se aos auspícios; a **agrimensura** (medição de terras) era essencial para as colónias.',
  { h: 'Tecnologia e obras públicas' },
  'Roma aprendeu com os Etruscos a trabalhar com **tufo** e com o **arco**, e a drenar zonas húmidas (a Cloaca Maxima, que drenava o Fórum, é a obra mais famosa). O primeiro **aqueduto**, a *Aqua Appia* (312 a.C., c. 16,5 km, quase todo subterrâneo), e a **Via Ápia** (312 a.C.) marcam o início da engenharia pública romana. O betão (*opus caementicium*) é uma invenção posterior (séc. III–II a.C.). Os grandes edifícios abobadados de betão que hoje associamos a Roma são muito posteriores.',
  { h: 'Guerra: do rei ao cidadão-soldado' },
  'Em princípio, todo o cidadão com bens servia no exército, a expensas próprias. No tempo dos reis, o exército seguia o modelo etrusco e grego do **hoplita**: infantaria pesada, em **falange** (linha compacta), com escudo redondo (*clipeus*), lança e capacete. Os mais ricos serviam na cavalaria (*equites*). Os soldados eram recrutados no início de cada ano, para campanhas sazonais (verão), e regressavam ao campo no outono. Em 406 a.C. (tradição), durante o cerco de Véios, foi criado o **soldo** (*stipendium*), que permitiu campanhas mais longas.',
  { img: 'rmr-falange-hoplita', leg: 'Ilustração gerada por IA. Hoplitas romanos em falange, século V a.C.; equipamento etrusco-grego.' },
  { h: 'A legião manipular' },
  'A falange não resultava em terreno acidentado, como o das guerras samnitas. Lívio descreve esta reforma por volta de 340 a.C. (e outros autores atribuem-na a Camilo); os historiadores veem nela uma evolução gradual do séc. IV a.C. A legião foi dividida em **manípulos** (*manipuli*, «punhados»), pequenas unidades de cerca de 120 homens (60 nos triários), dispostas em três linhas: os **hastati** (jovens, na frente), os **principes** (adultos) e os **triarii** (veteranos, na reserva). Esta formação, mais flexível, com espaços entre os manípulos, permitia manobrar em terreno difícil. Adotaram também o **scutum** (escudo oval) e o **pilum** (dardo pesado), de origem samnita, segundo alguns autores antigos.',
  { img: 'rmr-legionario-manipular', leg: 'Ilustração gerada por IA. Legionários romanos em formação manipular, início do século III a.C.' },
  { h: 'Acampamento, disciplina e inimigos' },
  'Os Romanos distinguiram-se pela **disciplina** e pela rotina de fortificar um acampamento todas as noites; Plutarco conta que o próprio Pirro, ao ver o acampamento romano, se impressionou com a sua ordem. Os seus inimigos nesta época foram: os **Etruscos** (cidades-Estado ricas, mas desunidas), **Équos e Volscos** (povos das montanhas, vizinhos incómodos), **Gauleses** (invasores celtas, temíveis em batalha aberta), **Samnitas** (guerreiros de montanha, com a tática da emboscada) e **Pirro** (mercenário helenístico, com elefantes e falange macedónica).',
  { h: 'Elefantes contra legiões' },
  'Em **Heraclea** (280 a.C.), os Romanos enfrentaram pela primeira vez **elefantes de guerra**, e os cavalos entraram em pânico. Pirro ganhou a batalha, mas com muitas baixas; em **Benevento** (275 a.C.), os Romanos conseguiram assustar os elefantes (segundo as fontes antigas, a dardo, e alguns autores falam em fogo), e Pirro perdeu. Foi o fim da sua campanha em Itália. O **prato de Capena** (Villa Giulia) mostra um elefante e o seu filhote e, segundo a opinião mais comum, evoca esta guerra.',
  { h: 'O sistema de alianças' },
  'O verdadeiro segredo da vitória romana na Itália foi político. Roma não anexou todos os derrotados: ofereceu a muitos a **cidadania** (parcial ou total), a outros uma **aliança** (*foedus*) com a obrigação de fornecer soldados, e deixou-lhes a autonomia local. Cada aliado estava ligado só a Roma, e não aos outros aliados (dividir para reinar). Em troca, partilhavam os despojos e o território conquistado. Quando Pirro ou, mais tarde, Aníbal invadiram a Itália, esperavam que os aliados se revoltassem; a maioria manteve-se fiel.'
];

const personalidades = [
  'Dos quinze nomes abaixo, os cinco primeiros (os reis) e vários dos seguintes (Bruto, Porsena, Cincinato, Camilo) estão envoltos em **lenda**: o que se conta deles foi escrito séculos depois e mistura facto, memória familiar e moral cívica. Diz-se quando é assim. Os últimos (Ápio Cláudio, Cúrio Dentato, Pirro) pertencem já à história documentada.',
  { h: 'Rómulo (lendário, 753 – 716 a.C.)' },
  'Fundador e primeiro rei de Roma, na tradição. Filho do deus Marte e de Reia Sílvia, abandonado com o irmão Remo, teria fundado a cidade no Palatino e matado o irmão numa disputa. A ele se atribuem o rapto das Sabinas, o Senado, as cúrias e o exército. Terá desaparecido numa tempestade e, depois, tornou-se o deus **Quirino**. Não há prova arqueológica de que tenha existido; é uma figura **lendária**, em que se misturam o fundador mítico e talvez um chefe real do séc. VIII a.C.',
  { h: 'Numa Pompílio (lendário, 715 – 673 a.C.)' },
  'Sabino de Cures, escolhido como segundo rei pela sua piedade. Segundo a tradição, organizou a religião romana (pontífices, Vestais, flâmines, calendário), construiu o templo de Jano e manteve a paz durante o seu reinado. Teria recebido conselhos da ninfa Egéria. É uma figura tradicional, que serve de contraponto a Rómulo, o guerreiro: **legislador** e fundador do culto. Os historiadores modernos consideram-no lendário.',
  { h: 'Tarquínio Prisco (616 – 579 a.C., tradição)' },
  'Quinto rei, de origem etrusca. Segundo a tradição, era filho de **Demarato**, mercador de Corinto emigrado em Tarquínia, e chegou a Roma com a mulher, **Tanaquil**, que lhe previu a realeza. Reinou como grande construtor: o Circo Máximo, a Cloaca Maxima, a drenagem do Fórum e os alicerces do templo de Júpiter. Foi assassinado pelos filhos de Anco Márcio. A arqueologia confirma a influência etrusca e a obra de urbanização c. 600 a.C., embora não o nome.',
  { h: 'Sérvio Túlio (578 – 535 a.C., tradição)' },
  'Sexto rei, filho de uma escrava (segundo uma versão) ou de um nobre latino (segundo outra); o imperador Cláudio, no séc. I d.C., disse que era, na verdade, o etrusco **Mastarna**, companheiro de Célio Vibena, e a *Tábua de Lyon* e as pinturas do túmulo François (Vulci) apontam nesse sentido. A tradição atribui-lhe a reforma do censo, as classes e centúrias, a divisão em tribos e a primeira muralha. Foi assassinado por **Tarquínio o Soberbo**, seu genro. É a figura que melhor mostra a fusão de histórias latinas e etruscas.',
  { h: 'Tarquínio o Soberbo (535 – 509 a.C., tradição)' },
  'Sétimo e último rei, **Lúcio Tarquínio o Soberbo** (*Superbus*), tomou o poder pela violência, governou como tirano (sem consultar o Senado), concluiu o templo capitolino, venceu os Volscos e conquistou Gábios, por um ardil do seu filho. A tradição diz que foi expulso quando o seu filho Sexto violou **Lucrécia**, que se matou. Tentou depois voltar com ajuda dos Etruscos de Veios, Tarquínia e Clúsio, mas sem sucesso, e morreu no exílio, em Cumas. A história da tirania era provavelmente reforçada pelos autores republicanos, para legitimar o novo regime.',
  { img: 'rmr-lucrecia-rembrandt', leg: 'Lucrécia, Rembrandt, 1664, National Gallery of Art, Washington.' },
  { h: 'Lúcio Júnio Bruto (lendário, 509 a.C.)' },
  'Sobrinho de Tarquínio o Soberbo, que se fingira de parvo para escapar à morte, segundo a tradição; depois da morte de Lucrécia, jurou expulsar a família real e foi, com Colatino, **primeiro cônsul**. Teria mandado executar os próprios filhos por conspirarem para repor o rei, uma imagem de severidade cívica que fez dele um herói da República. Morreu em combate contra Árrunte Tarquínio. A sua existência histórica é debatida; um dos Bruto que matou César, em 44 a.C., reclamava descender dele.',
  { img: 'rmr-bruto-capitolino', leg: 'Bruto Capitolino, bronze, Museus Capitolinos.' },
  { h: 'Lars Porsena (c. 508 a.C., tradição)' },
  'Rei etrusco de Clúsio que, segundo Lívio, atacou Roma para repor os Tarquínios mas desistiu, impressionado pela coragem romana: **Horácio Cocles** segurou sozinho a ponte Sublícia, **Múcio Cévola** queimou a mão na chama para mostrar a sua bravura e **Clélia** fugiu a nado. É a versão romana. Tácito, no séc. I d.C., escreve que Roma lhe foi «entregue», e Plínio diz que o tratado de paz proibia aos Romanos o uso do ferro, exceto para a agricultura, o que sugere uma derrota que a memória romana apagou.',
  { h: 'Lúcio Quíncio Cincinato (tradição, 458 a.C.)' },
  'Patrício e agricultor, que, segundo Lívio, foi chamado do arado para ser **ditador** quando um exército romano ficou cercado pelos Équos. Venceu em cerca de duas semanas, depositou o cargo e voltou à sua quinta. Tornou-se o modelo do cidadão que serve a República e depois regressa à vida privada. A história é provavelmente embelezada: não é claro se se trata de um facto, de um mito moral ou de uma mistura. O nome inspirou, no séc. XVIII, a Sociedade de Cincinato, e a cidade americana de Cincinnati.',
  { img: 'rmr-horacios-david', leg: 'O Juramento dos Horácios, J.-L. David, 1784, Louvre.' },
  { h: 'Marco Fúrio Camilo (m. 365 a.C., tradição)' },
  'Ditador em 396 a.C., conquistou Véios, e voltou a ser chamado depois do saque gaulês: segundo a tradição, recusou o resgate pago a Breno com a frase «Roma não se compra com ouro, mas com ferro», e libertou a cidade. Foi saudado como «segundo fundador de Roma». Os historiadores modernos acham que muito disto é uma lenda patriótica, com a vitória sobre Breno inventada para consolar os Romanos pela humilhação. Existiu, porém, e foi um dos principais comandantes do início do séc. IV a.C.',
  { h: 'Quinto Fábio Máximo Ruliano (séc. IV–III a.C.)' },
  'Grande general das guerras samnitas, cinco vezes cônsul, ditador em 315 e vencedor de Sentino (295 a.C.), com Públio Décio Mus. Foi também censor em 304 a.C. e reformou as tribos, restringindo o voto dos libertos às quatro tribos urbanas. Pertence já à **história documentada**, apesar de Lívio embelezar a sua carreira. A família dos Fábios teria, mais tarde, outro Fábio Máximo célebre, o «Cunctator», que enfrentaria Aníbal.',
  { h: 'Públio Décio Mus (o Jovem) (m. 295 a.C.)' },
  'Cônsul em Sentino, onde, segundo Lívio, repetiu o gesto do pai (que morrera em 340 a.C. na Guerra Latina): fez a *devotio*, a consagração ritual do general aos deuses infernais, para obter a vitória para o exército, e atirou-se contra os inimigos até à morte. A tradição da *devotio* é uma das mais impressionantes da religião romana; a historicidade de cada episódio é debatida.',
  { h: 'Ápio Cláudio Cego (c. 340 – c. 273 a.C.)' },
  'Censor em 312 a.C., começou a **Via Ápia** e a **Aqua Appia**, e, segundo a tradição, foi o primeiro a admitir filhos de libertos no Senado (medida anulada depois). Cônsul em 307 e 296, perdeu a vista na velhice (daí o *Caecus*, «o Cego»), mas, já cego, foi levado ao Senado em 280 a.C. para convencer os senadores a rejeitarem a paz proposta por Pirro; o discurso, segundo Cícero, ainda se conhecia no seu tempo. Pelas obras e pelo poder político, é a primeira figura romana com uma biografia sólida.',
  { h: 'Mânio Cúrio Dentato (m. 270 a.C.)' },
  'Plebeu e novo homem, três vezes cônsul, **somou vitórias** na Itália central: submeteu os Samnitas e os Sabinos (290 a.C.), derrotou os Lucanos e **venceu Pirro em Benevento** (275 a.C.). A tradição (Cícero, Plutarco) faz dele um modelo de austeridade, que recusou ouro samnita e que comia nabos junto à lareira. Foi encarregado de construir o segundo aqueduto de Roma, o *Anio Vetus* (272 a.C.), pago, segundo Frontino, com os despojos de Pirro. É um dos primeiros comandantes cuja carreira é historicamente sólida.',
  { h: 'Pirro do Épiro (319 – 272 a.C.)' },
  'Rei do Épiro, da família dos Eácidas e parente distante de Alexandre o Grande, foi um dos grandes generais helenísticos. Chamado por **Tarento** em 280 a.C., desembarcou em Itália com cerca de 25 000 homens e 20 elefantes (segundo Plutarco), venceu em Heraclea e Ásculo mas com perdas gravíssimas, passou à Sicília contra Cartago (278–276 a.C.) e voltou para ser travado em Benevento (275 a.C.). Dele, Plutarco cita uma frase: «mais uma vitória como esta e estamos perdidos» (a expressão «vitória de Pirro» vem daí). Morreu em Argos, em 272 a.C., atingido por uma telha atirada por uma mulher, segundo a tradição. A guerra mostrou aos Gregos que Roma era uma potência.',
  { img: 'rmr-pirro-busto', leg: 'Busto de Herculano tradicionalmente identificado como Pirro, Museu Arqueológico de Nápoles.' },
  { img: 'rmr-batalha-heraclea', leg: 'Ilustração gerada por IA. Batalha de Heracleia, 280 a.C.: elefantes de Pirro contra os romanos.' },
  { h: 'Caio Fabrício Luscino (cônsul 282 e 278 a.C.; censor 275 a.C.) e Cíneas (ativo c. 280 a.C.)' },
  'O embaixador de Pirro, **Cíneas** (um tessálio, discípulo de Demóstenes), foi a Roma propor a paz com presentes, mas não convenceu o Senado. Fabrício, o negociador romano, teria recusado o ouro e o suborno e mantido a firmeza; um dos episódios mais contados é o de Pirro, tentando assustá-lo com um elefante escondido por trás de uma cortina, que Fabrício ignorou. É uma **anedota moral** da tradição, de que não existe prova; mas a embaixada de Cíneas é histórica.'
];

const legado = [
  { h: 'A ideia de república' },
  'A palavra «república» vem do latim *res publica*, «coisa pública». A construção romana, com magistrados eleitos por um ano, que se vigiavam uns aos outros, com um Senado de ex-magistrados e com assembleias do povo, serviu de modelo a pensadores como Políbio, que a descreveu como «constituição mista», a Cícero, a Maquiavel, a Montesquieu e aos fundadores dos Estados Unidos, que chamaram «Senado» à câmara alta. O ideal de **virtude cívica** (*virtus*, *fides*, *gravitas*) vive nas figuras de Cincinato e dos Horácios.',
  { h: 'O direito romano' },
  'As XII Tábuas são a primeira pedra de um edifício que ocupou mil anos: o direito romano. Foi sistematizado por Justiniano no séc. VI d.C. (*Corpus Iuris Civilis*), redescoberto em Bolonha no séc. XI, e é a base dos sistemas jurídicos de Portugal, de Espanha, de França, de Itália, da Alemanha e de grande parte do mundo. Muitos conceitos (*pater familias*, *res*, *obligatio*, *usucapio*, a distinção entre direito público e privado) nasceram nesta época ou logo a seguir.',
  { h: 'Língua e alfabeto' },
  'O latim deu origem às línguas românicas, entre elas o **português**. O alfabeto latino, de origem etrusca e grega, é hoje o mais usado do mundo. Entre as palavras portuguesas que nos chegam desta época estão *senado*, *cônsul*, *tribuno*, *plebeu*, *república*, *censo* e *ditador*.',
  { h: 'Os fasces e os seus usos modernos' },
  'O feixe de varas e machado (**fasces**) foi adotado em muitas repúblicas como símbolo de autoridade e de união (a França revolucionária e os Estados Unidos, que o puseram na Câmara dos Representantes e em moedas). No séc. XX, deu o nome ao **fascismo** italiano, que o usou como símbolo, apropriando-se de uma imagem romana com um sentido muito diferente.',
  { h: 'Expressões e lendas que ficaram' },
  { lista: [
    '**«Vitória de Pirro»:** vitória com custos tão altos que equivale a uma derrota.',
    '**«Passar sob as Forcas Caudinas»:** sofrer uma humilhação (expressão das línguas românicas, a partir de 321 a.C.).',
    '**«Cincinato»:** o governante que deixa o poder e volta à vida simples; a cidade de Cincinnati (EUA) tem esse nome.',
    '**«Senado», «cônsul», «censo», «ditador»:** palavras romanas que a política atual ainda usa, com sentidos muito alterados.',
    '**Rómulo e Remo:** a loba com os gémeos é o símbolo da cidade, e aparece em moedas, brasões e camisolas de clubes.'
  ] },
  { h: 'Como sabemos o que sabemos: o problema das fontes' },
  'Os historiadores modernos aprenderam a ser críticos. Em 1811, **Barthold Niebuhr** mostrou que muito da história primitiva de Roma era lenda; no séc. XIX, **Theodor Mommsen** usou as inscrições e as leis para reconstruir as instituições. Hoje, a arqueologia (de Boni, Lanciani, Carandini e outros) complementa os textos, mas não os confirma nem refuta todos. O consenso é que os factos são pouco seguros antes de c. 300 a.C., e que as datas dos reis são, na maior parte, convencionais. Os próprios Romanos sabiam que os registos antigos tinham sido destruídos em 390 a.C. (Lívio).',
  { h: 'A descoberta do Lapis Niger' },
  'O arqueólogo italiano **Giacomo Boni**, que dirigiu as escavações do Fórum de 1898 a 1911, descobriu em 1899, sob um pavimento de mármore preto, uma inscrição em pedra com latim arcaico, gravada em boustrofédon (alternando linhas da esquerda para a direita e da direita para a esquerda). A pedra, que a tradição associava ao túmulo de Rómulo, demonstrou que o Fórum tinha uma vida ritual e escrita no séc. VI a.C. Boni também escavou o Palatino e o *Sepolcreto* do Fórum.',
  { h: 'Os Etruscos: o que Roma lhes deve' },
  'Roma deve aos Etruscos o seu primeiro urbanismo monumental, a arquitetura do templo, a técnica do arco e da drenagem, as insígnias de poder (fasces, toga e cadeira curul), o triunfo, as artes divinatórias, e provavelmente o alfabeto. O interesse pelos Etruscos, uma civilização cuja língua não se compreende bem, é hoje grande: Villa Giulia, Cerveteri e Tarquínia (Património Mundial da UNESCO desde 2004) são essenciais.',
  { img: 'rmr-cista-ficoroni', leg: 'Cista Ficoroni, de Preneste, Villa Giulia.' },
  { h: 'Pirro e a lição da Itália' },
  'A guerra contra Pirro mostrou a Roma que podia defrontar-se com uma grande potência helenística, e mostrou ao Mediterrâneo que Roma era já uma delas. A conquista da Itália forneceu o modelo (aliados, colónias, estradas, cidadania) que será exportado para o resto do Mediterrâneo. A Sicília, que será a primeira província romana, depois da Primeira Guerra Púnica, vai mostrar os limites desse modelo.',
  { img: 'rmr-prato-capena', leg: 'Reprodução de um pormenor do prato de Capena, século III a.C., com elefante de guerra e cria; Villa Giulia, Roma.' },
  { h: 'Onde visitar' },
  { lista: [
    '**Fórum Romano e Palatino** (Roma): o Lapis Niger, o templo de Saturno, a Regia, as cabanas do Palatino (Casa Romuli) e a vista sobre o Circo Máximo.',
    '**Museus Capitolinos** (Roma): a Loba, o Bruto e outras peças arcaicas.',
    '**Muralha serviana** (Roma): troços junto à estação Termini, no Aventino e em Piazza Albania.',
    '**Largo di Torre Argentina** (Roma): quatro templos republicanos, dos séculos IV–III a.C.',
    '**Cloaca Maxima:** a saída no Tibre, junto à Ponte Palatino, é visível do rio.',
    '**Via Ápia Antiga** e o **Parque Arqueológico**: o troço mais bem conservado da estrada de 312 a.C.',
    '**Museu Nacional Etrusco da Villa Giulia** (Roma): o Apolo de Véios, o Sarcófago dos Esposos, o prato de Capena.',
    '**Cerveteri e Tarquínia:** necrópoles etruscas (UNESCO, 2004).',
    '**Ilha Tiberina** (Roma): santuário de Esculápio de 291 a.C., onde hoje está o hospital Fatebenefratelli.'
  ] },
  { h: 'E a Península Ibérica?' },
  'No período desta página, a Hispânia ainda não faz parte da história de Roma: só a partir de 218 a.C., na Segunda Guerra Púnica, as legiões desembarcam na península. Os Romanos só chegam ao território do atual Portugal depois de 200 a.C., e a conquista da Lusitânia (e a resistência de Viriato) pertence à página **A República Tardia**.'
];

const quiz = [
  { p: 'Segundo a tradição romana (Varrão), em que ano foi fundada Roma?', op: ['1000 a.C.', '753 a.C.', '509 a.C.', '264 a.C.'], certa: 1, exp: 'A data de 753 a.C. é de Varrão (séc. I a.C.) e é convencional: a arqueologia mostra um processo gradual.' },
  { p: 'Quantos reis teve Roma, segundo a tradição?', op: ['Cinco', 'Sete', 'Doze', 'Dois'], certa: 1, exp: 'Rómulo, Numa, Tulo Hostílio, Anco Márcio, Tarquínio Prisco, Sérvio Túlio e Tarquínio o Soberbo; os três últimos seriam de origem etrusca ou ligados à Etrúria.' },
  { p: 'Que acontecimento a tradição associa ao fim da Monarquia, em 509 a.C.?', op: ['A violação de Lucrécia e a expulsão dos Tarquínios', 'O saque de Roma pelos Gauleses', 'A guerra contra Pirro', 'A batalha de Sentino'], certa: 0, exp: 'Segundo Lívio, a violação de Lucrécia por Sexto Tarquínio levou Bruto e Colatino a expulsar o rei e a tornarem-se cônsules.' },
  { p: 'Que dois magistrados dirigiam a República, eleitos por um ano?', op: ['Dois cônsules', 'Dois reis', 'Dois ditadores', 'Dois censores'], certa: 0, exp: 'Cada cônsul podia vetar o outro: o poder dividido evitava o regresso à monarquia.' },
  { p: 'O que eram os tribunos da plebe?', op: ['Generais plebeus', 'Sacerdotes', 'Juízes das XII Tábuas', 'Magistrados sacrossantos que protegiam os plebeus'], certa: 3, exp: 'Criados, segundo a tradição, em 494 a.C., após a primeira secessão da plebe; tinham direito de veto.' },
  { p: 'Em que consistiu o «Conflito das Ordens»?', op: ['A luta de plebeus contra patrícios por direitos políticos', 'A luta entre Roma e Cartago', 'Uma guerra entre Etruscos e Latinos', 'Uma luta entre sacerdotes'], certa: 0, exp: 'Durou de 494 a 287 a.C., e foi quase sempre pacífica, com secessões e leis.' },
  { p: 'Que texto foi a primeira lei escrita de Roma, c. 450 a.C.?', op: ['O Código de Justiniano', 'A Lex Hortensia', 'Os Livros Sibilinos', 'As XII Tábuas'], certa: 3, exp: 'Redigidas pelos decênviros em 451–450 a.C. e expostas no Fórum; o original perdeu-se.' },
  { p: 'Que povo saqueou Roma em 390 a.C. (data tradicional)?', op: ['Os Gauleses', 'Os Samnitas', 'Os Etruscos', 'Os Cartagineses'], certa: 0, exp: 'Os Gauleses Senones, comandados por Breno, derrotaram os Romanos no Ália e saquearam a cidade; só o Capitólio resistiu.' },
  { p: 'Que cidade etrusca foi conquistada por Roma em 396 a.C., depois de um longo cerco?', op: ['Cére', 'Tarquínia', 'Véios', 'Clúsio'], certa: 2, exp: 'Véios, a 16 km de Roma, caiu sob o comando de Camilo, segundo a tradição.' },
  { p: 'Que humilhação sofreu Roma nas Forcas Caudinas, em 321 a.C.?', op: ['Um exército foi cercado e obrigado a passar sob o jugo', 'Perdeu o Capitólio', 'Perdeu a frota', 'Os cônsules foram mortos'], certa: 0, exp: 'Os Samnitas cercaram um exército romano num desfiladeiro e obrigaram-no a render-se, humilhando-o.' },
  { p: 'Que estrada começou a ser construída em 312 a.C. por Ápio Cláudio Cego?', op: ['Via Flamínia', 'Via Egnácia', 'Via Ápia', 'Via Aurélia'], certa: 2, exp: 'A Via Ápia ligou Roma a Cápua, e foi depois prolongada até Brindes.' },
  { p: 'Que lei, em 287 a.C., fez com que as decisões da assembleia da plebe valessem para todos os cidadãos?', op: ['Lex Canuleia', 'Lex Ogulnia', 'Lex Poetelia', 'Lex Hortensia'], certa: 3, exp: 'A Lex Hortensia é considerada o fim do Conflito das Ordens.' },
  { p: 'Que rei do Épiro invadiu a Itália em 280 a.C., chamado por Tarento?', op: ['Alexandre o Grande', 'Aníbal', 'Pirro', 'Antíoco'], certa: 2, exp: 'Pirro venceu em Heraclea e Ásculo, mas com perdas enormes; foi vencido em Benevento (275 a.C.).' },
  { p: 'O que se entende por «vitória de Pirro»?', op: ['Uma vitória que custa tanto que equivale a derrota', 'Uma vitória fácil', 'Uma vitória naval', 'Uma vitória sem batalha'], certa: 0, exp: 'A expressão vem da guerra de Pirro contra Roma, em que as baixas foram pesadas.' },
  { p: 'Como foi Roma capaz de substituir tantas legiões perdidas nas suas guerras de conquista da Itália?', op: ['Contratou mercenários gregos', 'Libertou todos os escravos', 'Integrou os vencidos como cidadãos e aliados, obrigados a fornecer tropas', 'Recebeu ajuda de Cartago'], certa: 2, exp: 'O sistema de alianças e de cidadania, e não só a força militar, deu a Roma enorme reserva de homens.' }
];

export default {
  id: 'roma',
  cor: '#b5413a',
  emblema: '../../assets/img/roma.png',
  grupo: { ...GRUPO, aqui: 'monarquia-republica' },
  nome:    { pt: 'Monarquia e República Antiga', en: 'Monarchy and Early Republic' },
  periodo: { pt: '753 – 264 a.C.', en: '753 – 264 BC' },
  visao:          { pt: visao, en: EN.visao },
  linha:          { pt: linha, en: EN.linha },
  mapa:           { pt: mapa, en: EN.mapa },
  sociedade:      { pt: sociedade, en: EN.sociedade },
  personalidades: { pt: personalidades, en: EN.personalidades },
  legado:         { pt: [...legado, ...CRED.pt], en: [...EN.legado, ...CRED.en] },
  quiz:           { pt: quiz, en: EN.quiz }
};
