// FROM THE VEDIC AGE TO THE MAHAJANAPADAS (c. 1500 – 321 BC) — English version. Same structure and image ids as dados.js.
// Chronology is fragile: almost all dates before Alexander (326 BC) are estimates; the dates of the Magadhan kings follow tradition (Mahavamsa, Puranas) and some scholars lower or raise them. Flagged in the text.

const visao = [
  { caixa: 'In brief', texto: [
    'Between c. **1500 BC** and **321 BC** the world we later call “classical” took shape in northern India. It begins with the cattle-herders and poets of the **Rigveda** in the Punjab and ends with the fortified cities of the **Ganges** valley, the **sixteen great kingdoms** (*Mahajanapadas*), the rise of **Magadha**, the teaching of the **Buddha** and **Mahavira**, the annexation of the north-west by the **Persians**, and the lightning passage of **Alexander the Great** through the Punjab (326 BC). It is also the age of the **Vedas**, of the **Upanishads** and of the grammar of **Panini**.',
    'This is not the history of “one people” or of a single state. It is the slow story of communities that moved from herding to iron-tool farming, from tribes to kingdoms, from villages to cities, and from the fire ritual to the question of what we are and what frees us. Almost everything we know comes from texts handed down orally for centuries, from archaeology and from foreigners’ accounts; so dates are approximate, and many popular images (the “Vedic golden age”, for instance) are younger than the sources.'
  ] },
  { img: 'ive-mapa-mahajanapadas', leg: 'Map of the Mahajanapadas, the “great realms” of northern India, c. 500 BC.' },
  { h: 'Where it was' },
  'The stage was **northern India**. The oldest hymns are set in the **Punjab** and along the Indus and its tributaries (the “land of the seven rivers”, *Sapta Sindhu*), with the Hindu Kush and the Himalaya behind. Over time the centre of gravity moved east: to the **Doab** (the land between the Ganges and the Yamuna, home of the Kurus and Panchalas), then to the **middle Ganges** (Kosala, Kashi, Videha) and finally to **Magadha**, in what is now southern Bihar. The north-west (Gandhara, Taxila) remained the gateway to Iran and Central Asia.',
  'The east and centre had what the Punjab lacked: regular rainfall, alluvial soils, forests to clear, broad rivers for moving goods, and, in Magadha, iron ore close at hand. The **Deccan** and the south had a history of their own, with megalithic cultures and Dravidian languages; they enter here only where they touch the north.',
  { img: 'ive-mapa-india-vedica', leg: 'Schematic map of the regions of northern India in the Vedic period and the eastward shift.' },
  { h: 'When it existed' },
  'The phases below are a modern arrangement with fluid boundaries. Absolute dates only become firm from 326 BC, with Alexander.',
  { tabela: { cab: ['Phase', 'Approximate dates', 'What marks it'], linhas: [
    ['Early Vedic period', 'c. 1500 – 1000 BC', 'Hymns of the Rigveda; tribes of herders and warriors in the Punjab; chariots, horses, cattle; gods such as Indra, Agni and Varuna'],
    ['Later Vedic period', 'c. 1000 – 600 BC', 'Other Vedas and the Brahmanas; iron; farming villages in the Doab; Kuru and Panchala kingdoms; royal sacrifices; first Upanishads'],
    ['Second urbanisation and the Mahajanapadas', 'c. 600 – 450 BC', 'Cities of the Ganges; silver coins; 16 great realms; the Buddha and Mahavira; rise of Magadha under Bimbisara and Ajatashatru'],
    ['Persians in the north-west', 'c. 520 – 330 BC', 'Gandhara and Hindush are provinces of the Achaemenid Empire; tribute in gold; Aramaic and Kharosthi scripts; Panini'],
    ['Nandas and Alexander', 'c. 345 – 321 BC', 'The Nandas unify much of the Ganges; Alexander defeats Porus (326); the period ends with the founding of the Maurya Empire']
  ] } },
  { caixa: 'A note of caution on dates', texto: 'There are no Indian chronicles for this period. The dates of the Magadhan kings come from Buddhist lists (such as the Sri Lankan *Mahavamsa*) and from the *Puranas*, written centuries later; those of the Vedas come from the evolution of the language and from comparisons. The **dates of the Buddha and Mahavira** are debated (see below). That is why this text so often says “c.”, “according to tradition” and “debated”, and gives ranges where there is no consensus.' },
  { h: 'What sources we have' },
  'This was a civilisation that **spoke more than it wrote**. The sources are of very different kinds and must be read with care:',
  { lista: [
    '**Vedic texts:** the four Vedas (*Rigveda*, *Samaveda*, *Yajurveda*, *Atharvaveda*), the *Brahmanas*, *Aranyakas* and the first *Upanishads*, in Sanskrit, memorised and committed to writing only much later. They give the view of the Brahmin priests, not of the whole of society.',
    '**Buddhist and Jain texts:** the Pali canon (the *Nikayas*, the *Jatakas*) and the Jain *Agamas* describe kings, cities and merchants of the Buddha’s time, but were written or compiled centuries later, with a religious purpose.',
    '**Archaeology:** Painted Grey Ware and Northern Black Polished Ware (*NBPW*), earth and brick ramparts, iron, punch-marked coins; excavations at Hastinapura, Kaushambi, Rajgir, Ujjain and Taxila.',
    '**Persian inscriptions and Greek accounts:** Darius mentions Gandara and Hindush; Herodotus, Ctesias and, later, Alexander’s historians (Arrian, Quintus Curtius, Diodorus, Plutarch) describe India seen from outside, with errors and fantasies.',
    '**Grammarians:** Panini and his commentators reveal the spoken Sanskrit and the society that used it.'
  ] },
  { img: 'ive-pgw', leg: 'Painted Grey Ware, typical of the Doab between c. 1200 and c. 600 BC; linked, with debate, to the later Vedic kingdoms.' },
  { h: 'Who were they?' },
  'Most of the texts of this period are in **Vedic Sanskrit**, an Indo-Aryan language related to Avestan (of Iran) and, more distantly, to Greek, Latin and the Germanic and Slavic languages. The speakers called themselves *arya*, a word that meant “noble, of good family” and did not denote a “race”. The origin of the speakers of Indo-Aryan languages is one of the most debated and most politicised subjects in Indian history: most linguists and archaeologists accept that they reached the north-west in the second millennium BC from Central Asia and mixed with local populations; a minority argues for a local origin. Recent population genetics supports the steppe-migration thesis, but details remain under discussion.',
  'Either way, the result was not a uniform “Vedic people”: it was a set of tribes sharing language and ritual, living alongside communities of other languages (Dravidian, Austroasiatic), hunter-gatherers and long-established farmers. The words *dasa* and *dasyu* in the hymns denote enemies or servants, but it is impossible to say whom they correspond to.',
  { img: 'ive-rigveda-ms', leg: 'Manuscript of the Rigveda in Devanagari script (a late copy; the hymns were transmitted by memory for centuries).' },
  { h: 'Why they matter' },
  { lista: [
    '**Language and literature:** Vedic Sanskrit and Panini’s grammar are a foundation of linguistics; it was the study of Sanskrit, in the late eighteenth century, that helped show that the languages of India and Europe share one origin (the Indo-European family).',
    '**Ideas that crossed Asia:** *dharma*, *karma*, rebirth (*samsara*) and liberation (*moksha*, *nirvana*) appear or consolidate in this period.',
    '**Buddhism and Jainism:** two world religions were born in the cities of the Ganges, in an atmosphere of free debate among rival teachers.',
    '**Kingdoms and republics:** northern India had, at the same time, monarchies and assembly republics (*gana-sangha*), a political laboratory unique in antiquity.',
    '**Cities, coinage and trade:** the “second urbanisation” (the first was that of the Indus) created the world of merchants, guilds and roads that sustained the later empires.',
    '**Contact with Persia and Greece:** India’s first direct link to the Mediterranean world, which prepares the ground for the Mauryas, Indo-Greeks and Kushans.'
  ] },
  { img: 'ive-aldeia-vedica-rig', leg: 'Artist’s reconstruction: a camp of herders in the early Vedic period, with cattle, chariots and a fire altar.' },
  { caixa: 'This period today', texto: 'Vedic hymns are still **recited** in rituals across the subcontinent, with a memorisation technique so rigorous that the text has barely changed; UNESCO proclaimed Vedic chanting a masterpiece of the oral heritage of humanity in 2003. Lumbini, Bodh Gaya and Taxila are UNESCO World Heritage Sites. The Buddha’s cities (Rajgir, Vaishali, Varanasi, Kushinagar) are places of pilgrimage, and the name “India” comes from the river Indus, the *Sindhu*, via Persian and Greek, as does “Hindu”.' }
];

const linha = [
  'This timeline follows the main events and changes. Before 326 BC almost all dates are estimates; those of the Magadhan kings follow tradition and those of the Buddha and Mahavira are debated, as explained in each entry.',
  { linha: [
    { d: 'c. 1500 – 1200 BC (debated)', t: 'The first hymns of the Rigveda', x: 'In north-western India, priest-poets compose in Vedic Sanskrit the hymns of the **Rigveda**, about 1000 hymns to gods such as Indra, Agni, Varuna and Ushas. They speak of cattle, horses, chariots, rivers and wars between tribes. The text will be written down only much later; the dating (some propose c. 1900 BC, others c. 1200) is debated.' },
    { d: 'c. 1200 – 1000 BC', t: 'The other Vedas and the move east', x: 'The *Samaveda* (chants), the *Yajurveda* (ritual formulas) and then the *Atharvaveda* (spells and remedies) are composed. Indo-Aryan-speaking communities advance into the **Doab**, between the Ganges and the Yamuna. Painted Grey Ware appears.' },
    { d: 'c. 1000 – 800 BC', t: 'Iron and the kingdom of the Kurus', x: 'Iron (“dark metal”, *shyama ayas*, in the Atharvaveda) appears in the Ganges basin. The **Kurus**, in the Doab, organise the ritual and gather the hymns; King Parikshit is remembered in the texts. The **Brahmanas**, treatises on sacrifice, explain every gesture of the rite. The Kurus and the **Panchalas** are the great kingdoms of the age.' },
    { d: 'c. 800 – 600 BC (debated)', t: 'The first Upanishads', x: 'In the *Brihadaranyaka* and the *Chandogya*, teachers such as **Yajnavalkya** and **Uddalaka Aruni** move from ritual to the question of the *atman* (the deep self) and *Brahman* (the principle of everything). The ideas of rebirth and liberation appear. King **Janaka** of Videha, in the east, is patron of debates.' },
    { d: 'c. 700 – 600 BC', t: 'The second urbanisation', x: 'In the middle Ganges, cities arise with earth and brick ramparts (**Kaushambi**, **Varanasi**, **Ujjain**, **Rajgir**), with polished black pottery and iron tools. It is called “second” because the first urbanisation was that of the Indus valley, over a thousand years earlier.' },
    { d: 'c. 600 BC', t: 'The Mahajanapadas', x: 'Buddhist and Jain texts speak of **sixteen great kingdoms** (*Mahajanapadas*), from Gandhara to Assaka in the Deccan. Some are monarchies (Magadha, Kosala, Kashi, Avanti, Vatsa), others republics governed by assemblies (Vajji, Malla, Shakya).' },
    { d: 'c. 6th – 5th century BC', t: 'The first coins', x: '**Silver punch-marked coins** (*karshapana*) appear, among the oldest in the world (the date is much debated: from the 6th century BC, according to the Indian historiographical tradition, to the mid-4th century BC, according to Joe Cribb, who links them to Achaemenid coinage in the north-west). They ease taxes, trade and credit, and signal the growing power of merchants and kings.' },
    { d: 'c. 544 – 492 BC (tradition)', t: 'Bimbisara and the beginning of the rise of Magadha', x: 'King **Bimbisara** rules Magadha from Rajagriha (Rajgir), annexes the neighbouring kingdom of **Anga** and allies himself by marriage with Kosala. Buddhist tradition describes him as a protector of the Buddha. The dates follow the *Mahavamsa*; some historians propose much later dates (for example, c. 457 – 405 BC), and the short chronology of the Buddha places him around 400 BC.' },
    { d: 'c. 480 – 400 BC or c. 563 – 483 BC (debated)', t: 'The Buddha', x: 'Siddhartha Gautama, of the Shakya clan, teaches in the Ganges valley for about 45 years and dies at Kushinagar. The long chronology gives 563 – 483 BC (the Sinhalese tradition, 624 – 544 BC); the short one, preferred by many historians since a 1988 symposium, at which most speakers placed his death within about 20 years either side of 400 BC.' },
    { d: 'c. 6th – 5th century BC (debated)', t: 'Mahavira and Jainism', x: '**Vardhamana Mahavira**, born near Vaishali, is the last of the 24 teachers (*tirthankaras*) of Jainism. Jain tradition gives c. 599 – 527 BC; some historians place him about a century later, a contemporary of the Buddha. He teaches absolute non-violence (*ahimsa*).' },
    { d: 'c. 520 – 510 BC', t: 'The Persians in Gandhara and the Indus', x: 'The Achaemenid Empire of **Darius I** annexes **Gandara** and **Hindush** (the lower Indus); they appear as provinces in Darius’s inscriptions. Around 515 BC, according to Herodotus, the Greek **Scylax of Caryanda** sails down the Indus and returns by sea to Egypt. The Indian satrapy pays, according to Herodotus, 360 talents of gold dust a year.' },
    { d: 'c. 492 – 460 BC (tradition)', t: 'Ajatashatru and the war against the Vajjis', x: '**Ajatashatru**, son of Bimbisara, takes the throne (according to tradition, deposing his father), fights Kosala and destroys the republic of the **Vajjis** (Licchavis) at Vaishali, with war machines described in Jain texts. He fortifies the settlement of Pataligrama, which will become Pataliputra.' },
    { d: 'c. 480 BC', t: 'Indian soldiers in the Persian army', x: 'Herodotus lists contingents from Gandhara and India in the army of **Xerxes** marching against Greece: dressed in cotton, with cane bows and iron-tipped arrows. Indian soldiers appear again at Gaugamela, in 331 BC.' },
    { d: 'c. 6th – 4th century BC (debated)', t: 'Panini fixes Sanskrit', x: 'The grammarian **Panini**, of Shalatura in Gandhara (near Attock), composes the *Ashtadhyayi*, a grammar of Sanskrit with about 4000 rules. It fixes the “refined” language (*samskrta*) that will be distinguished from Vedic Sanskrit and from popular dialects (Prakrits).' },
    { d: 'c. 460 – 440 BC (tradition)', t: 'Pataliputra becomes the capital', x: 'According to tradition, **Udayin**, son of Ajatashatru, moves the capital from Rajagriha to **Pataliputra** (on the Ganges and the Son), easier to reach by river and better placed to control trade. The city will be the capital of Magadha and, later, of the Mauryas.' },
    { d: 'c. 413 – 345 BC (tradition)', t: 'The Shishunagas', x: 'According to the *Mahavamsa*, the **Shishunaga** dynasty succeeds the Haryankas. It annexes **Avanti** (with Ujjain), a decisive step in the unification of the north. The chronology is uncertain, and some sources give a different order of kings.' },
    { d: 'c. 345 BC', t: 'The Nandas', x: '**Mahapadma Nanda** founds the **Nanda** dynasty, which dominates almost the whole Ganges basin and parts of the centre and the east coast. The *Puranas* call him “destroyer of all kshatriyas”. The army and treasury are legendary; the last king, **Dhana Nanda**, is remembered for wealth and heavy taxation.' },
    { d: '331 BC', t: 'Gaugamela', x: 'Darius III musters at Gaugamela contingents from Bactria and Gandhara; according to Arrian, they include about 15 war elephants. Alexander wins, and the Persian provinces of the east lie open to him.' },
    { d: '327 BC', t: 'Alexander crosses the Hindu Kush', x: 'Alexander descends into the lands of the Kophen (Kabul), Swat and the Indus, facing tribes such as the Assakenoi (siege of Massaga, 327 – 326 BC). At Massaga, according to Diodorus and Quintus Curtius, even the mercenaries’ wives took up arms.' },
    { d: '326 BC', t: 'Taxila and the Hydaspes', x: 'The king of Taxila, **Ambhi** (Omphis in Greek sources), welcomes Alexander with open arms. In May, on the Hydaspes (Jhelum), Alexander defeats **Porus** in a very hard-fought battle, with elephants on the Indian side. He founds two cities, Nicaea and Bucephala, and leaves Porus to govern his kingdom.' },
    { d: 'late 326 BC', t: 'The army refuses to advance', x: 'On the river **Hyphasis** (Beas), Alexander’s soldiers, exhausted and frightened by reports of the huge Nanda army (sources give exaggerated figures, with thousands of elephants), refuse to go on. Alexander turns back.' },
    { d: '325 BC', t: 'The descent of the Indus', x: 'The army goes down the Hydaspes and the Indus in a fleet of hundreds of boats. In a campaign against the Malli (Malavas), Alexander is gravely wounded. He reaches Pattala, in the delta, and then leaves, by land and by sea (Nearchus), for Iran.' },
    { d: '325 – 323 BC', t: 'The garrisons dissolve', x: 'The governors left in the Punjab are killed or recalled in the following years. Alexander dies in Babylon in June 323 BC, and the divided empire leaves north-western India without a stable power.' },
    { d: 'c. 321 BC', t: 'The end of the Nandas and the start of the Mauryas', x: '**Chandragupta Maurya** (who, according to Plutarch, saw Alexander as a young man) overthrows the Nandas, takes Pataliputra and founds the **Maurya Empire**. The story of the next page begins.' }
  ] },
  { img: 'ive-moedas-punch', leg: 'Silver punch-marked coins (*karshapana*), 5th – 3rd centuries BC.' },
  { img: 'ive-persepolis-indianos', leg: 'An Indian delegation bringing tribute, relief on the Apadana stairway, Persepolis.' },
  { img: 'ive-kharosthi-shahbazgarhi', leg: 'Inscription in Kharosthi script (Ashoka’s edict at Shahbazgarhi, 3rd century BC): the script, derived from Aramaic, was born of contact with Persian administration.' },
  { img: 'ive-mapa-nandas', leg: 'Schematic map of the Nanda Empire, c. 323 BC.' },
  { img: 'ive-mapa-alexandre', leg: 'Map of Alexander’s campaign in north-western India, 327 – 325 BC.' },
  { img: 'ive-hidaspes-batalha', leg: 'Artist’s reconstruction: the battle of the Hydaspes between Alexander and Porus, 326 BC.' }
];

const mapa = [
  'In this period there was no single capital and no dominant centre. Here are the 16 Mahajanapadas and the key places: cities, sanctuaries and archaeological sites, from the north-west to the east, with the routes that linked them.',
  { h: 'The sixteen Mahajanapadas' },
  'The most widely used list comes from the Buddhist *Anguttara Nikaya*. Other texts give different lists: the *Digha Nikaya* omits four states of the north-west and south, and the Jain *Bhagavati* text presents another series, more focused on the centre and east. It is not an official political map, but a way of speaking of the great kingdoms of the Buddha’s time. Capital names and modern locations are, in some cases, approximate.',
  { tabela: { cab: ['Mahajanapada', 'Capital (tradition)', 'Region (today)', 'Regime'], linhas: [
    ['Anga', 'Champa', 'eastern Bihar and western Bengal', 'Monarchy; annexed by Bimbisara'],
    ['Magadha', 'Rajagriha, later Pataliputra', 'southern Bihar', 'Monarchy; the winning state'],
    ['Kashi', 'Varanasi', 'Uttar Pradesh', 'Monarchy; absorbed by Kosala and then by Magadha'],
    ['Kosala', 'Shravasti and Saketa (Ayodhya)', 'Uttar Pradesh', 'Monarchy'],
    ['Vajji (Vriji)', 'Vaishali', 'northern Bihar and southern Nepal', 'Confederation of clans, with the Licchavis and the Videhas'],
    ['Malla', 'Kushinagar and Pava', 'eastern Uttar Pradesh', 'Republic (*gana-sangha*)'],
    ['Chedi', 'Shuktimati', 'Bundelkhand', 'Monarchy'],
    ['Vatsa', 'Kaushambi', 'Uttar Pradesh', 'Monarchy'],
    ['Kuru', 'Indraprastha (Delhi)', 'Delhi and Haryana', 'Monarchy or republic'],
    ['Panchala', 'Kampilya and Ahichchhatra', 'Uttar Pradesh', 'Monarchy or republic'],
    ['Machcha (Matsya)', 'Viratanagara', 'Rajasthan', 'Monarchy'],
    ['Surasena', 'Mathura', 'Uttar Pradesh', 'Monarchy'],
    ['Assaka (Ashmaka)', 'Potana or Potali', 'Maharashtra and Telangana (Godavari)', 'Monarchy; the southernmost'],
    ['Avanti', 'Ujjain and Mahishmati', 'Madhya Pradesh', 'Monarchy'],
    ['Gandhara', 'Taxila and Pushkalavati', 'Punjab (Pakistan) and eastern Afghanistan', 'Monarchy'],
    ['Kamboja', 'Rajapura (debated)', 'north-west (Hindu Kush)', 'Monarchy or republic']
  ] } },
  { caixa: 'Republics and monarchies', texto: 'Several of the states in the texts were **oligarchic republics** (*gana* or *sangha*), governed by assemblies of clan chiefs who decided by debate and vote; the Vajjis, the Mallas and the Shakyas are the classic example. They were smaller and less wealthy than the monarchies, and ended up absorbed by Magadha and Kosala. Some see in the procedures of the Buddhist monastic community (motions, quorum, voting by sticks) an echo of how these assemblies worked, but this is a hypothesis.' },
  { h: 'Rajagriha' },
  'The first capital of Magadha lay in a valley ringed by five hills, near iron and copper mines. Its **cyclopean walls**, of dry-stone blocks with a perimeter of nearly 40 km, are the most visible defensive work, and have been dated to several different centuries (the period of Bimbisara is one hypothesis). Tradition links the city to the Buddha (who lived and taught in the bamboo grove, the *Veluvana*, which Bimbisara gave him) and to Mahavira, and to the **first Buddhist council**, convened after the master’s death, according to tradition, under Ajatashatru’s patronage.',
  { img: 'ive-rajgir-muralha', leg: 'Stretch of the cyclopean walls of Rajgir (ancient Rajagriha, Bihar).' },
  { img: 'ive-cidade-gangetica', leg: 'Artist’s reconstruction: a Ganges city in the 5th century BC, with earth and brick rampart, wooden gates and the river behind.' },
  { h: 'Pataliputra' },
  'According to Buddhist tradition, Ajatashatru had the village of **Pataligrama** (at the confluence of the Ganges and the Son) fortified to defend against the Vajjis; the Buddha, passing through, is said to have foretold the city’s greatness. Later the capital moved there (with Udayin, according to tradition). Today it is Patna. Excavations at Kumhrar and elsewhere have found only remains of Mauryan and later date, and the earliest levels lie beneath the modern city.',
  { img: 'ive-pataligama-fortaleza', leg: 'Artist’s reconstruction: the fortified village of Pataligrama, on the Ganges, in the time of Ajatashatru.' },
  { h: 'Vaishali' },
  'Capital of the **Vajjis**, the most famous clan republic, where the Licchavis lived. According to the *Mahaparinibbana Sutta*, Ajatashatru’s minister **Vassakara** went to ask the Buddha whether he should attack the Vajjis; the Buddha answered by listing the conditions of their welfare (frequent assemblies, respect for elders, among others), and the minister concluded that only through internal division could they be defeated. It is a late account, but it shows how the republic was thought of. It was also at Vaishali that, according to tradition, the second Buddhist council met, about a hundred years after the Buddha’s death (historicity debated).',
  { img: 'ive-vaishali-pilar', leg: 'Ashoka pillar and ancient stupa at Vaishali (Bihar); the pillar dates from the 3rd century BC, after the time of the republic.' },
  { h: 'Varanasi (Kashi)' },
  'One of the oldest continuously inhabited cities in India, on the Ganges. Excavations at **Rajghat** reveal occupation from c. 800 BC. It was a centre of trade in fine textiles and sandalwood, famous for its crafts, and the capital of Kashi until that kingdom was absorbed by Kosala. Buddhist tradition places Jataka tales “in the reign of Brahmadatta, king of Benares”. To the north lies **Sarnath**, where the Buddha preached his first sermon.',
  { img: 'ive-ganges-varanasi', leg: 'The Ganges at Varanasi (Benares), with its *ghats*; the city has been inhabited for almost three thousand years.' },
  { h: 'Lumbini, Bodh Gaya, Kushinagar' },
  'The Buddha’s life is tied to four places: **Lumbini** (birth, now in Nepal), **Bodh Gaya** (enlightenment), **Sarnath** (first sermon) and **Kushinagar** (death). At Lumbini, a 2013 excavation beneath the Maya Devi temple identified a timber structure that archaeologists date to c. the 6th century BC (interpretation debated). The site of **Kapilavastu**, city of the Shakyas, is disputed between Piprahwa (India) and Tilaurakot (Nepal). Ashoka’s pillar at Lumbini, of 249 BC, is the earliest proof that the site was venerated.',
  { img: 'ive-lumbini-pilar', leg: 'Ashoka’s pillar at Lumbini (Nepal), with a 3rd-century BC inscription identifying the Buddha’s birthplace.' },
  { img: 'ive-bodh-gaya', leg: 'The Mahabodhi Temple at Bodh Gaya (Bihar); the present building is later, but the site has been venerated since the 3rd century BC.' },
  { img: 'ive-kushinagar-ramabhar', leg: 'The Ramabhar stupa at Kushinagar, associated by tradition with the site of the Buddha’s cremation.' },
  { h: 'Shravasti and Kosala' },
  'Shravasti, capital of **Kosala** in the time of the Buddha and King **Pasenadi** (Prasenajit), was where the Buddha spent most rainy seasons, in the **Jetavana** park, bought, according to tradition, by the banker **Anathapindika** (covering it with gold coins). Kosala dominated Kashi and the Shakyas; under Pasenadi’s son Vidudabha, the Shakyas were attacked, according to tradition. Later, Kosala was absorbed by Magadha.',
  { img: 'ive-jetavana-bharhut', leg: 'Bharhut relief (2nd century BC) illustrating the purchase of the Jetavana by the merchant Anathapindika, with coins covering the ground.' },
  { h: 'Kaushambi and Ujjain' },
  '**Kaushambi**, capital of Vatsa, on the Yamuna, has one of the earliest brick ramparts and was a great river emporium between the Ganges and the west. **Ujjain**, capital of Avanti, lay at the crossroads between the north and the west coast (Bharuch) and was ringed by an enormous earthen bank (dated before c. 600 BC by some and to the 6th – 4th centuries BC by others; it already showed signs of urbanisation around 700 BC); later it is a centre of astronomy. King **Pradyota** of Avanti is Magadha’s great rival until the Shishunagas absorb it.',
  { h: 'Hastinapura and the world of the Kurus' },
  'The Kurus lived in the Doab, where Kurukshetra and **Hastinapura** lie, today a village near Meerut. In the excavations of the 1950s, B. B. Lal found Painted Grey Ware and traces of Ganges floods, which have been linked to the tradition that the city was swept away by the waters. The relationship between these finds and the war of the **Mahabharata** is **very debated**: the poem has layers from different centuries, and it is not a chronicle.',
  { h: 'Taxila and Gandhara' },
  '**Taxila** (*Takshashila*), near Islamabad, controlled the route between the Indus and Central Asia. The earliest city, the **Bhir Mound**, dates from c. the 6th century BC and was, under the Persians, then under Alexander (Ambhi) and the Mauryas, a great emporium. Later Buddhist texts speak of it as a place of study of medicine, arts and warfare; the grammarian **Panini** was from Gandhara. The capital of Gandhara was **Pushkalavati** (Charsadda), in the Peshawar valley.',
  { img: 'ive-taxila-bhir', leg: 'Remains of the Bhir Mound, the earliest city at Taxila (Pakistan), 6th – 2nd centuries BC.' },
  { img: 'ive-taxila-cidade', leg: 'Artist’s reconstruction: a street in Taxila in the 4th century BC, with stone and clay houses, merchants from the north-west and an ascetic.' },
  { h: 'The Persian satrapies: Gandara and Hindush' },
  'In the inscriptions of Darius and Xerxes, **Gandara** and **Hindush** appear among the provinces of the empire; Hindush corresponds to the lower Indus (Sind) and perhaps part of the Punjab. At Persepolis, the Apadana reliefs show “Indian” delegations bringing tribute; on Darius’s tomb at Naqsh-e Rustam, an inscription lists the provinces. The provincial capital was probably Taxila or Pushkalavati. The rule lasted about two centuries, until Alexander; it left the **Aramaic script** and **Kharosthi** (derived from it), coins and administrative techniques.',
  { img: 'ive-naqsh-rustam', leg: 'The tomb of Darius I at Naqsh-e Rustam (Iran); its inscriptions list the provinces of the empire, among them Gandara and Hindush.' },
  { img: 'ive-satrapia-persa', leg: 'Artist’s reconstruction: delegates from Gandhara delivering gold tribute to a Persian satrap, 5th century BC.' },
  { h: 'Rivers and routes' },
  'The great trade axis was the **Uttarapatha** (“northern route”), from Taxila through Mathura and Kaushambi to Varanasi, Pataliputra and the port of **Tamralipti**, at the mouth of the Ganges. Rivers such as the Ganges, Yamuna, Son and Gandak served as “motorways” for wooden boats. To the south, the **Dakshinapatha** linked Kaushambi and Ujjain to the Deccan (Pratishthana, Assaka) and to the west coast (Bharuch, Surparaka); to the west, the Indus connected Pattala with the sea and the Hindu Kush passes with Iran.',
  { h: 'The Deccan and the south' },
  'Only **Assaka**, on the Godavari, appears among the Mahajanapadas. In the Deccan and the south, the period is that of the **megalithic cultures** (stone tombs with iron and black-and-red pottery), of farmers and herders speaking Dravidian languages. The Tamil kingdoms (Chera, Chola, Pandya) already exist when Ashoka mentions them in the 3rd century BC, but their origins are obscure and the Sangam literature, in Tamil, is later.',
  { h: 'Alexander’s route' },
  'Alexander entered India by the valley of the Kophen (Kabul), went up the Swat and crossed the Indus near **Ohind** (Und), in early 326 BC. He went on to Taxila, defeated Porus on the Hydaspes, advanced to the **Hyphasis** (Beas), east of the Punjab, and turned back. The descent of the Indus (325 BC) took him to the delta; the return was made partly through Gedrosia (the Baluchistan desert), with heavy losses. The cities he founded (Nicaea, Bucephala, Alexandria on the Indus) have left no clear remains.'
];

const sociedade = [
  { h: '1. Political organisation' },
  'In the early Vedic period, the unit was the **tribe** (*jana*), led by a *rajan*, the “king” or chief, whose power was limited by assemblies (*sabha*, *samiti*). The chief led cattle raids and war, and was helped by a household priest (*purohita*). The hymns speak of the **battle of the ten kings** (*Dasarajna*), on the river Parushni (Ravi), in which the chief Sudas of the Bharatas defeated a coalition of tribes, one of the few historical episodes of the Rigveda.',
  'In the later period, the tribes settled in **territories** (*janapada*), and the chiefs became **kings** whose power rested on grand rites: the *rajasuya* (consecration), the *vajapeya* (chariot race) and the *ashvamedha*, the **horse sacrifice**, in which a horse, let loose for a year, roamed neighbouring territories, and a king who followed it claimed sovereignty over them. Assemblies lost weight, the warrior nobility (*kshatriyas*) and the priests (Brahmins) supported each other, and the idea of the king as protector of *dharma* emerged.',
  { img: 'ive-assembleia-sabha', leg: 'Artist’s reconstruction: an assembly (*sabha*) of the Vedic period, with clan chiefs seated in a circle under a shelter.' },
  { h: 'Monarchies and republics' },
  'In the age of the Mahajanapadas there were two forms of government. In the **monarchies** (Magadha, Kosala, Avanti, Vatsa), the king, helped by ministers, treasurers and generals, collected taxes (traditionally about a sixth of the harvest) and kept standing armies. In the **republics** (*gana-sangha*), an assembly of clan chiefs chose a president (*raja*) and decided by debate; the Vajjis had a confederation of eight clans. Buddhist texts praise the republics, Brahmins criticised them; but the monarchies, with greater resources, won.',
  { h: 'How Magadha won' },
  'Magadha had natural advantages: **iron and copper ores** in the hills, **elephants** from the nearby forests, alluvial soils rich in rice, **navigable rivers** (Ganges, Son, Gandak) and well-defended capitals. The kings added cunning and determination: Bimbisara married princesses of Kosala, Licchavi and Madra; Ajatashatru attacked the Vajjis and Kosala; the Nandas and then the Mauryas inherited an apparatus of taxes and war. The late texts stress one lesson: Magadha won more by organisation than by morality.',
  { h: 'Persia and the north-west' },
  'The north-west followed another path. Darius I made Gandhara and Hindush satrapies. The satraps sent tribute in gold, soldiers and goods, and Persian administration brought Aramaic as the language of bureaucracy. Herodotus says the Indian satrapy paid 360 talents of **gold dust** a year, the largest contribution in the empire, and tells that the gold was gathered from “giant ants” (a fanciful tale, perhaps a misunderstanding of a local story). Persian rule also took Indian soldiers to the wars of the Mediterranean.',
  { img: 'ive-daric', leg: 'Achaemenid gold daric; according to Herodotus, the tribute of the Indian satrapy was paid in gold dust.' },
  { h: '2. Vedic religion' },
  'The religion of the **Rigveda** is that of a society of herders and warriors: the gods are forces of nature and of the order of the world (*rita*), invoked with hymns, offerings of milk, clarified butter (*ghee*) and grain, and the ritual drink **Soma**, whose original plant is unknown (debated). Fire (*Agni*) is the messenger that carries offerings to the gods. There were no temples or cult images: sacrifice was performed in the open air, on temporary altars.',
  { tabela: { cab: ['God or goddess', 'Domain', 'Notes'], linhas: [
    ['Indra', 'Rain, thunder and war', 'The most invoked god in the Rigveda (about a quarter of the hymns); slays the dragon Vritra and frees the waters'],
    ['Agni', 'Sacrificial fire', 'Messenger between humans and gods; opens the Rigveda'],
    ['Soma', 'Sacred drink and plant', 'Book IX of the Rigveda is dedicated to him'],
    ['Varuna and Mitra', 'Cosmic order (*rita*) and oaths', 'Varuna sees all and punishes lies; kin of the Persian Mithra/Ahura Mazda'],
    ['Ushas', 'The dawn', 'One of the few prominent goddesses; very beautiful hymns'],
    ['Surya and Savitar', 'The Sun', 'The famous *Gayatri* (3.62.10) invokes Savitar'],
    ['Rudra and the Maruts', 'Storm', 'Rudra will later be associated with Shiva'],
    ['Vishnu', 'Strides across the universe', 'A minor god in the Rigveda; will gain importance later'],
    ['Prajapati', 'The creator', 'Dominant figure in the Brahmanas']
  ] } },
  { h: 'Ritual and the Brahmanas' },
  'In the later period sacrifice became a **complex system** of altars, formulas and specialists: four groups of priests, with the *hotar* (who recites the Rigveda), the *adhvaryu* (who performs the rite and murmurs formulas from the Yajurveda), the *udgatar* (who sings the Samaveda) and the *brahman* (who supervises). The *Brahmanas* explain the meaning of every gesture and say that sacrifice sustains the cosmos. The **Agnicayana** rite, the building of a brick altar in the shape of a bird, is still performed in Kerala, and was documented by researchers in 1975 and again in 2011.',
  { img: 'ive-yajna-reconstrucao', leg: 'Artist’s reconstruction: a fire sacrifice (*yajna*) conducted by priests in the Doab, c. 800 BC.' },
  { img: 'ive-agnicayana', leg: 'The Agnicayana ritual in Kerala (modern photograph): the tradition described in the Brahmanas is still practised.' },
  { h: 'From hymns to questions' },
  'Already in the hymns, some poets ask daring questions. The famous creation hymn (*Nasadiya*, Rigveda 10.129) asks where the world came from and ends, in paraphrase, with the doubt whether anyone knows, “perhaps not even he who watches from highest heaven”. In the **Upanishads** (from *upa-ni-shad*, “sitting near the teacher”), this attitude becomes central: inner sacrifice replaces outer. The question is: what lies behind the world (*Brahman*) and within each being (*atman*)? The answer, in formulas such as *tat tvam asi* (“you are that”, *Chandogya*), identifies the two.',
  { img: 'ive-upanishad-ms', leg: 'Manuscript of an Upanishad in Devanagari script (a much later copy; the text was transmitted orally).' },
  { img: 'ive-upanishad-dialogo', leg: 'Artist’s reconstruction: a teacher and pupils in a forest clearing, in debate, c. 7th century BC.' },
  { h: 'Samsara, karma and liberation' },
  'The first Upanishads (*Brihadaranyaka*, *Chandogya*, c. 8th – 6th centuries BC, dating debated) fix ideas that will run through all Indian history: a living being is reborn (*samsara*) according to its deeds (*karma*), and liberation (*moksha*) is to know the unity of *atman* and *Brahman*. The texts say that some of these doctrines, such as that of the five fires, were taught by kings (kshatriyas) to Brahmins, which shows the mixing of classes in the debate. The debates at the court of **Janaka**, in Videha, between **Yajnavalkya** and others, including the sage **Gargi**, are the most famous example.',
  { h: 'The revolution of the *shramanas*' },
  'In the 6th – 5th centuries BC, around the cities of the Ganges, **wandering** teachers appeared (*shramanas*, “those who strive”), who rejected the authority of the Vedas and the Brahmins and proposed paths of liberation for all. A Buddhist text (the *Samannaphala Sutta*) lists six: Purana Kassapa, Makkhali Gosala (the **Ajivikas**, fatalists), Ajita Kesakambali (a materialist), Pakudha Kaccayana, Sanjaya Belatthiputta (a sceptic) and Nigantha Nataputta (Mahavira). It was a time of **free debate**, in parks and groves near the cities, patronised by kings and bankers.',
  { img: 'ive-shramanas-debate', leg: 'Artist’s reconstruction: ascetics and rival teachers debating in a park beside a Ganges city, 5th century BC.' },
  { h: 'The Buddha' },
  'Siddhartha Gautama, of the Shakya clan, was born at Lumbini, at the foot of the Himalaya, the son of a chief. At 29 (according to tradition) he left noble life, sought teachers and ascetic practices, and attained enlightenment at Bodh Gaya. He preached his first sermon at Sarnath, taught for about 45 years and died at Kushinagar. His teaching sets out the **Four Noble Truths** (suffering, its cause, its cessation, the path) and the **Eightfold Path**, a “middle way” between luxury and mortification. He rejected animal sacrifice and the importance of birth. What he taught was preserved orally by the community (*sangha*) and written down, in Pali, only in Sri Lanka, in the 1st century BC; it is hard to separate with certainty what is the master’s and what is tradition’s.',
  { h: 'Mahavira and Jainism' },
  'Jain tradition sees **Mahavira** as the 24th *tirthankara*, after Parshvanatha (whom some historians consider a historical figure of c. the 8th – 6th century BC; Jain tradition gives him much earlier dates). He teaches **radical non-violence** (*ahimsa*): every living being has a soul (*jiva*), and ascetics sweep the path so as not to tread on insects; detachment and discipline free the soul from *karma*, conceived almost as a substance. Jainism enjoyed great support from merchants. The texts (*Agamas*) were fixed in writing only in the 5th century AD.',
  { h: 'Other currents' },
  'The **Ajivikas** of Makkhali Gosala held a strict determinism (everything is fixed from the start). The **materialists** (*Lokayata*, *Charvaka*) denied the afterlife and *karma*. The sceptics denied that anything could be known. Much of what we know of these schools comes from their opponents, because they left almost no texts. The Greek world knew these ascetics: Alexander’s historians speak of **gymnosophists** (naked sages) at Taxila; one of them, **Calanus**, followed the king and died on a pyre in Persia (324 BC).',
  { h: '3. Varna and jati' },
  'Already in the Rigveda there is the hymn of the **Purusha** (10.90), a late one, which says that the four **varnas** were born from the limbs of the primordial man: Brahmins (priests), *rajanya* or kshatriyas (warriors and rulers), vaishyas (producers and traders) and shudras (servants). The oldest legal texts, the *Dharmasutras* (c. 6th – 3rd centuries BC), define the duties of each group. In practice, social life was organised by smaller and more varied hereditary groups, the *jatis*.',
  { caixa: 'With care', texto: [
    'The texts on varna are **normative**: they say how the Brahmins thought society should be, not how it was. Buddhist texts, which give the opposite perspective, show a society in which kshatriyas were regarded as the highest class and in which merchants and bankers (*setthis*) were powerful. Historians debate how much social mobility was possible and how far the caste system known today was hardened later.',
    'The **Buddha** and **Mahavira** rejected the idea that birth decides a person’s worth, and admitted people of all varnas into their communities; but Buddhism did not abolish social distinctions in everyday life. Outside the scheme lived groups regarded as “impure”, such as the *chandalas*, of whom the texts speak with contempt.'
  ] },
  { h: '4. Women' },
  'The hymns of the Rigveda attribute compositions to women poets (*rishikas*), such as **Lopamudra**, **Ghosha** and **Apala**; the Upanishads show **Gargi** challenging Yajnavalkya in public and **Maitreyi** asking him for knowledge instead of goods. Later legal texts limit women’s independence, as they depended on father, husband and son. Upper-class widows had little autonomy, and ritual widow-burning (*sati*) is attested only much later.',
  'According to Buddhist tradition, the Buddha, after hesitating, accepted the order of **nuns** (*bhikkhunis*), with his aunt and stepmother, **Mahaprajapati Gotami**, at their head; the poems attributed to the nuns (*Therigatha*) are among the oldest texts of female authorship. The courtesan **Amrapali** of Vaishali, rich and a patron of the Buddha, is a figure of tradition, with a possible historical basis.',
  { h: '5. Economy' },
  'The base was **herding** (cattle were the measure of wealth: in the Rigveda conflicts revolve around cows) and, increasingly, **farming**. In the Ganges people grew **rice**, barley and wheat, lentils and sugar cane; the ox-drawn plough and iron tools allowed the forests to be cleared. There were herders, ploughmen, potters, weavers, carpenters and smiths, and villages that paid tribute to the king, the priest and the chief.',
  'The “second urbanisation” brought **merchants** (*setthi*) and **guilds** (*shreni*), organised by trade, who financed kings and monasteries. The banker **Anathapindika** (of Buddhist tradition) is the paradigm. Weights and **silver punch-marked coins** (*karshapana*, of about 3.4 g of silver, 32 *ratis*) appeared, along with credit and interest. Trade ran from the ports of the Ganges to the fairs of the Indus, and brought salt, copper, horses from the north-west, textiles from Varanasi, pearls and ivory.',
  { img: 'ive-mercado-punch', leg: 'Artist’s reconstruction: moneychangers weighing and checking punch-marked silver coins in a Ganges market, 5th century BC.' },
  { h: 'Slavery and dependent labour' },
  'There were **domestic slaves** (*dasa*, *dasi*), born in the house, bought, captured in war or held for debt, and wage workers. Buddhist texts forbid lay followers to trade in human beings, but the practice continued. It was not a slave-based economy like Rome’s: the main labour force was free farmers and dependants.',
  { h: '6. Writing and languages' },
  'Throughout this period literature was **oral**. The Vedas were memorised with extraordinary recitation techniques (word by word, interlaced, in reverse order), which guaranteed the fixity of the text. When did writing appear? The Indus civilisation (extinct c. 1900 BC) had writing, but its use was lost. **Brahmi**, from which almost all Indian and South-East Asian scripts descend, is firmly attested only in the 3rd century BC (Ashoka’s edicts); its origin (indigenous or inspired by Semitic scripts) is debated, and there are potsherds from Anuradhapura (Sri Lanka) that some date to c. 400 BC, but the dating is disputed. **Kharosthi**, of the north-west, derives from the Aramaic of Persian administration.',
  'The languages were **Vedic Sanskrit**, the “refined” Sanskrit fixed by Panini, the spoken **Prakrits** (and *Pali*, the language of the Buddhist texts) and, in the south, proto-Tamil. The word for “writing”, *lipi*, perhaps derives from Old Persian *dipi* (a debated hypothesis).',
  { h: 'Panini and grammar' },
  'The *Ashtadhyayi* of **Panini** (“eight chapters”) has about 4000 very concise rules, with auxiliary symbols and a system of definitions that generates the words of Sanskrit. It is regarded as the precursor of formal grammars, and was compared, in the twentieth century, to the notation used in programming languages. Panini did not invent grammar (he cites predecessors), but gave it definitive form; thanks to his rigour, Sanskrit remained almost stable for two millennia. The vocabulary reflects a society of villages, rivers, oxen, rice, coins and trades.',
  { img: 'ive-ashtadhyayi-ms', leg: 'Manuscript of Panini’s *Ashtadhyayi* (a late copy).' },
  { img: 'ive-panini-sutras', leg: 'Artist’s reconstruction: a grammarian and his pupils reciting rules from memory, in north-western India, 4th century BC.' },
  { h: '7. Village, house and family' },
  'The village (*grama*) was the core of life: houses of reed, wood, clay and thatch, some round, with a central domestic fire, and cattle pens. In the cities there were brick houses, streets, drains and walls. The family was **patrilineal and extended**: the father (*grihapati*, “lord of the house”) kept the domestic fire, lit daily with offerings, and ceremonies (*samskaras*) marked birth, initiation (*upanayana*), marriage and death. Marriage was generally arranged, but the old texts also know free choice (*svayamvara*), above all in the epics.',
  'The texts distinguish four **stages of life** (*ashramas*) for upper-class men: student, householder, hermit and renouncer. The complete scheme only formed later, but the idea of leaving home to seek liberation is already in the Upanishads and in the *shramana* movements.',
  { h: '8. Food' },
  'People ate **barley** and **wheat** (as bread or porridge), **rice** (increasingly, in the east), lentils, vegetables, fruit, **milk**, curd, **ghee** and honey. Meat (of cattle, goats, sheep, deer) was eaten at sacrifices and feasts; the idea of non-violence among Buddhists and Jains and the economic value of cattle gradually led to restrictions on meat-eating, but the process was slow and contested. Salt and pepper, ginger and turmeric flavoured food; *soma* was drunk in rituals, and *sura*, a fermented drink, at home.',
  { h: '9. Clothing and ornaments' },
  'People wore **wool**, **linen** and, increasingly, **cotton**: Herodotus related, with astonishment, that in India there were trees whose “wool” was better than that of sheep. Dress was wrapped and draped cloth: a lower garment (*vasas*, later *dhoti*) and a shawl (*uttariya*). Brahmins wore a sacred thread; ascetics, a loincloth or nudity, and Buddhist monks, robes of rags dyed with ochre. Hair was worn in many ways, with braids and knots. Jewellery was of gold, carnelian, agate, shell and glass beads.',
  { h: '10. Music, games and entertainment' },
  'The Samaveda is a book of **melodies** (*saman*), the oldest of India. There was the **vina** (harp or lute), flutes, drums (*dundubhi*), cymbals and conch shells. The Rigveda contains the famous **“gambler’s lament”** (10.34), in which a dice addict describes the ruin caused by gambling, and the Mahabharata revolves around a game of dice. **Chariot races**, hunting, wrestling, singing and dancing, festivals and fairs (*samaja*), mentioned in the Buddhist texts, were popular.',
  { h: '11. Education' },
  'Vedic education was **oral and personal**: the upper-class boy, after initiation (*upanayana*), lived in the teacher’s house (*guru*), served him, and memorised the texts by hearing and repeating them. Brahmins studied the Vedas and the six “limbs” (*vedangas*): pronunciation, metre, grammar, etymology, astronomy and ritual. Kshatriyas learned warfare. In the cities, teachers also taught crafts and arts. Later Buddhist texts describe **Taxila** as the place where princes and youths from all over India studied medicine, warfare and the arts, and say that Bimbisara’s physician **Jivaka** studied there; it is tradition, but it points to the city’s fame.',
  { img: 'ive-escola-oral', leg: 'Artist’s reconstruction: a teacher and pupils seated under a tree, reciting a Vedic text from memory.' },
  { h: '12. Mathematics, astronomy and medicine' },
  'Ritual required **geometry**: in the *Shulbasutras* (c. 800 – 500 BC, dating debated), manuals for building altars, there appears the rule linking the diagonal of a rectangle to its sides (what we now call the “Pythagorean theorem”) and an approximation of √2 correct to five decimal places (the work of Baudhayana). The Vedas use numbers up to 10¹² and give names to powers of ten. The lunisolar calendar, with 27 lunar mansions (*nakshatras*), is described in the *Vedanga Jyotisha*, a text of much-disputed date (from c. 1400 BC, on the earliest astronomical estimates, to the last centuries BC).',
  'Vedic medicine combined spells and plants: the *Atharvaveda* has formulas against fevers and wounds. Later, tradition points to teachers such as **Atreya** (credited with internal medicine) and the physician **Jivaka**, of Rajagriha, of whom the Buddhist texts tell of cures and surgeries, partly legendary.',
  { h: '13. Technology' },
  'The decisive advance was **iron**, at first for weapons and spearheads, then for axes, sickles and ploughshares, which allowed the humid forests of the Ganges to be cultivated. Pottery passed from **painted grey** (c. 1200 – 600 BC) to luxury **northern black polished ware** (*NBPW*, c. 700 – 200 BC), with an almost metallic sheen. People built ramparts of earth, brick and timber, moats, river boats and spoke-wheeled chariots. Cotton weaving and the metallurgy of copper and gold produced fine crafts.',
  { h: '14. Warfare' },
  'The Vedic hymns extol the **war chariot** drawn by horses, the bow, the spear and the axe; warriors were clan chiefs, with retinues. The Mahajanapadas developed armies of infantry, cavalry, chariots and **war elephants**, greatly prized in Magadha. Jain texts describe Ajatashatru’s machines against the Vajjis, a catapult that hurls stones and a chariot with rotating maces (an account hard to confirm). Alexander’s historians recorded Porus’s elephants and the tenacity of the Assakenoi and the Malli; Greek sources give the Nanda forces as enormous (200,000 infantry and thousands of elephants), figures surely exaggerated.'
];

const personalidades = [
  'For almost every name on this page, the biography is a mixture of fact, religious tradition and legend. Dates are flagged as uncertain where they are, and some figures (the teachers of the Upanishads) are known only from the texts that cite them.',
  { h: 'Yajnavalkya (c. 8th – 7th centuries BC, tradition)' },
  'The great teacher of the *Brihadaranyaka Upanishad*, at the court of Janaka in Videha. He teaches that the *atman* cannot be grasped by any description (“not this, not this”, *neti neti*) and debates with sages and with the sage Gargi. He is a figure at the dawn of Indian philosophical thought; nothing certain is known of his life.',
  { h: 'Janaka of Videha (tradition)' },
  'King of Videha, in the east, described in the texts as a patron of sages and himself a scholar, he is the model of the “philosopher-king” of Indian tradition. It is hard to say whether he was one king or several, since “Janaka” was a family title.',
  { h: 'Gargi Vachaknavi (7th century BC, tradition)' },
  'A sage of the Upanishads, who in the *Brihadaranyaka* challenges Yajnavalkya with questions about the origin of the world, until he warns her that her questions exceed the limit of knowledge. She shows that women took part in philosophical debate.',
  { h: 'Siddhartha Gautama, the Buddha (c. 563 – 483 BC or c. 480 – 400 BC)' },
  'The founder of Buddhism, of the Shakya clan. He left the palace, taught a path of liberation from suffering and founded a community of monks and nuns. He left nothing written. Depiction in human form appears only centuries later; before that, he was suggested by symbols (the wheel, the tree of Bodh Gaya, the footprints).',
  { h: 'Vardhamana Mahavira (c. 599 – 527 BC or about a century later)' },
  'The teacher of Jainism, born near Vaishali into a kshatriya family. At 30 he left home, spent years in rigorous asceticism and taught for about 30 years. He died at Pava. His teaching centred on non-violence and detachment.',
  { img: 'ive-mahavira-jaina', leg: 'Image of Mahavira, Jain sculpture of much later date: no portraits of the teacher exist.' },
  { h: 'Bimbisara (c. 544 – 492 BC, tradition)' },
  'King of Magadha who made Rajagriha a great capital and annexed Anga. He married princesses of Kosala, the Licchavis and the Madras, and was, according to Buddhist tradition, the first royal protector of the Buddha. Tradition says he was imprisoned and starved to death by his son, Ajatashatru, although the Jain and Buddhist versions differ.',
  { h: 'Ajatashatru (c. 492 – 460 BC, tradition)' },
  'Son of Bimbisara, king of Magadha for about 32 years. He made war on Kosala and destroyed the republic of the Vajjis. Buddhist texts say that, after killing his father, he repented and became a follower of the Buddha; the Jains claim him too. His war machines and fortifications made Magadha the greatest power of the north.',
  { img: 'ive-ajatashatru-bharhut', leg: 'Bharhut relief (c. 2nd century BC) representing Ajatashatru venerating the Buddha, who appears only as a symbol.' },
  { h: 'Panini (c. 6th – 4th centuries BC, debated)' },
  'The author of the *Ashtadhyayi*, born at Shalatura in Gandhara. Little is known of his life; tradition speaks of a tragic end, but that is legend. The work proves that at the time the north-west (then under Persian rule) was a great centre of learning.',
  { h: 'Darius I (c. 550 – 486 BC)' },
  'King of Persia who annexed Gandhara and the Indus to the empire and organised the administration of the satrapies. His inscriptions mention Hindush; his tomb and the reliefs of Persepolis show the peoples of the empire, among them the Indians. He sent Scylax to explore the Indus, c. 515 BC.',
  { h: 'Scylax of Caryanda (6th century BC)' },
  'The Greek explorer in Darius’s service. According to Herodotus, he went down the Indus, then sailed to the Red Sea in about thirty months. His work is lost; few fragments survive, and the travel account attributed to him (the *Periplus of Scylax*) is of later date.',
  { h: 'Dhana Nanda (reigned until c. 321 BC)' },
  'The last king of the Nandas, a contemporary of Alexander, is described in Indian and Greek sources as powerful, unpopular and extremely rich, with an enormous army; the Greeks call him “Agrammes” or “Xandrames”. He was overthrown by Chandragupta Maurya, c. 321 BC. The figure, linked to the rivalry with Chanakya, appears in a late legend.',
  { h: 'Ambhi of Taxila (4th century BC)' },
  'The king of Taxila (Omphis in Greek sources) who, instead of resisting, received Alexander with gifts, elephants and troops, allied with him against his rival Porus, and kept his kingdom. The attitude is debated: for some, betrayal; for others, political realism.',
  { h: 'Porus (4th century BC)' },
  'King of the Pauravas, between the Hydaspes and the Acesines. Defeated by Alexander in 326 BC after a hard battle, he stayed on to govern the kingdom as an ally. According to Arrian and Plutarch, when asked how he wished to be treated, he replied: “like a king” (an anecdote of the Greek historians). He is said to have been killed c. 317 BC by Eudemus, one of the governors Alexander left.',
  { img: 'ive-poro-decadracma', leg: 'Silver decadrachm of Alexander with elephants and a horseman, traditionally linked to the victory over Porus (interpretation debated).' },
  { h: 'Alexander the Great (356 – 323 BC)' },
  'The king of Macedon who conquered the Persian Empire and reached the Punjab. His time in India lasted less than two years, but his campaigns opened contact between India and the Mediterranean and supplied the first detailed Greek accounts of the country. He turned back at the Hyphasis, and died in Babylon, aged 32.',
  { img: 'ive-alexandre-herma', leg: 'The Azara Herm (Roman copy of a portrait of Alexander attributed to Lysippos), Louvre.' },
  { h: 'Jivaka Komarabhacca (6th – 5th centuries BC, tradition)' },
  'The most famous physician of Buddhist tradition, linked to the court of Bimbisara and to the care of the Buddha and the monks. Tradition says he studied at Taxila and performed operations on the brain and intestine; the accounts mix history with pious legend.'
];

const legado = [
  { h: 'Language and literature' },
  { lista: [
    '**Sanskrit and Panini’s grammar:** the basis of all linguistics; the study of Sanskrit (William Jones, 1786) revealed the Indo-European family. Panini’s grammar is still studied and compared with modern formal languages.',
    '**The Vedas and the oral tradition:** the Rigveda, transmitted by memory for more than three thousand years, is among the oldest living religious texts in the world; Vedic chanting is Intangible Cultural Heritage of Humanity (UNESCO).',
    '**The Upanishads:** became the foundation of much of Indian philosophy (Vedanta). They were translated into Persian (Dara Shikoh, 1657), then into Latin (Anquetil-Duperron, 1801 – 1802), and fascinated Schopenhauer.'
  ] },
  { h: 'Religion and ideas' },
  { lista: [
    '**Buddhism:** born in the middle Ganges, it is today a world religion; the *sangha*, the concept of the “middle way” and the idea of compassion are a legacy of this period.',
    '**Jainism and *ahimsa*:** Jain non-violence influenced Mahatma Gandhi, more than two thousand years later.',
    '**Dharma, karma, samsara, moksha:** concepts formed in this period and shared by Hinduism, Buddhism and Jainism.'
  ] },
  { h: 'Politics and economy' },
  { lista: [
    '**The assembly republics:** proof that northern India experimented with collegial forms of government long before the Mauryas.',
    '**Coinage and guilds:** the silver money economy and the organisation of merchants and craftsmen, which will sustain the later empires.'
  ] },
  { h: 'Cities and the outside world' },
  { lista: [
    '**The cities of the Ganges:** Varanasi, Rajgir, Vaishali, Kaushambi and Pataliputra still exist or lie beneath modern cities.',
    '**The encounter with Persia:** the Kharosthi script, administrative Aramaic and, perhaps, the idea of an imperial administration (which the Mauryas will take up).',
    '**The encounter with Greece:** the first direct contact with the Mediterranean, which opens the way to the Indo-Greek kingdoms and the art of Gandhara.',
    '**The name “India”:** from the *Sindhu* (Indus), via Persian *Hindush* and Greek *India*; “Hindu” has the same origin.'
  ] },
  { h: 'Rediscovery' },
  'The modern study of this period began in the late eighteenth century, with **William Jones** and the Asiatic Society of Calcutta (1784), and **Henry Colebrooke**, who published an essay on the Vedas in 1805. **Max Müller** edited the Rigveda with Sayana’s commentary between 1849 and 1874. Archaeology followed with **Alexander Cunningham** (Archaeological Survey of India, 1861), **John Marshall** (Taxila, 1913 – 1934) and **B. B. Lal** (Hastinapura, 1950s). Painted Grey Ware and polished black ware made it possible, in the twentieth century, to date archaeological levels and link them, with caution, to the texts.',
  { h: 'Where to visit' },
  { lista: [
    '**Rajgir and Nalanda (Bihar):** cyclopean walls, the bamboo grove and the hills linked to the Buddha and Mahavira.',
    '**Vaishali (Bihar):** Ashoka’s pillar and ruins of the city of the Licchavis.',
    '**Lumbini (Nepal, UNESCO), Bodh Gaya (Bihar, UNESCO), Sarnath and Kushinagar (Uttar Pradesh):** the four places of the Buddha.',
    '**Varanasi and Rajghat:** the *ghats* of the Ganges and the oldest archaeological site.',
    '**Taxila (Pakistan, UNESCO):** the Bhir Mound, the monasteries and the Taxila Museum.',
    '**Patna Museum, National Museum Delhi, Indian Museum (Kolkata):** punch-marked coins, pottery, Bharhut reliefs.',
    '**British Museum (London):** coins of Alexander, of Darius and of the Persian world.',
    '**Louvre Museum (Paris):** the Azara Herm (Alexander) and Achaemenid pieces.',
    '**Persepolis and Naqsh-e Rustam (Iran):** the reliefs with the “Indian” envoys and the tomb of Darius.'
  ] }
];

const quiz = [
  { p: 'Which is the oldest text of the Vedic tradition, composed in Vedic Sanskrit?', op: ['Mahabharata', 'Rigveda', 'Arthashastra', 'Ramayana'], certa: 1, exp: 'The Rigveda, with about a thousand hymns, was composed in north-western India (c. 1500 – 1000 BC, dating debated).' },
  { p: 'What does the word “Upanishad” mean, according to the most common explanation?', op: ['Great king', 'Sitting near the teacher', 'Horse sacrifice', 'Sacred book'], certa: 1, exp: 'It comes from *upa-ni-shad*, “sitting near the teacher”: teaching handed on at close quarters.' },
  { p: 'What do we call the “second urbanisation” in the history of India?', op: ['The founding of Pataliputra', 'The reappearance of cities in the Ganges from c. 700 – 600 BC', 'The Persian conquest', 'The building of stupas'], certa: 1, exp: 'The first was that of the Indus valley, over a thousand years earlier.' },
  { p: 'How many Mahajanapadas are there in the Buddhist lists?', op: ['Eight', 'Twelve', 'Sixteen', 'Twenty-four'], certa: 2, exp: 'Sixteen in the *Anguttara Nikaya* list, though other texts give different lists.' },
  { p: 'Which of these Mahajanapadas was a confederation governed by assemblies, with its capital at Vaishali?', op: ['Magadha', 'Avanti', 'Vajji', 'Gandhara'], certa: 2, exp: 'The Vajjis (with the Licchavis) were destroyed by Ajatashatru of Magadha.' },
  { p: 'Which successive capitals of Magadha are most often cited by tradition?', op: ['Rajagriha and then Pataliputra', 'Taxila and Ujjain', 'Mathura and Varanasi', 'Kaushambi and Shravasti'], certa: 0, exp: 'Rajagriha (Rajgir) was the first capital; Pataliputra (Patna) became the capital under Udayin, according to tradition.' },
  { p: 'Why is it so hard to date the Buddha?', op: ['Because he never existed', 'Because there are no contemporary chronicles, and traditions give different chronologies', 'Because the dates were erased by the Persians', 'Because he lived in two eras'], certa: 1, exp: 'There is a long chronology (death c. 483 BC) and a short one (c. 400 BC), both debated.' },
  { p: 'Who was Mahavira?', op: ['The founder of Buddhism', 'The last of the 24 tirthankaras of Jainism', 'A king of Magadha', 'A grammarian'], certa: 1, exp: 'A contemporary of the Buddha, he taught absolute non-violence (*ahimsa*).' },
  { p: 'Which north-western Indian script derives from the Aramaic of Persian administration?', op: ['Brahmi', 'Devanagari', 'Kharosthi', 'Tamil'], certa: 2, exp: 'Kharosthi, written right to left, was born of contact with the Achaemenid Empire.' },
  { p: 'Which Persian king annexed Gandhara and Hindush (the Indus) to the empire?', op: ['Cyrus', 'Darius I', 'Xerxes', 'Darius III'], certa: 1, exp: 'Darius I (c. 520 – 510 BC) listed them among his provinces; Cyrus may already have dominated Gandhara.' },
  { p: 'According to Herodotus, what was the tribute of the Indian satrapy to the Persian king?', op: ['Elephants', 'Gold dust', 'Spices', 'Silk fabrics'], certa: 1, exp: 'Herodotus speaks of 360 talents of gold dust a year.' },
  { p: 'Who wrote the *Ashtadhyayi*, a grammar of Sanskrit with about 4000 rules?', op: ['Kalidasa', 'Panini', 'Yajnavalkya', 'Chanakya'], certa: 1, exp: 'Panini, of Shalatura in Gandhara (c. 6th – 4th centuries BC, debated).' },
  { p: 'Which king did Alexander fight at the battle of the Hydaspes (326 BC)?', op: ['Ambhi', 'Dhana Nanda', 'Porus', 'Bimbisara'], certa: 2, exp: 'Porus was defeated, but confirmed as king and ally.' },
  { p: 'Why did Alexander turn back at the Hyphasis (Beas)?', op: ['He was mortally wounded', 'His army refused to advance', 'The Nandas sued for peace', 'He lost his horse Bucephalus'], certa: 1, exp: 'Exhausted and frightened by news of the huge Nanda army, the army refused to go on.' },
  { p: 'Which was the last dynasty to rule Magadha before the Mauryas?', op: ['The Guptas', 'The Nandas', 'The Kushans', 'The Shungas'], certa: 1, exp: 'The Nandas were overthrown by Chandragupta Maurya, c. 321 BC.' }
];

export default { visao, linha, mapa, sociedade, personalidades, legado, quiz };
