// THE CELTS — full English content. Same structure and same image slots as the Portuguese version (dados.js).
// “Celtic” is used with care: language vs. archaeological culture vs. identity. See “What does ‘Celtic’ mean?” (overview) and “Did the Celts exist? A debate” (legacy).
// Dates are approximate (middle chronology); “c.” and “debated” flag uncertainty. BC/AD.

const visao = [
  { caixa: 'In brief', texto: [
    'The **Celts** were a group of peoples of Iron Age Europe, linked by related languages (the **Celtic languages**) and, in part, by a shared material culture and art. They never formed an empire or a state: they were dozens of independent tribes, sometimes allied, often at war with one another. Between **c. 800 BC** and the 1st–5th centuries AD we find them from Ireland and the Iberian Peninsula to Bohemia, the Po valley and the centre of present-day Turkey.',
    'Their archaeological “core” is central Europe, where the **Hallstatt culture** (c. 800 – 450 BC), that of the first iron-using elites, and the **La Tène culture** (c. 450 – 1st century BC), that of curving art and great fortified settlements, developed. From there the Celts expanded: they took northern Italy, sacked Rome (c. 390 BC), attacked Delphi (279 BC) and founded **Galatia** in Anatolia. Rome gradually subdued them, from Italy to Gaul (58–50 BC) and Britain (from AD 43). But Ireland was never conquered, and in the islands and in Brittany languages and traditions survived: **six Celtic languages** are still spoken today.'
  ] },
  { img: 'cel-mapa-expansao', leg: 'Interpretive map of Celtic expansion, from the central European core to its greatest extent in the 3rd century BC.' },
  { caixa: 'A warning: “Celtic” is not a simple word', texto: [
    'Almost everything said about the Celts depends on the meaning given to the word, and the discussion among specialists is lively. Three uses should be distinguished:',
    '**1. Linguistic (the firmest).** The Celts are the speakers of languages of the Celtic family, a branch of Indo-European. This is a proven fact, based on inscriptions and texts: Gaulish, Celtiberian, Old Irish and Old Welsh belong to the same family.',
    '**2. Archaeological and artistic.** “Celtic” is used for the material culture of Hallstatt and La Tène, and for “Celtic art” of spirals and interlace. But a material culture is not a people, nor a language.',
    '**3. Identity (the most controversial).** The ancient Greeks called them **Keltoi** and **Galatai** and the Romans **Galli**; Julius Caesar says the Gauls called themselves “Celts”. But no ancient author calls the inhabitants of Britain or Ireland “Celts”, and it is doubtful that the peoples of Hallstatt, Gaul, Ireland and Galatia felt themselves to be one people. The idea of a “Celtic nation” is largely a construction of the 18th and 19th centuries. On this page “Celtic” is used mainly in senses 1 and 2, and we say so when we move to another.'
  ] },
  { h: 'Where they lived' },
  'There was no continuous Celtic territory; there were **areas** where Celtic languages were spoken and where a Hallstatt- or La Tène-type material culture is found, and these changed greatly over eight centuries.',
  { lista: [
    '**Central Europe (the core):** Austria, southern Germany, Bohemia, Switzerland and eastern France, where Hallstatt, La Tène and the “princely seats” of the early Iron Age are found.',
    '**Gaul:** present-day France, Belgium and parts of Switzerland and western Germany, with dozens of tribes (the Aedui, the Arverni, the Helvetii, the Belgae and many others).',
    '**The British Isles:** Britain (the “Brittonic” tribes) and Ireland (of “Goidelic” language). Here the use of the label “Celtic” is the most disputed.',
    '**The Iberian Peninsula:** the Celtiberians in the centre (Numantia, Botorrita) and populations in the north and west, including present-day Portugal, whose language and Celtic affiliation are debated (see the map and legacy sections).',
    '**Northern Italy:** Cisalpine Gaul, occupied by the Boii, Insubres, Senones and others from c. 400 BC.',
    '**The Danube and the Balkans:** the Boii in Bohemia (which takes its name from them), the Scordisci, and those who invaded Greece in 279 BC.',
    '**Anatolia:** **Galatia**, in the centre of modern Turkey, where three Celtic tribes settled in 278–277 BC and remained for centuries.'
  ] },
  { img: 'cel-hallstatt-vista', leg: 'Hallstatt, on the Hallstätter See (Austria); the cemetery and the salt mines lie on the slopes above the village.' },
  { h: 'When they existed' },
  'The dates are approximate and, for the earliest phases, debated. The main phases follow.',
  { tabela: { cab: ['Phase', 'Approximate dates', 'What marks it'], linhas: [
    ['Background', 'c. 1300 – 800 BC', 'Late Bronze Age: the Urnfield culture in central Europe and the “Atlantic” Bronze Age; the roots of the Celtic languages are debated'],
    ['Hallstatt', 'c. 800 – 450 BC', 'Early Iron Age; salt mines; graves with wagons and “princely seats” (Heuneburg, Vix, Hochdorf); trade with Greeks and Etruscans'],
    ['La Tène', 'c. 450 BC – 1st century BC', 'Curvilinear art; warriors with long swords; migrations to Italy, the Balkans and Anatolia; later, great fortified settlements (oppida) and coinage'],
    ['Roman conquest', '222 BC – 1st century AD', 'Cisalpine Gaul (3rd–2nd centuries BC); the Iberian Peninsula (3rd–1st centuries BC); Gaul (58–50 BC); Galatia (25 BC); Britain (from AD 43)'],
    ['Gallo-Roman and Romano-British world', '1st – 5th centuries AD', 'Roman cities and Latin, but continuity of names, cults and local languages; Gaulish probably disappears between the 5th and 7th centuries (debated)'],
    ['Insular survival', '5th century AD onwards', 'Ireland (never Roman), Scotland, Wales, Cornwall and Brittany keep Celtic languages and literatures, now Christian']
  ] } },
  { img: 'cel-torque-snettisham', leg: 'The Snettisham Great Torc (Norfolk), of a gold and silver alloy, c. 1st century BC, British Museum.' },
  { h: 'Who were they and where did they come from?' },
  'When and where the “Celtic language” was born is debated. The oldest explanation, from the 19th and 20th centuries, looked for the Celts’ “homeland” in central Europe (Hallstatt), from which they would have left in waves of migration. In recent decades, **John Koch** and **Barry Cunliffe** have defended the “Celtic from the West” theory: Celtic languages would have arisen along the Atlantic seaboard in the Bronze Age and spread from there eastwards; they rely above all on inscriptions from the south-west of the Iberian Peninsula (the so-called “Tartessian” language), but many specialists doubt that these inscriptions are Celtic. Others, such as **Simon James** and **John Collis**, stress that the populations of the islands were very different from those of the continent and that the term “Celtic” does not suit them.',
  'What can be said with certainty is little, but firm: the Celtic family is a branch of Indo-European; there were Celtic languages on the continent (Gaulish, Celtiberian, Lepontic) as early as the 6th century BC and later in the islands; and the first Greek sources speak of **Keltoi** in the interior of western Europe around 500 BC. Ancient DNA shows that there were large migrations into Britain in the Bronze Age (a 2022 study speaks of arrivals between c. 1300 and 800 BC), but DNA does not tell us what language was spoken: a person’s ancestry is one thing, the language of their mother another.',
  { h: 'Why they matter' },
  { lista: [
    '**The first “barbarian” Europe that we know from the inside:** they left very rich graves, fortified towns, works of art and hundreds of inscriptions, not only the often hostile portrait given by Greeks and Romans.',
    '**Art:** La Tène art, with its curves, spirals and faces hidden in patterns, is one of the great artistic traditions of ancient Europe, and it influenced the manuscripts and crosses of Ireland.',
    '**Iron engineering:** the Celts were great smiths, with swords, chain mail, ploughs, wheels with iron tyres and very sophisticated wagons.',
    '**The clash with Rome:** from Brennus to Vercingetorix and Boudica, the confrontation with Rome was one of the great dramas of antiquity and shaped western Europe.',
    '**The languages:** Irish, Welsh, Breton and Scottish Gaelic show a linguistic continuity of more than two thousand years.',
    '**The history of an idea:** how the “Celts” were invented and reinvented (by the ancients, by 18th- and 19th-century scholars, by nationalists and by popular culture) is a good example of how we read the past.'
  ] },
  { caixa: 'Not Celtic (common confusions)', texto: [
    '**Stonehenge, Newgrange and the dolmens** are much older than the Celts (Stonehenge reached its main form around 2500 BC). **The druids did not build Stonehenge**, and the popular link between the two is an invention of the 17th and 18th centuries. **The Vikings** were Scandinavians, of Germanic language, like the **Anglo-Saxons**. And the **Picts** of north-eastern Scotland are an open case: their language is debated and only part of what they wrote is known.'
  ] },
  { img: 'cel-stonehenge', leg: 'Stonehenge (England), in its main form around 2500 BC: much older than the Iron Age Celts.' },
  { img: 'cel-mapa-linguas', leg: 'Schematic map of the Hallstatt and La Tène heartlands and Celtic expansion, c. 800–50 BC.' },
  { img: 'cel-espada-hallstatt', leg: 'Hallstatt C iron swords, 7th–6th century BC, in the Wels Museum (Upper Austria).' },
  { caixa: 'The Celts today', texto: 'Six Celtic languages are still spoken: **Irish**, **Scottish Gaelic** and **Manx** (the “Goidelic” branch), and **Welsh**, **Cornish** and **Breton** (the “Brittonic” branch). Welsh is the most vigorous (about half a million speakers) and the one in the best position (UNESCO classifies it only as “vulnerable”). Manx lost its last native speaker in 1974 and Cornish ceased to be a mother tongue in the 18th or early 19th century, but both have been revitalized. The modern “Celtic nations” are Ireland, Scotland, Wales, Cornwall, the Isle of Man and Brittany; Galicia and Asturias claim a cultural Celtic heritage but no longer speak any Celtic language. In Portugal, the legacy is mainly archaeological and in place names (see the legacy section).' }
];

const linha = [
  'The timeline follows what archaeologists and ancient sources tell us about the Celts, from Hallstatt to the Middle Ages. Remember that almost everything we know in writing about the continental Celts was written by **Greeks and Romans**, who were rivals or enemies: it is a view from outside. The dates are approximate.',
  { linha: [
    { d: 'c. 1300 – 800 BC', t: 'Background: Urnfields and the Atlantic Bronze Age', x: 'In central Europe, the **Urnfield** culture (the dead are cremated and the ashes kept in urns) and, along the Atlantic coast, a network of bronze exchange link very distant regions. Where and when a “Proto-Celtic” language was first spoken is debated: some look for it here, others further west.' },
    { d: 'c. 800 BC', t: 'Hallstatt begins', x: 'With the spread of **iron**, the **Hallstatt** culture (named after an Austrian village) appears. The salt miners of Hallstatt, in Austria, grow rich; chiefs are buried with swords, four-wheeled wagons and fine bronze vessels. The cemetery was excavated from **1846** by **Johann Georg Ramsauer**, who opened about a thousand graves.' },
  ] },
  { img: 'cel-mineiros-sal', leg: 'Salt miners at Hallstatt, c. 600 BC; conjectural reconstruction. AI-generated illustration.' },
  { img: 'cel-hochdorf-kline', leg: 'The burial chamber of the Hochdorf “prince”, c. 530 BC, in an imagined reconstruction: the dead man on the bronze couch, with the cauldron, drinking horns and four-wheeled wagon. AI-generated illustration.' },
  { linha: [
    { d: '6th century BC', t: 'The first Celtic inscriptions', x: 'The oldest known writing in a Celtic language is **Lepontic**, written in an alphabet of Etruscan origin in northern Italy (the lakes region, around Lugano and Como), from the 6th century BC. At about the same time, the **Greeks of Phocaea** found **Massalia** (Marseille, c. 600 BC) and open a trading gateway to the interior of Gaul.' },
    { d: 'c. 600 – 500 BC', t: 'The “princely seats”', x: 'On fortified hills such as the **Heuneburg** (Germany), **Mont Lassois** (France) or the **Hohenasperg**, chiefs live who import wine, pottery and bronze from the Greeks and Etruscans. At the Heuneburg, a **mudbrick** wall in Mediterranean style (c. 600 BC) is a remarkable case of imitation, and Greek sources speak of a Celtic city, **Pyrene**, near the source of the Danube (Herodotus), which some identify with it (debated).' },
    { d: 'c. 530 BC', t: 'The Hochdorf grave', x: 'At Hochdorf (Germany), a chief of about 40 years and 1.87 m is buried lying on a **bronze couch**, with a cauldron of c. 500 litres full of mead, a **gold torc**, gold-covered shoes and a wagon. It was found intact in **1977**. It is one of the richest and most complete Celtic graves.' },
  ] },
  { linha: [
    { d: 'c. 500 BC', t: 'Vix and the first written “Celts”', x: 'In the grave of an elite woman at **Vix** (Burgundy) was placed an enormous **bronze krater** from Greece or southern Italy, **1.64 m** tall and weighing **208 kg**, with a capacity of about **1,100 litres**, next to a gold torc. Around 500 BC the geographer **Hecataeus of Miletus** mentions the **Keltoi**, and **Herodotus**, half a century later, says they live at the source of the Danube and beyond the Pillars of Hercules (his geography is confused).' },
  ] },
  { img: 'cel-vix-krater', leg: 'Bronze krater from the Vix grave (c. 500 BC), 1.64 m tall; Museum of Châtillon-sur-Seine.' },
  { linha: [
    { d: 'c. 450 BC', t: 'La Tène begins', x: 'Centres of power and art change: the **La Tène** culture is born, named after a site on the shore of Lake Neuchâtel (Switzerland), discovered in **1857**, where hundreds of iron and wooden objects appeared (weapons, tools, remains of bridges). Warrior graves with **long sword**, spear and shield now dominate, together with an art of **curves and spirals**.' },
    { d: 'c. 400 BC and after', t: 'The migrations: Italy', x: 'Celtic groups cross the Alps and settle in the Po valley: the **Insubres** (Mediolanum, Milan), the **Boii** (Felsina, Bologna), the **Senones** (Adriatic coast) and others. According to the Roman historian **Livy**, the cause was overpopulation in Gaul and a king, **Ambigatus**, who sent his nephews **Bellovesus** and **Segovesus** in search of new lands; the story is a late legend, but it reflects the Roman memory of a great migration.' },
  ] },
  { img: 'cel-la-tene-sitio', leg: 'The La Tène site on the shore of Lake Neuchâtel (Switzerland), where in 1857 hundreds of iron and wooden objects appeared.' },
  { img: 'cel-migracao', leg: 'A Gaulish migrating group with wagons and cattle, 4th–3rd century BC; conjectural reconstruction. AI-generated illustration.' },
  { linha: [
    { d: 'c. 390 BC', t: 'The sack of Rome', x: 'The **Senones**, under a chief the sources call **Brennus**, defeat the Romans at the **Allia** and sack Rome (the traditional date is 390 BC; other calculations give 387/386). Only the Capitol holds out. According to Livy, when the ransom was being weighed, Brennus added his sword to the scale and said *Vae victis* (“woe to the vanquished”); the phrase and the episode of the geese of the Capitol have a flavour of legend. The trauma marked the Roman attitude to the Gauls for centuries.' },
    { d: '279 BC', t: 'Delphi', x: 'A great Celtic force, led by another **Brennus** (the name may be a title; its meaning is debated), invades Macedonia and Greece and attacks the sanctuary of **Delphi**. According to the Greek **Pausanias**, the attackers were repelled amid storm, cold and Greek resistance; Brennus is said to have died of his wounds or by suicide. The Greeks celebrated the victory with the festival of the **Soteria**.' },
    { d: '278 – 277 BC', t: 'Galatia is born', x: 'According to the sources, about twenty thousand Celts cross into Asia at the invitation of King **Nicomedes I of Bithynia**, who wanted them as mercenaries. They divide into three tribes, the **Tolistobogii**, the **Tectosages** and the **Trocmi**, and settle on the central Anatolian plateau, which will come to be called **Galatia**. For more than a century they raid neighbouring Greek cities and levy tribute.' },
    { d: 'c. 232 BC', t: 'Attalus I defeats the Galatians', x: 'King **Attalus I of Pergamon** defeats the Galatians and confines them within borders. He had a great bronze monument erected at Pergamon with dead and wounded Gaulish warriors, of which we know Roman marble copies, such as the famous **“Dying Gaul”**: a naked warrior with a torc round his neck, treated with unusual compassion and dignity.' },
  ] },
  { img: 'cel-saque-roma', leg: 'Brennus’ Gauls in Rome, c. 390 BC; conjectural scene based on Livy’s account. AI-generated illustration.' },
  { img: 'cel-dying-gaul', leg: 'The “Dying Gaul”, Roman copy of a bronze original from Pergamon (c. 230–220 BC), Capitoline Museums, Rome.' },
  { linha: [
    { d: '225 – 222 BC', t: 'Telamon and the conquest of Cisalpine Gaul', x: 'A great coalition of **Boii, Insubres and Gaesatae** (the latter mercenaries who, according to the historian **Polybius**, fought naked) is destroyed at **Telamon** (225 BC). In 222 BC **Marcellus** defeats the Insubres at Clastidium and northern Italy becomes Roman territory, “Cisalpine Gaul”.' },
    { d: '2nd – 1st century BC', t: 'Oppida and coinage', x: 'In Gaul and central Europe great fortified settlements appear, the **oppida** (**Manching**, **Bibracte**, **Závist**, among others), with craftsmen, merchants and minted coins, often inspired by the gold staters of Philip II of Macedon. It is the first time the Celts have towns. In contact with the Mediterranean world, Gaulish inscriptions in Greek and Latin alphabets also appear.' },
    { d: '133 BC', t: 'The fall of Numantia', x: 'In the Iberian Peninsula, the Romans have great difficulty subduing the Celtiberians. The city of **Numantia**, of the Arevaci, resists a long siege by the general **Scipio Aemilianus** and surrenders in 133 BC. Six years earlier, in 139 BC, the Lusitanian **Viriathus** had been assassinated.' },
  ] },
  { img: 'cel-ancyra', leg: 'Temple of Augustus and Roma at Ankara (ancient Ancyra), on whose walls the text of the *Res Gestae* is preserved; Ancyra was the capital of Roman Galatia.' },
  { linha: [
    { d: '58 – 50 BC', t: 'Julius Caesar in Gaul', x: 'The proconsul **Julius Caesar** conquers Gaul in eight campaigns and writes his *Commentaries* (the *Gallic War*), the fullest account and the main source, partial and political, on the Gauls. He defeats the Helvetii (58), the Belgae (57), makes expeditions to Britain (55 and 54) and defeats the great revolt of 52.' },
    { d: '52 BC', t: 'Alesia', x: 'The Arvernian chief **Vercingetorix**, who had united many tribes, is besieged at **Alesia** by two lines of Roman fortifications, one inner and one outer, against a Gaulish relief army. He surrenders. He was taken to Rome, held for six years and executed after Caesar’s triumph, in 46 BC. According to Plutarch, there were a million dead and a million slaves in Caesar’s wars, figures that historians consider exaggerated.' },
  ] },
  { img: 'cel-alesia', leg: 'Reconstruction of the Roman fortifications at Alesia (52 BC), at the MuséoParc Alésia.' },
  { linha: [
    { d: '25 BC', t: 'Province of Galatia', x: 'When King **Amyntas** dies, Galatia is annexed by Augustus and becomes a Roman province, with its capital at **Ancyra** (Ankara). The Galatians keep their Gaulish language for centuries: around AD 387, **St Jerome**, who had visited Trier, says that the Galatians spoke almost the same language as the Treveri.' },
    { d: '12 BC', t: 'The altar of Lugdunum', x: 'At **Lugdunum** (Lyon) the altar of Roma and Augustus is inaugurated, the centre of the imperial cult and of the annual assembly of tribal delegates from Gaul. It shows how Gaulish elites came to take part in the Roman order: in AD 48 the emperor **Claudius**, born in Lyon, opens the Senate to Gaulish nobles.' },
    { d: 'AD 43', t: 'Rome invades Britain', x: 'The emperor **Claudius** sends four legions. **Caratacus**, of the Catuvellauni, resists until c. AD 51, and is handed over to Rome by the queen of the Brigantes, **Cartimandua**. The south of the island becomes the Roman province of **Britannia**.' },
    { d: 'AD 60 – 61', t: 'Boudica’s revolt', x: 'While the governor **Suetonius Paulinus** was attacking the druids of **Mona** (Anglesey), the queen of the Iceni, **Boudica**, rises against Roman abuses (according to Tacitus, her husband had left the kingdom jointly to the emperor and his daughters, the Romans annexed it, and her daughters were raped and she herself flogged). She destroys **Camulodunum** (Colchester), **Londinium** and **Verulamium**, but is defeated in a final battle, and dies (illness or poison, according to the sources).' },
  ] },
  { img: 'cel-boudica', leg: 'Statue of Boudica and her daughters by Thomas Thornycroft (19th century), Westminster, London: a Victorian image, not a portrait.' },
  { linha: [
    { d: 'AD 83 – 84', t: 'Mons Graupius and the walls', x: 'The general **Agricola** defeats the Caledonians at **Mons Graupius**, in Scotland (site uncertain), where, according to Tacitus, the chief **Calgacus** gave the famous speech against the Romans (“they make a desert and call it peace”). The frontier would eventually settle on **Hadrian’s Wall** (begun in AD 122). Ireland, which Agricola thought of conquering, was never occupied.' },
    { d: 'c. AD 410 – 450', t: 'Rome leaves Britain', x: 'The legions leave Britain around AD 410. Small Brittonic kingdoms continue in Wales, Cornwall and the north. During the 5th and 6th centuries many Britons emigrate to **Armorica** (which becomes **Brittany**) and, in smaller numbers, to Galicia (the diocese of **Britonia**, whose bishop **Maeloc** signs the acts of the Second Council of Braga, in 572).' },
    { d: '5th century', t: 'Christianity in Ireland', x: 'The pope sends **Palladius** to Ireland in 431 (according to Prosper of Aquitaine). **St Patrick**, a Briton who had been kidnapped and enslaved in Ireland, returns as a missionary (dates debated, 5th century). Monasteries appear, and become the great centres of culture. The first **ogham** inscriptions date from this time (4th–5th centuries AD).' },
    { d: '563 – 615', t: 'The travelling monks', x: '**Columba** (Colum Cille) founds the monastery of **Iona**, in Scotland, in 563; **Columbanus** leaves Bangor, in Ireland, c. 590, and founds **Luxeuil** and **Bobbio** (614). Irish monks carry books, schools and writing to much of Europe.' },
    { d: 'c. 800', t: 'The Book of Kells', x: 'A Gospel manuscript decorated with interlace, animals and spirals is made by monks (perhaps at Iona and finished at Kells; the point is debated). Today it is kept in **Dublin**.' },
  ] },
  { img: 'cel-ogham', leg: 'Ogham stone (Ireland), 5th–6th century AD: the writing is made with notches along the edge of the stone.' },
  { linha: [
    { d: '1707 – 1792', t: 'The Celts are “invented”', x: 'The Welshman **Edward Lhuyd** (1707) shows that Irish, Welsh, Breton and Cornish belong to one family with Gaulish, and uses the word “Celtic” for it. The Scottish poet **James Macpherson** publishes the supposed poems of **Ossian** (1760–63), partly forged. In 1792, **Iolo Morganwg** invents the Gorsedd, a “druidic” ceremony, in Wales. **Celtic revivalism** is born.' },
    { d: '1846 – 1994', t: 'Modern archaeology', x: 'Hallstatt (1846), La Tène (1857), Vix (1953), Hochdorf (1977) and **Glauberg** (1994, with a sandstone warrior statue of c. 500 BC) reveal the wealth of Celtic elites and change the image people had of them.' }
  ] },
  { h: 'Rediscovery' },
  'The Celts never disappeared from memory: the Romans wrote about them, Irish monks copied their stories and Renaissance scholars looked for them in the texts. The scientific “rediscovery” begins in the 19th century with Hallstatt and La Tène, and continues today with archaeology, linguistics (the decipherment of Celtiberian, for example) and ancient DNA. But the concept of “Celtic” remains disputed: see “Did the Celts exist?” in the legacy section.'
];

const mapa = [
  'There is no single “Celtic map”: there is a series of regions where archaeology, place names and inscriptions show Celtic-type languages or culture. The main places are these.',
  { tabela: { cab: ['Place', 'Where (today)', 'When / who', 'Importance'], linhas: [
    ['Hallstatt', 'Upper Austria', 'c. 800 – 450 BC', 'Salt mines and cemetery; gives its name to the early Iron Age'],
    ['Heuneburg', 'Baden-Württemberg, Germany', 'c. 600 – 500 BC', 'Princely seat with mudbrick wall; linked to trade with Massalia'],
    ['Hochdorf', 'Baden-Württemberg, Germany', 'c. 530 BC', 'Intact princely grave, with a bronze couch'],
    ['Mont Lassois / Vix', 'Burgundy, France', 'c. 500 BC', 'Princely seat; grave of the “Lady of Vix” with the enormous krater'],
    ['La Tène', 'Neuchâtel, Switzerland', 'c. 450 – 50 BC', 'Site that gives its name to the later Iron Age; deposit of weapons'],
    ['Manching', 'Bavaria, Germany', '3rd – 1st century BC', 'One of the largest oppida in central Europe, of about 380 hectares'],
    ['Bibracte', 'Mont Beuvray, Burgundy', '2nd – 1st century BC', 'Oppidum and capital of the Aedui; where Vercingetorix was proclaimed supreme leader'],
    ['Alesia', 'Alise-Sainte-Reine, Burgundy', '52 BC', 'Caesar’s final siege of Vercingetorix'],
    ['Tara and Navan Fort', 'Ireland', 'Iron Age and later', 'Ceremonial sites of the kings of Ireland, in tradition'],
    ['Maiden Castle', 'Dorset, England', '6th century BC – AD 43', 'One of the largest hillforts in Britain'],
    ['Citânia de Briteiros', 'Guimarães, Portugal', '4th century BC – 1st century AD and later', 'Large fortified settlement (“castro”) of the north-west of the Peninsula'],
    ['Conímbriga', 'Condeixa-a-Nova, Portugal', 'Iron Age; Roman city', 'Name with the Celtic-type suffix -briga (“fortified hill”)'],
    ['Numantia', 'Soria, Spain', 'Until 133 BC', 'City of the Celtiberian Arevaci, symbol of resistance'],
    ['Botorrita (Contrebia Belaisca)', 'Zaragoza, Spain', '2nd – 1st century BC', 'Bronzes with the longest Celtiberian texts'],
    ['Ancyra, Pessinus and Tavium', 'Ankara, Turkey', 'From 278 BC', 'Centres of the three tribes of Galatia'],
    ['Mediolanum (Milan) and Felsina (Bologna)', 'Northern Italy', 'From c. 400 BC', 'Centres of the Insubres and the Boii in Cisalpine Gaul']
  ] } },
  { h: 'Central Europe: salt, iron and power' },
  'The **Hallstatt** region, in the Alps, is a good starting point. There were salt mines there as early as the Bronze Age, and salt, which preserved meat and fish, was the basis of the wealth. The miners worked in deep galleries for centuries (the salt even preserved woollen clothes, leather shoes and wooden tools). The Hallstatt cemetery shows a society with great differences in wealth.',
  'Further west, between the 7th and 5th centuries BC, the **princely seats** appear: fortified settlements on hills, from which a chief controlled trade routes. The **Heuneburg**, on the upper Danube, and **Mont Lassois**, on the Seine, are among the best known. The graves of the chiefs and their families in the surroundings (**Hochdorf**, **Vix**, **Glauberg**) are full of imported objects and torcs, but also of local pieces.',
  { img: 'cel-bibracte', leg: 'Mont Beuvray: the monumental basin at Bibracte, capital of the Aedui, during the 1988 excavations.' },
  { h: 'Gaul and the oppida' },
  'In Gaul, the Romans described dozens of tribes: **Aedui**, **Arverni**, **Sequani**, **Helvetii**, **Belgae** (in the north), **Aquitani** (in the south-west, of a different language, related to ancient Basque), among others. Many had an **oppidum**, a fortified settlement of large area. Their walls were of the type called **murus gallicus**, described by Caesar: a structure of crossed timbers and stones, with a stone facing, which resisted battering rams well. **Bibracte** (Mont Beuvray) had a wall of five kilometres and was the capital of the Aedui; after the conquest it was replaced by the Roman city of **Autun**, founded by Augustus.',
  { img: 'cel-oppidum-reconstrucao', leg: 'Conjectural reconstruction of a Gaulish oppidum with a murus gallicus wall, 1st century BC. AI-generated illustration.' },
  { h: 'The British Isles' },
  'In Britain the Iron Age was a time of **fortified settlements** (**Maiden Castle**, **Danebury**), of roundhouses, of tribes (the Catuvellauni, the Iceni, the Brigantes, the Durotriges) and, in the south-east, of relations with Gaul. Julius Caesar says that the inhabitants of the south coast had come from Belgium. In **Ireland**, archaeology shows few settlements, but ceremonial sites on a large scale, such as **Tara** (Meath), **Navan Fort** (Armagh, the Emain Macha of the legends) and **Rathcroghan**, which later legends link to kings and heroes. Direct contact with the Roman world was small. Ireland also has relatively few “La Tène-type” objects, and its language is attested in writing only from the 4th century (ogham).',
  { img: 'cel-tara', leg: 'The Hill of Tara (Co. Meath, Ireland), ceremonial and symbolic site of the kings of Ireland.' },
  { h: 'The Iberian Peninsula and Portugal' },
  'The Peninsula was a mosaic. In the **centre**, the **Celtiberians** (Arevaci, Lusones, Belli, Titti) spoke a Celtic language, **Celtiberian**, which we know from more than a hundred inscriptions; the most important, the **Botorrita I Bronze** (discovered in 1970), is one of the longest texts, written in an alphabet of Iberian origin, and is still being studied. The Romans took almost two centuries to subdue the Peninsula (from 218 BC to the end of the Cantabrian wars, in 19 BC); the siege of Numantia, in 133 BC, was the end of Celtiberian resistance.',
  'In the **north-west** (Galicia, the Minho, Trás-os-Montes) there developed, from c. 900 BC, the **Castro culture**, of fortified settlements called **castros** or **citânias** (**Briteiros**, **Sanfins**, **Terroso**, **Santa Luzia**, **Monte Mozinho**). They had round or oval stone houses, with a very characteristic layout. It is a culture with its own features, and whether it was “Celtic” is much debated.',
  { img: 'cel-briteiros', leg: 'Citânia de Briteiros (Guimarães), fortified settlement of the Castro culture, with reconstructed houses.' },
  { img: 'cel-castro-lusitano', leg: 'Castro settlement of the north-west of the Peninsula, c. 1st century BC; conjectural reconstruction. AI-generated illustration.' },
  { caixa: 'Were there Celts in Portugal?', texto: [
    'The honest answer is “**in part, and it depends on what is meant by Celtic**”. Here is what is known.',
    '**What is firm:** (1) There are countless **place names of Celtic formation**: the suffix **-briga** (“fortified hill”, “fort”), as in **Conímbriga**, **Mirobriga** (Santiago do Cacém), **Talabriga** and many others. (2) **Pliny the Elder** and **Strabo** speak of populations called **Celtici** in the south-west (Alentejo) and the north-west (Galicia). (3) Many personal and divine names in the Roman inscriptions of the north-west and centre of Portugal (Bandua, Reve, Nabia) have roots that seem Indo-European and, for several, Celtic.',
    '**What is debated:** the **Lusitanian language**, known from few inscriptions, among them those of **Cabeço das Fráguas** (Guarda), **Lamas de Moledo** (Viseu) and Arroyo de la Luz (Cáceres), all roughly of the 1st century AD. It is Indo-European, but **most linguists do not consider it Celtic**: it keeps the initial *p* (as in the word *porcom*, “pig”), which Celtic languages lost. The “South-western language”, of the **South-western stelae** of the Algarve and Lower Alentejo (c. 7th – 5th century BC), which Koch considers Celtic and others do not, is also discussed. **Herodotus**, in the 5th century BC, says that the **Keltoi** lived beyond the Pillars of Hercules, next to the **Cynetes**, the westernmost people of Europe, and some place them in the Algarve.',
    'In short: the populations of the centre and north of what is now Portugal belonged to an Indo-European world with many Celtic features, but **there is no clear proof of a “Celtic” identity** (the Lusitanians and Gallaecians are not called Celts in any ancient source, except for the **Celtici**). The Romans conquered the territory between 218 and 19 BC; **Viriathus** (d. 139 BC), the chief of the Lusitanians, is a figure of resistance, of debated cultural affiliation.'
  ] },
  { img: 'cel-conimbriga', leg: 'Mosaic from the ruins of Conímbriga (Condeixa-a-Nova), a Roman city with a Celtic-style name (-briga).' },
  { img: 'cel-numancia', leg: 'Horse-shaped fibula from the Celtiberian necropolis of Numantia (Soria); the city held out against Rome until 133 BC.' },
  { h: 'Italy and Galatia' },
  { lista: [
    '**Cisalpine Gaul:** from c. 400 BC, Boii, Insubres, Senones and others occupy the Po plain. They founded or conquered cities such as Milan (**Mediolanum**) and Bologna (**Felsina**). Rome conquered the region between 225 and 191 BC and then romanized it so thoroughly that Virgil and Catullus, born there, are already Latin poets.',
    '**Galatia:** the three tribes settled around **Ancyra** (Ankara, the Tectosages), **Pessinus** (the Tolistobogii) and **Tavium** (the Trocmi). According to Strabo, each tribe was divided into four “tetrarchies”, and a council of 300 delegates met at the **Drynemeton** (“the oak sanctuary”). They were herders, warriors and mercenaries, who absorbed many Hellenistic and Phrygian features but kept Gaulish for centuries. St Paul wrote them the *Epistle to the Galatians*.'
  ] },
  { h: 'Routes and trade' },
  'The Celtic world was crossed by **trade routes**: the **salt** of Hallstatt and the Dürrnberg (Hallein), **tin** and amber (from the Baltic to the Mediterranean), the **iron** of Noricum (present-day Styria and Carinthia), **copper**, and the **wine** and pottery of Italy and Greece, which entered by the valleys of the **Rhône** and the **Seine** from Massalia. The historian **Diodorus** says (following Posidonius) that for one amphora of wine the Gauls gave a slave. The rivers (Danube, Rhine, Rhône, Loire, Seine) and the Alpine passes were the great highways.'
];

const sociedade = [
  { h: '1. Political organization' },
  'The Celts **had no state**. The political unit was the **tribe** (in Latin *civitas*, in Irish *túath*), with its territory, chiefs and assembly, allied or rival to its neighbours. Within the tribe there were warrior nobles, and power varied: in Caesar’s time some Gaulish tribes (such as the Aedui) had **magistrates elected** annually (the **vergobret**), others were monarchies, and many had passed from kings to aristocratic elites. The most powerful chiefs had **clients**: men who swore loyalty to them and fought for them.',
  'In **Ireland** society was dominated by kings of several levels (a “small” king of a tribe, a “great” king of a province, and the “high king”, more theoretical than real) and by a network of obligations described in medieval legal treatises, the **Brehon laws** (texts composed from the 7th century and preserved in later manuscripts). In **Galatia**, according to Strabo, each tribe was divided into four tetrarchies, each with a tetrarch, a judge, a military commander and two sub-commanders, and a council of 300 met at the Drynemeton.',
  { h: '2. Social classes' },
  'Caesar says that in Gaul only two classes counted: the **druids** and the **knights** (*equites*), the military nobility. The common people (*plebs*) were treated almost as slaves, indebted and dependent. Historians distrust this simplified view. In medieval Ireland there were kings, a class of sages and artists (**filid**, poets, jurists, smiths, physicians), free men and dependants. There were also **slaves**, many taken in war and sold to the Mediterranean world.',
  { img: 'cel-guerreiro-la-tene', leg: 'A Celtic warrior of the La Tène phase, 3rd century BC, with long sword, shield and torc; conjectural reconstruction. AI-generated illustration.' },
  { h: '3. Religion' },
  'Celtic religion is very poorly known. The Celts **left no sacred texts** and almost everything comes from: (1) **accounts by Greeks and Romans**, who see them from outside and often with hostility; (2) **inscriptions and sculptures** of the Roman period, which identify local gods with Roman gods (**interpretatio romana**); (3) **Irish and Welsh myths written by Christian monks** between the 7th and 14th centuries, long afterwards and filtered through Christianity; (4) **archaeology** (sanctuaries, votive deposits). That is why the “Celtic gods” of popular books are largely reconstructions.',
  { tabela: { cab: ['Deity', 'Probable role', 'Where the information comes from'], linhas: [
    ['Lugus', 'God of many talents (arts, trade, war); Caesar compares him to Mercury', 'Name in Lugdunum (Lyon), in Hispania (Peñalba de Villastar inscription) and, later, **Lugh** in Ireland'],
    ['Taranis', 'God of thunder (“thunder” in Gaulish)', 'Poem by **Lucan** and Roman altars'],
    ['Teutates', '“God of the tribe” (protector); appears in Lucan', 'Lucan; inscriptions in Britain'],
    ['Esus', 'God of obscure function; late commentators on Lucan say men were offered to him hanged from trees', 'Lucan; Pillar of the Boatmen (Paris)'],
    ['Cernunnos', 'Figure with deer antlers, associated with animals and abundance', 'The name appears clearly in only one inscription (Paris); antlered figures, such as the one on the Gundestrup cauldron, are unnamed'],
    ['Epona', 'Goddess of horses, much venerated among Roman cavalrymen', 'Countless dedications and sculptures throughout Gaul and Britain'],
    ['Belenus', 'God linked to light and healing', 'Inscriptions in Aquileia, Gaul and Britain'],
    ['Sulis', 'Goddess of the hot springs of Bath (*Aquae Sulis*), identified with Minerva', 'Temple and lead curse tablets at Bath'],
    ['Matres (Mothers)', 'Groups of three goddesses linked to fertility and protection', 'Sculptures and altars in Gaul, Germania and Britain'],
    ['Brigantia / Brigid', 'Goddess of a tribe of Britain (the Brigantes), and in Ireland a goddess and later a saint, of Kildare, with the day of 1 February', 'Roman inscriptions; medieval Irish texts (continuity between goddess and saint is debated)'],
    ['Bandua, Reve, Nabia', 'Local deities of the north-west and centre of the Iberian Peninsula', 'Roman inscriptions in Portugal and Galicia; their link with the Celts is debated']
  ] } },
  { img: 'cel-pilier-nautes', leg: 'Pillar of the Boatmen (Paris, early 1st century AD), the clearest ancient evidence for the name Cernunnos; Cluny Museum, Paris.' },
  { img: 'cel-gundestrup', leg: 'The Gundestrup cauldron (Denmark), silver, 2nd–1st century BC; origin debated (perhaps made in Thrace); National Museum of Denmark.' },
  { h: 'The druids' },
  'The **druids** were, according to Caesar (*Gallic War*, VI), the priestly and intellectual class of Gaul: they presided over sacrifices, taught, judged disputes and could excommunicate. According to him, training lasted up to twenty years and was oral, as **it was not permitted to put it in writing**. They believed in the immortality of the soul. **Pliny the Elder** describes a ceremony in which a druid, dressed in white, cuts **mistletoe** from an oak with a golden sickle (one of the few concrete details, and much quoted). At **Mona** (Anglesey), in AD 60, the druids were attacked by the Romans, according to Tacitus.',
  'The problem is that **we have no text written by a druid**. Most of what is said (rituals at Stonehenge, “druidic wisdom”, white robes) comes from Rome or was imagined later. The emperor **Claudius** banned their religion. In Ireland, druids appear in medieval stories, but already as figures of sorcery, defeated by Christian saints.',
  { img: 'cel-druida-ritual', leg: 'A druid ceremony in a grove, according to the classical sources; conjectural scene. AI-generated illustration.' },
  { h: 'Sacrifices, heads and sacred places' },
  { lista: [
    '**Places:** the Celts venerated **groves** (*nemeton*, “sacred place”), **rivers, lakes and springs**, and offered weapons, jewellery and objects. At **Llyn Cerrig Bach** (Anglesey), dozens of weapons, a slave chain and chariot fittings thrown into a lake between c. 150 BC and AD 100 were found in 1942.',
    '**The cult of heads:** Greeks and Romans (Posidonius, Diodorus, Strabo) say that Celtic warriors cut off the heads of enemies, hung them from the necks of their horses and preserved them in cedar oil; Posidonius says he saw this himself. Archaeology confirms the cult: at **Roquepertuse** and **Entremont** (southern France) there are porticoes with niches for skulls, and there are sculpted heads throughout the Celtic area.',
    '**Human sacrifice:** Caesar and Strabo speak of great wicker figures in which men were burned. Historians debate how much of the story is Roman propaganda, but human and animal sacrifice are plausible and there is isolated archaeological evidence. Roman sources, who also had human sacrifices in remote times, stress them to show the Gauls as “barbarians”.',
    '**The religious calendar:** the medieval Irish festivals of **Samhain** (1 November), **Imbolc**, **Beltane** and **Lughnasadh** divide the year into four, and the Coligny calendar suggests a year with similar divisions. The idea that they are “ancient” Celtic festivals is a reasonable extrapolation, but not always proven.'
  ] },
  { h: 'Myths: the great stories' },
  'The great Celtic narratives were only put into writing in the Middle Ages, in the islands. In Ireland, they are divided into “cycles”: the **Mythological** (the **Tuatha Dé Danann**, the “peoples of the goddess Danu”, whom tradition turned into gods and then into fairies), the **Ulster** (the hero **Cú Chulainn**, the queen **Medb** and the great tale *Táin Bó Cúailnge*, “The Cattle Raid of Cooley”), the **Fenian** (Fionn mac Cumhaill) and that of the kings. In Wales, the *Mabinogion* (eleven tales, copied in the 14th–15th centuries, from much older material) include characters such as Pwyll and Pryderi, and references to Arthur. These stories reflect a pagan world, but they were **written, chosen and retouched by Christians**, and cannot be read as a Celtic “sacred book”.',
  { h: '4. Economy' },
  'The Celts were above all **farmers and herders**. They grew wheat, barley, oats and rye, in ploughed fields, with **iron ploughs** and, in Gaul, used a reaping machine pulled by animals (the *vallus*, described by Pliny). They raised cattle, sheep, horses and, especially, **pigs** (Gaulish ham and bacon were exported to Rome, says Strabo). They worked **iron** on a large scale, as well as bronze, gold, amber, glass and coral.',
  '**Coinage** enters the Celtic world from the 4th–3rd century BC, in gold, silver and bronze, often in imitation of the staters of Philip II and Alexander. Trade went by rivers and roads, and there were **Italic** and Greek merchants in many settlements. The Celts sold **salt**, iron, hides, cattle, slaves and wool; they bought wine, oil and luxury objects.',
  { img: 'cel-forja', leg: 'A Celtic smith of the Iron Age, c. 2nd century BC; conjectural reconstruction. AI-generated illustration.' },
  { h: '5. Writing and language' },
  'The Celts valued **oral tradition**: the druids and, later, the Irish poets (**filid**) memorized enormous texts. But they were not illiterate: the **Helvetii** kept records in Greek (Caesar found a camp with lists of men in Greek letters), and **hundreds of inscriptions** in Celtic languages are known, written in borrowed alphabets: **Etruscan** (Lepontic), **Greek** and **Latin** (Gaulish), **Iberian** (Celtiberian) and, in the islands, **ogham**, an alphabet of strokes around a line that appears only from the 4th century AD. The longest texts are the **Coligny calendar** and the **Larzac lead tablet** (France, c. AD 100), both in Gaulish, and the **Botorrita bronzes**, in Celtiberian.',
  { tabela: { cab: ['Language', 'Branch', 'Where / when', 'Status'], linhas: [
    ['Lepontic', 'Continental Celtic', 'Northern Italy, 6th – 1st century BC', 'Extinct; the oldest Celtic writing'],
    ['Gaulish', 'Continental Celtic', 'Gaul, until the 5th–6th century AD', 'Extinct; left words in French, Portuguese and Spanish'],
    ['Celtiberian', 'Continental Celtic', 'Centre of the Iberian Peninsula, 3rd – 1st century BC', 'Extinct; known from bronzes and pottery'],
    ['Galatian', 'Continental Celtic', 'Anatolia, 3rd century BC – at least 4th century AD', 'Extinct; almost only personal names'],
    ['Lusitanian', 'Indo-European, but not Celtic (for most)', 'Centre of Portugal and Spanish Extremadura, 1st century AD', 'Extinct; few inscriptions'],
    ['Irish, Scottish Gaelic, Manx', 'Insular, Goidelic', 'Ireland, Scotland, Isle of Man', 'Living (Manx, revitalized)'],
    ['Welsh, Cornish, Breton', 'Insular, Brittonic', 'Wales, Cornwall, Brittany', 'Living (Cornish, revitalized)'],
    ['Pictish', 'Debated', 'North-east Scotland, 3rd – 9th century AD', 'Extinct; perhaps Brittonic, the point is discussed']
  ] } },
  { img: 'cel-coligny', leg: 'Fragment of the Coligny calendar, in bronze and in Gaulish, 2nd century AD; Gallo-Roman Museum, Lyon.' },
  { img: 'cel-botorrita', leg: 'Botorrita III bronze (c. 100 BC), with a Celtiberian text; Museum of Zaragoza.' },
  { h: '6. Home and family' },
  'In Britain and Ireland, the typical house was the **roundhouse**, with walls of wattle and daub or of stone, a conical thatched roof and a hearth in the centre. In Gaul and central Europe there were also rectangular timber houses. In the north-west of the Peninsula, the castros had stone houses, round or oval, and many courtyards. Settlements included granaries, storage pits and, in the oppida, craftsmen’s quarters.',
  'The family was extended and dominated by fathers and elder brothers, but **women** had in many societies more rights than in Rome: in medieval Irish laws they could own property, divorce in certain cases and, in Roman accounts, there are warrior queens (**Boudica**, **Cartimandua**). The children of the nobility were often raised by another family (Irish **fosterage**), a way of creating alliances. **Hospitality** was a sacred obligation.',
  { img: 'cel-casa-redonda', leg: 'A settlement of Iron Age roundhouses in Britain; conjectural reconstruction. AI-generated illustration.' },
  { h: '7. Food' },
  { lista: [
    '**Cereals:** bread, porridge and beer of barley or wheat. The Romans mention Gaulish beer (*cervesia*, the word that gave Portuguese “cerveja”).',
    '**Meat:** pork (the favourite), beef, mutton and game, cooked in **cauldrons** or roasted on spits. Caesar says the Britons did not eat hare, chicken or goose, for religious taboo.',
    '**Dairy:** milk, cheese and butter (Strabo says the Britons “did not know how to make cheese”; archaeology seems to contradict him).',
    '**Drinks:** **mead** (as at Hochdorf), beer and, for the elites, imported **wine**, which according to classical writers they drank neat (the Greeks mixed it with water and found this barbaric).',
    '**Feasts:** Posidonius describes banquets in which the best cut of meat (the “champion’s portion”) was contested by warriors, sometimes with duels. It is a literary image, but echoed in the Irish stories.'
  ] },
  { img: 'cel-bardo-festim', leg: 'A bard singing at a Celtic chieftain’s feast; conjectural scene. AI-generated illustration.' },
  { h: '8. Clothing' },
  'The Celts wore **trousers** (the *braccae*), which the Romans found strange (Gallia Narbonensis was even called *Gallia bracata*, “trousered Gaul”), a **tunic** and a **cloak** fastened at the shoulder by a **fibula** (a safety pin). Fabrics were of wool, sometimes **checked** or striped and brightly coloured: Diodorus speaks of cloaks “dyed in a thousand colours”. Checked woollen cloth has been preserved at Hallstatt. Warriors and elite women wore **torcs** (rigid necklaces of gold, bronze or silver), bracelets and earrings; men wore moustaches and, according to Diodorus, some bleached their hair with lime and combed it back. At Telamon, the **Gaesatae**, mercenaries, fought naked, according to Polybius.',
  { h: '9. Music, poetry and games' },
  'The Celts had **bards**, poets who sang the deeds of chiefs and ancestors (Posidonius describes them). Among the instruments known are **lyres** (and, later, **harps**) and the **carnyx**, a bronze trumpet in the shape of a boar or a dragon, played in battle to frighten the enemy; finds such as that of **Deskford** (Scotland) and **Tintignac** (France, 2004) have made it possible to reconstruct its sound. Board games (**fidchell** in Ireland, **gwyddbwyll** in Wales, attested only from the Middle Ages) and chariot races were common, as were wrestling and hunting.',
  { h: '10. Science, calendar and medicine' },
  'The **Coligny calendar** (discovered in 1897 at Coligny, in eastern France; bronze, 2nd century AD) is a five-year lunisolar calendar, with months of 29 or 30 days and an extra month to keep in step with the Sun, written in Gaulish with Latin letters. It shows remarkable astronomical knowledge and a distinctive way of reckoning time (in nights, according to Caesar). Caesar says the druids studied the stars, nature and the gods, and **Pliny** that they used medicinal plants, but these claims are poorly documented. A physician from Bordeaux of the 4th century, **Marcellus**, included recipes with Gaulish words in his book.',
  { h: '11. Technology' },
  { lista: [
    '**Iron metallurgy:** the Celts were masters of iron and steel; their swords were long and flexible, and the Romans praised the smiths of Noricum.',
    '**Chain mail:** it is probably a Celtic invention (4th–3rd century BC), later adopted by the Romans.',
    '**Wagons and wheels:** from the four-wheeled wagon of Hallstatt to the light two-wheeled war chariot, with wheels with iron tyres heated and fitted on, a very refined technique.',
    '**Construction:** walls of timber and stone (the *murus gallicus*), bridges and timber roads.',
    '**Others:** minted coinage, soap (according to Pliny, of tallow and beech ash, invented by the Gauls), wooden barrels and the reaping machine. Many of these attributions are made by Roman authors and some are disputed.'
  ] },
  { img: 'cel-escudo-battersea', leg: 'The Battersea Shield (River Thames), bronze with red glass decoration, c. 350–50 BC; British Museum.' },
  { img: 'cel-guerreiro-galaico', leg: 'Statue of a Gallaecian-Lusitanian warrior from Boticas (Portugal), with a round shield.' },
  { h: '12. War' },
  'War was central to Celtic elites. The Romans describe them as brave but disorderly: Polybius and Livy speak of a furious charge, of great badly tempered swords that bent (partly true, perhaps exaggerated). The infantry used **spear, long sword and shield** oval or rectangular (and, for the richer, helmet and chain mail); the **horsemen**, wealthy, were held to be the best of the time, and were recruited into the Roman army. **War chariots**, used in Italy and Britain, impressed Caesar. There were Celtic **mercenaries** all over the Mediterranean (in Ptolemaic Egypt, in Greece, in Carthage). Trophy heads and the noise of the **carnyx** completed the psychological effect.',
  { h: '13. Death and graves' },
  'In the early Iron Age, chiefs were buried under **great tumuli** (earth mounds), with wagons, weapons and vessels for a banquet in the afterlife (Hochdorf, Vix). In La Tène times, they come to be buried in flat cemeteries, with swords and, in certain regions (such as Yorkshire, in Britain), in dismantled chariots. In Gaul of the 2nd–1st century BC, **cremation** is common. The poorest left few traces. Belief in the immortality of the soul, according to Caesar and Diodorus, would explain courage in war, and some say the Celts lent money to be repaid in the next world (Valerius Maximus), a curiosity that no one can verify.'
];

const personalidades = [
  'No text written by the continental Celts themselves survives, and we know their main figures through Greeks and Romans; for the islands, the legends were written down much later. That is why what is history and what is legend is flagged.',
  { h: 'Brennus (4th and 3rd century BC)' },
  'The name is given by ancient sources to two chiefs: the one of the **Senones**, who defeated the Romans at the Allia and sacked Rome (c. 390 BC), and the one who led the invasion of Greece and the attack on Delphi (279 BC). Perhaps *Brennos* was a title rather than a name; the point is debated. The stories Romans and Greeks tell (the sword on the scale, the death at Delphi) mix fact and legend.',
  { h: 'Vercingetorix (c. 82 – 46 BC)' },
  'Chief of the **Arverni**, son of a noble who, according to Caesar, aspired to be king and was killed for it. In 52 BC he achieved what had rarely happened: uniting many Gaulish tribes against Rome. He used a “scorched earth” policy and won at **Gergovia**, but was besieged at **Alesia** and surrendered. He was paraded in Caesar’s triumph, in 46 BC, and executed. In the 19th century, France made him a national hero; the image has little to do with the real man, of whom we have no portrait (only the coins attributed to him).',
  { img: 'cel-vercingetorix', leg: 'Statue of Vercingetorix by Aimé Millet (1865), Alise-Sainte-Reine: a Romantic 19th-century image, as no ancient portrait exists.' },
  { h: 'Diviciacus (1st century BC)' },
  'Noble and druid of the **Aedui**, ally of Caesar at the start of the Gallic war. **Cicero**, who knew him, says that he mastered the “science of nature” and divination, and it is one of the rare times a real druid appears in a text by a contemporary. His brother, **Dumnorix**, was a rival and an enemy of Rome.',
  { h: 'Deiotarus (d. c. 40 BC)' },
  'Tetrarch and later king of the **Tolistobogii**, in Galatia. He allied with the Romans, supported Pompey in the civil war, was pardoned by Caesar and defended by Cicero (*Pro rege Deiotaro*, 45 BC). He shows a Hellenized Celtic elite, which governs like a Greek king and speaks the local language.',
  { h: 'Viriathus (d. 139 BC)' },
  'Chief of the **Lusitanians**, a shepherd (or hunter) who, according to Roman sources, led a guerrilla war against Rome between 147 and 139 BC. He was assassinated by three companions bribed by **Quintus Servilius Caepio**. He is a central figure of Portuguese memory, but **the Lusitanians are not always held to be Celts** (see the map section): he was an indigenous chief of the Peninsula, of Indo-European culture and language, and no ancient source calls him “Celtic”.',
  { h: 'Caratacus (d. after AD 51)' },
  'Prince of the **Catuvellauni**, son of Cunobelinus. He led the resistance against Claudius’ invasion for almost a decade, and was defeated c. AD 51. Handed over to Rome by the queen **Cartimandua**, he was taken to Rome and, according to **Tacitus**, his speech before the emperor (who spared his life) was memorable.',
  { h: 'Cartimandua (1st century AD)' },
  'Queen of the **Brigantes**, in northern Britain, an ally of Rome. She handed Caratacus over to the Romans, which earned her the hatred of many. She divorced her husband **Venutius** to marry his armour-bearer, and was driven out in AD 69, being evacuated by the Romans (Tacitus).',
  { h: 'Boudica (d. AD 60 or 61)' },
  'Queen of the **Iceni** (Norfolk). After the death of her husband, **Prasutagus**, who had left the kingdom partly to Rome, the Romans annexed it and mistreated the family. She raised the Iceni, the Trinovantes and others, and burned Camulodunum, Londinium and Verulamium, killing, according to Tacitus, about 70,000 people (a figure that is disputed). She was defeated; she is said to have died by poison or illness. The written sources are only Roman; her modern image is above all Victorian.',
  { h: 'Posidonius (c. 135 – c. 51 BC)' },
  'Greek philosopher and historian, from Apamea, who travelled in Gaul c. 100 BC. His work is lost, but **Strabo**, **Diodorus** and **Athenaeus** copied him, and he is the main source for much of what is said about Celtic customs (banquets, bards, severed heads, druids). He was an attentive observer, but he saw them through a framework of Greek ideas about “barbarians”.',
  { h: 'Julius Caesar (100 – 44 BC)' },
  'The conqueror of Gaul is the author of the fullest source on the Celts, the *Commentaries on the Gallic War*. It is a remarkable text and a **work of propaganda**: the author had to justify the war in the eyes of Rome. It contains valuable data (the tribes, the druids, the walls), but cannot be read as a neutral report.',
  { h: 'Medb and Cú Chulainn (legend)' },
  '**Medb**, queen of Connacht, and **Cú Chulainn**, young warrior of Ulster, are the main figures of the *Táin Bó Cúailnge*, an Irish epic tale preserved in medieval manuscripts (the *Book of Leinster*, c. 12th century, and an earlier version in the *Lebor na hUidre*). They are **legendary characters**, not historical ones; but the texts reflect, with much transformation, a world of warriors, chariots and duels.',
  { h: 'St Patrick (5th century)' },
  'A Romanized Briton, kidnapped at 16 by Irish pirates and enslaved in Ireland, where he kept flocks; he escaped and later returned as a missionary bishop. Two texts written by him in Latin are known, the *Confession* and the *Letter to Coroticus*, among the oldest written documents linked to Ireland. The dates are debated (5th century). The tradition that credits him with expelling the snakes is legend.',
  { h: 'Columba (c. 521 – 597) and Columbanus (c. 543 – 615)' },
  '**Columba**, an Irish noble, founded Iona (563) and converted part of the Picts, according to his biographer **Adomnán**. **Columbanus** left a monastery in Ireland for Gaul and Italy, and founded Luxeuil and Bobbio, where he died. They were among the main agents of insular culture and of the “pilgrimage for Christ” that brought Irish monks to the continent.',
  { h: 'Edward Lhuyd (1660 – 1709)' },
  'Welsh naturalist and linguist, keeper of the Ashmolean Museum in Oxford. In his *Archaeologia Britannica* (1707) he showed, by comparing vocabulary, that Welsh, Cornish, Breton, Irish and Scottish Gaelic belonged to one family and called it “Celtic”. He was the founder of the idea of a Celtic language family and, without meaning to, of a modern concept of “Celtic” that later grew beyond linguistics.'
];

const legado = [
  { h: 'What they left us' },
  { lista: [
    '**The living Celtic languages:** Irish (national language and first official language of the Republic of Ireland), Welsh (about half a million speakers), Scottish Gaelic, Breton, Cornish and Manx.',
    '**The literatures:** the Irish and Welsh myths and epics, one of the oldest vernacular literatures of Europe, and the legends of King **Arthur**, which the Welsh cycle and later French and English literature carried across Europe.',
    '**Place names:** *Paris* (from the **Parisii**), *Lyon* (*Lugdunum*), *Belgium* (from the **Belgae**), *Bohemia* (from the **Boii**), *Vienna* (*Vindobona*), and the suffixes *-dunum* (“fortress”), *-magus* (“plain”) and *-briga*.',
    '**Words:** in Portuguese, from Gaulish, via Latin, for example *carro* (cart), *légua* (league) and *cerveja* (beer) (according to etymological dictionaries).',
    '**Insular Christianity:** monasteries, schools, manuscripts and Irish missionaries who, between the 6th and 9th centuries, helped rebuild the Latin culture of Europe. The Synod of **Whitby** (664) discussed insular practices (the date of Easter, the tonsure) and chose the Roman usage.',
    '**The image:** the “Celts” have become an identity and cultural symbol of several nations and regions, and a popular brand.'
  ] },
  { h: 'Art' },
  '“**Celtic art**” is, first of all, the art of **La Tène**, from c. 450 BC: curves, spirals, **triskeles** (three spiral arms), palmettes and stylized foliage, faces that seem to hide in the patterns. It went through several phases (the “Early” style, that of **Waldalgesheim**, the “Plastic” style, the Sword style), from central Europe to the British Isles. The most famous objects are gold **torcs** (**Snettisham**), bronze mirrors, shields (**Battersea**), helmets (**Waterloo**) and stone sculpture (**Glauberg**, **Roquepertuse**).',
  'After the Roman conquest the style disappears on the continent, but **survives in the islands**: it gives rise to so-called **insular art** (7th – 9th centuries AD), that of manuscripts such as the **Book of Kells** and the *Book of Durrow*, of metalwork (the **Ardagh Chalice** and the **Tara Brooch**) and of Irish **stone crosses**, where La Tène spirals, Germanic interlace and biblical scenes are mixed.',
  { img: 'cel-book-of-kells', leg: 'Chi Rho page of the Book of Kells (c. 800), Trinity College, Dublin.' },
  { img: 'cel-cruz-monasterboice', leg: 'Muiredach’s Cross at Monasterboice (Ireland), c. 10th century.' },
  { img: 'cel-escriba-monge', leg: 'A monk copyist in an insular scriptorium, c. 8th century; conjectural reconstruction. AI-generated illustration.' },
  { h: 'Architecture' },
  'The Celts left no monumental stone buildings: they built mainly in **timber, earth and dry stone**. What remains are the **walls**, **ditches** and **platforms** of fortified settlements (oppida, hillforts, castros), graves (tumuli) and, in the Christian islands, the **round towers**, **oratories** and **crosses** of monasteries. The great cities associated with the Celts (Paris, Lyon, Milan, Vienna, Ankara) were, in practice, developed by the Romans.',
  { h: 'Did the Celts exist? A debate' },
  'The question is provocative, but serious: what does it mean to say that the Celts existed? The answer depends on the definition, and specialists are divided.',
  { lista: [
    '**The “traditional” position:** the Celts were a people or group of peoples of the Iron Age, with a language, a material culture (Hallstatt and La Tène) and common beliefs, who expanded from central Europe. It is the view of the 19th century and of a good part of the 20th.',
    '**The “critical” position** (**Simon James**, **John Collis** and others, since the 1990s): the ancients used *Keltoi* and *Galatai* vaguely; the inhabitants of the British Isles were never so called in antiquity; archaeological “cultures” do not coincide with languages or identities; the idea of a “Celtic nation” is a modern invention (of the 17th–19th centuries) and was used politically.',
    '**The “linguistic” position:** Celtic languages exist and form a solid family, so there are **Celts in the sense of speakers of Celtic languages**. It is not a modern idea: the speakers (and the inscriptions) are there. But it does not follow that they felt themselves to be one people.',
    '**The “Celtic from the West” theory** (**John Koch**, **Barry Cunliffe**): the Celtic language may have been born on the Atlantic seaboard in the Bronze Age, and not at Hallstatt. It divides the scientific community.'
  ] },
  'A reasonable consensus is this: **there were populations with Celtic languages, in many parts of Europe, with some shared practices and symbols; but there was no “Celtic nation” and no “Celtic empire”.** And the names we use today (“Celtic” art, “Celtic” nations) are in part recent inventions, which nevertheless have cultural value.',
  { img: 'cel-gorsedd', leg: 'A Gorsedd ceremony at the National Eisteddfod of Wales: a “druidic” tradition invented in 1792.' },
  { h: 'Celtic revivalism' },
  'From the 18th century, Europe rediscovers the Celts. **Ossian** (Macpherson, 1760) inspires Romanticism; **Iolo Morganwg** invents the Gorsedd (1792) and the idea of a succession of druids down to the Welsh bards; in the 19th century, archaeology, Irish and Scottish nationalism and language-revival movements give shape to a “**Pan-Celticism**”. There were also uses and abuses: 19th-century racial theories that made the Celts a “race” (now rejected by science), and a popular culture in which **druids**, **fairies**, “**Celtic**” **music** and **New Age** often have little to do with the historical Celts. Today the **Festival Interceltique de Lorient** (Brittany, since 1971) and Celtic-language schools show the more solid face of the phenomenon.',
  { h: 'Archaeological rediscovery' },
  'The archaeology of the Celts is recent: **Hallstatt** (1846), **La Tène** (1857), the **Gundestrup Cauldron** (1891), **Vix** (1953), **Hochdorf** (1977), **Glauberg** (1994). In the Peninsula, the **Botorrita Bronze** (1970) and the excavations at **Briteiros** (from 1875, by **Francisco Martins Sarmento**) opened up research. Today archaeology, ancient DNA and quantitative linguistics advance the debate, and the answers change with every discovery.',
  { caixa: 'To visit', texto: 'In **Austria**, **Hallstatt** and its salt mines. In **Germany**, the **Keltenwelt am Glauberg** (Hesse) and the museum at **Hochdorf**. In **France**, the **Museum of Châtillon-sur-Seine** (the Vix krater), the museum of **Bibracte** (Mont Beuvray) and the **MuséoParc Alésia**; in **Switzerland**, the **Laténium**, in Neuchâtel. In the **United Kingdom** and **Ireland**, the **British Museum**, the **National Museum of Ireland** (Dublin) and **Trinity College** (the Book of Kells), as well as **Tara** and monasteries such as **Glendalough** and **Monasterboice**. In **Portugal**, the **Citânia de Briteiros** and the **Museum of the Martins Sarmento Society** (Guimarães), the **ruins and museum of Conímbriga** and the **National Museum of Archaeology** (Lisbon). In **Spain**, **Numantia** (Soria) and the Museum of Zaragoza (the Botorrita bronzes).' }
];

const quiz = [
  { p: 'In what sense can we speak, most rigorously, of “Celts”?', op: ['As an empire governed from Gaul', 'As speakers of Celtic languages, with related material cultures', 'As a race originating in Ireland', 'As the builders of Stonehenge'], certa: 1, exp: 'The firmest use of the term is linguistic: the Celtic languages form a proven family. The Celts were never a state, and Stonehenge is much older.' },
  { p: 'After which Austrian site is the early Iron Age Celtic culture named?', op: ['La Tène', 'Hallstatt', 'Alesia', 'Bibracte'], certa: 1, exp: 'The Hallstatt culture (c. 800 – 450 BC) takes its name from a village with salt mines and a large cemetery, excavated from 1846.' },
  { p: 'Which culture follows Hallstatt, from c. 450 BC, known for its art of curves and spirals?', op: ['Tartessos', 'La Tène', 'Los Millares', 'Villanova'], certa: 1, exp: 'La Tène, the name of a site on the shore of Lake Neuchâtel, in Switzerland, discovered in 1857.' },
  { p: 'Which city was sacked by the Senones, led by Brennus, c. 390 BC?', op: ['Athens', 'Carthage', 'Rome', 'Massalia'], certa: 2, exp: 'The Gauls defeated the Romans at the Allia and sacked Rome; only the Capitol held out.' },
  { p: 'Who led the Gaulish resistance besieged at Alesia in 52 BC?', op: ['Boudica', 'Vercingetorix', 'Viriathus', 'Caratacus'], certa: 1, exp: 'The Arvernian Vercingetorix surrendered to Caesar after the siege and was executed in 46 BC, after Caesar’s triumph.' },
  { p: 'Which region of present-day Turkey was founded by Celts in 278–277 BC?', op: ['Phrygia', 'Cappadocia', 'Galatia', 'Lycia'], certa: 2, exp: 'The Tolistobogii, the Tectosages and the Trocmi settled on the central Anatolian plateau, Galatia, where St Paul wrote them a letter.' },
  { p: 'Which of these sources, written by Romans, is the main one on the conquest of Gaul?', op: ['The Metamorphoses, by Ovid', 'The Gallic War, by Julius Caesar', 'The Aeneid, by Virgil', 'The Annals, by Tacitus'], certa: 1, exp: 'Caesar’s Commentaries are the fullest source, but they are a work of propaganda, written by one of the protagonists.' },
  { p: 'What were the “druids”, according to Caesar?', op: ['Elite soldiers', 'Salt merchants', 'A class of priests, judges and sages', 'Kings of the tribes'], certa: 2, exp: 'Caesar describes them as priests and educators. No text written by a druid survives, so much of what is said about them is uncertain.' },
  { p: 'What are “oppida”?', op: ['Gold torcs', 'Large fortified settlements of the late Iron Age', 'Celtic alphabets', 'War chariots'], certa: 1, exp: 'The oppida (Bibracte, Manching and others) were fortified settlements with craftsmen, trade and, at times, coinage.' },
  { p: 'What was placed in the grave of an elite woman at Vix, c. 500 BC, which impresses by its size?', op: ['A three-metre iron sword', 'An enormous bronze krater, of about 1,100 litres', 'A solid gold statue', 'A boat'], certa: 1, exp: 'The Vix krater is 1.64 m tall, weighs 208 kg and was imported from the Greek world or southern Italy.' },
  { p: 'What is the Coligny calendar?', op: ['A map of the roads of Gaul', 'A five-year lunisolar calendar in Gaulish', 'A list of Irish kings', 'A medical treatise'], certa: 1, exp: 'Found in 1897, in bronze, it has months of 29 or 30 days and intercalary months to keep in step with the Sun; it dates from the 2nd century AD.' },
  { p: 'Why is it debated whether the Lusitanian language is Celtic?', op: ['Because it has no verbs', 'Because it keeps the initial p, which Celtic languages lost', 'Because it was written in ogham', 'Because it only existed in Galatia'], certa: 1, exp: 'The Cabeço das Fráguas inscription has the word porcom (“pig”), with initial p. Most linguists consider Lusitanian Indo-European, but not Celtic.' },
  { p: 'Which of these countries was never conquered by the Romans?', op: ['Gaul', 'Ireland', 'Britain (south)', 'Galatia'], certa: 1, exp: 'Agricola thought of conquering Ireland, but it was never done; that is why Celtic traditions survived there more intact.' },
  { p: 'Which Celtic language is still spoken by about half a million people and is the least endangered, according to UNESCO?', op: ['Cornish', 'Manx', 'Welsh', 'Gaulish'], certa: 2, exp: 'Welsh, spoken in Wales, is the Celtic language with the most vitality.' },
  { p: 'Who first used the word “Celtic” for the language family of the British Isles and Brittany, in 1707?', op: ['Julius Caesar', 'Edward Lhuyd', 'James Macpherson', 'Francisco Martins Sarmento'], certa: 1, exp: 'The Welshman Edward Lhuyd, in his *Archaeologia Britannica* (1707), showed that Irish, Welsh, Breton and Cornish were of the same family as Gaulish.' }
];

export default { visao, linha, mapa, sociedade, personalidades, legado, quiz };
