// ARMY AND WARFARE (Rome) — full English content. Same structure and same image slots as the Portuguese version (dados.js).
// Conventional dates (BC/AD). Troop and casualty figures are estimates; ancient authors (Polybius, Caesar, Tacitus, Josephus, Ammianus Marcellinus) are cited with caution.

const visao = [
  { caixa: 'In brief', texto: [
    'The **Roman army** was, for more than a thousand years, the institution that turned a small town in Latium into the mistress of the Mediterranean. It began as a militia of citizen-farmers, called up for summer campaigns; under Augustus it became a **permanent professional army**, with pay, terms of service, barracks and fortified frontiers; and in the fifth century AD it ended as a set of mobile forces, in large part made up of allies of Germanic origin, which could no longer defend the West.',
    'This page explains **how the army worked**: the legion and the auxiliary troops, its evolution (from Marius to Augustus and Diocletian), equipment, tactics, sieges, the navy, the frontiers (limes), the enemies and the great generals. It does not tell the political story period by period (for that, see the pages on the Late Republic, the High Empire and the Crisis and Dominate).'
  ] },
  { img: 'rex-coluna-trajano', leg: 'Trajan’s Column, Rome (AD 113), with spiral frieze.' },
  { h: 'Where and when' },
  'Rome’s military history stretches from the founding of the city (753 BC, the traditional date) to the deposition of Romulus Augustulus (AD 476, the conventional date). The army changed profoundly in that time; the table summarises the main phases, which historians debate in detail but whose general order is agreed.',
  { tabela: { cab: ['Phase', 'Period', 'Main characteristic'], linhas: [
    ['Archaic army', 'c. 753 – 509 BC (tradition)', 'Citizen militia, organised by wealth (the “Servian reform”, according to Livy, is debated).'],
    ['Early Republican legion', '509 – c. 107 BC', 'The “manipular” legion (hastati, principes, triarii): propertied citizens, mobilised for each campaign.'],
    ['Army of Marius and Caesar', 'c. 107 – 31 BC', 'Recruitment opened to the poor, cohorts, the eagle as sole standard, loyalty to the general.'],
    ['Army of the Principate', '27 BC – AD 235', 'Permanent professional army, 25 to 33 legions, auxiliary troops, Praetorians, service of 20 to 25 years.'],
    ['Army of the crisis and of Diocletian', '235 – 305', 'Wars on several fronts, mobile cavalry, the emperor’s escort, larger numbers.'],
    ['Late army', '306 – 476', 'Split between frontier troops (limitanei) and field troops (comitatenses), use of barbarian allies (foederati).']
  ] } },
  { img: 'rex-mapa-legioes-125', leg: 'Map of legion positions and naval bases in the Roman Empire, c. AD 125; English and Latin names.' },
  { h: 'What a legionary was' },
  'The **legionary** was a Roman citizen who served in the heavy infantry of the legion. He was armed with a shield, a short sword, a javelin and armour, marched with his kit on his back and spent much of his service building (roads, bridges, barracks) rather than fighting. In peacetime his main job was to **train and build**; in war he won above all through discipline, organisation and the ability to keep an army supplied for months.',
  { img: 'rex-legionario-reconstituicao', leg: 'Modern reenactment of a legionary wearing lorica segmentata.' },
  { h: 'Why it matters' },
  { lista: [
    '**It conquered and held an empire:** some five million km² at its height, defended by a few hundred thousand soldiers.',
    '**It was a school of organisation:** hierarchy, units of fixed size, training, logistics and military engineering that influenced European armies for centuries.',
    '**It was an engine of Romanisation:** soldiers founded cities (Mérida, Cologne, Chester, York), built roads and spread Latin; auxiliaries gained Roman citizenship at the end of their service.',
    '**It was also a political power:** the army made and unmade emperors, and its loyalty (or lack of it) decided many civil wars.',
    '**It left extraordinary sources:** the Vindolanda tablets, the Dura-Europos papyri, military diplomas, tombstones and Trajan’s Column let us know soldiers’ lives as for few ancient armies.'
  ] },
  { img: 'rex-aquila-estandarte', leg: 'AI-generated illustration. Aquilifer and legionary standards, c. AD 100: artistic interpretation.' },
  { h: 'How to use this page' },
  { lista: [
    '**Timeline:** military evolution, from the Samnite wars to the fall of the West.',
    '**Map:** battlefields, fortresses, sieges and frontiers, with a table and a section for each place.',
    '**Society:** organisation, equipment, tactics, discipline, the legionary’s life, the navy and the enemies.',
    '**People:** Roman generals and three remarkable opponents (Hannibal, Viriathus and Arminius).',
    '**Legacy:** what survives, where to visit, and the modern myths to avoid.',
    '**For the political background**, see the pages “The Late Republic”, “The High Empire” and “Crisis, Dominate and Fall”; for biographies of the emperors, “Emperors and great figures”.'
  ] },
  { caixa: 'A note on numbers', texto: 'Figures for soldiers, casualties and enemy armies come almost always from ancient authors (Polybius, Livy, Caesar, Josephus), who wrote long after the events, with propaganda and without statistics. On this page they are given **as orders of magnitude**, with “about” or “according to X”, and wherever historians disagree, we say so.' },
  { img: 'rex-testudo-reconstituicao', leg: 'Modern reenactment of the testudo formation.' },
  { caixa: 'The army today, in memory', texto: 'The Roman army remains present in modern culture, from cinema to games, and not always accurately. Much of what “everyone knows” (the thumbs-down, the chastity belt, the legion “lost” in Scotland) is false or very doubtful, and the “Legacy” section clears up the commonest myths. The archaeology of forts, battlefields and writing tablets is, fortunately, richer all the time.' }
];

const linha = [
  'This timeline follows Rome’s military evolution, from its origins to the fall of the West. Dates before the Middle Republic come from tradition and are uncertain; from the Punic Wars (3rd century BC) they are much firmer. For the political background, see the other pages.',
  { img: 'rex-augusto-prima-porta', leg: 'Augustus of Prima Porta, Vatican Museums; the cuirass depicts the return of the Parthian standards.' },
  { linha: [
    { d: 'c. 600 – 509 BC (tradition)', t: 'The royal army and the “Servian reform”', x: 'According to Livy and Dionysius of Halicarnassus, King Servius Tullius divided the citizens into classes by wealth, and each class supplied different weapons. Modern historians debate the date and form of this organisation: the archaic army was probably a militia of warriors fighting in a phalanx, in the Greek manner, and the reform was gradual.' },
    { d: 'c. 390 BC', t: 'The disaster at the Allia and the Gallic sack', x: 'A Roman army was routed by Gallic tribes at the river Allia, and Rome was taken and burned (Polybius’ date is 387/386; the traditional one, Varro’s, is 390). The experience marked Roman memory and led, according to tradition, to military reorganisations.' },
    { d: 'c. 340 – 290 BC', t: 'Samnite Wars: the manipular legion is born', x: 'Fighting in the hills of Samnium against an agile enemy favoured a legion articulated in small units, the **maniples**, more flexible than the phalanx. In 321 BC a Roman army was trapped at the Caudine Forks and forced to surrender. The exact dates of the change in arms and organisation are debated.' },
    { d: '280 – 275 BC', t: 'War against Pyrrhus', x: 'The king of Epirus, Pyrrhus, beat the Romans at Heraclea (280) and Asculum (279), but with heavy losses (hence “a Pyrrhic victory”), and was defeated at Beneventum (275). Rome faced a Hellenistic phalanx and war elephants for the first time, and emerged master of southern Italy.' },
    { d: '264 – 241 BC', t: 'First Punic War and the first fleet', x: 'To beat Carthage at sea, Rome built a fleet of hundreds of ships within a few years. According to Polybius, it copied a captured Carthaginian ship and used the corvus, a bridge with a hook for boarding enemy ships. Victories at Mylae (260) and the Aegates Islands (241) gave it Sicily.' },
    { d: '218 – 201 BC', t: 'Second Punic War: Hannibal in Italy', x: 'Hannibal crossed the Alps and defeated the Romans at the Trebia, Lake Trasimene and **Cannae (216 BC)**, where, according to Polybius, about 70,000 Romans and allies died. Rome did not surrender: it avoided direct battle, raised new armies and took the war to Spain and Africa. **Scipio** defeated Hannibal at **Zama (202 BC)**.' },
    { d: '197 – 168 BC', t: 'The legion defeats the Macedonian phalanx', x: 'At Cynoscephalae (197) and above all at **Pydna (168 BC)**, the legions beat the Macedonian armies, on broken ground where the phalanx lost cohesion. Polybius saw in this proof of the superiority of Roman organisation.' },
    { d: '147 – 133 BC', t: 'Viriathus and Numantia: war in Hispania', x: 'In Hispania, the Romans faced a long and draining war. The Lusitanian **Viriathus** defeated several praetors between 147 and 139 BC and was killed by treachery. **Numantia** held out until 133 BC, when **Scipio Aemilianus** surrounded it with a system of camps and walls and starved it into surrender.' },
    { d: 'c. 107 – 101 BC', t: 'Marius: the army changes', x: 'The consul **Gaius Marius** recruited propertyless volunteers for the war against Jugurtha (107) and reorganised the army during the threat of the Cimbri and Teutones, defeated at Aquae Sextiae (102) and Vercellae (101). The eagle became the legion’s sole standard. Historians see here the beginning of the soldiers’ personal loyalty to their generals, although the change was more gradual than tradition says.' },
    { d: '88 BC', t: 'Sulla marches on Rome', x: 'After the Social War (91–88 BC), in which Rome fought its Italian allies and ended by granting them citizenship, the consul **Sulla** led legions against the city itself, the first of several episodes in which the army was used in civil wars.' },
    { d: '58 – 50 BC', t: 'Caesar in Gaul', x: 'In eight years of campaigning, **Julius Caesar** conquered Gaul and made the first Roman incursions into Britain and beyond the Rhine. His Commentaries on the Gallic War are the best source, but they are also political propaganda. The high point was the siege of **Alesia (52 BC)**, against Vercingetorix.' },
    { d: '53 BC', t: 'Carrhae: defeat by the Parthians', x: 'The triumvir **Crassus** lost a large army in Mesopotamia, at Carrhae, to the cavalry and mounted archers of the Parthians. Crassus died and the Roman eagles fell into enemy hands. It was Augustus who would recover them, by diplomacy, in 20 BC.' },
    { d: '49 – 45 BC', t: 'Civil war: Caesar against Pompey', x: 'By crossing the Rubicon with a legion (49 BC), Caesar began the civil war. At **Pharsalus (48 BC)**, Caesar’s veteran infantry beat Pompey’s larger army. It was a war between Roman generals, with Roman legions on both sides.' },
    { d: '31 – 27 BC', t: 'Actium and the end of the civil war', x: 'At the naval battle of **Actium (31 BC)**, the fleet of **Agrippa**, Octavian’s commander, defeated Mark Antony and Cleopatra. Octavian was master of about sixty legions and discharged many, keeping some 28. In 27 BC he received the name **Augustus**.' },
    { d: '13 BC – AD 6', t: 'Augustus creates the standing army', x: 'Augustus fixed the length of service (16, later 20 years in the legions), created the **Praetorian Guard** and the permanent fleets, and in AD 6 set up the **aerarium militare**, a treasury to pay veterans’ discharge bonuses, funded by new taxes. For the first time there was an army paid by the state and loyal to the emperor.' },
    { d: 'AD 9', t: 'Teutoburg Forest: the disaster of Varus', x: 'Three legions (XVII, XVIII and XIX), six cohorts and three cavalry units, commanded by **Publius Quinctilius Varus**, were ambushed in Germania by a Cheruscan chief, **Arminius**, who had been a Roman officer. The disaster ended the attempt to conquer Germania up to the Elbe. Two of the three eagles were recovered by Germanicus (AD 15–16) and the third around AD 41.' },
    { d: 'AD 43', t: 'The conquest of Britain', x: 'Under Claudius, four legions and a large number of auxiliaries landed in Britain. Within a few years the south was conquered; the revolt of **Boudica** (AD 60/61) nearly drove them out, but was crushed.' },
    { d: 'AD 66 – 74', t: 'The Jewish War: Jerusalem and Masada', x: 'The revolt in Judaea led to the siege and destruction of Jerusalem by **Titus** in AD 70. The fortress of **Masada** fell only in 73 or 74, after a siege with an enormous ramp, known above all from Flavius Josephus.' },
    { d: 'AD 83/84', t: 'Mons Graupius', x: 'According to Tacitus, the governor **Agricola** defeated the Caledonians at the battle of Mons Graupius, in northern Scotland. The site is uncertain. Soon afterwards the Romans withdrew from much of the territory they had taken in Caledonia.' },
    { d: 'AD 101 – 106', t: 'Trajan in Dacia', x: 'Two wars against King **Decebalus** ended with the conquest of Dacia (part of today’s Romania), which became a province. The campaign is told in pictures on **Trajan’s Column** (113). It was one of the last great Roman conquests.' },
    { d: 'AD 117 – 122', t: 'Hadrian: from expansion to defence', x: 'Trajan brought the Empire to its greatest extent (116/117) with his campaign against the Parthians, but **Hadrian** gave up part of the conquests and fixed the frontiers. In 122, in Britain, work began on **Hadrian’s Wall**.' },
    { d: 'AD 166 – 180', t: 'The Marcomannic Wars', x: 'Under Marcus Aurelius, Germanic tribes crossed the Danube and reached northern Italy, at a time when the armies had been weakened by an epidemic, the so-called “Antonine Plague”. The emperor spent much of his last years campaigning on the Danube.' },
    { d: 'c. AD 193 – 212', t: 'Septimius Severus and the pay', x: 'Septimius Severus, put on the throne by the Danube legions, raised the pay (c. 197), created three new legions and allowed soldiers to live with their wives. Caracalla raised the pay again in 212. The cost was growing fiscal pressure.' },
    { d: 'AD 235 – 284', t: 'The Crisis of the Third Century', x: 'Half a century of civil wars, invasions and short-lived emperors. In 260 the emperor **Valerian** was captured by the Sasanian Persians. **Gallienus**, according to tradition, reformed the army, creating a mobile cavalry reserve (the extent of the reform is debated); **Aurelian** reunified the Empire and had the walls of Rome built.' },
    { d: 'AD 284 – 305', t: 'Diocletian and the Tetrarchy', x: 'Diocletian reorganised the provinces and the army: he increased numbers, multiplied the units (making them smaller) and fortified the frontiers. Four emperors (the Tetrarchy) made it possible to answer several threats at once.' },
    { d: 'AD 312', t: 'Milvian Bridge and the end of the Praetorians', x: 'Constantine defeated Maxentius at the Milvian Bridge and disbanded the Praetorian Guard, which had backed Maxentius. He created or consolidated a mobile field army (comitatenses) alongside the frontier troops (limitanei).' },
    { d: '9 August AD 378', t: 'Adrianople', x: 'Near today’s Edirne, in Turkey, the Goths of Fritigern destroyed the eastern army of the emperor **Valens**, who died (the circumstances of his death are uncertain). According to Ammianus Marcellinus about two thirds of the troops were lost, although the figures are debated. Ammianus compares it to Cannae.' },
    { d: 'AD 406 – 476', t: 'The West comes apart', x: 'At the end of 406, Vandals, Alans and Suebi crossed the Rhine. The West lost, little by little, its provinces and its control of an army increasingly made up of federates. In 476 the military leader **Odoacer** deposed Romulus Augustulus and sent the imperial insignia to Constantinople. The “fall” was a long process; the Eastern Empire continued.' }
  ] }
];

const mapa = [
  'The Roman army left its marks across Europe, North Africa and the Middle East: famous battlefields, fortresses, sieges, walls and roads. This section presents the most important places, from Italy to the Rhine, the Danube, Britain, the East and Hispania, with a table and a short note on each.',
  { img: 'rex-mapa-limes', leg: 'General map of the Roman Empire’s frontiers and roads, c. AD 125; English labels.' },
  { tabela: { cab: ['Place', 'Type', 'Date', 'Significance'], linhas: [
    ['Cannae (Apulia)', 'Battle', '216 BC', 'Hannibal envelops and destroys a large Roman army.'],
    ['Zama (near Carthage)', 'Battle', '202 BC', 'Scipio defeats Hannibal and ends the Second Punic War.'],
    ['Pydna (Macedonia)', 'Battle', '168 BC', 'The legion defeats the Macedonian phalanx.'],
    ['Numantia (Soria)', 'Siege', '134 – 133 BC', 'Scipio Aemilianus besieges and takes the Celtiberian city.'],
    ['Alesia (Burgundy)', 'Siege', '52 BC', 'Caesar besieges Vercingetorix with two lines of fortifications.'],
    ['Carrhae (Mesopotamia)', 'Battle', '53 BC', 'Defeat of Crassus by the Parthians.'],
    ['Pharsalus (Greece)', 'Battle', '48 BC', 'Caesar defeats Pompey.'],
    ['Actium (Greece)', 'Naval battle', '31 BC', 'Agrippa and Octavian defeat Mark Antony and Cleopatra.'],
    ['Teutoburg Forest / Kalkriese', 'Ambush', 'AD 9', 'Three legions destroyed by Arminius.'],
    ['Jerusalem', 'Siege', 'AD 70', 'Titus takes and destroys the city and the Temple.'],
    ['Masada (Judaea)', 'Siege', 'AD 73/74', 'The Romans build a ramp to take the fortress.'],
    ['Sarmizegetusa (Dacia)', 'Siege', 'AD 106', 'Trajan takes Decebalus’ capital.'],
    ['Hadrian’s Wall', 'Frontier', 'from c. AD 122', 'About 117 km between the Irish Sea and the North Sea.'],
    ['Vindolanda', 'Fort', 'c. AD 85 – 130', 'Source of hundreds of soldiers’ writing tablets.'],
    ['Dura-Europos (Syria)', 'Fortress city', 'taken c. 256/257', 'Sasanian siege with mines and countermines.'],
    ['Adrianople (Thrace)', 'Battle', 'AD 378', 'Goths destroy Valens’ army.']
  ] } },
  { h: 'Cannae: the perfect envelopment' },
  'On **2 August 216 BC** (the traditional date), at Cannae in Apulia, the Romans, with about 80,000 men according to Polybius, formed a very dense mass of infantry in the centre. Hannibal, weaker in infantry, let the centre give way and closed the wings and the cavalry behind the Romans, who found themselves surrounded. Polybius speaks of about **70,000 Roman and allied dead**; Livy gives lower figures. The consul Aemilius Paullus died. It is still studied as the model of a battle of annihilation.',
  { img: 'rex-canas-esquema', leg: 'Drawn diagram. Cannae, 216 BC: simplified three-stage diagram, left to right. Rome in red, Carthage in ochre; not to scale.' },
  { h: 'Alesia: two walls against two armies' },
  'In 52 BC, **Vercingetorix** took refuge with about 80,000 men (Caesar’s figure) in the fortified town of **Alesia**, on Mont Auxois in Burgundy. Caesar, with 10 to 11 legions, built a **line of contravallation** (facing the town, about 16 km long) and another of **circumvallation** (facing outwards, about 21 km), with ditches, stakes, towers and traps. A Gallic relief army, which Caesar says numbered 250,000 (a figure surely much exaggerated), failed to break through. Vercingetorix surrendered. Nineteenth-century and more recent excavations have confirmed the lines of fortification.',
  { img: 'rex-alesia-reconstituicao', leg: 'AI-generated illustration. Roman siege lines at Alesia, 52 BC: conjectural reconstruction.' },
  { h: 'Teutoburg Forest and Kalkriese' },
  'In **AD 9**, **Publius Quinctilius Varus** was leading three legions (XVII, XVIII and XIX), with auxiliaries and the baggage train, to winter quarters when he was attacked, over several days, by Germanic forces led by Arminius, in forest and marsh. Of the 15,000 to 20,000 men, few escaped. Historians now think that the most likely site of the final battle is **Kalkriese**, near Osnabrück, where coins, weapons and an earth rampart have been found, but the exact site remains **debated**. Augustus, according to Suetonius, cried: “Quinctilius Varus, give me back my legions!”.',
  { img: 'rex-lapide-celio', leg: 'Tombstone of Marcus Caelius, centurion of Legion XVIII killed in the Varian War, LVR-LandesMuseum, Bonn.' },
  { img: 'rex-emboscada-floresta', leg: 'AI-generated illustration. Roman column ambushed in Germania, AD 9: artistic interpretation.' },
  { h: 'Hadrian’s Wall and Vindolanda' },
  'Begun around **AD 122** (Hadrian visited Britain that year) and built by the legions II Augusta, VI Victrix and XX Valeria Victrix, **Hadrian’s Wall** was about **80 Roman miles (117 km)** long, from Wallsend on the North Sea to the Solway Firth, with forts at regular intervals, a milecastle (small post) at every Roman mile and two turrets between them. According to the usual interpretation it was a **control barrier**, not a wall to stop armies: it allowed movements to be watched, duties to be collected and the provinces to be protected. To the north, the turf **Antonine Wall** was begun around AD 142 and abandoned some twenty years later. At **Vindolanda**, a fort just south of the Wall, hundreds of inked **wooden tablets**, c. AD 85–130, were found, with letters, lists and requests from soldiers and their families.',
  { img: 'rex-muralha-adriano', leg: 'Aerial view of Hadrian’s Wall and Housesteads fort, Northumbria.' },
  { img: 'rex-vindolanda-tabua', leg: 'Vindolanda tablet 291, Claudia Severa’s invitation written in ink on wood, British Museum.' },
  { h: 'Rhine and Danube' },
  'In continental Europe, the frontier followed two great rivers: the **Rhine** and the **Danube**. Along them the legions settled in large permanent fortresses such as Vetera (Xanten), Mogontiacum (Mainz), Argentoratum (Strasbourg), **Carnuntum** (near Vienna), Vindobona (Vienna) and Aquincum (Budapest). Between the Rhine and the Danube, the **Upper German–Raetian limes** was a line of forts and towers with palisades and ditches, and the **Saalburg** fort, reconstructed from the end of the nineteenth century, gives a good idea of what an auxiliary fort looked like.',
  { img: 'rex-saalburg-forte', leg: 'Reconstructed Roman fort at Saalburg, Taunus, Germany.' },
  { h: 'Masada: the ramp' },
  'After the fall of Jerusalem (AD 70), the fortress of **Masada**, on a plateau above the Dead Sea, was the last to resist. According to **Flavius Josephus**, Legio X Fretensis, commanded by Flavius Silva, built camps around the fortress and an enormous **earth ramp** on the western side, and when the walls were breached (AD 73 or 74) it found 960 defenders dead by mass suicide. Archaeology confirms the camps, the ramp and the siege; **the mass suicide, as Josephus tells it, is disputed** by historians.',
  { img: 'rex-massada-rampa', leg: 'Roman siege ramp at Masada viewed from the fortress summit.' },
  { h: 'Dura-Europos: the frontier city' },
  'In Syria, on the Euphrates, **Dura-Europos** was a Hellenistic city taken by the Romans in the second century AD and garrisoned. It was besieged and taken by the Sasanians around **256/257**. Excavations revealed a synagogue, a Christian house-church, a mithraeum, military papyri (among them a calendar of army festivals, the Feriale Duranum) and the mines and countermines of the siege. According to a debated interpretation, the Persians may have used toxic gas in the mines.',
  { img: 'rex-dura-europos-ruinas', leg: 'Ruins of Dura-Europos, Syria.' },
  { h: 'Hispania and Lusitania' },
  'The conquest of the Iberian Peninsula took **two centuries** (218 BC to 19 BC). Against the Lusitanians, **Viriathus** (147–139 BC) defeated several Roman generals. Against the Celtiberians, **Numantia** held out until 133 BC. The wars against the Cantabrians and Asturians (29–19 BC) completed the conquest. After the conquest Hispania had a small garrison (from c. AD 74, Legio VII Gemina, at León, and auxiliaries); **Lusitania** had no legions, only auxiliary units. **Augusta Emerita** (Mérida) was founded in 25 BC for veterans of the legions V Alaudae and X Gemina, and a network of roads linked it to the other cities.',
  { img: 'rex-viriato-estatua', leg: 'Modern monument to Viriathus, Viseu.' },
  { h: 'Britain: Isca, Deva and Eboracum' },
  'In Britain, the great legionary fortresses were **Isca** (Caerleon, Wales, Legio II Augusta), **Deva** (Chester, Legio XX Valeria Victrix) and **Eboracum** (York, Legio VI Victrix), where Constantius Chlorus died in 306 and Constantine was acclaimed emperor by the troops. English towns whose names end in -chester, -cester or -caster derive from the Latin word castra (camp).',
  { img: 'rex-caerleon-anfiteatro', leg: 'Roman amphitheatre at Caerleon (Isca Augusta), Wales.' },
  { h: 'The permanent camps of Rome' },
  'In Rome, the **Castra Praetoria**, built around AD 23 under Tiberius and Sejanus, gathered the Praetorian cohorts in barracks beside the city wall. The Aurelian Wall (271–275) incorporated the walls of the camp. Constantine disbanded the Praetorians in 312 and the barracks were taken out of use; part of the structure is still visible today.',
  { h: 'Actium and the naval bases' },
  'The naval battle of **Actium** (2 September 31 BC) was fought in the Ambracian Gulf, in Greece. The permanent fleets created by Augustus had their main bases at **Misenum** (Bay of Naples) and **Ravenna** (Adriatic), and there were squadrons on the Rhine, on the Danube, in Britain and in Egypt.',
  { h: 'The Saxon Shore and the late frontiers' },
  'In the late third and the fourth centuries, the coasts of the English Channel and the North Sea were protected by a chain of stone forts with high walls and round towers, under an officer called the “Count of the Saxon Shore” (Litus Saxonicum), such as **Richborough**, **Portchester** and **Pevensey**. In the East, the **Strata Diocletiana** linked forts between Syria and Arabia.',
  { h: 'Adrianople' },
  'On **9 August 378**, near Adrianople (today Edirne) in Thrace, the emperor **Valens** attacked the Goths of Fritigern before the reinforcements of the emperor Gratian arrived, in the heat of the day, and the Gothic cavalry, returning from a foraging mission, fell on the Roman flank. Ammianus Marcellinus says that about two thirds of the army was lost; the figures are **much debated**. Valens vanished in the fighting.'
];

const sociedade = [
  'This section explains the army from the inside: how it was organised, who commanded it, how it was armed, trained, marched and fought, what a soldier’s life was like and how the army changed over the centuries.',
  { h: 'The legion of the Principate' },
  'The **legion** (legio) was the army’s main unit. In the Principate (first and second centuries AD) it had about **5,000 to 5,500 men** (the figure varies with the source and the period), divided into **10 cohorts**. Each of the first nine had six **centuries**, of about 80 men, and the first cohort, according to the most common reading, had five centuries of double strength (a debated point). Each legion had a number and a name (for example Legio X Fretensis or Legio II Augusta) and an emblem, the metal eagle (aquila).',
  { tabela: { cab: ['Unit', 'Composition', 'Commander'], linhas: [
    ['Contubernium', '8 soldiers sharing a tent or a room', 'a decanus'],
    ['Century', '10 contubernia, c. 80 men', 'centurion'],
    ['Cohort', '6 centuries, c. 480 men (the 1st, stronger)', 'the senior centurion'],
    ['Legion', '10 cohorts, c. 5,000 to 5,500 men, plus cavalry (c. 120) and technical staff', 'legate (legatus), a senator'],
    ['Auxilia', 'Cohorts of c. 480 or c. 800 men; cavalry alae', 'prefect or tribune, equestrian']
  ] } },
  { h: 'The officers' },
  'At the head of the legion was the **legate** (legatus legionis), a senator appointed by the emperor. Next came the **broad-stripe tribune** (tribunus laticlavius), a young senator at the start of his career, and the **camp prefect** (praefectus castrorum), an experienced veteran who dealt with logistics. There were also five **narrow-stripe tribunes**, young equestrians. The backbone of the legion was its roughly **60 centurions**, who rose from the ranks by merit (or by patronage) and were the real school of command. The senior centurion, the primus pilus, had great standing.',
  { h: 'The auxiliaries' },
  'The **auxiliaries** (auxilia) were troops recruited among the free subjects of the Empire who did not yet have Roman citizenship. They supplied what the legion lacked: cavalry, archers, slingers, light troops. They served about **25 years** and at the end received **Roman citizenship**, for themselves and their children, recorded on a bronze **military diploma**. By the second century the auxiliaries were as numerous as the legionaries.',
  { img: 'rex-diploma-militar', leg: 'Roman bronze military diploma, c. AD 149, Metropolitan Museum of Art.' },
  { h: 'The cavalry' },
  'Roman cavalry was mostly made up of **auxiliaries** (alae of about 500 horsemen); each legion had only a small body of cavalry (about 120). Peoples known as good horsemen were recruited: Gauls, Thracians, Hispanics, Numidians. In the third century tradition credits the emperor Gallienus with creating a mobile cavalry reserve (the importance of the reform is debated), which became normal in the late army.',
  { h: 'The Praetorian Guard' },
  'The **Praetorians** were the emperor’s personal guard, with shorter service (16 years), higher pay and barracks in Rome. Augustus created nine cohorts; under Tiberius they were gathered in the Castra Praetoria. They became a political force: Praetorian officers killed Caligula (41) and the Praetorians proclaimed Claudius, and in 193 they auctioned the throne to Didius Julianus. Constantine disbanded them in 312.',
  { img: 'rex-pretorianos-relevo', leg: 'Praetorians Relief, first century AD, Louvre collection; photographed at Louvre-Lens, with modern restorations.' },
  { h: 'From citizen army to professional army' },
  'In the early Republic the army was a **militia of propertied citizens**: each soldier paid for his own equipment, served in summer campaigns and went home. When wars became long and distant (Hispania, Greece, Africa), the model fell into crisis: peasants could not leave their land for years. The solution was to **recruit poor volunteers**, ever more dependent on the general who promised them pay and land.',
  { img: 'rex-altar-domicio', leg: 'Relief of the Altar of Domitius Ahenobarbus, depicting a census and soldiers, Louvre.' },
  { h: 'The Marian reform' },
  'In 107 BC, **Gaius Marius** accepted propertyless volunteers for the war in Numidia. From then on the legion became an institution less tied to the soldier’s wealth. Tradition credits him with many changes (the eagle as sole standard, uniform equipment, the load carried by the soldiers, “Marius’ mules”); historians consider that **some of them were gradual** and earlier than he. The political effect, however, was real: the soldier expected pay and land from his general, and this increased the generals’ power.',
  { h: 'The reform of Augustus' },
  'After Actium, Augustus reduced the army to about 28 legions and turned it into a **permanent force**. He fixed service at 16 years (later 20) and the discharge bonus (3,000 denarii, according to Cassius Dio); he created the aerarium militare (AD 6), distributed the legions in permanent camps on the frontiers and created the fleets and the Praetorian Guard. After Teutoburg the number fell to 25.',
  { h: 'Diocletian and Constantine' },
  'In the third century, generals obliged to defend several frontiers at once had created mobile forces alongside the frontier legions. **Diocletian** (284–305) increased total numbers (estimates range from about 390,000 to 600,000 men, but this is much debated), multiplied the units, which became smaller, and separated civil and military powers in the provinces. **Constantine** consolidated a **mobile army** (comitatenses), under supreme commanders (magistri militum), and the frontier troops (limitanei) were left with lower pay and prestige.',
  { img: 'rex-tetrarcas', leg: 'The porphyry Tetrarchs beside St Mark’s Basilica, Venice.' },
  { h: 'Recruitment' },
  'Legionaries were **Roman citizens**, generally between 18 and 23 years old. There were volunteers, and forced levies in hard times. Over time the origin changed: in the first century most came from Italy; in the second, from the provinces, more and more from the regions where the legions were stationed. Auxiliaries were recruited in the provinces and among neighbouring peoples. In late antiquity recruitment became hereditary for the sons of soldiers and veterans and many “barbarians” were enrolled.',
  { h: 'Pay and rewards' },
  { tabela: { cab: ['Emperor', 'Legionary’s annual pay', 'Note'], linhas: [
    ['Augustus', '225 denarii (900 sesterces)', 'Paid in three instalments; food, equipment and funerals were deducted.'],
    ['Domitian (c. 84)', '300 denarii', 'First major increase.'],
    ['Septimius Severus (c. 197)', '450 denarii', '50% increase.'],
    ['Caracalla (212)', '675 denarii', 'Another 50% increase.']
  ] } },
  'The figures are the most commonly cited; some sources and periods differ. Besides pay, soldiers received **donatives** (donativa) at accessions and victories, **spoils of war** and, at the end of service, the **discharge bonus** (praemia) in money or land. They could also save, thanks to the legion’s bank and the burial club.',
  { h: 'Marriage and family' },
  'Until Septimius Severus, serving soldiers **could not legally marry**, but many lived with partners and had children, who were not considered legitimate. On discharge, the auxiliary’s diploma recognised any marriage he had made. Civilian settlements (canabae and vici) grew up around the camps, where families, traders and craftsmen lived, and which often became towns.',
  { h: 'The legionary’s equipment' },
  'The Roman soldier used standardised equipment, state-made or licensed. The models changed over the centuries, but the basic set was:',
  { lista: [
    '**Helmet** (galea) of iron or bronze, with neck guard and cheek pieces; several types (Montefortino, Coolus, Imperial Gallic, Imperial Italic).',
    '**Armour:** mail shirt (lorica hamata), scale (squamata) or articulated plates (lorica segmentata), the latter attested from c. AD 9 (Kalkriese).',
    '**Shield** (scutum), curved and rectangular, of glued layers of wood, covered with leather and with a metal boss (umbo).',
    '**Short sword** (gladius), with a blade of about 40 to 55 cm, used for thrusting; **dagger** (pugio).',
    '**Javelin** (pilum), about 2 m long, with a soft iron shank that bent after striking, so that the enemy could not throw it back.',
    '**Sandals** (caligae), with hobnails in the soles, and a woollen tunic.'
  ] },
  { img: 'rex-lorica-segmentata', leg: 'Remains and reconstruction of lorica segmentata from the Corbridge Hoard, Corbridge Museum.' },
  { img: 'rex-gladius', leg: 'Mainz-type gladius with scabbard, known as the Sword of Tiberius, British Museum.' },
  { img: 'rex-capacete-galico', leg: 'Roman iron helmet from Valkenburg, Imperial Gallic type, Rijksmuseum van Oudheden, Leiden.' },
  { img: 'rex-escudo-dura', leg: 'Painted Roman shield from Dura-Europos (Yale 1933.715), archival photograph taken in 1934, before restoration.' },
  { h: 'The load' },
  'On the march each legionary carried his weapons, armour, tools (spade, pickaxe, saw, basket), cooking utensils, rations for several days and a palisade stake, all tied to a pole (furca) and carried on his back, which was called the sarcina. The total weight was about **25 to 30 kg**, or more. According to Vegetius, the standard march was 20 Roman miles (about 30 km) in five summer hours.',
  { h: 'Training and discipline' },
  'Recruits began with **marches and exercises with wooden weapons** (twice the weight of real ones), swimming, riding, and then manoeuvres in formation. Even veterans trained regularly, on special grounds and in amphitheatres. Josephus says, in essence, that the Romans’ drills were bloodless battles and their battles bloody drills. Discipline was harsh: **decimation** (decimatio), in which one soldier in ten was executed by lot, was rare; the **cudgelling** (fustuarium) punished desertion and abandoning one’s post. Other penalties: fines, demotion, extra duties, barley rations.',
  { h: 'The camp' },
  'The army marched by day and **built a fortified camp every night**: a ditch, an earth rampart and stakes and a palisade in a rectangle, with four gates, two main crossing streets and a space for the general (praetorium), the tents laid out in fixed order. In a few hours thousands of soldiers did the work. In permanent fortresses the same plan was made in stone, with the principia (headquarters), hospital, granaries, baths and barracks for the centuries. A legionary fortress covered about 20 ha.',
  { img: 'rex-castra-planta', leg: 'Drawn diagram. Educational plan of a legionary fortress, c. AD 100: generic arrangement with four gates, principia, commander’s residence, hospital, granaries and barracks; not to scale.' },
  { img: 'rex-acampamento-marcha', leg: 'AI-generated illustration. Roman marching camp, first century AD: artistic interpretation.' },
  { h: 'The march and the roads' },
  'Roman roads were, first of all, **military roads**: they allowed legions and supplies to be moved. They were built by the soldiers themselves, with layers of stone and gravel, side ditches and milestones. The **Via Appia** (312 BC) was the most famous. Over rivers, military engineers built pontoon or timber bridges: Caesar bridged the Rhine in ten days (55 BC), and Trajan’s bridge over the Danube at Drobeta (c. AD 105), designed by Apollodorus of Damascus, was one of the largest of antiquity.',
  { img: 'rex-via-appia', leg: 'Via Appia Antica, Rome.' },
  { h: 'The legionary’s life' },
  'A normal day included reveille, parade, duties, training, a meal and watches. The basic food was wheat (boiled into porridge or baked into bread), with olive oil, sour wine (posca), meat (often pork or beef), cheese and fish, and beer in the northern provinces. The **Vindolanda** tablets show real life: requests for beer, socks and underwear, letters from friends, a strength report, a birthday invitation written by one woman (Claudia Severa) to another (Sulpicia Lepidina). Soldiers sometimes despised the natives: one tablet refers to the “wretched little Britons” (Brittunculi).',
  { img: 'rex-vida-quartel', leg: 'AI-generated illustration. Life in Roman barracks, c. AD 100: artistic interpretation.' },
  { h: 'Tactics' },
  'In battle the legion usually formed in **three lines** (triplex acies), with gaps so that the front soldiers could be replaced by those behind. On contact, the Romans threw the pilum at short range and advanced with shield and gladius. The **cavalry** protected the flanks and pursued fugitives. To resist arrows, soldiers used the **tortoise** (testudo), with shields at the front and overhead. There were other formations: the **wedge** (cuneus), to break through, and the **circle** (orbis), when surrounded. Victory came from training, from a reserve of fresh troops and from the ability to retreat without breaking up.',
  { img: 'rex-manipulo-esquema', leg: 'Drawn diagram. Manipular legion in triplex acies: hastati in red, principes in ochre, triarii in blue; velites in front and cavalry on the flanks. Simplified diagram, not to scale.' },
  { h: 'Sieges' },
  'The Romans were specialists in sieges. The main methods were the **blockade** (circumvallation, as at Alesia and Numantia), the **assault** with ladders and **siege towers**, the **ram** (aries) against gates and walls, protected by mobile shelters (vineae, testudines), the **mine** under the walls and the **ramp** (Masada). The defenders answered with countermines, boiling oil, fire and stones.',
  { img: 'rex-torre-cerco', leg: 'AI-generated illustration. Machines and formations in a Roman siege, first century AD: artistic interpretation.' },
  { h: 'Artillery' },
  'Roman artillery (tormenta) was **torsion** artillery, powered by twisted bundles of sinew or hair. The **ballista** fired large bolts or stones; the **scorpio** was a small field ballista, very accurate; the **onager** (the name is attested only in the fourth century, in Ammianus Marcellinus) hurled stones with an arm. Each legion is thought to have had dozens of these machines (Vegetius mentions 55 carroballistae and 10 onagers, a doubtful figure), with a range of a few hundred metres.',
  { img: 'rex-balista', leg: 'Modern reconstruction of a Roman ballista at Gamla, Israel.' },
  { h: 'The navy' },
  'Rome became a naval power only in the **First Punic War** (264–241 BC). The fleet used **triremes** (three banks of rowers) and **quinqueremes** (the exact arrangement of the rowers is debated), and the tactic was **ramming** or **boarding**, with the corvus. Augustus created two **permanent fleets**, at **Misenum** and **Ravenna**, and later others: British, German, Pannonian, Moesian, Syrian, Alexandrian. The sailors, serving 26 years, had lower status than the legionaries. The fleet fought little, but patrolled rivers and seas, fought piracy and carried troops and supplies.',
  { img: 'rex-trireme', leg: 'AI-generated illustration. Roman trireme: artistic reconstruction with conjectural oar arrangement.' },
  { img: 'rex-relevo-praeneste', leg: 'Palestrina relief depicting a Roman warship, Vatican Museums.' },
  { img: 'rex-corvus', leg: 'AI-generated illustration. Corvus boarding in the First Punic War: conjectural interpretation of the mechanism.' },
  { h: 'Military engineering' },
  'Soldiers were also builders. The legions had engineers (architecti), surveyors, smiths and carpenters. They built **roads, bridges, aqueducts, forts, walls** (such as Hadrian’s) and **canals**. On campaign the army carried machines in pieces and made parts on the spot. The ramp at Masada and Trajan’s bridge show the scale of the work.',
  { h: 'Religion and honours' },
  'The army had its own religion: the **standards** (eagle, signa, vexilla) were sacred and kept in a small shrine in the headquarters, and losing them was a disgrace. The legion’s birthday and the emperor’s were celebrated, and his image was venerated. Soldiers worshipped Jupiter, Mars, Victory, local Matres and, among the officers, the Persian god **Mithras**, to whom there are mithraea beside Hadrian’s Wall. Brave soldiers received **decorations** (dona militaria): collars (torques), armbands (armillae), discs (phalerae) and **crowns**: the corona civica (for saving a citizen’s life), the corona muralis (for being first over a wall).',
  { img: 'rex-lapide-flavino', leg: 'Tombstone of Flavinus, standard-bearer of a cavalry ala, Hexham Abbey.' },
  { h: 'The triumph' },
  'A victorious general could be granted a **triumph**, a solemn parade through Rome with the prisoners, the spoils and the soldiers, climbing to the Capitol. It was an enormous honour, granted by the Senate: the general wore special dress and had behind him, according to tradition, a slave who reminded him that he was mortal. Under the Empire triumphs came to be reserved for the imperial family. The **Arch of Titus** in Rome commemorates the triumph over Judaea.',
  { h: 'Military medicine' },
  'The large fortresses had **hospitals** (valetudinaria), with wards and operating rooms, as seen at Vindonissa (Switzerland) and Carnuntum (Austria). There were army doctors, and the Greek **Dioscorides**, author of the treatise on medicinal plants, is thought to have served as an army doctor. Soldiers had hygiene facilities (baths, latrines) and even so disease was the main cause of death.',
  { h: 'The end of service' },
  'After 20 to 25 years the soldier was discharged and received his bonus in money or in land, often in a **veteran colony**, such as Colonia Agrippina (Cologne), Camulodunum (Colchester) and **Augusta Emerita** (Mérida). Veterans were among the most respected citizens, sometimes local magistrates, and spread Roman language and culture.',
  { h: 'Rome’s enemies' },
  { tabela: { cab: ['Enemy', 'Period', 'How they fought'], linhas: [
    ['Samnites and Etruscans', '4th – 3rd c. BC', 'Mountain infantry, ambushes; fortifications.'],
    ['Carthaginians', '3rd – 2nd c. BC', 'Powerful fleet, mercenaries, Numidian cavalry, elephants; Hannibal.'],
    ['Hellenistic kingdoms', '3rd – 2nd c. BC', 'Macedonian phalanx, elephants, heavy cavalry.'],
    ['Gauls and Germans', '1st c. BC – 4th c. AD', 'Mass warriors, great courage; ambush warfare in the Germanic case.'],
    ['Parthians and Sasanian Persians', '1st c. BC – 7th c. AD', 'Heavy cavalry (cataphracts) and horse archers.'],
    ['Dacians', '1st – 2nd c. AD', 'Mountain fortresses, the Dacian falx.'],
    ['Late “barbarian” peoples', '3rd – 5th c. AD', 'Goths, Franks, Alamanni, Vandals, Huns: large bands, often former allies.']
  ] } },
  'The Roman image of the “barbarians” is the one in the Roman sources, generally prejudiced. Many of these peoples negotiated, served in the army and ended up as Rome’s heirs.',
  { h: 'Military writings' },
  'There are several ancient **military treatises**: that of **Polybius** (Book VI of the Histories, c. 150 BC) on the Republican army; the Commentaries of **Caesar**; the Strategemata of **Frontinus** (first century); the De re militari of **Vegetius** (late fourth or early fifth century AD), an idealised reconstruction of the old legion, which was read throughout the Middle Ages but is **not reliable** for the legion of the Principate; and the Notitia Dignitatum, a list of units and commands of the late Empire.',
  { h: 'Myths about the Roman army' },
  { lista: [
    'The legion **“IX Hispana”** was not demonstrably wiped out in Scotland: it was at York until c. 108 and tile stamps at Nijmegen suggest a later presence on the Rhine, but it is debated whether this was the whole legion. Its final fate is **unknown**.',
    'The **tortoise** (testudo) was **not** the usual formation: it was a special formation, used above all in sieges and against arrows.',
    'Not all legionaries wore the plate armour of the films: **mail** remained in use throughout the Empire.',
    'The army was **not** made up only of Italians: from the second century AD most legionaries were of provincial origin.'
  ] }
];

const personalidades = [
  'These fourteen figures (eleven Romans and three opponents) were chosen for their military importance. Dates are the usual ones; where something is legend or debate, we say so. For full political biographies of the emperors, see the page “Emperors and great figures”.',
  { h: 'Scipio Africanus (c. 236 – 183 BC)' },
  '**Publius Cornelius Scipio** captured Cartagena (Carthago Nova) in 209 BC, defeated the Carthaginians at Ilipa (206) in Spain, and took the war to Africa, where he defeated Hannibal at **Zama (202 BC)**. He mastered tactics of flexibility and envelopment, which he learned from his opponent. His career ended in political disputes in Rome, and he died in retirement.',
  { h: 'Gaius Marius (c. 157 – 86 BC)' },
  'Born at Arpinum, he was consul **seven times** (107, 104–100 and 86 BC). He finished the war against Jugurtha and then defeated the Cimbri and Teutones at Aquae Sextiae and Vercellae (102 and 101 BC). He is associated with opening the army to the poor and with several changes of equipment, although many of these are earlier. He entered a civil war with Sulla and died a few days after beginning his seventh consulship.',
  { h: 'Lucius Cornelius Sulla (138 – 78 BC)' },
  'A commander in the Social War and the war against Mithridates (he won at Chaeronea, 86 BC). In 88 BC he was the first to lead legions against Rome. Dictator from 82 to 79 BC, he reformed the state in favour of the Senate and resigned, which is rare in Roman history.',
  { h: 'Julius Caesar (100 or 102 – 44 BC)' },
  'He commanded eight years of campaigns in Gaul, wrote their history (the Commentaries) and won the civil war at Pharsalus (48 BC). He was known for speed, for his skill at construction (the bridge over the Rhine, the siege of Alesia) and for his relationship with his soldiers, who followed him as they followed no one else. He was assassinated on the Ides of March, 44 BC.',
  { img: 'rex-cesar-busto', leg: 'Tusculum-type portrait of Julius Caesar, Turin Museum of Antiquities.' },
  { h: 'Marcus Vipsanius Agrippa (63 – 12 BC)' },
  'Friend and son-in-law of Augustus, he was the **admiral** who defeated Sextus Pompey at Naulochus (36 BC) and Mark Antony at Actium (31 BC). He built roads, aqueducts, baths and the first Pantheon. He is perhaps the most important general of the early Empire, and almost forgotten for having stood in the emperor’s shadow.',
  { h: 'Gnaeus Domitius Corbulo (c. AD 7 – 67)' },
  'A general under Claudius and Nero. He disciplined the legions on the Rhine and, in the East (AD 58–63), conducted the war against the Parthians over Armenia. Nero, suspicious, forced him to commit suicide.',
  { h: 'Gnaeus Julius Agricola (AD 40 – 93)' },
  'Governor of Britain (AD 77–84), he conquered northern England and part of Scotland. We know him from the biography written by his son-in-law, the historian **Tacitus**, which idealises him. Tacitus credits him with the victory at Mons Graupius.',
  { h: 'Trajan (AD 53 – 117)' },
  'A soldier emperor, born at Italica (Hispania). He conquered Dacia (101–106) and attacked the Parthians (113–117), bringing the Empire to its greatest extent. He spent much of his reign on campaign with the soldiers. Trajan’s Column is the greatest monument to the Roman army.',
  { h: 'Aurelian (c. AD 214 – 275)' },
  'Emperor from 270 to 275. He defeated the Goths and the Alamanni, beat the Palmyrene Empire (272–273) and the Gallic Empire (274), reunifying a state that seemed to have fallen apart. He had the **walls of Rome** built (271–275). He was assassinated by officers, according to tradition because of a misunderstanding (a story of doubtful reliability).',
  { h: 'Stilicho (c. AD 359 – 408)' },
  'Son of a Vandal father and a Roman mother, he was the West’s **supreme commander** (magister militum) under Honorius. He defeated Alaric’s Goths at Pollentia (402, outcome debated) and Radagaisus at Faesulae (406). On 31 December 406, Vandals, Alans and Suebi crossed the Rhine. Honorius had him executed in 408; two years later Alaric sacked Rome.',
  { h: 'Flavius Aetius (c. AD 391 – 454)' },
  'Some modern historians have called him “the last of the Romans”. With Gothic and other allies, he stopped Attila’s expansion at the **Catalaunian Plains** (451). He was killed in 454 by the emperor Valentinian III himself.',
  { h: 'Hannibal Barca (247 – c. 183 BC)' },
  'The Carthaginian commander who crossed the Alps in 218 BC and defeated the Romans at Cannae. He stayed 15 years in Italy without taking Rome. Defeated at Zama, he went into exile and in the end committed suicide, in Bithynia, rather than be handed over to the Romans. He was Rome’s greatest adversary.',
  { h: 'Viriathus (d. 139 BC)' },
  'Chief of the Lusitanians between 147 and 139 BC. According to Appian, he was a shepherd and hunter who became a leader; he defeated several Roman generals with guerrilla tactics. He was killed in his sleep by three companions, bribed by the consul Quintus Servilius Caepio. For the Portuguese he is a symbol of resistance, although the historical figure is known only from Roman and Greek sources written after the events, such as Appian and Diodorus.',
  { h: 'Arminius (c. 17 BC – AD 21)' },
  'Chief of the Cherusci, he served in the Roman army and was a citizen and an equestrian. He organised the Teutoburg ambush (AD 9). He later fought Germanicus and his rival Maroboduus. He was killed by relatives in AD 21. His figure was used in nineteenth-century German nationalism, which distorted his image.'
];

const legado = [
  { h: 'What the army left' },
  { lista: [
    '**Frontiers and forts:** Hadrian’s Wall, the Upper German–Raetian limes and hundreds of forts are today UNESCO heritage (“Frontiers of the Roman Empire”).',
    '**Cities:** many European cities grew from camps or veteran colonies: Cologne, Mérida, York, Chester, Vienna, Budapest, Xanten.',
    '**Roads and bridges:** the road network, with its military logic, determined routes still in use.',
    '**Words:** legion, cohort, centurion, camp (from campus), castle and castro (from castrum), army (from exercitus), soldier (from solidus, the coin in which pay was later reckoned), military (from miles).',
    '**Organisation:** hierarchy, units of fixed size, regular training, supply services and military engineering.'
  ] },
  { img: 'rex-arco-tito', leg: 'Arch of Titus relief depicting spoils from the Temple of Jerusalem, Rome.' },
  { h: 'Trajan’s Column' },
  'Dedicated in AD 113 in Trajan’s forum in Rome, it is about 30 m high (35 m with the pedestal), with a spiral frieze of about 190 m and more than 2,500 figures telling the Dacian wars. It is the best picture of the Roman army in action: soldiers building forts, crossing rivers, fighting and tending the wounded. Historians debate how far it is propaganda; it is, in any case, a source of the first importance.',
  { h: 'The Vindolanda tablets' },
  'Discovered from 1973, they are hundreds of small leaves of wood written in ink, c. AD 85 to 130. They are among the oldest surviving handwritten documents in Britain, and give a direct voice to soldiers and their families. Today the main collection is in the **British Museum**; the archaeological site of Vindolanda can be visited.',
  { h: 'Teutoburg and the archaeology of battlefields' },
  'Modern archaeology has identified battlefields (**Kalkriese**, the Harzhorn battlefield (c. AD 235) in Germany, Alesia, Masada). The **Kalkriese Museum and Park**, near Osnabrück, shows the rampart, weapons and coins. Archaeology shows a real army, different from the Hollywood image.',
  { h: 'What is World Heritage' },
  'Since 1987 (Hadrian’s Wall), UNESCO has been adding stretches of the **limes** to the World Heritage List: the Upper German–Raetian limes (2005), the Antonine Wall (2008), and, in 2021, the Lower Rhine limes and the western Danube limes. It is one of the largest transnational sites.',
  { h: 'Vegetius and the Middle Ages' },
  'Vegetius’ De re militari was copied and read throughout the Middle Ages, and then by Renaissance generals (Machiavelli, Maurice of Nassau). The image of an exemplary, disciplined legion passed into European military theory, even though Vegetius wrote long after the age of the classical legion.',
  { h: 'Where to visit' },
  { lista: [
    '**Hadrian’s Wall and Vindolanda** (England); **Caerleon** (Wales).',
    '**Saalburg**, **Xanten** (Archaeological Park) and **Kalkriese** (Germany); **Carnuntum** (Austria).',
    '**Alesia** (France): museum and site of the siege lines, and **Masada** (Israel).',
    '**Trajan’s Column**, the **Arch of Titus** and the **Castra Praetoria**, in Rome.',
    '**Mérida** (National Museum of Roman Art) and **León** (Spain), and the **Conímbriga Monographic Museum** (Portugal), for military and civilian life in the Peninsula.'
  ] },
  { h: 'Modern Roman armies' },
  '**Historical reenactment** groups (in England, Germany, Italy and other countries) recreate equipment, marches and camps, and have helped historians test the weight of weapons, the resistance of shields and life on campaign. The results are useful, but do not replace the sources.',
  { h: 'A lesson from history' },
  'The army that conquered the Mediterranean suffered terrible defeats and recovered from them; its strength came less from individual courage than from **organisation, training, logistics and the ability to learn from its opponents**. It also shows how a standing army can be decisive in politics: the power of generals and soldiers weighed on the institutions of the Republic and the Empire.',
  { h: 'The fall of the Western army' },
  'The Western army weakened over the fifth century, with losses of provinces and revenue, defeats, civil wars and growing use of **federates** with their own chiefs. Historians debate the causes (economic, political, demographic, military). The Eastern army, better financed, continued, under the Byzantine Empire, for more than a thousand years.'
];

const quiz = [
  { p: 'Roughly how many men did a legion of the Principate have?', op: ['500', '1,500', '5,000 to 5,500', '20,000'], certa: 2, exp: 'About 5,000 to 5,500 men, divided into 10 cohorts.' },
  { p: 'How many men did a century have, in theory?', op: ['10', '480', '80', '1,000'], certa: 2, exp: 'About 80 men, commanded by a centurion; six centuries made a cohort.' },
  { p: 'Who recruited propertyless volunteers for the army, from 107 BC?', op: ['Gaius Marius', 'Sulla', 'Caesar', 'Augustus'], certa: 0, exp: 'Gaius Marius, during the war against Jugurtha; historians see the change as gradual.' },
  { p: 'Which battle, in 216 BC, was one of the greatest Roman defeats, with about 70,000 dead according to Polybius?', op: ['Zama', 'Pydna', 'Cannae', 'Pharsalus'], certa: 2, exp: 'At Cannae, Hannibal enveloped the Roman army with his wings and cavalry.' },
  { p: 'What was the legionary’s curved shield called?', op: ['Clipeus', 'Scutum', 'Parma', 'Aspis'], certa: 1, exp: 'The scutum, curved and rectangular, made of glued layers of wood.' },
  { p: 'What was the legionary’s short sword?', op: ['Spatha', 'Falx', 'Pugio', 'Gladius'], certa: 3, exp: 'The gladius; the longer spatha was adopted later, above all by the cavalry; the pugio was the dagger.' },
  { p: 'What was the “pilum” for?', op: ['It was a sword', 'It was a javelin that bent when it struck', 'It was a siege machine', 'It was a helmet'], certa: 1, exp: 'The pilum was a javelin with a soft iron shank that bent, making the enemy shield useless.' },
  { p: 'Which siege of 52 BC involved two lines of fortification, one facing inwards and one outwards?', op: ['Alesia', 'Masada', 'Jerusalem', 'Numantia'], certa: 0, exp: 'At Alesia, Caesar besieged Vercingetorix and repelled the relief army.' },
  { p: 'Who commanded the three legions destroyed in the Teutoburg Forest, in AD 9?', op: ['Germanicus', 'Arminius', 'Agricola', 'Publius Quinctilius Varus'], certa: 3, exp: 'Varus was ambushed by Arminius, who had been a Roman officer.' },
  { p: 'Roughly how many kilometres long was Hadrian’s Wall?', op: ['40', '117', '500', '1,000'], certa: 1, exp: 'About 80 Roman miles, or 117 km, begun around AD 122.' },
  { p: 'What are the Vindolanda tablets?', op: ['Military laws engraved in bronze', 'Maps of the frontiers', 'Letters and lists written in ink on wood, by soldiers and families', 'Battle plans'], certa: 2, exp: 'Hundreds of wooden leaves of c. AD 85–130, found near Hadrian’s Wall.' },
  { p: 'Who created the permanent fleets of Misenum and Ravenna?', op: ['Pompey', 'Caesar', 'Augustus', 'Trajan'], certa: 2, exp: 'Augustus, after Actium.' },
  { p: 'Which emperor disbanded the Praetorian Guard, in 312?', op: ['Diocletian', 'Constantine', 'Aurelian', 'Septimius Severus'], certa: 1, exp: 'Constantine, after defeating Maxentius, whom the Praetorians supported.' },
  { p: 'Which battle of 378 destroyed the eastern army and killed the emperor Valens?', op: ['Adrianople', 'Carthage', 'Milvian Bridge', 'Catalaunian Plains'], certa: 0, exp: 'At Adrianople, the Goths destroyed much of the Roman army of the East.' },
  { p: 'What is true of Legio IX Hispana?', op: ['It was wiped out in Scotland in 117, as is proven', 'It was disbanded by Constantine', 'Its final fate is unknown; the myth of its annihilation in Scotland is unproven', 'It never existed'], certa: 2, exp: 'There is proof of the legion at York in 108 and, afterwards, possible traces on the Rhine (Nijmegen); its end is uncertain.' }
];

export default { visao, linha, mapa, sociedade, personalidades, legado, quiz };
