// EGYPT — PREDYNASTIC AND OLD KINGDOM — full English content. Same structure and same image slots as the Portuguese version (dados.js).
// Chronology: conventional dates of the English-language reference works (Old Kingdom, Dynasties 3–6, c. 2686 – 2181 BC; Early Dynastic Period c. 3150 – 2686 BC). Hornung, Krauss and Warburton (2006) propose somewhat later dates for the Old Kingdom; before c. 2000 BC all dates carry margins of decades or more, hence “c.”.

const visao = [
  { caixa: 'In brief', texto: [
    'This page tells the first nearly three thousand years of Egypt, from the farming villages of the Nile valley (around 5000 BC) to the end of the **Old Kingdom** (c. 2181 BC). It is the time when the first great territorial state in history took shape: King **Narmer** (c. 3100 BC) is associated with the unification of Upper and Lower Egypt, hieroglyphic writing appears, and the capital is founded at **Memphis**.',
    'In the Old Kingdom proper, the Egyptian state mobilised thousands of people, covered the limestone and granite deserts with quarries and roads, and built the **pyramids**: Djoser’s step pyramid at Saqqara (c. 2670 BC), the three pyramids of **Sneferu**, and, at Giza, those of **Khufu**, **Khafre** and **Menkaure**. It was the age of the “pyramid builders”, of the first religious texts of humankind (the Pyramid Texts) and of an administration so efficient that it left papyrus records more than 4,500 years old.'
  ] },
  { img: 'eai-mapa-egito', leg: 'Map of ancient Egypt with the valley, Delta and sites from different dynastic periods; it does not represent only the Old Kingdom.' },
  { h: 'Where it was' },
  'Ancient Egypt was a long oasis within the desert: a narrow strip of black soil, **Kemet** (“the Black Land”), on either side of the Nile, surrounded by **Deshret**, “the Red Land”, the desert. The river flows from south to north and, near modern Cairo, opens into a fan of branches, the **Delta**. For the Egyptians the country had two halves: **Upper Egypt** (the valley, in the south) and **Lower Egypt** (the Delta, in the north). This idea of “the Two Lands” stayed in the king’s titles for three thousand years.',
  'The river decided everything. Every year, between July and October, the Nile overflowed, left fertile silt on the fields and withdrew, leaving land ready for sowing. No rain was needed. So Egypt produced grain surpluses with little effort, and it was easy to govern from a central point: the river was the road, and a boat drifted downstream or sailed upstream with the north wind.',
  { img: 'eai-colheita-nilo', leg: 'Emmer wheat harvest beside the Nile around 2500 BC; imagined Old Kingdom scene. AI-generated illustration.' },
  { h: 'When it existed' },
  'Egyptologists divide Egyptian history into kingdoms and intermediate periods, and arrange the kings in **31 dynasties** (a system inherited from the priest Manetho, 3rd century BC). This page covers the following phases, with approximate dates.',
  { tabela: { cab: ['Phase', 'Approximate dates', 'What marks it'], linhas: [
    ['Neolithic', 'c. 5500 – 4400 BC', 'First farming villages: Fayum A and Merimde (Delta)'],
    ['Early Predynastic', 'c. 4400 – 3500 BC', 'Badarian and Naqada I cultures in Upper Egypt; copper and fine pottery'],
    ['Late Predynastic (Naqada II – III)', 'c. 3500 – 3150 BC', 'Chiefdom-towns such as Hierakonpolis; powerful chiefs; first signs of writing'],
    ['Dynasty 0 and Early Dynastic Period (Dynasties 1 – 2)', 'c. 3150 – 2686 BC', 'Narmer and the unification; Memphis; royal tombs at Abydos; state and administration'],
    ['Old Kingdom (Dynasties 3 – 6)', 'c. 2686 – 2181 BC', 'Djoser and the step pyramid; Age of the Pyramids; Pyramid Texts; decentralisation'],
    ['End of the Old Kingdom (Dynasties 7 – 8)', 'c. 2181 – 2160 BC', 'Short-lived kings at Memphis; many authors already place them in the First Intermediate Period']
  ] } },
  { img: 'eai-giza-panorama', leg: 'The three pyramids of Giza seen from the desert.' },
  { h: 'Who were the Egyptians of this time?' },
  'The Egyptians of the Old Kingdom descended from populations of the Nile valley, of the eastern and western deserts (which became arid through the Neolithic) and of the Delta, where there were contacts with the Levant. They spoke **Old Egyptian**, a language of the Afro-Asiatic family, and wrote it in hieroglyphs. The culture was not uniform: the south (Naqada, Hierakonpolis, Abydos) created the kingship and the artistic style that became “Egyptian”, and the north (Merimde, Maadi) had its own customs and pottery, absorbed into the unified state.',
  { img: 'eai-aldeia-predinastica', leg: 'Naqada-culture village beside the Nile around 3600 BC; hypothetical reconstruction. AI-generated illustration.' },
  'It is estimated that, in the time of the great pyramids, Egypt had between one and two million inhabitants, the great majority of them farmers. The figures are very uncertain.',
  { h: 'Why they matter' },
  { lista: [
    '**The first territorial state:** one king, one administration and one language, from Elephantine to the Mediterranean, about a thousand kilometres of river, c. 3100 BC. It was one of the first states in the world and lasted, with interruptions, three thousand years.',
    '**Writing:** hieroglyphs appear around 3300 – 3200 BC and, in the Old Kingdom, already serve administration, biographies, hymns and rituals.',
    '**Stone architecture:** Imhotep and his successors invented the monumental building in cut stone, and the Giza pyramids were the tallest structures made by humans for about 3,800 years (until the medieval cathedrals).',
    '**The idea of divine kingship:** the king as the living Horus, son of Ra, responsible for maintaining the order of the world (**ma’at**).',
    '**The first religious texts:** the Pyramid Texts (c. 2350 BC) are the oldest known collection of religious writings.',
    '**The workers:** the excavation of their villages and cemeteries showed that the pyramids were built by organised, well-fed Egyptians, not by “slaves”.'
  ] },
  { caixa: 'Old Kingdom Egypt today', texto: 'The pyramid fields of **Memphis and its surroundings** (from Giza to Dahshur) were inscribed on the UNESCO World Heritage List in 1979. The **Grand Egyptian Museum**, next to Giza, officially opened in November 2025 and holds many objects from this period. This page is only one of nine pages on Egypt; for the later periods, see “First Intermediate and Middle Kingdom”, “Second Intermediate and New Kingdom” and the others.' }
];

const linha = [
  'This timeline runs from the Neolithic to the end of the Old Kingdom. Before c. 2000 BC the dates are approximate and vary from author to author; we follow the conventional dates used in reference works. The identification of the earliest kings is partly debated.',
  { linha: [
    { d: 'c. 5500 – 4400 BC', t: 'The first farming villages', x: 'At **Fayum** lake and at **Merimde Beni Salama** (Delta), communities grow wheat and barley and keep cattle, sheep and goats, drawing on farming practices from the Near East. It is the beginning of settled life in Egypt.' },
    { d: 'c. 4400 – 4000 BC', t: 'The Badarian culture', x: 'At **Badari**, in Upper Egypt, fine black-topped pottery, ivory and copper objects and tombs appear that show the first signs of social difference.' },
    { d: 'c. 4000 – 3500 BC', t: 'Naqada I', x: 'Ever larger settlements in the south, with white-on-red decorated pottery and trade with the desert and the Red Sea (shells, hard stones).' },
    { d: 'c. 3500 – 3200 BC', t: 'Naqada II: the first chiefs', x: 'At **Hierakonpolis** (Nekhen), **Naqada** and **Abydos** live rich chiefs, with large tombs. At Hierakonpolis, “Tomb 100” is decorated with painted scenes of boats and hunting. Objects and ideas are imported from Mesopotamia and the Levant.' },
    { d: 'c. 3320 – 3150 BC', t: 'The first signs of writing', x: 'In tomb U-j at **Abydos**, belonging to an Upper Egyptian chief, labels of bone and ivory with incised signs were found. It is the earliest evidence of writing in Egypt, and one of the earliest in the world (its reading is debated).' },
  ] },
  { img: 'eai-macehead-escorpiao', leg: 'Scorpion king\'s macehead, Ashmolean, Oxford.' },
  { linha: [
    { d: 'c. 3200 – 3100 BC', t: 'Dynasty 0', x: '“Dynasty 0” is the name given to the chiefs and kings of the end of the Predynastic, such as **Ka**, **Scorpion** and **Iry-Hor**, of whom few names and objects survive. How they were related is unknown. The small chiefdoms of the south merge into a kingdom.' },
    { d: 'c. 3100 BC', t: 'Narmer and the “unification”', x: 'King **Narmer** is shown on the famous **Narmer Palette** with the white crown of Upper Egypt on one side and the red crown of Lower Egypt on the other. Later tradition speaks of a king **Menes** who united the country; his identification with Narmer (or with his successor Hor-Aha) is debated. The “unification” was probably a process of generations, not a single battle.' },
  ] },
  { img: 'eai-paleta-narmer', leg: 'Narmer Palette, Egyptian Museum, Cairo (JE 32169).' },
  { img: 'eai-unificacao-cena', leg: 'Royal ceremony in Narmer\'s time around 3100 BC, Hierakonpolis; imagined scene. AI-generated illustration.' },
  { linha: [
    { d: 'c. 3100 – 2900 BC', t: 'Hor-Aha and the capital at Memphis', x: 'According to tradition, the city of **Memphis** (“the White Walls”) is founded in this period, where the valley meets the Delta. The kings of the 1st Dynasty are buried at **Abydos**, in the Umm el-Qaab tombs, and the great dignitaries at Saqqara.' },
    { d: 'c. 3000 – 2900 BC', t: 'Den and Merneith', x: 'Queen **Merneith** seems to have ruled as regent for her son **Den**, of whom a depiction wearing the double crown survives. The kings of the 1st Dynasty rule over an organised state, with officials, tax collection and expeditions to the mines of Sinai.' },
  ] },
  { img: 'eai-faca-gebel-el-arak', leg: 'Gebel el-Arak Knife, Louvre.' },
  { img: 'eai-estela-djet', leg: 'Stele of Djet, Louvre.' },
  { linha: [
    { d: 'c. 2890 – 2686 BC', t: 'The 2nd Dynasty', x: 'A poorly documented period. The kings continue to be buried at Abydos or at Saqqara. **Peribsen** uses the name of **Seth** instead of Horus, perhaps because of internal conflict; **Khasekhemwy**, the last king, uses both gods together and closes the period, reunifying the country.' },
    { d: 'c. 2686 BC', t: 'The Old Kingdom begins', x: 'The **3rd Dynasty** opens the Old Kingdom. The first kings, such as Nebka and Sanakht, are poorly known. With **Djoser** Egypt enters an age of great stone works.' },
    { d: 'c. 2670 BC', t: 'Djoser and the step pyramid', x: 'King **Djoser** and his minister **Imhotep** build, at Saqqara, a funerary complex entirely of cut stone, with a six-step pyramid about 62 m high: the first great stone monument in Egypt.' },
  ] },
  { img: 'eai-estatua-djoser', leg: 'Djoser\'s serdab statue, Egyptian Museum, Cairo.' },
  { img: 'eai-construcao-djoser', leg: 'Construction of Djoser\'s complex around 2670 BC; artistic reconstruction of partially uncertain methods. AI-generated illustration.' },
  { linha: [
    { d: 'c. 2613 – 2589 BC', t: 'Sneferu, the great builder', x: 'The first king of the **4th Dynasty** rules for about 24 years. He builds or completes the pyramids of **Meidum**, the **Bent** and the **Red** (the latter the first smooth-sided pyramid with a uniform angle), sending expeditions to Lebanon for cedar and to Nubia.' },
    { d: 'c. 2589 – 2566 BC', t: 'Khufu and the Great Pyramid', x: 'Sneferu’s son builds at **Giza** the Great Pyramid, about 146 m high originally: the largest pyramid in Egypt. Little survives of his reign beyond the monument and an ivory statuette about 7.5 cm tall.' },
    { d: 'c. 2560 BC', t: 'The diary of Merer', x: 'Papyri found at **Wadi al-Jarf**, on the Red Sea (discovery announced in 2013), contain the diary of the team leader **Merer**, who transported limestone blocks from Tura to Giza for the casing of Khufu’s pyramid. They are the oldest inscribed papyri known.' },
    { d: 'c. 2558 – 2504 BC', t: 'Khafre and Menkaure', x: '**Khafre** (c. 2558 – 2532 BC) builds the second pyramid at Giza, with his valley temple; the **Sphinx** is usually attributed to him. **Menkaure** (c. 2532 – 2504 BC) builds the third, the smallest.' },
  ] },
  { linha: [
    { d: 'c. 2494 BC', t: 'The 5th Dynasty begins', x: '**Userkaf** inaugurates a dynasty with emphasis on the sun god **Ra**: he builds a sun temple and, from then on, the kings raise sun temples, while their pyramids become smaller and more poorly built.' },
    { d: 'c. 2487 – 2475 BC', t: 'Sahure and the sea expeditions', x: '**Sahure** builds his pyramid at **Abusir**. The reliefs of his temple show seagoing ships, and the expedition to **Punt**, a land of incense and resins in the south of the Red Sea, is recorded for the first time.' },
    { d: 'c. 2414 – 2375 BC', t: 'Djedkare Isesi and the administrative reform', x: 'In a long reign, the king reorganises the administration. It is the time of the vizier **Ptahhotep**, to whom tradition attributes the “Maxims”. The Abusir papyri (the archives of the temple of Neferirkare) testify to a sophisticated bureaucracy.' },
    { d: 'c. 2375 – 2345 BC', t: 'Unas and the Pyramid Texts', x: 'Inside the pyramid of **Unas**, the last king of the dynasty, the walls of the underground chambers are covered with hieroglyphs: the **Pyramid Texts**, the oldest collection of religious texts in the world.' },
  ] },
  { img: 'eai-pedra-palermo', leg: 'Palermo Stone, Archaeological Museum of Palermo.' },
  { linha: [
    { d: 'c. 2345 – 2181 BC', t: 'The 6th Dynasty: Teti, Pepi I and Merenre', x: 'The dynasty begins with **Teti** (Manetho says he was murdered by his guard, which is unconfirmed). The vizier **Weni**, who serves three kings, leads campaigns in Sinai and the Levant. The provincial governors (the nomarchs) become ever more powerful and autonomous.' },
    { d: 'c. 2278 – 2214 BC (or to c. 2184)', t: 'Pepi II, one of the longest-reigning kings', x: '**Pepi II** comes to the throne at about six years old. Ancient sources give him more than ninety years of reign (hence the “to c. 2184”); scholars doubt it, and many accept c. 64 years. It is one of the longest reigns in Egyptian history, and the last of the Old Kingdom with strong royal authority.' },
    { d: 'c. 2200 – 2150 BC', t: 'Drought and collapse of central power', x: 'Geological records point to a period of drought across the Near East (the “4.2 kiloyear event”), with weak Nile floods. At the same time, the governors’ offices become hereditary and the king loses resources. The relationship between the two phenomena is debated: the collapse was probably both political and climatic.' },
    { d: 'c. 2181 – 2160 BC', t: 'The 7th and 8th Dynasties', x: 'Short-lived kings rule at Memphis, the last of whom, **Ibi**, builds a small pyramid at South Saqqara, with Pyramid Texts. Manetho’s tradition speaks of “70 kings in 70 days”, certainly an exaggeration. Central power disappears: the **First Intermediate Period** follows (see the page “First Intermediate and Middle Kingdom”).' }
  ] }
];

const mapa = [
  'The Old Kingdom was a state centred on the region of **Memphis**, where the valley opens into the Delta. The great works, pyramids and temples, are concentrated in a strip of a few tens of kilometres (from Abu Rawash to Dahshur, with Meidum further south) along the west bank of the Nile, the “Land of the Dead”. Across the desert and along the river stretched the quarries, mines, roads and ports that sustained this building.',
  { tabela: { cab: ['Site', 'Region', 'Location today', 'Known for'], linhas: [
    ['Memphis (Ineb-hedj)', 'Lower Egypt (apex of the Delta)', 'Mit Rahina, near Cairo', 'Capital of the Old Kingdom; temple of Ptah; royal residence'],
    ['Saqqara', 'Lower Egypt', 'South of Cairo', 'Necropolis of Memphis; Djoser’s step pyramid; pyramid of Unas; tombs of dignitaries'],
    ['Giza', 'Lower Egypt', 'Plateau west of Cairo', 'Pyramids of Khufu, Khafre and Menkaure; Sphinx; workers’ town'],
    ['Abusir', 'Lower Egypt', 'Near Saqqara', '5th Dynasty pyramids and sun temples; Abusir papyri'],
    ['Dahshur', 'Lower Egypt', 'South of Saqqara', 'Sneferu’s Bent and Red Pyramids'],
    ['Meidum', 'Entrance to the Fayum', 'About 100 km south of Cairo', 'Pyramid of Huni/Sneferu; tombs with the statues of Rahotep and Nofret'],
    ['Abu Rawash', 'Lower Egypt', 'North of Giza', 'Pyramid of Djedefre, son of Khufu'],
    ['Heliopolis (Iunu)', 'Lower Egypt', 'North of Cairo', 'Centre of the cult of Ra; almost everything has disappeared'],
    ['Abydos', 'Upper Egypt', 'Near Sohag', 'Royal tombs of the 1st Dynasty (Umm el-Qaab); later the centre of the cult of Osiris'],
    ['Hierakonpolis (Nekhen)', 'Upper Egypt', 'Kom el-Ahmar', 'Predynastic capital; Narmer Palette and Scorpion macehead'],
    ['Naqada', 'Upper Egypt', 'Near Luxor', 'Site that gives its name to the Naqada I – III cultures'],
    ['Elephantine', 'Southern frontier', 'Near Aswan', 'Border fortress and port; departure of the expeditions to Nubia; tombs of the governors (Qubbet el-Hawa)'],
    ['Wadi al-Jarf', 'Red Sea coast', 'Near Zafarana', 'Oldest known harbour; papyri of the diary of Merer'],
    ['Sinai (Wadi Maghareh)', 'Sinai Peninsula', 'Southwest Sinai', 'Copper and turquoise mines; inscriptions of Old Kingdom kings'],
    ['Byblos (Kebny)', 'Outside Egypt', 'Jbeil, Lebanon', 'Port where the Egyptians obtained cedar; contacts since the 1st Dynasty'],
    ['Buhen', 'Nubia', 'Near Wadi Halfa, Sudan', 'Egyptian trading post in the Old Kingdom (copper); only partly known']
  ] } },
  { h: 'Memphis, the capital' },
  'According to tradition, **Memphis** was founded by King Menes (or Narmer) at the junction of Upper and Lower Egypt, c. 3100 BC. Its Egyptian name was **Ineb-hedj**, “the White Walls”; the name “Memphis” comes from Men-nefer, the name of the pyramid of Pepi I, which came to designate the city. It was the royal residence almost continuously during the Old Kingdom and after, and its god was **Ptah**, the god of craftsmen. Almost nothing remains today: only a few blocks, colossi and an open-air museum in the village of Mit Rahina, because the materials were reused by medieval Cairo. The city and its cemeteries were inscribed on the World Heritage List.',
  { img: 'eai-menfis-reconstrucao', leg: 'Memphis in the Old Kingdom around 2500 BC; conjectural reconstruction of poorly preserved architecture. AI-generated illustration.' },
  { h: 'Saqqara: the step pyramid' },
  'The necropolis of Memphis, **Saqqara**, has cemeteries from the 1st Dynasty on. The centre is the **pyramid of Djoser**, c. 2670 BC, surrounded by a limestone enclosure of 15 hectares, with about 1,680 niches in the wall, a court for the **Heb-Sed** festival, false chapels and an underground burial chamber. It began as a large mastaba (a rectangular tomb), successively enlarged into six steps, up to about 62 m. The underground galleries run for more than five kilometres and, in one of them, blue faience panels imitate reed matting. The pyramid reopened to the public in 2020 after restoration.',
  { img: 'eai-piramide-degraus', leg: 'Step Pyramid of Djoser, Saqqara.' },
  { h: 'Meidum, Dahshur and Sneferu’s three pyramids' },
  'Sneferu was the first great experimenter. At **Meidum**, a step pyramid (begun by Huni or by him) was turned into a smooth-sided pyramid, but the outer casing collapsed, perhaps already in antiquity, and today it looks like a tower surrounded by debris. At **Dahshur**, the **Bent Pyramid** changes angle halfway up (from about 54° to 43°), probably because of stability problems, and keeps much of its original limestone casing. The **Red Pyramid**, about 105 m high, is the first true smooth-sided pyramid, at a single angle (c. 43°).',
  { img: 'eai-piramide-curva', leg: 'Bent Pyramid, Dahshur.' },
  { img: 'eai-piramide-vermelha', leg: 'Red Pyramid, Dahshur.' },
  { img: 'eai-piramide-meidum', leg: 'Meidum pyramid.' },
  { h: 'Giza' },
  'On the **Giza** plateau, west of Cairo, three great pyramids stand in a line: that of **Khufu** (c. 146 m originally; today 138 m), that of **Khafre** (c. 143 m) and that of **Menkaure** (c. 65 m), plus the queens’ pyramids, hundreds of mastabas of dignitaries and the **Sphinx**, carved from the plateau’s own limestone, about 73 m long and 20 m high. Khafre’s pyramid looks larger than Khufu’s, but only because it stands on higher ground. Beside each one there is a mortuary temple, a covered causeway and a valley temple, by the Nile. The workers’ town, **Heit el-Ghurab**, lay to the south.',
  { img: 'eai-giza-reconstrucao', leg: 'Giza in the late Fourth Dynasty around 2500 BC, after construction of Menkaure\'s pyramid; hypothetical reconstruction. This does not represent Khafre\'s reign. AI-generated illustration.' },
  { img: 'eai-esfinge', leg: 'Great Sphinx of Giza with Khafre\'s pyramid.' },
  { h: 'Abusir and Abu Rawash' },
  'The 5th Dynasty built at **Abusir**, north of Saqqara, the pyramids of **Sahure**, **Neferirkare** and **Niuserre**, smaller, with temples of granite palm-shaped columns, and sun temples beside the river. It was here that the papyrus archive of the temple of Neferirkare was found in 1893. At **Abu Rawash**, north of Giza, stands the pyramid of **Djedefre**, Khufu’s son, much ruined, which was a quarry for later periods.',
  { h: 'Hierakonpolis and Abydos' },
  'In the south, **Hierakonpolis** (Nekhen) was the capital of the Predynastic chiefs and the place where the Narmer Palette and the Scorpion macehead were found, in the “Main Deposit” of the temple of Horus. **Abydos** has the tombs of the first kings, at **Umm el-Qaab**, “the mother of pots” (because of the potsherds), and Khasekhemwy’s gigantic mud-brick enclosure, the **Shunet el-Zebib**.',
  { h: 'Elephantine and Aswan' },
  'On the island of **Elephantine**, by the first cataract, stood the fortress of the southern frontier, from which the expeditions to Nubia set out. The local governors, such as **Harkhuf** and **Sabni**, were buried in rock-cut tombs on the opposite bank, at **Qubbet el-Hawa**, with their biographies carved at the entrance. The **granite** blocks of Aswan, used in chambers and sarcophagi, came down the river on barges.',
  { h: 'Sinai, Wadi al-Jarf and the Red Sea' },
  'The copper and turquoise of **Sinai** (Wadi Maghareh) were extracted by royal expeditions from the 3rd Dynasty. On the Red Sea, the harbour of **Wadi al-Jarf** was used in Khufu’s reign as a departure and arrival point for expeditions to Sinai, whence copper came to the Nile valley. It is the oldest known seaport, and the papyri of Merer were found in a gallery cut beside the harbour.',
  { h: 'Routes and neighbours' },
  { lista: [
    '**The Nile:** the main “road”. Boats went down with the current and up with the north wind; it is by the river that Aswan granite and Tura limestone arrived.',
    '**To Lebanon:** by sea, to **Byblos**, in search of cedar. The Palermo Stone records, in Sneferu’s reign, the arrival of forty ships laden with timber.',
    '**To Nubia:** along the Nile, south of Elephantine, caravans brought gold, ebony, ivory and skins. **Harkhuf** made four journeys to the land of **Yam**, in the south.',
    '**To Punt:** by sea, from the Red Sea, in search of incense, resins and gold; documented above all in Sahure’s reign.',
    '**To the oases of the Western Desert:** with the Old Kingdom settlement at **Ain Asil**, in the Dakhla oasis, a town of governors.'
  ] },
  { caixa: 'Some figures of the Age of the Pyramids', texto: 'Pyramid of Djoser: c. 62 m. Red Pyramid: c. 105 m. Khufu: c. 146 m (today 138 m). Khafre: c. 143 m. Menkaure: c. 65 m. Unas: c. 43 m. Pepi II: c. 52 m. The numbers vary by source, and original heights are reconstructed from what remains.' }
];

const sociedade = [
  { h: '1. Political organisation' },
  'Old Kingdom Egypt was a **divine monarchy**: the king, the **pharaoh** (the word was only applied to the king later, in the New Kingdom; in the Old Kingdom one said **nesut**, “king”, or **hem**, “majesty”), was the living Horus and, from the 4th Dynasty, the **son of Ra**. He governed with a **vizier** (or two, one for each half of the country), with heads of departments (treasury, granaries, the king’s works, justice) and with the king’s sons, who in the 4th Dynasty held the highest offices.',
  'The country was divided into about forty **nomes** (provinces), governed by **nomarchs**. At first they were royal officials, appointed and transferred; during the 6th Dynasty the office became hereditary and the nomarchs grew rich, with tombs of their own in their provinces, instead of being buried beside the king. This decentralisation was one of the causes of the state’s collapse.',
  { h: '2. Social classes' },
  'Society was a pyramid, in the literal sense: the king at the top, followed by the royal family (princes and queens, with great powers) and the high dignitaries, almost all relatives of the king until the end of the 4th Dynasty; then the **scribes** and officials, the **priests**, the **craftsmen** and the **soldiers**, and, at the base, the immense majority of **farmers**. There were few slaves in the sense of personal property (mostly foreign prisoners and household servants); the great divide was between those who could write and those who could not.',
  { img: 'eai-rahotep-nofret', leg: 'Statues of Rahotep and Nofret, Egyptian Museum, Cairo.' },
  { img: 'eai-ka-aper', leg: 'Detail of the wooden statue of Ka-aper (Sheikh el-Beled), Cairo.' },
  'Women could own property, inherit, sell, testify in court and hold office (priestesses of Hathor, officials, “overseer of female physicians”: the title of **Peseshet**, c. 2500 BC). They never became viziers, and rarely ruled; the regency of queens such as **Merneith** and **Ankhesenpepi II** was an exception.',
  { h: '3. Religion' },
  'The Egyptians believed in an ordered world, **ma’at** (“the just order”), which had to be maintained by rituals and good conduct, and over which the king watched. They had many gods, with human, animal or mixed forms, and the great cities had their principal god. Beliefs varied from place to place and changed over time; what we know of the Old Kingdom comes mainly from tombs and from the Pyramid Texts.',
  { tabela: { cab: ['God', 'Domain', 'Centre of cult', 'Depiction'], linhas: [
    ['Ra', 'Sun, creator; father of the king', 'Heliopolis', 'Man with a falcon head and sun disc'],
    ['Ptah', 'Craftsmen; creator by the word', 'Memphis', 'Mummiform man with a close-fitting cap'],
    ['Horus', 'Kingship, sky', 'Hierakonpolis, Edfu', 'Falcon, or man with a falcon head'],
    ['Osiris', 'Death, rebirth, the dead king', 'Busiris, later Abydos', 'Crowned man with green skin, mummified'],
    ['Isis', 'Magic, mother of Horus', 'Delta', 'Woman with a throne on her head'],
    ['Hathor', 'Love, music, sky, women', 'Dendera', 'Cow, or woman with horns and sun disc'],
    ['Anubis', 'Embalming, necropolises', 'Asyut, Saqqara', 'Jackal, or man with a jackal head'],
    ['Thoth', 'Writing, wisdom, moon', 'Hermopolis', 'Ibis, or man with an ibis head'],
    ['Sokar', 'God of the necropolis of Memphis', 'Memphis (Saqqara)', 'Falcon, or man with a falcon head'],
    ['Neith', 'Hunting, war, weaving', 'Sais', 'Woman with a bow or with the red crown'],
    ['Khnum', 'Nile floods, potter who shapes beings', 'Elephantine', 'Man with a ram’s head']
  ] } },
  'The **solar cult** gains strength in the 4th and 5th Dynasties. Kings come to call themselves “sons of Ra”, those of the end of the 5th Dynasty, such as Niuserre, build huge **sun temples** with open-air altars, and the Pyramid Texts treat the king’s destiny as a journey to the sky, where he joins Ra. The relationship between the solar religion of Heliopolis and the cult of Osiris, which appears in the Pyramid Texts, is one of the most debated points.',
  { img: 'eai-textos-piramides-unas', leg: 'Pyramid Texts inside the pyramid of Unas.' },
  { h: '4. The Pyramid Texts' },
  'Carved at **Saqqara**, first in the pyramid of **Unas** (c. 2350 BC) and then in those of **Teti**, **Pepi I**, **Merenre** and **Pepi II**, and in those of three queens, these texts comprise, in all, about **760 spells** (the “utterances”; the pyramid of Unas has 283), in Old Egyptian, written in columns, without illustration. They are spells, hymns and rituals for the dead king to climb to the sky, become a spirit (**akh**) and sail with Ra. They were discovered by Gaston Maspero in 1880 – 1881 (first in the pyramid of Pepi I, then in that of Unas). Centuries later, the same tradition would pass to coffins (the Coffin Texts) and to the Book of the Dead.',
  { h: '5. Economy and administration' },
  'The economy was **agricultural and redistributive**. Farmers grew cereals (emmer wheat, barley), flax, vines and vegetables and raised cattle, and handed over part of the harvest to the state and the temples. Officials counted the cattle every two years (the “cattle count”), and the years of reigns were sometimes named after it (for example, the “year of the 13th count”). There was no coined money: value was measured in weight of copper or grain, and payment was made in **rations** (bread, beer, meat, linen).',
  'The state sent expeditions to obtain what the valley lacked: **copper and turquoise** in Sinai, **cedar** in Lebanon, **gold, ebony and ivory** in Nubia, **incense** in Punt, **granite** at Aswan, **fine limestone** at Tura, **alabaster** at Hatnub and **basalt** at Widan el-Faras, in the Fayum, from where runs the oldest known paved road. The “corvée” (seasonal labour owed to the state) mobilised farmers during the flood, when they could not work the land.',
  { img: 'eai-barcos-nilo', leg: 'River transport of Tura limestone and Aswan granite around 2560 BC; imagined scene. Merer\'s diary documents limestone transport, not this particular mixed cargo. AI-generated illustration.' },
  { h: '6. Writing and documents' },
  '**Hieroglyphs** (“sacred carving” to the Greeks; to the Egyptians, “the divine words”) were born in the final phase of the Predynastic and, by the 1st Dynasty, already had hundreds of signs, which represent sounds or ideas or help to read a word. The faster, cursive **hieratic** script was used on papyrus. The oldest known papyrus, still blank, was found in the tomb of Hemaka at Saqqara (reign of Den). The oldest inscribed papyri are those of **Wadi al-Jarf** (c. 2560 BC), with the accounts and diary of Merer, and those of **Abusir** (c. 2400 BC), with the records of a temple.',
  { img: 'eai-papiro-merer', leg: 'Administrative papyrus from Abusir, Old Kingdom, photographed in an exhibition in Cleveland; a documentary alternative, not the diary of Merer.' },
  'Tomb inscriptions include the first **autobiographies** in history: people such as **Metjen** (3rd or 4th Dynasty), **Weni** or **Harkhuf** carve their careers and deeds on the walls, to be read by passers-by. The **Palermo Stone** (c. 2450 BC) is one of the **Royal Annals**, which record for each year the most important events of every reign, including the height of the Nile flood.',
  { img: 'eai-escriba-sentado', leg: 'Seated Scribe, Saqqara, Louvre (E 3023).' },
  { h: '7. The house' },
  'Houses were of **mud brick** (mud and straw dried in the sun), with palm-beam ceilings and flat roofs. Villages followed the river, on small rises the flood did not reach. A country house had few rooms, a courtyard, a bread oven and a silo. The rich had houses with gardens, a pool, wooden columns and cedar furniture. Almost all the houses have disappeared, and they are best known from the clay models in tombs and from the excavations at Heit el-Ghurab and Ain Asil.',
  { img: 'eai-casa-quotidiano', leg: 'Interior of an Old Kingdom house around 2400 BC; imagined everyday scene. AI-generated illustration.' },
  { h: '8. Food' },
  'The base was **bread** (of emmer wheat) and **beer** (of barley, thick and low in alcohol, drunk by everyone, including children). People also ate onions, garlic, lentils, beans, cucumbers, dates, figs, fish from the Nile and the Delta, fowl and, among the rich, beef and goat. Wine was a luxury product. The workers at Giza had regular rations of bread, beer and meat, as the cattle bones found at Heit el-Ghurab show. Food was sweetened with honey and dates.',
  { h: '9. Clothing and appearance' },
  'Clothing was of **linen**. Men wore a **kilt** (shendyt), long or short, and the rich wore finely pleated kilts. Women wore a tight strap dress down to the ankle. Children went naked until adolescence, with a lock of hair at the side (the “sidelock of youth”). Many wore **wigs** of human hair or fibre, and all who could wore **make-up** (kohl for the eyes, which also protected from the sun), oils, perfumes and jewellery of copper, gold, faience, carnelian and turquoise. People went barefoot, or in sandals of papyrus or leather.',
  { h: '10. Music, games and festivals' },
  'Tomb reliefs show musicians with **harps, flutes, double oboes and hand-clapping**, and dancers in groups. The most popular board game was **senet** (30 squares) and **mehen** (“the serpent”), a circular board, both present in tombs since the Early Dynastic Period. There was also the **game of hounds and jackals** (58 holes). Festivals were tied to the rhythm of nature and religion: the Nile flood, the new year and the festivals of the gods. For the king, the most important was the **Heb-Sed**, the jubilee festival, in which the king ran before the gods to renew his power.',
  { h: '11. Science and knowledge' },
  { lista: [
    '**Calendar:** the civil year had 365 days, in 3 seasons of 4 months of 30 days, plus 5 extra days. The seasons were **Akhet** (flood), **Peret** (growth) and **Shemu** (harvest). The link with the heliacal rising of **Sirius** (Sothis) at the time of the flood is much debated as to its origin. The calendar was already in use in the Old Kingdom.',
    '**Measurement:** the **royal cubit** (c. 52.5 cm, divided into 7 palms of 4 fingers) was the basic unit of length. Old Kingdom masons measured and aligned with remarkable precision: the base of the Great Pyramid differs by only a few centimetres between its sides.',
    '**Orientation:** the pyramids align with the cardinal points with errors of a few arcminutes; the most likely method uses stars or the Sun, but there is no certainty.',
    '**Mathematics:** the geometry used by the builders (slope, the seked) is well known only from later papyri, such as the Rhind (c. 1550 BC), copied from older texts.',
    '**Medicine:** the title “chief of dentists and physicians of the king” belonged to **Hesy-Ra** (3rd Dynasty). The surviving medical texts (Edwin Smith, Ebers) are from the New Kingdom, but the Edwin Smith, on wounds, describes knowledge that seems to originate in the Old Kingdom; this is a common hypothesis, not confirmed.'
  ] },
  { h: '12. Technology and building' },
  'Old Kingdom Egyptians worked with tools of **copper** (chisels, saws, adzes), of **dolerite** (stone hammers) and of wood, without iron and without pulleys, and without using the wheel for the blocks. They cut limestone with saws and chisels; granite, with dolerite balls and abrasives (quartz sand). They moved the blocks on **wooden sledges**, over dampened ground, as a later painting shows. Blocks went up by **ramps**; the remains of ramps and wooden posts at the **Hatnub** quarry (4th Dynasty) suggest stepped ramps with slopes of about 20%. Exactly how the pyramids were built is still debated.',
  { img: 'eai-transporte-pedra', leg: 'Transporting a block on a sledge at Giza around 2550 BC; artistic reconstruction. Water application illustrates a technical hypothesis, not a documented episode at this construction site. AI-generated illustration.' },
  { img: 'eai-grande-piramide', leg: 'Great Pyramid of Khufu.' },
  { caixa: 'Theories with no basis', texto: 'The pyramids were **not built by extraterrestrials, nor by a lost civilisation such as Atlantis**; they were built by Egyptians, and we know their villages, cemeteries, work records and the papyri that describe the transport of the stone. They were also **not built by slaves**: the account of **Herodotus** (5th century BC) of 100,000 enslaved men in Khufu’s service, written two thousand years later, is refuted by the excavations.' },
  { h: '13. The builders of Giza' },
  'In 1990, the workers’ cemeteries south of Giza revealed simple tombs, but with bread, beer and good medical care (there are skeletons with healed fractures and well-treated amputations). Further south, the team of **Mark Lehner** (AERA) excavated a village, **Heit el-Ghurab**, with bakeries, breweries, workshops, dormitories and dried fish. The work gangs had names such as “Friends of Khufu” or “Drunkards of Menkaure”, painted in relieving chambers of the pyramids. Estimates of the number of workers range from about 10,000 to 30,000, in shifts; a permanent core of specialists was reinforced by farmers during the flood.',
  { img: 'eai-heit-el-ghurab-cena', leg: 'Heit el-Ghurab settlement around 2500 BC, inspired by AERA excavations; artistic reconstruction. Gallery functions are interpretative; the food-production scene is not evidence of an excavated brewery. AI-generated illustration.' },
  { h: '14. War and frontiers' },
  'The Old Kingdom had no large standing army. Military expeditions were one-off campaigns, with recruits gathered for the occasion, in **Nubia**, **Libya** and **Sinai**. The autobiography of **Weni**, in the reign of Pepi I, tells of a campaign against the “sand-dwellers” (probably Bedouin of Sinai and the southern Levant) with an army that included Nubians and Libyans. He speaks of five incursions. In the south, relations with Nubia were mostly commercial, with an outpost at **Buhen**.',
  { img: 'eai-caravana-nubia', leg: 'Caravan returning from Yam around 2250 BC, inspired by Harkhuf\'s accounts; imagined scene. Yam\'s location is uncertain; the dancer of short stature is conjecturally depicted. AI-generated illustration.' },
  { h: '15. Death and tombs' },
  'The tomb was a “house for eternity”. Dignitaries were buried in **mastabas** (rectangular stone or mud-brick tombs, from the Arabic for “bench”) with decorated chapels, where the family brought offerings. Each tomb had a “**false door**”, through which the spirit (**ka**) came to receive food, and a **serdab** with the statue of the owner. Bodies were preserved with **natron** and **linen**; the earliest evidence of evisceration is that of Queen Hetepheres I (4th Dynasty), from whose tomb a chest with her viscera was salvaged. Full mummification developed only later.',
  { img: 'eai-relevo-sahure', leg: 'Ship relief from Sahure\'s complex, Abusir.' },
  { img: 'eai-abusir-reconstrucao', leg: 'Sahure\'s funerary complex at Abusir around 2480 BC; conjectural reconstruction. AI-generated illustration.' },
  { h: '16. Justice and law' },
  'No “law code” of the Old Kingdom is known. Justice was administered through decisions of the vizier, local courts and officials, according to tradition and the idea of ma’at. Some cases are known from inscriptions: **Weni** tells that, in the trial of a conspiracy in the king’s harem, he was charged with hearing the case alone, without other judges, and he is proud of it. There were corporal punishments, fines and confiscation of goods, and the death penalty for serious crimes.'
];

const personalidades = [
  'The figures of the Old Kingdom are known from inscriptions, statues and tombs, and rarely from long accounts. The biographies are therefore short and the dates approximate; what is tradition or hypothesis is marked.',
  { h: 'Narmer (c. 3100 BC)' },
  'King of the end of the Predynastic, or of the 1st Dynasty, known above all for the **Narmer Palette**, found at Hierakonpolis (1897 – 1898, by J. E. Quibell and F. W. Green). The palette shows him striking an enemy and then wearing the red crown of the North. Egyptologists debate whether it records the “unification” of the country or is a ritual image of the king as victor over disorder. Narmer’s name appears on vessels at Abydos and in Palestine, which indicates very wide territorial influence.',
  { h: 'Merneith (c. 2950 BC)' },
  'Queen of the 1st Dynasty, wife of King Djet and mother of Den, probably regent during her son’s childhood. Her tomb at Abydos is of the royal type, and her name appears on clay seals (on one of them as “king’s mother”); she is not in the New Kingdom king lists. It is one of the first cases of a woman in power; whether she was a “female pharaoh” is debated.',
  { h: 'Djoser (c. 2670 BC)' },
  'King of the 3rd Dynasty. His Horus name was **Netjerikhet**; “Djoser” is the form used by later scribes. His reign is thought to have lasted about two decades, which is uncertain; dates vary widely between authors (between c. 2690 and c. 2630 BC; Shaw, 2000, proposes c. 2630 – 2611 BC). The step pyramid was his greatest legacy. The **Famine Stela**, an inscription of the Ptolemaic period, at Aswan, credits him with ending a seven-year famine, but it is a much later text and considered legendary.',
  { h: 'Imhotep (c. 2670 BC)' },
  'Minister and architect of Djoser; his name and titles appear on the base of a statue of the king at Saqqara. He is credited with inventing building in cut stone. Later he was venerated as a sage, scribe and physician, and deified in the Late Period; the Greeks identified him with **Asclepius**. His tomb has never been found, despite searches at Saqqara.',
  { h: 'Sneferu (c. 2613 – 2589 BC)' },
  'Founder of the 4th Dynasty, father of Khufu. He built or completed three pyramids (Meidum, Bent and Red) and, according to the Palermo Stone, sent forty ships to fetch cedar from Lebanon and campaigned in Nubia. The Egyptians remembered him as a good king, and his cult lasted at least until the Middle Kingdom.',
  { h: 'Khufu (c. 2589 – 2566 BC)' },
  'Son of Sneferu and Queen Hetepheres I, and builder of the Great Pyramid, the tallest of the pyramids. Little written information survives from his reign, and only one ivory statuette of him, about 7.5 cm,, found at Abydos. To Herodotus we owe the image of a tyrant king, which has no basis in the Egyptian sources; his name continued to be venerated in later times. **Khufu’s ship**, dismantled in 1954 from a pit beside the pyramid, was about 43 m long.',
  { img: 'eai-barca-queops', leg: 'Reassembled funerary boat of Khufu.' },
  { img: 'eai-estatueta-queops', leg: 'Ivory statuette of Khufu, Cairo.' },
  { h: 'Hemiunu (c. 2570 BC)' },
  'Vizier of Khufu, nephew of the king, and “overseer of all the king’s works”. Many consider him the architect of the Great Pyramid, but that attribution is a deduction from his titles. His mastaba, at Giza, held a limestone statue of him, now in Hildesheim.',
  { h: 'Khafre (c. 2558 – 2532 BC)' },
  'Son of Khufu, builder of the second pyramid at Giza and, according to most Egyptologists, of the Sphinx, whose face would bear his features. Of the statues from his valley temple, there remains the diorite one that shows him seated, with the falcon Horus behind his head. The idea that the Sphinx is much older is a fringe theory, without the support of archaeologists.',
  { img: 'eai-estatua-khafre', leg: 'Detail of the diorite statue of Khafre, Cairo.' },
  { h: 'Menkaure (c. 2532 – 2504 BC)' },
  'Grandson of Khufu. His pyramid is less than half the height of its two neighbours, but its lower courses are of granite. The statues from his temple, including the famous group with the queen, were found by George Reisner (1908 – 1910). His successor, Shepseskaf, did not build a pyramid, but a large mastaba at South Saqqara.',
  { img: 'eai-miquerinos-rainha', leg: 'Menkaure and a queen, Museum of Fine Arts, Boston.' },
  { h: 'Ankhhaf (c. 2540 BC)' },
  'Prince and vizier of the 4th Dynasty, buried in a large mastaba at Giza. His limestone **bust**, found by Reisner, is one of the most famous examples of Old Kingdom portraiture: the face seems individual and realistic, not idealised. It shows that the dignitaries of the 4th Dynasty, relatives of the king, had access to royal-quality monuments.',
  { img: 'eai-busto-ankhhaf', leg: 'Bust of Ankhhaf, Museum of Fine Arts, Boston.' },
  { h: 'Ptahhotep (c. 2400 BC)' },
  'Vizier of King Djedkare Isesi, of the 5th Dynasty. Tradition attributes to him the **Maxims of Ptahhotep**, one of the oldest wisdom texts, addressed to his son, which advise humility, justice and control of speech. The most complete copy (the Prisse Papyrus, in the French National Library in Paris) is from the Middle Kingdom, and some scholars doubt that the text, in the form we have it, dates from the Old Kingdom.',
  { h: 'Weni the Elder (c. 2330 – 2290 BC)' },
  'An official who served **Teti**, **Pepi I** and **Merenre**. He began as a “keeper of the treasury” and rose to judge, military commander and governor of Upper Egypt. His autobiography, carved on a block at Abydos (now in the Egyptian Museum, Cairo), tells that he led a large army against the “sand-dwellers”, that he ordered blocks for the king’s pyramid, and that he dug canals at the first cataract. It is one of the first military accounts in Egyptian history, written by a man who was not a king.',
  { h: 'Harkhuf (c. 2250 BC)' },
  'Governor of Upper Egypt, linked to Elephantine, and caravan leader in the reign of Merenre and of Pepi II. He had carved in his tomb, at Qubbet el-Hawa, the account of his four journeys to **Yam**, in the south. It includes the letter from the young **Pepi II**, then still a child, asking him to bring back alive a dancing “dwarf” he was bringing from Yam, and promising him honours for the feat. It is one of the oldest surviving royal letters.',
  { h: 'Pepi II, or Neferkare (c. 2278 – 2214 BC, perhaps to c. 2184)' },
  'He came to the throne as a child and reigned, according to the Turin Canon and Manetho, more than ninety years; contemporary inscriptions only reach the 62nd year, and most Egyptologists accept a reign of about 64 years. His pyramid, at South Saqqara, is small and has Pyramid Texts. By the end of his reign, central power had weakened, and the governors were almost independent. Manetho and Herodotus speak of a queen **Nitocris** who is supposed to have succeeded him and taken revenge on the murderers of her brother; this is probably legend, and her identification with a king of the Turin Canon is debated.'
];

const legado = [
  { h: 'What they left us' },
  { lista: [
    '**The state and administration:** the idea of a central government with officials, a vizier, taxes and archives.',
    '**Monumental architecture:** the pyramid and the stone temple, copied over millennia and later imitated all over the world.',
    '**Writing:** hieroglyphs and hieratic, with all their use in administration and literature.',
    '**Literature:** the Maxims of Ptahhotep (attributed), the autobiographies and the Pyramid Texts, the first religious texts of humankind.',
    '**Art:** the sculpted portrait with an individual face, the narrative relief, the conventions of proportion that would last three thousand years.',
    '**Ideas about the afterlife:** the ka, the judgement, rebirth, which influenced all of Egyptian religion and, indirectly, other traditions.'
  ] },
  { h: 'Art' },
  'Old Kingdom art defined the “Egyptian style”: the statue facing forward, rigid, with the left leg slightly ahead, in hard stone; the relief in horizontal registers, with figures in profile and eyes frontal; the conventional colours (men reddish, women paler). At the same time there is a tendency to **realism** in private portraits, such as the bust of Ankhhaf, the Seated Scribe and Ka-aper. The reliefs of the tombs at Saqqara, such as that of Mereruka (6th Dynasty), show daily life: fishing, harvest, crafts, games.',
  { h: 'Architecture: from mastaba to pyramid' },
  'In a little over a century (from c. 2670 to c. 2560 BC), Egypt went from the mastaba to the step pyramid, then to the smooth-sided pyramid and, finally, to the Great Pyramid. No other civilisation made so rapid a development in size. The pyramid is a stone version of the “primeval mound” and of the rays of the Sun, and its shape links the dead king to Ra. Later, the pyramids become smaller, and the 5th Dynasty invests in sun temples.',
  { img: 'eai-abusir', leg: 'Pyramids of Abusir.' },
  { h: 'Rediscovery' },
  'The pyramids were never forgotten: they were visited by Greeks and Romans, described by Herodotus (5th century BC) and Diodorus, and included by the Greeks among the “seven wonders” (the Great Pyramid is the only one still standing). Around 820 – 832 AD, the caliph **al-Ma’mun** is said to have opened the tunnel that still serves as the entrance today. Reading hieroglyphs only became possible after **Champollion** (1822). In 1880 – 1881, **Maspero** discovered the Pyramid Texts; **Flinders Petrie** surveyed Giza in 1880 – 1882; **Reisner** excavated the cemeteries (1902 – 1942); **Ludwig Borchardt** excavated Abusir; **Jean-Philippe Lauer** restored Djoser’s complex for decades; in 1954 Khufu’s ship was discovered; and in 2013, the diary of Merer.',
  { h: 'Egypt and the imagination' },
  'Since antiquity the pyramids have inspired legends: Arabs said they had been built before the flood; in the Middle Ages they were thought to be Joseph’s granaries (the “legend of Joseph”); and modern **Egyptomania** (since Napoleon, in 1798) made them a universal symbol. Today, theories that they were made by extraterrestrials or lost civilisations are pseudoarchaeology, without foundation: they ignore the evidence of the workers, the quarries and the papyri.',
  { h: 'Open debates' },
  { lista: [
    '**How the pyramids were built:** straight, spiral, internal or mixed ramps; there is still no consensus.',
    '**The “unification”:** was it a long process or an episode under Narmer? And who is Menes?',
    '**The Sphinx:** the attribution to Khafre is the most accepted, but its exact dating has no direct proof.',
    '**The end of the Old Kingdom:** drought (the 4.2 kiloyear event), the power of the governors and the long reign of Pepi II; the relative weight of each factor is debated.',
    '**Chronology:** differences between authors reach several decades; the dates on this page are conventional.'
  ] },
  { h: 'Where to visit' },
  { lista: [
    '**Giza:** the plateau, with the three pyramids and the Sphinx. The **Grand Egyptian Museum**, next door, holds pieces from all periods, including Khufu’s boats.',
    '**Saqqara:** Djoser’s step pyramid, the pyramid of Unas and the tombs of Mereruka and Ti.',
    '**Dahshur:** the Bent and Red Pyramids, which can be entered, and are far less visited than those at Giza.',
    '**Egyptian Museum, Cairo:** the Narmer Palette, the statues of Djoser, Khafre, Rahotep and Nofret, and Ka-aper.',
    '**Louvre Museum, Paris:** the Seated Scribe and the Gebel el-Arak Knife. **Museum of Fine Arts, Boston:** the bust of Ankhhaf and the Menkaure group. **Ashmolean Museum, Oxford:** the Scorpion macehead.',
    '**Palermo Archaeological Museum:** the largest fragment of the Palermo Stone.'
  ] }
];

const quiz = [
  { p: 'What did the Egyptians call the fertile land of the Nile valley?', op: ['Deshret', 'Kemet', 'Punt', 'Ma’at'], certa: 1, exp: 'Kemet means “the Black Land”, because of the dark silt left by the flood; Deshret was “the Red Land”, the desert.' },
  { p: 'Which object, of c. 3100 BC, is associated with the unification of Upper and Lower Egypt?', op: ['The Rosetta Stone', 'The Narmer Palette', 'The mask of Tutankhamun', 'The Turin Canon'], certa: 1, exp: 'The Narmer Palette shows the king with the white crown and with the red one; its interpretation is debated.' },
  { p: 'What was the Egyptian name of the Old Kingdom capital, today Memphis?', op: ['Ineb-hedj (the White Walls)', 'Waset', 'Iunu', 'Akhetaten'], certa: 0, exp: 'Ineb-hedj, “the White Walls”; “Memphis” comes from Men-nefer, the name of Pepi I’s pyramid.' },
  { p: 'Who was the minister and architect credited with Djoser’s step pyramid?', op: ['Hemiunu', 'Imhotep', 'Ptahhotep', 'Weni'], certa: 1, exp: 'Imhotep served Djoser and was later venerated as a sage and a god.' },
  { p: 'Which 4th Dynasty king built three pyramids (Meidum, Bent and Red)?', op: ['Khufu', 'Sneferu', 'Menkaure', 'Unas'], certa: 1, exp: 'Sneferu experimented with forms until he reached the smooth-sided pyramid, the Red one.' },
  { p: 'What was the original height of Khufu’s Great Pyramid?', op: ['About 62 m', 'About 100 m', 'About 146 m', 'About 200 m'], certa: 2, exp: 'It was about 146.6 m; today, without the top and the casing, it is about 138 m.' },
  { p: 'Who built the pyramids, according to the excavations at Giza?', op: ['Hebrew slaves', 'Extraterrestrials', 'Organised Egyptian workers, fed and paid in rations', 'Prisoners of war only'], certa: 2, exp: 'The village of Heit el-Ghurab and the cemeteries show well-fed, well-treated Egyptian workers.' },
  { p: 'What is the diary of Merer?', op: ['A papyrus with the account of transporting limestone to the Great Pyramid', 'A love poem', 'A list of kings', 'A medical treatise'], certa: 0, exp: 'Found at Wadi al-Jarf, c. 2560 BC, it is among the oldest inscribed papyri known.' },
  { p: 'Which was the first pyramid with Pyramid Texts on its walls?', op: ['Djoser’s', 'Khufu’s', 'Unas’s', 'Menkaure’s'], certa: 2, exp: 'That of Unas, last king of the 5th Dynasty, c. 2350 BC.' },
  { p: 'To which king is the Sphinx of Giza usually attributed?', op: ['Khufu', 'Khafre', 'Djoser', 'Pepi II'], certa: 1, exp: 'Most Egyptologists attribute it to Khafre, c. 2550 BC.' },
  { p: 'What were nomarchs?', op: ['Priests of Ra', 'Governors of the provinces (nomes)', 'Army chiefs', 'Scribes of the king'], certa: 1, exp: 'Nomarchs governed the nomes; in the 6th Dynasty the office became hereditary and the king lost power.' },
  { p: 'Which royal festival served to renew the king’s power?', op: ['Opet', 'Heb-Sed', 'Wag', 'Khoiak'], certa: 1, exp: 'The Heb-Sed (jubilee) included a ritual run by the king; Djoser’s enclosure has a court for it.' },
  { p: 'Which 6th Dynasty king had a very long reign, perhaps about 64 years (or, according to ancient sources, over 90)?', op: ['Teti', 'Pepi II', 'Unas', 'Khasekhemwy'], certa: 1, exp: 'Pepi II came to the throne as a child; the length of his reign is debated.' },
  { p: 'Who wrote a famous autobiography while serving Teti, Pepi I and Merenre?', op: ['Weni', 'Imhotep', 'Ankhhaf', 'Hemiunu'], certa: 0, exp: 'Weni, official and commander, served three kings of the 6th Dynasty.' },
  { p: 'Besides the power of the governors, which factor is pointed to for the end of the Old Kingdom?', op: ['A Roman invasion', 'A drought that reduced the Nile floods', 'A volcanic eruption', 'The Black Death'], certa: 1, exp: 'Geological records point to a drought around 2200 BC; the weight of this factor is debated.' }
];

export default { visao, linha, mapa, sociedade, personalidades, legado, quiz };
