// SWAHILI CITY-STATES — full English content. Same structure and same image slots as the Portuguese version (dados.js).
// Dates are approximate. AD = Anno Domini. The period covered is c. AD 800–1500; the Portuguese arrival (1498–1509) is treated only in a short epilogue.

const visao = [
  { caixa: 'In brief', texto: [
    'The **Swahili city-states** were a string of independent trading towns that, from about the 8th–9th century onward, grew up along the East African coast, from southern Somalia to northern Mozambique, and on islands such as Lamu, Pate, Zanzibar, Mafia and Kilwa. Their people spoke **Swahili** (Kiswahili), a Bantu language with many Arabic loanwords, were mostly Muslim, and lived from the sea: they carried gold, ivory, iron, timber and enslaved people from inland Africa across the Indian Ocean, and brought back cloth, glass beads, Chinese porcelain and Islamic pottery.',
    'They never formed a single state. Each town (Kilwa, Mombasa, Malindi, Lamu, Pate, Mogadishu and dozens of others) had its own ruler, mosques, merchant families and fortunes, and they often rivalled one another. What united them was language, religion, a way of building in coral stone and a shared place in the monsoon trade of the Indian Ocean.'
  ] },
  { img: 'sua-mapa-costa', leg: 'Map highlighting the Swahili coast in green within present-day Africa; it does not show a medieval empire.' },
  { h: 'Where it was' },
  'The Swahili coast stretches for some **3,000 km** along the western Indian Ocean, from the Benadir coast of Somalia (Mogadishu, Brava) through Kenya and Tanzania to northern Mozambique (Sofala is usually taken as the southern limit of the trade), including the Comoros and the northern tip of Madagascar. The towns stood on islands, peninsulas and creek mouths, with a harbour in front and farmland behind. The Swahili name for the coast comes from the Arabic **sawāḥil**, «the coasts», plural of *sāḥil*.',
  'The climate is hot and humid, with two rainy seasons, and the coastal belt is fertile. But the geography that explains the Swahili world is the **monsoon**: for part of the year the winds blow from the north-east and carry ships from Arabia, Persia and India towards Africa; in the other part they blow from the south-west and carry them home. That regular, free «engine» made the coast part of a world network.',
  { img: 'sua-lamu-cidade', leg: 'Lamu Old Town, Kenya.' },
  { h: 'When it existed' },
  'The Swahili world did not begin on one date. Historians describe a slow process in several phases; the dates below are approximate and the stages overlap.',
  { tabela: { cab: ['Phase', 'Approximate dates', 'What marks it'], linhas: [
    ['Early coastal communities', 'c. AD 500 – 800', 'Villages of farmers, fishers and ironworkers in timber, clay and thatch; first contact with the Indian Ocean (imported glass, Gulf pottery in small amounts)'],
    ['Formation of the towns', 'c. 800 – 1000', 'Places such as Shanga, Manda, Unguja Ukuu and Kilwa grow; first timber mosques; imports of Islamic and Chinese ceramics; Islam spreads along the coast'],
    ['The first stone towns', 'c. 1000 – 1300', 'Coral-stone mosques and houses; local coinage (12th–13th century); Mogadishu’s great mosques; Kilwa rises'],
    ['Golden age', 'c. 1300 – 1500', 'Kilwa and the gold of Sofala; Husuni Kubwa and the Great Mosque; Songo Mnara and Gedi at their peak; Ibn Battuta (c. 1331); pillar tombs; richest and most cosmopolitan phase'],
    ['Epilogue: the Portuguese arrive', '1498 – 1509 (and beyond)', 'Vasco da Gama (1498); sack of Kilwa and Mombasa (1505); the Swahili towns lose control of the trade (see the epilogue in the Timeline)']
  ] } },
  { img: 'sua-aldeia-inicial', leg: 'Coastal village around 800, with timber-and-earth houses and mosque; hypothetical reconstruction. AI-generated illustration.' },
  { img: 'sua-kilwa-mesquita', leg: 'Ruins of the Great Mosque of Kilwa Kisiwani, Tanzania.' },
  { h: 'Where did they come from? A debated question' },
  'For a century, the origin of the Swahili was a battleground. The old story, told by the Swahili themselves in chronicles and repeated by 19th- and early 20th-century European scholars, said the towns were founded by **Persian princes from Shiraz** (the so-called **Shirazi**), who sailed to Africa and built the stone cities. Some colonial writers went further and credited Arab or Persian «colonists» with everything, as if the Africans of the coast had been incapable of creating a civilization.',
  'Archaeology has largely overturned that picture. Excavations from the 1960s on, and especially Mark Horton’s at **Shanga** (1980s), found that the earliest settlers were **African**: farmers and fishers using local pottery, living in timber and clay houses, who only gradually (over centuries) took up Islam, imported goods and stone building. Kenyan archaeologist **Chapurukha Kusimba** stresses the African roots of the iron industry and of the towns’ economy; Tanzanian archaeologist **Felix Chami** argues for deep African roots and for contact with the Indian Ocean long before Islam. Linguistics points the same way: Swahili is a Bantu language, and its Persian vocabulary is small and mostly came through Arabic.',
  { caixa: 'What is debated, and what is not', texto: [
    '**Settled:** the Swahili are, culturally and linguistically, an African people. The language is Bantu, the oldest settlements were African, and the stone architecture grew out of local materials and skills.',
    '**Debated:** how much and when outsiders arrived. A 2023 study of ancient DNA from about 80 medieval and early modern people (published in *Nature*) found that these people had mainly African female ancestry and a significant share of Asian ancestry (largely Persian) through the male line, with mixing dated to around AD 1000. This suggests that small groups of Persian and Arab men did settle and marry into local families, which may explain the «Shirazi» tradition. But it does not show «colonization»: the culture that resulted was African and Muslim, and the Shirazi story may also have been a way of claiming prestige and legitimacy.'
  ] },
  { h: 'The Swahili language' },
  'Swahili (Kiswahili) is a **Bantu language**, with the same basic grammar and vocabulary as other East African Bantu tongues, but with many **Arabic loanwords**, especially for religion, trade, law and abstract ideas (estimates of the Arabic share vary), and some from Persian and Indian languages. It has dialects along the coast: Kiamu (Lamu), Kimvita (Mombasa), Kiunguja (Zanzibar town, the basis of Standard Swahili) and others. In the period of this chapter it was written, when at all, in Arabic script; the oldest known Swahili manuscripts are from the 17th–18th century. Today it is spoken by well over 100 million people (estimates vary), is the lingua franca of East Africa, and is a working language of the African Union.',
  { h: 'Why they matter' },
  { lista: [
    '**Cities without an empire:** dozens of independent towns, sharing a language and a culture, grew rich through trade and not through conquest.',
    '**A bridge between Africa and the Indian Ocean:** their ports linked the gold of Zimbabwe and the ivory of the interior to Arabia, India and China.',
    '**A genuinely African, Muslim culture:** Swahili civilization is a case study of how African societies took in outside influences and made something new.',
    '**Architecture:** the carved coral-stone mosques, palaces, houses and pillar tombs are among the most original buildings of medieval Africa.',
    '**A global language:** Swahili is today one of the most widely spoken African languages.',
    '**A historical lesson:** the argument over their origins shows how colonial prejudice shaped (and distorted) the study of African history.'
  ] },
  { caixa: 'The Swahili coast today', texto: 'The **Ruins of Kilwa Kisiwani and Songo Mnara** (Tanzania, 1981), **Lamu Old Town** (Kenya, 2001), **Fort Jesus, Mombasa** (Kenya, 2011, a Portuguese building), the **Ruins of Gedi** (Kenya, 2024) and the Island of Mozambique (1991) are UNESCO World Heritage Sites. Swahili culture remains alive on the coast, in the language, the food, the carved doors, the poetry and the mosques.' },
  { img: 'sua-cidade-reconstrucao', leg: 'Swahili stone town around 1400, viewed from the sea; hypothetical reconstruction. AI-generated illustration.' }
];

const linha = [
  'This timeline follows the main events of the Swahili city-states. Dates before 1300 are approximate, and many «dates» come from later chronicles and may be legendary; this is marked in each entry.',
  { linha: [
    { d: '1st century AD', t: 'A first mention: Azania and Rhapta', x: 'The *Periplus of the Erythraean Sea*, a Greek sailing guide written by an unknown merchant of Roman Egypt (c. AD 40–70), mentions «Azania» and a trading port called **Rhapta**, with sewn boats and exports of ivory and tortoiseshell. Where Rhapta stood is still **unknown and debated** (somewhere on the coast of present-day Tanzania). It shows, at least, that the coast was already in contact with the wider world.' },
    { d: 'c. 500 – 800', t: 'African villages by the sea', x: 'Excavations on Zanzibar (Fukuchani), at Unguja Ukuu and elsewhere show settled communities of farmers, fishers and ironworkers by the 6th century at the latest, using timber, clay and thatch, with a little imported pottery and glass from the Persian Gulf. These are the **African roots** of the Swahili world.' },
    { d: 'c. 700 – 800', t: 'Shanga, Manda and Unguja Ukuu grow', x: 'At **Shanga** (Pate Island, Kenya) and **Manda**, as at Unguja Ukuu (Zanzibar), small settlements become trading ports. Imports of Islamic glazed ceramics and Chinese stoneware show contact with the Gulf and, indirectly, with China.' },
    { d: 'c. 800', t: 'The first mosques', x: 'In Shanga, Mark Horton found a sequence of mosques, the earliest of timber, from around the 8th–9th century (the exact dating is debated). It is among the earliest evidence of Islam south of the Sahara on the coast. Islam spread slowly, through trade, and for long coexisted with older beliefs.' },
    { d: '869 – 883', t: 'The Zanj Revolt in Iraq', x: 'In southern Iraq, thousands of enslaved people, called **Zanj** by the Arabs (a name for the East African coast), rose against the Abbasid caliphate. The revolt shows that slaves from East Africa were already being exported to the Gulf, but at a scale much smaller than in the 18th–19th centuries.' },
    { d: 'c. 10th century (tradition)', t: 'The legend of the founding of Kilwa', x: 'The **Kilwa Chronicle** says that a Persian prince of Shiraz, **Ali ibn al-Hasan**, bought the island of Kilwa from the local ruler (in the legend, by paying with cloth enough to surround it) and founded the dynasty later called **Shirazi**. The date given by tradition (often 957) is not reliable; archaeology shows the island was already inhabited and that the town grew mainly in the 11th–12th centuries.' },
    { d: '1107', t: 'An inscription at Kizimkazi', x: 'A Kufic (early Arabic script) inscription in the mosque of Kizimkazi, in the south of Zanzibar, is read as dated AH 500 (AD 1107). It is among the oldest dated Islamic inscriptions on the coast.' },
    { d: 'c. 11th – 12th century', t: 'The first stone towns', x: 'Coral-stone mosques and houses begin to replace timber and clay in towns such as Kilwa, Shanga, Gedi and Mogadishu. The first Great Mosque of Kilwa (northern prayer hall) is built. Gedi, in Kenya, is founded around this time.' },
    { d: 'c. 11th – 13th century (debated)', t: 'Coins on the coast', x: 'Kilwa begins to strike copper coins (and, later, silver ones), among the earliest minted in sub-Saharan Africa; Mogadishu does the same later. The date of the first issues is debated (c. 1100 is a common estimate), and the earliest are attributed by some scholars to a ruler named Ali ibn al-Hasan. Until then, cowries, beads and iron bars were used as a means of exchange.' },
    { d: '1203 – 1204 (tradition)', t: 'The Nabhani of Pate', x: 'The **Pate Chronicle** says that Sulaiman ibn Sulaiman al-Nabhani, from Arabia, arrived and married into the local royal family, founding the Nabhani dynasty of Pate. As in the case of Kilwa, the early part of the chronicle is **legendary** and has no archaeological confirmation.' },
    { d: '1269', t: 'Mogadishu’s mosque of Fakhr al-Din', x: 'A Kufic-style inscription dates the mosque of Fakhr al-Din in Mogadishu to AH 667 (AD 1269), one of several great mosques that show the wealth of this northern port.' },
    { d: 'c. 1277', t: 'The Mahdali dynasty takes Kilwa', x: 'According to the Kilwa Chronicle, the Shirazi line was replaced by the **Mahdali**, sayyids («descendants of the Prophet») of Yemeni origin. Under them Kilwa reached its peak.' },
    { d: 'c. 1300 (debated)', t: 'Kilwa controls the gold of Sofala', x: 'Kilwa secures control of **Sofala**, in Mozambique, the port through which flowed the gold of the Zimbabwe plateau. The date is debated: the chronicle suggests an earlier date (12th century), while other scholars point to the 13th or early 14th century.' },
    { d: 'c. 1310 – 1333', t: 'Al-Hasan ibn Sulaiman builds Kilwa’s grandeur', x: 'The sultan al-Hasan ibn Sulaiman, called **Abu’l-Mawahib** («father of gifts»), builds the palace of **Husuni Kubwa** and enlarges the Great Mosque with a southern extension and domes. These are the most ambitious stone buildings of the medieval coast.' },
    { d: 'c. 1331', t: 'Ibn Battuta visits the coast', x: 'The Moroccan traveller **Ibn Battuta** visits Mogadishu, Mombasa and Kilwa. The traditional date is 1331, but the chronology of his trip (c. 1330–1332) is debated, as is whether he saw all that he describes. He praises Kilwa as one of the most beautiful and most elegantly built towns in the world.' },
    { d: 'c. 14th century', t: 'Songo Mnara', x: 'On a small island south of Kilwa, **Songo Mnara** is founded as a town of coral-stone houses and mosques, occupied from the 14th to the 16th century.' },
    { d: '1399', t: 'The dated tomb of Gedi', x: 'The pillar tomb of Gedi, in Kenya, bears an Arabic inscription corresponding to AD 1399. Gedi reaches its peak in the 15th–16th centuries.' },
    { d: 'c. 1400 – 1425', t: 'Shanga is abandoned', x: 'Shanga, one of the oldest towns, is abandoned. Why is not known; possibilities include changes in the water supply and the rise of rival ports.' },
    { d: '1414 – c. 1419', t: 'China and the Swahili coast (debated)', x: 'In 1414 a giraffe from Malindi (arriving by way of Bengal) reaches the Ming court. Chinese sources record that fleets of **Zheng He** reached the coast of East Africa (Mogadishu, Brava and Malindi) in the following years. Chinese porcelain is very common on Swahili sites, but **direct proof of Zheng He’s visit is scarce**, and how far south he went is debated.' },
    { d: 'c. 1400 – 1500', t: 'The peak', x: 'Kilwa, Mombasa, Malindi, Pate, Lamu and Mogadishu flourish. Stone houses with niches for porcelain, pillar tombs, mosques and rich merchants characterise this period.' },
    { d: 'c. 1489 – 1490', t: 'Pêro da Covilhã on the coast', x: 'The Portuguese Pêro da Covilhã, sent by King John II (D. João II) in 1487 to find the route and markets of the East, goes from Cairo to India and, according to tradition, returns by way of Sofala, on the East African coast, before going back to Cairo. He gives the Portuguese crown its first first-hand information on the gold and the monsoon route (the details of his itinerary are debated).' },
    { d: '1498', t: 'Vasco da Gama arrives', x: 'Vasco da Gama’s fleet calls at Mozambique Island (March), at Mombasa (April, a hostile reception) and at Malindi (April), where the ruler, a rival of Mombasa, welcomes the Portuguese and provides a pilot for the crossing to India. A stone pillar was erected at Malindi (1498–99, the date varies).' },
    { d: '1500', t: 'Cabral', x: 'Pedro Álvares Cabral, on his way to India, calls at Mozambique, tries without success to make a treaty with Kilwa, and is well received at Malindi, where he takes on pilots.' },
    { d: '1502', t: 'Da Gama imposes tribute on Kilwa', x: 'On a second voyage, Vasco da Gama threatens to bombard Kilwa, and its ruler agrees to pay yearly tribute to Portugal.' },
    { d: '1505', t: 'Sack of Kilwa and Mombasa', x: 'On 24 July 1505 the fleet of the viceroy **Francisco de Almeida** attacks Kilwa with about 500 men and plunders it, then builds a fort (Santiago). In August it takes and burns Mombasa. In the following years (to c. 1515) the Portuguese come to dominate the main ports of the coast.' },
    { d: 'c. 1500', t: 'End of the period of this chapter', x: 'The golden age of the Swahili city-states ends. What follows (Portuguese forts and control of trade, Omani expansion in the 17th century, the Zanzibar sultanate in the 19th century) is the story of another period.' }
  ] },
  { h: 'Epilogue: after 1500 and the Portuguese link' },
  'The Portuguese arrival in 1498–1509 is the end of the independence and prosperity of the Swahili towns, as they were no longer free to trade as they wished: ships had to carry Portuguese passes (*cartazes*) and pay duties, and the gold of Sofala was largely diverted. The Portuguese left Kilwa in 1512 and the sultanate continued, weakened. After a long stay, in 1593–96 they built **Fort Jesus** at Mombasa, designed by the Italian engineer Giovanni Battista Cairati, in the time of Philip I of Portugal (Philip II of Spain). In 1698, after a long siege, Omani forces took the fort, and from then on Portuguese influence on the coast north of Mozambique was virtually over (with a brief return in 1728–29).',
  'The encounter left traces in the Swahili language. According to etymological dictionaries, words such as **meza** (table, from *mesa*), **mvinyo** (wine, from *vinho*), **bendera** (flag, from *bandeira*), **leso** (a kerchief, from *lenço*), **pesa** (money, from *peso*) and **gereza** (prison, from *igreja*, «church», apparently because a church was used as a jail) come from Portuguese. Portuguese chroniclers such as João de Barros and Duarte Barbosa also left some of the earliest long descriptions of the Swahili towns, in particular of Kilwa, Mombasa and Malindi, though from the point of view of the conquerors.',
  { img: 'sua-armada-1505', leg: 'Portuguese fleet off a Swahili town in 1505; artistic reconstruction. AI-generated illustration.' },
  { img: 'sua-forte-kilwa', leg: 'Kilwa Kisiwani fort, the Gereza.' }
];

const mapa = [
  'The Swahili city-states are a chain of ports along the coast, each with its own history. This map and table show the main ones, from north to south. Note that the northernmost (Mogadishu and Brava) belong to the Somali coast, with its own language and culture, but share the trade network with the Swahili towns, and many historians include them in the same world.',
  { img: 'sua-rotas-monsao', leg: 'Schematic map of seasonal Indian Ocean connections: teal for voyages towards East Africa during the northern winter, ochre for return voyages during the northern summer. Arrows indicate schematic journeys, not local wind directions.' },
  { tabela: { cab: ['Town', 'Where today', 'Period', 'Known for'], linhas: [
    ['Mogadishu and Brava (Barawa)', 'Southern Somalia', 'c. 10th – 16th c.', 'Northern ports with their own coinage, textiles and great mosques (Fakhr al-Din, 1269); Mogadishu was visited by Ibn Battuta'],
    ['Shanga', 'Pate Island, Kenya', 'c. 8th – early 15th c.', 'Excavated by Horton: shows the African origin of the towns; timber and stone mosques'],
    ['Manda', 'Manda Island, Kenya', 'c. 8th – 15th c.', 'Large town with coral-stone houses and a sea wall; early imports'],
    ['Lamu', 'Lamu Island, Kenya', 'c. 14th c. – today', 'Best-preserved Swahili town; carved doors; UNESCO 2001'],
    ['Pate', 'Pate Island, Kenya', 'c. 13th c. – 19th c.', 'Powerful sultanate; Pate Chronicle; poetry'],
    ['Gedi', 'Near Malindi, Kenya', 'c. 11th/12th – mid 17th c.', 'Town in the forest with a palace, mosques and a pillar tomb (1399); UNESCO 2024'],
    ['Malindi', 'Kenya', 'c. 14th c. – today', 'Ally of the Portuguese in 1498; sent a giraffe to China; the Vasco da Gama pillar'],
    ['Mombasa', 'Kenya', 'c. 12th c. – today', 'Island port; hostile to Da Gama (1498); sacked in 1505; Fort Jesus (UNESCO 2011)'],
    ['Zanzibar (Unguja Ukuu, Kizimkazi)', 'Zanzibar, Tanzania', 'c. 7th c. – today', 'Early trading port; Kizimkazi mosque (inscription of 1107)'],
    ['Mafia (Kisimani Mafia, Chole)', 'Mafia Island, Tanzania', 'c. 8th – 16th c.', 'Island towns near Kilwa and under its influence'],
    ['Kilwa Kisiwani', 'Tanzania', 'c. 9th c. – 16th c.', 'The richest town: Great Mosque, Husuni Kubwa, coins, gold of Sofala; UNESCO 1981'],
    ['Songo Mnara', 'Tanzania', 'c. 14th – 16th c.', 'Well-preserved town of stone houses; UNESCO 1981'],
    ['Sofala', 'Mozambique', 'c. 10th – 16th c.', 'Port of the gold from the Zimbabwe plateau, a Kilwa dependency; Portuguese fort from c. 1505–06']
  ] } },
  { h: 'Mogadishu and the north' },
  'Mogadishu, in southern Somalia, was already an important port in the early Middle Ages and by the 13th–14th century was a large and wealthy city, with its own coinage, a famous cloth industry (the *toob Benadir*, exported to Egypt and elsewhere) and great mosques. The mosque of Fakhr al-Din dates from 1269. Ibn Battuta visited it c. 1331 and described it as a city of enormous size, with many rich merchants, and a sultan who spoke both Arabic and the local language. Its Somali culture differs from the Swahili one further south, but the trade links were close.',
  { img: 'sua-mogadiscio-mesquita', leg: 'Fakhr al-Din Mosque, Mogadishu.' },
  { h: 'The Lamu archipelago: Shanga, Manda, Lamu and Pate' },
  'In the north of Kenya, the Lamu archipelago has some of the oldest and best-studied sites. **Shanga**, on Pate Island, was excavated by Mark Horton (1980s): it was founded in the 8th century, by farmers and fishers, and had a sequence of mosques; its stone town, of some 185 stone structures (according to the excavations), was abandoned c. 1400–1425. **Manda**, on an island nearby, was excavated by Neville Chittick in the 1960s and had large coral-stone houses and a sea wall. **Lamu** developed later (the town is at least 700 years old) and **Pate**, according to the Pate Chronicle, was ruled by the Nabhani dynasty; Pate poets later produced the oldest great works of Swahili literature in writing (17th–18th century).',
  { img: 'sua-shanga-ruinas', leg: 'Ruins on Pate Island, Kenya; the source does not identify them as Shanga.' },
  { img: 'sua-manda-ruinas', leg: 'Mosque wall at the ruins of Takwa, Manda Island, Kenya.' },
  { h: 'Gedi and Malindi' },
  'Gedi, in the forest not far from Malindi, was founded in the 11th–12th century (the earliest grave marker has been radiocarbon-dated to 1041–1278) and flourished in the 15th–16th centuries, with perhaps 2,500 inhabitants in a walled town of about 18 hectares. It has a Great Mosque, a palace, houses, wells and a pillar tomb with a date corresponding to 1399. Excavations found Chinese coins and celadon, Venetian beads and Islamic ceramics. It was abandoned in the mid-17th century; the reasons are debated (changes in the water supply and insecurity are among the explanations suggested). **Malindi**, to the north, rose in the 14th–15th centuries and, as a rival of Mombasa, welcomed Vasco da Gama in 1498.',
  { img: 'sua-gedi-ruinas', leg: 'Gedi ruins, Kenya.' },
  { img: 'sua-gedi-tumulo', leg: 'Pillar tomb at Gedi.' },
  { h: 'Mombasa' },
  'Mombasa was an island port that Ibn Battuta described c. 1331 as a place whose people were devout, of the Shafi’i rite, and whose mosques, he says, were strongly built of timber. By the 15th century it was a major rival of Malindi and Kilwa. In 1498 it greeted Vasco da Gama with suspicion, and in 1505 it was taken and burnt by the Portuguese. The present **Fort Jesus** (1593–96) is Portuguese.',
  { img: 'sua-mombaca-forte-jesus', leg: 'Fort Jesus, Mombasa (1593–1596).' },
  { h: 'Zanzibar and Mafia' },
  'Zanzibar (Unguja) was one of the first trading places of the coast: at **Unguja Ukuu**, excavations found imported pottery and glass from the Gulf and beads from the 7th–10th century, and at **Kizimkazi**, in the south of the island, a mosque has a Kufic inscription read as 1107 (the present building was largely rebuilt in the 18th century). The famous Stone Town of Zanzibar, however, is mostly 19th-century. **Mafia Island**, with Kisimani Mafia and Chole, was part of the circle of Kilwa and had coral-stone buildings and mosques.',
  { img: 'sua-kizimkazi', leg: 'Kizimkazi Mosque, Zanzibar, associated with an inscription dated 1107.' },
  { h: 'Kilwa Kisiwani, the richest city' },
  'Kilwa Kisiwani, on a small island off the south of Tanzania, was the richest and most powerful town in the Swahili world in the 14th–15th centuries. The **Kilwa Chronicle**, which survives in two versions (an Arabic one, the *Kitāb al-Sulwa*, and a Portuguese one by João de Barros, published in 1552), tells how Ali ibn al-Hasan of Shiraz founded the **Shirazi dynasty**; after it, the **Mahdali** dynasty came to power c. 1277. The chronicle is based on oral tradition and was altered to suit those in power, but recent DNA studies appear compatible with part of its core (the arrival of men from across the ocean who mixed with the local population).',
  'The town grew rich from the gold of **Sofala**, which Kilwa controlled, and from taxing all passing trade. It struck its own coins (copper and silver), and its merchants dealt with Arabia, India and China. The **Great Mosque**, begun in the 11th–12th century, was enlarged in the early 14th century under al-Hasan ibn Sulaiman with a great dome and vaults, a rare achievement in sub-Saharan Africa. The oldest part of the mosque dates to the 12th century (some authors push it back to the 11th). Close by, he built the palace of **Husuni Kubwa** («great fortress»), on a cliff overlooking the sea: about a hundred rooms and terraces around sunken courtyards, a large trading court with storerooms, and an octagonal swimming pool. The palace appears to have been left unfinished and soon abandoned.',
  { cit: 'Kilwa is one of the most beautiful and most elegantly built towns in the world.', fonte: 'Ibn Battuta, Rihla, on Kilwa (paraphrase of the sense; translations vary, for example H. A. R. Gibb’s)' },
  { img: 'sua-kilwa-cupulas', leg: 'Interior arches of the Great Mosque of Kilwa Kisiwani.' },
  { img: 'sua-husuni-kubwa', leg: 'Octagonal pool in the ruins of Husuni Kubwa palace, Kilwa.' },
  { img: 'sua-kilwa-reconstrucao', leg: 'Kilwa harbour around 1330, mosque and Husuni Kubwa palace; hypothetical reconstruction. AI-generated illustration.' },
  { h: 'Songo Mnara' },
  'On a small island south of Kilwa, Songo Mnara was occupied from the 14th to the 16th century. It has some five or six mosques (the count varies), cemeteries and a few dozen coral-stone house blocks, with plaster floors and niches. The excavations led by Jeffrey Fleisher and Stephanie Wynne-Jones (since 2009) show that people of different standing, in houses of stone and of earth, used similar imported goods, and that houses were open to commerce.',
  { img: 'sua-songo-mnara', leg: 'Songo Mnara ruins, Tanzania.' },
  { h: 'Sofala and Great Zimbabwe' },
  'The gold that made Kilwa rich was mined in the interior (the Zimbabwe plateau) and carried to the coast at **Sofala**, in Mozambique. Inland, the stone city of **Great Zimbabwe** (c. 11th–15th century) was at the centre of this trade: among its finds are Chinese celadon and glass beads that came through the Swahili ports, and some Kilwa coins have been found there. These two civilizations did not share a language or an architecture, but they depended on one another.',
  { img: 'sua-great-zimbabwe', leg: 'Great Enclosure at Great Zimbabwe.' },
  { h: 'The sea routes' },
  'The sea routes were the lifeline of the cities. From December to March the **north-east monsoon** (*kaskazi*) brought dhows from Arabia, Persia and India to Africa; from April to September the **south-west monsoon** (*kusi*) carried them back. A voyage between the Gulf and Kilwa could therefore be made once a year, with a stay on the coast of a few months. The Swahili merchants and ship-owners acted as middlemen: they did not control the Indian Ocean, but they sat at one of its crossroads.'
];

const sociedade = [
  'Almost everything we know about daily life on the Swahili coast comes from archaeology, from a few foreign travellers and chroniclers (Ibn Battuta, later the Portuguese) and from later Swahili traditions. The Swahili wrote little about themselves in this period, so what follows mixes evidence with careful inference, and says so where it is uncertain.',
  { h: '1. Political organization' },
  'Each town was an independent **city-state**, governed by a ruler (called *sultan*, *mfalme* or other titles, depending on the town) with a council of notable families. Rulers were usually chosen from within a dynasty, such as the Shirazi and Mahdali in Kilwa, or the Nabhani in Pate, but succession was often disputed, and the real power sometimes lay with viziers and powerful merchants, as with the emir Muhammad Kiwabi in Kilwa in the late 15th century. Rulers collected customs duties, minted coins in a few places, built mosques and palaces and acted as judges together with the *qadi* (Islamic judge). There was no standing army and no empire: relations between cities were a mix of trade, alliance, marriage and rivalry. Kilwa was the strongest, and some cities (Mafia, Sofala) were under its influence.',
  { h: '2. Social classes' },
  'Society was ranked. At the top was the **patriciate**, the *waungwana* («free» or «civilized» people), landowners, merchants and ship-owners who lived in the stone town, claimed Arab or Shirazi descent and showed their status through houses, clothes and generosity. Below them were free craftsmen, sailors and fishers, who often lived in earthen houses on the edge of the stone town, and **enslaved people** (*watumwa*), mostly from the interior, who worked as domestic servants, in agriculture and as porters. Beyond the town lived the people of the mainland, such as farmers and hunters, whom the town people sometimes called *washenzi* («barbarians»), though they were closely tied to the towns by trade.',
  { caixa: 'And the women?', texto: 'The evidence is scarce. The ancient DNA suggests that many men from outside took local wives, and that the people studied descended mostly from African women. Under Islamic law women could inherit and own property. Later Swahili tradition names several women rulers and poets, but for the period before 1500 the sources are silent, and much is conjecture.' },
  { h: '3. Religion' },
  'By the 11th–12th century most people of the stone towns were **Muslim**, mostly **Sunni** of the **Shafi’i** school; some early presence of other tendencies (such as the Ibadi) is discussed. Conversion was slow, by example and trade rather than by conquest, and old beliefs, especially in spirits (*pepo* and *jini*), continued alongside Islam, as they do today.',
  { tabela: { cab: ['Element', 'Role'], linhas: [
    ['Friday mosque (*msikiti*)', 'The centre of each town; coral-stone, with a mihrab (prayer niche) and a courtyard for ablutions. The first mosques were of timber.'],
    ['Qadi and learned men', 'Judges and teachers, who applied Islamic law and ran the Quran schools'],
    ['Sharifs and sayyids', 'Families who claimed descent from the Prophet; highly respected (as the Mahdali of Kilwa)'],
    ['Pilgrimage and learning', 'Some people went on the *hajj* or studied in Arabia; scholars came from Arabia and Yemen to teach'],
    ['Spirits (*pepo*, *jini*)', 'Beliefs in spirits that cause illness or good fortune, with healers and rituals, which survived under Islam'],
    ['Mwaka Kogwa', 'A festival of New Year held at Makunduchi (Zanzibar), whose origins (perhaps the Persian Nowruz?) are debated']
  ] } },
  { h: 'Life after death' },
  'Muslims were buried on their side, facing Mecca. Rich men were buried in stone tombs, often in front of the mosque; some of them (14th–15th centuries) had a tall **pillar** rising from the tomb (in Swahili *nguzo*), and some were decorated with imported Chinese porcelain bowls set into the plaster. The pillar tombs, found at Gedi, Mnarani, Malindi and elsewhere, are among the most distinctive Swahili monuments. Their purpose is not fully understood: they may mark the status of the dead.',
  { img: 'sua-mnarani-pilar', leg: 'Ruins of the Great Mosque at Mnarani, Kilifi, Kenya; an alternative to a pillar-tomb photograph.' },
  { img: 'sua-cerimonia-sexta', leg: 'Friday prayer in a Swahili mosque around 1350; imagined scene. AI-generated illustration.' },
  { h: '4. Economy and trade' },
  'The economy of the towns rested on **trade**, helped by a little fishing, farming and crafts. Farming (sorghum, millet, coconut, bananas, rice) fed the towns, but the wealth came from selling goods from the African interior and buying goods from the Indian Ocean world.',
  { tabela: { cab: ['Exports (from Africa)', 'Imports (to Africa)'], linhas: [
    ['Gold (from Zimbabwe, via Sofala)', 'Cotton and silk cloth (India, Gulf)'],
    ['Ivory', 'Glass beads and carnelian beads (India, Southeast Asia)'],
    ['Iron and copper', 'Chinese porcelain and celadon'],
    ['Mangrove poles (building timber) for Arabia', 'Glazed ceramics from the Persian Gulf and Iran'],
    ['Tortoiseshell, ambergris, rhino horn, rock crystal', 'Glass vessels, perfumes, spices'],
    ['Enslaved people (a small scale until the 18th century)', 'Silver and, in some periods, weapons']
  ] } },
  'The ships were **dhows**, wooden sailing vessels with a triangular (lateen) sail. On this coast there was also the *mtepe*, a large vessel whose planks were not nailed but **sewn together with coconut fibre**, a technique mentioned in the *Periplus* of the 1st century. Duties on cargo were collected in the harbour, and merchants from Arabia, India and Persia lived in the towns for months while waiting for the monsoon to change.',
  { img: 'sua-dhow', leg: 'Traditional lateen-sailed dhow, Lamu.' },
  { img: 'sua-mtepe', leg: 'Mtepe, a coir-sewn boat, on the beach at Zanzibar, around 1890.' },
  { img: 'sua-mercado-cais', leg: 'Trade on the quay of a Swahili port around 1400; imagined scene. AI-generated illustration.' },
  { img: 'sua-porcelana', leg: 'Celadon dish from the Longquan kilns, China, Yuan dynasty, 1300–1400.' },
  { img: 'sua-contas', leg: 'Detail of a mutisalah necklace from Timor with Indo-Pacific beads: a comparative example, not a find from the Swahili coast.' },
  { img: 'sua-moeda-kilwa', leg: 'Quiloa (Kilwa), engraving by Georg Braun and Franz Hogenberg, Civitates orbis terrarum, 1572; an alternative to the coin.' },
  { h: '5. Writing, learning and history' },
  'The language of religion, law and trade was **Arabic**, written in Arabic script; the coins and inscriptions (such as Kizimkazi 1107 and Mogadishu 1269) are in Arabic. Swahili itself was mainly spoken, and the first poetry we have in writing in Swahili (in Arabic script) is later (17th–18th century), though oral poetry certainly existed earlier. The history of the towns was passed on in chronicles that mix fact and legend: the **Kilwa Chronicle** and the **Pate Chronicle**, the latter published in English by C. H. Stigand in 1913. Quran schools taught reading and writing to boys, and learned men (*ulama*) taught law and theology.',
  { h: '6. House and family' },
  'The typical **stone house** (*nyumba ya mawe*) was a rectangular block of coral rag and lime mortar, usually one or two storeys, without windows to the street. Inside, a sequence of long, narrow rooms (the width limited by the span of the mangrove-pole beams, or *boriti*) opened onto a courtyard; there was a porch with benches (*baraza*) for receiving guests, a latrine and a well. In the plastered walls were **niches** (*zidaka*) in which imported porcelain was displayed. Poor people lived in houses of earth and thatch, near the stone town. Families were large, with servants and slaves, and the house was both home and business, with storerooms for goods.',
  { img: 'sua-casa-interior', leg: 'Interior of a coral-stone house around 1400; hypothetical reconstruction. AI-generated illustration.' },
  { img: 'sua-porta-lamu', leg: 'Carved wooden door in Lamu.' },
  { h: '7. Food' },
  'The base of the diet was cereals (sorghum, millet), later rice, with coconut, bananas, citrus fruits, sugar cane and vegetables, and **fish and shellfish** in abundance, along with goat, chicken and beef. Spices and rice were imported. Many foods that are now typical (maize, cassava, chillies, cashews, pineapples) came from the Americas and were introduced by the Portuguese **after 1500**, and so are not part of this chapter. Meals in rich houses were served on imported ceramics.',
  { h: '8. Clothes and jewellery' },
  'Elites wore cotton and silk imported from India and the Gulf, and local cloth (Mogadishu was famed for its textiles); men wore long robes and turbans or caps, women wore wrapped cloth and veils, though the details of dress before 1500 are poorly known. The rich wore **jewellery** of gold and silver, glass and carnelian beads, bracelets, rings and anklets; beads are among the most common finds. Ibn Battuta praises the generosity of the sultan of Kilwa in giving gifts, which earned him the epithet *Abu’l-Mawahib*.',
  { h: '9. Music and games' },
  'Music was based on drums, horns and other instruments, with songs and poetry. Ibn Battuta describes the sultan of Mogadishu escorted by musicians with drums and trumpets. The best-known Swahili horn, the **siwa**, of ivory or brass, is a symbol of chieftaincy at Lamu and Pate, and survives from later periods. A game found throughout East Africa, **bao** (mancala), was played on boards that are also carved on the stone of Swahili ruins; the dating of the earliest boards and the origin of the game are debated.',
  { img: 'sua-siwa', leg: 'Wedding dress and musicians with siwas in Lamu, engraving after a photograph by John Kirk.' },
  { img: 'sua-bao', leg: 'Bao board, an East African mancala game.' },
  { h: '10. Science, navigation and medicine' },
  'Swahili pilots used the stars and the monsoon calendar, and shared the knowledge of Arab, Persian and Indian navigators. Arabic sailing manuals by Ahmad ibn Majid (late 15th century) describe the East African coast. The **calendar** mixed the Islamic lunar year with a solar one for farming and navigation, and the New Year (*Nairuzi*) is celebrated in some places. Medicine combined Islamic learning with local herbal knowledge and healers; much is poorly documented for this period.',
  { h: '11. Technology' },
  { lista: [
    '**Coral building:** blocks of coral rag (dead reef) were cut and laid in lime mortar, with fresh coral (soft *Porites*) carved for mihrabs, doorways and tomb decoration; lime was made by burning coral.',
    '**Vaults and domes:** at Kilwa and other places, vaults and domes were made of coral and mortar, which was rare in Africa south of the Sahara.',
    '**Ironworking:** iron was smelted on the coast and inland, and exported.',
    '**Shipbuilding:** dhows and sewn boats made with local timber and coconut fibre.',
    '**Coins and weights:** the minting of copper and silver coins in Kilwa and Mogadishu.',
    '**Beads and weaving:** bead-making, ivory carving and cotton weaving.'
  ] },
  { img: 'sua-coral-cantaria', leg: 'Coral masonry and lime preparation for a mosque around 1300; imagined scene. AI-generated illustration.' },
  { h: '12. War' },
  'The Swahili towns were defended by walls (as at Gedi), by their island position and by archers; there were no large armies. Conflicts were mostly between towns (for example Mombasa against Malindi) or with the people of the mainland. Their weapons were bows, spears and swords. This explains why the Portuguese, with ships armed with cannon, steel armour and firearms, were able to overcome them quickly in 1505, although in Mombasa the defenders (according to Portuguese chroniclers, with some 1,500 archers from the mainland) resisted hard.'
];

const personalidades = [
  'Most Swahili people of this period are unnamed, and many rulers we know about from chronicles are partly legendary. These are the main figures, real or semi-legendary, and the scholars who study them.',
  { h: 'Ali ibn al-Hasan, founder of the Shirazi dynasty of Kilwa' },
  'The traditional founder of Kilwa, said by the chronicle to be a prince of Shiraz who came by sea with his family. Whether he existed as described is **debated**; coins attributed to a ruler of this name suggest that there was a real sultan Ali ibn al-Hasan in the 12th century, but the story of Persian origin may be partly a legend of legitimacy.',
  { h: 'Al-Hasan ibn Sulaiman (Abu’l-Mawahib), sultan of Kilwa' },
  'Ruled c. 1310 – c. 1333, the best-known of the Mahdali sultans. Ibn Battuta, who met him, praised his humility and generosity (the title *Abu’l-Mawahib* means «father of gifts»). He is credited with the palace of Husuni Kubwa and with the great extension of the Great Mosque, and he led the town at its peak.',
  { h: 'Muhammad Kiwabi, emir of Kilwa' },
  'A powerful emir (military leader and kingmaker) in Kilwa in the late 15th century, when the Mahdali sultans were weak. He shows how real power could pass from the sultan to his chief officials.',
  { h: 'Sulaiman ibn Sulaiman al-Nabhani, sultan of Pate' },
  'In the Pate Chronicle, the first Nabhani ruler of Pate, who is said to have arrived from Arabia c. 1203–04 and married into the local ruling family. The date and the account are **traditional and uncertain**.',
  { h: 'Fumo Liongo, the hero-poet' },
  'A **legendary** figure of Swahili tradition, usually placed in the north coast (Pate, Shungwaya) and often dated to the late Middle Ages, a warrior and poet in conflict with a ruler. Poems attributed to him are told and sung, but historians cannot say if he existed or when he lived.',
  { h: 'Ibn Battuta, the traveller' },
  'Born in Tangier, Morocco, in 1304, he travelled for some 29 years in Africa, Asia and Europe, and dictated his account (the *Rihla*) in 1355 to the scholar Ibn Juzayy. Around 1331 (the date is debated) he visited Mogadishu, Mombasa and Kilwa. He is the best-known written eyewitness of the Swahili world before the Portuguese, though some scholars question the details and chronology of his East African journey.',
  { img: 'sua-ibn-battuta', leg: 'Ibn Battuta in Egypt, illustration by Léon Benett, nineteenth century.' },
  { h: 'Zheng He, the Ming admiral' },
  'A Chinese eunuch admiral who commanded seven great naval expeditions between 1405 and 1433. According to Chinese sources, some fleets reached the coast of East Africa (Mogadishu, Brava, Malindi). The size of his ships is disputed, and how far south he went is debated. In any case, Chinese porcelain and African giraffes show that the two worlds were in contact.',
  { img: 'sua-girafa-ming', leg: 'Tribute Giraffe with Attendant, a sixteenth-century Chinese painting according to the Philadelphia Museum of Art, recalling the giraffe presented to the Ming court in 1414. Its attribution to Shen Du is not considered certain by the museum.' },
  { img: 'sua-zheng-he', leg: 'Modern statue of Zheng He at Sam Po Kong temple, Semarang, Indonesia.' },
  { h: 'Vasco da Gama (c. 1460–1524)' },
  'The Portuguese navigator who in 1497–99 opened the sea route to India. On the East African coast he stopped at Mozambique, Mombasa (where he met hostility) and Malindi (where the ruler welcomed him and gave him a pilot). In 1502, on a second voyage, he made Kilwa a tributary of Portugal.',
  { img: 'sua-vasco-da-gama', leg: 'Portrait of a knight, said to be Vasco da Gama, unknown Portuguese master, 1525–1550; Museu Nacional de Arte Antiga, Lisbon.' },
  { h: 'Francisco de Almeida (c. 1450–1510)' },
  'The first Portuguese viceroy of India (1505–09). In 1505, on his way to India, he took Kilwa (24 July) and Mombasa (August). He built the fort of Santiago in Kilwa. He died in 1510 at the Cape of Good Hope, killed by Khoikhoi people after an incident, on his way back to Portugal.',
  { img: 'sua-almeida', leg: 'Portrait of Francisco de Almeida, unknown artist, after 1545; Museu Nacional de Arte Antiga, Lisbon.' },
  { h: 'Pêro da Covilhã' },
  'A Portuguese spy and explorer sent by John II in 1487 to find the Christian kingdom of Prester John and the spice route. He went to India and, according to tradition, passed through Sofala on the East African coast, c. 1489–90, before going back to Cairo (the details of his itinerary are debated). He later stayed in Ethiopia. He is part of the Portuguese prehistory of the sea route.',
  { h: 'The modern researchers' },
  'Our picture of the Swahili world is the work of archaeologists: **James Kirkman** (Gedi, 1948 on), **Neville Chittick** (Kilwa and Manda, 1950s–60s), **Mark Horton** (Shanga and Zanzibar, 1980s), **Chapurukha Kusimba** (author of *The Rise and Fall of Swahili States*, 1999), **Felix Chami** (Tanzanian coast and islands) and, at Songo Mnara, **Jeffrey Fleisher** and **Stephanie Wynne-Jones** (since 2009). Chittick, although an excellent excavator, interpreted the culture as largely Persian, a view later rejected by his successors.'
];

const legado = [
  { h: 'What they left us' },
  { lista: [
    '**A living language:** Swahili, spoken today by over 100 million people, the lingua franca of East Africa.',
    '**An African Islam:** a coastal culture that fused African, Arab, Persian and Indian elements, which remains alive.',
    '**Stone architecture:** the oldest coral-stone towns of Africa south of the Sahara, with their mosques, palaces, houses and pillar tombs.',
    '**A model of trade without conquest:** cities that became rich as middlemen of the Indian Ocean.',
    '**A literature:** Swahili poetry (from the 17th–18th century in surviving manuscripts) and the chronicles of Kilwa and Pate.',
    '**A lesson about history:** the debate on their origins shows how prejudice distorted the study of Africa.'
  ] },
  { h: 'Art and crafts' },
  'Swahili art is mostly architectural and decorative: carved coral and plaster (mihrabs, niches, tombs), carved wooden doors and furniture (especially at Lamu, later), jewellery and beadwork, cloth and basketry, and the poetry and song of the coast. Imported porcelain and glass were also part of the decoration of the house.',
  { h: 'Architecture: coral stone' },
  'Swahili builders used **coral rag** and lime to raise mosques with domes and vaults, houses with courtyards and niches, palaces such as Husuni Kubwa and tall pillar tombs. These are original forms, unlike those of Arabia or Persia, and they developed from local techniques (such as the use of mangrove poles for roofs).',
  { img: 'sua-ilha-mocambique', leg: 'Fortress of São Sebastião, Mozambique Island.' },
  { h: 'The rediscovery of the Swahili world' },
  'European travellers and officials described the ruins from the 19th century. **James Kirkman** began the scientific excavation of Gedi in 1948, **Neville Chittick** excavated Kilwa (1958–65) and Manda (1960s), and in the 1980s **Mark Horton** showed at Shanga that the first settlers were African. Since the 1990s, Tanzanian and Kenyan scholars (Chami, Kusimba and others) and new work at Songo Mnara have changed the picture again, and DNA research (2023) has added a new level of evidence. Until the 1970s, many books wrote the Swahili as an «Arab» or «Persian» people; today the African perspective is the norm.',
  { h: 'Where to visit' },
  { tabela: { cab: ['Site', 'Country', 'Note'], linhas: [
    ['Kilwa Kisiwani and Songo Mnara', 'Tanzania', 'UNESCO 1981 (in Danger 2004–2014): Great Mosque, Husuni Kubwa, Gereza fort; Songo Mnara by boat'],
    ['Lamu Old Town', 'Kenya', 'UNESCO 2001: oldest living Swahili town; Lamu Museum (siwa horns, doors)'],
    ['Gedi Ruins', 'Kenya', 'UNESCO 2024: ruined town in the forest; pillar tomb'],
    ['Fort Jesus, Mombasa', 'Kenya', 'UNESCO 2011: Portuguese fort (1593–96), museum'],
    ['Malindi', 'Kenya', 'Vasco da Gama pillar; Portuguese chapel'],
    ['Island of Mozambique', 'Mozambique', 'UNESCO 1991: Portuguese fortress of São Sebastião, early Swahili town'],
    ['Zanzibar (Kizimkazi, Unguja Ukuu)', 'Tanzania', 'Kizimkazi mosque (inscription of 1107; building rebuilt in the 18th century); Stone Town (19th century)'],
    ['Mogadishu', 'Somalia', 'Mosque of Fakhr al-Din (1269); the security situation limits visits']
  ] } }
];

const quiz = [
  { p: 'What does the name «Swahili» come from?', op: ['A Persian word for «island»', 'The Arabic *sawāḥil*, «the coasts»', 'The name of a king of Kilwa', 'A Portuguese word for «sailors»'], certa: 1, exp: 'Swahili comes from the Arabic sawāḥil, plural of sāḥil («coast»): «the people of the coasts».' },
  { p: 'What kind of language is Swahili?', op: ['A Semitic language, like Arabic', 'An Indo-European language', 'A Bantu language with many Arabic loanwords', 'A creole of Portuguese'], certa: 2, exp: 'Swahili is a Bantu language; Arabic loanwords are many, but the grammar and basic vocabulary are Bantu.' },
  { p: 'What did the legend of the «Shirazi» say about the origin of the Swahili towns?', op: ['That they were founded by Portuguese sailors', 'That they were founded by Persian princes from Shiraz', 'That they were founded by Chinese admirals', 'That they came from Great Zimbabwe'], certa: 1, exp: 'The Kilwa Chronicle says a prince from Shiraz founded the Shirazi dynasty. Archaeology shows the towns grew from African communities.' },
  { p: 'Which archaeologist’s excavations at Shanga (1980s) helped to show the African origins of the Swahili towns?', op: ['Howard Carter', 'Mark Horton', 'Leonard Woolley', 'Heinrich Schliemann'], certa: 1, exp: 'Mark Horton’s excavations at Shanga, on Pate Island, found African settlers who only gradually took up Islam and stone building.' },
  { p: 'What gave the monsoon such importance?', op: ['It made the sea calm', 'Its seasonal winds took the dhows to Africa and back', 'It watered the gold mines', 'It kept pirates away'], certa: 1, exp: 'The north-east monsoon brought ships from Arabia and India; the south-west monsoon carried them home.' },
  { p: 'Which material was used in the stone buildings of the Swahili towns?', op: ['Granite blocks', 'Marble', 'Coral rag and lime mortar', 'Baked brick'], certa: 2, exp: 'Builders used coral rag cut from dead reefs, with lime made by burning coral; fresh coral was carved for details.' },
  { p: 'Which Swahili city was the richest, thanks to the gold of Sofala?', op: ['Gedi', 'Kilwa Kisiwani', 'Lamu', 'Manda'], certa: 1, exp: 'Kilwa controlled Sofala, the port of the gold of the Zimbabwe plateau, and minted its own coins.' },
  { p: 'Who built the palace of Husuni Kubwa in Kilwa (14th century)?', op: ['Vasco da Gama', 'Sultan al-Hasan ibn Sulaiman', 'Ibn Battuta', 'Francisco de Almeida'], certa: 1, exp: 'Husuni Kubwa, with its octagonal pool and about a hundred rooms, is attributed to al-Hasan ibn Sulaiman (c. 1310–1333).' },
  { p: 'Which Moroccan traveller visited Mogadishu, Mombasa and Kilwa around 1331?', op: ['Marco Polo', 'Ibn Khaldun', 'Ibn Battuta', 'Zheng He'], certa: 2, exp: 'Ibn Battuta described Kilwa as one of the most beautiful and well-built towns in the world.' },
  { p: 'What is DEBATED about Zheng He and the Swahili coast?', op: ['Whether China produced porcelain', 'How far his fleets sailed down the African coast', 'Whether Mogadishu existed', 'Whether giraffes live in Africa'], certa: 1, exp: 'Chinese sources suggest visits to Mogadishu, Brava and Malindi, but direct proof is scarce and the extent of his voyages is debated.' },
  { p: 'Which Swahili town welcomed Vasco da Gama in 1498 and gave him a pilot for India?', op: ['Mombasa', 'Kilwa', 'Malindi', 'Songo Mnara'], certa: 2, exp: 'Malindi, a rival of Mombasa, welcomed da Gama; Mombasa had received him with hostility.' },
  { p: 'What happened at Kilwa on 24 July 1505?', op: ['Ibn Battuta arrived', 'The Great Mosque was begun', 'Francisco de Almeida’s fleet attacked and sacked the town', 'The sultan converted to Christianity'], certa: 2, exp: 'Almeida, with some 500 men, took and plundered Kilwa and built the Fort of Santiago.' },
  { p: 'Which of these Swahili words comes from Portuguese?', op: ['*Meza* (table)', '*Maji* (water)', '*Jambo* (hello)', '*Baraza* (bench)'], certa: 0, exp: 'Meza comes from the Portuguese mesa; others include mvinyo (vinho), bendera (bandeira) and pesa (peso).' },
  { p: 'Fort Jesus in Mombasa, a UNESCO site since 2011, was built by…', op: ['The Omanis in the 18th century', 'The Portuguese in 1593–96', 'The Swahili sultans in the 14th century', 'The British in the 19th century'], certa: 1, exp: 'It was designed by Giovanni Battista Cairati and built by the Portuguese in 1593–96; the Omanis took it in 1698.' },
  { p: 'What did the 2023 DNA study of people buried in medieval and early modern Swahili towns suggest?', op: ['They were all of Persian origin', 'They had mainly African female ancestry and some Asian (largely Persian) male ancestry', 'They had no African ancestry', 'They came from China'], certa: 1, exp: 'The results suggest mixing around AD 1000, with immigrants (mostly men) joining African society. It does not support «colonization».' }
];

export default { visao, linha, mapa, sociedade, personalidades, legado, quiz };
