// ROME — main page, full English content. Same structure and same image slots as the Portuguese version (dados.js).
// Conventional dates (753 BC tradition; 509 BC Republic; 27 BC Principate; AD 476 end of the Western Empire). Figures are estimates.

const visao = [
  { caixa: 'In brief', texto: [
    'Rome began as a small town in Latium, in central Italy, and over more than a thousand years became the largest state of the Mediterranean world. According to tradition it was founded in **753 BC**; it was a **monarchy**, then a **Republic** (from 509 BC) and, from **27 BC**, an **Empire** ruled by emperors. At its height, around AD 117, the Empire covered some 5 million km² and perhaps 50 to 100 million inhabitants (estimates vary widely), from Britain to the Euphrates and from the Rhine to the Sahara.',
    'The **Western** Roman Empire disappeared in **AD 476**, but the **Eastern** one, with its capital at Constantinople, lasted until 1453 (what we now call the Byzantine Empire, the subject of another page in this project). This page gives the overall picture and introduces the eight pages that go deeper into each period and each theme.'
  ] },
  { img: 'rom-loba-capitolina', leg: 'Capitoline Wolf, bronze, Capitoline Museums, Rome.' },
  { h: 'Where and when' },
  'Rome grew up beside the **Tiber**, about 25 km from the sea, at a point where the river could be crossed and the hills offered protection. From there it first dominated **Latium**, then the whole **Italian peninsula** (by c. 264 BC), then the **Mediterranean** (by c. 146 BC) and finally western and central Europe, the Near East and North Africa. The Romans called the Mediterranean *Mare Nostrum*, “our sea”.',
  { tabela: { cab: ['Phase', 'Dates (conventional)', 'Regime', 'Page to go deeper'], linhas: [
    ['Foundation and Monarchy', 'c. 753 – 509 BC (tradition)', 'Seven kings, according to tradition; archaeology shows a city taking shape', 'Monarchy and Early Republic'],
    ['Early Republic', '509 – 264 BC', 'Consuls, Senate, assemblies; Conflict of the Orders; conquest of Italy', 'Monarchy and Early Republic'],
    ['Late Republic', '264 – 27 BC', 'Expansion across the Mediterranean; social crisis and civil wars', 'The Late Republic'],
    ['High Empire (Principate)', '27 BC – AD 192', 'Emperors, behind a republican façade; Pax Romana', 'The High Empire'],
    ['Crisis and Dominate', 'AD 193 – 476 (West)', 'Third-century crisis, reforms, absolute emperors, Christianisation', 'Crisis, Dominate and Fall']
  ] } },
  { img: 'rom-mapa-imperio', leg: 'Map of the Roman Empire in AD 117, with its provinces.' },
  { h: 'Foundation: myth and archaeology' },
  'The Romans said that **Romulus**, a descendant of Aeneas, the Trojan who escaped from Troy, founded the city on 21 April 753 BC after killing his brother **Remus**. The date was fixed by the scholar **Varro** in the 1st century BC; it is a **tradition**, not a fact. Archaeology shows something slower: villages of huts on the Palatine and other hills from the 10th–9th century BC, which gradually merged; the valley of the future Forum was drained and paved around 600 BC, and only then can we speak of a real city. We also know that archaic Rome was strongly influenced by the **Etruscans** (to the north) and the Greeks of southern Italy.',
  { img: 'rom-cena-fundacao', leg: 'AI-generated illustration. Iron Age village on the Palatine, c. 750 BC: conjectural reconstruction.' },
  { h: 'Why it matters' },
  { lista: [
    '**Law:** Roman law underlies the legal systems of continental Europe, Portugal included, and of Latin America.',
    '**Language:** Latin gave us Portuguese, Spanish, French, Italian and Romanian, and a large part of the scientific and legal vocabulary of every European language.',
    '**Politics:** the words *republic*, *senate*, *citizen*, *dictator* and the ideas of separated powers and annual magistracies come from Rome (and were read anew by Machiavelli, Montesquieu and the founders of the United States).',
    '**Engineering and town planning:** roads, aqueducts, bridges, sewers, concrete and cities with a grid plan.',
    '**Christianity:** the religion was born in a Roman province and spread along the Empire’s roads and cities; in the 4th century it became the religion favoured by the state.',
    '**The Iberian Peninsula:** Portugal was, in large part, the province of **Lusitania**; Roman cities, roads and ruins are part of our territory.'
  ] },
  { h: 'How to use this page and the others' },
  'This is the **main page**: it summarises. Each period and theme has its own page, reachable from the project menu:',
  { lista: [
    '**Monarchy and Early Republic:** from the foundation to 264 BC; Twelve Tables, Conflict of the Orders, Latin and Samnite wars, Pyrrhus.',
    '**The Late Republic:** 264 to 27 BC; Punic Wars, Gracchi, Marius and Sulla, Spartacus, Caesar, Actium.',
    '**The High Empire:** from Augustus to Commodus; Pax Romana, the peak under Trajan, provinces.',
    '**Crisis, Dominate and Fall:** AD 193 to 476; Diocletian, Constantine, invasions, end of the West.',
    '**Emperors and great figures:** biographies and a table of emperors.',
    '**Army and warfare:** legions, equipment, tactics, navy, limes.',
    '**Cities, monuments and engineering:** Rome, Pompeii, Ostia, aqueducts, roads, Hispania.',
    '**Religion, law and daily life:** gods, family, slavery, house, food, spectacles.'
  ] },
  { caixa: 'Beware of what “everybody knows”', texto: [
    'Much that is said about Rome is modern myth or from the movies: Nero did **not** play the lyre while Rome burned (there is no proof; the fire of AD 64 is real, Nero’s behaviour is debated); gladiators did **not** always say “Ave Caesar, morituri te salutant” (it is attested only once, at a naval show under Claudius); the thumbs-down gesture is not proven; the *vomitoria* were the exits of amphitheatres, not places to vomit. Throughout the page we mark what is tradition, what is debated and what is documented.'
  ] },
  { h: 'Rome today' },
  'The Empire left thousands of ruins, many of them UNESCO World Heritage Sites: the historic centre of Rome, Pompeii, Hadrian’s Wall, the Pont du Gard, Mérida and many more. The fall of the West in 476 is a **convention** of historians: for contemporaries it was a slow transformation, and many institutions, the language and the Church continued. The word “Rome” still names a living city of about 2.8 million inhabitants, where a Pantheon almost 1,900 years old is still in use.'
];

const linha = [
  'Conventional dates; those before c. 500 BC belong to tradition rather than documented history. For the detail of each period, see the respective pages.',
  { linha: [
    { d: 'c. 753 BC (tradition)', t: 'Foundation of Rome', x: 'According to Varro, Romulus founded the city on 21 April 753 BC. Archaeology shows settlements on the hills from the 10th–9th century BC, with no precise “foundation date”.' },
    { d: 'c. 616 – 509 BC (tradition)', t: 'Etruscan kings', x: 'According to Livy, the last three kings (Tarquinius Priscus, Servius Tullius and Tarquin the Proud) are linked to the Etruscan world (the origin of Servius Tullius is debated) and turned Rome into a city with walls, temples and drains (the *Cloaca Maxima*). The details are partly legendary.' },
    { d: '509 BC', t: 'Start of the Republic', x: 'Expulsion of the last king. In his place, two **consuls** elected for one year. The date is traditional; the real process may have been more gradual.' },
    { d: 'c. 494 – 287 BC', t: 'Conflict of the Orders', x: 'The plebeians’ struggle against the patricians for political rights. It created the tribunes of the plebs and opened the consulship to plebeians (367 BC onwards).' },
    { d: 'c. 451 – 450 BC', t: 'Twelve Tables', x: 'Rome’s first written code, displayed in the Forum. It survives only in quotations by later authors.' },
    { d: '343 – 275 BC', t: 'Samnite Wars and war with Pyrrhus', x: 'Three wars against the Samnites of south-central Italy gave Rome the centre of the peninsula and a system of colonies and roads (Via Appia, 312 BC). In 280–275 BC Pyrrhus, king of Epirus, won costly battles (the “Pyrrhic victories”) but was defeated; by 264 BC Rome dominated the whole Italian peninsula.' },
    { d: '264 – 241 BC', t: 'First Punic War', x: 'Against Carthage for Sicily. Rome built a large fleet and won; Sicily became the first province.' },
    { d: '218 – 201 BC', t: 'Second Punic War', x: 'Hannibal crossed the Alps and won at Cannae (216 BC). Scipio Africanus took the war to Africa and defeated him at Zama (202 BC). Rome took over the Carthaginian possessions in Hispania.' },
    { d: '146 BC', t: 'Destruction of Carthage and Corinth', x: 'At the end of the Third Punic War Carthage was razed; in the same year Corinth was destroyed and Greece passed under Roman control.' },
    { d: '133 – 121 BC', t: 'The Gracchi', x: 'Tiberius and Gaius Gracchus tried agrarian and social reforms and were killed in riots. Open political violence began.' },
    { d: '88 – 79 BC', t: 'Marius, Sulla and the civil wars', x: 'The first generals to march on Rome with their armies. Sulla was dictator (82–79 BC).' },
    { d: '73 – 71 BC', t: 'Spartacus’ revolt', x: 'The Republic’s greatest slave revolt; it ended with defeat and the crucifixion of thousands of prisoners along the Via Appia.' },
    { d: '58 – 50 BC', t: 'Conquest of Gaul', x: 'Caesar conquered Gaul (modern France, Belgium and neighbouring areas) and gained an army loyal to himself.' },
    { d: '49 – 44 BC', t: 'Caesar, dictator', x: 'He crossed the Rubicon in 49, defeated Pompey at Pharsalus (48) and was named dictator. He was assassinated on the Ides of March (15 March) 44 BC.' },
    { d: '31 BC', t: 'Battle of Actium', x: 'Octavian defeated Mark Antony and Cleopatra VII. In 30 BC Egypt was annexed.' },
    { d: '27 BC', t: 'Augustus and the Principate', x: 'The Senate gave Octavian the name **Augustus**. He pretended to restore the Republic but in practice gathered all power. This is the conventional start of the Empire.' },
    { d: 'AD 9', t: 'Disaster of Teutoburg Forest', x: 'Three legions were wiped out by Arminius in Germania. The Rhine became the frontier.' },
    { d: 'AD 64', t: 'Fire of Rome', x: 'It destroyed a large part of the city under Nero. Its causes and Nero’s behaviour are debated; Nero blamed the Christians.' },
    { d: 'AD 69 – 79', t: 'Year of the four emperors and the Flavian dynasty', x: 'Civil war (Galba, Otho, Vitellius, Vespasian); Vespasian’s victory began the Flavian dynasty. The Colosseum was inaugurated in 80, under Titus.' },
    { d: 'AD 98 – 117', t: 'Trajan and the territorial peak', x: 'Conquest of Dacia (101–106) and, in 114–117, of parts of Mesopotamia. In 117 the Empire reached its greatest extent.' },
    { d: 'AD 161 – 180', t: 'Marcus Aurelius', x: 'The last of the “five good emperors”. His reign saw wars on the Danube and the Antonine Plague (from 165).' },
    { d: 'AD 212', t: 'Edict of Caracalla', x: 'Roman citizenship granted to most free inhabitants of the Empire.' },
    { d: 'AD 235 – 284', t: 'Third-century crisis', x: 'Half a century of civil wars, invasions, inflation and dozens of short-lived emperors. Valerian was captured by the Persians in 260.' },
    { d: 'AD 284 – 305', t: 'Diocletian and the Tetrarchy', x: 'Administrative, economic and military reforms; power was shared among four rulers.' },
    { d: 'AD 312 – 337', t: 'Constantine', x: 'Victor at the Milvian Bridge (312), he tolerated Christianity (Edict of Milan, 313) and founded Constantinople (330).' },
    { d: 'AD 378 – 395', t: 'Adrianople and Theodosius', x: 'The Goths defeated and killed Emperor Valens in 378. Theodosius I made Nicene Christianity the official religion (380) and, dying in 395, left the Empire divided between his sons.' },
    { d: 'AD 410', t: 'Sack of Rome', x: 'Alaric’s Goths took and sacked Rome for three days, an enormous psychological shock.' },
    { d: 'AD 476', t: 'End of the Western Empire', x: 'Odoacer deposed the young Romulus Augustulus and sent the imperial insignia to Constantinople. For the East, the legitimate emperor was Julius Nepos, who died in 480. The “fall” is a convention: the Eastern Empire went on until 1453.' }
  ] }
];

const mapa = [
  'Rome was not a single city but a network of cities, roads and ports around the Mediterranean. This section presents the city of Rome, the main cities of the Empire, the most decisive battlefields and the great routes. For detail on cities and monuments, see the page “Cities, monuments and engineering”.',
  { img: 'rom-tabula-peutingeriana', leg: 'Rome detail in the Tabula Peutingeriana: facsimile from Konrad Miller’s 1887–1888 edition, based on the medieval copy of the Roman road map.' },
  { tabela: { cab: ['City', 'Roman name', 'Province / region', 'Place today'], linhas: [
    ['Rome', 'Roma', 'Italy (Latium)', 'Rome, Italy'],
    ['Ostia', 'Ostia', 'Italy', 'Ostia Antica, near Rome'],
    ['Pompeii', 'Pompeii', 'Italy (Campania)', 'Near Naples'],
    ['Ravenna', 'Ravenna', 'Italy', 'Ravenna, Italy'],
    ['Milan', 'Mediolanum', 'Italy (formerly Cisalpine Gaul)', 'Milan, Italy'],
    ['Carthage', 'Carthago', 'Africa', 'Tunis, Tunisia'],
    ['Alexandria', 'Alexandria', 'Egypt', 'Alexandria, Egypt'],
    ['Antioch', 'Antiochia', 'Syria', 'Antakya, Türkiye'],
    ['Constantinople', 'Constantinopolis (formerly Byzantium)', 'Thrace', 'Istanbul, Türkiye'],
    ['Athens', 'Athenae', 'Achaea (Greece)', 'Athens, Greece'],
    ['Lyon', 'Lugdunum', 'Gaul', 'Lyon, France'],
    ['London', 'Londinium', 'Britain', 'London, United Kingdom'],
    ['Trier', 'Augusta Treverorum', 'Gallia Belgica', 'Trier, Germany'],
    ['Mérida', 'Augusta Emerita', 'Lusitania', 'Mérida, Spain'],
    ['Tarragona', 'Tarraco', 'Hispania Tarraconensis', 'Tarragona, Spain'],
    ['Lisbon', 'Olisipo (Felicitas Iulia)', 'Lusitania', 'Lisbon, Portugal'],
    ['Braga', 'Bracara Augusta', 'Hispania Tarraconensis (Gallaecia)', 'Braga, Portugal']
  ] } },
  { h: 'The city of Rome' },
  'Early Rome spread over the famous **seven hills** (Palatine, Capitoline, Aventine, Quirinal, Viminal, Esquiline and Caelian), on the left bank of the Tiber. In the valley between them, the **Roman Forum** was the political and religious centre; beside it, the **Capitoline** was the site of the great temple of Jupiter. In the time of Augustus and the following emperors the city was rebuilt in marble, with new forums, baths, theatres, the **Colosseum**, the **Pantheon** and the **Circus Maximus**. It may have reached **a million inhabitants** (estimates range from half a million to over a million), the largest city of the western world for a very long time afterwards.',
  { img: 'rom-forum-romano', leg: 'Roman Forum viewed from the Capitoline Hill.' },
  { img: 'rom-cena-roma-imperial', leg: 'AI-generated illustration. Artistic reconstruction of imperial Rome, c. AD 315, inspired by the Plastico di Roma.' },
  { h: 'Italy: Ostia, Pompeii, Ravenna' },
  '**Ostia**, Rome’s port at the mouth of the Tiber, had warehouses, baths and apartment blocks (*insulae*) that are still well preserved. **Pompeii** and **Herculaneum**, buried by the eruption of Vesuvius in AD 79, preserved houses, murals and everyday objects. **Ravenna** was capital of the Western Empire from 402 and then of Odoacer and the Ostrogoths; it keeps remarkable Christian mosaics.',
  { img: 'rom-ravena-mosaico', leg: 'Mosaic of Justinian and his court, San Vitale, Ravenna.' },
  { img: 'rom-pompeia', leg: 'Forum of Pompeii with Mount Vesuvius.' },
  { h: 'The East: Alexandria, Antioch, Constantinople' },
  '**Alexandria**, founded by Alexander the Great, was one of the Empire’s largest cities, a great port and a centre of learning. **Antioch**, in Syria, was a provincial capital and the base for campaigns against the Persians. **Constantinople**, the “new Rome”, was founded by Constantine in AD 324–330 on the site of ancient Byzantium; its walls (built under Theodosius II in the early 5th century) protected the city until 1453.',
  { img: 'rom-muralhas-teodosianas', leg: 'Theodosian walls of Constantinople, present-day Istanbul.' },
  { h: 'The western provinces' },
  '**Gaul** (modern France) was conquered by Caesar and became one of the most Romanised regions, with cities such as Lyon and Arles. **Britain**, conquered from AD 43 under Claudius, had **Londinium** as its main city; to the north, Hadrian’s Wall (begun in AD 122) marked the frontier. **Germania** was divided: the banks of the Rhine were provinces, the other side stayed outside the Empire.',
  { img: 'rom-muralha-adriano', leg: 'Hadrian’s Wall, Northumberland, England.' },
  { h: 'Hispania and Portugal' },
  'The Romans reached the Iberian Peninsula in **218 BC**, during the Second Punic War, and the conquest was only completed in **19 BC**, under Augustus, after hard fighting against the Lusitanians (the chief **Viriathus**, assassinated c. 139 BC) and against the Cantabrians and Asturians. In Augustus’ time the province of **Lusitania** was formed, with its capital at **Augusta Emerita** (Mérida, founded in 25 BC); it covered, in large part, present-day Portugal south of the Douro, Spanish Extremadura and part of Salamanca. Northern Portugal belonged to **Tarraconensis**, with the city of **Bracara Augusta** (Braga) as a centre. Cities in present-day Portugal include **Olisipo** (Lisbon), **Pax Iulia** (Beja), **Ebora** (Évora), **Aeminium** (Coimbra), **Conimbriga** and **Scallabis** (Santarém).',
  { img: 'rom-conimbriga', leg: 'Mosaic in a Roman house at Conímbriga, Portugal.' },
  { img: 'rom-templo-evora', leg: 'Roman Temple of Évora, Portugal.' },
  { img: 'rom-merida-teatro', leg: 'Roman theatre of Mérida, Spain.' },
  { h: 'Roads, routes and sea' },
  'The Roman road network, largely paved, had, according to modern estimates, more than **400,000 km** of roads, of which about **80,000 km** were stone-paved, linking Rome to the provinces; the first great road, the **Via Appia**, dates from 312 BC. Along them were stations for changing horses and for overnight stays (mansiones). The **sea** was even more important: grain from Egypt and North Africa, olive oil from Baetica and wine from Italy travelled in cargo ships; a voyage from Ostia to Alexandria took, depending on winds and direction, from about two weeks to over a month (estimates).',
  { img: 'rom-via-appia', leg: 'Ancient Appian Way, south of Rome.' },
  { h: 'Decisive battlefields' },
  { lista: [
    '**Cannae (216 BC)**, Apulia: Hannibal surrounded and destroyed a much larger Roman army; between c. 48,000 (Livy) and 70,000 (Polybius) dead according to the ancient sources; figures to be taken with caution, as some modern historians propose much lower totals.',
    '**Zama (202 BC)**, south-west of Carthage: Scipio defeated Hannibal and ended the Second Punic War.',
    '**Pharsalus (48 BC)**, Greece: Caesar defeated Pompey in the civil war.',
    '**Actium (31 BC)**, Greece: Octavian defeated the fleet of Mark Antony and Cleopatra.',
    '**Teutoburg Forest (AD 9)**, Germania: three legions under Varus were destroyed.',
    '**Milvian Bridge (AD 312)**, near Rome: Constantine defeated Maxentius.',
    '**Adrianople (AD 378)**, Thrace: the Goths defeated the army of Valens.'
  ] }
];

const sociedade = [
  'This is the general portrait of Roman society. Each theme (army, cities, religion, daily life) has its own page where it is developed; here is the essential.',
  { h: 'The political system: from Monarchy to Empire' },
  'Rome had three regimes. Under the **Monarchy** (traditional), the king was military, religious and judicial leader, advised by a Senate of elders and acclaimed by the people. In the **Republic** (509–27 BC) power was shared: two **consuls** elected for one year, other magistrates (praetors, aediles, quaestors, censors), a powerful **Senate** and popular **assemblies**. Under Augustus and his successors, in the **Empire**, power was concentrated in an **emperor** (*princeps*, “first citizen”, in the High Empire; *dominus*, “lord”, later), with the Senate losing real power.',
  { img: 'rom-cena-forum-republica', leg: 'AI-generated illustration. Public assembly in the Roman Forum, c. 200 BC: artistic interpretation of the Republican period.' },
  { tabela: { cab: ['Magistracy', 'Who / how many', 'What it did'], linhas: [
    ['Consul', 'Two, for one year', 'Heads of state and army; convened the Senate and the assemblies'],
    ['Praetor', 'Between 2 and 16, depending on the period', 'Presided over justice; governed provinces'],
    ['Aedile', 'Four', 'Looked after buildings, markets, supply and public games'],
    ['Quaestor', 'Several', 'Managed finances; assisted governors'],
    ['Censor', 'Two, every five years', 'Took the census and supervised morals and the Senate'],
    ['Tribune of the plebs', 'Ten', 'Protected plebeians; had the right of veto'],
    ['Dictator', 'One, in emergencies, for six months', 'Temporary absolute power (Caesar, in the end, made himself “dictator for life”)']
  ] } },
  { h: 'Citizens and non-citizens' },
  'Society was divided into orders and classes. In the early Republic, the **patricians** (noble families) and the **plebeians** (the other citizens) fought a long struggle for political equality. Later, the elite was formed by the **senatorial order** and the **equestrian order** (the “knights”, many of them rich businessmen). Below were ordinary citizens, **freedmen** (freed slaves), foreigners and **slaves**. **Roman citizenship** was a valuable privilege, extended by stages to the Italian allies (after the Social War, 91–88 BC) and, in AD 212, to nearly all free inhabitants of the Empire.',
  { h: 'Slavery' },
  'Slavery was central to the Roman economy. Slaves were prisoners of war, children of slave women, victims of piracy or of the slave trade; they worked in mines, fields, houses and workshops, and as teachers, doctors and administrators. They could be freed and their children became citizens. It is calculated (with great uncertainty) that in Italy between a quarter and a third of the population was enslaved at the peak, and in the Empire as a whole between 10 and 20%. There were three great slave revolts in the Republic; the last, led by **Spartacus**, is the most famous.',
  { h: 'The family and the role of women' },
  'The basic unit of society was the **family** (*familia*), headed by the **pater familias**, with legal authority over children, grandchildren and slaves. Roman women could not vote or hold magistracies, but could own property, inherit and, in the Empire, divorce easily. Women such as Livia (wife of Augustus) or Agrippina held political power behind the scenes. Ancient testimonies were written almost always by men.',
  { h: 'Religion' },
  'Roman religion was **polytheistic** and closely tied to the state: public worship ensured the *pax deorum*, the “peace with the gods”. The Romans adopted Greek and foreign gods, and gave emperors divine honours (the imperial cult). From the late Republic onwards, eastern religions (Isis, Mithras, Cybele) and **Christianity** spread; Christianity was persecuted intermittently until Constantine and made the official religion at the end of the 4th century. The page “Religion, law and daily life” develops this theme.',
  { tabela: { cab: ['Roman god', 'Greek equivalent', 'Domain'], linhas: [
    ['Jupiter', 'Zeus', 'King of the gods, sky and thunder; protector of the state'],
    ['Juno', 'Hera', 'Queen of the gods, marriage and women'],
    ['Minerva', 'Athena', 'Wisdom, arts and strategic war'],
    ['Mars', 'Ares', 'War; mythical father of Romulus and Remus'],
    ['Venus', 'Aphrodite', 'Love and beauty; mother of Aeneas'],
    ['Apollo', 'Apollo', 'Prophecy, music and healing'],
    ['Vesta', 'Hestia', 'Hearth; the vestals kept the sacred fire'],
    ['Neptune', 'Poseidon', 'The sea'],
    ['Ceres', 'Demeter', 'Cereals and agriculture']
  ] } },
  { h: 'Law' },
  'Law is perhaps Rome’s greatest legacy. It began with the **Twelve Tables** (c. 450 BC) and developed through the work of the praetors and of the **jurists** (Gaius, Papinian, Ulpian). In the 6th century the eastern emperor **Justinian** had the *Corpus Iuris Civilis* compiled; rediscovered in the Middle Ages, it inspired the civil law of much of the world. Principles such as the presumption of innocence, contract, property and the distinction between public and private law are of Roman origin.',
  { h: 'Economy' },
  'The economy was above all **agricultural**: cereals, vines and olives, with large estates (*latifundia*) worked by slaves and tenants, alongside small peasants. Maritime trade and roads linked the provinces; there were mines (silver and copper in Hispania, gold at Las Médulas), workshops for pottery, glass, textiles and fish sauce (*garum*). Rome imported grain from Egypt and Africa and distributed it, in part free, to poor citizens (*annona*).',
  { h: 'Money and taxes' },
  'The standard coin was the silver **denarius**, created c. 211 BC; emperors debased it little by little, which fed the inflation of the 3rd century. Constantine created the gold **solidus** (309), which stayed stable for centuries. Taxes included levies on land and people (in the provinces), customs duties and, from Augustus, taxes on inheritances and sales. Taxes paid above all for the army.',
  { img: 'rom-denario-cesar', leg: 'Silver denarius of Julius Caesar, 44 BC.' },
  { h: 'Language and writing' },
  '**Latin** was the language of Rome and, with conquest, spread across the West; in the East Greek continued to be spoken. Writing used the Latin alphabet, derived from Etruscan and Greek, on papyrus, wax tablets and inscriptions in stone and bronze. “Literary” Latin differs from the spoken Latin of the people (*Vulgar Latin*), from which the Romance languages descend.',
  { h: 'Literature and thought' },
  'Roman literature, much influenced by Greek, had its golden age in Augustus’ time: Virgil (*Aeneid*), Horace and Ovid. Prose has Cicero, Caesar, Livy, Tacitus and Seneca, among many others. In philosophy the Romans preferred Stoicism (Seneca, Epictetus, Marcus Aurelius) and Epicureanism (Lucretius).',
  { img: 'rom-virgilio-mosaico', leg: 'Mosaic of Virgil between Clio and Melpomene, Bardo Museum, Tunis.' },
  { h: 'The Roman house' },
  'The rich lived in a **domus**, a one-storey house with an inner courtyard (*atrium*) and garden; ordinary people lived in **insulae**, multi-storey apartment blocks, often overcrowded and dangerous (fires, collapses). Rich houses had wall paintings and mosaics; few private houses had running water, even among the rich.',
  { img: 'rom-cena-domus-atrium', leg: 'AI-generated illustration. Atrium of a wealthy Pompeian domus, c. AD 50: artistic reconstruction.' },
  { h: 'Food' },
  'The base was bread and cereal porridge, olive oil, wine (almost always diluted with water), vegetables, cheese, fish and, in smaller quantities, meat. The poor man’s food was simple; the banquets of the rich, with several courses and exotic dishes, became famous. The fermented fish sauce **garum** was everywhere. Tomatoes and potatoes did not yet exist in Europe.',
  { img: 'rom-cena-taberna', leg: 'AI-generated illustration. Pompeian thermopolium, c. AD 70, with counter and dolia: artistic reconstruction.' },
  { h: 'Clothing' },
  'The typical male garment was the **tunic**; the citizen wore, in public and on formal occasions, the **toga**, of wool, heavy and uncomfortable, a mark of status. Women wore a long tunic and a **stola**, with the *palla* over it. Colours and stripes (the senators’ purple band) showed social rank.',
  { h: 'Education' },
  'Education was private and paid for. Boys (and some girls) first learned to read, write and count with a *ludi magister*; then they studied grammar and literature; sons of rich families learned rhetoric, essential for public life and the courts. Many teachers were Greek slaves or freedmen.',
  { h: 'Entertainment: circus, theatre, amphitheatre' },
  'The Romans were passionate about public spectacles. In the **Circus Maximus** there were chariot races (perhaps over 150,000 spectators, by estimate); in the **Colosseum** (inaugurated in AD 80), gladiator fights and animal hunts (perhaps 50,000 to 80,000 seats, by estimate); in theatres, comedies (Plautus, Terence) and tragedies. Gladiators were slaves, convicts or volunteers; some became famous. It is not true that every fight ended in death.',
  { img: 'rom-coliseu', leg: 'Colosseum, Rome.' },
  { img: 'rom-mosaico-gladiadores', leg: 'Scene from the gladiator mosaic, Galleria Borghese, Rome.' },
  { img: 'rom-cena-circo-maximo', leg: 'AI-generated illustration. Quadriga race in the Circus Maximus, c. AD 100: artistic interpretation.' },
  { h: 'Baths and hygiene' },
  'Public **baths** were places for hygiene, socialising and sport, with hot and cold pools, hypocaust heating (hot air under the floor), libraries and gardens. The Baths of Caracalla in Rome could hold thousands of people at once. Entry was cheap or free.',
  { img: 'rom-cena-termas', leg: 'AI-generated illustration. Frigidarium inspired by the Baths of Caracalla, c. AD 220: artistic reconstruction.' },
  { h: 'Medicine' },
  'Roman medicine used herbs and basic surgery, under strong Greek influence. The most famous doctor was the Greek **Galen** (129 – c. AD 216; the date of his death is debated), physician to Marcus Aurelius, whose works dominated medicine for over a thousand years. There were military hospitals (*valetudinaria*) in legionary forts. Childhood deaths were frequent; life expectancy at birth was, by estimate, about 20 to 30 years, because of infant mortality (those who reached adulthood could live much longer).',
  { h: 'Science and technology' },
  'The Romans were engineers more than theoretical scientists. They invented or perfected **concrete** (with volcanic ash), the **arch** and the **vault**, the network of **aqueducts** (11 great aqueducts served Rome), sewers, layered roads and hydraulic mining. The Pantheon still has the largest unreinforced concrete dome in the world (about 43 m in diameter). The Julian calendar (45 BC) is the basis of the one we use today.',
  { img: 'rom-panteao', leg: 'Interior of the Pantheon, Rome.' },
  { img: 'rom-aqueduto-segovia', leg: 'Aqueduct of Segovia, Spain.' },
  { img: 'rom-pont-du-gard', leg: 'Pont du Gard, near Nîmes, France.' },
  { h: 'War and the army' },
  'The army was the engine of Roman power. It was made up of **legions** of heavy infantry (c. 5,000 men each), supported by auxiliary troops and, later, by the fleet. Originally a militia of citizen-landowners, with the reform attributed to Marius (107 BC) it became a professional army of soldiers who served about 20 to 25 years and received land or money at the end. Discipline, engineering (building camps and roads) and logistics explain its successes. The page “Army and warfare” treats the theme in detail.',
  { img: 'rom-cena-legiao-batalha', leg: 'AI-generated illustration. Roman legionaries in battle formation, c. AD 100: artistic interpretation.' },
  { img: 'rom-trajano-coluna', leg: 'Reliefs on Trajan’s Column, Rome.' },
  { h: 'The triumph' },
  'The **triumph** was the great ceremony in which a victorious general paraded through the city with his soldiers, prisoners and spoils, up to the temple of Jupiter. It was said that a slave, standing behind him, reminded him that he was mortal, but this detail comes from late authors and may be embellishment.',
  { img: 'rom-cena-triunfo', leg: 'AI-generated illustration. Roman triumphal procession, c. AD 100: artistic interpretation.' },
  { h: 'Christianity in the Empire' },
  'Christianity was born in the province of Judaea in the 1st century and spread through Roman cities. It was persecuted irregularly (Nero, Decius, and Diocletian’s “Great Persecution”, 303–311). Constantine ended the persecutions with the **Edict of Milan** (313) and favoured the Church; in **380**, the Edict of Thessalonica (Theodosius I) declared Nicene Christianity the religion of the Empire.',
  { img: 'rom-constantino-colosso', leg: 'Head of the Colossus of Constantine, Capitoline Museums, Rome.' }
];

const personalidades = [
  'Thirteen figures who marked Rome, chosen from many: generals, statesmen, emperors and a hero of Iberian resistance. For full biographies and the table of emperors, see the page “Emperors and great figures”. Ancient birth dates are often approximate.',
  { h: 'Scipio Africanus (c. 236 – 183 BC)' },
  'Publius Cornelius Scipio conquered Hispania from the Carthaginians (Cartagena, 209 BC) and defeated **Hannibal** at Zama (202 BC), ending the Second Punic War; hence the nickname “Africanus”. He was the target of political accusations late in life and retired to Liternum.',
  { h: 'Cato the Elder (234 – 149 BC)' },
  'A conservative politician and writer, consul in 195 BC and censor in 184 BC. Author of *De Agri Cultura* (the oldest surviving Latin prose treatise). According to tradition he ended his speeches by calling for the destruction of Carthage; the exact phrase (“Carthago delenda est”) is fixed by later authors.',
  { h: 'Viriathus (d. c. 139 BC)' },
  'A Lusitanian chief, presented by ancient sources as a former shepherd who became a guerrilla leader. He defeated several Roman armies between c. 147 and 139 BC. He was assassinated by three companions bribed by the consul Caepio, according to Appian. Almost everything we know comes from Roman authors; his exact origin and role are debated.',
  { h: 'Cicero (106 – 43 BC)' },
  'Lawyer, orator and politician, consul in 63 BC, when he foiled Catiline’s conspiracy. He left speeches, letters and philosophical works that fixed classical Latin. He defended the Republic against Mark Antony and was killed on the triumvirs’ orders in 43 BC.',
  { img: 'rom-cicero-busto', leg: 'Bust of Cicero, Capitoline Museums, Rome.' },
  { h: 'Julius Caesar (100 – 44 BC)' },
  'Politician and general, conqueror of Gaul (58–50 BC) and author of the *Commentaries* on his campaigns. He crossed the Rubicon in 49 BC (“the die is cast”; the exact phrase varies among the sources), defeated Pompey and became dictator. He was assassinated on the Ides of March 44 BC by senators who accused him of wanting to be king. The phrase “Veni, vidi, vici”, quoted by Suetonius and Plutarch, refers to his victory at Zela in 47 BC.',
  { img: 'rom-cesar-busto', leg: 'Portrait of Julius Caesar known as the Chiaramonti Caesar, Vatican Museums.' },
  { img: 'rom-cena-senado-ides', leg: 'AI-generated illustration. Assassination of Julius Caesar in the Curia of Pompey, Ides of March, 44 BC: artistic interpretation.' },
  { h: 'Augustus (63 BC – AD 14)' },
  'Gaius Octavius, Caesar’s great-nephew and heir, defeated Mark Antony at Actium (31 BC) and in 27 BC received the name Augustus. He created the Principate, reformed the army, finances and administration, and gave Rome decades of internal peace, the *Pax Romana*. He died at Nola on 19 August AD 14. He ruled for about 40 years.',
  { img: 'rom-augusto-prima-porta', leg: 'Augustus of Prima Porta, Vatican Museums.' },
  { h: 'Nero (AD 37 – 68)' },
  'Emperor from 54 to 68, the last of the Julio-Claudian dynasty. The first years were of relative prudence, with Seneca as adviser; later he had his mother, Agrippina, and his first wife, Octavia, killed. The great fire of AD 64 and the persecution of Christians marked the reign. The ancient sources (Tacitus, Suetonius, Cassius Dio) are hostile; the story of the lyre during the fire has no proof. He committed suicide in 68, after revolts in the provinces.',
  { h: 'Trajan (AD 53 – 117)' },
  'Born in Italica (Hispania), he was the first provincial emperor (reigned 98 to 117). He conquered Dacia (101–106) and parts of Mesopotamia, and took the Empire to its greatest extent. He undertook great public works (Trajan’s Forum, Trajan’s Column, the hexagonal harbour basin at Portus, beside Ostia). He died at Selinus, in Cilicia, on the way back from the campaign.',
  { h: 'Hadrian (AD 76 – 138)' },
  'Also a native of Italica or of Rome (debated), emperor from 117 to 138. He gave up the Mesopotamian conquests and consolidated the frontiers, with **Hadrian’s Wall** in Britain. He toured the provinces, loved Greek culture and rebuilt the Pantheon. He put down the Jewish revolt of Bar Kokhba (132–135).',
  { h: 'Marcus Aurelius (AD 121 – 180)' },
  'Emperor from 161 to 180 (in the early years with Lucius Verus), he wrote in Greek the *Meditations*, reflections of Stoic inspiration. He spent much of his reign on campaign on the Danube. The equestrian bronze statue on the Capitoline is one of the few to survive from Antiquity. He died on 17 March 180, at Vindobona (Vienna) or near Sirmium; the sources differ and the place is debated.',
  { img: 'rom-marco-aurelio-equestre', leg: 'Equestrian statue of Marcus Aurelius, Capitoline Museums, Rome.' },
  { h: 'Diocletian (c. AD 244 – 311)' },
  'A soldier of humble origin from Dalmatia, he was emperor from 284 to 305. He ended the Third-century Crisis with reforms: he divided the Empire into more provinces, separated civil from military power and created the **Tetrarchy** (four rulers). He launched the last and greatest persecution of Christians (303). He abdicated voluntarily in 305 and retired to his palace at Split.',
  { h: 'Constantine I (c. AD 272 – 337)' },
  'Proclaimed emperor at York in 306, he was sole master of the Empire from 324. He defeated Maxentius at the Milvian Bridge (312), tolerated Christianity (Edict of Milan, 313) and convened the Council of Nicaea (325). He founded Constantinople (inaugurated in 330) and created the gold solidus. Historians debate the sincerity and timing of his conversion; he was baptised only on his deathbed.',
  { img: 'rom-arco-constantino', leg: 'Arch of Constantine, Rome.' },
  { h: 'Theodosius I (AD 347 – 395)' },
  'Emperor from 379 to 395, of Hispanic origin. He made Nicene Christianity the official religion (380), banned public pagan worship (391–392) and was the last to rule the whole Empire. At his death West and East passed to his sons Honorius and Arcadius, and never again had a single lasting ruler.'
];

const legado = [
  { h: 'What Rome left us' },
  { lista: [
    '**Law:** European and Latin American civil law descends from Roman law, via Justinian and the medieval universities.',
    '**Languages:** Portuguese and the other Romance languages come from spoken Latin; Latin was Europe’s scientific, legal and religious language until the 18th century.',
    '**Alphabet and calendar:** the Latin alphabet is used today by about 40% of humanity; the months of the calendar and the division into 12 months come from the Julian calendar.',
    '**Cities:** many European cities (London, Paris, Cologne, Lisbon, Braga) have Roman origins.',
    '**Engineering:** roads, bridges, aqueducts and the architecture of concrete, arch and vault.',
    '**Political ideas:** republic, senate, citizenship; models for the American and French revolutions.',
    '**Religion:** Christianity grew within the Empire; the Church of Rome and its organisation inherited the Roman administrative structure.'
  ] },
  { h: 'Art and architecture' },
  'Roman art was eclectic: it inherited from the Greeks, Etruscans and the East, but invented realistic portraiture (the masks of ancestors), the historical relief (Ara Pacis, Trajan’s Column) and domestic-scale mural painting and mosaic. Its architecture created the basilica, the triumphal arch, the amphitheatre and the baths. The idea of “classical” in Europe rests largely on Roman models (rediscovered in the Renaissance).',
  { img: 'rom-ara-pacis', leg: 'Ara Pacis Augustae, Rome.' },
  { h: 'Rediscovery' },
  'Rome was never forgotten; it was reinterpreted. In the **Renaissance**, humanists rediscovered Latin texts and ancient architecture. The excavations of **Herculaneum** (1738) and **Pompeii** (1748) inaugurated modern archaeology and gave rise to neoclassicism. The **Grand Tour** brought European nobles to Rome; Napoleon and Mussolini used the image of Rome for propaganda; today archaeology, DNA analysis and 3D technology keep revealing new data.',
  { h: 'Where to visit' },
  { lista: [
    '**Rome:** Roman Forum, Palatine, Colosseum, Pantheon, Baths of Caracalla, Via Appia, Capitoline and Vatican Museums.',
    '**Naples and surroundings:** Pompeii, Herculaneum, Oplontis, National Archaeological Museum.',
    '**Portugal:** Conimbriga (Condeixa), the Roman ruins of Tróia (Grândola), National Archaeology Museum (Lisbon), Roman Temple of Évora, ruins of Miróbriga (Santiago do Cacém), Milreu Villa (Faro), D. Diogo de Sousa Museum (Braga), Rabaçal Villa Museum (Penela), Pax Iulia (Beja).',
    '**Spain:** Mérida, Segovia, Tarragona, Italica.',
    '**France:** Pont du Gard, Arles, Orange, Nîmes.',
    '**United Kingdom:** Hadrian’s Wall, Bath, London.',
    '**North Africa and Middle East:** Leptis Magna (Libya), Timgad (Algeria), El Djem (Tunisia), Jerash (Jordan), Palmyra (Syria).'
  ] },
  { img: 'rom-tabula-peutingeriana', leg: 'Rome detail in the Tabula Peutingeriana: facsimile from Konrad Miller’s 1887–1888 edition, based on the medieval copy of the Roman road map.' },
  { h: 'A world that did not end in 476' },
  'In AD 476 imperial government in the West ended, but life went on: the Germanic kingdoms that succeeded it (Visigoths, Franks, Ostrogoths) kept the law, the language, the cities and the Church. In the Iberian Peninsula, the Visigothic kingdom lasted until 711. The **Eastern** Empire, with Constantinople as capital, survived until 1453; its history is treated on the Byzantine Empire page in this project.',
  { cit: 'There was no single “fall of Rome”: there was a slow transformation, with many continuities.', fonte: 'A synthesis of modern scholarship on Late Antiquity (not a quotation from a single author).' },
  { img: 'rom-cena-saque-410', leg: 'AI-generated illustration. Alaric’s Visigoths entering Rome through the Porta Salaria, AD 410: artistic interpretation.' },
  { h: 'Further reading' },
  { lista: [
    'Mary Beard, *SPQR: A History of Ancient Rome* (2015).',
    'Adrian Goldsworthy, *In the Name of Rome* and *Pax Romana*.',
    'Peter Heather, *The Fall of the Roman Empire* (2005).',
    'Livy (*Ab Urbe Condita*), Tacitus (*Annals*), Suetonius (*Lives of the Twelve Caesars*): the ancient sources.'
  ] },
  { h: 'Why did Rome last so long?' },
  'Historians propose several reasons: the ability to **integrate the conquered** (extended citizenship, the Italian allies), the strength of the **army**, the **flexibility** of its institutions, the network of **roads and cities**, and the fact that for centuries there were no enemies of equal strength. Its fall in the West also has many explanations (economic crisis, civil wars, external pressure, plague, climate change); there is no consensus. The simple idea of “moral decadence” should be avoided.'
];

const quiz = [
  { p: 'According to tradition, in what year was Rome founded?', op: ['753 BC', '509 BC', '27 BC', 'AD 476'], certa: 0, exp: 'The traditional date of 753 BC was fixed by Varro; archaeology shows a slower process.' },
  { p: 'In what year did the Roman Republic begin?', op: ['753 BC', '509 BC', '264 BC', '146 BC'], certa: 1, exp: 'In 509 BC, according to tradition, with the expulsion of the last king, Tarquin the Proud.' },
  { p: 'Who defeated Hannibal at the battle of Zama (202 BC)?', op: ['Julius Caesar', 'Scipio Africanus', 'Pompey', 'Marius'], certa: 1, exp: 'Scipio Africanus ended the Second Punic War.' },
  { p: 'Which slave revolt threatened the Republic between 73 and 71 BC?', op: ['Viriathus’ revolt', 'Spartacus’ revolt', 'Boudica’s revolt', 'Arminius’ revolt'], certa: 1, exp: 'Spartacus, a Thracian gladiator, led Rome’s greatest slave revolt.' },
  { p: 'Which battle, in 31 BC, secured Octavian’s power?', op: ['Pharsalus', 'Cannae', 'Actium', 'Philippi'], certa: 2, exp: 'At Actium, Octavian defeated Mark Antony and Cleopatra.' },
  { p: 'What name did Octavian receive in 27 BC?', op: ['Pontifex', 'Augustus', 'Imperator Perpetuus', 'Dominus'], certa: 1, exp: 'Augustus, a title given by the Senate; 27 BC is the conventional start of the Empire.' },
  { p: 'In what year did the Empire reach its greatest extent?', op: ['c. 27 BC', 'AD 117', 'AD 212', 'AD 395'], certa: 1, exp: 'Under Trajan, in AD 117, after the conquests in Dacia and Mesopotamia.' },
  { p: 'Which emperor had a wall built in Britain?', op: ['Trajan', 'Claudius', 'Hadrian', 'Constantine'], certa: 2, exp: 'Hadrian, from AD 122.' },
  { p: 'When was the Colosseum inaugurated?', op: ['27 BC', 'AD 80', 'AD 117', 'AD 312'], certa: 1, exp: 'In AD 80, under Emperor Titus, of the Flavian dynasty.' },
  { p: 'What was the name of the Roman province that covered much of present-day Portugal?', op: ['Baetica', 'Lusitania', 'Gaul', 'Achaea'], certa: 1, exp: 'Lusitania, with its capital at Augusta Emerita (Mérida).' },
  { p: 'Which emperor created the Tetrarchy?', op: ['Augustus', 'Trajan', 'Diocletian', 'Constantine'], certa: 2, exp: 'Diocletian, in AD 293, to share government among four rulers.' },
  { p: 'What did the Edict of Milan (313) do?', op: ['Made Christianity the only religion', 'Granted religious tolerance to Christians', 'Divided the Empire', 'Founded Constantinople'], certa: 1, exp: 'Constantine and Licinius guaranteed freedom of worship; only in 380 did Nicene Christianity become the official religion.' },
  { p: 'Who deposed Romulus Augustulus in AD 476?', op: ['Alaric', 'Attila', 'Odoacer', 'Theodoric'], certa: 2, exp: 'Odoacer, a Germanic military leader; the date 476 is a convention of historians.' },
  { p: 'What is the truth about Nero and the fire of Rome in AD 64?', op: ['He played the lyre while the city burned, according to all sources', 'The fire is real, but the lyre story has no proof', 'The fire never happened', 'Nero was away and blamed the Gauls'], certa: 1, exp: 'Tacitus mentions only the rumour that Nero sang of the ruin of Troy on a private stage; the image of him playing the lyre as Rome burned is later and unproven.' },
  { p: 'Which modern language does NOT derive from Latin?', op: ['Portuguese', 'Romanian', 'French', 'German'], certa: 3, exp: 'German is a Germanic language (with many Latin loanwords).' }
];

export default { visao, linha, mapa, sociedade, personalidades, legado, quiz };
