// CIDADES, MURALHAS E ROTA DA SEDA (China antiga) — página temática em português. A versão inglesa está em dados-en.js (mesma estrutura, mesmos ids de imagem).
// Datas aproximadas; números de população, de operários e de comprimentos são estimativas e vêm assinalados como tal. Dinastias na cronologia habitual (ver china/dados.js).
// Imagens: cada {img:'id'} procura o ficheiro  china/cidades-rota-seda/img/id.jpg  (ver IMAGENS_CHINA_CIDADES_ROTA_SEDA.md).
import EN from './dados-en.js';
import CRED from './creditos.js';
import { GRUPO } from '../grupo.js';

const visao = [
  { caixa: 'Em resumo', texto: [
    'Esta página conta a China pelas suas **cidades**, pelas suas **muralhas**, pelos seus **canais** e pelos **caminhos** que a ligaram ao resto do mundo. Começa em **Erlitou** e **Anyang** (c. 1800 – 1046 a.C.), passa pelas capitais dos **Han** e dos **Tang**, pela animada **Kaifeng** dos Song, por **Hangzhou**, pela **Dadu** de Kublai Khan e termina na **Pequim** dos Ming, por volta de **1500**. No caminho encontramos a **Grande Muralha** (que não é uma muralha só), o **Grande Canal**, a **Rota da Seda** e o comércio marítimo de **Quanzhou** e de **Guangzhou**.',
    'O fio condutor é simples: a China foi, durante três mil anos, um mundo de **aldeias e de campos**, mas as suas **cidades** eram planeadas, muradas e governadas como uma extensão da ordem do universo, e ligavam-se por **estradas, canais e rotas de comércio** que levavam seda, papel, chá e porcelana para o Ocidente, e traziam cavalos, vidro, religiões e ideias. Os números de população, de operários e de quilómetros são quase sempre **estimativas**; assinalamo-lo quando importa.'
  ] },
  { img: 'ccs-mapa-rota-seda', leg: 'Mapa da Rota da Seda e das rotas marítimas, de Chang’an ao Mediterrâneo' },
  { h: 'Cidade, muralha e mercado' },
  'A palavra chinesa para «cidade», **chengshi** (城市), junta dois caracteres: **cheng**, que significa «muralha» e também «cidade», e **shi**, «mercado». É uma boa definição da cidade chinesa: um espaço **cercado por uma muralha de terra batida** e com um **mercado** vigiado pelo Estado. A maior parte das cidades antigas eram capitais administrativas, sedes de funcionários, de guarnições e de templos, e só depois centros de comércio, embora, a partir dos Song, o comércio ganhasse a rua.',
  { h: 'Onde e quando' },
  'O tema abrange mais de três mil anos. A tabela resume as grandes fases, com os exemplos mais importantes. As datas são aproximadas.',
  { tabela: { cab: ['Fase', 'Datas aproximadas', 'Cidades e obras', 'O que muda'], linhas: [
    ['Primeiras cidades', 'c. 1800 – 1046 a.C.', 'Erlitou, Zhengzhou, Anyang', 'Palácios de terra batida, primeira rede de ruas, bronze e escrita'],
    ['Estados em guerra', '770 – 221 a.C.', 'Linzi, Handan, Xianyang; muralhas dos Estados; Dujiangyan', 'Cidades muradas, muralhas de fronteira, canais e irrigação'],
    ['Qin e Han', '221 a.C. – 220 d.C.', 'Chang’an, Luoyang; muralhas e torres de sinais até Dunhuang', 'Capitais imperiais; início da Rota da Seda; estradas e correio'],
    ['Divisão e Sui', '220 – 618', 'Luoyang (Wei do Norte), Daxing; Grande Canal; Mogao', 'Budismo e grutas; cidade-modelo de Daxing; canal que une o norte e o sul'],
    ['Tang', '618 – 907', 'Chang’an, Luoyang, Guangzhou, Yangzhou', 'Capital cosmopolita; sogdianos; comércio marítimo começa a crescer'],
    ['Song', '960 – 1279', 'Kaifeng, Hangzhou, Quanzhou', 'A cidade abre-se à rua; mercados noturnos; papel-moeda; navegação de longo curso'],
    ['Yuan e Ming inicial', '1271 – c. 1500', 'Dadu, Nanjing, Pequim; Grande Canal reconstruído; Grande Muralha dos Ming', 'Capital no norte; muralhas de tijolo; viagens de Zheng He']
  ] } },
  { img: 'ccs-mapa-chang-an-tang', leg: 'Plano de Chang’an na época Tang (recinto, quadrícula de bairros, dois mercados)' },
  { h: 'Uma cidade desenhada pelo poder' },
  'Ao contrário de muitas cidades europeias, que cresceram de forma orgânica à volta de um mercado ou de uma igreja, as grandes **capitais chinesas** eram muitas vezes **desenhadas de raiz**: um recinto retangular, orientado pelos pontos cardeais, com um eixo norte-sul, o palácio ao centro ou ao norte, e ruas em quadrícula. As regras vinham de textos antigos, como o *Registo dos Artífices* (*Kaogong ji*), e de conceitos de ordem cósmica. Era uma forma de dizer que o governo do homem e a ordem do mundo se correspondiam.',
  { h: 'Cinco coisas que esta página mostra' },
  { lista: [
    '**Planeamento:** como se desenhava uma capital e como as cidades quebraram a quadrícula nos tempos dos Song.',
    '**Muralhas:** a Grande Muralha, que é uma **sucessão de muralhas** construídas por dinastias diferentes, e as muralhas das cidades.',
    '**Água:** o Grande Canal e outros canais que levavam cereais do sul para o norte e que ligavam a China por dentro.',
    '**Caminhos:** a Rota da Seda e as rotas do mar, com os seus oásis, portos e comunidades de estrangeiros.',
    '**Quotidiano:** mercados, casas, comida, roupa, moeda e correio, ou seja, como se vivia nas cidades.'
  ] },
  { img: 'ccs-muralha-badaling', leg: 'Grande Muralha dos Ming em Badaling' },
  { h: 'Porque importam' },
  { lista: [
    '**Urbanismo:** a ideia de capital simétrica e orientada, nascida na China, foi copiada no Japão (Heijō-kyō, a atual Nara, e Heian-kyō, a atual Quioto), na Coreia e no Vietname.',
    '**Engenharia:** canais, pontes, diques e muralhas que ainda hoje se podem visitar e, em alguns casos, ainda funcionam (o Dujiangyan, o Grande Canal).',
    '**Troca de mundos:** a Rota da Seda e o mar fizeram da China parte de uma rede de trocas que ligava o Pacífico ao Mediterrâneo.',
    '**Vida urbana:** a cidade dos Song, com restaurantes, teatros, mercados noturnos e dinheiro de papel, parece estranhamente moderna.'
  ] },
  { img: 'ccs-grande-canal-hangzhou', leg: 'Grande Canal em Hangzhou' },
  { caixa: 'Uma nota de cautela sobre os números', texto: 'Nas fontes chinesas e estrangeiras, os números de habitantes, de operários e de quilómetros são **muitas vezes vagos ou exagerados**. Dizer que Chang’an tinha «um milhão de habitantes» é uma estimativa moderna, baseada em recenseamentos que contavam famílias fiscais, não pessoas; os cinco milhões de operários do Grande Canal sob os Sui são um número registado nos textos antigos que os historiadores leem com cuidado; e os comprimentos da Grande Muralha dependem do que se conta como «muralha». Quando damos um número, é porque a fonte o dá, e diz-se «cerca de» ou «segundo».' },
  { h: 'Hoje' },
  'Os locais desta página estão entre os mais visitados e mais estudados do mundo: a Grande Muralha (Património Mundial desde **1987**), o Palácio da Cidade Proibida (1987), as grutas de Mogao em Dunhuang (1987), o Grande Canal (2014), a rede de sítios da Rota da Seda no corredor Chang’an–Tianshan (2014), Yinxu em Anyang (2006), Quanzhou (2021) e o Eixo Central de Pequim (2024). A arqueologia continua a revelar cidades inteiras, e a China de hoje reivindica o passado da Rota da Seda como inspiração de projetos modernos.',
  { h: 'Atenção aos mitos' },
  { lista: [
    '**A Grande Muralha vista do espaço:** é um mito, anterior à era espacial. A muralha é comprida, mas **estreita**, e não se vê da Lua; da órbita baixa só se distingue, com dificuldade, em condições excecionais.',
    '**«Uma só muralha»:** não existiu uma muralha única, construída pelo Primeiro Imperador. Houve muitas, em épocas diferentes; a que se visita hoje é sobretudo dos **Ming**.',
    '**«A Estrada da Seda»:** era uma **rede** de caminhos e de intermediários, e quase ninguém a percorria de ponta a ponta. A palavra «Rota da Seda» só foi usada em 1877.',
    '**Marco Polo:** o seu relato é rico mas discutido; não é a nossa única fonte sobre a China dos Yuan.'
  ] }
];

const linha = [
  'Esta linha do tempo segue a **evolução das cidades, das muralhas, dos canais e dos caminhos**, desde as primeiras cidades até c. 1500. As datas são aproximadas; as anteriores a 841 a.C. são debatidas.',
  { linha: [
    { d: 'c. 1800 a.C.', t: 'Erlitou: uma rede de ruas e um palácio', x: 'O sítio de **Erlitou**, no rio Luo, tinha cerca de 300 hectares, uma grande plataforma de terra batida com edifícios de madeira, oficinas de bronze e uma **rede de ruas** de 10 a 20 metros de largura, a mais antiga conhecida na China. Se é a capital da lendária dinastia **Xia** ou de uma cultura sem nome, continua em debate.' },
    { d: 'c. 1600 a.C.', t: 'Zhengzhou e as muralhas de terra batida', x: 'A cidade Shang de **Zhengzhou** (c. 1630 – 1400 a.C.) tinha uma muralha de terra batida de cerca de 7 km de perímetro, com perto de 20 m de largura na base e cerca de 8 m de altura. É das primeiras grandes muralhas urbanas conhecidas.' },
    { d: 'c. 1300 – 1046 a.C.', t: 'Anyang (Yin), a última capital Shang', x: 'Em **Yinxu**, perto de Anyang, havia palácios, templos dos antepassados, oficinas de bronze e uma necrópole real. O sítio ocupa cerca de 30 km² e é Património Mundial desde 2006.' },
    { d: 'séc. VII – IV a.C.', t: 'As muralhas dos Estados', x: 'Nos Estados em guerra (Chu, Qi, Wei, Zhao, Yan e Qin), constroem-se **muralhas de fronteira** de terra batida e pedra, ao lado de grandes cidades muradas como **Linzi** (Qi). Os troços mais antigos são difíceis de datar com precisão.' },
    { d: '486 a.C.', t: 'O canal Hangou', x: 'O Estado de Wu manda abrir o canal **Hangou**, que liga o Yangtzé ao rio Huai, o troço mais antigo reconhecido do futuro Grande Canal. A obra serve sobretudo para transportar tropas.' },
    { d: 'c. 256 – 246 a.C.', t: 'Dujiangyan e o canal de Zheng Guo', x: 'Em Sichuan, o governador **Li Bing** (tradição) organiza o **Dujiangyan** para repartir as águas do rio Min, e em Shaanxi abre-se o canal de **Zheng Guo** (246 a.C.). Ambas as obras reforçaram a economia de Qin, o Estado que viria a unificar a China.' },
    { d: '221 – 210 a.C.', t: 'Qin: estradas, canais e muralha', x: 'O Primeiro Imperador manda uniformizar os eixos das carroças, abrir estradas, entre elas a «Estrada Direta» para norte (212 a.C.), e o canal **Lingqu** (214 a.C.), e liga muralhas anteriores no norte, sob o general **Meng Tian**. A sua capital é **Xianyang**.' },
    { d: '202 – 190 a.C.', t: 'Os Han fundam Chang’an', x: 'Liu Bang escolhe o vale do rio Wei. O palácio de **Weiyang** começa em 200 a.C. e as muralhas da cidade, com cerca de 25,7 km, a partir de 194 a.C. A cidade teria perto de 150 000 habitantes em 195 a.C. e cerca de 250 000 no ano 2 d.C. (estimativas a partir dos censos).' },
    { d: 'c. 138 – 100 a.C.', t: 'Zhang Qian e a abertura do Ocidente', x: 'As missões de **Zhang Qian** (138 e 119 a.C.) e as guerras contra os **Xiongnu** levam os Han ao corredor de Hexi. Constroem-se muralhas, torres de sinais e as passagens de **Yumen** e **Yang**, junto a **Dunhuang**. Nasce, na prática, a Rota da Seda.' },
    { d: '25 d.C.', t: 'Luoyang, capital dos Han Orientais', x: 'O imperador Guangwu fixa a corte em **Luoyang**. A cidade tem universidade imperial e, segundo a tradição, em 68 d.C. recebe o primeiro mosteiro budista, o do **Cavalo Branco**.' },
    { d: '97 e 166 d.C.', t: 'Ban Chao, Gan Ying e Roma', x: 'O general **Ban Chao** controla o Tarim e envia o enviado **Gan Ying** (97), que, segundo a leitura mais comum, chega às margens do Golfo Pérsico. Em 166, as fontes chinesas registam uma «embaixada» de **Andun**, rei de **Daqin** (Roma), identificado com Marco Aurélio, que terá chegado por mar; os historiadores suspeitam que fossem comerciantes.' },
    { d: 'c. 366 – 494', t: 'Mogao e Longmen: o budismo na pedra', x: 'A tradição situa em **366** o início das grutas de **Mogao**, em Dunhuang. Em **493 – 494**, os Wei do Norte mudam a capital para Luoyang e começam as grutas de **Longmen**. As rotas levam o budismo e a sua arte pela China.' },
    { d: '582 – 611', t: 'Daxing e o Grande Canal', x: 'O primeiro imperador Sui manda construir, em 582, a cidade de **Daxing**, desenhada pelo arquiteto **Yuwen Kai**. Entre **605** e **611**, o imperador **Yang** manda abrir ou unir canais entre Luoyang, o Yangtzé e a região de Pequim: nasce o **Grande Canal**, à custa de trabalho forçado.' },
    { d: '618 – c. 755', t: 'Chang’an, capital do mundo', x: 'Daxing torna-se a **Chang’an dos Tang**: cerca de 84 km², uma quadrícula de bairros murados, dois mercados e talvez um milhão de pessoas (estimativa). Chegam sogdianos, persas, turcos, japoneses, coreanos e monges indianos.' },
    { d: '714 e c. 826', t: 'O mar começa a contar', x: 'Em Guangzhou é criado, em 714, um gabinete para o comércio marítimo (*shibosi*). O **naufrágio de Belitung** (c. 826), com cerca de 60 000 peças de cerâmica chinesa, mostra um navio árabe a levar produtos Tang para o Golfo.' },
    { d: '751 e 755 – 763', t: 'Talas e An Lushan', x: 'A derrota no rio **Talas** (751) trava o avanço Tang na Ásia Central; a **rebelião de An Lushan** (755 – 763) devasta o norte. Chang’an é tomada e as rotas terrestres enfraquecem.' },
    { d: '904', t: 'A destruição de Chang’an', x: 'O senhor da guerra **Zhu Wen** manda desmontar os edifícios da cidade e transferir os habitantes para Luoyang. A grande Chang’an dos Tang nunca mais será capital.' },
    { d: '960 – 1127', t: 'Kaifeng: a cidade abre-se à rua', x: 'Com os Song do Norte, **Kaifeng** (Bianjing) é uma das maiores cidades do mundo (estimativa). A quadrícula dos bairros fechados desfaz-se: há lojas à beira da rua, restaurantes, teatros e **mercados noturnos**. Em 1127, os Jurchen tomam a cidade.' },
    { d: 'c. 1000 – 1087', t: 'Quanzhou e o gabinete do comércio marítimo', x: 'Quanzhou ganha a sua mesquita (1009) e, em 1087 (ou 1079), um **gabinete do comércio marítimo**. Torna-se um dos grandes portos do mundo, o «Zaitun» dos árabes.' },
    { d: '1132 – 1276', t: 'Hangzhou, capital dos Song do Sul', x: 'A corte dos Song fixa-se em **Hangzhou** (Lin’an), junto ao Lago Oeste e à saída do Grande Canal. É uma cidade de mais de um milhão de pessoas, segundo vários autores, com grandes mercados de arroz, de seda e de chá.' },
    { d: '1267 – 1293', t: 'Dadu, a cidade de Kublai Khan', x: 'Começada nos anos 1260 sob a direção de **Liu Bingzhong**, a nova capital **Dadu** (a «Grande Capital», a Khanbaliq dos viajantes) é a antepassada da Pequim atual. Em 1280 – 1293, o **Grande Canal** é refeito em linha reta até à capital.' },
    { d: '1366 – c. 1390', t: 'As muralhas dos Ming', x: 'Zhu Yuanzhang, que funda a dinastia Ming em 1368 com capital em **Nanjing**, manda erguer a enorme muralha desta cidade (cerca de 35 km segundo as contagens habituais, acabada por volta de 1390) e a de Xi’an (1370 – 1378). Dadu passa a **Beiping**.' },
    { d: '1405 – 1433', t: 'Zheng He no Oceano Índico', x: 'Sete grandes expedições marítimas, comandadas por **Zheng He**, vão de Nanjing a Calicute, a Ormuz e à costa leste de África. Depois de 1433 cessam e a corte volta o rosto à fronteira do norte.' },
    { d: '1406 – 1420', t: 'Pequim e a Cidade Proibida', x: 'O imperador **Yongle** muda a capital para o norte e constrói, em 14 anos, o palácio da **Cidade Proibida**, num eixo norte-sul que ainda hoje organiza a cidade.' },
    { d: 'c. 1449 – 1570', t: 'A Grande Muralha dos Ming', x: 'Depois do desastre de **Tumu** (1449), em que o imperador é capturado pelos mongóis, os Ming reforçam a fronteira do norte com muralha de tijolo e pedra, torres e fortalezas, sobretudo na segunda metade do século XV e entre 1567 e 1570, com o general **Qi Jiguang**.' }
  ] },
  { h: 'A redescoberta' },
  'A arqueologia moderna trouxe cidades à luz: em **1899** reconheceram-se os ossos oraculares; em **1928** começaram as escavações em Anyang; em **1950** foi descoberta a cidade Shang de Zhengzhou; em **1900** abriu-se a biblioteca escondida de Dunhuang; em **1973 – 74** apareceu o navio de Quanzhou e, em **1974**, o Exército de Terracota; e, desde os anos 1950, as escavações de Chang’an dos Han e dos Tang revelaram portas, ruas e palácios.'
];

const mapa = [
  'Este mapa não é de um país, mas de uma **rede**: capitais, cidades de comércio, fortalezas e portos, ligados por canais, estradas e caravanas. A tabela resume as principais; as secções seguintes contam as mais importantes.',
  { tabela: { cab: ['Local', 'Época', 'Onde fica hoje', 'Para que ficou conhecido'], linhas: [
    ['Erlitou / Zhengzhou', 'c. 1800 – 1400 a.C.', 'Yanshi e Zhengzhou, Henan', 'Primeira rede de ruas; primeiras grandes muralhas urbanas de terra batida da Idade do Bronze'],
    ['Anyang (Yinxu)', 'c. 1300 – 1046 a.C.', 'Anyang, Henan', 'Última capital Shang; ossos oraculares; túmulo de Fu Hao'],
    ['Chang’an', 'Han e Tang', 'Xi’an, Shaanxi', 'Capitais imperiais e ponto de partida da Rota da Seda'],
    ['Luoyang', 'Han Orientais a Tang', 'Luoyang, Henan', 'Capital «oriental»; Cavalo Branco; grutas de Longmen'],
    ['Kaifeng (Bianjing)', 'Song do Norte', 'Kaifeng, Henan', 'Cidade aberta à rua; mercados noturnos; Qingming'],
    ['Hangzhou (Lin’an)', 'Song do Sul', 'Hangzhou, Zhejiang', 'Capital do sul; Lago Oeste; fim do Grande Canal'],
    ['Dadu / Pequim', 'Yuan e Ming', 'Pequim', 'Capital de Kublai Khan; Cidade Proibida dos Ming'],
    ['Nanjing', 'Ming inicial', 'Nanjing, Jiangsu', 'Primeira capital Ming; uma das muralhas urbanas mais compridas do mundo'],
    ['Dunhuang', 'Han a Yuan', 'Gansu', 'Porta da Rota da Seda; grutas de Mogao; biblioteca escondida'],
    ['Guangzhou', 'Han a Ming', 'Guangdong', 'Porto do sul, aberto a árabes e persas'],
    ['Quanzhou', 'Song e Yuan', 'Fujian', 'O «Zaitun» dos viajantes; maior porto de comércio com o Índico'],
    ['Jiayuguan e Shanhaiguan', 'Ming', 'Gansu e Hebei', 'As duas extremidades da Grande Muralha dos Ming']
  ] } },
  { h: 'Erlitou e Zhengzhou: as primeiras cidades' },
  'Por volta de 1800 a.C., **Erlitou** (c. 300 hectares) foi talvez a maior povoação da Ásia Oriental. Tinha um palácio de terra batida, uma oficina de bronze e ruas em cruz. Cerca de 1600 a.C., a cidade Shang de **Zhengzhou** ergueu uma das primeiras grandes muralhas urbanas conhecidas da Idade do Bronze, de uns 7 km. A dinastia a que cada uma pertence (Xia ou Shang) é discutida, mas o desenho mostra já uma ideia de ordem e de poder.',
  { h: 'Anyang: a cidade dos reis Shang' },
  'Em **Yinxu**, a capital Shang de c. 1300 a 1046 a.C., o centro era formado por palácios e templos dos antepassados, rodeado por bairros de artesãos e por aldeias. A necrópole real, a noroeste, tem grandes túmulos com carros, cavalos e sacrifícios humanos. Até hoje, não se encontrou uma muralha em volta do núcleo palaciano. O túmulo de **Fu Hao** (1976) e os ossos oraculares são os achados mais célebres.',
  { img: 'ccs-yinxu-ruinas', leg: 'Ruínas do sítio de Yinxu, Anyang, Henan' },
  { h: 'Chang’an dos Han' },
  'O recinto dos Han, a noroeste da atual Xi’an, tinha um perímetro de cerca de 25,7 km, com doze portas e ruas largas. Os palácios ocupavam uma parte enorme da área, entre eles o **Weiyang**, de cerca de 5 km² (estimativa), várias vezes maior do que a Cidade Proibida. O resto era um mosaico de bairros, de mercados e de mansões. Os registos do ano 2 d.C. dão cerca de 250 000 habitantes à cidade (um número que pode incluir arredores).',
  { h: 'Chang’an dos Tang' },
  'A cidade de **Daxing**, dos Sui (582), foi herdada pelos Tang como **Chang’an**. Tinha cerca de 9,7 km de largura por 8,6 km de comprimento (c. 84 km²), uma **avenida central** com cerca de 150 m de largura e **mais de cem bairros murados** (*fang*), cujas portas se fechavam à noite. Havia dois mercados oficiais, o do Leste e o do Oeste. Os palácios ficavam a norte, e a partir de 634 o enorme palácio de **Daming**. Viviam aqui monges budistas, comerciantes sogdianos e persas, missionários cristãos nestorianos e, segundo as fontes chinesas, chegaram embaixadas de «Fulin» (Bizâncio). A população é estimada entre 800 000 e um milhão dentro das muralhas.',
  { img: 'ccs-ai-mercado-oeste', leg: 'Mercado Ocidental de Chang’an Tang, século VIII. Ilustração gerada por IA.' },
  { h: 'Xi’an depois dos Tang' },
  'Em 904, Zhu Wen desmantelou Chang’an. Os Ming construíram, entre 1370 e 1378, a muralha da cidade que hoje se visita, de terra batida (revestida de tijolo mais tarde), com cerca de 14 km de perímetro e uma área bem menor do que a da cidade Tang (cerca de um sexto a um sétimo, segundo as contagens). É das muralhas urbanas mais bem conservadas da China.',
  { img: 'ccs-xian-muralha', leg: 'Muralha da cidade de Xi’an (Ming)' },
  { h: 'Luoyang: a capital do Leste' },
  'Luoyang, no rio Luo, serviu várias dinastias. Foi capital dos **Han Orientais** (25 – 220), dos **Wei do Norte** (a partir de 493) e, com os Tang, a **«Capital Oriental»**, onde a corte residia quando faltava cereal em Chang’an. A imperatriz **Wu Zetian** fez dela a sua capital. Perto, em **Longmen**, abriram-se grutas budistas a partir de c. 493: são mais de 2000 grutas e nichos, com até 100 000 imagens, segundo as contagens habituais (variam).',
  { img: 'ccs-longmen', leg: 'Grutas de Longmen, Luoyang, com o Buda Vairocana da gruta Fengxian' },
  { h: 'Kaifeng: a cidade aberta' },
  'Dos Song do Norte (960 – 1127), a capital **Kaifeng** (Bianjing) ficava perto do rio Amarelo e ligava-se ao sistema do Grande Canal pelo canal Bian. As estimativas de população vão de pouco mais de 400 000 a mais de um milhão. A cidade quebrou as velhas regras: as lojas abriram junto às ruas, os mercados duraram à noite, e os restaurantes e casas de chá multiplicaram-se. O rolo de **Zhang Zeduan** mostra este mundo, e o livro de **Meng Yuanlao**, com prefácio de 1147, recorda-o com saudade. Um célebre **pagode de ferro** (1049, com cerca de 55 m de altura) ainda se vê.',
  { img: 'ccs-ferro-pagode-kaifeng', leg: 'Pagode de Ferro de Kaifeng (1049)' },
  { img: 'ccs-ai-kaifeng-noite', leg: 'Rua comercial noturna em Kaifeng Song, século XI. Ilustração gerada por IA.' },
  'Em 1127, os Jurchen tomaram Kaifeng e levaram a família imperial. A cidade, perto do rio Amarelo, foi ainda atingida por muitas cheias; em 1642, durante um cerco, os diques foram rompidos e a cidade ficou inundada, com centenas de milhares de mortos (estimativas).',
  { h: 'Hangzhou: a capital do sul' },
  'Depois da perda do norte, os Song fixaram-se em **Hangzhou**, que chamaram **Lin’an** («Paz Provisória»). A cidade, junto ao **Lago Oeste** e à foz do Grande Canal, passou de um milhão de habitantes, segundo vários historiadores. Os seus incêndios eram frequentes por causa das casas de madeira (o de 1237 terá destruído dezenas de milhares de casas). **Marco Polo**, que a chama Quinsai, descreve-a como a maior cidade do mundo, mas a sua passagem pela China é discutida.',
  { img: 'ccs-lago-oeste', leg: 'O Lago Oeste, Hangzhou' },
  { img: 'ccs-ai-hangzhou', leg: 'Canal e cidade de Hangzhou Song, século XIII. Ilustração gerada por IA.' },
  { h: 'Dadu e a Pequim dos Ming' },
  'Kublai Khan escolheu um sítio ao norte, perto da fronteira das estepes, para a nova capital **Dadu**, desenhada por **Liu Bingzhong** com a participação do muçulmano Ikhtiyar al-Din e baseada no velho modelo do *Kaogong ji*: ruas em quadrícula, palácio ao centro, mercados atrás. As obras começaram nos anos 1260 e acabaram por volta de 1293. Os Ming destruíram os palácios de Dadu em 1368 e chamaram à cidade Beiping; em 1403 o imperador **Yongle** (antes príncipe de Yan) deu-lhe o nome de **Beijing** («Capital do Norte»), e mandou construir, entre 1406 e 1420, a **Cidade Proibida**, de 72 hectares e cerca de 980 edifícios; a corte mudou-se de vez em 1421.',
  { img: 'ccs-ai-dadu', leg: 'Dadu, capital de Kublai Khan, c. 1290; reconstituição conjetural. Ilustração gerada por IA.' },
  { h: 'Dunhuang: a porta do deserto' },
  'Fundada pelos Han no fim do século II a.C. como comandância militar, **Dunhuang** ficava no extremo ocidental do corredor de Hexi, onde as rotas se dividiam, a norte e a sul do deserto de Taklamakan. As passagens de **Yumen** e **Yang** eram os postos de controlo. A sudeste da cidade, numa falésia, abrem-se as **grutas de Mogao**, com 735 grutas (492 pintadas), iniciadas segundo a tradição em 366. Numa delas, selada no início do século XI, havia cerca de 50 000 manuscritos, descobertos em 1900.',
  { img: 'ccs-mogao-fachada', leg: 'Fachada das grutas de Mogao, Dunhuang' },
  { h: 'Os oásis: Turfan, Kashgar e Samarcanda' },
  'Para lá de Dunhuang, as caravanas rodeavam o Taklamakan por dois caminhos de oásis: **Turfan** e **Kucha** a norte, **Khotan** e **Yarkand** a sul, até **Kashgar**, onde as duas rotas se juntavam. Depois, atravessavam o Pamir até à **Sogdiana** (Samarcanda, Bucara), à Báctria e à Pérsia. Em quase todas as cidades havia um **caravançarai**, onde se descansava, trocava e pagava taxas. Poucos comerciantes faziam o percurso inteiro: as mercadorias passavam de mão em mão.',
  { img: 'ccs-ai-oasis', leg: 'Cidade-oásis na Rota da Seda, século VIII. Ilustração gerada por IA.' },
  { h: 'Quanzhou: o «Zaitun»' },
  'No sul de Fujian, **Quanzhou** foi, nos séculos XI a XIV, o grande porto do comércio com o Índico. Havia comunidades árabes, persas, indianas e cristãs, a **mesquita de Qingjing** (1009), o templo budista de **Kaiyuan**, com dois pagodes de pedra do século XIII, e o templo maniqueísta de **Cao’an**. **Ibn Battuta** e **Marco Polo** descrevem-no como um dos maiores portos do mundo. Em 2021, a UNESCO inscreveu o conjunto dos seus monumentos.',
  { img: 'ccs-quanzhou-kaiyuan', leg: 'Os dois pagodes de pedra do templo Kaiyuan, Quanzhou' },
  { h: 'Guangzhou e o mar do sul' },
  'Guangzhou (Panyu, no tempo dos Han) comerciava com o Sudeste Asiático e a Índia já em 200 a.C. O túmulo do rei de Nanyue, **Zhao Mo** (c. 122 a.C.), tem objetos de longe. Com os Tang, tornou-se o principal porto da China e sede do gabinete de comércio marítimo (714). Em 879, o rebelde **Huang Chao** saqueou-a, e as fontes árabes falam de um massacre de estrangeiros, com números exagerados. Manteve-se como o grande porto do sul até ao século XIX (o chamado «sistema de Cantão» vigorou de 1757 a 1842).',
  { h: 'O Grande Canal' },
  'O Grande Canal tem hoje cerca de **1776 km**, de Hangzhou a Pequim, e é Património Mundial desde 2014. É um conjunto de canais feito ao longo de séculos: o Hangou (486 a.C.), os troços dos **Sui** (605 – 611), a reconstrução dos **Yuan** (1280 – 1293), que encurtou o trajeto em cerca de 700 km, e as reparações dos Ming. Transportava sobretudo o **cereal** do sul para as capitais do norte. Sob os Yuan, o troço mais alto, o canal de Jizhou, subia 42 m acima do Yangtzé, vencido com **comportas**; a eclusa de câmara, atribuída a **Qiao Weiyue** (984), é uma invenção chinesa dos Song.',
  { h: 'A Grande Muralha: troços e extremos' },
  'Do lado oeste, **Jiayuguan** (fundado em 1372) é a fortaleza que fecha o corredor de Hexi; no lado leste, **Shanhaiguan** («Passagem entre a Montanha e o Mar») liga a muralha ao golfo de Bohai. Entre as duas, perto de Pequim, os troços de **Badaling**, **Mutianyu**, **Jinshanling** e **Juyongguan** são os mais visitados. Mais a oeste, no deserto de Dunhuang, ficam os restos da muralha de terra e juncos dos **Han**.',
  { h: 'As rotas' },
  { lista: [
    '**Rota da estepe:** pelas pastagens a norte dos desertos, do norte da China à Sogdiana e ao mar Negro; era a das tribos nómadas.',
    '**Rotas dos oásis:** de Chang’an por Hexi e Dunhuang, e depois por dois ramos, a norte (Turfan, Kucha) e a sul (Khotan, Yarkand) do Taklamakan, até Kashgar e à Sogdiana.',
    '**Rota do sudoeste:** de Sichuan e Yunnan para o Tibete, a Birmânia e a Índia, por trilhos de montanha; ficou ligada ao chá e aos cavalos.',
    '**Rota marítima:** de Guangzhou ou Quanzhou ao Sudeste Asiático, à Índia, ao Golfo e à África Oriental.'
  ] }
];

const sociedade = [
  { h: '1. Planear uma capital' },
  'O *Kaogong ji*, o «Registo dos Artífices», um capítulo dos *Rituais de Zhou* que a maioria dos estudiosos data do fim dos Reinos Combatentes (séc. III a.C.), descreve a capital ideal: um quadrado com **nove *li* de lado**, **três portas em cada lado**, **nove ruas norte-sul e nove este-oeste**. Segundo a tradição, o templo dos antepassados ficava à esquerda e o altar da terra à direita; a corte à frente e o mercado atrás. Poucas cidades reais seguiram a letra do esquema, mas a ideia de **simetria, de eixo e de recinto** orientou as capitais durante séculos.',
  { cit: 'O mestre artífice constrói a capital: faz um quadrado de nove *li* de lado; cada lado tem três portas.', fonte: 'Kaogong ji, «Registo dos Artífices», cerca do séc. III a.C. (tradução livre)' },
  { img: 'ccs-ai-kaogongji', leg: 'Esquema da capital ideal do Kaogong ji; interpretação didática. Ilustração gerada por IA.' },
  { h: '2. Geomancia e eixo' },
  'O sítio de uma cidade escolhia-se com a ajuda de **adivinhos e geómantes**, atendendo à orientação, à água e às montanhas. Uma cidade deveria estar **voltada a sul**, com as costas ao norte, e o palácio ficava no eixo central. O imperador sentava-se de frente para o sul e os súbditos voltavam-se para ele. Em Pequim, este eixo ainda é a espinha da cidade.',
  { h: '3. Muralhas urbanas' },
  'A palavra *cheng* quer dizer «muralha» e «cidade». Quase todas as cidades tinham uma muralha de **terra batida**, feita por camadas finas comprimidas entre pranchas de madeira, com portas e torres. Foi sobretudo nos **Ming** que as grandes cidades passaram a ter muralhas revestidas de **tijolo**. A muralha defendia, mas também **controlava**: marcava onde acabava a cidade, onde se pagavam taxas e quem entrava. À volta, havia um fosso.',
  { img: 'ccs-pingjiang-tu', leg: 'Mapa de Pingjiang (Suzhou), gravado em pedra em 1229' },
  { h: '4. Bairros fechados e mercados vigiados' },
  'Nas cidades da época Han e Tang, a população vivia em **bairros** (*fang*) rodeados de muros, com portas que se fechavam ao anoitecer; passar a noite na rua era proibido (**recolher obrigatório**), salvo nas festas, como o Festival das Lanternas, em que, segundo as fontes, a proibição era levantada. O comércio só se fazia nos **mercados** oficiais, os *shi*, que, no tempo dos Tang, abriam ao meio-dia e fechavam antes do pôr do sol, vigiados por funcionários que fixavam preços e controlavam pesos e medidas.',
  { img: 'ccs-ai-chang-an-bairro', leg: 'Porta de um bairro de Chang’an Tang ao pôr do sol. Ilustração gerada por IA.' },
  { h: '5. A cidade quebra a quadrícula' },
  'No tempo dos Song, o crescimento do comércio tornou o modelo impossível. Em **Kaifeng** e em **Hangzhou**, as lojas abriram nas ruas, os mercados chegaram a todos os bairros, e a noite ganhou vida. Os escritos de **Meng Yuanlao** (sobre Kaifeng, prefácio de 1147) e de **Wu Zimu** (sobre Hangzhou, 1274) descrevem tavernas, casas de chá, palcos, vendedores ambulantes e lojas abertas até tarde. Pela primeira vez, a rua é o centro da vida urbana.',
  { img: 'ccs-qingming-cidade', leg: 'Pormenor da porta da cidade e da rua comercial em «Ao longo do rio no Festival de Qingming»' },
  { h: '6. A Grande Muralha: uma sucessão de muralhas' },
  'A Grande Muralha foi construída **por troços e por várias dinastias**: Estados em guerra desde o século VII – V a.C.; os **Qin**, que, segundo **Sima Qian**, ligaram os troços do norte sob o general **Meng Tian**, com cerca de 300 000 homens; os **Han**, que a levaram muito para oeste, até às portas de Dunhuang; os **Wei do Norte**, os **Sui**, e, sobretudo, os **Ming**. As muralhas de terra dos primeiros foram feitas de camadas de terra, de pedra ou, no deserto, de **juncos e cascalho**; a de tijolo e pedra dos Ming, com torres, é a que se vê nas fotografias.',
  { img: 'ccs-ai-muralha-qin', leg: 'Construção de muralha Qin de terra batida, c. 214 a.C. Ilustração gerada por IA.' },
  'Uma pesquisa oficial de **2012** deu um total de cerca de **21 196 km** de muralhas de todas as épocas; só a dos Ming mede uns **8850 km** (medição de 2009), contando troços de muralha, valas e barreiras naturais. As cifras variam conforme se contam trincheiras, torres isoladas e obstáculos.',
  { h: '7. Para que servia a muralha' },
  'A muralha não era um muro intransponível, mas um **sistema**: muralha, torres de vigia, fortes, guarnições, estradas e sinais de fumo e de fogo. Servia para **vigiar, retardar e controlar**: cobrar taxas, impedir razias e regular o comércio de cavalos e de gado com os nómadas. Resultou ora bem, ora mal: os Ming sofreram ataques apesar das muralhas (o de **Altan Khan** em 1550 chegou às portas de Pequim), e em **1644** a passagem de Shanhaiguan foi aberta aos Manchus por um general Ming, **Wu Sangui**. A defesa dependia mais dos homens do que das pedras.',
  { img: 'ccs-ai-torre-sinais', leg: 'Torre de sinais fronteiriça Han, perto de Dunhuang. Ilustração gerada por IA.' },
  { h: '8. Soldados, desterrados e lendas' },
  'Os que construíam e guarneciam a muralha eram soldados, camponeses mobilizados e condenados. Na época Han, os soldados da fronteira de Dunhuang deixaram milhares de **tiras de madeira** com ordens, contas, cartas e listas de provisões, uma fonte preciosa sobre a vida quotidiana na fronteira. A tradição popular guardou o sofrimento dos trabalhadores na lenda de **Meng Jiangnü**, cuja dor pela morte do marido, obrigado a trabalhar na muralha, teria feito desabar um troço. É uma **lenda**, não um facto.',
  { h: '9. Canais, estradas e transporte' },
  'Os grandes rios chineses correm de oeste para leste; para ligar o norte e o sul era preciso abrir **canais** que os cruzassem. O Grande Canal foi a mais importante destas obras. As estradas do **Qin** foram uniformizadas (a «Estrada Direta» de 212 a.C. tinha mais de 700 km, segundo estimativas), mas era a água que transportava o peso: o **cereal** do sul era o «imposto em géneros» que alimentava as capitais, o exército e a corte. Por volta de 735, segundo uma estimativa, chegavam pelo canal cerca de **150 milhões de quilos** de cereal por ano.',
  { img: 'ccs-ai-canal-sui', leg: 'Barcaças de cereais no Grande Canal, época Sui ou Tang. Ilustração gerada por IA.' },
  { h: '10. Engenharia de pontes, diques e eclusas' },
  'Os engenheiros chineses construíram **diques** e **comportas**, como no Dujiangyan, em uso desde c. 256 a.C. (a Li Bing, por tradição), o **canal Lingqu** (214 a.C.), que liga o sistema do Yangtzé ao do Pearl, e pontes famosas, como a de **Zhaozhou** (c. 595 – 605), uma ponte em arco de pedra com aberturas laterais, a mais antiga do tipo que se conserva. O **manual de construção** *Yingzao fashi*, de **Li Jie** (1103), descreve materiais, medidas e tipos de edifícios.',
  { h: '11. A Rota da Seda: como funcionava' },
  'A «Rota da Seda» foi uma **rede de caminhos** e de **mercados** entre a China e o Mediterrâneo, e só muito raramente alguém a percorreu inteira. Cada troço tinha os seus comerciantes, as suas taxas e os seus riscos. Os **sogdianos**, de Samarcanda, foram os grandes intermediários entre os séculos IV e VIII; tinham comunidades em Dunhuang, em Chang’an e em Luoyang. As mercadorias passavam de mão em mão, e os preços subiam a cada etapa. O transporte era feito em **camelos bactrianos**, que aguentam o frio e carregam mais de 150 kg.',
  { img: 'ccs-tang-camelo-musicos', leg: 'Camelo de cerâmica sancai com músicos, Tang, Museu de História de Shaanxi (Xi’an)' },
  { h: '12. O que ia e o que vinha' },
  { tabela: { cab: ['Da China para o Ocidente', 'Do Ocidente para a China'], linhas: [
    ['Seda (em rolos, usada como moeda)', 'Cavalos «celestiais» de Fergana, camelos'],
    ['Papel e técnicas de o fazer (a partir do séc. VIII, por tradição depois de Talas)', 'Vidro, pedras preciosas, lápis-lazúli'],
    ['Chá, porcelana, laca', 'Vinho de uva, uvas, luzerna, nozes, coentros (algumas por tradição)'],
    ['Pólvora, bússola, impressão (por esta via ou pelo mar)', 'Budismo, nestorianismo, maniqueísmo, zoroastrismo, islão'],
    ['Peles, ruibarbo, medicinas', 'Músicos, bailarinos, instrumentos (alaúde, harpa), roupas e modas «hu»']
  ] } },
  'As tradições atribuem a **Zhang Qian** muitas plantas, como a uva e a luzerna; os historiadores acham que algumas chegaram por outras vias ou depois. O que é seguro é que a China comprou **cavalos** e vendeu **seda** em enormes quantidades.',
  { h: '13. Religiões em viagem' },
  'O **budismo** chegou à China pelos oásis, no século I d.C., trazido por monges e comerciantes. A sua arte nas grutas de Mogao e de Longmen mostra a influência da Índia e da Ásia Central. Os **cristãos nestorianos** estão documentados por uma grande estela de **781**, erguida em Chang’an e hoje em Xi’an; os **maniqueus**, os **zoroastrianos**, os **judeus** (Kaifeng) e os **muçulmanos** (Guangzhou, Quanzhou, Chang’an) tinham templos e comunidades. A corte Tang tolerou estas religiões, com períodos de perseguição, sobretudo contra o budismo em 845.',
  { img: 'ccs-estela-nestoriana', leg: 'Estela nestoriana (781), Museu Beilin, Xi’an' },
  { h: '14. Dunhuang e as grutas de Mogao' },
  'Em Mogao, monges e mecenas abriram, durante cerca de mil anos, grutas-templo na falésia, cobertas de pinturas de budas, de paraísos e de cenas da vida corrente. Numa pequena gruta selada no início do século XI, a «Biblioteca» (gruta 17), guardaram-se cerca de 50 000 textos, em chinês, tibetano, sogdiano, sânscrito e outras línguas: sutras, contratos, cartas, mapas, o **Sutra do Diamante** (868). Foram descobertos em 1900 por **Wang Yuanlu**; em 1907 e 1908, **Aurel Stein** e **Paul Pelliot** compraram muitos.',
  { img: 'ccs-mogao-mural', leg: 'Pintura mural budista das grutas de Mogao' },
  { h: '15. O comércio marítimo' },
  'A partir dos Tang, e sobretudo dos Song, o **mar** tornou-se mais importante do que o deserto. Os navios chineses, chamados **juncos**, tinham casco com **compartimentos estanques**, velas de esteira e leme de popa; no século XII, a **bússola** de agulha magnética já era usada na navegação. Os portos tinham um **superintendente do comércio marítimo** (*shibosi*), que cobrava taxas. Os produtos de exportação eram a porcelana, a seda, o cobre (em moedas) e o chá; importavam-se especiarias, incenso, marfim, madeiras e pedras preciosas.',
  { img: 'ccs-belitung-taca', leg: 'Cerâmica de Changsha e outros objetos do naufrágio de Belitung, Asian Civilisations Museum, Singapura.' },
  { img: 'ccs-navio-quanzhou', leg: 'Casco de navio do século XIII de Quanzhou, pavilhão do Museu das Relações Ultramarinas no templo Kaiyuan.' },
  { h: '16. Estrangeiros nas cidades chinesas' },
  'Os Tang, os Song e os Yuan tiveram **bairros de estrangeiros** em Chang’an, Guangzhou, Quanzhou e Yangzhou, onde árabes, persas, indianos, sogdianos e coreanos viviam com os seus costumes, e alguns tinham funções oficiais. Os Tang aceitaram **ministros e generais** de origem estrangeira, como An Lushan, de ascendência sogdiana e turca. Com os Mongóis, as comunidades de **muçulmanos** (*semu*) foram favorecidas. Os Ming, ao contrário, limitaram o comércio privado com o estrangeiro.',
  { h: '17. Como era o quotidiano numa cidade' },
  'Uma rua de Chang’an ou de Kaifeng tinha ruído, cheiros e cores: **carregadores**, **vendedores** de comida, casas de chá, **adivinhos**, escribas, **cavaleiros** e **burros** de carga. Os bairros tinham **poços**, e a cidade, esgotos e valas; as **casas de madeira** ardiam com facilidade, e Hangzhou, no século XIII, tinha torres de vigia e **bombeiros** organizados. As cidades Song tinham **hospitais**, asilos e cemitérios públicos mantidos pelo Estado, e as grandes festas (o Ano Novo, o Qingming, o Festival das Lanternas, o Festival da Lua) enchiam as ruas.',
  { h: '18. Mercados, lojas e corporações' },
  'Nos mercados, as lojas agrupavam-se por **ofícios** (rua dos açougueiros, dos ourives, dos livros), e os comerciantes e artesãos de cada ramo formavam **corporações** (*hang*), que fixavam preços e regras. No tempo dos Song multiplicaram-se os **restaurantes** com especialidades, as **estalagens**, os **penhores** e o **crédito**. Um conhecido lugar de diversão, o *washe*, tinha palcos de teatro, contadores de histórias, acrobatas e marionetas.',
  { img: 'ccs-ai-restaurante-song', leg: 'Restaurante em Kaifeng Song. Ilustração gerada por IA.' },
  { h: '19. Casas' },
  'A casa urbana típica, sobretudo no norte, era a de **pátio**: edifícios de um só piso à volta de um pátio central, virados a sul, de **estrutura de madeira**, paredes de tijolo ou de terra e telhado de telha. As regras de **luxo** (*suntuárias*) fixavam, por classes, o tamanho da casa, o número de vãos e as cores. Os modelos de cerâmica de casas Han, achados em túmulos, mostram **torres**, celeiros, poços e pocilgas. No norte, as camas de tijolo aquecidas, os *kang*, ajudavam a enfrentar o inverno.',
  { img: 'ccs-han-casa-modelo', leg: 'Modelo funerário de cerâmica de uma casa com torre, época Han' },
  { img: 'ccs-ai-casa-patio', leg: 'Casa de pátio de uma família de funcionários, época Tang ou Song. Ilustração gerada por IA.' },
  { h: '20. Comida' },
  'No norte comia-se **painço**, depois **trigo** em massas e pães (os *hubing*, «bolos dos bárbaros», estiveram na moda nos Han e Tang); no sul, **arroz**. Em Lajia, em Qinghai, encontrou-se uma tigela com **massa de painço** com cerca de 4000 anos, uma das mais antigas conhecidas. A carne mais comum era a de porco; entre as elites Tang, o carneiro e os lacticínios, de influência dos povos do norte, estiveram em moda. O **chá**, descrito no manual de **Lu Yu** (c. 760 – 780), tornou-se a bebida da cidade. Da cozinha Song, com restaurantes de estilos do norte e do sul, sobreviveram descrições detalhadas.',
  'Muita da comida «chinesa» que hoje conhecemos é **mais tardia**: o **pimento** (malagueta), o **amendoim**, a **batata-doce** e o **milho** vieram da América depois de 1500, e a cozinha picante de Sichuan é bem posterior. O **açúcar** de cana foi refinado com técnicas aprendidas na Índia no tempo dos Tang (tradição de c. 647).',
  { h: '21. Roupa' },
  'A roupa dependia do clima e da classe. Os pobres usavam **cânhamo** e **rami**; os ricos, **seda**. O **algodão** só se generalizou nos Song e nos Yuan; a tradição atribui a **Huang Daopo**, no fim do século XIII, a divulgação das técnicas de fiação no delta do Yangtzé. As cores e as formas eram reguladas: a partir dos Tang, o amarelo ficou reservado ao imperador. Nos Tang, a corte e as cidades adotaram modas **«hu»** de origem da Ásia Central (chapéus, casacos justos, botas); a moda feminina Tang era, em geral, mais ousada do que a dos Song. A prática dos **pés atados** das mulheres surgiu na elite durante os Song e espalhou-se depois; a sua origem é debatida.',
  { h: '22. Moeda' },
  'A moeda chinesa mais característica é a **moeda de bronze redonda com furo quadrado**, introduzida pelos Qin (*banliang*) e depois padronizada pelos Han com a **wuzhu** (118 a.C.), cunhada durante mais de 700 anos. Os Tang criaram a **Kaiyuan tongbao** (621), que serviu de modelo durante séculos, na China e fora dela. As moedas eram enfiadas em **cordões** de mil, e em compras grandes usavam-se rolos de **seda** e, mais tarde, **prata**.',
  { img: 'ccs-cash-moedas', leg: 'Cordão de moedas chinesas cash, exposição museológica.' },
  'Os Song cunharam enormes quantidades (cerca de seis mil milhões de moedas em 1085, segundo uma estimativa) e, por serem pesadas, inventaram o **papel-moeda**: o *jiaozi* de Sichuan (emissão oficial c. 1024) e o *huizi* dos Song do Sul. Os **Yuan** fizeram do papel-moeda (*chao*) a moeda principal, e **Marco Polo** admira-se com ele. A emissão excessiva levou à inflação.',
  { img: 'ccs-notas-yuan', leg: 'Nota (chao) da dinastia Yuan, tempo de Kublai Khan' },
  { h: '23. Correio e comunicações' },
  'O correio era um serviço **do Estado**, só para ordens e informações oficiais. Desde os Qin e os Han havia **estações** (*yi*, *you*) em estradas e rios, com cavalos e relés. No tempo dos Tang, as fontes falam de cerca de **1600 estações** (1639, segundo uma contagem), com milhares de funcionários. Os Song entregaram o correio rápido à autoridade militar (o Shumiyuan). Os **mongóis** criaram o *yam*, com estações a cada 30 – 60 km e mensageiros que, por estimativa, faziam 200 a 300 km por dia, com **tabuinhas** (*paiza*) que davam direito a cavalos e alojamento. As cartas privadas iam por amigos, comerciantes ou, nos Ming, por «agências de correio» particulares.',
  { img: 'ccs-ai-posta', leg: 'Correio montado num posto de muda de cavalos, época Tang ou Yuan. Ilustração gerada por IA.' },
  { h: '24. Mulheres e vida urbana' },
  'As mulheres da elite viviam sobretudo na casa e no pátio interior, mas as cidades e os mercados deram espaço a **vendedoras**, **tecedeiras**, parteiras, cantoras e donas de estalagens. Nos Tang, havia mulheres que montavam a cavalo e jogavam polo; nos Song, a vida da mulher da elite ficou mais restrita. As fontes, escritas quase só por homens, mostram pouco a vida das camponesas e das artesãs.',
  { h: '25. Guerra e cidades cercadas' },
  'As cidades muradas eram a chave da guerra: quem as tomava, controlava a região. As técnicas de cerco evoluíram: escadas e torres, minas, **catapultas**, e depois a pólvora. Os mongóis levaram **engenheiros** persas e chineses; no cerco de **Xiangyang** (1268 – 1273), usaram trabucos de contrapeso, e o cerco acabou com a rendição da cidade. As muralhas dos Ming foram adaptadas à era dos **canhões**.',
  { h: '26. A água, a ameaça e o encanto' },
  'O **rio Amarelo** mudou muitas vezes de curso e provocou cheias terríveis; muitas cidades foram abandonadas ou enterradas. **Kaifeng** é um exemplo: está **assente sobre camadas de cidades** mais antigas, sepultadas por sucessivas cheias e lodo. Cuidar de diques, canais e comportas era um dos primeiros deveres de um funcionário, e a «domesticação das águas» é um tema central da lenda de Yu o Grande.',
  { h: '27. Ensino, livros e teatro nas cidades' },
  'As cidades eram também o lugar do **estudo**: escolas, bibliotecas, academias e os centros de **impressão**. No tempo dos Song, a imprensa fez descer o preço dos livros, e as casas de chá e os palcos urbanos ouviam histórias, óperas e canções. Os exames imperiais atraíam a Kaifeng e a Hangzhou milhares de candidatos, que enchiam as pensões e as livrarias.',
  { h: '28. Cidade e campo' },
  'Mesmo no auge, a vasta maioria dos chineses vivia no campo. Os Song são o período em que a proporção de população urbana terá subido mais, mas os números são incertos. As cidades viviam do campo, que lhes dava cereal, impostos e trabalhadores, e o campo comprava nas cidades sal, ferro, tecidos e utensílios.',
  { h: '29. Música, jogos e festas' },
  'A música urbana misturou, nos Tang, as melodias chinesas com as da Ásia Central, com o **alaúde** (*pipa*) e a **harpa**. Os jogos de tabuleiro (*weiqi*), o **polo** e as **corridas de barcos-dragão** eram populares. Nas cidades, as festas do calendário marcavam o ano: as **lanternas**, o **Qingming** (a limpeza dos túmulos), o Duanwu e o Festival da Lua.',
  { h: '30. Tecnologia da cidade' },
  'Em muitas cidades houve **relógios de água**, **torres de tambor e de sino** que marcavam as horas e abriam e fechavam as portas, **aquedutos** e fontes. O relógio astronómico de **Su Song** (1092) em Kaifeng é o exemplo mais famoso. As técnicas de impressão e a **bússola** mudaram a vida urbana e marítima.',
  { h: '31. Segurança, justiça e poder' },
  'Cada cidade tinha um **magistrado**, que era juiz, cobrador de impostos e chefe de polícia. Havia **vigias noturnos**, prisões, e leis severas contra a falsificação de moeda. Os funcionários eram transferidos regularmente, para evitar que criassem raízes locais.',
  { h: '32. O sal, o ferro e o Estado' },
  'O Estado controlava o **sal** e o **ferro** desde os Han, e esses monopólios eram uma fonte de receita central. **Yangzhou**, no Grande Canal, foi desde os Tang um centro da administração e do comércio do sal. A porcelana, a seda e o chá eram fabricados em oficinas privadas ou oficiais, e as cidades ao longo das rotas eram os seus mercados.',
  { h: '33. Desigualdade e pobreza' },
  'A cidade era lugar de grande riqueza e de grande pobreza. Os Song tinham **instituições de caridade**, mas também mendigos, ladrões e desempregados. Os impostos, o trabalho forçado, as secas e as cheias levavam as famílias camponesas à cidade, onde muitas se tornavam servos ou trabalhadores sem terra.',
  { h: '34. Outros caminhos: a rota do chá e dos cavalos' },
  'Além da Rota da Seda, houve a **rota do chá e dos cavalos**, que levava o chá de Sichuan e de Yunnan ao Tibete, em troca de cavalos de guerra, e foi muito importante nos Tang e nos Song. Era uma rota de montanha, de mulas e de carregadores, e não de camelos.',
  { h: '35. Como sabemos tudo isto' },
  'Conhecemos as cidades chinesas por **escavações**, por **plantas** (como o mapa de Pingjiang, de 1229), por **pinturas**, por **textos**, como as obras de Meng Yuanlao e de Wu Zimu, por **relatos de viajantes** e por **modelos** de cerâmica de túmulos. Cada fonte tem o seu viés: os relatos dos viajantes exageram, as pinturas idealizam, os textos oficiais falam de normas, e a arqueologia mostra o que sobreviveu.'
];

const personalidades = [
  'Os nomes abaixo são de **governantes, engenheiros, generais, monges, cronistas e viajantes** ligados às cidades, às muralhas, aos canais e às rotas. Quando há lendas ou dúvidas, ficam assinaladas.',
  { h: 'Li Bing (séc. III a.C.)' },
  'Governador de Shu (Sichuan) sob o rei de Qin, a quem a tradição atribui o **Dujiangyan** (c. 256 a.C.), que repartiu as águas do rio Min e fez da planície de Chengdu a «terra da abundância» (*tianfu zhi guo*). O sistema ainda irriga, hoje, mais de 600 000 hectares. Não se sabe quase nada da sua vida; é possível que o projeto seja obra de uma equipa e de várias gerações.',
  { h: 'Meng Tian (m. 210 a.C.)' },
  'General de **Qin**, que, segundo **Sima Qian**, comandou cerca de 300 000 homens contra os Xiongnu e dirigiu a ligação das muralhas do norte e a abertura da «Estrada Direta». Depois da morte do Primeiro Imperador, foi obrigado a suicidar-se por uma intriga da corte. Sima Qian, que visitou a obra, critica o sofrimento que ela custou.',
  { h: 'Xiao He (m. 193 a.C.)' },
  'Chanceler de Liu Bang e organizador da administração Han. Segundo o *Shiji*, dirigiu a construção do palácio de **Weiyang**, em Chang’an, e mandou-o fazer majestoso para mostrar o poder da nova dinastia; ao imperador, que o achou excessivo, respondeu que um palácio assim era necessário para impor respeito. É uma anedota da tradição.',
  { h: 'Zhang Qian (m. 114 a.C.) e Ban Chao (32 – 102)' },
  '**Zhang Qian**, enviado por Wu Di, esteve preso mais de dez anos pelos Xiongnu e trouxe a primeira informação sobre a Sogdiana e a Báctria. **Ban Chao**, general do tempo dos Han Orientais, conquistou o Tarim, ocupou Khotan e Kashgar e foi nomeado **Protetor-Geral das Regiões Ocidentais** em 91. Em 97 enviou **Gan Ying** em direção a Daqin (Roma); Gan Ying parou, segundo a fonte chinesa, perto de uma grande extensão de água, e deu à China a primeira descrição do Ocidente.',
  { h: 'Yuwen Kai (555 – 612)' },
  'Arquiteto e engenheiro dos Sui, desenhou **Daxing** (582), a futura Chang’an dos Tang, e **Luoyang**, a «Capital Oriental» (605). A sua quadrícula de bairros foi a mais ambiciosa da época. As suas obras serviram de modelo a **Heijō-kyō** (Nara) e a **Heian-kyō** (Quioto), no Japão.',
  { h: 'O imperador Yang dos Sui (569 – 618)' },
  'Segundo filho do fundador dos Sui, subiu ao trono em 604. Mandou construir a capital de Luoyang e unir os canais num sistema, **o Grande Canal**, à custa de milhões de trabalhadores forçados (cinco milhões, segundo uma fonte antiga, uma cifra provavelmente exagerada). Os historiadores tradicionais fizeram dele o tirano que perdeu a dinastia, por causa dos custos, das guerras na Coreia e das revoltas, mas o canal foi uma das obras mais úteis da China.',
  { img: 'ccs-yangdi-retrato', leg: 'Imperador Yang dos Sui, em «Os Treze Imperadores», atribuído a Yan Liben, Museu de Belas-Artes de Boston' },
  { h: 'Xuanzang (602 – 664)' },
  'O monge que, em 629 (ou 627, segundo outras fontes), saiu de Chang’an, atravessou Dunhuang, Turfan, Samarcanda e a Báctria e chegou à Índia, onde estudou em Nalanda. Regressou em 645 com centenas de manuscritos por Khotan, e escreveu o **relato** (*Registos Ocidentais dos Tang*), uma fonte essencial sobre a Ásia Central e a Índia do século VII. Em Chang’an, em 652, ergueu-se o **Pagode do Grande Ganso Selvagem** para guardar os textos que trouxe.',
  { h: 'Meng Yuanlao e Zhang Zeduan (séc. XII)' },
  '**Meng Yuanlao** escreveu, por volta de 1147, as *Recordações do Sonho do Esplendor Oriental* (*Dongjing meng hua lu*), com saudades da Kaifeng que perdera em 1127: ruas, restaurantes, festas, divertimentos. **Zhang Zeduan** (c. 1085 – c. 1145) é o pintor a quem se atribui o rolo *Ao longo do rio no Festival de Qingming*. De ambos sabe-se pouco, e a interpretação do rolo (Kaifeng ou outro local, e que festival) é discutida.',
  { h: 'Li Jie (1065 – 1110)' },
  'Funcionário e engenheiro dos Song do Norte, autor do **Yingzao fashi** (1103), o manual de construção mais completo da China antiga, com regras para a madeira, o tijolo, o telhado, a decoração e a cor. É a nossa melhor fonte sobre como se construíam os grandes edifícios Song.',
  { h: 'Liu Bingzhong (1216 – 1274) e Guo Shoujing (1231 – 1316)' },
  '**Liu Bingzhong**, monge e conselheiro de Kublai Khan, desenhou **Dadu** e a cidade de verão de **Shangdu**. O seu discípulo **Guo Shoujing**, astrónomo e engenheiro hidráulico, refez o **Grande Canal** até à capital (1280 – 1293) e reformou o calendário.',
  { h: 'O imperador Yongle (1360 – 1424)' },
  'Zhu Di, filho de Zhu Yuanzhang, tomou o trono em 1402 contra o sobrinho e transferiu a capital para o norte, para **Pequim**, onde construiu a Cidade Proibida (1406 – 1420), sustentou as expedições de **Zheng He** e mandou fazer a grande enciclopédia *Yongle dadian*. Foi também um chefe militar que combateu os mongóis.',
  { img: 'ccs-yongle-retrato', leg: 'Retrato do imperador Yongle, Museu Nacional do Palácio, Taipé' },
  { h: 'Zheng He (1371 – 1433)' },
  'Eunuco muçulmano originário de Yunnan, comandou, entre 1405 e 1433, sete expedições marítimas do Mar da China à Índia, a Ormuz e à costa da África Oriental, com frotas muito grandes (algumas dezenas a centenas de navios e perto de 28 000 homens na primeira, segundo as fontes; as dimensões dos navios são debatidas). Trouxe embaixadores e animais exóticos, como uma girafa. Depois da sua morte, as expedições não foram retomadas.',
  { h: 'Wang Yuanlu, Aurel Stein e Paul Pelliot' },
  '**Wang Yuanlu** (c. 1849 – 1931), monge taoista, guardava as grutas de Mogao e encontrou em 1900 a biblioteca escondida. O arqueólogo húngaro-britânico **Aurel Stein** (1862 – 1943), em 1907, e o francês **Paul Pelliot** (1878 – 1945), em 1908, compraram-lhe milhares de manuscritos que hoje estão em Londres e Paris. A compra é hoje vista de forma crítica na China e no Ocidente.',
  { h: 'Ibn Battuta (1304 – c. 1368/69)' },
  'Viajante marroquino que visitou a China por volta de 1345 – 1346 e descreveu **Quanzhou** (Zaitun) como um porto imenso, com juncos enormes. Os historiadores discutem se esteve em todos os lugares que descreve, mas o seu relato dá uma visão independente da de Marco Polo.'
];

const legado = [
  { h: 'O que nos deixaram' },
  { lista: [
    '**A cidade planeada:** o modelo da capital com eixo, recinto e quadrícula passou à Coreia, ao Japão (Nara e Quioto) e ao Vietname, e ainda se reconhece em Pequim.',
    '**A Grande Muralha:** símbolo da China, e uma das maiores obras de engenharia militar do mundo, ainda que mais complexa e descontínua do que a imagem popular.',
    '**O Grande Canal:** a maior via de água artificial do mundo, ainda em parte navegável, que uniu o norte e o sul da China.',
    '**A Rota da Seda:** uma rede de trocas de bens, religiões, técnicas e ideias entre a China, a Ásia Central, a Índia, a Pérsia e o Mediterrâneo.',
    '**O dinheiro de papel e o comércio:** a China Song e Yuan deu ao mundo as primeiras notas e uma economia de mercado muito desenvolvida.'
  ] },
  { h: 'Património Mundial' },
  'A UNESCO inscreveu muitos dos lugares desta página: a **Grande Muralha** e a **Cidade Proibida** (1987), as **grutas de Mogao** (1987), **Yinxu** (2006), o **Lago Oeste** de Hangzhou (2011), o **Grande Canal** e os **sítios da Rota da Seda** no corredor Chang’an–Tianshan (2014, partilhado com o Cazaquistão e o Quirguistão), **Quanzhou** (2021) e o **Eixo Central de Pequim** (2024).',
  { h: 'Arte' },
  'A pintura de **Dunhuang**, os rolos como o de **Qingming**, a escultura de **Longmen** e as figuras de cerâmica **sancai** dos Tang são o retrato visual destas cidades e rotas. A poesia Tang está cheia de **passagens** e de despedidas na fronteira, como as de Wang Wei e de Li Bai.',
  { h: 'Arquitetura' },
  'Os palácios, as muralhas e os templos de madeira de Chang’an desapareceram, mas as plantas e os desenhos sobreviveram. O que se vê hoje em Pequim, em Xi’an e em Nanjing é sobretudo Ming. A tradição de construir com **madeira e consolas** manteve-se no Japão e na Coreia, onde se conservam alguns dos melhores exemplos de edifícios do estilo Tang.',
  { img: 'ccs-cidade-proibida', leg: 'A Cidade Proibida, Pequim: Pavilhão da Harmonia Suprema' },
  { h: 'A Rota da Seda hoje' },
  'O nome **«Rota da Seda»** foi popularizado pelo geógrafo alemão Ferdinand von Richthofen, em 1877. A China de hoje usa essa imagem na iniciativa **«Uma Faixa, Uma Rota»**, lançada em 2013, que investe em portos, estradas e caminhos-de-ferro por toda a Ásia, África e Europa. Os historiadores discutem as semelhanças e as diferenças entre a Rota da Seda histórica e este projeto.',
  { h: 'Portugal e a China pelo mar' },
  'A rota marítima descrita nesta página acabou por ser percorrida por navios portugueses: em **1513**, **Jorge Álvares** chegou à ilha de Tamão, no delta do Rio das Pérolas, e, a partir de cerca de **1557**, os portugueses estabeleceram-se em **Macau**, que se manteve ligada a Portugal até 1999. O **Museu do Oriente**, em Lisboa, e o Museu de Macau guardam testemunhos desse encontro.',
  { h: 'Redescoberta' },
  'Os estudos sobre as cidades chinesas começaram com os eruditos Song, que reuniram inscrições e bronzes, e foram retomados, no século XX, pela arqueologia. As escavações de **Chang’an** (desde 1957), de **Luoyang**, de **Anyang** (desde 1928), de **Dunhuang** e de **Quanzhou** mudaram o que sabemos. A **biblioteca escondida de Dunhuang** (1900) e as **tiras de madeira** da fronteira Han são das descobertas mais ricas.',
  { h: 'Onde visitar' },
  { lista: [
    '**Xi’an:** muralha Ming, Pagode do Grande Ganso Selvagem, Museu Beilin (estela nestoriana), Museu de História de Shaanxi, ruínas de Daming e de Weiyang.',
    '**Pequim:** Cidade Proibida, a torre do Tambor e a do Sino, as secções de Badaling, Mutianyu e Jinshanling da Grande Muralha, e o parque da muralha de terra de Dadu.',
    '**Luoyang e Kaifeng:** grutas de Longmen e templo do Cavalo Branco; Pagode de Ferro e o parque temático Qingming de Kaifeng.',
    '**Dunhuang:** grutas de Mogao, dunas de Mingsha e lago da Lua Crescente, e as ruínas da muralha Han e da passagem de Yumen.',
    '**Hangzhou, Quanzhou e Nanjing:** Lago Oeste e Grande Canal; mesquita de Qingjing, templo de Kaiyuan e museu marítimo; muralha Ming de Nanjing.',
    '**Em Portugal:** Museu do Oriente (Lisboa) e Museu de Macau, e as coleções de porcelana chinesa em muitos museus.'
  ] },
  { img: 'ccs-jiayuguan', leg: 'Fortaleza de Jiayuguan, extremo ocidental da Grande Muralha dos Ming' }
];

const quiz = [
  { p: 'O que significa a palavra chinesa «cheng» (城), que entra em «chengshi», «cidade»?', op: ['Mercado', 'Muralha e cidade', 'Rio', 'Palácio'], certa: 1, exp: 'Cheng significa «muralha» e «cidade»; shi quer dizer «mercado».' },
  { p: 'Qual é o sítio mais antigo onde se encontrou uma rede de ruas na China?', op: ['Chang’an', 'Kaifeng', 'Dadu', 'Erlitou'], certa: 3, exp: 'Erlitou (c. 1800 a.C.) tinha ruas de 10 a 20 m de largura, a mais antiga rede urbana conhecida.' },
  { p: 'Segundo o «Kaogong ji», quantas portas tinha cada lado da capital ideal?', op: ['Uma', 'Duas', 'Três', 'Nove'], certa: 2, exp: 'Um quadrado de nove li de lado, com três portas em cada lado e nove ruas em cada direção.' },
  { p: 'Que dinastia construiu a maior parte da Grande Muralha que hoje se visita?', op: ['Qin', 'Han', 'Tang', 'Ming'], certa: 3, exp: 'A muralha de tijolo e pedra de Pequim vem sobretudo dos Ming, séculos XV a XVII.' },
  { p: 'Qual destas afirmações sobre a Grande Muralha é um mito?', op: ['Foi construída por várias dinastias', 'Tem cerca de 21 000 km se contadas todas as épocas', 'É visível a olho nu da Lua', 'Tem torres de sinais'], certa: 2, exp: 'A muralha não se vê da Lua; da órbita baixa só em condições excecionais.' },
  { p: 'Qual era a função principal do Grande Canal?', op: ['Irrigar o deserto', 'Defender a fronteira', 'Separar a China dos nómadas', 'Transportar cereais do sul para o norte'], certa: 3, exp: 'O cereal do sul alimentava as capitais, o exército e a corte.' },
  { p: 'Quem mandou construir o Grande Canal, entre 605 e 611, à custa de enorme trabalho forçado?', op: ['Imperador Yang dos Sui', 'Kublai Khan', 'Wu Zetian', 'Zhu Yuanzhang'], certa: 0, exp: 'O imperador Yang uniu canais já existentes e abriu outros. Os Yuan refizeram-no mais tarde.' },
  { p: 'Quantos mercados oficiais tinha a Chang’an dos Tang?', op: ['Dois', 'Um', 'Quatro', 'Nenhum'], certa: 0, exp: 'Havia o Mercado Leste e o Mercado Oeste.' },
  { p: 'Que cidade, no tempo dos Song, quebrou as regras antigas e passou a ter mercados noturnos e lojas na rua?', op: ['Xianyang', 'Kaifeng', 'Anyang', 'Dunhuang'], certa: 1, exp: 'Kaifeng, onde o ritmo da rua e do comércio é descrito por Meng Yuanlao e pintado no rolo de Qingming.' },
  { p: 'Quem usou o nome «Rota da Seda» pela primeira vez, em 1877?', op: ['Marco Polo', 'Zhang Qian', 'Ferdinand von Richthofen', 'Xuanzang'], certa: 2, exp: 'O geógrafo alemão chamou-lhe «Seidenstrasse». Os antigos nunca usaram a expressão.' },
  { p: 'Quem eram os grandes intermediários da Rota da Seda entre os séculos IV e VIII?', op: ['Os romanos', 'Os vikings', 'Os incas', 'Os sogdianos'], certa: 3, exp: 'Os sogdianos, de Samarcanda, tinham comunidades em Dunhuang, Chang’an e Luoyang.' },
  { p: 'O que se descobriu em 1900 numa gruta de Mogao, em Dunhuang?', op: ['O Exército de Terracota', 'Uma biblioteca de cerca de 50 000 manuscritos', 'Os ossos oraculares', 'O túmulo de Fu Hao'], certa: 1, exp: 'Foi o monge Wang Yuanlu quem a encontrou; Stein e Pelliot compraram muitos documentos.' },
  { p: 'Que porto foi chamado «Zaitun» pelos viajantes árabes e inscrito pela UNESCO em 2021?', op: ['Guangzhou', 'Hangzhou', 'Quanzhou', 'Tianjin'], certa: 2, exp: 'Quanzhou, na costa de Fujian, foi um dos maiores portos do mundo nos séculos XI a XIV.' },
  { p: 'Qual foi a moeda chinesa mais característica durante mais de dois mil anos?', op: ['A moeda de bronze redonda com furo quadrado', 'A moeda de ouro', 'A nota de seda', 'A moeda de prata oval'], certa: 0, exp: 'Das banliang dos Qin às Kaiyuan tongbao dos Tang, o modelo manteve-se até ao século XX.' },
  { p: 'Quem é o imperador Ming que mudou a capital para Pequim e construiu a Cidade Proibida?', op: ['Zhu Yuanzhang', 'Kublai Khan', 'Yongle', 'Wu Di'], certa: 2, exp: 'Yongle (Zhu Di) transferiu a corte para Pequim, e a Cidade Proibida foi construída entre 1406 e 1420.' }
];

export default {
  id: 'china',
  cor: '#b83a3a',
  emblema: '../../assets/img/china.png',
  grupo: { ...GRUPO, aqui: 'cidades-rota-seda' },
  nome:    { pt: 'Cidades, muralhas e Rota da Seda', en: 'Cities, walls and the Silk Road' },
  periodo: { pt: 'c. 1800 a.C. – c. 1500 d.C.', en: 'c. 1800 BC – c. AD 1500' },
  visao:          { pt: visao, en: EN.visao },
  linha:          { pt: linha, en: EN.linha },
  mapa:           { pt: mapa, en: EN.mapa },
  sociedade:      { pt: sociedade, en: EN.sociedade },
  personalidades: { pt: personalidades, en: EN.personalidades },
  legado:         { pt: [...legado, ...CRED.pt], en: [...EN.legado, ...CRED.en] },
  quiz:           { pt: quiz, en: EN.quiz }
};
