// A REPÚBLICA TARDIA (264–27 a.C.) — conteúdo completo em português. A versão inglesa está em dados-en.js (mesma estrutura e mesmos ids de imagem).
// Cronologia: datas convencionais (anos a.C.); os dias exatos de batalhas e eventos seguem a tradição antiga (Políbio, Lívio, Apiano, Plutarco) e algumas são debatidas.
// Imagens: cada {img:'id'} procura o ficheiro  roma/republica-tardia/img/id.jpg  (ver IMAGENS_ROMA_REPUBLICA_TARDIA.md).
import EN from './dados-en.js';
import CRED from './creditos.js';
import { GRUPO } from '../grupo.js';

const visao = [
  { caixa: 'Em resumo', texto: [
    'Em 264 a.C., Roma era a senhora de toda a península italiana, mas ainda era uma potência regional. Em 27 a.C., quando Octaviano recebeu o nome de **Augusto**, Roma governava todo o Mediterrâneo, da Hispânia ao Egito e da Gália à Síria. Entre uma data e outra passaram-se 237 anos e uma das transformações mais rápidas e violentas da história antiga: a **República Tardia**.',
    'É a época das **Guerras Púnicas** contra Cartago (264–146 a.C.), da destruição de Cartago e de Corinto (146 a.C.), da conquista da Grécia, da Hispânia e do Oriente, dos irmãos **Gracos**, de **Mário** e **Sula**, de **Espártaco**, de **Pompeu**, **Crasso** e **César**, de **Cícero**, das guerras civis e, por fim, da batalha de **Áccio** (31 a.C.). Foi também o tempo em que as instituições da cidade-Estado deixaram de conseguir governar um império, e em que a República morreu, não de um só golpe, mas por desgaste.'
  ] },
  { img: 'rrt-mapa-expansao', leg: 'Mapa da República Romana em 44 a.C., no final da expansão republicana.' },
  { h: 'Onde e quando' },
  'A página começa onde acaba a de **Monarquia e República Antiga**: a derrota de Pirro (275 a.C.) e o domínio romano sobre a Itália. O seu ponto final é 27 a.C., quando o Senado conferiu a Octaviano o nome de Augusto: o ano que se toma, por convenção, como início do Principado (veja a página **O Alto Império**). Não é uma fronteira nítida: os contemporâneos não sabiam que a República tinha acabado, e o próprio Augusto apresentou o seu poder como a «restauração da República».',
  { tabela: { cab: ['Fase', 'Datas', 'Marcos principais'], linhas: [
    ['Guerras Púnicas e conquista do Mediterrâneo ocidental', '264 – 146 a.C.', '1.ª Guerra Púnica (264–241), Aníbal e a 2.ª (218–201), Zama (202), destruição de Cartago (146)'],
    ['Conquista do Oriente e da Hispânia', '215 – 133 a.C.', 'Guerras da Macedónia, Pidna (168), Corinto (146), Viriato (147–139), Numância (133)'],
    ['A crise: Gracos e Mário', '133 – 100 a.C.', 'Tibério e Caio Graco, guerra de Jugurta, cimbros e teutões, reformas de Mário'],
    ['Guerras civis de Sula', '91 – 78 a.C.', 'Guerra Social, Mitridates, marcha sobre Roma, proscrições, ditadura de Sula'],
    ['A era de Pompeu e Cícero', '78 – 60 a.C.', 'Sertório, Espártaco, piratas, conquista do Oriente, conjura de Catilina'],
    ['César e as guerras civis', '60 – 44 a.C.', 'Triunvirato, Gália, Rubicão, Fársalo, ditadura, Idos de Março'],
    ['O fim da República', '44 – 27 a.C.', 'Segundo Triunvirato, Filipos, António e Cleópatra, Áccio, Augusto']
  ] } },
  { h: 'Como era a República' },
  'A República romana não tinha constituição escrita. Funcionava com **magistrados eleitos por um ano** (dois **cônsules** à cabeça, depois pretores, edis e questores), com os **tribunos da plebe** (que podiam vetar medidas), com as assembleias do povo e, sobretudo, com o **Senado**, um conselho vitalício de ex-magistrados, que dominava a política externa, as finanças e a religião. Era um sistema pensado para impedir que um só homem tivesse poder demais. Funcionou enquanto Roma foi uma cidade-Estado que fazia guerra durante a primavera e o verão. Deixou de funcionar quando os generais passaram anos longe, a comandar exércitos leais mais a eles do que ao Estado.',
  { img: 'rrt-forum-romano', leg: 'Fórum Romano, vista das ruínas atuais.' },
  { h: 'Porque importam estes dois séculos' },
  { lista: [
    '**A forma como se faz um império:** províncias, governadores, impostos, cobradores privados (os publicanos), escravos em massa, estradas e colónias: um modelo que durou séculos e que a Europa estudou e imitou.',
    '**O debate sobre o poder:** a ideia de um governo misto, de separação de poderes, de mandatos limitados, e o medo do «tirano», passou da Roma republicana a Maquiavel, aos Pais Fundadores dos Estados Unidos e à Revolução Francesa.',
    '**Palavras e instituições:** «senado», «cônsul», «veto», «ditador», «candidato», «campanha», «república» (*res publica*, «coisa pública»).',
    '**A literatura:** Cícero, César, Lucrécio, Catulo, Salústio, Plauto e Terêncio escreveram em latim obras que se leem até hoje.',
    '**Portugal:** foi nesta época que os romanos chegaram ao território do atual Portugal e que Viriato lhes resistiu.'
  ] },
  { img: 'rrt-triunfo-republicano', leg: 'Ilustração gerada por IA. Triunfo romano na República Tardia, c. 60 a.C.; cena interpretativa.' },
  { h: 'Uma história com muitas fontes, e todas com autor' },
  'Quase tudo o que sabemos desta época vem de autores antigos com posição própria. **Políbio** (grego, refém em Roma, testemunha de Cartago e de Corinto) é o historiador mais fiável da expansão. **Lívio** (escreveu já no tempo de Augusto) conta as guerras com talento e com patriotismo. **Salústio** foi partidário de César. **César** escreveu os seus próprios Comentários, que são também propaganda. **Cícero** deixou centenas de cartas e discursos, que mostram a política por dentro. **Apiano** e **Plutarco** escreveram séculos depois, mas com fontes que perdemos. Sempre que um número ou uma data vem de uma fonte antiga e é duvidoso, esta página di-lo.',
  { h: 'Hoje' },
  'A República Tardia é talvez o período mais estudado da Antiguidade pela política: a polarização, o recurso à violência, o uso do dinheiro para comprar votos, a erosão das normas, o general popular que desafia o Senado. Mas convém não forçar paralelos. Roma era uma sociedade escravista, em que votava uma minoria de homens livres; a sua «democracia» era limitada e fortemente enviesada a favor dos ricos. O que torna a história tão instrutiva não é o paralelo com o presente, é a lentidão com que as instituições se foram esvaziando.'
];

const linha = [
  'Esta linha do tempo segue 237 anos de história. As datas são as convencionais, em anos a.C.; para os dias exatos usa-se o calendário romano da época, que antes da reforma de César (46 a.C.) não coincidia bem com as estações. Os números de efetivos e de baixas vêm de fontes antigas e são, em geral, exagerados ou incertos.',
  { linha: [
    { d: '264 a.C.', t: 'Início da 1.ª Guerra Púnica', x: 'Mercenários campânios (os mamertinos) ocupam Messina, na Sicília, e pedem ajuda a Roma contra Siracusa e Cartago. Roma envia tropas para fora da Itália pela primeira vez, e entra em guerra com Cartago, a grande potência naval. Segundo a tradição, é também o ano dos primeiros combates de gladiadores em Roma, num funeral.' },
    { d: '260 a.C.', t: 'Roma constrói uma frota e vence em Milas', x: 'Segundo Políbio, os romanos copiaram um navio cartaginês capturado, construíram cerca de 100 quinquerremes e inventaram o *corvus*, uma ponte com gancho que transformava o combate naval num combate de infantaria. A vitória de Gaio Duílio em Milas foi a primeira grande vitória naval romana.' },
    { d: '241 a.C.', t: 'Fim da 1.ª Guerra Púnica', x: 'Depois de vinte e três anos, a vitória nas ilhas Égadas obriga Cartago a pedir a paz: abandona a Sicília e paga uma pesada indemnização. A Sicília torna-se a primeira **província** romana (a Sardenha e a Córsega seguem-se por volta de 238–227 a.C.).' },
    { d: '218 a.C.', t: 'Aníbal atravessa os Alpes', x: 'Depois de tomar Sagunto, na Hispânia (219), Aníbal parte de Cartagena e leva um exército, com elefantes, pelos Pirenéus, pelo Ródano e pelos Alpes, para invadir a Itália. Vence os romanos no Ticino e no Trebbia. Os números exatos do exército variam consoante a fonte.' },
    { d: '216 a.C.', t: 'Cannas', x: 'Em Cannas, na Apúlia, o exército cartaginês cerca e destrói as legiões romanas: as fontes antigas dão entre c. 48 000 e 70 000 mortos romanos, e vários milhares de prisioneiros (Políbio fala de cerca de 10 000). É uma das maiores derrotas da história de Roma. Mas os aliados da Itália central mantêm-se, na maioria, fiéis, e Roma recusa negociar.' },
    { d: '212 – 211 a.C.', t: 'Siracusa e Cápua', x: 'Os romanos tomam Siracusa, depois de um longo cerco; o sábio **Arquimedes** morre no saque (a versão do soldado que o mata é tradição). Em 211, Cápua, a grande cidade que passara para Aníbal, rende-se e é severamente punida.' },
    { d: '209 – 206 a.C.', t: 'Cipião conquista a Hispânia cartaginesa', x: 'Públio Cornélio Cipião, que viria a ser chamado «o Africano», toma de surpresa Cartagena (Carthago Nova) em 209 e vence em Ilipa (206). Os cartagineses são expulsos da Hispânia: começa a presença romana de mais de seis séculos na Península. Em 206 funda-se Itálica, perto de Sevilha.' },
    { d: '202 a.C.', t: 'Zama', x: 'Cipião desembarca em África e vence Aníbal em Zama. A paz de 201 reduz Cartago a uma cidade sem império e sem frota. Aníbal governa a cidade durante alguns anos e acabará por morrer no exílio, na Bitínia, por volta de 183 a.C.' },
    { d: '197 – 168 a.C.', t: 'As guerras do Oriente', x: 'Roma derrota Filipe V da Macedónia em Cinoscéfalas (197); em 196, Flaminino proclama a «liberdade dos Gregos». Antíoco III, da Síria, é vencido em Magnésia (190). Em Pidna (168), Paulo Emílio derrota Perseu, o último rei da Macedónia; a Macedónia é dividida em quatro repúblicas.' },
    { d: '155 – 139 a.C.', t: 'Guerra lusitana e Viriato', x: 'Os lusitanos, entre o Tejo e o Douro, resistem a Roma. Por volta de 150, o governador Sérvio Galba mata à traição milhares de lusitanos. **Viriato**, que escapou, lidera a resistência de c. 147 a 139 a.C., até ser assassinado por três companheiros subornados pelo cônsul Servílio Cepião.' },
    { d: '149 – 146 a.C.', t: 'Terceira Guerra Púnica; Cartago e Corinto destruídas', x: 'Depois de anos de pressão (a tradição atribui a Catão, o Velho, o refrão «Cartago deve ser destruída»), Roma ataca Cartago. Cipião Emiliano toma-a em 146. A cidade é arrasada e as suas terras tornam-se a província de **África**. No mesmo ano, Múmio destrói Corinto e a Grécia fica sob controlo romano. (O sal lançado sobre as terras de Cartago é uma invenção moderna.)' },
    { d: '133 a.C.', t: 'Numância e Pérgamo; Tibério Graco', x: 'Cipião Emiliano toma Numância, depois de vários anos de guerra na Celtibéria. O rei Átalo III lega o reino de Pérgamo a Roma (a província da Ásia nasce por volta de 129). Em Roma, o tribuno Tibério Graco propõe uma reforma agrária e é assassinado por senadores, numa das primeiras mortes políticas violentas da República.' },
    { d: '123 – 121 a.C.', t: 'Caio Graco', x: 'O irmão de Tibério, eleito tribuno duas vezes, propõe leis sobre trigo, tribunais, colónias e cidadania. Em 121, o Senado aprova o decreto de emergência (*senatus consultum ultimum*) e Caio morre com milhares de apoiantes. Por volta de 121–118 nasce a Gália Transalpina (o futuro Narbonense).' },
    { d: '112 – 105 a.C.', t: 'Guerra contra Jugurta', x: 'O rei númida Jugurta compra senadores e derrota generais. Gaio Mário, um «homem novo», é eleito cônsul em 107 e acaba a guerra com a ajuda de Sula, o seu questor. A guerra revelou a corrupção da elite e a força de um general popular.' },
    { d: '105 – 101 a.C.', t: 'Cimbros e teutões; as reformas de Mário', x: 'Tribos germânicas derrotam Roma em Arausio (105), uma das piores derrotas desde Cannas. Mário, cônsul seguido (104–100), reorganiza o exército e vence-os em Aquae Sextiae (102) e Vercelas (101). A partir de então os legionários são recrutados também entre os pobres e dependem do general para as terras de reforma.' },
    { d: '91 – 88 a.C.', t: 'Guerra Social', x: 'Os aliados italianos, que combatiam por Roma mas não eram cidadãos, rebelam-se. Roma cede: a lei Júlia (90) e outras estendem a cidadania aos italianos que não se tinham rebelado ou que se rendessem, e, em poucos anos, à maior parte da Itália.' },
    { d: '88 – 82 a.C.', t: 'Mitridates, Sula e a guerra civil', x: 'Mitridates VI do Ponto invade a Ásia, e em 88 manda massacrar os romanos e italianos da província (as fontes falam de 80 000 mortos, número que se discute). Sula, cônsul, marcha sobre Roma com o seu exército (88), pela primeira vez na história da cidade. Segue-se uma guerra civil com Mário e Cina; Sula vence na Porta Colina (82).' },
    { d: '82 – 79 a.C.', t: 'A ditadura de Sula', x: 'Sula faz-se nomear ditador «para escrever leis e reorganizar a República», proscreve os inimigos (listas de nomes cujos bens eram confiscados e cujos assassinos eram recompensados), reforça o Senado e limita os tribunos. Em 79 abdica, caso raro na história, e morre em 78.' },
    { d: '73 – 71 a.C.', t: 'A revolta de Espártaco', x: 'Escravos fugidos de uma escola de gladiadores, em Cápua, formam um exército de dezenas de milhares (Apiano fala de c. 120 000, número duvidoso). Derrotam várias legiões. Crasso vence-os em 71; seis mil prisioneiros são crucificados ao longo da Via Ápia, segundo Apiano.' },
    { d: '67 – 63 a.C.', t: 'Pompeu no Oriente; Cícero cônsul', x: 'Pompeu recebe poderes extraordinários para eliminar os piratas do Mediterrâneo (67) e depois para vencer Mitridates (66). Reorganiza o Oriente: a Síria torna-se província (64) e ele toma Jerusalém (63). Em Roma, Cícero, cônsul em 63, denuncia a conjura de Catilina.' },
    { d: '60 – 53 a.C.', t: 'O Primeiro Triunvirato', x: 'César, Pompeu e Crasso fazem um acordo político privado (nunca teve base legal, e a palavra «triunvirato» é moderna). César é cônsul em 59 e depois governador da Gália. Julia, filha de César e mulher de Pompeu, morre em 54; Crasso morre em Carras (53), derrotado pelos partas.' },
    { d: '58 – 50 a.C.', t: 'A conquista da Gália', x: 'César conquista a Gália e escreve os *Comentários à Guerra da Gália*. Atravessa o Reno e o canal da Mancha (55 e 54). Em 52, cerca Vercingetórix em Alésia, com duas linhas de fortificações, numa das grandes operações de cerco da Antiguidade.' },
    { d: '49 a.C.', t: 'O Rubicão', x: 'Quando o Senado lhe ordena que desmobilize, César atravessa o Rubicão, o rio que marcava o limite da sua província, com uma legião (10 ou 11 de janeiro). A frase «a sorte está lançada» é tradição, e a forma exata varia. Pompeu e a maioria do Senado deixam a Itália.' },
    { d: '48 – 45 a.C.', t: 'Fársalo, Tapso, Munda', x: 'César vence Pompeu em Fársalo, na Grécia, em 48; Pompeu é assassinado ao chegar ao Egito. César fica em Alexandria com Cleópatra e derrota os pompeianos em Tapso (46) e Munda, na Hispânia (45). Em 46 reforma o calendário.' },
    { d: '44 a.C.', t: 'Os Idos de Março', x: 'Nomeado ditador perpétuo em fevereiro, César é assassinado a 15 de março, por mais de sessenta conspiradores, entre eles Bruto e Cássio, numa reunião do Senado na Cúria de Pompeu. Não tinham plano para o dia seguinte.' },
    { d: '43 – 42 a.C.', t: 'O Segundo Triunvirato e Filipos', x: 'Octaviano, Marco António e Lépido recebem poderes legais por cinco anos e proscrevem milhares de inimigos, entre eles Cícero, morto em dezembro de 43. Em 42, em Filipos, na Macedónia, vencem Bruto e Cássio, que se suicidam.' },
    { d: '31 – 30 a.C.', t: 'Áccio e Alexandria', x: 'A 2 de setembro de 31, a frota de Octaviano, comandada por Agripa, vence a de António e Cleópatra em Áccio, na Grécia. No verão de 30, Octaviano entra em Alexandria; António e Cleópatra suicidam-se. O Egito torna-se uma posse pessoal do futuro imperador.' },
    { d: '27 a.C.', t: 'Octaviano torna-se Augusto', x: 'A 13 de janeiro, Octaviano declara que devolve o poder ao Senado e ao povo; o Senado dá-lhe províncias importantes com a maior parte das legiões e, a 16 de janeiro, o nome de **Augusto**. Começa o Principado: a República, na forma, continua; na realidade, acabou.' }
  ] },
  { img: 'rrt-mapa-guerras-punicas', leg: 'Mapa das batalhas e do percurso de Aníbal na Segunda Guerra Púnica.' },
  { img: 'rrt-galera-corvus', leg: 'Ilustração gerada por IA. Batalha naval da Primeira Guerra Púnica, c. 260 a.C.: abordagem com o corvus; interpretação conjetural.' },
  { img: 'rrt-anibal-busto', leg: 'Fotografia histórica do busto de Cápua tradicionalmente atribuído a Aníbal, Museu Arqueológico Nacional de Nápoles. A identificação é incerta.' },
  { img: 'rrt-canas-batalha', leg: 'Ilustração gerada por IA. Batalha de Canas, 216 a.C.; interpretação panorâmica.' },
  { img: 'rrt-denario-idos-marco', leg: 'Denário de prata de Bruto com a legenda EID MAR, 42 a.C., Museu Britânico (1860,0328.124).' }
];

const mapa = [
  'A República Tardia mede-se em mapas: cada conquista é uma província, cada província é uma fonte de impostos, escravos e rivalidade entre generais. Esta secção apresenta as cidades, os campos de batalha e as rotas que contam a história de 264 a 27 a.C., e a ligação de tudo isto ao território de Portugal.',
  { tabela: { cab: ['Cidade', 'Nome latino / antigo', 'Papel na República Tardia', 'Local hoje'], linhas: [
    ['Roma', 'Roma', 'Capital, sede do Senado e das assembleias; entre 500 000 e 1 milhão de habitantes no fim do período (estimativa muito debatida)', 'Roma, Itália'],
    ['Cartago', 'Karthago', 'Grande potência marítima, rival de Roma; destruída em 146 a.C. e refundada por César e Augusto', 'Cartago, Tunísia'],
    ['Siracusa', 'Syracusae', 'Principal cidade grega da Sicília; tomada em 212 a.C.', 'Siracusa, Sicília'],
    ['Cápua', 'Capua', 'Cidade campânia, passou para Aníbal e foi punida; escola de gladiadores de Espártaco', 'Santa Maria Capua Vetere, Itália'],
    ['Cartagena', 'Carthago Nova', 'Base cartaginesa na Hispânia, tomada por Cipião em 209 a.C.', 'Cartagena, Espanha'],
    ['Numância', 'Numantia', 'Cidade celtibera, tomada em 133 a.C. depois de longo cerco', 'Garray, Soria, Espanha'],
    ['Corinto', 'Corinthus', 'Cidade grega destruída em 146 a.C.; refundada por César em 44', 'Corinto, Grécia'],
    ['Pérgamo', 'Pergamum', 'Reino legado a Roma em 133 a.C. (província da Ásia)', 'Bergama, Turquia'],
    ['Massília', 'Massalia', 'Cidade grega, aliada de Roma, que apoiou Pompeu e foi tomada por César em 49', 'Marselha, França'],
    ['Alésia', 'Alesia', 'Último reduto de Vercingetórix, 52 a.C.', 'Alise-Sainte-Reine, França'],
    ['Alexandria', 'Alexandria', 'Capital do Egito ptolemaico, cenário da guerra entre César e Cleópatra', 'Alexandria, Egito'],
    ['Olisipo', 'Olisipo', 'Povoado lusitano às margens do Tejo; tornou-se mais tarde Felicitas Iulia (data debatida)', 'Lisboa, Portugal']
  ] } },
  { img: 'rrt-cartago-ruinas', leg: 'Termas de Antonino em Cartago, Tunísia.' },
  { h: 'Roma e a Itália' },
  'No centro do mapa está **Roma**, uma cidade com colinas, um rio, um Fórum de ruas estreitas, o Capitólio com o seu templo de Júpiter e, na planície, o Campo de Marte, onde se reuniam as assembleias e o exército. A sua rede de **estradas** (a Via Ápia, a Via Flamínia, a Via Emília) ligava a capital à Itália e permitia mover legiões. A península estava dividida entre cidadãos romanos, **colónias latinas** e **aliados** (os *socii*), que forneciam soldados. Foi esta rede de aliados que deu a Roma a reserva de homens para vencer Aníbal.',
  { img: 'rrt-via-appia', leg: 'Via Ápia Antiga com pavimento de basalto.' },
  { h: 'Cartago e o norte de África' },
  'Fundada, segundo a tradição, por colonos de Tiro no século IX a.C. (a data tradicional é 814 a.C.), **Cartago** dominava o comércio do Mediterrâneo ocidental, com um porto circular para a marinha de guerra. Foi derrotada na Primeira Guerra Púnica, perdeu a Sicília e, depois de Zama, perdeu todo o império. Em 146 a.C. foi tomada, saqueada e arrasada; os seus habitantes vendidos como escravos. A região tornou-se a província romana de **África**, uma das principais fontes de trigo de Roma. A cidade foi refundada como colónia romana por César (planos de 44 a.C.) e por Augusto, e voltaria a ser uma grande cidade.',
  { h: 'A Sicília: o primeiro laboratório do império' },
  'A **Sicília**, a primeira província (c. 241 a.C.), tornou-se o celeiro de Roma e o exemplo de como se governava um território conquistado: com um governador, cobradores de impostos que cobravam o dízimo sobre as colheitas e uma administração local que se aproveitava das cidades gregas. Em 70 a.C., o processo de Cícero contra **Verres**, governador acusado de roubar a província, mostrou com detalhe os abusos possíveis. Foi também na Sicília que rebentaram, em 135–132 e em 104–100 a.C., as duas primeiras grandes revoltas de escravos.',
  { h: 'A Hispânia e o território de Portugal' },
  'A Hispânia foi o primeiro grande território continental conquistado fora da Itália em que Roma ficou até ao fim do Império do Ocidente. Depois da expulsão dos cartagineses (206 a.C.) criaram-se duas províncias, a **Hispânia Citerior** e a **Ulterior** (197 a.C.). O interior e o noroeste resistiram durante mais de um século: as guerras celtiberas (181–133 a.C.), terminadas com a queda de **Numância**, e as guerras lusitanas. O território do atual Portugal estava dividido entre muitos povos (lusitanos, galaicos, cónios, célticos); os romanos chegaram a sul do Tejo, e só no tempo de Augusto se completou a conquista do noroeste.',
  { img: 'rrt-numancia-ruinas', leg: 'Ruínas de Numância, Garray, Soria.' },
  { h: 'Viriato e a Lusitânia' },
  '**Viriato** é o primeiro grande vulto da história do território português. Segundo as fontes (Apiano, Diodoro), era um pastor, depois caçador e chefe de bandos, que se tornou o líder dos lusitanos depois do massacre de Galba (c. 150 a.C.). Durante cerca de oito anos venceu exércitos romanos com emboscadas e guerra de movimento, e chegou a impor um tratado a Roma (c. 141 a.C.), que Roma depois rompeu. Foi assassinado, em 139 a.C., por três companheiros, **Audax**, **Ditalcão** e **Minuro**, subornados pelo cônsul Cepião; os romanos recusaram-lhes a recompensa prometida. Em 138–136 a.C., **Décimo Júnio Bruto** fez campanha até ao Douro e à Galécia; segundo Estrabão, terá fortificado Olisipo e a linha do Tejo. A localização do «monte de Vénus» e de outros lugares é muito debatida.',
  { img: 'rrt-viriato-viseu', leg: 'Monumento a Viriato em Viseu, de Mariano Benlliure, inaugurado em 1940.' },
  { h: 'Sertório, César e o fim da conquista' },
  'Na década de 70 a.C., a Hispânia foi o palco da guerra de **Sertório**, que reuniu lusitanos e celtiberos contra o governo de Sula. Em 61–60 a.C., **César**, propretor da Ulterior, fez campanha contra tribos lusitanas, nas serras Hermínias (identificadas habitualmente com a serra da Estrela) e foi pelo mar até Brigantium (Corunha). Por esta época, ou pouco depois, surgem as ligações de **Olisipo** (Lisboa, *Felicitas Iulia*), de **Pax Iulia** (Beja) e de Scallabis (Santarém, *Praesidium Iulium*) aos Júlios: se foi César ou Augusto que lhes deu estes nomes é debatido.',
  { h: 'O Oriente grego' },
  'A conquista do Oriente fez-se contra reinos helenísticos já enfraquecidos: a Macedónia (derrotada em Cinoscéfalas, 197, e em Pidna, 168), a Síria de Antíoco III (Magnésia, 190), o Ponto de Mitridates VI. A cada vitória, Roma proclamava a «liberdade» das cidades gregas e, pouco depois, impunha tutela. Em **Corinto**, em 146, destruiu uma cidade e os seus tesouros (estátuas, quadros) foram levados para Roma. O Egito dos Ptolemeus, ainda independente, tornou-se dependente da proteção romana.',
  { img: 'rrt-corinto-templo', leg: 'Templo arcaico de Apolo, Corinto antiga.' },
  { h: 'A Gália' },
  'Até 58 a.C. Roma controlava apenas o sul da Gália (a Gália Narbonense, a «Província»). Em oito anos, César conquistou o resto: os helvécios, os belgas, os vénetos, os aquitanos, e invadiu a Germânia e a Britânia (55–54). A grande revolta de **Vercingetórix**, chefe dos arvernos, terminou em Alésia (52 a.C.). Os números das fontes (c. 1 milhão de mortos e outro de escravos, segundo Plutarco) são muito exagerados, mas o impacto foi enorme.',
  { img: 'rrt-mapa-galia-cesar', leg: 'Mapa da Gália durante as campanhas de César, 58–50 a.C.' },
  { img: 'rrt-vercingetorix', leg: 'Monumento a Vercingetórix, Aimé Millet, 1865; Alise-Sainte-Reine.' },
  { img: 'rrt-alesia-cerco', leg: 'Ilustração gerada por IA. Cerco de Alésia, 52 a.C.; reconstituição conjetural das fortificações.' },
  { h: 'Roma por dentro: o Fórum e a Cúria de Pompeu' },
  'Os eventos decisivos tiveram lugares precisos. No **Fórum** discursavam os tribunos; Tibério Graco foi morto junto ao Capitólio e Caio nas margens do Tibre; os proscritos de Sula e de António tiveram as cabeças exibidas na Tribuna (a de Cícero foi pregada nos Rostros). Em 55 a.C., Pompeu inaugurou o primeiro teatro de pedra de Roma, no Campo de Marte; no complexo ficava uma sala de reuniões, a **Cúria de Pompeu**, onde, a 15 de março de 44 a.C., César foi assassinado. As suas ruínas ficam na atual Largo di Torre Argentina, entre os templos republicanos da zona.',
  { img: 'rrt-largo-argentina', leg: 'Largo di Torre Argentina, Roma, templos republicanos junto da área da Cúria de Pompeu.' },
  { h: 'Os campos de batalha das guerras' },
  { tabela: { cab: ['Batalha', 'Ano', 'Adversários', 'Local hoje'], linhas: [
    ['Trebbia', '218 a.C.', 'Aníbal contra o cônsul Semprónio Longo', 'Norte de Itália'],
    ['Lago Trasimeno', '217 a.C.', 'Aníbal contra Flamínio', 'Úmbria, Itália'],
    ['Cannas', '216 a.C.', 'Aníbal contra Varrão e Paulo Emílio', 'Apúlia, Itália'],
    ['Zama', '202 a.C.', 'Cipião contra Aníbal', 'Tunísia (local exato debatido)'],
    ['Pidna', '168 a.C.', 'Paulo Emílio contra Perseu da Macedónia', 'Norte da Grécia'],
    ['Aquae Sextiae', '102 a.C.', 'Mário contra os teutões', 'Aix-en-Provence, França'],
    ['Vercelas', '101 a.C.', 'Mário e Cátulo contra os cimbros', 'Norte de Itália (local debatido)'],
    ['Porta Colina', '82 a.C.', 'Sula contra os samnitas e os marianos', 'Roma'],
    ['Carras', '53 a.C.', 'Os partas contra Crasso', 'Sudeste da Turquia'],
    ['Alésia', '52 a.C.', 'César contra Vercingetórix', 'França'],
    ['Fársalo', '48 a.C.', 'César contra Pompeu', 'Tessália, Grécia'],
    ['Filipos', '42 a.C.', 'Octaviano e António contra Bruto e Cássio', 'Macedónia, Grécia'],
    ['Áccio', '31 a.C.', 'Octaviano e Agripa contra António e Cleópatra', 'Costa ocidental da Grécia']
  ] } },
  { h: 'Rotas e fronteiras' },
  'O mapa da República Tardia é o de um império marítimo. O **mar** era a grande estrada: o trigo da Sicília, do Egito e de África chegava a Óstia e a Pozzuoli; as legiões atravessavam o Adriático por Brundísio. As **estradas** romanas faziam o resto: a Via Ápia (para o sul), a Via Flamínia (para o Adriático), a Via Emília (para o vale do Pó), a Via Domícia (para a Gália e a Hispânia, c. 118 a.C.) e a Via Egnácia (pela Macedónia, séc. II a.C.). Ainda não havia fronteira fixa ou «limes»: Roma tinha províncias e zonas de influência, e a sua fronteira era onde as legiões chegavam.'
];

const sociedade = [
  'Esta secção descreve como se governava, como se vivia e como se combatia na República Tardia: instituições, classes sociais, religião, economia, escravatura, quotidiano, ciência, técnica e exército. Em muitos aspetos Roma mudou muito entre 264 e 27 a.C.; sempre que possível, a data da mudança é indicada.',
  { h: 'O Senado e os magistrados' },
  'O **Senado** tinha 300 membros, na prática vitalícios (Sula alargou-o para 600, César para 900). Não fazia leis, mas aconselhava os magistrados, controlava as finanças, a política externa e a religião, e distribuía as províncias. Os **magistrados** eram eleitos por um ano: 2 **cônsules** (chefes do Estado e do exército), os **pretores** (justiça e governo das províncias), os **edis** (obras públicas, mercados e jogos), os **questores** (finanças) e os **censores** (recenseamento e moralidade, eleitos cada cinco anos). Os dez **tribunos da plebe** protegiam os cidadãos comuns e podiam vetar as decisões de outros magistrados. A carreira seguia uma ordem fixa, o **cursus honorum**, com idades mínimas definidas por lei em 180 a.C. (a *lex Villia annalis*).',
  { h: 'As assembleias e o voto' },
  'Os cidadãos votavam em assembleias: nos **comícios centuriados** (organizados por classes de riqueza, onde os ricos votavam primeiro e muitas vezes decidiam) elegiam-se cônsules e pretores; nos **comícios tribais**, os tribunos, edis e questores, e votavam-se leis. Para votar, era preciso estar em Roma, o que excluía a maioria dos cidadãos da Itália. O voto foi tornado secreto por leis entre 139 e 107 a.C. A corrupção eleitoral (compra de votos, distribuição de cereais e jogos) era corrente e levou a várias leis que quase nunca se cumpriram.',
  { h: 'Optimates e populares' },
  'Os historiadores falam de duas tendências: os **optimates** («os melhores»), que defendiam o poder do Senado, e os **populares**, que apelavam ao povo contra o Senado, em geral através dos tribunos e das assembleias. Não eram partidos organizados, mas métodos: Tibério Graco, Mário e César usaram a via popular, Sula e Catão a via senatorial. Quase todos eram aristocratas ricos. As lutas eram sobre o poder, a terra e as províncias, mais do que sobre ideologia.',
  { img: 'rrt-comicios', leg: 'Ilustração gerada por IA. Votação no Campo de Marte, c. 70 a.C.; cena interpretativa.' },
  { h: 'A sociedade: ordens e classes' },
  { lista: [
    '**Senadores:** a elite, com fortunas em terras; proibidos, por uma lei de c. 218 a.C., de ter navios comerciais de mar alto.',
    '**Cavaleiros (*equites*):** a segunda ordem, de ricos. Muitos eram os **publicanos**, empresários que arrematavam, por contrato com o Estado, a cobrança de impostos, as minas e as obras públicas.',
    '**Plebe:** os cidadãos comuns: camponeses, artesãos, pequenos comerciantes e, cada vez mais, desempregados nas cidades. A plebe urbana dependia de distribuição de trigo, pelo menos desde as leis de Caio Graco (123 a.C.).',
    '**Aliados italianos e latinos:** não eram cidadãos romanos, até 90–88 a.C.; pagavam impostos de guerra e forneciam metade do exército.',
    '**Libertos:** antigos escravos libertados, que se tornavam cidadãos, mas sem acesso a magistraturas; os filhos dos libertos eram livres de pleno direito.',
    '**Escravos:** sem direitos, propriedade do dono, que podia vendê-los, castigá-los e libertá-los.'
  ] },
  { h: 'Clientela e família' },
  'A sociedade romana funcionava por **relações pessoais**. Cada poderoso (o *patronus*) tinha clientes que o saudavam de manhã, o apoiavam nos votos e recebiam proteção e favores. A unidade básica era a **família** (*familia*), dirigida pelo *pater familias*, com poder legal sobre filhos, mulher (consoante o tipo de casamento), escravos e bens. As mulheres não votavam nem ocupavam cargos, mas as das famílias ricas administravam bens e exerciam influência política; a mãe dos Gracos, **Cornélia**, ficou como modelo, e **Fúlvia**, mulher de Clódio e depois de António, foi uma figura política de peso.',
  { h: 'A terra, os camponeses e os latifúndios' },
  'Foi o problema social central. As guerras longas tiraram camponeses das suas terras durante anos e as terras conquistadas, o *ager publicus*, foram ocupadas pelos ricos. Nasceram **latifúndios** trabalhados por escravos e os camponeses empobrecidos migraram para Roma. Foi a este problema que Tibério Graco tentou responder em 133 a.C., com uma lei que limitava a terra pública que um indivíduo podia ocupar (cerca de 500 *iugera*). A resistência a esta lei começou a série de crises violentas.',
  { h: 'A escravatura' },
  'A conquista fez entrar em Itália um número enorme de escravos: prisioneiros de guerra (150 000 do Épiro, em 167 a.C., segundo as fontes, mas o número discute-se), vítimas de piratas, filhos de escravas. As estimativas modernas para a Itália do século I a.C. são muito debatidas, mas a escravatura era um traço central da economia, e talvez 20 a 30% da população. As condições eram mais duras nas minas e nos campos do que nas casas. Houve três grandes revoltas: duas na Sicília (135–132 e 104–100 a.C.) e a de **Espártaco** (73–71 a.C.). Todas foram esmagadas com violência.',
  { img: 'rrt-escravos-minas', leg: 'Ilustração gerada por IA. Trabalho de adultos escravizados numa mina de prata da Hispânia, século II a.C.; cena interpretativa.' },
  { h: 'A religião do Estado' },
  'A religião romana era uma relação contratual com os deuses, a *pax deorum*: o Estado fazia os ritos exatos e os deuses davam proteção. Os **sacerdócios** (pontífices, áugures, vestais, flâmines) eram cargos políticos disputados por senadores: César foi eleito Pontífice Máximo em 63 a.C. Antes de decisões importantes consultavam-se os auspícios (voo das aves, apetite dos frangos sagrados). Os romanos importaram deuses: **Cibele**, a Grande Mãe, foi trazida da Ásia Menor em 204 a.C., em plena guerra com Aníbal; em 186 a.C. o Senado reprimiu duramente o culto de Baco (as *Bacanais*). Em momentos de crise extrema, as fontes referem sacrifícios humanos de dois gregos e dois gauleses, enterrados vivos (em 228, 216 e 114 a.C.).',
  { tabela: { cab: ['Deus', 'Equivalente grego', 'Domínio', 'Notas'], linhas: [
    ['Júpiter', 'Zeus', 'Céu, raio, juramento', 'Templo no Capitólio, com Juno e Minerva (a Tríade Capitolina)'],
    ['Juno', 'Hera', 'Mulheres, casamento', 'Protetora do Estado'],
    ['Minerva', 'Atena', 'Sabedoria, ofícios', 'Terceira da Tríade'],
    ['Marte', 'Ares', 'Guerra', 'Pai mítico de Rómulo; o Campo de Marte leva o seu nome'],
    ['Vénus', 'Afrodite', 'Amor, vitória', 'Antepassada mítica dos Júlios; César dedicou-lhe um templo em 46 a.C.'],
    ['Vesta', 'Héstia', 'Lar da cidade', 'Fogo sagrado mantido pelas vestais'],
    ['Ceres', 'Deméter', 'Cereais, colheitas', 'Ligada à plebe e ao fornecimento de trigo'],
    ['Cibele (Magna Mater)', 'Cibele', 'Grande Mãe', 'Culto importado da Frígia em 204 a.C.'],
    ['Janus', 'Sem equivalente', 'Começos e passagens', 'Deus de duas faces; dá nome a janeiro']
  ] } },
  { h: 'Economia: tributos, minas e comércio' },
  'A guerra foi o motor da economia: os despojos, as indemnizações e os tributos das províncias enriqueceram o Estado e a elite. Depois da vitória sobre a Macedónia, em 167 a.C., os cidadãos romanos deixaram de pagar imposto direto, até 43 a.C. Os **publicanos** cobravam os impostos das províncias (o dízimo na Sicília, os impostos da Ásia desde 123 a.C.) e muitas vezes abusavam. A Hispânia dava prata e outros metais (as minas de Cartagena, por exemplo, empregavam dezenas de milhares de trabalhadores, segundo Políbio). O comércio marítimo cresceu, com o trigo de Sicília, de África e do Egito, o vinho e o azeite de Itália, e os portos de Pozzuoli e de Óstia.',
  { h: 'Moeda' },
  'O sistema monetário romano modernizou-se na guerra de Aníbal: o **denário** de prata (equivalente a 10 asses, depois 16) foi introduzido por volta de 211 a.C. e manteve-se durante séculos. A partir de 44 a.C., César foi o primeiro romano vivo a aparecer numa moeda. As moedas serviam também de propaganda: os assassinos de César cunharam um denário com dois punhais e a legenda EID MAR.',
  { h: 'Escrita, latim e literatura' },
  'O latim escrevia-se com um alfabeto de 21 letras (mais tarde, 23), em tabuinhas de cera, papiro e, em monumentos, em pedra e bronze. A literatura latina nasceu com a influência grega: **Lívio Andrónico** traduziu a *Odisseia* e produziu a primeira peça de teatro em latim (240 a.C.); **Énio** escreveu os *Anais* em verso; os comediógrafos **Plauto** e **Terêncio** adaptaram peças gregas. No século I a.C., a prosa e a poesia latinas atingiram o seu auge com **Cícero**, **César**, **Salústio**, **Lucrécio**, **Catulo** e **Varrão**.',
  { h: 'Casa e cidade' },
  'Em Roma, a maioria vivia em **insulae**, blocos de apartamentos de vários andares, de tijolo e madeira, perigosos pelo risco de incêndio e de desabamento. Os ricos tinham **domus**, casas térreas em torno de um átrio com impluvium, e vilas no campo. A cidade crescia sem plano: ruas estreitas e sombrias, grandes incêndios, cheias do Tibre. Os aquedutos (a Aqua Marcia, construída em 144–140 a.C., foi o maior até então) traziam água de longe, e a **Cloaca Máxima** drenava o Fórum.',
  { h: 'Alimentação' },
  'A base era a trilogia **cereais, vinho e azeite**. O pão e o *puls*, uma papa de trigo, alimentavam os pobres; a carne era rara. Os ricos organizavam banquetes (*convivia*) com pratos de caça, peixe e frutas, e usavam o molho de peixe fermentado, o *garum*. Os alimentos vindos das províncias (os figos de África, as cerejas do Ponto que Lúculo levou para Itália, segundo Plínio) tornaram a mesa mais variada. O Senado chegou a promulgar leis contra o luxo à mesa (as *leges sumptuariae*), com pouco efeito.',
  { h: 'Vestuário' },
  'O traje romano de cidadão era a **toga**, de lã branca, que só homens cidadãos podiam usar em público; por baixo, a **túnica**. Os magistrados usavam a **toga praetexta**, com orla púrpura; os candidatos a cargos, a **toga cândida**, branqueada (de onde vem «candidato»). As mulheres casadas usavam a **stola** sobre a túnica, e a *palla* como manto. Os generais triunfantes vestiam a toga púrpura e dourada. Ao longo do período, a seda e a púrpura de Tiro entraram como luxos.',
  { h: 'Educação' },
  'A educação era privada. Os filhos dos ricos aprendiam com pedagogos (muitas vezes escravos gregos), depois com o *grammaticus* (literatura grega e latina) e, por fim, com o retor (retórica). Foi no século II a.C. que a cultura grega se tornou a base da educação da elite, apesar da oposição de Catão, o Velho. Em 155 a.C., uma embaixada de três filósofos atenienses causou sensação em Roma, mas o Senado mandou-os embora por a sua dialética ser considerada perigosa. A retórica era a arte política por excelência: Cícero escreveu vários tratados sobre ela.',
  { h: 'Jogos, teatro e gladiadores' },
  'Os **jogos públicos** (*ludi*), pagos por magistrados e generais, eram a principal diversão: corridas de carros no Circo Máximo, peças de teatro e, em crescendo, combates de **gladiadores**. Segundo a tradição, o primeiro combate em Roma foi em 264 a.C., num funeral. A origem é debatida, talvez da Campânia ou da Etrúria. Os combates deixaram de ser exclusivamente funerários e tornaram-se espetáculo político: César, em 65 a.C., ofereceu jogos com 320 pares de gladiadores. A frase «Ave, César, os que vão morrer saúdam-te» está atestada uma única vez, com Cláudio, mais tarde, e não era um ritual.',
  { img: 'rrt-gladiadores', leg: 'Ilustração gerada por IA. Treino de gladiadores em Cápua, c. 75 a.C.' },
  { h: 'Ciência, medicina e técnica' },
  'A ciência romana foi sobretudo prática. Na medicina, Roma recebeu os médicos gregos (a tradição diz que o primeiro foi **Arcágato**, em 219 a.C.), apesar da desconfiança de Catão. O **calendário** era lunar e desajustado; em 46 a.C., César, aconselhado pelo astrónomo Sosígenes, criou o **calendário juliano**, de 365 dias com um ano bissexto a cada quatro, que se manteve durante mais de 1600 anos na Europa. A engenharia romana usava o **betão** (*opus caementicium*, com cinza vulcânica da Campânia), que permitiu abóbadas e arcos. Em Roma, **Lucrécio** (*Da Natureza das Coisas*) expôs em verso a física de Epicuro.',
  { h: 'O exército: da legião manipular à de Mário' },
  'Até Mário, o exército era uma **milícia de cidadãos proprietários**, convocados em tempo de guerra. A legião de Políbio (séc. II a.C.) tinha cerca de 4 200 infantes, divididos em linhas: os jovens *hastati*, os experientes *principes*, os veteranos *triarii* (e os *velites* de armamento ligeiro), organizados em **manípulos**, mais cerca de 300 cavaleiros. Com o alargamento das guerras, os camponeses não podiam ausentar-se tanto tempo. Em 107 a.C., Mário recrutou voluntários sem terras (*capite censi*), segundo Salústio: a medida, que a tradição apresenta como uma «reforma» súbita, foi na realidade gradual. A legião passou a organizar-se em **coortes**, com a águia (*aquila*) como estandarte, e os soldados a depender do general para o soldo e as terras de reforma.',
  { img: 'rrt-legionario-mariano', leg: 'Ilustração gerada por IA. Legionário romano da época de Mário, c. 100 a.C.; estudo interpretativo do equipamento.' },
  { h: 'Armamento e táticas' },
  'O soldado levava o *scutum* (escudo), o *gladius hispaniensis* (espada curta, adotada, segundo a tradição, a partir da Hispânia), o **pilum** (dardo pesado, que se dobrava ao embater) e uma cota de malha (*lorica hamata*). A tática romana assentava na disciplina, na flexibilidade das linhas e na engenharia: acampamentos fortificados todas as noites e cercos metódicos, como em Siracusa, Numância e Alésia. A cavalaria era fornecida em grande parte pelos aliados.',
  { h: 'A marinha' },
  'Roma não tinha marinha de guerra importante até 260 a.C., quando construiu uma frota e adotou o *corvus* para transformar o combate naval em combate de infantaria. Perdeu frotas inteiras com tempestades (mais navios do que em combate, segundo Políbio) e reconstruiu-as. No século I a.C., a luta contra os **piratas** e as guerras civis (Naulocos, Áccio) mostraram o peso do mar. As galés usadas eram trirremes e quinquerremes, movidas por remadores livres, não por escravos acorrentados, ao contrário do que o cinema mostra.',
  { h: 'O Estado de emergência: ditadura e senatus consultum ultimum' },
  'A **ditadura** era uma magistratura de emergência, com seis meses de duração. Foi usada ao longo da República para crises militares (Fábio Máximo foi ditador em 217). Sula transformou-a num instrumento de poder pessoal (82–79) e César fez-se nomear ditador várias vezes e, por fim, «perpétuo» (44). Em paralelo, o Senado criou em 121 a.C. o **senatus consultum ultimum**, um decreto que pedia aos cônsules que «cuidassem de que a República não sofresse dano», e que serviu de justificação para matar Caio Graco, os catilinários e outros. Os seus críticos (Cícero foi criticado depois de 63) diziam que era ilegal matar cidadãos sem julgamento.',
  { h: 'O Direito e os tribunais' },
  'A lei romana era interpretada por magistrados e juristas. Nesta época a base era o Direito das XII Tábuas (449 a.C.), a que se juntaram os **éditos dos pretores**, que ano após ano adaptavam as regras às situações novas. Em 149 a.C. criou-se o primeiro tribunal permanente (contra extorsão por governadores), seguido de outros. Os **juristas** (Quinto Múcio Escévola, Sérvio Sulpício Rufo) aprofundaram a ciência do direito. As sentenças dependiam muitas vezes da eloquência dos advogados, como mostram os discursos de Cícero contra Verres, em defesa de Milão e de outros.',
  { h: 'A crise dos Gracos' },
  'Em 133 a.C., **Tibério Graco**, tribuno da plebe, apresentou a reforma agrária, passou-a diretamente à assembleia contra o veto de um colega (que fez destituir) e usou o legado de Pérgamo para financiar a distribuição. Os senadores consideraram-no um tirano e mataram-no, com centenas de apoiantes. Em 123–121 a.C., o irmão, **Caio**, lançou um programa muito mais vasto: trigo subsidiado, colónias, tribunais abertos aos cavaleiros, estradas. Também ele morreu, com milhares de partidários. Estas mortes marcaram o fim da convicção de que a política romana se resolvia sem derramar sangue de cidadãos.',
  { h: 'Mário, Sula e a política das armas' },
  'Foram os generais que mudaram o sistema. **Mário** foi eleito cônsul sete vezes (107, 104–100, 86), ao arrepio da tradição. **Sula** marchou sobre Roma com legionários, tomou a cidade (88 e 82 a.C.), assassinou os adversários por proscrição e reescreveu a Constituição, reforçando o Senado e cortando os poderes dos tribunos. Mostrou que a força do exército podia vencer a lei. Depois dele, **Pompeu**, **Crasso** e **César** recorreram à mesma lógica, com a diferença de que César perdoou os adversários vencidos (a *clementia Caesaris*), ainda que acabasse assassinado por alguns deles.',
  { img: 'rrt-sepulcro-cipioes', leg: 'Túmulo dos Cipiões, Roma, Via Ápia.' },
  { h: 'Dinheiro e política: os generais-empresários' },
  'A política era caríssima: eleger-se cônsul exigia milhões de sestércios em jogos, banquetes e subornos. Os candidatos endividavam-se para ter acesso às províncias, onde tentavam enriquecer. **Crasso** foi o mais rico de Roma: fez fortuna com as proscrições de Sula, com imóveis e com uma brigada de bombeiros privada que comprava, por quase nada, casas em chamas. **César** esteve afundado em dívidas antes da Gália. Os vencidos nas províncias pagavam o preço.',
  { h: 'As conquistas e o seu preço' },
  'Houve verdadeiro lucro: tributos, minas, escravos e terras. Mas houve também um custo social e moral. As cidades da Itália viam-se cheias de escravos e de desempregados; os soldados voltavam sem terra; o poder dos governadores, longe de Roma e sem supervisão efetiva, levou a abusos como os de Verres. O Estado romano não criou uma administração profissional para as províncias; confiou-as a governadores anuais e a empresários privados. Foi esta lacuna, mais do que qualquer vício moral das elites, que tornou a República inviável.',
  { h: 'O Calendário e o tempo' },
  'O calendário republicano tinha 355 dias e um mês intercalar, decidido pelos pontífices, que muitas vezes o manipulavam por razões políticas, e por isso estava, no tempo de César, desfasado das estações em cerca de três meses. Em 46 a.C., o «ano da confusão», com 445 dias, repôs a ordem. O novo calendário entrou em vigor a 1 de janeiro de 45. O mês Quintilis foi rebatizado **Julius** (julho) em honra de César, e, depois, Sextilis tornou-se *Augustus* (agosto).',
  { h: 'Mulheres' },
  'As mulheres romanas livres eram cidadãs, mas sem direitos políticos. Podiam ter propriedade, e algumas famílias deixavam-lhes bens por herança. As mulheres da elite tiveram influência política indireta: **Servília** (mãe de Bruto e amante de César), **Clódia**, a possível «Lésbia» de Catulo (a identificação é debatida), **Fúlvia** e **Cleópatra**, rainha estrangeira com quem César e António tiveram filhos. Em 195 a.C., as mulheres fizeram manifestações em Roma, contra a *lex Oppia* (que limitava o seu luxo), e conseguiram revogá-la, apesar de Catão.',
  { h: 'A Itália depois da guerra social' },
  'Depois da Guerra Social (91–88 a.C.), a maior parte da Itália obteve a cidadania romana. Os novos cidadãos foram inscritos em poucas tribos, o que lhes diminuía o peso nas votações. Em 49 a.C. a cidadania chegou aos habitantes da Gália Cisalpina (a norte do Pó). Esta integração, muito mais ampla do que a de qualquer cidade grega, é um dos segredos do sucesso romano e preparou a posterior extensão da cidadania às províncias.',
  { h: 'Cidades e colónias' },
  'Roma fundou colónias de cidadãos e de latinos, em pontos estratégicos da Itália e, depois, das províncias: Narbo Martius, na Gália (118 a.C.), Itálica (206 a.C., fundação para veteranos) na Hispânia, Corinto (44 a.C., por César) e Cartago (planos de César e concretização de Augusto). As colónias serviam para resolver o problema da terra (instalando veteranos e pobres) e para vigiar o território. Foi por esta via que se espalhou a língua, o direito e a cultura romana.',
  { h: 'A propaganda e a imagem do poder' },
  'Os generais usavam a arte e a arquitetura para se promoverem. Os **triunfos** e as construções públicas (templos, teatros, basílicas, pórticos) davam fama. Pompeu construiu o primeiro teatro de pedra em Roma (55 a.C.); César, o Fórum de César (46 a.C.), com um templo a Vénus Genetrix. As **moedas** passaram a levar os retratos de vivos. Os retratos de pedra, de tradição realista (cabeças enrugadas, de aristocratas idosos) cedem lugar a retratos mais idealizados, à moda helenística.',
  { h: 'Vida privada, dívidas e crise' },
  'O endividamento foi um problema crónico. Em 63 a.C., Catilina prometeu cancelar dívidas (*tabulae novae*), com apoio de falidos e de camponeses desesperados; foi derrotado, mas o problema persistiu. As elites também estavam endividadas: César devia imensas somas antes de partir para a Gália. O Estado romano, porém, não tinha um banco público; os empréstimos eram privados, com um limite legal habitual de 12% ao ano, que na prática muitas vezes se excedia.',
  { h: 'Cultura grega e resistência' },
  'Roma absorveu a cultura grega: arte, filosofia, medicina, retórica, teatro. As estátuas e quadros levados de Siracusa, Corinto e Pérgamo decoraram templos e casas. Alguns, como Catão, o Velho, resistiram e consideraram esse luxo uma ameaça aos costumes antigos (*mos maiorum*). Outros, como os Cipiões, tornaram-se patronos de poetas e filósofos. No fim da República, ser romano e ser culto significava dominar o grego: Cícero estudou em Atenas e em Rodes e escreveu tratados filosóficos adaptando ideias gregas ao latim.',
  { h: 'Cleópatra, o Egito e o trigo' },
  'O Egito dos Ptolemeus, o reino helenístico mais rico, era o grande fornecedor de trigo. Os últimos reis dependiam da proteção de Roma; Ptolemeu XII foi reposto no trono em 55 a.C. com tropas romanas. **Cleópatra VII** (69–30 a.C.) governou com o irmão e marido Ptolemeu XIII; foi expulsa, e César, que a apoiou na guerra de Alexandria (48–47), instalou-a no trono. Teve com ele um filho, **Cesarião** (47 a.C.). Depois aliou-se a António, de quem teve três filhos. A sua queda em 30 a.C. pôs fim ao último reino helenístico.',
  { h: 'O Principado em gestação' },
  'Octaviano, sobrinho-neto e filho adotivo de César, tinha 18 anos quando este morreu. Em 13 anos eliminou António e todos os rivais. Em 27 a.C., em vez de se apresentar como rei ou ditador (nomes odiados), apresentou-se como **princeps** («o primeiro cidadão»), mantendo cônsules e Senado, mas conservando o comando das legiões e das províncias. A fórmula resolveu o problema que a República não conseguira resolver: como governar um império mantendo a ficção do governo republicano. Veja **O Alto Império**.'
];

const personalidades = [
  'Estas 15 figuras marcaram a história da República Tardia. Algumas foram heróis para os romanos, outras vilões; quase todas foram as duas coisas, consoante quem contava. Os dados biográficos vêm de fontes antigas, nem sempre fiáveis, e as datas de nascimento são frequentemente incertas.',
  { h: 'Públio Cornélio Cipião, o Africano (c. 236 – 183 a.C.)' },
  'O general que venceu Aníbal. Aos vinte e poucos anos, tomou Cartagena (209 a.C.), expulsou os cartagineses da Hispânia (206) e levou a guerra a África, onde venceu em Zama (202). Recebeu o nome de «Africano». Foi cônsul duas vezes, mas acabou acusado de corrupção pelos adversários políticos e retirou-se para Literno, na Campânia, onde morreu. Foi admirado pelos gregos e protetor da cultura helenística. O seu neto adotivo, Cipião Emiliano, destruiria Cartago e Numância.',
  { h: 'Catão, o Velho (234 – 149 a.C.)' },
  'Homem novo, vindo da Tusculana, foi cônsul (195), censor (184) e o modelo do romano austero e conservador. Opôs-se ao luxo e à influência grega, o que não o impediu de aprender grego. Escreveu o primeiro tratado em prosa latina conservado, *De Agri Cultura*. A tradição atribui-lhe o refrão «Cartago deve ser destruída» no fim dos seus discursos. Foi também a favor da *lex Voconia*, que limitou os direitos hereditários das mulheres. É, para a posteridade, o símbolo da antiga virtude republicana, mas nem sempre era assim retratado pelos contemporâneos.',
  { h: 'Aníbal Barca (247 – c. 183 a.C.)' },
  'O general cartaginês que quase destruiu Roma. Filho de Amílcar Barca, jurou aos nove anos, segundo a tradição, ser eterno inimigo de Roma. Comandou os cartagineses na Hispânia, invadiu a Itália atravessando os Alpes (218 a.C.) e venceu os romanos em Trebbia, Trasimeno e Cannas. Durante quinze anos permaneceu em Itália, sem conseguir tomar Roma. Derrotado por Cipião em Zama, serviu Cartago como magistrado e depois fugiu, exilado, para o Oriente. Perseguido por Roma, suicidou-se com veneno na Bitínia, c. 183 a.C. Os romanos, que o temiam, foram dos que mais o admiraram.',
  { h: 'Os Gracos: Tibério (c. 163 – 133) e Caio (c. 154 – 121 a.C.)' },
  'Irmãos da família dos Semprónios Gracos, netos de Cipião Africano por via materna, filhos de **Cornélia**. Tibério, tribuno em 133 a.C., propôs a reforma agrária e foi morto por senadores; Caio, tribuno em 123 e 122, propôs trigo barato, colónias, tribunais de cavaleiros, e morreu em 121 a.C. Os historiadores antigos (Plutarco, Apiano) viram neles heróis ou demagogos. Para os modernos, foram reformadores que revelaram os problemas de uma Itália em transformação, e a sua morte marcou o início do período de violência política.',
  { img: 'rrt-gracos', leg: 'Os Gracos, grupo esculpido por Eugène Guillaume em 1853, Museu d’Orsay, Paris.' },
  { h: 'Gaio Mário (c. 157 – 86 a.C.)' },
  'Originário de Arpino, «homem novo» sem antepassados senadores, casou com uma Júlia, tia de César. Foi cônsul sete vezes. Acabou a guerra de Jugurta (105), venceu cimbros e teutões (102–101) e reorganizou o exército. Em 88 a.C., a disputa com Sula pelo comando da guerra contra Mitridates levou à guerra civil. Mário e o seu aliado Cina tomaram Roma em 87 e massacraram adversários, e Mário morreu a 13 de janeiro de 86, já no sétimo consulado. Foi um grande general e um político implacável.',
  { img: 'rrt-mario-busto', leg: 'Busto tradicionalmente chamado «Mário», Gliptoteca de Munique (319). A identificação não é segura.' },
  { h: 'Lúcio Cornélio Sula (138 – 78 a.C.)' },
  'Aristocrata empobrecido, tornou-se questor de Mário e foi quem recebeu a rendição de Jugurta (105). Venceu na Guerra Social, e, cônsul em 88, foi o primeiro a marchar sobre Roma. Combateu Mitridates na Grécia e na Ásia, regressou em 83 e venceu a guerra civil. Como ditador (82–79), proscreveu milhares, reescreveu a constituição e abdicou. Os romanos chamaram-lhe *Felix* («afortunado»). A sua marcha mostrou que o exército podia decidir a política, e foi o modelo, e o aviso, para os que vieram depois.',
  { img: 'rrt-sula-busto', leg: 'Busto tradicionalmente chamado «Sula», Gliptoteca de Munique (309). A identificação não é segura.' },
  { h: 'Gneu Pompeu Magno (106 – 48 a.C.)' },
  'Começou a carreira ainda muito novo, com um exército particular, ao lado de Sula, que lhe chamou *Magnus* («o Grande»). Pôs fim à guerra de Sertório na Hispânia (72), acabou a revolta de Espártaco (71), limpou o Mediterrâneo de piratas em três meses (67), derrotou Mitridates e reorganizou o Oriente (66–62). Foi o homem mais poderoso de Roma, mas não soube transformar o prestígio em política duradoura. Casou com Julia, filha de César. Derrotado em Fársalo (48), foi morto em Pelúsio, ao chegar ao Egito, por ordem do rei Ptolemeu XIII.',
  { img: 'rrt-pompeu-busto', leg: 'Retrato atribuído a Pompeu; Ny Carlsberg Glyptotek, Copenhaga.' },
  { h: 'Marco Licínio Crasso (c. 115 – 53 a.C.)' },
  'O homem mais rico de Roma. Apoiou Sula, enriqueceu com as proscrições e com o imobiliário, e venceu Espártaco (71), com métodos brutais, incluindo a decimação das suas tropas, segundo Plutarco e Apiano. Foi o terceiro do pacto com Pompeu e César. Em 53 a.C., à frente de um exército na Síria, quis a glória militar de uma guerra contra os partas e foi derrotado em Carras, onde morreu com o filho Públio. A tradição, provavelmente apócrifa, diz que os partas lhe derramaram ouro derretido na boca.',
  { img: 'rrt-crasso-busto', leg: 'Retrato de um romano desconhecido, século I a.C., Louvre (MR 510), anteriormente atribuído a Crasso, Galba ou Pisão.' },
  { h: 'Marco Túlio Cícero (106 – 43 a.C.)' },
  'O maior orador romano e o mais importante prosador latino. Natural de Arpino, «homem novo», chegou a cônsul em 63 a.C. e denunciou a conjura de Catilina, o que o fez «pai da pátria» para uns e tirano para outros (executou conspiradores sem julgamento, e foi exilado em 58). Acusou Verres (70). Foi um defensor da República, mas hesitante: seguiu Pompeu, aceitou o perdão de César, atacou António nas *Filípicas*. Foi morto por ordem de António, em 7 de dezembro de 43 a.C., e a sua cabeça foi exposta nos Rostros. Chegaram até nós cerca de 900 cartas, uma fonte inigualável.',
  { img: 'rrt-cicero-busto', leg: 'Busto de Cícero; Museus Capitolinos, Roma.' },
  { h: 'Gaio Júlio César (100 – 44 a.C.)' },
  'Patrício de uma família antiga mas pouco poderosa, sobrinho por afinidade de Mário, escapou por pouco às proscrições de Sula. Foi pontífice máximo (63), cônsul (59), governador da Gália (58–50), conquistador da Gália e vencedor da guerra civil (49–45). Escreveu os *Comentários* com enorme habilidade política. Como ditador, reformou o calendário, alargou o Senado, fundou colónias e planeou campanhas na Dácia e contra os partas. Foi assassinado a 15 de março de 44 a.C., por senadores que o acusavam de querer ser rei, embora ele tenha recusado a coroa no festival das Lupercais, segundo as fontes. A data de nascimento, 100 ou 102 a.C., é discutida.',
  { img: 'rrt-cesar-busto', leg: 'Busto de Júlio César; Museus do Vaticano.' },
  { h: 'Espártaco (m. 71 a.C.)' },
  'Trácio de nascimento, foi soldado, prisioneiro e depois gladiador numa escola de Cápua. Em 73 a.C., com cerca de setenta companheiros, escapou e formou um exército de escravos. Venceu várias legiões na Itália do Sul. Não sabemos o que pretendia: fugir da Itália (o mais provável, segundo Plutarco), ou saquear. Foi derrotado por Crasso e morreu em combate, o corpo nunca identificado. A sua figura, de enorme impacto cultural, tem pouca base nas fontes: os relatos de Plutarco e Apiano são escassos e escritos por romanos.',
  { img: 'rrt-espartaco-estatua', leg: 'Espártaco quebrando as correntes, Denis Foyatier, 1830; Louvre.' },
  { h: 'Viriato (m. 139 a.C.)' },
  'Chefe lusitano, de origem humilde; as fontes antigas não dizem onde nasceu, e a tradição moderna aponta para a região da serra da Estrela. Escapou ao massacre de Galba e, em c. 147 a.C., foi eleito chefe dos lusitanos. Durante oito anos, com bandos pequenos e rápidos, derrotou os pretores romanos na Hispânia. Os romanos tiveram de lhe oferecer um tratado, que depois não cumpriram. Foi morto à traição em 139 a.C. A sua memória foi retomada no século XVI e, sobretudo, no século XIX e XX, como símbolo nacional português, apesar de os lusitanos não serem «portugueses» no sentido moderno.',
  { h: 'Cleópatra VII Filopátor (69 – 30 a.C.)' },
  'A última rainha do Egito ptolemaico. Descendente de Ptolemeu I, foi a única da sua dinastia a aprender egípcio, segundo Plutarco. Com o apoio de César, venceu o irmão na guerra civil (47 a.C.); depois ligou-se a Marco António e usou o poder romano para tentar restaurar o império ptolemaico. Derrotada em Áccio, suicidou-se em 30 a.C. A tradição, a partir de Plutarco, fala de uma áspide; os modernos discutem se não terá sido veneno. A propaganda de Octaviano pintou-a como uma estrangeira sedutora e perigosa, imagem que a literatura e o cinema perpetuaram.',
  { img: 'rrt-cleopatra-busto', leg: 'Busto de Cleópatra VII com diadema; Altes Museum, Berlim.' },
  { h: 'Marco António (83 – 30 a.C.)' },
  'Soldado e orador, braço direito de César na Gália e na guerra civil, cônsul em 44 a.C. Fez o elogio fúnebre de César e agitou o povo contra os conspiradores. Aliado de Octaviano e Lépido no Segundo Triunvirato, venceu em Filipos (42). Ficou com o Oriente e ligou-se a Cleópatra. A campanha contra os partas (36) falhou, e a propaganda de Octaviano acusou-o de se ter «helenizado» e de querer dividir o império. Derrotado em Áccio, suicidou-se em Alexandria. A sua imagem, como a de Cleópatra, foi escrita pelos vencedores.',
  { img: 'rrt-antonio-busto', leg: 'Busto masculino tradicionalmente atribuído a Marco António, Museus do Vaticano. A ficha do Commons situa a peça na época Flávia (69–96 d.C.); a identificação é incerta.' },
  { h: 'Gaio Júlio César Octaviano, mais tarde Augusto (63 a.C. – 14 d.C.)' },
  'Sobrinho-neto de César, foi por ele adotado em testamento. Tinha 18 anos quando o tio morreu. Nos dezassete anos seguintes, aliou-se a António e Lépido, vingou o tio, eliminou os adversários e, em Áccio (31), com Agripa, venceu António. Em 27 a.C., criou, com a fórmula do *princeps* e da «restauração da República», o regime que durou cerca de cinco séculos no Ocidente. Foi implacável nas proscrições de 43 e moderado depois. Esta página termina aqui; a sua longa vida de governante é contada em **O Alto Império**.',
  { img: 'rrt-octaviano-busto', leg: 'Retrato do jovem Octaviano, cerca de 31 a.C., Museus Capitolinos, fotografado numa exposição no Grand Palais, Paris.' }
];

const legado = [
  { h: 'O que nos deixaram' },
  'A República Tardia deixou-nos o latim clássico, o direito romano em formação, o modelo do império e uma experiência política de séculos, estudada por todos os que depois pensaram nos limites do poder. Deixou também as obras de **Cícero**, **César**, **Lucrécio** e **Salústio**, que ainda se lêem, e uma tradição de monumentos e de moedas. Deixou ainda uma advertência: como as instituições se corroem quando os agentes políticos deixam de respeitar as regras.',
  { h: 'A queda da República: explicações' },
  'Porque caiu? Não há uma só resposta. Os historiadores apontam: o **tamanho do império** e a falta de uma administração profissional; os **exércitos fiéis aos generais** e não ao Estado; a **desigualdade** e o problema da terra; a **competição** entre aristocratas por prestígio e riqueza; a **violência política** sem castigo. Para Salústio, foi a corrupção moral que se seguiu à destruição de Cartago (a tese do *metus hostilis*); para os modernos, uma combinação de causas estruturais e escolhas individuais. Houve contingência: se César não tivesse sido assassinado, ou se António tivesse vencido em Áccio, a história seria outra.',
  { img: 'rrt-morte-cesar', leg: 'A morte de César, Jean-Léon Gérôme, 1867; Walters Art Museum.' },
  { h: 'O assassinato de César e o mito de Bruto' },
  'Os conspiradores, que se chamavam «libertadores», julgaram restaurar a República e não perceberam que o regime já estava morto. A frase «Tu quoque, Brute?» é de Shakespeare, não das fontes antigas; Suetónio refere que César teria dito, em grego, «também tu, meu filho?», mas apresenta-o como uma versão que circulava. O tiranicídio (matar um tirano) foi, desde então, um tema político: de Dante (que pôs Bruto e Cássio no último círculo do Inferno), aos republicanos do século XVIII.',
  { h: 'Cícero e a literatura' },
  'Os textos de Cícero (discursos, cartas, tratados filosóficos) foram o modelo da prosa latina e da retórica europeia. Petrarca, no século XIV, redescobriu as suas cartas, o que foi um marco do Humanismo. O poema de **Lucrécio** sobre o epicurismo, quase perdido, foi encontrado em 1417 pelo humanista Poggio Bracciolini. Os *Comentários* de César são ainda hoje um modelo de prosa clara.',
  { img: 'rrt-cicero-catilina', leg: 'Cícero denuncia Catilina, Cesare Maccari, 1888; Palazzo Madama, Roma.' },
  { h: 'O direito e as instituições' },
  'A ideia de **magistraturas anuais**, de **colegialidade** (dois cônsules que se vigiavam) e de **veto**, a prática da **assembleia**, o conceito de **república**: tudo isso foi lido, no Renascimento e depois, como alternativa à monarquia. Políbio, que descreveu a Constituição romana como mista (monarquia, aristocracia, democracia), influenciou Montesquieu e os fundadores dos Estados Unidos, que dividiram o poder em ramos e chamaram «Senado» à câmara alta. Os termos «cônsul», «ditador» e «tribuno» foram usados nas revoluções francesa e americana, e depois no século XX.',
  { h: 'A expansão e o Mediterrâneo' },
  'A conquista da Grécia e do Oriente pôs Roma em contacto com o helenismo, e o Mediterrâneo tornou-se, como diziam os romanos, o *mare nostrum*. A unidade política que daí resultou (estradas, língua, moeda, direito) permitiu a circulação de pessoas, ideias e religiões, incluindo, mais tarde, o cristianismo. O Mediterrâneo só voltaria a ser uma unidade política com o Império Romano.',
  { img: 'rrt-actium-batalha', leg: 'Ilustração gerada por IA. Batalha de Áccio, 31 a.C.; interpretação artística.' },
  { img: 'rrt-rubicao', leg: 'Ilustração gerada por IA. César junto do Rubicão, janeiro de 49 a.C., antes da travessia; cena interpretativa.' },
  { h: 'Os mitos da República' },
  { lista: [
    '**«Cartago deve ser destruída» e o sal:** a primeira é atribuída a Catão pelas fontes (Plutarco, Plínio); a história do sal lançado nos campos para os tornar estéreis só aparece no século XIX.',
    '**Os gladiadores e o polegar:** não há prova de que o polegar para baixo significasse a morte. O gesto é debatido e a imagem vem da pintura do século XIX.',
    '**«Alea iacta est» (a sorte está lançada):** é tradição; Suetónio dá a frase em latim, e Plutarco cita-a em grego. Ninguém sabe a forma exata.',
    '**«Veni, vidi, vici» (vim, vi, venci):** Plutarco diz que César a escreveu numa carta a um amigo, a propósito da vitória de Zela (47 a.C.); Suetónio diz que foi exibida no seu triunfo.',
    '**Espártaco, herói da liberdade:** foi uma construção moderna, sobretudo dos séculos XVIII e XIX, sem grande base nas fontes antigas.',
    '**Cleópatra e o nariz:** a famosa frase de Pascal (o nariz de Cleópatra) é uma reflexão sobre a história, e não prova nada sobre a sua aparência. Os retratos em moeda mostram um perfil marcado, de nariz comprido e queixo forte.'
  ] },
  { h: 'O que mudou em Portugal' },
  'Desde 206 a.C. (Itálica) a Hispânia foi romanizada. A conquista da Lusitânia começou com as guerras de Viriato e acabou, com a pacificação do noroeste, no tempo de Augusto. A língua latina, que deu origem ao português, o direito romano, a rede de estradas, as cidades (*Olisipo*, *Pax Iulia*, *Scallabis*, *Aeminium*, *Bracara Augusta*, estas últimas já no Império) e o cristianismo têm raízes neste processo. Mas convém lembrar que os povos pré-romanos tinham as suas línguas e as suas culturas, e que a «romanização» foi gradual e desigual.',
  { h: 'Onde ver a República Tardia' },
  { lista: [
    '**Roma:** o Fórum Romano e o Capitólio; o Largo di Torre Argentina (a Cúria de Pompeu, onde César foi morto); o túmulo dos Cipiões, na Via Ápia Antiga; a Via Ápia; o Museu Capitolino e os Museus do Vaticano (retratos de Pompeu, César, Cícero).',
    '**Cartago (Tunísia):** sítio arqueológico e museu, com as colinas de Byrsa e o tofet (ruínas púnicas sob as romanas).',
    '**Espanha:** Numância (Soria), Itálica (Santiponce, Sevilha), o Museu de Cartagena (Carthago Nova).',
    '**França:** o Alésia MuséoParc (Alise-Sainte-Reine), junto ao local tradicional do cerco de 52 a.C.',
    '**Portugal:** em Lisboa, o Museu de Lisboa — Teatro Romano e o Museu Nacional de Arqueologia; em Viseu, a estátua de Viriato e o Museu Grão Vasco. Não há vestígios materiais seguros de Viriato.',
    '**Grécia:** Corinto antiga, Fársalo (campo de batalha), Filipos (sítio arqueológico) e Nicópolis (perto de Preveza), a cidade que Octaviano fundou para comemorar Áccio.'
  ] },
  { h: 'Questões abertas' },
  { lista: [
    '**As «reformas de Mário»:** foi súbita (107 a.C.), ou gradual? Os estudiosos modernos tendem a vê-la como um processo.',
    '**A data de nascimento de César** (100 ou 102 a.C.), e a de Cleópatra: estimativas.',
    '**Os números** de mortos em Cannas, Alésia e do exército de Espártaco: sempre exagerados nas fontes antigas.',
    '**O local da batalha de Zama**, de Vercelas, e de muitas outras: discutido.',
    '**Quem foi o fundador** de Olisipo como *Felicitas Iulia* e de Pax Iulia: César ou Augusto?',
    '**A morte de Cleópatra:** áspide, veneno, ou assassínio ordenado por Octaviano? A versão oficial foi o suicídio, mas há quem suspeite.'
  ] },
  { h: 'Leitura recomendada' },
  { lista: [
    'Políbio, *Histórias*; Lívio, *Desde a Fundação da Cidade*; Apiano, *Guerras Civis*; Plutarco, *Vidas Paralelas*; César, *Comentários*; Cícero, *Cartas*; Salústio, *A Conjuração de Catilina* e *A Guerra de Jugurta*.',
    'Mary Beard, *SPQR: A History of Ancient Rome* (2015); Tom Holland, *Rubicon* (2003); Adrian Goldsworthy, *The Fall of Carthage* (2000) e *Caesar: Life of a Colossus* (2006); Ronald Syme, *The Roman Revolution* (1939); Harriet Flower, *Roman Republics* (2010).'
  ] }
];

const quiz = [
  { p: 'Que acontecimento marcou o início das Guerras Púnicas, em 264 a.C.?', op: ['A tomada de Cartago', 'A intervenção romana em Messina, na Sicília', 'A travessia dos Alpes por Aníbal', 'A fundação de Cartagena'], certa: 1, exp: 'Os mamertinos pediram ajuda a Roma em Messina; Roma enviou tropas e entrou em guerra com Cartago.' },
  { p: 'Que invenção, segundo Políbio, permitiu aos romanos vencer os cartagineses no mar?', op: ['O *corvus*, uma ponte com gancho', 'O fogo grego', 'O aríete de bronze', 'A galera de três remos'], certa: 0, exp: 'O *corvus* prendia os navios inimigos e transformava o combate naval num combate de infantaria.' },
  { p: 'Em que batalha, em 216 a.C., Aníbal destruiu um exército romano em Itália?', op: ['Zama', 'Cannas', 'Alésia', 'Áccio'], certa: 1, exp: 'Em Cannas, na Apúlia, a cavalaria cartaginesa envolveu a infantaria romana.' },
  { p: 'Quem venceu Aníbal em Zama, em 202 a.C.?', op: ['Fábio Máximo', 'Cipião, o Africano', 'Mário', 'Catão, o Velho'], certa: 1, exp: 'Públio Cornélio Cipião desembarcou em África e venceu Aníbal em Zama.' },
  { p: 'Que dois locais foram destruídos por Roma em 146 a.C.?', op: ['Siracusa e Cápua', 'Numância e Pérgamo', 'Cartago e Corinto', 'Atenas e Esparta'], certa: 2, exp: 'Cipião Emiliano arrasou Cartago e Múmio destruiu Corinto.' },
  { p: 'Quem liderou a resistência lusitana a Roma e foi assassinado em 139 a.C.?', op: ['Vercingetórix', 'Sertório', 'Viriato', 'Jugurta'], certa: 2, exp: 'Viriato foi morto por três companheiros subornados pelo cônsul Servílio Cepião.' },
  { p: 'Que reforma propôs Tibério Graco, em 133 a.C.?', op: ['A abolição da escravatura', 'Uma reforma agrária', 'A criação do Senado', 'A reforma do calendário'], certa: 1, exp: 'Tibério propôs distribuir a terra pública a cidadãos pobres e foi morto por senadores.' },
  { p: 'O que fez Sula de inédito em 88 a.C.?', op: ['Tornou-se cônsul vitalício', 'Marchou sobre Roma com um exército', 'Aboliu o Senado', 'Venceu Aníbal'], certa: 1, exp: 'Foi o primeiro general a entrar em Roma com legiões, desencadeando a guerra civil.' },
  { p: 'Quem esmagou a revolta de Espártaco, em 71 a.C.?', op: ['Pompeu', 'Crasso', 'César', 'Sula'], certa: 1, exp: 'Crasso venceu os escravos; Pompeu reclamou o crédito por eliminar os fugitivos.' },
  { p: 'Que cônsul denunciou a conjura de Catilina, em 63 a.C.?', op: ['Cícero', 'César', 'Catão', 'Pompeu'], certa: 0, exp: 'Cícero foi cônsul em 63 a.C. e desmascarou Catilina nos seus discursos no Senado.' },
  { p: 'Onde cercou César o chefe gaulês Vercingetórix, em 52 a.C.?', op: ['Gergóvia', 'Alésia', 'Massília', 'Fársalo'], certa: 1, exp: 'Em Alésia, César construiu duas linhas de fortificações, uma contra a cidade e outra contra o exército de socorro.' },
  { p: 'Que rio atravessou César em 49 a.C., iniciando a guerra civil?', op: ['O Tibre', 'O Reno', 'O Rubicão', 'O Pó'], certa: 2, exp: 'O Rubicão marcava o limite da sua província; atravessá-lo com tropas era um ato de guerra.' },
  { p: 'Em que data foi assassinado César?', op: ['15 de março de 44 a.C.', '1 de janeiro de 45 a.C.', '2 de setembro de 31 a.C.', '13 de janeiro de 27 a.C.'], certa: 0, exp: 'Os Idos de Março de 44 a.C.; os conspiradores incluíam Bruto e Cássio.' },
  { p: 'Que batalha de 31 a.C. deu a vitória a Octaviano sobre António e Cleópatra?', op: ['Filipos', 'Áccio', 'Munda', 'Carras'], certa: 1, exp: 'Em Áccio, a frota de Agripa venceu a de António e Cleópatra, na costa da Grécia.' },
  { p: 'Que nome recebeu Octaviano do Senado, em 27 a.C.?', op: ['Rex', 'Dictator', 'Augusto', 'Imperator Perpétuo'], certa: 2, exp: 'O Senado deu-lhe o nome de Augusto e, de facto, começou o Principado.' }
];

export default {
  id: 'roma',
  cor: '#b5413a',
  emblema: '../../assets/img/roma.png',
  grupo: { ...GRUPO, aqui: 'republica-tardia' },
  nome:    { pt: 'A República Tardia', en: 'The Late Republic' },
  periodo: { pt: '264 – 27 a.C.', en: '264 – 27 BC' },
  visao:          { pt: visao, en: EN.visao },
  linha:          { pt: linha, en: EN.linha },
  mapa:           { pt: mapa, en: EN.mapa },
  sociedade:      { pt: sociedade, en: EN.sociedade },
  personalidades: { pt: personalidades, en: EN.personalidades },
  legado:         { pt: [...legado, ...CRED.pt], en: [...EN.legado, ...CRED.en] },
  quiz:           { pt: quiz, en: EN.quiz }
};
