// THE PHARAOHS — full English content. Same structure and same image slots as the Portuguese version (dados.js).
// Reference chronology: Ian Shaw (ed.), The Oxford History of Ancient Egypt, 2000, for the large phases and dynasties; reign dates are rounded and given with “c.”.

const visao = [
  { caixa: 'In brief', texto: [
    'The **pharaoh** was the king of Egypt: head of state, commander of the army, supreme judge and, above all, the intermediary between gods and men. For about three thousand years, from c. 3100 BC until the death of Cleopatra VII in 30 BC, Egypt was ruled by a succession of kings whom historians, following the Egyptian priest Manetho, group into **31 dynasties**, plus the age of the Macedonian and Ptolemaic kings.',
    'This page does not tell the story of the country period by period (for that, go to the pages on the Old, Middle and New Kingdoms, the Late Period and the Ptolemies and Romans), but explains **what a pharaoh was**: what he was called, what crowns he wore, which ceremonies legitimised him, how he was succeeded, how a king’s memory could be erased, and then presents 30 pharaohs and queens who shaped the history of Egypt.'
  ] },
  { img: 'efa-mascara-tutankhamon', leg: 'Gold funerary mask of Tutankhamun, photographed in the Egyptian Museum in Cairo (JE 60672).' },
  { h: 'The word “pharaoh”' },
  'The word “pharaoh” comes from the Egyptian **per-aa**, “the Great House”, which meant the palace, that is, the royal institution. Only in the **New Kingdom** (from the 18th Dynasty) did it come to be used for the person of the king as well, and only much later did it become the usual name. It passed into Hebrew (Par’oh) and Greek (Pharaō), and from there into European languages. The Egyptians themselves called the king **nesut-bity**, “he of the sedge and the bee”, that is, king of Upper and Lower Egypt, or simply “His Majesty” (hem-ef).',
  { h: 'A god-king?' },
  'The pharaoh was not a god like the others, but neither was he a mere mortal. The Egyptians said that the living king was the embodiment of the god **Horus**, son of Osiris, and that he was the “son of Ra” (the sun god). After death he was identified with **Osiris**, lord of the afterlife, and his successor became the new Horus. Egyptologists debate how far the Egyptians considered him divine: the texts show that he was seen as a being of special nature, a bridge between the divine and human spheres, but bound, like men, to do his duty towards the gods.',
  { img: 'efa-serekh-djet', leg: 'Stela of Djet, falcon above the serekh, Louvre (E 11007).' },
  { h: 'Ma’at: the order the pharaoh maintains' },
  'The pharaoh’s central task was to maintain **ma’at**: the order, truth and justice of the universe, personified in a goddess with a feather on her head. Ma’at was the opposite of **isfet**, chaos, falsehood and disorder. The king maintained it in three ways: by **performing the cult** of the gods (building temples, making offerings), by **defending Egypt** from its enemies and by **doing justice** to his subjects. In reliefs he is shown offering ma’at to the gods, and he always defeats his enemies, even when in reality the outcome was a draw or a defeat.',
  { img: 'efa-corte-faraonica', leg: 'Audience at a New Kingdom pharaonic court, c. 1350 BC: king with blue crown, vizier, scribes and attendants. AI-generated illustration.' },
  { h: 'What the pharaoh did' },
  { lista: [
    '**Religious leader:** in theory, the only priest of all the temples; in practice, priests acted in his name.',
    '**Head of state:** he appointed the vizier, the governors of the nomes (the provinces) and the high officials; he was the source of law, although the Egyptians had no known written law code.',
    '**Military leader:** he commanded the army; in inscriptions he is the one who defeats the enemies, and some kings, such as Thutmose III and Ramesses II, really did lead the campaigns.',
    '**Symbolic owner of the land:** Egypt was the king’s “property”, which he administered through officials and temples; the land and its produce paid taxes in grain, cattle and labour.',
    '**Guarantor of the Nile flood:** the success of the harvest depended on the annual flood, and a bad flood was a sign that ma’at had been broken.'
  ] },
  { h: 'The pharaoh in practice' },
  'The image of the all-powerful king is the one found in official inscriptions, but in practice the pharaoh depended on a bureaucracy (the **vizier**, the scribes, the governors), on the priests (whose power grew enormously in the New Kingdom) and on the army. There were strong kings who reorganised the country, and weak kings whom officials governed; there were murdered kings, palace coups and usurpations. The theory was one of absolute power; the reality was a balance between the king, the court, the temples and the provinces.',
  { h: 'Women on the throne' },
  'The throne was normally held by a man, but some women ruled: **Merneith** (1st Dynasty, probably a regent), **Sobekneferu** (end of the 12th Dynasty), **Hatshepsut** (18th Dynasty), **Twosret** (end of the 19th Dynasty) and **Cleopatra VII** (Ptolemaic Period). Some others, such as Nitocris, whom Herodotus mentions, are legendary figures or of doubtful existence. Queens, even without reigning, held great power, especially the **Great Royal Wives**.',
  { h: 'How the time of the pharaohs is counted' },
  'The Egyptians did not number years from a fixed event: they counted them by the **regnal years** of each king (“year 5 of king X”). Manetho, a priest from Sebennytos who wrote in Greek in the 3rd century BC under Ptolemy II (his book, the Aegyptiaca, is lost but survives in summaries), divided the kings into **30 dynasties** (the Persians of the 31st Dynasty were added later). Egyptologists keep this scheme, adding periods such as the Old, Middle and New Kingdoms and the Intermediate Periods, which are times of political division.',
  { caixa: 'Chronology: a note of caution', texto: 'The dates on this page follow the chronology of **Ian Shaw** (The Oxford History of Ancient Egypt, 2000), in particular for the limits of the great periods, and always come with **“c.”**. Other accepted chronologies (Hornung, Krauss and Warburton, 2006; von Beckerath, 1997) differ by **a few years** in the New Kingdom and by **decades or more before the Middle Kingdom**. After 664 BC the dates are much firmer, because Greek and Babylonian sources cross-check them.' },
  { h: 'Why they matter' },
  { lista: [
    '**The longest monarchy in history:** an institution with 3000 years of continuity, interrupted only by periods of division and by foreign rule (which generally adopted the titles and ceremonial of the pharaoh).',
    '**A model of sacred power:** the idea of a king who is also a religious figure influenced the ancient Mediterranean, from Alexander to the Roman emperors.',
    '**Monuments and art:** from the pyramids to the temples of Karnak and Abu Simbel, almost everything one visits in Egypt was built on a pharaoh’s orders.',
    '**Written records:** the king lists, annals and stelae allow a chronology that, in this detail, exists for almost no other ancient civilisation.'
  ] },
  { caixa: 'The pharaohs today', texto: 'Almost all known pharaohs were buried in pyramids or rock-cut tombs, and many were plundered in antiquity. The bodies of about twenty kings and queens survive and are now in the **National Museum of Egyptian Civilization** in Cairo, to which they were moved in a solemn parade in April 2021. The treasure of Tutankhamun, the only royal tomb of the New Kingdom found almost intact, is in the **Grand Egyptian Museum**, opened at Giza in 2025.' }
];

const linha = [
  'This timeline follows the political history of Egypt through its most important kings. Dates are approximate, in Shaw’s chronology (2000); before the Middle Kingdom the margin of error is decades, and even in the New Kingdom it can reach a few years. For the detail of each period, see the respective pages.',
  { linha: [
    { d: 'c. 3200 – 3100 BC', t: 'Dynasty 0: the first kings', x: 'At Abydos, tomb U-j yielded labels with signs that are among the oldest writing in Egypt, and the tomb of a powerful ruler. The names of some chiefs (“Scorpion”, “Crocodile”) are known, but it is **not known** whether they were kings of an already unified Egypt, and their order is debated. Egyptologists call it “Dynasty 0”.' },
    { d: 'c. 3100 BC', t: 'Narmer and the unification', x: 'The **Narmer Palette** shows the king wearing both the white crown of the south and the red one of the north. Egyptian tradition credited the unification to a king called **Menes**, who may be Narmer or his successor Aha: the question is debated. Unification was most probably a gradual process rather than a single conquest.' }
  ] },
  { img: 'efa-narmer-paleta', leg: 'Reverse of the Narmer Palette, Egyptian Museum, Cairo (JE 32169).' },
  { linha: [
    { d: 'c. 3100 – 2686 BC', t: 'Dynasties 1 and 2: the Thinite Period', x: 'The kings (Aha, Djer, Den, Khasekhemwy and others) were buried at **Abydos**, in Upper Egypt, and had the capital built at **Memphis**, at the junction of the two lands. In this period the royal titulary, the **serekh** and the first state run by scribes appeared. In the 2nd Dynasty there were religious rivalries between the cult of Horus and that of Seth (King Peribsen used the name of Seth).' },
    { d: 'c. 2667 – 2648 BC', t: 'Djoser and the Step Pyramid', x: '**Djoser**, of the 3rd Dynasty, had the architect **Imhotep** raise at Saqqara the first great stone building in Egypt, the **Step Pyramid**, surrounded by a complex of temples and buildings for the Heb-Sed festival.' }
  ] },
  { img: 'efa-djoser-estatua', leg: 'Statue of Djoser from the Saqqara serdab, Egyptian Museum (JE 49158).' },
  { linha: [
    { d: 'c. 2613 – 2589 BC', t: 'Snefru, the pyramid builder', x: '**Snefru**, founder of the 4th Dynasty, built (or finished) several pyramids: that of Meidum, the **Bent Pyramid** and the **Red Pyramid** at Dahshur, the first true smooth-sided pyramid. Centuries later he was remembered as a good king.' },
    { d: 'c. 2589 – 2566 BC', t: 'Khufu and the Great Pyramid', x: '**Khufu** (Cheops, in Greek) built the **Great Pyramid of Giza**, about 146 m high originally, the tallest monument in the world for almost four thousand years. It was not built by slaves: it was a state project with paid and fed workers (see the page “Monuments and sites”).' }
  ] },
  { img: 'efa-gize-piramides', leg: 'The three great pyramids of Giza.' },
  { linha: [
    { d: 'c. 2558 – 2503 BC', t: 'Khafre and Menkaure', x: 'Khufu’s son (**Khafre**) and grandson (**Menkaure**) built the other two Giza pyramids. The **Sphinx** is usually attributed to Khafre, although the attribution is not absolutely certain. Menkaure made a much smaller pyramid, but with a granite casing.' },
    { d: 'c. 2494 – 2345 BC', t: '5th Dynasty: the cult of Ra', x: 'The kings began to build **sun temples** at Abusir and to add “son of Ra” to their names. At the end of the dynasty, the walls of the pyramid of King **Unas** (c. 2345 BC) are the first to carry the **Pyramid Texts**, ritual formulas for life in the afterlife.' },
    { d: 'c. 2345 – 2181 BC', t: '6th Dynasty and Pepi II', x: 'Local governors gain power. **Pepi II** came to the throne as a child and tradition gives him a reign of more than ninety years, the longest in Egyptian history, but contemporary records only reach year 62 and many Egyptologists propose about 64 years. At his death, c. 2184 BC, the state fell apart.' },
    { d: 'c. 2181 – 2055 BC', t: 'The First Intermediate Period', x: 'Royal power weakened. Ephemeral kings at Memphis (Dynasties 7 and 8), a dynasty at **Herakleopolis** (9 and 10) and another at **Thebes** (11) disputed the country. Famine, low floods and civil wars mark the texts, but the true scale of the “crisis” is debated.' },
    { d: 'c. 2055 – 2004 BC', t: 'Mentuhotep II reunifies the country', x: '**Mentuhotep II**, of Thebes, defeated the kings of Herakleopolis and reunited Egypt around 2055 BC, founding the **Middle Kingdom**. His tomb-temple at Deir el-Bahari is a model for later monuments.' }
  ] },
  { img: 'efa-mentuhotep-ii-estatua', leg: 'Statue of Mentuhotep II with the red crown, Egyptian Museum (JE 36195).' },
  { linha: [
    { d: 'c. 1985 – 1956 BC', t: 'Amenemhat I and the 12th Dynasty', x: 'The former vizier **Amenemhat I** founded the 12th Dynasty and moved the capital to **Itjtawy**, near the Fayum. He was probably assassinated, and his successor **Senusret I**, already governing with him in a **co-regency**, took power without trouble. The “Story of Sinuhe” and the “Teaching of Amenemhat” may refer to these events.' },
    { d: 'c. 1870 – 1831 BC', t: 'Senusret III', x: 'He reorganised the administration, reduced the power of local governors and fortified the border with **Nubia** with huge fortresses at Buhen and Semna. His statues, with a grave and weary face, are among the most famous in Egyptian art.' },
    { d: 'c. 1831 – 1786 BC', t: 'Amenemhat III', x: 'One of the longest (about 45 years) and most prosperous reigns of the Middle Kingdom: large irrigation works in the **Fayum**, mines in Sinai, and two pyramids (Dahshur and **Hawara**). The Greeks called his funerary temple at Hawara the “Labyrinth”.' },
    { d: 'c. 1777 – 1773 BC', t: 'Sobekneferu and the end of the 12th Dynasty', x: '**Sobekneferu**, probably a daughter of Amenemhat III, is the first woman known with certainty to have reigned as pharaoh. With her the 12th Dynasty ended; the 13th Dynasty still held the country together for a time, but central power eroded until the Second Intermediate Period.' },
    { d: 'c. 1650 – 1550 BC', t: 'The Hyksos', x: 'Chiefs of Asiatic origin, the **Hyksos** (15th Dynasty), dominated the Delta from **Avaris**, while Egyptian kings at Thebes (17th Dynasty) held the south. The word “Hyksos” comes from the Egyptian heqa-khasut, “rulers of foreign lands”. Tradition says they brought the war chariot and the horse to Egypt.' },
    { d: 'c. 1550 – 1525 BC', t: 'Ahmose I expels the Hyksos', x: '**Ahmose I** took Avaris and reunified Egypt, founding the 18th Dynasty and the **New Kingdom**. His brother **Kamose** had already begun the war, and some consider it the true beginning of the reconquest: how the credit is divided between them is debated.' },
    { d: 'c. 1473 – 1458 BC', t: 'Hatshepsut, king of Egypt', x: 'First regent for the young Thutmose III, **Hatshepsut** took the title of king around 1473 BC and ruled for about 15 years, in a peaceful reign of great works, such as the temple of **Deir el-Bahari** and the expedition to the land of **Punt**.' },
    { d: 'c. 1479 – 1425 BC', t: 'Thutmose III, the warrior king', x: 'Alone in power since c. 1458 BC, he led about **17 campaigns** in Syria-Palestine, with the victory of **Megiddo** (c. 1457 BC). Egypt reached the greatest extent of its history, from the Euphrates to the Fourth Cataract of the Nile.' }
  ] },
  { img: 'efa-hatshepsut-estatua', leg: 'Colossal kneeling statue of Hatshepsut, Metropolitan Museum.' },
  { linha: [
    { d: 'c. 1390 – 1352 BC', t: 'Amenhotep III, the king of peace and wealth', x: 'A peaceful reign of splendour: **Luxor**, the **Colossi of Memnon**, hundreds of statues, diplomatic correspondence with the kings of Babylon, Mitanni and Arzawa (the “Amarna letters”) and three Heb-Sed festivals.' },
    { d: 'c. 1352 – 1336 BC', t: 'Akhenaten and Amarna', x: '**Amenhotep IV**, who changed his name to **Akhenaten**, imposed the cult of the solar disc **Aten**, founded a new capital, **Akhetaten** (Amarna), and completely changed the style of art. After his death the city was abandoned and his name erased.' }
  ] },
  { img: 'efa-akhenaton-colosso', leg: 'Colossal statue of Akhenaten from Karnak, Egyptian Museum in Cairo.' },
  { linha: [
    { d: 'c. 1336 – 1295 BC', t: 'From Tutankhamun to Horemheb', x: '**Tutankhamun** (c. 1336 – 1327 BC) restored the cult of Amun and returned to Memphis and Thebes. After **Ay** (c. 1327 – 1323 BC), the general **Horemheb** (c. 1323 – 1295 BC) reorganised the state and erased the memory of the Amarna kings, closing the 18th Dynasty.' },
    { d: 'c. 1294 – 1213 BC', t: 'Seti I and Ramesses II', x: 'The 19th Dynasty began with **Ramesses I** and continued with **Seti I** (c. 1294 – 1279 BC), who recovered territory in Syria, and with **Ramesses II** (c. 1279 – 1213 BC), who reigned 66 years, fought the battle of **Qadesh** (c. 1274 BC) and signed with the Hittites the oldest peace treaty whose text survives (c. 1259 BC).' }
  ] },
  { img: 'efa-ramses-ii-estatua', leg: 'Statue of Ramesses II, Museo Egizio, Turin (C. 1380).' },
  { linha: [
    { d: 'c. 1184 – 1153 BC', t: 'Ramesses III and the Sea Peoples', x: 'The last great king of the New Kingdom defeated the **Sea Peoples** and the Libyans, but the state weakened, with strikes, inflation and a **harem conspiracy** that probably cost him his life. His successors (Ramesses IV to XI) gradually lost power.' },
    { d: 'c. 1069 – 945 BC', t: 'Dynasties 21 and 22: Tanis, Thebes and the Libyans', x: 'With the end of the New Kingdom the country split: kings at **Tanis** (21st Dynasty), in the Delta, and high priests of Amun at **Thebes**. Around 945 BC, **Shoshenq I**, descended from Libyan chiefs, reunified the country and founded the 22nd Dynasty.' },
    { d: 'c. 747 – 656 BC', t: 'The Nubian kings (25th Dynasty)', x: 'The kings of Kush (Nubia), from **Napata**, beginning with **Piye** (king from c. 747 BC), conquered Egypt and ruled it for about 90 years. **Taharqa** (c. 690 – 664 BC) is the most important, until he was driven out by the Assyrians.' }
  ] },
  { img: 'efa-taharqa-esfinge', leg: 'Sphinx of Taharqa from Kawa, British Museum.' },
  { linha: [
    { d: '664 – 332 BC', t: 'Saites, Persians and the last native kings', x: '**Psamtik I** (664 – 610 BC) founded the 26th Dynasty at Sais and reunified the country. The Persians conquered Egypt in 525 BC (27th Dynasty). After a short independence (Dynasties 28 to 30), with **Nectanebo II** (360 – 343 BC) as the last native Egyptian king, they returned in 343 BC (31st Dynasty) until the arrival of Alexander in 332 BC.' },
    { d: '305 – 30 BC', t: 'The Ptolemies and Cleopatra VII', x: 'After the death of Alexander, the general **Ptolemy** (king from 305 BC) founded a Macedonian dynasty that ruled for 275 years from Alexandria. The last, **Cleopatra VII**, died in 30 BC, and Egypt became a province of Rome. Roman emperors continued to be portrayed as pharaohs in the temples.' }
  ] },
  { img: 'efa-cleopatra-busto', leg: 'Bust of Cleopatra VII with diadem, Altes Museum, Berlin.' }
];

const mapa = [
  'The pharaohs did not have a single capital: they changed residence according to the dynasty, politics and the defence of the kingdom. In general there was an **administrative capital** (near the apex of the Delta, near Memphis, or in the eastern Delta), a **religious city** (Thebes, with the god Amun) and **royal necropoles** where the kings were buried.',
  { img: 'efa-mapa-egito', leg: 'Map of ancient Egypt with the main cities.' },
  { tabela: { cab: ['City', 'Egyptian / Greek name', 'Main period', 'Location today'], linhas: [
    ['Hierakonpolis', 'Nekhen', 'Predynastic', 'Kom el-Ahmar, Upper Egypt'],
    ['Abydos / Thinis', 'Abdju / Tjeni', '1st and 2nd Dynasties (tombs)', 'Abydos (Umm el-Qa’ab)'],
    ['Memphis', 'Ineb-hedj, “White Walls”; Men-nefer', '1st to 8th Dynasties and, intermittently, afterwards', 'Mit Rahina, near Cairo'],
    ['Herakleopolis', 'Henen-nesut', '9th and 10th Dynasties', 'Ihnasya el-Medina, Middle Egypt'],
    ['Thebes', 'Waset; Diospolis Magna', '11th, 17th and 18th to 20th Dynasties (occasional residence)', 'Luxor and Karnak'],
    ['Itjtawy', '“Seizer of the Two Lands”', '12th Dynasty', 'Near Lisht, by the Fayum'],
    ['Avaris', 'Hut-waret', '15th Dynasty (Hyksos)', 'Tell el-Dab’a, eastern Delta'],
    ['Akhetaten', '“Horizon of Aten”', 'c. 1346 – 1332 BC (Akhenaten)', 'Tell el-Amarna, Middle Egypt'],
    ['Pi-Ramesses', '“House of Ramesses”', '19th and 20th Dynasties', 'Qantir, eastern Delta'],
    ['Tanis', 'Djanet', '21st and 22nd Dynasties', 'San el-Hagar, eastern Delta'],
    ['Sais', 'Sau', '26th Dynasty (Saite)', 'Sa el-Hagar, western Delta'],
    ['Alexandria', 'Rhakotis / Alexandreia', '331 BC – AD 641 (Ptolemaic capital)', 'Alexandria, Egypt']
  ] } },
  { h: 'Hierakonpolis and Abydos: the cradle' },
  'Before the dynasties, **Hierakonpolis** (Nekhen, “City of the Falcon”) was a great centre of Upper Egypt, where the Narmer Palette was found. **Abydos** was the necropolis of the first kings (Dynasties 0, 1 and 2), at Umm el-Qa’ab, the “mother of pots”, and later became the sacred place of Osiris, where many kings (such as Seti I) had temples or cenotaphs, symbolic tombs, built to take part in his resurrection.',
  { h: 'Memphis: the capital of the Two Lands' },
  'Founded, according to tradition, by King Menes on the border between Upper and Lower Egypt, **Memphis** was the capital of the Old Kingdom and, in many periods, the main administrative seat of the country. Its god was **Ptah**, the creator god and patron of craftsmen. From there the kings set out for the necropoles of the western desert. The monuments of Memphis have largely disappeared (they were reused as a quarry by medieval Cairo), but the pyramids of Saqqara, Giza, Abusir and Dahshur, nearby, still exist.',
  { img: 'efa-menfis-reconstrucao', leg: 'Conjectural artistic reconstruction of New Kingdom Memphis, c. 1300 BC, with the temple of Ptah, palace and Nile harbour. AI-generated illustration.' },
  { h: 'The necropoles of the Old and Middle Kingdoms' },
  'The pyramids line the west bank of the Nile, the side of the setting sun and of the realm of the dead: **Saqqara** (Djoser, Unas, Teti and Pepi II), **Dahshur** (Snefru and Senusret III), **Meidum**, **Giza** (Khufu, Khafre and Menkaure), **Abusir** (5th Dynasty), **Lisht** (Amenemhat I and Senusret I), **Hawara** and **Lahun** (Amenemhat III and Senusret II), in the Fayum. In the New Kingdom royal pyramids ceased to be built: the kings were buried in rock-cut tombs, at Thebes.',
  { h: 'Thebes and the Valley of the Kings' },
  '**Thebes** (Waset) was the city of **Amun** and, from the 18th Dynasty, the “religious capital” of the empire. On the east bank are the temples of **Karnak** and **Luxor**; on the west bank, the “city of the dead”: the **Valley of the Kings** (about 63 tombs numbered KV1 to KV63, from Thutmose I or soon after, to Ramesses XI), the **Valley of the Queens**, the great funerary temples (“temples of millions of years”) of Hatshepsut, Amenhotep III, Ramesses II (the Ramesseum) and Ramesses III (Medinet Habu), and the village of **Deir el-Medina**, home of the craftsmen who decorated the tombs.',
  { img: 'efa-vale-reis', leg: 'Valley of the Kings, western Thebes.' },
  { h: 'Itjtawy, the Fayum and the last kings of the Middle Kingdom' },
  'The 12th Dynasty moved the capital to **Itjtawy** (“Seizer of the Two Lands”), which has not yet been located with certainty; it would lie near **Lisht**, where the pyramids of Amenemhat I and Senusret I stand. The kings turned the **Fayum**, a fertile oasis, into an agricultural region through drainage and irrigation works (Amenemhat III), and built there the pyramids of Hawara and Lahun.',
  { h: 'Avaris: the capital of the Hyksos' },
  '**Avaris** (Hut-waret), today **Tell el-Dab’a**, in the eastern Delta, was a large city with a population from the Levant, with Syrian-style temples and warrior burials. It was the capital of the Hyksos kings and was taken by Ahmose I (c. 1550 BC). Minoan-style frescoes with bulls and acrobats have also been found there, suggesting contacts with the Aegean.',
  { h: 'Akhetaten (Amarna): the city of one god' },
  'In c. 1346 BC Akhenaten founded on a bay of the Nile an entirely new capital, **Akhetaten**, “the Horizon of Aten”, today **Tell el-Amarna**. It was built in a few years and abandoned shortly after his death. The palaces, the temples open to the sun, the residential quarters, the tombs of the nobles and the archive of clay tablets with diplomatic correspondence (the Amarna letters) have been found. There stood the workshop of the sculptor **Thutmose**, where the bust of Nefertiti was found.',
  { img: 'efa-amarna-reconstrucao', leg: 'Conjectural artistic reconstruction of Akhetaten (Amarna), c. 1340 BC: open-air Aten temple, Royal Road and palaces; Aten disc with hand-ended rays as a symbolic religious motif. AI-generated illustration.' },
  { h: 'Pi-Ramesses: the capital of Ramesses II' },
  'The “House of Ramesses”, in the eastern Delta near the Asian border, was the new residence of Ramesses II and the kings of the 19th Dynasty, and the base for the campaigns against the Hittites. The Bible speaks of a city called “Raamses”, which some link to the Exodus, but that link is much debated. It has been identified at **Qantir** and, after a branch of the Nile changed course at the end of the New Kingdom, the city was dismantled and its monuments taken to **Tanis**.',
  { img: 'efa-pi-ramesses-reconstrucao', leg: 'Conjectural artistic reconstruction of Pi-Ramesses, c. 1250 BC, with quays, temples, palaces and chariot facilities. AI-generated illustration.' },
  { h: 'Tanis: the capital and the golden tombs' },
  '**Tanis** (San el-Hagar) was the capital of the 21st and 22nd Dynasties. There, in 1939, the French archaeologist Pierre Montet discovered **intact royal tombs**, among them that of **Psusennes I**, with a gold mask and a silver coffin, now in the Egyptian Museum in Cairo. Many of the obelisks and statues of Ramesses II found here were in fact brought from Pi-Ramesses.',
  { h: 'Napata, El-Kurru and Nuri: the Nubia of the pharaohs' },
  'The kings of the 25th Dynasty, from **Napata** in Nubia (present-day Sudan), near the Fourth Cataract, were buried in small, steep pyramids at **El-Kurru** (Piye) and **Nuri** (Taharqa). The region learned art, cults and titles from Egypt but kept its own identity: the Nubian kings wore a crown with two uraei (cobras).',
  { h: 'Sais, Mendes, Sebennytos and the capitals of the last native kings' },
  'In the Delta, **Sais** (26th Dynasty), **Mendes** (29th Dynasty) and **Sebennytos** (30th Dynasty) were successively the capitals of the last Egyptian kings. Almost nothing remains: the ground is damp and has been much disturbed, and the stones were reused. But the Greek texts of Herodotus describe Sais, and the Saite kings were buried in the necropolis of Sais.',
  { h: 'Alexandria: the capital of the Ptolemies' },
  'Founded by Alexander the Great in 331 BC, **Alexandria** was the capital of the Ptolemies for 275 years, a great Greek city on the edge of the Delta, with a harbour, the **Pharos lighthouse**, the **Museum** and the **Library**. It lost its status as political capital at the end of the Ptolemies and remained one of the largest cities in the Mediterranean. Of Cleopatra’s palace, today only submerged remains survive in the eastern harbour.',
  { h: 'Routes and borders' },
  'The **Nile**, flowing from south to north, was the main “road” of Egypt, and the wind, blowing the other way, gave the return journey under sail. Egypt defended itself from the desert with **border fortresses**: to the north-east, the “Walls of the Ruler”; to the south, the Nubian fortresses from Buhen to Semna; to the east, the “Way of Horus”, which ran through Tjaru (Sile) to Gaza and Syria-Palestine, and along which the pharaohs marched on campaign.'
];

const sociedade = [
  'This section explains the “machinery” of kingship: the king’s five names, his insignia and crowns, the ceremonies that legitimised him, the rules of succession and the table of the dynasties.',
  { h: 'The royal titulary: the five names' },
  'Each pharaoh had an official titulary of **five names**, which was consolidated in the Middle Kingdom. Each stressed one aspect of kingship. The last two, written inside an elongated loop, the **cartouche**, are the names by which kings are known today.',
  { tabela: { cab: ['Name', 'In Egyptian', 'What it means', 'Example (Ramesses II)'], linhas: [
    ['1. Horus name', 'Hor', 'The king as living Horus; written in the serekh, the palace façade, with a falcon above. It is the oldest name.', 'Strong bull, beloved of Ma’at'],
    ['2. Two Ladies name', 'Nebty', 'The king protected by the vulture goddess Nekhbet (Upper Egypt) and the cobra Wadjet (Lower Egypt).', 'Protector of Egypt who subdues foreign countries'],
    ['3. Golden Horus name', 'Hor-nebu', 'The king as eternal Horus, linked to gold, symbol of the divine. Its exact meaning is debated.', 'Rich in years, great in victories'],
    ['4. Throne name (prenomen)', 'Nesut-bity', 'Chosen at the coronation; “he of the sedge and the bee”. In a cartouche; usually contains the name of Ra.', 'Usermaatra-Setepenra (“Powerful is the Ma’at of Ra, chosen of Ra”)'],
    ['5. Birth name (nomen)', 'Sa-Ra', '“Son of Ra”. In a cartouche; the name the person had at birth.', 'Ramessu-meryamun (“Ra has borne him, beloved of Amun”)']
  ] } },
  { img: 'efa-titulatura-esquema', leg: 'Diagram of the five royal names: Horus, Nebty, Golden Horus, prenomen and nomen. Blank serekh and cartouches, without a transcription of Ramesses II’s names.' },
  'Cartouches appear from the 4th Dynasty (with Snefru, perhaps earlier with Huni). They were a magical protection (“that which the sun encircles”), and were the key to Champollion’s decipherment of hieroglyphs in 1822, when he recognised in them the names of **Ptolemy** and **Cleopatra** (and then that of Ramesses).',
  { img: 'efa-cartucho', leg: 'Cartouches of Ramesses II on an obelisk at Tanis.' },
  { h: 'Crowns and insignia' },
  { tabela: { cab: ['Insignia', 'Egyptian', 'Description and meaning'], linhas: [
    ['White Crown', 'Hedjet', 'Tall and conical, of Upper Egypt, associated with the vulture goddess Nekhbet.'],
    ['Red Crown', 'Deshret', 'With a spiral at the front, of Lower Egypt, associated with the cobra goddess Wadjet and with Neith.'],
    ['Double Crown', 'Pschent / Sekhemty', 'The union of the two, a symbol of rule over the Two Lands; attested from the 1st Dynasty.'],
    ['Royal headcloth', 'Nemes', 'Striped cloth covering the head and falling on each side of the face; the Sphinx and Tutankhamun’s mask wear it.'],
    ['Blue Crown (“war crown”)', 'Khepresh', 'A crown of blue leather or cloth with golden discs, worn in battle and ceremonies from the New Kingdom.'],
    ['Atef Crown', 'Atef', 'White crown with feathers and discs, linked to Osiris and to religious ceremonies.'],
    ['Uraeus', 'Iaret', 'Rearing cobra on the king’s forehead, spitting fire at enemies; it protects the king.'],
    ['Crook and flail', 'Heka and nekhakha', 'The two royal sceptres, crossed on the chest; the crook (of the shepherd) and the flail symbolise rule and protection of the people.'],
    ['False beard', '—', 'Tied to the chin, with a curved tip for gods and a straight one for kings; worn by pharaohs, including women such as Hatshepsut.']
  ] } },
  { img: 'efa-coroas-esquema', leg: 'Pharaonic crowns and headcloth, left to right: Hedjet, Deshret, Pschent, Khepresh, Atef and nemes.' },
  { img: 'efa-cajado-mangual', leg: 'Crook, flail and sekhem sceptre from Tutankhamun’s tomb, photographed at the Egyptian Museum in Cairo.' },
  { h: 'The coronation' },
  'The coronation was a process in several stages rather than a single day. The king was chosen (by his father, by oracles of the god or by force), purified, dressed with the insignia and **“enthroned”** in the temple; he received the throne name and the five names, and symbolically stood over his enemies. There was the ceremony of the “Union of the Two Lands” (sema-tawy), in which the king appeared with the two crowns. The temple of Hatshepsut at Deir el-Bahari shows scenes of her coronation.',
  { img: 'efa-coroacao-cena', leg: 'Imagined New Kingdom coronation: priests place the double crown on a young pharaoh inside a temple. AI-generated illustration.' },
  { h: 'The Heb-Sed festival' },
  'The **Heb-Sed** (or “jubilee festival”) was a ceremony of **renewal** of the king, who had to reaffirm his capacity to rule. By tradition it was celebrated in the 30th year of the reign and then every three or four years. The king ran, symbolically, in a ritual enclosure, covering the limits of the territory, and sat on double thrones to receive the crowns anew. There is evidence for it already in the Thinite Period (under **Den**), and **Djoser**’s complex has the best-known Heb-Sed court; **Amenhotep III** celebrated three and **Ramesses II**, who reigned 66 years, celebrated more than a dozen. Not every king reached his 30th year: some celebrated it earlier.',
  { img: 'efa-hebsed-cena', leg: 'Heb-Sed ritual run in Djoser’s complex, c. 2650 BC: king with white crown between ceremonial markers. AI-generated illustration.' },
  { h: 'Succession' },
  'There was no single law of succession. The most common principle was that the throne passed to the **eldest son of the Great Royal Wife**, but many kings were sons of secondary wives, and those without legitimate sons chose, or imposed, another candidate. To strengthen their claim, kings could marry a **princess of the previous line**, including a sister or half-sister, and in some cases they claimed that the god Amun had taken the form of the father to beget them (the so-called “divine birth texts” of Hatshepsut and Amenhotep III). But there were usurpers, generals (Horemheb), high priests who took royal titulary (Herihor) and foreign chiefs (Libyans, Nubians, Persians, Macedonians) who rose to the throne.',
  { h: 'Co-regency' },
  'In several periods the older pharaoh associated his heir with the throne during his lifetime, in a **co-regency**, to ensure the transfer of power. The surest case is that of **Amenemhat I and Senusret I**, in the 12th Dynasty. Others, such as **Hatshepsut and Thutmose III**, are situations of joint rule rather than co-regencies in the strict sense. Whether co-regencies existed between **Amenhotep III and Akhenaten**, between **Akhenaten and Smenkhkare** and between **Seti I and Ramesses II** (who was already crown prince and regent) is debated by Egyptologists, and changes the chronology of the Amarna period.',
  { h: 'The harem and the Great Royal Wife' },
  'The king had a **principal wife**, the “Great Royal Wife” (hemet-nesut-weret), and several other wives and concubines. The **harem** (per-khener, “house of the enclosures”) was not just a place for women: it was an institution with lands, weaving workshops and staff. Pharaohs married foreign princesses to seal alliances, from Mitanni, Babylon and the Hittites, but, according to a letter of Amenhotep III to the king of Babylon, the pharaoh’s daughters were **not given in marriage to foreign kings**. Ramesses II was an exception: he married a Hittite princess in his 34th regnal year.',
  { h: 'Conspiracies, murders and usurpations' },
  'Despite the image of absolute power, some pharaohs were assassinated. Amenemhat I was probably killed by palace conspirators. In the time of Ramesses III, a **harem conspiracy**, in which a secondary wife (Tiye) and her son (Pentaweret) tried to put him on the throne, is documented in the **Judicial Papyrus of Turin**, with the names and sentences of the conspirators. In 2012 a CT study of the mummy of Ramesses III showed a deep cut in the throat, which explains his death; but it is not known whether the pharaoh died immediately.',
  { h: 'Damnatio memoriae: erasing a king' },
  'Erasing someone’s name and image meant, for the Egyptians, destroying their existence in the afterlife. The best-known cases are those of **Hatshepsut**, whose images and name were hammered out and removed, not immediately after her death but some 20 years later, in the reign of Thutmose III (or after); and of **Akhenaten** and the Amarna kings, who were left out of the royal lists of Abydos and Saqqara. The reasons in each case are debated: for Hatshepsut, the view today leans more towards a question of **succession** (securing the rights of Amenhotep II) than personal revenge.',
  { img: 'efa-akhenaton-familia', leg: 'Stela of Akhenaten, Nefertiti and three daughters, Neues Museum, Berlin (ÄM 14145).' },
  { h: 'The king’s death and funeral' },
  'The king’s death was a state event. The body was embalmed (mummification lasted about 70 days), and the funeral included a procession, the **opening of the mouth** ceremony (a ritual in which the senses were restored to the dead so that he could eat, speak and breathe in the afterlife) and placing in the tomb, with furniture, jewellery and food for eternity. From the Old to the Middle Kingdom the royal tomb was normally a **pyramid**; in the New Kingdom the kings were buried in the **Valley of the Kings**, in rock-cut tombs, with the funerary temples separate, on the plain.',
  { img: 'efa-funeral-real', leg: 'New Kingdom royal funeral procession in the Theban necropolis: gilded shrine on an ox-drawn sledge, priests, mourners and offerings. AI-generated illustration.' },
  { h: 'The pharaohs at war' },
  'Many of the relief scenes show the king **striking an enemy** by the hair, an image that goes back to the Narmer Palette. It is more ritual than descriptive: the king always triumphs. In practice, the pharaohs of the New Kingdom led armies of infantry, archers and **war chariots**; conducted campaigns in Nubia, Libya and Syria-Palestine; and formed a professional army larger than in earlier periods, in which foreigners played an important role.',
  { h: 'Administration: the vizier and the officials' },
  'The pharaoh’s right hand was the **vizier** (tjaty), who headed justice, administration and public works; in the New Kingdom there were two (Upper and Lower Egypt). There was also the “Treasurer”, the “Overseer of the Granaries”, the governors of each **nome** (province), the scribes and the army commanders. Officials were rewarded with lands, offices and tombs.',
  { h: 'The pharaoh’s economy' },
  'The state collected **taxes in kind** (grain, linen, cattle, labour) and stored them in granaries and warehouses of the palace and the temples. There was no coinage until the Late Period (the first Egyptian coins appear under the Persians and the Greeks): trade was done by **weights** (the deben, of copper or silver). The pharaoh’s wealth came from agriculture, the gold of Nubia, the mines of Sinai and the eastern desert, trade and, in the New Kingdom, foreign tribute.',
  { h: 'The pharaohs and foreigners' },
  'Egyptian kings received or fought neighbours: Nubians, Libyans, Asiatics, Hittites, Assyrians, Persians. There were also **foreign** pharaohs who became Egyptian in ceremonial: the **Hyksos** (of Asiatic origin), the **Libyans**, the **Nubians** (25th Dynasty), the **Persians** (27th and 31st Dynasties) and the **Macedonians** (Ptolemies). Each group adopted the pharaoh’s titulary and insignia, which shows the strength of the institution.',
  { h: 'The pharaoh, religion and the temples' },
  'The king was responsible for **building and maintaining the temples**: it was his duty and his means of propaganda. Reliefs show him making offerings to the gods, and inscriptions record his gifts of land, cattle and slaves. The temples, in turn, had great wealth and power, and in the New Kingdom the priesthood of **Amun** at Thebes became almost a rival of the king. At the end of the New Kingdom, the high priests of Amun governed the south.',
  { h: 'The king’s image and portrait' },
  'Royal portraits are **idealised**: the king is always young, strong and serene. But there are exceptions: the statues of **Senusret III** show a grave, weary face; those of **Akhenaten**, with an elongated face and wide belly and hips, are of a unique style; those of **Ramesses II**, who lived almost 90 years, always show a young king. To identify a king, what counts is the **inscribed name** rather than the face.',
  { h: 'The table of the 31 dynasties (Shaw’s chronology, 2000)' },
  'The following list follows the chronology of **Ian Shaw (2000)**. All dates are approximate and the numbering of the dynasties is Manetho’s. Some dynasties were contemporary (for example the 14th, 15th, 16th and 17th, and the 22nd, 23rd, 24th and 25th), so the dates do not add up.',
  { h: 'Predynastic, Thinite Period and Old Kingdom' },
  { tabela: { cab: ['Dynasty', 'Dates (BC)', 'Capital', 'Important kings and events'], linhas: [
    ['Dynasty 0', 'c. 3200 – 3100', 'Abydos, Hierakonpolis', 'Chiefs such as “Scorpion”; formation of the state'],
    ['Dynasty 1', 'c. 3100 – 2890', 'Memphis / Abydos', 'Narmer, Aha, Djer, Den, Qaa; hieroglyphic writing; Merneith'],
    ['Dynasty 2', 'c. 2890 – 2686', 'Memphis / Abydos', 'Peribsen and Khasekhemwy, Horus–Seth rivalry'],
    ['Dynasty 3', 'c. 2686 – 2613', 'Memphis', 'Djoser and Imhotep; Step Pyramid; Huni'],
    ['Dynasty 4', 'c. 2613 – 2494', 'Memphis', 'Snefru, Khufu, Djedefre, Khafre, Menkaure; Giza pyramids'],
    ['Dynasty 5', 'c. 2494 – 2345', 'Memphis', 'Userkaf, Sahure, Niuserre, Unas; sun temples; Pyramid Texts'],
    ['Dynasty 6', 'c. 2345 – 2181', 'Memphis', 'Teti, Pepi I, Merenre, Pepi II; end of the Old Kingdom'],
    ['Dynasties 7 and 8', 'c. 2181 – 2160', 'Memphis', 'Ephemeral kings, of whom little is known; start of the 1st Intermediate Period']
  ] } },
  { h: 'First Intermediate Period and Middle Kingdom' },
  { tabela: { cab: ['Dynasty', 'Dates (BC)', 'Capital', 'Important kings and events'], linhas: [
    ['Dynasties 9 and 10', 'c. 2160 – 2025', 'Herakleopolis', 'Khety (Akhtoy); rivalry with Thebes'],
    ['Dynasty 11', 'c. 2125 – 1985', 'Thebes', 'Intef I to III; Mentuhotep II reunifies (c. 2055)'],
    ['Dynasty 12', 'c. 1985 – 1773', 'Itjtawy', 'Amenemhat I, Senusret I to III, Amenemhat III, Sobekneferu'],
    ['Dynasty 13', 'c. 1773 – c. 1650', 'Itjtawy, later Thebes', 'More than 50 kings, many ephemeral; Sobekhotep and Neferhotep'],
    ['Dynasty 14', 'c. 1773 – c. 1650', 'Xois (Delta)', 'Local Delta kings, contemporary with the 13th']
  ] } },
  { h: 'Second Intermediate Period and New Kingdom' },
  { tabela: { cab: ['Dynasty', 'Dates (BC)', 'Capital', 'Important kings and events'], linhas: [
    ['Dynasty 15 (Hyksos)', 'c. 1650 – 1550', 'Avaris', 'Apophis, Khyan; kings of Asiatic origin'],
    ['Dynasty 16', 'c. 1650 – 1580', 'Thebes', 'Kings of the south, poorly documented'],
    ['Dynasty 17', 'c. 1580 – 1550', 'Thebes', 'Seqenenre Tao, Kamose; start of the war against the Hyksos'],
    ['Dynasty 18', 'c. 1550 – 1295', 'Thebes (later Amarna)', 'Ahmose I, Hatshepsut, Thutmose III, Amenhotep III, Akhenaten, Tutankhamun, Ay, Horemheb'],
    ['Dynasty 19', 'c. 1295 – 1186', 'Pi-Ramesses', 'Ramesses I, Seti I, Ramesses II, Merneptah, Twosret'],
    ['Dynasty 20', 'c. 1186 – 1069', 'Pi-Ramesses', 'Setnakht, Ramesses III to XI; end of the New Kingdom']
  ] } },
  { h: 'Third Intermediate Period and Late Period' },
  { tabela: { cab: ['Dynasty', 'Dates (BC)', 'Capital', 'Important kings and events'], linhas: [
    ['Dynasty 21', 'c. 1069 – 945', 'Tanis', 'Smendes, Psusennes I; high priests of Amun at Thebes'],
    ['Dynasty 22 (Libyan)', 'c. 945 – 715', 'Tanis, Bubastis', 'Shoshenq I, Osorkon I, Osorkon II'],
    ['Dynasty 23', 'c. 818 – 715', 'Leontopolis, Thebes', 'Kings rival to the 22nd'],
    ['Dynasty 24', 'c. 727 – 715', 'Sais', 'Tefnakht, Bakenrenef'],
    ['Dynasty 25 (Nubian)', 'c. 747 – 656', 'Napata, Memphis, Thebes', 'Piye, Shabaka, Shebitku, Taharqa, Tantamani'],
    ['Dynasty 26 (Saite)', '664 – 525', 'Sais', 'Psamtik I, Necho II, Apries, Amasis (Ahmose II), Psamtik III'],
    ['Dynasty 27 (Persian)', '525 – 404', 'Memphis (satrapy)', 'Cambyses, Darius I, Xerxes, Artaxerxes; Egypt as a satrapy'],
    ['Dynasty 28', '404 – 399', 'Sais', 'Amyrtaeus, the only king of this dynasty'],
    ['Dynasty 29', '399 – 380', 'Mendes', 'Nepherites I, Hakor'],
    ['Dynasty 30', '380 – 343', 'Sebennytos', 'Nectanebo I and Nectanebo II, the last native Egyptian king'],
    ['Dynasty 31 (Persian)', '343 – 332', 'Memphis', 'Artaxerxes III, Darius III; second Persian domination'],
    ['Macedonian kings and Ptolemies', '332 – 30', 'Alexandria', 'Alexander, Ptolemy I to XV, Cleopatra VII; outside Manetho’s 31 dynasties']
  ] } },
  { caixa: 'Debates and divergences in this table', texto: 'The existence and order of some kings of Dynasty 0, of Dynasties 7 to 8 and of Dynasties 13 to 17 are **very uncertain**. The 16th Dynasty may be a group of Theban kings and other kings of the south. The division between the 22nd, 23rd and 24th is also debated, and some Egyptologists join or separate dynasties differently. The date limits given here may be **decades off** before the Middle Kingdom and **a few years off** in the New Kingdom. Dynasty 1 is dated here from c. 3100 BC (Narmer, by the usual dating); Shaw (2000) has it begin around 3000 BC.' }
];

const personalidades = [
  'These 30 pharaohs and queens were chosen because they shaped the history of Egypt or the memory of modern times. Dates are approximate (Shaw’s chronology, 2000); where something is legend, tradition or debate, it says so.',
  { h: 'Narmer (c. 3100 BC)' },
  'King of the end of the Predynastic Period, known above all for the **Narmer Palette**, found at Hierakonpolis in 1898, which shows him with both the white and the red crown. He was probably buried at Abydos. Egyptian tradition credited the unification to a “Menes” who may be Narmer or his successor Aha: this is debated, and unification was probably a longer process.',
  { h: 'Djoser (c. 2667 – 2648 BC)' },
  'King of the 3rd Dynasty (the second or the first, depending on the king list followed). With his architect **Imhotep** he raised at Saqqara the **Step Pyramid**, the first great stone building in the world. A late inscription (the Famine Stela, written already in Ptolemaic times) links him to a legendary seven-year drought: this is tradition, not history.',
  { h: 'Snefru (c. 2613 – 2589 BC)' },
  'Founder of the 4th Dynasty. He built at Meidum and at Dahshur (the **Bent Pyramid** and the **Red Pyramid**, the first smooth-sided one): he was the king who raised the most stone in Egypt, and the one who worked out how to make a true pyramid. The Westcar Papyrus, written much later, presents him as an affable king. He was Khufu’s father.',
  { h: 'Khufu, “Cheops” (c. 2589 – 2566 BC)' },
  'Builder of the **Great Pyramid of Giza**, about 146 m high, with about 2.3 million blocks. The only image of him that has survived is an **ivory statuette** 7.5 cm tall. Herodotus, about two thousand years later, described him as a tyrant who closed the temples and used slaves; this is a tradition with no archaeological basis, and the finds at Giza show paid workers. In 2013, papyri of an official, **Merer**, were found at **Wadi el-Jarf**, recording the transport of limestone for the pyramid: the oldest inscribed papyri known, and the most direct written testimony of its construction.',
  { img: 'efa-queops-estatueta', leg: 'Ivory statuette of Khufu, Egyptian Museum (JE 36143).' },
  { h: 'Khafre, “Chephren” (c. 2558 – 2532 BC)' },
  'Son of Khufu and builder of the second pyramid at Giza, which looks the largest because it stands on higher ground. The **Sphinx** is usually attributed to him, although the identification, like its date, is debated. His diorite statue, with the falcon Horus protecting him, is a masterpiece of Egyptian sculpture.',
  { img: 'efa-quefren-estatua', leg: 'Diorite statue of Khafre, Egyptian Museum (JE 10062).' },
  { h: 'Menkaure, “Mycerinus” (c. 2532 – 2503 BC)' },
  'Son of Khafre. His pyramid is the smallest of the three at Giza (about 65 m), but with a granite casing. His group statues are famous: the **triads** (the king accompanied by the goddess Hathor and by deities of the nomes) and the **dyad** in the **Museum of Fine Arts, Boston**, with the king and his queen. Herodotus made him a good king, in contrast to his father.',
  { img: 'efa-miquerinos-triade', leg: 'Menkaure and queen, Museum of Fine Arts, Boston (11.1738).' },
  { h: 'Pepi II (c. 2278 – 2184 BC)' },
  'He came to the throne as a child and, according to the Turin Canon, reigned more than 90 years, which would be the longest reign in Egyptian history; but contemporary records only reach year 62 and many Egyptologists propose about 64 years. A letter of his, to an expedition leader, asking him to bring back a “dancing dwarf” from the south, is famous. In his time the power of local governors grew and, after his death, the Old Kingdom state fell apart.',
  { h: 'Mentuhotep II (c. 2055 – 2004 BC)' },
  'A Theban king who, after a civil war, defeated Herakleopolis and **reunified Egypt** around 2055 BC, beginning the **Middle Kingdom**. He had a new funerary temple built at Deir el-Bahari, which served as a model for Hatshepsut’s. In his statues he appears with the red crown and a face painted black, the colour of Osiris and fertility.',
  { h: 'Senusret III (c. 1870 – 1831 BC)' },
  'A 12th Dynasty king who strengthened central power, reduced the autonomy of governors and fortified the Nubian border, with fortresses at Buhen and Semna. A stela of his at Semna warns that no Nubian should pass. He is remembered for his portraits with a **grave face, heavy eyes and firm mouth**, which depart from the eternal youth of earlier kings. He built a pyramid at Dahshur and a cenotaph at Abydos.',
  { img: 'efa-sesostris-iii-cabeca', leg: 'Fragment of the face of Senusret III, Metropolitan Museum (26.7.1394).' },
  { h: 'Amenemhat III (c. 1831 – 1786 BC)' },
  'One of the longest-reigning (about 45 years) and most prosperous kings of the Middle Kingdom. He carried out large irrigation works in the **Fayum**, sent expeditions to the turquoise mines of Sinai and built two pyramids: one at Dahshur, which cracked, and another at **Hawara**. His funerary temple, which the Greeks called the “Labyrinth”, has not come down to us in good condition. With his immediate successors (Amenemhat IV and Sobekneferu) the 12th Dynasty came to an end.',
  { h: 'Sobekneferu (c. 1777 – 1773 BC)' },
  'Probably a daughter of Amenemhat III and the **first woman known with certainty to have reigned as pharaoh**. She ruled for only about four years, the end of the 12th Dynasty. She used a mixture of male and female insignia. Few monuments of hers remain, and a few headless statues. Her name means “the beauty of Sobek”, the crocodile god.',
  { h: 'Ahmose I (c. 1550 – 1525 BC)' },
  'Founder of the 18th Dynasty and of the **New Kingdom**. He took Avaris and expelled the Hyksos, then extended Egyptian power to Nubia and southern Levant. His brother **Kamose** had already begun the war and may deserve more credit than tradition gives him, which is debated. His mummy was found in the Deir el-Bahari cache. His mother, **Ahhotep I**, and wife, **Ahmose-Nefertari**, were figures of great prestige, the latter venerated as a goddess at Thebes.',
  { h: 'Hatshepsut (c. 1473 – 1458 BC)' },
  'Daughter of Thutmose I and widow of Thutmose II, she was regent for the young Thutmose III and, c. 1473 BC, had herself crowned **king**, with the full titulary and the false beard. She reigned about 15 years, in a time of peace and prosperity, with the expedition to the land of **Punt**, the building of the temple of **Deir el-Bahari** and the obelisks of Karnak. She had the support of the official **Senenmut**. Her images and name were erased, but decades after her death. The identification of her mummy (KV60), proposed in 2007, is accepted by many but not by all.',
  { h: 'Thutmose III (c. 1479 – 1425 BC)' },
  'King for 54 years, but he ruled alone only from c. 1458 BC. He led about **17 campaigns** in Syria-Palestine, the most famous at **Megiddo**, described in the annals of the temple of Karnak. He created the largest Egyptian empire, and was a great builder. Historians have sometimes called him the “Napoleon of Egypt”, a comparison that says more about the taste of the time than it informs. Two of his obelisks are now in London and New York (the “Cleopatra’s Needles”).',
  { img: 'efa-tutmes-iii-estatua', leg: 'Greywacke statue of Thutmose III, Luxor Museum.' },
  { h: 'Amenhotep III (c. 1390 – 1352 BC)' },
  'He reigned nearly 38 years, in the period of greatest splendour and wealth of Egypt. He built the temple of **Luxor**, his funerary temple (of which the **Colossi of Memnon** remain), the palace of **Malqata** and left hundreds of statues, among them those of the lioness goddess **Sekhmet**. He married **Tiye**, who held great power, and foreign princesses. His correspondence with the kings of Mitanni and Babylon in the **Amarna letters** shows the diplomacy of the Bronze Age.',
  { h: 'Akhenaten (c. 1352 – 1336 BC)' },
  'Son of Amenhotep III, he was called Amenhotep IV until the 5th year of his reign, when he changed his name to **Akhenaten** (“He who serves the Aten”) and founded the city of **Akhetaten**. He raised the solar disc **Aten** above the other gods and closed the traditional cults, which many describe, debatably, as “monotheism”. He changed art, which became more naturalistic (and, in some cases, extremely stylised). After his death the cult was abandoned and his name erased. Theories linking him to Moses or to biblical monotheism have no solid historical basis.',
  { h: 'Nefertiti (14th century BC)' },
  'Great Royal Wife of Akhenaten, shown beside him as an equal, and one of the best-known women of antiquity, thanks to the **bust** found at Amarna in December 1912 by Ludwig Borchardt’s German expedition, in the workshop of the sculptor Thutmose. Her name means “the beautiful one has come”. Her parents are not known with certainty. She disappears from the inscriptions around year 12 to 14 of Akhenaten, and it is debated whether she died or became co-regent under the name Neferneferuaten. Her tomb has not yet been found, and the identification of a mummy as hers (the “Younger Lady” of KV35) is rejected by most Egyptologists.',
  { img: 'efa-nefertiti-busto', leg: 'Bust of Nefertiti, Neues Museum, Berlin (ÄM 21300).' },
  { h: 'Tutankhamun (c. 1336 – 1327 BC)' },
  'He came to the throne aged about 9 and died around 18 or 19. He restored the cult of Amun and changed his name (originally Tutankhaten). He was almost unknown until **Howard Carter** found his tomb (**KV62**) on 4 November 1922, practically intact, with about 5400 objects. DNA studies (2010) suggest that he was the son of the king of mummy KV55 (probably Akhenaten) and of a sister of his; the cause of death is debated (an infected broken leg, malaria, bone disease). The “curse of the pharaoh” is an invention of the press.',
  { img: 'efa-tutankhamon-trono', leg: 'Detail of the backrest of Tutankhamun’s golden throne, photographed at the Egyptian Museum in Cairo (JE 62028).' },
  { h: 'Horemheb (c. 1323 – 1295 BC)' },
  'Before becoming king he was a general under Tutankhamun and Ay. He rose to the throne without belonging to the royal family and closed the 18th Dynasty, restoring order after Amarna, and reforming justice and administration with his **Edict**. He demolished the monuments of Akhenaten and reused them as filling for his pylons. As he had no children, he chose the general **Ramesses I** to succeed him. He has a tomb at Saqqara (as general) and another in the Valley of the Kings (KV57).',
  { h: 'Seti I (c. 1294 – 1279 BC)' },
  'Second king of the 19th Dynasty, he restored Egyptian power in Syria and campaigned against the Hittites and Libyans. He completed the great **Hypostyle Hall of Karnak** and built the temple of **Abydos**, where the **Abydos King List** is found. His tomb in the Valley of the Kings (**KV17**) is one of the longest and most beautiful in the valley, discovered by Giovanni Belzoni in 1817. His mummy is among the best preserved.',
  { img: 'efa-seti-i-abidos', leg: 'Relief of Seti I in the temple at Abydos.' },
  { h: 'Ramesses II, “the Great” (c. 1279 – 1213 BC)' },
  'He reigned 66 years and lived almost 90. He fought the Hittites at the battle of **Qadesh** (c. 1274 BC), which he presented as a victory but which was more of a draw; then, c. 1259 BC, he signed with the Hittite king **Hattusili III** the oldest **peace treaty** whose text survives. He founded **Pi-Ramesses**, built the **Ramesseum** and the temples of **Abu Simbel**, and completed the hall at Karnak. He had many wives and more than 100 children. His mummy was sent to Paris in 1976 to treat a fungus, and, according to a much-repeated story, entered France with an Egyptian passport listing his occupation as “king (deceased)”. Shelley’s poem Ozymandias (1818) is an evocation of Ramesses II, whose throne name, Usermaatra, the Greeks transcribed as “Ozymandias”.',
  { h: 'Nefertari (13th century BC)' },
  'Great Royal Wife of Ramesses II and the most honoured of his wives: for her the small temple at Abu Simbel, dedicated to the goddess Hathor, was built, and her tomb in the Valley of the Queens (**QV66**), one of the most beautiful in Egypt, with very well preserved paintings. Her name means “the beautiful companion”. She wrote letters to the Hittite queen Puduhepa. Her parents are not known; her tomb was restored from 1986 to 1992.',
  { img: 'efa-nefertari-tumba', leg: 'Painting in Nefertari’s tomb (QV66), Valley of the Queens.' },
  { h: 'Ramesses III (c. 1184 – 1153 BC)' },
  'The last great king of the New Kingdom. He defeated the **Sea Peoples** and the Libyans, and built the temple of **Medinet Habu**. In his reign took place one of the first documented **strikes** in history: the craftsmen of Deir el-Medina, over lack of rations. He was the target of a harem conspiracy (Judicial Papyrus of Turin). A 2012 CT study showed a deep cut in the throat of his mummy. The **Great Harris Papyrus** is a long document of his reign.',
  { h: 'Shoshenq I (c. 945 – 924 BC)' },
  'A descendant of Libyan chiefs, he founded the **22nd Dynasty**, reunified Egypt and appointed his son as high priest at Thebes, to control the south. Around 925 BC he led a campaign in the Levant, recorded on the walls of the temple of Karnak (the **Bubastite Portal**), with a list of conquered cities. He is generally identified with the **Shishak** of the Bible, who attacked Jerusalem, but the identification has been debated.',
  { h: 'Piye (c. 747 – 716 BC)' },
  'King of Napata (Nubia), he came out of the south and conquered Egypt around 730 BC, according to his victory stela. He founded the 25th Dynasty. He chose to return to Napata, leaving governors in Egypt. He was devoted to Amun and restored the temples. He was buried in a pyramid at El-Kurru.',
  { h: 'Taharqa (c. 690 – 664 BC)' },
  'The most important Nubian king of the 25th Dynasty. He reigned 26 years and built at Karnak, Kawa and Napata. He defended Egypt against the Assyrians: he was defeated by **Esarhaddon** in 671 BC (Memphis taken) and by **Ashurbanipal** soon after. He withdrew to the south and died in 664 BC, and was buried in a pyramid at Nuri. In the Bible he is “Tirhakah”, king of Cush.',
  { h: 'Psamtik I (664 – 610 BC)' },
  'Founder of the 26th (Saite) Dynasty. He began as a vassal of the Assyrians, and c. 656 BC unified the country and expelled them, taking advantage of the wars in Assyria. He recruited **Greek and Carian** mercenaries and opened Egypt to Greek trade (the city of **Naukratis**). He reigned 54 years, and his time was one of renaissance of ancient art and culture, with styles that imitated the Old Kingdom.',
  { h: 'Nectanebo II (c. 360 – 343 BC)' },
  'The **last native Egyptian pharaoh**. He carried out great temple works (for example at Philae and Sebennytos). In 343 BC he lost the war against the Persian king Artaxerxes III and fled south, probably to Nubia. Later a legend, the Alexander Romance, made him the true father of Alexander the Great, which has no historical basis.',
  { img: 'efa-nectanebo-ii-falcao', leg: 'Nectanebo II protected by the falcon Horus, Metropolitan Museum (34.2.1).' },
  { h: 'Ptolemy I Soter (c. 367 – 283 BC)' },
  'A general of Alexander the Great, he became **satrap of Egypt** in 323 BC, brought Alexander’s body to Egypt and proclaimed himself king in 305 BC, founding the **Ptolemaic** dynasty. He chose **Alexandria** as capital and favoured the development of the **Museum**, to which the Library is linked (the founding of the Library is attributed to him or to his son, and is debated). He wrote a history of Alexander’s campaigns, which is lost. He appears on coins and in temples, with the ceremonial of a pharaoh.',
  { img: 'efa-ptolemeu-moeda', leg: 'Reverse of a silver tetradrachm of Ptolemy I Soter, with an eagle on a thunderbolt.' },
  { h: 'Cleopatra VII (69 – 30 BC)' },
  'A queen of Macedonian origin, the last of the Ptolemies and the last to reign over Egypt as pharaoh. She came to the throne in 51 BC, at first with her brothers, and was driven out by them; with the support of **Julius Caesar** she regained power in 47 BC, and had a son by him, **Ptolemy Caesar** (Caesarion). After Caesar she allied with **Mark Antony**, with whom she had three children. They were defeated by Octavian, the future Augustus, at Actium (31 BC). Cleopatra died in 30 BC, probably by suicide (the story of the asp is from the Roman tradition); her tomb has never been found. According to Plutarch, she was the first Ptolemaic queen to speak Egyptian.',
  { h: 'And the others?' },
  'Many other important kings remain untold: Userkaf, Amenemhat I, Senusret I, Kamose, Amenhotep II, Thutmose IV, Merneptah, Twosret, Osorkon II, Necho II, Darius I, Ptolemy II and others. The history of Egypt knows **hundreds of royal names**, and many are known only from one inscription or from an entry in the king lists.'
];

const legado = [
  { h: 'What they left us' },
  { lista: [
    '**Monuments:** the pyramids, the temples of Karnak, Luxor and Abu Simbel, the Valley of the Kings and the colossi were almost all built on the orders of the pharaohs.',
    '**Official art:** the convention of the king in profile and frontal view, of ideal proportions and ritual gesture, lasted for three thousand years.',
    '**Lists and annals:** the royal lists allow the chronology to be reconstructed, and the annals of Thutmose III or Ramesses II give us descriptions of wars and politics.',
    '**Ideas of sacred kingship:** the king as shepherd of his people, as son of the god and mediator, influenced the Ptolemies, the Roman emperors and, indirectly, the idea of Christian kingship.',
    '**The word “pharaoh”,** which passed into European languages, and the fame of the kings, from Tutankhamun to Cleopatra.'
  ] },
  { h: 'The king lists and Manetho' },
  'What we know of the order of the kings comes from Egyptian **royal lists**, which complement one another and do not always agree. The **Palermo Stone** (5th Dynasty, in fragments) records the kings of the Predynastic Period and the Old Kingdom, with the height of the Nile flood in each year. The **Turin Papyrus** (or Turin Royal Canon), from the time of Ramesses II, listed more than 300 names and the length of the reigns, but is very fragmentary. The **Abydos List**, in the temple of Seti I, shows 76 names, in which, for example, Hatshepsut and the Amarna kings are missing. The **Karnak List** and the **Saqqara List** are others.',
  { img: 'efa-pedra-palermo', leg: 'Palermo Stone, Museo Archeologico Regionale Antonio Salinas.' },
  { img: 'efa-lista-turim', leg: 'Fragment of the Turin Royal Canon, Museo Egizio (Cat. 1874).' },
  { img: 'efa-lista-abidos', leg: 'Abydos King List, temple of Seti I.' },
  'The priest **Manetho** wrote, in the 3rd century BC, the Aegyptiaca, a history of Egypt in Greek, divided into 30 dynasties. The text is lost and is known only from summaries by later authors (Josephus, Africanus, Eusebius), with errors and variants. But its division into dynasties remains the basis of Egyptology.',
  { h: 'The royal mummies' },
  'Of the roughly 60 tombs of the Valley of the Kings, almost all had already been plundered in antiquity. Around 1000 BC the priests of Amun gathered the mummies of the New Kingdom kings and hid them in caches. The most famous was that at **Deir el-Bahari** (TT320), found in 1881, with more than 40 royal and priestly mummies, among them Ahmose I, Thutmose III, Seti I and Ramesses II. In 1898 **Victor Loret** found another cache, in the tomb of **Amenhotep II** (KV35), with other kings, among them Amenhotep III, Merneptah and Ramesses IV to VI.',
  { img: 'efa-mumia-ramses-ii', leg: 'Mummy of Ramesses II, historical photograph; now in the National Museum of Egyptian Civilization, Cairo.' },
  { h: 'The tomb of Tutankhamun' },
  'On 4 November 1922 **Howard Carter**, funded by Lord Carnarvon, found the entrance to tomb **KV62**. It was the only New Kingdom pharaoh’s tomb found almost intact, with about **5400 objects**, and gave rise to “**Tutmania**”, a worldwide craze. For the first time, the complete collection of the tomb has been brought together in a single place, in the Grand Egyptian Museum. The “curse” is a creation of the press of the time.',
  { h: 'DNA and CT: the pharaohs as patients' },
  'Since the 2000s, CT scans and DNA tests have made it possible to study royal mummies without opening them. In **2010**, a study led by Zahi Hawass suggested the kinship relations of Tutankhamun’s family (father, mother and grandparents) and illnesses of the king, such as malaria. These results, like the 2012 work on **Ramesses III**, are much debated by specialists, who point to the difficulties of ancient DNA.',
  { h: 'The parade of the pharaohs (2021)' },
  'On **3 April 2021**, 22 royal mummies (18 kings and 4 queens) were carried in procession from the Egyptian Museum in Tahrir Square to the **National Museum of Egyptian Civilization** in Fustat, Cairo, in an event broadcast around the world and known as the “Pharaohs’ Golden Parade”.',
  { h: 'The decipherment of hieroglyphs and the names of kings' },
  'It was the **cartouches** that allowed **Jean-François Champollion**, in 1822, to decipher hieroglyphs: by comparing the names of **Ptolemy** and **Cleopatra** on an obelisk from Philae and on the Rosetta Stone, he recognised the sounds of each sign, and then read the names of Ramesses and Thutmose. From then on it was possible to read the kings’ names on the monuments.',
  { h: 'The pharaoh in modern culture' },
  'The pharaohs have been part of the Western imagination since the 19th century: Shelley’s poem Ozymandias (1818), Verdi’s opera Aida (1871), the “Egyptomania” of the world’s fairs, cinema (the various versions of Cleopatra) and, more recently, the Tutmania of the exhibitions. They almost always oversimplify: pharaohs were rarely the tyrants of the movies, and the pyramids were not built by slaves or by extraterrestrials, a pseudo-archaeological hypothesis with **no basis whatever**.',
  { h: 'Open questions' },
  { lista: [
    'Where is the tomb of **Nefertiti**? Radar searches in KV62, in 2015 to 2018, did not confirm hidden chambers.',
    'Who was **Neferneferuaten**, the ruler after Akhenaten: Nefertiti, another figure or two different people?',
    'What was the relationship between **Amenhotep III** and **Akhenaten**: was there a co-regency? If so, how long?',
    'Where is the tomb of **Cleopatra VII** and of **Mark Antony**?',
    'Who was, in fact, the “**Menes**” of tradition, and how did the unification of Egypt happen?'
  ] },
  { h: 'Where to see the pharaohs' },
  { lista: [
    '**Cairo:** the Egyptian Museum in Tahrir Square (Narmer, Djoser, Khufu, Khafre, Mentuhotep II); the National Museum of Egyptian Civilization (royal mummies); and the **Grand Egyptian Museum** at Giza, with the whole treasure of Tutankhamun.',
    '**Luxor:** the Luxor Museum (Thutmose III, Amenhotep III), the temples of Karnak and Luxor, the Valley of the Kings and of the Queens.',
    '**Berlin:** the Neues Museum (Nefertiti and the family of Akhenaten).',
    '**Turin:** the Museo Egizio (Ramesses II, the Royal Papyrus).',
    '**Paris, London and New York:** the Louvre, the British Museum and the Metropolitan (Hatshepsut, Nectanebo II and others).'
  ] },
  { h: 'Recommended reading' },
  { lista: [
    '**Ian Shaw (ed.),** The Oxford History of Ancient Egypt (2000), the reference chronology of this page.',
    '**Toby Wilkinson,** The Rise and Fall of Ancient Egypt (2010), a political history of the pharaohs.',
    '**Aidan Dodson and Dyan Hilton,** The Complete Royal Families of Ancient Egypt (2004), a reference work on the kings and their families.',
    '**Erik Hornung, Rolf Krauss and David Warburton (eds.),** Ancient Egyptian Chronology (2006), the most complete study of the chronology.'
  ] }
];

const quiz = [
  { p: 'What does the Egyptian word “per-aa”, from which “pharaoh” comes, originally mean?', op: ['Son of Ra', 'The Great House (the palace)', 'Lord of the Two Lands', 'The Shepherd'], certa: 1, exp: 'Per-aa meant the palace; only in the New Kingdom did it come to be used for the king as well.' },
  { p: 'Of which god was the living pharaoh the embodiment?', op: ['Osiris', 'Anubis', 'Horus', 'Seth'], certa: 2, exp: 'The living king was Horus; after death he was identified with Osiris.' },
  { p: 'Which concept represents the order, truth and justice that the pharaoh had to maintain?', op: ['Ka', 'Ma’at', 'Isfet', 'Ba'], certa: 1, exp: 'Ma’at was the opposite of isfet, chaos.' },
  { p: 'How many names made up the full royal titulary?', op: ['Two', 'Three', 'Five', 'Seven'], certa: 2, exp: 'Horus name, Two Ladies, Golden Horus, throne name (prenomen) and birth name (nomen).' },
  { p: 'Which crown was that of Upper Egypt?', op: ['The red one (Deshret)', 'The white one (Hedjet)', 'The blue one (Khepresh)', 'The Atef'], certa: 1, exp: 'The Hedjet, white and conical; the red one was that of Lower Egypt.' },
  { p: 'What is the Heb-Sed?', op: ['A famous battle', 'The king’s jubilee festival of renewal', 'A type of tomb', 'A god'], certa: 1, exp: 'Traditionally celebrated in the 30th year and then every three or four years.' },
  { p: 'Which king is associated with the first pyramid, the Step Pyramid of Saqqara?', op: ['Khufu', 'Snefru', 'Djoser', 'Pepi II'], certa: 2, exp: 'Djoser (3rd Dynasty), with the architect Imhotep.' },
  { p: 'Who was the first woman known with certainty to have reigned as pharaoh?', op: ['Hatshepsut', 'Cleopatra VII', 'Nefertiti', 'Sobekneferu'], certa: 3, exp: 'Sobekneferu, at the end of the 12th Dynasty, c. 1777 – 1773 BC.' },
  { p: 'Which pharaoh expelled the Hyksos and founded the New Kingdom?', op: ['Ahmose I', 'Mentuhotep II', 'Thutmose III', 'Ramesses II'], certa: 0, exp: 'Ahmose I took Avaris, c. 1550 BC.' },
  { p: 'Which pharaoh founded the city of Akhetaten (Amarna) and imposed the cult of Aten?', op: ['Tutankhamun', 'Amenhotep III', 'Horemheb', 'Akhenaten'], certa: 3, exp: 'Akhenaten, c. 1346 BC, founded the city, which was abandoned soon after his death.' },
  { p: 'Who discovered the tomb of Tutankhamun, in 1922?', op: ['Howard Carter', 'Champollion', 'Belzoni', 'Mariette'], certa: 0, exp: 'Howard Carter, with the financial backing of Lord Carnarvon, on 4 November 1922.' },
  { p: 'With which people did Ramesses II sign the oldest peace treaty whose text survives?', op: ['The Assyrians', 'The Hittites', 'The Libyans', 'The Nubians'], certa: 1, exp: 'Around 1259 BC, with Hattusili III, after the battle of Qadesh.' },
  { p: 'Who was the last native Egyptian pharaoh?', op: ['Psamtik III', 'Nectanebo II', 'Taharqa', 'Amasis'], certa: 1, exp: 'Nectanebo II, 30th Dynasty, who fled from the Persians in 343 BC.' },
  { p: 'Which Egyptian priest divided the kings into 30 dynasties in the 3rd century BC?', op: ['Imhotep', 'Herodotus', 'Manetho', 'Hecataeus'], certa: 2, exp: 'Manetho wrote the Aegyptiaca in Greek, under Ptolemy II.' },
  { p: 'Who died in 30 BC, after the defeat at Actium, and was the last to reign as pharaoh?', op: ['Hatshepsut', 'Cleopatra VII', 'Twosret', 'Arsinoe II'], certa: 1, exp: 'Cleopatra VII; afterwards Egypt became a Roman province.' }
];

export default { visao, linha, mapa, sociedade, personalidades, legado, quiz };
