// CHINA ANTIGA — conteúdo completo em português. A versão inglesa está em dados-en.js (mesma estrutura).
import EN from './dados-en.js';
import { GRUPO } from './grupo.js';
import CRED from './creditos.js';
// Datas aproximadas; a história chinesa só tem datas «seguras» (anuais) a partir de 841 a.C. (início do período Gonghe) e, em rigor, de 722 a.C.; antes disso as cronologias variam consoante os autores. Mongóis têm página própria.
// Imagens: cada {img:'id'} procura o ficheiro  china/img/id.jpg  (ver IMAGENS_CHINA.md para a lista e os prompts).

const visao = [
  { caixa: 'Em resumo', texto: [
    'A **China antiga** é a história da região dos rios **Amarelo** (Huang He) e **Azul** (Yangtzé) desde as primeiras aldeias agrícolas até à conquista mongol e ao fim da dinastia **Yuan**, em 1368 d.C. É uma das poucas civilizações da Antiguidade que, apesar das guerras e das mudanças de dinastia, mantém uma **continuidade** reconhecível: a mesma escrita, as mesmas ideias sobre o governo e a mesma consciência de formar um mundo próprio, o «Tudo sob o Céu» (*Tianxia*).',
    'Neste período a China inventou o **bronze ritual** de uma perfeição técnica espantosa, a **escrita** em ossos e carapaças (a antepassada dos caracteres de hoje), a **filosofia** de Confúcio e do Daoísmo, o primeiro **império unificado** (Qin, 221 a.C.), o **papel**, a **seda** que ligou o mundo pela Rota da Seda, o **exame imperial** para escolher funcionários, a **imprensa**, a **pólvora**, a **bússola** e a **porcelana**. Misturam-se aqui história e lenda: os primeiros «reis» são míticos e damos-lhes o devido lugar.'
  ] },
  { img: 'chi-mapa-regiao', leg: 'Mapa das culturas do Neolítico Médio na China.' },
  { h: 'Onde ficava' },
  'O berço da civilização chinesa é a **Planície Central** (*Zhongyuan*), a bacia média e inferior do **rio Amarelo**, assim chamado pela cor do **loess**, a poeira fina e fértil que o vento trouxe da Ásia Central. É uma terra fácil de lavrar com ferramentas simples, ideal para o **painço**, mas o rio, com cheias catastróficas, obrigou desde cedo a organizar trabalho coletivo, canais e diques. Mais a sul, no vale do **Yangtzé**, cultivava-se **arroz** desde há milhares de anos, e foi aí que, mais tarde, se concentrou a população e a riqueza do país.',
  'A China está protegida por barreiras naturais: desertos e montanhas a oeste (o planalto do Tibete), estepes a norte, o mar a leste. Esse isolamento relativo ajudou a desenvolver uma cultura própria, mas nunca foi total: as estepes foram sempre fonte de comércio e de ameaça (cavaleiros nómadas), e as oásis do Noroeste ligavam a China à Ásia Central e, daí, ao Mediterrâneo.',
  { img: 'chi-yangshao-vaso', leg: 'Vaso de cerâmica pintada Yangshao.' },
  { h: 'Quando existiu' },
  'A chamada «história de cinco mil anos» mistura factos e tradição. Os arqueólogos distinguem culturas pré-históricas e, só a partir dos Shang (c. 1250 a.C.), há escrita que se possa ler. As datas abaixo são aproximadas e, para as mais antigas, **debatidas**.',
  { tabela: { cab: ['Fase', 'Datas aproximadas', 'O que a marca'], linhas: [
    ['Neolítico', 'c. 7000 – 2000 a.C.', 'Aldeias agrícolas: Yangshao (painço, cerâmica pintada), Longshan (cerâmica negra, cidades muradas), Liangzhu (jade, arroz, grande cidade-santuário)'],
    ['Erlitou («Xia»?)', 'c. 1900 – 1500 a.C.', 'Primeiro grande palácio e bronzes; liga-se à lendária dinastia Xia, mas isso continua em debate'],
    ['Shang', 'c. 1600 – 1046 a.C.', 'Reis-sacerdotes, ossos oraculares, bronzes rituais, capital em Anyang'],
    ['Zhou Ocidental', 'c. 1046 – 771 a.C.', 'Mandato do Céu; sistema de feudos'],
    ['Primaveras e Outonos', '770 – 476 a.C.', 'O poder da corte Zhou esvazia-se; Confúcio e o Daoísmo'],
    ['Reinos Combatentes', '475 – 221 a.C.', 'Sete grandes Estados em guerra; Sun Tzu, Mozi, legalistas; ferro e cavalaria'],
    ['Qin', '221 – 206 a.C.', 'Primeiro império unificado; Shi Huangdi; Exército de Terracota'],
    ['Han', '206 a.C. – 220 d.C.', 'Império estável; Rota da Seda; papel; Confucionismo oficial'],
    ['Três Reinos e divisão', '220 – 589', 'Wei, Shu e Wu; invasões do norte; expansão do budismo'],
    ['Sui e Tang', '581 – 907', 'Reunificação; Grande Canal; Chang’an; poesia; imprensa'],
    ['Song', '960 – 1279', 'Revolução económica; pólvora, bússola, tipos móveis, porcelana; Neoconfucionismo'],
    ['Yuan (mongol)', '1271 – 1368', 'Kublai Khan unifica a China sob domínio mongol']
  ] } },
  { img: 'chi-liangzhu-cong', leg: 'Cong de jade da cultura de Liangzhu.' },
  { h: 'Quem eram os chineses antigos?' },
  'Não havia «uma China» étnica ou política antes de 221 a.C. Havia muitas culturas regionais, com línguas diferentes, que se foram fundindo. Os povos da Planície Central chamavam-se a si próprios **Huaxia** («a grande e bela civilização») e olhavam os vizinhos como «bárbaros» (*Yi, Man, Rong, Di*), embora estes fossem muitas vezes aliados, esposas, mercenários e, por fim, conquistadores. O nome **Han**, hoje o do grupo maioritário, vem da dinastia Han; a palavra «China» vem provavelmente do nome da dinastia **Qin**, através do sânscrito e do persa.',
  { h: 'Mito e história' },
  'A tradição chinesa começa com os **Três Soberanos e os Cinco Imperadores**, figuras como **Huangdi**, o «Imperador Amarelo», e **Yu o Grande**, que teria domado as cheias do rio durante treze anos e fundado a dinastia **Xia**. Os chineses de hoje chamam a si próprios, simbolicamente, «descendentes de Yan e de Huang». Os historiadores tratam estas figuras como **lendas** com núcleo simbólico (Yu representa o esforço coletivo contra as cheias). Quanto à dinastia Xia, ainda não se encontrou nenhuma inscrição contemporânea que a confirme: o sítio de **Erlitou** pode ser a sua capital, mas **continua em debate**. A história documentada começa com os **Shang**.',
  { h: 'Porque importam' },
  { lista: [
    '**Continuidade:** a escrita chinesa, em evolução contínua há mais de 3000 anos, é a mais antiga ainda em uso no mundo.',
    '**Ideias:** Confúcio e o Daoísmo moldaram a ética, a política e a arte do Extremo Oriente até hoje.',
    '**Estado:** o império com funcionários escolhidos por exame foi uma invenção chinesa, depois copiada.',
    '**Invenções:** papel, imprensa, pólvora e bússola mudaram o mundo, incluindo a Europa.',
    '**Comércio:** a Rota da Seda ligou a China a Roma, à Pérsia e à Índia.'
  ] },
  { h: 'Hoje' },
  'A China é hoje a segunda maior economia do mundo, e o seu passado, sobretudo o Exército de Terracota e a Grande Muralha, é um dos principais destinos turísticos. A arqueologia chinesa vive um período de grandes descobertas (Liangzhu, Sanxingdui, novos túmulos Han), e as fontes escritas, como os *Anais de Primavera e Outono*, o *Shiji* e os poemas Tang, continuam a ser lidas e citadas.'
];

const linha = [
  'Esta linha do tempo segue os acontecimentos principais da China antiga. As datas são aproximadas; as anteriores a 841 a.C. são sempre debatidas. A história mítica (Huangdi, Yu) aparece assinalada como tal.',
  { linha: [
    { d: 'c. 7000 a.C.', t: 'Os primeiros agricultores', x: 'Em Jiahu (rio Amarelo, c. 7000 a.C.) e em Hemudu (Yangtzé, c. 5500 – 3300 a.C.) há aldeias com **painço** e **arroz**, cerâmica, e flautas de osso. Em Jiahu aparecem sinais gravados em carapaças, cuja natureza é debatida e que não são uma escrita comprovada.' },
    { d: 'c. 5000 – 3000 a.C.', t: 'Cultura de Yangshao', x: 'Aldeias de casas semienterradas, como **Banpo**, perto de Xi’an, com cerâmica pintada, painço e porcos. Nas tradições populares, é a «cultura de Huangdi», uma associação sem prova.' },
    { d: 'c. 3300 – 2300 a.C.', t: 'Liangzhu: jade e arroz', x: 'No delta do Yangtzé, a cultura de **Liangzhu** constrói uma cidade com diques e canais, e esculpe milhares de **jades rituais** (*cong* e *bi*). Está na lista do Património Mundial da UNESCO desde 2019.' },
    { d: 'c. 3000 – 1900 a.C.', t: 'Longshan e as cidades muradas', x: 'Em todo o norte, a cultura de **Longshan** (cerâmica negra e fina) constrói cidades com muralhas de terra batida, sinal de guerra e de chefes poderosos. Aqui situa-se, na tradição, a era dos mitos de Yao, Shun e Yu.' },
    { d: 'c. 1900 – 1500 a.C.', t: 'Erlitou', x: 'No rio Luo, em Henan, a cidade de **Erlitou** tem o palácio mais antigo da China, uma oficina de bronze e vasos rituais *jue*. Muitos arqueólogos chineses veem aqui a dinastia **Xia**; outros, uma cultura anterior sem nome. É debatido.' },
    { img: 'chi-erlitou-jue', leg: 'Vaso de bronze jue de Erlitou.' },
    { d: 'c. 1600 a.C.', t: 'Começam os Shang', x: 'Segundo a tradição, **Tang** derrota o último rei Xia e funda a dinastia **Shang**. As capitais antigas (Zhengzhou, Yanshi) têm muralhas enormes e bronzes ricos.' },
    { d: 'c. 1300 a.C.', t: 'Anyang, a última capital Shang', x: 'O rei **Pan Geng**, segundo a tradição, muda a capital para **Yin** (perto de Anyang). É aqui que os **ossos oraculares** mostram a primeira escrita chinesa certa, de c. 1250 a.C., no reinado de **Wu Ding**.' },
    { d: 'c. 1046 a.C.', t: 'Os Zhou vencem os Shang', x: 'O rei **Wu** de Zhou derrota o último rei Shang, **Di Xin**, na batalha de Muye. Os Zhou proclamam que o Céu retirou o seu mandato aos Shang (o **Mandato do Céu**). A data exata é debatida (entre 1046 e 1027 a.C.).' },
    { img: 'chi-zhou-bronze', leg: 'Ding de bronze com inscrição, Zhou Ocidental, Museu dos Bronzes de Baoji.' },
    { d: '770 a.C.', t: 'A corte Zhou foge para leste', x: 'Depois de um ataque de bárbaros e rebeldes, que mata o rei You, a corte muda-se para **Luoyi**. Começam os **Zhou Orientais** e, com eles, o período das **Primaveras e Outonos**: os reis têm prestígio sem poder.' },
    { d: 'c. 551 – 479 a.C.', t: 'Confúcio', x: 'O mestre **Kong Qiu**, o Confúcio, ensina em Lu uma ética de ordem e de dever. Mais ou menos na mesma época (a data é incerta) surge o texto do **Daodejing**, atribuído a Laozi.' },
    { d: '475 a.C.', t: 'Os Reinos Combatentes', x: 'Sete grandes Estados (Qin, Chu, Qi, Yan, Han, Zhao, Wei) lutam entre si. Aparecem exércitos de camponeses com ferro e bestas, a cavalaria, a moeda e os tratados de arte da guerra, como o de **Sun Tzu**.' },
    { d: '356 – 338 a.C.', t: 'As reformas de Shang Yang', x: 'O ministro legalista **Shang Yang** transforma o Estado de **Qin**: leis iguais e duras, recompensas pelo mérito militar, registo da população. Qin torna-se o mais forte dos Estados.' },
    { d: '221 a.C.', t: 'Qin unifica a China', x: 'O rei **Zheng** de Qin conquista o último reino rival e proclama-se **Shi Huangdi**, «Primeiro Imperador». Uniformiza a escrita, os pesos, as medidas e a moeda.' },
    { img: 'chi-exercito-terracota', leg: 'Exército de Terracota, fosso 1, Xi’an.' },
    { d: '210 – 206 a.C.', t: 'Morte do Imperador e queda de Qin', x: 'Shi Huangdi morre em 210 a.C., durante uma viagem; o seu filho é incapaz, e rebeliões de camponeses e antigos nobres derrubam a dinastia em 206 a.C.' },
    { d: '202 a.C.', t: 'Liu Bang funda os Han', x: 'O antigo chefe de aldeia **Liu Bang** vence o rival Xiang Yu e proclama-se imperador **Gaozu** dos **Han**. Mantém as instituições Qin, mas com leis mais brandas.' },
    { d: '141 – 87 a.C.', t: 'O imperador Wu Di', x: 'Durante o seu longo reinado, o império expande-se para o Tarim, a Coreia e o Vietname. O enviado **Zhang Qian** viaja ao Ocidente (c. 138 e 119 a.C.), e abre-se a **Rota da Seda**. O confucionismo torna-se a ideologia oficial.' },
    { d: 'c. 94 a.C.', t: 'O Shiji', x: 'O historiador **Sima Qian** conclui a primeira grande história geral da China, as «Memórias do Historiador» (*Shiji*), desde Huangdi até ao seu tempo.' },
    { d: '105 d.C.', t: 'Cai Lun e o papel', x: 'O eunuco **Cai Lun** apresenta ao imperador He um papel feito de casca, trapos e redes. Já existia papel mais grosseiro antes, mas Cai Lun é o primeiro a aperfeiçoá-lo para a escrita.' },
    { d: '220 – 280', t: 'Os Três Reinos', x: 'A dinastia Han desfaz-se depois da revolta dos Turbantes Amarelos (184). O império divide-se em **Wei**, **Shu** e **Wu**, com figuras como Cao Cao, Liu Bei, Sun Quan e Zhuge Liang, cujas histórias o romance do século XIV *Romance dos Três Reinos* tornou lendárias.' },
    { d: '581 – 618', t: 'Sui: a reunificação', x: 'Yang Jian, o imperador **Wen**, reunifica o país depois de cerca de 360 anos de divisão. O seu filho Yangdi manda construir o **Grande Canal**, mas as guerras na Coreia e os trabalhos forçados provocam revoltas.' },
    { d: '618 – 907', t: 'A dinastia Tang', x: 'Li Yuan e o filho Li Shimin (**Taizong**) fundam um império cosmopolita, com capital em **Chang’an**. É o tempo dos poetas Li Bai e Du Fu, de **Wu Zetian**, única mulher a reinar em nome próprio, e dos monges-peregrinos como **Xuanzang**.' },
    { d: '751 e 755 – 763', t: 'Talas e a rebelião de An Lushan', x: 'Os Tang perdem a batalha do rio **Talas** contra os árabes, e uma rebelião de um general, **An Lushan**, devasta o norte. O império sobrevive, mas enfraquecido.' },
    { d: '868', t: 'O Sutra do Diamante', x: 'Impresso em Dunhuang, é o livro **impresso com data** mais antigo do mundo, hoje na Biblioteca Britânica.' },
    { img: 'chi-sutra-diamante', leg: 'Sutra do Diamante, 868, Biblioteca Britânica.' },
    { d: '960 – 1127', t: 'Song do Norte', x: 'O general **Zhao Kuangyin** funda os **Song** com capital em **Kaifeng**. Há grande desenvolvimento do comércio, das cidades, da ciência e do exame imperial. O norte é perdido para os **Jurchen** em 1127.' },
    { d: '1127 – 1279', t: 'Song do Sul', x: 'Com a capital em **Hangzhou**, os Song do Sul têm uma economia marítima e uma cultura brilhante, mas acabam vencidos pelos mongóis.' },
    { d: '1271 – 1368', t: 'A dinastia Yuan', x: 'Kublai Khan, neto de Gengis Khan, proclama a dinastia **Yuan** (1271), conquista os Song do Sul (1279) e constrói **Dadu** (Pequim). Em 1368, as revoltas dos Turbantes Vermelhos expulsam os mongóis, e **Zhu Yuanzhang** funda a dinastia **Ming**, com que acaba este período.' }
  ] },
  { h: 'A redescoberta' },
  'A China antiga foi conservada pelos próprios chineses, que sempre estudaram os seus clássicos e coleccionaram bronzes e jades. A arqueologia moderna começou no século XX: em **1899** descobriu-se que os «ossos de dragão» das farmácias tinham inscrições; em **1928** começaram as escavações em Anyang; em **1974**, camponeses a abrir um poço encontraram o Exército de Terracota; em **1976**, o túmulo de Fu Hao; e em **1986**, as fossas de **Sanxingdui**, na província de Sichuan.'
];

const mapa = [
  'A China antiga não tinha uma capital única: mudava com cada dinastia, às vezes dentro da mesma. As cidades principais ficavam em geral nos vales do rio Amarelo e do rio Wei, e só mais tarde se deslocaram para o Yangtzé.',
  { img: 'chi-mapa-qin', leg: 'Mapa dos sete Reinos Combatentes cerca de 250 a.C., incluindo Qin, antes da unificação de 221 a.C.' },
  { tabela: { cab: ['Cidade', 'Dinastia', 'Local hoje', 'Para que ficou conhecida'], linhas: [
    ['Erlitou', 'Xia (?) / início do bronze', 'Yanshi, Henan', 'O palácio mais antigo da China; oficina de bronze'],
    ['Anyang (Yin)', 'Shang', 'Anyang, Henan', 'Última capital Shang; ossos oraculares; túmulo de Fu Hao'],
    ['Haojing e Luoyi', 'Zhou', 'Xi’an e Luoyang', 'As capitais Zhou, a ocidental e a oriental'],
    ['Xianyang', 'Qin', 'perto de Xi’an', 'Capital de Shi Huangdi, a oeste do seu túmulo'],
    ['Chang’an', 'Han e Tang', 'Xi’an, Shaanxi', 'Início da Rota da Seda; no tempo dos Tang era das maiores cidades do mundo'],
    ['Luoyang', 'Han Orientais, Wei, Tang', 'Luoyang, Henan', 'Capital oriental; grutas budistas de Longmen'],
    ['Kaifeng', 'Song do Norte', 'Henan', 'Cidade comercial de enorme animação'],
    ['Hangzhou', 'Song do Sul', 'Zhejiang', 'Capital marítima, ao pé do Lago Oeste'],
    ['Dadu', 'Yuan', 'Pequim', 'Capital de Kublai Khan, antecessora da Pequim de hoje'],
    ['Sanxingdui', 'Contemporânea dos Shang', 'Sichuan', 'Cultura de bronzes e máscaras muito diferente da do rio Amarelo']
  ] } },
  { h: 'Anyang e o mundo Shang' },
  'Anyang, capital Shang de c. 1300 a 1046 a.C., é hoje o sítio arqueológico chamado **Yinxu**, «as ruínas de Yin». Tinha palácios de terra batida, oficinas de bronze, jade e osso, e uma necrópole real com túmulos de reis, onde foram sepultados cavalos, carros, servos e prisioneiros sacrificados.',
  { img: 'chi-ai-anyang', leg: 'Vista imaginada de Anyang, capital Shang, cerca de 1200 a.C. Ilustração gerada por IA.' },
  { h: 'Chang’an, capital dos Han e dos Tang' },
  'Os Han fundaram o seu **Chang’an** («Paz Duradoura») em 202 a.C., a sul do rio Wei. Em 582, o imperador Wen dos Sui construiu a sudeste a nova cidade de Daxing, que os Tang (618) herdaram como Chang’an: uma cidade em quadrícula, de cerca de 80 km² e talvez um milhão de habitantes na região (estimativa), com mercados oficiais, mosteiros budistas, templos persas e comunidades de comerciantes sogdianos e de monges.',
  { img: 'chi-ai-chang-an', leg: 'Reconstituição conjetural de Chang’an na época Tang, século VIII. Ilustração gerada por IA.' },
  { h: 'Kaifeng e a vida urbana dos Song' },
  'Kaifeng, capital dos Song do Norte, é a cidade do famoso rolo **«Ao longo do rio no Festival de Qingming»**, de Zhang Zeduan (século XII). Pela primeira vez, uma capital chinesa quebra o desenho em quadrícula: ruas animadas, lojas, tavernas e mercados noturnos.',
  { img: 'chi-rolo-qingming', leg: 'Pormenor da ponte de Ao longo do rio no Festival de Qingming, versão original Song atribuída a Zhang Zeduan.' },
  { h: 'A Rota da Seda e as rotas do mar' },
  'A **Rota da Seda** (nome dado no século XIX por um geógrafo alemão, Ferdinand von Richthofen) é uma rede de caminhos, não uma estrada: partia de Chang’an, passava pelo corredor de Hexi, pelas oásis de Dunhuang, Turfan e Kashgar, e continuava por Samarcanda, a Pérsia e a Síria até ao Mediterrâneo. Além de seda, levava papel, chá, porcelana e ideias, e trazia cavalos, vidro, vinho, uvas, o budismo e novas religiões. A partir dos Tang e sobretudo dos Song, o comércio por **mar**, de Quanzhou e de Guangzhou até à Índia, à Arábia e à África, tornou-se mais importante do que o terrestre.',
  { img: 'chi-ai-rota-seda', leg: 'Caravana da Rota da Seda junto a Dunhuang na época Han. Ilustração gerada por IA.' },
  { h: 'A Grande Muralha: um aviso' },
  'A Grande Muralha de imagens turísticas é, sobretudo, a muralha da dinastia **Ming** (séculos XIV a XVII), de tijolo e pedra. Os Qin ligaram, no século III a.C., troços de muralhas de terra dos Estados do norte; os Han alargaram-nos; mas não existiu «uma muralha» contínua de 221 a.C.'
];

const sociedade = [
  { h: '1. Organização política' },
  'Os **Shang** governavam por uma aristocracia de clãs, onde o rei era sobretudo o grande sacerdote que falava com os antepassados. Os **Zhou** inventaram a ideia do **Mandato do Céu**: o rei, o «Filho do Céu», governa por vontade do Céu enquanto governar com justiça; se for mau, o Céu retira o mandato e a dinastia cai. A ideia justificou a vitória dos Zhou e foi invocada por todas as dinastias seguintes.',
  'Os Zhou repartiram o território por parentes e aliados, os **feudos**, onde os senhores deviam fidelidade ao rei. Com o tempo, os senhores tornaram-se independentes e começaram as guerras. Os **Qin** substituíram os feudos por **comandâncias** (*jun*) e condados governados por funcionários nomeados e removíveis, o modelo do Estado centralizado chinês. Os **Han** mantiveram esse sistema, com uma burocracia cada vez mais instruída em confucionismo.',
  { img: 'chi-ai-zhou-corte', leg: 'Audiência imaginada na corte Zhou Ocidental, cerca de 800 a.C. Ilustração gerada por IA.' },
  { h: '2. Os Cem Mestres' },
  'Entre os séculos VI e III a.C., a desordem política foi acompanhada de um extraordinário debate de ideias, o das **Cem Escolas**. As principais:',
  { tabela: { cab: ['Escola', 'Mestre', 'Ideia central'], linhas: [
    ['Confucionismo', 'Confúcio (551 – 479 a.C.), Mêncio, Xunzi', 'Ordem social baseada na virtude, no respeito pelos mais velhos, nos rituais e na educação'],
    ['Daoísmo', 'Laozi (tradicional), Zhuangzi', 'Seguir o **Dao**, o «Caminho» natural das coisas; ação sem esforço (*wuwei*); simplicidade'],
    ['Moísmo', 'Mozi (c. 470 – 391 a.C.)', 'Amor universal, sem preferências; condena a guerra agressiva'],
    ['Legalismo', 'Shang Yang, Han Fei, Li Si', 'Só leis claras e castigos duros mantêm a ordem; o Estado acima de tudo'],
    ['Escola da Guerra', 'Sun Tzu (tradicional)', 'Vencer com planeamento, informação e engano, evitando batalhas inúteis'],
    ['Yin-Yang', 'Zou Yan', 'O mundo é feito de forças complementares, e de cinco fases (madeira, fogo, terra, metal, água)']
  ] } },
  { img: 'chi-ai-academia-jixia', leg: 'Debate imaginado na Academia Jixia, Qi, século IV a.C. Ilustração gerada por IA.' },
  { h: '3. Classes sociais' },
  'A sociedade chinesa era vista como uma hierarquia de quatro grupos: os **eruditos-funcionários** (*shi*), os **camponeses** (*nong*), os **artesãos** (*gong*) e os **comerciantes** (*shang*). Os camponeses ocupavam o segundo lugar, porque produziam o alimento e pagavam os impostos; os comerciantes ficavam em último, apesar de poderem ser ricos. No topo, o **imperador** e a corte, a nobreza e, a partir dos Han, uma elite de famílias que dominavam os cargos. Abaixo estavam os **servos e os escravos**, em geral devido a dívidas ou a condenações. A mulher estava subordinada ao pai, ao marido e ao filho (*as três obediências*), mas houve imperatrizes poderosas, como **Lü Zhi** (Han) e **Wu Zetian** (Tang).',
  { h: '4. Religião e cultos' },
  'A religião chinesa mais antiga é o culto dos **antepassados** e do **Céu** (*Tian*). Os Shang faziam oferendas de comida, vinho e sacrifícios aos antepassados reais, em **vasos de bronze**, e consultavam-nos por **adivinhação**. Os Zhou acrescentaram o Céu como juiz moral. Mais tarde, juntaram-se o Daoísmo religioso, com os seus imortais, e o **budismo**, vindo da Índia a partir do século I d.C., que se tornou muito popular entre os séculos IV e IX.',
  { img: 'chi-osso-oracular', leg: 'Osso oracular Shang.' },
  { h: 'Ossos oraculares' },
  'Os reis Shang faziam perguntas aos antepassados («Vai chover? Devo atacar? A doença do rei vai passar?») e gravavam-nas em **omoplatas de boi** ou **carapaças de tartaruga**. Depois aqueciam o osso com uma brasa até se abrirem fendas, e os adivinhos liam a resposta. Muitas vezes gravava-se também o resultado. Encontraram-se mais de 150 000 fragmentos, a maior fonte direta sobre a política e a religião Shang.',
  { img: 'chi-ai-adivinhacao', leg: 'Cena imaginada de adivinhação Shang com um plastrão de tartaruga. Ilustração gerada por IA.' },
  { h: 'O Daoísmo e o Confucionismo' },
  'O **Daodejing**, atribuído a **Laozi** e com cerca de 5000 caracteres, é um dos livros mais traduzidos do mundo. Já a existência de Laozi é discutida: pode ser uma figura lendária, e o livro, uma compilação. **Confúcio** não fundou uma religião: ensinava virtudes como a **humanidade** (*ren*), o **ritual** (*li*) e a **piedade filial** (*xiao*). Os seus ensinamentos foram reunidos pelos discípulos nos *Analectos*. Com os Han, o confucionismo passa a ser a base da educação dos funcionários e, depois, o centro da vida cultural chinesa.',
  { h: '5. Economia, moeda e comércio' },
  'A base era a **agricultura** de pequenos camponeses: painço e trigo no norte, arroz no sul. As ferramentas de **ferro** (arados, enxadas), usadas desde c. 500 a.C., e os sistemas de irrigação, como o canal de **Dujiangyan** (c. 256 a.C.), multiplicaram a produção. A moeda mais antiga foi a de **conchas de cauri**; os Reinos Combatentes usaram moedas em forma de **faca** e de **pá**, e os Qin impuseram a moeda redonda de bronze com buraco quadrado, que durou dois mil anos. No tempo dos Song apareceu o **papel-moeda** (*jiaozi*, em Sichuan, início do século XI; emissão oficial em 1024), o mais antigo do mundo.',
  'O Estado controlava o **sal** e o **ferro** (monopólios desde Wu Di, 119 a.C.). O comércio a longa distância fez ricas cidades como Chang’an e, depois, os portos de Quanzhou e Guangzhou, onde viviam árabes, persas e indianos.',
  { img: 'chi-moeda-faca', leg: 'Moeda em forma de faca, Reinos Combatentes.' },
  { h: '6. Escrita e literatura' },
  'A escrita chinesa é **logográfica**: cada carácter representa uma palavra ou sílaba com sentido. A mais antiga forma segura é a dos **ossos oraculares** (c. 1250 a.C.), já com milhares de caracteres, e que se reconhece como antepassada da atual. As formas seguintes foram a escrita em **bronze**, a **escrita de selo**, que o primeiro imperador tornou oficial, a **escrita de chancelaria**, dos Han, mais simples e rápida de pintar com pincel, e, a partir do século III d.C., a **escrita regular**, a base da de hoje.',
  'Escrevia-se em **tiras de bambu** atadas com fio, em **seda**, e, depois de c. 100 d.C., em **papel**. Os principais clássicos são os *Cinco Clássicos* (poesia, história, rituais, mutações e Primaveras e Outonos), os *Analectos* e o *Daodejing*. A **poesia** chega ao auge no tempo dos Tang, com **Li Bai** (701 – 762) e **Du Fu** (712 – 770). Os **exames** exigiam saber de cor os clássicos, e escrever ensaios e poesia.',
  { h: '7. O exame imperial' },
  'A ideia de escolher funcionários pelo **mérito** vem dos Han, com recomendações; os **Sui** criaram os exames, e os **Tang** e sobretudo os **Song** fizeram deles o caminho principal para o poder. Em princípio, qualquer homem livre podia concorrer, mas só os que tinham tempo e dinheiro para estudar dez ou vinte anos tinham verdadeira hipótese. Os candidatos passavam dias fechados em celas minúsculas, a escrever. O sistema durou até **1905**. É uma das razões pelas quais o Estado chinês foi tão estável e culto.',
  { img: 'chi-ai-exame', leg: 'Cena conjetural de exames na China Song. Ilustração gerada por IA.' },
  { h: '8. Casa e família' },
  'A unidade básica era a **família alargada** de várias gerações, sob o chefe de família. As casas do norte tinham pátio rodeado de pavilhões de madeira com telhados de telha; as do sul tinham estruturas de madeira e paredes de taipa. Os aristocratas viviam em grandes complexos de pátios, com jardins; os camponeses, em casas de taipa com um ou dois quartos. A **madeira** era o material principal: por isso quase nenhum edifício antigo chegou aos nossos dias, e o que sabemos vem de túmulos, modelos de cerâmica e pinturas.',
  { img: 'chi-ai-casa-han', leg: 'Casa e quotidiano familiar na época Han, reconstituição conjetural. Ilustração gerada por IA.' },
  { h: '9. Alimentação' },
  'No norte, comia-se **painço** (em papas e pão cozido a vapor), mais tarde **trigo** em massas e noodles; no sul, **arroz**. Acompanhava-se com **legumes**, **soja** (tofu, molho de soja), peixe, porco, aves, e, a partir dos Han, carne de carneiro e cavalo entre os ricos. Bebia-se **vinho de cereais**; o **chá** era já bebido nos Han e tornou-se bebida nacional com os Tang. Comia-se com **pauzinhos** (hashi), conhecidos desde os Shang. A cozinha ritual era importante: os vasos de bronze guardavam comida e vinho para os antepassados.',
  { h: '10. Vestuário e a seda' },
  'A roupa era um sinal de classe. Usava-se um **manto** cruzado (*yi*) atado com cinto, de cânhamo e algodão para os pobres, e de **seda** para os ricos. As mulheres da elite usavam longos vestidos de seda. A **seda** vem do bicho-da-seda (*Bombyx mori*), alimentado com folhas de amoreira. A lenda atribui a descoberta à imperatriz **Leizu**, mulher de Huangdi; há fios e tecidos de seda muito antigos (de mais de 4000 anos). Durante séculos, a China manteve o **segredo** da sua produção, e só no século VI d.C. ela chegou a Bizâncio.',
  { img: 'chi-ai-seda', leg: 'Sericicultura e produção de seda na época Han, cena imaginada. Ilustração gerada por IA.' },
  { h: '11. Música, jogos e artes' },
  'A música era, para Confúcio, essencial na educação. Os instrumentos de bronze e de pedra eram os mais importantes nas cerimónias. O mais impressionante é o conjunto de cerca de **65 sinos** do túmulo do marquês **Yi de Zeng** (c. 433 a.C.), com mais de 2500 anos, ainda utilizável. Também havia a cítara *qin*, as flautas e os tambores. Jogavam-se o **weiqi** (go), o **liubo** e, mais tarde, o xadrez chinês. A **caligrafia** e a **pintura** eram as artes mais nobres; a pintura de paisagem chega a um grande refinamento no tempo dos Song.',
  { img: 'chi-sinos-zeng', leg: 'Sinos do marquês Yi de Zeng, Hubei.' },
  { h: '12. Bronze, jade e cerâmica' },
  'O **bronze** chinês é diferente do ocidental: em vez da técnica da cera perdida, os artesãos Shang fundiam em **moldes de peças** de argila, obtendo decorações muito ricas. Os vasos eram rituais, para oferecer comida e vinho aos antepassados, e simbolizavam o poder: nove *ding* (trípodes) representavam a autoridade do rei. O maior vaso conhecido, o **Houmuwu ding** (c. 1300 – 1100 a.C.), pesa cerca de 832 kg. A tradição guarda o gosto pelo bronze até aos nossos dias.',
  { img: 'chi-shang-ding', leg: 'Ding de bronze Shang.' },
  'O **jade** era mais precioso do que o ouro: duro, belo e simbólico da virtude. Desde Liangzhu os chineses esculpiam discos *bi* e tubos *cong*. No tempo dos Han, os príncipes eram sepultados em **fatos de jade** com milhares de placas cosidas a fio de ouro, na esperança de preservarem o corpo. A **cerâmica** chinesa remonta a 20 000 anos; passou pela louça negra de Longshan, pelo grés vidrado dos Han, pelas figuras Tang (*sancai*) e pela **porcelana** dos Song.',
  { img: 'chi-han-jade', leg: 'Fato funerário de jade de Liu Sheng, Mancheng.' },
  { img: 'chi-porcelana-song', leg: 'Taça de grés com vidrado celadon, dinastia Song (960–1279), Honolulu Museum of Art, 3752.1.' },
  { img: 'chi-fu-hao', leg: 'Vaso ritual fangyi de bronze com o nome de Fu Hao, Museu Nacional da China.' },
  { h: '13. Ciência e tecnologia' },
  'Alguns dos grandes inventos da China:',
  { tabela: { cab: ['Invento', 'Quando', 'Notas'], linhas: [
    ['Papel', 'Han, c. 100 a.C. – 105 d.C.', 'Existiu desde o século II a.C.; Cai Lun (105 d.C.) aperfeiçoou-o'],
    ['Sismoscópio', '132 d.C.', 'De **Zhang Heng**: urna de bronze que indicava a direção de um terramoto distante'],
    ['Ferro fundido', 'c. 500 a.C.', 'Os chineses fundiam ferro cerca de 1500 anos antes da Europa'],
    ['Besta', 'Reinos Combatentes', 'Arma de gatilho de bronze, decisiva para o exército Qin'],
    ['Imprensa', 'Tang, séc. VII – IX', 'Blocos de madeira; o Sutra do Diamante é de 868'],
    ['Tipos móveis', 'c. 1040', '**Bi Sheng**, em barro, descrito por Shen Kuo; os de metal vêm depois, na Coreia'],
    ['Pólvora', 'Tang, séc. IX; Song, séc. XI', 'Descoberta por alquimistas; na guerra, com os Song'],
    ['Bússola', 'Han a Song', 'Ímane de agulha, primeiro adivinhatório, e depois usada no mar (séc. XI – XII)'],
    ['Papel-moeda', 'Song, início do séc. XI', 'Em Sichuan (emissão oficial c. 1024)']
  ] } },
  { img: 'chi-papel-han', leg: 'Fragmento de mapa em papel de Fangmatan, túmulo 5, Han Ocidental, início do século II a.C.' },
  { img: 'chi-sismoscopio', leg: 'Réplica do sismoscópio de Zhang Heng.' },
  { h: '14. Medicina' },
  'A medicina chinesa baseava-se na ideia de equilíbrio entre o **yin** e o **yang** e entre os «cinco elementos». O clássico *Huangdi Neijing* («Cânone Interno do Imperador Amarelo»), escrito no tempo dos Reinos Combatentes e Han, descreve a circulação do **qi** («sopro vital») e a **acupunctura**. Os médicos usavam **ervas** (de que o lendário **Shennong** teria provado centenas), massagem e dieta. **Hua Tuo** (c. 140 – 208) é lembrado por ter usado anestesia com uma poção, e **Sun Simiao** (séc. VII), no tempo dos Tang, escreveu tratados sobre a ética médica.',
  { h: '15. Guerra' },
  'Nos Reinos Combatentes, os exércitos passaram de pequenos grupos de nobres em carros de guerra para **massas de infantaria** e cavalaria, equipadas com **ferro** e **bestas**. **Sun Tzu**, na *Arte da Guerra*, defendia que o melhor general vence sem combater. Os Qin criaram o exército mais temível do tempo, com disciplina e recompensas por mérito. Os Han combatiam os **Xiongnu**, confederação nómada do norte, e os Tang tinham exércitos de cavalaria e de mercenários. No tempo dos Song, a defesa baseou-se em fortalezas e nas armas de pólvora, mas o império não conseguiu travar os Jurchen e os mongóis.',
  { img: 'chi-ai-porto-song', leg: 'Porto de Quanzhou na época Song, reconstituição conjetural. Ilustração gerada por IA.' },
  { img: 'chi-ai-imprensa', leg: 'Oficina de impressão xilográfica na época Song, cena imaginada. Ilustração gerada por IA.' },
  { img: 'chi-sanxingdui-mascara', leg: 'Máscara de bronze de Sanxingdui.' }
];

const personalidades = [
  'A história chinesa é rica em biografias, e as principais fontes são a *Shiji* de Sima Qian e as «histórias dinásticas» oficiais. As figuras abaixo são reais; quando há lendas, ficam assinaladas.',
  { h: 'Fu Hao, consorte e general Shang (c. 1250 a.C.)' },
  'Uma das esposas do rei **Wu Ding**. Os ossos oraculares mostram-na a comandar exércitos, a presidir a rituais e a ter terras próprias. O seu túmulo, descoberto em 1976 em Anyang, intacto, continha mais de 460 bronzes e cerca de 775 jades.',
  { h: 'Rei Wen e Duque de Zhou (c. 1100 – 1040 a.C.)' },
  'O **rei Wen** preparou a queda dos Shang e o seu filho, o rei **Wu**, concluiu-a. O **duque de Zhou**, irmão de Wu, foi regente do jovem rei Cheng, e a tradição elogia-o como o governante ideal. Confúcio venerava-o.',
  { h: 'Confúcio (551 – 479 a.C.)' },
  '**Kong Qiu**, chamado Kongzi, «Mestre Kong». Nasceu em Lu, de família pobre de nobres, foi professor e funcionário e andou anos de corte em corte a tentar aplicar as suas ideias, sem grande êxito. Morreu convencido de que falhara. Só depois da sua morte, e sobretudo com os Han, a sua doutrina triunfou. Os *Analectos* são o melhor registo das suas palavras.',
  { img: 'chi-confucio', leg: 'Retrato de Confúcio, autor desconhecido, dinastia Ming, Casa da Família Kong, Qufu.' },
  { h: 'Laozi (tradicional, séc. VI a.C.)' },
  'Segundo a tradição, foi arquivista da corte Zhou, e escreveu o *Daodejing* antes de partir para o Ocidente, a pedido de um guarda da fronteira. Muitos académicos duvidam de que tenha existido como pessoa: o livro tomou a forma atual no século IV – III a.C. Ao lado dele está **Zhuangzi** (séc. IV a.C.), de histórias humorísticas, como a do sonho da borboleta.',
  { img: 'chi-laozi', leg: 'Laozi montado num boi, de Zhang Lu, dinastia Ming, Museu Nacional do Palácio, Taipé.' },
  { h: 'Sun Tzu (tradicional, c. séc. V a.C.)' },
  'O autor atribuído da *Arte da Guerra*, **Sun Wu**, general do reino de Wu. A obra foi provavelmente composta ou ampliada nos Reinos Combatentes. Em 1972, em Yinqueshan, encontraram-se tiras de bambu do século II a.C. com o seu texto, o que confirma a antiguidade.',
  { img: 'chi-sunzi-bambu', leg: 'Tiras de bambu da Arte da Guerra, Yinqueshan.' },
  { h: 'Mozi (c. 470 – 391 a.C.)' },
  'Fundador do **Moísmo**, ensinava o «amor universal» e condenava as guerras de agressão, embora defendesse a defesa organizada das cidades. Mestre de engenheiros e de lógica, ficou na sombra de Confúcio mas influenciou o pensamento chinês.',
  { h: 'Shang Yang (c. 390 – 338 a.C.)' },
  'Ministro de Qin. Introduziu o **Legalismo** na prática: leis públicas, castigos duros e recompensas militares. Fez de Qin uma potência, mas, sob um novo rei, foi executado, esquartejado por carros, segundo a tradição.',
  { h: 'Shi Huangdi, Primeiro Imperador (259 – 210 a.C.)' },
  '**Ying Zheng**, rei de Qin desde 246 a.C., unificou a China em 221 e tomou o título de **Huangdi**. Uniformizou a escrita, os pesos, as medidas e o eixo das carroças, construiu estradas e canais, e mandou reunir os grandes trabalhos defensivos do norte. Governou com mão de ferro: a tradição acusa-o de ter queimado os livros dos filósofos (213 a.C.) e enterrado vivos eruditos (212 a.C.), factos que os historiadores modernos acham exagerados pelos Han. Teve medo da morte: procurou o elixir da imortalidade, e pode ter morrido envenenado por pílulas de mercúrio. O seu túmulo, com o Exército de Terracota, ainda não foi aberto.',
  { img: 'chi-guerreiro-terracota', leg: 'Guerreiro de terracota individual.' },
  { h: 'Liu Bang e o imperador Wu (c. 256 – 195 a.C. e 156 – 87 a.C.)' },
  '**Liu Bang**, filho de camponeses e chefe de aldeia, fundou os Han. **Wu Di**, seu bisneto, governou 54 anos, expandiu o império e impôs o confucionismo. Era um grande conquistador, mas deixou os cofres vazios e o povo cansado.',
  { h: 'Zhang Qian (m. 114 a.C.)' },
  'Enviado de Wu Di ao Ocidente para procurar aliados contra os Xiongnu. Foi capturado e preso dez anos. Ao regressar, trouxe notícias da Sogdiana, da Báctria e da Pérsia, e abriu a Rota da Seda.',
  { h: 'Sima Qian (c. 145 – c. 86 a.C.)' },
  'O «Grande Historiador». Escreveu o *Shiji*, em 130 capítulos, de Huangdi a Wu Di. Condenado à castração por defender um general em desgraça, continuou a escrever para terminar a obra do pai.',
  { h: 'Cai Lun (m. 121 d.C.) e Zhang Heng (78 – 139 d.C.)' },
  '**Cai Lun**, eunuco da corte, aperfeiçoou o papel em 105. **Zhang Heng** foi astrónomo, matemático, poeta e inventor: construiu uma esfera armilar movida a água e o sismoscópio (132).',
  { h: 'Cao Cao, Liu Bei, Zhuge Liang (séc. II – III d.C.)' },
  'Figuras reais da era dos Três Reinos, tornadas lendárias pelo romance do século XIV. **Zhuge Liang** (181 – 234), conselheiro de Liu Bei, é retratado como estratega genial; a história real é mais sóbria do que o romance.',
  { h: 'Wu Zetian (624 – 705)' },
  'Concubina do imperador Taizong e depois esposa de Gaozong, governou de facto e, em 690, proclamou-se imperatriz de uma nova dinastia, **Zhou**. É a única mulher a reinar em nome próprio na história chinesa. Foi retratada como tirana pelos historiadores confucianos, mas promoveu os exames, o budismo e funcionários capazes.',
  { h: 'Xuanzang (602 – 664)' },
  'Monge budista que, em 629, partiu a pé para a Índia à procura de textos originais, e voltou em 645 com 657 manuscritos, que passou o resto da vida a traduzir. O seu relato inspirou o romance *Viagem ao Ocidente* (séc. XVI).',
  { h: 'Li Bai (701 – 762) e Du Fu (712 – 770)' },
  'Os dois maiores poetas Tang: **Li Bai**, livre, boémio, dedicado ao vinho e à lua; **Du Fu**, grave, que viu a guerra e a miséria da rebelião de An Lushan e a descreveu em versos de compaixão. Sobreviveram cerca de mil poemas de Li Bai e quase 1500 de Du Fu.',
  { h: 'Shen Kuo (1031 – 1095), Su Song e Bi Sheng' },
  '**Shen Kuo**, polímata dos Song, escreveu os *Ensaios do Lago dos Sonhos* sobre astronomia, geologia, magnetismo e os tipos móveis de **Bi Sheng**. **Su Song** construiu, em Kaifeng, uma torre-relógio astronómica movida a água, em 1092.',
  { h: 'Zhu Xi (1130 – 1200)' },
  'Filósofo que sistematizou o **Neoconfucionismo**, juntando a moral confuciana a uma visão do universo. A sua edição dos *Quatro Livros* foi, de 1313 a 1905, a base dos exames.',
  { h: 'Kublai Khan (1215 – 1294)' },
  'Neto de Gengis Khan, tornou-se Grande Khan em 1260. Fundou a dinastia **Yuan** (1271), conquistou os Song do Sul (1279) e construiu **Dadu**. Governou uma China dividida entre a corte mongol e a administração chinesa, e promoveu o comércio, o papel-moeda e a astronomia. Sobre os mongóis em geral, ver a página dos Mongóis.',
  { img: 'chi-kublai', leg: 'Retrato póstumo de Kublai Khan, cerca de 1294, atribuído a Araniko, Museu Nacional do Palácio, Taipé.' },
  { h: 'Marco Polo: uma nota' },
  'O veneziano **Marco Polo** (1254 – 1324) conta, no *Livro das Maravilhas*, que viveu na China de Kublai Khan entre c. 1275 e 1292. Há historiadores que duvidam de que tenha lá estado, porque não menciona o chá, os pauzinhos, a muralha ou a imprensa; outros defendem que o relato é, no essencial, verdadeiro. A questão **continua em debate**, mas o livro ajudou a fixar a imagem da China na Europa.'
];

const legado = [
  { h: 'O que nos deixaram' },
  { lista: [
    '**Escrita:** os caracteres chineses, em uso há mais de 3000 anos, são a base também da escrita japonesa e, em parte, da coreana e da vietnamita.',
    '**Ideias:** o confucionismo e o daoísmo moldaram o Extremo Oriente: respeito pela família, pelo estudo e pela harmonia.',
    '**Estado:** a burocracia por exame foi imitada pela Coreia, Vietname e Japão, e inspirou reformas europeias dos séculos XVIII e XIX.',
    '**Invenções:** papel, imprensa, pólvora e bússola chegaram à Europa pela Rota da Seda e pelo mar e, como disse Francis Bacon no século XVII, «mudaram a face do mundo».',
    '**Objetos:** seda, chá e porcelana (*china*, em inglês) foram os produtos que fizeram do Oriente um sonho europeu.'
  ] },
  { h: 'Arte' },
  'A arte chinesa não procurou a imitação exata da natureza, mas o **espírito** das coisas. A **caligrafia** é considerada a maior das artes, e a **pintura de paisagem** (*shanshui*, «montanhas e águas») atinge o auge nos Song. A escultura budista (Yungang, Longmen) e as figuras de cerâmica Tang são outras glórias.',
  { img: 'chi-tang-camelo', leg: 'Camelo sancai com cavaleiro, dinastia Tang, 723, Museu Nacional da China.' },
  { h: 'Arquitetura' },
  'A arquitetura chinesa é de **madeira**, com colunas, consolas (*dougong*) e grandes telhados de telha em curva. Os edifícios de madeira mais antigos que se conservam são do século VIII (o templo de Nanchan, c. 782). As **pagodes** vêm das estupas budistas indianas. As muralhas de terra, os túmulos e as pontes de pedra são outra herança.',
  { img: 'chi-muralha', leg: 'Grande Muralha, Mutianyu.' },
  { img: 'chi-ai-oficina-terracota', leg: 'Oficina Qin de figuras de terracota, cerca de 220 a.C., cena imaginada. Ilustração gerada por IA.' },
  { h: 'A redescoberta' },
  'Os chineses nunca esqueceram o seu passado, mas só no século XX a arqueologia tomou a dianteira. Em 1928 começou a escavação de Anyang; em 1974 o Exército de Terracota; em 1976 o túmulo de Fu Hao; em 1986 Sanxingdui. Os **manuscritos de Dunhuang**, descobertos em 1900 numa gruta fechada, trouxeram milhares de textos budistas, e o Sutra do Diamante. Em 2019, **Liangzhu** foi inscrita no Património Mundial.',
  { h: 'Onde visitar' },
  { lista: [
    '**Xi’an:** Exército de Terracota e Museu de História de Shaanxi.',
    '**Pequim:** Museu Nacional da China, Museu do Palácio (Cidade Proibida), Grande Muralha em Mutianyu e Badaling.',
    '**Anyang:** Yinxu e o seu museu.',
    '**Sichuan:** Museu de Sanxingdui.',
    '**Xangai:** Museu de Xangai (bronzes, jades, cerâmica).',
    '**Fora da China:** Museu Britânico (Londres), Museu Guimet e Museu Cernuschi (Paris), Museu Rietberg (Zurique), Museu Metropolitano (Nova Iorque), e, em Portugal, o Museu do Oriente (Lisboa) e o Museu de Macau.'
  ] },
  { cit: 'Aprender sem pensar é inútil; pensar sem aprender é perigoso.', fonte: 'Atribuído a Confúcio, Analectos, 2.15' }
];

const quiz = [
  { p: 'Que rio é o berço da civilização chinesa mais antiga?', op: ['O Yangtzé', 'O rio Amarelo', 'O Mekong', 'O Tarim'], certa: 1, exp: 'A Planície Central, no médio e baixo rio Amarelo, é o berço das primeiras dinastias.' },
  { p: 'Em que se escreviam as perguntas aos antepassados nos tempos Shang?', op: ['Em papiro', 'Em papel', 'Em ossos e carapaças', 'Em tábuas de argila'], certa: 2, exp: 'Os ossos oraculares (omoplatas de boi e carapaças de tartaruga) trazem a escrita chinesa mais antiga certa, c. 1250 a.C.' },
  { p: 'Qual é o estatuto da dinastia Xia?', op: ['Tem inscrições que a provam', 'É lendária ou debatida, sem prova escrita contemporânea', 'Foi fundada por Confúcio', 'É posterior aos Han'], certa: 1, exp: 'O sítio de Erlitou pode ser a sua capital, mas a identificação continua em debate.' },
  { p: 'O que é o «Mandato do Céu»?', op: ['Um imposto', 'A ideia de que o Céu dá e retira o direito de governar', 'Um tratado de paz', 'Um exame'], certa: 1, exp: 'Foi usado pelos Zhou para justificar a queda dos Shang.' },
  { p: 'Quem é o autor tradicional do Daodejing?', op: ['Confúcio', 'Mozi', 'Laozi', 'Sun Tzu'], certa: 2, exp: 'A existência de Laozi como pessoa é, contudo, debatida.' },
  { p: 'Que escola defendia leis duras e o Estado acima de tudo?', op: ['O Confucionismo', 'O Legalismo', 'O Moísmo', 'O Daoísmo'], certa: 1, exp: 'O Legalismo de Shang Yang e Han Fei fez de Qin uma potência.' },
  { p: 'Em que ano unificou Qin o território chinês?', op: ['771 a.C.', '475 a.C.', '221 a.C.', '202 a.C.'], certa: 2, exp: 'Em 221 a.C. o rei Zheng tornou-se Shi Huangdi, o Primeiro Imperador.' },
  { p: 'Como foi descoberto o Exército de Terracota?', op: ['Por arqueólogos em 1928', 'Por camponeses a abrir um poço em 1974', 'Por Marco Polo', 'Foi sempre visível'], certa: 1, exp: 'Foi em Lintong, perto de Xi’an, em 1974.' },
  { p: 'A Grande Muralha que hoje se visita é sobretudo de que dinastia?', op: ['Qin', 'Han', 'Tang', 'Ming'], certa: 3, exp: 'Os troços mais conhecidos foram reconstruídos nos séculos XIV a XVII.' },
  { p: 'Quem aperfeiçoou o papel em 105 d.C. no tempo dos Han?', op: ['Zhang Heng', 'Cai Lun', 'Bi Sheng', 'Sima Qian'], certa: 1, exp: 'Existia papel mais grosseiro antes, mas Cai Lun apresentou ao imperador um papel melhorado.' },
  { p: 'Que rota ligava a China ao Mediterrâneo?', op: ['A Rota do Incenso', 'A Rota da Seda', 'A Rota do Âmbar', 'A Rota do Chá'], certa: 1, exp: 'Era uma rede de caminhos, sobretudo a partir de Chang’an, desde os Han.' },
  { p: 'Qual foi a única mulher a reinar em nome próprio na China imperial?', op: ['Lü Zhi', 'Wu Zetian', 'Cixi', 'Fu Hao'], certa: 1, exp: 'Wu Zetian proclamou a dinastia Zhou em 690.' },
  { p: 'Qual é o livro impresso com data mais antigo do mundo?', op: ['A Bíblia de Gutenberg', 'O Sutra do Diamante, 868', 'Os Analectos', 'O Shiji'], certa: 1, exp: 'Foi encontrado em Dunhuang e está na Biblioteca Britânica.' },
  { p: 'Quem inventou os tipos móveis de barro, c. 1040?', op: ['Su Song', 'Shen Kuo', 'Bi Sheng', 'Zhu Xi'], certa: 2, exp: 'É descrito por Shen Kuo nos Ensaios do Lago dos Sonhos.' },
  { p: 'Quem foi o fundador da dinastia Yuan?', op: ['Gengis Khan', 'Kublai Khan', 'Zhu Yuanzhang', 'Zhao Kuangyin'], certa: 1, exp: 'Kublai proclamou a dinastia em 1271 e conquistou os Song do Sul em 1279.' }
];

export default {
  id: 'china',
  cor: '#b83a3a',
  grupo: { ...GRUPO, aqui: '' },
  emblema: '../assets/img/china.png',
  nome:    { pt: 'China antiga', en: 'Ancient China' },
  periodo: { pt: 'c. 2000 a.C. – 1500 d.C.', en: 'c. 2000 BC – AD 1500' },
  visao:          { pt: visao, en: EN.visao },
  linha:          { pt: linha, en: EN.linha },
  mapa:           { pt: mapa, en: EN.mapa },
  sociedade:      { pt: sociedade, en: EN.sociedade },
  personalidades: { pt: personalidades, en: EN.personalidades },
  legado:         { pt: [...legado, ...CRED.pt], en: [...EN.legado, ...CRED.en] },
  quiz:           { pt: quiz, en: EN.quiz }
};
