// ANCIENT EGYPT — Monuments and sites (English content). Same structure and same image slots as the Portuguese version (dados.js).
// Reign dates follow Shaw (ed.), The Oxford History of Ancient Egypt, 2000. Dates before the Middle Kingdom are approximate (c.).

const visao = [
  { caixa: 'In brief', texto: [
    'Ancient Egypt left the most impressive and best-preserved group of **stone monuments** of the ancient world: pyramids, temples, obelisks, colossal statues and rock-cut tombs, spread over some three thousand years. Many survived because they were built of stone (not mud brick, like houses and palaces), because the climate is dry and because they stood on the desert edge, away from the flood.',
    'This page travels the sites from north to south, from **Giza** to **Abu Simbel** (and Nubia), and explains **how they were built**: where the stone came from, with what tools, who worked on them and what they were paid. It also shows who built them (**Imhotep**, **Hemiunu**, **Senenmut**…) and who rediscovered them (**Champollion**, **Belzoni**, **Carter**…). Reign dates follow **Shaw (2000)**.'
  ] },
  { img: 'emo-mapa-sitios', leg: 'Map of ancient Egypt with main sites, from the Delta to Nubia.' },
  { h: 'What all these monuments have in common' },
  'The Egyptians built for **eternity**. The houses of the living were mud brick, which crumbles; the “houses of eternity” (tombs) and the “houses of the gods” (temples) were stone, to last for ever. That is why almost everything we see today is **religious and funerary** architecture, and little of everyday Egypt: palaces and towns have vanished, with rare exceptions (Amarna, Kahun, Deir el-Medina).',
  { img: 'emo-gize-panorama', leg: 'The three great pyramids of Giza seen from the plateau.' },
  { h: 'The main types of monument' },
  { lista: [
    '**Mastabas** (Old Kingdom): flat-roofed tombs of brick or stone, with an underground burial chamber. The name comes from the Arabic for “bench”.',
    '**Pyramids** (from c. 2670 BC): royal tombs, first stepped (Djoser), then smooth-sided (Sneferu, Khufu). Pharaohs stopped building them in the New Kingdom.',
    '**Cult temples**: the “house of the god”, where the king (through the priests) served the deity every day. Karnak, Luxor, Edfu and Dendera are the best-known examples.',
    '**Mortuary temples**: places where the dead king’s cult was kept up. In the New Kingdom they stood on the west bank of Thebes, away from the tomb.',
    '**Obelisks**: granite monoliths topped by a small pyramid, linked to the sun cult.',
    '**Rock-cut tombs**: dug into the rock at Beni Hasan, the Valley of the Kings and the Theban necropoleis.',
    '**Colossal statues and the Sphinx**, **fortresses** (mostly in Nubia) and **workers’ towns**.'
  ] },
  { img: 'emo-esquema-tipos', leg: 'Cross-section diagram of the evolution of royal tomb forms: mastaba, Step Pyramid, Bent Pyramid and smooth-sided pyramid; approximate comparative scale. Educational diagram.' },
  { h: 'When they were built' },
  'Large-scale stone building began with the pyramid of **Djoser** at Saqqara, c. 2670 BC. The high point of the pyramids was the **Old Kingdom** (c. 2686 – 2181 BC), with the Great Pyramid of Giza (c. 2589 – 2566 BC). After the collapse of political order (First Intermediate Period), the pharaohs of the **Middle Kingdom** (c. 2055 – 1650 BC) built pyramids again, but smaller and of brick. In the **New Kingdom** (c. 1550 – 1069 BC) the centre of the monumental world moved to **Thebes**: the great temples of Karnak and Luxor, the tombs hidden in the Valley of the Kings, and Abu Simbel. After that, the Ptolemies and the Roman emperors went on building temples “in the Egyptian style” (Edfu, Dendera, Philae) until the 3rd century AD.',
  { img: 'emo-abu-simbel', leg: 'Facade of the Great Temple of Abu Simbel, with the four colossi of Ramesses II.' },
  { h: 'Why they matter' },
  { lista: [
    '**Engineering:** they show how a society without iron tools, pulleys or wheels for heavy loads moved and raised blocks of tens of tonnes.',
    '**Organisation:** the evidence from the Great Pyramid, the transport of stone and the workers’ villages shows a state able to plan works over decades.',
    '**Information:** the walls of temples and tombs are the largest archives of ancient Egypt: religious texts, king lists, war reports, scenes of everyday life.',
    '**Imagination:** from them come Western “Egyptomania” and a part of the world’s cultural tourism.'
  ] },
  { caixa: 'A necessary warning', texto: 'Many ideas without foundation circulate about the pyramids, such as that they were built by **slaves**, by extraterrestrials or by a lost earlier civilisation. Archaeology shows the opposite: they were built by **Egyptians, workers paid and fed by the state**, who left behind their villages, their bakeries, their tombs and their names. See the section “How they were built”.' },
  { h: 'The monuments today' },
  'Seven places in Egypt are on the **UNESCO World Heritage** list, three of them from the pharaonic age: **Memphis and its Necropolis** (the pyramid fields from Giza to Dahshur), **Ancient Thebes with its Necropolis** (Karnak, Luxor, the Valley of the Kings…) and the **Nubian Monuments** (from Abu Simbel to Philae), all inscribed in 1979. In November 2025 the **Grand Egyptian Museum**, next to Giza, was officially inaugurated, where the Tutankhamun collection is gathered.'
];

const linha = [
  'Timeline of the building of the great monuments. Reigns follow Shaw (2000); before the Middle Kingdom dates are approximate (c.) and vary from author to author by decades or even more than a century.',
  { linha: [
    { d: 'c. 3300 – 3000 BC', t: 'The first royal tombs at Abydos', x: 'In the cemetery of **Umm el-Qaab**, at Abydos, the first rulers are buried in **mud-brick** chambers roofed with wood, with thousands of offering jars. In a tomb earlier than the 1st Dynasty (U-j, c. 3300 BC), labels turned up bearing the earliest writing signs in Egypt. These burials are the starting point of what will become the royal tomb.' },
    { d: 'c. 2670 BC', t: 'Djoser and the first great stone building', x: 'The pharaoh **Djoser** (3rd Dynasty) has built at **Saqqara**, under the direction of **Imhotep**, a funerary complex in limestone and a **six-step pyramid** about 60 m high. It was the first monumental building of cut stone in the world, and the model for everything that followed.' },
  ] },
  { img: 'emo-saqqara-djoser', leg: 'Djoser’s Step Pyramid, Saqqara.' },
  { linha: [
    { d: 'c. 2613 – 2589 BC', t: 'Sneferu, the great builder', x: '**Sneferu** (4th Dynasty) is the pharaoh who moved the most stone: the pyramid of **Meidum** (changed from stepped to smooth, and partly collapsed), the **Bent Pyramid** and the **Red Pyramid** at Dahshur. The Bent Pyramid changes angle halfway up (from c. 54° to c. 43°), probably to avoid a collapse; the Red is the first complete smooth-sided pyramid.' },
  ] },
  { img: 'emo-meidum', leg: 'Pyramid of Meidum.' },
  { img: 'emo-dahshur-curvada', leg: 'Bent Pyramid of Sneferu, Dahshur.' },
  { linha: [
    { d: 'c. 2589 – 2566 BC', t: 'The Great Pyramid of Khufu', x: 'At **Giza**, **Khufu** (Cheops) raises the largest of the pyramids: **146.6 m** high originally, about 2.3 million blocks, a base c. 230 m on each side. It was the tallest structure built by humans for more than 3,700 years. Its Egyptian name was **Akhet Khufu**, “Horizon of Khufu”. The architect usually named is **Hemiunu**, the king’s vizier.' },
    { d: 'c. 2558 – 2503 BC', t: 'Khafre, Menkaure and the Sphinx', x: '**Khafre** builds the second pyramid of Giza (c. 143 m originally) and, according to most specialists, has the **Great Sphinx** carved from an outcrop of limestone. **Menkaure** builds the third, much smaller (c. 65 m), but with its lower part faced in Aswan granite.' },
  ] },
  { img: 'emo-gize-original', leg: 'Artistic reconstruction of Giza, c. 2500 BC, with white limestone casing; the golden finish at the apex is conjectural. AI-generated illustration.' },
  { linha: [
    { d: 'c. 2487 – 2350 BC', t: 'Abusir and the sun temples', x: 'In the 5th Dynasty the pharaohs build smaller and poorer-quality pyramids at **Abusir** and **Saqqara**, and open-air **sun temples** with a large obelisk (that of **Niuserre**, at Abu Gurab). At the same time the cult of the sun god **Ra** gains weight.' },
    { d: 'c. 2350 BC', t: 'The pyramid of Unas and the Pyramid Texts', x: 'Inside the pyramid of **Unas**, at Saqqara, the walls of the burial chamber are covered for the first time with **religious texts**: the oldest religious writings known from Egypt (the **Pyramid Texts**).' },
    { d: 'c. 2010 BC', t: 'Mentuhotep II at Deir el-Bahari', x: 'With the country reunited, **Mentuhotep II** (Middle Kingdom) builds at **Deir el-Bahari**, in Thebes, a terraced mortuary temple with colonnades and a central structure, at the foot of a cliff. How it was crowned (pyramid or another form) is not known for certain. It will inspire Hatshepsut’s temple next door.' },
    { d: 'c. 1971 BC', t: 'Senusret I and the start of Karnak', x: '**Senusret I** (c. 1971 – 1926 BC) has built the first buildings we know at **Karnak**, among them the “White Chapel” (rebuilt today in the open-air museum), and raises an obelisk at **Heliopolis**, the only one still standing on that site. The king’s pyramid is at **Lisht**.' },
    { d: 'c. 1870 – 1800 BC', t: 'Nubian fortresses and brick pyramids', x: '**Senusret III** builds powerful fortresses on the Nile in **Nubia** (Buhen, Semna), and **Amenemhat III** builds the Black Pyramid at Dahshur and another at **Hawara**, in the Faiyum. Today the fortresses of Buhen and Semna lie under the waters of Lake Nasser.' },
    { d: 'c. 1550 BC', t: 'Ahmose I, the last royal pyramid', x: '**Ahmose I** (c. 1550 – 1525 BC), who drives out the Hyksos and founds the New Kingdom, builds at Abydos the **last royal pyramid in Egypt**, of which few traces remain. From then on kings are buried in tombs hidden in the rock.' },
    { d: 'c. 1504 – 1492 BC', t: 'Thutmose I, Ineni and the Valley of the Kings', x: 'The architect **Ineni** serves Amenhotep I and **Thutmose I**: he builds pylons at Karnak and, as he himself writes, digs the king’s tomb “no one seeing, no one hearing”. Many regard this tomb as the first in the **Valley of the Kings** (the identification is debated). The village of **Deir el-Medina**, where the workmen will live, has its first remains from this reign.' },
  ] },
  { img: 'emo-deir-el-bahari', leg: 'Hatshepsut’s mortuary temple and ruins of Mentuhotep II’s temple, Deir el-Bahari.' },
  { linha: [
    { d: 'c. 1473 – 1458 BC', t: 'Hatshepsut: Deir el-Bahari and the obelisks', x: 'The queen-pharaoh **Hatshepsut** has her mortuary temple built at Deir el-Bahari, usually attributed to **Senenmut**, and raises two great granite obelisks at Karnak. One still stands, about 29 m high: it is the second tallest ancient obelisk in existence.' },
    { d: 'c. 1390 – 1352 BC', t: 'Amenhotep III and the age of splendour', x: '**Amenhotep III** builds the **temple of Luxor**, a great mortuary temple (of which only the two **Colossi of Memnon** remain) and temples in Nubia (such as Soleb). It is one of the richest and most productive reigns for building.' },
    { d: 'c. 1346 – 1327 BC', t: 'Amarna and Tutankhamun', x: '**Akhenaten** founds the new capital, **Akhetaten** (Amarna), with temples open to the Sun and made of small blocks (the talatat). After his death the city is abandoned and the temples dismantled; **Tutankhamun**, who reigns briefly, is buried in a small tomb (KV62), probably adapted in haste (this is debated).' },
    { d: 'c. 1294 – 1279 BC', t: 'Seti I: Abydos and Karnak', x: '**Seti I** builds his great temple at **Abydos**, with the famous “King List”, completes the gigantic **Hypostyle Hall of Karnak** and has the most beautiful tomb in the Valley of the Kings dug (KV17), discovered in 1817 by Belzoni.' },
    { d: 'c. 1279 – 1213 BC', t: 'Ramesses II, the greatest builder', x: '**Ramesses II** leaves works all over the country and in Nubia: the **Ramesseum**, the extension of Luxor, the new capital **Pi-Ramesses** and, c. 1264 – 1244 BC, the temples of **Abu Simbel**, cut into the rock. For his wife **Nefertari** he has a tomb decorated (QV66), considered one of the most beautiful in Egypt.' },
  ] },
  { img: 'emo-medinet-habu', leg: 'First pylon of Ramesses III’s mortuary temple at Medinet Habu, Thebes.' },
  { linha: [
    { d: 'c. 1184 – 1153 BC', t: 'Ramesses III at Medinet Habu', x: '**Ramesses III** builds at Medinet Habu the last great mortuary temple of the New Kingdom, surrounded by a wall. The reliefs show the wars against the “Sea Peoples”.' },
    { d: 'c. 1000 – 800 BC', t: 'Tanis, the recycled capital', x: 'In the Delta, the kings of the 21st and 22nd Dynasties build **Tanis**, reusing blocks and statues from Pi-Ramesses. In 1939 – 1940 intact royal tombs were found there (Psusennes I), with a silver coffin and a gold mask.' },
    { d: 'c. 690 – 664 BC', t: 'Taharqa and Nubian Egypt', x: 'The pharaoh **Taharqa**, of the 25th Dynasty (king of Kush), builds at Karnak and in Nubia (Kawa, Jebel Barkal), and has his pyramid at **Nuri**. Nubian pyramids follow the Egyptian model, but are smaller and steeper.' },
    { d: 'c. 380 – 362 BC', t: 'Nectanebo I, the last great native builder', x: '**Nectanebo I** (30th Dynasty) restores temples across the country: the avenue of sphinxes from Luxor to Karnak, and the first buildings of the temple of Isis at **Philae**. It is the start of a last golden age of religious architecture.' },
    { d: 'c. 331 – 280 BC', t: 'Alexandria and the Lighthouse', x: 'Alexander the Great founds **Alexandria** in 331 BC. Under Ptolemy I and II the **Lighthouse of Alexandria** (Pharos) is built, more than 100 m high, one of the Seven Wonders of the ancient world. It fell in medieval earthquakes.' },
  ] },
  { img: 'emo-farol-alexandria', leg: 'Conjectural reconstruction of the Lighthouse of Alexandria, c. 280 BC, and the harbour with Hellenistic ships. AI-generated illustration.' },
  { linha: [
    { d: '237 – 57 BC', t: 'Edfu, Dendera, Kom Ombo, Philae', x: 'The Ptolemies build (and the Romans finish) gigantic temples that keep the pharaonic style: **Edfu** (begun in 237 BC and finished in 57 BC), **Dendera**, **Kom Ombo**, **Esna**, **Philae**. They are the best-preserved ancient temples in Egypt.' },
    { d: 'AD 394 and 537', t: 'The end of the temples', x: 'The last known inscription in hieroglyphs was carved at **Philae** in AD 394; the last in demotic, in 452. According to the historian Procopius, the temple of Philae was officially closed in the time of Justinian, c. 537. Many temples were afterwards turned into churches, monasteries and houses.' },
    { d: '1798 – 1858', t: 'Scientific rediscovery', x: 'Napoleon’s expedition (1798) takes to Egypt scholars who publish the Description de l’Égypte; **Champollion** deciphers the hieroglyphs (1822); **Belzoni** clears the entrance of Abu Simbel and discovers the tomb of Seti I (1817); **Mariette** founds the Antiquities Service (1858).' },
    { d: '1922', t: 'The tomb of Tutankhamun', x: 'On 4 November, **Howard Carter**’s team finds the steps leading to the tomb of Tutankhamun (KV62), the only royal tomb in the Valley of the Kings found almost intact.' },
    { d: '1960 – 1980', t: 'The UNESCO Nubian campaign', x: 'To save the monuments from the rising waters of the **Aswan High Dam**, UNESCO coordinates one of the greatest cultural rescues ever: Abu Simbel is dismantled and rebuilt higher up (1964 – 1968) and the Philae complex is moved to another island (1977 – 1980).' },
    { d: '2025', t: 'Inauguration of the Grand Egyptian Museum', x: 'On 1 November 2025 the **Grand Egyptian Museum** is officially inaugurated, about 2 km from the pyramids of Giza, presented as the largest archaeological museum in the world devoted to a single civilisation. It opened to the public in November, after years of partial opening.' }
  ] }
];

const mapa = [
  'Egypt’s monuments line up along the **Nile**, from north to south, and in the deserts and oases beside it. The Egyptians called the Delta **Lower Egypt** and the southern valley **Upper Egypt** (“upper” is the south, because the river flows north). Here we use the six regions of the theme: Lower Egypt, Middle Egypt, Upper Egypt, Nubia, the Oases and Sinai/Red Sea.',
  { tabela: { cab: ['Region', 'Site', 'Main period', 'Best known for'], linhas: [
    ['Lower Egypt', 'Giza', 'Old Kingdom', 'Three great pyramids and the Sphinx'],
    ['Lower Egypt', 'Saqqara', 'Old Kingdom – Roman period', 'Djoser’s step pyramid; painted mastabas; Serapeum'],
    ['Lower Egypt', 'Dahshur and Meidum', 'Old Kingdom', 'Bent, Red and Meidum pyramids'],
    ['Lower Egypt', 'Memphis', 'All periods', 'Ancient capital; temple of Ptah; colossus of Ramesses II'],
    ['Lower Egypt', 'Heliopolis', 'All periods', 'City of Ra; obelisk of Senusret I'],
    ['Lower Egypt', 'Tanis and Bubastis', 'Third Intermediate Period', 'Delta capitals; royal tombs at Tanis'],
    ['Lower Egypt', 'Alexandria', 'Ptolemaic and Roman period', 'Lighthouse, catacombs of Kom el-Shoqafa'],
    ['Middle Egypt', 'Faiyum (Hawara, Lahun)', 'Middle Kingdom', 'Brick pyramids; workers’ town of Kahun'],
    ['Middle Egypt', 'Beni Hasan', 'Middle Kingdom', 'Rock-cut tombs with scenes of wrestling and crafts'],
    ['Middle Egypt', 'Amarna (Akhetaten)', 'c. 1346 – 1332 BC', 'Capital of Akhenaten'],
    ['Upper Egypt', 'Abydos', 'Predynastic – New Kingdom', 'Earliest royal tombs; temple of Seti I'],
    ['Upper Egypt', 'Dendera', 'Ptolemaic and Roman period', 'Temple of Hathor'],
    ['Upper Egypt', 'Karnak and Luxor', 'Middle Kingdom – Roman period', 'Egypt’s largest religious complex'],
    ['Upper Egypt', 'Valley of the Kings and Valley of the Queens', 'New Kingdom', 'Royal tombs cut into the rock'],
    ['Upper Egypt', 'Deir el-Bahari, Medinet Habu, Ramesseum', 'Middle and New Kingdom', 'Mortuary temples of the west bank'],
    ['Upper Egypt', 'Edfu, Kom Ombo, Esna', 'Ptolemaic and Roman period', 'Well-preserved temples'],
    ['Upper Egypt', 'Aswan and Philae', 'All periods', 'Granite quarries; temple of Isis'],
    ['Nubia', 'Abu Simbel', 'c. 1264 – 1244 BC', 'Temples of Ramesses II and Nefertari'],
    ['Nubia', 'Buhen, Semna, Soleb', 'Middle and New Kingdom', 'Fortresses and temples on the Nile (now in Sudan or submerged)'],
    ['Nubia', 'Jebel Barkal, Nuri, Meroe', 'New Kingdom – 4th century AD', 'Pyramids and temples of Kush'],
    ['Oases', 'Siwa, Bahariya, Kharga, Dakhla', 'Late and Roman period', 'Oracle of Amun, mummies, temples'],
    ['Sinai and Red Sea', 'Serabit el-Khadim, Wadi el-Jarf, Wadi Hammamat', 'All periods', 'Turquoise mines, ports, quarries']
  ] } },
  { h: 'Lower Egypt — Giza, the plateau of the pyramids' },
  'On the **Giza** plateau, on the west bank of the Nile next to present-day Cairo, stand the pyramids of **Khufu** (146.6 m), **Khafre** (c. 143 m, now 136 m) and **Menkaure** (c. 65 m), surrounded by queens’ pyramids, mastabas of relatives and high officials, temples and the **Sphinx**. It is the only one of the Seven Wonders of the ancient world still standing. Beside the Great Pyramid, pits with dismantled boats were found: the **solar boat of Khufu**, made of cedar, 43 m long, discovered in 1954.',
  { img: 'emo-esfinge', leg: 'Great Sphinx of Giza, with Khafre’s pyramid.' },
  { h: 'The Great Sphinx' },
  'It measures c. 73 m long and 20 m high and was **carved directly from the bedrock** of an old quarry. Most specialists attribute it to **Khafre** (c. 2500 BC), because it stands beside his valley temple; this attribution is not unanimous. It was often buried in sand: Prince **Thutmose IV** (c. 1400 BC) cleared it and left the “Dream Stele” between its paws. The nose was damaged centuries later, in the Middle Ages, and **not by Napoleon’s soldiers**, as is often said: it was already missing in earlier drawings.',
  { h: 'Saqqara and Memphis' },
  '**Saqqara** was the great necropolis of **Memphis**, the first capital of unified Egypt. It has Djoser’s step pyramid, the pyramids with texts (Unas, Teti, Pepi), decorated mastabas of high officials (Ti, Ptahhotep, Mereruka) and the **Serapeum**, underground galleries where the sacred Apis bulls were buried, discovered by **Mariette** in 1851. At **Memphis** (today Mit Rahina) little remains: an open-air museum, an alabaster sphinx and the great fallen colossus of Ramesses II, found in 1820.',
  { h: 'Dahshur and Meidum' },
  'South of Saqqara, **Dahshur** has the **Bent Pyramid** and the **Red Pyramid** of Sneferu and the Middle Kingdom brick pyramids (the Black Pyramid of Amenemhat III). Further south, the pyramid of **Meidum**, a “tower” of three visible steps, shows the result of a pyramid whose outer casing fell off. Here the Egyptians learned to raise smooth, stable pyramids.',
  { h: 'Heliopolis, Tanis and Bubastis' },
  '**Heliopolis** (now in the suburbs of Cairo) was the centre of the sun-god cult; only the **obelisk of Senusret I** remains. In the Delta, **Tanis** (San el-Hagar) was the capital of the kings of the 21st and 22nd Dynasties and holds their royal tombs, discovered by **Pierre Montet** in 1939 – 1940; **Bubastis** was the city of the cat-goddess **Bastet**. Much of the Delta has been lost, buried in mud or under modern towns, which makes archaeology difficult.',
  { h: 'Alexandria' },
  'Founded in 331 BC, **Alexandria** had the **Lighthouse (Pharos)** and the Museum and Library. Of the lighthouse there remains the **Qaitbay Fort** (1477), built with its blocks, and submerged blocks found in underwater excavations in the 1990s. The city keeps the **catacombs of Kom el-Shoqafa** (c. 2nd century AD, with Greco-Egyptian funerary art) and “Pompey’s Pillar”, of c. AD 297.',
  { h: 'Middle Egypt — Faiyum, Beni Hasan and Amarna' },
  'In the **Faiyum**, the pyramid of **Amenemhat III** at **Hawara** was called the “Labyrinth” by Greek authors (the idea comes from a great mortuary temple, now vanished), and the workers’ town of **Lahun/Kahun**, excavated by **Petrie** (1889 – 1890), shows how a building community lived. At **Beni Hasan** the tombs cut into the cliff have paintings of crafts, hunting and hand-to-hand wrestling. **Amarna** (**Akhetaten**) is the city of **Akhenaten**, built and abandoned in some fifteen years; the **bust of Nefertiti**, now in Berlin, was found there.',
  { h: 'Upper Egypt — Abydos' },
  '**Abydos** is the sacred site of **Osiris**. At **Umm el-Qaab** lie the oldest royal tombs; and the **temple of Seti I** (c. 1290 BC), with exquisite reliefs, holds the **Abydos King List** with 76 pharaohs’ names. Behind it is the **Osireion**, an enigmatic building that reproduces the mythical tomb of Osiris. It was a place of pilgrimage throughout Egyptian history.',
  { img: 'emo-abidos-seti', leg: 'Courtyard and colonnade of the Temple of Seti I, Abydos.' },
  { h: 'Upper Egypt — Dendera, Edfu, Kom Ombo and Esna' },
  'These temples date from the **Ptolemaic and Roman** periods, but follow the traditional Egyptian plan. **Dendera** is the temple of the goddess **Hathor**, with an astronomical ceiling (the famous “Zodiac” was removed in 1820 and is in the Louvre). **Edfu**, dedicated to **Horus**, is the best-preserved temple in Egypt: its pylon, court, halls and sanctuary are almost intact. **Kom Ombo** is a double temple, of **Sobek** (the crocodile) and **Horus the Elder**. **Esna** has a Roman columned hall with an astronomical ceiling.',
  { h: 'Karnak' },
  '**Karnak**, the ancient **Ipet-isut** (“The Most Select of Places”), is the largest religious complex in Egypt, dedicated chiefly to **Amun-Ra**. It grew for some two thousand years, from Senusret I (c. 1971 BC) to the Ptolemies, with a succession of pylons, courts, obelisks, statues and sacred lakes. Its **Hypostyle Hall**, of c. 5,000 m², has **134 columns** in 16 rows, 12 of them c. 21 m high, built mostly by Seti I and Ramesses II.',
  { img: 'emo-karnak-hipostila', leg: 'Hypostyle Hall of the temple of Amun, Karnak.' },
  { img: 'emo-karnak-obelisco', leg: 'Obelisk of Hatshepsut, Karnak.' },
  { h: 'Luxor' },
  'The **temple of Luxor** was built chiefly by **Amenhotep III** and **Ramesses II**, c. 2.5 km from Karnak, to which it was linked by an avenue of sphinxes (c. 2.7 km long, restored and reopened in 2021). It served the annual **Opet** festival, in which Amun’s image went by boat, in procession, from Karnak to Luxor. A medieval mosque (Abu el-Haggag) is built inside the temple and is still in use. Of the two obelisks at the entrance, one stands at Luxor and the other in Paris (Place de la Concorde), since 1836.',
  { img: 'emo-luxor-templo', leg: 'Ramesses II’s pylon and obelisk, Luxor Temple.' },
  { img: 'emo-karnak-festa-opet', leg: 'Opet festival procession at Karnak, c. 1250 BC, with priests carrying Amun’s sacred barque. AI-generated illustration.' },
  { h: 'The west bank of Thebes: Valley of the Kings, Queens and mortuary temples' },
  'On the west bank of **Thebes**, at the desert’s edge, the New Kingdom royal tombs lie hidden in the **Valley of the Kings**, more than 60 numbered (KV1 to KV64), among them those of **Seti I**, **Ramesses II** (KV7) and **Tutankhamun** (KV62). In the **Valley of the Queens** is the tomb of **Nefertari** (QV66). Facing the Nile are each king’s **mortuary temples**: that of **Hatshepsut** at Deir el-Bahari, the **Ramesseum** of Ramesses II (inspiration for “Ozymandias”, Shelley’s poem), **Medinet Habu** of Ramesses III and the **Colossi of Memnon**, remains of that of Amenhotep III.',
  { img: 'emo-vale-reis', leg: 'Valley of the Kings, Thebes, general view.' },
  { h: 'Aswan, Elephantine and Philae' },
  'At **Aswan**, by the First Cataract, are the **granite quarries** from which obelisks and statues came, and **Elephantine island** with its nilometer. **Philae**, temple of the goddess **Isis** (with most of its buildings from the Ptolemies and the Romans), was one of the last centres of Egyptian paganism. It was dismantled and rebuilt on the island of **Agilkia** in 1977 – 1980, when the dam raised the waters.',
  { img: 'emo-filas', leg: 'Temple of Isis at Philae, Agilkia Island.' },
  { h: 'Nubia — Abu Simbel and the fortresses' },
  '**Nubia** is the territory south of Aswan, today shared between Egypt and Sudan. **Abu Simbel** is its most famous site: two rock-cut temples, the Great Temple of **Ramesses II** and a smaller one of the queen **Nefertari** and the goddess **Hathor**. In the Middle Kingdom the pharaohs built fortresses here (**Buhen**, **Semna**) to control gold and trade. In the New Kingdom they raised temples such as that of **Soleb**. Almost everything that stood along the Nile was covered by **Lake Nasser** in the 1960s.',
  { h: 'Nubia — Napata and Meroe' },
  'With the 25th Dynasty (c. 747 – 656 BC), kings of **Kush**, whose capital was Napata, ruled Egypt and built at **Jebel Barkal**, **El-Kurru** and **Nuri**. Later the capital moved to **Meroe**, in present-day Sudan, where there are some two hundred Nubian **pyramids** (3rd century BC to 4th century AD), smaller and steeper than the Egyptian ones. They are not Egyptian, but they inherited the idea.',
  { h: 'The oases of the Western Desert' },
  'At **Siwa**, the oracle of **Amun** was visited by **Alexander the Great** in 331 BC. At **Bahariya** the “Valley of the Golden Mummies” was discovered in 1996, with hundreds of Greco-Roman mummies already excavated (and probably thousands still to dig). At **Kharga**, the temple of **Hibis** dates from the Persian and Saite periods; at **Dakhla** there are Old Kingdom sites (Balat) and Roman ones. They were stopping points for caravans and producers of wine, dates and grain.',
  { h: 'Sinai and the Red Sea' },
  'In **Sinai**, **Serabit el-Khadim** had a temple of **Hathor, “Lady of Turquoise”**, and mines of that stone, and on its cliffs appear “Proto-Sinaitic” inscriptions, a possible origin of the alphabet (the dating is debated). The Red Sea coast had ports used for the expeditions to **Punt** (Mersa/Wadi Gawasis) and, in the time of **Khufu**, a port at **Wadi el-Jarf**, where the papyri of the diary of **Merer** were found in 2013. In the eastern desert lay the quarries of **Wadi Hammamat** (greywacke) and, in Roman times, those of granite (Mons Claudianus) and porphyry (Mons Porphyrites).',
  { h: 'The routes' },
  'The monuments were linked by Egypt’s fastest road, the **Nile**: the river carried blocks of stone from south to north (with the current) and travellers and troops from north to south (with the wind). The cargo boats were large, and the quarries of Aswan, Tura and Gebel el-Silsila all lay beside the river or canals. The desert quarries (Wadi Hammamat, Gebel el-Asr) demanded expeditions with donkeys and soldiers.'
];

const sociedade = [
  { h: '1. Who ordered the building' },
  'A building project was a **decision of the king**, passed to a senior official: the **vizier** or the **“overseer of all the king’s works”**. He had to gather stone, timber, copper, boats, food and people. The documents give us names: **Imhotep** (Djoser), **Hemiunu** (Khufu), **Ineni** (Thutmose I), **Senenmut** (Hatshepsut), **Amenhotep, son of Hapu** (Amenhotep III). As in every age, it is hard to separate what the architect designed from what was later attributed to him.',
  { h: '2. Where the stone came from' },
  'The Egyptians used local stone whenever they could, and went far only for special stones. In the great pyramids the core was limestone quarried a few metres away, on the Giza plateau itself.',
  { tabela: { cab: ['Stone', 'Origin', 'Main uses'], linhas: [
    ['Common limestone', 'Plateaux beside the works (Giza, Saqqara)', 'Core of pyramids, temples'],
    ['Fine white limestone', 'Tura and Maasara, east bank, near Cairo', 'Casing of pyramids; reliefs'],
    ['Sandstone', 'Gebel el-Silsila (north of Aswan)', 'New Kingdom temples, from Karnak to Medinet Habu'],
    ['Granite and granodiorite', 'Aswan', 'Obelisks, statues, sarcophagi, burial chambers'],
    ['Quartzite', 'Gebel el-Ahmar, near Cairo', 'Colossal statues (Colossi of Memnon)'],
    ['Egyptian alabaster (calcite)', 'Hatnub, Middle Egypt', 'Vessels, statues, sarcophagi'],
    ['Greywacke (bekhen)', 'Wadi Hammamat, eastern desert', 'Statues, sarcophagi'],
    ['Diorite and gneiss', 'Quarries in the Nubian desert', 'Statues (the seated Khafre in the Cairo Museum)']
  ] } },
  { img: 'emo-pedreira-assuao', leg: 'Work in an Aswan granite quarry in the New Kingdom, with dolerite pounding balls and an obelisk still attached to bedrock. AI-generated illustration.' },
  { h: '3. Tools' },
  'The builders of the Old Kingdom used **copper** tools and, later, **bronze**, but iron came into general use much later. They cut limestone with copper chisels and saws, using abrasive sand. For **granite**, extremely hard, they used **dolerite pounders**, an even harder stone, to crush it to dust, and tube drills with sand to bore holes. There were also wooden mallets, wedges, levers, ropes and measuring instruments such as the **plumb bob**, the **square** and the **cord**.',
  { h: '4. Moving the stone: boats, sledges and wet sand' },
  'Blocks were loaded onto **boats** and carried along the Nile and canals, above all during the **flood**, when the water came closer to the works. On land they were dragged on **wooden sledges** over sand. A painting in the tomb of **Djehutihotep** (Deir el-Bersha, c. 1900 BC) shows a colossus of c. 58 tonnes being pulled by 172 men, while someone pours liquid in front of the sledge. A physics experiment (2014) confirmed that **wet sand** greatly reduces friction.',
  { img: 'emo-barco-blocos', leg: 'Old Kingdom boats transporting limestone blocks along the Nile, c. 2560 BC. AI-generated illustration.' },
  { h: '5. The diary of Merer' },
  'In 2013 the team of **Pierre Tallet** discovered at **Wadi el-Jarf**, on the Red Sea coast, the **oldest inscribed papyri in Egypt**, the records of a crew of about 40 men led by **Merer**, who carried limestone from Tura to Giza in the year after **Khufu**’s 13th cattle count (c. 26th–27th year of the reign, c. 2560 BC). They show boats, canals and a harbour beside the pyramid, and mention **Ankhhaf**, the king’s half-brother, as responsible for the port. It is the written testimony closest to the building of the Great Pyramid.',
  { img: 'emo-papiro-merer', leg: 'Administrative papyrus from Abusir, Fifth Dynasty, displayed at the Cleveland Museum of Art; replaces the photograph of Merer’s diary.' },
  { h: '6. How blocks were raised: the ramp debate' },
  'No one knows for certain how the upper courses of the Great Pyramid were built. The main hypotheses are: **straight ramps** (of brick and rubble), **zigzag ramps** or ramps around the pyramid, an **internal ramp** (Jean-Pierre Houdin’s hypothesis) and the use of levers. Probably more than one was combined. In 2018 a steep ramp with post holes and side stairways, from the time of Khufu (c. 2589 BC), was found at **Hatnub**, in an alabaster quarry — a rare example of its kind.',
  { img: 'emo-rampa-construcao', leg: 'Pyramid construction with a ramp, sledges and limestone blocks: artistic hypothesis of a debated method. AI-generated illustration.' },
  { h: '7. Obelisks: how they were cut and raised' },
  'An obelisk is a single block of granite. In the Aswan quarry the workmen pounded the stone with **dolerite pounders** to open a trench around it. The **Unfinished Obelisk** (c. 42 m, nearly 1,100 tonnes, probably attributed to Hatshepsut) was abandoned because it **cracked**: it shows the method, but also the risk. To raise one, ramps and **sand pits** were used, but the exact method is debated. The Romans and the moderns took obelisks to Rome, Constantinople, Paris, London (1878) and New York (1881).',
  { img: 'emo-obelisco-inacabado', leg: 'Unfinished Obelisk in the Aswan quarry.' },
  { img: 'emo-obelisco-erguer', leg: 'Artistic hypothesis of raising an obelisk with a sand ramp, ropes and levers in the New Kingdom. AI-generated illustration.' },
  { h: '8. The pyramid workers: they were not slaves' },
  'The Greek historian **Herodotus**, who visited Egypt some two thousand years later, wrote that 100,000 men worked in three-month shifts. That figure has no documentary basis. What archaeology shows is an **organised workforce**: a permanent team of **thousands of specialists** (masons, sculptors, carpenters, bakers), reinforced by **seasonal workers**, above all during the flood, when there was no farming. It is estimated (Mark Lehner) that Khufu’s project occupied 20,000 to 25,000 people, but this is an estimate.',
  { img: 'emo-heit-ghurab', leg: 'Gateway of the Wall of the Crow at Heit el-Ghurab, Giza: engraving published by Howard Vyse, 1837.' },
  { h: '9. Heit el-Ghurab, the “builders’ city”' },
  'South of Giza, the team of **Mark Lehner** and **Zahi Hawass** has excavated since the 1990s the “**Lost City**” (Heit el-Ghurab, “the Wall of the Crow”): sleeping galleries, **bakeries**, breweries, workshops and stores of **cattle, fish and bread**. Nearby, in the **workers’ cemeteries**, the workmen were buried with honour (bread, beer, objects), in tombs shaped like mini-pyramids or mastabas. The crews had names, such as “**Friends of Khufu**” and “**Drunkards of Menkaure**”, known from graffiti. The size of the population is debated.',
  { img: 'emo-aldeia-operarios', leg: 'Artistic reconstruction of a workers’ village near Giza, c. 2500 BC, with galleries, bakeries and beer production. AI-generated illustration.' },
  { h: '10. Deir el-Medina, the village of the artisans of the Valley of the Kings' },
  '**Deir el-Medina**, in Thebes, was the village of the diggers, painters and scribes of the royal tombs: its ancient name was **Set Maat**, “the Place of Truth”. Founded around the time of Thutmose I, it had about 70 brick houses in a closed valley, beside its cemetery of painted tombs. The workmen were divided into two **“gangs”**, right and left, each with its foreman. The artisans were literate: they left thousands of **ostraca** (shards with text and drawings) with letters, accounts, complaints and stories, a unique source for everyday life. The village was excavated by **Bernard Bruyère** (1922 – 1951).',
  { img: 'emo-deir-el-medina', leg: 'Workers’ village of Deir el-Medina, Thebes, general view.' },
  { h: '11. Wages, rations and the first recorded strike' },
  'The workmen received state **rations**, mostly of grain (for bread and beer), plus fish, vegetables, oil and firewood, and could earn extra from private jobs. The ostraca record absences and their reasons (illness, brewing beer, funerals). In **year 29 of Ramesses III** (c. 1156 BC), with the grain late, the workmen of Deir el-Medina **stopped work** and marched to the mortuary temples: it is regarded as the first recorded strike in history.',
  { h: '12. Painters and sculptors: working inside the tomb' },
  'Once the chamber was dug, scribes and draughtsmen drew red **grids** on the wall and sketched the figures in ink; a master corrected them in black; only then did the sculptors carve and the painters colour. Light came from **lamps**. Egyptian painting follows a **canon**: in the New Kingdom a standing human figure is 18 squares from the sole to the hairline (in the Late Period, 21). The colours were mineral: ochre, Egyptian blue (an artificial pigment), malachite, charcoal.',
  { img: 'emo-pintores-tumba', leg: 'Painters and draughtsmen decorating a New Kingdom royal tomb, with red grid, pigments and oil lamps. AI-generated illustration.' },
  { h: '13. Planning: measures, plans and maps' },
  'The unit of measure was the **royal cubit** (c. 52.3 cm), divided into 7 palms of 4 fingers. The base of the Great Pyramid was c. 440 cubits, and its height c. 280. The builders used **cords**, **squares** and plumb lines, and left **plans** on ostraca, on papyri and on the walls themselves: the **Turin Papyrus** (c. 1150 BC) has a **map of a mining region** and is regarded as the oldest topographical map known.',
  { img: 'emo-esquema-piramide', leg: 'Schematic section of the Great Pyramid: entrance, descending passage, Grand Gallery, King’s and Queen’s Chambers, relieving chambers and subterranean chamber. Educational diagram.' },
  { h: '14. Orientation and astronomy' },
  'The pyramids of the Old Kingdom are aligned with the **cardinal points** with great accuracy: in the Great Pyramid the error is under a tenth of a degree. The method used (observing circumpolar stars, the Sun or something else) is **debated**. Temples also had symbolic orientations: at **Karnak** an alignment with the winter solstice has been proposed (the interpretation is debated), and at **Abu Simbel**, on two dates a year (today 22 February and 22 October), the Sun reaches the sanctuary.',
  { h: '15. Mastabas' },
  'The **mastaba** was the tomb of high officials and relatives of the king: a low building of brick or stone, with an **offering chapel** at the surface (with a “false door” through which the dead person received offerings) and, below it, a shaft leading to the burial chamber. The walls of the chapels at **Saqqara** have scenes of farming, hunting, crafts and banquets, so that the dead person would go on having everything needed in eternity.',
  { h: '16. Pyramids' },
  'The pyramid is a stone “stairway” or “sunray” for the king to climb to heaven. Beliefs linked it to the sun god and to resurrection. Its complex included a **mortuary temple** next to the pyramid, a covered **causeway** and a **valley temple** near the river, where the funeral procession arrived by boat. There were also **queens’ pyramids** and small **satellite pyramids**. The interior was a set of corridors blocked with great stone plugs, which did not prevent robbery.',
  { h: '17. Cult temples' },
  'An Egyptian temple of the New Kingdom and later follows a plan: **avenue of sphinxes**, **pylon** (monumental gateway with two towers), open **court**, **hypostyle hall** (columned, ever darker) and, at the far end, the **sanctuary** with the god’s image, in near-total darkness. The temple is a **model of the cosmos**: the floor is the earth, the columns are papyrus and lotus plants, the ceiling is the starry sky. Only priests entered the inner parts; ordinary people stayed in the outer courts. Every day the god was “served”: washed, dressed and offered food.',
  { img: 'emo-esquema-templo', leg: 'Schematic plan and perspective of a New Kingdom temple: sphinx avenue, pylon, courtyard, hypostyle hall and sanctuary. Educational diagram.' },
  { h: '18. “Temples of millions of years”' },
  'In the New Kingdom, the king’s mortuary temple on the west bank of Thebes was called a “**temple of millions of years**”. It served the cult of the dead king, but also the living king, and had a ritual link with the great temple of Amun on the opposite bank: at the **Valley** festival, Amun’s image visited them. Some were huge and very rich (**Ramesseum**, **Medinet Habu**), with workshops, storehouses and gardens, and worked as economic centres.',
  { h: '19. Rock-cut tombs and the Valley of the Kings' },
  'The pharaohs of the New Kingdom abandoned the pyramids, **visible and robbable**, and chose to dig tombs in the rock of a dry valley behind Thebes, overlooked by a pyramid-shaped mountain, **al-Qurn**. Corridors descend towards the burial chamber, with walls decorated with the **Book of Gates**, the **Amduat** and other texts that follow the Sun on its night journey. The tombs of the nobles (the “Theban Tombs”, TT) have paintings of everyday scenes, more colourful and more personal.',
  { h: '20. Statues and colossi' },
  'The Egyptians made statues to **serve as a body** for the spirit (the ka) and to represent the king and the gods in the temples. Colossi show the king’s power: the **Colossi of Memnon**, c. 18 m, in quartzite; the four seated statues of **Abu Simbel**, c. 20 m, carved in the rock; the colossus of **Ramesses II** at Memphis. Statues of very hard stone (diorite, granite) were polished with sand and stone until they shone.',
  { h: '21. Fortresses and towns' },
  'Few civil buildings survived, being of brick, but some are known: the Middle Kingdom **Nubian fortresses** (Buhen, Semna), with walls and ditches, the town of **Kahun**, that of **Amarna** and the workers’ villages. Houses were of sun-dried mud brick, with a roof of palm trunks and a stair to the terrace; the streets were narrow.',
  { h: '22. Building fast: the talatat of Amarna' },
  'To build the temples of **Aten** at Karnak and at Amarna, **Akhenaten** had small sandstone blocks used, the **talatat**, of c. 52 × 26 cm, which one man could carry, allowing very fast building. After Akhenaten, **Horemheb** and his successors dismantled the temples of Aten and reused the blocks as rubble in the pylons of Karnak. For decades they have been recovered and catalogued, and put back together on paper like a “jigsaw” of tens of thousands of pieces.',
  { h: '23. Robbery and protecting tombs' },
  'Tombs were robbed from antiquity. The **Abbott Papyrus** and other texts from the reign of **Ramesses IX** describe inquiries into tomb robbers in Thebes. To protect what remained, the priests of the 21st Dynasty **moved the royal mummies** to hiding places: that of **Deir el-Bahari**, revealed to the authorities in 1881 (the Abd el-Rassul family already knew of it), and that of **KV35** (the tomb of Amenhotep II), found in 1898 by Victor Loret. The tomb of **Tutankhamun** escaped because it was covered by rubble from another tomb.',
  { h: '24. Colour and image: what the temples looked like' },
  'Today we see the monuments in pale stone, but they **were painted**: reliefs, columns and ceilings had bright colours (blue, red, yellow, green). It can still be seen in protected parts: the ceiling of the hypostyle hall at Dendera, the hall at Esna (cleaned and restored in recent years) and the tombs. Pyramids faced in polished limestone shone in the sun; the capstone (**pyramidion**) may have been covered with electrum (an alloy of gold and silver), but no covering has survived.',
  { h: '25. How long it took' },
  'The evidence points to relatively short building times for the size: the Great Pyramid in about **two decades** (Khufu’s reign lasted c. 23 years), Abu Simbel in c. 20 years. Great temples such as **Karnak**, by contrast, were works of centuries, to which each king added. The pace depended on the flood, festivals and wars, and many monuments were left unfinished at the king’s death.',
  { h: '26. The second life of the monuments' },
  'The monuments were never “still”. Kings reused stone and statues of their predecessors (Ramesses II and the kings of Tanis did so a great deal), and erased or altered names. After the end of paganism, temples were turned into churches, monasteries and houses; the village of **Djeme** occupied the court of Medinet Habu; the temple of **Hatshepsut** had a Coptic monastery (the Arabic name Deir el-Bahari means “northern monastery”). Already in the Middle Ages, the white limestone of the pyramids was used to build mosques and forts in Cairo.',
  { h: '27. The boat of Khufu' },
  'Beside the Great Pyramid, pits with **dismantled boats**, of Lebanese cedar, were found in 1954. The first was reassembled: it is **43.6 m** long and was displayed in a museum beside the pyramid; it was transferred to the **Grand Egyptian Museum** in 2021. Its function (a boat for carrying the body, a “solar boat” for the king’s journey in the sky, or others) is debated.',
  { h: '28. What has no basis' },
  'Popular theories say the pyramids were built by extraterrestrials, by Atlantis or by an earlier civilisation, that the Sphinx is 10,000 years old, or that “a curse” killed those who opened the tomb of Tutankhamun. **None has support** in archaeological, geological or historical evidence. The dates of the pyramids are given by inscriptions, by radiocarbon dating of charcoal and wood remains, and by the builders’ names. The “curse” began to be invented in the press of 1923, when **Lord Carnarvon** died, and studies found no difference in lifespan between those who were present at the tomb and others.',
  { h: '29. Pyramids, not only in Egypt' },
  'The pyramids of Egypt number more than a hundred (lists vary from c. 118 to over 130). When the Egyptians stopped building them, the kings of **Kush** took them up again (Nuri, Meroe), and the pyramid motif was copied much later, in monuments in Europe and the Americas. But the pyramids of Mesoamerica (the Maya and the Aztecs, for example) are independent of those of Egypt: they are stepped platforms with a temple on top, not tombs.',
  { h: '30. Architects and artists: craft and prestige' },
  'The names of **builders and artists** appear only in some cases. Architects were high-ranking officials, and some were **deified** after death: **Imhotep** and **Amenhotep, son of Hapu**. Ordinary artisans, even if literate and well paid, almost never left their names on the works, and so most monuments are in practice anonymous.',
  { h: '31. Gardens, sacred lakes and water' },
  'Temples had **sacred lakes** (priests purified themselves in them), gardens, vineyards and workshops. At **Karnak** the Sacred Lake is c. 120 × 77 m. Nile water was also decisive for the works: nilometers (such as that at **Elephantine**) measured the flood and **canals** carried the stone.',
  { h: '32. The monuments as books' },
  'The walls of temples bear **texts and images** of every kind: festival calendars, offering lists, hymns, ritual formulas, accounts of campaigns (the battle of **Kadesh** at Abu Simbel and the Ramesseum) and myths (the contest of Horus and Seth at Edfu). Kings’ names are written inside **cartouches** (the elongated oval, with a cord, as protection). It was with the help of an obelisk from Philae (now at Kingston Lacy, England) that **Champollion** confirmed his reading of the cartouches of Ptolemy and Cleopatra.',
  { h: '33. Conserving for the future' },
  'Stone suffers from **salt** rising from the ground, from **damp** (the Aswan dam raised the water table), from pollution and from millions of visitors. Egyptologists work on **drainage**, cleaning and consolidation, and on limiting visitor numbers in the most fragile tombs: that of **Nefertari** admits only small groups. Digitisation and 3D photogrammetry make it possible to study and keep copies, and there are replicas, such as that of Tutankhamun’s tomb, beside Carter’s house.',
  { h: '34. Legend and fact: the “Library” and the “labyrinths”' },
  'Some monuments mentioned by classical authors have never been found, such as the **Labyrinth** of the Faiyum, described by Herodotus and Strabo, or the **Library of Alexandria**, whose exact location is unknown. Herodotus describes the pyramids, but is not always reliable: he gives Khufu a hundred thousand workers and tells of a “reign of cruelty” that the inscriptions do not confirm. Greek authors should be used as late witnesses, not as direct sources.',
  { h: '35. Building again: Egyptian architecture copied' },
  'Even in the time of the Ptolemies and the Romans, temples were designed with the same plan as the old ones, with new elements such as the **mammisi** (“birth houses” of the child-god) and waterside kiosks, like that of **Trajan** at Philae. In modern Egypt and abroad the style has been copied, from the glass pyramid of the **Louvre** (1989) to the “**Egyptian Revival**” of the 19th century (obelisks, cemeteries, bridges), and in Las Vegas, the Luxor hotel.'
];

const personalidades = [
  'This list brings together those who **designed and directed** the monuments and those who **studied and rediscovered** them. For the ancient builders, what the sources say is distinguished from what tradition later attributed to them.',
  { h: 'Imhotep (c. 2650 BC)' },
  'Vizier and “chancellor of the king of Lower Egypt” of **Djoser**. His name is on the base of a statue of the king discovered at Saqqara in 1926. Tradition makes him the architect of the step pyramid, but no document of the time says so explicitly. He was **deified** more than two thousand years later and identified by the Greeks with **Asclepius**, god of medicine. The location of his tomb is unknown.',
  { h: 'Hemiunu (c. 2570 BC)' },
  'Nephew and vizier of **Khufu**, with the title “**overseer of all the king’s works**”. He is usually named as the **architect of the Great Pyramid**, because his office tied him to the building works, but no text of the time says that he designed it. His mastaba lies at Giza, and a statue of him, discovered in 1912, is in Hildesheim, Germany. His name is the one most associated with the Great Pyramid.',
  { img: 'emo-hemiunu-estatua', leg: 'Painted limestone statue of Hemiunu, Roemer- und Pelizaeus-Museum, Hildesheim.' },
  { h: 'Ineni (c. 1520 – 1480 BC)' },
  'Architect of **Amenhotep I** and **Thutmose I**, and still active at the start of the reign of **Hatshepsut**. At Karnak he built pylons IV and V and a columned hall, and, according to his own account, dug the tomb of Thutmose I **in secret**. His autobiography, in his tomb at Thebes (TT81), is one of the richest on an architect’s career.',
  { h: 'Senenmut (c. 1470 – 1458 BC)' },
  'High official of **Hatshepsut**: “steward of Amun” and tutor of the princess Neferure. He is generally named as the **architect of the temple of Deir el-Bahari**, but the inscriptions mostly give him the post of supervisor of works. He had two tombs; the second, beneath the temple, has an **astronomical ceiling**. His images were later damaged, and his end is unknown. Some imagine an intimate relationship with the queen, but there is **no proof**.',
  { h: 'Amenhotep, son of Hapu (c. 1420 – 1350 BC)' },
  'A scribe of modest origin (born at Athribis, in the Delta) who rose to “overseer of all the king’s works” of **Amenhotep III**: he organised the transport of the quartzite of the **Colossi of Memnon**. He received the rare honour of a mortuary temple of his own, and was later **deified**, as a healer, alongside Imhotep. A statue shows him already old, and an inscription of his claims he reached the age of 80.',
  { h: 'Kha (c. 1400 BC)' },
  'Chief of works (“architect”) from the time of Amenhotep II to Amenhotep III at **Deir el-Medina**. His **tomb (TT8)**, found almost intact in 1906 by **Ernesto Schiaparelli**, held his body, that of his wife **Merit**, and all their furniture, food, clothing and tools, and is in the Egyptian Museum in Turin. It is the best picture of the comfort of a family of elite artisans.',
  { h: 'Jean-François Champollion (1790 – 1832)' },
  'French philologist, he deciphered the hieroglyphs in **1822** on the basis of the Rosetta Stone and the cartouches of Ptolemy and Cleopatra, on the Philae obelisk. He understood that the signs were **phonetic and symbolic** at the same time. He made one expedition to Egypt (1828 – 1829), the only one, and copied monuments from Karnak to Abu Simbel. He died at 41.',
  { img: 'emo-champollion', leg: 'Portrait of Champollion by Léon Cogniet (1831), Louvre.' },
  { h: 'Giovanni Battista Belzoni (1778 – 1823)' },
  'An Italian from Padua, a former circus performer, he worked in Egypt for the British consul **Henry Salt**. He brought from Thebes to the British Museum the colossal bust of Ramesses II (1816), cleared the entrance of **Abu Simbel** (1817), discovered the tomb of **Seti I** (KV17) and entered the pyramid of Khafre (1818). His methods (battering rams, mass removal) would be unacceptable today. He died in 1823 in the Kingdom of Benin (now Nigeria), on an exploring journey.',
  { img: 'emo-belzoni', leg: 'Portrait of Giovanni Battista Belzoni, nineteenth century.' },
  { h: 'Karl Richard Lepsius (1810 – 1884)' },
  'German Egyptologist who led the great **Prussian expedition** (1842 – 1845), from the Delta to Sudan. He copied, drew and measured hundreds of monuments and published the twelve volumes of the Denkmäler aus Aegypten und Aethiopien. He excavated at Giza and Saqqara and numbered the known pyramids (the “Lepsius list”, still used). He took many pieces to Berlin.',
  { h: 'Auguste Mariette (1821 – 1881)' },
  'A Frenchman, he discovered the **Serapeum of Saqqara** in 1851. In 1858 he founded the **Egyptian Antiquities Service** (the future Egyptian archaeological authority) and the Bulaq museum, which later gave rise to the Egyptian Museum in Cairo. He excavated dozens of sites and tried to ban the export of antiquities, but his own digs were quick and poorly documented. He was also tied to the opera Aida (1871).',
  { h: 'Sir William Matthew Flinders Petrie (1853 – 1942)' },
  'Regarded as the “**father of Egyptian archaeology**” for his rigour: he measured, recorded and published everything, and invented **sequence dating** of pottery. He excavated at Giza (measuring the Great Pyramid), Hawara, Kahun, Amarna, Naqada and dozens of other places. He was the first professor of Egyptology in the United Kingdom (University College London). He died in Jerusalem, in 1942.',
  { img: 'emo-petrie', leg: 'Portrait of Sir Flinders Petrie, 1903.' },
  { h: 'Howard Carter (1874 – 1939)' },
  'An Englishman, draughtsman and archaeologist, financed by **Lord Carnarvon**, he found on **4 November 1922** the entrance to the tomb of **Tutankhamun**, and spent ten years cataloguing more than 5,000 objects. It was exemplary documentation work for its time, but there were also disputes over the removal of pieces and relations with the Egyptian authorities. The “curse of Tutankhamun” is a press invention.',
  { img: 'emo-carter-tut', leg: 'Howard Carter examining Tutankhamun’s coffin; photograph by Harry Burton.' },
  { h: 'Mark Lehner (b. 1950)' },
  'American archaeologist, he has directed since the 1980s the **Giza Plateau Mapping Project** (AERA). He is chiefly responsible for the excavation of the **Lost City** (Heit el-Ghurab), which showed where the builders of the pyramids lived, ate and slept. He was one of those who proposed the figure of 20,000 to 25,000 workers, and he carries out practical building experiments.',
  { h: 'Zahi Hawass (b. 1947)' },
  'Egyptian Egyptologist, for years the head of Egypt’s antiquities authority (secretary-general of the Supreme Council of Antiquities, 2002 – 2011, and briefly minister, 2011). He directed excavations at Giza (he discovered the workers’ cemeteries), at Saqqara and in the Valley of the Golden Mummies, and was a very media-friendly figure. He is also a **controversial** personality, for his control of information and excavations and for his requests for the return of pieces such as the Rosetta Stone and the bust of Nefertiti.'
];

const legado = [
  { h: 'What they left us' },
  'The monuments of Egypt are **the best-known image of antiquity**. The pyramids, the Sphinx, the temples and the colossi show the Egyptian idea of eternity and of the order of the world (maat). They were also the first great school of **stone architecture** and of large-project management, and influenced the Greeks and the Romans (who took obelisks to Rome and built temples of Isis throughout the Empire).',
  { h: 'UNESCO World Heritage' },
  { lista: [
    '**Memphis and its Necropolis — the Pyramid Fields from Giza to Dahshur** (1979).',
    '**Ancient Thebes with its Necropolis** (Karnak, Luxor, Valley of the Kings and Queens, Deir el-Bahari…) (1979).',
    '**Nubian Monuments from Abu Simbel to Philae** (1979).',
    'In all, Egypt has seven properties, which also include Islamic Cairo, Saint Catherine’s Monastery, Abu Mena and Wadi Al-Hitan.'
  ] },
  { h: 'The saving of Abu Simbel and Nubia' },
  'With the building of the **Aswan High Dam** (1960 – 1970), Lake Nasser threatened to submerge the monuments of Nubia. In 1960, **UNESCO** launched an international campaign, to which dozens of countries responded. The Great Temple and the temple of Nefertari at **Abu Simbel** were cut into about a thousand blocks and rebuilt 65 m higher and 208 m further inland (**1964 – 1968**), at a cost of c. 40 million dollars. **Philae** was moved to the island of Agilkia (1977 – 1980). Four temples were given to countries that helped: that of **Debod** is in Madrid, that of **Dendur** in New York, that of **Taffeh** in Leiden and that of **Ellesiya** in Turin.',
  { img: 'emo-abu-simbel-resgate', leg: 'Dismantling of an Osiriac pillar in the entrance hall of Abu Simbel’s Great Temple during the UNESCO rescue.' },
  { h: 'The museums' },
  'The **Egyptian Museum in Tahrir Square**, Cairo (1902), holds the largest collection of pharaonic antiquities. In **April 2021**, 22 royal mummies (18 kings and 4 queens) were moved in procession to the **National Museum of Egyptian Civilisation**, at Fustat. The **Grand Egyptian Museum** (GEM), near Giza, was officially inaugurated on **1 November 2025**, with some 100,000 pieces, among them those of Tutankhamun (more than 5,000 objects, shown together for the first time), an 11 m colossus of Ramesses II in the atrium and the solar boat of Khufu.',
  { img: 'emo-gem-grande-museu', leg: 'Facade of the Grand Egyptian Museum, Giza.' },
  { h: 'Continuing rediscovery' },
  'Much is still being discovered. The **ScanPyramids** team detected, with cosmic rays (muons), a large **cavity** above the Grand Gallery (announced in 2017) and a **corridor** on the north face of the pyramid (2023); their function and what they contain are unknown. At Saqqara, tombs and animal catacombs keep turning up, and in the Faiyum and the Delta there is much left to excavate. Photogrammetry, ground-penetrating radar and satellite analysis reveal buried structures.',
  { h: 'Conservation and threats' },
  'The greatest enemy is time: the rising **water table** and **salt**, the pollution of Cairo, the climate, urban pressure (Cairo is now close to Giza), looting and modern building. There is also the risk of **mass tourism**. The most fragile tombs, such as that of **Nefertari**, have limited visits; the paintings in the Valley of the Kings are being monitored.',
  { h: 'Tourism and economy' },
  'Tourism is one of Egypt’s main sources of foreign currency: 14.7 million visitors arrived in 2010 (the peak of that period) and about 15.7 million in 2024, drawn above all by Giza, Luxor and Abu Simbel. The rise in visits brought jobs and funds for conservation, but also challenges (political instability, the terrorist attack of **1997** at Deir el-Bahari, the 2020 pandemic).',
  { h: 'Controversies: restorations, repatriation and “new” monuments' },
  'Restoration projects are not uncontroversial. In 2022 the announcement of **re-cladding the pyramid of Menkaure** in granite was criticised by many archaeologists, for altering the monument’s appearance. The Avenue of Sphinxes at Luxor required the demolition of houses. Older are the disputes over **repatriation**: the Rosetta Stone (British Museum), the bust of Nefertiti (Berlin) and the Dendera zodiac (Louvre), which Egypt claims or asks to borrow.',
  { h: 'Egyptomania' },
  'Since the Romans, and above all since Napoleon, there has been a Western taste for Egypt: obelisks in Paris, London and New York, the **glass pyramid of the Louvre**, funerary and Masonic architecture, cinema (The Mummy), music (Aida), fashion and jewellery. The discovery of Tutankhamun (1922) set off a new wave, and exhibitions of his collection are among the most visited in the world.',
  { h: 'Where to visit' },
  { lista: [
    '**Giza, Saqqara and Dahshur**, in half a day or a day, plus the **Grand Egyptian Museum** (book a ticket).',
    '**Luxor**: Karnak, Luxor temple (lit at night), Valley of the Kings (some tombs need an extra ticket), Deir el-Bahari, Medinet Habu, Deir el-Medina.',
    '**Edfu, Kom Ombo, Esna and Dendera** (by boat or by car, between Luxor and Aswan).',
    '**Aswan**: Philae, the Unfinished Obelisk, Elephantine.',
    '**Abu Simbel**, c. 280 km from Aswan.',
    '**Outside Egypt**: the Louvre, the British Museum, the Egyptian Museums of Berlin and Turin, the Metropolitan Museum of New York (Temple of Dendur), the Egyptian Museum of Turin (tomb of Kha) and the Temple of Debod (Madrid).'
  ] },
  { h: 'Main sources' },
  'Besides the publications of each excavation, the reference works are The Oxford History of Ancient Egypt (ed. Ian Shaw, 2000), The Complete Pyramids (Mark Lehner, 1997), The Complete Valley of the Kings and The Complete Temples of Ancient Egypt (Richard Wilkinson) and the work of Pierre Tallet and Dieter Arnold. The UNESCO website and the Griffith Institute archive (Oxford) bring together information and documents.'
];

const quiz = [
  { p: 'What was the first great cut-stone building in Egypt, c. 2670 BC?', op: ['The Great Pyramid of Giza', 'The temple of Luxor', 'Abu Simbel', 'Djoser’s step pyramid at Saqqara'], certa: 3, exp: 'Djoser and his architect Imhotep raised at Saqqara the first great work of cut stone.' },
  { p: 'What was the original height of Khufu’s Great Pyramid?', op: ['About 80 m', 'About 200 m', 'About 146.6 m', 'About 300 m'], certa: 2, exp: 'Today it is c. 138 m, through loss of the top and the casing.' },
  { p: 'Who built the pyramids, according to the archaeological evidence?', op: ['Foreign slaves', 'Egyptian workers paid and fed by the state', 'Extraterrestrials', 'Persian soldiers'], certa: 1, exp: 'The villages, bakeries and tombs of the workers beside Giza show an organised and honoured workforce.' },
  { p: 'What do the Wadi el-Jarf papyri (diary of Merer) reveal?', op: ['The map of Tutankhamun’s tomb', 'The translation of the hieroglyphs', 'The interior of the Sphinx', 'How limestone was carried from Tura to Giza'], certa: 3, exp: 'Discovered in 2013, they are the oldest inscribed papyri and mention the transport of stone for Khufu’s pyramid.' },
  { p: 'Which stone, from Aswan, was mainly used for obelisks and colossi?', op: ['Granite', 'White marble', 'Black basalt', 'Tura limestone'], certa: 0, exp: 'Aswan granite was the stone of obelisks; Tura limestone was used for the fine casing.' },
  { p: 'Why was the Unfinished Obelisk at Aswan left in the quarry?', op: ['It was too small', 'The king died soon afterwards', 'Cracks appeared in the granite', 'It was stolen'], certa: 2, exp: 'It cracked during carving. It would have been about 42 m and close to 1,100 tonnes.' },
  { p: 'What was the village of the artisans who dug the tombs of the Valley of the Kings called?', op: ['Amarna', 'Abydos', 'Deir el-Medina (Set Maat)', 'Tanis'], certa: 2, exp: 'Set Maat, “the Place of Truth”, is today Deir el-Medina, on the west bank of Thebes.' },
  { p: 'What happened in year 29 of Ramesses III, at Deir el-Medina?', op: ['A strike over delayed grain rations', 'A flood', 'The discovery of a tomb', 'A fire'], certa: 0, exp: 'It is regarded as the first recorded strike in history.' },
  { p: 'Who deciphered the hieroglyphs, in 1822?', op: ['Howard Carter', 'Auguste Mariette', 'Flinders Petrie', 'Jean-François Champollion'], certa: 3, exp: 'Champollion used the Rosetta Stone and the cartouches of kings such as Ptolemy and Cleopatra.' },
  { p: 'Who discovered the tomb of Tutankhamun, in November 1922?', op: ['Giovanni Belzoni', 'Zahi Hawass', 'Howard Carter', 'Mark Lehner'], certa: 2, exp: 'Carter, financed by Lord Carnarvon, found the steps on 4 November 1922.' },
  { p: 'What were cult temples for in ancient Egypt?', op: ['Public meetings', 'Storing grain', 'Trying criminals', 'Serving the god every day, through the priests'], certa: 3, exp: 'The temple was the “house of the god”, whose statue was washed, dressed and fed daily.' },
  { p: 'Why was the temple of Abu Simbel moved in 1964–1968?', op: ['An earthquake', 'The rising waters of the Aswan High Dam', 'A war', 'A fire'], certa: 1, exp: 'The temples were cut into blocks and rebuilt higher up, in a UNESCO campaign.' },
  { p: 'What is a mastaba?', op: ['A type of boat', 'A sun temple', 'A flat-roofed tomb with a chapel and burial chamber', 'A type of column'], certa: 2, exp: 'The name comes from the Arabic for “bench”. It was the typical tomb of high officials in the Old Kingdom.' },
  { p: 'Is it true that Napoleon’s soldiers broke off the Sphinx’s nose?', op: ['Yes, with a cannon shot', 'No: the nose was already missing in earlier records', 'Yes, but by accident', 'No: it never had a nose'], certa: 1, exp: 'There are drawings and accounts earlier than Napoleon in which the nose is already missing; one tradition blames a fanatic in the 14th century.' },
  { p: 'When was the Grand Egyptian Museum officially inaugurated?', op: ['1902', '1964', '1 November 2025', '2011'], certa: 2, exp: 'The museum, next to Giza, partly opened earlier and was officially inaugurated in November 2025.' }
];

export default { visao, linha, mapa, sociedade, personalidades, legado, quiz };
